### ISSUE TITLE
grpc_basictests_python Windows - ERROR: Aborting VM command due to timeout of 5400 seconds

### ISSUE THREAD

**Issue by apolcyn** [grpc/grpc#25124] opened 2021-01-08 23:50 UTC
```
No tests will be skipped.
Will run these tests:
  run_tests_python_windows_opt_native: "bash tools/run_tests/helper_scripts/run_tests_in_workspace.sh -t -j 8 -x ../run_tests/python_windows_opt_native/sponge_log.xml --report_suite_name python_windows_opt_native -l python -c opt --iomgr_platform native --max_time 5400 --report_multi_target"
  run_tests_python_windows_opt_gevent: "bash tools/run_tests/helper_scripts/run_tests_in_workspace.sh -t -j 8 -x ../run_tests/python_windows_opt_gevent/sponge_log.xml --report_suite_name python_windows_opt_gevent -l python -c opt --iomgr_platform gevent --max_time 5400 --report_multi_target"
  run_tests_python_windows_opt_asyncio: "bash tools/run_tests/helper_scripts/run_tests_in_workspace.sh -t -j 8 -x ../run_tests/python_windows_opt_asyncio/sponge_log.xml --report_suite_name python_windows_opt_asyncio -l python -c opt --iomgr_platform asyncio --max_time 5400 --report_multi_target"

2021-01-08 13:19:30,255 START: run_tests_python_windows_opt_native
2021-01-08 13:49:36,303 PASSED: run_tests_python_windows_opt_native [time=1806.0sec, retries=0:0]
2021-01-08 13:49:36,303 START: run_tests_python_windows_opt_gevent
2021-01-08 14:18:40,440 PASSED: run_tests_python_windows_opt_gevent [time=1744.1sec, retries=0:0]
2021-01-08 14:18:40,440 START: run_tests_python_windows_opt_asyncio


ERROR: Aborting VM command due to timeout of 5400 seconds

```

https://source.cloud.google.com/results/invocations/a1be7d10-d090-409a-a33d-8203b7d2fb73/targets/grpc%2Fcore%2Fpull_request%2Fwindows%2Fgrpc_basictests_python/log

Seen in https://github.com/grpc/grpc/pull/24979

**Comment by gnossen** [comment] 2021-01-08 23:52
Reassigning to @lidizheng since it looks like it stalled during a Windows asyncio test.

**Comment by lidizheng** [comment] 2021-01-09 02:02
`5400/3=1800`, looks like it is caused by a slow run. We could extend the job timeout.

**Closed** 2022-06-03 20:58 UTC
Labels: kind/bug, lang/Python, priority/P2
