### ISSUE TITLE
grpc_csharp_plugin fails to generate empty service 

### ISSUE THREAD

**Issue by dariogriffo** [grpc/grpc#15660] opened 2018-06-06 13:52 UTC
While trying to generate c# classes of an empty service with the nuget package grpc.tools v 1.12.0 on windows 10, with the following command:

`protoc.exe --plugin=protoc-gen-grpc="protos\grpc_csharp_plugin.exe" -I=protos " -I="$(SolutionDir)protos\protobuf\src" -I="$(SolutionDir)protos\googleapis" --grpc_out="$(ProjectDir)Api" "$(SolutionDir)protos\myprotocol\api\api.proto"
`

and the following definition of the service

```
service Network {

};
```

The following code is generated

 
![issue](https://user-images.githubusercontent.com/3247183/41042261-79d15e48-69a1-11e8-8526-8fa794dc16f5.png)

If I change the service to the following:

```
service Network {
	rpc ToDo (EmptyMessage) returns (EmptyMessage) {
	}
};
```

with he defined EmptyMessage

```
message EmptyMessage {
}
```

the generated code is fine:

![fix](https://user-images.githubusercontent.com/3247183/41042266-7d7103c8-69a1-11e8-898c-0410a45fc418.png)

**Comment by jtattermusch** [comment] 2018-06-06 14:12
Dupe of #15574.    Fixed in  https://github.com/grpc/grpc/pull/15583. Fix will be in the next release (v1.13, coming soon)

**Closed by jtattermusch** 2018-06-06 14:12 UTC
