### ISSUE TITLE
Python Testing

### ISSUE THREAD

**Issue by pgrosu** [grpc/grpc#7591] opened 2016-07-30 22:35 UTC
I will use this as a way to test and troubleshoot the 1.0.x for Python.  I will update my smoke test spreadsheet and rerun the test(s) in case of updates are made.

Thanks,
Paul

**Comment by pgrosu** [comment] 2016-07-30 22:38
##### Test [Installation:Python 3.5::Linux]

```
$ pip3.5 install --pre  grpcio-tools --user
Collecting grpcio-tools
  Using cached grpcio_tools-1.0.0rc1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-yrwx73es/grpcio-tools/setup.py", line 146, in <module>
        protoc_ext_module(),
      File "/tmp/pip-build-yrwx73es/grpcio-tools/setup.py", line 138, in maybe_cythonize
        from Cython import Build
    ImportError: No module named 'Cython'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-yrwx73es/grpcio-tools
You are using pip version 8.0.2, however version 8.1.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
[pgrosu@eofe4 route_guide]$ pip3.5 install --pre  grpcio-tools -$ pip3.5 install --pre  grpcio-tools --user-user
  Using cached grpcio_tools-1.0.0rc1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-yrwx73es/grpcio-tools/setup.py", line 146, in <module>
        protoc_ext_module(),
      File "/tmp/pip-build-yrwx73es/grpcio-tools/setup.py", line 138, in maybe_cythonize
        from Cython import Build
    ImportError: No module named 'Cython'
```

Is 3.5 supported and can `Cython` self-install if required?

**Comment by nathanielmanistaatgoogle** [comment] 2016-08-01 20:38
Closing as a duplicate of [issue 7555](https://github.com/grpc/grpc/issues/7555).

**Comment by thunderboltsid** [comment] 2016-08-01 20:40
To answer the second question, Python3.5 support is currently at a beta level.

**Comment by pgrosu** [comment] 2016-08-01 20:45
Thanks @thunderboltsid,  I'll update my comments for the Python 3.5 test.

@nathanielmanistaatgoogle This is not a duplicate of #7555, and this issue will  be periodically reopened as necessary to inquire about and update all the test results I'm running for gRPC.

**Comment by nathanielmanistaatgoogle** [comment] 2016-08-01 21:09
@pgrosu: ah, okay. I wasn't clear at first that this issue is so far a work in progress.

**Comment by pgrosu** [comment] 2016-08-01 21:42
@nathanielmanistaatgoogle No worries, totally understandable :)  Basically I'm running a set of tests pretending I am a new user and putting it together in terms of steps to validate against, which hopefully will help others.  Here is a very preliminary copy, though I am still at the beginning of the Python tests and troubleshooting the Windows installation:

[gRPC_Python_Smoke_Tests_Summary_Report.pdf](https://www.dropbox.com/s/horck0uvyyphhgz/gRPC_Python_Smoke_Tests_Summary_Report.pdf?dl=1)

Thanks,
~p

**Comment by nathanielmanistaatgoogle** [comment] 2016-08-01 21:59
Hey, that's pretty cool! Thanks!

**Comment by pgrosu** [comment] 2016-08-02 00:00
Gladly, happy to help - thanks :)  Hopefully it will be one path for new users to learn the varied capabilities of gRPC, while practicing using it with little effort.  The documentation is still very rough, so it will take a bit of time to cover all languages systematically.

**Comment by nathanielmanistaatgoogle** [comment] 2016-08-02 16:42
@pgrosu: regarding "the documentation is still very rough", we're actively working on improving the docs for 1.0.0. Are you following changes to [the grpc.github.io repository](https://github.com/grpc/grpc.github.io/)? Have you seen the [new-as-of-two-weeks-ago Python quickstart](https://github.com/grpc/grpc.github.io/blob/GA/docs/quickstart/python.md)?

**Comment by pgrosu** [comment] 2016-08-02 16:59
@nathanielmanistaatgoogle: I was referring that my documentation is very rough :)  I was not following the repository, and didn't know that it is actively being updated, but now I'm watching it.  Thanks for pointing me to it, and it looks great!  I will file some issues over there, since it would be nice to have some documented examples using both the `MetadataCredentialsPlugin` and custom SSL credentials (certs and private keys) via `SslCredentials`.  I know this is a big ask, but I will file one for documenting the [shared C library](https://github.com/grpc/grpc/tree/master/src/core), and how to properly create a new surface API by integrating with it.

**Comment by hsaliak** [comment] 2016-11-16 01:15
Thanks for all the tests! Closing the issue.

**Closed by hsaliak** 2016-11-16 01:15 UTC
Labels: FOR DISCUSSION, python, requires reporter action
