### ISSUE TITLE
FAILED: tests.cloud_to_prod_auth:default:ruby:oauth2_auth_token

### ISSUE THREAD

**Issue by muxi** [grpc/grpc#12605] opened 2017-09-16 18:57 UTC
Failed in https://grpc-testing.appspot.com/job/gRPC_interop_pull_requests/16726/testReport/junit/(root)/tests/cloud_to_prod_auth_default_ruby_oauth2_auth_token/

```
Error Message

Failure
Stacktrace

/var/local/git/grpc/src/ruby/lib/grpc/generic/active_call.rb:31:in `check_status': 14:Endpoint read failed (GRPC::Unavailable)
	from /var/local/git/grpc/src/ruby/lib/grpc/generic/active_call.rb:171:in `attach_status_results_and_complete_call'
	from /var/local/git/grpc/src/ruby/lib/grpc/generic/active_call.rb:363:in `request_response'
	from /var/local/git/grpc/src/ruby/lib/grpc/generic/client_stub.rb:152:in `request_response'
	from /var/local/git/grpc/src/ruby/lib/grpc/generic/service.rb:170:in `block (3 levels) in rpc_stub_class'
	from src/ruby/pb/test/client.rb:668:in `perform_large_unary'
	from src/ruby/pb/test/client.rb:344:in `oauth2_auth_token'
	from src/ruby/pb/test/client.rb:758:in `call'
	from src/ruby/pb/test/client.rb:758:in `main'
	from src/ruby/pb/test/client.rb:763:in `<main>'
I, [2017-09-16T17:11:02.824611 #68]  INFO -- : ... connecting securely to 216.239.32.254:443
```

**Comment by jtattermusch** [comment] 2017-11-06 15:19
Dupe of #10763.

**Closed by jtattermusch** 2017-11-06 15:19 UTC
Labels: infra/BUILDPONY
