### ISSUE TITLE
Flaky Python Travis test

### ISSUE THREAD

**Issue by jcanizales** [grpc/grpc#1656] opened 2015-05-19 17:17 UTC
Test run: https://travis-ci.org/grpc/grpc/jobs/63126554

Error log:
.ssss..s..ERROR:root:Unexpected exception from task run in logging pool!
Traceback (most recent call last):
  File "/home/travis/build/grpc/grpc/python2.7_virtual_environment/local/lib/python2.7/site-packages/grpc/framework/foundation/logging_pool.py", line 43, in _wrapping
    return behavior(*args, **kwargs)
  File "/home/travis/build/grpc/grpc/python2.7_virtual_environment/local/lib/python2.7/site-packages/grpc/_adapter/rear.py", line 217, in _spin
    self._on_write_event(operation_id, event, rpc_state)
  File "/home/travis/build/grpc/grpc/python2.7_virtual_environment/local/lib/python2.7/site-packages/grpc/_adapter/rear.py", line 147, in _on_write_event
    rpc_state.common.write.pending.pop(0), operation_id)
Exception: Defect: attempted to invoke already-invoked call!
TIMEOUT: test/compiler/python_plugin_test.py
FAILED: Some tests failed
The command "./tools/run_tests/run_tests.py -l $TEST -t -j 16 -c $CONFIG -s 4.0" exited with 2.

**Comment by murgatroid99** [comment] 2015-05-19 17:26
This is a duplicate of #1573

**Closed** 2015-05-19 17:26 UTC
Labels: python
