### ISSUE TITLE
Newly added http2_badserver_interop tests fail, but Jenkins task still passes

### ISSUE THREAD

**Issue by makdharma** [grpc/grpc#9474] opened 2017-01-26 18:23 UTC
I added two more tests with PR #9458 . The console output of the gRPC_interop_pull_requests task [here](https://grpc-testing.appspot.com/job/gRPC_interop_pull_requests/10867/console) shows a problem with docker images. But Jenkins task still passes.

So two issues -
1. What is the problem with Docker images?
2. Why is the interop task not failing?

**Comment by nicolasnoble** [comment] 2017-01-26 23:51
The only thing I am wondering is that error here: "cannot enable tty mode on non tty input". Care to disable the -t option ?

**Comment by makdharma** [comment] 2017-01-31 18:19
I removed the "-t" option in #9515 .
Docker seems to be running after this change.
Some interop tests are failing, however. Console output is [here](https://grpc-testing.appspot.com/job/gRPC_interop_pull_requests/11031/console). Failing tests are:
tests.cloud_to_cloud:python:http2_server:rst_during_data
tests.cloud_to_cloud:python:http2_server:rst_after_header
tests.cloud_to_cloud:python:http2_server:rst_after_data

And python -ve interop tests also.

**Comment by adelez** [comment] 2017-01-31 18:42
The new tests broke the HTML report: https://grpc-testing.appspot.com/job/gRPC_interop_pull_requests/11031/HTML_Report/.

It should look like https://grpc-testing.appspot.com/job/gRPC_interop_pull_requests/HTML_Report/. I'll put in a fix.

**Comment by ncteisen** [comment] 2017-01-31 20:11
Those tests are now failing due to this commit: [Revert "Revert "Metadata handling rewrite""](https://github.com/grpc/grpc/commit/7c70b6c144a20782b6be4751da68c6aa7b35648d), which takes away more specific debugging prints right [here](https://github.com/grpc/grpc/commit/7c70b6c144a20782b6be4751da68c6aa7b35648d#diff-434e605a287683b6db888d5786b51cb2L115).

My tests asserted that the status details were `Received RST_STREAM with error code 0`. Now all that is output is `RST_STREAM`.

Will follow up with @ctiller about why the more verbose error message was removed to determine if the test should change, or if the verbose error message should be re-added.

**Comment by ericgribkoff** [comment] 2017-01-31 22:25
The java:http2_server tests are flaky. Can reproduce when using docker locally, but not when running the server and client directly. Still looking into root cause.

**Comment by jtattermusch** [comment] 2017-02-02 02:13
Update: Rootcause was explained in https://github.com/grpc/grpc/pull/9458. @adelez  is working on a better integration of badserver interop tests into run_interop_tests.py.

IMHO the `-t` tty "issue" is a red herring (at least is seems unrelated to the actual cause).

**Comment by ericgribkoff** [comment] 2017-02-03 23:04
The Java test flakes were due to two factors:

- the goaway issue noted here: https://github.com/grpc/grpc/issues/9300
- a race condition between starting the docker http2 python servers and the test clients

These will be fixed by https://github.com/grpc/grpc-java/issues/2694

**Comment by apolcyn** [comment] 2017-03-02 04:45
saw failures between java and http2 server:
```
tests.cloud_to_cloud:java:http2_server:rst_during_data
tests.cloud_to_cloud:java:http2_server:goaway
tests.cloud_to_cloud:java:http2_server:max_streams
tests.cloud_to_cloud:java:http2_server:rst_after_data
tests.cloud_to_cloud:java:http2_server:ping
tests.cloud_to_cloud:java:http2_server:rst_after_header
```

all have log of:
```
Feb 27, 2017 10:11:33 PM io.grpc.testing.integration.Http2Client run
INFO: Running test max_streams
Feb 27, 2017 10:11:33 PM io.netty.util.internal.MacAddressUtil defaultMachineId
WARNING: Failed to find a usable hardware address from the network interfaces; using random bytes: 8c:f8:40:16:5a:ac:c1:b5
```

pr: https://github.com/grpc/grpc/pull/9894

**Comment by ericgribkoff** [comment] 2017-03-17 08:02
The tests failure should all be fixed now. @makdharma the Jenkins log from https://github.com/grpc/grpc/pull/9458 is gone, so I'm not sure what the issue was with failing tests and Jenkins still returning success. If that issue pops up again we can reopen this.

**Closed by ericgribkoff** 2017-03-17 08:02 UTC
