### ISSUE TITLE
Error when installing gRPC pecl PHP extension wit PHP 8

### ISSUE THREAD

**Issue by joesantos418** [grpc/grpc#25803] opened 2021-03-24 19:27 UTC
### What version of gRPC and what language are you using?
gRPC pecl extension version 1.36.0 (the latest at the time of writing)
PHP 8.0 (using the php:8.0-cli-alpine Docker image as base)

### What operating system (Linux, Windows,...) and version?
Alpine Linux 3.13 (using the php:8.0-cli-alpine Docker image as base)

### What runtime / compiler are you using (e.g. python version or version of gcc)
I'm trying to install a pecl extension

### What did you do?
I tried to build from this Dockerfile:
`FROM php:8.0-cli-alpine

RUN set -xe \
    && apk update \
    && apk --no-cache --virtual .build-deps add autoconf build-base linux-headers \
    && apk --no-cache add libzip-dev

RUN pecl install grpc && docker-php-ext-enable grpc`

### What did you expect to see?
The image build with no errors.

### What did you see instead?
An error:

`
 cc -I. -I/tmp/pear/temp/grpc -I/tmp/pear/temp/pear-build-defaultuserifPkCP/grpc-1.36.0/include -I/tmp/pear/temp/pear-build-defaultuserifPkCP/grpc-1.36.0/main -I/tmp/pear/temp/grpc -I/usr/local/include/php -I/usr/local/include/php/main -I/usr/local/include/php/TSRM -I/usr/local/include/php/Zend -I/usr/local/include/php/ext -I/usr/local/include/php/ext/date/lib -I/tmp/pear/temp/grpc/include -I/tmp/pear/temp/grpc/src/core/ext/upb-generated -I/tmp/pear/temp/grpc/src/core/ext/upbdefs-generated -I/tmp/pear/temp/grpc/src/php/ext/grpc -I/tmp/pear/temp/grpc/third_party/abseil-cpp -I/tmp/pear/temp/grpc/third_party/address_sorting/include -I/tmp/pear/temp/grpc/third_party/boringssl-with-bazel/src/include -I/tmp/pear/temp/grpc/third_party/re2 -I/tmp/pear/temp/grpc/third_party/upb -DHAVE_CONFIG_H -Wall -Werror -Wno-parentheses-equality -Wno-unused-value -std=c11 -g -O2 -fvisibility=hidden -DOPENSSL_NO_ASM -D_GNU_SOURCE -DWIN32_LEAN_AND_MEAN -D_HAS_EXCEPTIONS=0 -DNOMINMAX -DGRPC_ARES=0 -DGRPC_POSIX_FORK_ALLOW_PTHREAD_ATF
ORK=1 -c /tmp/pear/temp/grpc/third_party/upb/upb/json_decode.c  -fPIC -DPIC -o third_party/upb/upb/.libs/json_decode.o
/tmp/pear/temp/grpc/third_party/upb/upb/json_decode.c: In function 'jsondec_value':
/tmp/pear/temp/grpc/third_party/upb/upb/json_decode.c:774:10: error: '*((void *)&val+8)' may be used uninitialized in this function [-Werror=maybe-uninitialized]
  774 |   return val;
      |          ^~~
/tmp/pear/temp/grpc/third_party/upb/upb/json_decode.c:738:10: error: '*((void *)&val+8)' may be used uninitialized in this function [-Werror=maybe-uninitialized]
  738 |   return val;
      |          ^~~
/tmp/pear/temp/grpc/third_party/upb/upb/json_decode.c: At top level:
cc1: note: unrecognized command-line option '-Wno-parentheses-equality' may have been intended to silence earlier diagnostics
cc1: all warnings being treated as errors
make: *** [Makefile:2123: third_party/upb/upb/json_decode.lo] Error 1
ERROR: `make' failed
The command '/bin/sh -c pecl install grpc && docker-php-ext-enable grpc' returned a non-zero code: 1
`

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

See [TROUBLESHOOTING.md](https://github.com/grpc/grpc/blob/master/TROUBLESHOOTING.md) for how to diagnose problems better.

### Anything else we should know about your project / environment?
Not that I can think of

**Comment by stanley-cheung** [comment] 2021-04-06 19:16
Duplicate of #25250.

**Closed by stanley-cheung** 2021-04-06 19:16 UTC
Labels: kind/bug, lang/php, priority/P2
