### ISSUE TITLE
C#: Service account to JWT token upgrade fails when no scopes provided

### ISSUE THREAD

**Issue by jskeet** [grpc/grpc#8573] opened 2016-10-31 07:29 UTC
The code at https://github.com/GoogleCloudPlatform/google-cloud-dotnet/blob/master/apis/Google.Monitoring.V3/Google.Monitoring.V3.Snippets/MetricServiceClientSnippets.cs simply uses the Monitoring service via gRPC to list metric descriptors. (You can run it using `dotnet test` in the relevant directory, after building. I realize many readers of this may not have dotnet cli installed though.)

This succeeds if:

- You use credentials from `gcloud auth login`
- You use service account credentials (via the `GOOGLE_APPLICATION_CREDENTIALS` environment variable) and the code is configured to add appropriate scopes.

It fails with an authentication error if you use service account credentials and the code is *not* configured to add any scopes.

My understanding is that scopes should not be required in gRPC when using service account credentials, as some magic is meant to happen with JWT, but it appears not to be working as expected.

The same issue occurs in Java - see https://github.com/grpc/grpc-java/issues/2391

Please let me know if you need more information, or if I can help diagnose this in any way.

**Comment by jtattermusch** [comment] 2016-11-09 22:17
Does the same version of gRPC C# work with JWTs against other APIs (e.g. pubsub)? If so, the problem is most likely configuration of Google.Monitoring API backend (and in that case it might be worth filing an internal bug with the Monitoring API team).

**Comment by jskeet** [comment] 2016-11-09 22:36
I'd have to check, but I don't believe I've ever seen it work without any scopes being defined.

**Comment by jskeet** [comment] 2016-11-10 10:50
Just tried with pubsub - without scopes being used, I get exactly the same problem.

**Comment by jtattermusch** [comment] 2016-11-23 12:01
I just made sure and I can reproduce the issue exactly as described (tried cloud pubsub with C#)

Here's my snippet:
```
// use a service account credential created in cloud console
            Environment.SetEnvironmentVariable("GOOGLE_APPLICATION_CREDENTIALS", "C:\\Users\\jtattermusch\\jtattermuschCloudTest-247e7ff31a02.json");

            var credentials = Google.Apis.Auth.OAuth2.GoogleCredential.GetApplicationDefaultAsync().Result;

            // without specifying the scope, a JWT auth is used and the calls fail with StatusCode.Unauthenticated
            credentials = credentials.CreateScoped(new[] { "https://www.googleapis.com/auth/pubsub" });

            string projectId = "jtattermuschcloudtest";
            string topicId = "myTopic";

            var channel = new Channel("pubsub.googleapis.com:443", credentials.ToChannelCredentials());

            PublisherClient publisher = PublisherClient.Create(channel);
            string topicName = PublisherClient.FormatTopicName(projectId, topicId);
            publisher.CreateTopic(topicName);
```

**Comment by jtattermusch** [comment] 2017-12-12 00:38
@jskeet  were we able to verify that this now works fine in 1.8.x releases (now that the port ":443" suffix now gets removed automatically by C-core https://github.com/grpc/grpc/pull/13235)?

**Comment by jskeet** [comment] 2017-12-12 11:10
Yes, my [testing code](https://github.com/GoogleCloudPlatform/google-cloud-dotnet/tree/master/adhoc/Google.Cloud.ScopeTesting) passes when I use 1.8.0-pre2.

**Comment by jtattermusch** [comment] 2017-12-13 00:58
In that case I will close this issue. 1.8.0 will be released in the next few days.

**Closed by jtattermusch** 2017-12-13 00:58 UTC
Labels: lang/C#
