### ISSUE TITLE
[gRPC Objc] Random grpc error in production environment with "grpc_message":"Stream removed","grpc_status":2

### ISSUE THREAD

**Issue by XinLin** [grpc/grpc#26135] opened 2021-04-30 01:11 UTC
`Error Domain=io.grpc Code=2 "{"created":"@1619724244.297637000","description":"Error received from peer ipv4:35.201.81.34:443","file":"vendor/grpc/gRPC-Core/src/core/lib/surface/call.cc","file_line":1068,"grpc_message":"Stream removed","grpc_status":2}" UserInfo={io.grpc.HeadersKey={
}, io.grpc.TrailersKey={
}, NSDebugDescription={"created":"@1619724244.297637000","description":"Error received from peer ipv4:35.201.81.34:443","file":"vendor/grpc/gRPC-Core/src/core/lib/surface/call.cc","file_line":1068,"grpc_message":"Stream removed","grpc_status":2}, NSLocalizedDescription=Stream removed}`

language: Objective C
version: v1.36.0

I could not reproduce it in my side but keep seeing 10% errors from production environment on iOS.

**Comment by yulin-liang** [comment] 2021-04-30 07:09
XinLin, can you provide more information? There's a similar issue: #15623, based on users' comments, `Stream removed` can happen if  two different processes listen on the same port. But there's no enough information, I'm not pretty sure.

**Comment by yulin-liang** [comment] 2021-04-30 07:11
Does it only happen on v1.36.0?

**Comment by XinLin** [comment] 2021-04-30 15:45
we only have v1.36.0 in production so we do not know whether other versions have the same issue or not.

the tricky part is that we could not reproduce it locally and only have the above logs.

**Comment by yulin-liang** [comment] 2021-04-30 18:11
It would be hard to pinpoint the root cause only based on this log. I'll keep an eye on it and do some search, also let me know if you have more information.

**Comment by XinLin** [comment] 2021-05-05 17:24
we also tried gRPC ObjC with Cronet and gRPC Java, and they worked as expected and no such error found.

**Comment by yulin-liang** [comment] 2021-05-05 17:59
Do you mean it only happens with CFStream transport? Are u able to reproduce it? How do you test it with Cronet and gRPC Java?

**Comment by yulin-liang** [comment] 2021-05-05 18:35
Based on [the code](https://github.com/grpc/grpc/blob/master/src/core/ext/transport/chttp2/transport/chttp2_transport.cc#L2197-L2205), feels like you attempt to close a stream twice. But it is hard to pinpoint the root cause if this is not reproducible.

**Comment by XinLin** [comment] 2021-05-06 00:27
We have grpc java on Android and grpc objc on iOS and running in production environment, we do not see the same error on grpc java; we also enabled cronet for grpc and do not see same error on grpc objc with cronet.

The tricky part is that we could not reproduce it locally.

**Comment by XinLin** [comment] 2021-05-06 00:44
It looks like the error coming from backend: https://github.com/grpc/grpc/blob/7125bbe5a564e30ad63c4f19bed89e7676cb7c29/src/core/lib/surface/call.cc#L1065

**Comment by yulin-liang** [comment] 2021-05-06 06:39
hmm, since you said it only happened with CFStream transport, it sounded more like a client error to me. Do you have any server logs, we may need to make sure if it comes from server side?

**Comment by XinLin** [comment] 2021-05-14 01:08
finally I got the steps to reproduce this issue:
we setup a test endpoint and make a unary call with 50KB payload for 1000 times

`for i in 0 ..< 1000 {`
                    `DispatchQueue.global().asyncAfter(deadline: .now() + TimeInterval(i*2), execute: {`
                        `callUnaryEndpoint(payloadSize: payloadSizeBytes)`
                    `})`
                `}`

then we saw 3 errors from the console logs:

1.
E0513 16:57:36.112099000 6180745216 completion_queue.cc:708]           Operation failed: tag=0x2803598c0, error={"created":"@1620950256.111996000","description":"Truncated message","file":"/Users/xinlinp/ios/vendor/grpc/gRPC-Core/src/core/ext/transport/chttp2/transport/chttp2_transport.cc","file_line":2971}


NSDebugDescription={"created":"@1620950256.112576000","description":"No status received","file":"/Users/xinlinp/ios/vendor/grpc/gRPC-Core/src/core/lib/surface/call.cc","file_line":1091,"grpc_status":2}, NSLocalizedDescription=No status received}

2.
E0513 17:11:18.110140000 6183612416 completion_queue.cc:708]           Operation failed: tag=0x280179350, error={"created":"@1620951078.110064000","description":"Truncated message","file":"/Users/xinlinp/ios/vendor/grpc/gRPC-Core/src/core/ext/transport/chttp2/transport/chttp2_transport.cc","file_line":3051}


Error Domain=io.grpc Code=2 "{"created":"@1620951078.110464000","description":"Error received from peer ipv4:35.227.224.91:443","file":"/Users/xinlinp/ios/vendor/grpc/gRPC-Core/src/core/lib/surface/call.cc","file_line":1068,"grpc_message":"Stream removed","grpc_status":2}"


3.
E0513 17:11:58.117039000 6180745216 completion_queue.cc:708]           Operation failed: tag=0x280261380, error={"created":"@1620951118.116933000","description":"Truncated message","file":"/Users/xinlinp/ios/vendor/grpc/gRPC-Core/src/core/ext/transport/chttp2/transport/chttp2_transport.cc","file_line":2971}

domain: io.grpc, errorCode: 2, description: Error Domain=io.grpc Code=2 "{"created":"@1620951118.117516000","description":"No status received","file":"/Users/xinlinp/ios/vendor/grpc/gRPC-Core/src/core/lib/surface/call.cc","file_line":1091,"grpc_status":2}"


>

**Comment by yulin-liang** [comment] 2021-05-14 08:31
I'm working on another internal issue, I'll take a look at this one ASAP. Thanks Xin for reproducing it, I'll get back to you once I find out the root cause.

**Comment by yulin-liang** [comment] 2021-05-18 18:43
Hi Xin, is this reproducible for you? I still can not reproduce it even with 1MB payload for 1000 times. 
![image](https://user-images.githubusercontent.com/64815511/118706290-0cc03080-b7ce-11eb-89fb-ec799ef6619e.png)

**Comment by XinLin** [comment] 2021-05-18 18:55
Thanks @yulin-liang for looking into this! 
Yes I can reproduce it locally.
We have a mirror endpoint grpc endpoint which just return the payload from the mobile side;
And we also send the request with real payload by adding random int(to avoid compress too much from gzip).

**Comment by yulin-liang** [comment] 2021-05-18 19:08
I tried several times, still can not reproduce it. Are there any other factors may affect it? I just need to make 1000 unary calls with 50kb payload for each, is that right?

**Comment by XinLin** [comment] 2021-05-18 19:10
server side also return the same payload to the mobile side in my testing steps.

**Comment by yulin-liang** [comment] 2021-05-25 16:37
Can you try to set the environment variable `GRPC_CFSTREAM_RUN_LOOP = 1`. We had a similar issue, which had been fixed by using RunLoop based poller.

**Comment by XinLin** [comment] 2021-05-25 21:32
yes it works @yulin-liang 
Is there any way we can set this programmatically? Or environment variable `GRPC_CFSTREAM_RUN_LOOP = 1` is the only way?

**Comment by yulin-liang** [comment] 2021-05-26 06:50
There's no other way to enable RunLoop based poller.

**Closed by yulin-liang** 2021-05-26 06:50 UTC
Labels: lang/ObjC
