### ISSUE TITLE
OSX: ld: library not found for -lprotoc

### ISSUE THREAD

**Issue by timotheecour** [grpc/grpc#8756] opened 2016-11-15 17:53 UTC
```
git clone https://github.com/grpc/grpc
cd grpc
git submodule update --init --recursive
make -j8
```

```
[HOSTCXX] Compiling src/compiler/ruby_plugin.cc
[AR]      Creating /Users/timothee/git_clone/temp/grpc/libs/opt/libgrpc.a
[AR]      Creating /Users/timothee/git_clone/temp/grpc/libs/opt/libgrpc_cronet.a
[LD]      Linking /Users/timothee/git_clone/temp/grpc/libs/opt/libgrpc.dylib
[LD]      Linking /Users/timothee/git_clone/temp/grpc/libs/opt/libgrpc_cronet.dylib
[HOSTLD]  Linking /Users/timothee/git_clone/temp/grpc/bins/opt/grpc_node_plugin
[HOSTLD]  Linking /Users/timothee/git_clone/temp/grpc/bins/opt/grpc_php_plugin
[HOSTLD]  Linking /Users/timothee/git_clone/temp/grpc/bins/opt/grpc_python_plugin
ld: library not found for -lprotoc
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [/Users/timothee/git_clone/temp/grpc/bins/opt/grpc_node_plugin] Error 1
make: *** Waiting for unfinished jobs....
ld: library not found for -lprotoc
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [/Users/timothee/git_clone/temp/grpc/bins/opt/grpc_php_plugin] Error 1
ld: library not found for -lprotoc
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [/Users/timothee/git_clone/temp/grpc/bins/opt/grpc_python_plugin] Error 1
```

**Comment by mehrdada** [comment] 2017-06-09 00:08
I am unable to reproduce the problem on my Mac running Sierra. I suspect the problem has been fixed so I am going to close this issue. Please let us know if you are still experiencing this issue with steps to reproduce the problem. Thanks!

**Closed by mehrdada** 2017-06-09 00:08 UTC
Labels: macOS, protoc plugins, Version/1.0.x
