### ISSUE TITLE
"Failed to load gRPC binary module because it was not installed for the current system"

### ISSUE THREAD

**Issue by psaelango** [grpc/grpc#15431] opened 2018-05-17 18:32 UTC
### What version of gRPC and what language are you using?
 I've have tried different versions of gRPC - ( 1.8.x to 1.11.x)
 
### What operating system (Linux, Windows, …) and version?
 Ubuntu 16.04.4 (LTS)
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
Tried different versions of Nodejs (6.x.x to 8.x.x)
 
### What did you do?
 I'm trying to deploy meteor bundled application in the linux machine. The meteor application works fine in the windows. But with the same versions of configuration (Node,Mongo) if I try to deploy in linux machine it gives the following error message. I tried to comment the grpc code of lines and the application runs fine. 

### What did you see instead?
![capture](https://user-images.githubusercontent.com/20283380/40196608-6ba0f2da-59e7-11e8-8af5-33d3b743d7a7.JPG)

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).
 Below is the nginx error log file
[error.log](https://github.com/grpc/grpc/files/2014308/error.log)

**Comment by psaelango** [comment] 2018-05-17 19:28
Yes I've tried "npm rebuild"

**Comment by Vijendra07Kulhade** [comment] 2018-11-29 07:21
I am getting the similar error. Is there any workaround for the above problem?
`Error: Failed to load gRPC binary module because it was not installed for the current system
Expected directory: node-v64-linux-x64-glibc
Found: [node-v59-linux-x64-glibc]
This problem can often be fixed by running "npm rebuild" on the current system
Original error: Cannot find module '/app/node_modules/grpc/src/node/extension_binary/node-v64-linux-x64-glibc/grpc_node.node'
    at Object.<anonymous> (/app/node_modules/grpc/src/grpc_extension.js:53:17)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/app/node_modules/grpc/src/client_interceptors.js:145:12)
    at Module._compile (internal/modules/cjs/loader.js:689:30)`

**Comment by nicolasnoble** [comment] 2018-11-29 08:00
This issue was long stale, closing it. Please open a new issue on https://github.com/grpc/grpc-node instead with your full information and reproduction case.

**Closed by nicolasnoble** 2018-11-29 08:00 UTC
Labels: kind/bug, lang/node, priority/P2
