### ISSUE TITLE
Some tests consistently failing for C core with gcc4.4 

### ISSUE THREAD

**Issue by jtattermusch** [grpc/grpc#6861] opened 2016-06-10 00:58 UTC
`python tools/run_tests/run_tests.py --use_docker -l c -c dbg --arch x64 --compiler gcc4.4`

https://grpc-testing.appspot.com/job/gRPC_portability_master/2889/language=c,scenario=linux_x64_gcc4.4/

Failing tests:
tests.bins/dbg/gpr_log_test polling=legacy
tests.bins/dbg/gpr_log_test polling=poll

**Comment by vjpai** [comment] 2016-06-13 21:39
I have the root cause of this now, but I can't explain it.
This code is dying in gpr_getenv.  That function has the following code in place to try all possible getenv function names. Unfortunately, none of them are passing. As a result, getenv_func is NULL when we get out of this loop. This is certainly because gcc-4.4 comes equipped with a quite old version of glibc.

  const char *names[] = {"secure_getenv", "__secure_getenv", "getenv"};
  for (size_t i = 0; getenv_func == NULL && i < GPR_ARRAY_SIZE(names); i++) {
    getenv_func = (getenv_type)dlsym(RTLD_DEFAULT, names[i]);
    if (getenv_func != NULL && strstr(names[i], "secure") == NULL) {
      gpr_log(GPR_DEBUG,
              "Warning: insecure environment read function '%s' used",
              names[i]);
    }
  }

**Comment by vjpai** [comment] 2016-06-13 22:16
Actually, simpler explanation likely.

**Comment by vjpai** [comment] 2016-06-18 01:42
Fixed by #6863

**Closed by vjpai** 2016-06-18 01:42 UTC
Labels: core
