### ISSUE TITLE
Stuck when calling inexistent method on local server

### ISSUE THREAD

**Issue by jcanizales** [grpc/grpc#1907] opened 2015-06-04 06:14 UTC
When running the route_guide C++ server of the grpc-common repo locally, making a call to an inexistent method doesn't result in an error (e.g. "Unimplemented"). Instead the server seems to accept the call and stay silent.

Is that expected for that particular server implementation?

**Comment by yang-g** [comment] 2015-06-04 07:00
I think it is a bug. I used to have it somewhere but I guess I did not convert it to an issue.

**Comment by ctiller** [comment] 2015-06-04 13:35
There is an issue: https://github.com/grpc/grpc/issues/483

**Comment by jcanizales** [comment] 2015-06-04 19:33
For context, I use "calling a nonexistent method" as a test that I'm actually talking correctly to a server. I've commented the test out for the moment.

**Comment by jayantkolhe** [comment] 2015-08-03 23:10
dupe of #483

**Closed by jayantkolhe** 2015-08-03 23:10 UTC
Labels: c++
