### ISSUE TITLE
bins/ubsan/h2_ssl_proxy_test stream_compression_ping_pong_streaming GRPC_POLL_STRATEGY=epollex

### ISSUE THREAD

**Issue by kpayson64** [grpc/grpc#13762] opened 2017-12-13 22:26 UTC
```
D1213 20:56:51.489097299    3850 ev_posix.cc:128]            Using polling engine: epollex
D1213 20:56:51.489228349    3850 dns_resolver.cc:293]        Using native dns resolver
I1213 20:56:51.489331036    3850 stream_compression_ping_pong_streaming.cc:41] Running test: test_pingpong_streaming/chttp2/simple_ssl_fullstack
D1213 20:56:51.492630376    3850 proxy.cc:89]                PROXY ADDR:localhost:10426 BACKEND:localhost:17343
I1213 20:56:51.743481443    3850 stream_compression_ping_pong_streaming.cc:41] Running test: test_pingpong_streaming/chttp2/simple_ssl_fullstack
D1213 20:56:51.748499786    3850 proxy.cc:89]                PROXY ADDR:localhost:23283 BACKEND:localhost:20837
I1213 20:56:51.875736795    3850 stream_compression_ping_pong_streaming.cc:41] Running test: test_pingpong_streaming/chttp2/simple_ssl_fullstack
D1213 20:56:51.878515252    3850 proxy.cc:89]                PROXY ADDR:localhost:7221 BACKEND:localhost:2082
I1213 20:56:52.001568521    3850 stream_compression_ping_pong_streaming.cc:41] Running test: test_pingpong_streaming/chttp2/simple_ssl_fullstack
D1213 20:56:52.004655249    3850 proxy.cc:89]                PROXY ADDR:localhost:16434 BACKEND:localhost:7312

2017-12-13 21:12:00,269 TIMEOUT: bins/ubsan/h2_ssl_proxy_test stream_compression_ping_pong_streaming GRPC_POLL_STRATEGY=epollex [pid=3850, time=908.8sec]
```
https://sponge.corp.google.com/target?id=91f4de69-5ee9-41e4-8d86-31049f1afb17&target=grpc/ubuntu/pull_request/grpc_c_ubsan&searchFor=&show=ALL&sortBy=STATUS

**Comment by dgquintas** [comment] 2017-12-20 20:40
Duplicate of #13846

**Closed by dgquintas** 2017-12-20 20:40 UTC
Labels: infra/BUILDPONY
