### ISSUE TITLE
AsyncDuplexStreamingCall hang/deadlock on net48 on linux

### ISSUE THREAD

**Issue by shaan1337** [grpc/grpc#25488] opened 2021-02-18 07:19 UTC
### What version of gRPC and what language are you using?
Grpc.Core 2.35.0 (latest)
Grpc.Tools 2.35.0 (latest)
Google.Protobuf 3.14.0 (latest)
C# (net48)

### What operating system (Linux, Windows,...) and version?
Linux (Ubuntu 18.04)

### What runtime / compiler are you using (e.g. python version or version of gcc)
mono 6.12.0.107

### What did you do?
Please see https://github.com/shaan1337/async-duplex-streaming-call-hang for a minimal repro of the issue or 
[async-duplex-streaming-call-hang.zip](https://github.com/grpc/grpc/files/6000877/async-duplex-streaming-call-hang.zip)

### What did you expect to see?
The application should exit.
 - The application does not hang when the target framework is changed to `netcoreapp3.1` or `net5.0`
- The application does not hang when AsyncDuplexStreamingCall is changed to another type of call (e.g AsyncClientStreamingCall)
- Attaching a debugger shows that the C# gRPC thread pool is getting stuck during the shut down phase (during application exit)

### What did you see instead?
The application hangs.

### Anything else we should know about your project / environment?
I'm available if you need any additional information. I'm attempting to find the cause of the deadlock and will share updates if I make any progress.

**Comment by rburns1293** [comment] 2022-03-14 18:26
Thanks for the reproduction. I ran it and got the same results with the application hanging using target framework net48 but passing for net5.0 or netcoreapp3.1.

**Comment by jtattermusch** [comment] 2022-03-15 12:05
I can also reproduce using your example, but at the same time there seem to be problem with your example itself:

- After setting `GRPC_VERBOSITY=debug` env variable I got this warning (which indicates that you're probably not waiting for the client call to finish as you should)
```
W0315 11:30:59.219262 Grpc.Core.Channel Channel shutdown was called but there are still 1 active calls for that channel.
```
- the hang seems to be caused by the TestInterceptor logic. TBH I don't understand what the interceptor's logic is supposed to do (it first invokes the ReadWrite handler, but then returns a new instance of `AsyncDuplexStreamingCall` for no apparent reason.

- you never invoke `await _channel.ShutdownAsync()` and `await _server.ShutdownAsync()` before exiting from the app as you should  -  even though that doesn't seem to be actually causing the behavior you're seeing, it's a contributing factor.


See https://github.com/grpc/grpc/blob/d589f4e6ca88168c306ebc7a883a615dc46d3f2b/src/csharp/Grpc.Core.Tests/Interceptors/ClientInterceptorTest.cs#L169 for an example of a meaningful DuplexStreamingCall interceptor.

**Comment by jtattermusch** [comment] 2022-03-15 12:07
Since the logic in the TestInterceptor serves no clear purpose an is probably broken and removing the interceptor makes the problem go away, I'm going to close this issue since it doesn't seem to be a gRPC bug.

**Closed by jtattermusch** 2022-03-15 12:07 UTC
Labels: kind/bug, lang/C#, priority/P2
