### ISSUE TITLE
grpcio fails to install on Python via pip on Apple Silicon M1 chip (MacOS arm64)

### ISSUE THREAD

**Issue by ricardoprins** [grpc/grpc#25993] opened 2021-04-16 20:39 UTC
gRPC 1.37, Mac OS Big Sur 11.2.3, Apple M1 Silicon chip, Python 3.9

I'm trying to install it via pip (pip install grpcio)

Error message:

ERROR: Command errored out with exit status 1: <local folder>/env/bin/python3.9 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/1t/r94t70gn0xj16whplgkkdf_c0000gn/T/pip-install-7yjvucyg/grpcio_ecb1088260c445fdabf541a1eb00e477/setup.py'"'"'; __file__='"'"'/private/var/folders/1t/r94t70gn0xj16whplgkkdf_c0000gn/T/pip-install-7yjvucyg/grpcio_ecb1088260c445fdabf541a1eb00e477/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/1t/r94t70gn0xj16whplgkkdf_c0000gn/T/pip-record-4ctb2rbl/install-record.txt --single-version-externally-managed --compile --install-headers <local folder>/env/include/site/python3.9/grpcio Check the logs for full command output.

I've tried the solutions suggested at #24390 - no success. Please let me know if I can provide more information to clarify.

**Comment by ricardoprins** [comment] 2021-04-16 20:58
This is the full error log file, attached to this message.
[errorlog.txt](https://github.com/grpc/grpc/files/6327855/errorlog.txt)

**Comment by gnossen** [comment] 2021-04-19 17:19
The actual compilation error:

```
2021-04-16T14:57:06,881     clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -D_WIN32_WINNT=1536 -DOPENSSL_NO_ASM=1 -DGPR_BACKWARDS_COMPATIBILITY_MODE=1 -DHAVE_CONFIG_H=1 -DGRPC_ENABLE_FORK_SUPPORT=1 -DPyMODINIT_FUNC=extern "C" __attribute__((visibility ("default"))) PyObject* -DGRPC_POSIX_FORK_ALLOW_PTHREAD_ATFORK=1 -Isrc/python/grpcio -Iinclude -I. -Ithird_party/abseil-cpp -Ithird_party/address_sorting/include -Ithird_party/cares -Ithird_party/cares/cares -Ithird_party/cares/config_darwin -Ithird_party/re2 -Ithird_party/boringssl-with-bazel/src/include -Ithird_party/upb -Isrc/core/ext/upb-generated -Isrc/core/ext/upbdefs-generated -Ithird_party/xxhash -Ithird_party/zlib -I/opt/homebrew/include -I/opt/homebrew/opt/openssl@1.1/include -I/opt/homebrew/opt/sqlite/include -I/Users/ricardoprins/Documents/repositories/inspireme/env/include -I/opt/homebrew/opt/python@3.9/Frameworks/Python.framework/Versions/3.9/include/python3.9 -c third_party/zlib/gzlib.c -o python_build/temp.macosx-11-arm64-3.9/third_party/zlib/gzlib.o -stdlib=libc++ -fvisibility=hidden -fno-wrapv -fno-exceptions -pthread
2021-04-16T14:57:06,924     third_party/zlib/gzlib.c:252:9: error: implicit declaration of function 'lseek' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
2021-04-16T14:57:06,924             LSEEK(state->fd, 0, SEEK_END);  /* so gzoffset() is correct */
2021-04-16T14:57:06,924             ^
2021-04-16T14:57:06,924     third_party/zlib/gzlib.c:14:17: note: expanded from macro 'LSEEK'
2021-04-16T14:57:06,924     #  define LSEEK lseek
2021-04-16T14:57:06,924                     ^
2021-04-16T14:57:06,924     third_party/zlib/gzlib.c:252:9: note: did you mean 'fseek'?
2021-04-16T14:57:06,924     third_party/zlib/gzlib.c:14:17: note: expanded from macro 'LSEEK'
2021-04-16T14:57:06,924     #  define LSEEK lseek
2021-04-16T14:57:06,924                     ^
2021-04-16T14:57:06,924     /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/stdio.h:162:6: note: 'fseek' declared here
2021-04-16T14:57:06,925     int      fseek(FILE *, long, int);
2021-04-16T14:57:06,925              ^
2021-04-16T14:57:06,925     third_party/zlib/gzlib.c:258:24: error: implicit declaration of function 'lseek' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
2021-04-16T14:57:06,925             state->start = LSEEK(state->fd, 0, SEEK_CUR);
2021-04-16T14:57:06,925                            ^
2021-04-16T14:57:06,925     third_party/zlib/gzlib.c:14:17: note: expanded from macro 'LSEEK'
2021-04-16T14:57:06,925     #  define LSEEK lseek
2021-04-16T14:57:06,925                     ^
2021-04-16T14:57:06,925     third_party/zlib/gzlib.c:359:9: error: implicit declaration of function 'lseek' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
2021-04-16T14:57:06,925         if (LSEEK(state->fd, state->start, SEEK_SET) == -1)
2021-04-16T14:57:06,925             ^
2021-04-16T14:57:06,925     third_party/zlib/gzlib.c:14:17: note: expanded from macro 'LSEEK'
2021-04-16T14:57:06,925     #  define LSEEK lseek
2021-04-16T14:57:06,925                     ^
2021-04-16T14:57:06,926     third_party/zlib/gzlib.c:400:15: error: implicit declaration of function 'lseek' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
2021-04-16T14:57:06,926             ret = LSEEK(state->fd, offset - state->x.have, SEEK_CUR);
2021-04-16T14:57:06,926                   ^
2021-04-16T14:57:06,926     third_party/zlib/gzlib.c:14:17: note: expanded from macro 'LSEEK'
2021-04-16T14:57:06,926     #  define LSEEK lseek
2021-04-16T14:57:06,926                     ^
2021-04-16T14:57:06,926     third_party/zlib/gzlib.c:496:14: error: implicit declaration of function 'lseek' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
2021-04-16T14:57:06,926         offset = LSEEK(state->fd, 0, SEEK_CUR);
2021-04-16T14:57:06,926                  ^
2021-04-16T14:57:06,926     third_party/zlib/gzlib.c:14:17: note: expanded from macro 'LSEEK'
2021-04-16T14:57:06,926     #  define LSEEK lseek
2021-04-16T14:57:06,926                     ^
2021-04-16T14:57:06,926     5 errors generated.
```

**Comment by tdonovic** [comment] 2021-05-04 02:27
I wonder if https://github.com/grpc/grpc/issues/24677 is caused by this? Certainly get that impression (since I had this same issue) on m1 macs

**Comment by ricardoprins** [comment] 2021-05-04 02:45
> I wonder if #24677 is caused by this? Certainly get that impression (since I had this same issue) on m1 macs

Could be. To be quite honest, I don't have the time currently to investigate this issue - I simply am using a diff computer now to do what I need. But from what I see, it seems to me that there are many issues involved with the new m1 macs...

**Comment by matejnevlud** [comment] 2021-09-21 17:24
+ 1

**Comment by pcmoritz** [comment] 2021-10-20 23:17
I hope a wheel can be provided for gRPC on M1 to make it easy and quick to install :)

This issue should probably be higher priority given how quickly the mac ecosystem is switching to M1.

**Comment by MustafaHaddara** [comment] 2022-01-01 19:39
> I wonder if #24677 is caused by this? Certainly get that impression (since I had this same issue) on m1 macs

FYI [the workaround](https://github.com/grpc/grpc/issues/24677#issuecomment-728721822) described in that thread worked for me:

```
GRPC_PYTHON_BUILD_SYSTEM_ZLIB=true pip install grpcio
```

**Comment by lclpedro** [comment] 2022-03-29 17:28
if doesn't resolved above, try install python 3.9.8 or superior..

**Comment by pietrodn** [comment] 2022-03-29 19:53
Please try the solution proposed in [this comment](https://github.com/grpc/grpc/issues/25082#issuecomment-1082312000). I verified it today and it works.

**Comment by pietrodn** [comment] 2022-10-22 07:36
I decided to set up a periodic GitHub Actions workflow to provide **daily builds of Apple Silicon wheels for Mac**. It will automatically cut a new release the day a new `grpcio` version is released on PyPI.

In the releases page of this repo you can find and download the wheels for Python 3.8, 3.9, 3.10, 3.11.
(Use at your own risk, these are not tested.)
https://github.com/pietrodn/grpcio-mac-arm-build

**Comment by gnossen** [comment] 2023-02-06 18:56
1.52.0 has been released with proper universal2 artifacts which support both x86 macs and M1/2 macs, so going ahead and closing this issue.

**Closed by gnossen** 2023-02-06 18:56 UTC
Labels: kind/bug, lang/Python, priority/P2
