### ISSUE TITLE
c_linux_opt_native.bins/opt/h2_census_nosec_test graceful_server_shutdown GRPC_POLL_STRATEGY=epollsig

### ISSUE THREAD

**Issue by murgatroid99** [grpc/grpc#11166] opened 2017-05-16 22:09 UTC
https://grpc-testing.appspot.com/job/gRPC_master_linux/2392/testReport/junit/(root)/c_linux_opt_native/bins_opt_h2_census_nosec_test_graceful_server_shutdown_GRPC_POLL_STRATEGY_epollsig/

```
D0514 12:56:01.386509987    5966 test_config.c:403]          test slowdown factor: sanitizer=1, fixture=1, poller=1, total=1
I0514 12:56:01.386614361    5966 ev_epollsig_linux.c:90]     epoll engine will be using signal: 40
D0514 12:56:01.386625564    5966 ev_posix.c:121]             Using polling engine: epollsig
D0514 12:56:01.386637127    5966 dns_resolver.c:316]         Using native dns resolver
I0514 12:56:01.386677664    5966 graceful_server_shutdown.c:53] Running test: test_early_server_shutdown_finishes_inflight_calls/chttp2/fullstack+census
E0514 12:56:11.395574711    5966 cq_verifier.c:228]          no event received, but expected:
0x65 GRPC_OP_COMPLETE success=1 test/core/end2end/tests/graceful_server_shutdown.c:160




*******************************
Caught signal SIGABRT
bins/opt/h2_census_nosec_test[0x49af6e]
/lib/x86_64-linux-gnu/libpthread.so.0(+0xf890)[0x7f3a41953890]
/lib/x86_64-linux-gnu/libc.so.6(gsignal+0x37)[0x7f3a415ce067]
/lib/x86_64-linux-gnu/libc.so.6(abort+0x148)[0x7f3a415cf448]
bins/opt/h2_census_nosec_test[0x426b58]
bins/opt/h2_census_nosec_test[0x40f34c]
bins/opt/h2_census_nosec_test[0x404521]
bins/opt/h2_census_nosec_test[0x403108]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf5)[0x7f3a415bab45]
bins/opt/h2_census_nosec_test[0x403143]
Command terminated by signal 6
```

**Comment by yang-g** [comment] 2017-05-17 17:59
Duplicate of #10653

**Closed by yang-g** 2017-05-17 17:59 UTC
Labels: BUILDPONY, core
