### ISSUE TITLE
csharp travis failure

### ISSUE THREAD

**Issue by yang-g** [grpc/grpc#2186] opened 2015-06-23 23:15 UTC
I do not know whether is reported anywhere yet.

partial log:

Tests run: 38, Errors: 0, Failures: 1, Inconclusive: 0, Time: 7.8991229 seconds
  Not run: 0, Invalid: 0, Ignored: 0, Skipped: 0

Errors and Failures:
1) Test Failure : Grpc.Core.Tests.ClientServerTest.UnknownMethodHandler
     Expected: Unimplemented
  But was:  Unknown

at Grpc.Core.Tests.ClientServerTest.UnknownMethodHandler () [0x00000] in <filename unknown>:0

[0;31mFAILED[0m: Grpc.Core.Tests [ret=1, pid=8931]
[0G[2K[0;31mFAILED[0m: Some tests failed
travis_time:end:00f93757:start=1435100323144465590,finish=1435100357612111193,duration=34467645603
[0K
[31;1mThe command "./tools/run_tests/run_tests.py -l $TEST -t -j $JOBS -c $CONFIG -s 4.0" exited with 2.[0m

Done. Your build exited with 1.

**Comment by yang-g** [comment] 2015-06-23 23:16
Full log: https://s3.amazonaws.com/archive.travis-ci.org/jobs/68068454/log.txt

**Comment by jtattermusch** [comment] 2015-06-23 23:59
Duplicate of https://github.com/grpc/grpc/issues/2146

**Closed by jtattermusch** 2015-06-23 23:59 UTC
Labels: C#, Travis
