### ISSUE TITLE
Python Debian Package

### ISSUE THREAD

**Issue by LiranLast** [grpc/grpc#11255] opened 2017-05-20 16:23 UTC
At this time, the only packages for python deployment are based on pip.

I'm building a Python-based application using gRPC and need to deploy it using a Debian package. The lack of such a gRPC package for python makes this very difficult.

Do you have any plans to add python-grpcio to the Debian archives?

**Comment by nathanielmanistaatgoogle** [comment] 2017-05-20 20:49
Closing as a duplicate of [issue 1165](https://github.com/grpc/grpc/issues/1165) - I _think_ this is unlikely to happen but maybe tell us more about what's inadequate about `pip install grpcio`?

**Closed by nathanielmanistaatgoogle** 2017-05-20 20:49 UTC
Labels: packaging & distribution, python
