### ISSUE TITLE
FAILED: cloud_to_prod_auth:gateway_v4:python:oauth2_auth_token

### ISSUE THREAD

**Issue by apolcyn** [grpc/grpc#12207] opened 2017-08-16 21:57 UTC
Unavailable status

```
2017-08-16 14:03:49,993 WAITING: ETA 3.1 sec; 9 queued, 12 jobs running, 265 complete, 3 failed
2017-08-16 14:03:49,993 running run_interop
Traceback (most recent call last):
  File "src/python/grpcio_tests/setup.py", line 102, in <module>
    test_runner=TEST_RUNNER,)
  File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/var/local/git/grpc/src/python/grpcio_tests/commands.py", line 184, in run
    self.run_client()
  File "/var/local/git/grpc/src/python/grpcio_tests/commands.py", line 200, in run_client
    client.test_interoperability()
  File "/var/local/git/grpc/src/python/grpcio_tests/tests/interop/client.py", line 126, in test_interoperability
    test_case.test_interoperability(stub, args)
  File "/var/local/git/grpc/src/python/grpcio_tests/tests/interop/methods.py", line 476, in test_interoperability
    _oauth2_auth_token(stub, args)
  File "/var/local/git/grpc/src/python/grpcio_tests/tests/interop/methods.py", line 393, in _oauth2_auth_token
    response = _large_unary_common_behavior(stub, True, True, None)
  File "/var/local/git/grpc/src/python/grpcio_tests/tests/interop/methods.py", line 138, in _large_unary_common_behavior
    response = response_future.result()
  File "/var/local/git/grpc/py27/local/lib/python2.7/site-packages/grpc/_channel.py", line 279, in result
    raise self
grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with (StatusCode.UNAVAILABLE, Endpoint read failed)>

2017-08-16 14:03:49,993 FAILED: cloud_to_prod_auth:gateway_v4:python:oauth2_auth_token [ret=1, pid=28465]
```

sponge log is in https://kokoro.corp.google.com/job/grpc/job/ubuntu/job/pull_request/job/grpc_interop_toprod/1139/

this issue, as well as https://github.com/grpc/grpc/issues/12207 and https://github.com/grpc/grpc/issues/12204 might batch into the same group

**Comment by adelez** [comment] 2017-08-18 22:54
Based on the status code, I think it's a duplicate of #12204

**Closed by adelez** 2017-08-18 22:54 UTC
Labels: lang/Python
