### ISSUE TITLE
Compile error on Unity Android (when using il2cpp scripting backend)

### ISSUE THREAD

**Issue by aki017** [grpc/grpc#16012] opened 2018-07-13 05:38 UTC
### What version of gRPC and what language are you using?
grpc 1.13
csharp
 
### What operating system (Linux, Windows, …) and version?
 mac 10.13.6
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
Unity 2018.2.0f2
 
### What did you do?

Copy nuget DLL and libgrpc_csharp_ext to Unity project then Build for android with il2cpp  backend
 
### What did you expect to see?

Build success
 
### What did you see instead?
 
Build failed

<details>
<summary>error 1</summary>

It's not really same error but message is same
```
$PROJECT_ROOT/Library/il2cpp_android_armeabi-v7a/il2cpp_cache/DF9F83A8EC0BC7E29490BDDC2C565638.o: In function `DllImportsFromStaticLib_grpcsharp_init_m1026693466':
$PROJECT_ROOT/Temp/StagingArea/Il2Cpp/il2cppOutput/Bulk_Assembly-CSharp_2.cpp:16645: undefined reference to `grpcsharp_init'
```
</details>

workaround for this, 
```diff
        internal class DllImportsFromStaticLib
        {
-            private const string ImportName = "__Internal";
+            private const string ImportName = "grpc_csharp_ext";
```

It seems il2cpp transpile DllImportsFromStaticLib but `[DllImport("__Internal")]` is failed

<details>
<summary>error 2</summary>

Runtime Logcat
```
E/Unity(7004): NotSupportedException: To marshal a managed method, please add an attribute named 'MonoPInvokeCallback' to the method definition.
```

</details>

workaround for this, 
NativeLogRedirector.cs
```diff
+        [MonoPInvokeCallback(typeof(GprLogDelegate))]
         private static void HandleWrite(IntPtr fileStringPtr, int line, ulong threadId, IntPtr severityStringPtr, IntPtr msgPtr)
```

**Comment by jtattermusch** [comment] 2018-07-13 13:12
Thanks for reporting, this is good input!

Out of interest: Are you transpiling the precompiled DLL with Grpc.Core assembly  from the net45   or netstandard1.5? (I assume it net45, but I wanted to check).

In a way, I'm surprised that we are getting an error about DllImportFromStatibLib, which should not be used for android at all (android should use the DllImportsFromSharedLib class), but I guess the transpiler is just checking things to eagerly. The problem is we need  DllImportFromStatibLib  to support other platforms, so we can't just remove it.

We can't just add `[MonoPInvokeCallback(typeof(GprLogDelegate))]` as that would break build on Windows and .NETcore. We'll have to cope up with some other way to make the transpiler happy.

**Comment by aki017** [comment] 2018-07-14 15:32
@jtattermusch 
That’s right, Api Compatibility Level is net45
Unity now supports .NET4.x and .NET Standard 2.0
![image](https://user-images.githubusercontent.com/1407394/42725809-34d58ac0-87c5-11e8-90be-b89b24187292.png)

@jsmouret
place `.c` file on unity? 
I have not tried it yet, but can be DLLImport as `__Internal`?
Your example seems better.

Use source instead of dll on Unity is one idea.

and i found one more problem
https://github.com/grpc/grpc/blob/f9f5c67/src/csharp/Grpc.Core/Internal/DefaultSslRootsOverride.cs#L44
unity convert dll to cpp, so not working.

Should I separate Issue?(DllImport, MonoPInvokeCallback, GetManifestResourceStream)

**Comment by jsmouret** [comment] 2018-07-15 02:20
In Unity version 2018.2, c/cpp files can be compiled automatically in the game library for non-editor targets.
( https://docs.unity3d.com/Manual/WindowsPlayerCPlusPlusSourceCodePluginsForIL2CPP.html )

**Comment by jtattermusch** [comment] 2018-07-23 18:03
"Error 2" was fixed by https://github.com/grpc/grpc/pull/16094.  Still not sure about the right resolution for "Error 1".

**Comment by jjlehtinen** [comment] 2018-09-11 12:35
Personally went with 
```
#if UNITY_ANDROID
	        private const string ImportName = "grpc_csharp_ext";
#else
	        private const string ImportName = "__Internal";
#endif
```

for now as a workaround.

**Comment by hefesto84** [comment] 2018-12-04 15:43
@aki017 I don't know if you still need help but I have an application made in unity for Android and iOS with IL2CPP with GRPC working perfectly.

**Closed** 2019-02-15 17:03 UTC
Labels: kind/enhancement, lang/C#, priority/P2
