### ISSUE TITLE
Macos linker error: malformed archive TOC entry for _zlibVersion, offset 295472 is beyond end of file 188416

### ISSUE THREAD

**Issue by apolcyn** [grpc/grpc#19469] opened 2019-06-26 06:39 UTC
Seen in https://source.cloud.google.com/results/invocations/883bbed0-2f48-4ab4-92c4-bdd6ddeb0699/targets/grpc%2Fcore%2Fpull_request%2Fmacos%2Fgrpc_basictests_c_cpp/log, from https://github.com/grpc/grpc/pull/19397 

during C/C++ macos basic tests

Snippet from the log:

```
o /Volumes/BuildData/tmpfs/src/github/grpc/workspace_c_macos_opt_native/objs/opt/third_party/zlib/crc32.o /Volumes/BuildData/tmpfs/src/github/grpc/workspace_c_macos_opt
_native/objs/opt/third_party/zlib/deflate.o /Volumes/BuildData/tmpfs/src/github/grpc/workspace_c_macos_opt_native/objs/opt/third_party/zlib/gzclose.o /Volumes/BuildData
/tmpfs/src/github/grpc/workspace_c_macos_opt_native/objs/opt/third_party/zlib/gzlib.o /Volumes/BuildData/tmpfs/src/github/grpc/workspace_c_macos_opt_native/objs/opt/thi
rd_party/zlib/gzread.o /Volumes/BuildData/tmpfs/src/github/grpc/workspace_c_macos_opt_native/objs/opt/third_party/zlib/gzwrite.o /Volumes/BuildData/tmpfs/src/github/grp
c/workspace_c_macos_opt_native/objs/opt/third_party/zlib/infback.o /Volumes/BuildData/tmpfs/src/github/grpc/workspace_c_macos_opt_native/objs/opt/third_party/zlib/inffa
st.o /Volumes/BuildData/tmpfs/src/github/grpc/workspace_c_macos_opt_native/objs/opt/third_party/zlib/inflate.o /Volumes/BuildData/tmpfs/src/github/grpc/workspace_c_maco
s_opt_native/objs/opt/third_party/zlib/inftrees.o /Volumes/BuildData/tmpfs/src/github/grpc/workspace_c_macos_opt_native/objs/opt/third_party/zlib/trees.o /Volumes/Build
Data/tmpfs/src/github/grpc/workspace_c_macos_opt_native/objs/opt/third_party/zlib/uncompr.o /Volumes/BuildData/tmpfs/src/github/grpc/workspace_c_macos_opt_native/objs/o
pt/third_party/zlib/zutil.o 
ranlib -no_warning_for_no_symbols /Volumes/BuildData/tmpfs/src/github/grpc/workspace_c_macos_opt_native/libs/opt/libaddress_sorting.a
cc -L/Volumes/BuildData/tmpfs/src/github/grpc/workspace_c_macos_opt_native/libs/opt/protobuf -g  -fPIC -Llibs/opt -L/usr/local/lib    /Volumes/BuildData/tmpfs/src/githu
b/grpc/workspace_c_macos_opt_native/objs/opt/tools/codegen/core/gen_legal_metadata_characters.o -lm -lz -lz   -o /Volumes/BuildData/tmpfs/src/github/grpc/workspace_c_ma
cos_opt_native/bins/opt/gen_legal_metadata_characters
[LD]      Linking /Volumes/BuildData/tmpfs/src/github/grpc/workspace_c_macos_opt_native/bins/opt/gen_percent_encoding_tables
mkdir -p `dirname /Volumes/BuildData/tmpfs/src/github/grpc/workspace_c_macos_opt_native/bins/opt/gen_percent_encoding_tables`
ld: warning: directory not found for option '-L/Volumes/BuildData/tmpfs/src/github/grpc/workspace_c_macos_opt_native/libs/opt/protobuf'
ld: malformed archive TOC entry for _zlibVersion, offset 295472 is beyond end of file 188416
 file 'libs/opt/libz.a'
cc -L/Volumes/BuildData/tmpfs/src/github/grpc/workspace_c_macos_opt_native/libs/opt/protobuf -g  -fPIC -Llibs/opt -L/usr/local/lib    /Volumes/BuildData/tmpfs/src/githu
b/grpc/workspace_c_macos_opt_native/objs/opt/tools/codegen/core/gen_percent_encoding_tables.o -lm -lz -lz   -o /Volumes/BuildData/tmpfs/src/github/grpc/workspace_c_maco
s_opt_native/bins/opt/gen_percent_encoding_tables
clang: error: linker command failed with exit code 1 (use -v to see invocation)
ranlib -no_warning_for_no_symbols /Volumes/BuildData/tmpfs/src/github/grpc/workspace_c_macos_opt_native/libs/opt/libz.a
make: *** [/Volumes/BuildData/tmpfs/src/github/grpc/workspace_c_macos_opt_native/bins/opt/gen_legal_metadata_characters] Error 1
make: *** Waiting for unfinished jobs....
ld: warning: directory not found for option '-L/Volumes/BuildData/tmpfs/src/github/grpc/workspace_c_macos_opt_native/libs/opt/protobuf'

2019-06-25 20:35:09,034 FAILED: make [ret=2, pid=6592, time=66.3sec]
2019-06-25 20:35:09,035 FAILED: Some tests failed

2019-06-25 20:35:09,070 FAILED: run_tests_c_macos_opt_native [ret=1, pid=5202, time=81.5sec]
2019-06-25 20:35:09,070 START: run_tests_c++_macos_dbg_native
2019-06-25 21:02:33,551 PASSED: run_tests_c++_macos_dbg_native [time=1644.5sec, retries=0:0]
2019-06-25 21:02:33,551 START: run_tests_c++_macos_opt_native
2019-06-25 21:29:59,076 PASSED: run_tests_c++_macos_opt_native [time=1645.5sec, retries=0:0]
2019-06-25 21:29:59,115 FAILED: Some run_tests.py instance have failed.
```

**Comment by vjpai** [comment] 2019-09-05 19:25
This is definitely infrastructural caused by some diskspace thing.

**Comment by AspirinSJL** [comment] 2019-10-09 22:37
Closing because it seems transient.

**Closed by AspirinSJL** 2019-10-09 22:37 UTC
Labels: infra/Kokoro, lang/c++, platform/macOS, priority/P2
