### ISSUE TITLE
Feature Request: DNS resolver - configurable frequency, SRV and TXT lookups via authority URL

### ISSUE THREAD

**Issue by rantav** [grpc/grpc#18743] opened 2019-04-12 11:38 UTC
This FR was originally opened for https://github.com/grpc/grpc-go/issues/2751 but @dfawley suggested to reopen it here.

### Use case(s) - what problem will this feature solve?
When using the DNS resolver it's impossible to configure the frequency of lookups.   
The frequency is 30 minutes (at least in Go); what we need is 30 seconds or so (configurable).   
We load balance using DNS and during deployment servers go down and up and so we want the grpc client to be able to notice these updates in a timely manner, 30 minutes is way too long.  Other means (such as Envoy, Consul agent etc) are valid options but right now we want to stick to plain old DNS. 

On top of that we want a way to disable the SRV and the TXT queries, mainly for efficiency (if we query every 30 seconds we want the bare minimum, only A lookups, that's all). 

I know this topic had been discussed plenty before, a few points of reference: 

gRPC related issue: https://github.com/grpc/grpc/issues/12295

Go gRPC issues: 

https://github.com/grpc/grpc-go/issues/1663
https://github.com/grpc/grpc-go/issues/2279
https://github.com/grpc/grpc-go/issues/2306
https://github.com/grpc/grpc-go/issues/1998

And I know that in the past there had been objection due to efficiency concerns (running SRV lookup and then for each result an A lookup and then TXT lookup, every 30 seconds could result in considerable load on the DNS server) therefore I bundle my suggestion to configure all three: `minFreq`, `lookupSRV` and `lookupTXT` 

### Proposed Solution
The suggestion is to allow URL parameters to the _authority_ section which would allow additional configuration, here's an example (conforming to [naming](https://github.com/grpc/grpc/blob/master/doc/naming.md))

```
dns://127.0.0.1:8600?lookupSRV=0&lookupTXT=0&refreshRate=30/endpoint.service.consul.:8080
```

Where in this example

`127.0.0.1:8600?lookupSRV=0&lookupTXT=0&refreshRate=30` the entire authority section
`127.0.0.1` is the IP of the DNS server
`8600` is the DNS server port (default is 53)
`lookupSRV=0` disables SRV records lookups
`lookupTXT=0` disables TXT records lookup
`refreshRate=30` configures the refresh frequency to 30 seconds

`endpoint.service.consul.` is the host to lookup at the DNS server. This name returns zero or more A records. 
`8080` is the service port (when disabling SRV lookups we need to specify the port) 

### Alternatives Considered
Right now there's an option to disable the TXT lookup, with `resolver.BuildOption.DisableServiceConfig` (in `grpc-go`) but there's no way to disable SRV lookups or to configure the refresh frequency via the `BuildOption`.  
To be honest, I haven't figured out how as a grpc client I'm able to access and configure the BuildOption, but if it's something that's supposed to be accessible to gRPC clients (and I just missed it) then an alternative solution might be to add those two options to `BuildOption`. If we don't, then there would be two ways to disable TXT lookups and that's less than ideal

### Additional Context

I know others have been told "your requirements are unique, you should build your own resolver", I can do that. But I thought it's worth checking if there's more common interest that I could contribute this back, e.g. work on the mainline DNS resolver.  

I am familiar with the Go gRPC lib and somewhat with the Java gRPC client but not with others. However according to Doug this behavior is common or at least similar to all clients so worth discussing here. 
I'm happy to send a PR at least for the grpc-go lib.

**Comment by sanjaypujare** [comment] 2019-04-14 23:15
I have a couple of concerns with this FR:

- as per [rfc3986]([https://tools.ietf.org/html/rfc3986#section-3.2] ) authority cannot contain question mark (...The  authority component ... is terminated by ... question mark ("?") ) 

- we should not be configuring the DNS resolver via query parameters in a query. The query should be purely a "read-only" operation. For any configuration or "write" operations shouldn't there be a system of access control?

How about using the "scheme" to specify some of these things e.g. "dnsA" for A-record only look up. This way the resolver plugin would know to only do A record lookup.

**Comment by rantav** [comment] 2019-04-15 06:21
Thank you @sanjaypujare, good points, let me comment inline: 

> *  as per rfc3986 authority cannot contain question mark (...The authority component ... is terminated by ... question mark ("?") )

I agree it does not conform to this RFC. 
If you agree this is a viable feature though (being able to configure the DNS resolver), then I'm happy to hear other suggestions (I'll comment on your next suggestion below).   
Another option to consider: providing arguments or configuration options to the `Dialer` in Go or `NameResolver.Factory` in Java (I believe) and so on in other languages. In terms of operator friendliness I feel that the URL scheme I proposed is  superior but if indeed conformance to the RFC is a concern then other options are on the table.  
My inspiration was taken from JDBC connection strings.

Another option might be instead of using a question mark `?`  and ampersand  `&`, use semicolon `;` like sqlserver connection strings define. Not a huge fan of that, but perhaps in terms of conformance it's better. So we would have as an example:

```
dns://127.0.0.1:8600;lookupSRV=0;lookupTXT=0;refreshRate=30/endpoint.service.consul.:8080
```


> * we should not be configuring the DNS resolver via query parameters in a query. The query should be purely a "read-only" operation. For any configuration or "write" operations shouldn't there be a system of access control?

I see your point about query parameters semantics (read-only semantics). On the other hand, it's common to use JDBC connection strings with parameters to configure database access, so to me it looks like similar evil and perhaps in the context of configuring a DNS resolver, the semantic is clear and not so confusing.  I'm happy to hear more thoughts on that. 

I'm not sure about your comment regarding access control, I mean we already provide the DNS authority, that's huge control already, do you feel that configuring the DNS authority requires special access control? (which is not required in order to provide the authority)

> How about using the "scheme" to specify some of these things e.g. "dnsA" for A-record only look up. This way the resolver plugin would know to only do A record lookup.

But then how would you configure a lookup frequency? So yeah, it's possible to define a few schemes with various combinations such as `dns`, `dnsA`, `dnsT` and `dnsAT` but the most important thing (to me) is the configurable lookup frequency which cannot be configured with the scheme as far as I can see. On top of that, if we want to define more parameters in the future it will become difficult to maintain all the various permutations. 

Thank you again for your feedback! 
I'm looking forward to getting more feedback on this FR.

**Comment by sanjaypujare** [comment] 2019-04-15 17:41
> Thank you @sanjaypujare, good points, let me comment inline:
> 
> > * as per rfc3986 authority cannot contain question mark (...The authority component ... is terminated by ... question mark ("?") )
> 
> I agree it does not conform to this RFC.
> If you agree this is a viable feature though (being able to configure the DNS resolver), then I'm happy to hear other suggestions (I'll comment on your next suggestion below).

Agreed, let's discuss the viability and semantics first; then we can deal with the syntax.

One thing I realized, all of your so-called configuration options (that are not read-only) only apply to the local resolver plugin. So the refreshRate=30 tells the plugin to refresh every 30 seconds (by querying the DNS server at that frequency) and does not involved pushing the config to any server. So that makes it much better. You still need to think about cases where the client code uses 2 different values for the refreshRate where the rest of the URI is otherwise the same. I don't know what it takes for the resolver to maintain per-channel/per-caller settings.

On the other hand if you think all of your settings really apply to the whole DNS resolver why not set them via env variables or such system wide settings? That eliminates the need to extend the URI syntax.

> Another option to consider: providing arguments or configuration options to the `Dialer` in Go or `NameResolver.Factory` in Java (I believe) and so on in other languages. In terms of operator friendliness I feel that the URL scheme I proposed is superior but if indeed conformance to the RFC is a concern then other options are on the table.

This is similar to the env var or system wide settings idea above. I like this option of setting these config values in the factory.

> My inspiration was taken from JDBC connection strings.

The values apply per JDBC connection and the JDBC driver keeps per-connection state to be able to implement that. 

> 
> I'm not sure about your comment regarding access control, I mean we already provide the DNS authority, that's huge control already, do you feel that configuring the DNS authority requires special access control? (which is not required in order to provide the authority)

I take that back, since the config values in your description only apply to the local resolver plugin and we can assume the caller should have full control over how that plugin should behave.

> 
> > How about using the "scheme" to specify some of these things e.g. "dnsA" for A-record only look up. This way the resolver plugin would know to only do A record lookup.
> 
> But then how would you configure a lookup frequency? So yeah, it's possible to define a few schemes with various combinations such as `dns`, `dnsA`, `dnsT` and `dnsAT` but the most important thing (to me) is the configurable lookup frequency which cannot be configured with the scheme as far as I can see. On top of that, if we want to define more parameters in the future it will become difficult to maintain all the various permutations.

That's correct, this wouldn't address all of your requirements but I thought something along these lines doesn't need URI syntax extension.

**Comment by rantav** [comment] 2019-04-16 09:53
> Agreed, let's discuss the viability and semantics first; then we can deal with the syntax.

OK, so how can we push this forward?

> You still need to think about cases where the client code uses 2 different values for the refreshRate where the rest of the URI is otherwise the same. I don't know what it takes for the resolver to maintain per-channel/per-caller settings.

The client (grpc client) creates the channel by providing a URL such as demonstrated above (e.g. `dns://127.0.0.1:8600?refreshRate=30/endpoint.service.consul.:8080`. Each client can use a different URL and this URL could contain a different authority and/or different parameters to the authority. So various resolvers (if created), over different grpc client channels, need not be in sync, they can each utilize a separate instance of the resolver, each configured with different params. 

One more point I did not discuss before.  
My suggestion addresses a way to configure a specific DNS authority. What still need to be specified (open for discussion) is how to configure access parameters to the default authority. Implementation wise it seems easy (at least from my knowledge of the Go go) but interface wise (e.g. the spec) requires some thinking. 

Let me explain. 
This is a valid URL: `dns://endpoint.service.consul.:8080` 
This URL tells us to use the default DNS resolver and resolve the address `endpoint.service.consul.`
This is also a valid URL (per my suggestion): `dns://127.0.0.1:8600?refreshRate=30/endpoint.service.consul.:8080`
This URL tells us to use the DNS server at `127.0.0.1` port `8600` in order to resolve `endpoint.service.consul.` every 30 seconds.
However, how do you specify usage of the *default DNS server* but with a refresh rate of 30 seconds? 
Something like this? `dns://?refreshRate=30/endpoint.service.consul.:8080`. The `?refreshRate=30` seems a bit odd. But the use case is legit. 
This needs to be solved. 

> On the other hand if you think all of your settings really apply to the whole DNS resolver why not set them via env variables or such system wide settings?

I don't think that all setting apply to all DNS resolvers. I mean, it's something that could work for me in my own specific use case but generally speaking, I think that settings should be per-connection and not global. I don't like the approach of env vars b/c it's not explicit enough (plus it's global and not per channel). 
 
> The values apply per JDBC connection and the JDBC driver keeps per-connection state to be able to implement that.

That is my intent as well. Values per grpc connection and a state per connection (which, BTW already exists, I don't add more state which did not exist before). See my PR below. 

This draft PR is here to demonstrate how things could work in Golang: https://github.com/rantav/grpc-go/pull/1

**Comment by sanjaypujare** [comment] 2019-04-16 16:47
> > Agreed, let's discuss the viability and semantics first; then we can deal with the syntax.
> 
> OK, so how can we push this forward?

In terms of semantics I think we are almost there. Pls see my comments below.


> The client (grpc client) creates the channel by providing a URL such as demonstrated above (e.g. `dns://127.0.0.1:8600?refreshRate=30/endpoint.service.consul.:8080`. Each client can use a different URL and this URL could contain a different authority and/or different parameters to the authority. So various resolvers (if created), over different grpc client channels, need not be in sync, they can each utilize a separate instance of the resolver, each configured with different params.
> 

I looked at the grpc-java NameResolvers and that implementation appears consistent with what you are saying. Not sure if refreshRate would need additional threading etc. but makes sense.  


> One more point I did not discuss before.
> My suggestion addresses a way to configure a specific DNS authority. What still need to be specified (open for discussion) is how to configure access parameters to the default authority. Implementation wise it seems easy (at least from my knowledge of the Go go) but interface wise (e.g. the spec) requires some thinking.

Correct. The default authority (although not specified) is just one authority to which the parameters apply. 

> 
> Let me explain.
> This is a valid URL: `dns://endpoint.service.consul.:8080`
> This URL tells us to use the default DNS resolver and resolve the address `endpoint.service.consul.`

As per https://github.com/grpc/grpc/blob/master/doc/naming.md your URL should be `dns:endpoint.service.consul.:8080`. The `//` goes with the (non-default) authority.

> This is also a valid URL (per my suggestion): `dns://127.0.0.1:8600?refreshRate=30/endpoint.service.consul.:8080`
> This URL tells us to use the DNS server at `127.0.0.1` port `8600` in order to resolve `endpoint.service.consul.` every 30 seconds.
> However, how do you specify usage of the _default DNS server_ but with a refresh rate of 30 seconds?
> Something like this? `dns://?refreshRate=30/endpoint.service.consul.:8080`. The `?refreshRate=30` seems a bit odd. But the use case is legit.

The `//` should not be there so `dns:?refreshRate=30/endpoint.service.consul.:8080`

> This needs to be solved.

I was thinking why should the "query params" follow the authority (or more correctly precede the host)? Why can't you supply your config params as query params using the traditional URI syntax e.g.

`dns://127.0.0.1:8600/endpoint.service.consul.:8080?lookupSRV=0&lookupTXT=0&refreshRate=30`

The params really apply to the whole query and I don't think we should somehow try to keep them close to the authority.


> I don't think that all setting apply to all DNS resolvers. I mean, it's something that could work for me in my own specific use case but generally speaking, I think that settings should be per-connection and not global. I don't like the approach of env vars b/c it's not explicit enough (plus it's global and not per channel).
> 
> > The values apply per JDBC connection and the JDBC driver keeps per-connection state to be able to implement that.
> 
> That is my intent as well. Values per grpc connection and a state per connection (which, BTW already exists, I don't add more state which did not exist before). See my PR below.

I understand your point but unless someone really needs to supply different parameters per DNS query I think we can consider the short-cut of BuildOption or such for now

**Comment by rantav** [comment] 2019-04-17 05:48
> I was thinking why should the "query params" follow the authority (or more correctly precede the host)? Why can't you supply your config params as query params using the traditional URI syntax e.g.

I like it. Initially I wanted to keep the query parameters close to the authority in order to make it clear that they apply to the authority, but come to think of it, placing them at the end of the URL make sense just the same. Plus it solves two problems: the conformance to the RFC and what to do when there's no authority provided (using the default DNS server).

So a URL with authority would look like (as you suggested, just a shorter version for readability): 
```
dns://127.0.0.1:8600/endpoint.service.consul.:8080?refreshRate=30
```

And a URL without authority (using the default DNS server) would look like: 
```
dns://endpoint.service.consul.:8080?refreshRate=30
```

> ... unless someone really needs to supply different parameters per DNS query I think we can consider the short-cut of BuildOption or such for now

I'm not sure we're on the same page here. AFAIK BuildOptions are also per-connection. So unless I'm mistaken, BuildOption and URL parameters provide the same capability but with different implementations e.g. BuildOption must be configured programmatically while DNS url is provided by the connection string (which is typically controlled by an operator), so to me it looks like the a more appropriate interface.

**Comment by sanjaypujare** [comment] 2019-04-17 17:19
> And a URL without authority (using the default DNS server) would look like:
> 
> ```
> dns://endpoint.service.consul.:8080?refreshRate=30
> ```

As I mentioned before and as per [this spec](https://github.com/grpc/grpc/blob/master/doc/naming.md#name-syntax), shouldn't it be:
```
dns:endpoint.service.consul.:8080?refreshRate=30
```
i.e. without the 2 leading slashes? 

> > ... unless someone really needs to supply different parameters per DNS query I think we can consider the short-cut of BuildOption or such for now
> 
> I'm not sure we're on the same page here. AFAIK BuildOptions are also per-connection. So unless I'm mistaken, BuildOption and URL parameters provide the same capability but with different implementations e.g. BuildOption must be configured programmatically while DNS url is provided by the connection string (which is typically controlled by an operator), so to me it looks like the a more appropriate interface.

Sorry I don't know BuildOptions well and may be that analogy was incorrect. But the point was to set "global" settings for the resolver (env vars for example) if that works for your use-cases. But if you really want to go with your proposal, let's see what others feel about this because I think this would be a non-trivial change.

**Comment by rantav** [comment] 2019-04-17 19:15
Regarding this
```
dns:endpoint.service.consul.:8080?refreshRate=30
```
You are correct per the spec, however from my testing the Go client doesn't work this way. Could be a bug in the Go client? Perhaps a bug in the spec?  
I wonder how other technologies deal with that.  

This does work: 
```
dns:///endpoint.service.consul.:8080?refreshRate=30
```

But removing the `///` results in incorrect selection of the resolver. (I assume a URL parser is used and that parser expects a `scheme://`, but that's just a guess, I couldn't find the code that does that so far)

**Comment by sanjaypujare** [comment] 2019-04-17 19:40
> Regarding this
> 
> ```
> dns:endpoint.service.consul.:8080?refreshRate=30
> ```
> You are correct per the spec, however from my testing the Go client doesn't work this way. Could be a bug in the Go client? Perhaps a bug in the spec?

I think the naming.md spec in grpc needs to be fixed to be compliant with [this](https://tools.ietf.org/html/rfc3986#section-3) which says:

```
URI         = scheme ":" hier-part [ "?" query ] [ "#" fragment ]

      hier-part   = "//" authority path-abempty
                  / path-absolute
                  / path-rootless
                  / path-empty
```

So even though //  and authority go together the initial "/" is mandatory so your example would be

 ```
dns:/endpoint.service.consul.:8080?refreshRate=30
```
And I think 

```
dns:///endpoint.service.consul.:8080?refreshRate=30
```
is illegal since authority cannot be empty after "//".

But this doesn't block your proposal which is really about adding the query part after the "?" and implementing it in the resolver for which I want to see what others say.

**Comment by markdroth** [comment] 2019-04-17 20:56
Sanjay, I think you're misreading the ABNF syntax.  When it says this:

```
hier-part   = "//" authority path-abempty
                  / path-absolute
                  / path-rootless
                  / path-empty
```

Note that on the last three lines, the `/` is not quoted.  This is ABNF syntax to indicate an "or" -- in other words, it's saying that `hier-part` is defined as `"//" authority path-abempty` OR `path-absolute` OR `path-rootless` OR `path-empty`.

I don't see anything in this spec that indicates that the initial "/" is mandatory.  And in fact, it would badly break every existing parser on the internet (including ours) if that were the case.

**Comment by sanjaypujare** [comment] 2019-04-17 22:18
@markdroth you are right. I didn't notice the missing "" around `/` .  Also I didn't realize they use `/` in the ABNF grammar to indicate alternatives (I have seen `|` for that) that might have caused me to misread.

Not sure if the Go client then has a bug based on what @rantav reported? I think he said `dns:endpoint.service.consul.:8080` didn't work as expected.

**Comment by markdroth** [comment] 2019-04-17 22:31
Stepping back for a moment, I think the discussion about how to configure this is premature; we first need to discuss whether or not we are actually going to support this.  And that discussion is actually exactly what is being discussed in #12295, so I'm going to close this as a duplicate of that.

**Closed by markdroth** 2019-04-17 22:31 UTC
