### ISSUE TITLE
Installation on Windows 10

### ISSUE THREAD

**Issue by Malwy** [grpc/grpc#20999] opened 2019-11-11 13:44 UTC
### What did you do?
Tried to install it from pip install command
If possible, provide a recipe for reproducing the error. Try being specific and include code snippets if helpful.

### What did you expect to see?
Installation completed

### What did you see instead?

>     ERROR: Command errored out with exit status 1:
>      command: 'c:\users\administrator\appdata\local\programs\python\python38-32\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Administrator\\AppData\\Local\\Temp\\2\\pip-install-6hv8xzb8\\grpcio\\setup.py'"'"'; __file__='"'"'C:\\Users\\Administrator\\AppData\\Local\\Temp\\2\\pip-install-6hv8xzb8\\grpcio\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\Administrator\AppData\Local\Temp\2\pip-record-nkilt9xu\install-record.txt' --single-version-externally-managed --compile
>          cwd: C:\Users\Administrator\AppData\Local\Temp\2\pip-install-6hv8xzb8\grpcio\
>     Complete output (66 lines):
>     Found cython-generated files...
>     running install
>     running build
>     running build_py
>     running build_project_metadata
>     creating python_build
>     creating python_build\lib.win32-3.8
>     creating python_build\lib.win32-3.8\grpc
>     copying src\python\grpcio\grpc\_auth.py -> python_build\lib.win32-3.8\grpc
>     copying src\python\grpcio\grpc\_channel.py -> python_build\lib.win32-3.8\grpc
>     copying src\python\grpcio\grpc\_common.py -> python_build\lib.win32-3.8\grpc
>     copying src\python\grpcio\grpc\_compression.py -> python_build\lib.win32-3.8\grpc
>     copying src\python\grpcio\grpc\_grpcio_metadata.py -> python_build\lib.win32-3.8\grpc
>     copying src\python\grpcio\grpc\_interceptor.py -> python_build\lib.win32-3.8\grpc
>     copying src\python\grpcio\grpc\_plugin_wrapping.py -> python_build\lib.win32-3.8\grpc
>     copying src\python\grpcio\grpc\_server.py -> python_build\lib.win32-3.8\grpc
>     copying src\python\grpcio\grpc\_utilities.py -> python_build\lib.win32-3.8\grpc
>     copying src\python\grpcio\grpc\__init__.py -> python_build\lib.win32-3.8\grpc
>     creating python_build\lib.win32-3.8\grpc\beta
>     copying src\python\grpcio\grpc\beta\implementations.py -> python_build\lib.win32-3.8\grpc\beta
>     copying src\python\grpcio\grpc\beta\interfaces.py -> python_build\lib.win32-3.8\grpc\beta
>     copying src\python\grpcio\grpc\beta\utilities.py -> python_build\lib.win32-3.8\grpc\beta
>     copying src\python\grpcio\grpc\beta\_client_adaptations.py -> python_build\lib.win32-3.8\grpc\beta
>     copying src\python\grpcio\grpc\beta\_metadata.py -> python_build\lib.win32-3.8\grpc\beta
>     copying src\python\grpcio\grpc\beta\_server_adaptations.py -> python_build\lib.win32-3.8\grpc\beta
>     copying src\python\grpcio\grpc\beta\__init__.py -> python_build\lib.win32-3.8\grpc\beta
>     creating python_build\lib.win32-3.8\grpc\experimental
>     copying src\python\grpcio\grpc\experimental\gevent.py -> python_build\lib.win32-3.8\grpc\experimental
>     copying src\python\grpcio\grpc\experimental\session_cache.py -> python_build\lib.win32-3.8\grpc\experimental
>     copying src\python\grpcio\grpc\experimental\__init__.py -> python_build\lib.win32-3.8\grpc\experimental
>     creating python_build\lib.win32-3.8\grpc\framework
>     copying src\python\grpcio\grpc\framework\__init__.py -> python_build\lib.win32-3.8\grpc\framework
>     creating python_build\lib.win32-3.8\grpc\_cython
>     copying src\python\grpcio\grpc\_cython\__init__.py -> python_build\lib.win32-3.8\grpc\_cython
>     creating python_build\lib.win32-3.8\grpc\experimental\aio
>     copying src\python\grpcio\grpc\experimental\aio\_channel.py -> python_build\lib.win32-3.8\grpc\experimental\aio
>     copying src\python\grpcio\grpc\experimental\aio\_server.py -> python_build\lib.win32-3.8\grpc\experimental\aio
>     copying src\python\grpcio\grpc\experimental\aio\__init__.py -> python_build\lib.win32-3.8\grpc\experimental\aio
>     creating python_build\lib.win32-3.8\grpc\framework\common
>     copying src\python\grpcio\grpc\framework\common\cardinality.py -> python_build\lib.win32-3.8\grpc\framework\common
>     copying src\python\grpcio\grpc\framework\common\style.py -> python_build\lib.win32-3.8\grpc\framework\common
>     copying src\python\grpcio\grpc\framework\common\__init__.py -> python_build\lib.win32-3.8\grpc\framework\common
>     creating python_build\lib.win32-3.8\grpc\framework\foundation
>     copying src\python\grpcio\grpc\framework\foundation\abandonment.py -> python_build\lib.win32-3.8\grpc\framework\foundation
>     copying src\python\grpcio\grpc\framework\foundation\callable_util.py -> python_build\lib.win32-3.8\grpc\framework\foundation
>     copying src\python\grpcio\grpc\framework\foundation\future.py -> python_build\lib.win32-3.8\grpc\framework\foundation
>     copying src\python\grpcio\grpc\framework\foundation\logging_pool.py -> python_build\lib.win32-3.8\grpc\framework\foundation
>     copying src\python\grpcio\grpc\framework\foundation\stream.py -> python_build\lib.win32-3.8\grpc\framework\foundation
>     copying src\python\grpcio\grpc\framework\foundation\stream_util.py -> python_build\lib.win32-3.8\grpc\framework\foundation
>     copying src\python\grpcio\grpc\framework\foundation\__init__.py -> python_build\lib.win32-3.8\grpc\framework\foundation
>     creating python_build\lib.win32-3.8\grpc\framework\interfaces
>     copying src\python\grpcio\grpc\framework\interfaces\__init__.py -> python_build\lib.win32-3.8\grpc\framework\interfaces
>     creating python_build\lib.win32-3.8\grpc\framework\interfaces\base
>     copying src\python\grpcio\grpc\framework\interfaces\base\base.py -> python_build\lib.win32-3.8\grpc\framework\interfaces\base
>     copying src\python\grpcio\grpc\framework\interfaces\base\utilities.py -> python_build\lib.win32-3.8\grpc\framework\interfaces\base
>     copying src\python\grpcio\grpc\framework\interfaces\base\__init__.py -> python_build\lib.win32-3.8\grpc\framework\interfaces\base
>     creating python_build\lib.win32-3.8\grpc\framework\interfaces\face
>     copying src\python\grpcio\grpc\framework\interfaces\face\face.py -> python_build\lib.win32-3.8\grpc\framework\interfaces\face
>     copying src\python\grpcio\grpc\framework\interfaces\face\utilities.py -> python_build\lib.win32-3.8\grpc\framework\interfaces\face
>     copying src\python\grpcio\grpc\framework\interfaces\face\__init__.py -> python_build\lib.win32-3.8\grpc\framework\interfaces\face
>     creating python_build\lib.win32-3.8\grpc\_cython\_cygrpc
>     copying src\python\grpcio\grpc\_cython\_cygrpc\__init__.py -> python_build\lib.win32-3.8\grpc\_cython\_cygrpc
>     creating python_build\lib.win32-3.8\grpc\_cython\_credentials
>     copying src\python\grpcio\grpc\_cython\_credentials\roots.pem -> python_build\lib.win32-3.8\grpc\_cython\_credentials
>     running build_ext
>     error: [WinError 2] Impossibile trovare il file specificato
>     ----------------------------------------
> ERROR: Command errored out with exit status 1: 'c:\users\administrator\appdata\local\programs\python\python38-32\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Administrator\\AppData\\Local\\Temp\\2\\pip-install-6hv8xzb8\\grpcio\\setup.py'"'"'; __file__='"'"'C:\\Users\\Administrator\\AppData\\Local\\Temp\\2\\pip-install-6hv8xzb8\\grpcio\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\Administrator\AppData\Local\Temp\2\pip-record-nkilt9xu\install-record.txt' --single-version-externally-managed --compile Check the logs for full command output.

**Comment by gnossen** [comment] 2019-11-11 18:30
Closing as duplicate of https://github.com/grpc/grpc/issues/20879

**Closed by gnossen** 2019-11-11 18:30 UTC
Labels: area/packaging & distribution, kind/bug, lang/Python, priority/P2
