### ISSUE TITLE
c++_linux_opt_native.bins/opt/end2end_test --gtest_filter=ProxyEnd2end/ProxyEnd2endTest.EchoDeadline fails in Master 

### ISSUE THREAD

**Issue by dgquintas** [grpc/grpc#10092] opened 2017-03-10 17:36 UTC
https://grpc-testing.appspot.com/job/gRPC_master_linux/1727/testReport/junit/(root)/c++_linux_opt_native/bins_opt_end2end_test___gtest_filter_ProxyEnd2end_ProxyEnd2endTest_EchoDeadline_3__GRPC_POLL_STRATEGY_epoll/

```
Note: Google Test filter = ProxyEnd2end/ProxyEnd2endTest.EchoDeadline/3
[==========] Running 1 test from 1 test case.
[----------] Global test environment set-up.
[----------] 1 test from ProxyEnd2end/ProxyEnd2endTest
[ RUN      ] ProxyEnd2end/ProxyEnd2endTest.EchoDeadline/3
D0310 15:35:27.349632201   14727 end2end_test.cc:230]        TestScenario{use_proxy=true, credentials='INSECURE_CREDENTIALS'}
D0310 15:35:27.349675026   14727 ev_posix.c:107]             Using polling engine: epoll
I0310 15:35:27.352158780   14727 server_builder.cc:247]      Synchronous server. Num CQs: 4, Min pollers: 1, Max Pollers: 2147483647, CQ timeout (msec): 10
D0310 15:35:27.352207037   14727 ev_posix.c:107]             Using polling engine: epoll
I0310 15:35:27.370007394   14727 server_builder.cc:247]      Synchronous server. Num CQs: 4, Min pollers: 1, Max Pollers: 2147483647, CQ timeout (msec): 10
E0310 15:35:27.381182981   14727 sync_posix.c:66]            assertion failed: pthread_mutex_unlock(mu) == 0
*******************************
Caught signal SIGABRT
```

**Comment by dgquintas** [comment] 2017-09-24 01:05
Not seen in quite a while, closing.

**Comment by murgatroid99** [comment] 2017-11-07 18:30
Seen again: https://sponge.corp.google.com/target?id=97778a11-1762-41a8-a73a-d99d4b2e701e&target=grpc/ubuntu/pull_request/grpc_basictests_cpp_opt&searchFor=&show=ALL&sortBy=STATUS

```
Note: Google Test filter = ProxyEnd2end/ProxyEnd2endTest.EchoDeadline/1
[==========] Running 1 test from 1 test case.
[----------] Global test environment set-up.
[----------] 1 test from ProxyEnd2end/ProxyEnd2endTest
[ RUN      ] ProxyEnd2end/ProxyEnd2endTest.EchoDeadline/1
D1106 21:28:05.961754440   26784 end2end_test.cc:217]        TestScenario{use_proxy=true, inproc=false, credentials='ssl'}
D1106 21:28:05.961827546   26784 ev_posix.cc:135]            Using polling engine: poll-cv
D1106 21:28:05.961839277   26784 dns_resolver.cc:307]        Using native dns resolver
D1106 21:28:06.965049564   26784 ev_posix.cc:135]            Using polling engine: poll-cv
D1106 21:28:06.965103497   26784 dns_resolver.cc:307]        Using native dns resolver
I1106 21:28:06.965155281   26784 server_builder.cc:269]      Synchronous server. Num CQs: 4, Min pollers: 1, Max Pollers: 2, CQ timeout (msec): 10
I1106 21:28:06.984864183   26784 server_builder.cc:269]      Synchronous server. Num CQs: 4, Min pollers: 1, Max Pollers: 2, CQ timeout (msec): 10
test/cpp/end2end/end2end_test.cc:1348: Failure
Expected: (response.param().request_deadline() - sent_deadline.tv_sec) <= (1), actual: 2 vs 1
[  FAILED  ] ProxyEnd2end/ProxyEnd2endTest.EchoDeadline/1, where GetParam() = TestScenario{use_proxy=true, inproc=false, credentials='ssl'} (2072 ms)
[----------] 1 test from ProxyEnd2end/ProxyEnd2endTest (2072 ms total)

[----------] Global test environment tear-down
[==========] 1 test from 1 test case ran. (2072 ms total)
[  PASSED  ] 0 tests.
[  FAILED  ] 1 test, listed below:
[  FAILED  ] ProxyEnd2end/ProxyEnd2endTest.EchoDeadline/1, where GetParam() = TestScenario{use_proxy=true, inproc=false, credentials='ssl'}

 1 FAILED TEST
D1106 21:28:08.033801824   26784 ev_posix.cc:135]            Using polling engine: poll-cv
D1106 21:28:08.033827137   26784 dns_resolver.cc:307]        Using native dns resolver
```

**Comment by yang-g** [comment] 2017-12-13 00:42
This has not appeared for 2 weeks. Closing.

**Comment by dgquintas** [comment] 2017-12-19 22:46
This is still happening (current HEAD at 1c4d410c109157bfe924144bc777e57169d5c1e3). Reopening.

**Comment by jtattermusch** [comment] 2018-01-30 21:54
The failure details is interesting:
`test/cpp/end2end/end2end_test.cc:1337: Failure
Expected: (response.param().request_deadline() - sent_deadline.tv_sec) <= (1), actual: 2 vs 1`

According to the comment: "1 second error is allowed". 2 seconds seems close enough.
https://github.com/grpc/grpc/blob/9233201cc34e478e2a4d290c53bcf782a3864676/test/cpp/end2end/end2end_test.cc#L1337


```
[ RUN      ] ProxyEnd2end/ProxyEnd2endTest.EchoDeadline/1
D0124 20:37:26.993214151   21342 end2end_test.cc:217]        TestScenario{use_proxy=true, inproc=false, credentials='ssl'}
I0124 20:37:26.993294064   21342 ev_epoll1_linux.cc:114]     grpc epoll fd: 3
D0124 20:37:26.993305649   21342 ev_posix.cc:128]            Using polling engine: epoll1
D0124 20:37:26.993311926   21342 dns_resolver.cc:294]        Using native dns resolver
I0124 20:37:26.996632659   21342 ev_epoll1_linux.cc:114]     grpc epoll fd: 3
D0124 20:37:26.996654777   21342 ev_posix.cc:128]            Using polling engine: epoll1
D0124 20:37:26.996667094   21342 dns_resolver.cc:294]        Using native dns resolver
I0124 20:37:26.996708128   21342 server_builder.cc:269]      Synchronous server. Num CQs: 4, Min pollers: 1, Max Pollers: 2, CQ timeout (msec): 10
I0124 20:37:26.998464969   21342 server_builder.cc:269]      Synchronous server. Num CQs: 4, Min pollers: 1, Max Pollers: 2, CQ timeout (msec): 10
I0124 20:37:26.999175671   21599 subchannel.cc:603]          New connected subchannel at 0x7f4a70001110 for subchannel 0x7f4a88003320
I0124 20:37:27.002135508   21604 subchannel.cc:603]          New connected subchannel at 0x7f4a640110f0 for subchannel 0x7f4a88006520
test/cpp/end2end/end2end_test.cc:1338: Failure
Expected: (response.param().request_deadline() - sent_deadline.tv_sec) <= (1), actual: 2 vs 1
[  FAILED  ] ProxyEnd2end/ProxyEnd2endTest.EchoDeadline/1, where GetParam() = TestScenario{use_proxy=true, inproc=false, credentials='ssl'} (13 ms)
```

```
[==========] Running 1 test from 1 test case.
[----------] Global test environment set-up.
[----------] 1 test from ProxyEnd2end/ProxyEnd2endTest
[ RUN      ] ProxyEnd2end/ProxyEnd2endTest.EchoDeadline/3
D0130 17:16:15.982121402   14852 end2end_test.cc:217]        TestScenario{use_proxy=true, inproc=false, credentials='INSECURE_CREDENTIALS'}
D0130 17:16:15.982566701   14852 ev_posix.cc:128]            Using polling engine: epollex
D0130 17:16:15.982617841   14852 dns_resolver.cc:294]        Using native dns resolver
D0130 17:16:15.988347264   14852 ev_posix.cc:128]            Using polling engine: epollex
D0130 17:16:15.988403522   14852 dns_resolver.cc:294]        Using native dns resolver
I0130 17:16:15.988668808   14852 server_builder.cc:269]      Synchronous server. Num CQs: 4, Min pollers: 1, Max Pollers: 2, CQ timeout (msec): 10
I0130 17:16:15.996157487   14852 server_builder.cc:269]      Synchronous server. Num CQs: 4, Min pollers: 1, Max Pollers: 2, CQ timeout (msec): 10
I0130 17:16:15.999288596   16625 subchannel.cc:603]          New connected subchannel at 0x6030000255d0 for subchannel 0x61600008d380
I0130 17:16:16.001380042   16625 subchannel.cc:603]          New connected subchannel at 0x603000024040 for subchannel 0x61600008c780
test/cpp/end2end/end2end_test.cc:1337: Failure
Expected: (response.param().request_deadline() - sent_deadline.tv_sec) <= (1), actual: 2 vs 1
[  FAILED  ] ProxyEnd2end/ProxyEnd2endTest.EchoDeadline/3, where GetParam() = TestScenario{use_proxy=true, inproc=false, credentials='INSECURE_CREDENTIALS'} (35 ms)
```

**Comment by jtattermusch** [comment] 2018-01-30 22:16
Ok, I've confirmed my suspicion. The 2 seconds difference can happen  when we are close to the boundary of the next second  (tv_nsec is close the 1 billion).

So this seems to be just a badly designed test (the request_deadline in the response should have bigger precision than just seconds).

From my local runs with added logging:
```
I0130 23:10:39.001073091   69350 end2end_test.cc:1337]       request_deadline 1517350340
I0130 23:10:39.001085663   69350 end2end_test.cc:1338]       sent_deadline.tv_sec 1517350338
I0130 23:10:39.001092410   69350 end2end_test.cc:1339]       sent_deadline.tv_nsec 997481058
test/cpp/end2end/end2end_test.cc:1340: Failure
Expected: (response.param().request_deadline() - sent_deadline.tv_sec) <= (1), actual: 2 vs 1
[  FAILED  ] ProxyEnd2end/ProxyEnd2endTest.EchoDeadline/1, where GetParam() = TestScenario{use_proxy=true, inproc=false, credentials='ssl'} (10 ms)
```

```
I0130 23:10:32.000589931    8970 end2end_test.cc:1337]       request_deadline 1517350333
I0130 23:10:32.000603429    8970 end2end_test.cc:1338]       sent_deadline.tv_sec 1517350331
I0130 23:10:32.000609854    8970 end2end_test.cc:1339]       sent_deadline.tv_nsec 996396253
test/cpp/end2end/end2end_test.cc:1340: Failure
Expected: (response.param().request_deadline() - sent_deadline.tv_sec) <= (1), actual: 2 vs 1
[  FAILED  ] ProxyEnd2end/ProxyEnd2endTest.EchoDeadline/1, where GetParam() = TestScenario{use_proxy=true, inproc=false, credentials='ssl'} (11 ms)
```

**Closed** 2018-01-31 07:55 UTC
Labels: infra/BUILDPONY, lang/c++, priority/P1
