### ISSUE TITLE
Bazel: cc_grpc_library doesn't work when used in an external workspace

### ISSUE THREAD

**Issue by drigz** [grpc/grpc#14144] opened 2018-01-23 18:15 UTC
### What version of gRPC and what language are you using?

20e7074e4101b4fdbae1764caa952301b38957c4 

### What operating system (Linux, Windows, …) and version?
 
Ubuntu 14.04
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
 
gcc 4.8.4, bazel 0.9.0
 
### What did you do?

Build examples when using gRPC as an external repository:

```
> cat WORKSPACE                                                                                                                                                                                           [0/1159]
git_repository(
    name = "com_github_grpc_grpc",
    commit = "ac0808b107d73613191b66617a547a201871a845",
    remote = "https://github.com/grpc/grpc.git",
)

load("@com_github_grpc_grpc//:bazel/grpc_deps.bzl", "grpc_deps")

grpc_deps()

bind(
    name = "grpc_cpp_plugin",
    actual = "@com_github_grpc_grpc//:grpc_cpp_plugin",
)

bind(
    name = "grpc++_codegen_proto",
    actual = "@com_github_grpc_grpc//:grpc++_codegen_proto",
)
> bazel build @com_github_grpc_grpc//examples:helloworld
INFO: Analysed target @com_github_grpc_grpc//examples:helloworld (0 packages loaded).
INFO: Found 1 target...
ERROR: /usr/local/google/home/rodrigoq/.cache/bazel/_bazel_rodrigoq/255b0a538ff9ed77f751ada4321e0106/external/com_github_grpc_grpc/examples/BUILD:31:1: output 'external/com_github_grpc_grpc/examples/com_github_grpc_grpc/examples/protos/helloworld.grpc.pb.h' was not created
ERROR: /usr/local/google/home/rodrigoq/.cache/bazel/_bazel_rodrigoq/255b0a538ff9ed77f751ada4321e0106/external/com_github_grpc_grpc/examples/BUILD:31:1: output 'external/com_github_grpc_grpc/examples/com_github_grpc_grpc/examples/protos/helloworld.grpc.pb.cc' was not created
ERROR: /usr/local/google/home/rodrigoq/.cache/bazel/_bazel_rodrigoq/255b0a538ff9ed77f751ada4321e0106/external/com_github_grpc_grpc/examples/BUILD:31:1: not all outputs were created or valid
Target @com_github_grpc_grpc//examples:helloworld failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 0.529s, Critical Path: 0.12s
FAILED: Build did NOT complete successfully
```
 
### What did you expect to see?
 
Build succeeds.
 
### What did you see instead?
 
The build fails, because the wrong path is used for the output files. `com_github_grpc_grpc` has been erroneously duplicated due to incorrect handling of external paths:

`'external/com_github_grpc_grpc/examples/com_github_grpc_grpc/examples/protos/helloworld.grpc.pb.h' was not created`

**Comment by g-easy** [comment] 2018-07-03 04:15
This is still happening.

**Comment by vam-google** [comment] 2019-05-08 18:44
@g-easy Is it still happening? I can't reproduce it. 

`bazel build @com_github_grpc_grpc//examples:helloworld` works fine when exectued from a repository which consumes `@com_github_grpc_grpc` as a dependency

**Comment by g-easy** [comment] 2019-05-09 08:41
I think your PR fixes the problem but that specific target in grpc doesn't build due to an unrelated Python issue:

```
bazel build @com_github_grpc_grpc//examples:helloworld
[...]
ERROR: error loading package '@com_github_grpc_grpc//examples': in /.../external/com_github_grpc_grpc/bazel/python_rules.bzl: Unable to find package for @grpc_python_dependencies//:requirements.bzl: The repository '@grpc_python_dependencies' could not be resolved.
```

My WORKSPACE:
```
load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

http_archive(
    name = "com_github_grpc_grpc",
    strip_prefix = "grpc-master",
    urls = ["https://github.com/grpc/grpc/archive/master.tar.gz"],
)

load("@com_github_grpc_grpc//bazel:grpc_deps.bzl", "grpc_deps")
grpc_deps()
```

**Comment by vam-google** [comment] 2019-06-05 18:49
@g-easy I think you are missing `grpc_python_dependencies` dependency and related stuff in your WORKSPACE file. Note, bazel does not automatically import transitive dependencies of your direct dependencies (here `com_github_grpc_grpc` is your direct dependency and `grpc_python_dependencies` is your transitive dependency), so you have to do it manually.

The grpc repo in its WORKSPACE file first imports `io_bazel_rules_python` and then calls `pip_import` (this rule is defined in `io_bazel_rules_python`) to load `grpc_python_dependencies`. More details here: [WORKSPACE#L29](https://github.com/grpc/grpc/blob/master/WORKSPACE#L29)

**Comment by g-easy** [comment] 2019-12-03 01:21
Sorry for the lack of followup, looks like this works now:

```
$ cat WORKSPACE 
load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

http_archive(
    name = "com_github_grpc_grpc",
    strip_prefix = "grpc-master",
    urls = ["https://github.com/grpc/grpc/archive/master.tar.gz"],
)

load("@com_github_grpc_grpc//bazel:grpc_deps.bzl", "grpc_deps")
grpc_deps()

load("@com_github_grpc_grpc//bazel:grpc_extra_deps.bzl", "grpc_extra_deps")
grpc_extra_deps()

load("@io_bazel_rules_python//python:pip.bzl", "pip_import", "pip_repositories")

pip_import(
    name = "grpc_python_dependencies",
    requirements = "@com_github_grpc_grpc//:requirements.bazel.txt",
)

load("@grpc_python_dependencies//:requirements.bzl", "pip_install")

pip_repositories()

pip_install()

$ bazel build @com_github_grpc_grpc//examples:helloworld_cc_grpc
[...]
Target @com_github_grpc_grpc//examples:helloworld_cc_grpc up-to-date
```

**Comment by apolcyn** [comment] 2020-05-05 18:48
Based on the last comment, since it looks like this has been fixed, closing.

Please reopen there's still a bug, or post questions to grpc-io or stackoverflow

**Closed by apolcyn** 2020-05-05 18:48 UTC
Labels: infra/Bazel, kind/bug, lang/c++, priority/P2
