### ISSUE TITLE
Ruby flake: the secure http client/server behaves like basic GRPC message delivery is OK completes calls by sending status to client and server

### ISSUE THREAD

**Issue by ctiller** [grpc/grpc#1981] opened 2015-06-08 18:21 UTC
Failures:
  1) the secure http client/server behaves like basic GRPC message delivery is OK completes calls by sending status to client and server
     Failure/Error: expect(recvd_rpc).to_not eq nil
       
       expected: value != nil
            got: nil
       
       (compared using ==)
     Shared Example Group: "basic GRPC message delivery is OK" called from ./spec/client_server_spec.rb:383
     # ./spec/client_server_spec.rb:58:in `server_allows_client_to_proceed'
     # ./spec/client_server_spec.rb:155:in `block (2 levels) in <top (required)>'
I0608 18:00:57.020618206    9462 completion_queue.c:223] RETURN_EVENT[0x1f1a510]: QUEUE_SHUTDOWN
I0608 18:00:57.020658507    9462 completion_queue.c:223] RETURN_EVENT[0x1f23c60]: QUEUE_SHUTDOWN
Finished in 12.04 seconds (files took 0.54974 seconds to load)
89 examples, 1 failure

**Comment by tbetbetbe** [comment] 2015-06-23 16:24
This test fails here:

```ruby
  svr_batch = server_call.run_batch(@server_queue, @server_tag, deadline, ops)
  expect(svr_batch.send_metadata).to be true
```

That's checking the result of a call to the core api's grpc_call_run_batch via the [ruby wrapping layer](https://github.com/grpc/grpc/blob/master/src/ruby/ext/grpc/rb_call.c#L581)

I'm adding the core label:

It's not clear why most of the time the call to grpc_call_run_batch should produce the expected result, an then vary rarely fail like this, but it should be looked into.

**Comment by tbetbetbe** [comment] 2015-08-24 19:42
PTAL: @jayantkolhe, @hsaliak cannot reproduce locally after 20 iterations, removing Beta label

**Comment by jtattermusch** [comment] 2015-11-05 22:23
Is this still a thing?

**Comment by tbetbetbe** [comment] 2015-11-12 04:25
Nope. closing.

**Closed by tbetbetbe** 2015-11-12 04:25 UTC
Labels: cannot reproduce, core, ruby, Travis
