### ISSUE TITLE
Hangs Rails when using Spring

### ISSUE THREAD

**Issue by ngauthier** [grpc/grpc#1679] opened 2015-05-20 19:10 UTC
Hello!

When using the Ruby GRPC gem with Rails an Spring, GRPC causes a hang when exiting the application. I've created a replication here:

https://github.com/ngauthier/grpc-rails-hang-example

Simply run that script and you will see that it hangs before it reaches the "unreachable" section.

When attaching GDB and backtracing, I get this:

```
#0  pthread_cond_wait@@GLIBC_2.3.2 () at ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
#1  0x00007f5c16a5572e in gpr_cv_wait () from /usr/local/lib/libgpr.so.0
#2  0x00007f5c16a553b5 in gpr_event_wait () from /usr/local/lib/libgpr.so.0
#3  0x00007f5c16cb5168 in grpc_iomgr_shutdown () from /usr/local/lib/libgrpc.so.0
#4  0x00007f5c16cc2e6e in grpc_shutdown () from /usr/local/lib/libgrpc.so.0
#5  0x00007f5c21b49749 in ruby_vm_run_at_exit_hooks (vm=0x7f5c22667f20) at vm.c:350
#6  ruby_vm_destruct (vm=0x7f5c22667f20) at vm.c:1838
#7  0x00007f5c219f3666 in ruby_cleanup (ex=0) at eval.c:235
#8  0x00007f5c219f38c9 in ruby_stop (ex=<optimized out>) at eval.c:265
#9  0x00007f5c21a69421 in rb_f_fork (obj=<optimized out>) at process.c:3688
#10 0x00007f5c21b30d37 in vm_call_cfunc_with_frame (ci=<optimized out>, reg_cfp=0x7f5c219a1d40, th=0x7f5c226685f0) at vm_insnhelper.c:1382
#11 vm_call_cfunc (th=<optimized out>, reg_cfp=0x7f5c219a1d40, ci=<optimized out>) at vm_insnhelper.c:1475
#12 0x00007f5c21b35257 in vm_exec_core (th=th@entry=0x7f5c226685f0, initial=initial@entry=0) at insns.def:1024
#13 0x00007f5c21b39a98 in vm_exec (th=th@entry=0x7f5c226685f0) at vm.c:1400
#14 0x00007f5c21b47b3c in invoke_block_from_c (splattable=1, defined_class=140033691000240, cref=0x0, blockptr=0x0, argv=0x0, argc=0, self=140033694056520, 
    block=<optimized out>, th=0x7f5c226685f0) at vm.c:813
#15 vm_yield (argc=0, argv=0x0, th=0x7f5c226685f0) at vm.c:853
#16 rb_yield_0 (argv=0x0, argc=0) at vm_eval.c:987
#17 loop_i () at vm_eval.c:1058
#18 0x00007f5c219f419e in rb_rescue2 (b_proc=b_proc@entry=0x7f5c21b474a0 <loop_i>, data1=data1@entry=0, r_proc=r_proc@entry=0x0, data2=data2@entry=0) at eval.c:808
#19 0x00007f5c21b2ee4e in rb_f_loop (self=140033694056520) at vm_eval.c:1092
#20 0x00007f5c21b30d37 in vm_call_cfunc_with_frame (ci=<optimized out>, reg_cfp=0x7f5c219a1e30, th=0x7f5c226685f0) at vm_insnhelper.c:1382
#21 vm_call_cfunc (th=th@entry=0x7f5c226685f0, reg_cfp=reg_cfp@entry=0x7f5c219a1e30, ci=ci@entry=0x7f5c22a91108) at vm_insnhelper.c:1475
#22 0x00007f5c21b3fb6e in vm_call_method (th=0x7f5c226685f0, cfp=0x7f5c219a1e30, ci=0x7f5c22a91108) at vm_insnhelper.c:1691
#23 0x00007f5c21b35257 in vm_exec_core (th=th@entry=0x7f5c226685f0, initial=initial@entry=0) at insns.def:1024
#24 0x00007f5c21b39a98 in vm_exec (th=0x7f5c226685f0) at vm.c:1400
#25 0x00007f5c21b48b65 in rb_iseq_eval (iseqval=<optimized out>) at vm.c:1657
#26 0x00007f5c219f59ee in rb_load_internal0 (th=0x7f5c226685f0, fname=fname@entry=140033695139840, wrap=wrap@entry=0) at load.c:614
#27 0x00007f5c219f74ae in rb_load_internal (wrap=0, fname=140033695139840) at load.c:643
#28 rb_require_internal (fname=140033695139960, fname@entry=140033695140720, safe=0) at load.c:1004
#29 0x00007f5c219f7813 in rb_require_safe (safe=<optimized out>, fname=140033695140720) at load.c:1052
#30 rb_f_require (obj=<optimized out>, fname=140033695140720) at load.c:818
#31 0x00007f5c21b30d37 in vm_call_cfunc_with_frame (ci=<optimized out>, reg_cfp=0x7f5c219a1f20, th=0x7f5c226685f0) at vm_insnhelper.c:1382
#32 vm_call_cfunc (th=th@entry=0x7f5c226685f0, reg_cfp=reg_cfp@entry=0x7f5c219a1f20, ci=ci@entry=0x7f5c22a71e90) at vm_insnhelper.c:1475
#33 0x00007f5c21b3fb6e in vm_call_method (th=0x7f5c226685f0, cfp=0x7f5c219a1f20, ci=0x7f5c22a71e90) at vm_insnhelper.c:1691
#34 0x00007f5c21b3530d in vm_exec_core (th=th@entry=0x7f5c226685f0, initial=initial@entry=0) at insns.def:1054
#35 0x00007f5c21b39a98 in vm_exec (th=th@entry=0x7f5c226685f0) at vm.c:1400
#36 0x00007f5c21b48ddf in rb_iseq_eval_main (iseqval=iseqval@entry=140033695141080) at vm.c:1670
#37 0x00007f5c219efd7f in ruby_exec_internal (n=0x7f5c22a7ccd8) at eval.c:252
#38 0x00007f5c219f395f in ruby_exec_node (n=0x7f5c22a7ccd8) at eval.c:317
#39 ruby_run_node (n=<optimized out>) at eval.c:309
#40 0x00007f5c219ef90b in main (argc=5, argv=0x7ffd65e89cd8) at main.c:36
```

Which looks like it is hanging while shutting down the IO or something. Unfortunately my C is extremely rusty. Any ideas?

Thanks!

**Comment by ctiller** [comment] 2015-05-20 21:47
(I'm not in a location where I can easily reproduce this currently)

Can you try in gdb (and post the results):
```thread apply all backtrace```

It looks like there's some kind of deadlock happening at shutdown here. The above command should give me enough information to fix it.

**Comment by ngauthier** [comment] 2015-05-20 22:10
Will do tomorrow AM. Thanks!

**Comment by ngauthier** [comment] 2015-05-21 12:30
```
(gdb) thread apply all backtrace

Thread 2 (Thread 0x7f904a308700 (LWP 30069)):
#0  0x00007f90494b78dd in poll () at ../sysdeps/unix/syscall-template.S:81
#1  0x00007f904a497e30 in timer_thread_sleep (gvl=0x7f904b65af28) at thread_pthread.c:1436
#2  thread_timer (p=0x7f904b65af28) at thread_pthread.c:1543
#3  0x00007f9049ed16aa in start_thread (arg=0x7f904a308700) at pthread_create.c:333
#4  0x00007f90494c2eed in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109

Thread 1 (Thread 0x7f904a2e5700 (LWP 30062)):
#0  0x00007f9049ed9e0d in read () at ../sysdeps/unix/syscall-template.S:81
#1  0x00007f904a49d476 in rb_thread_io_blocking_region (func=func@entry=0x7f904a361a20 <internal_read_func>, data1=data1@entry=0x7ffc83feb070, fd=<optimized out>)
    at thread.c:1399
#2  0x00007f904a3641f6 in rb_read_internal (count=8192, buf=0x7f904c587fe0, fd=<optimized out>) at io.c:967
#3  io_bufread (ptr=0x7f904c587fe0 "", len=8192, fptr=0x7f904b874b30) at io.c:2094
#4  0x00007f904a364344 in bufread_call (arg=arg@entry=140722522993280) at io.c:2133
#5  0x00007f904a3355e0 in rb_ensure (b_proc=0x7f904a364330 <bufread_call>, data1=140722522993280, e_proc=e_proc@entry=0x7f904a409880 <rb_str_unlocktmp>, 
    data2=<optimized out>) at eval.c:907
#6  0x00007f904a41afb0 in rb_str_locktmp_ensure (str=<optimized out>, func=func@entry=0x7f904a364330 <bufread_call>, arg=arg@entry=140722522993280) at string.c:2098
#7  0x00007f904a368a0b in io_fread (fptr=0x7f904b874b30, size=8192, offset=<optimized out>, str=140257719062000) at io.c:2147
#8  read_all (fptr=fptr@entry=0x7f904b874b30, siz=siz@entry=8192, str=140257719062000, str@entry=8) at io.c:2417
#9  0x00007f904a36ca65 in io_read (argc=<optimized out>, argv=<optimized out>, io=<optimized out>) at io.c:2880
#10 0x00007f904a471d37 in vm_call_cfunc_with_frame (ci=<optimized out>, reg_cfp=0x7f904a2e2b10, th=0x7f904b65b5f0) at vm_insnhelper.c:1382
#11 vm_call_cfunc (th=th@entry=0x7f904b65b5f0, reg_cfp=reg_cfp@entry=0x7f904a2e2b10, ci=ci@entry=0x7f904c67dca8) at vm_insnhelper.c:1475
#12 0x00007f904a480b6e in vm_call_method (th=0x7f904b65b5f0, cfp=0x7f904a2e2b10, ci=0x7f904c67dca8) at vm_insnhelper.c:1691
#13 0x00007f904a47630d in vm_exec_core (th=th@entry=0x7f904b65b5f0, initial=initial@entry=0) at insns.def:1054
#14 0x00007f904a47aa98 in vm_exec (th=0x7f904b65b5f0) at vm.c:1400
#15 0x00007f904a489b65 in rb_iseq_eval (iseqval=<optimized out>) at vm.c:1657
#16 0x00007f904a3369ee in rb_load_internal0 (th=0x7f904b65b5f0, fname=140257717112320, wrap=<optimized out>) at load.c:614
#17 0x00007f904a336d42 in rb_load_internal (wrap=<optimized out>, fname=<optimized out>) at load.c:643
#18 rb_f_load (argc=<optimized out>, argv=<optimized out>) at load.c:703
#19 0x00007f904a471d37 in vm_call_cfunc_with_frame (ci=<optimized out>, reg_cfp=0x7f904a2e2e30, th=0x7f904b65b5f0) at vm_insnhelper.c:1382
#20 vm_call_cfunc (th=th@entry=0x7f904b65b5f0, reg_cfp=reg_cfp@entry=0x7f904a2e2e30, ci=ci@entry=0x7f904c37b5d0) at vm_insnhelper.c:1475
#21 0x00007f904a480b6e in vm_call_method (th=0x7f904b65b5f0, cfp=0x7f904a2e2e30, ci=0x7f904c37b5d0) at vm_insnhelper.c:1691
#22 0x00007f904a47630d in vm_exec_core (th=th@entry=0x7f904b65b5f0, initial=initial@entry=0) at insns.def:1054
#23 0x00007f904a47aa98 in vm_exec (th=0x7f904b65b5f0) at vm.c:1400
#24 0x00007f904a489b65 in rb_iseq_eval (iseqval=<optimized out>) at vm.c:1657
#25 0x00007f904a3369ee in rb_load_internal0 (th=0x7f904b65b5f0, fname=fname@entry=140257717128840, wrap=wrap@entry=0) at load.c:614
#26 0x00007f904a3384ae in rb_load_internal (wrap=0, fname=140257717128840) at load.c:643
#27 rb_require_internal (fname=140257717129080, fname@entry=140257717129120, safe=0) at load.c:1004
#28 0x00007f904a338813 in rb_require_safe (safe=<optimized out>, fname=140257717129120) at load.c:1052
#29 rb_f_require (obj=<optimized out>, fname=140257717129120) at load.c:818
#30 0x00007f904a471d37 in vm_call_cfunc_with_frame (ci=<optimized out>, reg_cfp=0x7f904a2e2ed0, th=0x7f904b65b5f0) at vm_insnhelper.c:1382
#31 vm_call_cfunc (th=th@entry=0x7f904b65b5f0, reg_cfp=reg_cfp@entry=0x7f904a2e2ed0, ci=ci@entry=0x7f904c453e30) at vm_insnhelper.c:1475
#32 0x00007f904a480b6e in vm_call_method (th=0x7f904b65b5f0, cfp=0x7f904a2e2ed0, ci=0x7f904c453e30) at vm_insnhelper.c:1691
#33 0x00007f904a47630d in vm_exec_core (th=th@entry=0x7f904b65b5f0, initial=initial@entry=0) at insns.def:1054
#34 0x00007f904a47aa98 in vm_exec (th=0x7f904b65b5f0) at vm.c:1400
#35 0x00007f904a489b65 in rb_iseq_eval (iseqval=<optimized out>) at vm.c:1657
#36 0x00007f904a3369ee in rb_load_internal0 (th=0x7f904b65b5f0, fname=140257717149160, wrap=<optimized out>) at load.c:614
#37 0x00007f904a336d42 in rb_load_internal (wrap=<optimized out>, fname=<optimized out>) at load.c:643
#38 rb_f_load (argc=<optimized out>, argv=<optimized out>) at load.c:703
#39 0x00007f904a471d37 in vm_call_cfunc_with_frame (ci=<optimized out>, reg_cfp=0x7f904a2e2f70, th=0x7f904b65b5f0) at vm_insnhelper.c:1382
#40 vm_call_cfunc (th=th@entry=0x7f904b65b5f0, reg_cfp=reg_cfp@entry=0x7f904a2e2f70, ci=ci@entry=0x7f904bb3f818) at vm_insnhelper.c:1475
#41 0x00007f904a480b6e in vm_call_method (th=0x7f904b65b5f0, cfp=0x7f904a2e2f70, ci=0x7f904bb3f818) at vm_insnhelper.c:1691
#42 0x00007f904a47630d in vm_exec_core (th=th@entry=0x7f904b65b5f0, initial=initial@entry=0) at insns.def:1054
#43 0x00007f904a47aa98 in vm_exec (th=th@entry=0x7f904b65b5f0) at vm.c:1400
#44 0x00007f904a489ddf in rb_iseq_eval_main (iseqval=iseqval@entry=140257717151000) at vm.c:1670
#45 0x00007f904a330d7f in ruby_exec_internal (n=0x7f904b686518) at eval.c:252
#46 0x00007f904a33495f in ruby_exec_node (n=0x7f904b686518) at eval.c:317
#47 ruby_run_node (n=<optimized out>) at eval.c:309
#48 0x00007f904a33090b in main (argc=4, argv=0x7ffc83fed628) at main.c:36
```

**Comment by ngauthier** [comment] 2015-05-21 12:31
```
(gdb) thread apply all backtrace

Thread 1 (Thread 0x7fc6043f0700 (LWP 30089)):
#0  pthread_cond_wait@@GLIBC_2.3.2 () at ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
#1  0x00007fc5f961472e in gpr_cv_wait () from /usr/local/lib/libgpr.so.0
#2  0x00007fc5f96143b5 in gpr_event_wait () from /usr/local/lib/libgpr.so.0
#3  0x00007fc5f9874168 in grpc_iomgr_shutdown () from /usr/local/lib/libgrpc.so.0
#4  0x00007fc5f9881e6e in grpc_shutdown () from /usr/local/lib/libgrpc.so.0
#5  0x00007fc604595749 in ruby_vm_run_at_exit_hooks (vm=0x7fc606313f20) at vm.c:350
#6  ruby_vm_destruct (vm=0x7fc606313f20) at vm.c:1838
#7  0x00007fc60443f666 in ruby_cleanup (ex=0) at eval.c:235
#8  0x00007fc60443f8c9 in ruby_stop (ex=<optimized out>) at eval.c:265
#9  0x00007fc6044b5421 in rb_f_fork (obj=<optimized out>) at process.c:3688
#10 0x00007fc60457cd37 in vm_call_cfunc_with_frame (ci=<optimized out>, reg_cfp=0x7fc6043edd40, th=0x7fc6063145f0) at vm_insnhelper.c:1382
#11 vm_call_cfunc (th=th@entry=0x7fc6063145f0, reg_cfp=reg_cfp@entry=0x7fc6043edd40, ci=ci@entry=0x7fc606744a78) at vm_insnhelper.c:1475
#12 0x00007fc60458bb6e in vm_call_method (th=0x7fc6063145f0, cfp=0x7fc6043edd40, ci=0x7fc606744a78) at vm_insnhelper.c:1691
#13 0x00007fc604581257 in vm_exec_core (th=th@entry=0x7fc6063145f0, initial=initial@entry=0) at insns.def:1024
#14 0x00007fc604585a98 in vm_exec (th=th@entry=0x7fc6063145f0) at vm.c:1400
#15 0x00007fc604593b3c in invoke_block_from_c (splattable=1, defined_class=140488484280320, cref=0x0, blockptr=0x0, argv=0x0, argc=0, self=140488487385120, 
    block=<optimized out>, th=0x7fc6063145f0) at vm.c:813
#16 vm_yield (argc=0, argv=0x0, th=0x7fc6063145f0) at vm.c:853
#17 rb_yield_0 (argv=0x0, argc=0) at vm_eval.c:987
#18 loop_i () at vm_eval.c:1058
#19 0x00007fc60444019e in rb_rescue2 (b_proc=b_proc@entry=0x7fc6045934a0 <loop_i>, data1=data1@entry=0, r_proc=r_proc@entry=0x0, data2=data2@entry=0) at eval.c:808
#20 0x00007fc60457ae4e in rb_f_loop (self=140488487385120) at vm_eval.c:1092
#21 0x00007fc60457cd37 in vm_call_cfunc_with_frame (ci=<optimized out>, reg_cfp=0x7fc6043ede30, th=0x7fc6063145f0) at vm_insnhelper.c:1382
#22 vm_call_cfunc (th=th@entry=0x7fc6063145f0, reg_cfp=reg_cfp@entry=0x7fc6043ede30, ci=ci@entry=0x7fc60673ca68) at vm_insnhelper.c:1475
#23 0x00007fc60458bb6e in vm_call_method (th=0x7fc6063145f0, cfp=0x7fc6043ede30, ci=0x7fc60673ca68) at vm_insnhelper.c:1691
#24 0x00007fc604581257 in vm_exec_core (th=th@entry=0x7fc6063145f0, initial=initial@entry=0) at insns.def:1024
#25 0x00007fc604585a98 in vm_exec (th=0x7fc6063145f0) at vm.c:1400
#26 0x00007fc604594b65 in rb_iseq_eval (iseqval=<optimized out>) at vm.c:1657
#27 0x00007fc6044419ee in rb_load_internal0 (th=0x7fc6063145f0, fname=fname@entry=140488488420360, wrap=wrap@entry=0) at load.c:614
#28 0x00007fc6044434ae in rb_load_internal (wrap=0, fname=140488488420360) at load.c:643
#29 rb_require_internal (fname=140488488420480, fname@entry=140488488421240, safe=0) at load.c:1004
#30 0x00007fc604443813 in rb_require_safe (safe=<optimized out>, fname=140488488421240) at load.c:1052
#31 rb_f_require (obj=<optimized out>, fname=140488488421240) at load.c:818
#32 0x00007fc60457cd37 in vm_call_cfunc_with_frame (ci=<optimized out>, reg_cfp=0x7fc6043edf20, th=0x7fc6063145f0) at vm_insnhelper.c:1382
#33 vm_call_cfunc (th=th@entry=0x7fc6063145f0, reg_cfp=reg_cfp@entry=0x7fc6043edf20, ci=ci@entry=0x7fc60671df10) at vm_insnhelper.c:1475
#34 0x00007fc60458bb6e in vm_call_method (th=0x7fc6063145f0, cfp=0x7fc6043edf20, ci=0x7fc60671df10) at vm_insnhelper.c:1691
#35 0x00007fc60458130d in vm_exec_core (th=th@entry=0x7fc6063145f0, initial=initial@entry=0) at insns.def:1054
#36 0x00007fc604585a98 in vm_exec (th=th@entry=0x7fc6063145f0) at vm.c:1400
#37 0x00007fc604594ddf in rb_iseq_eval_main (iseqval=iseqval@entry=140488488421600) at vm.c:1670
#38 0x00007fc60443bd7f in ruby_exec_internal (n=0x7fc6067288e0) at eval.c:252
#39 0x00007fc60443f95f in ruby_exec_node (n=0x7fc6067288e0) at eval.c:317
#40 ruby_run_node (n=<optimized out>) at eval.c:309
#41 0x00007fc60443b90b in main (argc=5, argv=0x7ffc3b4509b8) at main.c:36
```

**Comment by ctiller** [comment] 2015-07-14 19:38
Tim: it's probably worth trying to reproduce this (and maybe building a test around it)

**Comment by justinko** [comment] 2015-08-03 03:09
This is a blocker for using gRPC with a default Rails application.

**Comment by jayantkolhe** [comment] 2015-09-04 06:58
any updates

**Comment by tbetbetbe** [comment] 2015-09-04 19:35
@jayantkolhe: removing the beta milestone

Rationale:

- since this was reported, there have been significant changes to how shut down works as multiple wrapped layers have had and fixed shut down issues.  E.g, #2946, #2720, and most recently for ruby,  #3144.

- it's not practical to include automated tests for rails itself in the grpc ruby test suite; the ruby test suite has enough tests that already cover shut down

Next steps
- a manual attempt to reproduce using that latest version of the core and ruby extension.  As there are no api changes involved, this work and and changes that result from it need not block beta

**Comment by justinko** [comment] 2015-11-11 18:39
Not sure about the releases, but this is fixed in master! :trophy:

**Comment by tbetbetbe** [comment] 2015-11-12 04:23
Cool, thanks for the update - closing!

**Closed** 2015-11-12 04:23 UTC
Labels: core, ruby
