### ISSUE TITLE
Interop tests and servers should all use the same flow control window

### ISSUE THREAD

**Issue by ejona86** [grpc/grpc#1666] opened 2015-05-20 00:18 UTC
Right now we are generally using 1 MB as the connection window size and 64 KB as the stream flow control window. However, the tests were written assuming we were using the defaults of 64 KB for both. Also, it seems in the future we will be changing the flow control windows more. Java for instance is considering upping the window to 1 MB after putting in better memory handling. Java is also expecting to auto-tune the flow control window size based on the bandwidth-delay product.

We should specify that interop clients and servers should hard-code a fixed connection and stream window size. Given that we want to find bugs with the interop tests, I suggest 64 KB for both, but I'm open to alternatives.

**Comment by ctiller** [comment] 2015-05-20 00:48
I'm good with 64kb for both. I'd like to push it explicitly into the
interop tests however, as I'd like the ability to tune the defaults over
time.

**Comment by ejona86** [comment] 2015-05-20 01:07
Yes, pushing it explicitly into the interop test client/server was my intention.

**Comment by dgquintas** [comment] 2016-11-16 00:15
Did this ever happen?

**Comment by ejona86** [comment] 2016-11-16 09:42
Looking at `interop-test-descriptions.md`, it seems not.

**Comment by ncteisen** [comment] 2017-12-20 18:38
Current c core behavior: start with defaults of 64k for transport and stream windows, then tune base on BDP estimate and lookahead bytes based on know message size.

There is no mode to keep everything fixed, and only ping pong the basic bookkeeping updates.

Is this feature request still worthwhile?

**Comment by ejona86** [comment] 2018-01-08 15:41
It is still worthwhile in the sense that we need interop tests to tickle flow control.

**Comment by ncteisen** [comment] 2019-02-06 15:46
Duplicate of #14932

**Closed by ncteisen** 2019-02-06 15:46 UTC
Labels: area/core, area/interop, disposition/FOR DISCUSSION, kind/enhancement, lang/all wrapped languages, priority/P3
