### ISSUE TITLE
Aborting bidirectional streaming RPCs leads to issues with _MultiThreadedRendezvous with gRPC 1.32.0

### ISSUE THREAD

**Issue by tmccnnll** [grpc/grpc#24171] opened 2020-09-17 20:47 UTC
### What version of gRPC and what language are you using?

`1.32.0` and Python

### What operating system (Linux, Windows,...) and version?

- `macOS Mojave 10.14.6`
- `Linux 5fa39a7f0e3f 4.15.0-1077-aws #81-Ubuntu SMP Wed Jun 24 16:48:15 UTC 2020 x86_64 Linux`

### What runtime / compiler are you using (e.g. python version or version of gcc)

- Python `3.5.9`
- Python `3.6.10`
- Python `3.7.7`
- Python `3.8.3`

### What did you do?

Upgrading from `grpcio==1.32.0` from `grpcio==1.31.0` seems to cause issues with `_MultiThreadedRendezvous` when working with bidirectional streaming RPCs.

Steps to reproduce:

1. Server is hosting a bidirectional streaming RPC
2. Client dials this bidirectional streaming RPC and sends messages while capturing the response object (i.e., the `_MultiThreadedRendezvous` object) in a variable instead of consuming/iterating over it
3. Server sends at least one response to the client
4. Server then calls `context.abort` to terminate the RPC
5. Client calls any of the `_MultiThreadedRendezvous` object's methods that themselves call `_common.wait(...)`; e.g., `code`, `details`, or `result`

Here is an example gRPC client and server that demonstrates the issue: 
[hellostreamingworld.tar.gz](https://github.com/grpc/grpc/files/5241689/hellostreamingworld.tar.gz)

### What did you expect to see?

Client code receives return value from `_MultiThreadedRendezvous` method call and finishes execution. This is what happens with `grpcio==1.31.0`

### What did you see instead?

Client code will get stuck waiting for the return value of the method call and execution does not proceed.

If the execution is interrupted with a `SIGINT`, you will see the following traceback:
```
Traceback (most recent call last):
  File "/Users/tylermcconnell/.pyenv/versions/3.7.7/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Users/tylermcconnell/.pyenv/versions/3.7.7/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/tylermcconnell/Documents/source/grpc/examples/python/hellostreamingworld/hellostreamingworld_client.py", line 45, in <module>
    run()
  File "/Users/tylermcconnell/Documents/source/grpc/examples/python/hellostreamingworld/hellostreamingworld_client.py", line 38, in run
    logging.info("Resulting code from broken input: %s", reply_iter.code())
  File "/Users/tylermcconnell/.pyenv/versions/3.7.7/lib/python3.7/site-packages/grpc/_channel.py", line 571, in code
    _common.wait(self._state.condition.wait, _done)
  File "/Users/tylermcconnell/.pyenv/versions/3.7.7/lib/python3.7/site-packages/grpc/_common.py", line 141, in wait
    _wait_once(wait_fn, MAXIMUM_WAIT_TIMEOUT, spin_cb)
  File "/Users/tylermcconnell/.pyenv/versions/3.7.7/lib/python3.7/site-packages/grpc/_common.py", line 106, in _wait_once
    wait_fn(timeout=timeout)
  File "/Users/tylermcconnell/.pyenv/versions/3.7.7/lib/python3.7/threading.py", line 300, in wait
    gotit = waiter.acquire(True, timeout)
```

Some other things to note:

- Consuming the responses from the `_MultiThreadedRendezvous` object (e.g., iterating through the object in a loop or wrapping it in a `list`) allows the client-side execution to proceed
- Adding a timeout to the RPC allows the client-side execution to proceed with the client receiving a `DEADLINE_EXCEEDED` status code
- If the server immediately calls `context.abort` upon receiving a request (i.e., before sending any response) then the client-side execution will proceed
- Using `context.cancel` on the server-side instead of `context.abort` results in the same outcome

**Comment by XuanWang-Amos** [comment] 2023-04-14 22:15
Hi, sorry we didn't get a chance to check this out sooner. I tested the latest release (1.53.0) and it seems to be working fine now. I'm closing this issue since I can't reproduce the problem anymore.

If you still think this is an issue, please reopen it or file a new issue.

**Closed by XuanWang-Amos** 2023-04-14 22:15 UTC
Labels: kind/bug, lang/Python, priority/P2
