### ISSUE TITLE
Grpc.Core.RpcException: Status(StatusCode=Unavailable, Detail="OS Error")

### ISSUE THREAD

**Issue by vuukle** [grpc/grpc#14653] opened 2018-03-09 11:46 UTC
### What version of gRPC and what language are you using?
We recently(yesterday) upgraded to 1.10.0 from 1.9.0 and using aspnetcore 2.0 on google app engine fle
 
### What operating system (Linux, Windows, …) and version?
 Google APP Engine Flex for aspnet core
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
 aspnetcore
 
### What did you do?
If possible, provide a recipe for reproducing the error. Try being specific and include code snippets if helpful.
You may check the thread [here ](https://github.com/GoogleCloudPlatform/google-cloud-dotnet/issues/1903#issuecomment-371771638)too but yesterday after upgraded to 1.10.0 we started seeing a new grpc error as mentioned above 
 
### What did you expect to see?
 i expected the errors to go away after upgrading to 1.10.0
 
### What did you see instead?
```
 Grpc.Core.RpcException: Status(StatusCode=Unavailable, Detail="OS Error")

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).
Grpc.Core.RpcException: Status(StatusCode=Unavailable, Detail="OS Error")
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification
at Grpc.Core.Internal.AsyncCall`2.UnaryCall
at Grpc.Core.DefaultCallInvoker.BlockingUnaryCall[TRequest,TResponse]
at Grpc.Core.Interceptors.InterceptingCallInvoker.<BlockingUnaryCall>b__3_0[TRequest,TResponse]
at Grpc.Core.ClientBase.ClientBaseConfiguration.ClientBaseConfigurationInterceptor.BlockingUnaryCall[TRequest,TResponse]
at Grpc.Core.Interceptors.InterceptingCallInvoker.BlockingUnaryCall[TRequest,TResponse]
at Google.Cloud.Datastore.V1.Datastore.DatastoreClient.RunQuery
at Google.Api.Gax.Grpc.ApiCall.<>c__DisplayClass0_0`2.<Create>b__1
at Google.Api.Gax.Grpc.ApiCallRetryExtensions.<>c__DisplayClass1_0`2.<WithRetry>b__0
at Google.Cloud.Datastore.V1.QueryStreamer.<Sync>d__7.MoveNext
at System.Collections.Generic.List`1.AddEnumerable
at System.Linq.Enumerable.ToList[TSource]
at Google.Cloud.Datastore.V1.LazyDatastoreQuery.GetAllResults
``` 

### Anything else we should know about your project / environment?

please check the screenshot 

![image](https://user-images.githubusercontent.com/2103977/37206187-9bc3f542-2365-11e8-960a-773a808559a2.png)

**Comment by david-martyn-ford** [comment] 2018-08-20 11:38
I am also having the same issue with gRPC 1.9.0 and .NET Core 2.0 which is hosted in Kubernetes. 

Issue is only seen in .NET services, none of our Node.js services have had any issues.

**Comment by jtattermusch** [comment] 2018-08-28 12:50
@david-martyn-ford  can you provide a reproduction? Have you tried with newer versions of gRPC? (v1.14.1 is currently the latest). Also, it's not clear how often this happens (e.g. in % of runs)

**Comment by david-martyn-ford** [comment] 2018-09-03 09:11
@jtattermusch We are still experiencing the same issue when running version `v1.14.1`. I'll try setup an app to reproduce it and provide more information like number of times it errors

**Comment by david-martyn-ford** [comment] 2018-10-01 14:27
@mioyingluffy Unfortunately not, we've added more advanced healthchecks to detect when the issue appears and restarts the container which resolves it for a day or two - far from ideal.

I'm not entirely sold it's actually related to gRPC but actually to the ASP.NET docker image we are using (`microsoft/aspnetcore:2.0`). We've recently added RabbitMQ into our service which also drops at the same time the gRPC issue comes up as well. Both get resolved after a restart.

**Comment by jtattermusch** [comment] 2018-11-06 12:45
@david-martyn-ford   it would be great to establish if this is a docker or kubernetes related problem. If you could setup a reproduction where things fail with both gRPC and some other middleware, it would be super helpful.

**Comment by evhfla** [comment] 2018-11-07 21:33
Hum...I am not doing anything special.  It is intermittent, but mostly happened after a new deployment.

**Comment by bitlkoskela** [comment] 2019-01-03 08:41
We're also still seeing this occur daily on GKE and .Net Core 2.1. Is [src/core/lib/iomgr/resolve_address_posix.cc](https://github.com/grpc/grpc/blob/9bc6cd1a72b0493f7786c6458d26d621a10befb0/src/core/lib/iomgr/resolve_address_posix.cc#L108) the only place where the status message `OS Error` can be generated? So is this DNS-related? Is there any way to extract more information about the error?

**Comment by jtattermusch** [comment] 2019-02-13 14:55
@bitlkoskela  would you be able to provide code that reproduces it on GKE?
Instructions for extra logging and tracing: https://github.com/grpc/grpc/blob/master/TROUBLESHOOTING.md

**Comment by ubercow** [comment] 2019-05-22 03:27
I might be having the same issue.

I'm using a csharp server and client (1.17.0) on Azure Kubernetes Engine. Requests are being proxied through Heptio Contour.

If I make a call, then wait ~5 minutes, then attempt to make another call it will wait 2 minutes before failing on a recvmsg syscall timeout. After, it seems to retry internally and immediately fails with a Broken Pipe. The next time I attempt a call, it seems to reestablish the connection and succeeds.

I believe in my case, it's due to Azure's Load Balancer closing the connection after 5 minutes. According to their docs, 4 minutes is the default. I'm not familiar with the internals of linux's sockets, but perhaps there is some way to make this fail faster?

In my case, calls are few and far between so I'm working around this now by closing the connection after every call.

If you think my logs would be helpful I'd be happy to post them.

**Comment by jtattermusch** [comment] 2019-05-24 07:52
@ubercow   if Azure Load Balance is closing your connection, what behavior would you expect besides the RPC failing? (there is an ongoing effort for automatic retries, but it's not ready yet, so for now you need to retry yourself).
To keep the connection alive, you might be able to configure keepalive options: e.g. https://github.com/grpc/grpc/blob/f4ce5fc2510c342adc86afa41a9354d9956a9092/include/grpc/impl/codegen/grpc_types.h#L229 but I don't know enought about Azure Load Balancer to be able to say if that's going to help.

**Comment by prairieapps** [comment] 2019-06-19 16:09
We are experiencing this error intermittently using .NET Core 2.2.4 & Docker

**Comment by jtattermusch** [comment] 2019-11-12 08:53
Can someone provide a minimal reproduction with instructions how to reproduce? This issue has been open for long time and it seems that without a reproductions we won't be able to make any progress.

**Comment by bitlkoskela** [comment] 2019-11-12 13:21
@jtattermusch We actually found a working solution for this problem just this month. We still are not sure about the specific reason, and we don't have a reproduction to provide but we haven't seen these errors where we previously got them very consistently (every day).

The solution was just to enable keepalive pings for long-lived channels, like suggested before. We followed this blog post: https://cs.mcgill.ca/~mxia3/2019/02/23/Using-gRPC-in-Production/ . After applying these settings, the errors went away completely.

So the underlying issue seems to indeed be sockets closing / broken pipes. I don't know exactly why we have been unable to create a reproduction case for this, as the pattern seems to be pretty clear: a channel is used for a few hours, then it's kept idle for a day or two, then the first call fails. It may have something to do with GKE-specific connection handling or something like that.

Why the RpcException does not contain any other information other than "OS Error"? That has made finding the cause of the issue much more difficult than should be necessary.

**Comment by albertocsm** [comment] 2019-11-18 12:37
having the same issue with .Net core and gRPC on AKS.

could this be related to .net gRPC's client connection balancer?
if something like [this](https://github.com/albertocsm/grpc-client-balancing-test/blob/master/client/main.go#L31) is happening under the covers out of the box, maybe there's some issue there...

**Comment by jtattermusch** [comment] 2020-08-18 09:11
To summarize:
The issues mentioned in this issue seem to have a common factor of service being run in a managed environment (e.g. Google Appengine Flex, AKS etc.). What seems to happen is the managed environment kills existing connections after a while (e.g. after max connection lifetime determined by the environment is reached or after a period of inactivity on that connection when a loadbalancer is used).
This is pretty natural and the solution is to 
a) just retry the RPC (which is a good practice in distributed environments anyway), which will recreate a connection and things will get back to normal
b) setup keepalives to keep connection "active" even when no request/responses are being sent and thus avoid killing the connection by the managed environment (e.g. kubernetes engine loadbalancer). This approach might or might not help depending on the technical details of the platform you're using.

Since there is no way gRPC can magically avoid connections from being killed by the managed enviroment (besides setting keepalives correctly), I'll close this issue as not actionable.

**Closed by jtattermusch** 2020-08-18 09:11 UTC
Labels: disposition/cannot reproduce, kind/bug, lang/C#, priority/P3

**Comment by JohnRelix** [comment] 2023-10-19 21:45
Unhandled Exception: Grpc.Core.RpcException: Status(StatusCode="Unavailable", Detail="Error starting gRPC call. HttpRequestException: An error occurred while sending the request. IOException: The request was aborted. IOException: Pipe is broken.", DebugException="System.Net.Http.HttpRequestException: An error occurred while sending the request.
 ---> System.IO.IOException: The request was aborted.
 ---> System.IO.IOException: Pipe is broken.
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() + 0x20
   at System.Threading.Tasks.Sources.ManualResetValueTaskSourceCore`1.ThrowForFailedGetResult(Int16) + 0x2a
   at System.Threading.Tasks.Sources.ManualResetValueTaskSourceCore`1.GetResult(Int16) + 0x2a
   at System.IO.Pipes.PipeStream.PipeValueTaskSource.GetResult(Int16) + 0x21
   at System.IO.Pipes.PipeStream.PipeValueTaskSource.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16) + 0xd
   at System.Net.Http.Http2Connection.<FlushOutgoingBytesAsync>d__67.MoveNext() + 0x1f1
   --- End of inner exception stack trace ---
   at System.Net.Http.Http2Connection.ThrowRequestAborted(Exception) + 0x11
   at System.Net.Http.Http2Connection.Http2Stream.CheckResponseBodyState() + 0x40
   at System.Net.Http.Http2Connection.Http2Stream.TryEnsureHeaders() + 0x2b
   at System.Net.Http.Http2Connection.Http2Stream.<ReadResponseHeadersAsync>d__73.MoveNext() + 0x350
--- End of stack trace from previous location ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() + 0x20
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task) + 0xb6
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task) + 0x42
   at System.Net.Http.Http2Connection.<SendAsync>d__118.MoveNext() + 0x57c
   --- End of inner exception stack trace ---
   at System.Net.Http.Http2Connection.<SendAsync>d__118.MoveNext() + 0x6c2
--- End of stack trace from previous location ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() + 0x20
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task) + 0xb6
   at System.Net.Http.HttpConnectionPool.<SendWithVersionDetectionAndRetryAsync>d__84.MoveNext() + 0x885
--- End of stack trace from previous location ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() + 0x20
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task) + 0xb6
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task) + 0x42
   at System.Net.Http.RedirectHandler.<SendAsync>d__4.MoveNext() + 0x1b6
--- End of stack trace from previous location ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() + 0x20
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task) + 0xb6
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task) + 0x42
   at Grpc.Net.Client.Balancer.Internal.BalancerHttpHandler.<SendAsync>d__10.MoveNext() + 0x726
--- End of stack trace from previous location ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() + 0x20
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task) + 0xb6
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task) + 0x42
   at Grpc.Net.Client.Internal.GrpcCall`2.<RunCall>d__73.MoveNext() + 0xe27")
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() + 0x20
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task) + 0xb6
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task) + 0x42
   at Grpc.Net.Client.Internal.Retry.RetryCallBaseClientStreamReader`2.<MoveNext>d__4.MoveNext() + 0x1d1
--- End of stack trace from previous location ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() + 0x20
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task) + 0xb6
   at Grpc.Core.AsyncStreamReaderExtensions.<ReadAllAsyncCore>d__1`1.MoveNext() + 0x197
--- End of stack trace from previous location ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() + 0x20
   at System.Threading.Tasks.Sources.ManualResetValueTaskSourceCore`1.ThrowForFailedGetResult(Int16) + 0x2a
   at System.Threading.Tasks.Sources.ManualResetValueTaskSourceCore`1.GetResult(Int16) + 0x2a
   at Unity.ILPP.Trigger.TriggerApp.<ProcessArgumentsAsync>d__1.MoveNext() + 0xe04
--- End of stack trace from previous location ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() + 0x20
   at Unity.ILPP.Trigger.TriggerApp.<ProcessArgumentsAsync>d__1.MoveNext() + 0xfa2
--- End of stack trace from previous location ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() + 0x20
   at Unity.ILPP.Trigger.TriggerApp.<ProcessArgumentsAsync>d__1.MoveNext() + 0x1149
--- End of stack trace from previous location ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() + 0x20
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task) + 0xb6
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task) + 0x42
   at Unity.ILPP.Trigger.TriggerApp.<RunAsync>d__0.MoveNext() + 0xc7
--- End of stack trace from previous location ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() + 0x20
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task) + 0xb6
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task) + 0x42
   at Program.<<Main>$>d__0.MoveNext() + 0x1a3
--- End of stack trace from previous location ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() + 0x20
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task) + 0xb6
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task) + 0x42
   at Program.<Main>(String[]) + 0x20
   at Unity.ILPP.Trigger!<BaseAddress>+0x47849b
![Screenshot 2023-10-20 052253](https://github.com/grpc/grpc/assets/86653025/f912561e-bf04-489b-9e72-6022f53afcaa)
I have the same issue in unity framework i dont know how to solve it please help
