### ISSUE TITLE
QPS benchmark failure with 500kib resource quota

### ISSUE THREAD

**Issue by apolcyn** [grpc/grpc#9609] opened 2017-02-06 22:43 UTC
```
++ dirname tools/run_tests/performance/run_qps_driver.sh
+ cd tools/run_tests/performance/../../..
+ bins/opt/qps_json_driver '--scenarios_json={"scenarios": [{"name": "cpp_protobuf_sync_streaming_qps_unconstrained_secure_500kib_resource_quota", "warmup_seconds": 5, "benchmark_seconds": 30, "num_servers": 1, "server_config": {"resource_quota_size": 512000, "async_server_threads": 0, "security_params": {"use_test_ca": true, "server_host_override": "foo.test.google.fr"}, "payload_config": {"simple_params": {"resp_size": 0, "req_size": 0}}, "server_type": "SYNC_SERVER"}, "client_config": {"client_type": "SYNC_CLIENT", "security_params": {"use_test_ca": true, "server_host_override": "foo.test.google.fr"}, "payload_config": {"simple_params": {"resp_size": 0, "req_size": 0}}, "client_channels": 64, "async_client_threads": 0, "outstanding_rpcs_per_channel": 16, "rpc_type": "STREAMING", "load_params": {"closed_loop": {}}, "histogram_params": {"max_possible": 60000000000.0, "resolution": 0.01}}, "num_clients": 0}]}' --scenario_result_file=scenario_result.json
RUNNING SCENARIO: cpp_protobuf_sync_streaming_qps_unconstrained_secure_500kib_resource_quota
I0206 18:50:35.041819075   20328 driver.cc:259]              Starting server on localhost:10000 (worker #0)
I0206 18:50:35.041957986   20328 ev_epoll_linux.c:93]        epoll engine will be using signal: 40
D0206 18:50:35.041971013   20328 ev_posix.c:107]             Using polling engine: epoll
I0206 18:50:35.045392636   20328 driver.cc:306]              Starting client on localhost:10010 (worker #1)
D0206 18:50:35.045445960   20328 driver.cc:322]              Client 0 gets 64 channels
I0206 18:50:35.418071823   20328 driver.cc:343]              Initiating
I0206 18:50:35.633121563   20328 driver.cc:364]              Warming up
I0206 18:50:40.633302545   20328 driver.cc:370]              Starting
I0206 18:50:40.644975517   20328 driver.cc:397]              Running
I0206 18:51:10.633300212   20328 driver.cc:411]              Finishing clients
I0206 18:51:10.643337228   20328 driver.cc:425]              Received final status from client 0
I0206 18:51:30.087466381   20328 driver.cc:457]              Finishing servers
I0206 18:51:30.087939647   20328 driver.cc:471]              Received final status from server 0
```

https://grpc-testing.appspot.com/job/gRPC_performance_pull_requests/9061/testReport/junit/(root)/benchmarks/qps_json_driver_cpp_protobuf_sync_streaming_qps_unconstrained_secure_500kib_resource_quota/

pr #9589 against master

**Comment by dgquintas** [comment] 2017-02-16 18:21
We should address this issue ASAP. It's been keeping the performance test red for a while.

**Comment by dgquintas** [comment] 2017-02-22 18:16
Duplicate of #9399

**Closed by dgquintas** 2017-02-22 18:16 UTC
Labels: benchmarking, P1
