### ISSUE TITLE
Comments from .proto file should appear in the code generated by grpc_objc_plugin

### ISSUE THREAD

**Issue by jtattermusch** [grpc/grpc#6344] opened 2016-04-28 15:42 UTC
This should be easily done when utilizing the GetComment methods added in #6181.

**Comment by jayantkolhe** [comment] 2016-06-08 18:09
We need to propogate comments from proto to generated Obj-C code and run Obj-C docgen of some kind on it.

**Comment by makdharma** [comment] 2016-06-08 22:11
PR https://github.com/grpc/grpc/pull/6841

**Comment by jcanizales** [comment] 2016-06-09 01:01
I think there's a duplicate of this issue somewhere.

**Closed** 2016-06-09 22:32 UTC
Labels: ObjC, P1, protoc plugins
