### ISSUE TITLE
(dbg, c, windows): Failure on tests.vsprojects/Debug/h2_compress_nosec_test.exe binary_metadata

### ISSUE THREAD

**Issue by vjpai** [grpc/grpc#6167] opened 2016-04-13 21:33 UTC
https://grpc-testing.appspot.com/job/gRPC_master/16439/config=dbg,language=c,platform=windows/testReport/junit/(root)/tests/vsprojects_Debug_h2_compress_nosec_test_exe_binary_metadata/

Error Message

Failure
Standard Output

D0413 02:55:21.489000000  7780 test_config.c:278] test slowdown: machine=1.000000 build=1.000000 total=1.000000
I0413 02:55:21.490000000  7780 binary_metadata.c:55] test_request_response_with_metadata_and_payload/chttp2/fullstack_compression
E0413 02:55:27.001000000  7780 cq_verifier.c:248] event not found: OP_COMPLETE: tag:00000001 OK
E0413 02:55:27.001000000  7780 cq_verifier.c:251] have tags: 00000065
Abort handler called.
*** 0: 00000000013B6EEF  - 0000000000000000
*** 1: 00000000013B73F7  - 0000000000000000
*** 2: 0000000001418279  - 0000000000000000
*** 3: 00000000014121A4  - 0000000000000000
*** 4: 0000000001482EF6  - 0000000000000000
*** 5: 00000000013F2A2D  - 0000000000000000
*** 6: 00000000013F32C0  - 0000000000000000
*** 7: 00000000013F09A7  - 0000000000000000
*** 8: 00000000013B134A  - 0000000000000000
*** 9: 000000000141250A  - 0000000000000000
*** 10: 000000000141265D  - 0000000000000000
*** 11: 0000000075C8338A BaseThreadInitThunk - 0000000075C83378
*** 12: 0000000077129A02 RtlInitializeExceptionChain - 000000007712999F
*** 13: 00000000771299D5 RtlInitializeExceptionChain - 000000007712999F

**Comment by stanley-cheung** [comment] 2016-04-14 15:59
Dupe of #5884?

**Comment by vjpai** [comment] 2016-04-15 14:35
Not a dup - this was on master, but #5884 was on portability master. Different platform.

**Closed** 2016-04-27 20:49 UTC
Labels: BUILDPONY, core, P1, Windows
