### ISSUE TITLE
tests.cloud_to_cloud:java:http2_server:rst_during_data  flake

### ISSUE THREAD

**Issue by jtattermusch** [grpc/grpc#11180] opened 2017-05-17 07:04 UTC
https://grpc-testing.appspot.com/job/gRPC_interop_pull_requests/14136/testReport/junit/(root)/tests/cloud_to_cloud_java_http2_server_rst_during_data/
Assertion error: operation timed out

Maybe just a one-off.

**Comment by ejona86** [comment] 2017-05-17 17:58
Duplicate of #10686

**Closed by ejona86** 2017-05-17 17:58 UTC
Labels: interop, Java
