### ISSUE TITLE
C++ non blocking server 

### ISSUE THREAD

**Issue by LuckyCloud** [grpc/grpc#2228] opened 2015-06-26 04:11 UTC
can grpc imp an c++ non blocking server 
the asyn server demo in grpc-common is bclocked at 
#0  0x00007ffff633c0d3 in poll () from /lib64/libc.so.6
#1  0x00007ffff77c1098 in ?? () from /usr/local/lib/libgrpc.so.0
#2  0x00007ffff77c0c6e in grpc_pollset_work () from /usr/local/lib/libgrpc.so.0
#3  0x00007ffff77ca765 in grpc_completion_queue_next () from /usr/local/lib/libgrpc.so.0
#4  0x00007ffff7bc51bd in grpc::CompletionQueue::AsyncNextInternal(void**, bool*, gpr_timespec) () from /usr/local/lib/libgrpc++_unsecure.so.0
#5  0x0000000000409d47 in grpc::CompletionQueue::Next(void**, bool*) ()
#6  0x000000000040a4f4 in ServerImpl::HandleRpcs() ()
#7  0x000000000040a0ae in ServerImpl::Run() ()
#8  0x0000000000409c6f in main ()

**Comment by ctiller** [comment] 2015-07-17 22:23
I think this is a duplicate of #2278

**Comment by ctiller** [comment] 2015-07-21 20:01
I no longer think this duplicates #2278

**Closed** 2015-08-24 20:37 UTC
Labels: c++, WIP
