### ISSUE TITLE
c_linux_opt_native.bins/opt/h2_oauth2_test high_initial_seqno GRPC_POLL_STRATEGY=epollsig

### ISSUE THREAD

**Issue by murgatroid99** [grpc/grpc#11169] opened 2017-05-16 22:17 UTC
https://grpc-testing.appspot.com/job/gRPC_master_linux/2399/testReport/junit/(root)/c_linux_opt_native/bins_opt_h2_oauth2_test_high_initial_seqno_GRPC_POLL_STRATEGY_epollsig/

```
D0515 07:46:04.150381381   13406 test_config.c:403]          test slowdown factor: sanitizer=1, fixture=1, poller=1, total=1
I0515 07:46:04.150502269   13406 ev_epollsig_linux.c:90]     epoll engine will be using signal: 40
D0515 07:46:04.150512889   13406 ev_posix.c:121]             Using polling engine: epollsig
D0515 07:46:04.150532129   13406 dns_resolver.c:316]         Using native dns resolver
I0515 07:46:04.150574501   13406 high_initial_seqno.c:57]    Running test: test_invoke_requests first_seqno=16777213/chttp2/simple_ssl_with_oauth2_fullstack
I0515 07:46:05.157509800   13406 high_initial_seqno.c:240]   Running test: Passed simple request 0
I0515 07:46:06.158841361   13406 high_initial_seqno.c:240]   Running test: Passed simple request 1
I0515 07:46:07.160260791   13406 high_initial_seqno.c:240]   Running test: Passed simple request 2
I0515 07:46:08.161649239   13406 high_initial_seqno.c:240]   Running test: Passed simple request 3
I0515 07:46:09.162435688   13406 high_initial_seqno.c:240]   Running test: Passed simple request 4
I0515 07:46:10.163843213   13406 high_initial_seqno.c:240]   Running test: Passed simple request 5
I0515 07:46:11.165172058   13406 high_initial_seqno.c:240]   Running test: Passed simple request 6
I0515 07:46:12.166587359   13406 high_initial_seqno.c:240]   Running test: Passed simple request 7
I0515 07:46:13.167990370   13406 high_initial_seqno.c:240]   Running test: Passed simple request 8
I0515 07:46:14.169422915   13406 high_initial_seqno.c:240]   Running test: Passed simple request 9
I0515 07:46:14.169935570   13406 high_initial_seqno.c:57]    Running test: test_invoke_requests first_seqno=2147483645/chttp2/simple_ssl_with_oauth2_fullstack
I0515 07:46:15.176679181   13406 high_initial_seqno.c:240]   Running test: Passed simple request 0
I0515 07:46:16.181414726   13406 high_initial_seqno.c:240]   Running test: Passed simple request 1
I0515 07:46:17.184846236   13406 high_initial_seqno.c:240]   Running test: Passed simple request 2
I0515 07:46:18.188243609   13406 high_initial_seqno.c:240]   Running test: Passed simple request 3
I0515 07:46:19.191865260   13406 high_initial_seqno.c:240]   Running test: Passed simple request 4
I0515 07:46:20.194395622   13406 high_initial_seqno.c:240]   Running test: Passed simple request 5
I0515 07:46:21.198380097   13406 high_initial_seqno.c:240]   Running test: Passed simple request 6
I0515 07:46:22.201963511   13406 high_initial_seqno.c:240]   Running test: Passed simple request 7
E0515 07:46:32.212241932   13406 cq_verifier.c:228]          no event received, but expected:
0x65 GRPC_OP_COMPLETE success=1 test/core/end2end/tests/high_initial_seqno.c:165




*******************************
Caught signal SIGABRT
bins/opt/h2_oauth2_test[0x54cbae]
/lib/x86_64-linux-gnu/libpthread.so.0(+0xf890)[0x7fe15993f890]
/lib/x86_64-linux-gnu/libc.so.6(gsignal+0x37)[0x7fe1595ba067]
/lib/x86_64-linux-gnu/libc.so.6(abort+0x148)[0x7fe1595bb448]
bins/opt/h2_oauth2_test[0x428c48]
bins/opt/h2_oauth2_test[0x411cf4]
bins/opt/h2_oauth2_test[0x40508e]
bins/opt/h2_oauth2_test[0x403838]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf5)[0x7fe1595a6b45]
bins/opt/h2_oauth2_test[0x403873]
Command terminated by signal 6
```

**Comment by yang-g** [comment] 2017-05-17 17:59
Duplicate of #10653

**Closed by yang-g** 2017-05-17 17:59 UTC
Labels: BUILDPONY, core
