### ISSUE TITLE
Set up and host gRPC API docs for beta in gh-pages branch for ObjC

### ISSUE THREAD

**Issue by hsaliak** [grpc/grpc#2853] opened 2015-08-07 22:58 UTC

**Comment by jcanizales** [comment] 2015-08-13 04:57
I think this is a duplicate of #2582.

**Comment by jcanizales** [comment] 2015-09-03 11:49
Notes:
* Use [appledoc](http://gentlebytes.com/appledoc/)'s style for formatting the comments.
* [Currently deployed docs](http://cocoadocs.org/docsets/gRPC/0.6.0/).
* [How to preview changes](http://cocoadocs.org/readme/#previewing-my-library-in-cocoadocs).

**Comment by jcanizales** [comment] 2015-10-19 19:47
Stubtasks:

- [ ] Script to convert comment style.
- [ ] Bash script to open the preview (with instructions to install).
- [ ] Change all .h files.
- [ ] Submit new minor version to Cocoapods.

**Closed** 2016-03-09 22:35 UTC
Labels: documentation, ObjC
