### ISSUE TITLE
Intermittent Stream Removed and Deadline Exceeded 

### ISSUE THREAD

**Issue by eranchetz** [grpc/grpc#23277] opened 2020-06-23 17:18 UTC
### What version of gRPC and what language are you using?
1.27.1  on python

### What operating system (Linux, Windows,...) and version?
GKE (COS) - Linux

### What runtime / compiler are you using (e.g. python version or version of gcc)
Python 3.6

### What did you do?
We are seeing intermittent "Stream removed" and "Deadline Exceeded" errors when connecting from one workload (pod) on a GKE Cluster to another GKE cluster, 

status = StatusCode.UNKNOWN
details = "Stream removed"
debug_error_string = "{"created":"@1588517609.045272010","description":"Error received from peer ipv4:<masked_ip_address>","file":"src/core/lib/surface/call.cc","file_line":1056,"grpc_message":"Stream removed","grpc_status":2}"

status = StatusCode.DEADLINE_EXCEEDED
details = "Deadline Exceeded"
debug_error_string = "{"created":"@1588517612.050181040","description":"Deadline Exceeded","file":"src/core/ext/filters/deadline/deadline_filter.cc","file_line":69,"grpc_status":4}"

### What did you expect to see?
Less errors, or a better way to understand why these error occur. 

### What did you see instead?
the errors above

### Anything else we should know about your project / environment?
1. DEADLINE_EXCEEDED error occurs when the client determines that the server is taking longer then the default timeout to process the request (in our case 3s and 10s in one service  and in another).
2. statistically 10% of client requests fail on the first try with DEADLINE_EXCEEDED, the majority of them succeeds upon retry (there is only 1 retry due to business logic).
3. Inspecting the server side, it seems that when a request fails with DEADLINE_EXCEEDED it didn't even got to the server in the first place - I suspect that the client failed to establish connection to the server.
4. We also enabled GRPC_VERBOSITY=info and debug but it wasn't helpful in any way. 

Let us know if you need any further or information on our side.

**Comment by lidizheng** [comment] 2020-07-07 17:03
@eranchetz `DEADLINE_EXCEEDED` here might caused by many factor. Can you post your log with `GRPC_VERBOSITY=debug GRPC_TRACE=all`?

**Comment by pradn** [comment] 2020-09-15 21:09
I have a customer that's seeing a very similar UNKNOWN/stream removed issue for a customer using Cloud PubSub's Python library. It's also on GKE, but with grpcio version 1.31.0. We've told the customer to try to catch the error and reset the subscriber; we can possibly get you more detailed logs if the customer is willing.

Their dependencies:
> google-api-core==1.22.1
google-api-python-client==1.10.0
google-auth==1.20.1
google-auth-httplib2==0.0.4
google-cloud==0.34.0
google-cloud-core==1.4.1
google-cloud-firestore==1.8.1
google-cloud-logging==1.15.1
google-cloud-monitoring==0.36.0
google-cloud-pubsub==1.7.0
google-cloud-secret-manager==1.0.0
google-cloud-storage==1.30.0
google-cloud-trace==0.24.0
google-crc32c==0.1.0
google-resumable-media==0.7.1
googleapis-common-protos==1.52.0
grpc-google-iam-v1==0.12.3
grpcio==1.31.0

Error:
> xtPayload: "ERROR:root:{'msg': 'Exiting with an exception', 'error': "Unknown('Stream removed')", 'stack_tracke': 'Traceback (most recent call last):\n File "/usr/local/lib/python3.8/site-packages/google/api_core/grpc_helpers.py", line 57, in error_remapped_callable\n return callable_(*args, **kwargs)\n File "/usr/local/lib/python3.8/site-packages/grpc/_channel.py", line 826, in __call__\n return _end_unary_response_blocking(state, call, False, None)\n File "/usr/local/lib/python3.8/site-packages/grpc/_channel.py", line 729, in _end_unary_response_blocking\n raise _InactiveRpcError(state)\ngrpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:\n\tstatus = StatusCode.UNKNOWN\n\tdetails = "Stream removed"\n\tdebug_error_string = "{"created":"@1598295328.810963156","description":"Error received from peer ipv4:74.125.69.95:443","file":"src/core/lib/surface/call.cc","file_line":1061,"grpc_message":"Stream removed","grpc_status":2}"\n>\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n File "/app/main.py", line 37, in main\n consume_messages(subscriber, subscription_path, ingest_recording)\n File "/app/app/consumer.py", line 41, in consume_messages\n subscriber.modify_ack_deadline(\n File "/usr/local/lib/python3.8/site-packages/google/cloud/pubsub_v1/_gapic.py", line 40, in <lambda>\n fx = lambda self, *a, **kw: wrapped_fx(self.api, *a, **kw) # noqa\n File "/usr/local/lib/python3.8/site-packages/google/cloud/pubsub_v1/gapic/subscriber_client.py", line 939, in modify_ack_deadline\n self._inner_api_calls["modify_ack_deadline"](\n File "/usr/local/lib/python3.8/site-packages/google/api_core/gapic_v1/method.py", line 145, in __call__\n return wrapped_func(*args, **kwargs)\n File "/usr/local/lib/python3.8/site-packages/google/api_core/retry.py", line 281, in retry_wrapped_func\n return retry_target(\n File "/usr/local/lib/python3.8/site-packages/google/api_core/retry.py", line 184, in retry_target\n return target()\n File "/usr/local/lib/python3.8/site-packages/google/api_core/timeout.py", line 214, in func_with_timeout\n return func(*args, **kwargs)\n File "/usr/local/lib/python3.8/site-packages/google/api_core/grpc_helpers.py", line 59, in error_remapped_callable\n six.raise_from(exceptions.from_grpc_error(exc), exc)\n File "<string>", line 3, in raise_from\ngoogle.api_core.exceptions.Unknown: None Stream removed\n'}

**Comment by lidizheng** [comment] 2020-09-15 23:07
@pradn For customer issues, can you use internal Bugnizer and assign to the gRPC component? If you think the error is caused by gRPC.

**Comment by lidizheng** [comment] 2021-08-05 16:50
@brianlieg Can you create a reproduce case? Each case might have quite different causes. The "Stream Removed" is likely to be caused by network issues, e.g., stream removed by the middle proxies. The "deadline exceed" can be caused by system network setups, proxies, backends.

**Comment by lidizheng** [comment] 2021-08-05 16:50
We recommend to upgrade to the latest release before further debugging.

**Comment by brianlieg** [comment] 2021-08-05 16:57
@lidizheng thank you for your feedback can you confirm the version of the latest and for which libraries?

**Comment by lidizheng** [comment] 2021-08-05 17:06
The latest gRPC Python release is https://github.com/grpc/grpc/releases/tag/v1.39.0. You can install it as `grpcio==1.39.0`.

**Comment by XuanWang-Amos** [comment] 2023-04-10 21:39
Since it's been more than two years, we're closing this issue, if this still happens with latest release, please file a new issue.

**Closed by XuanWang-Amos** 2023-04-10 21:39 UTC
Labels: kind/bug, area/core, lang/Python, priority/P2
