### ISSUE TITLE
grpc c++ ssl/tls with windows cert store

### ISSUE THREAD

**Issue by youyuanwu** [grpc/grpc#30114] opened 2022-06-27 05:54 UTC
Problem:
For most service running on windows in production, certificate with private key is stored in window cert store, and in most cases the private key of the certificate is not exportable. To use grpc with boringSSL/OpenSSL, we need to provide the private key of the cert, and this is not possible. Our service/app is in c++ running on windows, and this is preventing us to choose grpc as the rpc framework.

Feature ask:
We would like to use grpc c++ with windows cert store and native windows ssl functionalities.
libcurl can be compiled with openssl or windows sspi, and we wish grpc c++ can support the same. 

Our work around:
We are considering writing HTTPS server with protobuf payload, and by passing the grpc auth layer, or use plain https.

Some additional thoughts:
Maybe one can create a OpenSSL_PAL, that wraps around the windows sspi library and make it look like OpenSSL lib, and then compile with grpc c++. Similar to https://github.com/microsoft/WinHttpPAL, which makes libcurl looks like winhttp.

**Comment by drfloob** [comment] 2022-06-27 14:09
There have been a number of requests for this feature over the years, and unfortunately the gRPC team has not been able to prioritize this work. No open source developers have taken the initiative to contribute a satisfactory version yet (one that can pass a security review, and meets the project's coding standards), but we'd still welcome the attempt. Marking as a duplicate of https://github.com/grpc/grpc/issues/19962, though I could choose from many.

CC @ZhenLian

**Closed by drfloob** 2022-06-27 14:09 UTC
Labels: kind/enhancement, lang/c++, priority/P2, untriaged

**Comment by youyuanwu** [comment] 2022-06-27 18:07
If we were to contribute this feature, is there any guidance or suggestions? 
Right now, the code base is ingrained in openssl, not sure how to separate it. The PAL approach mentioned above maybe possible, but I think it will ultimately require some new windows specific grpc APIs exposed to accept "CERT_CONTEXT" input to the backend.
