### ISSUE TITLE
'Building wheel for grpcio-tools' on Alpine is extremely slow 

### ISSUE THREAD

**Issue by ghevge** [grpc/grpc#26620] opened 2021-07-07 12:49 UTC
I'm  seeing this extremely slow (at least 1/2 h just to build the wheels for grpcio-tools and grpcio) 'Building wheel for grpcio-tools' behavior, each time I'm rebuilding my container after changing something in the requirements. I'm on alpine 3.13 , python 3.9.5 and the latest pip available for this stack.

grpcio-tools=1.38.1

Is there any way of improving this behavior?

BTW I've tried to installed the precompiled linux cp39 wheels available here: https://pypi.org/project/grpcio-tools/1.38.1/#modal-close but none of them seems to work with my platform. I keep getting the error : '....whl is not a supported wheel on this platform. '

Thanks

**Comment by ghevge** [comment] 2021-07-07 15:56
It seems the alpine support is now available yet. WIP https://github.com/pypa/auditwheel/issues/305

**Comment by lidizheng** [comment] 2021-07-07 17:29
We are discussing this issue in https://github.com/grpc/grpc/issues/24344. If the problem is solved, feel free to close it.

**Comment by robertsben** [comment] 2021-09-24 15:30
It looks like musllinux support is now available, as of https://github.com/pypa/auditwheel/issues/327. Is there any intention for grpc to publish musllinux binary wheels now?

**Comment by lidizheng** [comment] 2021-09-24 16:58
Good to learn PyPA has added the musl wheel support. I think we should publish the musllinux wheels. https://www.python.org/dev/peps/pep-0656/

**Comment by rushilsrivastava** [comment] 2022-01-14 20:46
Would love to see this as well, following #28092

**Comment by rushilsrivastava** [comment] 2022-01-21 02:27
For anyone waiting on #28092, I published some prebuilt docker images available here: https://github.com/rushilsrivastava/python-grpcio-alpine-docker

**Comment by lidizheng** [comment] 2022-06-03 21:09
It's released since v1.44.x.

**Closed by lidizheng** 2022-06-03 21:09 UTC
Labels: kind/bug, lang/Python, priority/P2
