### ISSUE TITLE
(tsan / c++ / linux) tests.bins/tsan/qps_test

### ISSUE THREAD

**Issue by sreecha** [grpc/grpc#5509] opened 2016-03-01 16:53 UTC
https://grpc-testing.appspot.com/job/gRPC_master/15496/config=dbg,language=c++,platform=linux/

Recent builds where this failed:
https://grpc-testing.appspot.com/job/gRPC_master/15496
https://grpc-testing.appspot.com/job/gRPC_master/15492
https://grpc-testing.appspot.com/job/gRPC_master/15471
https://grpc-testing.appspot.com/job/gRPC_master/15463

**Comment by jtattermusch** [comment] 2016-03-15 17:36
Today qps_test has flaked under TSAN.
https://grpc-testing.appspot.com/job/gRPC_master/15811/config=tsan,language=c++,platform=linux/testReport/junit/(root)/tests/bins_tsan_qps_test/

```
FATAL: ThreadSanitizer CHECK failed: /tmp/buildd/llvm-toolchain-3.5-3.5/projects/compiler-rt/lib/sanitizer_common/sanitizer_stacktrace.cc:68 "((count)) < ((size))" (0x1, 0x1)
FATAL: ThreadSanitizer CHECK failed: /tmp/buildd/llvm-toolchain-3.5-3.5/projects/compiler-rt/lib/sanitizer_common/sanitizer_stacktrace.cc:68 "((count)) < ((size))" (0x1, 0x1)
FATAL: ThreadSanitizer CHECK failed: /tmp/buildd/llvm-toolchain-3.5-3.5/projects/compiler-rt/lib/sanitizer_common/sanitizer_stacktrace.cc:68 "((count)) < ((size))" (0x1, 0x1)
FATAL: ThreadSanitizer CHECK failed: /tmp/buildd/llvm-toolchain-3.5-3.5/projects/compiler-rt/lib/sanitizer_common/sanitizer_stacktrace.cc:68 "((count)) < ((size))" (0x1, 0x1)
FATAL: ThreadSanitizer CHECK failed: /tmp/buildd/llvm-toolchain-3.5-3.5/projects/compiler-rt/lib/sanitizer_common/sanitizer_stacktrace.cc:68 "((count)) < ((size))" (0x1, 0x1)
```

It that just a flake or something that might have been introduced by recent merges?

**Comment by ctiller** [comment] 2016-03-15 17:45
This is an outdated clang version. It may have been introduced by a recent
merge, it may be the weather.

We need to move our TSAN builds to a more recent clang (we'll likely want
to build from source).

**Comment by jtattermusch** [comment] 2016-03-15 17:56
Alright, I've seen this several times over last X builds. Almost definitely something we didn't have before.

Marking this as P0 as greeness it at stake.

CC @ctiller , @nicolasnoble

**Comment by jtattermusch** [comment] 2016-03-16 22:39
Seen many times today, e.g. (https://grpc-testing.appspot.com/job/gRPC_master/15850/config=tsan,language=c++,platform=linux/testReport/junit/(root)/tests/bins_tsan_qps_test/)

**Comment by jcanizales** [comment] 2016-03-18 05:21
Seen again today https://grpc-testing.appspot.com/job/gRPC_master/15855/config=tsan,language=c++,platform=linux/testReport/junit/(root)/tests/bins_tsan_qps_test/

**Comment by jcanizales** [comment] 2016-03-18 06:03
It's not really flaky though, it just fails consistently in all runs.

**Comment by soltanmm** [comment] 2016-03-18 21:32
Seen again as (consistently) failing:

https://grpc-testing.appspot.com/job/gRPC_master/15886/config=tsan,language=c++,platform=linux/testReport/junit/(root)/tests/bins_tsan_qps_test/
https://grpc-testing.appspot.com/job/gRPC_master/15887/config=tsan,language=c++,platform=linux/testReport/(root)/tests/bins_tsan_qps_test/
https://grpc-testing.appspot.com/job/gRPC_master/15888/config=tsan,language=c++,platform=linux/testReport/(root)/tests/bins_tsan_qps_test/
https://grpc-testing.appspot.com/job/gRPC_master/15889/config=tsan,language=c++,platform=linux/testReport/(root)/tests/bins_tsan_qps_test/
https://grpc-testing.appspot.com/job/gRPC_master/15890/config=tsan,language=c++,platform=linux/testReport/(root)/tests/bins_tsan_qps_test/
https://grpc-testing.appspot.com/job/gRPC_master/15891/config=tsan,language=c++,platform=linux/testReport/(root)/tests/bins_tsan_qps_test/
https://grpc-testing.appspot.com/job/gRPC_master/15893/config=tsan,language=c++,platform=linux/testReport/(root)/tests/bins_tsan_qps_test/
https://grpc-testing.appspot.com/job/gRPC_master/15894/config=tsan,language=c++,platform=linux/testReport/(root)/tests/bins_tsan_qps_test/
https://grpc-testing.appspot.com/job/gRPC_master/15895/config=tsan,language=c++,platform=linux/testReport/(root)/tests/bins_tsan_qps_test/
https://grpc-testing.appspot.com/job/gRPC_master/15897/config=tsan,language=c++,platform=linux/testReport/junit/(root)/tests/bins_tsan_qps_test/

**Comment by jtattermusch** [comment] 2016-03-18 21:38
@vjpai   this is failing most of our builds on master. Feel free to ask for help from anyone on the team if that would speed up fixing.

**Comment by vjpai** [comment] 2016-03-18 22:07
So, the issue is that updating tsan to unbreak this test ends up giving us
a more sensitive tsan that breaks 9 other tests. We need to resolve those.

**Comment by vjpai** [comment] 2016-03-18 22:08
And obviously, I want to fix those 9. It's just a question of when to do
it. Is it okay to have those 9 temporarily broken?

**Comment by soltanmm** [comment] 2016-03-18 22:18
I'm of the opinion that 'new' failures from more sensitive instruments aren't really 'new' at all. *casts vote*

**Comment by jtattermusch** [comment] 2016-03-18 22:19
Let's disable qps_test for now and file a P0 issue to re-enable it once we fix the 9 failing tests (and address those as P0 too, of course).

**Comment by jtattermusch** [comment] 2016-03-23 15:12
Seems fixed. Thanks!

**Closed by jtattermusch** 2016-03-23 15:12 UTC
Labels: BUILDPONY, c++, Linux, P0
