### ISSUE TITLE
gRPC PHP doesn't increment the extension version

### ISSUE THREAD

**Issue by michaelbausor** [grpc/grpc#10997] opened 2017-05-04 20:58 UTC
The extension version is here: https://github.com/grpc/grpc/blob/master/src/php/ext/grpc/php_grpc.h#L44

`phpversion('grpc')` returns 0.1.0

cc @stanley-cheung

**Comment by stanley-cheung** [comment] 2017-05-04 21:59
dupe of #10842

**Closed by stanley-cheung** 2017-05-04 21:59 UTC
