### ISSUE TITLE
Python Server Block at server.start()

### ISSUE THREAD

**Issue by Linerd** [grpc/grpc#11257] opened 2017-05-20 20:19 UTC
Please answer these questions before submitting your issue. 
 
### Should this be an issue in the gRPC issue tracker?
 
Create new issues for bugs and feature requests. An issue needs to be actionable. General gRPC discussions and usage questions belong to:
- [grpc.io mailing list](https://groups.google.com/forum/#!forum/grpc-io)
- [StackOverflow, with `grpc` tag](http://stackoverflow.com/questions/tagged/grpc)
 
*Please don't double post your questions in more locations, we are monitoring both channels and the time spent de-duplicating questions can is better spent answering more user questions.*
 
### What version of gRPC and what language are you using?
Python
 
### What operating system (Linux, Windows, …) and version?
Ubuntu 16.04 Linux 4.4.0-75-generic
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
Python 2.7.12
 
### What did you do?
If possible, provide a recipe for reproducing the error. Try being specific and include code snippets if helpful.

Wrote a simple Python grpc server that streams messages back and forth with a client.

### What did you expect to see?
The server starts after server.start() and enters the waiting loop 
 
### What did you see instead?
The start() function is blocked, when KeyboardInterrpu is raised, 
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/local/lib/python2.7/dist-packages/grpc/_server.py", line 673, in _serve
    event = state.completion_queue.poll()
  File "src/python/grpcio/grpc/_cython/_cygrpc/completion_queue.pyx.pxi", line 114, in grpc._cython.cygrpc.CompletionQueue.poll (src/python/grpcio/grpc/_cython/cygrpc.c:10482)
KeyboardInterrupt

After this exception the program moves on and the server is started.

Or, if a client connects to the server during the blocking, the server will also start correctly.

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

**Comment by nathanielmanistaatgoogle** [comment] 2017-05-20 20:51
What version of `grpcio` are you using? Please share with us your server code?

**Comment by Linerd** [comment] 2017-05-20 21:55
1.3.0

class XXServicer(xx_service_pb2_grpc.xxServicer):

    def __init__(self):
        self.is_active = True

    def GetCommand(self, request_iterator, context):
        metadata = dict(context.invocation_metadata())
        agentID = metadata['agentid']
        print('agent %s connected' % agentID)
        while self.is_active:
            for resp in request_iterator:
                print(resp)
            [some code that send msgs to the client]
            time.sleep(0.001)
        print('GetCommand() is closing...')

**Comment by nathanielmanistaatgoogle** [comment] 2017-05-22 00:18
Where's the rest of your code? Where's the part that calls [`grpc.Server.start`](http://www.grpc.io/grpc/python/grpc.html#grpc.Server.start)?

**Comment by Linerd** [comment] 2017-05-22 00:59
server = grpc.server(futures.ThreadPoolExecutor(max_workers=10))
xx_service_pb2_grpc.add_XXServicer_to_server(XXServicer(), server)
server.add_insecure_port('[::]:50050')
server.start()
print('Server started')

It's no different from the python example.

I think it has something to do with this issue https://github.com/gevent/gevent/issues/786, because I was trying to start the server within a green thread. If I run the same code in a standalone python app, all work fine.

I wonder if there is any workaround from GRPC side.

**Comment by nathanielmanistaatgoogle** [comment] 2017-05-22 01:17
Closing as a duplicate of [issue 4629](https://github.com/grpc/grpc/issues/4629).

Yes, [gRPC Python is not yet compatible with `gevent`](https://github.com/gevent/gevent/issues/786#issuecomment-203988312). gRPC Python's current implementation uses [`threading.Thread`](https://docs.python.org/3/library/threading.html#threading.Thread)s to make calls that block for significant durations and will interfere with any other code that relies on threads not doing that.

**Closed by nathanielmanistaatgoogle** 2017-05-22 01:17 UTC
Labels: python, requires reporter clarification
