### ISSUE TITLE
error: dereferencing pointer to incomplete type ‘RSA {aka struct rsa_st}’ rsa->n =

### ISSUE THREAD

**Issue by berli** [grpc/grpc#11416] opened 2017-06-06 08:54 UTC
I git the latest source code, compile them in Ubuntu 16.04
that got follow errors:

[MAKE] Generating cache.mk [C] Compiling src/core/lib/security/credentials/jwt/jwt_verifier.c src/core/lib/security/credentials/jwt/jwt_verifier.c: In function ‘pkey_from_jwk’: src/core/lib/security/credentials/jwt/jwt_verifier.c:498:10: error: dereferencing pointer to incomplete type ‘RSA {aka struct rsa_st}’ rsa->n = ^ Makefile:2526: recipe for target '/home/berli/grpc/objs/opt/src/core/lib/security/credentials/jwt/jwt_verifier.o' failed

I tried https://github.com/grpc/grpc/issues/8976 the instructions, but still
please help

**Comment by nicolasnoble** [comment] 2017-06-06 21:16
This is a duplicate of #8801 and #10589

**Comment by nathanielmanistaatgoogle** [comment] 2017-06-07 21:01
Closing as a duplicate of issues [8801](https://github.com/grpc/grpc/issues/8801) and [10589](https://github.com/grpc/grpc/issues/10589).

**Closed by nathanielmanistaatgoogle** 2017-06-07 21:01 UTC
Labels: build, c
