### ISSUE TITLE
FAILED: bins/opt/grpclb_test GRPC_POLL_STRATEGY=epollex

### ISSUE THREAD

**Issue by yang-g** [grpc/grpc#13081] opened 2017-10-20 04:52 UTC
I1020 00:02:15.341895184   29321 grpclb_test.cc:647]         Server[127.0.0.1:21945] shutting down
I1020 00:02:15.341950384   29325 grpclb_test.cc:334]         Server[127.0.0.1:21945] being torn down
I1020 00:02:15.342145633   29321 grpclb_test.cc:665]         Server[127.0.0.1:21945] bye bye
I1020 00:02:15.342156932   29321 grpclb_test.cc:647]         Server[127.0.0.1:6682] shutting down
I1020 00:02:15.342199037   29327 grpclb_test.cc:334]         Server[127.0.0.1:6682] being torn down
I1020 00:02:15.342302875   29321 grpclb_test.cc:665]         Server[127.0.0.1:6682] bye bye
I1020 00:02:15.342310597   29321 grpclb_test.cc:647]         Server[127.0.0.1:7702] shutting down
I1020 00:02:15.342364804   29329 grpclb_test.cc:334]         Server[127.0.0.1:7702] being torn down
E1020 00:02:20.348416979   29321 grpclb_test.cc:655]         assertion failed: grpc_completion_queue_pluck(shutdown_cq, tag(1000), grpc_timeout_seconds_to_deadline(5), NULL) .type == GRPC_OP_COMPLETE

*******************************
Caught signal SIGABRT
bins/opt/grpclb_test[0x554c6e]
/lib/x86_64-linux-gnu/libpthread.so.0(+0xf890)[0x7f8255f7e890]
/lib/x86_64-linux-gnu/libc.so.6(gsignal+0x37)[0x7f82551b6067]

**Comment by dgquintas** [comment] 2017-10-24 22:15
Duplicate of #13128

**Closed by dgquintas** 2017-10-24 22:15 UTC
Labels: infra/BUILDPONY
