### ISSUE TITLE
sanity checks fail for tools/distrib/python/check_grpcio_tools.py on a fresh docker 

### ISSUE THREAD

**Issue by dgquintas** [grpc/grpc#9677] opened 2017-02-11 00:11 UTC
```
$ ./tools/run_tests/run_tests.py -l sanity --use_docker
...
port server is up and ready

/var/local/git/grpc/tools/distrib/python/bazel_deps.sh: line 39: bazel: command not found
Traceback (most recent call last):
  File "tools/distrib/python/check_grpcio_tools.py", line 40, in <module>
    check_protoc_lib_deps_content = make.get_deps()
  File "/var/local/git/grpc/tools/distrib/python/make_grpcio_tools.py", line 119, in get_deps
    cc_files_output = bazel_query(BAZEL_DEPS_PROTOC_LIB_QUERY)
  File "/var/local/git/grpc/tools/distrib/python/make_grpcio_tools.py", line 113, in bazel_query
    output = subprocess.check_output([BAZEL_DEPS, query])
  File "/usr/lib/python2.7/subprocess.py", line 573, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command '['/var/local/git/grpc/tools/distrib/python/bazel_deps.sh', '//:protoc_lib']' returned non-zero exit status 127
FAILED: tools/distrib/python/check_grpcio_tools.py [ret=1, pid=1564]
```

@nicolasnoble FYI

**Comment by jtattermusch** [comment] 2017-02-22 15:31
I think I know what's causing this, just ran into that when trying to update third_party/protobuf to 3.2.0  (btw, the scripts around make_grpcio_tools.py are pretty messy).

Btw, it seems that there is some issue with protobuf's BUILD file in 3.2.0: https://github.com/google/protobuf/issues/2745

**Comment by dgquintas** [comment] 2017-02-22 17:53
ah, yes! I've found that doing a `git clean -xfd` on `third_party/protobuf` "fixes" it.

**Comment by mehrdada** [comment] 2017-11-17 22:26
https://github.com/grpc/grpc/issues/13404 was closed as a duplicate of this, which has been causing ongoing test failures for some reason.

**Comment by mehrdada** [comment] 2017-11-17 22:29
I changed my mind and decided to close as dupe of the other instead as the error message is slightly different in the newer, related bug.

**Closed by mehrdada** 2017-11-17 22:29 UTC
Labels: area/test, infra/BUILDPONY, lang/Python
