### ISSUE TITLE
DNS resolution failed / Failed to pick subchannel

### ISSUE THREAD

**Issue by ComptonAlvaro** [grpc/grpc#23273] opened 2020-06-23 10:48 UTC
No matter if the service is running or not, when I run the client and try to send a request to the service, I get the error DNS resolution failed / failed to pick subchannel.

The code of the service is this:

            const int port = yyyy;
            var keypair = new KeyCertificatePair(_clientCertificate, _clientPrivateKey);
            var sslCreds = new SslCredentials(_caCertificate, keypair);

            var channel = new Channel("https://x.x.x.x", port, sslCreds);

            var client = new Gestor.GestorClient(channel);
            return client;
The complete error that I have is:
{"Status(StatusCode=\"Unavailable\", Detail=\"DNS resolution failed\", DebugException=\"Grpc.Core.Internal.CoreErrorDetailException: {\"created\":\"@1592666370.497000000\",\"description\":\"Failed to pick subchannel\",\"file\":\"T:\\src\\github\\grpc\\workspace_csharp_ext_windows_x64\\src\\core\\ext\\filters\\client_channel\\client_channel.cc\",\"file_line\":3948,\"referenced_errors\":[{\"created\":\"@1592666370.497000000\",\"description\":\"Resolver transient failure\",\"file\":\"T:\\src\\github\\grpc\\workspace_csharp_ext_windows_x64\\src\\core\\ext\\filters\\client_channel\\resolving_lb_policy.cc\",\"file_line\":216,\"referenced_errors\":[{\"created\":\"@1592666370.497000000\",\"description\":\"DNS resolution failed\",\"file\":\"T:\\src\\github\\grpc\\workspace_csharp_ext_windows_x64\\src\\core\\ext\\filters\\client_channel\\resolver\\dns\\c_ares\\dns_resolver_ares.cc\",\"file_line\":375,\"grpc_status\":14,\"referenced_errors\":[{\"created\":\"@1592666370.497000000\",\"description\":\"C-ares status is not ARES_SUCCESS qtype=A name=https://x.x.x.x:yyyy is_balancer=0: Domain name not found\",\"file\":\"T:\\src\\github\\grpc\\workspace_csharp_ext_windows_x64\\src\\core\\ext\\filters\\client_channel\\resolver\\dns\\c_ares\\grpc_ares_wrapper.cc\",\"file_line\":287,\"referenced_errors\":[{\"created\":\"@1592666370.497000000\",\"description\":\"C-ares status is not ARES_SUCCESS qtype=AAAA name=https://x.x.x.x:yyyy is_balancer=0: Domain name not found\",\"file\":\"T:\\src\\github\\grpc\\workspace_csharp_ext_windows_x64\\src\\core\\ext\\filters\\client_channel\\resolver\\dns\\c_ares\\grpc_ares_wrapper.cc\",\"file_line\":287}]}]}]}]}\")"}

This is with the new version 2.30.0. preview1. But I get the same error with the version 2.29.x, but I get more details in the preview version.

Thanks.

EDIT: I get this error if I ise "x.x.x.x" as address instead of "https://x.x.x.x":

`"Status(StatusCode=\"Unavailable\", Detail=\"Empty update\", DebugException=\"Grpc.Core.Internal.CoreErrorDetailException: {\"created\":\"@1592937202.525000000\",\"description\":\"Failed to pick subchannel\",\"file\":\"T:\\src\\github\\grpc\\workspace_csharp_ext_windows_x64\\src\\core\\ext\\filters\\client_channel\\client_channel.cc\",\"file_line\":3948,\"referenced_errors\":[{\"created\":\"@1592937202.525000000\",\"description\":\"Empty update\",\"file\":\"T:\\src\\github\\grpc\\workspace_csharp_ext_windows_x64\\src\\core\\ext\\filters\\client_channel\\lb_policy\\pick_first\\pick_first.cc\",\"file_line\":200,\"grpc_status\":14}]}\")"`

**Comment by apolcyn** [comment] 2020-06-23 17:59
Why is `https://` being used as a prefix?

@ComptonAlvaro did you ever see this work before, making this a regression? Or has this never worked?

**Comment by ComptonAlvaro** [comment] 2020-06-23 18:06
@apolcyn Sorrry, I didn't understand. is it not needed to use https://? I thought it is needed to know if I want to connect with TLS or without TLS, in which cases I would choose http://

I have never been able to connect to the service. It is my first try with gRPC.

**Comment by apolcyn** [comment] 2020-06-23 18:09
The use of `SslCredentials` here is going to configure the channel to use secure connections.

In general, gRPC channels configure security via constructing them with the proper "channel credentials" object. The "scheme" isn't used to configure plaintext or secure...

**Comment by ComptonAlvaro** [comment] 2020-06-23 18:10
Then don't I have to use https:// in the address? I just have to set the IP?

**Comment by apolcyn** [comment] 2020-06-23 18:18
That's correct

**Comment by ComptonAlvaro** [comment] 2020-06-23 18:36
If I use only the IP I get the error that I indicate in the original post.

**Comment by apolcyn** [comment] 2020-06-23 18:42
> If I use only the IP I get the error that I indicate in the original post.

That's definitely unexpected.

So to be sure, you are creating the channel like this:

`var channel = new Channel("x.x.x.x", port, sslCreds);`

?

where "x.x.x.x" is a valid IPv4 address?

**Comment by ComptonAlvaro** [comment] 2020-06-23 18:44
I am creating my channel in this way:

`            var channel = new Channel("x.x.x.x", port, sslCreds);
            var client = new Service.ServiceClient(channel);`

**Comment by apolcyn** [comment] 2020-06-23 18:45
Can you please run this under these environment variables:

`GRPC_VERBOSITY=DEBUG`
`GRPC_TRACE=cares_resolver,cares_address_sorting`

and share the output? That will print some useful extra debug info.

**Comment by ComptonAlvaro** [comment] 2020-06-23 18:47
do I have to set the in this way?

`            Environment.SetEnvironmentVariable("GRPC_VERBOSITY", "DEBUG");
            Environment.SetEnvironmentVariable("GRPC_TRACE", "api,cares_resolver,cares_address_sorting");`

**Comment by apolcyn** [comment] 2020-06-23 18:48
That's one way to set it, yes (those environment variables must be set before you using the gRPC library, though).

**Comment by ComptonAlvaro** [comment] 2020-06-23 18:49
I am setting it before the creation of the channel, but the exception gives the same message.

**Comment by apolcyn** [comment] 2020-06-23 18:51
I don't expect the exception message to change. There should be a bunch of log messages printed out by the gRPC library to "stderr", though. Can you please share the logs to "stderr" here?

**Comment by ComptonAlvaro** [comment] 2020-06-23 18:52
How could I see the stderr? My client is a WPF Core application with one button that send a hello request to the service.

**Comment by apolcyn** [comment] 2020-06-23 19:01
I'm a little unfamiliar with how to capture these logs specifically in a WPF Core application - maybe https://stackoverflow.com/questions/160587/no-output-to-console-from-a-wpf-application is useful?

cc @jtattermusch  - Jan, do you have a simple suggested way to capture trace logs here?

**Comment by ComptonAlvaro** [comment] 2020-06-23 19:02
Thank, I will see and I will cpture the logs in WPF. When I have the results, I will share here.

**Comment by apolcyn** [comment] 2020-06-23 19:03
Realized this may be a known issue (https://github.com/grpc/grpc/issues/19233) -- the logs will still be helpful if you can get them though

**Comment by ComptonAlvaro** [comment] 2020-06-24 07:31
The output is this:

`D0624 09:29:01.073692 Grpc.Core.Internal.NativeExtension gRPC native library loaded successfully.
D0624 09:29:01.076629 0 T:\src\github\grpc\workspace_csharp_ext_windows_x64\src\core\ext\filters\client_channel\lb_policy_registry.cc:39: registering LB policy factory for "grpclb"
D0624 09:29:01.076735 0 T:\src\github\grpc\workspace_csharp_ext_windows_x64\src\core\ext\filters\client_channel\lb_policy_registry.cc:39: registering LB policy factory for "cds_experimental"
D0624 09:29:01.077022 0 T:\src\github\grpc\workspace_csharp_ext_windows_x64\src\core\ext\filters\client_channel\lb_policy_registry.cc:39: registering LB policy factory for "eds_experimental"
D0624 09:29:01.077306 0 T:\src\github\grpc\workspace_csharp_ext_windows_x64\src\core\ext\filters\client_channel\lb_policy_registry.cc:39: registering LB policy factory for "lrs_experimental"
D0624 09:29:01.077616 0 T:\src\github\grpc\workspace_csharp_ext_windows_x64\src\core\ext\filters\client_channel\lb_policy_registry.cc:39: registering LB policy factory for "priority_experimental"
D0624 09:29:01.077904 0 T:\src\github\grpc\workspace_csharp_ext_windows_x64\src\core\ext\filters\client_channel\lb_policy_registry.cc:39: registering LB policy factory for "weighted_target_experimental"
D0624 09:29:01.078186 0 T:\src\github\grpc\workspace_csharp_ext_windows_x64\src\core\ext\filters\client_channel\lb_policy_registry.cc:39: registering LB policy factory for "xds_routing_experimental"
D0624 09:29:01.078489 0 T:\src\github\grpc\workspace_csharp_ext_windows_x64\src\core\ext\filters\client_channel\lb_policy_registry.cc:39: registering LB policy factory for "pick_first"
D0624 09:29:01.078775 0 T:\src\github\grpc\workspace_csharp_ext_windows_x64\src\core\ext\filters\client_channel\lb_policy_registry.cc:39: registering LB policy factory for "round_robin"
D0624 09:29:01.079065 0 T:\src\github\grpc\workspace_csharp_ext_windows_x64\src\core\ext\filters\client_channel\resolver\dns\c_ares\dns_resolver_ares.cc:504: Using ares dns resolver
E0624 09:29:01.102737 0 T:\src\github\grpc\workspace_csharp_ext_windows_x64\src\core\tsi\ssl_transport_security.cc:793: Invalid cert chain file.
E0624 09:29:01.102916 0 T:\src\github\grpc\workspace_csharp_ext_windows_x64\src\core\lib\security\security_connector\ssl\ssl_security_connector.cc:114: Handshaker factory creation failed with TSI_INVALID_ARGUMENT.
E0624 09:29:01.103658 0 T:\src\github\grpc\workspace_csharp_ext_windows_x64\src\core\ext\transport\chttp2\client\secure\secure_channel_create.cc:132: Failed to create secure subchannel for secure name 'x.x.x.x:yyyy'
E0624 09:29:01.104377 0 T:\src\github\grpc\workspace_csharp_ext_windows_x64\src\core\ext\transport\chttp2\client\secure\secure_channel_create.cc:50: Failed to create channel args during subchannel creation.`

**Comment by ComptonAlvaro** [comment] 2020-06-26 07:36
Sorry, the last message has a problem because of certificate. It said that the problem is with a certificate, it was because I was using private cert as public key. I correct the problem and the error is this:

`D0626 09:33:50.610088 Grpc.Core.Internal.UnmanagedLibrary Attempting to load native library "D:\Datos\Alvaro\programacion\proyectos\GestorAplicaciones\gRPC\GestorAplicaciones\GestorAplicaciones.Client.ConsoleCore\bin\Debug\netcoreapp3.1\runtimes/win/native\grpc_csharp_ext.x64.dll"
D0626 09:33:50.640945 Grpc.Core.Internal.NativeExtension gRPC native library loaded successfully.
D0626 09:33:50.643019 0 T:\src\github\grpc\workspace_csharp_ext_windows_x64\src\core\ext\filters\client_channel\lb_policy_registry.cc:39: registering LB policy factory for "grpclb"
D0626 09:33:50.643123 0 T:\src\github\grpc\workspace_csharp_ext_windows_x64\src\core\ext\filters\client_channel\lb_policy_registry.cc:39: registering LB policy factory for "cds_experimental"
D0626 09:33:50.643173 0 T:\src\github\grpc\workspace_csharp_ext_windows_x64\src\core\ext\filters\client_channel\lb_policy_registry.cc:39: registering LB policy factory for "eds_experimental"
D0626 09:33:50.643220 0 T:\src\github\grpc\workspace_csharp_ext_windows_x64\src\core\ext\filters\client_channel\lb_policy_registry.cc:39: registering LB policy factory for "lrs_experimental"
D0626 09:33:50.643270 0 T:\src\github\grpc\workspace_csharp_ext_windows_x64\src\core\ext\filters\client_channel\lb_policy_registry.cc:39: registering LB policy factory for "priority_experimental"
D0626 09:33:50.643319 0 T:\src\github\grpc\workspace_csharp_ext_windows_x64\src\core\ext\filters\client_channel\lb_policy_registry.cc:39: registering LB policy factory for "weighted_target_experimental"
D0626 09:33:50.643368 0 T:\src\github\grpc\workspace_csharp_ext_windows_x64\src\core\ext\filters\client_channel\lb_policy_registry.cc:39: registering LB policy factory for "xds_routing_experimental"
D0626 09:33:50.643420 0 T:\src\github\grpc\workspace_csharp_ext_windows_x64\src\core\ext\filters\client_channel\lb_policy_registry.cc:39: registering LB policy factory for "pick_first"
D0626 09:33:50.643469 0 T:\src\github\grpc\workspace_csharp_ext_windows_x64\src\core\ext\filters\client_channel\lb_policy_registry.cc:39: registering LB policy factory for "round_robin"
D0626 09:33:50.643523 0 T:\src\github\grpc\workspace_csharp_ext_windows_x64\src\core\ext\filters\client_channel\resolver\dns\c_ares\dns_resolver_ares.cc:504: Using ares dns resolver
I0626 09:33:52.769486 0 T:\src\github\grpc\workspace_csharp_ext_windows_x64\src\core\ext\filters\client_channel\subchannel.cc:1033: Connect failed: {"created":"@1593156832.768000000","description":"OS Error","file":"T:\src\github\grpc\workspace_csharp_ext_windows_x64\src\core\lib\iomgr\tcp_client_windows.cc","file_line":105,"os_error":"Unable to retrieve error string","syscall":"ConnectEx","wsa_error":10061}
I0626 09:33:52.770141 0 T:\src\github\grpc\workspace_csharp_ext_windows_x64\src\core\ext\filters\client_channel\subchannel.cc:970: Subchannel 000001D3AF43AF60: Retry immediately
I0626 09:33:52.770296 0 T:\src\github\grpc\workspace_csharp_ext_windows_x64\src\core\ext\filters\client_channel\subchannel.cc:997: Failed to connect to channel, retrying`

**Comment by ComptonAlvaro** [comment] 2020-06-26 07:39
If I use localhost as address I get  this error:

`D0626 09:38:57.154635 Grpc.Core.Internal.UnmanagedLibrary Attempting to load native library "D:\Datos\Alvaro\programacion\proyectos\GestorAplicaciones\gRPC\GestorAplicaciones\GestorAplicaciones.Client.ConsoleCore\bin\Debug\netcoreapp3.1\runtimes/win/native\grpc_csharp_ext.x64.dll"
D0626 09:38:57.186418 Grpc.Core.Internal.NativeExtension gRPC native library loaded successfully.
D0626 09:38:57.188430 0 T:\src\github\grpc\workspace_csharp_ext_windows_x64\src\core\ext\filters\client_channel\lb_policy_registry.cc:39: registering LB policy factory for "grpclb"
D0626 09:38:57.188547 0 T:\src\github\grpc\workspace_csharp_ext_windows_x64\src\core\ext\filters\client_channel\lb_policy_registry.cc:39: registering LB policy factory for "cds_experimental"
D0626 09:38:57.188606 0 T:\src\github\grpc\workspace_csharp_ext_windows_x64\src\core\ext\filters\client_channel\lb_policy_registry.cc:39: registering LB policy factory for "eds_experimental"
D0626 09:38:57.188669 0 T:\src\github\grpc\workspace_csharp_ext_windows_x64\src\core\ext\filters\client_channel\lb_policy_registry.cc:39: registering LB policy factory for "lrs_experimental"
D0626 09:38:57.188735 0 T:\src\github\grpc\workspace_csharp_ext_windows_x64\src\core\ext\filters\client_channel\lb_policy_registry.cc:39: registering LB policy factory for "priority_experimental"
D0626 09:38:57.188797 0 T:\src\github\grpc\workspace_csharp_ext_windows_x64\src\core\ext\filters\client_channel\lb_policy_registry.cc:39: registering LB policy factory for "weighted_target_experimental"
D0626 09:38:57.188868 0 T:\src\github\grpc\workspace_csharp_ext_windows_x64\src\core\ext\filters\client_channel\lb_policy_registry.cc:39: registering LB policy factory for "xds_routing_experimental"
D0626 09:38:57.188935 0 T:\src\github\grpc\workspace_csharp_ext_windows_x64\src\core\ext\filters\client_channel\lb_policy_registry.cc:39: registering LB policy factory for "pick_first"
D0626 09:38:57.189002 0 T:\src\github\grpc\workspace_csharp_ext_windows_x64\src\core\ext\filters\client_channel\lb_policy_registry.cc:39: registering LB policy factory for "round_robin"
D0626 09:38:57.189074 0 T:\src\github\grpc\workspace_csharp_ext_windows_x64\src\core\ext\filters\client_channel\resolver\dns\c_ares\dns_resolver_ares.cc:504: Using ares dns resolver
E0626 09:38:57.301401 0 T:\src\github\grpc\workspace_csharp_ext_windows_x64\src\core\tsi\ssl_transport_security.cc:1395: Handshake failed with fatal error SSL_ERROR_SSL: error:1000007d:SSL routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED.
D0626 09:38:57.301915 0 T:\src\github\grpc\workspace_csharp_ext_windows_x64\src\core\lib\security\transport\security_handshaker.cc:184: Security handshake failed: {"created":"@1593157137.301000000","description":"Handshake failed","file":"T:\src\github\grpc\workspace_csharp_ext_windows_x64\src\core\lib\security\transport\security_handshaker.cc","file_line":307,"tsi_code":10,"tsi_error":"TSI_PROTOCOL_FAILURE"}
I0626 09:38:57.302540 0 T:\src\github\grpc\workspace_csharp_ext_windows_x64\src\core\ext\filters\client_channel\subchannel.cc:1033: Connect failed: {"created":"@1593157137.301000000","description":"Handshake failed","file":"T:\src\github\grpc\workspace_csharp_ext_windows_x64\src\core\lib\security\transport\security_handshaker.cc","file_line":307,"tsi_code":10,"tsi_error":"TSI_PROTOCOL_FAILURE"}
E0626 09:38:57.305271 0 T:\src\github\grpc\workspace_csharp_ext_windows_x64\src\core\tsi\ssl_transport_security.cc:1395: Handshake failed with fatal error SSL_ERROR_SSL: error:1000007d:SSL routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED.
D0626 09:38:57.305488 0 T:\src\github\grpc\workspace_csharp_ext_windows_x64\src\core\lib\security\transport\security_handshaker.cc:184: Security handshake failed: {"created":"@1593157137.305000000","description":"Handshake failed","file":"T:\src\github\grpc\workspace_csharp_ext_windows_x64\src\core\lib\security\transport\security_handshaker.cc","file_line":307,"tsi_code":10,"tsi_error":"TSI_PROTOCOL_FAILURE"}
I0626 09:38:57.306568 0 T:\src\github\grpc\workspace_csharp_ext_windows_x64\src\core\ext\filters\client_channel\subchannel.cc:1033: Connect failed: {"created":"@1593157137.305000000","description":"Handshake failed","file":"T:\src\github\grpc\workspace_csharp_ext_windows_x64\src\core\lib\security\transport\security_handshaker.cc","file_line":307,"tsi_code":10,"tsi_error":"TSI_PROTOCOL_FAILURE"}
I0626 09:38:57.307056 0 T:\src\github\grpc\workspace_csharp_ext_windows_x64\src\core\ext\filters\client_channel\subchannel.cc:972: Subchannel 0000016EF0C31490: Retry in 935 milliseconds`

**Comment by JACKCHEN96** [comment] 2020-07-24 07:47
Hi, how did you fix this bug then?

**Comment by ComptonAlvaro** [comment] 2020-07-29 10:24
The problem to DNS failed it is not to use HTPPS//, just I have to use the IP, "x.x.x.x".

**Comment by apolcyn** [comment] 2020-07-29 16:47
@ComptonAlvaro re the CERTIFICATE_VERIFY errors when you used localhost, I think https://github.com/grpc/grpc/blob/70f001565b7116638749c30072484bba30b3c244/include/grpc/impl/codegen/grpc_types.h#L271 is likely relevant. When using localhost, you probably need to override the server name used for secure name checking, using that option.

Closing since the DNS issue seems resolved.

**Closed by apolcyn** 2020-07-29 16:47 UTC
Labels: area/core, kind/bug, lang/core, priority/P2
