### ISSUE TITLE
c++_linux_dbg.bins/dbg/json_run_localhost

### ISSUE THREAD

**Issue by soltanmm-google** [grpc/grpc#9148] opened 2016-12-16 22:00 UTC
https://grpc-testing.appspot.com/job/gRPC_pull_requests_linux/1449/testReport/junit/(root)/c++_linux_dbg/bins_dbg_json_run_localhost___scenarios_json____scenarios______name____cpp_protobuf_async_client_sync_server_streaming_qps_unconstrained_secure____warmup_seconds___0___benchmark_seconds___1___num_servers___1___server_config_____async_server_threads___0___core_limit___0___security_params_____use_test_ca___true___server_host_override____foo_test_google_fr_____server_type____SYNC_SERVER_____num_clients___0___client_config_____client_type____ASYNC_CLIENT____security_params_____use_test_ca___true___server_host_override____foo_test_google_fr_____payload_config_____simple_params_____resp_size___0___req_size___0_____client_channels___64___async_client_threads___0___outstanding_rpcs_per_channel___100___rpc_type____STREAMING____load_params_____closed_loop_________histogram_params_____max_possible___60000000000_0___resolution___0_01_______GRPC_POLL_STRATEGY_poll_cv/

**Comment by dgquintas** [comment] 2016-12-16 22:05
Duplicate of #9007

**Closed by dgquintas** 2016-12-16 22:05 UTC
Labels: BUILDPONY, c++
