### ISSUE TITLE
using grpc with a proxy server

### ISSUE THREAD

**Issue by InnovistaLucia** [grpc/grpc#12815] opened 2017-10-04 07:27 UTC
I wrote an issue in the google.cloud.speech github repository, and was redirected to this repository because there seems to be a problem with grpc framework when working in an intranet communicating through a proxy server (#https://github.com/GoogleCloudPlatform/google-cloud-dotnet/issues/1504).

The environment is a x84 .NET Application running on a windows server 2016 OS (but it can also be reproduced on other Windows OS like Windows 7 and Windows Server 2008 R2).
The issue was tested with the .net libraries of Google.Cloud.Speech.V1 (Version 1.0.0.0) relying (among others) on the Google.Api.Gax.Grpc.dll (Version 2.1.0.0) and this on Grpc.Core.dll / Grpc.Auth.dll (both Version 1.6.1.0).

Tracking the network traffic shows that all requests that are using normal REST technologies work well respecting the process Proxy settings but the communication that is using the grpc component fails.
It seems that he grpc requests are ignoring the Proxy setting (i'm using the static setting for the .NET process: System.Net.WebRequest.DefaultWebProxy).
The google SpeechClient (and maybe all APIs relying on grpc) wont work ignoring this setting. Is there a workaround? Tried to use some grpc known environment-variables ("http_proxy", "https_proxy"...) but without success.

**Comment by apolcyn** [comment] 2017-10-10 23:50
I am not completely sure what is meant here. IIC `System.Net.WebRequest.DefaultWebProxy` only affects code that is using [WebRequest](https://msdn.microsoft.com/en-us/library/system.net.webrequest(v=vs.110).aspx)?

**Comment by InnovistaLucia** [comment] 2017-10-11 06:32
Thanks, for your answer. You are right: the DefaultWebProxy setting only affects "normal" WebRequests and as far as i understand, grpc uses an alternative way of HTTP 2 communication over tcp.
I just mentioned the setting for comparision.
In my opinion the .NET Wrapper assemblies of grpc (Grpc.Core.dll) are responsible to either
1. respect Proxy Settings given in the .NET Environment of the process (like the System.Net.WebRequest.DefaultWebProxy)
OR
2. respect proxy Settings given in the operation system (in Windows Client OS, the IE Proxy settings)
OR
3. make it in any way possible to set the proxy for grpc requests (over Environment Variables or whatever)

Since the other derivates of grpc (Java or Node.js f.e.) are able to work with a proxy environment, i assume that this is a Bug in the .NET Wrapper.
Protecting your communication in an intranet with a pass throug proxy server is a standard infrastructure in companies. I dont know why this problem with the .NET wrapper doesnt offend more people using this framework.

**Comment by fhoek** [comment] 2017-10-18 12:33
I can confirm this problem also exists in communication we tried with Google.Cloud.PubSub.V1 nuget package which uses Grpc.Core version 1.6.1. I've tried adding the environment variable **http_proxy** but with no success (got it from [here](https://github.com/grpc/grpc/issues/9989)). 

This is a big issue for us since we designed our solution around a few google cloud services like Pub/Sub and we can't run it in the customer's environment right now without adjusting the firewall.

**Comment by fhoek** [comment] 2017-12-06 08:39
This items can be closed. I've tested it again after #13323 was linked to this issue and it works. My earlier mistake was that I did not put an URI in the environment variable but simply <server>:<port>. Any non-URI value will be silently ignored. Once I changed it to <scheme><server>:<port> (eg. http://foo.bar:8080) it worked like a charm on .NET 45 Full Framework.

**Comment by apolcyn** [comment] 2018-05-15 23:27
closing per the last comment here.

**Closed by apolcyn** 2018-05-15 23:27 UTC
Labels: lang/C#
