### ISSUE TITLE
python client not responding to non-ok error code returned by server

### ISSUE THREAD

**Issue by fangweili** [grpc/grpc#7743] opened 2016-08-15 23:56 UTC
The setting:
1. Synchronous C++ gRPC [server](https://github.com/tensorflow/serving/blob/master/tensorflow_serving/model_servers/main.cc) built against gRPC (with bazel) @39650266
2. Synchronous Python gRPC client using pip installed gRPC (tried 0.13/0.15/1.0rc2)

The problem:
When server returns [non-ok code](https://github.com/tensorflow/serving/blob/master/tensorflow_serving/model_servers/main.cc#L144) in handler implementation, client gets stuck until timeout (as if response is not received from server).

**Comment by kpayson64** [comment] 2016-08-16 01:35
I verified that we see the proper behavior with a python client and c++ server sending a non-ok status using our interop setup:
https://github.com/grpc/grpc/blob/master/doc/interop-test-descriptions.md#status_code_and_message

Can you include your client side code?

**Comment by fangweili** [comment] 2016-08-16 16:37
The client code is currently part of a simple integration [test](https://github.com/tensorflow/serving/blob/master/tensorflow_serving/model_servers/tensorflow_model_server_test.py#L96), using manually generated [stub](https://github.com/tensorflow/serving/blob/master/tensorflow_serving/apis/prediction_service_pb2.py).

**Comment by kpayson64** [comment] 2016-08-17 23:49
What status code is causing the problem specifically?

Also, could you give the trace for a single gRPC call from both the client and server side?

You can get traces by running with the following environment variable:
```GRPC_TRACE='api'```

**Comment by nathanielmanistaatgoogle** [comment] 2016-08-18 00:03
Your Python code looks fine; I don't see any obvious causes of trouble and your problem doesn't correspond to any known defects.

1. Is the Python client the only client you've written? If you write the client in another language and run it against the same server, do you see the same problem?
2. How certain are you that you've observed the problem with `grpcio` 0.13.x, 0.15.x, and 1.0.0rc2? With what version of `pip` are you installing `grpcio`? Might I trouble you to use `pip freeze` to verify that each version you expect to be installed at each stage of your investigation is actually installed? We believe that you will have to pass `--pre` to `pip` to install 1.0.0rc2.
3. Do you see the same problem if you make an asynchronous call and then block on the result (change `result = stub.Predict(request, 5.0)` to `result = stub.Predict.future(request, 5.0).result()`)?

Some unlikely-to-matter cosmetic things I noticed:

1. It looks like you generated your code using a 0.14-or-earlier version of the code generator. Consider rerunning the code generator with the latest (also 1.0.0rc2) version of [`grpcio-tools`](https://pypi.python.org/pypi/grpcio-tools)? If you do rerun the code generator, you'll get two additional classes and one additional function allowing you to upgrade from the Beta API to the GA API. There are no known bugs with the Beta API, but you may prefer to see your code without the word "beta" on every other line.
2. On line ninety-eight, would that be better as `self.assertIn('y', result.outputs)`? Would the last two lines of `VerifyPredictRequest` be better as `self.assertSequenceEqual((3.0,), result.outputs['y'].float_val)`?

**Comment by a11r** [comment] 2016-08-25 04:44
Are we ready to close this as not reproducible ?

**Comment by nathanielmanistaatgoogle** [comment] 2016-08-25 15:09
@a11r: no.

**Comment by nathanielmanistaatgoogle** [comment] 2016-08-30 19:32
Resolving after working offline with @fangweili: the problem was that the server was generating a much-too-large status details string.

**Closed by nathanielmanistaatgoogle** 2016-08-30 19:32 UTC
Labels: c++, python
