### ISSUE TITLE
TIMEOUT: bm_fullstack_streaming_pump BM_PumpStreamServerToClient

### ISSUE THREAD

**Issue by markdroth** [grpc/grpc#21961] opened 2020-02-10 15:29 UTC
https://source.cloud.google.com/results/invocations/94aef143-44c9-46a3-a3bd-16d864ff76b7/targets/grpc%2Fcore%2Fpull_request%2Flinux%2Fgrpc_microbenchmark_diff/log

```
2020-02-05 00:42:21,173 TIMEOUT: bm_fullstack_streaming_pump BM_PumpStreamServerToClient<MinSockPair>/0 counters new 2/10 [pid=12072, time=3605.1sec]
```

```
2020-02-05 00:46:21,179 TIMEOUT: bm_fullstack_streaming_pump BM_PumpStreamServerToClient<SockPair>/0 counters new 1/10 [pid=4476, time=3605.7sec]
```

```
2020-02-05 01:23:31,229 TIMEOUT: bm_fullstack_streaming_pump BM_PumpStreamServerToClient<SockPair>/0 counters old 3/10 [pid=20604, time=3605.1sec]
```

**Comment by gnossen** [comment] 2020-02-25 20:21
This is currently the #2 flakiest test in the repo. @jtattermusch do you have bandwidth to look at this?

**Comment by jtattermusch** [comment] 2020-02-26 05:52
Dupe of https://github.com/grpc/grpc/issues/22055.

**Closed by jtattermusch** 2020-02-26 05:52 UTC
Labels: infra/BUILDPONY, kind/bug, lang/c++, priority/P1
