### ISSUE TITLE
FAILED: bins/dbg/end2end_test --gtest_filter=ProxyEnd2end/ProxyEnd2endTest.Peer/0  GRPC_POLL_STRATEGY=epoll

### ISSUE THREAD

**Issue by muxi** [grpc/grpc#10128] opened 2017-03-13 17:00 UTC
Happened in https://grpc-testing.appspot.com/job/gRPC_pull_requests_linux/3459/consoleFull
```
2017-03-13 03:07:00,550 D0313 03:06:59.763874795    4381 test_config.c:393]          test slowdown factor: sanitizer=1, fixture=1, poller=1, total=1
I0313 03:06:59.764167068    4381 ev_epoll_linux.c:93]        epoll engine will be using signal: 40
D0313 03:06:59.764197727    4381 ev_posix.c:107]             Using polling engine: epoll
D0313 03:06:59.764424639    4381 ev_posix.c:107]             Using polling engine: epoll
D0313 03:06:59.764539539    4381 ev_posix.c:107]             Using polling engine: epoll
D0313 03:06:59.764688367    4381 ev_posix.c:107]             Using polling engine: epoll
D0313 03:06:59.764814527    4381 ev_posix.c:107]             Using polling engine: epoll
D0313 03:06:59.764914837    4381 ev_posix.c:107]             Using polling engine: epoll
D0313 03:06:59.765013228    4381 ev_posix.c:107]             Using polling engine: epoll
D0313 03:06:59.765107808    4381 ev_posix.c:107]             Using polling engine: epoll
D0313 03:06:59.765203037    4381 ev_posix.c:107]             Using polling engine: epoll
D0313 03:06:59.765327292    4381 ev_posix.c:107]             Using polling engine: epoll
D0313 03:06:59.765441133    4381 ev_posix.c:107]             Using polling engine: epoll
D0313 03:06:59.765558300    4381 ev_posix.c:107]             Using polling engine: epoll
D0313 03:06:59.765678832    4381 ev_posix.c:107]             Using polling engine: epoll
D0313 03:06:59.765791243    4381 ev_posix.c:107]             Using polling engine: epoll
D0313 03:06:59.765899909    4381 ev_posix.c:107]             Using polling engine: epoll
D0313 03:06:59.766011764    4381 ev_posix.c:107]             Using polling engine: epoll
D0313 03:06:59.766122124    4381 ev_posix.c:107]             Using polling engine: epoll
D0313 03:06:59.766229302    4381 ev_posix.c:107]             Using polling engine: epoll
D0313 03:06:59.766361516    4381 ev_posix.c:107]             Using polling engine: epoll
D0313 03:06:59.766486293    4381 ev_posix.c:107]             Using polling engine: epoll
D0313 03:06:59.766592000    4381 ev_posix.c:107]             Using polling engine: epoll
D0313 03:06:59.766692515    4381 ev_posix.c:107]             Using polling engine: epoll
D0313 03:06:59.766793786    4381 ev_posix.c:107]             Using polling engine: epoll
D0313 03:06:59.766893038    4381 ev_posix.c:107]             Using polling engine: epoll
D0313 03:06:59.766988250    4381 ev_posix.c:107]             Using polling engine: epoll
D0313 03:06:59.767083076    4381 ev_posix.c:107]             Using polling engine: epoll
D0313 03:06:59.771112779    4381 ev_posix.c:107]             Using polling engine: epoll
D0313 03:06:59.771620953    4381 ev_posix.c:107]             Using polling engine: epoll
D0313 03:06:59.771942445    4381 ev_posix.c:107]             Using polling engine: epoll
D0313 03:06:59.772171753    4381 ev_posix.c:107]             Using polling engine: epoll
D0313 03:06:59.772326333    4381 ev_posix.c:107]             Using polling engine: epoll
D0313 03:06:59.772448098    4381 ev_posix.c:107]             Using polling engine: epoll
D0313 03:06:59.772561546    4381 ev_posix.c:107]             Using polling engine: epoll
D0313 03:06:59.772678262    4381 ev_posix.c:107]             Using polling engine: epoll
D0313 03:06:59.772797672    4381 ev_posix.c:107]             Using polling engine: epoll
D0313 03:06:59.773518426    4381 ev_posix.c:107]             Using polling engine: epoll
D0313 03:06:59.773666883    4381 ev_posix.c:107]             Using polling engine: epoll
D0313 03:06:59.773919430    4381 ev_posix.c:107]             Using polling engine: epoll
D0313 03:06:59.774036721    4381 ev_posix.c:107]             Using polling engine: epoll
D0313 03:06:59.774138149    4381 ev_posix.c:107]             Using polling engine: epoll
D0313 03:06:59.774240443    4381 ev_posix.c:107]             Using polling engine: epoll
D0313 03:06:59.774506966    4381 ev_posix.c:107]             Using polling engine: epoll
Note: Google Test filter = ProxyEnd2end/ProxyEnd2endTest.Peer/0
[==========] Running 1 test from 1 test case.
[----------] Global test environment set-up.
[----------] 1 test from ProxyEnd2end/ProxyEnd2endTest
[ RUN      ] ProxyEnd2end/ProxyEnd2endTest.Peer/0
D0313 03:06:59.774968022    4381 end2end_test.cc:230]        TestScenario{use_proxy=false, credentials='ssl'}
D0313 03:06:59.775027901    4381 ev_posix.c:107]             Using polling engine: epoll
I0313 03:06:59.812075617    4381 server_builder.cc:247]      Synchronous server. Num CQs: 4, Min pollers: 1, Max Pollers: 2147483647, CQ timeout (msec): 10
D0313 03:06:59.812156736    4381 ev_posix.c:107]             Using polling engine: epoll
E0313 03:06:59.891068259    4381 sync_posix.c:66]            assertion failed: pthread_mutex_unlock(mu) == 0



*******************************
Caught signal SIGABRT
bins/dbg/end2end_test[0x6242c4]
/lib/x86_64-linux-gnu/libpthread.so.0(+0xf8d0)[0x7f7214c8f8d0]
/lib/x86_64-linux-gnu/libc.so.6(gsignal+0x37)[0x7f7213ec7067]
/lib/x86_64-linux-gnu/libc.so.6(abort+0x148)[0x7f7213ec8448]
bins/dbg/end2end_test[0x4b9913]
bins/dbg/end2end_test[0x55c3e4]
bins/dbg/end2end_test[0x55c4fe]
bins/dbg/end2end_test[0x55e464]
bins/dbg/end2end_test[0x4e92f9]
bins/dbg/end2end_test[0x4d32d8]
bins/dbg/end2end_test[0x4ac638]
bins/dbg/end2end_test[0x43d7e8]
bins/dbg/end2end_test[0x41090a]
bins/dbg/end2end_test[0x6eb6c4]
bins/dbg/end2end_test[0x6e6ce2]
bins/dbg/end2end_test[0x6ce52c]
bins/dbg/end2end_test[0x6cece7]
bins/dbg/end2end_test[0x6cf3aa]
bins/dbg/end2end_test[0x6d5ed5]
bins/dbg/end2end_test[0x6ecac2]
bins/dbg/end2end_test[0x6e7a76]
bins/dbg/end2end_test[0x6d4aa5]
bins/dbg/end2end_test[0x43df6f]
bins/dbg/end2end_test[0x42764e]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf5)[0x7f7213eb3b45]
bins/dbg/end2end_test[0x40e8d1]
```

**Comment by yang-g** [comment] 2017-03-13 18:45
Seems like a dup of #10092.

**Comment by yang-g** [comment] 2017-03-13 23:59
I could not reproduce on my machine.

**Comment by dgquintas** [comment] 2017-09-24 01:05
Not seen in quite a while, closing.

**Closed by dgquintas** 2017-09-24 01:05 UTC
Labels: infra/BUILDPONY
