### ISSUE TITLE
csharp.Grpc.IntegrationTesting.ExternalDnsWithTracingClientServerTest flake

### ISSUE THREAD

**Issue by rmstar** [grpc/grpc#18126] opened 2019-02-21 18:56 UTC
https://source.cloud.google.com/results/invocations/cf8d6c4f-1f50-463e-88fd-a25d5fbc79d1/targets/grpc%2Fcore%2Fpull_request%2Fmacos%2Fgrpc_basictests_dbg/log
```
I0221 01:44:50.847989 123145551552512 /Volumes/BuildData/tmpfs/src/github/grpc/workspace_csharp_macos_dbg_native/src/core/lib/surface/init.cc:209: grpc_shutdown(void)
Caught exception in native callback System.ExecutionEngineException: String conversion error: Illegal byte sequence encounted in the input.
  at (wrapper managed-to-native) System.Runtime.InteropServices.Marshal.PtrToStringAnsi(intptr)
  at Grpc.Core.Internal.NativeLogRedirector.HandleWrite (System.IntPtr fileStringPtr, System.Int32 line, System.UInt64 threadId, System.IntPtr severityStringPtr, System.IntPtr msgPtr) [0x0002b] in <06b8f23a434245b8b944cae9f284da39>:0
Caught exception in native callback System.ExecutionEngineException: String conversion error: Illegal byte sequence encounted in the input.
  at (wrapper managed-to-native) System.Runtime.InteropServices.Marshal.PtrToStringAnsi(intptr)
  at Grpc.Core.Internal.NativeLogRedirector.HandleWrite (System.IntPtr fileStringPtr, System.Int32 line, System.UInt64 threadId, System.IntPtr severityStringPtr, System.IntPtr msgPtr) [0x0002b] in <06b8f23a434245b8b944cae9f284da39>:0
Run Settings
    Number of Test Workers: 1
    Work Directory: /Volumes/BuildData/tmpfs/src/github/grpc/workspace_csharp_macos_dbg_native
    Internal Trace: Off
Test Run Summary
  Overall result: Passed
  Test Count: 1, Passed: 1, Failed: 0, Warnings: 0, Inconclusive: 0, Skipped: 0
  Start time: 2019-02-21 09:44:38Z
    End time: 2019-02-21 09:44:50Z
    Duration: 12.626 seconds
Caught exception in native callback System.Threading.ThreadAbortException: Thread was being aborted.
  at (wrapper managed-to-native) System.Net.Sockets.Socket.Socket_internal(System.Net.Sockets.Socket,System.Net.Sockets.AddressFamily,System.Net.Sockets.SocketType,System.Net.Sockets.ProtocolType,int&)
  at System.Net.Sockets.Socket..ctor (System.Net.Sockets.AddressFamily addressFamily, System.Net.Sockets.SocketType socketType, System.Net.Sockets.ProtocolType protocolType) [0x00040] in <23340a11bb41423aa895298bf881ed68>:0
  at Grpc.IntegrationTesting.SocketUsingLogger.MyLog (System.Action delegateLog) [0x00008] in <4b10b0d1c4f74d13b594ef0093ed75c9>:0
  at Grpc.IntegrationTesting.SocketUsingLogger.Info (System.String message) [0x00015] in <4b10b0d1c4f74d13b594ef0093ed75c9>:0
  at Grpc.Core.Internal.NativeLogRedirector.HandleWrite (System.IntPtr fileStringPtr, System.Int32 line, System.UInt64 threadId, System.IntPtr severityStringPtr, System.IntPtr msgPtr) [0x0007a] in <06b8f23a434245b8b944cae9f284da39>:0
2019-02-21 01:49:42,366 TIMEOUT: csharp.Grpc.IntegrationTesting.ExternalDnsWithTracingClientServerTest [pid=86438, time=304.5sec]
2019-02-21 01:49:42,370 FAILED: csharp.Grpc.IntegrationTesting.ExternalDnsWithTracingClientServerTest
2019-02-21 01:49:42,413 START: tools/run_tests/helper_scripts/post_tests_csharp.sh
2019-02-21 01:49:42,425 PASSED: tools/run_tests/helper_scripts/post_tests_csharp.sh [time=0.0sec, retries=0:0]
2019-02-21 01:49:42,427 FAILED: Some tests failed
2019-02-21 01:49:42,969 FAILED: run_tests_csharp_macos_dbg_native [ret=2, pid=80570, time=452.4sec]
```

**Comment by jtattermusch** [comment] 2019-04-01 23:53
Seen again on https://github.com/grpc/grpc/pull/18602

@apolcyn  any ideas why this is failing or plans to fix?

**Comment by apolcyn** [comment] 2019-04-02 00:04
This has been tricky to reproduce manually, but I do see it occurring on master too. Looking... (I have a theory that https://github.com/grpc/grpc/pull/17688 may help)

**Comment by apolcyn** [comment] 2019-04-03 22:20
I think there are actually two different failures happening here: 

* One is the error happening here and is specific to the `ExternalDnsWithTracingClientServerTest` test. What's happening here is that the test actually passes in reasonable time, but then it looks like it takes a long time to shut down. During that time, the test hits the five minute timeout and it looks like that is somehow in turn prompting the `System.Threading.ThreadAbortException` during a log message. I suspect that this failure mode is probably related to slowness of running under `GRPC_TRACE=all`.

* The other error is an actual DNS resolution flake, where I've noticed more occurrences with the `ExternalDnsClientServerTest`. In that one, the RPC actually fails with a `StatusCode=Unavailable, Detail="DNS resolution failed"` status. I think that this failure will be fixed by https://github.com/grpc/grpc/pull/17688 - I could repro before that change (~1 in 1000) and haven't been able to repro with it.

**Comment by apolcyn** [comment] 2019-08-21 20:55
Seen again in https://source.cloud.google.com/results/invocations/70f3c738-cafe-433d-b350-919e9e61c859/targets/github%2Fgrpc%2Fcsharp_linux_opt_native/tests

**Comment by jtattermusch** [comment] 2019-10-24 07:29
Even though this is not that common, it's by far the top C# test flake: https://testgrid.corp.google.com/Basic%20Tests#Basic%20Tests%20CSharp%20Linux&width=5

**Comment by jtattermusch** [comment] 2019-11-13 15:04
The problem I'm seeing is as follows:
- the test itself actually passes quickly (within a few seconds)
- things get stuck during the shutdown (it keeps printing traces from timer manager).
- after five minutes of doing nothing the tests times out, which is reported as an error.

So the interesting part is finding out why things get stuck at shutdown.

```
I1113 05:50:41.139185 140544890840832 /usr/local/google/home/jtattermusch/github/grpc/src/core/lib/surface/completion_queue.cc:1397: grpc_completion_queue_shutdown(cq=
0x7fd3202e6890)
I1113 05:50:41.139245 140544890840832 /usr/local/google/home/jtattermusch/github/grpc/src/core/lib/surface/completion_queue.cc:1403: grpc_completion_queue_destroy(cq=0
x7fd3202e69d0)
I1113 05:50:41.139321 140544890840832 /usr/local/google/home/jtattermusch/github/grpc/src/core/lib/surface/completion_queue.cc:1397: grpc_completion_queue_shutdown(cq=
0x7fd3202e69d0)
I1113 05:50:41.139799 140544945551104 /usr/local/google/home/jtattermusch/github/grpc/src/core/lib/surface/init.cc:212: grpc_shutdown(void)

Run Settings
    Number of Test Workers: 1
    Work Directory: /usr/local/google/home/jtattermusch/github/grpc
    Internal Trace: Off

Test Run Summary
  Overall result: Passed
  Test Count: 1, Passed: 1, Failed: 0, Warnings: 0, Inconclusive: 0, Skipped: 0
  Start time: 2019-11-13 10:50:40Z
    End time: 2019-11-13 10:50:41Z
    Duration: 0.715 seconds

I1113 05:50:41.770011 140544909739776 /usr/local/google/home/jtattermusch/github/grpc/src/core/lib/iomgr/timer_manager.cc:204: wait ended: was_timed:1 kicked:0
I1113 05:50:41.770228 140544909739776 /usr/local/google/home/jtattermusch/github/grpc/src/core/lib/iomgr/timer_generic.cc:718: TIMER CHECK BEGIN: now=1010 next=9223372036854775807 tls_min=350 glob_min=1010
I1113 05:50:41.770347 140544909739776 /usr/local/google/home/jtattermusch/github/grpc/src/core/lib/iomgr/timer_generic.cc:613:   .. shard[12]->min_deadline = 1010
I1113 05:50:41.770411 140544909739776 /usr/local/google/home/jtattermusch/github/grpc/src/core/lib/iomgr/timer_generic.cc:535:   .. shard[12]: heap_empty=true
I1113 05:50:41.770471 140544909739776 /usr/local/google/home/jtattermusch/github/grpc/src/core/lib/iomgr/timer_generic.cc:510:   .. shard[12]->queue_deadline_cap --> 1169
I1113 05:50:41.770528 140544909739776 /usr/local/google/home/jtattermusch/github/grpc/src/core/lib/iomgr/timer_generic.cc:576:   .. shard[12] popped 0
```

**Closed** 2019-11-14 08:45 UTC
Labels: infra/BUILDPONY, kind/bug, lang/C#, priority/P2
