### ISSUE TITLE
CPU core maxed out by grpc_csharp_ext.x86.dll!_grpcsharp_version_string

### ISSUE THREAD

**Issue by sandersaares** [grpc/grpc#14350] opened 2018-02-07 06:07 UTC
### Should this be an issue in the gRPC issue tracker?
 Yes

### What version of gRPC and what language are you using?
 C# 1.7.1

Possibly older version, as this software has been deployed for some time now. The gRPC DLL files carry a date of October 31 2017.
 
### What operating system (Linux, Windows, …) and version?
 Windows 10 v1709
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
.NET Framework 4.7
 
### What did you do?
I have service that among other things exposes a gRPC API. This API is idle (literally zero clients configured to call it as far as I know).
 
### What did you expect to see?
My service does its work (updating text files every few minutes/hours) and nothing related to gRPC occurs.
 
### What did you see instead?
Yesterday and at the same time, every running instance of this service (total count 3) maxed out one CPU core and has remained so for around 20 hours now. Exploring running threads via Process Explorer yields the following:

![image](https://user-images.githubusercontent.com/9914262/35900429-9b7c8aba-0bda-11e8-9417-5d7a78912ed3.png)

I have no debug symbols loaded, so I assume the symbol it shows for the function is just wrong (getting a version string seems unlikely to be capable of using much CPU).

This has so far occurred on at least 3 instances of the app on the same server. I am *not* able to reproduce it on my PC by starting a copy of the app. The problematic instances were started approximately a month ago and were started at the same time, so possibly the running time has something to do with it.
 
### Anything else we should know about your project / environment?
Here is a memory dump of one such process in a CPU-burning state: https://media.axprod.net/issues/grpc_maxed_cpucore/Axinom.Lapd.Receiver.7z

**Comment by jtattermusch** [comment] 2018-02-07 08:13
Thanks for reporting. Is there a way I can reproduce? (looks like you can't reproduce locally).
- how often does it happen?
- any other info that would help me reproduce? (spending so much time in grpcsharp_version_string does sound odd indeed).

**Comment by jtattermusch** [comment] 2018-02-07 08:14
https://github.com/grpc/grpc/blob/fb369d95677b85995071e8255230c8bd7e291216/src/csharp/ext/grpc_csharp_ext.c#L1117

**Comment by sandersaares** [comment] 2018-02-07 08:16
This is the only instance it has occurred so far. The three processes are still running and eating CPU - if there is anything I can do to provide more info I am happy to troubleshoot and analyze the system further.

**Comment by jtattermusch** [comment] 2018-02-07 08:22
Also, grpcsharp_version_string is actually never invoked in Grpc C#  (and GetCoreVersionString is only an internal function which is even more weird). Could you attach a debugger to the running process and get as much info as you can from it?

**Comment by sandersaares** [comment] 2018-02-07 08:29
There is a process memory dump linked in the OP that you should be able to open with a debugger. I was not able to divine any useful information out of there myself with some quick probing around, though.

Are the symbol files for grpc_csharp_ext.x86.dll available somewhere? I suspect the function Process Monitor references there is just the name of the closes exported function in memory and it is not really the function being executed. Symbol files might clear that but I was not able to find the symbols with some basic googling, though perhaps I was looking in the wrong place.

**Comment by jtattermusch** [comment] 2018-02-07 08:35
I can probably find the .pdb file for you if you provide me with your version of grpc_csharp_ext.dll (exact file size or checksum)

**Comment by sandersaares** [comment] 2018-02-07 08:38
Filename grpc_csharp_ext.x86.dll, size 1367552 bytes, date October 31 2017, sha1 b496dd1a560eb3097994747ea94969b75e8dfce9

**Comment by jtattermusch** [comment] 2018-04-03 14:36
@sandersaares  is this still happening in any later version (v1.8.x, v1.9.x, v1.10.x). There have been a bunch of stability fixes since v1.7.1 where this issue was seen and considering we weren't able to reproduce the issue, there's not much we can do here.
I'm going to close this issue, feel free to reopen if you have some new inputs.

**Closed by jtattermusch** 2018-04-03 14:36 UTC
Labels: lang/C#

**Comment by sandersaares** [comment] 2018-04-03 14:47
I have not seen it on later versions. Will make a new issue if it happens again (cannot reopen issues that contributors have closed).

**Comment by jtattermusch** [comment] 2018-06-12 08:12
FYI, starting from 1.13.0-pre1, we are making the debug symbols available (at least for windows now).
See https://github.com/grpc/grpc/issues/15437.

**Comment by christophergilbert** [comment] 2018-07-31 02:18
We came across this problem in gRPC version 1.3 and have created a manual set of patches that we apply to that version when we build it from source.  We have not been able to invest the time to re-implement the patch we created for the later versions of gRPC but we did analyze version 1.8 to both confirm the issue was still there but at the same time realised the patch code would have to be extensively modified.

The short summary of the issue is the complex way relative and absolute times are handled and used within gRPC coupled with the fact that certain time transformations pass through variables whose types are platform dependent (ie 64 bit or 32 bit).  On the 32 bit systems this causes certain times to get truncated and then code checking for deadlines will fail after monotonic times exceed approx 24.7 days.

Before getting into the analysis I have attached two 7-zip files.

[grpc.1.3.0.timebase.changes.zip](https://github.com/grpc/grpc/files/2243488/grpc.1.3.0.timebase.changes.zip)

grpc.1.3.0.timebase.changes.zip contains just enough code to force the issue to reproduce in about 5 minutes.

[grpc.1.3.0.deadline.changes.zip](https://github.com/grpc/grpc/files/2243481/grpc.1.3.0.deadline.changes.zip)

grpc.1.3.0.deadline.changes.zip contains all the code we changed to fix the issue.  Note that we kept the timebase from the repro for convenience. 

What follows is my original longer analysis when we first encountered the issue.

**Analysis** 

After analyzing over 10 different process dumps captured in this state, I have been able to get to the root cause of the issue.

The abs_deadline passed into gpr_cv_wait is monotonic with tv_sec equal to 2147483.
After 25 days, though, the current time in monotonic form has a larger tv_sec, for example, 2324204.
Then in gpr_cv_wait() the abs_deadline is converted to realtime which will be the current realtime minus the difference between the two monotonic times.
This means gpr_cv_wait will immediately timeout without ever releasing the mutex (critical section).  I think this is the crucial reason why it goes 100% cpu on this thread and never gets any work done because the other threads are blocked from supplying it with work to do.

int gpr_cv_wait(gpr_cv *cv, gpr_mu *mu, gpr_timespec abs_deadline) {
  int timeout = 0;
  DWORD timeout_max_ms;
  mu->locked = 0;
if (gpr_time_cmp(abs_deadline, gpr_inf_future(abs_deadline.clock_type)) == 0) {
    **_SleepConditionVariableCS(cv, &mu->cs, INFINITE);_**
  } else {
    abs_deadline = gpr_convert_clock_type(abs_deadline, GPR_CLOCK_REALTIME);
    gpr_timespec now = gpr_now(abs_deadline.clock_type);
    int64_t now_ms = (int64_t)now.tv_sec * 1000 + now.tv_nsec / 1000000;
    int64_t deadline_ms =
        (int64_t)abs_deadline.tv_sec * 1000 + abs_deadline.tv_nsec / 1000000;
    if (now_ms >= deadline_ms) {
      _**timeout = 1;**_
    } else {
      if ((deadline_ms - now_ms) >= INFINITE) {
        timeout_max_ms = INFINITE - 1;
      } else {
        timeout_max_ms = (DWORD)(deadline_ms - now_ms);
      }
      timeout = (SleepConditionVariableCS(cv, &mu->cs, timeout_max_ms) == 0 &&
                 GetLastError() == ERROR_TIMEOUT);
    }
  }
  mu->locked = 1;
  return timeout;
}

The interesting thing is that I think the intent of the code that is being run is to generally supply a deadline that is infinite but a transform at some point is converting tv_sec = 7fffffff ffffffff to tv_sec = 2147483.  Figuring out where this is happening is the key.  In the code above, I have highlighted two lines.  The "timeout = 1" line is the code that currently executes in this scenario.  The "SleepConditionVariableCS" line is the code that probably should execute in this situation where the original intent is for an infinite deadline.

So where does the deadline get screwed up prior to gpr_cv_wait?  Well, gpr_cv_wait can be called by two other functions in this broad context: 
•	grpc_completion_queue_pluck
•	grpc_completion_queue_next
Both functions are very similar and take a deadline timespec as realtime infinite.  This is then converted to monotonic infinite.  Then the current now time in monotonic form is retrieved and a copy of the deadline made for this iteration.  Then, in both functions, just prior to the call to gpr_cv_wait, the now timespec and the iteration deadline timespec are both passed to the gpr_timer_check function.

Through raw stack analysis of multiple snapshot dumps, I have been able to confirm that all timespecs are in good order going into the gpr_timer_check function.  I also have one dump that caught the critical thread in the middle of executing gpr_timer_check and just prior to writing the incorrect deadline back to the out parameter.  

bool grpc_timer_check(grpc_exec_ctx *exec_ctx, gpr_timespec now, gpr_timespec **_*next_**) {
  // prelude
  GPR_ASSERT(now.clock_type == g_clock_type);
  **_gpr_atm now_atm = timespec_to_atm_round_down(now);_**

  /* fetch from a thread-local first: this avoids contention on a globally
     mutable cacheline in the common case */
  gpr_atm min_timer = gpr_tls_get(&g_last_seen_min_timer);
  if (now_atm < min_timer) {
    if (next != NULL) {
      **_*next = atm_to_timespec(GPR_MIN(timespec_to_atm_round_up(*next), min_timer));_**
    }
    // removed tracing code
    return 0;
  }

  grpc_error *shutdown_error =
      gpr_time_cmp(now, gpr_inf_future(now.clock_type)) != 0
          ? GRPC_ERROR_NONE
          : GRPC_ERROR_CREATE_FROM_STATIC_STRING("Shutting down timer system");

  // removed tracing code

  // actual code
  bool r;
  gpr_atm next_atm;
  if (next == NULL) {
    r = run_some_expired_timers(exec_ctx, now_atm, NULL, shutdown_error);
  } else {
    **_next_atm = timespec_to_atm_round_down(*next);_**
    r = run_some_expired_timers(exec_ctx, now_atm, &next_atm, shutdown_error);
    **_*next = atm_to_timespec(next_atm);_**
  }

  // removed tracing code
  return r > 0;
}

Specifically, gpr_timer_check converts the now and deadline timespecs into gpr_atm types.  Unfortunately, this type is defined as a pointer, meaning that it will be 64 bits on 64 bit builds and 32 bit on 32 bit builds.  We have a 32 bit build and so all gpr_atm variables are only 32 bits.  Now gpr_timer_check also modifies the deadline but it does so by modifying the atm version of the deadline and then it converts the atm deadline back to a deadline timespec.  This is bad.  All times and deadlines in gpr_atm form are in milliseconds relative to the start of the process.  This means we hit max value for all these timers and deadlines just before 25 days.

**Conclusion**

The only conclusion I can draw is that this timer aspect of grpc was never tested on 32 bit builds beyond 25 days.  

The problem is solvable but not trivial and can only be addressed by changing grpc code.  It’s not enough to change just gpr_timer_check or just to handle the infinite deadline case properly as all deadline timers are affected and they are used in numerous places.

**Comment by jtattermusch** [comment] 2018-07-31 07:07
@christophergilbert thanks for the detailed analysis. I think your analysis is correct and this bug was at some point noticed by other users too. We believe it's now fixed by https://github.com/grpc/grpc/pull/14894  (and there's a duplicate issue https://github.com/grpc/grpc/issues/15336).

The fix is available starting from version v1.13.0 - can you try that things are working well for you?

Btw, the gRPC versions 1.3.0 and 1.8.0 your are mentioning are pretty old - I'd recommend upgrading to a newer release if possible.

**Comment by christophergilbert** [comment] 2018-07-31 15:30
@jtattermusch thanks for the quick reply.  Having read through the back and forth discussion on #14894 I would say that looks extremely promising.  We will try out the 1.13 version with our c# process immediately.  Our c++ processes will have to wait until we can update our compiler.
