### ISSUE TITLE
grpc CLI client

### ISSUE THREAD

**Issue by mwitkow** [grpc/grpc#3020] opened 2015-08-21 09:59 UTC
`protoc` currently allows you to encode a textual message into a protobuf using the `--encode` function, and similarly `decode`. All of that by referencing the protobuf's package and message name.

For rapid development it would be great to be able to call a GRPC service by pointing a `grpc` tool at a directory of `.proto` files, specify the full path to the Service and then it would automatically make either a unary or streaming call.

Is there something like this planned for `grpc`? If not, how hard would be to get `protoc` code and merge it with a `grpc` C++ client library?

**Comment by yang-g** [comment] 2015-08-21 16:49
This is essentially a dup of #1805.
We have a command line tool which only takes serialized binary proto files and I would like to extend it to take text form protos. It currently supports unary rpc only (or a one-ping-one-pong stream) since it is not quite clear to me how to handle user instructed streaming now.

The code is in https://github.com/grpc/grpc/blob/master/test/cpp/util/grpc_cli.cc and there are comments as examples. Suggestions are welcomed.

Thanks.

**Comment by mwitkow-io** [comment] 2015-08-24 09:02
@yang-g thanks for pointing me at that. 

Yes, server reflection Google-style would be awesome. However, we could get some useful stuff before that with relying on manual pointing to a pool of `.proto` files.

As for user instructed streaming, how about modelling it after unix pipes? For textual protos you know when they start and end because you've got `< >` markes. Same for JSON with `{ }` for start end. For binary protos it may be trickier, though.

I wish I knew c++ well enough to get cracking on this.

**Comment by yang-g** [comment] 2015-11-05 22:34
closed as mostly a duplicate of #1805

**Closed by yang-g** 2015-11-05 22:34 UTC
Labels: c++

**Comment by 0xcaff** [comment] 2018-02-22 21:15
For anyone who's looking, there is:

* Polygot: https://github.com/grpc-ecosystem/polyglot
* Built In tool https://github.com/grpc/grpc/blob/master/doc/command_line_tool.md
