### ISSUE TITLE
Unobserved task exception for disposed but not exhausted-by-client server streaming call

### ISSUE THREAD

**Issue by jskeet** [grpc/grpc#17458] opened 2018-12-11 12:03 UTC
### What version of gRPC and what language are you using?

Grpc.Core 1.17.0, C# 
 
### What operating system (Linux, Windows, …) and version?
 
Windows 10, x64.
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
 
.NET Core SDK (recent enough to support C# 7.3) with `<LangVersion>latest</LangVersion>` in the project file.
 
### What did you do?

Create a project using Google.Cloud.Spanner.V1 version 2.0.0-beta05 (just for simple bootstrapping; I've deliberately not used any of the additional manual code here, other than to create a client simply).

First create a Spanner database (not included in this repro). No tables are required. Then run the following code, which assumes default credentials are available. Change the YOUR_PROJECT_ID etc appropriately

```csharp
using Google.Cloud.Spanner.Common.V1;
using Google.Cloud.Spanner.V1;
using System;
using System.Threading;
using System.Threading.Tasks;

class Program
{
    static async Task Main(string[] args)
    {
        TaskScheduler.UnobservedTaskException += (sender, e) => Console.WriteLine(e.Exception);
        var dbName = new DatabaseName("YOUR_PROJECT_ID", "YOUR_INSTANCE_ID", "YOUR_DATABASE_ID");
        var client = SpannerClient.Create().GrpcClient;

        var session = await client.CreateSessionAsync(new CreateSessionRequest { DatabaseAsDatabaseName = dbName });

        for (int i = 0; i < 1000; i++)
        {
            Console.WriteLine($"Starting iteration {i}");
            var request = new ExecuteSqlRequest
            {
                SessionAsSessionName = session.SessionName,
                Sql = "SELECT 1",
            };
            using (var streamingCall = client.ExecuteStreamingSql(request))
            {
                var headers = await streamingCall.ResponseHeadersAsync;
                var responseStream = streamingCall.ResponseStream;
                await responseStream.MoveNext(default);
            }
            Thread.Sleep(1000);
            GC.Collect();
        }

    }
}
```

### What did you expect to see?

No output other than "Iteration 0" etc. 
 
### What did you see instead?
 
After some time (it varies, but normally fairly early - before iteration 50):

```text
System.AggregateException: A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread. (Status(StatusCode=Cancelled, Detail="Cancelled")) ---> Grpc.Core.RpcException: Status(StatusCode=Cancelled, Detail="Cancelled")
   --- End of inner exception stack trace ---
---> (Inner Exception #0) Grpc.Core.RpcException: Status(StatusCode=Cancelled, Detail="Cancelled")<---
 ```

### Anything else we should know about your project / environment?

I've observed this with Bigtable as well. It's intermittent in both cases.

If the client code exhausts the stream, e.g.

```csharp
while (await responseStream.MoveNext(default))
{
}
```

... then no exception is seen.

**Comment by kkm000** [comment] 2018-12-25 08:57
Possibly related: https://github.com/grpc/grpc/issues/8451.

**Comment by jtattermusch** [comment] 2019-01-02 20:45
Does ".NET Core SDK (recent enough to support C# 7.3) with <LangVersion>latest</LangVersion> in the project file." imply that this is specific to C# 7.3 or have you observed for other C# versions as well?

**Comment by kkm000** [comment] 2019-01-02 22:30
@jtattermusch, the C# language version is only important to enable the `async Main`, that requires language spec version 7.1, while the default is 7.0. This only affects a compiler flag (akin to `-std=c++17` to gcc), while the compiler is tied to/comes with the SDK. But I'd bet it's not the compiler issue.

@jskeet, could you please check if sockets are leaked when the error occurs? That was what I'd seen in #8451, before adding a similar stream-draining loop. In my case, there positively had been more unread messages when I was disposing of the the call. If Spanner may _sometimes_ return more than one record in your test, that would match my pattern.

Also, I think that `GC.WaitForPendingFinalizers()` after the `GC.Collect()` will add more determinism to the repro (maybe to the point of hiding the error, though). Also, I am wondering if `Thread.Sleep(1000);` could similarly mask a bug. Could you check if going with just `GC.Collect(); GC.WaitForPendingFinalizers();` but no Sleep changes anything?

**Comment by jskeet** [comment] 2019-01-02 22:35
@kkm000: I'll look tomorrow. Do you have a preferred way of checking for socket leakage?

(I'd previously had `GC.WaitForPendingFinalizers()` in the code, but I *think* it didn't change how often the exception occurred. Will check that too.)

**Comment by kkm000** [comment] 2019-01-03 01:59
> Do you have a preferred way of checking for socket leakage?

AFAICR, quoting the two-years-younger myself,

> If the call is disposed by the client without first reading the server stream to EOF, channel will not close its socket on shutdown, and a warning message is reported: _W1020 18:40:55.407708 Grpc.Core.Channel Channel shutdown was called but there are still 1 active calls for that channel._

So the socket was not closed in a call to `client.ShutdownAsync().Wait()`, and netstat listed it as CONNECTED. I do not remember if the Wait call on it blocked forever, or rather simply returned without closing the socket--I think the latter had been the case, but I am wobbling. I'm certain I used netstat.

Oh, I wish I could remember all the fine points! I reported the error against v1.0.0 over 2 years ago.

**Comment by jskeet** [comment] 2019-01-03 10:07
Just reran my tests:

- No warning or error logs
- No leaked sockets, as far as I can tell. (Over the course of the whole test, netstat showed a single socket for the process)

**Comment by kkm000** [comment] 2019-01-05 13:13
@jskeet, thanks for checking.

I played with the code a bit. I repro the exception, but the reproduction is very inconsistent; once I got the exception reported on iteration 20, then in the hundreds, then not at all. I reduced the wait, added/removed WaitForPendingFinalizers(), but this does not seem to affect it much.

Interesting, I cannot compare the behavior against what I originally reported. The channel just refuses to shut down. I modified the code slightly; create the channel outside of SpanerClient.Create():
```c#
    var cred = GoogleCredential.FromFile(@"...../mycred.json");
    var channel = new Channel(SpannerClient.DefaultEndpoint.Host,
      SpannerClient.DefaultEndpoint.Port, cred.ToChannelCredentials());
    var client = SpannerClient.Create(channel).GrpcClient;
```
then shut it down last thing before exiting the program
```c#
    await channel.ShutdownAsync();
    await Task.Delay(2000);
    Console.WriteLine($"Channel state = {channel.State}\nPress ENTER to exit...");
    Console.ReadLine();
  }
}
```
The output shows that the channel is `Ready`, while the documentation on the `State` property says that the channels state will be `Shutdown`.
```
Channel state = Ready
Press ENTER to exit...
```
Accordingly, the socket stays open even while the program is waiting for key, regardless of whether the error occurred or not (after say 5 iterations).
```
> netstat -n -b
 . . .
  TCP    10.2.0.129:56799       216.58.219.42:443      ESTABLISHED
 [dotnet.exe]
```
In my old ticket, against v1.0, this happened only if there was an unobserved GrpcException earlier. I'll check the same client v1.7.0 against our server next week.

**Comment by kkm000** [comment] 2019-01-05 13:16
Huh, and
```c#
Console.WriteLine($"Channel state = {channel.State}, Shutdown requested? {channel.ShutdownToken.IsCancellationRequested}");
```
prints
```
Channel state = Ready, Shutdown requested? True
```
Weird.

**Comment by bmulder-innoseis** [comment] 2019-09-05 14:27
I am also having this issue.
My guess is that in my case if some code inside the loop `while (await call.ResponseStream.MoveNext())` throws an exception, the stream is not exhausted and this Unobserved Task Exception occurs because of that.
Could you please continue to look into this?

**Comment by jtattermusch** [comment] 2019-11-12 10:59
My analysis of what's happening:
1. the response stream is not exhausted because MoveNext() is not called until it returns false (we knew that)
2. the `call.Dispose()` that's invoked when leaving the using(var call = ) statement cancels the call.
3. because the call is cancelled, eventually the call streaming call finishes with status "Cancelled" and a callback is invoked internally to clean up. The code that creates the `Grpc.Core.RpcException: Status(StatusCode=Cancelled, Detail="Cancelled")` is here: https://github.com/grpc/grpc/blob/0605a977c88af6dc4d3ab308dd8b7cbb5aec9ea6/src/csharp/Grpc.Core/Internal/AsyncCall.cs#L584. The interesting part is that the "Unobserved task exception" is set into a task via TaskCompletionSource (= so no operation really fails, we're just storing the exception in case the users will ask about the call's status later).  Nevertheless, the Exception property of Task created by TaskCompletionSource needs to be observed anyway.

https://stackoverflow.com/questions/36620124/do-i-need-to-observe-the-exception-property-of-a-task-created-by-a-taskcompletio

**Closed** 2019-12-03 17:19 UTC
Labels: kind/bug, lang/C#, priority/P2
