### ISSUE TITLE
Grpc.Tools does not generate code after project clean (in .NET classic project)

### ISSUE THREAD

**Issue by ghord** [grpc/grpc#18625] opened 2019-04-03 10:15 UTC
### What version of gRPC and what language are you using?

C#
 Grpc 1.19.0 
 
### What operating system (Linux, Windows,...) and version?
 Windows 10
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
 Visual Studio 2019
.net 4.7,2 

### What did you do?
1. Created new project .net 4.7.2 (classic only) **this bug does not appear in .net core projects**
2. Added nuget packages Grpc, Google.Protobuf and Grpc.Tools
3. Linked sample greet.proto to the project, set Build Action to ProtoBuf
```
syntax = "proto3";

package CoreSchema;

service Greeter {
  rpc SayHello (HelloRequest) returns (HelloReply) {}
}

message HelloRequest {
  string name = 1;
}

message HelloReply {
  string message = 2;
}
````
4. Build the project and it works fine. Files Greet.cs and GreetRpc.cs are correctly generated in obj/Debug
5. Added code using the client `var greeter = new Greeter.GreeterClient(channel);` **in the same project** 
6. Again, project builds fine
7. Run Clean on project
8. Project does not build anymore, files Greet.cs and GreetRpc.cs are missing
 
### What did you expect to see?
Project builds after clean
 
### What did you see instead?

Project fail to build with error
error CS0246: The type or namespace name 'Greeter' could not be found (are you missing a using directive or an assembly reference?)

### Anything else we should know about your project / environment?
It looks like msbuild task fail to run if the project does not compile before the generation. The solution would be to compile proto files in separate project. Is this the way it should be used in .net classic projects? (this works fine in .net core project)

**Comment by jtattermusch** [comment] 2019-04-11 09:59
CC @kkm000

**Comment by itshemant09** [comment] 2019-08-29 06:54
Any update on this ?? I am getting the same error error CS0246: The type or namespace name 'Greeter' could not be found (are you missing a using directive or an assembly reference?)

**Comment by kkm000** [comment] 2019-08-30 18:57
@itshemant09, I'm sorry about sitting on this issue for months. I do have a couple of gRPC tickets on me that do indeed hold some fine mates back, and am trying hard to carve out a couple days to get them fixed.

This one can be worked around for now by copying the generated files once they are built, but if you need to change the proto files often as you develop, this can certainly be frustrating.

**Comment by chriszwang** [comment] 2019-10-31 14:45
@kkm000 Any update on the fix you mentioned on Aug. 30?  It is been few months and it is frustrating you have to copy the file after each clean.

**Comment by jtattermusch** [comment] 2019-11-12 11:34
I just tried to reproduce with your instructions and I wasn't able to. I followed the instructions and the build worked for me just fine regardless of how many times and ran "clean".

Can you provide a minimal project that reproduces the problem?

**Comment by Stallkicker** [comment] 2019-12-09 00:33
@chriszwang @ghord Do either of you have the "Automatically clean up usings on save" feature enabled in VS? I had the same issue occur when playing around with the example, and after making modifications the `using Helloworld;` statement was missing. After adding the statement back, the code would successfully compile again.

**Comment by ihorbond** [comment] 2019-12-16 04:13
Having the same issue with .NET core console app. The build process doesnt generate types defined in .proto

**Comment by jtattermusch** [comment] 2019-12-17 12:43
I'm not able to reproduce - can someone provide an example project that reproduces the problem? Otherwise I cannot help.

**Comment by jtattermusch** [comment] 2019-12-17 12:44
@ihorbond  did you check this advice? https://github.com/grpc/grpc/issues/18625#issuecomment-563017236

**Comment by ihorbond** [comment] 2020-01-09 04:41
> @ihorbond did you check this advice? [#18625 (comment)](https://github.com/grpc/grpc/issues/18625#issuecomment-563017236)

It was a mistake on my end, everything works, thanks

**Comment by jtattermusch** [comment] 2020-01-09 10:46
Closing because could not reproduce.
In some cases this could have been caused by "Automatically clean up usings on save" in Visual Studio as described in https://github.com/grpc/grpc/issues/18625#issuecomment-563017236 so please doublecheck that if you think you're experiencing the issue.

**Closed by jtattermusch** 2020-01-09 10:46 UTC
Labels: kind/bug, lang/C#, priority/P2
