### ISSUE TITLE
grpc memory leak and connection problem

### ISSUE THREAD

**Issue by Rhysol** [grpc/grpc#13319] opened 2017-11-09 06:32 UTC
My grpc version is  1.7.2 And running my program on centos7. 
Here is my demo code: https://github.com/Rhysol/GrpcDemo
1. First ,I send 100k requests to my grpc server. Then I saw my server use almost 22% memory and did not release these memory before client disconnect. And I am sure these request has been responsed. After that I continue send the request  100k every time and did not disconnect from server. I send about 900k requests then my client been killed and the server release the memory .The server used almost 60% memory.

2. I can run client and server in one system, it runs ok. But when I run client in another centos7 system, it can not connect to server and returns error code 14 and error message 'connect failed'.

I don't know what's happend and I can't find too much useful information about connection in the grpc document. So I submit this issue.

**Comment by luchunminglu** [comment] 2017-11-09 06:51
the memory leak may be fixed in 1.7.1. I test this version already one week, it works fine.

**Comment by Rhysol** [comment] 2017-11-09 07:07
@luchunminglu But the grpc on github is 1.6 version,how could you get 1.7.1 version?

**Comment by Rhysol** [comment] 2017-11-09 07:10
@luchunminglu I download from https://github.com/grpc/grpc recently. I don't sure if it's 1.7.1.

**Comment by Rhysol** [comment] 2017-11-09 07:56
@luchunminglu I test it on version 1.7.2, it has the same promble

**Comment by Rhysol** [comment] 2017-11-09 08:47
I just test the c++ greeter_async_client2 and greeter_async_server. it has the same promble.

**Comment by AngryLemonn** [comment] 2017-11-22 16:02
I am having the same problem here. In my case, I used sync clients and sync servers (like helloworld client/server). 1K of request, 0.7% of memory (56MB of 8GB) passing one boolean from the client to the server, onlyyyyy oneeeee booooolean.

Any idea??

**Comment by trusch** [comment] 2017-11-23 06:23
Same here, I can provide a demo script if this would help.

The server just eats all my memory ;)

**Comment by jtattermusch** [comment] 2018-01-16 11:34
Does the problem this still persist in 1.8.3?

**Comment by Rhysol** [comment] 2018-01-17 06:45
@jtattermusch I haven't test on 1.8.3 yet. And also just test on centos7. I will test it when I am free.

**Comment by srini100** [comment] 2018-03-20 00:53
@Rhysol, I know it's been a while. Do you still see this issue. Can you make your demo code available?

**Comment by Rhysol** [comment] 2018-04-08 12:02
@srini100 Sorry, I have delete it from my repositroy.  I can't help you.

**Comment by Rhysol** [comment] 2018-04-08 12:15
@srini100 I have found my code and upload to my repository. But I don't know if it's ok. I havn't test it a long while. https://github.com/Rhysol/GrpcDemo

**Comment by vjpai** [comment] 2018-04-10 16:10
@trusch - can you provide the repro script that you mentioned also?

**Comment by trusch** [comment] 2018-04-12 15:03
I'm sorry but it's been a while. When I remember correctly I worked around by reusing existing connections.

**Comment by srini100** [comment] 2018-05-01 14:56
@vjpai @hcaseyal I can see the memory leak by running the async server and async client examples. Server keeps holding more and more memory even after client RPCs are done. Sometimes it releases some memory when client disconnects but most of the times it just accumulates the memory.

**Comment by srini100** [comment] 2018-05-01 14:58
![alloc_trace](https://user-images.githubusercontent.com/35056280/39477854-660c5064-4d15-11e8-8dd0-d15170d562d0.png)

**Comment by srini100** [comment] 2018-05-01 16:51
Marking this as P1 until we have better understanding of memory usage.

**Comment by ztao1987** [comment] 2018-05-04 14:06
@srini100 which version do you use?

**Comment by srini100** [comment] 2018-05-04 17:12
1.10 as well as latest on master.

**Comment by ztao1987** [comment] 2018-05-05 02:29
Since grpc server is a long running backend process, memory leak is quite a serious issue. Do we have any schedule when to fix it?

**Comment by hcaseyal** [comment] 2018-05-05 02:44
This is being actively looked into.

**Comment by ztao1987** [comment] 2018-05-05 03:06
Great!

**Comment by changleicn** [comment] 2018-05-08 07:27
@hcaseyal we encountered the same memory leak issue, and it is blocking our work. it would be great if it can be fixed soon. Thanks.

**Comment by hcaseyal** [comment] 2018-05-14 23:04
@changleicn Can you provide repro instructions?

**Comment by hcaseyal** [comment] 2018-05-15 15:36
I have tried reproducing the issue with the async client and server examples under various tooling (valgrind on Linux, activity monitor on Mac, and internal tools) and did not see the server holding memory after client RPCs were done. Top disagrees, but that's because glibc is probably holding on to the freed memory.

**Comment by changleicn** [comment] 2018-05-15 15:55
@hcaseyal 

This is the proto definition we used:
syntax = "proto3";

package myrpc;

service MsgTransfer {
  rpc SendMsg (stream MyMsg) returns (stream MyMsg) {}
}

message MyMsg {
  bytes msg = 1;
}


This is how we do read:
readMsg.reset(new myrpc::MyMsg);
  clientData->stream->Read(readMsg.get(), reinterpret_cast<void *>(this));

We used bidi stream async mode, same as the async server and async client example.  Found that if client doesn’t disconnect, the stream hold quite a lot of memory.

**Comment by hcaseyal** [comment] 2018-05-15 16:53
@changleicn As mentioned above, we have thoroughly investigated the async case using external as well as internal tools that track detailed memory usage. Our conclusion is that gRPC server is not holding onto any more memory than it should after all RPCs have completed. 

I am closing this issue, but if you are able to provide the specific reproduction case along with the tools you used to show the memory blow up, feel free to re open and we will take another look.

**Closed by hcaseyal** 2018-05-15 16:53 UTC
Labels: kind/bug, lang/c++, priority/P1

**Comment by srini100** [comment] 2018-05-15 20:27
@changleicn, if you are using glibc have you tried playing with malloc threshold parameters to free the memory to OS?

**Comment by ztao1987** [comment] 2018-05-15 23:38
@hcaseyal Have you monitored the client side? In my case the leak is not in server side, but in client side. I start up my user process which owns several rpc clients, also there is one completion queue thread which is shared by all these rpc clients. When rpc clients disconnects, my user process still owns quite a lot of memory which exists in grpc, maybe in cq part.

**Comment by ztao1987** [comment] 2018-05-15 23:40
@srini100 Does it work? If so, could you please help share this? currently I am blocked by the memory leak in grpc client side.

**Comment by hcaseyal** [comment] 2018-05-16 00:00
@ztao1987 I could see no evidence of a memory leak in client side either. If you think there is a memory leak in grpc, could you please include more information so that I can help you? I.e., a specific reproduction case (code would help, the tools you used to show memory blow up, and OS and compiler version.

**Comment by ztao1987** [comment] 2018-05-16 00:55
![wechatimg69](https://user-images.githubusercontent.com/11328679/40090796-9944dbea-58e6-11e8-9869-872e9ee87a3e.jpeg)
I tested on mac os 10.11.6, seems GrpcBufferReader continues to hold the memory.

**Comment by hcaseyal** [comment] 2018-05-16 01:09
@ztao1987 I need more information. I see the screenshot, but what tool are you using? Which version of grpc? Compiler? Can you provide a repro script or some code that I can run to reproduce your results? Are you experiencing an oom?

**Comment by hcaseyal** [comment] 2018-05-16 02:27
@ztao1987 Also, how long after you disconnected the clients did you get the memory profile you screenshotted?

**Comment by ztao1987** [comment] 2018-05-16 11:58
@hcaseyal I checked my code again, seems the issue is in my part, not in grpc. Server continues to write, but the client doesn't read the message which holds a lot of memory.

**Comment by hcaseyal** [comment] 2018-05-16 15:29
@ztao1987 Glad you found the issue! Thank you for posting the resolution.
