### ISSUE TITLE
py27_native.test.unit._channel_ready_future_test.ChannelReadyFutureTest is flaky on master

### ISSUE THREAD

**Issue by jtattermusch** [grpc/grpc#15308] opened 2018-05-08 13:27 UTC
E.g.
https://source.cloud.google.com/results/invocations/505e665b-86c0-43b0-8dc9-3ee7651642b4
https://source.cloud.google.com/results/invocations/d2b80a54-fb8c-48ae-b249-5cd73ea18a6d

```
++ dirname /var/local/git/grpc/tools/run_tests/helper_scripts/run_python.sh
+ cd /var/local/git/grpc/tools/run_tests/helper_scripts/../../..
++ realpath py27_native/bin/python
+ PYTHON=/var/local/git/grpc/py27_native/bin/python2.7
++ pwd
+ ROOT=/var/local/git/grpc
+ /var/local/git/grpc/py27_native/bin/python2.7 /var/local/git/grpc/src/python/grpcio_tests/setup.py test_lite
running test_lite
Running       unit._channel_ready_future_test.ChannelReadyFutureTest.test_immediately_connectable_channel_connectivity
[95mTesting gRPC Python...
[0m[92mSUCCESS       unit._channel_ready_future_test.ChannelReadyFutureTest.test_immediately_connectable_channel_connectivity
[0mRunning       unit._channel_ready_future_test.ChannelReadyFutureTest.test_lonely_channel_connectivity
[92mSUCCESS       unit._channel_ready_future_test.ChannelReadyFutureTest.test_lonely_channel_connectivity
[0m2 tests finished:
	2 successful
	0 unsuccessful
	0 skipped
	0 expected failures
	0 unexpected successes
Interrupted Tests:
	[]
Errors/Failures:
Unexpected successes: []
/var/local/git/grpc/tools/run_tests/helper_scripts/run_python.sh: line 25: 11869 Segmentation fault      (core dumped) $PYTHON "$ROOT/src/python/grpcio_tests/setup.py" "$2"
```

**Comment by nathanielmanistaatgoogle** [comment] 2018-05-15 00:39
@jtattermusch: do we happen to know the flake rate? Any guess at it?

**Comment by jtattermusch** [comment] 2018-05-15 11:02
@nathanielmanistaatgoogle no need to guess, it is easy to query for flake rate of any of our flakes and you can do it yourself.

```
select * from jenkins_test_results.aggregate_results where
  job_name like '%'  # you can filter job name here
  and test_name like '%ChannelReadyFutureTest%'  # choose a test name you are interested in
  and result != 'PASSED'
order by timestamp desc
limit 1000
```

the current flakiness seems to be around 3-4%, also, it looks like this has been introduced recently.

Also, it seems that this has been introduced recently, first occurence is from 2018-05-04 
https://source.cloud.google.com/results/invocations/d2b80a54-fb8c-48ae-b249-5cd73ea18a6d

**Comment by jtattermusch** [comment] 2018-11-20 15:22
Still seeing this on master (currently one of the top python flakes).
It looks like it's only happening with python2.7

https://source.cloud.google.com/results/invocations/970f3c89-48be-40e4-8f52-a01260c4fd59
https://source.cloud.google.com/results/invocations/21db8ab0-4a77-4b2a-8d7d-386dc67867d4
https://source.cloud.google.com/results/invocations/1c874005-3565-4f53-8186-3c3046eb8be7
https://source.cloud.google.com/results/invocations/cb3fba49-649c-4e4e-a84d-e0a5aa5c271d

**Comment by lidizheng** [comment] 2018-11-30 01:06
Unable to reproduce with parallel execution. It may indicate that the flakyness is not introduced by CPU contention or computation resource contention...

The not-working script:
```
#!/bin/bash -ex

if [[ $1 == '-b' ]]; then
  export GRPC_PYTHON_BUILD_EXT_COMPILER_JOBS=12
  python tools/run_tests/run_tests.py -j16 --build_only -l python --compiler python2.7
fi

export GRPC_PYTHON_TESTRUNNER_FILTER=unit._channel_ready_future_test.ChannelReadyFutureTest

for i in {1..1000}
do
  python src/python/grpcio_tests/setup.py test_lite > /tmp/t${i}.out 2> /tmp/t${i}.err &
done
```

**Comment by ericgribkoff** [comment] 2018-12-17 19:18
> the current flakiness seems to be around 3-4%, also, it looks like this has been introduced recently.
> 
> Also, it seems that this has been introduced recently, first occurence is from 2018-05-04
> https://source.cloud.google.com/results/invocations/d2b80a54-fb8c-48ae-b249-5cd73ea18a6d

Looking only at Python changes, the following PRs were merged just before the first occurrence of this flake:

1. https://github.com/grpc/grpc/pull/15132 - Keep Core memory inside cygrpc.Channel objects
1. https://github.com/grpc/grpc/pull/15254 - Add grpc.Channel.close()
1. https://github.com/grpc/grpc/pull/15229 - Remove CleanupThread

I can't find any changes on the server side that are suspect, and nothing has jumped out from the prep-work in #15132 for Channel.close(), but given other issues (https://github.com/grpc/grpc/pull/16296) my guess would be that the cause is somewhere in there and the segfault is happening on the client side, not the server. Still investigating.

**Comment by ericgribkoff** [comment] 2018-12-19 16:14
This is happening more frequently now that #17444 is merged. Bumped priority and working on this today.

**Comment by ericgribkoff** [comment] 2018-12-22 05:01
https://github.com/grpc/grpc/pull/17579 seems to have mitigated or fixed the seg faults in our tests. 10 consecutive green builds on master for grpc_basictests_multilang; will keep monitoring.

#17579 is basically a band-aid over the bug(s) in how we handle Python/Cython deallocation, by ensuring we explicitly close channels/servers in our tests; still working on a fix for the underlying issue, but hopefully the flaky build symptom is now mitigated.

**Comment by ericgribkoff** [comment] 2018-12-27 22:41
This hasn't recurred on master since #17579. I'll wait a bit more before closing this issue, but downgrading it to a P2. The underlying bug investigation is tracked by the newly reopened https://github.com/grpc/grpc/issues/11804.

**Comment by ericgribkoff** [comment] 2019-02-15 23:06
Haven't seen this failure post #17579, marking closed.

**Closed by ericgribkoff** 2019-02-15 23:06 UTC
Labels: infra/BUILDPONY, kind/bug, lang/Python, priority/P2
