### ISSUE TITLE
Exception while handling RPC. Operation is not valid due to the current state of the object.

### ISSUE THREAD

**Issue by PFSHI** [grpc/grpc#20112] opened 2019-08-29 06:24 UTC
### What version of gRPC and what language are you using?
gRPC 2.23.0    c# 

### What operating system (Linux, Windows,...) and version?
Windows 10

### What runtime / compiler are you using (e.g. python version or version of gcc)
.net core 2.2 

### What did you do?
run gRPC Server

### What did you see instead?

```
Exception while handling RPC. Operation is not valid due to the current state of the object.
Source:Grpc.Core
Stack:at Grpc.Core.Internal.AsyncCallServer`2.SendStatusFromServerAsync(Status status, Metadata trailers, Nullable`1 optionalWrite) in T:\src\github\grpc\src\csharp\Grpc.Core\Internal\AsyncCallServer.cs:line 137
   at Grpc.Core.Internal.ServerStreamingServerCallHandler`2.HandleCall(ServerRpcNew newRpc, CompletionQueueSafeHandle cq) in T:\src\github\grpc\src\csharp\Grpc.Core\Internal\ServerCallHandler.cs:line 142
   at Grpc.Core.Server.HandleCallAsync(ServerRpcNew newRpc, CompletionQueueSafeHandle cq, Action`2 continuation) in T:\src\github\grpc\src\csharp\Grpc.Core\Server.cs:line 346
```

**Comment by jtattermusch** [comment] 2019-09-17 12:37
This is a duplicate of https://github.com/grpc/grpc/issues/9377

**Closed by jtattermusch** 2019-09-17 12:37 UTC
Labels: kind/bug, lang/C#, priority/P2
