### ISSUE TITLE
transparent retry can cause regression with buffer_hint

### ISSUE THREAD

**Issue by BusyJay** [grpc/grpc#31465] opened 2022-10-26 10:46 UTC
### What version of gRPC and what language are you using?
1.46.5 and Rust. But language should not matter.

### What operating system (Linux, Windows,...) and version?
Linux.

### What runtime / compiler are you using (e.g. python version or version of gcc)
grpc-rs / Rust

### What did you do?
Recently I'm working on updating grpc c core to 1.46.5 for https://github.com/tikv/grpc-rs. I find that one of benchmark `rust_protobuf_async_streaming_from_client_unconstrained` has large regression. And the regression come from https://github.com/grpc/grpc/pull/28943. After setting `grpc.enable_retries` to 0, the regression is gone.

What `rust_protobuf_async_streaming_from_client_unconstrained` does is quite simple, it behaves the same as C++'s version `cpp_protobuf_async_streaming_qps_unconstrained_secure_1b` except all messages but the last one are sent with `buffer_hint` set to true.

### What did you expect to see?

No performance regression.

### What did you see instead?

The throughput is decreased from more than 100k to less than 50k.

**Comment by veblush** [comment] 2022-11-01 19:40
I reassigned this issue to Mark who worked on #28943. @BusyJay would you elaborate a bit more like what test is doing and what numbers you got with the old version of gRPC and 1.46.5?

**Comment by markdroth** [comment] 2022-11-01 20:02
It looks like the retry code at that point in history wasn't properly passing along the send_message flags, so `GRPC_WRITE_BUFFER_HINT` wasn't being propagated.  However, it looks like that problem was subsequently fixed in #29987.  If the problem is being caused by `GRPC_WRITE_BUFFER_HINT` not being propagated, then upgrading to gRPC 1.48 or newer should fix it.

**Comment by BusyJay** [comment] 2022-11-02 04:15
I rerun the test `env GRPC_POLL_STRATEGY=epoll1 python tools/run_tests/run_performance_tests.py -l rust -r rust_protobuf_async_streaming_from_client_unconstrained` on a 8 core Linux VM:

Version | Enable retry | Disable retry | Regression
------------|--------------|----|----
v1.46.5 | 203209.3 | 1345224.6 | 84.9%

**Closed** 2022-12-02 00:00 UTC
Labels: kind/bug, lang/core, priority/P2, disposition/requires reporter action, untriaged
