### ISSUE TITLE
xds_end2end_test XdsTest/LocalityMapTest.UpdateMap/FakeResolver

### ISSUE THREAD

**Issue by yashykt** [grpc/grpc#21676] opened 2020-01-15 19:30 UTC
https://source.cloud.google.com/results/invocations/20a36dc2-9551-4500-bdd3-40cf6c9a891e/targets/%2F%2Ftest%2Fcpp%2Fend2end:xds_end2end_test@poller%3Depoll1/tests

**Comment by markdroth** [comment] 2020-01-15 19:57
This is a duplicate of #20792.

**Closed by markdroth** 2020-01-15 19:57 UTC
Labels: kind/bug, priority/P2
