### ISSUE TITLE
Interop ALTS Tests (internal CI) failure due to cloud_to_cloud:java:go_server:ping_pong:alts test timeout

### ISSUE THREAD

**Issue by karthikravis** [grpc/grpc#23284] opened 2020-06-23 21:17 UTC
https://source.cloud.google.com/results/invocations/e057f299-43bd-4a38-836e-0958c232d0aa/log

Exception in thread "main" java.lang.AssertionError: Timed out waiting for response
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.junit.Assert.assertNotNull(Assert.java:712)
	at io.grpc.testing.integration.AbstractInteropTest.pingPong(AbstractInteropTest.java:776)
	at io.grpc.testing.integration.TestServiceClient.runTest(TestServiceClient.java:271)
	at io.grpc.testing.integration.TestServiceClient.run(TestServiceClient.java:214)
	at io.grpc.testing.integration.TestServiceClient.main(TestServiceClient.java:72)
Shutting down

2020-06-23 12:26:59,799 FAILED: cloud_to_cloud:java:go_server:ping_pong:alts [ret=1, pid=9198, time=7.7sec]

Seen on https://github.com/grpc/grpc/pull/23183

**Comment by gnossen** [comment] 2020-06-26 18:40
Duplicate of https://github.com/grpc/grpc/issues/18111

**Closed by gnossen** 2020-06-26 18:40 UTC
Labels: kind/bug, priority/P2
