### ISSUE TITLE
grpc objective-c client crash

### ISSUE THREAD

**Issue by FlyTengteng** [grpc/grpc#3299] opened 2015-09-09 08:55 UTC
These days I have used the RouteGruide example of grpc objective-c. If i shutdown the server every 2 minutes, the client will crash, and the crashed point is 

sync_posix.c:53] assertion failed: ret == 0

Anyone have met this situation? How to fix this bug?

**Comment by hsaliak** [comment] 2016-04-29 18:59
@sreecha do we have a stress test that checks for server shutdowns?

**Comment by sreecha** [comment] 2016-04-29 19:54
@hsaliak : We do not have one for server shudown-and-restarts yet.  This is mainly because, most of our interop clients (and in this case, the client in the route guide example) are not written to handle server restarts..

**Comment by makdharma** [comment] 2016-06-14 23:54
This looks like a duplicate of issue #2859. That issue was closed due to unable to reproduce. I'm closing this for the same reason. Please reopen if it still happens.

**Closed by makdharma** 2016-06-14 23:54 UTC
Labels: ObjC, P2, wrapped languages
