### ISSUE TITLE
grpc-python: calling init_grpc_aio twice results in all grpc calls to hang

### ISSUE THREAD

**Issue by FlorianLudwig** [grpc/grpc#23711] opened 2020-08-02 18:55 UTC
### What version of gRPC and what language are you using?
```
grpcio==1.30.0
```

### What operating system (Linux, Windows,...) and version?
Linux

### What runtime / compiler are you using (e.g. python version or version of gcc)
python 3.8

### What did you do?
Please provide either 1) A unit test for reproducing the bug or 2) Specific steps for us to follow to reproduce the bug. If there’s not enough information to debug the problem, gRPC team may close the issue at their discretion. You’re welcome to re-open the issue once you have a reproduction.

```
import grpc.experimental.aio as grpcaio

grpcaio.init_grpc_aio()
grpcaio.init_grpc_aio()
await grpcaio.insecure_channel(address)
# never reached
```

### What did you expect to see?
Working

### What did you see instead?
Hang

### Anything else we should know about your project / environment?
I would say it is not be best practices to call init multiple times but I would expect it to not break - or at least be documented that it is not allowed to be called multiple times. The use case where I came across this was inside unit tests.

**Comment by lidizheng** [comment] 2020-08-03 17:37
@FlorianLudwig Can you share more details about the hang or share a complete reproduction case? I tested locally multiple init works fine. In your snippet, the hang occurs after you trying to await on a channel instead of after the second init.

**Comment by FlorianLudwig** [comment] 2020-08-03 19:44
@lidizheng 

FIle: test_23711.py
```
import pytest
import grpc.experimental.aio as grpcaio


@pytest.mark.asyncio
async def test_a():
    grpcaio.init_grpc_aio()
    channel = grpcaio.insecure_channel("127.0.0.1:2379")
    await channel.channel_ready()
    print("channel ready")


@pytest.mark.asyncio
async def test_b():
    grpcaio.init_grpc_aio()
    channel = grpcaio.insecure_channel("127.0.0.1:2379")
    await channel.channel_ready()
    print("channel ready")
```

With `pytest` and `pytest-asyncio` installed run:
`pytest test_23711.py`

**Comment by lidizheng** [comment] 2020-08-03 22:17
There is a known issue with latest `pytest-asyncio` with v1.30.0. `pytest-asncio` creates new event loop for each tests.

Link to the fix https://github.com/grpc/grpc/pull/23377 and the cause https://github.com/googleapis/gapic-generator-python/issues/491#issuecomment-651419733. 

To resolve this issue, the first option is using only one designated event_loop.

```python
_test_event_loop = asyncio.new_event_loop()

@pytest.fixture
def event_loop():
    asyncio.set_event_loop(_test_event_loop)
    return asyncio.get_event_loop()

# The your test
@pytest.mark.asyncio
async def test_b(event_loop):
    ...
```

Option 2 is try out our [daily build](https://packages.grpc.io/archive/2020/08/80bdca9b68aab75950f2712585d43e544e9bf186-77a22eae-6450-4cc1-8f6a-bff6309f0828/index.xml) or prerelease `v1.31.0-pre2`. They should include the merged fix.

Option 3 is pairing the init with shutdown. gRPC is counting refs of its asyncio module. If the tests only call `init_grpc_aio` without `shutdown_grpc_aio`, then some gRPC component will stick to the old event loop forever then appear stuck (hang).

Option 4 Remove `init_grpc_aio()`. `init_grpc_aio()` is no longer required. We managed to automate the initialization, and this helps ref-counting.

**Closed** 2020-08-17 17:54 UTC
Labels: kind/bug, lang/Python, priority/P2
