### ISSUE TITLE
C#: Grpc.Core native libs copying every project build. No project update support.

### ISSUE THREAD

**Issue by halachkin** [grpc/grpc#24262] opened 2020-09-29 09:05 UTC
Grpc.Core nuget causes Visual Studio build projects every time, leaving no update support.

**What version of gRPC and what language are you using?**
C#, Grpc.Core 2.32.0 , net472.

**What operating system (Linux, Windows,...) and version?**
Windows 10

**What runtime / compiler are you using (e.g. python version or version of gcc)**
.net 4.7.2, Visual Studio 2019

**What did you do?**
My C# project references Grpc.Core nuget. 
Each time I build my project visual studio build it again instead of updating.

**What did you expect to see?**
Visual studio detects that there are not any project changes and skip build.

**What did you see instead?**
Dependent projects are starting full build process each time. 

The problem actually is here:
https://github.com/grpc/grpc/blob/8cc7244716365b4f361fde7c610248a60771e22f/src/csharp/Grpc.Core/build/net45/Grpc.Core.targets#L2-L44

I would be nice to have
```
<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory> 
```
Instead of
```
<CopyToOutputDirectory>Always</CopyToOutputDirectory> 
```
Or at least give user control over this property.

**Comment by jtattermusch** [comment] 2020-10-05 16:08
Looks like this will be fixed by https://github.com/grpc/grpc/pull/23391.

**Comment by jtattermusch** [comment] 2020-10-05 16:10
Also, this is basically a dupe of https://github.com/grpc/grpc/issues/23622.

**Closed by jtattermusch** 2020-10-05 16:10 UTC
Labels: kind/enhancement, priority/P2
