### ISSUE TITLE
src/core/iomgr/udp_server.c fails to build in XCode

### ISSUE THREAD

**Issue by murgatroid99** [grpc/grpc#3041] opened 2015-08-24 19:43 UTC
When I `pod install` in src/objective-c/tests and then try to build the tests in the resulting `xcworkspace`, the build fails with an error that says "/Users/mlumish/grpc/src/core/iomgr/udp_server.c:240:39: Use of undeclared identifier '`IPV6_RECVPKTINFO`'"

However, if I build the C core from the command line with `make`, there is no such error

**Comment by murgatroid99** [comment] 2015-08-26 00:57
This issue has been sufficiently worked around for Beta, but only by preventing that line from being compiled in the iOS build. Which means that it will have to be fixed before that file will actually work on iOS.

**Comment by jcanizales** [comment] 2015-09-29 18:30
@rjshade: Apparently https://github.com/grpc/grpc/commit/a294487e37a8aeb47859423ee2fb6aec18cdae13 wasn't enough to get `IPV6_RECVPKTINFO` on iOS or OSX. Do you know what would be missing? [This forum comment](https://trac.macports.org/ticket/31614#comment:3) mentions some includes after the `#define`; maybe it's that? (It also uses a different RFC number, but I've confirmed that just changing it doesn't work).

**Comment by rjshade** [comment] 2015-09-29 20:22
@jcanizales I'm not sure, I remember that stumbling across the incantation in a294487e37a8aeb47859423ee2fb6aec18cdae13 took a bit of digging. Do you have an OSX environment to test this on (I don't have one handy)?

This looks like a plausible fix:
https://code.google.com/p/tunnelblick/source/browse/trunk/third_party/openvpn/openvpn-2.3-alpha1/patches/002-socket.c-IPV6_RECVPKTINFO.diff?r=2058

**Comment by jcanizales** [comment] 2015-09-29 20:50
In theory our Jenkins tests for the C library on Mac OS *should* catch this. But I also have an OS X environment to test if that doesn't work.

**Comment by hsaliak** [comment] 2016-04-29 19:05
@murgatroid99 is there anything further to do here? Can I close this issue?

**Comment by murgatroid99** [comment] 2016-04-29 20:01
I don't think we can just close this. The workaround I added just deletes a line of code if we're running on iOS. Unless something has changed since then, that file just won't work properly on iOS. I think it would be better to have a more nuanced solution.

**Comment by makdharma** [comment] 2016-05-02 22:39
This code has been restructured in src/core/lib/iomgr/socket_utils_common_posix.c and a define called GPR_HAVE_IPV6_RECVPKTINFO guards the use of IPV6_RECVPKTINFO. I don't see any problem with this so far. ctiller@ do you have any thoughts? I think this bug should be closed.

**Comment by murgatroid99** [comment] 2016-05-02 22:43
It looks like my workaround is no longer present, and it looks like it was replaced by proper handling, so I have no objection to closing this.

**Closed** 2016-05-02 22:52 UTC
Labels: core, MacOS, ObjC, P1
