### ISSUE TITLE
cpp/helloworld: LEAKED OBJECT on windows

### ISSUE THREAD

**Issue by chai2010** [grpc/grpc#2417] opened 2015-07-14 02:15 UTC
1. Install CMake and MSVC2012 and Perl
2. git clone https://github.com/chai2010/grpc-windows
3. open `PowerShell` and `cd build-windows`
4. run `build-openssl-win32.bat` to build openssl
5. run `build-debug-proj-mt.bat` to generate win32-debug project
6. open `zz_build_debug_proj_mt_tmp/GRPC.sln`
7. build `helloworld_server` and `helloworld_client`
8. run `helloworld_server.exe` and `helloworld_client.exe`

`helloworld_server.exe` output:

```
C:\go\ccpkg\grpc-windows\build-windows\zz_build_debug_proj_mt_tmp\Debug>helloworld_server.exe
Server listening on 0.0.0.0:50051
```

`helloworld_client.exe` output:

```
C:\go\ccpkg\grpc-windows\build-windows\zz_build_debug_proj_mt_tmp\Debug>helloworld_client.exe
Greeter received: Hello world
D0714 10:02:07.453000000  6444 C:\go\ccpkg\grpc-windows\src\core\iomgr\iomgr.c:163] Failed to free 1 iomgr objects before shutdown deadline: memory leaks are likely
D0714 10:02:07.453000000  6444 C:\go\ccpkg\grpc-windows\src\core\iomgr\iomgr.c:168] LEAKED OBJECT: client:socket=0x006323D8 00632468
```

**Comment by chai2010** [comment] 2015-07-14 02:49
grpc version 4d0b7427faecfdbb1635c2ab158c922d7511b865

**Comment by jtattermusch** [comment] 2015-07-14 05:03
Hi, this is basically a duplicate of #1650.

You missed the fix (https://github.com/grpc/grpc/pull/2416) by just a few commits. Can you update your code to the latest upstream/master version and try again?

**Comment by jtattermusch** [comment] 2015-07-14 05:05
Please let me know if you are still having trouble. Otherwise I will close this soon.

**Comment by chai2010** [comment] 2015-07-14 05:29
@jtattermusch The tip is OK. Thanks!

**Closed** 2015-07-14 05:35 UTC
