### ISSUE TITLE
WritesPerRpcTest.UnaryPingPong Fails on Mac

### ISSUE THREAD

**Issue by gnossen** [grpc/grpc#20096] opened 2019-08-28 00:03 UTC
```
2019-08-27 14:39:05,165 FAILED: bins/opt/writes_per_rpc_test --gtest_filter=WritesPerRpcTest.UnaryPingPong  GRPC_POLL_STRATEGY=poll
```

https://source.cloud.google.com/results/invocations/75c63dae-0f8f-4b47-b9a0-f4e75a2e3a6c/log

**Comment by jtattermusch** [comment] 2019-08-28 07:45
I'm seeing this on almost every PR now

**Comment by jtattermusch** [comment] 2019-08-28 07:48
Is this a dupe of https://github.com/grpc/grpc/issues/19819?

**Closed as completed** 2019-08-28 16:50 UTC
Labels: kind/bug, lang/c++, priority/P1, disposition/BUILDNURSE
