### ISSUE TITLE
C# package builds and distrib tests failing 100% on all platforms since morning of June 21 

### ISSUE THREAD

**Issue by apolcyn** [grpc/grpc#26546] opened 2021-06-24 05:09 UTC
C# builds and/or distrib tests are failing on all platforms since the morning of June 21, roughly somewhere between 9am and 11am. The initial build that started failing in all of these jobs appears to be on a re-run of commit `cf1ebf7387830cf7c69c6dbc931000b56ee048f5`, so it's not clearly a PR caused the regressions. Further, error logs are different enough that it's not clear whether or not all of these errors are even related.

See linux package builds: https://fusion.corp.google.com/projectanalysis/summary/KOKORO/prod:grpc%2Fcore%2Fmaster%2Flinux%2Fgrpc_build_packages

Example error:

```
/usr/share/dotnet/sdk/2.1.816/Sdks/NuGet.Build.Tasks.Pack/buildCrossTargeting/NuGet.Build.Tasks.Pack.targets(198,5): error : Could not find a part of the path '/var/local/git/grpc/src/csharp/nativelibs/csharp_ext_macos_x64'. [/var/local/git/grpc/src/csharp/Grpc.Core/Grpc.Core.csproj]
+ FAILED=true
+ '[' artifacts '!=' '' ']'
+ mkdir -p /tmpfs/src/github/grpc/artifacts
+ docker cp build_and_run_docker_dd0d32a0-deb7-4215-a639-c93ff8517226:/var/local/git/grpc/artifacts /tmpfs/src/github/grpc
+ docker rm -f build_and_run_docker_dd0d32a0-deb7-4215-a639-c93ff8517226
build_and_run_docker_dd0d32a0-deb7-4215-a639-c93ff8517226
+ '[' true '!=' '' ']'
+ exit 1

2021-06-23 19:48:23,027 FAILED: build_package.csharp_package_nuget_linux [ret=1, pid=9604, time=214.8sec]
```

linux distrib tests: https://fusion.corp.google.com/projectanalysis/summary/KOKORO/prod:grpc%2Fcore%2Fmaster%2Flinux%2Fgrpc_distribtests

Example error:

```
+ docker run -e RELATIVE_COPY_PATH=test/distrib -e RUN_COMMAND=test/distrib/csharp/run_distrib_test_dotnetcli.sh --cap-add SYS_PTRACE -e EXTERNAL_GIT_ROOT=/var/local/jenkins/grpc -e 'THIS_IS_REALLY_NEEDED=see https://github.com/docker/docker/issues/14203 for why docker is awful' -e KOKORO_BUILD_ID=30ae0769-1b93-4754-a87b-9ed476fb8b78 -e KOKORO_BUILD_NUMBER=15952 -e KOKORO_BUILD_URL= -e KOKORO_JOB_NAME=grpc/core/master/linux/grpc_distribtests -v /tmpfs/src/github/grpc:/var/local/jenkins/grpc:ro -w /var/local/git/grpc --name=build_and_run_docker_9aa507b1-0dad-4ede-8c38-e4e42f17e20d grpctesting/csharp_alpine_x64:ad69c44d058b83910b333f0c2ede094e73af465b /bin/bash -l /var/local/jenkins/grpc/tools/run_tests/dockerize/docker_run.sh
+ '[' test/distrib == '' ']'
+ mkdir -p /var/local/git/grpc/test/distrib
+ cp -r /var/local/jenkins/grpc/test/distrib/cpp /var/local/jenkins/grpc/test/distrib/csharp /var/local/jenkins/grpc/test/distrib/php /var/local/jenkins/grpc/test/distrib/python /var/local/jenkins/grpc/test/distrib/ruby /var/local/git/grpc/test/distrib
++ command -v rvm
+ '[' -x '' ']'
+ cd /var/local/git/grpc
+ test/distrib/csharp/run_distrib_test_dotnetcli.sh
++ dirname test/distrib/csharp/run_distrib_test_dotnetcli.sh
+ cd test/distrib/csharp
+ unzip -o /var/local/jenkins/grpc/input_artifacts/csharp_nugets_windows_dotnetcli.zip -d TestNugetFeed
unzip:  cannot find or open /var/local/jenkins/grpc/input_artifacts/csharp_nugets_windows_dotnetcli.zip, /var/local/jenkins/grpc/input_artifacts/csharp_nugets_windows_dotnetcli.zip.zip or /var/local/jenkins/grpc/input_artifacts/csharp_nugets_windows_dotnetcli.zip.ZIP.
+ FAILED=true
+ '[' '' '!=' '' ']'
+ docker rm -f build_and_run_docker_9aa507b1-0dad-4ede-8c38-e4e42f17e20d
build_and_run_docker_9aa507b1-0dad-4ede-8c38-e4e42f17e20d
+ '[' true '!=' '' ']'
+ exit 1

2021-06-23 20:17:30,053 FAILED: distribtest.csharp_linux_x64_alpine_dotnetcli [ret=1, pid=14636, time=39.1sec]
```

windows distrib tests: https://fusion.corp.google.com/projectanalysis/summary/KOKORO/prod:grpc%2Fcore%2Fmaster%2Fwindows%2Fgrpc_distribtests

Example error:

```
T:\src\github\grpc\workspace_csharp_windows_x86\test\distrib\csharp\DistribTest>nuget restore -PackagesDirectory ../packages   || goto :error


Invalid package version for package id 'Grpc': ''





T:\src\github\grpc\workspace_csharp_windows_x86\test\distrib\csharp\DistribTest>echo Failed!


Failed!





T:\src\github\grpc\workspace_csharp_windows_x86\test\distrib\csharp\DistribTest>exit /b 1




2021-06-23 20:22:46,265 FAILED: distribtest.csharp_windows_x86 [ret=1, pid=3752, time=62.4sec]
```

macos distrib tests: https://fusion.corp.google.com/projectanalysis/summary/KOKORO/prod:grpc%2Fcore%2Fmaster%2Fmacos%2Fgrpc_distribtests

Example error:

```
+ echo 'Running in workspace workspace_csharp_macos_x64'
Running in workspace workspace_csharp_macos_x64
+ cd workspace_csharp_macos_x64
+ test/distrib/csharp/run_distrib_test.sh
++ dirname test/distrib/csharp/run_distrib_test.sh
+ cd test/distrib/csharp
+ unzip -o ../../../../input_artifacts/csharp_nugets_windows_dotnetcli.zip -d TestNugetFeed
unzip:  cannot find or open ../../../../input_artifacts/csharp_nugets_windows_dotnetcli.zip, ../../../../input_artifacts/csharp_nugets_windows_dotnetcli.zip.zip or ../../../../input_artifacts/csharp_nugets_windows_dotnetcli.zip.ZIP.

2021-06-23 20:15:29,795 FAILED: distribtest.csharp_macos_x64 [ret=9, pid=24907, time=18.3sec]
```

**Comment by jtattermusch** [comment] 2021-06-24 09:09
Ok, this is actually not a problem with C# package_build and distribtests.
The real problem is that the macos artifact build (which precedes the build_package and distribtests steps) is broken and fails to generate any artifacts. subsequently, the build_package is missing the necessary macos C# artifacts and it fails.

The rootcause problem is tracked internally as b/191857029 and on github as https://github.com/grpc/grpc/issues/26522
https://fusion.corp.google.com/projectanalysis/summary/KOKORO/prod:grpc%2Fcore%2Fmaster%2Fmacos%2Fgrpc_build_artifacts

**Comment by jtattermusch** [comment] 2021-06-24 09:09
Closing as its a result of #26522

**Closed by jtattermusch** 2021-06-24 09:09 UTC
Labels: area/build, kind/bug, lang/C#, priority/P0/RELEASE BLOCKER

**Comment by jtattermusch** [comment] 2021-06-24 09:18
On a more general note, I see folks mis-identifying the rootcause of problems in the artifact - packages - distribtest flow way too often. Basically, I think the issue is that there are multiple jobs (artifact linux, artifact macos, artifact windows, build packages linux, distribtests linux, distribtests macos, distribtests windows) that are grouped/chained together and depend on each other's outcome, but from kokoro perspective, they are mostly presented as individual jobs and that makes finding the links between these jobs far from straightforward.

I think this is something we should fix going forward, otherwise we're going to see confusion and misinterpretation in the future as well. I've already done some work along these lines in https://github.com/grpc/grpc/pull/26176, but more work is needed to achieve similar results for other languages.
