### ISSUE TITLE
[Python install] using the command: "" docker build --tag=mediapipe . ""

### ISSUE THREAD

**Issue by dgrnd4** [grpc/grpc#24045] opened 2020-09-01 22:29 UTC
Hi there , with the command **docker build --tag=mediapipe .** i'm having this kind of problem using the powershell in windows:

  src/core/lib/iomgr/ev_epollex_linux.cc:977:57: note: an enum with different value name is defined in another translation unit
     typedef enum { WRR_NEW_ROOT, WRR_EMPTIED, WRR_REMOVED } worker_remove_result;
                                                             ^
    ./src/core/lib/iomgr/ev_posix.h:46:16: warning: type 'struct grpc_event_engine_vtable' violates the C++ One Definition Rule [-Wodr]
     typedef struct grpc_event_engine_vtable {
                    ^
    ./src/core/lib/iomgr/ev_posix.h:46:16: note: a different type is defined in another translation unit
     typedef struct grpc_event_engine_vtable {
                    ^
    ./src/core/lib/iomgr/ev_posix.h:51:65: note: the first difference of corresponding definitions is field 'fd_create'
       grpc_fd* (*fd_create)(int fd, const char* name, bool track_err);
                                                                     ^
    ./src/core/lib/iomgr/ev_posix.h:51:65: note: a field of same name but different type is defined in another translation unit
       grpc_fd* (*fd_create)(int fd, const char* name, bool track_err);
                                                                     ^
    src/core/lib/iomgr/ev_epoll1_linux.cc:141:8: warning: type 'struct grpc_fork_fd_list' violates the C++ One Definition Rule [-Wodr]
     struct grpc_fork_fd_list {
            ^
    src/core/lib/iomgr/ev_poll_posix.cc:68:8: note: a different type is defined in another translation unit
     struct grpc_fork_fd_list {
            ^
    src/core/lib/iomgr/ev_epoll1_linux.cc:142:12: note: the first difference of corresponding definitions is field 'fd'
       grpc_fd* fd;
                ^
    src/core/lib/iomgr/ev_poll_posix.cc:71:12: note: a field of same name but different type is defined in another translation unit
       grpc_fd* fd;
                ^
    ./src/core/lib/iomgr/ev_posix.h:44:24: note: type 'struct grpc_fd' should match type 'struct grpc_fd'
     typedef struct grpc_fd grpc_fd;
                            ^
    src/core/lib/iomgr/ev_epoll1_linux.cc:236:8: warning: type 'struct grpc_pollset_set' violates the C++ One Definition Rule [-Wodr]
     struct grpc_pollset_set {
            ^
    src/core/lib/iomgr/ev_poll_posix.cc:245:8: note: a different type is defined in another translation unit
     struct grpc_pollset_set {
            ^
    src/core/lib/iomgr/ev_epoll1_linux.cc:237:8: note: the first difference of corresponding definitions is field 'unused'
       char unused;
            ^
    src/core/lib/iomgr/ev_poll_posix.cc:246:10: note: a field with different name is defined in another translation unit
       gpr_mu mu;
              ^
    third_party/zlib/gzlib.c:252:9: warning: type of 'lseek' does not match original declaration [-Wlto-type-mismatch]
             LSEEK(state->fd, 0, SEEK_END);  /* so gzoffset() is correct */
             ^
    /usr/include/unistd.h:337:16: note: return value type mismatch
     extern __off_t lseek (int __fd, __off_t __offset, int __whence) __THROW;
                    ^
    /usr/include/x86_64-linux-gnu/bits/types.h:140:25: note: type '__off_t' should match type 'int'
     __STD_TYPE __OFF_T_TYPE __off_t; /* Type of file sizes and offsets.  */
                             ^
    /usr/include/unistd.h:337:16: note: 'lseek' was previously declared here
     extern __off_t lseek (int __fd, __off_t __offset, int __whence) __THROW;
                    ^
    /usr/include/unistd.h:337:16: note: code may be misoptimized unless -fno-strict-aliasing is used
    third_party/zlib/gzread.c:35:15: warning: type of 'read' does not match original declaration [-Wlto-type-mismatch]
             ret = read(state->fd, buf + *have, get);
                   ^
    /usr/include/x86_64-linux-gnu/bits/unistd.h:25:16: note: return value type mismatch
     extern ssize_t __REDIRECT (__read_alias, (int __fd, void *__buf,
                    ^
    /usr/include/x86_64-linux-gnu/sys/types.h:109:19: note: type 'ssize_t' should match type 'int'
     typedef __ssize_t ssize_t;
                       ^
    /usr/include/x86_64-linux-gnu/bits/unistd.h:25:16: note: '__read_alias' was previously declared here
     extern ssize_t __REDIRECT (__read_alias, (int __fd, void *__buf,
                    ^
    /usr/include/x86_64-linux-gnu/bits/unistd.h:25:16: note: code may be misoptimized unless -fno-strict-aliasing is used
    third_party/zlib/gzwrite.c:89:20: warning: type of 'write' does not match original declaration [-Wlto-type-mismatch]
                 writ = write(state->fd, strm->next_in, put);
                        ^
    /usr/include/unistd.h:369:16: note: return value type mismatch
     extern ssize_t write (int __fd, const void *__buf, size_t __n) __wur;
                    ^
    /usr/include/x86_64-linux-gnu/sys/types.h:109:19: note: type 'ssize_t' should match type 'int'
     typedef __ssize_t ssize_t;
                       ^
    /usr/include/unistd.h:369:16: note: 'write' was previously declared here
     extern ssize_t write (int __fd, const void *__buf, size_t __n) __wur;
                    ^
    /usr/include/unistd.h:369:16: note: code may be misoptimized unless -fno-strict-aliasing is used
    /tmp/ccI01wMz.ltrans1.ltrans.o: In function `grpc_core::(anonymous namespace)::XdsRoutingLb::RoutePicker::Pick(grpc_core::LoadBalancingPolicy::PickArgs)':
    <artificial>:(.text+0x3fc6): undefined reference to `__wrap_memcpy'
    <artificial>:(.text+0x3ff8): undefined reference to `__wrap_memcpy'
    <artificial>:(.text+0x40c9): undefined reference to `__wrap_memcpy'
    <artificial>:(.text+0x40f2): undefined reference to `__wrap_memcpy'
    /tmp/ccI01wMz.ltrans1.ltrans.o: In function `grpc_core::(anonymous namespace)::EdsLb::CreateChildPolicyConfigLocked()':
    <artificial>:(.text+0xe747): undefined reference to `__wrap_memcpy'
    /tmp/ccI01wMz.ltrans1.ltrans.o:<artificial>:(.text+0xe892): more undefined references to `__wrap_memcpy' follow
    collect2: error: ld returned 1 exit status
    Traceback (most recent call last):
      File "/usr/local/lib/python3.6/dist-packages/setuptools/_distutils/unixccompiler.py", line 204, in link
        self.spawn(linker + ld_args)
      File "/tmp/pip-build-nsqngj12/grpcio/src/python/grpcio/_spawn_patch.py", line 54, in _commandfile_spawn
        _classic_spawn(self, command)
      File "/usr/local/lib/python3.6/dist-packages/setuptools/_distutils/ccompiler.py", line 910, in spawn
        spawn(cmd, dry_run=self.dry_run, **kwargs)
      File "/usr/local/lib/python3.6/dist-packages/setuptools/_distutils/spawn.py", line 88, in spawn
        "command %r failed with exit code %s" % (cmd, exitcode))
    distutils.errors.DistutilsExecError: command '/usr/bin/x86_64-linux-gnu-g++' failed with exit code 1

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/tmp/pip-build-nsqngj12/grpcio/src/python/grpcio/commands.py", line 264, in build_extensions
        build_ext.build_ext.build_extensions(self)
      File "/usr/local/lib/python3.6/dist-packages/setuptools/_distutils/command/build_ext.py", line 449, in build_extensions
        self._build_extensions_serial()
      File "/usr/local/lib/python3.6/dist-packages/setuptools/_distutils/command/build_ext.py", line 474, in _build_extensions_serial
        self.build_extension(ext)
      File "/usr/local/lib/python3.6/dist-packages/setuptools/command/build_ext.py", line 196, in build_extension
        _build_ext.build_extension(self, ext)
      File "/usr/local/lib/python3.6/dist-packages/setuptools/_distutils/command/build_ext.py", line 560, in build_extension
        target_lang=language)
      File "/usr/local/lib/python3.6/dist-packages/setuptools/_distutils/ccompiler.py", line 717, in link_shared_object
        extra_preargs, extra_postargs, build_temp, target_lang)
      File "/usr/local/lib/python3.6/dist-packages/setuptools/_distutils/unixccompiler.py", line 206, in link
        raise LinkError(msg)
    distutils.errors.LinkError: command '/usr/bin/x86_64-linux-gnu-g++' failed with exit code 1

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-nsqngj12/grpcio/setup.py", line 427, in <module>
        cmdclass=COMMAND_CLASS,
      File "/usr/local/lib/python3.6/dist-packages/setuptools/__init__.py", line 153, in setup
        return distutils.core.setup(**attrs)
      File "/usr/local/lib/python3.6/dist-packages/setuptools/_distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/local/lib/python3.6/dist-packages/setuptools/_distutils/dist.py", line 967, in run_commands
        self.run_command(cmd)
      File "/usr/local/lib/python3.6/dist-packages/setuptools/_distutils/dist.py", line 986, in run_command
        cmd_obj.run()
      File "/usr/local/lib/python3.6/dist-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/usr/local/lib/python3.6/dist-packages/setuptools/_distutils/command/install.py", line 566, in run
        self.run_command('build')
      File "/usr/local/lib/python3.6/dist-packages/setuptools/_distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/local/lib/python3.6/dist-packages/setuptools/_distutils/dist.py", line 986, in run_command
        cmd_obj.run()
      File "/usr/local/lib/python3.6/dist-packages/setuptools/_distutils/command/build.py", line 135, in run
        self.run_command(cmd_name)
      File "/usr/local/lib/python3.6/dist-packages/setuptools/_distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/local/lib/python3.6/dist-packages/setuptools/_distutils/dist.py", line 986, in run_command
        cmd_obj.run()
        _build_ext.run(self)
      File "/usr/local/lib/python3.6/dist-packages/setuptools/_distutils/command/build_ext.py", line 340, in run
        self.build_extensions()
      File "/tmp/pip-build-nsqngj12/grpcio/src/python/grpcio/commands.py", line 267, in build_extensions
        support.diagnose_build_ext_error(self, error, formatted_exception)
      File "/tmp/pip-build-nsqngj12/grpcio/src/python/grpcio/support.py", line 116, in diagnose_build_ext_error
        "backtrace).\n\n{}".format(formatted))
    commands.CommandError:

    We could not diagnose your build failure. If you are unable to proceed, please file an issue at http://www.github.com/grpc/grpc with `[Python install]` in the title; please attach the whole log (including everything that may have appeared above the Python backtrace).

    Traceback (most recent call last):
      File "/usr/local/lib/python3.6/dist-packages/setuptools/_distutils/unixccompiler.py", line 204, in link
        self.spawn(linker + ld_args)
      File "/tmp/pip-build-nsqngj12/grpcio/src/python/grpcio/_spawn_patch.py", line 54, in _commandfile_spawn
        _classic_spawn(self, command)
      File "/usr/local/lib/python3.6/dist-packages/setuptools/_distutils/ccompiler.py", line 910, in spawn
        spawn(cmd, dry_run=self.dry_run, **kwargs)
      File "/usr/local/lib/python3.6/dist-packages/setuptools/_distutils/spawn.py", line 88, in spawn
        "command %r failed with exit code %s" % (cmd, exitcode))
    distutils.errors.DistutilsExecError: command '/usr/bin/x86_64-linux-gnu-g++' failed with exit code 1

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/tmp/pip-build-nsqngj12/grpcio/src/python/grpcio/commands.py", line 264, in build_extensions
        build_ext.build_ext.build_extensions(self)
      File "/usr/local/lib/python3.6/dist-packages/setuptools/_distutils/command/build_ext.py", line 449, in build_extensions
        self._build_extensions_serial()
      File "/usr/local/lib/python3.6/dist-packages/setuptools/_distutils/command/build_ext.py", line 474, in _build_extensions_serial
        self.build_extension(ext)
      File "/usr/local/lib/python3.6/dist-packages/setuptools/command/build_ext.py", line 196, in build_extension
        _build_ext.build_extension(self, ext)
      File "/usr/local/lib/python3.6/dist-packages/setuptools/_distutils/command/build_ext.py", line 560, in build_extension
        target_lang=language)
      File "/usr/local/lib/python3.6/dist-packages/setuptools/_distutils/ccompiler.py", line 717, in link_shared_object
        extra_preargs, extra_postargs, build_temp, target_lang)
      File "/usr/local/lib/python3.6/dist-packages/setuptools/_distutils/unixccompiler.py", line 206, in link
        raise LinkError(msg)
    distutils.errors.LinkError: command '/usr/bin/x86_64-linux-gnu-g++' failed with exit code 1

    ----------------------------------------
Command "/usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-nsqngj12/grpcio/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-ba9bqe62-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-nsqngj12/grpcio/
The command '/bin/sh -c pip3 install tensorflow==1.14.0' returned a non-zero code: 1

**Comment by dgrnd4** [comment] 2020-09-01 22:40
if is better, that's a txt with the problem 
[errore.txt](https://github.com/grpc/grpc/files/5159134/errore.txt)

**Comment by lidizheng** [comment] 2020-09-02 01:01
This is likely share the same root cause as https://github.com/grpc/grpc/issues/24028. Can you try to specify `SETUPTOOLS_USE_DISTUTILS=stdlib` environment variable and build again?

**Comment by dgrnd4** [comment] 2020-09-02 09:20
To specify SETUPTOOLS_USE_DISTUTILS=stdlib environment variable are these the right steps?
- go to computer, right click -> propiety
- advanced field -> environment variable
- i added the variable for the account that i'm using in windows and for the whole system as in the photo 
![envirnment variable](https://user-images.githubusercontent.com/69434832/91963555-48819b80-ed0e-11ea-8886-9689424fb136.PNG)

Is that right? and after that is ok just press ok, right?

**Comment by dgrnd4** [comment] 2020-09-02 09:37
i did it but still the problem. Below the whole problem showed 
[errore.txt](https://github.com/grpc/grpc/files/5161388/errore.txt)

**Comment by lidizheng** [comment] 2020-09-02 16:30
@dgrnd4 You are using Docker. So, setting the Windows environment variable is not sufficient.

Another path is that you can downgrade `setuptools` version to < 50? For example, `44.1.1`.

**Comment by dgrnd4** [comment] 2020-09-02 16:36
Do you think that now is it fine?

If you read my error , the last sentence says that:
**The command '/bin/sh -c pip3 install tensorflow==1.14.0' returned a non-zero code: 1**

that means something for you?

However downgraded setuptools by the command **pip install setuptools==44.1.1**
Do you think that is fine and i can build it again?

**Comment by XuanWang-Amos** [comment] 2023-04-11 22:17
Closing this issue since we're no longer support versions below 1.46.0, if this issue still exist, feel free to reopen or create a new issue.

**Closed by XuanWang-Amos** 2023-04-11 22:17 UTC
Labels: kind/bug, lang/Python, priority/P2
