### ISSUE TITLE
python _server_ssl_cert_config_test.ServerSSLCertReloadTestWithClientAuth is flaky

### ISSUE THREAD

**Issue by jtattermusch** [grpc/grpc#17138] opened 2018-11-07 15:37 UTC
Started flaking recently, first occurrence after flakines rate went up (to ~20% ) is 
https://source.cloud.google.com/results/invocations/60ee131b-25eb-42fc-86b5-b76c6687192b

other instances:
https://source.cloud.google.com/results/invocations/093c7eb5-db48-4c81-b8b5-300ecdb1c1ac
https://source.cloud.google.com/results/invocations/06a07e16-9919-4e56-8343-5c65b789adab

**Comment by jtattermusch** [comment] 2018-11-07 15:39
```
Errors/Failures:
[91munit._server_ssl_cert_config_test.ServerSSLCertReloadTestWithoutClientAuth.test[0m
[1mtraceback:[0m
Traceback (most recent call last):
  File "/usr/lib/python2.7/unittest/case.py", line 329, in run
    testMethod()
  File "/var/local/git/grpc/src/python/grpcio_tests/tests/unit/_server_ssl_cert_config_test.py", line 354, in _test
    self.assertEqual(len(actual_calls), 0)
  File "/usr/lib/python2.7/unittest/case.py", line 513, in assertEqual
    assertion_func(first, second, msg=msg)
  File "/usr/lib/python2.7/unittest/case.py", line 506, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 1 != 0
[1mstdout:[0m
[1mstderr:[0m
E1106 13:27:47.989212566   10442 ssl_transport_security.cc:1229] Handshake failed with fatal error SSL_ERROR_SSL: error:1000007d:SSL routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED.
E1106 13:27:47.996206294   10442 ssl_transport_security.cc:1229] Handshake failed with fatal error SSL_ERROR_SSL: error:1000007d:SSL routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED.
ERROR:grpc._cython.cygrpc:Error fetching certificate config
Traceback (most recent call last):
  File "src/python/grpcio/grpc/_cython/_cygrpc/credentials.pyx.pxi", line 306, in grpc._cython.cygrpc._server_cert_config_fetcher_wrapper
  File "/var/local/git/grpc/src/python/grpcio_tests/tests/unit/_server_ssl_cert_config_test.py", line 122, in __call__
    raise ValueError('just for fun, should not affect the test')
ValueError: just for fun, should not affect the test
E1106 13:27:48.010822932   10459 ssl_security_connector.cc:173] Failed fetching new server credentials, continuing to use previously-loaded credentials.
E1106 13:27:48.643280685   10442 ssl_transport_security.cc:1229] Handshake failed with fatal error SSL_ERROR_SSL: error:1000007d:SSL routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED.
E1106 13:27:48.674066540   10442 ssl_transport_security.cc:1229] Handshake failed with fatal error SSL_ERROR_SSL: error:1000007d:SSL routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED.
E1106 13:27:48.974190579   10452 ssl_transport_security.cc:1229] Handshake failed with fatal error SSL_ERROR_SSL: error:1000007d:SSL routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED.
E1106 13:27:48.980019495   10442 ssl_transport_security.cc:1229] Handshake failed with fatal error SSL_ERROR_SSL: error:1000007d:SSL routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED.
```

@lidizheng  please bisect to find out the root cause.

**Comment by lidizheng** [comment] 2018-11-07 21:11
A quick note that there are two failed unit tests:
* ServerSSLCertReloadTest**With**ClientAuth
* ServerSSLCertReloadTest**Without**ClientAuth

Didn't find a way to reproduce it. Trying to statically find the bug in the testing logic...

**Comment by lidizheng** [comment] 2018-11-08 02:12
This bug can be reproduced by:

```bash
#!/bin/bash -ex

GRPC_PYTHON_TESTRUNNER_FILTER=unit._server_ssl_cert_config_test.ServerSSLCertReloadTestWithClientAuth

for i in {1..30}
do
  python src/python/grpcio_tests/setup.py test_lite&
done
```

**Comment by lidizheng** [comment] 2018-11-09 21:47
Another quick note about bisecting the root cause, this unit test:
* Failed at 1.14.1
* Passed at 1.8.0
* Passed at 1.10.0
* Failed at 1.12.0

Keep updating...

**Comment by lidizheng** [comment] 2018-11-12 22:19
I bisected the commit, and found the commit that breaks this unit test:
```
lidiz@ddev:~/src/grpc$ git bisect bad
ca7ba4d0ac3ab452c5db60befc8be37fd6e2339b is the first bad commit
commit ca7ba4d0ac3ab452c5db60befc8be37fd6e2339b
Author: Nathaniel Manista <nathaniel@google.com>
Date:   Fri Apr 20 02:49:34 2018 +0000

    Keep Core memory inside cygrpc.Channel objects

    This removes invocation-side completion queues from the _cygrpc API.
    Invocation-side calls are changed to no longer share the same lifetime
    as Core calls.

    Illegal metadata is now detected on invocation rather than at the start
    of a batch (so passing illegal metadata to a response-streaming method
    will now raise an exception immediately rather than later on when
    attempting to read the first response message).

    It is no longer possible to create a call without immediately starting
    at least one batch of operations on it. Only tests are affected by this
    change; there are no real use cases in which one wants to start a call
    but wait a little while before learning that the server has rejected
    it.

    It is now required that code above cygrpc.Channel spend threads on
    next_event whenever events are pending. A cygrpc.Channel.close method
    is introduced, but it merely blocks until the cygrpc.Channel's
    completion queues are drained; it does not itself drain them.

    Noteworthy here is that we drop the cygrpc.Channel.__dealloc__ method.
    It is not the same as __del__ (which is not something that can be added
    to cygrpc.Channel) and there is no guarantee that __dealloc__ will be
    called at all or that it will be called while the cygrpc.Channel
    instance's Python attributes are intact (in testing, I saw both in
    different environments). This commit does not knowingly break any
    garbage-collection-based memory management working (or "happening to
    appear to work in some circumstances"), though if it does, the proper
    remedy is to call grpc.Channel.close... which is the objective towards
    which this commit builds.

:040000 040000 5b30f47e4720728758b3efd1ad7577c6bf72596f bdf8d4c2648eed9d1ed8de0f001a74653befa6a9 M	src
```

**Comment by jtattermusch** [comment] 2018-11-20 15:14
This is currently one of our top flakes (flakiness rate >10%)

**Comment by jtattermusch** [comment] 2018-11-20 15:19
CC @ericgribkoff

**Comment by ericgribkoff** [comment] 2018-11-21 03:05
Fixed by https://github.com/grpc/grpc/pull/17260

**Closed by ericgribkoff** 2018-11-21 03:05 UTC
Labels: infra/BUILDPONY, kind/internal cleanup, lang/Python, priority/P1
