### ISSUE TITLE
c_windows_opt.vsprojects/Release/h2_http_proxy_nosec_test.exe connectivity

### ISSUE THREAD

**Issue by matt-kwong** [grpc/grpc#9153] opened 2016-12-16 22:56 UTC
https://grpc-testing.appspot.com/job/gRPC_master_windows/888/testReport/junit/(root)/c_windows_opt/vsprojects_Release_h2_http_proxy_nosec_test_exe_connectivity/

`D1216 04:08:30.687000000  4408 test_config.c:290] test slowdown: machine=1.000000 build=1.000000 poll=1.000000 total=1.000000
I1216 04:08:30.693000000  4408 http_proxy.c:429] Proxy address: localhost:2480
D1216 04:08:30.694000000  4932 connectivity.c:55] verifying
D1216 04:08:30.794000000  4408 connectivity.c:97] watching
I1216 04:08:30.796000000 11032 http_connect_handshaker.c:282] Connecting to server localhost:2478 via HTTP proxy localhost:2480
I1216 04:08:31.796000000 11032 subchannel.c:681] Connect failed: {"created":"@1481861311.796000000","description":"End of TCP stream","file":"C:\jenkins\workspace\gRPC_master_windows\workspace_c_windows_opt\vsprojects\..\src\core\lib\iomgr\tcp_windows.c","file_line":184}
I1216 04:08:31.796000000 11032 http_connect_handshaker.c:282] Connecting to server localhost:2478 via HTTP proxy localhost:2480
I1216 04:08:31.801000000 11032 http_proxy.c:131] HTTP proxy server connect: {"created":"@1481861311.801000000","description":"OS Error","file":"C:\jenkins\workspace\gRPC_master_windows\workspace_c_windows_opt\vsprojects\..\src\core\lib\iomgr\tcp_client_windows.c","file_line":119,"os_error":"No connection could be made because the target machine actively refused it.\r\n","syscall":"ConnectEx","wsa_error":10061}
I1216 04:08:32.796000000 11032 subchannel.c:681] Connect failed: {"created":"@1481861312.796000000","description":"End of TCP stream","file":"C:\jenkins\workspace\gRPC_master_windows\workspace_c_windows_opt\vsprojects\..\src\core\lib\iomgr\tcp_windows.c","file_line":184}
I1216 04:08:32.796000000 11032 subchannel.c:478] Retry immediately
I1216 04:08:32.796000000 11032 subchannel.c:430] Failed to connect to channel, retrying
I1216 04:08:32.797000000 11032 http_connect_handshaker.c:282] Connecting to server localhost:2478 via HTTP proxy localhost:2480
D1216 04:08:32.797000000  4408 connectivity.c:129] *** STARTING SERVER ***
D1216 04:08:32.800000000  4408 connectivity.c:134] *** STARTED SERVER ***
I1216 04:08:32.802000000 11032 http_proxy.c:131] HTTP proxy client read: {"created":"@1481861312.802000000","description":"An established connection was aborted by the software in your host machine.\r\n","file":"C:\jenkins\workspace\gRPC_master_windows\workspace_c_windows_opt\vsprojects\..\src\core\lib\iomgr\tcp_windows.c","file_line":175}
I1216 04:08:32.802000000 11032 http_proxy.c:131] HTTP proxy server read: {"created":"@1481861312.802000000","description":"End of TCP stream","file":"C:\jenkins\workspace\gRPC_master_windows\workspace_c_windows_opt\vsprojects\..\src\core\lib\iomgr\tcp_windows.c","file_line":184}
D1216 04:08:33.303000000  4408 connectivity.c:151] *** SHUTTING DOWN SERVER ***
E1216 04:08:36.304000000  4408 cq_verifier.c:184] assertion failed: e->success == ev->success
Abort handler called.
*** 0: 0000000000B72A8E  - 0000000000000000
*** 1: 0000000000B72D7A  - 0000000000000000
*** 2: 0000000000BE278B  - 0000000000000000
*** 3: 0000000000BD1EF9  - 0000000000000000
*** 4: 0000000000BD20D9  - 0000000000000000
*** 5: 0000000000BBAB8C  - 0000000000000000
*** 6: 0000000000B71239  - 0000000000000000
*** 7: 0000000000BE28BC  - 0000000000000000
*** 8: 000000007544336A BaseThreadInitThunk - 0000000075443358
*** 9: 0000000077879902 RtlInitializeExceptionChain - 000000007787989F
*** 10: 00000000778798D5 RtlInitializeExceptionChain - 000000007787989F`

Similar to: #9088

**Comment by nathanielmanistaatgoogle** [comment] 2017-01-05 21:25
Seen in [`gRPC_master_windows` build 1120](https://grpc-testing.appspot.com/job/gRPC_master_windows/1120/testReport/junit/(root)/c_windows_opt/vsprojects_Release_h2_http_proxy_nosec_test_exe_connectivity/).

**Comment by dgquintas** [comment] 2017-02-01 17:41
@nicolasnoble could you disable this and similar tests on Windows while the issue is addressed?

**Comment by apolcyn** [comment] 2017-04-25 02:52
same error seen again on waht looks like all recent windows master runs.

a log is in https://grpc-testing.appspot.com/job/gRPC_master_windows/2366/testReport/junit/(root)/c_windows_opt_native/vsprojects_Release_h2_http_proxy_test_exe_connectivity/

**Comment by ericgribkoff** [comment] 2017-05-03 00:23
Seen again: https://grpc-testing.appspot.com/job/gRPC_master_windows/2421/

**Comment by jtattermusch** [comment] 2017-05-05 07:44
@nicolasnoble we can't have an issue marked as P0 stay around for a month. I've made this a P1. If you don't have cycles, please reassign.

**Comment by murgatroid99** [comment] 2017-05-17 16:31
Seen again on master: https://grpc-testing.appspot.com/job/gRPC_master_windows/2510/testReport/junit/(root)/c_windows_opt_native/vsprojects_Release_h2_http_proxy_nosec_test_exe_connectivity/

**Comment by muxi** [comment] 2017-05-18 05:12
Still happening on master:
https://grpc-testing.appspot.com/job/gRPC_master_windows/2571/

**Comment by makdharma** [comment] 2017-05-31 22:48
Should be fixed with #11224

**Closed by makdharma** 2017-05-31 22:48 UTC
Labels: BUILDPONY, P1, Windows
