### ISSUE TITLE
linux/grpc_build_packages failing on Ruby package build (CBF)

### ISSUE THREAD

**Issue by ananda1066** [grpc/grpc#26675] opened 2021-07-13 17:37 UTC
Looks like protoc_macos artifact is failing to build in linux/grpc_build_packages since July 5:

```
+ [[ macos_x64 == \m\a\c\o\s\_\x\8\6 ]]
+ input_dir=/var/local/jenkins/grpc/input_artifacts/protoc_macos_x64
+ output_dir=/var/local/git/grpc/src/ruby/tools/bin/x86_64-macos
+ mkdir -p /var/local/git/grpc/src/ruby/tools/bin/x86_64-macos/google/protobuf
+ mkdir -p /var/local/git/grpc/src/ruby/tools/bin/x86_64-macos/google/protobuf/compiler
+ cp '/var/local/jenkins/grpc/input_artifacts/protoc_macos_x64/protoc*' '/var/local/jenkins/grpc/input_artifacts/protoc_macos_x64/grpc_ruby_plugin*' /var/local/git/grpc/src/ruby/tools/bin/x86_64-macos/
cp: cannot stat `/var/local/jenkins/grpc/input_artifacts/protoc_macos_x64/protoc*': No such file or directory
cp: cannot stat `/var/local/jenkins/grpc/input_artifacts/protoc_macos_x64/grpc_ruby_plugin*': No such file or directory
+ FAILED=true
```

Example failure: https://source.cloud.google.com/results/invocations/a46267f6-2f6d-4ecd-bbfe-32f1773de2cc/targets/github%2Fgrpc/tests;group=tasks;test=build_package.ruby_package;row=2

**Comment by jtattermusch** [comment] 2022-01-20 11:05
Seems like the issue is long gone (original reported in July 2021). Closing.

**Closed by jtattermusch** 2022-01-20 11:05 UTC
Labels: kind/bug, lang/ruby, priority/P1
