### ISSUE TITLE
Objective C tests seem flaky on Jenkins

### ISSUE THREAD

**Issue by nicolasnoble** [grpc/grpc#6117] opened 2016-04-07 18:15 UTC
https://grpc-testing.appspot.com/job/grpc_master_test/config=opt,language=objc,platform=macos/

**Comment by makdharma** [comment] 2016-04-08 14:19
hi Nico, the failure seems to be in the interopTestRemote, which actually
tries to access a remote server. This could be the result of flaky network.
I will disable this test for now and see if flake goes away.

**Comment by makdharma** [comment] 2016-04-15 23:14
I confirmed that this flake happens on my macbook as well. Roughly 1 in 5 times.

**Comment by makdharma** [comment] 2016-04-18 17:39
Attaching the client log from a failed test.
[fail_log.txt](https://github.com/grpc/grpc/files/224341/fail_log.txt)

**Comment by makdharma** [comment] 2016-04-18 18:01
Full log (earlier log was partial).
[failed_log.txt](https://github.com/grpc/grpc/files/224378/failed_log.txt)

**Comment by jcanizales** [comment] 2016-04-18 18:04
These are the relevant parts:

```
I0418 10:34:35.187737000 123145305063424 completion_queue.c:346] RETURN_EVENT[0x7f823960c130]: OP_COMPLETE: tag:0x7f82395414a0 OK <<???>>

I0418 10:34:35.187854000 123145305063424 completion_queue.c:346] RETURN_EVENT[0x7f823960c130]: OP_COMPLETE: tag:0x7f823bb00e10 OK <<???>>

I0418 10:34:35.187946000 123145303453696 call.c:1473] grpc_call_start_batch(call=0x7f823a00ce00, ops=0x7f82394ca760, nops=1, tag=0x7f82394c7350, reserved=0x0)
I0418 10:34:35.188004000 123145303453696 call.c:1185] ops[0]: SEND_CLOSE_FROM_CLIENT
[...]
I0418 10:34:35.188339000 123145305063424 completion_queue.c:346] RETURN_EVENT[0x7f823960c130]: OP_COMPLETE: tag:0x7f82394c7350 OK <<SEND_CLOSE_FROM_CLIENT>>
[...]
I0418 10:34:35.575792000 123145305063424 completion_queue.c:346] RETURN_EVENT[0x7f823960c130]: OP_COMPLETE: tag:0x7f82397bae80 OK <<???>>

I0418 10:34:35.576128000 123145303453696 call.c:1473] grpc_call_start_batch(call=0x7f823a00ce00, ops=0x7f8239548ba0, nops=1, tag=0x7f8239548bf0, reserved=0x0)

I0418 10:34:35.576259000 123145303453696 call.c:1185] ops[0]: RECV_MESSAGE ptr=0x7f8239548b10
[...]
I0418 10:34:35.576852000 123145305063424 completion_queue.c:346] RETURN_EVENT[0x7f823960c130]: OP_COMPLETE: tag:0x7f82397baf30 OK <<???>>

I0418 10:34:35.577183000 123145305063424 completion_queue.c:295] grpc_completion_queue_next(cc=0x7f823960c130, deadline=gpr_timespec { tv_sec: 9223372036854775807, tv_nsec: 0, clock_type: 1 }, reserved=0x0)
[...]
/Users/makarandd/Work/gitx/grpc_flake_debug/src/objective-c/tests/InteropTests.m:100: error: -[InteropTestsRemote testEmptyUnaryRPC] : ((error) == nil) failed: "Error Domain=io.grpc Code=13 "The writer finished without producing any value." UserInfo={NSLocalizedDescription=The wri \

I0418 10:34:35.577315000 123145305063424 completion_queue.c:346] RETURN_EVENT[0x7f823960c130]: OP_COMPLETE: tag:0x7f8239548bf0 OK \ <<RECV_MESSAGE>>

ter finished without producing any value.}" - Finished with unexpected error: Error Domain=io.grpc Code=13 "The writer finished without producing any value." UserInfo={NSLocalizedDescription=The writer finished without producing any value.}

```

**Comment by jcanizales** [comment] 2016-04-18 18:11
Four of the tags correspond to `grpc_call_start_batch` invocations above the fold. (Can we remove the grpc_auth_property_iterator_next log, or move it to another trace key?)

The two for which we have the corresponding invocations are `SEND_CLOSE_FROM_CLIENT` and `RECV_MESSAGE`. `RECV_MESSAGE` shows up in the completion queue after tag `0x7f82397baf30`, which might be the tag that triggers the call to finish (receive status & trailers).

**Comment by jcanizales** [comment] 2016-04-18 18:26
These are the 6 ops sent during a unary call, so at least the count of tags coming back from the completion queue is right:

`GRPCOpSendMetadata`
`GRPCOpSendMessage`
`GRPCOpSendClose`

`GRPCOpRecvMetadata`
`GRPCOpRecvMessage`
`GRPCOpRecvStatus`

**Comment by jcanizales** [comment] 2016-04-18 18:30
Just saw the full log now; updating it :)

**Comment by hsaliak** [comment] 2016-04-29 18:35
Tracked in #6207 closing this.

**Closed by hsaliak** 2016-04-29 18:35 UTC
Labels: ObjC
