### ISSUE TITLE
GPR_UNREACHABLE_CODE causes warnings in ios

### ISSUE THREAD

**Issue by y-zeng** [grpc/grpc#6979] opened 2016-06-21 18:05 UTC
GPR_UNREACHABLE_CODE causes "control may reach end of non-void function" warnings in ios.
#6922 silenced this warning in objective-c tests temporarily.

**Comment by jcanizales** [comment] 2016-06-24 18:37
This is a duplicate of https://github.com/grpc/grpc/issues/6118

**Closed by jcanizales** 2016-06-24 18:37 UTC
Labels: core
