### ISSUE TITLE
Port remains in 'Listening' state after disposing of Grpc.Core.Server

### ISSUE THREAD

**Issue by Somer-Sault** [grpc/grpc#30167] opened 2022-07-01 12:21 UTC
### What version of gRPC and what language are you using?
C#
Nugets:
```
Grpc.Core.Api 2.46.3
Grpc.Tools 2.47.0
Google.Protobuf 3.21.2
```

Unit tests nugets:
```
NUnit 3.13.3
NUnit3TestAdapter 4.2.1
```
### What operating system (Linux, Windows,...) and version?
``` Windows 10,  20H2 OS build 19042.1766```

### What runtime / compiler are you using (e.g. python version or version of gcc)
```.NET Framework 4.7```

### What did you do?
Ran test:
```
    [Test]
    public async Task GRPC_ServerDisposingTest()
    {
      string host = "0.0.0.0";
      int port = 10555;

      var server = new global::Grpc.Core.Server();
      var serverPort = new ServerPort(host, port, ServerCredentials.Insecure);
      if (server.Ports.Add(serverPort) == 0)
        throw new Exception($"Adding port {Port} has failed 1 ");

      //server.Start();

      await server.ShutdownAsync();
      // Port is still in 'listening' state after the shutdown, unless you explicitly call server.Start() before

      server = new Server();
      serverPort = new ServerPort(host, port, ServerCredentials.Insecure);
      if (server.Ports.Add(serverPort) == 0)
        throw new Exception($"Adding port {Port} has failed 2");
      await server.ShutdownAsync();
    }
```

### What did you expect to see?
When created second time, the server should allow to add port successfullly.

### What did you see instead?
Exception "_Adding port {Port} has failed 2_" raised as the port still in 'listening' state after the first server shutdown. I've used ```netstat -ano```  in cmd line or with ```Get-NetTCPConnection -LocalPort 10555``` in PowerShell to check.

### Anything else we should know about your project / environment?
Users have noticed a similar problem a couple of times on the product env.
The console app (see below) periodically throws the exception "_Adding port {Port} has failed_" only much less often in comparison to the unit test (which  reproduces it regurarly). It made me think that the cause maybe in race conditions in the c-library...
```C#
    static async Task Main(string[] args)
    {
      for (int i = 0; i < 10; i++)
      {
        try
        {
          // Init server
          var server = new Server();

          // Register port
          if (server.Ports.Add(new ServerPort("0.0.0.0", Port, ServerCredentials.Insecure)) == 0)
            throw new Exception($"Adding port {Port} has failed");

          // Dispose
          await server.ShutdownAsync();
        }
        catch (Exception e)
        {
          Console.WriteLine($"{i} FAIL:{e.Message}");
        }
      }
    Console.ReadKey();
}
```

As a _workaround_ - call ```server.Start()``` before the first server shutdown (commented line in the test above). Seems it somehow triggers port's disposal.

Attached grpc trace after the unit tests execution with the following flags:
```
GRPC_TRACE all
GRPC_VERBOSITY debug
```
[trace_PR32302.txt](https://github.com/grpc/grpc/files/9028729/trace_PR32302.txt)

**Comment by tonydnewell** [comment] 2022-07-09 10:59
Investigating.

Is there any reason why you don't want to call `server.Start()` - that seems to be a good workaround?

I can reproduce the issue and I've attached some logs for the cases with and without `server.Start()` with API tracing `GRPC_TRACE=api`

[issue30167-noStart.txt](https://github.com/grpc/grpc/files/9076332/issue30167-noStart.txt)
[issue30167-withStart.txt](https://github.com/grpc/grpc/files/9076333/issue30167-withStart.txt)

**Comment by Somer-Sault** [comment] 2022-07-11 06:14
Hi @tonydnewell, 
In general, it's not from practical usage - just has been revealed from one of the unit tests' scenario.

**Comment by tonydnewell** [comment] 2022-07-18 11:16
I think that is either an API misuse (must call Start()) or an internal C core issue and not something particular to the C# implementation.

When a port is added the server immediately binds to the port and starts listening. In the native code this eventually calls
`Chttp2ServerAddPort()` which creates a listener with `Chttp2ServerListener::Create()`

The shutdown path for both cases (with and without `server.Start()`) is identical in the C# layer - both calling the native method `grpc_shutdown_and_notify()`

**Comment by tonydnewell** [comment] 2022-08-01 09:37
Duplicate of https://github.com/grpc/grpc/issues/23390

**Comment by tonydnewell** [comment] 2022-08-04 10:14
Exactly the same behaviour with the _Python_ API - stopping the server without first starting it leaves a port in the listening state.

```python
    # Python example reproducing the same problem
    server = grpc.server(futures.ThreadPoolExecutor(max_workers=10))
    helloworld_pb2_grpc.add_GreeterServicer_to_server(Greeter(), server)
    server.add_insecure_port('[::]:50051')
    print("Added listening port 50051, sleeping...", flush=True)
    time.sleep(10)

    # don't do the start
    # print("Starting", flush=True)
    # server.start()

    print("Stopping", flush=True)
    server.stop(None)

    print("Sleeping for 10 seconds", flush=True)
    time.sleep(10)

    print("Starting new server", flush=True)
    server2 = grpc.server(futures.ThreadPoolExecutor(max_workers=10))
    helloworld_pb2_grpc.add_GreeterServicer_to_server(Greeter(), server2)
    server2.add_insecure_port('[::]:50051')
    # error happens here
```


However the _cpp_ API seems to be different in that the the `ServerBuilder` does not start listening until the server is started with `BuildAndStart()`

I think this is just how the APIs work and not specific to C#

**Comment by jtattermusch** [comment] 2022-08-16 11:02
closing as dupe of https://github.com/grpc/grpc/issues/23390.

**Closed by jtattermusch** 2022-08-16 11:02 UTC
Labels: kind/bug, lang/C#, priority/P2
