### ISSUE TITLE
Missed `all` choice for `--config` parameter in `run_tests.py`

### ISSUE THREAD

**Issue by soon** [grpc/grpc#5643] opened 2016-03-08 09:47 UTC
According to the [documentation](https://github.com/grpc/grpc/blob/9b9c40cfe8aab8699cc446087313af9059e8db3a/CONTRIBUTING.md), it is possible to run all tests for specified language using the following script parameters:

> If you want to run all the possible tests for any of the languages {c, c++, node, php, python}, do this:
> 
>     ./tools/run_tests/run_tests.py -l <lang> -c all

However, `all` parameter value has been [removed](https://github.com/grpc/grpc/commit/77db432c2d1733b56ed01fcd9c3df1960b62f97e#diff-14b1292f5c2927c65222a1492af2bed9L651) since 77db432c2d1733b56ed01fcd9c3df1960b62f97e. 

Should the documentation be also updated?

**Comment by stanley-cheung** [comment] 2016-03-08 19:30
Dupe of #5561

**Closed** 2016-03-08 19:31 UTC
Labels: documentation
