### ISSUE TITLE
ruby interop tests failing

### ISSUE THREAD

**Issue by markdroth** [grpc/grpc#20471] opened 2019-10-03 16:55 UTC
https://source.cloud.google.com/results/invocations/7d29e2c6-51d6-4a63-9320-bcb4b2c36ef4/targets/github%2Fgrpc%2Finterop_test/tests;group=tests;test=cloud_to_cloud:aspnetcore:ruby_server:cancel_after_begin:tls;row=1

There are a large number of test failures, and they all involve ruby as either the client or the server.

**Comment by jtattermusch** [comment] 2019-10-04 15:29
Looks like this could be is because of google-protobuf 3.10 gem was just pushed.
(not good because the gem is supposed to be backward compatible).

@rafi-kamal

**Comment by jtattermusch** [comment] 2019-10-04 15:29
Interop tests are failing on master at 100% rate.

**Comment by jtattermusch** [comment] 2019-10-04 15:32
@rafi-kamal  I believe there was a non-backwards-compatible change (needs to be rolled back?)
```
/usr/local/rvm/gems/ruby-2.5.3/gems/google-protobuf-3.10.0-x86_64-linux/lib/google/protobuf.rb:61:in `infer_package': undefined method `size' for nil:NilClass (NoMethodError)
	from /usr/local/rvm/gems/ruby-2.5.3/gems/google-protobuf-3.10.0-x86_64-linux/lib/google/protobuf.rb:109:in `fixup_descriptor'
	from /var/local/git/grpc/src/ruby/pb/src/proto/grpc/testing/test_pb.rb:9:in `add_file'
	from /var/local/git/grpc/src/ruby/pb/src/proto/grpc/testing/test_pb.rb:9:in `block in <top (required)>'
	from /var/local/git/grpc/src/ruby/pb/src/proto/grpc/testing/test_pb.rb:8:in `instance_eval'
	from /var/local/git/grpc/src/ruby/pb/src/proto/grpc/testing/test_pb.rb:8:in `build'
	from /var/local/git/grpc/src/ruby/pb/src/proto/grpc/testing/test_pb.rb:8:in `<top (required)>'
	from /usr/local/rvm/rubies/ruby-2.5.3/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /usr/local/rvm/rubies/ruby-2.5.3/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /var/local/git/grpc/src/ruby/pb/src/proto/grpc/testing/test_services_pb.rb:23:in `<top (required)>'
	from src/ruby/pb/test/client.rb:42:in `require_relative'
	from src/ruby/pb/test/client.rb:42:in `<main>'
```

**Comment by rafi-kamal** [comment] 2019-10-04 17:07
@haberman @teboring do you know the root cause of the failure? I'll see if 3.10.0 can be rolled back.

**Comment by haberman** [comment] 2019-10-04 17:35
@jtattermusch That's not a backward-incompatible change, it just looks like a bug. How can I reproduce it?

**Comment by rafi-kamal** [comment] 2019-10-04 18:21
I've yanked the gem.

```
➜   gem yank google-protobuf -v 3.10.0 
Yanking gem from https://rubygems.org...
Successfully deleted gem: google-protobuf (3.10.0)
```

**Comment by jtattermusch** [comment] 2019-10-07 06:11
seems fixed on master.

**Closed by jtattermusch** 2019-10-07 06:11 UTC
Labels: infra/BUILDPONY, kind/bug, lang/ruby, priority/P1

**Comment by rafi-kamal** [comment] 2019-10-07 18:07
@jtattermusch do you know what the root cause is or how can we reproduce the issue? We would like to release Ruby 3.10 again after fixing the bug.

**Comment by apolcyn** [comment] 2019-10-08 05:51
I haven't verified this myself but this <i>should</i> be reproducable by checking out the grpc github repo and trying to load the same ruby-generated protos that this test client tried to load.

E.g. something like:

```
> git clone https://github.com/grpc/grpc.git
> cd grpc && ruby src/ruby/pb/src/proto/grpc/testing/test_services_pb.rb
```

Let me know if that doesn't work.

Thanks for addressing quickly btw.
