### ISSUE TITLE
Make `grpc_register_event_engine_factory` a public API

### ISSUE THREAD

**Issue by BusyJay** [grpc/grpc#24783] opened 2020-11-18 08:50 UTC
### Is your feature request related to a problem? Please describe.
Due to https://github.com/grpc/grpc/issues/15535, we probably want to spawn jobs that may block to other thread pool. However, spawning too many threads may not always to be a good idea. On the other hand, it's said in the [docs](https://github.com/grpc/grpc/blob/master/doc/core/grpc-polling-engines.md):
> gRPC needed some component that can "efficiently" do the above operations using the threads provided by the applications (i.e., not create any new threads). Also by "efficiently" we mean optimized for latency and throughput

But there seems to be no way to provide custom polling engine into c core.

### Describe the solution you'd like
Making `grpc_register_event_engine_factory` a public API, so that users can develop their version of poll engine, and control when to spawn new threads and how to manage tasks.

### Describe alternatives you've considered
None yet.

### Additional context
grpc-rs wants this feature to use a global unified thread pool, see also https://github.com/tikv/grpc-rs/issues/497.

**Comment by markdroth** [comment] 2020-12-01 01:14
Duplicate of #20194.

**Closed by markdroth** 2020-12-01 01:14 UTC
Labels: kind/enhancement, priority/P2
