### ISSUE TITLE
csharp grpc plugin generates Grpc.cs file in root of output path

### ISSUE THREAD

**Issue by ido-namely** [grpc/grpc#22807] opened 2020-04-28 16:46 UTC
### Is your feature request related to a problem? Please describe.
Event though protoc for csharp support several options for how to generate files [compile options](https://developers.google.com/protocol-buffers/docs/reference/csharp-generated#compiler_options), they are not respected by grpc plugin.
Specifically, the problem I have is when generating two services using the same parent directory which have the same proto name (e.g service.proto). they are both generated as `ServiceGrpc.cs` in the root of the specified output directory.
Admittedly, there are ways to work around this (rename the files, change dir structure etc), but I think it would be good to have the generated file located with the rest of the files generated by prococ which can use a nested structure when provided with the `base_namespace` option.

### Describe the solution you'd like
Grpc generated files should follow the `csharp_opt` options( base_namespace, file_extension) to determine where and with what name to generate the grpc services files.

### Describe alternatives you've considered
Renaming my directory structure or giving more unique names to proto files.

### Additional context
In the example I used the name `service.proto` which can lead to thinking about just giving a more proper name according to the service defined, however this happened when adding a second implementation to an existing service (v2) which required a different sub dir and namespace but I'd prefer to not have to version the proto name as well.

**Comment by jtattermusch** [comment] 2020-04-28 16:54
This is basically a duplicate of https://github.com/grpc/grpc/issues/13724 and https://github.com/grpc/grpc/issues/17672

**Closed** 2020-04-28 16:54 UTC
Labels: kind/enhancement, lang/C#, priority/P2
