### ISSUE TITLE
Seeing continuous failures in grpc Multilang and Mac OS Basic tests

### ISSUE THREAD

**Issue by mhaidrygoog** [grpc/grpc#16861] opened 2018-10-12 17:16 UTC
Continuous failures in MacOS (Opt, Debug) tests and Multilang tests.

Failures observed since 10 Oct

Error log : 
```
+ node merge_kokoro_logs.js
TypeError: Cannot read property 'testsuites' of null
    at merged.testsuites.testsuite.Array.concat.apply.objects.map (/Volumes/BuildData/tmpfs/src/github/grpc/grpc-node/merge_kokoro_logs.js:44:126)
    at Array.map (<anonymous>)
    at readDir.then.then (/Volumes/BuildData/tmpfs/src/github/grpc/grpc-node/merge_kokoro_logs.js:44:109)
    at <anonymous>
 
```

**Comment by mhaidrygoog** [comment] 2018-10-12 17:30
Error logs where the issue first occured -
https://source.cloud.google.com/results/invocations/44e43e3a-1000-499d-8a55-05aacb8c20b7/targets/grpc%2Fcore%2Fmaster%2Fmacos%2Fgrpc_basictests_opt/log

https://source.cloud.google.com/results/invocations/467171c1-96b4-4a0d-86b4-6afa81e03ff8/targets/grpc%2Fcore%2Fmaster%2Fmacos%2Fgrpc_basictests_dbg/log

https://source.cloud.google.com/results/invocations/0d7bae9a-b0db-4c09-bfaa-5c34d6323b97/targets/grpc%2Fcore%2Fmaster%2Flinux%2Fgrpc_basictests_multilang/log

Commit at which the error started appearing -

https://github.com/grpc/grpc/commit/73c99f890a42479bc82e2c0ab132a97cbcf8434a

**Comment by jtattermusch** [comment] 2018-10-16 06:55
Dupe of https://github.com/grpc/grpc/issues/16846

**Closed by jtattermusch** 2018-10-16 06:55 UTC
