### ISSUE TITLE
Using GRPC libraries produces lots of deprecation warnings and also it hangs

### ISSUE THREAD

**Issue by vsubramani** [grpc/grpc#6715] opened 2016-05-25 18:51 UTC
Feedback from Andrew Macvean's Veneer Toolkit Usability Study. Looks like a GRPC issue.

Arguably the largest usability issues experienced during the session related to the underlying dependency on gRPC. Namely:
A number of gRPC API deprecation warnings were output during execution.
gRPC was failing to close connections on completion of execution, causing the participant's’ application to ‘hang’ for a number of minutes before timing out.

In both cases, participants showed concern about their implementation, and the reliability of the client library.

“I see a whole bunch of deprecated packages messages. I would go back to the documentation to see if I have used the right api and packages” - Participant 3

“Warnings are scary, slightly uncomfortable. I usually ignore them. It would be nice, if they were not there” - Participant 6

/cc @rok987 
/cc @andrewmacvean

**Comment by ctiller** [comment] 2016-05-25 19:05
Is it possible to turn this issue into something actionable?

Which languages were studied?
What were the warnings?
What hung?

**Comment by vsubramani** [comment] 2016-05-26 00:21
Language: Python
Library: grpc through veneer toolkit
Installation instructions: http://pythonhosted.org/gax-google-pubsub-v1/starting.html#installation
Code Used: 
`#!/usr/bin/env python2.7
from google.pubsub.v1.publisher_api import PublisherApi

try:	
	api = PublisherApi()
	project = api.project_path('vsubramani-gcp-explorer')
	all_topics = list(api.list_topics(project))
	
except Exception as e:
    print 'failed with {0}'.format(e)`

Error Obtained:
`(vtk5) vsubramani-macbookpro2:VTKSample vsubramani$ python PubSubSample.py 
/Users/vsubramani/Documents/Projects/VTKSample/vtk5/lib/python2.7/site-packages/google/pubsub/v1/pubsub_pb2.py:1168: DeprecationWarning: the alpha API (includes this package) is deprecated, unmaintained, and no longer tested. Please migrate to the beta API.
  from grpc.early_adopter import implementations as early_adopter_implementations
/Users/vsubramani/Documents/Projects/VTKSample/vtk5/lib/python2.7/site-packages/grpc/_adapter/fore.py:39: DeprecationWarning: the alpha API (includes this package) is deprecated, unmaintained, and no longer tested. Please migrate to the beta API.
  from grpc.framework.base import interfaces as base_interfaces
/Users/vsubramani/Documents/Projects/VTKSample/vtk5/lib/python2.7/site-packages/grpc/early_adopter/implementations.py:36: DeprecationWarning: the alpha API (includes this package) is deprecated, unmaintained, and no longer tested. Please migrate to the beta API.
  from grpc.framework.alpha import _face_utilities
/Users/vsubramani/Documents/Projects/VTKSample/vtk5/lib/python2.7/site-packages/grpc/framework/alpha/_face_utilities.py:35: DeprecationWarning: the alpha API (includes this package) is deprecated, unmaintained, and no longer tested. Please migrate to the beta API.
  from grpc.framework.face import interfaces as face_interfaces  # pylint: disable=unused-import
`

**Comment by vsubramani** [comment] 2016-05-26 00:21
Accidentally closed. Reopened.

**Comment by dklempner** [comment] 2016-05-26 02:28
Hasn't the warning issue here already been explained as using ancient codegen, which would presumably be fixed by rerunning the proto compiler? @nathanielmanistaatgoogle claims in https://github.com/googleapis/gax-python/issues/81 that the deprecated calls haven't been generated in months.

Regarding the hang, there's been a whole slew of bugfixes recently, both in c core and in the python wrappings. Iif there's a clear 100% reproduction it's probably worth retrying with 0.14.0 and/or grpc master to see if it's already been fixed.

**Comment by soltanmm** [comment] 2016-05-26 07:08
@vsubramani Building on what @dklempner mentioned, it appears that `gax-python` is pinned about two months behind gRPC head. You'll definitely want to ping the issue you filed with them w.r.t. that, as such warnings are effectively out of our control due to their version pinning.

Please file a separate issue if you see the hang with an up-to-date gRPC installation.

**Closed by soltanmm** 2016-05-26 07:08 UTC
Labels: bug, documentation, packaging & distribution, python
