### ISSUE TITLE
tests.cloud_to_cloud:java:http2_server:rst_during_data failure

### ISSUE THREAD

**Issue by apolcyn** [grpc/grpc#10686] opened 2017-04-17 23:30 UTC
this looks like a build/infrastructure failure

```
Regression

tests.cloud_to_cloud:java:http2_server:rst_during_data (from grpc.tests)

Failing for the past 1 build (Since Unstable#13373 )
Took 8 sec.
Error Message

Failure
Standard Output

Apr 17, 2017 7:54:59 PM io.grpc.testing.integration.Http2Client run
INFO: Running test rst_during_data
Apr 17, 2017 7:54:59 PM io.netty.util.internal.MacAddressUtil defaultMachineId
WARNING: Failed to find a usable hardware address from the network interfaces; using random bytes: a9:f5:f0:b5:b1:20:50:19
Exception in thread "main" java.lang.AssertionError: Operation timed out
	at io.grpc.testing.integration.Http2Client$Tester.rstDuringData(Http2Client.java:262)
	at io.grpc.testing.integration.Http2Client$Tester.access$500(Http2Client.java:216)
	at io.grpc.testing.integration.Http2Client.runTest(Http2Client.java:200)
	at io.grpc.testing.integration.Http2Client.run(Http2Client.java:182)
	at io.grpc.testing.integration.Http2Client.main(Http2Client.java:90)
```

https://grpc-testing.appspot.com/job/gRPC_interop_pull_requests/13373/testReport/junit/(root)/tests/cloud_to_cloud_java_http2_server_rst_during_data/

pr: https://github.com/grpc/grpc/pull/10670

**Comment by apolcyn** [comment] 2017-04-25 03:00
same error seen again in a recent interop run on 4/24 - (this happens sometimes but not always)

https://grpc-testing.appspot.com/job/gRPC_interop_master/12527/testReport/junit/(root)/tests/cloud_to_cloud_java_http2_server_rst_during_data/

**Comment by matt-kwong** [comment] 2017-05-12 23:13
Seen again here: https://grpc-testing.appspot.com/job/gRPC_interop_master/12849/testReport/junit/(root)/tests/cloud_to_cloud_java_http2_server_rst_during_data/

```
Stacktrace

May 12, 2017 7:01:29 PM io.grpc.testing.integration.Http2Client run
INFO: Running test rst_during_data
May 12, 2017 7:01:29 PM io.netty.util.internal.MacAddressUtil defaultMachineId
WARNING: Failed to find a usable hardware address from the network interfaces; using random bytes: 48:aa:81:d9:19:c3:6c:96
Exception in thread "main" java.lang.AssertionError: Operation timed out
	at io.grpc.testing.integration.Http2Client$Tester.rstDuringData(Http2Client.java:262)
	at io.grpc.testing.integration.Http2Client$Tester.access$500(Http2Client.java:216)
	at io.grpc.testing.integration.Http2Client.runTest(Http2Client.java:200)
	at io.grpc.testing.integration.Http2Client.run(Http2Client.java:182)
	at io.grpc.testing.integration.Http2Client.main(Http2Client.java:90)
```

**Comment by muxi** [comment] 2017-05-18 05:20
Still happening in master:
https://grpc-testing.appspot.com/job/gRPC_interop_master/12967/testReport/(root)/tests/cloud_to_cloud_java_http2_server_rst_during_data/

**Comment by makdharma** [comment] 2017-05-19 16:54
seen again #11047

**Comment by dgquintas** [comment] 2017-06-29 21:57
Seen again: https://grpc-testing.appspot.com/job/gRPC_interop_pull_requests/15057/console

```
2017-06-28 21:25:16,944 Jun 28, 2017 9:25:09 PM io.grpc.testing.integration.Http2Client run
INFO: Running test rst_during_data
Exception in thread "main" java.lang.AssertionError: Operation timed out
	at io.grpc.testing.integration.Http2Client$Tester.rstDuringData(Http2Client.java:247)
	at io.grpc.testing.integration.Http2Client$Tester.access$500(Http2Client.java:201)
	at io.grpc.testing.integration.Http2Client.runTest(Http2Client.java:185)
	at io.grpc.testing.integration.Http2Client.run(Http2Client.java:167)
	at io.grpc.testing.integration.Http2Client.main(Http2Client.java:75)

2017-06-28 21:25:16,945 FAILED: cloud_to_cloud:java:http2_server:rst_during_data [ret=1, pid=14895]
```

**Comment by dgquintas** [comment] 2017-08-03 16:38
Again: https://grpc-testing.appspot.com/job/gRPC_interop_pull_requests/15858/

**Comment by dgquintas** [comment] 2017-08-03 16:39
This has been happening relatively often for a while now. Any plans/ideas? @ericgribkoff @ejona86

**Comment by ericgribkoff** [comment] 2017-08-18 06:54
Same root cause as reported in https://github.com/grpc/grpc/issues/10390, and now fixed with a larger timeout in the Java client (https://github.com/grpc/grpc-java/pull/3333)

**Closed by ericgribkoff** 2017-08-18 06:54 UTC
Labels: infra/BUILDPONY, lang/Java
