### ISSUE TITLE
FLAKE: bins/dbg/grpclb_end2end_test --gtest_filter=UpdatesTest.UpdateBalancers on MacOS

### ISSUE THREAD

**Issue by jtattermusch** [grpc/grpc#14673] opened 2018-03-12 11:06 UTC
Recent failure on master:
https://sponge.corp.google.com/invocation?id=e1e3e592-5a5e-49e7-980e-65c2fa51766b
https://sponge.corp.google.com/invocation?id=6173d9ca-1164-410e-b2eb-992e84d046b7
https://sponge.corp.google.com/invocation?id=724a6614-77ad-4955-84dd-c20224df8481

Logs:
```
test/cpp/end2end/grpclb_end2end_test.cc:530: Failure
Value of: status.ok()
  Actual: false
Expected: true
code=4 message=Deadline Exceeded
I0222 11:19:48.659000000 123145308741632 grpclb_end2end_test.cc:196]   LB[0x7feba3100060]: received initial message 'initial_request {
  name: "servername_not_used"
}
'
I0222 11:19:48.659052000 123145308741632 grpclb_end2end_test.cc:308]   LB[0x7feba3100060]: sleeping for 0 ms...
I0222 11:19:48.659080000 123145308741632 grpclb_end2end_test.cc:314]   LB[0x7feba3100060]: Woke up! Sending response 'server_list {
  servers {
    ip_address: "\177\000\000\001"
    port: 24628
  }
}
'
test/cpp/end2end/grpclb_end2end_test.cc:532: Failure
      Expected: response.message()
      Which is: ""
To be equal to: kRequestMessage_
      Which is: "Live long and prosper."
```

```
I0307 04:48:33.509801000 140735162880000 grpclb_end2end_test.cc:978]   ========= DONE WITH SECOND BATCH ==========
test/cpp/end2end/grpclb_end2end_test.cc:987: Failure
      Expected: 1U
      Which is: 1
To be equal to: balancer_servers_[1].service_->request_count()
      Which is: 2
test/cpp/end2end/grpclb_end2end_test.cc:988: Failure
      Expected: 1U
      Which is: 1
To be equal to: balancer_servers_[1].service_->response_count()
      Which is: 2
```

```
I0309 22:34:46.488768000 123145309814784 grpclb_end2end_test.cc:259]   LB[0x7fbe2940b450]: done
test/cpp/end2end/test_service_impl.cc:130: Failure
Value of: context->IsCancelled()
  Actual: true
Expected: false
I0309 22:34:48.030750000 123145303375872 grpclb.cc:476]                Missing LB token for backend address 'ipv4:127.0.0.1:28907'. The empty token will be used instead
test/cpp/end2end/test_service_impl.cc:130: Failure
Value of: context->IsCancelled()
  Actual: true
Expected: false
```

**Comment by jtattermusch** [comment] 2018-03-12 11:06
There is some similarity with https://github.com/grpc/grpc/issues/14672.

**Comment by dgquintas** [comment] 2018-03-12 17:53
@AspirinSJL do you mind having a look as well? It seems all these issues are happening on mac only :/

**Comment by AspirinSJL** [comment] 2018-03-12 20:48
I'm looking at this one first because I tried it last Friday. 

BTW, I just noticed that the command I used last Friday has a typo so the polling engine is not forced to be poll,. Not sure whether this is related to the reproducibility, but we will see...

**Comment by dgquintas** [comment] 2018-03-13 15:19
The polling engine is always poll on macos

**Comment by AspirinSJL** [comment] 2018-03-14 03:33
I can't reproduce either issue locally.

I think we need to try to reproduce it on kokoro mac machine then.

**Comment by jtattermusch** [comment] 2018-04-03 14:45
I haven't seen an instance of this since 2018-03-09 (but it was pretty rare even before).

**Comment by jtattermusch** [comment] 2018-04-03 14:46
Closing for now, let's reopen if seen again.

**Comment by muxi** [comment] 2018-05-03 15:05
Seen again at https://source.cloud.google.com/results/invocations/c01c55b1-6d55-4b87-89e8-43864b3be4e2/targets/github%2Fgrpc%2Fcpp_macos_dbg_native/tests

**Comment by jtattermusch** [comment] 2018-05-21 23:04
Seen again on 2018-05-19.

**Comment by AspirinSJL** [comment] 2018-05-22 01:28
Because the flakiness is low and it's hard to repro locally, I'm changing this to P2.

**Comment by AspirinSJL** [comment] 2018-06-19 23:36
Duplicate of #15027.

**Closed by AspirinSJL** 2018-06-19 23:36 UTC
Labels: infra/BUILDPONY, kind/bug, lang/c++, platform/macOS, priority/P2
