### ISSUE TITLE
Shutting down Grpc on Windows with Grpc 0.6.0 produces memory leak warning

### ISSUE THREAD

**Issue by degloff** [grpc/grpc#2720] opened 2015-07-30 11:16 UTC
Shutting down Grpc on the client side produces the following log messages:

	shutting down Grpc...
	Waiting for GPRC threads to finish.
	Completion queue has shutdown successfully, thread grpc 0 exiting.
	Completion queue has shutdown successfully, thread grpc 1 exiting.
	Completion queue has shutdown successfully, thread grpc 3 exiting.
	Completion queue has shutdown successfully, thread grpc 2 exiting.
	D30.07.2015 13:12:02 0 c:\users\jtattermusch\github\grpc\src\core\iomgr\iomgr.c:119: Waiting for 1 iomgr objects to be destroyed and executing final callbacks
	D30.07.2015 13:12:02 0 c:\users\jtattermusch\github\grpc\src\core\iomgr\iomgr.c:126: Waiting for 1 iomgr objects to be destroyed
	D30.07.2015 13:12:12 0 c:\users\jtattermusch\github\grpc\src\core\iomgr\iomgr.c:156: Failed to free 1 iomgr objects before shutdown deadline: memory leaks are likely
	D30.07.2015 13:12:12 0 c:\users\jtattermusch\github\grpc\src\core\iomgr\iomgr.c:161: LEAKED OBJECT: client 012E68B0
	D30.07.2015 13:12:12 19404752 c:\users\jtattermusch\github\grpc\src\core\iomgr\iocp_windows.c:130: iocp_loop is done
	GRPC shutdown.
	done.

On the server side I get:

    E30.07.2015 13:12:12 13080576 c:\users\jtattermusch\github\grpc\src\core\iomgr\tcp_windows.c:152: ReadFile overlapped error: An existing connection was forcibly closed by the remote host.

Any idea what is the reason? We use Grpc 0.6.0. 

Many thanks for some feedback.

**Comment by soltanmm** [comment] 2015-07-30 22:37
The `iomgr` leak happens all over the place currently; I'm doubtful that is specifically a Windows problem.

cc @jtattermusch

**Comment by jtattermusch** [comment] 2015-07-30 23:38
I am pretty sure this is Windows specific. It's duplicate of issue #1650 that has been fixed by #2416.
Looks like we should do 0.6.1 release with this fix in place.

**Closed by jtattermusch** 2015-07-30 23:38 UTC
Labels: Windows

**Comment by jtattermusch** [comment] 2015-07-31 03:14
The 0.6.1 version of Grpc nuget packages was published and it contains the fix (an some related windows stabillity fixes). Please upgrade your project and let me know if this solves your problem.

https://www.nuget.org/packages/Grpc/
