### ISSUE TITLE
New Failure: py35.test.reflection._reflection_servicer_test.ReflectionServicerTest

### ISSUE THREAD

**Issue by dgquintas** [grpc/grpc#13426] opened 2017-11-16 22:30 UTC
- Test: py35.test.reflection._reflection_servicer_test.ReflectionServicerTest
- Poll Strategy: None
- URL: https://kokoro2.corp.google.com/job/grpc/job/windows/job/master/job/grpc_basictests_dbg/114

**Comment by mehrdada** [comment] 2017-11-16 23:45
This looks like an issue caused by a new google/protobuf release on PyPI. It was pushed yesterday (3.5.0)

**Comment by mehrdada** [comment] 2017-11-17 22:32
Update: protobuf 3.5.1 is going to fix this issue. We have to wait till it gets published and this failure should go away.

**Comment by dgquintas** [comment] 2017-11-18 01:01
Is there a timeline?

**Comment by mehrdada** [comment] 2017-11-18 01:09
I heard it should be out before the next business week ends (i.e. Wednesday). I think the cause is diagnosed and the fix is going to be straightforward.

**Comment by mehrdada** [comment] 2017-11-22 23:55
A supplementary update to 3.5.0 is uploaded to PyPI so this should be fixed now. Please ping the issue if you encounter it again for builds starting from now on.

**Closed by mehrdada** 2017-11-22 23:55 UTC
Labels: infra/New Failure, lang/Python, priority/P0/RELEASE BLOCKER
