### ISSUE TITLE
RPC get grpc_status unavailable after server restart

### ISSUE THREAD

**Issue by yyh-graphsql** [grpc/grpc#9767] opened 2017-02-17 18:26 UTC
I have two kinds of stubs shared one channel to a remote server.
I will send an RPC, restart the server and then resend an RPC. But the second RPC will get the following error: Error found in RPC, code: 14, error msg: {"created":"@1487355639.990709165","description":"EOF","file":"src/core/lib/iomgr/tcp_posix.c","file_line":235,"grpc_status":14}

I will try to connect channel after server restart, like this:
  grpc_connectivity_state state;
  do {
    state = channel_->GetState(true);
    if (state != GRPC_CHANNEL_READY && state != GRPC_CHANNEL_CONNECTING) {
      usleep(kChannelTimeoutMS);
      retried++;
    }
  } while (state != GRPC_CHANNEL_READY  &&
      state != GRPC_CHANNEL_CONNECTING && retried < kChannelRetryCount);
  if (retried == kChannelRetryCount) {
    return Status::kNotReady;
  }

I don't know where is getting me wrong. The channel suppose to reconnect by itself right? even the channel is in CONNECTING state, I also get the grpc_state 14.

**Comment by cysnake4713** [comment] 2017-02-18 06:43
same problem here!! +1

**Comment by ncteisen** [comment] 2017-02-19 01:58
This is a known issue with the c core. TL;DR, we know why it happens, and it will be addressed by the retry implementation coming in the next few months. Check out this [gRFC](https://github.com/grpc/proposal/pull/12) for more details. Specifically [this section](https://github.com/ncteisen/proposal/blob/4d61d04e3db298b1c2503e1ab0245f16e1b86967/A6.md#transparent-retries).

Basically this occurs because the RPC goes all the way through the channel, lb_policy, subchannel, to the transport before it realizes the connection has terminated, and at that point it is too late to try to reconnect, so the RPC fails. But again, this will soon be fixed.

For now hacking together your own simple retry logic is the best fix.

**Comment by yyh-graphsql** [comment] 2017-02-20 16:12
@ncteisen  Have you notice the retry logic I posted above. The thing is even the retry logic succeed, but when it comes to "stub.xxx", it will also get UNAVAILABLE.
@cysnake4713 Did you get the exactly same problem? For me, it showed randomly when ran in my local virtual machine.

**Comment by yyh-graphsql** [comment] 2017-02-20 21:29
@ncteisen  The situation I encountered is actually like this:

- Set up channel to Server A
- Send an RPC and succeed
- Restart Server A until it can receive RPCs
- Re-send an RPC and this RPC got UNAVAILABLE

Seems the thing is not like the server restart at the middle stage of one RPC. I just reuse a channel before and after server restart.

**Comment by ncteisen** [comment] 2017-02-20 21:44
That situation is expected behavior. Try doing this:
* Set up channel to Server A
* Send an RPC and succeed
* Restart Server A until it can receive RPCs
* Re-send an RPC and this RPC got UNAVAILABLE
* Send another RPC, this one should work fine.

**Comment by ncteisen** [comment] 2017-02-20 21:47
Also, would suggest checking out [WaitForConnected](https://github.com/grpc/grpc/blob/5098508d2d41a116113f7e333c516cd9ef34a943/include/grpc%2B%2B/impl/codegen/channel_interface.h#L90) and [set_wait_for_ready](https://github.com/grpc/grpc/blob/46357c882df1afc28f7a5228c40fde522093fa32/include/grpc%2B%2B/impl/codegen/client_context.h#L232). They have some of the functionality that your pseudocode was using.

**Comment by yyh-graphsql** [comment] 2017-02-22 15:30
@ncteisen You mean before re-send the RPC, if I WaitForConnected for the channel I used, the re-sent RPC will also work fine? Actually, I'm also curious about why when restarting the server the first RPC will fail and the second is ok. Can you explain me a little bit or give me some references? Thank you!

**Comment by ncteisen** [comment] 2017-02-22 16:32
When you kill the server, there is no mechanism in place to let the client know that the connection has gone bad. Instead, the client will believe that their channel is in a good state, and thus when an RPC is sent, it will travel all the way down to the transport layer before realizing that the connection had been closed.

At that point the failure is bubbled up to the client application. But, as I mentioned earlier, there is a work in progress to implement transparent retries in these situations.

Check out this [gRFC](https://github.com/grpc/proposal/pull/12) for more details. Specifically [this section](https://github.com/ncteisen/proposal/blob/4d61d04e3db298b1c2503e1ab0245f16e1b86967/A6.md#transparent-retries).

**Closed** 2017-07-12 18:17 UTC
