### ISSUE TITLE
[Python install] can't install grpcio-tools in Alpine, Python 3.5

### ISSUE THREAD

**Issue by skyler** [grpc/grpc#8708] opened 2016-11-10 03:24 UTC
```
# cat /proc/version
Linux version 4.4.20-moby (root@3934ed318998) (gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.2) ) #1 SMP Thu Sep 15 12:10:20 UTC 2016
# python --version
Python 3.5.2
```
Using [this Dockerfile](https://github.com/docker-library/python/blob/83b8e044aa38ab97b5427a9591e0537464e976e6/3.5/alpine/Dockerfile)

I've installed
```
python3-dev
linux-headers
```
which I had to do to even get as far as I have. When I `pip install grpcio-tools`, I get a bunch of errors that culimate with
```
    We could not diagnose your build failure. Please file an issue at http://www.github.com/grpc/grpc with `[Python install]` in the title.

    Traceback (most recent call last):
      File "/usr/local/lib/python3.5/distutils/unixccompiler.py", line 196, in link
        self.spawn(linker + ld_args)
      File "/tmp/pip-build-83rho7k2/grpcio/src/python/grpcio/_spawn_patch.py", line 67, in _commandfile_spawn
        _classic_spawn(self, command)
      File "/usr/local/lib/python3.5/distutils/ccompiler.py", line 909, in spawn
        spawn(cmd, dry_run=self.dry_run)
      File "/usr/local/lib/python3.5/distutils/spawn.py", line 36, in spawn
        _spawn_posix(cmd, search_path, dry_run=dry_run)
      File "/usr/local/lib/python3.5/distutils/spawn.py", line 159, in _spawn_posix
        % (cmd, exit_status))
    distutils.errors.DistutilsExecError: command 'gcc' failed with exit status 1
```
I've attached the entire error output:
[PythonBuildErrorLog.txt](https://github.com/grpc/grpc/files/582453/PythonBuildErrorLog.txt)

**Comment by soltanmm-google** [comment] 2016-11-16 00:39
The failure has to do with trying to install `grpcio`, which makes this a duplicate of #8658. Thanks for the report!

**Closed by soltanmm-google** 2016-11-16 00:39 UTC
