### ISSUE TITLE
DataStore protocol error?

### ISSUE THREAD

**Issue by timanovsky** [grpc/grpc#7661] opened 2016-08-08 06:31 UTC
Got this exception (Ruby) when  reading from DataStore, as far as I understand it is while deserializing server response:
```
TypeError: wrong argument type false (expected String)
/app/vendor/bundle/ruby/2.3.0/gems/grpc-1.0.0.pre1-x86_64-linux/src/ruby/lib/grpc/generic/rpc_desc.rb:62:in `decode'
/app/vendor/bundle/ruby/2.3.0/gems/grpc-1.0.0.pre1-x86_64-linux/src/ruby/lib/grpc/generic/rpc_desc.rb:62:in `call'
/app/vendor/bundle/ruby/2.3.0/gems/grpc-1.0.0.pre1-x86_64-linux/src/ruby/lib/grpc/generic/rpc_desc.rb:62:in `block in unmarshal_proc'
/app/vendor/bundle/ruby/2.3.0/gems/grpc-1.0.0.pre1-x86_64-linux/src/ruby/lib/grpc/generic/active_call.rb:231:in `remote_read'
/app/vendor/bundle/ruby/2.3.0/gems/grpc-1.0.0.pre1-x86_64-linux/src/ruby/lib/grpc/generic/active_call.rb:309:in `request_response'
/app/vendor/bundle/ruby/2.3.0/gems/grpc-1.0.0.pre1-x86_64-linux/src/ruby/lib/grpc/generic/client_stub.rb:167:in `request_response'
/app/vendor/bundle/ruby/2.3.0/gems/grpc-1.0.0.pre1-x86_64-linux/src/ruby/lib/grpc/generic/service.rb:184:in `block (3 levels) in rpc_stub_class'
/app/vendor/bundle/ruby/2.3.0/gems/gcloud-0.12.1/lib/gcloud/datastore/service.rb:76:in `block in lookup'
/app/vendor/bundle/ruby/2.3.0/gems/gcloud-0.12.1/lib/gcloud/datastore/service.rb:144:in `block in execute'
/app/vendor/bundle/ruby/2.3.0/gems/gcloud-0.12.1/lib/gcloud/backoff.rb:112:in `block in execute_grpc'
/app/vendor/bundle/ruby/2.3.0/gems/gcloud-0.12.1/lib/gcloud/backoff.rb:110:in `loop'
/app/vendor/bundle/ruby/2.3.0/gems/gcloud-0.12.1/lib/gcloud/backoff.rb:110:in `execute_grpc'
/app/vendor/bundle/ruby/2.3.0/gems/gcloud-0.12.1/lib/gcloud/datastore/service.rb:143:in `execute'
/app/vendor/bundle/ruby/2.3.0/gems/gcloud-0.12.1/lib/gcloud/datastore/service.rb:76:in `lookup'
/app/vendor/bundle/ruby/2.3.0/gems/gcloud-0.12.1/lib/gcloud/datastore/dataset.rb:337:in `find_all'
/app/vendor/bundle/ruby/2.3.0/gems/gcloud-0.12.1/lib/gcloud/datastore/dataset.rb:306:in `find'
```

**Comment by timanovsky** [comment] 2016-08-08 17:13
I have created similar ticket in gcloud: https://github.com/GoogleCloudPlatform/gcloud-ruby/issues/817  May be the problem belongs there.

**Comment by apolcyn** [comment] 2016-08-17 19:11
cc @murgatroid99 thinking that this could be from an unfilled recv_message? Anything we call decode with should be safe, correct?

**Comment by apolcyn** [comment] 2016-08-17 20:33
Trouble seeing exactly where that error could be thrown. Are there any steps we can go through to reproduce this?

**Comment by bmclean** [comment] 2016-08-22 16:41
Yes, we are also seeing this error several times a day. We see it randomly when retrieving a list of entities from datastore, most requests of the same datastore query are successful.

```
TypeError: wrong argument type false (expected String)
/app/vendor/bundle/ruby/2.3.0/gems/grpc-1.0.0.pre1-x86_64-linux/src/ruby/lib/grpc/generic/rpc_desc.rb:62:in `decode'
/app/vendor/bundle/ruby/2.3.0/gems/grpc-1.0.0.pre1-x86_64-linux/src/ruby/lib/grpc/generic/rpc_desc.rb:62:in `call'
/app/vendor/bundle/ruby/2.3.0/gems/grpc-1.0.0.pre1-x86_64-linux/src/ruby/lib/grpc/generic/rpc_desc.rb:62:in `block in unmarshal_proc'
/app/vendor/bundle/ruby/2.3.0/gems/grpc-1.0.0.pre1-x86_64-linux/src/ruby/lib/grpc/generic/active_call.rb:231:in `remote_read'
/app/vendor/bundle/ruby/2.3.0/gems/grpc-1.0.0.pre1-x86_64-linux/src/ruby/lib/grpc/generic/active_call.rb:309:in `request_response'
/app/vendor/bundle/ruby/2.3.0/gems/grpc-1.0.0.pre1-x86_64-linux/src/ruby/lib/grpc/generic/client_stub.rb:167:in `request_response'
/app/vendor/bundle/ruby/2.3.0/gems/grpc-1.0.0.pre1-x86_64-linux/src/ruby/lib/grpc/generic/service.rb:184:in `block (3 levels) in rpc_stub_class'
/app/vendor/bundle/ruby/2.3.0/gems/gcloud-0.12.1/lib/gcloud/datastore/service.rb:76:in `block in lookup'
/app/vendor/bundle/ruby/2.3.0/gems/gcloud-0.12.1/lib/gcloud/datastore/service.rb:144:in `block in execute'
/app/vendor/bundle/ruby/2.3.0/gems/gcloud-0.12.1/lib/gcloud/backoff.rb:112:in `block in execute_grpc'
/app/vendor/bundle/ruby/2.3.0/gems/gcloud-0.12.1/lib/gcloud/backoff.rb:110:in `loop'
/app/vendor/bundle/ruby/2.3.0/gems/gcloud-0.12.1/lib/gcloud/backoff.rb:110:in `execute_grpc'
/app/vendor/bundle/ruby/2.3.0/gems/gcloud-0.12.1/lib/gcloud/datastore/service.rb:143:in `execute'
/app/vendor/bundle/ruby/2.3.0/gems/gcloud-0.12.1/lib/gcloud/datastore/service.rb:  95:in `run_query'
/app/vendor/bundle/ruby/2.3.0/gems/gcloud-0.12.1/lib/gcloud/datastore/dataset.rb: 392:in `run'

**Comment by apolcyn** [comment] 2016-08-22 17:38
This looks like its being thrown from within the protobuf c-ext, but not sure exactly where. Is there a way we can see what type of protobuf message your expecting? Or would you be able to provide any raw data being received from datastore that we're attempting to decode here, possibly with grpc trace logging?

**Comment by quartzmo** [comment] 2016-08-22 17:47
@apolcyn Just from reading @bmclean's backtrace, I think the type should be a `google.datastore.v1beta3.LookupResponse`, correct?

**Comment by quartzmo** [comment] 2016-08-22 18:01
Something that really puzzles me in  @bmclean's backtrace is how a `run_query` call seems to change to a `lookup` call...

```sh
/app/vendor/bundle/ruby/2.3.0/gems/gcloud-0.12.1/lib/gcloud/datastore/service.rb:76:in `block in lookup'
...
/app/vendor/bundle/ruby/2.3.0/gems/gcloud-0.12.1/lib/gcloud/datastore/service.rb:  95:in `run_query'
```

**Comment by apolcyn** [comment] 2016-08-22 18:40
@quartzmo I'm having a hard time seeing exactly where this is happening as well, but it looks like somewhere in the execute/retry code this is happening.

But one thing that occurred to me is I don't think I'm looking at the correct branch. Is the datastore code in https://github.com/GoogleCloudPlatform/gcloud-ruby? On the master, or 0.12 branch?

Also I think it is happening in the LookupResponse decoding, but since this looks like a generic type, is there a way we might be able to get an example of the expected entity?

**Comment by bmclean** [comment] 2016-08-22 18:57
@quartzmo Sorry, the backtrace was incorrect (my mistake). We see the error on both and I somehow combined them. I have edited and pasted the exact backtrace as captured.

**Comment by quartzmo** [comment] 2016-08-22 19:07
@bmclean Thanks! I was questioning reality there for a moment!

@apolcyn Not `master`. It looks to me from the backtraces that both @timanovsky and @bmclean  are using `0.12.1`. So if you have cloned the repo, use:

```
$ git checkout v0.12.1
$ bundle install
```

**Comment by quartzmo** [comment] 2016-08-22 19:08
@apolcyn I will also try to reproduce this.

**Comment by murgatroid99** [comment] 2016-08-22 20:05
If it is possible to do so without exposing sensitive information, it would be great to get a complete gRPC trace of a failing request by running it with `GRPC_TRACE=all GRPC_VERBOSITY=DEBUG`. If that has too much information, an example of a raw (serialized) response message that causes this error may be helpful.

**Comment by apolcyn** [comment] 2016-08-22 20:39
I think I was able to get this same error. When running the main example on the README page in https://github.com/GoogleCloudPlatform/gcloud-ruby, for datastore.

After saving multiple Task entities as suggested on the README, I changed the code to look like:

where the false boolean is now a "false" string
```
  10.times do |i|
    task = datastore.entity "RubyDebuggingTask", "rubySampleOtherTask#{i}" do |t|
      t["type"] = "Personal"
      t["done"] = "false"
      t["priority"] = i
      t["description"] = "Learn Cloud Datastore"
    end

    datastore.save task
  end


# Run a query for all completed tasks
  query = datastore.query("RubyDebuggingTask").
      where("done", "=", "false")
```

and got:

```
/usr/local/google/home/apolcyn/.rvm/gems/ruby-2.3.0/gems/grpc-1.0.0.pre1-x86_64-linux/src/ruby/lib/grpc/generic/rpc_desc.rb:62:in `decode': wrong argument type false (expected String) (TypeError)
	from /usr/local/google/home/apolcyn/.rvm/gems/ruby-2.3.0/gems/grpc-1.0.0.pre1-x86_64-linux/src/ruby/lib/grpc/generic/rpc_desc.rb:62:in `call'
	from /usr/local/google/home/apolcyn/.rvm/gems/ruby-2.3.0/gems/grpc-1.0.0.pre1-x86_64-linux/src/ruby/lib/grpc/generic/rpc_desc.rb:62:in `block in unmarshal_proc'
	from /usr/local/google/home/apolcyn/.rvm/gems/ruby-2.3.0/gems/grpc-1.0.0.pre1-x86_64-linux/src/ruby/lib/grpc/generic/active_call.rb:231:in `remote_read'
	from /usr/local/google/home/apolcyn/.rvm/gems/ruby-2.3.0/gems/grpc-1.0.0.pre1-x86_64-linux/src/ruby/lib/grpc/generic/active_call.rb:309:in `request_response'
	from /usr/local/google/home/apolcyn/.rvm/gems/ruby-2.3.0/gems/grpc-1.0.0.pre1-x86_64-linux/src/ruby/lib/grpc/generic/client_stub.rb:167:in `request_response'
	from /usr/local/google/home/apolcyn/.rvm/gems/ruby-2.3.0/gems/grpc-1.0.0.pre1-x86_64-linux/src/ruby/lib/grpc/generic/service.rb:184:in `block (3 levels) in rpc_stub_class'
	from /usr/local/google/home/apolcyn/debug_ruby/cloned_datastore_repo/gcloud-ruby/lib/gcloud/datastore/service.rb:95:in `block in run_query'
	from /usr/local/google/home/apolcyn/debug_ruby/cloned_datastore_repo/gcloud-ruby/lib/gcloud/datastore/service.rb:144:in `block in execute'
	from /usr/local/google/home/apolcyn/debug_ruby/cloned_datastore_repo/gcloud-ruby/lib/gcloud/backoff.rb:112:in `block in execute_grpc'
	from /usr/local/google/home/apolcyn/debug_ruby/cloned_datastore_repo/gcloud-ruby/lib/gcloud/backoff.rb:110:in `loop'
	from /usr/local/google/home/apolcyn/debug_ruby/cloned_datastore_repo/gcloud-ruby/lib/gcloud/backoff.rb:110:in `execute_grpc'
	from /usr/local/google/home/apolcyn/debug_ruby/cloned_datastore_repo/gcloud-ruby/lib/gcloud/datastore/service.rb:143:in `execute'
	from /usr/local/google/home/apolcyn/debug_ruby/cloned_datastore_repo/gcloud-ruby/lib/gcloud/datastore/service.rb:95:in `run_query'
	from /usr/local/google/home/apolcyn/debug_ruby/cloned_datastore_repo/gcloud-ruby/lib/gcloud/datastore/dataset.rb:392:in `run'
	from 7661_repro_attempt.rb:37:in `main'
	from 7661_repro_attempt.rb:42:in `<main>'
```

**Comment by quartzmo** [comment] 2016-08-22 20:42
@apolcyn Great! I'll try to reproduce as you did.

**Comment by quartzmo** [comment] 2016-08-22 20:59
Unfortunately, using `0.12.1` and apolcyn's code above, I could not reproduce the error.

```sh
irb(main):029:0> query = datastore.query("RubyDebuggingTask").where("done", "=", "false")
=> #<Gcloud::Datastore::Query:0x007fb38c8a2770 @grpc=<Google::Datastore::V1beta3::Query: projection: [], kind: [<Google::Datastore::V1beta3::KindExpression: name: "RubyDebuggingTask">], filter: <Google::Datastore::V1beta3::Filter: composite_filter: <Google::Datastore::V1beta3::CompositeFilter: op: :AND, filters: [<Google::Datastore::V1beta3::Filter: composite_filter: nil, property_filter: <Google::Datastore::V1beta3::PropertyFilter: property: <Google::Datastore::V1beta3::PropertyReference: name: "done">, op: :EQUAL, value: <Google::Datastore::V1beta3::Value: boolean_value: nil, integer_value: nil, double_value: nil, key_value: nil, entity_value: nil, geo_point_value: nil, array_value: nil, timestamp_value: nil, null_value: nil, meaning: 0, string_value: "false", blob_value: nil, exclude_from_indexes: false>>>]>, property_filter: nil>, order: [], distinct_on: [], start_cursor: "", end_cursor: "", offset: 0, limit: nil>>
irb(main):030:0> tasks = datastore.run query
=> [#<Gcloud::Datastore::Entity:0x007fb38a1b6aa8 @properties=#<Gcloud::Datastore::Properties:0x007fb38a1b6490 @hash={"type"=>"Personal", "done"=>"false", "priority"=>0, "description"=>"Learn Cloud Datastore"}>, @key=#<Gcloud::Datastore::Key:0x007fb38a1b6918 @kind="RubyDebuggingTask", @name="rubySampleOtherTask0", @project="bustling-kayak-91516", @namespace="">, @_exclude_indexes={"type"=>false, "done"=>false, "priority"=>false, "description"=>false}>, 
...
```

**Comment by bmclean** [comment] 2016-08-22 21:06
The entities I am retrieving do have a boolean property but none of the properties are set to a string such as "false". I am able to query the same result set multiple times correctly before receiving the error.

**Comment by apolcyn** [comment] 2016-08-22 21:38
I've seen this multiple times after doing many rounds of inserts and then changing the field type, but strangely it might have just been a coincidence when I was doing so. I am thinking that this is might happen with a certain ordering of inserts, queries, and field changes, but I've been unable to find any exact steps that work consistently.

**Comment by bmclean** [comment] 2016-08-22 22:21
This is an example of a successful query and response.

from service.rb run_query, this is the `run_req` variable:
```
<Google::Datastore::V1beta3::RunQueryRequest: read_options: nil, partition_id: nil, query: <Google::Datastore::V1beta3::Query: projection: [], kind: [<Google::Datastore::V1beta3::KindExpression: name: "Something">], filter: <Google::Datastore::V1beta3::Filter: composite_filter: <Google::Datastore::V1beta3::CompositeFilter: op: :AND, filters: [<Google::Datastore::V1beta3::Filter: composite_filter: nil, property_filter: <Google::Datastore::V1beta3::PropertyFilter: property: <Google::Datastore::V1beta3::PropertyReference: name: "__key__">, op: :HAS_ANCESTOR, value: <Google::Datastore::V1beta3::Value: boolean_value: nil, integer_value: nil, double_value: nil, key_value: <Google::Datastore::V1beta3::Key: partition_id: nil, path: [<Google::Datastore::V1beta3::Key::PathElement: kind: "ParentSomething", id: 5644449073856512, name: nil>]>, entity_value: nil, geo_point_value: nil, array_value: nil, timestamp_value: nil, null_value: nil, meaning: 0, string_value: nil, blob_value: nil, exclude_from_indexes: false>>>, <Google::Datastore::V1beta3::Filter: composite_filter: nil, property_filter: <Google::Datastore::V1beta3::PropertyFilter: property: <Google::Datastore::V1beta3::PropertyReference: name: "active">, op: :EQUAL, value: <Google::Datastore::V1beta3::Value: boolean_value: false, integer_value: nil, double_value: nil, key_value: nil, entity_value: nil, geo_point_value: nil, array_value: nil, timestamp_value: nil, null_value: nil, meaning: 0, string_value: nil, blob_value: nil, exclude_from_indexes: false>>>]>, property_filter: nil>, order: [], distinct_on: [], start_cursor: "", end_cursor: "", offset: 0, limit: nil>, gql_query: nil, project_id: "our-project-id">
```
from active_call.rb in def remote_read, this is the `res` variable:
```
received_req (unmarshalled): <Google::Datastore::V1beta3::RunQueryResponse: batch: <Google::Datastore::V1beta3::QueryResultBatch: entity_result_type: :FULL, entity_results: [<Google::Datastore::V1beta3::EntityResult: entity: <Google::Datastore::V1beta3::Entity: key: <Google::Datastore::V1beta3::Key: partition_id: <Google::Datastore::V1beta3::PartitionId: project_id: "our-project-id", namespace_id: "">, path: [<Google::Datastore::V1beta3::Key::PathElement: kind: "ParentSomething", id: 5701001512222720, name: nil>, <Google::Datastore::V1beta3::Key::PathElement: kind: "Something", id: 1, name: nil>]>,

properties: {
"active"=><Google::Datastore::V1beta3::Value: boolean_value: false, integer_value: nil, double_value: nil, key_value: nil, entity_value: nil, geo_point_value: nil, array_value: nil, timestamp_value: nil, null_value: nil, meaning: 0, string_value: nil, blob_value: nil, exclude_from_indexes: false>,
"userAgent"=><Google::Datastore::V1beta3::Value: boolean_value: nil, integer_value: nil, double_value: nil, key_value: nil, entity_value: nil, geo_point_value: nil, array_value: nil, timestamp_value: nil, null_value: nil, meaning: 0, string_value: "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36", blob_value: nil, exclude_from_indexes: false>,
"name"=><Google::Datastore::V1beta3::Value: boolean_value: nil, integer_value: nil, double_value: nil, key_value: nil, entity_value: nil, geo_point_value: nil, array_value: nil, timestamp_value: nil, null_value: nil, meaning: 0, string_value: "Something A", blob_value: nil, exclude_from_indexes: false>,
"remoteAddr"=><Google::Datastore::V1beta3::Value: boolean_value: nil, integer_value: nil, double_value: nil, key_value: nil, entity_value: nil, geo_point_value: nil, array_value: nil, timestamp_value: nil, null_value: nil, meaning: 0, string_value: "198.169.134.185", blob_value: nil, exclude_from_indexes: false>,
"uuid"=><Google::Datastore::V1beta3::Value: boolean_value: nil, integer_value: nil, double_value: nil, key_value: nil, entity_value: nil, geo_point_value: nil, array_value: nil, timestamp_value: nil, null_value: nil, meaning: 0, string_value: "E4B86283-C776-40AB-A160-D344BFB6E80D", blob_value: nil, exclude_from_indexes: false>,
"updatedAt"=><Google::Datastore::V1beta3::Value: boolean_value: nil, integer_value: nil, double_value: nil, key_value: nil, entity_value: nil, geo_point_value: nil, array_value: nil, timestamp_value: <Google::Protobuf::Timestamp: seconds: 1471639081, nanos: 531507000>, null_value: nil, meaning: 0, string_value: nil, blob_value: nil, exclude_from_indexes: false>}>,

skipped_cursor: "", more_results: :NO_MORE_RESULTS, skipped_results: 0>, query: nil>
```

**Comment by bmclean** [comment] 2016-08-23 15:28
@murgatroid99 @apolcyn We have captured a failing request [trace](https://gist.github.com/bmclean/27d134268d39d917e70e0c19f7b8ade5) with `GRPC_TRACE=all GRPC_VERBOSITY=DEBUG`.

**Comment by bmclean** [comment] 2016-08-23 15:34
One thing to note is we were unable to reproduce the error locally connected to the actual datastore. One difference is that when the app running locally our Puma web server is configured with one process. In production it is configured with two processes. We reconfigured production to run with one process and never saw the error. We once again configured production with two processes and saw the error almost immediately.

**Comment by murgatroid99** [comment] 2016-08-23 23:54
We have tracked down the root cause of this failure. It appears to be a garbage collection-related interpreter bug that has been fixed in the most recent stable ruby release: 2.3.1. Upgrading seems to completely fix it.

**Comment by nicolasnoble** [comment] 2016-08-24 04:11
Also, to be fair, the bug rather belongs in the protobuf project :-)

**Comment by timanovsky** [comment] 2016-08-24 05:38
@murgatroid99  ouch, awesome job tracking this down. Will upgrade to 2.3.1 (but I think we have problems with some gem, that's why we are on 2.3.0)

**Comment by nicolasnoble** [comment] 2016-08-24 07:22
So the problem leads us to believe this is garbage collector related in all cases, and we can even reproduce it in 2.3.1 by pushing the gc. But this is really a protobuf or even ruby bug. I have created a bug in the relevant repository here: https://github.com/google/protobuf/issues/2004

I will close this one here - please use the bug in protobuf for further discussion.

**Closed by nicolasnoble** 2016-08-24 07:22 UTC
Labels: ruby
