### ISSUE TITLE
test flake: c_linux_ubsan_native.bins/ubsan/h2_census_nosec_test shutdown_finishes_calls GRPC_POLL_STRATEGY=epollsig

### ISSUE THREAD

**Issue by jtattermusch** [grpc/grpc#11131] opened 2017-05-15 09:57 UTC
https://grpc-testing.appspot.com/job/gRPC_pull_requests_ubsan_c/181/

```
D0512 14:21:57.100180049    4432 test_config.c:403]          test slowdown factor: sanitizer=5, fixture=1, poller=1, total=5
I0512 14:21:57.100420302    4432 ev_epollsig_linux.c:90]     epoll engine will be using signal: 40
D0512 14:21:57.100449777    4432 ev_posix.c:121]             Using polling engine: epollsig
D0512 14:21:57.100482267    4432 dns_resolver.c:316]         Using native dns resolver
I0512 14:21:57.100577774    4432 shutdown_finishes_calls.c:53] Running test: test_early_server_shutdown_finishes_inflight_calls/chttp2/fullstack+census
E0512 14:22:47.165205567    4432 cq_verifier.c:228]          no event received, but expected:
0x65 GRPC_OP_COMPLETE success=1 test/core/end2end/tests/shutdown_finishes_calls.c:153




*******************************
Caught signal SIGABRT
bins/ubsan/h2_census_nosec_test[0x101d310]
/lib/x86_64-linux-gnu/libpthread.so.0(+0xf890)[0x7f2c88f32890]
/lib/x86_64-linux-gnu/libc.so.6(gsignal+0x37)[0x7f2c8868c067]
/lib/x86_64-linux-gnu/libc.so.6(abort+0x148)[0x7f2c8868d448]
bins/ubsan/h2_census_nosec_test[0x5fb1d8]
bins/ubsan/h2_census_nosec_test[0x5f2c5a]
bins/ubsan/h2_census_nosec_test[0x5a1a96]
bins/ubsan/h2_census_nosec_test[0x59e8a3]
bins/ubsan/h2_census_nosec_test[0x42f689]
bins/ubsan/h2_census_nosec_test[0x429352]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf5)[0x7f2c88678b45]
bins/ubsan/h2_census_nosec_test[0x4054fd]
```

**Comment by yang-g** [comment] 2017-05-17 18:23
Duplicate of: #10653

**Closed by yang-g** 2017-05-17 18:23 UTC
Labels: BUILDPONY, core
