### ISSUE TITLE
[Python] gprc server hang when request method not exist.

### ISSUE THREAD

**Issue by yancl** [grpc/grpc#4529] opened 2015-12-18 12:25 UTC
Hi, recently we meet a case that when we send a request with the method not exist in the server, the server will hang there and not work anymore, even the later request methods exist.

After some dig of the code, we got here:

```
def _on_service_acceptance_event(self, event, server):
    """Handle a service invocation event."""
    service_acceptance = event.service_acceptance
    if service_acceptance is None:
      return

    call = service_acceptance.call
    call.accept(self._completion_queue, call)
    # TODO(nathaniel): Metadata support.
    call.premetadata()
    call.read(call)
    method = service_acceptance.method

    self._rpc_states[call] = _common.CommonRPCState(
        _common.WriteState(_LowWrite.OPEN, _common.HighWrite.OPEN, []), 1,
        self._request_deserializers[method],
        self._response_serializers[method])

    ticket = base_interfaces.FrontToBackTicket(
        call, 0, base_interfaces.FrontToBackTicket.Kind.COMMENCEMENT, method,
        base_interfaces.ServicedSubscription.Kind.FULL, None, None,
        service_acceptance.deadline - time.time())
    self._rear_link.accept_front_to_back_ticket(ticket)

    server.service(None)
```

as you can see, the ` self._request_deserializers[method]` will throw an exception, but the following code just throw it after do some log and make the woker thread abort:

```
def _wrap(behavior):
  """Wraps an arbitrary callable behavior in exception-logging."""
  @functools.wraps(behavior)
  def _wrapping(*args, **kwargs):
    try:
      return behavior(*args, **kwargs)
    except Exception as e:
      logging.exception('Unexpected exception from task run in logging pool!')
      raise
  return _wrapping
```

so will you fix this bug? thanks:)

**Comment by jcanizales** [comment] 2015-12-18 19:30
Thanks for going as far as debugging it!!

**Comment by nathanielmanistaatgoogle** [comment] 2016-01-22 21:48
I believe this is a duplicate of #2002, because I believe you're using the Alpha ("early_adopter") API. Upgrade to the Beta API and I believe you will be unable to reproduce the problem.

**Closed by nathanielmanistaatgoogle** 2016-01-22 21:48 UTC
Labels: bug, python
