### ISSUE TITLE
C# Compression API

### ISSUE THREAD

**Issue by AhmadChaker** [grpc/grpc#10902] opened 2017-04-28 03:56 UTC
I can't seem to find any extensive documentation on how to setup message compression using C#. 
The only reference to compression I can find is in the file:
grpc/src/csharp/Grpc.Core/WriteOptions.cs
however it's not clear what setting this variable does!

Is there a way to setup compression on both client side requests and server responses using C# ?

**Comment by jtattermusch** [comment] 2017-04-28 14:35
This is basically a duplicate of: https://github.com/grpc/grpc/issues/4170

The functionality is there, but you need to unable by setting appropriate channel option or by setting a metadata entry in your RPC.
Some guidance can be found here:
https://github.com/grpc/grpc/blob/master/src/csharp/Grpc.Core.Tests/CompressionTest.cs

The channel options and metadata names/values are language agnostic, so you can use whatever works for other languages.

**Closed by jtattermusch** 2017-04-28 14:35 UTC
