### ISSUE TITLE
Connection delay when C# server is redirecting stdout and stderr of child processes on windows

### ISSUE THREAD

**Issue by ArtusCanisLupus** [grpc/grpc#24545] opened 2020-10-23 08:02 UTC
### What version of gRPC and what language are you using?
2.33.1 with C#

### What operating system (Linux, Windows,...) and version?
Windows 10, Version 1909

### What runtime / compiler are you using (e.g. python version or version of gcc)
.NET Core 3.1

### What did you do?
I have a C# application on windows, which starts 10 child processes and opens a gRPC server.
I use a simple C# client to call a gRPC function.
If I simply start the child processes, the gRPC server does respond immediately to the first gRPC call.
But if I am redirecting stdout and stderr of the child processes, it takes 11 seconds, until I get the response to the first gRPC call.
After the 11 seconds the server is working normally.

**Comment by jtattermusch** [comment] 2020-10-27 09:40
Can you please provide a minimal reproduction (ideally in form of a github repository)?

**Comment by ArtusCanisLupus** [comment] 2020-10-27 10:18
Yes, of course:
[GrpcProblem](https://github.com/ArtusCanisLupus/GrpcProblem)
Just build the solution and run Client.exe in the bin directory.
Client.exe will start Server.exe automatically.
If you don't want that, then remove the lines 16 to 27 in Client\Program.cs and start the server manually before starting the client.

If you set the bool value in line 24 in Server\Program.cs to false, the problem disappears.
The problem gets worse, if the child processes start writing to stdout and stderr.
I did a test with writing "Output" to stdout and "Error" to stderr every second: 54 seconds until the gRPC server reacts to the call.

Btw: I'm using the ProcessJob implementation to avoid manual kills of the child processes. Disabling the ProcessJob did not resolve the problem.

**Comment by tonydnewell** [comment] 2022-05-24 07:44
This isn't a gRPC issue. There is a bug in the way the example to reproduce the problem starts child processes.
When redirecting stdout or stderr, StartInfo must have UseShellExecute=false.  
See https://docs.microsoft.com/en-us/dotnet/api/system.diagnostics.processstartinfo.redirectstandardoutput?view=netcore-3.1
When this is set correctly then the example runs without a problem.

**Comment by jtattermusch** [comment] 2022-05-24 07:53
@tonydnewell  thanks for the investigation.
I'm going to close this now since this isn't a bug in gRPC.

Out of interest: IIUC the doc says *You must set [UseShellExecute](https://docs.microsoft.com/en-us/dotnet/api/system.diagnostics.processstartinfo.useshellexecute?view=netcore-3.1) to false if you want to set [RedirectStandardOutput](https://docs.microsoft.com/en-us/dotnet/api/system.diagnostics.processstartinfo.redirectstandardoutput?view=netcore-3.1) to true. Otherwise, reading from the [StandardOutput](https://docs.microsoft.com/en-us/dotnet/api/system.diagnostics.process.standardoutput?view=netcore-3.1) stream throws an exception.* - do we understand the mechanism how this results in delay described by the user?

**Closed by jtattermusch** 2022-05-24 07:53 UTC
Labels: kind/bug, lang/C#, platform/Windows, priority/P2

**Comment by tonydnewell** [comment] 2022-05-24 08:04
The example starts 10 child processes in the server all with redirects.  My investigation showed that the number of child processes made a difference: 5 or less no delay, > 5 then each one added about 1 second to the delay.  As exceptions were being swallowed/ignored by the example and the processes weren't being started correctly I didn't investigate further - possibly some internal .NET exception handling or garbage collection.
