### ISSUE TITLE
GRPC Channel not teared down even after deleting Channel Object

### ISSUE THREAD

**Issue by ramarkandasamy** [grpc/grpc#18976] opened 2019-05-07 12:10 UTC
### What version of gRPC and what language are you using?
 1.20.0-dev and C++
 
### What operating system (Linux, Windows,...) and version?
 Linux
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
 g++
 
### What did you do?
If possible, provide a recipe for reproducing the error. Try being specific and include code snippets if helpful.

Creating channel using 
std::shared_ptr<Channel> channel_1;
channel_1 = grpc::CreateChannel(sGoServerIP+ ":50051", grpc::InsecureChannelCredentials());
 
and trying to close the connection

delete channel_1.get();

### What did you expect to see?
 Expecting the connection to be closed and not present after the object deleted 
### What did you see instead?
But still the connection is in  ESTABLISHED state when checking "netstat -tapnu" 

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

See [TROUBLESHOOTING.md](https://github.com/grpc/grpc/blob/master/TROUBLESHOOTING.md) for how to diagnose problems better.
 
### Anything else we should know about your project / environment?
We are using GRPC for connecting with GOBGP server.

**Comment by JHDDReis** [comment] 2019-07-30 14:35
I also have this issue, I think this might be related to the library initialization?

A clean closing the channel from the client should be a must-have.

**Comment by yang-g** [comment] 2019-07-30 15:58
Not sure whether this is caused by the subchannel pool not being released.
In general the cleanup may happen in an async manner and what is observed here could be working as intended.
@JHDDReis If you have some form of repro, it could be helpful because the original one is overly simplified that it does not make sense. Thanks.

**Comment by JHDDReis** [comment] 2019-07-31 07:22
Hi @yang-g ,

I am looking at gRPC from client-side, and one of the features I need and implemented is a stream from where the client is waiting for events from a device (server):

```
m_channel = grpc::CreateChannel(target, grpc::InsecureChannelCredentials());  
...
m_stubClient = Client::NewStub(m_channel);
...
```
Then requesting the event stream and implement an 

```
 m_events = std::make_unique<std::thread>([this]()
 {
     ::google::protobuf::Empty request{};
     m_eventReader  = m_stubClient->EventStream(SetContext(m_contextAuthId, 30), request);
     event::Event message;
     std::string event;
      while (m_eventReader->Read(&message))
       {
           auto status = protoMessageToJsonString(message, event);
           if (!status.ok())
            {
                   ///.... do something 
            }
        /// ... do another something
       }
      return m_eventReader->Finish();
}
```

Now if I want to close the gRPC connection, on the client-side, the program will be hanging in the Read call until it receives a new event from the server. 

I tried to delete the channel, but it only does not work.

We could be creative and create a solution to send a request to the server to disconnect and then receive it as an event and acted upon it.

For now, the only way to perform a clean disconnect is to exit the client or forcibly detach the Read thread.

Please let me know if it is this what you wanted or if there is another workflow I am not aware of.
Thank you

**Comment by AspirinSJL** [comment] 2019-08-06 20:05
I believe each RPC holds a ref to the underlying channel. If you want to perform graceful shutdown, you may need to finish the RPC properly. At some point, we are done with the RPC, and we let either the server or the client to trigger the completion (e.g.m `WritesDone ()`).

**Closed by AspirinSJL** 2019-08-06 20:05 UTC
Labels: kind/question, lang/c++

**Comment by yang-g** [comment] 2019-08-06 21:00
@JHDDReis So the proper way to cancel a pending RPC is to try TryCancel on your ClientContext. The channel will not be cleaned up until all the rpcs are done as said above.

**Comment by JHDDReis** [comment] 2019-08-07 07:11
@yang-g thank you for the input. 
I am using the following workflow to perform a clean shutdown from client-side:

1. Send from the client a disconnect request, warning the server-side that the client will initiate the shutdown process;
2. Closing streams from the client using TryCancel the streams from the client-side at the moment;
3. Deleting the object channel.
