### ISSUE TITLE
Python artifacts build is broken on master

### ISSUE THREAD

**Issue by jtattermusch** [grpc/grpc#15364] opened 2018-05-14 18:24 UTC
https://source.cloud.google.com/results/invocations/9f530d78-3f3b-4490-9258-ab0f62f1f3ed/targets/github%2Fgrpc/tests

This is happening on multiple configurations for 100% of the builds.

**Comment by mehrdada** [comment] 2018-05-14 18:25
Probably a dupe of https://github.com/grpc/grpc/issues/15361

**Closed by mehrdada** 2018-05-14 18:25 UTC
Labels: infra/BUILDPONY, priority/P1
