### ISSUE TITLE
Objective-C: Incorrect case for generated import statements

### ISSUE THREAD

**Issue by chrisgummer** [grpc/grpc#3569] opened 2015-09-29 23:19 UTC
When using protoc to generate service proto, the generated import statements have incorrect case. Regular messages have the correct case when generated.

For example:

    #import "google/protobuf/any.proto"

results in:

    #import "Google/protobuf/any.pbobjc.h"

when we expect:

    #import "google/protobuf/Any.pbobjc.h"

**Comment by makdharma** [comment] 2016-05-02 23:16
I could not reproduce this bug on my Mac. When I compile the helloworld example, the import statement has correct case (ex: Helloworld.pbobjc.m:#import "Helloworld.pbobjc.h"). Looking at the generator code, I see that the filename passes through FileNameInUpperCamel() function from src/compiler/generator_helpers.h, which ensures that first letter is capitalized. @chrisgummer  - Can you confirm if this bug can be closed?

**Comment by jcanizales** [comment] 2016-05-03 05:56
Yeah, by blaming that function, it was indeed resolved with PR #2762

**Comment by jcanizales** [comment] 2016-05-03 06:09
Chris was probably using the gRPC plugin before the patch got released.

**Comment by makdharma** [comment] 2016-05-03 20:14
Closing.

**Closed by makdharma** 2016-05-03 20:14 UTC
Labels: ObjC, P1
