### ISSUE TITLE
.NET Standard 2.0 support

### ISSUE THREAD

**Issue by siebigteroth** [grpc/grpc#12159] opened 2017-08-11 05:50 UTC
.NET Standard 2.0 is now final: https://github.com/dotnet/announcements/issues/24

Is it planned to move to this version and support all platforms?
.NET Framework 4.6.1
.NET Core 2.0
Mono 5.4
Xamarin.iOS 10.14
Xamarin.Mac 3.8
Xamarin.Android 7.5
UWP

I'm especially interested in Xamarin.

**Comment by jtattermusch** [comment] 2017-08-11 16:33
Basically a dupe of https://github.com/grpc/grpc/issues/9441.

We are planning to support these (and we mostly already do):
.NET Framework 4.6.1
.NET Core 2.0
Mono 5.4

We are not planning to support Xamarin or UWP in the nearest future (there is an issue specifically for Xamarin support).

**Closed by jtattermusch** 2017-08-11 16:33 UTC

**Comment by kinsen** [comment] 2017-11-21 10:37
Hi , @jtattermusch . Would you tell me the plan when you release the version for .NET Core 2.0 ?

**Comment by jtattermusch** [comment] 2017-11-22 18:47
I have no ETA unfortunately - if you want to speed up the progress, you're welcome to come up with a pull request that adds the support. https://github.com/grpc/grpc/issues/9441 provides some guidance - let's continue the discussion there as this issue is closed (also, is there anything in particular that doesn't work for you?).
