### ISSUE TITLE
bins/opt/xds_end2end_test --gtest_filter=UpdatesTest.UpdateBalancersButKeepUsingOriginalBalancer is flaky

### ISSUE THREAD

**Issue by jtattermusch** [grpc/grpc#19241] opened 2019-06-05 08:58 UTC
https://source.cloud.google.com/results/invocations/b3d7098f-90e7-4cdb-8120-2bfbe79a1989/targets/github%2Fgrpc%2Fcpp_macos_opt_native/tests

**Comment by jtattermusch** [comment] 2019-06-05 08:58
```
I0604 15:49:55.567965000 140735667577728 xds_end2end_test.cc:1135]     ========= UPDATE 1 DONE ==========
I0604 15:49:55.570787000 123145426534400 subchannel.cc:1079]           New connected subchannel at 0x7fb605508ea0 for subchannel 0x7fb607009a20
test/cpp/end2end/xds_end2end_test.cc:616: Failure
Value of: status.ok()
  Actual: false
Expected: true
code=4 message=Deadline Exceeded
test/cpp/end2end/xds_end2end_test.cc:618: Failure
      Expected: response.message()
      Which is: ""
To be equal to: kRequestMessage_
      Which is: "Live long and prosper."
I0604 15:50:05.568104000 140735667577728 xds_end2end_test.cc:668]      backend about to shutdown
I0604 15:50:05.568626000 140735667577728 chttp2_transport.cc:1800]     ipv4:127.0.0.1:63053: Sending goaway err={"created":"@1559688605.568556000","description":"Server shutdown","file":"src/core/lib/surface/server.cc","file_line":320,"grpc_status":0}
I0604 15:50:05.568939000 140735667577728 xds_end2end_test.cc:672]      backend shutdown completed
I0604 15:50:05.568958000 140735667577728 xds_end2end_test.cc:668]      backend about to shutdown
I0604 15:50:05.569225000 140735667577728 xds_end2end_test.cc:672]      backend shutdown completed
I0604 15:50:05.569245000 140735667577728 xds_end2end_test.cc:668]      backend about to shutdown
I0604 15:50:05.569422000 140735667577728 xds_end2end_test.cc:672]      backend shutdown completed
I0604 15:50:05.569438000 140735667577728 xds_end2end_test.cc:668]      backend about to shutdown
I0604 15:50:05.569707000 140735667577728 xds_end2end_test.cc:672]      backend shutdown completed
I0604 15:50:05.569732000 140735667577728 xds_end2end_test.cc:668]      balancer about to shutdown
I0604 15:50:05.569746000 123145434583040 chttp2_transport.cc:1157]     ipv4:127.0.0.1:15261: Got goaway [0] err={"created":"@1559688605.569723000","description":"GOAWAY received","file":"src/core/ext/transport/chttp2/transport/chttp2_transport.cc","file_line":1151,"grpc_status":14,"http2_error":0,"raw_bytes":"Server shutdown"}
I0604 15:50:05.569766000 140735667577728 xds_end2end_test.cc:294]      LB[0x7fb60540cdb0]: shut down
I0604 15:50:05.569811000 123145431900160 xds_end2end_test.cc:280]      LB[0x7fb60540cdb0]: done
I0604 15:50:05.569904000 123145425461248 chttp2_transport.cc:1800]     ipv4:127.0.0.1:63052: Sending goaway err={"created":"@1559688605.569834000","description":"Server shutdown","file":"src/core/lib/surface/server.cc","file_line":320,"grpc_status":0}
I0604 15:50:05.570231000 140735667577728 xds_end2end_test.cc:672]      balancer shutdown completed
I0604 15:50:05.570251000 140735667577728 xds_end2end_test.cc:668]      balancer about to shutdown
I0604 15:50:05.570266000 140735667577728 xds_end2end_test.cc:294]      LB[0x7fb6055084e0]: shut down
I0604 15:50:05.570329000 140735667577728 chttp2_transport.cc:1800]     ipv4:127.0.0.1:63054: Sending goaway err={"created":"@1559688605.570306000","description":"Server shutdown","file":"src/core/lib/surface/server.cc","file_line":320,"grpc_status":0}
I0604 15:50:05.570565000 140735667577728 xds_end2end_test.cc:672]      balancer shutdown completed
I0604 15:50:05.570570000 123145434583040 subchannel.cc:1028]           Connect failed: {"created":"@1559688605.570527000","description":"Failed to connect to remote host: Connection refused","errno":61,"file":"src/core/lib/iomgr/tcp_client_posix.cc","file_line":207,"os_error":"Connection refused","syscall":"connect","target_address":"ipv4:127.0.0.1:15261"}
I0604 15:50:05.570595000 140735667577728 xds_end2end_test.cc:668]      balancer about to shutdown
I0604 15:50:05.570637000 123145434583040 chttp2_transport.cc:1157]     ipv4:127.0.0.1:32478: Got goaway [0] err={"created":"@1559688605.570627000","description":"GOAWAY received","file":"src/core/ext/transport/chttp2/transport/chttp2_transport.cc","file_line":1151,"grpc_status":14,"http2_error":0,"raw_bytes":"Server shutdown"}
I0604 15:50:05.570667000 140735667577728 xds_end2end_test.cc:294]      LB[0x7fb607002a20]: shut down
I0604 15:50:05.570781000 123145434583040 chttp2_transport.cc:1157]     ipv4:127.0.0.1:25478: Got goaway [0] err={"created":"@1559688605.570765000","description":"GOAWAY received","file":"src/core/ext/transport/chttp2/transport/chttp2_transport.cc","file_line":1151,"grpc_status":14,"http2_error":0,"raw_bytes":"Server shutdown"}
I0604 15:50:05.570823000 123145434583040 subchannel.cc:967]            Subchannel 0x7fb60700da80: Retry in 999 milliseconds
I0604 15:50:05.570910000 140735667577728 xds_end2end_test.cc:672]      balancer shutdown completed
[  FAILED  ] UpdatesTest.UpdateBalancersButKeepUsingOriginalBalancer (10040 ms)
```

**Comment by markdroth** [comment] 2019-12-13 15:53
This looks like a duplicate of #20711.

**Closed by markdroth** 2019-12-13 15:53 UTC
Labels: infra/BUILDPONY, kind/bug, lang/core, priority/P2
