### ISSUE TITLE
gRPC Connection Between Docker Containers on Amazon ECS Failing

### ISSUE THREAD

**Issue by skybox2** [grpc/grpc#19633] opened 2019-07-12 18:55 UTC
### What version of gRPC and what language are you using?
Client: Python 3.5.6
Client gRPC version: 
```
grpcio                 1.21.1
grpcio-tools           1.21.1
```
Server: Scala 2.12.8 
 
### What operating system (Linux, Windows,...) and version?
Ubuntu 16.04.6 LTS (GNU/Linux 4.4.0-1087-aws x86_64)
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
Python 
 
### What did you do?
We deployed two docker containers on an Ubuntu Amazon EC2 machine using ECS task definitions. The first container is a Scala server that is exposing a gRPC endpoint to the second container, which is the Python client.

Both on the host machine and while bashed in to the Python container, we tried to run the following client code:
```
import grpc

import LookupService_pb2
import LookupService_pb2_grpc

def run():
    # NOTE(gRPC Python Team): .close() is possible on a channel and should be
    # used in circumstances in which the with statement does not fit the needs
    # of the code.

    with grpc.insecure_channel('localhost:2530') as channel:
        stub = LookupService_pb2_grpc.LookupServiceStub(channel)
        response = stub.lookupTransaction(LookupService_pb2.LookupRequest(input_param="input_param")
        print(response)

run()
```
The connection works fine when we run the client on the host machine. However, regardless of the docker network configuration, we get a `StatusCode.UNAVAILABLE` error when attempting to connect to the server from inside the Python docker container.

We've tried several different network configurations:
1. Adding both containers to the docker host network, and exposing the Scala server gRPC port on the host network. Host strings attempted: `localhost:2530`, `127.0.0.1:2530`, `::1:2530`. 
2. Adding both containers to the default docker bridge network, and exposing the Scala server gRPC port on the bridge network (`0.0.0.0:2530->2530/tcp`). Host string attempted: `localhost:2530`, `172.17.0.1:2530`, `172.17.0.3:2530`. The last IP was pulled by running `docker network inspect bridge`. 
3. Creating a custom bridge network and adding both containers to the network. Same connection strings as (2).
 
### What did you expect to see?
 Successful connection from the Python client to the Scala server.
 
### What did you see instead?
 We saw the following error when we ran the gRPC sample client in the docker container running the Python client: 
```
Traceback (most recent call last):
  File "grpc_client.py", line 16, in <module>
    run()
  File "grpc_client.py", line 13, in run
    response = stub.lookupTransaction(LookupService_pb2.LookupRequest(input_params='param'))
  File "/usr/local/lib/python3.5/site-packages/grpc/_channel.py", line 565, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/usr/local/lib/python3.5/site-packages/grpc/_channel.py", line 467, in _end_unary_response_blocking
    raise _Rendezvous(state, None, None, deadline)
grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with:
    status = StatusCode.UNAVAILABLE
    details = "Socket closed"
    debug_error_string = "{"created":"@1562952583.277651283","description":"Error received from peer ipv4:10.203.7.8:8099","file":"src/core/lib/surface/call.cc","file_line":1046,"grpc_message":"Socket closed","grpc_status":14}"
```
### Anything else we should know about your project / environment?
netstat output for our server:
```
root@ip-x-x-x-x:~# netstat -tulpn | grep 2530
tcp6       0      0 :::2530                 :::*                    LISTEN      17297/docker-proxy
```

**Comment by gnossen** [comment] 2019-07-12 20:17
@skybox2 Can you please help us troubleshoot the problem?

Let's start by eliminating docker networking issues. It sounds like you have the ability to shell into your containers. Can you install netcat and run `nc -l -s ${SERVER_CONTAINER_IP} -p ${SERVER_PORT}` from the server container and `echo "test" | nc ${SERVER_CONTAINER_IP} ${SERVER_PORT}` from the client container. 

Also, let's get some more output from the client. Please set the following [environment variables](https://github.com/grpc/grpc/blob/master/doc/environment_variables.md) when running the client.

```
GRPC_TRACE=all
GRPC_VERBOSITY=DEBUG
```

If we don't get information from either of these, we might need a minimal reproduction case.

**Comment by lidizheng** [comment] 2019-07-12 20:36
@skybox2 If you are using AWS L4 ELB, there is an known issue https://github.com/grpc/grpc/issues/18710 preventing gRPC traffic to go through.

**Comment by lidizheng** [comment] 2019-09-03 17:39
Closing since reporter didn't reply, if this issue still exist, please reopen it.

**Closed by lidizheng** 2019-09-03 17:39 UTC
Labels: disposition/requires reporter action, kind/bug, lang/Java, lang/Python
