### ISSUE TITLE
Code coverage csharp ext coverage is unavailable.

### ISSUE THREAD

**Issue by adelez** [grpc/grpc#6672] opened 2016-05-20 19:00 UTC
https://grpc-testing.appspot.com/job/gRPC_coverage/5642/HTML_Report/

**Comment by jtattermusch** [comment] 2016-05-23 01:29
Thank for filing this but I won't have time for this any time soon. 

The HTML report works correctly on pull requests (csharp, linux, gcov) though, so I suspect it's a nit. Mind taking a look?

https://grpc-testing.appspot.com/view/Pull%20requests/job/gRPC_pull_requests/9176/config=gcov,language=csharp,platform=linux/

**Comment by jtattermusch** [comment] 2016-05-23 01:33
Ok, so it's unavailable because all the C# tests gcov tests are failing
https://grpc-testing.appspot.com/job/gRPC_coverage/5642/#showFailuresLink

But they work no problem on gRPC pull request  - so I suspect the problem is the fact that we are running all the gcov tests under a single multilang image.

**Comment by jtattermusch** [comment] 2016-05-23 01:34
btw, the C# code coverage itself (not the C# ext code) is on pull requests under gcov,windows (as getting line coverage for C# code on linux is tricky).

**Comment by jtattermusch** [comment] 2016-05-23 01:36
Btw in the previous build https://grpc-testing.appspot.com/job/gRPC_coverage/5641/HTML_Report/  the C# coverage is available - so it's just that the test have failed.

**Comment by adelez** [comment] 2016-05-24 22:56
Thank you for looking into this. Closing this bug then,

**Comment by adelez** [comment] 2016-05-26 00:55
It seems both C# and PHP code coverages are rarely available. You have to open many tests before being able to see a valid report. We need to somehow still generate the report even if the test fails. @stanley-cheung for PHP.

**Comment by jtattermusch** [comment] 2016-11-22 08:25
Currently all code coverage reports are broken so this issue is not useful anymore (closing for bankruptcy).

**Closed by jtattermusch** 2016-11-22 08:25 UTC
Labels: C#
