### ISSUE TITLE
tests.Grpc.Core.Tests timeout 

### ISSUE THREAD

**Issue by a11r** [grpc/grpc#4320] opened 2015-12-07 22:47 UTC
https://grpc-testing.appspot.com/job/gRPC_master/13538/config=opt,language=csharp,platform=linux/testReport/

**Comment by jtattermusch** [comment] 2015-12-16 21:31
I've split out C# tests into separate processes by test class. This should make tracking down the root cause of the timeout easier.

closing this issue as test "tests.Grpc.Core.Tests" as such doesn't exist anymore.

**Closed by jtattermusch** 2015-12-16 21:31 UTC
Labels: BUILDPONY, C#, P0
