### ISSUE TITLE
the broken path for the release package on 'pecl.php.net'

### ISSUE THREAD

**Issue by simonkuang** [grpc/grpc#7937] opened 2016-08-31 06:39 UTC
There is a bug in `config.m4` of php-ext release package on 'pecl.php.net'. It's some broken include path.

From line 8 to 10:
```
  PHP_ADD_INCLUDE(../../grpc/include)
  PHP_ADD_INCLUDE(../../grpc/src/php/ext/grpc)
  PHP_ADD_INCLUDE(../../grpc/third_party/boringssl/include)
```

But, all of three include path are broken. It should be just one line:
```
  PHP_ADD_INCLUDE(third_party/boringssl/include)
```

**Comment by simonkuang** [comment] 2016-08-31 07:10
Some logs with error.

while `configure`

    ...
    checking for awk... awk
    checking if awk is broken... no
    checking whether to enable grpc support... yes, shared
    ./configure: line 4107: cd: ../../grpc: No such file or directory
    ./configure: line 4138: cd: ../../grpc/src/php/ext: No such file or directory
    ./configure: line 4169: cd: ../../grpc/third_party/boringssl: No such file or directory
    checking for ld used by cc... /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ld
    checking if the linker (/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ld) is GNU ld... no
    checking for /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ld option to reload object files... -r
    checking for BSD-compatible nm... /usr/bin/nm -B
    ...


while `make`

    ...
    In file included from /Volumes/RamDisk/grpc-1.0.0/src/core/lib/security/credentials/google_default/google_default_credentials.c:46:
    In file included from ./src/core/lib/security/credentials/jwt/jwt_credentials.h:38:
    ./src/core/lib/security/credentials/jwt/json_token.h:38:10: fatal error: 'openssl/rsa.h' file not found
    #include <openssl/rsa.h>
             ^
    1 error generated.
    make: *** [src/core/lib/security/credentials/google_default/google_default_credentials.lo] Error 1

**Comment by stanley-cheung** [comment] 2016-08-31 07:39
Probably dupe of #7922

**Comment by simonkuang** [comment] 2016-08-31 07:52
>stanley-cheung commented 6 minutes ago
>Probably dupe of #7922

oh yes, it's about the same problem.

should i close this issue?

**Comment by stanley-cheung** [comment] 2016-08-31 21:36
What platform / OS version did you get this error? And how can I reproduce?

**Comment by simonkuang** [comment] 2016-09-01 08:04
>@stanley-cheung
> 
>stanley-cheung commented 6 hours ago
>What platform / OS version did you get this error? And how can I reproduce?

MacOS and CentOS 7.X x84_64

steps:

```
wget https://pecl.php.net/get/grpc-1.0.0.tgz
tar zxf grpc-1.0.0.tgz
cd grpc-1.0.0
phpize
./configure    ## get the warning about three broken pathes
make    ##  get the fatal error that cannot find 'openssl/rsa.h'
```

or 

```
pecl install grpc    ## for new install
pecl upgrade grpc    ## for guys who installed a previous version
```

**Comment by thinkerou** [comment] 2016-09-01 08:40
Hi, maybe you should read the discuss #7923.

**Comment by stanley-cheung** [comment] 2016-09-01 15:21
The pecl package is not considered source so we don't support unzipping it and then running `phpize`, `./configure` etc. If you want to compile from source, you need to follow the instructions in the [src/php/README.md](https://github.com/grpc/grpc/tree/master/src/php). 

I have just tried on Mac and I am able to do a fresh install of `pecl install grpc`. If `pecl install grpc` fails for you, can you show me the log please?

**Comment by simonkuang** [comment] 2016-09-02 08:43
>@stanley-cheung
>
>stanley-cheung commented 15 hours ago • edited
>The pecl package is not considered source so we don't support unzipping it and then running phpize, ./configure etc. If you want to compile from source, you need to follow the instructions in the src/php/README.md.
>
>I have just tried on Mac and I am able to do a fresh install of pecl install grpc. If pecl install grpc fails for you, can you show me the log please?

I have checked out the installation with pecl on CentOS, it's perfect. Sorry for my negligence.

The solution with pecl to install grpc ext is good.

But still i cannot build grpc extensions from source on pecl.php.net, and this is exactly the way to build ext with homebrew on Mac. So i'm trapped between 'fixing' grpc release package on pecl site for source building and 'fixing' homebrew formula modifying 'config.m4' before phpize. The latter hacking solution is not elegant, i think.

Additional, the php installed with homebrew by default has no pear module, there is no `pecl` command. homebrew encourages to install php ext with `brew install` instead of `pecl install`. May we should consider the situations that homebrew formula and many other automatic scripts which build php ext from the source downloaded on 'pecl.php.net'. If they have to clone the whole grpc repo, there is a huge cost in network transmission.

**Comment by stanley-cheung** [comment] 2016-09-02 19:55
Yea the current status is that we only support the one line package install thru `pecl install`, or compile from source thru github. Previously we looked into supporting `brew install` but run into a bunch of problems. I will keep this in mind to see if we can support `brew install` in the future.

**Closed by stanley-cheung** 2016-09-02 19:55 UTC
Labels: php
