### ISSUE TITLE
CreateChannel stuck in infinite loop

### ISSUE THREAD

**Issue by williamledda** [grpc/grpc#29247] opened 2022-03-29 08:46 UTC
### What version of gRPC and what language are you using?
v 1.44.0

### What operating system (Linux, Windows,...) and version?
```
$ uname -a
Linux wled 5.13.0-37-generic #42~20.04.1-Ubuntu SMP Tue Mar 15 15:44:28 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
````

### What runtime / compiler are you using (e.g. python version or version of gcc)
```
$ which g++
/usr/lib/ccache/g++

$ /usr/lib/ccache/g++ --version
g++ (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0

$ ccache --version
ccache version 3.7.7

Copyright (C) 2002-2007 Andrew Tridgell
Copyright (C) 2009-2020 Joel Rosdahl
```

### What did you do?
I can just reproduce creating a channel
```
int main(int argc, char** argv) {
  std::string target_str = "localhost:5044";
  grpc::CreateChannel(target_str, grpc::InsecureChannelCredentials());
  std::cout << "Done with grpc version: " << grpc::Version() << "\n";
  return 0;
}
```

### What did you expect to see?

- Application does not hang up.
- grpc version at the end.

### What did you see instead?

- Application hangs up and takes 100% CPU
- By running with `GRPC_VERBOSITY=DEBUG GRPC_TRACE=all`, I can see the following:
```
$ GRPC_VERBOSITY=DEBUG GRPC_TRACE=all data_cache_app
D0328 16:20:51.468528054   10862 ev_posix.cc:173]            Using polling engine: epollex
D0328 16:20:51.468591334   10862 lb_policy_registry.cc:42]   registering LB policy factory for "grpclb"
D0328 16:20:51.468597282   10862 lb_policy_registry.cc:42]   registering LB policy factory for "priority_experimental"
D0328 16:20:51.468599578   10862 lb_policy_registry.cc:42]   registering LB policy factory for "weighted_target_experimental"
D0328 16:20:51.468601543   10862 lb_policy_registry.cc:42]   registering LB policy factory for "pick_first"
D0328 16:20:51.468603473   10862 lb_policy_registry.cc:42]   registering LB policy factory for "round_robin"
D0328 16:20:51.468610472   10862 dns_resolver_ares.cc:491]   Using ares dns resolver
D0328 16:20:51.468619474   10862 certificate_provider_registry.cc:33] registering certificate provider factory for "file_watcher"
D0328 16:20:51.468624073   10862 lb_policy_registry.cc:42]   registering LB policy factory for "cds_experimental"
D0328 16:20:51.468626361   10862 lb_policy_registry.cc:42]   registering LB policy factory for "xds_cluster_impl_experimental"
D0328 16:20:51.468630510   10862 lb_policy_registry.cc:42]   registering LB policy factory for "xds_cluster_resolver_experimental"
D0328 16:20:51.468632717   10862 lb_policy_registry.cc:42]   registering LB policy factory for "xds_cluster_manager_experimental"
```

### Anything else we should know about your project / environment?
- c++17
- This seems exactly the same of #21280

**Comment by williamledda** [comment] 2022-03-29 12:41
Some discovering:

- After other tests, I found that by calling ``grpc_init()`` before calling the ``grpc::CreateChannel(...)`` works. Do I need to call it explicitly?

- Depending on how I link my test application I need to call the grpc_init() or not:
**Need** to call grpc_init(): ``test_app -> a_library -> a_communication_library -> gRPC::grpc++``
**No** Need to call grpc_init(): ``test_app -> a_library -> gRPC::grpc++``

Is there a proper/recommended way to initialize the library?

**Comment by ctiller** [comment] 2022-03-29 16:24
Any chance you could run your program under a debugger and collect a call
stack on wherever it's spinning?

**Comment by yashykt** [comment] 2022-04-01 20:37
Assigning @veblush as the one who originally fixed it

**Comment by veblush** [comment] 2022-04-14 22:31
Usually this would be a symptom of the ODR ([link](https://github.com/grpc/grpc/issues/24422#issuecomment-843326936)) would you show how to build it (preferably a build script) if possible.

**Comment by williamledda** [comment] 2022-08-04 11:14
@veblush 
Is the change proposed in https://github.com/grpc/grpc/issues/24422#issuecomment-1023458026 an actual workaround/solution? Is so is it included, or is there any plan to include it in any version?

**Comment by williamledda** [comment] 2022-09-04 15:08
Hello? Any update on this issue?

**Comment by amscins** [comment] 2022-12-08 15:35
> @veblush Is the change proposed in [#24422 (comment)](https://github.com/grpc/grpc/issues/24422#issuecomment-1023458026) an actual workaround/solution? Is so is it included, or is there any plan to include it in any version?

@williamledda 

Well, *I* have been struggling with this issue half a day now, and I'm definitely a grpc beginner, but for me this comment actually helps.

Curious how such a blocker issue can remain unsolved for over a year.

**Comment by btbouwens** [comment] 2022-12-09 08:41
Same here, running Fedora 36 with grpc 1.41 I still got the same issue.
Building and installing the latest grpc (1.51) also didn't solve it, but with the above comment it finally works!

**Comment by williamledda** [comment] 2022-12-10 16:36
@amscins @btbouwens 
I agree but it is extremely annoying because if you change the version you have to apply the patch again. I really do not understand how it is possible that this is not included yet on the official release yet.

**Comment by veblush** [comment] 2022-12-15 18:19
I'm closing this as this problem is caused by ODR violation having multiple gRPC libraries linked.

**Closed by veblush** 2022-12-15 18:19 UTC
Labels: kind/bug, lang/c++, priority/P2

**Comment by btbouwens** [comment] 2022-12-20 10:13
So I understand that it is illegal to use libgrpc++_unsecure.so and libgrpc++_reflection.so in one build, as the former will pull in libgrpc_unsecure.so and the latter libgrpc.so, both of which contain _Z16grpc_tracer_initPKc and _Z16grpc_tracer_initv to name some examples ....

**Comment by williamledda** [comment] 2022-12-20 20:51
> So I understand that it is illegal to use libgrpc++_unsecure.so and libgrpc++_reflection.so in one build, as the former will pull in libgrpc_unsecure.so and the latter libgrpc.so, both of which contain _Z16grpc_tracer_initPKc and _Z16grpc_tracer_initv to name some examples ....

Interesting consideration, unftortunately it doesn't seem properly documented anywhere. If you also look at the exemples (just take the hello world) it links both ${_REFLECTION} ${_GRPC_GRPCPP} to the same target.

**Comment by chf2117** [comment] 2024-07-03 16:13
@veblush Since this is a perennial issue, would it be possible to add a clear failure message for these ODR violations instead of an infinite loop?
