### ISSUE TITLE
Bug: Python grpcio: Reconnecting to server fails because try_to_connect is not honored?

### ISSUE THREAD

**Issue by viksit** [grpc/grpc#6478] opened 2016-05-06 22:30 UTC
In a situation where the server goes down, what is the best way to get the python client to keep trying?

In the following situation, it seems to go into an IDLE state and doesn't retry if the server is killed.

```
channel = implementations.insecure_channel(server, port)
channel.subscribe(lambda x: print("cb: ", x), True)
```

The subscription callback prints TRANSIENT_FAILURE, and moves to IDLE - and thats it.

What am I missing here?

Edit:

It appears that if I set the success callback with try_to_connect=True, for some reason it isn't honored. If I end up doing this however, the client tries to reconnect.

```
channel._connectivity_channel._try_to_connect = True
```

Can someone verify this?

**Comment by sunwangme** [comment] 2016-05-08 07:18
yes,  unsubscrible + subscrible repeated.

the bug:
_connectivity_channel.py
def _poll_connectivity(self, low_channel, initial_try_to_connect):
......
while True:
low_channel.watch_connectivity_state(
low_connectivity, time.time() + 0.2, completion_queue, None)
event = completion_queue.next()
with self._lock:
if not self._callbacks_and_connectivities and not self._try_to_connect:
self._polling = False
self._connectivity = None
completion_queue.shutdown()
break
try_to_connect = self._try_to_connect //<--------
self._try_to_connect = False //<--------- dont reconnect after shutdown

**Comment by nathanielmanistaatgoogle** [comment] 2016-06-16 21:37
@viksit: could you elaborate a little more on what your expectations are? Is it the case that you expect the channel to continue to attempt to connect for the entire time that your callback is subscribed?

@sunwangme: could you elaborate a little more on what specifically is defective about the two lines to which you've called attention? What would you change about them to fix them?

**Comment by sunwangme** [comment] 2016-06-17 00:28
it is not a bug,if write more comments about api.

sorry, but we change solution to grpc-go.

grpc-python raise error:cant spawn thread after run 20 hours. and nobody help us.

we just detect channel state.by send unary ping with timeout,  grpc-go removed channel state api.

**Comment by viksit** [comment] 2016-06-17 01:01
@nathanielmanistaatgoogle essentially, it looks like the try_to_connect param isn't being honored. I got past it by setting it explicitly.

The behavior that I'd like is this: if an upstream grpc server goes down, the client shouldn't just sit IDLE, because when it comes back up, it won't be utilized. Ideally, the client should keep trying with some sort of exponential backoff.

I believe this behavior is already in there, but due to some logic (which could be a bug), it appears that the flag is set to False when it should in fact obey what the constructor set earlier.

**Comment by nathanielmanistaatgoogle** [comment] 2016-06-18 16:22
I think the `try_to_connect` param is being honored - when an application subscribes to a channel's connectivity, the channel tries to connect _just at that time_. Perhaps we should change the documentation of the parameter to more clearly state that it applies only at subscription-time and not for the entire duration of the application's connectivity subscription?

There may be a case for supporting channels that always try to stay connected, but after speaking with @ctiller about this we're concerned about channels creating busywork for servers. Could you tell us more about your intended use case? If channels were to always keep trying to connect when they weren't connected, how would your application be improved?

**Comment by alamaison** [comment] 2016-10-19 17:01
Does this mean `channel_ready_future` only tries to connect the channel if it has never been connected before?  But if it was connected and since got disconnected its `result()` returns successfully?

**Comment by nathanielmanistaatgoogle** [comment] 2016-10-21 01:55
@alamaison: I think there's a race condition in your question - if a channel has been connected and then is disconnected and then `channel_ready_future` is called, the `Future` that is returned may mature immediately (if the channel hadn't yet detected that it is disconnected) or may not mature until the channel is reconnected. Can you tell us more about the use case from which your question arises?

**Comment by alamaison** [comment] 2016-10-21 09:16
@nathanielmanistaatgoogle Ok so we understood that `channel_ready_future` would make sure channel was connected before maturing.  We've been calling it before making every API call, to make sure the channel hasn't been disconnected while idle.

But we've found that after some idle time, an API call will fail with 'connection reset by peer' despite `channel_ready_future` maturing successfully.  If we repeat the API call on the same stub/channel (with no further call to `channel_ready_future`) it succeeds, as though the failed call has caused the channel to realise it was disconnected and reconnect.

However, if we go idle again then call `channel._channel.check_connectivity_state` on the underlying cython channel instead of using `channel_ready_future`, the API call succeeds first time.

Obviously we'd rather not call private internals, but what is the correct way to do this?

**Comment by alamaison** [comment] 2016-10-21 13:52
@nathanielmanistaatgoogle It may be that `channel._channel.check_connectivity_state` doesn't actually repair the channel reliably after all.  So take that bit with a pinch of salt

**Comment by nathanielmanistaatgoogle** [comment] 2016-10-21 15:42
@alamaison: if you're able to report a circumstance in which `cygrpc.Channel.check_connectivity_state(True)` does not actually repair the channel when it can we'd love to hear about it.

To the more general question of "what is the correct way?": if it's RPCs that you want to make, just make your RPCs. Checking connectivity before making an RPC is inherently racy if your connection is flapping. If what you care about is successful RPCs, why not just attempt RPCs and see which ones are successful? Tell us more about your use case that helps us understand why channel connectivity, in the absence of RPCs, is interesting?

**Comment by alamaison** [comment] 2016-10-21 15:47
@nathanielmanistaatgoogle What seems to be happening is the channel thinks it's ready.  `cygrpc.Channel.check_connectivity_state(False)` returns `2` (READY) therefore `cygrpc.Channel.check_connectivity_state(True)` doesn't do anything because it thinks it has nothing to do.  In the cases where `cygrpc.Channel.check_connectivity_state(True)` _did_ repair the channel, it returned `1` meaning it considered itself IDLE.

**Comment by alamaison** [comment] 2016-10-21 16:02
> if it's RPCs that you want to make, just make your RPCs

The reason we have been checking connectivity state is that we didn't want to risk retrying an RPC that has side effects - is it guaranteed that the server didn't receive the RPC when `StatusCode.UNAVAILABLE` is raised?

Of course, even if that were the case, the RPC could fail to return after the server acts on it and the callers need custom retry logic.  But checking connectivity seemed like a reasonable interim measure.

**Comment by alamaison** [comment] 2016-10-21 16:04
> if you're able to report a circumstance in which cygrpc.Channel.check_connectivity_state(True) does not actually repair the channel

FWIW, this only seems to happen on one particular link that leaves one AWS VPC, routes via the internet, and enters a different AWS account's VPC.

**Comment by nathanielmanistaatgoogle** [comment] 2016-10-25 20:04
If you can turn your observations with `cygrpc.check_connectivity_state`/`cygrpc.watch_connectivity_state` into a program (or program) that fail(s) when it(they) should succeed, we'd love that bug report, especially if the failure only happens on one particular link.

As to the problem of making RPCs that you're actually trying to solve: the only guarantee is that if you see status `OK` on the client then at least one backend received the RPC, processed it, and emitted `OK` status. `UNAVAILABLE` does not guarantee anything about the RPC not-having-been-attempted on any backend. So... what's stopping your RPCs from being idempotent?

**Comment by alamaison** [comment] 2016-10-25 21:29
When you say at least one backend server, presumably it would be exactly one if we're not using the new load balancing API?

> So... what's stopping your RPCs from being idempotent?

Do you mean the server-side should deduplicate the requests? In some cases, such as RPCs to create a new instance of something, it's not obvious to me how to detect the duplication server-side. Unless all requests take an ID specifically for the purpose. 

Are gRPC RPCs generally expected to be idempotent?

We'll try and put a repro program together

**Comment by alamaison** [comment] 2016-10-27 16:29
@nathanielmanistaatgoogle 
> we'd love that bug report

Done: #8538

**Comment by nathanielmanistaatgoogle** [comment] 2016-11-02 00:55
Yes, it would presumably be exactly one if the channel you create on your client is a direct connection to exactly one server.

It is **not** the case that gRPC _requires_ idempotence in application-level RPC semantics.

Allowing my own personal engineering orientation and history to bleed into the conversation: idempotence solves a lot of problems before they even arise, so I recommend defaulting to making it part of your application-level protocol.

**Comment by muxi** [comment] 2017-12-11 22:25
@nathanielmanistaatgoogle can we close this?

**Comment by nathanielmanistaatgoogle** [comment] 2017-12-31 20:26
Closing; please poke us if closing is a mistake and the problem described here remains an ongoing defect!

**Closed by nathanielmanistaatgoogle** 2017-12-31 20:26 UTC
Labels: kind/enhancement, lang/Python, priority/P2
