### ISSUE TITLE
FLAKE: //test/core/slice:slice_test for C++ on Windows

### ISSUE THREAD

**Issue by lidizheng** [grpc/grpc#20547] opened 2019-10-09 23:07 UTC
https://source.cloud.google.com/results/invocations/c1d81945-e498-45aa-a257-6b8d16815b4d/targets

Exit with non-zero code, not much information.

**Comment by jtattermusch** [comment] 2019-10-10 06:46
dupe of https://github.com/grpc/grpc/issues/20519

**Closed by jtattermusch** 2019-10-10 06:46 UTC
Labels: kind/bug, lang/c++, priority/P2
