### ISSUE TITLE
The 'Pods' target has transitive dependencies that include static binaries:

### ISSUE THREAD

**Issue by yarnping** [grpc/grpc#4199] opened 2015-11-22 09:06 UTC
I follow this by step
https://github.com/grpc/grpc/tree/release-0_11/src/objective-c
command pod install error shows up
The 'Pods' target has transitive dependencies that include static binaries: (/Users/xxx/workspace/xcode/iBBS-Swift/Pods/OpenSSL/lib/libcrypto.a and /Users/xxx/workspace/xcode/iBBS-Swift/Pods/OpenSSL/lib/libssl.a)

**Comment by sipdar** [comment] 2015-11-23 02:30
--use-libraries

**Comment by ceoacai** [comment] 2015-11-23 03:08
@sipdar pod lib lint --use-libraries， in which directory to use this command？
I found in Podfile use_frameworks! lead to error,but I can't remove use_frameworks! cause I already use several frameworks

**Comment by bdotdub** [comment] 2015-11-24 17:20
This is related to #4121

**Comment by jcanizales** [comment] 2015-12-01 21:25
I've got a change ready, to switch our OpenSSL podspec to something that doesn't require using static libraries. But once that is cleared, there are still problems that I've filed in the Cocoapods repo: https://github.com/CocoaPods/CocoaPods/issues/4605

**Comment by hsaliak** [comment] 2016-04-29 18:31
Duplicate of  #4351. let's continue the discussion there.

**Closed by hsaliak** 2016-04-29 18:31 UTC
Labels: ObjC, wrapped languages
