### ISSUE TITLE
Allow run_performance_tests to upload all non failing tests

### ISSUE THREAD

**Issue by vjpai** [grpc/grpc#6899] opened 2016-06-14 18:59 UTC
Otherwise, one failing test will kill everything that comes afterward (eg #6898)

**Comment by jtattermusch** [comment] 2016-06-14 20:38
All results are uploaded separately. The problem is that the following scenarios actually fail, not really in uploading results.

**Comment by jtattermusch** [comment] 2016-06-14 20:40
Ok, so #6898 is because there's a build failure. Special casing the logic to skip tests for given language if build has failed would be too complicated.

**Comment by vjpai** [comment] 2016-06-14 20:40
I understand why the following scenarios in the same language would fail (dead workers?) but why does this fail across languages?

**Comment by jtattermusch** [comment] 2016-06-14 20:42
I think what we really need is https://github.com/grpc/grpc/issues/6540. There are probably simple answers why some scenarios are failing, but the only thing we see is an assertion failure.

**Comment by dgquintas** [comment] 2016-11-16 00:06
ping

**Comment by jtattermusch** [comment] 2016-11-16 08:19
I don't think this can be reasonably addressed in the nearest future. If build fails, the perf tests fail, that makes sense.
We should be in a position when all languages are always buildable (i.e. not ignoring tests and get rid of infrastructure flakes if any), and then we don't have a problem.

**Closed by jtattermusch** 2016-11-16 08:19 UTC
Labels: benchmarking, tools
