### ISSUE TITLE
Greeter example doesn't work with latest Nuget assemblies

### ISSUE THREAD

**Issue by qed-** [grpc/grpc#11426] opened 2017-06-07 12:31 UTC
### What version of gRPC and what language are you using?
1.3.6, C# 
 
### What operating system (Linux, Windows, …) and version?
Windows 10 build 14393.693

 ### What runtime / compiler are you using (e.g. python version or version of gcc)
Visual studio 2015, .Net 4.5 
 
### What did you do?
Follow the Quickstart instructions here (which checks out from the 1.0.x branch) http://www.grpc.io/docs/quickstart/csharp.html the Greeter client/server demo apps work correctly.

Then update Nuget libraries, which installs Grpc 1.3.6, and run example apps again.

### What did you expect to see?
Example apps running as before. 
 
### What did you see instead?
Unhandled exception in the client app:
An unhandled exception of type 'Grpc.Core.RpcException' occurred in mscorlib.dll
Additional information: Status(StatusCode=Unavailable, Detail="Connect Failed")

**Comment by jtattermusch** [comment] 2017-06-09 10:17
You're right saying that we should update the Quickstart page to refer to a newer branch than v1.0.x (which is ~9months old).

Nevertheless, I've tried to reproduce based on your instructions and everything worked just fine.
Actually, you'll get the `An unhandled exception of type 'Grpc.Core.RpcException' occurred in mscorlib.dll
Additional information: Status(StatusCode=Unavailable, Detail="Connect Failed")` error when you run the client without starting a server first - did you forget to run the server?

**Comment by jtattermusch** [comment] 2017-06-09 10:17
Closing as I cannot reproduce the problem.

**Closed by jtattermusch** 2017-06-09 10:17 UTC
Labels: C#, Windows
