### ISSUE TITLE
python performance benchmarks are broken on master

### ISSUE THREAD

**Issue by jtattermusch** [grpc/grpc#15293] opened 2018-05-07 17:10 UTC
They have been failing for a while

https://source.cloud.google.com/results/invocations/d88092df-1c56-43c6-b098-2bd8e477fbca/targets/github%2Fgrpc%2Freports%2F8core/tests;query=python;passed=true

Looks like client is failing to connect
```
I0507 04:30:29.350729874    4872 subchannel.cc:470]          Subchannel 0x7f2068003600: Retry in 1633 milliseconds
I0507 04:30:30.983245677    4876 subchannel.cc:425]          Failed to connect to channel, retrying
I0507 04:30:30.983805413    4872 subchannel.cc:646]          Connect failed: {"created":"@1525667430.983748889","description":"Failed to connect to remote host: OS Error","errno":111,"file":"src/core/lib/iomgr/tcp_client_posix.cc","file_line":201,"os_error":"Connection refused","syscall":"connect","target_address":"ipv4:10.240.0.251:10500"}
I0507 04:30:30.983832099    4872 subchannel.cc:470]          Subchannel 0x7f2068003600: Retry in 2353 milliseconds
I0507 04:30:33.336200997    4874 subchannel.cc:425]          Failed to connect to channel, retrying
I0507 04:30:33.336844774    4872 subchannel.cc:646]          Connect failed: {"created":"@1525667433.336772710","description":"Failed to connect to remote host: OS Error","errno":111,"file":"src/core/lib/iomgr/tcp_client_posix.cc","file_line":201,"os_error":"Connection refused","syscall":"connect","target_address":"ipv4:10.240.0.251:10500"}
```

**Comment by mehrdada** [comment] 2018-05-15 23:10
Closing as dupe of https://github.com/grpc/grpc/issues/15376

**Closed by mehrdada** 2018-05-15 23:10 UTC
Labels: area/performance/benchmarking, infra/BUILDPONY, kind/internal cleanup, lang/Python, priority/P2
