### ISSUE TITLE
C# - Server fails to release sockets

### ISSUE THREAD

**Issue by mgravell** [grpc/grpc#23390] opened 2020-07-06 07:51 UTC
(cross-reference: https://github.com/protobuf-net/protobuf-net.Grpc/issues/109)

It seems that `Server` is very reluctant to release sockets, even when `KillAsync` or `ShutdownAsync` is called and awaited - subsequent calls to `Start()` on the same port are likely to fail. Is this known/intentional?

Tested (with failure) on `2.29.0` and `2.30.0`

Example:

``` c#
[Fact]
public async Task ServerFailsToReleasePort()
{
    var port = 10050;

    var server = new Server()
    {
        Ports = { new ServerPort("localhost", port, ServerCredentials.Insecure) }
    };
    // it seems that the port is already in use at this point

    // try all kinds of ways to release the port
    await server.ShutdownAsync();
    // await server.KillAsync(); // kill also doesn't release, but can't Shutdown *and* Kill
    await server.ShutdownTask;
            

    var server2 = new Server()
    {
        Ports = { new ServerPort("localhost", port, ServerCredentials.Insecure) }
    };

    // server2.Services.Add(...) // note: repros even without any services added
    server2.Start(); // <--- crash, socket is still in use.
}
```

**Comment by mgravell** [comment] 2020-07-06 08:08
(adding @TFTomSun)

**Comment by TFTomSun** [comment] 2022-03-15 13:47
@jtattermusch on windows

**Comment by rburns1293** [comment] 2022-05-18 19:36
```C#
class Program
  {
    const int Port = 30051;

    public async static Task Main(string[] args)
    {
        try {
          // Start and shutdown servers repeatedly.
          for (int i = 0; i < 10; i++) {
            Server server = new Server
            {
              Ports = { new ServerPort("localhost", Port, ServerCredentials.Insecure) }
            };
            server.Start();
            await server.ShutdownAsync();
        }
        Console.WriteLine("No exceptions.");
        } catch (Exception e) {
            Console.WriteLine(e);
        }
    }
  }
```

I tried starting up and shutting down servers repeatedly but couldn't recreate the issue on ```2.29.0``` or ```2.30.0```.  This is for ```netcoreapp3.1``` and ```.net48``` on windows 10.  @mgravell I know it's been a while but do you still have a copy of your repo to verify you still see the issue? Apart from something wrong in my test, I wonder if a windows update might have resolved this.

**Comment by tonydnewell** [comment] 2022-08-01 09:36
This is the same as https://github.com/grpc/grpc/issues/30167

The problem is that Server.Start() is not called before Server.ShutdownAsync().
I'm not sure if this is API misuse issue (i.e. you must call Server.Start() after creating a new server port) or if it is a c-core issue.

**Comment by jtattermusch** [comment] 2022-08-16 10:57
Since creating a server, then adding ports to it and NOT calling server.Start() afterwards seems a bit pointless, it think it's fine to say that the correct API usage is 1. create server (and add ports in the constructor or afterwards) 2. call server.Start() 3. call server.ShuddownAsync() or server.KillAsync().

I agree that the current behavior makes it possible to get the server into weird states (e.g. create server, add ports  and  then call shutdownAsync without calling Start() as reported) and we could potentially modify the behavior slightly to avoid these odd states, but it would need to be a simple modification, since Grpc.Core is currently in maintenance mode and with the "correct" API usage, things work as expected.

One potential improvement is to make sure that Start() gets automatically called when ShutdownAsync() gets invoked if it hasn't already been invoked (perhaps along with printing a warning log line). But unless there are users that would welcome such behavior, we might as well close this issue as "won't fix" (and perhaps just improve the doc comments for Server class API's expectations).

**Comment by tonydnewell** [comment] 2022-10-04 13:21
Created PR https://github.com/grpc/grpc/pull/31232 to do what was suggested in https://github.com/grpc/grpc/issues/23390#issuecomment-1216479019

**Comment by jtattermusch** [comment] 2022-10-11 14:24
Should be fixed by https://github.com/grpc/grpc/pull/31232. It will be in the next patch release of 2.46.x

**Closed by jtattermusch** 2022-10-11 14:24 UTC
Labels: kind/bug, lang/C#, platform/Windows, area/api, priority/P2
