### ISSUE TITLE
C# RpcException has very verbose exception.Message property

### ISSUE THREAD

**Issue by timmydo** [grpc/grpc#27066] opened 2021-08-19 23:30 UTC
### Is your feature request related to a problem? Please describe.
I'm always frustrated when I catch a generic exception which is actually a RpcException and print ex.Message. It fills up my console with 100 lines of stack trace

### Describe the solution you'd like
I'd like to just see the error message without the stack trace.

### Describe alternatives you've considered
Catching RpcException specifically and printing the status code is possible but annoying to have to do.

### Additional context
I think the underlying issue is that Status.ToString() is used in the RpcException ctor for base.message--Status.ToString() prints stack traces. Maybe Status could have a .Message which doesn't print the stack.

Thanks!!!

**Comment by jtattermusch** [comment] 2022-10-11 14:36
@tonydnewell  can you please take a look?

**Comment by jtattermusch** [comment] 2022-12-14 10:27
possibly related: https://github.com/grpc/grpc/issues/25740

**Comment by tonydnewell** [comment] 2022-12-14 11:37
@jtattermusch would changing the format of the status string be a breaking change? Would anyone be parsing it?

**Comment by jtattermusch** [comment] 2022-12-14 14:45
> @jtattermusch would changing the format of the status string be a breaking change? Would anyone be parsing it?

I think changing the contents of status.ToString() would be fine. It is not a breaking change.

**Comment by tonydnewell** [comment] 2022-12-19 14:19
I've made a change in PR https://github.com/grpc/grpc/pull/31932 to remove the stack trace when adding the `DebugException` information to `Status.ToString()`

However I've not been able to reproduce the original reported problem with "100 lines of stack trace" since the only `DebugException` that I can see added is that in https://github.com/grpc/grpc/blob/af855eb64eea02d2f7b68d49c3d4d7a263649104/src/csharp/Grpc.Core/Internal/BatchContextSafeHandle.cs#L97 which doesn't contain a stack trace since it wasn't thrown.

**Comment by jtattermusch** [comment] 2022-12-20 18:47
Fixed by https://github.com/grpc/grpc-dotnet/pull/1992, the fix will be in the next release of Grpc.Core.Api (the upcoming 2.52.x). The fix will work both for grpc-dotnet and Grpc.Core, but for Grpc.Core, you need to explicitly use Grpc.Core.Api 2.52+ (once it's released).

**Closed by jtattermusch** 2022-12-20 18:47 UTC
Labels: kind/enhancement, lang/C#, area/api, priority/P2

**Comment by jtattermusch** [comment] 2022-12-20 18:50
We can potentially backport the change into 2.46.x as well, but for now there seems to be no reason to do so since Grpc.Core 2.46.x  will work just fine with more recent versions of Grpc.Core.Api.
