### ISSUE TITLE
When using the demo pod install error

### ISSUE THREAD

**Issue by zhaohuang2016** [grpc/grpc#15546] opened 2018-05-25 02:31 UTC
[!] Error installing BoringSSL
[!] /usr/bin/git clone https://boringssl.googlesource.com/boringssl /var/folders/hp/3gx151ys17v8473j92dgsv_w0000gn/T/d20180525-1681-10v6gz9 --template= --single-branch --depth 1 --branch version_for_cocoapods_9.0

Cloning into '/var/folders/hp/3gx151ys17v8473j92dgsv_w0000gn/T/d20180525-1681-10v6gz9'...
fatal: unable to access 'https://boringssl.googlesource.com/boringssl/': Could not resolve host: boringssl.googlesource.com

I'm from China. I used VPN for installation or error reporting.
How should I solve this problem?
Thanks

**Comment by ncteisen** [comment] 2018-05-30 18:08
does the usual installation mechanism work for you?

https://github.com/grpc/grpc/blob/master/INSTALL.md

**Comment by zhaohuang2016** [comment] 2018-05-31 00:45
I've tried it many times from the documentation, and it's when 'pod install' goes wrong.
I'm using objective-c.The following is the terminal integrity error.

zhaohuangdeMac-mini:~ zhaohuang$ cd /Users/zhaohuang/grpc/examples/objective-c/helloworld 
zhaohuangdeMac-mini:helloworld zhaohuang$ pod install
Analyzing dependencies
Fetching podspec for `HelloWorld` from `.`
Downloading dependencies
Installing !ProtoCompiler (3.4.0)
Installing !ProtoCompiler-gRPCPlugin (1.7.1)
Installing BoringSSL (9.1)

[!] Error installing BoringSSL
[!] /usr/bin/git clone https://boringssl.googlesource.com/boringssl /var/folders/hp/3gx151ys17v8473j92dgsv_w0000gn/T/d20180531-933-d9z66l --template= --single-branch --depth 1 --branch version_for_cocoapods_9.0

Cloning into '/var/folders/hp/3gx151ys17v8473j92dgsv_w0000gn/T/d20180531-933-d9z66l'...
fatal: unable to access 'https://boringssl.googlesource.com/boringssl/': Failed to connect to boringssl.googlesource.com port 443: Operation timed out
zhaohuangdeMac-mini:helloworld zhaohuang$

**Comment by zhaohuang2016** [comment] 2018-05-31 02:19
How can I change 'https://boringssl.googlesource.com/boringssl/' to 'https://github.com/google/boringssl/'. 'https://github.com/google/boringssl/' this address can normal 'pod install.' Thanks!

**Comment by nicolasnoble** [comment] 2018-05-31 02:59
Duplicate of #15326 - answers and discussions are there.

**Closed by nicolasnoble** 2018-05-31 02:59 UTC
Labels: disposition/requires reporter action

**Comment by zhaohuang2016** [comment] 2018-06-01 04:01
Thanks
