### ISSUE TITLE
Java cloud-to-cloud compression tests failing

### ISSUE THREAD

**Issue by muxi** [grpc/grpc#20884] opened 2019-10-31 19:03 UTC
Sample case: https://source.cloud.google.com/results/invocations/371fa7e2-b35d-4895-a2a8-93da03e475e2/targets/github%2Fgrpc%2Finterop_test/tests;group=tests;test=cloud_to_cloud:java:aspnetcore_server:server_compressed_streaming:tls;row=1
```
Running test server_compressed_streaming
Exception in thread "main" java.lang.AssertionError: io.grpc.StatusRuntimeException: CANCELLED: Failed to read message.
	at io.grpc.testing.integration.AbstractInteropTest.assertSuccess(AbstractInteropTest.java:1818)
	at io.grpc.testing.integration.AbstractInteropTest.serverCompressedStreaming(AbstractInteropTest.java:700)
	at io.grpc.testing.integration.TestServiceClient.runTest(TestServiceClient.java:267)
	at io.grpc.testing.integration.TestServiceClient.run(TestServiceClient.java:214)
	at io.grpc.testing.integration.TestServiceClient.main(TestServiceClient.java:72)
Caused by: io.grpc.StatusRuntimeException: CANCELLED: Failed to read message.
	at io.grpc.Status.asRuntimeException(Status.java:533)
	at io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onClose(ClientCalls.java:447)
	at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
	at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
	at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
	at io.grpc.internal.CensusStatsModule$StatsClientInterceptor$1$1.onClose(CensusStatsModule.java:700)
	at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
	at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
	at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
	at io.grpc.internal.CensusTracingModule$TracingClientInterceptor$1$1.onClose(CensusTracingModule.java:399)
	at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:510)
	at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:66)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.close(ClientCallImpl.java:630)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.access$700(ClientCallImpl.java:518)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1MessagesAvailable.runInternal(ClientCallImpl.java:611)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1MessagesAvailable.runInContext(ClientCallImpl.java:584)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: io.grpc.StatusRuntimeException: INTERNAL: Invalid protobuf byte sequence
	at io.grpc.Status.asRuntimeException(Status.java:524)
	at io.grpc.protobuf.lite.ProtoLiteUtils$MessageMarshaller.parse(ProtoLiteUtils.java:218)
	at io.grpc.protobuf.lite.ProtoLiteUtils$MessageMarshaller.parse(ProtoLiteUtils.java:118)
	at io.grpc.MethodDescriptor.parseResponse(MethodDescriptor.java:276)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1MessagesAvailable.runInternal(ClientCallImpl.java:599)
	... 6 more
Caused by: com.google.protobuf.InvalidProtocolBufferException: Unexpected end of ZLIB input stream
	at io.grpc.testing.integration.Messages$StreamingOutputCallResponse.<init>(Messages.java:9332)
	at io.grpc.testing.integration.Messages$StreamingOutputCallResponse.<init>(Messages.java:9265)
	at io.grpc.testing.integration.Messages$StreamingOutputCallResponse$1.parsePartialFrom(Messages.java:9893)
	at io.grpc.testing.integration.Messages$StreamingOutputCallResponse$1.parsePartialFrom(Messages.java:9887)
	at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:86)
	at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:48)
	at io.grpc.protobuf.lite.ProtoLiteUtils$MessageMarshaller.parseFrom(ProtoLiteUtils.java:223)
	at io.grpc.protobuf.lite.ProtoLiteUtils$MessageMarshaller.parse(ProtoLiteUtils.java:215)
	... 9 more
Caused by: java.io.EOFException: Unexpected end of ZLIB input stream
	at java.util.zip.InflaterInputStream.fill(InflaterInputStream.java:240)
	at java.util.zip.InflaterInputStream.read(InflaterInputStream.java:158)
	at java.util.zip.GZIPInputStream.read(GZIPInputStream.java:117)
	at io.grpc.internal.MessageDeframer$SizeEnforcingInputStream.read(MessageDeframer.java:468)
	at com.google.protobuf.CodedInputStream$StreamDecoder.tryRefillBuffer(CodedInputStream.java:2785)
	at com.google.protobuf.CodedInputStream$StreamDecoder.isAtEnd(CodedInputStream.java:2708)
	at com.google.protobuf.CodedInputStream$StreamDecoder.readTag(CodedInputStream.java:2059)
	at io.grpc.testing.integration.Messages$StreamingOutputCallResponse.<init>(Messages.java:9302)
	... 16 more
Shutting down
```

**Comment by ejona86** [comment] 2019-10-31 22:17
Java's not changed this recently. Seems likely aspnetcore change. https://github.com/grpc/grpc-dotnet/pull/629 looks related fits the time period.

@JamesNK is there any potential funny business going on with compression with the new change? Are you certain you "finished" the gzip stream? It looks like you read the output before disposing the stream. Flush is not normally enough with gzip, because it has the final Adler32 at the end of the stream.

**Comment by ejona86** [comment] 2019-10-31 22:23
Yeah, it seems Dispose finishes the gzip stream:
https://referencesource.microsoft.com/#system/sys/System/IO/compression/DeflateStream.cs,596

**Comment by JamesNK** [comment] 2019-10-31 22:32
Looking now

**Comment by ejona86** [comment] 2019-10-31 23:21
I've created https://github.com/grpc/grpc-go/issues/3135 and https://github.com/grpc/grpc/issues/20889 since it seems more implementations should have noticed and had the client see a failure.

**Comment by ejona86** [comment] 2019-10-31 23:30
dotnet has merged a fix and I've triggered a test run.

**Comment by ejona86** [comment] 2019-10-31 23:51
https://source.cloud.google.com/results/invocations/2fb7ac6d-6988-4f3d-b761-0d495008fd0a/targets passed, so this is confirmed fixed by https://github.com/grpc/grpc-dotnet/pull/637 .

**Comment by ejona86** [comment] 2019-10-31 23:52
Thank you @JamesNK for the fast turnaround!

**Closed by ejona86** 2019-10-31 23:51 UTC
Labels: infra/BUILDPONY, kind/bug, lang/Java, priority/P2
