### ISSUE TITLE
cloud_to_cloud:aspnetcore:dart_server:custom_metadata:tls Failure

### ISSUE THREAD

**Issue by gnossen** [grpc/grpc#22162] opened 2020-02-27 00:20 UTC
https://source.cloud.google.com/results/invocations/e9ea50d9-df65-4784-9418-fc41671606a3/log

```
dbug: Grpc.Net.Client.Internal.GrpcCall[4]
      => GrpcMethodType:DuplexStreaming GrpcUri:/grpc.testing.TestService/FullDuplexCall
      Finished gRPC call.
Unhandled exception. System.AggregateException: One or more errors occurred. (Can't get the call trailers because the call has not completed successfully.)
 ---> System.InvalidOperationException: Can't get the call trailers because the call has not completed successfully.
   at Grpc.Net.Client.Internal.GrpcCall`2.GetTrailers() in /var/local/git/grpc-dotnet/src/Grpc.Net.Client/Internal/GrpcCall.cs:line 344
   at Grpc.Net.Client.Internal.HttpClientCallInvoker.Callbacks`2.<>c.<.cctor>b__4_2(Object state) in /var/local/git/grpc-dotnet/src/Grpc.Net.Client/Internal/HttpClientCallInvoker.cs:line 145
   at Grpc.Core.AsyncCallState.GetTrailers()
   at Grpc.Core.AsyncDuplexStreamingCall`2.GetTrailers()
   at InteropTestsClient.InteropClient.RunCustomMetadataAsync(TestServiceClient client) in /var/local/git/grpc-dotnet/testassets/InteropTestsClient/InteropClient.cs:line 715
   at InteropTestsClient.InteropClient.RunTestCaseAsync(IChannelWrapper channel, ClientOptions options) in /var/local/git/grpc-dotnet/testassets/InteropTestsClient/InteropClient.cs:line 293
   at InteropTestsClient.InteropClient.Run() in /var/local/git/grpc-dotnet/testassets/InteropTestsClient/InteropClient.cs:line 144
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at InteropTestsClient.InteropClient.<>c.<Run>b__7_1(ClientOptions options) in /var/local/git/grpc-dotnet/testassets/InteropTestsClient/InteropClient.cs:line 136
   at CommandLine.ParserResultExtensions.WithParsed[T](ParserResult`1 result, Action`1 action)
   at InteropTestsClient.InteropClient.Run(String[] args) in /var/local/git/grpc-dotnet/testassets/InteropTestsClient/InteropClient.cs:line 124
   at InteropTestsClient.Program.Main(String[] args) in /var/local/git/grpc-dotnet/testassets/InteropTestsClient/Program.cs:line 25
```

**Comment by jtattermusch** [comment] 2020-03-30 09:01
Dupe of https://github.com/grpc/grpc/issues/22512

**Closed by jtattermusch** 2020-03-30 09:01 UTC
Labels: area/test, kind/bug, priority/P2
