### ISSUE TITLE
C#: Invalid input 'Grpc.sln'. The file type was not recognized

### ISSUE THREAD

**Issue by dgquintas** [grpc/grpc#10614] opened 2017-04-12 20:28 UTC
https://grpc-testing.appspot.com/job/gRPC_pull_requests_linux/4499/testReport/junit/(root)/aggregate_tests/run_tests_csharp_linux_opt_native/

```
63%Expanding 64%Expanding 65%Expanding 66%Expanding 67%Expanding 68%Expanding 69%Expanding 70%Expanding 71%Expanding 72%Expanding 73%Expanding 74%Expanding 75%Expanding 76%Expanding 77%Expanding 78%Expanding 79%Expanding 80%Expanding 81%Expanding 82%Expanding 83%Expanding 84%Expanding 85%Expanding 86%Expanding 87%Expanding 88%Expanding 89%Expanding 90%Expanding 91%Expanding 92%Expanding 93%Expanding 94%Expanding 95%Expanding 96%Expanding 97%Expanding 98%Expanding 99%Expanding 100% 2438 ms
error: Invalid input 'Grpc.sln'. The file type was not recognized.

2017-04-12 09:18:02,971 FLAKE: tools/run_tests/helper_scripts/pre_build_csharp.sh [ret=1, pid=1038]
2017-04-12 09:18:03,147 ++ dirname tools/run_tests/helper_scripts/pre_build_csharp.sh
+ cd tools/run_tests/helper_scripts/../../../src/csharp
+ dotnet restore Grpc.sln
error: Invalid input 'Grpc.sln'. The file type was not recognized.

2017-04-12 09:18:03,147 FLAKE: tools/run_tests/helper_scripts/pre_build_csharp.sh [ret=1, pid=1067]
2017-04-12 09:18:03,322 ++ dirname tools/run_tests/helper_scripts/pre_build_csharp.sh
+ cd tools/run_tests/helper_scripts/../../../src/csharp
+ dotnet restore Grpc.sln
error: Invalid input 'Grpc.sln'. The file type was not recognized.

2017-04-12 09:18:03,322 FLAKE: tools/run_tests/helper_scripts/pre_build_csharp.sh [ret=1, pid=1084]
2017-04-12 09:18:03,497 ++ dirname tools/run_tests/helper_scripts/pre_build_csharp.sh
+ cd tools/run_tests/helper_scripts/../../../src/csharp
+ dotnet restore Grpc.sln
error: Invalid input 'Grpc.sln'. The file type was not recognized.

2017-04-12 09:18:03,497 FLAKE: tools/run_tests/helper_scripts/pre_build_csharp.sh [ret=1, pid=1100]
2017-04-12 09:18:03,674 ++ dirname tools/run_tests/helper_scripts/pre_build_csharp.sh
+ cd tools/run_tests/helper_scripts/../../../src/csharp
+ dotnet restore Grpc.sln
error: Invalid input 'Grpc.sln'. The file type was not recognized.

2017-04-12 09:18:03,674 FLAKE: tools/run_tests/helper_scripts/pre_build_csharp.sh [ret=1, pid=1116]
2017-04-12 09:18:03,847 ++ dirname tools/run_tests/helper_scripts/pre_build_csharp.sh
+ cd tools/run_tests/helper_scripts/../../../src/csharp
+ dotnet restore Grpc.sln
error: Invalid input 'Grpc.sln'. The file type was not recognized.

2017-04-12 09:18:03,847 FAILED: tools/run_tests/helper_scripts/pre_build_csharp.sh [ret=1, pid=1132]
2017-04-12 09:18:03,847 FAILED: Some tests failed
  adding: reports/ (stored 0%)
  adding: reports/index.html (deflated 22%)
+ DOCKER_EXIT_CODE=1
++ mktemp
+ TEMP_REPORTS_ZIP=/tmp/tmp.RYfbXQNLeD
+ docker cp run_tests_2bd5ac4c-1afe-4d60-9b53-fe56d1e4a564:/var/local/git/grpc/reports.zip /tmp/tmp.RYfbXQNLeD
+ unzip -o /tmp/tmp.RYfbXQNLeD -d /home/jenkins/workspace/gRPC_pull_requests_linux
Archive:  /tmp/tmp.RYfbXQNLeD
  inflating: /home/jenkins/workspace/gRPC_pull_requests_linux/reports/index.html  
+ rm -f /tmp/tmp.RYfbXQNLeD
+ docker rm -f run_tests_2bd5ac4c-1afe-4d60-9b53-fe56d1e4a564
run_tests_2bd5ac4c-1afe-4d60-9b53-fe56d1e4a564
+ exit 1
Traceback (most recent call last):
  File "tools/run_tests/run_tests.py", line 1314, in <module>
    env=env)
  File "/usr/lib/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'tools/run_tests/dockerize/build_docker_and_run_tests.sh' returned non-zero exit status 1
```

**Comment by dgquintas** [comment] 2017-04-12 21:08
Also making interop fail: https://grpc-testing.appspot.com/job/gRPC_interop_pull_requests/13192/console

**Comment by dgquintas** [comment] 2017-04-12 21:09
And portability linux: https://grpc-testing.appspot.com/job/gRPC_portability_pull_requests_linux/4545/testReport/junit/(root)/aggregate_tests/run_tests_csharp_linux_dbg_native_default_coreclr/

**Comment by apolcyn** [comment] 2017-04-12 21:35
It looks like this is caused by the addition of `src/csharp/global.json` in https://github.com/grpc/grpc/pull/10598, which conflicts with it's removal in recent master PR (https://github.com/grpc/grpc/pull/10480).

#10480 relies on the most recent version of `dotnet` sdk to build, but the added `global.json` file iss forcing an older, incompatible version.

**Comment by muxi** [comment] 2017-04-14 17:45
This happened again in https://grpc-testing.appspot.com/job/gRPC_interop_pull_requests/13297/console

**Comment by dgquintas** [comment] 2017-04-15 17:27
It's still happening in interop: https://grpc-testing.appspot.com/job/gRPC_interop_pull_requests/13329/console

**Comment by jtattermusch** [comment] 2017-04-18 09:46
I am pretty sure this was fixed in https://github.com/grpc/grpc/pull/10616/files. Is it possible that your PRs didn't have the freshest upstream/master in them?

**Comment by jtattermusch** [comment] 2017-04-20 13:47
Please reopen if seen again.

**Closed by jtattermusch** 2017-04-20 13:47 UTC
Labels: BUILDPONY, C#, P0
