### ISSUE TITLE
Unexpected GOAWAY in Ruby client

### ISSUE THREAD

**Issue by iredelmeier** [grpc/grpc#15514] opened 2018-05-23 00:19 UTC
### What version of gRPC and what language are you using?

* Server: go with grpc-go 1.7.0
* Client: ruby with grpc 1.10.0

I've seen the same behaviour with a newer server (grpc-go 1.12.0) and any Ruby version >= 1.8.0 up to the latest release (1.12.0).
 
### What operating system (Linux, Windows, …) and version?

* macOS 10.13.4
* Ubuntu 14.04 w/ 4.4.0-124-generic kernel
 
### What runtime / compiler are you using (e.g. python version or version of gcc)

* go 1.10.2
* ruby 2.4.2
 
### What did you do?

We have:
* Multiple exposed gRPC services
* A Go server with a non-infinite [`MaxConnectionIdle`](https://godoc.org/google.golang.org/grpc/keepalive#ServerParameters) time
* A Ruby client that calls multiple of the services, potentially waiting more than the `MaxConnectionIdle` time between requests

### What did you expect to see?
 
Successful requests regardless of how much time lapses between requests from the client (assuming that there are no unrelated failures).
 
### What did you see instead?
 
The client sometimes fails with `GOAWAY received`, e.g.:

```
/Users/pivotal/.rubies/ruby-2.4.2/lib/ruby/gems/2.4.0/gems/grpc-1.12.0-universal-darwin/src/ruby/lib/grpc/generic/active_call.rb:31:in `check_status': 13:GOAWAY received (GRPC::Internal)
	from /Users/pivotal/.rubies/ruby-2.4.2/lib/ruby/gems/2.4.0/gems/grpc-1.12.0-universal-darwin/src/ruby/lib/grpc/generic/active_call.rb:180:in `attach_status_results_and_complete_call'
	from /Users/pivotal/.rubies/ruby-2.4.2/lib/ruby/gems/2.4.0/gems/grpc-1.12.0-universal-darwin/src/ruby/lib/grpc/generic/active_call.rb:372:in `request_response'
	from /Users/pivotal/.rubies/ruby-2.4.2/lib/ruby/gems/2.4.0/gems/grpc-1.12.0-universal-darwin/src/ruby/lib/grpc/generic/client_stub.rb:178:in `block in request_response'
	from /Users/pivotal/.rubies/ruby-2.4.2/lib/ruby/gems/2.4.0/gems/grpc-1.12.0-universal-darwin/src/ruby/lib/grpc/generic/interceptors.rb:170:in `intercept!'
	from /Users/pivotal/.rubies/ruby-2.4.2/lib/ruby/gems/2.4.0/gems/grpc-1.12.0-universal-darwin/src/ruby/lib/grpc/generic/client_stub.rb:177:in `request_response'
	from /Users/pivotal/.rubies/ruby-2.4.2/lib/ruby/gems/2.4.0/gems/grpc-1.12.0-universal-darwin/src/ruby/lib/grpc/generic/service.rb:170:in `block (3 levels) in rpc_stub_class'
	from client.rb:21:in `increment'
	from client.rb:42:in `main'
	from client.rb:45:in `<main>'
```
 
### Anything else we should know about your project / environment?

I've made a [demo server/client](https://github.com/iredelmeier/goaway) that demonstrates the failure. (Please let me know if there are any issues running it!)

Some other things:
* I haven't been able to reproduce the error in go, python, or node
* The bug seems to only occur when there are **multiple services**, and the time lapse happens between them - something along the lines of:
  * Request to service A receives a GOAWAY, creates a new connection, and ultimately succeeds
  * Nothing happens for some period of time
  * Request to service B receives a GOAWAY and can't sort itself out
* It seems like the bug was introduced in [#ccfdfb3a41](https://github.com/grpc/grpc/commit/ccfdfb3a41), which looks to us like a pretty surprising culprit!! Preliminary messing around with the change didn't fix it, but we didn't delve too far into the commit.

**Comment by oozie** [comment] 2018-06-28 21:20
We have worked around the issue in https://github.com/cloudfoundry-incubator/perm-rb/commit/0afccde31148878c4bf2215510cd9d71f0894f0e by explicitly creating a shared channel and passing it to each of the two client stubs.

**Comment by apolcyn** [comment] 2018-07-17 07:19
@iredelmeier great repro case, thanks!

this is very reproduceable, and I'm seeing it reproduce even with two different channels of the <i>same</i> service.

I've trimmed this down further to something along the lines of:

```
stub_1 = <service class>("127.0.0.1:1000", :this_channel_is_insecure)
stub_2 = <service class>("127.0.0.1:1000", :this_channel_is_insecure)
stub_1.do_call()
stub_2.do_call()
stub_2.do_call()
```

(using 127.0.0.1 directly is making the GOAWAY happen sooner because we're cycling through all possible addresses sooner, rather than when using localhost and resolving to ipv4 and ipv6 loopback).

Not at the bottom of this but it's looking like something along these lines:

1) channel C1 creates subchannel S1, makes a call on it, and then receives a GOAWAY. Upon receiving a GOAWAY it unref's S1, destroys it and removes it from the index. C1 also re-resolves and creates a new subchannel S2
2) channel C2 creates a call, matches S2 in the subchannel index, performs the call, and then receives a GOAWAY. It unref's S2 but doesn't destroy it because C1 is somehow still holding a ref on it
3) channel C2 creates a second call, matches S2 in the subchannel index, attempts to perform a call on it, but then finds S2 in "transient failure" state because of the previous GOAWAY, and then fails.

It seems strange that that "ref" from C1 is causing C2 to keep matching and using S2, even when S2 is not useable....

**Comment by aniketdivekar** [comment] 2018-07-17 10:15
@apolcyn @iredelmeier I'm facing the same issue with Ruby 2.4.3 and grpc 1.12. Is there any workaround for this?

**Comment by AspirinSJL** [comment] 2018-07-17 17:58
@apolcyn C2 unref's S2 due to connectivity change to TRANSIENT_FAILURE right? I think C1 should also have received the connectivity change notification and unref'ed C2. Could you check why C1 didn't behave like that or paste the log with the relevant tracers on? Thanks!

**Comment by apolcyn** [comment] 2018-07-17 20:46
here is my slightly trimmed down repro:

```
#!/usr/bin/env ruby

this_dir = File.expand_path(File.dirname(__FILE__))
protos_lib_dir = File.join(this_dir, 'lib')
grpc_lib_dir = File.join(File.dirname(File.dirname(File.dirname(this_dir))), 'grpc', 'src', 'ruby', 'lib')
$LOAD_PATH.unshift(grpc_lib_dir) unless $LOAD_PATH.include?(grpc_lib_dir)
$LOAD_PATH.unshift(protos_lib_dir) unless $LOAD_PATH.include?(protos_lib_dir)
$LOAD_PATH.unshift(this_dir) unless $LOAD_PATH.include?(this_dir)

require 'grpc'
require 'decrementer_services_pb'
require 'incrementer_services_pb'

def decrement(stub)
  STDERR.puts 'Calling first service...'
  stub.decrement(Goaway::DecrementRequest.new).count
  STDERR.puts 'Called first service'
  STDERR.puts 'Sleeping for 1 second...'
  sleep 1.5
end

def main
  decrementer_stub1 = Goaway::Decrementer::Stub.new(
    '127.0.0.1:50051',
    :this_channel_is_insecure
  )
  decrementer_stub2 = Goaway::Decrementer::Stub.new(
    '127.0.0.1:50051',
    :this_channel_is_insecure
  )

  STDERR.puts 'Decrement on stub 1'
  decrement(decrementer_stub1)
  STDERR.puts 'Decrement on stub 2'
  decrement(decrementer_stub2)
  STDERR.puts 'Decrement on stub 2'
  decrement(decrementer_stub2)
  STDERR.puts 'Decrement on stub 2'
  decrement(decrementer_stub2)
  return
end
```

here is the log: https://gist.github.com/apolcyn/22ba8d5e796461ee21d8434a891f88d6

**Comment by apolcyn** [comment] 2018-07-17 20:47
> Could you check why C1 didn't behave like that or paste the log with the relevant tracers on? Thanks!

@AspirinSJL I'm looking in to why C1 didn't pick up that notification and unref

**Comment by markdroth** [comment] 2018-07-18 14:14
Yes.

**Comment by apolcyn** [comment] 2018-07-18 19:22
@AspirinSJL 

> @apolcyn C2 unref's S2 due to connectivity change to TRANSIENT_FAILURE right? I think C1 should also have received the connectivity change notification and unref'ed C2. Could you check why C1 didn't behave like that or paste the log with the relevant tracers on? Thanks!

With more looking, it actually seems that C1 is not picking up the connectivity change notification on S2 because it never starts watching it.

That is (from what I can tell), when C1 receives the GOAWAY on S1, it [it's pick first policy set's started_picking_=false](https://github.com/grpc/grpc/blob/master/src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc#L514) and then it re-resolves. Then, upon re-resolving and creating S2, C1's pick fist policy [does not start a new connectivity watch](https://github.com/grpc/grpc/blob/master/src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc#L406) because it's <i>started_picking_=false</i>, and C1 will never start a new watch on S2 because we never create a new call on C1 and so C1 never starts picking.

**Comment by AspirinSJL** [comment] 2018-07-19 01:18
I see the problem.. Thanks for digging into this!

So this issue will happen as long as pick_first hasn't started picking, not just in case of re-resolution. The separation of subchannel reffing and state watching causes pick first to be unaware of that the reffed subchannel is already unusable. As a result, the subchannel is in TRANSIENT_FAILURE (even worse, with a GOAWAY error) when it's used next time. It will eventually be READY (if the server is up again), but before that the picks will fail if that's the only subchannel.

One possible fix is to force invalidating the subchannel when something really bad (like, GOAWAY received) happens. In subchannel_index, any invalid subchannel is invisible to future users. So the next LB policy will create a new subchannel from IDLE state. Before an LB policy starts watching a subchannel, it will check whether it's still valid or not.

@markdroth Does that sound reasonable?

BTW, I don't know why C2 still tries to reconnect to the subchannel after it sees the subchannel has a GOAWAY error in step 3 though. I thought GOAWAY means no retry.

**Comment by markdroth** [comment] 2018-07-19 15:32
Ideally, PF should handle a GOAWAY by putting the channel into idle state, although the exact desired behavior is not well defined.  For example, it could be argued that we should really handle this by completely resetting the client_channel back to its initial state: unref the LB policy and stop the resolver from resolving.  Currently, we don't do any of that; instead, we re-resolve, create subchannels based on the resolver result, but then don't watch the connectivity state of the new subchannels, which seems pretty stupid -- we're doing some work we don't need to and leaving things in a bit of an inconsistent state (thus leading to problems like this bug).  @ejona86, @dfawley, and I were planning to write up an idleness design later this quarter to clearly define what the right behavior should be here.

For now, I agree that it seems wrong that we take a ref to a subchannel that we're not watching.  However, it's not clear to me that we can solve this problem by removing the subchannel from the index, because we would need some way to do that atomically with respect to the connectivity state notification.  Otherwise, there will always be a window during which another channel might still grab the subchannel from the index.

Another possible interim solution would be to change PF so that when it receives an update and `started_picking_` is false, it will save the addresses from the update but not actually create the subchannel list for those addresses until it does start picking.  However, if we do this, we should do it as non-invasively as possible, because if we later decide to handle this by resetting the client_channel back to its initial state, then we would want to remove this code.

Alternatively, maybe the right thing to do here is to go ahead and do the work of resetting the client_channel to its initial state.  We could do that by having PF report IDLE, and then having client_channel see that state and unref the LB policy and stop resolving.  That might actually be both easier and cleaner, and it would also allow us to simplify the LB policy API slightly (internally, see http://go/grpc-c-core-client-channel-roadmap#heading=h.78p3kqsnue7z for details).

Let's chat offline with Eric and Doug to decide how to proceed.

**Comment by AspirinSJL** [comment] 2018-07-19 17:49
Yeah, this needs thorough thought.

Regarding my proposed fix (which might be obsolete now), I think it's fine if some channel runs into the race. If a channel refs the subchannel just before it's labeled as invalid, there are two cases. (1) If the picking and watching also starts before the labeling, then that channel may have to accept that the server is not ready around that point and the next pick might fail. Even if the channel created a new subchannel, the server might still send it a GOAWAY. (2) If the picking and watching starts after the labeling, the invalidity of the subchannel will be detected if we add a check when the channel starts watching a subchannel.

**Comment by AspirinSJL** [comment] 2018-07-19 18:01
Also, about why C2 still tries to re-connect to S2 when it sees a GOAWAY error. Is that because the discontinuation upon GOAWAY is only triggered by transport layer when the GOAWAY frame is initially received?

**Comment by markdroth** [comment] 2018-07-19 19:30
I chatted with Eric this morning about this.  There are still some concerns that we need to think through as part of the idleness design that may push us in the direction of having LB policies be able to trigger idleness without shutting down name resolution, so let's not proceed with having the client_channel reset to its initial state at this point.

Eric did, however, suggest another option, which is to change the subchannel API such that (re)connection attempts are triggered separately from connectivity state watches (i.e., instead of a connectivity watch implying a connection attempt, there would be a separate method to tell it to try to connect).  That way, PF could always have a connectivity state watch, even if `started_picking_` is false.  The only thing that we'd trigger when we set `started_picking_` to true would be the connection attempts.  Thus, the LB policy would notice if the subchannel goes into `TRANSIENT_FAILURE` even if it's not trying to connect.  I'm not sure how invasive this change would be, but it's probably worth looking into.

Another interesting question (although I think not directly related to this bug) is why we're recreating the subchannel after a GOAWAY in the first place.  Ever since #13932, the subchannel throws away the connected subchannel when it goes into `TRANSIENT_FAILURE`, so if we just renew the watch on the subchannel, it should try to establish a new connection.  Maybe there's something we need to clean up here.

With regard to the question about why C2 still tries to use S2, I assume it's because after step 1, S2 is always held in the subchannel index due to the ref held by C1, so no matter how many times C2 re-resolves, it will always keep getting the same subchannel from the index for the same address.

**Comment by AspirinSJL** [comment] 2018-07-23 05:16
I think separating the connectivity watching API from the connection API still can't solve the problem. First of all, I suppose we are still watching the subchannels one by one in PF. If the first subchannel is always in `IDLE` (which can happen if we re-resolved but haven't got a new pick), we won't watch the rest of the subchannel list. The problem remains. Actually, even if every subchannel in the subchannel list can can exit `IDLE` quickly, we still have a similar problem if the subchannel we are interested in is the 1000th one in the subchannel list and all the other 999 subchannels are connecting to unreachable backends. Before the 1000th subchannel is watched by PF 1, it may have already transitioned into `TRANSIENT_FAILURE` because it's used and discarded (due to a GOAWAY) quickly by another channel. Even when it's watched by PF 1, it won't be unreffed after we see it's in `TRANSIENT_FAILURE` state because we will keep the whole subchannel list and continue trying it (we will re-resolve and unref the subchannel list after #16076, but if the re-resolution result is the same as the current one, PF 1 still holds at least one ref to that subchannel). To sum up, we are not eliminating the gap between reffing and watching.

Or, do we want to watch the subchannles in PF in parallel?

Back to this issue, its direct problem is that when C2 is trying to connect to a recovered server, it's matching to a previously failed subchannel in subchannel index so the pick fails while it shouldn't. Instead of trying to notify the external users to unref the failed subchannel, I think it's more straightforward to hide the failed subchannel from C2 so that C2 can use a new subchannel from `IDLE` state. Or, reset the subchannel to `IDLE` after it's `TRANSIENT_FAILURE`, if we don't have restriction of such state transition.

I can understand why C2 still uses S2, but I couldn't understand why it will transition from `IDLE` to `TRANSIENT_FAILURE` to `CONNECTING` to `READY`, as shown in the [log](https://gist.github.com/apolcyn/22ba8d5e796461ee21d8434a891f88d6). But now I guess that means the channel can keep trying connecting to a server even after GOAWAY is received. GOAWAY only applies to one connection; it doesn't affect re-connection.

Do you mean the subchannel recreation in step 1 after C1 receives a GOAWAY? That's because C1's PF has selected S1. When a GOAWAY arrives, S1 transitions to `TRANSIENT_FAILURE`. If the selected subchannel goes to `TRANSIENT_FAILURE`, instead of renewing the watch, we will unref it, and maybe remove it from subchannel index.

**Closed** 2018-08-17 17:02 UTC
Labels: kind/bug, lang/core, priority/P2
