### ISSUE TITLE
make: when Cross Compiling, zlib and c-ares libs created are not crosscompiled (while other libs are).

### ISSUE THREAD

**Issue by varshanbp** [grpc/grpc#11768] opened 2017-07-12 10:07 UTC
### Should this be an issue in the gRPC issue tracker?
Yes
 
### What version of gRPC and what language are you using?
 gRPC 1.4.0 / CPP
 
### What operating system (Linux, Windows, …) and version?
 Linux Ubuntu 16.04
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
 gcc 5.4.0 / g++ 5.4.0
 
### What did you do?
Cross Compile GRPC
 
### What did you expect to see?
 All Cross Compiled Libraries
 
### What did you see instead?
Got all Cross Compiled Libraries but C-ARES and ZLIB was compiled for Ubuntu and not cross compiled.

**Comment by jtattermusch** [comment] 2017-07-19 17:11
Are you cross-compiling using make or cmake? (or some other way).
What platform are you crosscompiling for?
Please include the commands you ran.

**Comment by varshanbp** [comment] 2017-07-29 05:45
make

**Comment by jtattermusch** [comment] 2017-08-02 08:40
As noted before, the exact commands to reproduce would be helpful.

**Comment by toulouse** [comment] 2018-01-06 10:55
@jtattermusch  I'm having trouble with cmake not building zlib and c-ares right, which I suspect is related or identical. I ran into this in a project I was just starting: https://github.com/toulouse/grpc_zlib_cares_broken_example

Here are the build steps. Apologies that it's not as minimal as it could be.

# Build commands
```
mkdir build
cd build/
cmake -G Ninja ..
ninja grpc
ninja sqlite
ninja flatbuffers
```
# nm output (only libgrpc_unsecure seems to have any references - all not found - to zlib)
```
toulouse@DevBox:~/ircsrv/build$ ls grpc/src/grpc/*.a
grpc/src/grpc/libgpr.a                  grpc/src/grpc/libgrpc_unsecure.a
grpc/src/grpc/libgrpc_plugin_support.a  grpc/src/grpc/libgrpc++_unsecure.a

toulouse@DevBox:~/ircsrv/build$ nm ./grpc/src/grpc/libgrpc_unsecure.a | grep inflateEnd
                 U inflateEnd
                 U inflateEnd
```
# Build error
```
FAILED: ircsrv
: && /usr/bin/c++     CMakeFiles/ircsrv.dir/src/main.cpp.o  -o ircsrv  zlib/install/lib/libz.a protobuf/src/protobuf/libprotobuf.a sqlite/install/lib/libsqlite.a grpc/src/grpc/libgrpc++_unsecure.a grpc/src/grpc/libgrpc_unsecure.a grpc/src/grpc/libgpr.a flatbuffers/src/flatbuffers/libflatbuffers.a -lpthread && :
grpc/src/grpc/libgrpc_unsecure.a(grpc_ares_ev_driver_posix.cc.o): In function `grpc_ares_notify_on_event_locked(grpc_exec_ctx*, grpc_ares_ev_driver*)':
grpc_ares_ev_driver_posix.cc:(.text+0x199): undefined reference to `ares_getsock'
grpc/src/grpc/libgrpc_unsecure.a(grpc_ares_ev_driver_posix.cc.o): In function `on_readable_cb(grpc_exec_ctx*, void*, grpc_error*)':
grpc_ares_ev_driver_posix.cc:(.text+0x56c): undefined reference to `ares_cancel'
grpc_ares_ev_driver_posix.cc:(.text+0x606): undefined reference to `ares_destroy'
grpc_ares_ev_driver_posix.cc:(.text+0x63c): undefined reference to `ares_process_fd'
grpc/src/grpc/libgrpc_unsecure.a(grpc_ares_ev_driver_posix.cc.o): In function `on_writable_cb(grpc_exec_ctx*, void*, grpc_error*)':
grpc_ares_ev_driver_posix.cc:(.text+0x817): undefined reference to `ares_cancel'
grpc_ares_ev_driver_posix.cc:(.text+0x8af): undefined reference to `ares_destroy'
grpc_ares_ev_driver_posix.cc:(.text+0x9bd): undefined reference to `ares_process_fd'
grpc/src/grpc/libgrpc_unsecure.a(grpc_ares_ev_driver_posix.cc.o): In function `grpc_ares_ev_driver_create':
grpc_ares_ev_driver_posix.cc:(.text+0xa1f): undefined reference to `ares_init'
grpc_ares_ev_driver_posix.cc:(.text+0xa48): undefined reference to `ares_strerror'
grpc/src/grpc/libgrpc_unsecure.a(grpc_ares_ev_driver_posix.cc.o): In function `grpc_ares_ev_driver_destroy':
grpc_ares_ev_driver_posix.cc:(.text+0xb9a): undefined reference to `ares_destroy'
CMakeFiles/ircsrv.dir/src/main.cpp.o: In function `GreeterServiceImpl::GreeterServiceImpl()':
main.cpp:(.text._ZN18GreeterServiceImplC2Ev[_ZN18GreeterServiceImplC5Ev]+0x15): undefined reference to `Greeter::Service::Service()'
main.cpp:(.text._ZN18GreeterServiceImplC2Ev[_ZN18GreeterServiceImplC5Ev]+0x49): undefined reference to `Greeter::Service::~Service()'
CMakeFiles/ircsrv.dir/src/main.cpp.o: In function `GreeterServiceImpl::~GreeterServiceImpl()':
main.cpp:(.text._ZN18GreeterServiceImplD2Ev[_ZN18GreeterServiceImplD5Ev]+0x32): undefined reference to `Greeter::Service::~Service()'
CMakeFiles/ircsrv.dir/src/main.cpp.o:(.data.rel.ro._ZTI18GreeterServiceImpl[_ZTI18GreeterServiceImpl]+0x10): undefined reference to `typeinfo for Greeter::Service'
grpc/src/grpc/libgrpc_unsecure.a(message_compress.cc.o): In function `zlib_compress(grpc_exec_ctx*, grpc_slice_buffer*, grpc_slice_buffer*, int)':
message_compress.cc:(.text+0xad): undefined reference to `deflateInit2_'
message_compress.cc:(.text+0x1ae): undefined reference to `deflate'
message_compress.cc:(.text+0x2ef): undefined reference to `deflateEnd'
grpc/src/grpc/libgrpc_unsecure.a(message_compress.cc.o): In function `zlib_decompress(grpc_exec_ctx*, grpc_slice_buffer*, grpc_slice_buffer*, int)':
message_compress.cc:(.text+0x54c): undefined reference to `inflateInit2_'
message_compress.cc:(.text+0x64e): undefined reference to `inflate'
message_compress.cc:(.text+0x78f): undefined reference to `inflateEnd'
grpc/src/grpc/libgrpc_unsecure.a(grpc_ares_wrapper.cc.o): In function `on_srv_query_done_cb(void*, int, int, unsigned char*, int)':
grpc_ares_wrapper.cc:(.text+0x38c): undefined reference to `ares_strerror'
grpc_ares_wrapper.cc:(.text+0x438): undefined reference to `ares_parse_srv_reply'
grpc_ares_wrapper.cc:(.text+0x453): undefined reference to `ares_free_data'
grpc_ares_wrapper.cc:(.text+0x4f6): undefined reference to `ares_gethostbyname'
grpc_ares_wrapper.cc:(.text+0x557): undefined reference to `ares_gethostbyname'
grpc/src/grpc/libgrpc_unsecure.a(grpc_ares_wrapper.cc.o): In function `on_txt_done_cb(void*, int, int, unsigned char*, int)':
grpc_ares_wrapper.cc:(.text+0x5d8): undefined reference to `ares_parse_txt_reply_ext'
grpc_ares_wrapper.cc:(.text+0x62b): undefined reference to `ares_free_data'
grpc_ares_wrapper.cc:(.text+0x63b): undefined reference to `ares_strerror'
grpc_ares_wrapper.cc:(.text+0x80e): undefined reference to `ares_free_data'
grpc/src/grpc/libgrpc_unsecure.a(grpc_ares_wrapper.cc.o): In function `on_hostbyname_done_cb(void*, int, int, hostent*)':
grpc_ares_wrapper.cc:(.text+0x91c): undefined reference to `ares_strerror'
grpc_ares_wrapper.cc:(.text+0xae2): undefined reference to `ares_inet_ntop'
grpc_ares_wrapper.cc:(.text+0xbb8): undefined reference to `ares_inet_ntop'
grpc/src/grpc/libgrpc_unsecure.a(grpc_ares_wrapper.cc.o): In function `grpc_dns_lookup_ares_impl(grpc_exec_ctx*, char const*, char const*, char const*, grpc_pollset_set*, grpc_closure*, grpc_lb_addresses**, bool, char**)':
grpc_ares_wrapper.cc:(.text+0xddf): undefined reference to `ares_set_servers_ports'
grpc_ares_wrapper.cc:(.text+0xe89): undefined reference to `ares_gethostbyname'
grpc_ares_wrapper.cc:(.text+0xee6): undefined reference to `ares_search'
grpc_ares_wrapper.cc:(.text+0x104c): undefined reference to `ares_gethostbyname'
grpc_ares_wrapper.cc:(.text+0x109b): undefined reference to `ares_query'
grpc_ares_wrapper.cc:(.text+0x10bb): undefined reference to `ares_strerror'
grpc/src/grpc/libgrpc_unsecure.a(grpc_ares_wrapper.cc.o): In function `grpc_ares_init':
grpc_ares_wrapper.cc:(.text+0x138d): undefined reference to `ares_library_init'
grpc_ares_wrapper.cc:(.text+0x13a6): undefined reference to `ares_strerror'
grpc/src/grpc/libgrpc_unsecure.a(grpc_ares_wrapper.cc.o): In function `grpc_ares_cleanup':
grpc_ares_wrapper.cc:(.text+0x1421): undefined reference to `ares_library_cleanup'
grpc/src/grpc/libgrpc_unsecure.a(stream_compression_gzip.cc.o): In function `grpc_stream_compression_context_destroy_gzip(grpc_stream_compression_context*)':
stream_compression_gzip.cc:(.text+0xc): undefined reference to `inflate'
stream_compression_gzip.cc:(.text+0x1b): undefined reference to `deflateEnd'
stream_compression_gzip.cc:(.text+0x31): undefined reference to `inflateEnd'
grpc/src/grpc/libgrpc_unsecure.a(stream_compression_gzip.cc.o): In function `gzip_flate(grpc_stream_compression_context_gzip*, grpc_slice_buffer*, grpc_slice_buffer*, unsigned long*, unsigned long, int, bool*)':
stream_compression_gzip.cc:(.text+0x92): undefined reference to `inflate'
stream_compression_gzip.cc:(.text+0x297): undefined reference to `inflate'
grpc/src/grpc/libgrpc_unsecure.a(stream_compression_gzip.cc.o): In function `grpc_stream_compression_context_create_gzip(grpc_stream_compression_method)':
stream_compression_gzip.cc:(.text+0x5b6): undefined reference to `deflateInit2_'
stream_compression_gzip.cc:(.text+0x5bd): undefined reference to `deflate'
stream_compression_gzip.cc:(.text+0x5f2): undefined reference to `inflateInit2_'
stream_compression_gzip.cc:(.text+0x5f9): undefined reference to `inflate'
grpc/src/grpc/libgrpc_unsecure.a(stream_compression_gzip.cc.o): In function `grpc_stream_decompress_gzip(grpc_stream_compression_context*, grpc_slice_buffer*, grpc_slice_buffer*, unsigned long*, unsigned long, bool*)':
stream_compression_gzip.cc:(.text+0x65c): undefined reference to `inflate'
grpc/src/grpc/libgrpc_unsecure.a(stream_compression_gzip.cc.o): In function `grpc_stream_compress_gzip(grpc_stream_compression_context*, grpc_slice_buffer*, grpc_slice_buffer*, unsigned long*, unsigned long, grpc_stream_compression_flush)':
stream_compression_gzip.cc:(.text+0x6bc): undefined reference to `deflate'
collect2: error: ld returned 1 exit status
```

# Installed -dev packages, if that helps (Debian 9)
toulouse@DevBox:~$ dpkg -l | grep dev | cut -d " " -f3
autotools-dev
dpkg-dev
freeglut3-dev:amd64
icu-devtools
libbison-dev:amd64
libblkid1:amd64
libboost-all-dev
libboost-atomic-dev:amd64
libboost-atomic1.62-dev:amd64
libboost-chrono-dev:amd64
libboost-chrono1.62-dev:amd64
libboost-context-dev:amd64
libboost-context1.62-dev:amd64
libboost-coroutine-dev:amd64
libboost-coroutine1.62-dev:amd64
libboost-date-time-dev:amd64
libboost-date-time1.62-dev:amd64
libboost-dev:amd64
libboost-exception-dev:amd64
libboost-exception1.62-dev:amd64
libboost-fiber-dev:amd64
libboost-fiber1.62-dev:amd64
libboost-filesystem-dev:amd64
libboost-filesystem1.62-dev:amd64
libboost-graph-dev:amd64
libboost-graph-parallel-dev
libboost-graph-parallel1.62-dev
libboost-graph1.62-dev:amd64
libboost-iostreams-dev:amd64
libboost-iostreams1.62-dev:amd64
libboost-locale-dev:amd64
libboost-locale1.62-dev:amd64
libboost-log-dev
libboost-log1.62-dev
libboost-math-dev:amd64
libboost-math1.62-dev:amd64
libboost-mpi-dev
libboost-mpi-python-dev
libboost-mpi-python1.62-dev
libboost-mpi1.62-dev
libboost-program-options-dev:amd64
libboost-program-options1.62-dev:amd64
libboost-python-dev
libboost-python1.62-dev
libboost-random-dev:amd64
libboost-random1.62-dev:amd64
libboost-regex-dev:amd64
libboost-regex1.62-dev:amd64
libboost-serialization-dev:amd64
libboost-serialization1.62-dev:amd64
libboost-signals-dev:amd64
libboost-signals1.62-dev:amd64
libboost-system-dev:amd64
libboost-system1.62-dev:amd64
libboost-test-dev:amd64
libboost-test1.62-dev:amd64
libboost-thread-dev:amd64
libboost-thread1.62-dev:amd64
libboost-timer-dev:amd64
libboost-timer1.62-dev:amd64
libboost-tools-dev
libboost-type-erasure-dev:amd64
libboost-type-erasure1.62-dev:amd64
libboost-wave-dev:amd64
libboost-wave1.62-dev:amd64
libboost1.62-dev:amd64
libboost1.62-tools-dev
libc-dev-bin
libc6-dev:amd64
libdevmapper-event1.02.1:amd64
libdevmapper1.02.1:amd64
libdrm-dev:amd64
libexpat1-dev:amd64
libfl-dev:amd64
libfontconfig1-dev:amd64
libfreetype6-dev
libgcc-6-dev:amd64
libgl1-mesa-dev:amd64
libglu1-mesa-dev:amd64
libhwloc-dev:amd64
libibverbs-dev
libice-dev:amd64
libicu-dev
libjpeg-dev
libjpeg62-turbo-dev:amd64
libltdl-dev:amd64
libmount1:amd64
libnuma-dev:amd64
libopenmpi-dev
libpng-dev:amd64
libpthread-stubs0-dev:amd64
libpython-dev:amd64
libpython2.7-dev:amd64
libpython3-dev:amd64
libpython3.5-dev:amd64
libsm-dev:amd64
libstdc++-6-dev:amd64
libudev1:amd64
libwebp-dev:amd64
libx11-dev:amd64
libx11-doc
libx11-xcb-dev:amd64
libxau-dev:amd64
libxcb-dri2-0-dev:amd64
libxcb-dri3-dev:amd64
libxcb-glx0-dev:amd64
libxcb-present-dev:amd64
libxcb-randr0-dev:amd64
libxcb-render0-dev:amd64
libxcb-shape0-dev:amd64
libxcb-sync-dev:amd64
libxcb-xfixes0-dev:amd64
libxcb1-dev:amd64
libxdamage-dev:amd64
libxdmcp-dev:amd64
libxext-dev:amd64
libxfixes-dev:amd64
libxshmfence-dev:amd64
libxt-dev:amd64
libxxf86vm-dev:amd64
linux-libc-dev:amd64
manpages-dev
mesa-common-dev:amd64
mpi-default-dev
python-dev
python2.7-dev
python3-dev
python3.5-dev
udev
x11proto-core-dev
x11proto-damage-dev
x11proto-dri2-dev
x11proto-fixes-dev
x11proto-gl-dev
x11proto-input-dev
x11proto-kb-dev
x11proto-xext-dev
x11proto-xf86vidmode-dev
xtrans-dev
zlib1g-dev:amd64

**Comment by toulouse** [comment] 2018-01-06 21:48
Interestingly, when adding 
```
+    ${CMAKE_CURRENT_BINARY_DIR}/grpc/src/grpc/third_party/cares/cares/lib/libcares.a
+    ${CMAKE_CURRENT_BINARY_DIR}/grpc/src/grpc/third_party/zlib/libz.a
```
to the CMakeFiles in the repo I provided, the zlib and cares linking issues go away. The odd thing is that zlib (via cmake externalproject instead of grpc/third_party) was already present as the first library:

/home/toulouse/ircsrv/build/zlib/install/lib/libz.a;/home/toulouse/ircsrv/build/protobuf/src/protobuf/libprotobuf.a;/home/toulouse/ircsrv/build/sqlite/install/lib/libsqlite.a;/home/toulouse/ircsrv/build/grpc/src/grpc/libgrpc++_unsecure.a;/home/toulouse/ircsrv/build/grpc/src/grpc/libgrpc_unsecure.a;/home/toulouse/ircsrv/build/grpc/src/grpc/libgpr.a;/home/toulouse/ircsrv/build/flatbuffers/src/flatbuffers/libflatbuffers.a;-lpthread;/home/toulouse/ircsrv/build/grpc/src/grpc/third_party/cares/cares/lib/libcares.a;/home/toulouse/ircsrv/build/grpc/src/grpc/third_party/zlib/libz.a

**Comment by jtattermusch** [comment] 2018-01-09 09:10
@toulouse  perhaps it's obvious, but the order or static libs passed to linker matters (so libz.a being listed as first is not helpful):
https://stackoverflow.com/questions/45135/why-does-the-order-in-which-libraries-are-linked-sometimes-cause-errors-in-gcc

**Comment by jackyko1991** [comment] 2018-01-24 15:21
@toulouse could you please explain further which cmakefile do you add the target linked library to solve the problem?

**Comment by dontsovcmc** [comment] 2018-05-31 02:19
It's better to describe what libraries GRPC needs under windows and Linux! I also see, that under linux it wants cares library. It's not the same as windows.

**Comment by jtattermusch** [comment] 2018-05-31 10:30
@varshanbp  looks like the initial bug is for crosscompilation with make. I'd suggest using `cmake` instead, because it has much better support for crosscompilation.

**Comment by dontsovcmc** [comment] 2018-05-31 10:36
I build with cmake. GRPC build successfully, but my project got same error when linking... I add zlib.a, libcares.a it doesn't help)

**Comment by sreecha** [comment] 2018-08-16 20:33
@dontsovcmc , did you manage to resolve the issue? 

@jtattermusch : can we close this issue? (looks like this issue was first reported by @varshanbp and you already recommended using `cmake`. The issue reported by @toulouse seemed to be resolved by changing the order of libs passed to the linker)

**Comment by dontsovcmc** [comment] 2018-08-17 01:05
have you updated build scripts?

**Comment by jtattermusch** [comment] 2018-08-20 09:45
@dontsovcmc   if you're still having issues, can you please share the exact list of commands you are running to reproduce the issue (as well as info about your environment)?

**Comment by dontsovcmc** [comment] 2018-08-20 18:08
I can check it only in September,sorry

**Comment by hypdeb** [comment] 2019-05-17 12:49
Happens in Docker container too. Here is the file I use :
```
FROM ubuntu:latest
RUN apt-get update && apt-get install -y \
    cmake \
    gcc \
    g++ \
    libboost-all-dev \
    build-essential \
    autoconf \
    libtool \
    pkg-config \
    libgflags-dev \
    libgtest-dev \
    clang \
    libc++-dev
RUN apt-get install -y \
    git \
    openssh-server \
    libc-ares-dev

RUN wget https://dl.google.com/go/go1.12.2.linux-amd64.tar.gz
RUN tar -xvf go1.12.2.linux-amd64.tar.gz
RUN mv go /usr/local

RUN git clone https://github.com/protocolbuffers/protobuf.git --recurse-submodules
WORKDIR /protobuf
RUN ./autogen.sh
RUN ./configure
RUN make
RUN make check
RUN make install
RUN ldconfig
WORKDIR /

RUN git clone https://github.com/grpc/grpc --recurse-submodules
WORKDIR /grpc
RUN mkdir .build
WORKDIR /grpc/.build
RUN apt-get install -y libssl-dev
RUN cmake -DgRPC_INSTALL=ON -DgRPC_BUILD_TESTS=OFF -DgRPC_PROTOBUF_PROVIDER=package -DgRPC_ZLIB_PROVIDER=package -DgRPC_CARES_PROVIDER= -DgRPC_SSL_PROVIDER=package -DCMAKE_BUILD_TYPE=Release ..
RUN make
RUN make install
```

**Comment by jtattermusch** [comment] 2019-10-22 06:41
In the future, we will only be providing cmake as a way for users to build (and Makefile will only be used internally if at all). Closing.

**Closed by jtattermusch** 2019-10-22 06:41 UTC
Labels: area/build, infra/Bazel, kind/bug, lang/c++, priority/P2
