### ISSUE TITLE
Client channel connection state tracking inconsistency

### ISSUE THREAD

**Issue by mlarkin2015** [grpc/grpc#22898] opened 2020-05-07 21:14 UTC
### What version of gRPC and what language are you using?
Various - reproduced on 1.27.3, 1.28.1 and 1.29.0

### What operating system (Linux, Windows,...) and version?
Ubuntu 18.04 LTS and CentOS 7

### What runtime / compiler are you using (e.g. python version or version of gcc)
g++ 8.4.0

### What did you do?
We noticed that waiting for READY state on the channel behaves two different ways, depending on which API you use. The following code illustrates the issue.

There are 2 code blocks shown. The first spins in a loop after the channel is established, and waits for the state to be GRPC_CHANNEL_READY. This **always** takes 5 seconds, even on a connection to a server on the same machine. I did a tcpdump of the connection during this phase, and the connection is ESTABLISHED, but no data is being sent. The TCP handshake to open the socket is finished, but the channel state is still CONNECTING for that entire 5 seconds.

The second code block calls channel->WaitForStateChange in a loop, also waiting for the READY state. This always loops exactly twice (IDLE->CONNECTING->READY), and happens basically instantaneously.

This seems like two different and equivalent things - checking if the channel is READY, but one approach seems to delay for some reason while the other does not. It seems as if WaitForStateChange proactively goes out and gets the current state while GetState by itself is waiting on some 5s timer to update the state, which doesn't seem correct (why would the state value returned from GetState not be updated right when the underlying channel state changes?)

```
#include <grpcpp/grpcpp.h>

using namespace grpc;
using namespace std;

int
main(int argc, char **argv)
{
	shared_ptr<Channel> channel;
	grpc::Status status;
	grpc_connectivity_state state;

	channel = CreateChannel("127.0.0.1:9999",
	    InsecureChannelCredentials());

//
// Spin on GetState(), wait for READY.
// This block seems to always spin for 5 seconds, regardless of the real
// connection state (the socket is connected and just sitting there doing
// nothing according to tcpdump)
//
#if 0
	state = channel->GetState(true);
	if (state != GRPC_CHANNEL_READY) {
		printf("spin for gRPC state: %i\n", state);

		while(state != GRPC_CHANNEL_READY)
			state = channel->GetState(true);
		
		printf("spin done, state: %i\n", state);
	}
#endif

//
// The following block also waits for READY by waiting for 2 state transitions
// from IDLE, which happen immediately without delay.
//
	state = channel->GetState(true);
	printf("WaitForStateChange starting state: %i\n", state);
	while (state < GRPC_CHANNEL_READY) {
		bool wsc = channel->WaitForStateChange(state,
		    gpr_inf_future(GPR_CLOCK_REALTIME));
		state = channel->GetState(true);
		printf("WaitForStateChange final ret: %i, state: %i\n", wsc,
		    state);
	}

	return 0;
}
```

### What did you expect to see?
Expected to see channel->GetState return the connected state and not delay for 5s before returning the right answer.

### What did you see instead?
gRPC delayed by 5s before updating whatever state was returned from GetState when waiting for the READY state.

**Comment by mlarkin2015** [comment] 2020-05-07 21:17
PS, the server is irrelevant, it can be any interface being implemented (as this demo code doesn't even do any RPCs at all)

**Comment by markdroth** [comment] 2020-05-07 21:43
I know this seems counter-intuitive, but it is actually working as intended in the context of gRPC's current polling model.  The polling model itself is actually the underlying problem here, and we hope to change to a different model in the not-too-distant future, but that work is still underway.

Basically, the current polling model is that we rely on borrowing threads from the application to perform polling for network I/O.  In general, this is done by calling `CompletionQueue::Next()`, but there are some other calls, including `WaitForStateChange()`, that also do polling.  However, the `GetState()` call does not do any polling; it basically just looks at the current state of the channel from whenever the last I/O was done.

When you ask a channel to connect, we need to do some polling to process the I/O for the name resolution, TCP connection establishment, and any necessary handshaking.  If no polling is happening, then nothing is checking for any I/O, meaning that we can't make any progress on establishing the connection.

This polling model has caused a number of problems in cases like this one where the application is not actually giving us any threads to do any polling.  One of the work-arounds that we tried was creating an internal "backup poller", which will wake up every 5 seconds and do some polling, just in case the application isn't doing it.  That's why the code that only calls `GetState()` does eventually succeed after 5 seconds.

But, as you can tell from this example, this work-around is not really sufficient to solve the fundamental problem here, which is that our current polling model just doesn't really work well.  It complicated to understand and hard to use, and it often surprises users.  And there are some other drawbacks as well, such as making it very hard to integrate into existing event loops.

As a result, we are in the process of moving to a new polling model, wherein we will have a dedicated set of polling threads always running and handling I/O.  And we will access the poller via a new `EventManager` API, which applications will be able to provide their own implementations of to integrate with existing event loops.  You can watch #20194 and #16504 for progress on that effort.

Until that happens, however, the behavior you're seeing here is working as intended.  I know that's not a great answer, but it's the best we can do for now.

I hope this info is helpful.

**Closed by markdroth** 2020-05-07 21:43 UTC
Labels: kind/bug, priority/P2

**Comment by mlarkin2015** [comment] 2020-05-08 00:39
Thanks Mark for the followup.
