### ISSUE TITLE
[python3] Connect server with a wrong ip but  succeeded unexpectedly

### ISSUE THREAD

**Issue by BossZou** [grpc/grpc#21050] opened 2019-11-12 14:03 UTC
### What version of gRPC and what language are you using?
grpcio v1.24.1
grpcio-tools v1.24.1
python 3.6.9

### What operating system (Linux, Windows,...) and version?
Ubuntu 18.04

### What runtime / compiler are you using (e.g. python version or version of gcc)
python 3.6.9

### What did you do?
I launched a server locally, and process pytest for my test case connecting server with a wrong ip `123.0.0.1`, strangely client connected successfully.  I set grpc environment varialbes `export GRPC_VERBOSITY=DEBUG` `export GRPC_TRACE=http,api,client_channel_routing,cares_resolver` and the output message is:
```
I1112 20:08:26.871317464   15110 init.cc:164]                grpc_init(void)
I1112 20:08:26.871340186   15130 completion_queue.cc:682]    cq_end_op_for_next(cq=0x55f8b8d7cbe0, tag=0x7f504699eef0, error={"created":"@1573560506.871317449","description":"Timed out waiting for connection state change","file":"src/core/ext/filters/client_channel/channel_connectivity.cc","file_line":142}, done=0x7f50482286c0, done_arg=0x7f5030015850, storage=0x7f5030015938)
I1112 20:08:26.871348393   15110 completion_queue.cc:504]    grpc_completion_queue_create_internal(completion_type=0, polling_type=0)
I1112 20:08:26.871354424   15110 completion_queue.cc:504]    grpc_completion_queue_create_internal(completion_type=0, polling_type=0)
I1112 20:08:26.871362007   15110 channel_create.cc:97]       grpc_insecure_channel_create(target=123.0.0.1:19530, args=0x7f50469b2390, reserved=(nil))
I1112 20:08:26.871368363   15126 completion_queue.cc:1060]   RETURN_EVENT[0x55f8b8d7cbe0]: OP_COMPLETE: tag:0x7f504699eef0 ERROR
I1112 20:08:26.871372004   15110 init.cc:164]                grpc_init(void)
I1112 20:08:26.871417625   15110 client_channel.cc:1367]     chand=0x55f8b8dad3d8: creating client_channel for channel stack 0x55f8b8dad1f8
I1112 20:08:26.871566469   15126 channel_connectivity.cc:232] grpc_channel_watch_connectivity_state(channel=0x55f8b8da8290, last_observed_state=3, deadline=gpr_timespec { tv_sec: 1573560507, tv_nsec: 71561216, clock_type: 1 }, cq=0x55f8b8d7cbe0, tag=0x7f504699ee80)
I1112 20:08:26.871580786   15126 completion_queue.cc:960]    grpc_completion_queue_next(cq=0x55f8b8d7cbe0, deadline=gpr_timespec { tv_sec: 1573560507, tv_nsec: 71579166, clock_type: 1 }, reserved=(nil))
I1112 20:08:26.871604159   15131 channel_connectivity.cc:43] grpc_channel_check_connectivity_state(channel=0x55f8b8dad190, try_to_connect=1)
I1112 20:08:26.871625571   15131 resolving_lb_policy.cc:196] resolving_lb=0x7f5028000f60: starting name resolution
I1112 20:08:26.871630817   15131 client_channel.cc:1273]     chand=0x55f8b8dad3d8: update: state=CONNECTING picker=0x7f50280010e0
D1112 20:08:26.871636256   15131 dns_resolver_ares.cc:176]   (c-ares resolver) resolver:0x7f5028001100 AresDnsResolver::StartLocked() is called.
D1112 20:08:26.871640254   15131 grpc_ares_wrapper.cc:605]   (c-ares resolver) request:0x7f50280015e0 c-ares grpc_dns_lookup_ares_locked_impl name=123.0.0.1:19530, default_port=https
D1112 20:08:26.871688129   15131 dns_resolver_ares.cc:427]   (c-ares resolver) resolver:0x7f5028001100 Started resolving. pending_request_:0x7f50280015e0
I1112 20:08:26.871693731   15131 client_channel.cc:1551]     chand=0x55f8b8dad3d8: created resolving_lb_policy=0x7f5028000f60
I1112 20:08:26.871698317   15131 resolving_lb_policy.cc:441] resolving_lb=0x7f5028000f60: got resolver result
I1112 20:08:26.871716241   15131 resolving_lb_policy.cc:339] resolving_lb=0x7f5028000f60: Creating new child policy pick_first
I1112 20:08:26.871722791   15131 resolving_lb_policy.cc:393] resolving_lb=0x7f5028000f60: created new LB policy "pick_first" (0x7f5028001be0)
I1112 20:08:26.871726090   15131 resolving_lb_policy.cc:356] resolving_lb=0x7f5028000f60: Updating child policy 0x7f5028001be0
I1112 20:08:26.871751023   15131 client_channel.cc:831]      chand=0x55f8b8dad3d8: creating subchannel wrapper 0x7f50280039f0 for subchannel 0x7f5028002d20
I1112 20:08:26.871772593   15131 client_channel.cc:992]      chand=0x55f8b8dad3d8: connectivity change for subchannel wrapper 0x7f50280039f0 subchannel 0x7f5028002d20 (connected_subchannel=(nil) state=CONNECTING); hopping into combiner
I1112 20:08:26.871833742   15131 chttp2_transport.cc:839]    W:0x7f50280057e0 CLIENT [ipv4:123.0.0.1:19530] state IDLE -> WRITING [TRANSPORT_FLOW_CONTROL]
I1112 20:08:26.871840412   15131 chttp2_transport.cc:839]    W:0x7f50280057e0 CLIENT [ipv4:123.0.0.1:19530] state WRITING -> WRITING+MORE [INITIAL_WRITE]
I1112 20:08:26.871854286   15131 subchannel.cc:1086]         New connected subchannel at 0x7f5028001af0 for subchannel 0x7f5028002d20
I1112 20:08:26.871862865   15131 chttp2_transport.cc:1900]   perform_transport_op[t=0x7f50280057e0]: ON_CONNECTIVITY_STATE_CHANGE:p=0x7f5028002958:from=READY BIND_POLLSET_SET
I1112 20:08:26.871867873   15131 client_channel.cc:992]      chand=0x55f8b8dad3d8: connectivity change for subchannel wrapper 0x7f50280039f0 subchannel 0x7f5028002d20 (connected_subchannel=0x7f5028001af0 state=READY); hopping into combiner
I1112 20:08:26.871871851   15131 client_channel.cc:1040]     chand=0x55f8b8dad3d8: processing connectivity change in combiner for subchannel wrapper 0x7f50280039f0 subchannel 0x7f5028002d20 (connected_subchannel=(nil) state=CONNECTING): watcher=0x7f5028002930
I1112 20:08:26.871875330   15131 client_channel.cc:1273]     chand=0x55f8b8dad3d8: update: state=CONNECTING picker=0x7f5028001810
I1112 20:08:26.871879886   15131 client_channel.cc:1040]     chand=0x55f8b8dad3d8: processing connectivity change in combiner for subchannel wrapper 0x7f50280039f0 subchannel 0x7f5028002d20 (connected_subchannel=0x7f5028001af0 state=READY): watcher=0x7f5028002930
I1112 20:08:26.871883198   15131 client_channel.cc:1273]     chand=0x55f8b8dad3d8: update: state=READY picker=0x7f5028004fc0
I1112 20:08:26.871887166   15131 client_channel.cc:1477]     chand=0x55f8b8dad3d8: updating subchannel wrapper 0x7f50280039f0 data plane connected_subchannel to 0x7f5028001af0
I1112 20:08:26.871894206   15131 writing.cc:116]             CLIENT: Ping sent [ipv4:123.0.0.1:19530]: 2/2
I1112 20:08:26.871897812   15131 chttp2_transport.cc:839]    W:0x7f50280057e0 CLIENT [ipv4:123.0.0.1:19530] state WRITING+MORE -> WRITING [begin write in current thread]
I1112 20:08:26.871908089   15131 chttp2_transport.cc:2660]   ipv4:123.0.0.1:19530: Start BDP ping err="No Error"
I1112 20:08:26.872195762   15131 channel_connectivity.cc:232] grpc_channel_watch_connectivity_state(channel=0x55f8b8dad190, last_observed_state=0, deadline=gpr_timespec { tv_sec: 1573560507, tv_nsec: 72190720, clock_type: 1 }, cq=0x55f8b8d59b40, tag=0x7f50469ab470)
I1112 20:08:26.872209883   15131 completion_queue.cc:682]    cq_end_op_for_next(cq=0x55f8b8d59b40, tag=0x7f50469ab470, error="No Error", done=0x7f50482286c0, done_arg=0x7f50280018f0, storage=0x7f50280019d8)
I1112 20:08:26.872216585   15131 completion_queue.cc:960]    grpc_completion_queue_next(cq=0x55f8b8d59b40, deadline=gpr_timespec { tv_sec: 1573560507, tv_nsec: 72215344, clock_type: 1 }, reserved=(nil))
I1112 20:08:26.872221769   15131 completion_queue.cc:1060]   RETURN_EVENT[0x55f8b8d59b40]: OP_COMPLETE: tag:0x7f50469ab470 OK
I1112 20:08:26.872287176   15131 channel_connectivity.cc:43] grpc_channel_check_connectivity_state(channel=0x55f8b8dad190, try_to_connect=0)
I1112 20:08:26.872413586   15131 channel_connectivity.cc:232] grpc_channel_watch_connectivity_state(channel=0x55f8b8dad190, last_observed_state=2, deadline=gpr_timespec { tv_sec: 1573560507, tv_nsec: 72408832, clock_type: 1 }, cq=0x55f8b8d59b40, tag=0x7f50469ab470)
I1112 20:08:26.872428649   15131 completion_queue.cc:960]    grpc_completion_queue_next(cq=0x55f8b8d59b40, deadline=gpr_timespec { tv_sec: 1573560507, tv_nsec: 72426872, clock_type: 1 }, reserved=(nil))
```

My client code is:
```Python
class GrpcMilvus(ConnectIntf):

    def __init__(self):
        self._channel = None
        self._stub = None
        self._uri = None
        self.server_address = None
        self.status = None

    def set_channel(self, host=None, port=None, uri=None):

        if host is not None:
            _port = port or "19530"
            _host = host
        elif port is None:
            try:
                config_uri = urlparse(config.GRPC_URI)
                _uri = urlparse(uri) if uri else config_uri

                if _uri.scheme != 'tcp':
                    raise ParamError(
                        'Invalid parameter uri: `{}`. Scheme `{}` '
                        'is not supported'.format(_uri, _uri.scheme))

                _host = _uri.hostname
                _port = _uri.port

            except Exception:
                raise ParamError("`{}` is illegal".format(uri))
        else:
            raise ParamError("Param is not complete. Please invoke as follow:\n"
                             "\t(host = ${HOST}, port = ${PORT})\n"
                             "\t(uri = ${URI})\n")

        if not is_legal_host(_host) or not is_legal_port(_port):
            raise ParamError("host or port is illegal")

        self._uri = str(_host) + ':' + str(_port)
        self.server_address = self._uri
        self._channel = grpc.insecure_channel(
            self._uri,
            options=[(cygrpc.ChannelArgKey.max_send_message_length, -1),
                     (cygrpc.ChannelArgKey.max_receive_message_length, -1)]
        )

    def connect(self, host=None, port=None, uri=None, timeout=3):
        if self._channel is None:
            self.set_channel(host, port, uri)

        elif self.connected():
            return Status(message="You have already connected!", code=Status.CONNECT_FAILED)

        try:
            grpc.channel_ready_future(self._channel).result(timeout=timeout)
        except grpc.FutureTimeoutError:
            raise NotConnectError('Fail connecting to server on {}. Timeout'.format(self._uri))
        except grpc.RpcError as e:
            raise NotConnectError("Connect error: <{}>".format(e))
        except Exception as e:
            raise NotConnectError("Error occurred when trying to connect server:\n<{}>".format(e))
        else:
            self._stub = milvus_pb2_grpc.MilvusServiceStub(self._channel)
            self.status = Status(message='Successfully connected! {}'.format(self._uri))
            return self.status

    def connected(self):
        if not self._stub or not self.status or not self._channel:
            return False

        try:
            grpc.channel_ready_future(self._channel).result(timeout=2)
        except (grpc.FutureTimeoutError, grpc.RpcError):
            return False
        else:
            return True
```

My test case code is:
```Python
def test_connect_with_invalid_uri(self, get_invalid_uri):
        milvus = Milvus()
        uri_value = get_invalid_uri
        with pytest.raises(Exception) as e:
            milvus.connect(uri=uri_value, timeout=1)
        assert not milvus.connected()
```

And the error output messge is:
```Python
    def test_connect_with_invalid_uri(self, get_invalid_uri):
        milvus = Milvus()
        uri_value = get_invalid_uri
        with pytest.raises(Exception) as e:
>           milvus.connect(uri=uri_value, timeout=1)
E           Failed: DID NOT RAISE <class 'Exception'>
```

### What did you expect to see?
I was troubled by this problem for several days. Thanks for your any help!!!!

### What did you see instead?

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

See [TROUBLESHOOTING.md](https://github.com/grpc/grpc/blob/master/TROUBLESHOOTING.md) for how to diagnose problems better.

**Comment by lidizheng** [comment] 2019-11-12 19:15
@BossZou In my local reproduce, I found your code raises `NotConnectError` exception as expected. There might be some network setting in your environment that is causing this unexpected behavior. I recommend to run your code in a clean slate VM, and see if problems goes away.

**Comment by BossZou** [comment] 2019-11-13 02:28
@lidizheng .The bug doesn't reappear every time。 In my CI environment, This bug reappear occasionally too.

**Comment by BossZou** [comment] 2019-11-21 07:27
I Found the bug appear when a client object connected exists in the same process.

**Comment by lidizheng** [comment] 2019-11-21 23:37
@BossZou Can you provide more info about how to reproduce it? With your snippet, I still can't reproduce this error, even with your latest update, adding a connected channel at side. The ideal format is a single script that can trigger this error.

**Comment by yashykt** [comment] 2020-05-05 18:02
Closing this down since reporter has not responded in quite some time. Please feel free to re-open if the bug persists.

**Closed by yashykt** 2020-05-05 18:02 UTC
Labels: kind/bug, lang/Python, priority/P2
