### ISSUE TITLE
centos 6.7 x86_64 "make" error

### ISSUE THREAD

**Issue by wulinlw** [grpc/grpc#5366] opened 2016-02-23 07:20 UTC
hi, i'm was install grpc in centos 6.7 X86_64
but when i run "make" ,I get the following output:
anybody help me? thanks!

> [root@localhost protobuf]# protoc --version
libprotoc 3.0.0
[root@localhost protobuf]# cd ../../
[root@localhost grpc]# make
[MAKE]    Generating /root/grpc/libs/opt/pkgconfig/grpc.pc
[MAKE]    Generating /root/grpc/libs/opt/pkgconfig/grpc_unsecure.pc
[MAKE]    Generating cache.mk
[C]       Compiling src/core/profiling/basic_timers.c
[C]       Compiling src/core/profiling/stap_timers.c
[C]       Compiling src/core/support/alloc.c
[C]       Compiling src/core/support/avl.c
[C]       Compiling src/core/support/cmdline.c
[C]       Compiling src/core/support/cpu_iphone.c
[C]       Compiling src/core/support/cpu_linux.c
[C]       Compiling src/core/support/cpu_posix.c
[C]       Compiling src/core/support/cpu_windows.c
[C]       Compiling src/core/support/env_linux.c
cc1: warnings being treated as errors
src/core/support/env_linux.c: In function ?.pr_getenv?.
src/core/support/env_linux.c:67: error: implicit declaration of function ?.ecure_getenv?
src/core/support/env_linux.c:67: error: initialization makes pointer from integer without a cast
make: *** [/root/grpc/objs/opt/src/core/support/env_linux.o] Error 1

**Comment by alanrong** [comment] 2016-02-23 09:15
I have just met this problem.I found 'getenv' and '__secure_getenv' in <stdlib.h>  but without 'secure_getenv'. so I replace secure_getenv with __secure_getenv.

**Comment by wulinlw** [comment] 2016-02-23 10:08
@alanrong  it's works!
but i got this error [https://github.com/grpc/grpc/issues/4571](url)

> [C]       Compiling third_party/boringssl/crypto/bio/buffer.c
[C]       Compiling third_party/boringssl/crypto/bio/connect.c
cc1: warnings being treated as errors
third_party/boringssl/crypto/bio/connect.c: In function ?.plit_host_and_port?.
third_party/boringssl/crypto/bio/connect.c:127: error: declaration of ?.lose?.shadows a global declaration
/usr/include/unistd.h:350: error: shadowed declaration is here
make: *** [/root/grpc/objs/opt/third_party/boringssl/crypto/bio/connect.o] Error 1

**Comment by jtattermusch** [comment] 2016-02-23 17:17
Seems like duplicate of https://github.com/grpc/grpc/issues/5370.

**Closed by jtattermusch** 2016-02-23 17:17 UTC
