### ISSUE TITLE
gRPC beta throwing termination callback exception occasionally

### ISSUE THREAD

**Issue by shuowusc** [grpc/grpc#4126] opened 2015-11-15 17:04 UTC
gRPC beta throwing exception occasionally on the server side:

 Exception calling termination callback!
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/grpc/framework/foundation/callable_util.py", line 69, in _call_logging_exceptions
    return _EasyOutcome(Outcome.Kind.RETURNED, behavior(*args, **kwargs), None)
  File "/usr/local/lib/python2.7/site-packages/grpc/framework/crust/_control.py", line 537, in set_outcome
    return self._set_outcome(outcome)
  File "/usr/local/lib/python2.7/site-packages/grpc/framework/crust/_control.py", line 257, in _set_outcome
    code = self._up_completion.value.code
AttributeError: 'NoneType' object has no attribute 'code'

**Comment by nathanielmanistaatgoogle** [comment] 2015-11-18 00:06
I believe this is a duplicate of #3919.

**Closed by nathanielmanistaatgoogle** 2015-11-18 00:06 UTC
Labels: python
