### ISSUE TITLE
System.Buffers is a Required Dependency for .NET Framework

### ISSUE THREAD

**Issue by immiao** [grpc/grpc#32471] opened 2023-02-24 06:05 UTC
### What version of gRPC and what language are you using?

C#
Grpc.Core 2.46.3
Grpc.Core.Api 2.48.0

### What operating system (Linux, Windows,...) and version?

Windows

### What runtime / compiler are you using (e.g. python version or version of gcc)

.NET v4.7.2

### What did you do?

Getting below exceptions when sending requests to server via an established `Grpc.Core.Channel` which is in ready state.

```
Grpc.Core.RpcException: 'Status(StatusCode="Cancelled", Detail="CANCELLED", DebugException="Grpc.Core.Internal.CoreErrorDetailException: {"created":"@1677218175.100000000","description":"Error received from peer ipv4:127.0.0.1:13452","file":"..\..\..\src\core\lib\surface\call.cc","file_line":953,"grpc_message":"CANCELLED","grpc_status":1}")'
```

### What did you expect to see?

More clear exception messages about why this is in cancelled state. Clearly caller did not cancel it.

### What did you see instead?

Traces without much useful information.

### Anything else we should know about your project / environment?

This turns out to be caused by a missing DLL `System.Buffers`.

Can you please add this DLL to the dependency list in .nuspec?
I have seen similar posts asking the same question however there wasn't any useful answer.

**Comment by tonydnewell** [comment] 2023-02-27 12:01
@immiao I'm not sure why you did not see System.Buffers in your project as it is a dependency for Grpc.Core (via a dependency on System.Memory) and should have been automatically included.

I've just created a .NET Framework 4.7.2 project and added the Grpc.Core and Grpc.Api NuGet packages and I can see System.Buffers has been added.

From my project file:
```xml
  <ItemGroup>
    <Reference Include="Grpc.Core, Version=2.0.0.0, Culture=neutral, PublicKeyToken=d754f35622e28bad, processorArchitecture=MSIL">
      <HintPath>packages\Grpc.Core.2.46.3\lib\net45\Grpc.Core.dll</HintPath>
    </Reference>
    <Reference Include="Grpc.Core.Api, Version=2.0.0.0, Culture=neutral, PublicKeyToken=d754f35622e28bad, processorArchitecture=MSIL">
      <HintPath>packages\Grpc.Core.Api.2.48.0\lib\net462\Grpc.Core.Api.dll</HintPath>
    </Reference>
    <Reference Include="System" />
    <Reference Include="System.Buffers, Version=4.0.2.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51, processorArchitecture=MSIL">
      <HintPath>packages\System.Buffers.4.4.0\lib\netstandard2.0\System.Buffers.dll</HintPath>
    </Reference>
    <Reference Include="System.Core" />
    <Reference Include="System.Memory, Version=4.0.1.1, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51, processorArchitecture=MSIL">
      <HintPath>packages\System.Memory.4.5.3\lib\netstandard2.0\System.Memory.dll</HintPath>
    </Reference>
    <Reference Include="System.Numerics" />
    <Reference Include="System.Numerics.Vectors, Version=4.1.3.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a, processorArchitecture=MSIL">
      <HintPath>packages\System.Numerics.Vectors.4.4.0\lib\net46\System.Numerics.Vectors.dll</HintPath>
    </Reference>
    <Reference Include="System.Runtime.CompilerServices.Unsafe, Version=4.0.4.1, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a, processorArchitecture=MSIL">
      <HintPath>packages\System.Runtime.CompilerServices.Unsafe.4.5.2\lib\netstandard2.0\System.Runtime.CompilerServices.Unsafe.dll</HintPath>
    </Reference>
    <Reference Include="System.Xml.Linq" />
    <Reference Include="System.Data.DataSetExtensions" />
    <Reference Include="Microsoft.CSharp" />
    <Reference Include="System.Data" />
    <Reference Include="System.Net.Http" />
    <Reference Include="System.Xml" />
  </ItemGroup>
```

**Comment by immiao** [comment] 2023-03-08 04:36
@tonydnewell 
System.Buffers is not listed as part of the dependencies in the .nuspec.

I think you are relying on luck that Visual Studio will add it for you automatically.

**Comment by tonydnewell** [comment] 2023-03-08 08:49
@immiao To help us understand how this happened can you say how you created your project? Did to take an existing project and change its target framework? I'd like to understand so that we can prevent this happening.

Looking at the Grpc.Core 2.46.3 .nuspec it has a dependency on System.Memory 4.5.3, so the dependency should be resolved:
```xml
<dependencies>
      <group targetFramework=".NETFramework4.5">
        <dependency id="Grpc.Core.Api" version="2.46.3" exclude="Build,Analyzers" />
        <dependency id="System.Memory" version="4.5.3" exclude="Build,Analyzers" />
      </group>
      ...
</dependencies>
```
and the .nuspec for System.Memory 4.5.3 has the dependency on System.Buffers:

```xml
<dependencies>
      ...
      <group targetFramework=".NETFramework4.5">
        <dependency id="System.Buffers" version="4.4.0" />
        <dependency id="System.Runtime.CompilerServices.Unsafe" version="4.5.2" />
      </group>
      <group targetFramework=".NETFramework4.6.1">
        <dependency id="System.Buffers" version="4.4.0" />
        <dependency id="System.Numerics.Vectors" version="4.4.0" />
        <dependency id="System.Runtime.CompilerServices.Unsafe" version="4.5.2" />
      </group>
      ...
</dependencies>
```

**Comment by tonydnewell** [comment] 2023-03-08 10:25
There have been a few related issues often to do with incorrect bind redirects. These might shed some light on what has happened with your project.

I'm reluctant to explicitly add System.Buffers to the dependencies for Grpc.Core as it is already an indirect dependency and I don't want to cause versioning problems later on or in other projects. When we fully understand why your project had an issue then we can discuss a possible solution.

- https://github.com/grpc/grpc/issues/21406
- https://github.com/grpc/grpc/issues/22083
- https://github.com/grpc/grpc/issues/23955

**Comment by immiao** [comment] 2023-03-10 08:48
I think this may be because the build system I am using does not add dependencies automatically from .nuspec which may explain why I am hitting this.

Since System.Buffers is an indirect dependency of Grpc.Core already which can be inferred from .nuspec I am actually OK with it.

Now my only ask is that if the error message could be more clear saying that it's due to missing dependencies it will be much easier to troubleshoot - all it said was "CANCELLED" which was really misleading.

**Comment by jtattermusch** [comment] 2023-03-10 13:06
For extra logging, you could've set `GRPC_VERBOSITY=debug` (and possibly other extra logging) as per https://github.com/grpc/grpc/blob/master/TROUBLESHOOTING.md

I'm closing this as "working as intended" since you using a non-standard build system it seems.

**Closed by jtattermusch** 2023-03-10 13:06 UTC
Labels: kind/bug, lang/C#, priority/P2

**Comment by immiao** [comment] 2023-03-13 02:09
@jtattermusch where do I find these logs for .NET after I set the environment variable?

It seems like none of the classes are taking a Grpc.Core.Logging.ILogger as an input

**Comment by tonydnewell** [comment] 2023-03-13 09:06
@immiao The default logger logs to System.Console (i.e. the standard output for the process).  You can change this using `GrpcEnvironment.SetLogger()`
