### ISSUE TITLE
objc CallAPIv2Tests testTimeout failure

### ISSUE THREAD

**Issue by apolcyn** [grpc/grpc#22214] opened 2020-03-03 02:21 UTC
```
Mon Mar  2 17:05:09 PST 2020 - Test Case '-[CallAPIv2Tests testIdempotentProtoRPC]' passed (0.002 seconds).
Mon Mar  2 17:05:09 PST 2020 - Test Case '-[CallAPIv2Tests testMetadata]' started.
Mon Mar  2 17:05:09 PST 2020 - Test Case '-[CallAPIv2Tests testMetadata]' passed (0.606 seconds).
Mon Mar  2 17:05:09 PST 2020 - Test Case '-[CallAPIv2Tests testOAuthToken]' started.
Mon Mar  2 17:05:09 PST 2020 - Test Case '-[CallAPIv2Tests testOAuthToken]' passed (0.002 seconds).
Mon Mar  2 17:05:09 PST 2020 - Test Case '-[CallAPIv2Tests testResponseSizeLimitExceeded]' started.
Mon Mar  2 17:05:09 PST 2020 - Test Case '-[CallAPIv2Tests testResponseSizeLimitExceeded]' passed (0.003 seconds).
Mon Mar  2 17:05:09 PST 2020 - Test Case '-[CallAPIv2Tests testTimeout]' started.
Mon Mar  2 17:05:09 PST 2020 - E0302 17:04:16.357022000 123145481273344 ssl_transport_security.cc:1407] Handshake failed with fatal error SSL_ERROR_SSL: error:100000f7:SSL routines:OPENSSL_internal:WRONG_VERSION_NUMBER.
Mon Mar  2 17:05:09 PST 2020 - E0302 17:04:16.357546000 123145481273344 ssl_transport_security.cc:1407] Handshake failed with fatal error SSL_ERROR_SSL: error:100000f7:SSL routines:OPENSSL_internal:WRONG_VERSION_NUMBER.
Mon Mar  2 17:05:09 PST 2020 - /Volumes/BuildData/tmpfs/src/github/grpc/workspace_objc_macos_opt_native/src/objective-c/tests/UnitTests/APIv2Tests.m:412: error: -[CallAPIv2Tests testTimeout] : ((error.code) equal to (GRPCErrorCodeDeadlineExceeded)) failed: ("14") is not equal to ("4")
Mon Mar  2 17:05:09 PST 2020 - Test Case '-[CallAPIv2Tests testTimeout]' failed (0.005 seconds).
Mon Mar  2 17:05:09 PST 2020 - Test Case '-[CallAPIv2Tests testTimeoutBackoff1]' started.
Mon Mar  2 17:05:09 PST 2020 - Test Case '-[CallAPIv2Tests testTimeoutBackoff1]' passed (0.002 seconds).
Mon Mar  2 17:05:09 PST 2020 - Test Case '-[CallAPIv2Tests testTimeoutBackoff2]' started.
Mon Mar  2 17:05:09 PST 2020 - Test Case '-[CallAPIv2Tests testTimeoutBackoff2]' passed (0.002 seconds).
Mon Mar  2 17:05:09 PST 2020 - Test Case '-[CallAPIv2Tests testUserAgentPrefix]' started.
Mon Mar  2 17:05:09 PST 2020 - Test Case '-[CallAPIv2Tests testUserAgentPrefix]' passed (0.006 seconds).
Mon Mar  2 17:05:09 PST 2020 - Test Suite 'CallAPIv2Tests' failed at 2020-03-02 17:04:16.371.
Mon Mar  2 17:05:09 PST 2020 - 	 Executed 15 tests, with 1 failure (0 unexpected) in 5.082 (5.089) seconds
Mon Mar  2 17:05:09 PST 2020 - Test Suite 'InteropTestsEmptySuite' started at 2020-03-02 17:04:16.372
Mon Mar  2 17:05:09 PST 2020 - Test Suite 'InteropTestsEmptySuite' passed at 2020-03-02 17:04:16.372.
Mon Mar  2 17:05:09 PST 2020 - 	 Executed 0 tests, with 0 failures (0 unexpected) in 0.000 (0.000) seconds
```

full log: https://source.cloud.google.com/results/invocations/763955c9-682a-41b0-a1ff-03a8c1936252/targets/github%2Fgrpc%2Frun_tests%2Fobjc_macos_opt_native%2Fmac-test-basictests/tests

seen in PR: https://github.com/grpc/grpc/pull/22211

**Comment by veblush** [comment] 2020-03-12 15:59
Closed because it's duplicate of https://github.com/grpc/grpc/issues/9538

**Closed by veblush** 2020-03-12 15:59 UTC
Labels: kind/bug, priority/P2
