### ISSUE TITLE
c-ares on Windows: DNS resolution failed exception when trying to connect locally via host name

### ISSUE THREAD

**Issue by jwfx** [grpc/grpc#25252] opened 2021-01-25 13:37 UTC
### What version of gRPC and what language are you using?
C#
gRPC 2.35 packages
### What operating system (Linux, Windows,...) and version?
Windows Server 2012 R2
### What runtime / compiler are you using (e.g. python version or version of gcc)
 .NET Core 2.1.0
### What did you do?
Modified sample code here: https://github.com/jwfx/grpc/commit/c0545746bddfacd7ea8a0bb35943c065976fd85b

1. Run the GreeterServer on 0.0.0.0
2. Run the GreeterClient on the same machine connecting to the host name

### What did you expect to see?
Connection should succeed when using the ares resolver.
### What did you see instead?
Connection fails with exception

```
Unhandled Exception: Grpc.Core.RpcException: Status(StatusCode="Unavailable", Detail="DNS resolution failed for service: MYTESTHOST:30051", DebugException="Grpc.Core.Internal.CoreErrorDetailException: {"created":"@1611579519.773000000", "description":"Resolver transient failure","file":"..\..\..\src\core\ext\filters\client_channel\client_channel.cc","file _line":2141,"referenced_errors":[{"created":"@1611579519.773000000",...
```

### Anything else we should know about your project / environment?

This issue seems to occur when the Windows machine is not registered at the DNS server (`nslookup <machinename>` fails, but `ping <machinename>` works). The c-ares resolver seems to try to resolve the hosts IP remotely instead of locally, which fails due to lack of a DNS record. Switching to the native resolver fixes the issue.

There should probably be a bypass similar to what was done by @apolcyn for resolving localhost on Windows, see https://github.com/grpc/grpc/pull/16420

**Comment by jtattermusch** [comment] 2021-01-29 13:14
Reassigning to @apolcyn  as this seems to be c-ares related.

**Comment by jtattermusch** [comment] 2021-01-29 13:17
@jwfx  just to verify this is a c-ares related problem, can you run your the example with 
`GRPC_DNS_RESOLVER=native` (disables c-ares) and come back with the result?
https://github.com/grpc/grpc/blob/master/doc/environment_variables.md

**Comment by jwfx** [comment] 2021-01-29 14:04
@jtattermusch 
I tested that and the native resolver does not have this issue. See last paragraph in my initial issue.

**Comment by jtattermusch** [comment] 2022-10-11 14:21
@tonydnewell  can you please take a look?  (also note that it looks somewhat similar to https://github.com/grpc/grpc/issues/25953).

**Comment by tonydnewell** [comment] 2022-10-13 12:58
@jwfx @jtattermusch
I can reproduce this on my local Windows machine. However I think this is not a gRPC problem - it is a problem in a badly configured environment.

Basically the c-ares resolver only does DNS lookups. It does not do netbios lookups. If you want netbios lookups then use the native resolver.

To fix the environment for c-ares:
 - add the host information to the DNS server
 - or add the host information to the local `hosts` file (usually in `C:\Windows\System32\drivers\etc\hosts`)

Notes on testing this:
I added an entry to my `lmhosts` file (not to be confused with `hosts` file) - this is used for local netbios lookups. The name I added could be resolved by the native resolver but could not be looked up by the c-ares resolver.

**Comment by jwfx** [comment] 2022-10-13 16:26
I understand your point and I agree that Microsoft has more than one questionable default configuration and behavior, but I doubt there will be much movement on that end...

I think being able to connect to your own machine name should just work out of the box, without having to change Windows default settings. The machine could even be completely without network and it should _just_ work.

If c-ares cannot support this use case, which in my humble opinion is not completely outlandish, then maybe it is not fit for the task at hand. Maybe on Windows the native resolver should be default? To be honest I don't know the complete backstory for c-ares in gRPC.

For localhost the same issue was addressed in the past, if I may quote myself.

> There should probably be a bypass similar to what was done by @apolcyn for resolving localhost on Windows, see https://github.com/grpc/grpc/pull/16420

**Comment by tonydnewell** [comment] 2022-10-13 17:53
If all that you want to do is talk to the local machine then "localhost" will work.

If you want other machines to talk to this machine then DNS needs to be configured correctly.

I can't see the scenario where you want to talk the the local machine by its name but no one else can talk to the machine by its name (because its not in DNS) but you don't want to use "localhost".

I agree c-ares _could_ get the local machine name (from the registry) on start up and use that like it does for for "localhost" - any thoughts @apolcyn @jtattermusch

**Comment by jtattermusch** [comment] 2022-10-14 12:49
> If all that you want to do is talk to the local machine then "localhost" will work.
> 
> If you want other machines to talk to this machine then DNS needs to be configured correctly.
> 
> I can't see the scenario where you want to talk the the local machine by its name but no one else can talk to the machine by its name (because its not in DNS) but you don't want to use "localhost".
> 
> I agree c-ares _could_ get the local machine name (from the registry) on start up and use that like it does for for "localhost" - any thoughts @apolcyn @jtattermusch

@apolcyn  would be the right person to answer that.

**Comment by tonydnewell** [comment] 2022-10-14 14:19
Summary for clarification

Problem:
Using the default c-ares resolver on Windows does not resolve names that are netbios names and not in DNS. E.g. the local machine name is not resolved unless it is also specified in DNS (or local hosts file). 

Note - this is not C# specific

Workarounds:
- use the native resolver
- add the name to DNS
- add the name to the local hosts file
- use "localhost"

Possible solutions:
- make native resolver the default on Windows
- add netbios support to c-ares
- add local name recognition to c-ares
- update documentation to describe the behaviour and the possible workarounds
- or do nothing as there are several workarounds

**Comment by tonydnewell** [comment] 2022-10-18 10:15
I've created a PR to update the documentation for the resolvers
https://github.com/grpc/grpc/pull/31385

**Comment by tonydnewell** [comment] 2022-10-20 08:42
@jtattermusch I suggest we close this with no fix planned as the documentation has now been updated for NetBIOS support:
https://github.com/grpc/grpc/blob/master/doc/environment_variables.md

**Closed** 2022-10-20 12:48 UTC
Labels: kind/bug, lang/C#, platform/Windows, priority/P2
