### ISSUE TITLE
Jenkins Basic Tests Windows 'h2_http_proxy_test connectivity' flaky

### ISSUE THREAD

**Issue by muxi** [grpc/grpc#8996] opened 2016-12-08 01:02 UTC
```
I1207 19:30:39.790000000  4212 http_proxy.c:428] Proxy address: localhost:2815
D1207 19:30:39.790000000 10848 connectivity.c:55] verifying
D1207 19:30:39.891000000  4212 connectivity.c:97] watching
I1207 19:30:39.892000000 11932 http_connect_handshaker.c:273] Connecting to server localhost:2814 via HTTP proxy localhost:2815
I1207 19:30:40.889000000 11932 http_proxy.c:131] HTTP proxy server connect: {"created":"@1481139040.889000000","description":"OS Error","file":"C:\jenkins\workspace\gRPC_pr_win\workspace_c_windows_dbg\vsprojects\..\src\core\lib\iomgr\tcp_client_windows.c","file_line":119,"os_error":"No connection could be made because the target machine actively refused it.\r\n","syscall":"ConnectEx","wsa_error":10061}
I1207 19:30:40.889000000 11932 subchannel.c:675] Connect failed: {"created":"@1481139040.889000000","description":"End of TCP stream","file":"C:\jenkins\workspace\gRPC_pr_win\workspace_c_windows_dbg\vsprojects\..\src\core\lib\iomgr\tcp_windows.c","file_line":184}
I1207 19:30:40.889000000 11932 http_connect_handshaker.c:273] Connecting to server localhost:2814 via HTTP proxy localhost:2815
I1207 19:30:41.890000000 11932 subchannel.c:675] Connect failed: {"created":"@1481139041.890000000","description":"End of TCP stream","file":"C:\jenkins\workspace\gRPC_pr_win\workspace_c_windows_dbg\vsprojects\..\src\core\lib\iomgr\tcp_windows.c","file_line":184}
I1207 19:30:41.890000000 11932 subchannel.c:478] Retry immediately
I1207 19:30:41.890000000 11932 subchannel.c:430] Failed to connect to channel, retrying
I1207 19:30:41.890000000 11932 http_connect_handshaker.c:273] Connecting to server localhost:2814 via HTTP proxy localhost:2815
D1207 19:30:41.890000000  4212 connectivity.c:129] *** STARTING SERVER ***
I1207 19:30:41.890000000 11932 http_proxy.c:131] HTTP proxy server connect: {"created":"@1481139041.890000000","description":"OS Error","file":"C:\jenkins\workspace\gRPC_pr_win\workspace_c_windows_dbg\vsprojects\..\src\core\lib\iomgr\tcp_client_windows.c","file_line":119,"os_error":"No connection could be made because the target machine actively refused it.\r\n","syscall":"ConnectEx","wsa_error":10061}
D1207 19:30:41.897000000  4212 connectivity.c:134] *** STARTED SERVER ***
D1207 19:30:42.394000000  4212 connectivity.c:151] *** SHUTTING DOWN SERVER ***
E1207 19:30:45.395000000  4212 cq_verifier.c:184] assertion failed: e->success == ev->success
Abort handler called.
*** 0: 000000000115481F  - 0000000000000000
*** 1: 0000000001154D27  - 0000000000000000
*** 2: 00000000011F6589  - 0000000000000000
*** 3: 00000000011F1984  - 0000000000000000
*** 4: 00000000013BCA7D  - 0000000000000000
*** 5: 00000000013BC021  - 0000000000000000
*** 6: 00000000011CD5F0  - 0000000000000000
*** 7: 00000000011CD7AF  - 0000000000000000
*** 8: 00000000011BFE2B  - 0000000000000000
*** 9: 00000000011513AA  - 0000000000000000
*** 10: 00000000011F1CEA  - 0000000000000000
*** 11: 00000000011F1E3D  - 0000000000000000
*** 12: 000000007684336A BaseThreadInitThunk - 0000000076843358
*** 13: 0000000077339902 RtlInitializeExceptionChain - 000000007733989F
*** 14: 00000000773398D5 RtlInitializeExceptionChain - 000000007733989F
```

Refer to:
https://grpc-testing.appspot.com/job/gRPC_pr_win/1269/consoleFull
https://grpc-testing.appspot.com/job/gRPC_pr_win/1272/consoleFull

**Comment by ericgribkoff** [comment] 2016-12-09 22:20
Seen again: https://grpc-testing.appspot.com/job/gRPC_master_windows/811/testReport/junit/(root)/c_windows_opt/vsprojects_Release_h2_http_proxy_test_exe_connectivity/

**Comment by matt-kwong** [comment] 2016-12-16 22:50
Seen again:
https://grpc-testing.appspot.com/job/gRPC_master_windows/894/
https://grpc-testing.appspot.com/job/gRPC_master_windows/892/
https://grpc-testing.appspot.com/job/gRPC_master_windows/890/#showFailuresLink
https://grpc-testing.appspot.com/job/gRPC_master_windows/889/

**Comment by dgquintas** [comment] 2017-01-24 17:51
Seen again in #9453

**Comment by jtattermusch** [comment] 2017-05-10 08:43
Duplicate of #9153 and #9088.

**Closed by jtattermusch** 2017-05-10 08:43 UTC
Labels: BUILDPONY, flaky test
