### ISSUE TITLE
UNAVAILABLE status and "Connect Failed" details running "hello world" example

### ISSUE THREAD

**Issue by nirenrc** [grpc/grpc#9987] opened 2017-03-06 08:17 UTC
Hello

I am using python 2.7 & gRPC-io 1.1.3 for testing hello world; unfortunately greeter_client.py return below error. What could be wrong here?
python greeter_server.py &
[1] 1606
python greeter_client.py
Traceback (most recent call last):
  File "greeter_client.py", line 47, in <module>
    run()
  File "greeter_client.py", line 42, in run
    response = stub.SayHello(helloworld_pb2.HelloRequest(name='you'))
  File "/virt_test/env/local/lib/python2.7/site-packages/grpc/_channel.py", line 507, in __call__
    return _end_unary_response_blocking(state, False, deadline)
  File "/virt_test/env/local/lib/python2.7/site-packages/grpc/_channel.py", line 455, in _end_unary_response_blocking
    raise _Rendezvous(state, None, None, deadline)

Niren

**Comment by nirenrc** [comment] 2017-03-06 20:48
Hello

CPP based examples are working fine for both hello world, router guide includes CPP bases server and client, In another combination of CPP client & Python based server is OK too. It just issue of python based client is not working. I had followed instructions from http://www.grpc.io/docs/tutorials/basic/python.html 

Virtualenv and non virrtualenv did not make any difference, 

Is there additional changes or environment setting are required? Please let me know desperately looking for help.

Niren

**Comment by keekun** [comment] 2017-03-16 17:09
I have the same error  just like this.

go Server + go Client -> OK
go Server + grpc-gateway + curl -> OK
go Server + Py3.5 Client -> line 445 raise _Rendezvous(state, None, None, deadline)

**Comment by nathanielmanistaatgoogle** [comment] 2017-04-26 21:19
@nirenrc and @keekun: thank you for sharing the stack traces with us, but is that all the output emitted from your program? Was there nothing else? Anything that looks like `grpc.StatusCode.<something>` or a descriptive error message? Also have you modified the hello world code at all?

**Comment by stevec2810** [comment] 2017-05-31 10:11
I also have issues with greeter_clint.py. greeter_server.py seems to be running..

# python greeter_client.py
Traceback (most recent call last):
  File "greeter_client.py", line 48, in <module>
    run()
  File "greeter_client.py", line 43, in run
    response = stub.SayHello(helloworld_pb2.HelloRequest(name='you'))
  File "/usr/lib64/python2.7/site-packages/grpc/_channel.py", line 507, in __call__
    return _end_unary_response_blocking(state, call, False, deadline)
  File "/usr/lib64/python2.7/site-packages/grpc/_channel.py", line 455, in _end_unary_response_blocking
    raise _Rendezvous(state, None, None, deadline)
grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with (StatusCode.UNAVAILABLE, Connect Failed)>

I install grpcio tools and grpc

**Comment by stevec2810** [comment] 2017-05-31 10:16
[root@testserver helloworld]# ps -ef |grep greeter_server
root     17900 17562  0 20:09 pts/4    00:00:00 python greeter_server.py
root     22421 17362  0 20:20 pts/2    00:00:00 grep --color=auto greeter
[root@testserver helloworld]# netstat -anp |grep 17900
tcp6       0      0 :::50051                :::*                    LISTEN      17900/python

just to show server is running...

**Comment by nathanielmanistaatgoogle** [comment] 2017-05-31 15:45
@stevec2810: does this happen every time or just some of the time? Is the problem abated by adding `grpc.channel_ready_future(channel).result()` between the `channel = ` line and the `stub = ` line? With what version of `grpcio` are you observing the problem?

**Comment by stevec2810** [comment] 2017-06-01 07:47
Hi. Thanks for the Help.
Installing collected packages: grpcio
Successfully installed grpcio-1.3.5
Installing collected packages: grpcio-tools
Successfully installed grpcio-tools-1.3.5
These come from pip 9.0.1
I added the mod you suggested but the client just sits there in an endless loop.

**Comment by stevec2810** [comment] 2017-06-01 08:11
I also built from source the following version.
Installing collected packages: grpcio
  Running setup.py install for grpcio ... done
Successfully installed grpcio-1.5.0.dev0
But I get the same when I try to run the hello world client. All this is done inside a virtualenv
(src27grpc) [root@test helloworld]# python --version
Python 2.7.13
(src27grpc) [root@gnpifibersim1 helloworld]# python greeter_client.py
Traceback (most recent call last):
  File "greeter_client.py", line 48, in <module>
    run()
  File "greeter_client.py", line 43, in run
    response = stub.SayHello(helloworld_pb2.HelloRequest(name='you'))
  File "/root/Downloads/src27grpc/lib/python2.7/site-packages/grpc/_channel.py", line 507, in __call__
    return _end_unary_response_blocking(state, call, False, deadline)
  File "/root/Downloads/src27grpc/lib/python2.7/site-packages/grpc/_channel.py", line 455, in _end_unary_response_blocking
    raise _Rendezvous(state, None, None, deadline)
grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with (StatusCode.UNAVAILABLE, Connect Failed)>
(src27grpc) [root@test helloworld]# netstat -anp |grep 50051
tcp        0      0 :::50051                    :::*                        LISTEN      26960/python
(src27grpc) [root@test helloworld]# ps -ef |grep  26960
root     26960 26944  0 04:02 pts/5    00:00:00 python greeter_server.py
root     27097 24903  0 04:09 pts/4    00:00:00 grep 26960
(src27grpc) [root@test helloworld]#

**Comment by nathanielmanistaatgoogle** [comment] 2017-06-01 15:53
@stevec2810: tell us more about your platform? On what hardware and with what operating system are you working? I just went through [the Hello World exercise](http://www.grpc.io/docs/quickstart/python.html) on my Debian 8 workstation in Google Compute Engine and it worked as expected.

When ran `greeter_client.py` without `greeter_server.py` running, I saw the `(StatusCode.UNAVAILABLE, Connect Failed)` that you're seeing. Is it possible that you've got something like a misconfigured firewall or something else preventing applications from locally connecting to other applications?

**Comment by stevec2810** [comment] 2017-06-01 16:08
System is Centos 6.9 with python 2.7.13. I also tested it on Centos 7.2 and same issue. Iptables is stopped completely. the greeter_server appears to be running, but I don't know any way to debug this as I am completely new to it. Hardware is a VM running in VMware, 2G RAM single vcpu fairly straightforward system.

**Comment by stevec2810** [comment] 2017-06-01 16:14
(src27grpc) [root@test helloworld]# gcc --version
gcc (GCC) 4.7.2 20121015 (Red Hat 4.7.2-5)
Copyright (C) 2012 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

(src27grpc) [root@test helloworld]# python --version
Python 2.7.13

**Comment by nathanielmanistaatgoogle** [comment] 2017-06-01 16:19
@stevec2810: on how many different systems have you observed the problem? Do you have access to multiple systems on which to test?

**Comment by stevec2810** [comment] 2017-06-01 16:39
I have many systems unfortunately all are either redhat/centos base.

**Comment by nathanielmanistaatgoogle** [comment] 2017-06-01 16:44
@stevec2810: that's fine; if it's the case that our example fails on all systems of a given type that's certainly alarming information that we'd like to have confirmed. Are you able to reproduce the problem on a completely "clean" freshly-installed system? I don't know much about VMware; are you able to reproduce the problem on some system outside VMware?

**Comment by stevec2810** [comment] 2017-06-01 16:52
vmwrae doesn't matter really, ust think of it as a fresh server. These are brand new installs. This one is Centos 6.9 with development tools installed, upgraded GCC to 4.7 installed protocol buffers from source, built the grpcio from source..build Bazel from source..installed python 2.7 and virtualenv. this system is about as basic and brand new as I could make it.

**Comment by nathanielmanistaatgoogle** [comment] 2017-06-02 05:33
@stevec2810: just one more sanity check: is the problem isolated to gRPC Python (or gRPC)? Are you able, in the same environment, to spin up a random HTTP server, connect to it, and get a response from it?

**Comment by stevec2810** [comment] 2017-06-02 06:53
not sure I follow you. you want a web server running on port 80 on this server or is there some way to test gRPC from http?

**Comment by stevec2810** [comment] 2017-06-02 08:09
So, I installed httpd and configured a simple webpage, I can connect to it, so the TCP stack and applications are working correctly

**Comment by stevec2810** [comment] 2017-06-02 08:43
(src27grpc) [root@test Downloads]# cd grpc/examples/python/helloworld/
(src27grpc) [root@test helloworld]# python greeter_server.py &
[1] 2071
(src27grpc) [root@test helloworld]# netstat -anp |grep 2071
tcp        0      0 :::50051                    :::*                        LISTEN      2071/python
(src27grpc) [root@test helloworld]# python greeter_client.py
Traceback (most recent call last):
  File "greeter_client.py", line 48, in <module>
    run()
  File "greeter_client.py", line 43, in run
    response = stub.SayHello(helloworld_pb2.HelloRequest(name='you'))
  File "/root/Downloads/src27grpc/lib/python2.7/site-packages/grpc/_channel.py", line 507, in __call__
    return _end_unary_response_blocking(state, call, False, deadline)
  File "/root/Downloads/src27grpc/lib/python2.7/site-packages/grpc/_channel.py", line 455, in _end_unary_response_blocking
    raise _Rendezvous(state, None, None, deadline)
grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with (StatusCode.UNAVAILABLE, Connect Failed)>
(src27grpc) [root@test helloworld]# telnet localhost 80
Trying ::1...
Connected to localhost.
Escape character is '^]'.
GET /index.htm HTTP/1.1
host: localhost


you can see here the hosted page, and the servers running on the port. is there anyway to send a command to the server on the telnet port 50051? just to test it
HTTP/1.1 200 OK
Date: Fri, 02 Jun 2017 08:41:00 GMT
Server: Apache/2.2.15 (CentOS)
Last-Modified: Fri, 02 Jun 2017 08:35:59 GMT
ETag: "a5b3f-c3-550f60af3cb9c"
Accept-Ranges: bytes
Content-Length: 195
Connection: close
Content-Type: text/html; charset=UTF-8

<HTML>

<HEAD>

<TITLE>Test Page</TITLE>

</HEAD>

<BODY BGCOLOR="FFFFFF">


<HR>

<a href="http://www.google.comm">Hello</a>

Google

<H1>Testing</H1>



</HR>
</BODY>

</HTML>





Connection closed by foreign host.
(src27grpc) [root@test helloworld]#

**Comment by nathanielmanistaatgoogle** [comment] 2017-06-02 13:35
@stevec2810: on Google Compute Engine, using both the GCE-provided CentOS 7 and RHEL 7 images, the following works for me (prints `Greeter client received: Hello, you!`) in brand-new virtual machines:
```
sudo yum install git python-virtualenv
virtualenv venv
venv/bin/pip install --upgrade pip
venv/bin/pip install --upgrade grpcio grpcio-tools
git clone https://github.com/grpc/grpc
cd grpc/examples/python/helloworld
../../../../venv/bin/python greeter_server.py &
../../../../venv/bin/python greeter_client.py
```
. Do you have access to virtual machines on Google Compute Engine? If so, do those exact steps work for you?

**Comment by stevec2810** [comment] 2017-06-02 18:12
ahh, no I don't have a cloud compute account.

I was trying to build a gRPC server inside my network. I don't really have access to the cloud from inside the network. so I would need to be able to produce a working gRPC server without using your image. I can see there is probably something in your environment that I don't have.

**Comment by nathanielmanistaatgoogle** [comment] 2017-06-02 21:43
@stevec2810: I'm starting to run out of ideas but since you mentioned having built from source, are you able to run the tests? `./tools/run_tests/run_tests.py --language=python --newline_on_success`? Most of those tests make local connections between servers and clients.

**Comment by stevec2810** [comment] 2017-06-03 08:11
(src27grpc) [root@gnpifibersim1 grpc_src]# ./tools/run_tests/run_tests.py --language=python --newline_on_success

++ dirname /root/Downloads/grpc_src/tools/run_tests/helper_scripts/build_python.sh
+ cd /root/Downloads/grpc_src/tools/run_tests/helper_scripts/../../..
++ uname -s
+ PLATFORM=Linux
+ PYTHON=python3.4
+ VENV=py34
+ VENV_RELATIVE_PYTHON=bin/python
+ TOOLCHAIN=unix
++ is_msys
++ '[' Linux '!=' Linux ']'
++ exit 1
+ '[' ']'
++ pwd
+ ROOT=/root/Downloads/grpc_src
+ export 'CFLAGS=-I/root/Downloads/grpc_src/include -std=gnu99 -fno-wrapv '
+ CFLAGS='-I/root/Downloads/grpc_src/include -std=gnu99 -fno-wrapv '
+ export GRPC_PYTHON_BUILD_WITH_CYTHON=1
+ GRPC_PYTHON_BUILD_WITH_CYTHON=1
+ export LANG=en_US.UTF-8
+ LANG=en_US.UTF-8
+ HOST_PYTHON=python
++ is_linux
++ '[' '' '!=' Linux ']'
++ echo true
+ '[' true ']'
++ command -v ccache
+ '[' -x '' ']'
+ python3.4 -m virtualenv py34
Using base prefix '/usr/local'
New python executable in /root/Downloads/grpc_src/py34/bin/python3.4
Also creating executable in /root/Downloads/grpc_src/py34/bin/python
Installing setuptools, pip, wheel...done.
++ script_realpath py34/bin/python
+++ command -v realpath
++ '[' -x '' ']'
+++ command -v grealpath
++ '[' -x '' ']'
++ exit 1
+ VENV_PYTHON=
FAILED: /root/Downloads/grpc_src/tools/run_tests/helper_scripts/build_python.sh [ret=1, pid=29889]
FAILED: Some tests failed
(src27grpc) [root@gnpifibersim1 grpc_src]#

**Comment by stevec2810** [comment] 2017-06-03 08:39
to me it looks like there is a whole lot more required than I currently have dependency wise. This is my python env. I just followed the install for grpcio and it doesn't work. Maybe I need a google cloud VM to make this work? 

[root@test grpc_src]# pip freeze
coverage==4.4.1
Cython==0.25.2
enum34==1.1.6
futures==3.1.1
grpcio==1.5.0.dev0
protobuf==3.3.0
six==1.10.0
twitter-text-python==1.1.0
virtualenv==15.1.0
[root@test grpc_src]#

**Comment by stevec2810** [comment] 2017-06-03 11:36
Does this help, running server with DEBUG on GRPC_TRACE?

D0603 07:34:11.021291685   30230 timer_generic.c:559]        TIMER CHECK END: 0 timers triggered; next=99329.495262007 [8008]
D0603 07:34:11.021295852   30230 timer_manager.c:161]        sleep for a while
I0603 07:34:11.037029960   30232 ev_epollsig_linux.c:1489]   pollset_work: ends
I0603 07:34:11.037060704   30232 completion_queue.c:861]     RETURN_EVENT[0x2338e90]: QUEUE_TIMEOUT
I0603 07:34:11.037076447   30232 completion_queue.c:764]     grpc_completion_queue_next(cc=0x2338e90, deadline=gpr_timespec { tv_sec: 1496489651, tv_nsec: 237073094, clock_type: 1 }, reserved=(nil))
I0603 07:34:11.037085453   30232 ev_epollsig_linux.c:1426]   pollset_work: pollset: 0x2338ff8, worker 0x7fcb768f4b20, pi 0x7fcb68001000
I0603 07:34:11.037090458   30232 ev_epollsig_linux.c:1428]   pollset_work: begins
I0603 07:34:11.237375627   30232 ev_epollsig_linux.c:1489]   pollset_work: ends
I0603 07:34:11.237446552   30232 completion_queue.c:861]     RETURN_EVENT[0x2338e90]: QUEUE_TIMEOUT
I0603 07:34:11.237465959   30232 completion_queue.c:764]     grpc_completion_queue_next(cc=0x2338e90, deadline=gpr_timespec { tv_sec: 1496489651, tv_nsec: 437460822, clock_type: 1 }, reserved=(nil))
I0603 07:34:11.237491671   30232 ev_epollsig_linux.c:1426]   pollset_work: pollset: 0x2338ff8, worker 0x7fcb768f4b20, pi 0x7fcb68001000
I0603 07:34:11.237503263   30232 ev_epollsig_linux.c:1428]   pollset_work: begins
I0603 07:34:11.437877314   30232 ev_epollsig_linux.c:1489]   pollset_work: ends
I0603 07:34:11.437945985   30232 completion_queue.c:861]     RETURN_EVENT[0x2338e90]: QUEUE_TIMEOUT
I0603 07:34:11.437974468   30232 completion_queue.c:764]     grpc_completion_queue_next(cc=0x2338e90, deadline=gpr_timespec { tv_sec: 1496489651, tv_nsec: 637967247, clock_type: 1 }, reserved=(nil))
I0603 07:34:11.437993167   30232 ev_epollsig_linux.c:1426]   pollset_work: pollset: 0x2338ff8, worker 0x7fcb768f4b20, pi 0x7fcb68001000
I0603 07:34:11.438004013   30232 ev_epollsig_linux.c:1428]   pollset_work: begins
^CI0603 07:34:11.597278939   30228 server.c:1227]              grpc_server_shutdown_and_notify(server=0x22f9a00, cq=0x2338e90, tag=0x7fcb7730fc20)
I0603 07:34:11.597355432   30228 completion_queue.c:564]     cq_end_op_for_next(exec_ctx=0x7ffd0ab93900, cc=0x2338e90, tag=0x7fcb77d62c20, error={"created":"@1496489651.597331390","description":"Server Shutdown","file":"src/core/lib/surface/server.c","file_line":1265}, done=0x7fcb7c106900, done_arg=0x236a280, storage=0x236a2b8)
E0603 07:34:11.597378725   30228 completion_queue.c:567]     Operation failed: tag=0x7fcb77d62c20, error={"created":"@1496489651.597331390","description":"Server Shutdown","file":"src/core/lib/surface/server.c","file_line":1265}
I0603 07:34:11.597394587   30228 ev_epollsig_linux.c:1128]   pollset_worker_kick: Kicking worker: 0x7fcb768f4b20 (thread id: 140511844198144)
D0603 07:34:11.597432644   30228 lockfree_event.c:167]       lfev_set_shutdown: 0x2368658 curr=0x2377540 err={"created":"@1496489651.597420354","description":"Server shutdown","file":"src/core/lib/iomgr/tcp_server_posix.c","file_line":573}
D0603 07:34:11.597460227   30228 lockfree_event.c:167]       lfev_set_shutdown: 0x2368660 curr=(nil) err={"created":"@1496489651.597420354","description":"Server shutdown","file":"src/core/lib/iomgr/tcp_server_posix.c","file_line":573}
D0603 07:34:11.597481032   30228 lockfree_event.c:167]       lfev_set_shutdown: 0x2368658 curr=0x22f74e1 err={"created":"@1496489651.597471552","description":"Server shutdown","file":"src/core/lib/iomgr/tcp_server_posix.c","file_line":573}
D0603 07:34:11.597500924   30228 lockfree_event.c:167]       lfev_set_shutdown: 0x2368658 curr=0x22f74e1 err={"created":"@1496489651.597492249","description":"Server destroyed","file":"src/core/lib/iomgr/tcp_server_posix.c","file_line":204}
I0603 07:34:11.597555053   30228 completion_queue.c:564]     cq_end_op_for_next(exec_ctx=0x7ffd0ab93900, cc=0x2338e90, tag=0x7fcb7730fc20, error="No Error", done=0x7fcb7c107eb0, done_arg=0x22f9a00, storage=0x23686b0)
I0603 07:34:11.597917397   30232 ev_epollsig_linux.c:1447]   pollset_work: pollset: 0x2338ff8, worker: 0x7fcb768f4b20 received kick
I0603 07:34:11.597941272   30232 ev_epollsig_linux.c:1489]   pollset_work: ends

**Comment by nathanielmanistaatgoogle** [comment] 2017-06-05 19:18
@stevec2810:

* Yes, building gRPC Python and running its tests requires having much more installed than what is required to merely install and use _built_ gRPC Python.
* When you write "I was trying to build a gRPC server inside my network."... have you been able to reproduce the problem outside your network? Do you have access to any machine outside your network?
* With what other ports have you attempted to complete the exercise? You'd have to modify the `greeter_server.py` and `greeter_client.py` files, but that shouldn't be an issue. Is something blocking your use of port 50051 specifically, or blocking your use of a large range of high-numbered ports?
* When you write "there is probably something in your environment that I don't have", I suspect it's the exact opposite, and that there's something in _your_ environment that only you have preventing the exercise from working.

**Comment by stevec2810** [comment] 2017-06-06 08:52
I finally got it to work.
I rebuilt another server, using protocol buffers 3.2.0 and an older version of grpc on a new install of centos 7.3,but I don't think that was it.
In the end I made it work by modifying line
channel = grpc.insecure_channel('localhost:50051')
 
to have the IP address of my FIRST Ethernet interface. If I use any other interface it fails. this is despite the server apparently running on all interfaces see the following.
[root@gnpigrpc1 helloworld]# netstat -anp |grep 50051
tcp6       0      0 :::50051                :::*                    LISTEN      26188/python
I think the colons indicate that the server is running on other interfaces?
However, until I put eth0 ip in the channel line nothing works..but with it...
[root@grpc1 helloworld]# python greeter_client.py
Greeter client received: Hello, you!
Maybe your systems work because they only have 1 interface? I need this to bind to a different interface. I want to make grpc servers that interface to client gRPC devices inside a LAN whilst providing access outside on another Ethernet interface to other services...

Do I need to modify this line to work on other interfaces?
server.add_insecure_port('[::]:50051')
maybe no square brackets...I don't know...

**Comment by nicolasnoble** [comment] 2017-06-07 21:43
I would suspect you have IPv6 issues with your machine. Try replacing the word `localhost` in the channel creation call with `127.0.0.1` first, then with `::1`. Both are technically the same thing, the former for IPv4, the latter for IPv6. The binding to `[::]:50051` means any address, IPv4 or IPv6 - that's known as a wildcard in IPv6.

Very typical processes, such as telnetd or sshd would only bind to IPv4, not IPv6, even if it's using a wildcard. Many systems that are improperly configured for IPv6 would still work fine with very typical processes because they would be IPv4 only. If you are having connection troubles such as the ones you're describing, it's very likely your system isn't properly configured with IPv6, but that gRPC is trying to use it anyway, because that's what you're telling it to do.

**Comment by pumpernickelBrad** [comment] 2017-08-11 16:07
I'm seeing the same problem as @stevec2810. Except that even if I specify the IP of any of my interfaces in the client's insecure channel I will always get the same failure to connect.

Similar scenario with RHEL 6.6, multiple interfaces and I don't want to use eth0. Has anyone had any luck debugging this?

**Comment by kpayson64** [comment] 2017-12-14 21:17
#13790 Will surface the detailed error string in Python, which should help debugging these type of network issues in the future.

**Closed by kpayson64** 2017-12-14 21:17 UTC
Labels: area/documentation, disposition/requires reporter action, lang/Python

**Comment by mspandit** [comment] 2018-03-03 15:33
We were seeing this error in our environment but were able to resolve it by unsetting the http_proxy and https_proxy environment variables:
```
$ unset http_proxy; unset https_proxy; python greeter_server.py &
$ unset http_proxy; unset https_proxy; python greeter_client.py
```

**Comment by Titanssword** [comment] 2018-03-20 13:30
I also met this problem today,  I solve this by changing `localhost` in `channel = grpc.insecure_channel('localhost:50051')` to the correct availble IP address.

**Comment by mkbennour** [comment] 2018-04-19 12:41
Hey, I have this error too 
`{ Error: 14 UNAVAILABLE: Connect Failed
    at new createStatusError (..../node_modules/grpc/src/client.js:64:15)
    at .../node_modules/grpc/src/client.js:583:15
  code: 14,
  metadata: Metadata { _internal_repr: {} },
  details: 'Connect Failed' }`
could someone help me please ?

**Comment by VimanyuAgg** [comment] 2018-05-05 01:36
The issue seems to be more frequent as the number of gRPC servers and client increases. I was able to run 6 gRPC servers and clients with no such issue, but when I increased the # of servers/clients to 12 issue occurs roughly 1 in 4 tries and when the # of servers/clients increased to 22, the issue occurs almost in every try. 

Would be happy to share any necessary/relevant info/logs.

**Comment by li-zemin** [comment] 2018-05-16 01:31
@stevec2810 Hello, I met the same problem as you. And I found that the test example provided is used to test on one device, run greeter_server.py in one terminal,run greeter_client.py in another terminal. However,  the two different terminals are belong to one device. So, the script in greeter_client.py is "channel = grpc.insecure_channel('localhost:50051')". And if you change localhost to  another device host, you can establish connect between two different devices.
Besides, I closed the ipv6 service of devices.

**Comment by iZhangZheng** [comment] 2018-07-17 06:57
If you see this error, you may check whether you have a proxy now, if so, you may fix this by stop that proxy.
That's what happened to me.

**Comment by h4x3rotab** [comment] 2018-10-14 01:31
@iZhangZheng You saved my day!

**Comment by fatichar** [comment] 2018-10-26 08:41
> I am getting the same error on my Ubuntu machine using "Hello World" example with dot net core. The difference is that there is no problem when using Insecure credentials. I get the error when I use SSL authentication. This is the code I am using https://stackoverflow.com/questions/37714558/how-to-enable-server-side-ssl-for-grpc
> 
> And getting this exception:
> 
> ```
> Grpc.Core.RpcException: Status(StatusCode=Unavailable, Detail="Connect Failed")
>    at Grpc.Core.Internal.AsyncCall`2.UnaryCall(TRequest msg) in T:\src\github\grpc\src\csharp\Grpc.Core\Internal\AsyncCall.cs:line 75
>    at Grpc.Core.DefaultCallInvoker.BlockingUnaryCall[TRequest,TResponse](Method`2 method, String host, CallOptions options, TRequest request) in T:\src\github\grpc\src\csharp\Grpc.Core\DefaultCallInvoker.cs:line 46
>    at Grpc.Core.Interceptors.InterceptingCallInvoker.<BlockingUnaryCall>b__3_0[TRequest,TResponse](TRequest req, ClientInterceptorContext`2 ctx) in T:\src\github\grpc\src\csharp\Grpc.Core\Interceptors\InterceptingCallInvoker.cs:line 51
>    at Grpc.Core.ClientBase.ClientBaseConfiguration.ClientBaseConfigurationInterceptor.BlockingUnaryCall[TRequest,TResponse](TRequest request, ClientInterceptorContext`2 context, BlockingUnaryCallContinuation`2 continuation) in T:\src\github\grpc\src\csharp\Grpc.Core\ClientBase.cs:line 174
>    at Grpc.Core.Interceptors.InterceptingCallInvoker.BlockingUnaryCall[TRequest,TResponse](Method`2 method, String host, CallOptions options, TRequest request) in T:\src\github\grpc\src\csharp\Grpc.Core\Interceptors\InterceptingCallInvoker.cs:line 48
>    at Helloworld.Greeter.GreeterClient.SayHelloAgain(HelloRequest request, CallOptions options) in /tarana/home/pravin.chaudhary/TCC/grpc/examples/csharp/Helloworld/Greeter/HelloworldGrpc.cs:line 150
>    at Helloworld.Greeter.GreeterClient.SayHelloAgain(HelloRequest request, Metadata headers, Nullable`1 deadline, CancellationToken cancellationToken) in /tarana/home/pravin.chaudhary/TCC/grpc/examples/csharp/Helloworld/Greeter/HelloworldGrpc.cs:line 146
>    at GreeterClient.Program.Main(String[] args) in /tarana/home/pravin.chaudhary/TCC/grpc/examples/csharp/Helloworld/GreeterClient/Program.cs:line 48
> ```

Fixed. Issue was that I was using IP address to connect to the server, but while creating the certificate, hostname was used.
