### ISSUE TITLE
 tests.cloud_to_prod_auth:default:javaokhttp:jwt_token_creds

### ISSUE THREAD

**Issue by ZhouyihaiDing** [grpc/grpc#12618] opened 2017-09-18 16:18 UTC
From #12495
https://grpc-testing.appspot.com/job/gRPC_interop_pull_requests/16743/testReport/
 output:
```
Gradle is no longer run automatically. Make sure to run
'./gradlew installDist -PskipCodegen=true' or
'./gradlew :grpc-interop-testing:installDist -PskipCodegen=true' after any
changes. -PskipCodegen=true is optional, but requires less setup.
[jetty-alpn-agent] Using: alpn-boot-8.1.11.v20170118.jar
Running test jwt_token_creds
[jetty-alpn-agent] Replacing: sun/security/ssl/ClientHandshaker
Sep 18, 2017 3:51:34 PM io.grpc.okhttp.internal.Platform getAndroidSecurityProvider
WARNING: Unable to find Conscrypt
[jetty-alpn-agent] Replacing: sun/security/ssl/HelloExtensions
[jetty-alpn-agent] Replacing: sun/security/ssl/ExtensionType
[jetty-alpn-agent] Replacing: sun/security/ssl/ClientHandshaker$2
[jetty-alpn-agent] Replacing: sun/security/ssl/Alerts
Exception in thread "main" io.grpc.StatusRuntimeException: UNAVAILABLE
```

**Comment by jtattermusch** [comment] 2017-11-06 15:15
Dupe of #10763.

**Closed by jtattermusch** 2017-11-06 15:15 UTC
Labels: infra/BUILDPONY
