### ISSUE TITLE
Completion queue draining blocks until all pending alarms fire.

### ISSUE THREAD

**Issue by Anomander** [grpc/grpc#16656] opened 2018-09-19 20:13 UTC
Re-creating [#16591](https://github.com/grpc/grpc/issues/16591) as I found no way to reopen it.

Current behavior requires all alarms to be tracked by the application, so that they can be cancelled manually alongside the server shutdown. Otherwise, clean shutdown is impossible, or may take a long time.

I'm looking for confirmation that it is intended behavior.

### What version of gRPC and what language are you using?
 1.13, 1.14
C++
 
### What operating system (Linux, Windows, …) and version?
Linux 
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
GCC 8.2 
 
### What did you do?
```cpp
#include <chrono>

#include <grpc/support/log.h>
#include <grpcpp/alarm.h>
#include <grpcpp/grpcpp.h>

using namespace std::chrono_literals;

int main() {
  ::grpc::ServerBuilder builder;
  builder.AddListeningPort("[::]:0", grpc::InsecureServerCredentials());
  auto          cq     = builder.AddCompletionQueue();
  auto          server = builder.BuildAndStart();
  void*         tag;
  bool          ok;
  ::grpc::Alarm alarm;
  alarm.Set(cq.get(), ::std::chrono::system_clock::now() + 5s, (void*)1);

  server->Shutdown();
  cq->Shutdown();

  GPR_ASSERT(cq->Next(&tag, &ok));
  GPR_ASSERT(ok);
  GPR_ASSERT(tag == (void*)1);

  return 0;
}
``` 
### What did you expect to see?
I expected the application to exit immediately after shutdown. I expected the pending alarm to be cancelled.
 
### What did you see instead?
The application blocked for the full duration of the alarm (5s in this case).

**Comment by ncteisen** [comment] 2018-09-19 22:02
I have reopened the original, will close this as duplicate of #16591

**Closed by ncteisen** 2018-09-19 22:02 UTC
