### ISSUE TITLE
[C++] Sync server ignores thread creation error, leads to single-threaded behavior

### ISSUE THREAD

**Issue by tudor** [grpc/grpc#20531] opened 2019-10-08 21:07 UTC
### What version of gRPC and what language are you using?

gRPC 1.20.1, C++, but the bug exists in master as well (by code inspection)

### What operating system (Linux, Windows,...) and version?

Ubuntu Linux 18.04

### What runtime / compiler are you using (e.g. python version or version of gcc)

gcc 7.3

### What did you do?

Opened many concurrent connections to sync gRPC server; thread creation failed, and the sync gRPC server does not recover from that (`num_pollers_` and `num_threads_` become incorrect) and ends up using one single thread to process all connections.

Detailed analysis below.

### What did you expect to see?

Closing the connection with `RESOURCE_EXHAUSTED` if thread creation fails.

### What did you see instead?

We had a load spike (due to what is likely a bug in our system, we ended up with 20k concurrent connections to this sync C++ server).  We were running with the default configuration, `min_pollers_ = 1`, `max_pollers_ = 2`.

The sync C++ server attempts to keep at least 1 poller thread around to handle new connections, so it spawns new threads whenever new connections arrive: https://github.com/grpc/grpc/blob/57bae312b97b2388b03fc55ebea466aeb66c8d6d/src/cpp/thread_manager/thread_manager.cc#L180

However, the `WorkerThread` constructor does not handle the case where the OS thread creation fails. `grpc_core::Thread` signals thread creation error in the `success` output parameter to the `Thread` constructor: https://github.com/grpc/grpc/blob/57bae312b97b2388b03fc55ebea466aeb66c8d6d/src/core/lib/gprpp/thd.h#L86

However the `WorkerThread` constructor doesn't pass a `success` argument: https://github.com/grpc/grpc/blob/57bae312b97b2388b03fc55ebea466aeb66c8d6d/src/cpp/thread_manager/thread_manager.cc#L34

Because thread creation failed, `num_pollers_` is now erroneously always at least 1 (the new thread never gets a chance to decrement it, as it never started), and so the check in https://github.com/grpc/grpc/blob/57bae312b97b2388b03fc55ebea466aeb66c8d6d/src/cpp/thread_manager/thread_manager.cc#L170 never fires again.

This means that the sync server never creates more threads in response to requests any more, and so uses only one thread to process requests from that moment onwards.

The fix would be to handle thread creation failure gracefully.

cc: @igorcanadi @ari-e

**Comment by vjpai** [comment] 2019-10-08 21:32
Thanks for the detailed investigation. I'll take a look at this. Do you have a code segment to repro the failure by any chance?

**Comment by tudor** [comment] 2019-10-08 21:37
No; this happened in production for us, and we haven't tried to reproduce in isolation. If it were me, I'd probably force thread creation failure (either probabilistically or with some global flag) while testing a fix for this bug.

**Comment by vjpai** [comment] 2019-10-15 16:04
Closing as duplicate of #20366

**Closed by vjpai** 2019-10-15 16:04 UTC
Labels: kind/bug, lang/c++, priority/P2
