### ISSUE TITLE
FAILED: 	bins/msan/h2_http_proxy_test max_connection_idle GRPC_POLL_STRATEGY=epoll1 

### ISSUE THREAD

**Issue by AspirinSJL** [grpc/grpc#12338] opened 2017-08-30 21:33 UTC
```
Failure
D0830 15:11:15.308272121   31788 test_config.c:388]          test slowdown factor: sanitizer=4, fixture=1, poller=1, total=4
I0830 15:11:15.315433671   31788 ev_epoll1_linux.c:92]       grpc epoll fd: 3
D0830 15:11:15.316383941   31788 ev_posix.c:111]             Using polling engine: epoll1
D0830 15:11:15.317807421   31788 dns_resolver.c:301]         Using native dns resolver
I0830 15:11:15.339125992   31788 http_proxy_fixture.c:497]   Proxy address: localhost:24218
I0830 15:11:15.361750520   31788 http_connect_handshaker.c:304] Connecting to server localhost:20787 via HTTP proxy ipv6:[::1]:24218
D0830 15:11:15.362252686   31822 http_proxy_fixture.c:341]   on_read_request_done: 0x74400001c800 "No Error"
D0830 15:11:15.368412437   31788 max_connection_idle.c:72]   client_peer_before_call=localhost:20787
E0830 15:11:35.368926260   31788 cq_verifier.c:273]          cq returned unexpected event: OP_COMPLETE: tag:0x1 OK
E0830 15:11:35.369003973   31788 cq_verifier.c:280]          expected tags:
tag(101) GRPC_OP_COMPLETE success=1 test/core/end2end/tests/max_connection_idle.c:110

I0830 15:11:35.369386044   31822 http_proxy_fixture.c:136]   HTTP proxy server read: {"created":"@1504105895.369269447","description":"Socket closed","fd":11,"file":"src/core/lib/iomgr/tcp_posix.c","file_line":285,"target_address":"ipv6:[::1]:20787"}



*******************************
Caught signal SIGABRT
bins/msan/h2_http_proxy_test(backtrace+0xa3)[0x7e000006d753]
bins/msan/h2_http_proxy_test[0x7e0001ff60d1]
bins/msan/h2_http_proxy_test[0x7e000005e599]
/lib/x86_64-linux-gnu/libpthread.so.0(+0xf8d0)[0x7f1b567a98d0]
/lib/x86_64-linux-gnu/libc.so.6(gsignal+0x37)[0x7f1b55f03067]
/lib/x86_64-linux-gnu/libc.so.6(abort+0x148)[0x7f1b55f04448]
bins/msan/h2_http_proxy_test[0x7e00003088be]
bins/msan/h2_http_proxy_test[0x7e00001fe940]
bins/msan/h2_http_proxy_test[0x7e00001faaf9]
bins/msan/h2_http_proxy_test[0x7e00001f950d]
bins/msan/h2_http_proxy_test[0x7e00000d569d]
bins/msan/h2_http_proxy_test[0x7e00000ce1d6]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf5)[0x7f1b55eefb45]
bins/msan/h2_http_proxy_test[0x7e000004b12f]
```

**Comment by dgquintas** [comment] 2017-09-24 01:33
Duplicate of #12394

**Closed by dgquintas** 2017-09-24 01:33 UTC
Labels: infra/BUILDPONY
