### ISSUE TITLE
FAILED: interop_server_python

### ISSUE THREAD

**Issue by ncteisen** [grpc/grpc#15673] opened 2018-06-07 14:32 UTC
https://source.cloud.google.com/results/invocations/44db236a-9dee-42f1-962c-f6fbab888801/targets/grpc%2Fcore%2Fpull_request%2Flinux%2Fgrpc_interop_tocloud/log

```
ERROR:root:Exception calling application: Method not implemented!
Traceback (most recent call last):
  File "/var/local/git/grpc/py27_native/local/lib/python2.7/site-packages/grpc/_server.py", line 385, in _call_behavior
    return behavior(argument, context), True
  File "/var/local/git/grpc/src/python/grpcio_tests/src/proto/grpc/testing/test_pb2_grpc.py", line 130, in UnimplementedCall
    raise NotImplementedError('Method not implemented!')
NotImplementedError: Method not implemented!
ERROR:root:Exception calling application: Method not implemented!
Traceback (most recent call last):
  File "/var/local/git/grpc/py27_native/local/lib/python2.7/site-packages/grpc/_server.py", line 385, in _call_behavior
    return behavior(argument, context), True
  File "/var/local/git/grpc/src/python/grpcio_tests/src/proto/grpc/testing/test_pb2_grpc.py", line 130, in UnimplementedCall
    raise NotImplementedError('Method not implemented!')
NotImplementedError: Method not implemented!
ERROR:root:Exception calling application: Method not implemented!
Traceback (most recent call last):
  File "/var/local/git/grpc/py27_native/local/lib/python2.7/site-packages/grpc/_server.py", line 385, in _call_behavior
    return behavior(argument, context), True
  File "/var/local/git/grpc/src/python/grpcio_tests/src/proto/grpc/testing/test_pb2_grpc.py", line 130, in UnimplementedCall
    raise NotImplementedError('Method not implemented!')
NotImplementedError: Method not implemented!
ERROR:root:Exception calling application: Method not implemented!
Traceback (most recent call last):
  File "/var/local/git/grpc/py27_native/local/lib/python2.7/site-packages/grpc/_server.py", line 385, in _call_behavior
    return behavior(argument, context), True
  File "/var/local/git/grpc/src/python/grpcio_tests/src/proto/grpc/testing/test_pb2_grpc.py", line 130, in UnimplementedCall
    raise NotImplementedError('Method not implemented!')
NotImplementedError: Method not implemented!
ERROR:root:Exception calling application: Method not implemented!
Traceback (most recent call last):
  File "/var/local/git/grpc/py27_native/local/lib/python2.7/site-packages/grpc/_server.py", line 385, in _call_behavior
    return behavior(argument, context), True
  File "/var/local/git/grpc/src/python/grpcio_tests/src/proto/grpc/testing/test_pb2_grpc.py", line 130, in UnimplementedCall
    raise NotImplementedError('Method not implemented!')
NotImplementedError: Method not implemented!
ERROR:root:Exception calling application: Method not implemented!
Traceback (most recent call last):
  File "/var/local/git/grpc/py27_native/local/lib/python2.7/site-packages/grpc/_server.py", line 385, in _call_behavior
    return behavior(argument, context), True
  File "/var/local/git/grpc/src/python/grpcio_tests/src/proto/grpc/testing/test_pb2_grpc.py", line 130, in UnimplementedCall
    raise NotImplementedError('Method not implemented!')
NotImplementedError: Method not implemented!
ERROR:root:Exception calling application: Method not implemented!
Traceback (most recent call last):
  File "/var/local/git/grpc/py27_native/local/lib/python2.7/site-packages/grpc/_server.py", line 385, in _call_behavior
    return behavior(argument, context), True
  File "/var/local/git/grpc/src/python/grpcio_tests/src/proto/grpc/testing/test_pb2_grpc.py", line 130, in UnimplementedCall
    raise NotImplementedError('Method not implemented!')
NotImplementedError: Method not implemented!
ERROR:root:Exception calling application: Method not implemented!
Traceback (most recent call last):
  File "/var/local/git/grpc/py27_native/local/lib/python2.7/site-packages/grpc/_server.py", line 385, in _call_behavior
    return behavior(argument, context), True
  File "/var/local/git/grpc/src/python/grpcio_tests/src/proto/grpc/testing/test_pb2_grpc.py", line 130, in UnimplementedCall
    raise NotImplementedError('Method not implemented!')
NotImplementedError: Method not implemented!
ERROR:root:Exception calling application: Method not implemented!
Traceback (most recent call last):
  File "/var/local/git/grpc/py27_native/local/lib/python2.7/site-packages/grpc/_server.py", line 385, in _call_behavior
    return behavior(argument, context), True
  File "/var/local/git/grpc/src/python/grpcio_tests/src/proto/grpc/testing/test_pb2_grpc.py", line 130, in UnimplementedCall
    raise NotImplementedError('Method not implemented!')
NotImplementedError: Method not implemented!
ERROR:root:Exception calling application: Method not implemented!
Traceback (most recent call last):
  File "/var/local/git/grpc/py27_native/local/lib/python2.7/site-packages/grpc/_server.py", line 385, in _call_behavior
    return behavior(argument, context), True
  File "/var/local/git/grpc/src/python/grpcio_tests/src/proto/grpc/testing/test_pb2_grpc.py", line 130, in UnimplementedCall
    raise NotImplementedError('Method not implemented!')
NotImplementedError: Method not implemented!
ERROR:root:Exception calling application: Method not implemented!
Traceback (most recent call last):
  File "/var/local/git/grpc/py27_native/local/lib/python2.7/site-packages/grpc/_server.py", line 385, in _call_behavior
    return behavior(argument, context), True
  File "/var/local/git/grpc/src/python/grpcio_tests/src/proto/grpc/testing/test_pb2_grpc.py", line 130, in UnimplementedCall
    raise NotImplementedError('Method not implemented!')
NotImplementedError: Method not implemented!
E0607 00:28:50.814074023      15 sync_posix.cc:47]           assertion failed: pthread_mutex_lock(mu) == 0
2018-06-06 17:31:57,124 FAILED: interop_server_python [ret=139, pid=7109, time=322.3sec]
Server "python" has exited prematurely.
```

**Comment by mehrdada** [comment] 2018-06-12 18:16
Closing as duplicate of https://github.com/grpc/grpc/issues/15557. 

The `NotImplementedError: Method not implemented!` messages in the log are red herring. It's a mock object that is supposed to be unimplemented raising an error for test purposes, which is expected. The actual issue seems to be

```
E0607 00:28:50.814074023      15 sync_posix.cc:47]           assertion failed: pthread_mutex_lock(mu) == 0
```

**Closed by mehrdada** 2018-06-12 18:16 UTC
Labels: infra/test env flake, kind/bug, lang/Python, priority/P2
