### ISSUE TITLE
how to get metadata in python grpc client

### ISSUE THREAD

**Issue by coconut6711** [grpc/grpc#6069] opened 2016-04-02 03:54 UTC
HI,
I am trying to write a python grpc client and get the metadata transmitted from server, how can we achieve that? And example python code?

Thanks.

**Comment by nathanielmanistaatgoogle** [comment] 2016-06-06 23:16
Closing as a duplicate of [issue 6142](https://github.com/grpc/grpc/issues/6142).

**Closed by nathanielmanistaatgoogle** 2016-06-06 23:16 UTC
Labels: python, question
