### ISSUE TITLE
grpc-server(serverA) got a memory leak when sync calling another server(serverB) with client of serverB in serverA's interface

### ISSUE THREAD

**Issue by ann-wzhao** [grpc/grpc#30799] opened 2022-08-31 01:23 UTC
### What version of gRPC and what language are you using?
try with two different versions both have memory leak:
1.  grpc version: 1.48.0-dev
     protobuf version: 3.19.4.0
2. grpc version: 1.32.0
    protobuf version: 3.13.3

c++

### What operating system (Linux, Windows,...) and version?
ubuntu20.04

### What runtime / compiler are you using (e.g. python version or version of gcc)
g++ (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0

### What did you do?
I started my sync grpc-server **serverA** . One of serverA's interfaces calls sync **greeter_server**(A demo provided by examples) by **stub**. (the code is showed as bellowed img)

When serverA's multi-clients(concurrency=800) sync calls serverA's this interface, the memory of serverA increases  constantly. And the memory of  serverA is not be released when its clients stop connect to serverA.

It seems that a memory leak occurs with serverA when serverA's clients call it concurrently. But serverA only calls **greeter_server** by **stub**. 

Contrastly,  when only one serveA's client(concurrency=1) do the same thing as the above, the memory of serverA didn't increase apparently. 

It appears that no memory leak occurs when serverA is called with one client (concurrency=1).

PS: The total number of serverA client's requests with **(concurrency=1)** and **(concurrency=800)** is equal.

So strange!

Thanks you for your answers!
![image](https://user-images.githubusercontent.com/84758182/187435448-b5da2ef8-0b4b-4db3-a4e3-0e10b0952a13.png)

### What did you expect to see?
no memory leak when a grpc-server(serverA) calls another grpc-server with high concurrency.
grpc sync server memory can be released when calling other grpc servers.

### What did you see instead?
memory leak when a grpc-server(serverA) calls another grpc-server with high concurrency.
grpc sync server memory can not be released when calling other grpc servers.

**Comment by veblush** [comment] 2022-09-13 19:43
Would you elaborate on how you noticed there was a memory leak? Seeing an increase on memory consumption doesn't necessary means that there is a leak. If you can use a memory leak detector and it reports some leaks, it would be useful.

**Comment by veblush** [comment] 2022-09-13 19:44
Duplicate of https://github.com/grpc/grpc/issues/30792

**Closed by veblush** 2022-09-13 19:44 UTC
Labels: kind/bug, lang/c++, priority/P2, disposition/requires reporter action, untriaged
