### ISSUE TITLE
Same message name in different namespaces included in the same client project results in compile error

### ISSUE THREAD

**Issue by khteh** [grpc/grpc#21238] opened 2019-11-18 07:59 UTC
### What operating system (Linux, Windows,...) and version?
Ubuntu 19.10

### What runtime / compiler are you using (e.g. .NET Core SDK version `dotnet --info`)
```
$ dn --info
.NET Core SDK (reflecting any global.json):
 Version:   3.0.100
 Commit:    04339c3a26

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  19.10
 OS Platform: Linux
 RID:         ubuntu.19.10-x64
 Base Path:   /usr/share/dotnet-3.0.100/sdk/3.0.100/

Host (useful for support):
  Version: 3.0.0
  Commit:  7d57652f33

.NET Core SDKs installed:
  3.0.100 [/usr/share/dotnet-3.0.100/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.App 3.0.0 [/usr/share/dotnet-3.0.100/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.0.0 [/usr/share/dotnet-3.0.100/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```

### What did you do?
If possible, provide a recipe for reproducing the error. Try being specific and include code snippets if helpful.
I have the same base response message NAME defined in multiple micro services but in different namespaces and packages:
```
syntax = "proto3";
option csharp_namespace = "Biz4x.Identity";
package Biz4x.Identity;
message Response {
    bool success = 1;
    repeated Error errors = 2;
}
message Error {
    string code = 1;
    string description = 2;
}
```
Including in another micro service which needs to consume multiple micro services result in compile time error:
```
/usr/share/dotnet-3.0.100/sdk/3.0.100/Roslyn/Microsoft.CSharp.Core.targets(59,5): error MSB3105: The item "obj/Debug/netcoreapp3.0//Response.cs" was specified more than once in the "Sources" parameter.  Duplicate items are not supported by the "Sources" parameter. [/usr/src/4xlabs/bz-frontend/src/Biz4x.Frontend.Client/Biz4x.Frontend.Client.csproj]
```
### What did you expect to see?
No error

### What did you see instead?

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

See [TROUBLESHOOTING.md](https://github.com/grpc/grpc-dotnet/blob/master/TROUBLESHOOTING.md) for how to diagnose problems better.

**Comment by jtattermusch** [comment] 2019-11-20 12:56
Looks like dupe of https://github.com/grpc/grpc/issues/17672?

**Comment by jtattermusch** [comment] 2019-11-20 13:00
@khteh  you're saying "I have the same base response message NAME defined in multiple micro services but in different namespaces and packages" but you only include one .proto snippet. Can you also provide other .proto files (or share a full example project). That would make reproducing the problem much easier.

**Comment by khteh** [comment] 2019-11-20 13:08
Cannot share an internal commercial project. It is not difficult to reproduce. I have the following structure in a class library project:

Protos/Service1/*.protos
Protos/Service2/*.protos

and both Service1 and Service2 use the same message structure with the same name for common purpose. However they are in different .proto namespaces and packages. For example, in another micro service I have:
```
syntax = "proto3";
option csharp_namespace = "Biz4x.Service2";
package Biz4x.Service2;
message Response {
    bool success = 1;
    repeated Error errors = 2;
}
message Error {
    string code = 1;
    string description = 2;
}
```
this is a legitimate use case as the C# code uses the same class in difference micro-service namespaces without incurring much changes to the C# code. In fact, the `Reponse` class should be a base class but GRPC does NOT support inheritance.

**Comment by khteh** [comment] 2019-11-21 07:52
https://github.com/grpc/grpc/issues/17672 helps by specifying different `OutputDir` for individual `Protos/*/*.protos` folders. Thanks.

**Comment by jtattermusch** [comment] 2020-04-28 15:36
Closing as duplicate of #17672.

**Closed by jtattermusch** 2020-04-28 15:36 UTC
Labels: kind/bug, lang/C#, priority/P2
