### ISSUE TITLE
java-csharp interop failed with INTERNAL: Connection closed with unknown cause

### ISSUE THREAD

**Issue by yang-g** [grpc/grpc#9762] opened 2017-02-17 17:17 UTC
https://grpc-testing.appspot.com/job/gRPC_interop_pull_requests/11469/testReport/junit/(root)/tests/cloud_to_cloud_java_csharpcoreclr_server_custom_metadata/

```
Feb 17, 2017 7:48:10 AM io.netty.util.internal.MacAddressUtil defaultMachineId
WARNING: Failed to find a usable hardware address from the network interfaces; using random bytes: 05:48:18:20:6f:30:58:f0
Exception in thread "main" io.grpc.StatusRuntimeException: INTERNAL: Connection closed with unknown cause
	at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:227)
	at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:208)
	at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:141)
	at io.grpc.testing.integration.TestServiceGrpc$TestServiceBlockingStub.unaryCall(TestServiceGrpc.java:408)
	at io.grpc.testing.integration.AbstractInteropTest.customMetadata(AbstractInteropTest.java:962)
	at io.grpc.testing.integration.TestServiceClient.runTest(TestServiceClient.java:264)
	at io.grpc.testing.integration.TestServiceClient.run(TestServiceClient.java:197)
	at io.grpc.testing.integration.TestServiceClient.main(TestServiceClient.java:81)
Shutting down
```

Maybe a java issue? @ejona86

**Comment by ejona86** [comment] 2017-02-23 23:57
It seems a Java <> C# interaction issue. The Java side doesn't know what went wrong. And the C# side doesn't log anything (it is the only server that logs nothing). It seems the C# side should look into it. I looked at the Java side and didn't see anything recent that could have caused this.

**Comment by yang-g** [comment] 2017-02-23 23:58
Thanks Eric for looking.
Re-assigning to Jan.

**Comment by jtattermusch** [comment] 2017-02-27 11:42
Very similar issue to: 
- https://github.com/grpc/grpc/issues/9865 (ruby)
- https://github.com/grpc/grpc/issues/9878 (node)
- https://github.com/grpc/grpc/issues/9797 (php)

That seems to indicate it's an Java vs C core issue (rather than wrapped lang specific).

**Comment by jtattermusch** [comment] 2017-02-28 12:43
My debugging has lead to conclusion that C core doesn't deliver the request message, and that's why the interop tests fails:
https://github.com/grpc/grpc/blob/cd232f64c634cba1e95b30db5d270114db6b1fc4/src/csharp/Grpc.Core/Internal/ServerCallHandler.cs#L82 - in a unary call, reading one request message is expected.

It happens in about 50% of cases. It also seems that if only happens across a secure secure.

**Comment by jtattermusch** [comment] 2017-02-28 13:20
Also, in serverside logs (GRPC_VERBOSITY=debug, GRPC_TRACE=all), I see lots of instances of 
`E0228 14:18:02.422869 139793523537664 src/core/lib/http/parser.c:287: HTTP client max line length (4096) exceeded`

**Comment by dgquintas** [comment] 2017-02-28 22:47
@ejona86 would you know what kind of large metadata Java may be sending?
@jtattermusch the traces should be showing you the value of the incoming metadata (ie, those offending too-long headers). Do you see anything there? it's surprising this is only an issue for C# but not other C Core-based languages.

**Comment by jtattermusch** [comment] 2017-03-01 07:59
@dgquintas   no, it's not an issue just for C#,   we definitely see the same problem for PHP: https://github.com/grpc/grpc/issues/9797. 
I also guess that #9865 (ruby) #9878 (node) will have similar root cause.

**Comment by jtattermusch** [comment] 2017-03-01 13:44
Here's the log from C# server with `GRPC_TRACE=http,http1,tcp,secure_endpoint,transport_security` https://gist.github.com/anonymous/bb08ca5796e7268d812a2a5fbb262361

**Comment by jtattermusch** [comment] 2017-03-01 14:05
From the log it looks like that parsing of headers themselves is fine, but something odd happens when parsing the payload (according to the spec, should be a protobuf message containing 271828 bytes of zeros).

**Comment by apolcyn** [comment] 2017-03-02 04:42
seen again https://grpc-testing.appspot.com/job/gRPC_interop_pull_requests/11728/testReport/junit/(root)/tests/cloud_to_cloud_java_csharpcoreclr_server_custom_metadata/

pr https://github.com/grpc/grpc/pull/9894

**Comment by apolcyn** [comment] 2017-03-10 03:02
seen again in https://grpc-testing.appspot.com/job/gRPC_interop_pull_requests/12021/testReport/junit/(root)/tests/cloud_to_cloud_java_csharp_server_large_unary/ 
pr: https://github.com/grpc/grpc/pull/10076 against v1.2.x

**Comment by jtattermusch** [comment] 2017-03-10 07:50
Fixed in #10073.

**Closed** 2017-03-10 07:50 UTC
Labels: BUILDPONY, interop

**Comment by apolcyn** [comment] 2017-03-10 18:31
I think this will still be happening in against v1.2.x..

pr: https://github.com/grpc/grpc/pull/9986 runs into it, log in https://grpc-testing.appspot.com/job/gRPC_interop_pull_requests/12040/testReport/junit/(root)/tests/cloud_to_cloud_java_csharpcoreclr_server_custom_metadata/

**Comment by jtattermusch** [comment] 2017-03-13 14:30
@apolcyn, are you 100% sure that you had https://github.com/grpc/grpc/pull/10073 in your tree when this issue happened? If so, it would mean #10073 doesn't fix this fully. Please double check.

**Comment by apolcyn** [comment] 2017-03-13 16:06
It just looks like #10073 didn't make it into `v1.2.x`. I think #10073 makes the fix on master, but it doesn't look like it's in the `v1.2.x` branch history - so just expecting `v1.2.x` pr's to still run into it.

**Comment by jtattermusch** [comment] 2017-03-13 18:43
No, I am pretty sure it's there: 

git checkout upstream/v1.2.x

```
commit 072c5af838aa9b6bcb98dbf4dd969708ba794152
Author: Craig Tiller <ctiller@google.com>
Date:   Thu Mar 9 10:25:04 2017 -0800

    Write an essay
```

Have you seen the failure anyway?

**Comment by apolcyn** [comment] 2017-03-13 18:58
sorry about that, I was searching for the same commit hashes in v1.2.x and master branches, which differ.

I've since rebased the pr which I saw this failure in and #10073 is indeed in the branch history, so I think my comment above is incorrect.

**Comment by pvox** [comment] 2017-10-03 11:02
I'm getting the StatusRuntimeException even before max connection age is reached. Provided max connection age is 5min.
StatusRuntimeException : Status{code=INTERNAL, description=Connection closed with unknown cause, cause=null}

P.S. Written server and client in JAVA. Added thread sleep of 1sec and sending 8 messages per channel. Channel count is 2.

**Comment by ejona86** [comment] 2017-10-05 17:01
@pvox, this issue was for our interop tests and so your issue is different. For a user problem please send an email to grpc-io@googlegroups.com (preferred) or create an issue on https://github.com/grpc/grpc-java. Include the versions being used and logs and explain when you experience the error.
