### ISSUE TITLE
[FLAKE] build_docker_java Gradle download failure

### ISSUE THREAD

**Issue by lidizheng** [grpc/grpc#22875] opened 2020-05-05 22:33 UTC
```
+ CONTAINER_NAME=build_grpc_interop_java_0a28bb59-6202-42f1-b5a6-da4a10749560
+ docker run --cap-add SYS_PTRACE -e 'THIS_IS_REALLY_NEEDED=see https://github.com/docker/docker/issues/14203 for why docker is awful' -e 'THIS_IS_REALLY_NEEDED_ONCE_AGAIN=For issue 4835. See https://github.com/docker/docker/issues/14203 for why docker is awful' -i -v /tmpfs/src/github/grpc:/var/local/jenkins/grpc:ro -v /tmpfs/src/github/grpc-java:/var/local/jenkins/grpc-java:ro -v /tmpfs/src/github/grpc-go:/var/local/jenkins/grpc-go:ro -v /tmpfs/src/github/grpc-dart:/var/local/jenkins/grpc-dart:ro -v /tmpfs/src/github/grpc-node:/var/local/jenkins/grpc-node:ro -v /tmpfs/src/github/grpc-dotnet:/var/local/jenkins/grpc-dotnet:ro -v /home/kbuilder/service_account:/var/local/jenkins/service_account:ro --name=build_grpc_interop_java_0a28bb59-6202-42f1-b5a6-da4a10749560 grpctesting/grpc_interop_java:c0dc2dddbb3c7b62b4b8e059571c5181af5bcc0f bash -l /var/local/jenkins/grpc/tools/dockerfile/interoptest/grpc_interop_java/build_interop.sh
stdin: is not a tty
/tmp/grpc-java /
Downloading https://services.gradle.org/distributions/gradle-5.6.2-bin.zip
.........................................................................................

Welcome to Gradle 5.6.2!

Here are the highlights of this release:
 - Incremental Groovy compilation
 - Groovy compile avoidance
 - Test fixtures for Java projects
 - Manage plugin versions via settings script

For more details see https://docs.gradle.org/5.6.2/release-notes.html

*** Skipping the build of codegen and compilation of proto files because skipCodegen=true
  * Skipping the build of Android projects because skipAndroid=true

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':grpc-xds:shadowJar'.
> Could not resolve all files for configuration ':grpc-xds:runtimeClasspath'.
   > Could not download opencensus-proto.jar (io.opencensus:opencensus-proto:0.2.0)
      > Could not get resource 'https://maven-central.storage-download.googleapis.com/repos/central/data/io/opencensus/opencensus-proto/0.2.0/opencensus-proto-0.2.0.jar'.
         > Connection reset

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1m 11s
```

https://source.cloud.google.com/results/invocations/677239c7-6ed7-4288-9fc9-ec36541720e3/targets/github%2Fgrpc%2Finterop_docker_build/tests;group=tests;test=build_docker_java;row=1

**Comment by markdroth** [comment] 2020-05-05 22:47
Duplicate of #13379.

**Closed by markdroth** 2020-05-05 22:47 UTC
Labels: disposition/BUILDCOP, kind/bug, lang/Java, priority/P2

**Comment by lidizheng** [comment] 2020-05-05 23:20
(#13379 is caused by name resolution failure, this one is caused by connection reset.)

**Comment by markdroth** [comment] 2020-05-06 15:01
I'm not sure why that matters.  They are both the same underlying problem, which is that the build has external dependencies.
