### ISSUE TITLE
grpc unity iOS: crash at Grpc.Core.Internal.PlatformApis.GetUnityRuntimePlatform on start up

### ISSUE THREAD

**Issue by umegaya** [grpc/grpc#19262] opened 2019-06-06 01:07 UTC
### What version of gRPC and what language are you using?
grpc_unity_package.1.22.0-dev.zip from daily build page.
 
### What operating system (Linux, Windows,...) and version?
osx 10.14.4 
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
 Unity 2018.4.0f1
 
### What did you do?

https://github.com/umegaya/mobile-game-http-latency-test/blob/master/client/Assets/Scripts/PingRunner.cs#L94

basically just try to invoke simple unary async call. note that android build from same codes run without any error. 
 
### What did you expect to see?
ios build can invoke unary call without error, as android version can. 
 
### What did you see instead?
error on creating channel object.
 
```
NullReferenceException: Object reference not set to an instance of an object.
  at Grpc.Core.Internal.PlatformApis.GetUnityRuntimePlatform () [0x00000] in <00000000000000000000000000000000>:0 
  at Grpc.Core.Internal.NativeExtension.LoadNativeMethodsUnity () [0x00000] in <00000000000000000000000000000000>:0 
  at Grpc.Core.Internal.NativeExtension..ctor () [0x00000] in <00000000000000000000000000000000>:0 
  at Grpc.Core.Internal.NativeExtension.Get () [0x00000] in <00000000000000000000000000000000>:0 
  at Grpc.Core.Internal.NativeMethods.Get () [0x00000] in <00000000000000000000000000000000>:0 
  at Grpc.Core.GrpcEnvironment.GrpcNativeInit () [0x00000] in <00000000000000000000000000000000>:0 
  at Grpc.Core.GrpcEnvironment..ctor () [0x00000] in <00000000000000000000000000000000>:0 
  at Grpc.Core.GrpcEnvironment.AddRef () [0x00000] in <00000000000000000000000000000000>:0 
  at Grpc.Core.Channel..ctor (System.String target, Grpc.Core.ChannelCredentials credentials, System.Collections.Generic.IEnumerable`1[T] options) [0x00000] in <00000000000000000000000000000000>:0 
  at LatencyResearch.GrpcPing..ctor (System.String domain, System.String iaas) [0x00000] in <00000000000000000000000000000000>:0 
  at LatencyResearch.Measure+<Exec>d__4.MoveNext () [0x00000] in <00000000000000000000000000000000>:0 
  at UnityEngine.SetupCoroutine.InvokeMoveNext (System.Collections.IEnumerator enumerator, System.IntPtr returnValueAddress) [0x00000] in <00000000000000000000000000000000>:0 
```
 
### Anything else we should know about your project / environment?
- I try `.Net standard 2.0` and `.Net 4.x` for Api Compatibility Level, but both crashed same place
- [TROUBLESHOOTING.md](https://github.com/grpc/grpc/blob/master/TROUBLESHOOTING.md) does not works because error is happen before entering code c library.

**Comment by jtattermusch** [comment] 2019-06-24 13:57
This seems to be what's crashing:
https://github.com/grpc/grpc/blob/2780136fcf9bd268aaddea74b115fbc2faa97c61/src/csharp/Grpc.Core/Internal/PlatformApis.cs#L171

I'm wondering why, the `UnityEngine.Application.platform` is not really something that could be missing in a working unity application.
https://docs.unity3d.com/ScriptReference/Application-platform.html

**Comment by blunoob** [comment] 2019-12-22 11:25
I am still getting the same error on Unity 2019.2.6f1 when building for android with il2cpp. Is there any chance that the problem is not there in MagicOnion library?

I/Unity:    >> e.Message >> Object reference not set to an instance of an object.   
Exception :   at Grpc.Core.Internal.PlatformApis.GetUnityRuntimePlatform () [0x00000] in <00000000000000000000000000000000>:0 
      at Grpc.Core.Internal.NativeExtension.LoadNativeMethodsUnity () [0x00000] in <00000000000000000000000000000000>:0 
      at Grpc.Core.Internal.NativeExtension..ctor () [0x00000] in <00000000000000000000000000000000>:0 
      at Grpc.Core.Internal.NativeExtension.Get () [0x00000] in <00000000000000000000000000000000>:0 
      at Grpc.Core.Internal.NativeMethods.Get () [0x00000] in <00000000000000000000000000000000>:0 
      at Grpc.Core.GrpcEnvironment.GrpcNativeInit () [0x00000] in <00000000000000000000000000000000>:0 
      at Grpc.Core.GrpcEnvironment..ctor () [0x00000] in <00000000000000000000000000000000>:0 
      at Grpc.Core.GrpcEnvironment.AddRef () [0x00000] in <00000000000000000000000000000000>:0 
      at Grpc.Core.Channel..ctor (System.String target, Grpc.Core.ChannelCredentials credentials, System.Collections.Generic.IEnume

**Comment by blunoob** [comment] 2019-12-29 14:26
The error is now gone. Looks like its fixed in the grpc daily build from yesterday.

**Comment by ogswr** [comment] 2019-12-30 12:00
That's good to hear.

**Comment by bitplex** [comment] 2020-05-07 03:08
It's seems to IL2CPP-ByteCodeStripping.

# add file: /Assets/link.xml

<linker>
    <assembly fullname="UnityEngine">
        <type fullname="UnityEngine.Application" preserve="filelds">
            <property name="platform"/>
        </type>
    </assembly>
</linker>

**Comment by jtattermusch** [comment] 2020-05-11 13:56
Looks like the workaround https://github.com/grpc/grpc/issues/19262#issuecomment-625003117 has been confirmed and this also doesn't seem to be an issue in the grpc code. Closing.

**Closed by jtattermusch** 2020-05-11 13:56 UTC
Labels: kind/bug, lang/C#, platform/macOS, priority/P2
