### ISSUE TITLE
stream disconnect with error recvmsg:Connection reset by peer

### ISSUE THREAD

**Issue by Hundred-Killer** [grpc/grpc#36043] opened 2024-03-03 11:14 UTC
### What version of gRPC and what language are you using?
python - client
golang - server

grpcio==1.60.0
grpcio-tools==1.60.0
google.golang.org/grpc v1.60.0
google.golang.org/protobuf v1.32.0

### What operating system (Linux, Windows,...) and version?
Linux Ubuntu 22.04.4 LTS (GNU/Linux 5.15.0-97-generic x86_64)

### What runtime / compiler are you using (e.g. python version or version of gcc)
python:3.9-alpine
golang:1.22

### What did you do?
Hello, I had a task to make stable streaming of data from the server to the client, but sometimes for unknown reasons the network breaks.

I have searched the entire Internet but have not found an answer to my question. I use python for the client, and golang for the server. In the beginning, I used load balancers (envoy, haproxy, nginx), I thought that the problem was in them, but after I started using docker dns, the problem continued. I also thought that there was a problem with the network, writing to their support they said that everything was fine.

I have been trying to fix this problem for about a month and all without success, please help.

### What did you expect to see?
stable streaming

### What did you see instead?

```
D0303 10:35:28.703454877      74 call.cc:1050]                         set_final_status CLI UNKNOWN:Error received from peer ipv4:10.0.3.8:5061 {created_time:"2024-03-03T10:35:28.70331282+00:00", grpc_status:14, grpc_message:"recvmsg:Connection reset by peer"}
I0303 10:35:28.703537652      74 connectivity_state.cc:158]            ConnectivityStateTracker client_transport[0x7f78f24dc370]: READY -> SHUTDOWN (close_transport, OK)
I0303 10:35:28.703547860      74 connectivity_state.cc:166]            ConnectivityStateTracker client_transport[0x7f78f24dc370]: notifying watcher 0x7f78f245e260: READY -> SHUTDOWN
I0303 10:35:28.703562488      74 connectivity_state.cc:78]             watcher 0x7f78f245e260: delivering async notification for SHUTDOWN (OK)
I0303 10:35:28.703578859      74 pick_first.cc:656]                    [PF 0x7f78f24332f0] subchannel list 0x7f78f7693510 index 0 of 1 (subchannel 0x7f78f771d250): connectivity changed: old_state=READY, new_state=IDLE, status=OK, shutting_down=0, pending_watcher=0x7f78f23d7180, seen_transient_failure=0, p->selected_=0x7f78f20d3890, p->subchannel_list_=0x7f78f7693510, p->latest_pending_subchannel_list_=0
I0303 10:35:28.703584870      74 pick_first.cc:685]                    Pick First 0x7f78f24332f0 selected subchannel connectivity changed to IDLE
I0303 10:35:28.703645655      74 pick_first.cc:1106]                   [PF 0x7f78f24332f0] Shutting down subchannel_list 0x7f78f7693510
I0303 10:35:28.703656174      74 pick_first.cc:639]                    [PF 0x7f78f24332f0] subchannel list 0x7f78f7693510 index 0 of 1 (subchannel 0x7f78f771d250): cancelling watch and unreffing subchannel
I0303 10:35:28.703663959      74 connectivity_state.cc:181]            ConnectivityStateTracker client_channel[0x7f78f2325d00]: get current state: READY
I0303 10:35:28.703669760      74 connectivity_state.cc:158]            ConnectivityStateTracker client_channel[0x7f78f2325d00]: READY -> IDLE (helper, OK)
I0303 10:35:28.703677074      74 pick_first.cc:1099]                   [PF 0x7f78f24332f0] Destroying subchannel_list 0x7f78f7693510
I0303 10:35:28.703714324      74 pick_first.cc:486]                    Pick First 0x7f78f24332f0 received update with 1 addresses
--- Logging error ---
Traceback (most recent call last):
  File "/app/.../.../....py", line 376, in startStreamingClient
    async for response in stub.NoneStreaming(input_data):
  File "/usr/local/lib/python3.9/site-packages/grpc/aio/_call.py", line 356, in _fetch_stream_responses
    await self._raise_for_status()
  File "/usr/local/lib/python3.9/site-packages/grpc/aio/_call.py", line 263, in _raise_for_status
    raise _create_rpc_error(
grpc.aio._call.AioRpcError: <AioRpcError of RPC that terminated with:
        status = StatusCode.UNAVAILABLE
        details = "recvmsg:Connection reset by peer"
        debug_error_string = "UNKNOWN:Error received from peer ipv4:10.0.3.8:5061 {created_time:"2024-03-03T10:35:28.70331282+00:00", grpc_status:14, grpc_message:"recvmsg:Connection reset by peer"}"
>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/logging/__init__.py", line 1083, in emit
    msg = self.format(record)
  File "/usr/local/lib/python3.9/logging/__init__.py", line 927, in format
    return fmt.format(record)
  File "/usr/local/lib/python3.9/logging/__init__.py", line 663, in format
    record.message = record.getMessage()
  File "/usr/local/lib/python3.9/logging/__init__.py", line 367, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/app/main.py", line 23, in <module>
    asyncio.run(main())
  File "/usr/local/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 634, in run_until_complete
    self.run_forever()
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 601, in run_forever
    self._run_once()
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 1905, in _run_once
    handle._run()
  File "/usr/local/lib/python3.9/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/local/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py", line 309, in _process_update
    response = await self.feed_update(bot, update, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py", line 158, in feed_update
    response = await self.update.wrap_outer_middleware(
  File "/usr/local/lib/python3.9/site-packages/aiogram/dispatcher/middlewares/error.py", line 25, in __call__
    return await handler(event, data)
  File "/usr/local/lib/python3.9/site-packages/aiogram/dispatcher/middlewares/user_context.py", line 27, in __call__
    return await handler(event, data)
  File "/usr/local/lib/python3.9/site-packages/aiogram/fsm/middleware.py", line 41, in __call__
    return await handler(event, data)
  File "/usr/local/lib/python3.9/site-packages/aiogram/dispatcher/event/telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
  File "/usr/local/lib/python3.9/site-packages/aiogram/dispatcher/event/handler.py", line 43, in call
    return await wrapped()
  File "/usr/local/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py", line 276, in _listen_update
    return await self.propagate_event(update_type=update_type, event=event, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/aiogram/dispatcher/router.py", line 128, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
  File "/usr/local/lib/python3.9/site-packages/aiogram/dispatcher/router.py", line 123, in _wrapped
    return await self._propagate_event(
  File "/usr/local/lib/python3.9/site-packages/aiogram/dispatcher/router.py", line 148, in _propagate_event
    response = await observer.trigger(event, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/aiogram/dispatcher/event/telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
  File "/usr/local/lib/python3.9/site-packages/aiogram/dispatcher/event/handler.py", line 43, in call
    return await wrapped()
  File "/app/handlers/user_handler.py", line 219, in callback
    await startStreaming(last_json, callback, datetime.now(), "no")
  File "/app/.../.../..._....py", line 331, in start_streaming
    await startStreamingClient(data, params, user_settings, start_time, callback)
  File "/app/.../../..._....py", line 395, in startStreamingClient
    await error_handler(callback=callback, error_message="error.", error_time=str(start_time.strftime("%d.%m.%Y, %H:%M:%S")), error_exeptions="error", stop=True)
  File "/app/handlers/errors_handler.py", line 16, in error_handler
    logging.error("ERROR:", error_exeptions)
Message: 'ERROR:'
Arguments: ('error',)
```

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

See [TROUBLESHOOTING.md](https://github.com/grpc/grpc/blob/master/TROUBLESHOOTING.md) for how to diagnose problems better.

**Comment by 10-Kirito** [comment] 2024-03-06 11:10
Hi, I also encountered this problem recently. My reason was that I turned on the proxy. When I turned off the proxy, everything worked well!

**Comment by Hundred-Killer** [comment] 2024-03-06 11:11
> Hi, I also encountered this problem recently. My reason was that I turned on the proxy. When I turned off the proxy, everything worked well!

What kind of proxy?

**Comment by Hundred-Killer** [comment] 2024-03-06 12:03
@10-Kirito  I still get this error

```
options = [
     ('grpc.enable_http_proxy', 0),
]
```

**Comment by 10-Kirito** [comment] 2024-03-07 01:27
@Hundred-Killer  When I run the helloworld example in grpc(https://github.com/grpc/grpc/tree/master/examples/cpp/helloworld), it will display the follow error:

This is the server test:
![image](https://github.com/grpc/grpc/assets/101441382/5cb7b1ba-fab0-4f0e-bd58-694617dcc926)

Then when I run the client, it will occurs the same error to you:
![image](https://github.com/grpc/grpc/assets/101441382/3b598ab1-8523-4be7-ba3b-ef2adcde5b19)

![image](https://github.com/grpc/grpc/assets/101441382/aeb50335-1c11-47e7-85da-5242ea7cbe7f)

The reason just is that I set the proxy, and I unset the proxy, then it will work well:

![image](https://github.com/grpc/grpc/assets/101441382/cc9a241c-7179-4557-9e7b-07d103caf227)

So I guess you have a similar problem to me. You can check your system proxy in your OS.

**Comment by Hundred-Killer** [comment] 2024-03-07 11:43
@10-Kirito I am running the client in a Docker container, but I checked through printenv anyway, http_proxy and https_proxy were not found in the container

**Comment by gnossen** [comment] 2024-03-15 22:45
From the client side, this seems pretty cut and dry. The TCP connection was terminated: `recvmsg:Connection reset by peer`. That could be caused by several different things, several of which you mentioned already checking. One is the server. If the server unexpectedly died, you might expect to see an error like this. Another possibility is any local firewall rules you have set up in the kernel.

**Comment by Hundred-Killer** [comment] 2024-03-16 11:32
@gnossen Tech support says that everything is fine with the servers. I didn't touch the firewall rules.

**Comment by Hundred-Killer** [comment] 2024-03-24 08:31
problem is still not solved

**Comment by Hundred-Killer** [comment] 2024-03-29 12:51
Will using secure channel help?

**Comment by XuanWang-Amos** [comment] 2024-04-01 23:18
Closing this for now since we don't have much to work on, feel free to reopen if you have a reproduction case.

**Closed by XuanWang-Amos** 2024-04-01 23:18 UTC
Labels: kind/bug, lang/Python, priority/P2

**Comment by fighterhit** [comment] 2024-09-06 02:51
We also encountered this problem in the k8s cluster. This error occasionally occurred when using the **Cluster IP Service** to connect to the grpc server, but it almost never occurred when using the **Headless Service**, that is, directly connecting to the Pod IP.

**Comment by Caeoon-Kaihong** [comment] 2025-05-12 03:46
I had the same problem, but because my GRPC server crashed. But I don't understand why there is a null pointer crash error.
