### ISSUE TITLE
Prebuilt gems doesn't work under Alpine Linux

### ISSUE THREAD

**Issue by x-yuri** [grpc/grpc#25711] opened 2021-03-13 03:04 UTC
### What version of gRPC and what language are you using?
1.36.0, Ruby

### What operating system (Linux, Windows,...) and version?
Alpine Linux

### What runtime / compiler are you using (e.g. python version or version of gcc)
Ruby 2.7.2

### What did you do?
`a.sh`:

```sh
#!/bin/sh -eux
gem install grpc
for f in `find /usr/local/bundle/gems -name "*.so"`; do
    ldd "$f" || true
done
```

```
$ chmod u+x a.sh
$ docker run --rm -itv $PWD/a.sh:/a.sh ruby:2.7.2-alpine ./a.sh
...
+ ldd /usr/local/bundle/gems/grpc-1.36.0-x86_64-linux/src/ruby/lib/grpc/2.7/grpc_c.so
	/lib/ld-musl-x86_64.so.1 (0x7f1fcc320000)
	libm.so.6 => /lib/ld-musl-x86_64.so.1 (0x7f1fcc320000)
	libc.so.6 => /lib/ld-musl-x86_64.so.1 (0x7f1fcc320000)
Error loading shared library ld-linux-x86-64.so.2: No such file or directory (needed by /usr/local/bundle/gems/grpc-1.36.0-x86_64-linux/src/ruby/lib/grpc/2.7/grpc_c.so)
Error relocating /usr/local/bundle/gems/grpc-1.36.0-x86_64-linux/src/ruby/lib/grpc/2.7/grpc_c.so: rb_ivar_set: symbol not found
Error relocating /usr/local/bundle/gems/grpc-1.36.0-x86_64-linux/src/ruby/lib/grpc/2.7/grpc_c.so: rb_check_typeddata: symbol not found
Error relocating /usr/local/bundle/gems/grpc-1.36.0-x86_64-linux/src/ruby/lib/grpc/2.7/grpc_c.so: rb_struct_aref: symbol not found
Error relocating /usr/local/bundle/gems/grpc-1.36.0-x86_64-linux/src/ruby/lib/grpc/2.7/grpc_c.so: rb_const_get: symbol not found
Error relocating /usr/local/bundle/gems/grpc-1.36.0-x86_64-linux/src/ruby/lib/grpc/2.7/grpc_c.so: rb_struct_define: symbol not found
Error relocating /usr/local/bundle/gems/grpc-1.36.0-x86_64-linux/src/ruby/lib/grpc/2.7/grpc_c.so: rb_define_class_under: symbol not found
Error relocating /usr/local/bundle/gems/grpc-1.36.0-x86_64-linux/src/ruby/lib/grpc/2.7/grpc_c.so: rb_sym2id: symbol not found
Error relocating /usr/local/bundle/gems/grpc-1.36.0-x86_64-linux/src/ruby/lib/grpc/2.7/grpc_c.so: __strftime_l: symbol not found
Error relocating /usr/local/bundle/gems/grpc-1.36.0-x86_64-linux/src/ruby/lib/grpc/2.7/grpc_c.so: rb_hash_aref: symbol not found
Error relocating /usr/local/bundle/gems/grpc-1.36.0-x86_64-linux/src/ruby/lib/grpc/2.7/grpc_c.so: rb_protect: symbol not found
Error relocating /usr/local/bundle/gems/grpc-1.36.0-x86_64-linux/src/ruby/lib/grpc/2.7/grpc_c.so: rb_str_new_static: symbol not found
Error relocating /usr/local/bundle/gems/grpc-1.36.0-x86_64-linux/src/ruby/lib/grpc/2.7/grpc_c.so: rb_hash_aset: symbol not found
Error relocating /usr/local/bundle/gems/grpc-1.36.0-x86_64-linux/src/ruby/lib/grpc/2.7/grpc_c.so: rb_obj_freeze: symbol not found
Error relocating /usr/local/bundle/gems/grpc-1.36.0-x86_64-linux/src/ruby/lib/grpc/2.7/grpc_c.so: rb_id2name: symbol not found
Error relocating /usr/local/bundle/gems/grpc-1.36.0-x86_64-linux/src/ruby/lib/grpc/2.7/grpc_c.so: rb_fix2int: symbol not found
Error relocating /usr/local/bundle/gems/grpc-1.36.0-x86_64-linux/src/ruby/lib/grpc/2.7/grpc_c.so: rb_str_new: symbol not found
Error relocating /usr/local/bundle/gems/grpc-1.36.0-x86_64-linux/src/ruby/lib/grpc/2.7/grpc_c.so: rb_define_class: symbol not found
Error relocating /usr/local/bundle/gems/grpc-1.36.0-x86_64-linux/src/ruby/lib/grpc/2.7/grpc_c.so: rb_struct_new: symbol not found
Error relocating /usr/local/bundle/gems/grpc-1.36.0-x86_64-linux/src/ruby/lib/grpc/2.7/grpc_c.so: rb_rescue: symbol not found
Error relocating /usr/local/bundle/gems/grpc-1.36.0-x86_64-linux/src/ruby/lib/grpc/2.7/grpc_c.so: __strdup: symbol not found
Error relocating /usr/local/bundle/gems/grpc-1.36.0-x86_64-linux/src/ruby/lib/grpc/2.7/grpc_c.so: rb_thread_call_without_gvl: symbol not found
Error relocating /usr/local/bundle/gems/grpc-1.36.0-x86_64-linux/src/ruby/lib/grpc/2.7/grpc_c.so: rb_float_value: symbol not found
Error relocating /usr/local/bundle/gems/grpc-1.36.0-x86_64-linux/src/ruby/lib/grpc/2.7/grpc_c.so: rb_hash_foreach: symbol not found
Error relocating /usr/local/bundle/gems/grpc-1.36.0-x86_64-linux/src/ruby/lib/grpc/2.7/grpc_c.so: rb_hash_new: symbol not found
Error relocating /usr/local/bundle/gems/grpc-1.36.0-x86_64-linux/src/ruby/lib/grpc/2.7/grpc_c.so: rb_define_module: symbol not found
Error relocating /usr/local/bundle/gems/grpc-1.36.0-x86_64-linux/src/ruby/lib/grpc/2.7/grpc_c.so: rb_string_value_ptr: symbol not found
Error relocating /usr/local/bundle/gems/grpc-1.36.0-x86_64-linux/src/ruby/lib/grpc/2.7/grpc_c.so: rb_string_value_cstr: symbol not found
Error relocating /usr/local/bundle/gems/grpc-1.36.0-x86_64-linux/src/ruby/lib/grpc/2.7/grpc_c.so: rb_mutex_lock: symbol not found
Error relocating /usr/local/bundle/gems/grpc-1.36.0-x86_64-linux/src/ruby/lib/grpc/2.7/grpc_c.so: rb_num2uint: symbol not found
Error relocating /usr/local/bundle/gems/grpc-1.36.0-x86_64-linux/src/ruby/lib/grpc/2.7/grpc_c.so: rb_error_arity: symbol not found
Error relocating /usr/local/bundle/gems/grpc-1.36.0-x86_64-linux/src/ruby/lib/grpc/2.7/grpc_c.so: rb_intern2: symbol not found
Error relocating /usr/local/bundle/gems/grpc-1.36.0-x86_64-linux/src/ruby/lib/grpc/2.7/grpc_c.so: rb_str_cat: symbol not found
Error relocating /usr/local/bundle/gems/grpc-1.36.0-x86_64-linux/src/ruby/lib/grpc/2.7/grpc_c.so: rb_num2int: symbol not found
Error relocating /usr/local/bundle/gems/grpc-1.36.0-x86_64-linux/src/ruby/lib/grpc/2.7/grpc_c.so: rb_str_new_cstr: symbol not found
Error relocating /usr/local/bundle/gems/grpc-1.36.0-x86_64-linux/src/ruby/lib/grpc/2.7/grpc_c.so: ruby_xmalloc: symbol not found
Error relocating /usr/local/bundle/gems/grpc-1.36.0-x86_64-linux/src/ruby/lib/grpc/2.7/grpc_c.so: rb_obj_is_proc: symbol not found
Error relocating /usr/local/bundle/gems/grpc-1.36.0-x86_64-linux/src/ruby/lib/grpc/2.7/grpc_c.so: rb_obj_classname: symbol not found
Error relocating /usr/local/bundle/gems/grpc-1.36.0-x86_64-linux/src/ruby/lib/grpc/2.7/grpc_c.so: rb_funcallv: symbol not found
Error relocating /usr/local/bundle/gems/grpc-1.36.0-x86_64-linux/src/ruby/lib/grpc/2.7/grpc_c.so: rb_global_variable: symbol not found
Error relocating /usr/local/bundle/gems/grpc-1.36.0-x86_64-linux/src/ruby/lib/grpc/2.7/grpc_c.so: rb_define_alias: symbol not found
Error relocating /usr/local/bundle/gems/grpc-1.36.0-x86_64-linux/src/ruby/lib/grpc/2.7/grpc_c.so: rb_num2long: symbol not found
Error relocating /usr/local/bundle/gems/grpc-1.36.0-x86_64-linux/src/ruby/lib/grpc/2.7/grpc_c.so: rb_ary_new: symbol not found
Error relocating /usr/local/bundle/gems/grpc-1.36.0-x86_64-linux/src/ruby/lib/grpc/2.7/grpc_c.so: rb_define_module_under: symbol not found
Error relocating /usr/local/bundle/gems/grpc-1.36.0-x86_64-linux/src/ruby/lib/grpc/2.7/grpc_c.so: rb_mutex_unlock: symbol not found
Error relocating /usr/local/bundle/gems/grpc-1.36.0-x86_64-linux/src/ruby/lib/grpc/2.7/grpc_c.so: rb_ary_entry: symbol not found
Error relocating /usr/local/bundle/gems/grpc-1.36.0-x86_64-linux/src/ruby/lib/grpc/2.7/grpc_c.so: rb_gc_mark: symbol not found
Error relocating /usr/local/bundle/gems/grpc-1.36.0-x86_64-linux/src/ruby/lib/grpc/2.7/grpc_c.so: rb_empty_keyword_given_p: symbol not found
Error relocating /usr/local/bundle/gems/grpc-1.36.0-x86_64-linux/src/ruby/lib/grpc/2.7/grpc_c.so: rb_define_alloc_func: symbol not found
Error relocating /usr/local/bundle/gems/grpc-1.36.0-x86_64-linux/src/ruby/lib/grpc/2.7/grpc_c.so: rb_ivar_get: symbol not found
Error relocating /usr/local/bundle/gems/grpc-1.36.0-x86_64-linux/src/ruby/lib/grpc/2.7/grpc_c.so: rb_raise: symbol not found
Error relocating /usr/local/bundle/gems/grpc-1.36.0-x86_64-linux/src/ruby/lib/grpc/2.7/grpc_c.so: rb_intern: symbol not found
Error relocating /usr/local/bundle/gems/grpc-1.36.0-x86_64-linux/src/ruby/lib/grpc/2.7/grpc_c.so: rb_id2sym: symbol not found
Error relocating /usr/local/bundle/gems/grpc-1.36.0-x86_64-linux/src/ruby/lib/grpc/2.7/grpc_c.so: rb_free_tmp_buffer: symbol not found
Error relocating /usr/local/bundle/gems/grpc-1.36.0-x86_64-linux/src/ruby/lib/grpc/2.7/grpc_c.so: rb_check_type: symbol not found
Error relocating /usr/local/bundle/gems/grpc-1.36.0-x86_64-linux/src/ruby/lib/grpc/2.7/grpc_c.so: rb_mutex_new: symbol not found
Error relocating /usr/local/bundle/gems/grpc-1.36.0-x86_64-linux/src/ruby/lib/grpc/2.7/grpc_c.so: ruby_xfree: symbol not found
Error relocating /usr/local/bundle/gems/grpc-1.36.0-x86_64-linux/src/ruby/lib/grpc/2.7/grpc_c.so: ruby_xmalloc2: symbol not found
Error relocating /usr/local/bundle/gems/grpc-1.36.0-x86_64-linux/src/ruby/lib/grpc/2.7/grpc_c.so: rb_str_buf_new: symbol not found
Error relocating /usr/local/bundle/gems/grpc-1.36.0-x86_64-linux/src/ruby/lib/grpc/2.7/grpc_c.so: rb_struct_aset: symbol not found
Error relocating /usr/local/bundle/gems/grpc-1.36.0-x86_64-linux/src/ruby/lib/grpc/2.7/grpc_c.so: rb_data_typed_object_wrap: symbol not found
Error relocating /usr/local/bundle/gems/grpc-1.36.0-x86_64-linux/src/ruby/lib/grpc/2.7/grpc_c.so: rb_class2name: symbol not found
Error relocating /usr/local/bundle/gems/grpc-1.36.0-x86_64-linux/src/ruby/lib/grpc/2.7/grpc_c.so: rb_define_const: symbol not found
Error relocating /usr/local/bundle/gems/grpc-1.36.0-x86_64-linux/src/ruby/lib/grpc/2.7/grpc_c.so: rb_ary_push: symbol not found
Error relocating /usr/local/bundle/gems/grpc-1.36.0-x86_64-linux/src/ruby/lib/grpc/2.7/grpc_c.so: rb_thread_create: symbol not found
Error relocating /usr/local/bundle/gems/grpc-1.36.0-x86_64-linux/src/ruby/lib/grpc/2.7/grpc_c.so: rb_obj_class: symbol not found
Error relocating /usr/local/bundle/gems/grpc-1.36.0-x86_64-linux/src/ruby/lib/grpc/2.7/grpc_c.so: rb_keyword_given_p: symbol not found
Error relocating /usr/local/bundle/gems/grpc-1.36.0-x86_64-linux/src/ruby/lib/grpc/2.7/grpc_c.so: rb_jump_tag: symbol not found
Error relocating /usr/local/bundle/gems/grpc-1.36.0-x86_64-linux/src/ruby/lib/grpc/2.7/grpc_c.so: rb_eTypeError: symbol not found
Error relocating /usr/local/bundle/gems/grpc-1.36.0-x86_64-linux/src/ruby/lib/grpc/2.7/grpc_c.so: rb_cInteger: symbol not found
Error relocating /usr/local/bundle/gems/grpc-1.36.0-x86_64-linux/src/ruby/lib/grpc/2.7/grpc_c.so: rb_cStruct: symbol not found
Error relocating /usr/local/bundle/gems/grpc-1.36.0-x86_64-linux/src/ruby/lib/grpc/2.7/grpc_c.so: rb_eRangeError: symbol not found
Error relocating /usr/local/bundle/gems/grpc-1.36.0-x86_64-linux/src/ruby/lib/grpc/2.7/grpc_c.so: rb_cTime: symbol not found
Error relocating /usr/local/bundle/gems/grpc-1.36.0-x86_64-linux/src/ruby/lib/grpc/2.7/grpc_c.so: rb_eLoadError: symbol not found
Error relocating /usr/local/bundle/gems/grpc-1.36.0-x86_64-linux/src/ruby/lib/grpc/2.7/grpc_c.so: rb_eNameError: symbol not found
Error relocating /usr/local/bundle/gems/grpc-1.36.0-x86_64-linux/src/ruby/lib/grpc/2.7/grpc_c.so: rb_cTrueClass: symbol not found
Error relocating /usr/local/bundle/gems/grpc-1.36.0-x86_64-linux/src/ruby/lib/grpc/2.7/grpc_c.so: rb_eException: symbol not found
Error relocating /usr/local/bundle/gems/grpc-1.36.0-x86_64-linux/src/ruby/lib/grpc/2.7/grpc_c.so: rb_eRuntimeError: symbol not found
Error relocating /usr/local/bundle/gems/grpc-1.36.0-x86_64-linux/src/ruby/lib/grpc/2.7/grpc_c.so: rb_cSymbol: symbol not found
Error relocating /usr/local/bundle/gems/grpc-1.36.0-x86_64-linux/src/ruby/lib/grpc/2.7/grpc_c.so: rb_cFloat: symbol not found
Error relocating /usr/local/bundle/gems/grpc-1.36.0-x86_64-linux/src/ruby/lib/grpc/2.7/grpc_c.so: rb_cNilClass: symbol not found
Error relocating /usr/local/bundle/gems/grpc-1.36.0-x86_64-linux/src/ruby/lib/grpc/2.7/grpc_c.so: rb_eArgError: symbol not found
Error relocating /usr/local/bundle/gems/grpc-1.36.0-x86_64-linux/src/ruby/lib/grpc/2.7/grpc_c.so: rb_cObject: symbol not found
Error relocating /usr/local/bundle/gems/grpc-1.36.0-x86_64-linux/src/ruby/lib/grpc/2.7/grpc_c.so: rb_cFalseClass: symbol not found
```

### What did you expect to see?
No errors

### What did you see instead?
Errors

### Workaround
```sh
gem install --platform ruby grpc
```

**Comment by drfloob** [comment] 2021-03-15 18:42
Duplicate of https://github.com/grpc/grpc/issues/24116. Alpine Linux isn't actively supported or tested with grpc-ruby.

CC @apolcyn

**Closed by drfloob** 2021-03-15 18:42 UTC
Labels: kind/bug, priority/P2

**Comment by x-yuri** [comment] 2021-03-25 16:56
I'm not so sure of it being a duplicate, because in this case it fails to require `grpc` (`ruby -e 'require "grpc"'`) unless installed with `--platform ruby`. And I had no further issues with `google-protobuf`, and at least didn't get to the point where it segfaults. But I see your reasoning.

P.S. Relocation errors [can be ignored][a].

[a]: https://github.com/rake-compiler/rake-compiler/issues/188#issuecomment-805919921

**Comment by laurynas** [comment] 2022-12-30 10:26
Following works when installing gems with bundler:
```
BUNDLE_FORCE_RUBY_PLATFORM=1 bundle install
```
Also `force_ruby_platform` can be specified in bundle config.
https://bundler.io/v2.2/man/bundle-config.1.html

**Comment by jscheel** [comment] 2023-06-06 04:02
this solution leads to a significantly longer bundle time

**Comment by mroach** [comment] 2023-11-24 10:34
For anyone encountering problems on Alpine these days and arriving here by searcing, the error message is now:

```
Error loading shared library ld-linux-x86-64.so.2: No such file or directory
```

Install the `gcompat` package on Alpine, and at least in my case, that solved it.

```
apk add --no-cache gcompat
```
