### ISSUE TITLE
New Failure: py34.test.unit.beta._face_interface_test.MultiCallableInvokerBlockingInvocationInlineServiceTest

### ISSUE THREAD

**Issue by dgquintas** [grpc/grpc#13425] opened 2017-11-16 22:25 UTC
- Test: py34.test.unit.beta._face_interface_test.MultiCallableInvokerBlockingInvocationInlineServiceTest
- Poll Strategy: None
- URL: https://kokoro2.corp.google.com/job/grpc/job/ubuntu/job/master/job/grpc_basictests_multilang/182

**Comment by nathanielmanistaatgoogle** [comment] 2017-11-17 16:48
Closing as a duplicate of [issue 9538](https://github.com/grpc/grpc/issues/9538) (note `WRONG_VERSION_NUMBER` in the test log).

**Closed by nathanielmanistaatgoogle** 2017-11-17 16:48 UTC
Labels: area/test, infra/New Failure, lang/Python
