### ISSUE TITLE
gRPC client does not unblock when server becomes unreachable

### ISSUE THREAD

**Issue by AshutoshNasikkar** [grpc/grpc#3482] opened 2015-09-25 05:12 UTC
A process has a main thread writing to gRPC while gRPC thread is blocked for socket activity as it's using completion queue API, cq.Next. While reading / writing messages or in idle state if the server becomes unreachable either via server going down or traffic getting non-routable (interface down) the gRPC thread remains blocked for a very long time in cq.Next. The main thread tries to close the current gRPC channel object by writing "WritesDone", "Finish" however the gRPC thread stays blocked.

As a workaround, cq.AsyncNext is used with a timeout of 5 seconds. When main thread issues "WritesDone" and "Finish" it also indicates via a flag to gRPC thread to disconnect from existing session such that when AsyncNext timesOut and if Disconnect is detected it issues "cq.Shutdown" and again waits on cq.AsyncNext. Here the assumption is that "AsyncNext" should return with "CompletionQueue::SHUTDOWN" so that completion queue can be flushed out and gRPC channel object destructed. But its observed that AsyncNext again returns with timeout and this loop continues and gRPC object is never destructed.

Please suggest if there are any changes required to the above approach.
To me it appears that gRPC is unable to handle unreachable scenarios in both blocking and non blocking APIs.
If its a genuine issue, I request a fix for it.

Some sample logs for cq.Next to illustrate the issue. The server had gone down for some time and was brought online approx 11:20. Still the connectivity kept failing and took a long time to recover.
Sep  17 11:13:03  GC-Agent[10340]: grpclib:: on_writable failed during connect
Sep  17 11:13:34  GC-Agent[10340]: grpclib:: on_writable failed during connect
Sep  17 11:14:38  GC-Agent[10340]: grpclib:: on_writable failed during connect
Sep  17 11:15:42  GC-Agent[10340]: grpclib:: on_writable failed during connect
Sep  17 11:16:46  GC-Agent[10340]: grpclib:: on_writable failed during connect
Sep  17 11:17:50  GC-Agent[10340]: grpclib:: on_writable failed during connect
Sep  17 11:18:54  GC-Agent[10340]: grpclib:: on_writable failed during connect
Sep  17 11:19:37  GC-Agent[10340]: grpclib:: Handshake failed with fatal error SSL_ERROR_SSL: error:1408F10B:SSL routines:SSL3_GET_RECORD:wrong version number.
Sep  17 11:19:37  GC-Agent[10340]: grpclib:: Handshake failed with error TSI_PROTOCOL_FAILURE
Sep  17 11:19:37  GC-Agent[10340]: grpclib:: Secure transport setup failed with error 2.
Sep  17 11:19:47  GC-Agent[10340]: grpclib:: on_writable failed during connect
Sep  17 11:20:19  GC-Agent[10340]: grpclib:: on_writable failed during connect
Sep  17 11:21:23  GC-Agent[10340]: grpclib:: on_writable failed during connect
Sep  17 11:22:28  GC-Agent[10340]: grpclib:: on_writable failed during connect
Sep  17 11:23:32  GC-Agent[10340]: grpclib:: on_writable failed during connect
Sep  17 11:24:36  GC-Agent[10340]: grpclib:: on_writable failed during connect
Sep  17 11:25:39  GC-Agent[10340]: grpclib:: on_writable failed during connect
Sep  17 11:26:44  GC-Agent[10340]: grpclib:: on_writable failed during connect
Sep  17 11:27:47  GC-Agent[10340]: grpclib:: on_writable failed during connect
Sep  17 11:28:51  GC-Agent[10340]: grpclib:: on_writable failed during connect
Sep  17 11:29:55  GC-Agent[10340]: grpclib:: on_writable failed during connect
Sep  17 11:36:41  GC-Agent[10340]: grpclib:: Handshake failed with fatal error SSL_ERROR_SSL: error:1408F10B:SSL routines:SSL3_GET_RECORD:wrong version number.
Sep  17 11:36:41  GC-Agent[10340]: grpclib:: Handshake failed with error TSI_PROTOCOL_FAILURE
Sep  17 11:36:41  GC-Agent[10340]: grpclib:: Secure transport setup failed with error 2.
Sep  17 11:36:51  GC-Agent[10340]: grpclib:: on_writable failed during connect
Sep  17 11:37:23  GC-Agent[10340]: grpclib:: on_writable failed during connect
Sep  17 11:38:28  GC-Agent[10340]: grpclib:: on_writable failed during connect
Sep  17 11:39:32  GC-Agent[10340]: grpclib:: on_writable failed during connect
Sep  17 11:40:36  GC-Agent[10340]: grpclib:: on_writable failed during connect
Sep  17 11:41:40  GC-Agent[10340]: grpclib:: on_writable failed during connect
Sep  17 11:42:43  GC-Agent[10340]: grpclib:: on_writable failed during connect
Sep  17 11:43:48  GC-Agent[10340]: grpclib:: on_writable failed during connect
Sep  17 11:44:51  GC-Agent[10340]: grpclib:: on_writable failed during connect
Sep  17 11:45:55  GC-Agent[10340]: grpclib:: on_writable failed during connect
Sep  17 11:46:59  GC-Agent[10340]: grpclib:: on_writable failed during connect
Sep  17 12:10:51  GC-Agent[10340]: GrpcChannel: CQ op completed tag = 2141869200
Sep  17 12:10:51  GC-Agent[10340]: GrpcChannel: unknown tag returned
Sep  17 12:10:51  GC-Agent[10340]: GrpcChannel: Get next completed operation
Sep  17 12:10:51  GC-Agent[10340]: GrpcChannel: CQ op completed tag = 2
Sep  17 12:10:51  GC-Agent[10340]: GrpcChannel: write tag returned
Sep  17 12:10:51  GC-Agent[10340]: GrpcChannel::dequeue_sendQ called
Sep  17 12:10:51  GC-Agent[10340]: GrpcChannel::setWriteReady called val=TRUE
Sep  17 12:10:51  GC-Agent[10340]: GrpcChannel: Get next completed operation
Sep  17 12:10:51  GC-Agent[10340]: GrpcChannel: CQ op completed tag = 3
Sep  17 12:10:51  GC-Agent[10340]: GrpcChannel: writedone tag returned
Sep  17 12:10:51  GC-Agent[10340]: GrpcChannel: Get next completed operation
Sep  17 12:10:51  GC-Agent[10340]: GrpcChannel: CQ op completed tag = 4
Sep  17 12:10:51  GC-Agent[10340]: GrpcChannel: finish tag returned
Sep  17 12:10:51  GC-Agent[10340]: GrpcChannel: Get next completed operation
Sep  17 12:10:51  GC-Agent[10340]: GrpcChannel: CQ op completed tag = 1
Sep  17 12:10:51  GC-Agent[10340]: GrpcChannel: CQ returned failure ret:True ok:False

**Comment by ctiller** [comment] 2015-09-25 14:40
Is this for a streaming or a unary request?

**Comment by AshutoshNasikkar** [comment] 2015-09-26 06:34
The communication between server and client is on a need basis with a configurable keepalive (15secs default). So it's not a continuous streaming of messages. That would be unary request.

**Comment by ctiller** [comment] 2015-10-07 19:29
I think what you want to do is cancel the pending RPC when you're shutting things down (ClientContext.TryCancel()).

**Comment by shuowusc** [comment] 2015-10-12 23:21
We observed a similar issue when a bi-directional streaming Python client gets stuck trying to destroy a stub for an unreachable server. Because of this bug, we are unable to productionize our code. Is there any way to workaround this issue? 

Relevant stack traces:

# ThreadID: 4419948544
File: "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 783, in __bootstrap
  self.__bootstrap_inner()
File: "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 810, in __bootstrap_inner
  self.run()
File: "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 763, in run
  self.__target(*self.__args, **self.__kwargs)
File: "/Library/Python/2.7/site-packages/concurrent/futures/thread.py", line 73, in _worker
  work_item.run()
File: "/Library/Python/2.7/site-packages/concurrent/futures/thread.py", line 61, in run
  result = self.fn(*self.args, **self.kwargs)
File: "/Library/Python/2.7/site-packages/grpc/framework/foundation/logging_pool.py", line 43, in _wrapping
  return behavior(*args, **kwargs)
File: "/Library/Python/2.7/site-packages/grpc/_adapter/fore.py", line 222, in _spin
  event = completion_queue.get(None)
File: "/Library/Python/2.7/site-packages/grpc/_adapter/_intermediary_low.py", line 188, in get
  ev = self._internal.next()
File: "/Library/Python/2.7/site-packages/grpc/_adapter/_low.py", line 43, in next
  raw_event = self.completion_queue.next(deadline)

# ThreadID: 4415741952
File: "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 783, in __bootstrap
  self.__bootstrap_inner()
File: "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 810, in __bootstrap_inner
  self.run()
File: "/Users/shuo.wu/git/workflow/server/executor/registration_manager.py", line 74, in run
  stub.__exit__(None, None, None)
File: "/Library/Python/2.7/site-packages/grpc/early_adopter/implementations.py", line 161, in __exit__
  self._rear_link.stop()
File: "/Library/Python/2.7/site-packages/grpc/_adapter/rear.py", line 373, in stop
  self._stop()
File: "/Library/Python/2.7/site-packages/grpc/_adapter/rear.py", line 356, in _stop
  self._condition.wait()
File: "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 339, in wait
  waiter.acquire()

**Comment by nathanielmanistaatgoogle** [comment] 2015-10-12 23:37
@shuowusc: it looks from your stack traces that you're using the `grpc.early_adopter` API. Do your problems persist if you upgrade to the `grpc.beta` API?

**Comment by shuowusc** [comment] 2015-10-26 23:01
I am unable to reproduce this in beta. So this is no longer an issue for us at this moment. Thanks.

**Comment by nathanielmanistaatgoogle** [comment] 2015-11-05 23:08
@AshutoshNasikkar: is this still an open issue for you? Are you still able to observe the defective behavior described in this report?

**Comment by shuowusc** [comment] 2015-11-05 23:12
I was able to solve this issue, but there are other issues with gRPC beta.
One time the client was stuck on an RPC indefinitely, but I don't have any
new information for debugging yet. You can close it out. Thanks!

Thanks,
Shuo

**Comment by ctiller** [comment] 2015-11-05 23:44
I think this has been addressed; feel free to re-open if not.

**Closed by ctiller** 2015-11-05 23:44 UTC

**Comment by AshutoshNasikkar** [comment] 2015-11-06 02:28
TryCancel is working for me. Thank you all.

**Comment by csenanda** [comment] 2017-12-05 19:36
I am facing the exact same problem and am using grpc v1.0.0
Here is how my code goes

ClientContext context;
std::unique_ptr<Consumer::Stub> stub_ = Consumer::NewStub(channel);
ThreadEventReader = stub_->GetDataStream(&context, Filter);  //streaming rpc call
// blocked read - until stream closed
while (ThreadEventReader->Read(&StreamedData))
{
                cout << "UpdateStream: " << StreamedData.displayvalue() << endl;
}

If the connection to the server drops out, the thread gets blocked in Read indefinitely.
Its easy to reproduce consistently if the server is a remote node.  Let me know if you need additional info.
