### ISSUE TITLE
tests.cloud_to_cloud:*:http2_server:*  timing out on v1.2.x branch

### ISSUE THREAD

**Issue by jtattermusch** [grpc/grpc#10455] opened 2017-04-04 13:40 UTC
It may be a flake.
https://grpc-testing.appspot.com/job/gRPC_interop_pull_requests/12898/#showFailuresLink

e.g.
```
Apr 04, 2017 8:36:19 AM io.grpc.testing.integration.Http2Client run
INFO: Running test rst_during_data
Apr 04, 2017 8:36:19 AM io.netty.util.internal.MacAddressUtil defaultMachineId
WARNING: Failed to find a usable hardware address from the network interfaces; using random bytes: 53:63:aa:c7:6c:56:8d:18
Exception in thread "main" java.lang.AssertionError: Operation timed out
	at io.grpc.testing.integration.Http2Client$Tester.rstDuringData(Http2Client.java:262)
	at io.grpc.testing.integration.Http2Client$Tester.access$500(Http2Client.java:216)
	at io.grpc.testing.integration.Http2Client.runTest(Http2Client.java:200)
	at io.grpc.testing.integration.Http2Client.run(Http2Client.java:182)
	at io.grpc.testing.integration.Http2Client.main(Http2Client.java:90)
```

**Comment by ncteisen** [comment] 2017-04-04 15:27
Ahh no not a flake. Eric investigated this [issue](10056) and solved this in #10100. It should be backported to v1.2.x

**Comment by ericgribkoff** [comment] 2017-04-05 15:45
Closed via https://github.com/grpc/grpc/issues/10463

**Comment by apolcyn** [comment] 2017-04-25 03:09
reopening as what looks like a batch of similar errors happened today and yesterda (4/24 and 4/23)

`rst_during_data` and `rst_after_data` both show similar errors as above, and `max_streams` shows errors as below:

log in https://grpc-testing.appspot.com/job/gRPC_interop_master/12523/

```
Regression

tests.cloud_to_cloud:java:http2_server:max_streams (from grpc.tests)

Failing for the past 1 build (Since Unstable#12523 )
Took 9.6 sec.
add description
Error Message

Failure
Standard Output

Apr 24, 2017 2:30:10 PM io.grpc.testing.integration.Http2Client run
INFO: Running test max_streams
Apr 24, 2017 2:30:10 PM io.netty.util.internal.MacAddressUtil defaultMachineId
WARNING: Failed to find a usable hardware address from the network interfaces; using random bytes: 33:1a:bf:15:9e:13:e0:e7
Exception in thread "main" java.lang.RuntimeException: java.util.concurrent.TimeoutException
	at io.grpc.testing.integration.Http2Client.run(Http2Client.java:186)
	at io.grpc.testing.integration.Http2Client.main(Http2Client.java:90)
Caused by: java.util.concurrent.TimeoutException
	at com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:411)
	at com.google.common.util.concurrent.AbstractFuture$TrustedFuture.get(AbstractFuture.java:84)
	at io.grpc.testing.integration.Http2Client$Tester.maxStreams(Http2Client.java:295)
	at io.grpc.testing.integration.Http2Client$Tester.access$800(Http2Client.java:216)
	at io.grpc.testing.integration.Http2Client.runTest(Http2Client.java:209)
	at io.grpc.testing.integration.Http2Client.run(Http2Client.java:182)
	... 1 more
Apr 24, 2017 2:30:16 PM io.netty.util.concurrent.DefaultPromise notifyListener0
WARNING: An exception was thrown by io.grpc.netty.NettyClientStream$Sink$2.operationComplete()
java.lang.IllegalStateException: onStreamAllocated was not called, but it seems the stream is active
	at com.google.common.base.Preconditions.checkState(Preconditions.java:174)
	at io.grpc.internal.AbstractStream2$TransportState.onSentBytes(AbstractStream2.java:289)
	at io.grpc.netty.NettyClientStream$Sink$2.operationComplete(NettyClientStream.java:173)
	at io.grpc.netty.NettyClientStream$Sink$2.operationComplete(NettyClientStream.java:167)
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:507)
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:481)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:420)
	at io.netty.util.concurrent.DefaultPromise.setSuccess(DefaultPromise.java:95)
	at io.netty.channel.DefaultChannelPromise.setSuccess(DefaultChannelPromise.java:76)
	at io.netty.channel.DefaultChannelPromise.setSuccess(DefaultChannelPromise.java:71)
	at io.netty.handler.codec.http2.StreamBufferingEncoder$Frame.release(StreamBufferingEncoder.java:309)
	at io.netty.handler.codec.http2.StreamBufferingEncoder$DataFrame.release(StreamBufferingEncoder.java:357)
	at io.netty.handler.codec.http2.StreamBufferingEncoder$PendingStream.close(StreamBufferingEncoder.java:292)
	at io.netty.handler.codec.http2.StreamBufferingEncoder.writeRstStream(StreamBufferingEncoder.java:184)
	at io.grpc.netty.NettyClientHandler.cancelStream(NettyClientHandler.java:470)
	at io.grpc.netty.NettyClientHandler.write(NettyClientHandler.java:244)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:739)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:731)
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:817)
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:724)
	at io.netty.channel.DefaultChannelPipeline.write(DefaultChannelPipeline.java:1022)
	at io.netty.channel.AbstractChannel.write(AbstractChannel.java:291)
	at io.grpc.netty.WriteQueue.flush(WriteQueue.java:127)
	at io.grpc.netty.WriteQueue.access$000(WriteQueue.java:47)
	at io.grpc.netty.WriteQueue$1.run(WriteQueue.java:59)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:403)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:445)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144)
	at java.lang.Thread.run(Thread.java:745)

Apr 24, 2017 2:30:16 PM com.google.common.util.concurrent.AggregateFuture$RunningState handleException
SEVERE: Got more than one input Future failure. Logging failures after the first
java.lang.RuntimeException: io.grpc.StatusRuntimeException: CANCELLED
	at io.grpc.testing.integration.Http2Client$Tester$MaxStreamsWorker.run(Http2Client.java:349)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:108)
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:41)
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:77)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: io.grpc.StatusRuntimeException: CANCELLED
	at io.grpc.Status.asRuntimeException(Status.java:531)
	at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:138)
	at io.grpc.testing.integration.TestServiceGrpc$TestServiceBlockingStub.unaryCall(TestServiceGrpc.java:473)
	at io.grpc.testing.integration.Http2Client$Tester$MaxStreamsWorker.run(Http2Client.java:347)
	... 7 more
Caused by: java.lang.InterruptedException
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.reportInterruptAfterWait(AbstractQueuedSynchronizer.java:2014)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2048)
	at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:442)
	at io.grpc.stub.ClientCalls$ThreadlessExecutor.waitAndDrain(ClientCalls.java:584)
	at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:135)
	... 9 more

Apr 24, 2017 2:30:16 PM com.google.common.util.concurrent.AggregateFuture$RunningState handleException
SEVERE: Got more than one input Future failure. Logging failures after the first
java.lang.RuntimeException: io.grpc.StatusRuntimeException: CANCELLED
	at io.grpc.testing.integration.Http2Client$Tester$MaxStreamsWorker.run(Http2Client.java:349)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:108)
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:41)
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:77)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: io.grpc.StatusRuntimeException: CANCELLED
	at io.grpc.Status.asRuntimeException(Status.java:531)
	at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:138)
	at io.grpc.testing.integration.TestServiceGrpc$TestServiceBlockingStub.unaryCall(TestServiceGrpc.java:473)
	at io.grpc.testing.integration.Http2Client$Tester$MaxStreamsWorker.run(Http2Client.java:347)
	... 7 more
Caused by: java.lang.InterruptedException
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.reportInterruptAfterWait(AbstractQueuedSynchronizer.java:2014)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2048)
	at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:442)
	at io.grpc.stub.ClientCalls$ThreadlessExecutor.waitAndDrain(ClientCalls.java:584)
	at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:135)
	... 9 more
```

**Comment by murgatroid99** [comment] 2017-05-17 16:57
Seen again: https://grpc-testing.appspot.com/job/gRPC_interop_master/12903/testReport/junit/(root)/tests/cloud_to_cloud_java_http2_server_max_streams/

**Comment by muxi** [comment] 2017-05-18 05:21
Still happening on master:
https://grpc-testing.appspot.com/job/gRPC_interop_master/12964/testReport/junit/(root)/tests/cloud_to_cloud_java_http2_server_max_streams/

**Comment by yang-g** [comment] 2017-05-19 16:13
https://grpc-testing.appspot.com/job/gRPC_interop_pull_requests/13942/

**Comment by ericgribkoff** [comment] 2017-08-18 06:53
This seems to have been the same issue reported in https://github.com/grpc/grpc/issues/10390, and was caused by too small a timeout in the Java client.

**Closed by ericgribkoff** 2017-08-18 06:53 UTC
Labels: infra/BUILDPONY, kind/bug/interop
