### ISSUE TITLE
Bazel build for C++ failed on external dependency based on gRPC v1.15.1

### ISSUE THREAD

**Issue by ravil23** [grpc/grpc#16775] opened 2018-10-03 23:06 UTC
### What version of gRPC and what language are you using?
 gRPC 1.15.1 (C++)
 
### What operating system (Linux, Windows, …) and version?
 OS X
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
Bazel 0.17.2
Apple LLVM version 10.0.0 (clang-1000.10.44.2)
Target: x86_64-apple-darwin17.7.0
Thread model: posix
 
### What did you do?
If possible, provide a recipe for reproducing the error. Try being specific and include code snippets if helpful.

I try to add external dependency by next code in my WORKSPACE file:
```
git_repository(
    name = "grpc",
    remote = "https://github.com/grpc/grpc.git",
    tag = "v1.15.1",
    init_submodules = True,
)
```

After that I run building of C++ library:
```
bazel build @grpc//:grpc++
```
 
### What did you expect to see?

I expect some C++ libraries as it work on gRPC v1.13.1:
```
INFO: SHA256 (https://github.com/grpc/grpc/archive/v1.13.1.tar.gz) = af0d41b5fab2797a3bd71bfe1b8c94e553b7c7317f87f664de26bafbf75677c4
INFO: Build options have changed, discarding analysis cache.
WARNING: /private/var/tmp/_bazel_admin/e511d3e4923cacd00506281eacfaf097/external/grpc/BUILD:1992:1: in srcs attribute of cc_library rule @grpc//:grpc_nanopb: please do not import '@grpc//third_party/nanopb:pb_common.c' directly. You should either move the file to this package or depend on an appropriate rule there. Since this rule was created by the macro 'grpc_generate_one_off_targets', the error might have been caused by the macro implementation in /private/var/tmp/_bazel_admin/e511d3e4923cacd00506281eacfaf097/external/grpc/bazel/grpc_build_system.bzl:172:12
WARNING: /private/var/tmp/_bazel_admin/e511d3e4923cacd00506281eacfaf097/external/grpc/BUILD:1992:1: in srcs attribute of cc_library rule @grpc//:grpc_nanopb: please do not import '@grpc//third_party/nanopb:pb_decode.c' directly. You should either move the file to this package or depend on an appropriate rule there. Since this rule was created by the macro 'grpc_generate_one_off_targets', the error might have been caused by the macro implementation in /private/var/tmp/_bazel_admin/e511d3e4923cacd00506281eacfaf097/external/grpc/bazel/grpc_build_system.bzl:172:12
WARNING: /private/var/tmp/_bazel_admin/e511d3e4923cacd00506281eacfaf097/external/grpc/BUILD:1992:1: in srcs attribute of cc_library rule @grpc//:grpc_nanopb: please do not import '@grpc//third_party/nanopb:pb_encode.c' directly. You should either move the file to this package or depend on an appropriate rule there. Since this rule was created by the macro 'grpc_generate_one_off_targets', the error might have been caused by the macro implementation in /private/var/tmp/_bazel_admin/e511d3e4923cacd00506281eacfaf097/external/grpc/bazel/grpc_build_system.bzl:172:12
INFO: Analysed target @grpc//:grpc++ (16 packages loaded).
INFO: Found 1 target...
Target @grpc//:grpc++ up-to-date:
  bazel-bin/external/grpc/libgrpc++.a
  bazel-bin/external/grpc/libgrpc++.so
INFO: Elapsed time: 118.016s, Critical Path: 3.51s
INFO: 769 processes: 769 darwin-sandbox.
INFO: Build completed successfully, 770 total actions
```
 
### What did you see instead?
 
Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

```
INFO: SHA256 (https://github.com/grpc/grpc/archive/v1.15.1.tar.gz) = 0186e800fbda420305c3489ddb28394059e1e6fc192a97fc7412d21b7306d82e
INFO: Build options have changed, discarding analysis cache.
INFO: Analysed target @grpc//:grpc++ (18 packages loaded).
INFO: Found 1 target...
ERROR: /private/var/tmp/_bazel_admin/e511d3e4923cacd00506281eacfaf097/external/grpc/BUILD:1817:1: C++ compilation of rule '@grpc//:alts_proto' failed (Exit 1)
In file included from external/grpc/src/core/tsi/alts/handshaker/transport_security_common.pb.c:4:
external/grpc/src/core/tsi/alts/handshaker/transport_security_common.pb.h:6:10: fatal error: 'pb.h' file not found
#include "pb.h"
         ^~~~~~
1 error generated.
Target @grpc//:grpc++ failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 17.553s, Critical Path: 0.96s
INFO: 7 processes: 7 darwin-sandbox.
FAILED: Build did NOT complete successfully
```

**Comment by jiangtaoli2016** [comment] 2018-10-04 03:47
@yihuazhang could you please take a look?

**Comment by yihuazhang** [comment] 2018-10-04 16:34
@ravil23 

The error is caused by nanopb library not being correctly linked into gRPC. 

@dgquintas, I noticed you made several nanopb-related changes (e.g., https://github.com/grpc/grpc/pull/15595), and do you have any insights on this?

**Comment by vjpai** [comment] 2019-02-05 18:18
@ncteisen : Noah, I think that you have touched the nanopb BUILD stuff recently, correct? Do you have a solution here?

**Comment by ncteisen** [comment] 2019-02-05 21:20
This fix was all in TensorFlow's build system. See here: https://github.com/tensorflow/tensorflow/commit/80ac0c26cc16ffa1804c1092e298dee021f64b36

**Comment by ncteisen** [comment] 2019-02-06 15:36
Closing for now, let me know by commenting if following similar steps to the ones taken for TensorFlow does not help and I will re open

**Closed by ncteisen** 2019-02-06 15:36 UTC
Labels: kind/bug, lang/c++, priority/P2
