### ISSUE TITLE
It should be possible to `pip install grpc` in order to get the Python components

### ISSUE THREAD

**Issue by alex** [grpc/grpc#1044] opened 2015-03-14 17:33 UTC
Without this grpc is very difficult to fit into most existing python deployment workflows

**Comment by nathanielmanistaatgoogle** [comment] 2015-03-17 00:36
Duplicate of #936.

**Comment by alex** [comment] 2015-03-17 00:37
Whoops, sorry about that! (I searched for "pip", didn't occur to me to search for packaging)

**Closed by nathanielmanistaatgoogle** 2015-03-17 00:36 UTC
