### ISSUE TITLE
Grpc.Tools build target precludes Rider inspection on generated files

### ISSUE THREAD

**Issue by calebatwd** [grpc/grpc#17898] opened 2019-02-01 02:13 UTC
### What version of gRPC and what language are you using?
Grpc.Tools 1.18.0
 
### What operating system (Linux, Windows, …) and version?
 MacOs Mojave and Windows 10
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
 C# MSBuild on netstandard1.5 and netstandard2.1
`dotnet build`
 
### What did you do?
Opened the csharp sample solution for helloworld loaded in **Rider** (the Jetbrains IDE) and built. (First found on a larger project, then repro'd on the sample).
From the sample csproj
```
  <ItemGroup>
    <Protobuf Include="../../../protos/helloworld.proto" Link="helloworld.proto" />
  </ItemGroup>
```
 
### What did you expect to see?
A fresh build should result in no build errors and code-inspection indexing of the generated files, followed by symbols resolving as Rider performs indexing and Synchronization (no red).
 
### What did you see instead?
After a fresh build (which succeeds), the generated files in `obj/Debug/netstandard1.5/` aren't picked up by code inspection resulting in design-time symbol errors and no intellisense. Subsequent builds, cleans, build targets, don't resolved the issue.

### Possible Fix
From https://rider-support.jetbrains.com/hc/en-us/community/posts/360000777140-Rider-ReSharper-ignoring-generated-code, I was able to go into `grpc/src/csharp/Grpc.Tools/build/_protobuf/Google.Protobuf.Tools.targets` and change **line 113** of the `_Protobuf_Compile_BeforeCsCompile` step from **`BeforeCompile`** to **`ResolveAssemblyReferences`**. After modifying and testing a local nuget with the change, this resolved the issue on both windows 10 and macos.
 
### Anything else we should know about your project / environment?
It's unclear to me from reading msbuild docs what the negative implications are of moving the build target to run before ResolveAssemblyReferences instead of BeforeCompile.
From https://github.com/grpc/grpc/blob/master/src/csharp/BUILD-INTEGRATION.md
/cc @kkm000

**Comment by kkm000** [comment] 2019-02-02 19:18
Thanks for the workaround! I've never heard about Rider, but I'll check your pointers. Would you be able to check a nightly build of the Tools package, when available, against this problem?

**Comment by gaeshi** [comment] 2019-02-23 05:36
I have the same problem.

The solution proposed by @calebatwd works with `Grpc.Tools Version=1.17.0`, but doesn't seem to be working with `Grpc.Tools Version=1.18.0`.

I'm using Rider 2018.3.3 on Linux (Ubuntu 18.04 if it's important).

**Comment by gaeshi** [comment] 2019-02-24 02:51
The workaround doesn't work `Grpc.Tools v1.19.0-pre1` either.

**Comment by vfrz** [comment] 2019-02-24 11:53
I can confirm the workaround is only working with version 17 using Rider 2018.3.3 on Win 10.

**Comment by kkm000** [comment] 2019-03-22 07:41
This is a little bit... interesting, since the tooling did not change. 
```
$ git diff v1.17.0..v1.19.1 src/csharp/Grpc.Tools
```
shows two changes, neither of which could possibly change anything in the build sequence. @gaeshi, @vfrx, do you think anything else could have changed in your setup? Build is composed of a large number of interlocked pieces. For example, if you downgrade the package now, would the workaround still work? I would appreciate if you could test that!

It seems to me that Ryder build hooks up into the wrong point in the MS build tooling. There is a target `GenerateAdditionalSources` that is run earlier, that we could hook up to, but it won't help us, as it is also executed later. I am a little bit concerned about hooking up into the build process so early as `ResolveAsssemblyReferences`. Generally, no compilation is supposed to happen at this point; actually, even package conflicts have not been resolved by that time, if you hook to it with a `BeforeTargets` condition.

Could you please check if at the last hooking after, not before this target helps? Instead of `CallTarget` (which is actually almost never used), a better way is to have your (perhaps empty) target run by way of After/Before targets and *depend* on the target you want to actually trigger, like
```xml
  <Target Name="_My_Workaround"
          AfterTargets="ResolveAsssemblyReferences"
          DependsOnTargets="Protobuf_Compile"
          Condition=" '$(Language)' == 'C#' " />
```
This would schedule Protobuf_Compile right after `ResolveAsssemblyReferences` has completed. I assume that they call this target explicitly, so your AfterTargets will also run before returning results to the caller. Only if that does not help, try BeforeTargets instead. It would be less correct, but if it works for you...

It's not impossible that we add a workaround especially for Ryder, but it seems to me that something in the way it evaluates the build is not exactly right. They do perhaps need assembly references resolved anyway for Intellisense to work. Also, this is apparently part of their *design time* build. I just cannot think of finding my way around internals in an unfamiliar IDE. For VS I install an extension that allows debugging design-time build. There is a couple of environment variables that I can set which trade its debugginess for performance. But I won't ride a white horse into this unfamiliar territory, for sure. Is it possible that any good soul here helps me get in touch with their engineers?

**Comment by gaeshi** [comment] 2019-03-23 05:09
Thank you, @kkm000 for looking into this, but unfortunately your proposed workaround didn't seem to work on my machine.

As for getting in touch with Rider's engineers - they have a tracker here:
https://youtrack.jetbrains.com/issues/RIDER?q=grpc

Looks like they are aware of the issue and working on it.

**Comment by gaeshi** [comment] 2019-03-23 05:22
In Rider 2019.1 EAP2, the following configuration seems to work fine:

```
<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>netstandard1.5</TargetFramework>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Google.Protobuf" Version="3.7.0" />
        <PackageReference Include="Grpc" Version="1.17.0" />
        <PackageReference Include="Grpc.Tools" Version="1.17.0" PrivateAssets="All" />
    </ItemGroup>
    
    <ItemGroup>
        <Folder Include="proto"/>
        <Protobuf Include="proto/greet.proto" Link="proto/greet.proto" />
    </ItemGroup>

</Project>
```

Please note that I'm not doing a `CallTarget` on the `_Protobuf_Compile_BeforeCsCompile` before `ResolveAssemblyReferences` anymore here.

However, updating the version of `Grpc` and `Grpc.Tools` to anything above `1.17.0` results in the same behavior (design-time symbol errors and no intellisense).

**Comment by kkm000** [comment] 2019-03-24 13:34
@gaeshi, thanks much for verifying the issue. I'm going to try to understand what is the difference between the versions then.

**Comment by kkm000** [comment] 2019-03-25 23:28
I've posted a private comment to one of the issues there asking the devs to chime in here (private only because I do not want to split this discussion into two in separate places; there is much more information here already than there; there are only reports w/o any analysis). I hope there should be a reaction to that.

Nevertheless, if anyone is in a closer contact with the Rider team, in particular people involved with the design-time build, encouraging them to chime in here would be indeed helpful.

**Comment by xtmq** [comment] 2019-03-27 11:36
I will explain how Rider builds project model and uses msbuild in this comment. 
Short summary - Rider 2019.1 works with Grps toolkit fine our of the box if you specify `*.proto` files in a project. 

To build project model Rider runs msbuild as a separate process. Rider tells msbuild which projects it has to load and obtains results. 'Load' means msbuild project evaluation plus some msbuild targets execution. 

So Rider has a specific set of targets (like ResolveAssemblyReferences) to execute and also it scans projects and finds targets producing 'Compile' items. In our case it is `_Protobuf_AugmentLanguageCompile`. But this target has no dependencies (even transitive or implicit) on `Protobuf_PrepareCompile` / `Protobuf_CoreCompile` so no items were generated and added into projects. 

In 2019.1 we have just included `Protobuf_Compile` target in default targets set so for now everything should work fine.

**Comment by gaeshi** [comment] 2019-03-27 23:45
@xtmq Thank you very much for looking into this!

As I wrote above, I can confirm it works in Rider 2019.1 EAP2 perfectly fine with Grpc.Tools version `1.17.0`. For some reason, the behavior is not the same with the newer releases of Grpc.Tools.

Here is an example project:

https://github.com/gaeshi/grpc-greeting-dotnet/blob/master/Greeter/Greeter.csproj

Updating the version of Grpc.Tools to anything above renders design-time symbol errors and no intellisense.

Rider version:
```
JetBrains Rider 2019.1 EAP
Build #RD-191.6349.96, built on March 21, 2019
Rider EAP User
Expiration date: April 20, 2019
JRE: 1.8.0_202-release-1483-b40 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 4.15.0-46-generic
```

**Comment by xtmq** [comment] 2019-03-28 11:18
I have the latest Rider (EAP3) and installed Grpc and Grpc.Tools 1.19 into your project and everything seems to work ok...

**Comment by xtmq** [comment] 2019-03-28 11:18
But I had to remove obj/bin folders and reopen solution after updating packages to 1.19.

**Comment by jen20** [comment] 2019-03-28 14:43
Using v1.19.0 of the `Grpc` and `Grpc.Tools` packages, and the build of Rider detailed below, everything works OK _provided_ I keep the workaround documented above by @calebatwd. If I remove the workaround, symbol resolution fails. I have not yet tried the EAP, however.

```
JetBrains Rider 2018.3.4
Build #RD-183.6092.12, built on March 4, 2019
JRE: 1.8.0_152-release-1343-b28 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.14.3
```

**Comment by gaeshi** [comment] 2019-03-31 22:13
@xtmq I can confirm that it works on my installation of Rider EAP3 with Grpc.Tools 1.19 fine, too, no workarounds needed. Here is my current csproj:

```
<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>netstandard1.5</TargetFramework>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Google.Protobuf" Version="3.7.0" />
        <PackageReference Include="Grpc" Version="1.19.0" />
        <PackageReference Include="Grpc.Tools" Version="1.19.0" PrivateAssets="All" />
    </ItemGroup>
    
    <ItemGroup>
        <Folder Include="proto" />
        <Protobuf Include="proto/greet.proto" Link="proto/greet.proto" />
    </ItemGroup>

</Project>
```

@jen20 Please consider trying EAP3. You can install it side by side with the other versions and launch it easily using Jetbrains Toolbox.

**Comment by jen20** [comment] 2019-03-31 22:15
I have confirmed all is well in the EAP - I don't like forcing that on downstream devs so I'll leave the workaround in place for now and wait for the next stable release of Rider.

**Comment by kkm000** [comment] 2019-04-01 02:23
@xmtq, thanks for chiming in here and fixing the issue so quickly!

First and above all, I'm sure there are deep reasons you have to do the design time build differently from [the recommended (and poorly documented!) practice](https://github.com/dotnet/project-system/blob/master/docs/design-time-builds.md), so please do not perceive the following as an unasked-for advise; I just thought that sharing my experience with MSBuild and common Microsoft's own use of it in their build scripting would prove fruitful.

In general, codegen does not happen before `ResolveAssemblyReferences` completes, as it might potentially have dependencies on the resolved TFM, for example. It's not generalizable, so it's a rare and nonconformant practice. Note that this limitation does not apply to us, as our codegen depends entirely on .proto files, and does not care about the dependencies or SDK locations. Still, I'm reluctant to hook the codegen to such an early phase, unless specifically for Rider. If you can suggest how to positively determine that we are building under Rider, however (some distinguishable property  set?), then I'm fine with such a hack. But I am worrying about breaking other IDEs (e. g. Xamarin) if I do that unchecked in a general case.

Microsoft's own build extensions scripts that augment the Compile list hook up onto the `CoreCompile` item as BeforeTargets, or by modifying the `CoreCompileDependsOn` property. Here's a prime example from from Microsoft.ServiceModel.targets (support for remote Web services metadata, see the Add/Service... item in VS):
```xml
  <Target
    Name="PreXsdCodeGen"
    BeforeTargets="CoreCompile">
```
The same is true for the Workflow Extension, the T4 Text Templating Engine, and Gandalf only knows what else, speaking of MS own tooling. Trying to guess what various MS extensions or 3rd party NuGet packages would add to the Compile list may turn into a never-ending chase.

Unfortunately, this is not all nice and shiny. One notable offender is XAML generation tooling for the classic projects, which infers design-time state not by checking `DesignTimeBuild=true` or `BuildingProject=false`, as it is supposed to, but rather by looking only at `BuildingInsideVisualStudio=true`. For this case, setting the latter is the only option I know of to make it add the files *.i.cs and *.g.cs which are generated from XAML files. The practical hack that I khow of to force build behave as if it were invoked by VS is to invoke either the `Compile` or of `CompileDesignTime` target with the following options set:

* DesignTimeBuild=true
* SkipCompilerExecution=true
* BuildingInsideVisualStudio=true (yes, a moderately dangerous hack, but goes a long way)
* ProvideCommandLineArgs=true

It is also notable that VS itself calls the `Compile` target with the above properties set, and avoids the use of `CompileDesignTime`. I haven't spotted any differences in the behavior, however; I'd rather go the VS way, as this code path is less likely to break.

Also, C++ projects currently use an entirely different scripting and peculiar targets, but I do not know if you guys support C++ builds.

In general, I found the following two tools indispensable for debugging builds, both design/build time in VS and command line MSBuild/dotnet: the [Project System Tools](https://marketplace.visualstudio.com/items?itemName=VisualStudioProductTeam.ProjectSystemTools) extension for VS, which records builds as binlogs inside VS, and the [MSBuild Binary and Structured Log Viewer](http://msbuildlog.com/) to display the binlogs (both from the above extension and `msbuild -bl`; the latter are richer).

I believe I shared the most significant points of what I've learned about different build processes in a few different MS environments. Again, having no idea about your engineering constraints, I am not suggesting that you should lean toward use this approach; this road is also far from being rosy and will indeed also ask for certain hacks for peculiarities in different project types. I thought it would be worth sharing what I've learned in hope you could find this informative.

**Comment by xtmq** [comment] 2019-04-01 07:57
Thank you for so detailed advice, it's really interesting to hear all these thoughts.

First of all I do not think you have to change anything in the targets. The only issue I see - the target `_Protobuf_AugmentLanguageCompile` does not have any dependencies on related (required) targets. 

About design time build. At some point Rider called `Compile` target with `DesignTimeBuild=true`. In the same way as omni-sharp did. But we have faced several issues and this year we want to still call some predefined targets + all 'Compile-item-producers' as I wrote above. Probably we will review and enable design time build for msbuild 16.0 but I'm not sure for now =) 

The short list of reasons for us do NOT call design time build:

1) Performance. Our set of targets loads big solutions 2 times (for dotnet core 3 times) faster than the same 'Compile + DesignTimeBuild' run. 

2) Unlike VS Rider uses a user's toolset and does not have its own (Ok, technically it has, but it is a different story). 
So you just install Rider on the machine and it discovers all msbuild\xbuild installations from .net framework, VS, mono, unity and so on. Then Rider matches required (by solution/projects) and installed (in a build tool) SDKs, targets and API version and some other things and tries to automatically select the best toolset for the current solution automatically. 
Of course you can manually choose the toolset, for example then you are testing msbuild built from sources =) Or then you have a special toolset for the solution (like Roslyn repository).
That all means Rider has to be able to work with various different tools (msbuild from 4.0 to 16.0, win, crossplat and even xbuild). So anyway we have to support the most common subset of targets to load different kind of projects (including cpp, yes). 

3) We had problems with design time build in Xamarin projects. Probably they have fixed all these issues already, but one year ago it was impossible to have a stable load+build+deploy chain with design time build somewhy. But I do not remember exact reasons... 

So for now it is better for us to find, analyze and collect toolkits where our approach does not work (like protobuf). 

By the way Rider has already bundlelled Structured Log Viewer on Windows, in 192 we will add actions to build\load project and immediately show binary logs in viewer.... Wanted to do it in 191, but have no time unfortunately..

**Comment by kkm000** [comment] 2019-04-08 01:56
@xtmq, thanks for chiming in. I did not realize the scale of the problems you are facing, really. Supporting such a variety of build tools is a really, really hard problem.

Regarding `_Protobuf_AugmentLanguageCompile` dependencies, it's a part of sequence that is called by `ProtoBuf_Compile` target:
https://github.com/grpc/grpc/blob/a339a13591cb1fab70abe41ffa03a31d1b196eab/src/csharp/Grpc.Tools/build/_protobuf/Google.Protobuf.Tools.targets#L98-L107

So we could technically say that `Protobuf_ResolvePlatform` depends on `Protobuf_BeforeCompile`, and `_Protobuf_SelectFiles` depends on both`Protobuf_ResolvePlatform` and `Protobuf_BeforeCompile` etc; but it would be a mess and hard to maintain. Such a sequencing semantics is used in MSBuild quite often, for various reasons (different batching requirements; hook-up extension point targets etc). It would not be the best idea to invoke this target by itself; also, the `_` prefix conventionally mark an "internal" target, that external scripts should not hook onto, or explicitly invoke. 

I see where you are coming from: you essentially want to run `Protobuf_Compile` for its side effects only, without actually invoking protoc. This is a very sensible idea. There is currently another project that is integrating the tools, and this code is being changed, too. Currently the invocation is gated by this condition
https://github.com/grpc/grpc/blob/a339a13591cb1fab70abe41ffa03a31d1b196eab/src/csharp/Grpc.Tools/build/_protobuf/Google.Protobuf.Tools.targets#L248-L250

but I remember at one point I asked to rename the variable `Protobuf_DisableDesignTimeBuild` or similar, to keep the naming convention, so its name may also change. Besides this caution, it would be a step up from invoking only a part of the sequence, including internal `_...` targets.

I suggest this: Since our codebase is currently changing, and your part is working, let's use your fix as is, since your users are waiting for it. In case we break you later, or you'd find you need a better solution for another reason, please open an issue here and *tag me* (I do not monitor all issues), and we will figure it out. My best thinking is, if there were a variable that we would know is set only in Rider desgn-time build, it would be fairly easy to augment the condition above condition with e. g.  `... and $(RiderDesignTimeBuild) != 'true'`. This would be more robust than depending on yet-unfinalized variable, in a sense that anyone who changes this code would pay attention to the special case and won't break it. With this in place, you could call the much more public `Protobuf_Compile`, and it would do everything for you end-to-end. This may be just one of possible options; we do not need to design everything right now, just keep it in mind in case there would be an issue later.

**Comment by xtmq** [comment] 2019-04-08 08:59
Ok agreed =) 
I think you can close the issue for now

**Comment by kkm000** [comment] 2019-05-08 05:30
@jtattermusch, this is fixed, please close.

**Closed** 2019-05-14 13:46 UTC
Labels: area/protoc plugins, kind/bug, lang/C#

**Comment by mikebm** [comment] 2019-07-14 19:13
I had to use this same workaround of adding the Target/CallTarget to my csproj in VS2019 on Mac as well. Otherwise intellisense and the using statements could not be resolved.
