### ISSUE TITLE
sync_posix.cc:65 assertion failed: pthread_mutex_lock(mu) == 0

### ISSUE THREAD

**Issue by emrehe** [grpc/grpc#24921] opened 2020-12-07 02:26 UTC
### What version of gRPC and what language are you using?
gRPC 1.27，python 3.6.5

### What operating system (Linux, Windows,...) and version?
CentOS 7.6

### What runtime / compiler are you using (e.g. python version or version of gcc)
python 3.6.5

### What did you do?
Please provide either 1) A unit test for reproducing the bug or 2) Specific steps for us to follow to reproduce the bug. If there’s not enough information to debug the problem, gRPC team may close the issue at their discretion. You’re welcome to re-open the issue once you have a reproduction.

use gRPC to transfer data, the error info shows as: 
sync_posix.cc:65 assertion failed: pthread_mutex_lock(mu) == 0
and the gRPC transfer process will exit, happened randomly after sending out or before sending out. 

### What did you expect to see?
expect to see gRPC sending successfully

### What did you see instead?
he gRPC transfer process will exit, happened randomly after sending out or before sending out. 

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

See [TROUBLESHOOTING.md](https://github.com/grpc/grpc/blob/master/TROUBLESHOOTING.md) for how to diagnose problems better.

**Comment by emrehe** [comment] 2020-12-08 00:56
From former discussion thread, I tried to test on gRPC version 1.20, does not resolve this issue.

**Comment by whuyinpeng** [comment] 2021-01-05 09:13
I’m running a grpc-based service on Rethat 7.7, the kernel version is 3.10.0-1062, the grpc version is v1.11.0.
My server process which been started about two months ago core dump recently, and the backtrace stack is below (printed by backtrace call):
 
grpc/src/core/lib/gpr/sync_posix.cc:48                           ———>  assertion failed: pthread_mutex_lock(mu) == 0 
grpc/src/core/lib/iomgr/ev_epollex_linux.cc:1085           
grpc/src/core/lib/iomgr/ev_epollex_linux.cc:1158
grpc/src/core/lib/iomgr/ev_posix.cc:265
grpc/src/core/lib/iomgr/tcp_posix.cc:207
grpc/src/core/lib/iomgr/tcp_posix.cc:228
grpc/src/core/lib/iomgr/tcp_posix.cc:673
grpc/src/core/lib/iomgr/endpoint.cc:33
grpc/src/core/ext/transport/chttp2/transport/chttp2_transport.cc:1011
grpc/src/core/lib/iomgr/exec_ctx.cc:46
grpc/src/core/lib/iomgr/exec_ctx.cc:129
grpc/src/core/lib/iomgr/exec_ctx.h:97
grpc/src/core/lib/surface/call.cc:1934
grpc/src/cpp/server/server_cc.cc:627

It’s weird that the epollex engine requires kernel version >= 4.5, is there a known bug?
I can’t reproduce the bug in my test environment and it’s all the information I can provide, does that help?

**Comment by whuyinpeng** [comment] 2021-01-05 09:47
I’m running a grpc-based service on Rethat 7.7, the kernel version is 3.10.0-1062, the grpc version is v1.11.0. My server process which been started about two months ago core dump recently, and the backtrace stack is below (printed by backtrace call):
grpc/src/core/lib/gpr/sync_posix.cc:48                ---------> assertion failed: pthread_mutex_lock(mu) == 0  grpc/src/core/lib/iomgr/ev_epollex_linux.cc:1085 grpc/src/core/lib/iomgr/ev_epollex_linux.cc:1158 grpc/src/core/lib/iomgr/ev_posix.cc:265 grpc/src/core/lib/iomgr/tcp_posix.cc:207 grpc/src/core/lib/iomgr/tcp_posix.cc:228 grpc/src/core/lib/iomgr/tcp_posix.cc:673 grpc/src/core/lib/iomgr/endpoint.cc:33 grpc/src/core/ext/transport/chttp2/transport/chttp2_transport.cc:1011 grpc/src/core/lib/iomgr/exec_ctx.cc:46 grpc/src/core/lib/iomgr/exec_ctx.cc:129 grpc/src/core/lib/iomgr/exec_ctx.h:97 grpc/src/core/lib/surface/call.cc:1934 grpc/src/cpp/server/server_cc.cc:627
It’s weird that the epollex engine requires kernel version >= 4.5, is there a known bug? I can’t reproduce the bug in my test environment and it’s all the information I can provide, does that help?

**Comment by gnossen** [comment] 2021-01-05 18:36
@emrehe @whuyinpeng Can either of you provide a reproduction case?

**Comment by whuyinpeng** [comment] 2021-01-06 01:34
@gnossen If the information is not enough, you may ignore it. I'm trying to reproduce the assertion failure, thank you.

**Comment by emrehe** [comment] 2021-01-23 07:43
@gnossen reproduce procedures based on my programs, is the error logs and code lines enough for troubleshooting?

**Comment by gnossen** [comment] 2021-01-25 18:15
@emrehe I'm afraid not. The error message you've included is usually indicative of an OS-level issue, but there's not a lot of other information here to rely on.

> reproduce procedures based on my programs

I don't see a link to a reproduction case in this thread. Am I missing something?

**Comment by XuanWang-Amos** [comment] 2023-04-11 22:13
Closing this issue since we're no longer support versions below 1.46.0, if this issue still exist, please open a new issue.

**Closed by XuanWang-Amos** 2023-04-11 22:13 UTC
Labels: kind/bug, lang/Python, priority/P2
