### ISSUE TITLE
gRPC 1.26.0 not compatible with ruby 2.7.0

### ISSUE THREAD

**Issue by dirkdk** [grpc/grpc#21572] opened 2020-01-02 05:09 UTC
### What version of gRPC and what language are you using?
1.26.0 with Ruby

### What operating system (Linux, Windows,...) and version?
Docker on MacOS with Debian
see https://github.com/docker-library/ruby/blob/e0f00b9a0841c8b0f78faecd07afb4c5754b3c27/2.7/buster/slim/Dockerfile

### What runtime / compiler are you using (e.g. python version or version of gcc)
Ruby 2.7.0

### What did you do?
I configured a new base Docker image from 2.6.5 ruby to 2.7.0 ruby, ran `docker-compose build` and then this failure popped up

### What did you expect to see?
build succeeded

### What did you see instead?
```
Installing googleapis-common-protos-types 1.0.4
Fetching grpc 1.26.0 (x86_64-linux) (was 1.22.0)
Installing grpc 1.26.0 (x86_64-linux) (was 1.22.0)
Gem::RuntimeRequirementNotMetError: grpc requires Ruby version >= 2.3, <
2.7.dev. The current ruby version is 2.7.0.0.
An error occurred while installing grpc (1.26.0), and Bundler cannot continue.
Make sure that `gem install grpc -v '1.26.0'` succeeds before bundling.

In Gemfile:
  google-cloud-logging was resolved to 1.9.3, which depends on
    google-gax was resolved to 1.8.1, which depends on
      googleapis-common-protos was resolved to 1.3.9, which depends on
        grpc
```

**Comment by nicolasnoble** [comment] 2020-01-02 05:13
As ruby 2.7 got released over the holidays, as usual, we won't be able to start supporting it after a few weeks into the new year.

**Comment by brightest-dazes** [comment] 2020-01-02 05:51
What is the reason?

**Comment by nicolasnoble** [comment] 2020-01-02 06:07
People being on holiday and thus being unable to release new packages
during that time.

**Comment by tonobo** [comment] 2020-01-02 10:37
Why strictly pinning the ruby version to < 2.7? Couldn't this prepared before if it's really necessary?

**Comment by nicolasnoble** [comment] 2020-01-02 15:35
The fact it has 2.7.dev means that some work was done to prepare for the final 2.7 release. We will do a final round of testing and checking before letting 2.7 in.

We've been burned many many times with Christmas Ruby releases, with nobody at the office to address issues for a while. This at least prevents explosions.

**Comment by nicolasnoble** [comment] 2020-01-02 15:37
And that issue is in fact a duplicate of #21514. Switching these around.

**Closed by nicolasnoble** 2020-01-02 15:37 UTC
Labels: area/packaging & distribution, kind/bug, lang/ruby, priority/P2
