### ISSUE TITLE
grpc library keeps retrying openssl connection, even though client received certificate expired message from server.

### ISSUE THREAD

**Issue by mkaroshi** [grpc/grpc#23767] opened 2020-08-07 18:53 UTC
### What version of gRPC and what language are you using?
v1.24, go

### What operating system (Linux, Windows,...) and version?
yocto

### What runtime / compiler are you using (e.g. python version or version of gcc)
gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-39.0.3)

### What did you do?
I used go gnmi client, which uses grpc library. The gnmi client tries to establish TLS connection with grpc server, grpc server replies with "Certificate Expired". The gnmi client keeps sending Client Hello, after receiving "Certificate Expired" message.

### What did you expect to see?
gnmi client should not retry after receiving "Certificate Expired" message.

### What did you see instead?
gnmi client keeps retrying(sending client hello)

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).
pcap attached.
[ha.txt](https://github.com/grpc/grpc/files/5043139/ha.txt)

### Anything else we should know about your project / environment?
Opened a jira against openssl. Here is the link
https://github.com/openssl/openssl/issues/12552

**Comment by mkaroshi** [comment] 2020-08-12 18:28
Any update?

**Comment by apolcyn** [comment] 2020-08-12 19:36
This issue does not point out any actual problems. If there is a real problem, please explain, ideally in the form of a reproducibly failing test case. Otherwise, this would appear to be working as intended.

So closing because this seems like a question rather than a bug.

For general questions and troubleshooting, please ask/look for answers at StackOverflow, with "grpc" tag: https://stackoverflow.com/questions/tagged/grpc

For questions that specifically need to be answered by gRPC team members, please ask/look for answers at grpc.io mailing list: https://groups.google.com/forum/#!forum/grpc-io

**Closed by apolcyn** 2020-08-12 19:36 UTC
Labels: kind/bug, priority/P2

**Comment by mkaroshi** [comment] 2020-08-12 20:01
When you receive SSL error message from the server such as certificate expired, the gnmi client which uses grpc library, should not send client hello again. Since the error messages are final. Whats the use of retrying(sending client hello again)?


    On Wednesday, August 12, 2020, 12:37:12 PM PDT, apolcyn <notifications@github.com> wrote:  
 
 


This issue does not point out any actual problems. If there is a real problem, please explain, ideally in the form of a reproducibly failing test case. Otherwise, this would appear to be working as intended.

So closing because this seems like a question rather than a bug.

For general questions and troubleshooting, please ask/look for answers at StackOverflow, with "grpc" tag: https://stackoverflow.com/questions/tagged/grpc

For questions that specifically need to be answered by gRPC team members, please ask/look for answers at grpc.io mailing list: https://groups.google.com/forum/#!forum/grpc-io

**Comment by apolcyn** [comment] 2020-08-12 22:19
For one, it's not clear that the error is final -- what guarantees that the second connect attempt will go to the same exact server and so result in the exact same error, for example?

**Comment by mkaroshi** [comment] 2020-08-12 22:24
Thank you so much for your reply. Your answer makes sense.
    On Wednesday, August 12, 2020, 03:20:04 PM PDT, apolcyn <notifications@github.com> wrote:  
 
 


For one, it's not clear that the error is final -- what guarantees that the second connect attempt will go to the same exact server and so result in the exact same error, for example?
