### ISSUE TITLE
write stream error:GRPC_CALL_ERROR_ALREADY_INVOKED

### ISSUE THREAD

**Issue by fxrrrr** [grpc/grpc#3953] opened 2015-10-24 16:37 UTC
I started using grpc several days ago, and try to use an async server to write steam rpc, but there is an error GRPC_CALL_ERROR_ALREADY_INVOKED.
////rpc def
//service Test{
//  rpc GetList (ListRequest) returns (stream ListReply) {}
//}
////request rpc call
//ServerAsyncWriter<ListReply> writer;
//service_->RequestGetList(&ctx_, &request_, &writer, new_cq_, cq_, this);

when server got the client rpc call, and write several ListReply continuously back to client, like:
//writer.Write(reply1, this);
//writer.Write(reply2, this);  //error
//writer.Write(reply3, this);  
//writer.Finish(Status::OK, this);

there will be an error GRPC_CALL_ERROR_ALREADY_INVOKED.
I trace the code and find because of the "GRPC_IOREQ_SEND_INITIAL_METADATA" op in "static grpc_call_error start_ioreq()".

if after the first "Write", the following steam "Write" are send asynchronous, there will be ok.

I want to know what's the problem here?

**Comment by jcanizales** [comment] 2015-10-30 19:02
CC: @yang-g

**Comment by yang-g** [comment] 2015-11-02 06:31
I think this is a duplicate of #4007

**Closed by yang-g** 2015-11-02 06:31 UTC
Labels: c++
