### ISSUE TITLE
All node tests are failing in interop tests

### ISSUE THREAD

**Issue by adelez** [grpc/grpc#12875] opened 2017-10-06 21:33 UTC
https://kokoro.corp.google.com/job/grpc/job/ubuntu/job/master/job/grpc_interop_tocloud/

Tests start to fail since build 470: 
https://sponge.corp.google.com/target?id=e404c081-00e5-4033-af41-0130df6297f1&target=github/grpc&searchFor=&show=ALL&sortBy=STATUS
All tests timed out.

In this one: https://sponge.corp.google.com/target?id=6191a52e-051b-43db-aa2f-fe3320ca998d&target=github/grpc&searchFor=&show=ALL&sortBy=STATUS
Error becomes:
Failure
node: symbol lookup error: /var/local/git/grpc/src/node/extension_binary/node-v57-linux-x64/grpc_node.node: undefined symbol: grpc_timer_list_init

**Comment by matt-kwong** [comment] 2017-10-06 21:34
Does Node use CMake? It might be related to #12872

**Comment by murgatroid99** [comment] 2017-10-06 21:58
Node does not use CMake.

It looks to me like the problem is that the symbol is getting mangled by the C++ compiler, but the references to the symbol are not getting mangled. For this build, that symbol is defined in `src/core/lib/iomgr/timer_uv.cc`, so this specific error wouldn't be encountered in other builds.

@yashykt This seems related to your PR. Do you know what might have happened there?

**Comment by yashykt** [comment] 2017-10-06 22:24
I remember seeing similar errors (uv errors too) when I was creating my PR, but it was fixed by including the header which declared them as extern "C"

**Comment by murgatroid99** [comment] 2017-10-06 22:28
I see the problem. The function signature is wrong in the function declaration in `timer_uv.cc`, so it's not picking up the `extern "C"` declaration from the header file. I'll send a PR to fix it.

**Comment by yashykt** [comment] 2017-10-06 22:29
grpc_timer_list_init is declared in src/core/lib/iomgr/timer.h which IS included in timer_uv.cc

**Comment by yashykt** [comment] 2017-10-06 22:29
ah OK

**Comment by jtattermusch** [comment] 2017-11-21 06:19
Can this be closed?

**Comment by jtattermusch** [comment] 2017-11-21 06:20
Looks like it has been fixed in  #12885.

**Closed by jtattermusch** 2017-11-21 06:20 UTC
Labels: infra/BUILDPONY, priority/P1
