### ISSUE TITLE
h2_http_proxy_nosec_test and h2_http_proxy_test fail consistently on Windows

### ISSUE THREAD

**Issue by dgquintas** [grpc/grpc#9542] opened 2017-02-01 17:44 UTC
See #9186, #9153, #9088, #9037

If no immediate fix is available, please disable them for the time being.

**Comment by markdroth** [comment] 2017-02-01 17:56
FYI, these tests on Windows have been useful in the past for detecting real bugs, even despite their flakiness.  Disabling them would take away that signal.  It might be better to live with the flakiness until someone has time to fix them.

**Comment by dgquintas** [comment] 2017-02-01 17:58
Fair enough. @nicolasnoble would you be able to give a timeline for a fix?

**Comment by apolcyn** [comment] 2017-03-22 21:19
seen again in pr: #9986 against v1.2.x

log in https://grpc-testing.appspot.com/job/gRPC_pr_win/3733/testReport/junit/(root)/c_windows_opt_native/vsprojects_Release_h2_http_proxy_nosec_test_exe_keepalive_timeout/

**Comment by kpayson64** [comment] 2017-05-04 16:31
Seen Again:
https://grpc-testing.appspot.com/job/gRPC_portability_master_windows/2405/#showFailuresLink

**Comment by jtattermusch** [comment] 2017-05-05 07:15
@nicolasnoble   we can't have an issue marked as P0  stay around for a month. I've made this a P1. If you don't have cycles, please reassign.

**Comment by markdroth** [comment] 2017-05-11 20:18
Seen yet again:

https://grpc-testing.appspot.com/job/gRPC_master_windows/2500/testReport/junit/(root)/c_windows_dbg_native/vsprojects_Debug_h2_http_proxy_test_exe_connectivity/

https://grpc-testing.appspot.com/job/gRPC_master_windows/2500/testReport/junit/(root)/c_windows_opt_native/vsprojects_Release_h2_http_proxy_test_exe_connectivity/

https://grpc-testing.appspot.com/job/gRPC_master_windows/2500/testReport/junit/(root)/c_windows_opt_native/vsprojects_Release_h2_http_proxy_nosec_test_exe_connectivity/

https://grpc-testing.appspot.com/job/gRPC_master_windows/2500/testReport/junit/(root)/c_windows_dbg_native/vsprojects_Debug_h2_http_proxy_nosec_test_exe_connectivity/

Craig's #10802 was supposed to have fixed this.  Anecdotally, I've noticed that since that PR was merged, the "connectivity" test has been failing fairly reliably, but the other tests seem much less flaky now.

**Comment by jtattermusch** [comment] 2017-05-11 20:26
I am looking into this currently, it's a bit tricky because it's hard to reproduce locally. It seems timing sensitive (adding more GRPC_TRACE logs prevents this from happening). Ideas are welcome.

**Comment by makdharma** [comment] 2017-05-17 21:27
I've been debugging this also. I had to modify the windows logging code to collect logs in RAM so it does not affect the timing. The bug is between the proxy and server connection (I think). So far I've seen following steps -
1. Client connects to proxy
2. proxy connects to server - The async ConnectEx from Proxy call succeeds, but the server has not called AcceptEx on its listening socket yet.
3. Client sends data to proxy. Proxy receives successfully.
4. proxy sends this data to server. The synchronous WSASend call succeeds
5. grpc_server_shutdown_and_notify is called on main thread
5. Server AcceptEx the connection from proxy.
7. all server sockets are DisconnectEx and closed.
8. Proxy has no indication of server sockets closed and times out waiting for response..

In the passing case (with a 10 ms sleep after step 2 in proxy), the server sends a GOAWAY that eventually reaches the proxy. The shutdown happens after AcceptEx.

Still debugging..

**Comment by makdharma** [comment] 2017-05-17 22:35
Slight correction -  in step 7 above, all sockets are not closed. Only the listening sockets are closed as part of tpc_server_destroy. The socket that Accepted the call stayed open, hence the proxy had no knowledge of server shutdown.

**Comment by makdharma** [comment] 2017-05-18 17:25
Here's the problem in chttp2_server.c. The on_accept function, when in shutdown state, destroys the endpoint. The grpc_endpoint_destroy code does not shut down the socket. Adding grpc_endpoint_shutdown just before grpc_endpoint_destroy in chttp2_server.c fixes this issue.

**Comment by makdharma** [comment] 2017-05-18 17:26
PR in the works.

**Closed** 2017-05-25 19:11 UTC
Labels: BUILDPONY, P1
