### ISSUE TITLE
FLAKE: //test/cpp/naming:cancel_ares_query_test[x64_windows-fastbuild]

### ISSUE THREAD

**Issue by jtattermusch** [grpc/grpc#20971] opened 2019-11-07 14:21 UTC
Currently our second most common flake on Windows RBE (flakiness rate 8%)

Recent occurrences
https://source.cloud.google.com/results/invocations/c0fe8c4f-e3b0-4d41-92b8-a87919854cc8/targets/%2F%2Ftest%2Fcpp%2Fnaming:cancel_ares_query_test/tests
https://source.cloud.google.com/results/invocations/0e51efd5-d114-45a2-a2a8-abb38cea54b1/targets/%2F%2Ftest%2Fcpp%2Fnaming:cancel_ares_query_test/tests
https://source.cloud.google.com/results/invocations/592af135-8b72-4a79-adec-542b85ac0bc6/targets/%2F%2Ftest%2Fcpp%2Fnaming:cancel_ares_query_test/tests
https://source.cloud.google.com/results/invocations/fad1bdc1-6f71-48a8-b1c6-2b59442beb62/targets/%2F%2Ftest%2Fcpp%2Fnaming:cancel_ares_query_test/tests

```
Executing tests from //test/cpp/naming:cancel_ares_query_test
-----------------------------------------------------------------------------
D1106 18:21:08.375000000  6324 test/core/util/test_config.cc:384] test slowdown factor: sanitizer=1, fixture=1, poller=1, total=1
[==========] Running 5 tests from 1 test suite.
[----------] Global test environment set-up.
[----------] 5 tests from CancelDuringAresQuery
D1106 18:21:08.381000000  6324 src/core/ext/filters/client_channel/resolver/dns/c_ares/dns_resolver_ares.cc:503] Using ares dns resolver
[ RUN      ] CancelDuringAresQuery.TestCancelActiveDNSQuery
[       OK ] CancelDuringAresQuery.TestCancelActiveDNSQuery (32 ms)
[ RUN      ] CancelDuringAresQuery.TestFdsAreDeletedFromPollsetSet
[       OK ] CancelDuringAresQuery.TestFdsAreDeletedFromPollsetSet (6 ms)
[ RUN      ] CancelDuringAresQuery.TestHitDeadlineAndDestroyChannelDuringAresResolutionIsGraceful
D1106 18:21:08.427000000  6324 test/cpp/naming/cancel_ares_query_test.cc:287] TestCancelActiveDNSQuery. query timeout setting: 0
[       OK ] CancelDuringAresQuery.TestHitDeadlineAndDestroyChannelDuringAresResolutionIsGraceful (11 ms)
[ RUN      ] CancelDuringAresQuery.TestHitDeadlineAndDestroyChannelDuringAresResolutionWithQueryTimeoutIsGraceful
D1106 18:21:08.438000000  6324 test/cpp/naming/cancel_ares_query_test.cc:287] TestCancelActiveDNSQuery. query timeout setting: 1
test/cpp/naming/cancel_ares_query_test.cc(365): error: Expected equality of these values:
  status
    Which is: 4
  expected_status_code
    Which is: 14
[  FAILED  ] CancelDuringAresQuery.TestHitDeadlineAndDestroyChannelDuringAresResolutionWithQueryTimeoutIsGraceful (24 ms)
```

https://github.com/grpc/grpc/blob/cc43fd64ab97e45fcdd38759dd8d9eb273823b9e/test/cpp/naming/cancel_ares_query_test.cc#L365

**Comment by jtattermusch** [comment] 2019-11-07 14:24
Looks like the test got GRPC_STATUS_DEADLINE_EXCEEDED instead of the expected GRPC_STATUS_UNAVAILABLE.

**Comment by jtattermusch** [comment] 2019-11-07 14:34
Manual repro
`~/bazel-1.0.0-windows-x86_64.exe --bazelrc=tools/remote_build/windows.bazelrc test --config=windows_opt //test/cpp/naming:cancel_ares_query_test  --runs_per_test=50`

**Comment by jtattermusch** [comment] 2019-11-07 16:02
btw, it looks like that just increasing the 10ms timeout to e.g. 100ms here fixes flake (according to my experiments)
https://github.com/grpc/grpc/blob/cc43fd64ab97e45fcdd38759dd8d9eb273823b9e/test/cpp/naming/cancel_ares_query_test.cc#L317

Note that windows timer has relatively low resolution.

**Comment by apolcyn** [comment] 2019-11-08 09:09
Thanks for the data.

Some notes:

I think this is likely the same bug as https://github.com/grpc/grpc/issues/19880, which I'm seeing as  reproducable at a rate of maybe 3% when ran under `dbg`

A sample failure `cares_resolver` trace log looks like this:

```
[ RUN      ] CancelDuringAresQuery.TestHitDeadlineAndDestroyChannelDuringAresResolutionWithQueryTimeoutIsGraceful
D1108 08:51:57.629701760      18 cancel_ares_query_test.cc:387] hello - apolcyn
D1108 08:51:57.629799348      18 cancel_ares_query_test.cc:287] TestCancelActiveDNSQuery. query timeout setting: 1
D1108 08:51:57.630700867      18 dns_resolver_ares.cc:175]   (c-ares resolver) resolver:0x1066720 AresDnsResolver::StartLocked() is called.
D1108 08:51:57.630728531      18 grpc_ares_wrapper.cc:605]   (c-ares resolver) request:0x1069ef0 c-ares grpc_dns_lookup_ares_locked_impl name=dont-care-since-wont-be-resolved.test.com:1234, default_port=https
D1108 08:51:57.646033435      18 grpc_ares_ev_driver.cc:157] (c-ares resolver) request:0x1069ef0 grpc_ares_ev_driver_create_locked
D1108 08:51:57.646062358      18 grpc_ares_wrapper.cc:381]   (c-ares resolver) request:0x1069ef0 Using DNS server [::1]:3137
D1108 08:51:57.646244004      18 grpc_ares_wrapper.cc:160]   (c-ares resolver) request:0x1069ef0 create_hostbyname_request_locked host:dont-care-since-wont-be-resolved.test.com port:53764 is_balancer:0
D1108 08:51:57.646651873      18 grpc_ares_wrapper.cc:160]   (c-ares resolver) request:0x1069ef0 create_hostbyname_request_locked host:dont-care-since-wont-be-resolved.test.com port:53764 is_balancer:0
D1108 08:51:57.646813784      18 grpc_ares_ev_driver.cc:392] (c-ares resolver) request:0x1069ef0 new fd: c-ares fd: 5
D1108 08:51:57.646824056      18 grpc_ares_ev_driver.cc:98]  (c-ares resolver) request:0x1069ef0 Ref ev_driver 0x1069f90
D1108 08:51:57.646829067      18 grpc_ares_ev_driver.cc:407] (c-ares resolver) request:0x1069ef0 notify read on: c-ares fd: 5
D1108 08:51:57.646837158      18 grpc_ares_ev_driver.cc:465] (c-ares resolver) request:0x1069ef0 ev_driver=0x1069f90 grpc_ares_ev_driver_start_locked. timeout in 3 ms
D1108 08:51:57.646841834      18 grpc_ares_ev_driver.cc:98]  (c-ares resolver) request:0x1069ef0 Ref ev_driver 0x1069f90
D1108 08:51:57.646909412      18 grpc_ares_ev_driver.cc:230] (c-ares resolver) request:0x1069ef0 ev_driver=0x1069f90. next ares process poll time in 1000 ms
D1108 08:51:57.646915886      18 grpc_ares_ev_driver.cc:98]  (c-ares resolver) request:0x1069ef0 Ref ev_driver 0x1069f90
D1108 08:51:57.646924881      18 dns_resolver_ares.cc:445]   (c-ares resolver) resolver:0x1066720 Started resolving. pending_request_:0x1069ef0
test/cpp/naming/cancel_ares_query_test.cc:365: Failure
Expected equality of these values:
  status
    Which is: 4
  expected_status_code
    Which is: 14
D1108 08:51:57.647609976      18 grpc_ares_ev_driver.cc:313] (c-ares resolver) request:0x1069ef0 readable on c-ares fd: 5
D1108 08:51:57.647628206      18 grpc_ares_wrapper.cc:243]   (c-ares resolver) request:0x1069ef0 on_hostbyname_done_locked host=dont-care-since-wont-be-resolved.test.com C-ares status is not ARES_SUCCESS: DNS query cancelled
D1108 08:51:57.647761759      18 grpc_ares_wrapper.cc:243]   (c-ares resolver) request:0x1069ef0 on_hostbyname_done_locked host=dont-care-since-wont-be-resolved.test.com C-ares status is not ARES_SUCCESS: DNS query cancelled
D1108 08:51:57.647778002      18 grpc_ares_ev_driver.cc:105] (c-ares resolver) request:0x1069ef0 Unref ev_driver 0x1069f90
D1108 08:51:57.647804174      18 grpc_ares_ev_driver.cc:119] (c-ares resolver) request:0x1069ef0 delete fd: c-ares fd: 5
D1108 08:51:57.647812813      18 grpc_ares_ev_driver.cc:449] (c-ares resolver) request:0x1069ef0 ev driver stop working
D1108 08:51:57.647839645      18 grpc_ares_ev_driver.cc:105] (c-ares resolver) request:0x1069ef0 Unref ev_driver 0x1069f90
D1108 08:51:57.647849349      18 grpc_ares_ev_driver.cc:247] (c-ares resolver) request:0x1069ef0 ev_driver=0x1069f90 on_timeout_locked. driver->shutting_down=1. err="Cancelled"
D1108 08:51:57.647853712      18 grpc_ares_ev_driver.cc:105] (c-ares resolver) request:0x1069ef0 Unref ev_driver 0x1069f90
D1108 08:51:57.648011886      18 grpc_ares_ev_driver.cc:276] (c-ares resolver) request:0x1069ef0 ev_driver=0x1069f90 on_ares_backup_poll_alarm_locked. driver->shutting_down=1. err="Cancelled"
D1108 08:51:57.648024645      18 grpc_ares_ev_driver.cc:105] (c-ares resolver) request:0x1069ef0 Unref ev_driver 0x1069f90
D1108 08:51:57.648029498      18 grpc_ares_ev_driver.cc:108] (c-ares resolver) request:0x1069ef0 destroy ev_driver 0x1069f90
D1108 08:51:57.648127213      18 dns_resolver_ares.cc:166]   (c-ares resolver) resolver:0x1066720 destroying AresDnsResolver
[  FAILED  ] CancelDuringAresQuery.TestHitDeadlineAndDestroyChannelDuringAresResolutionWithQueryTimeoutIsGraceful (19 ms)
```

The only thing weird here I see (and which I seem to see in all of these failures) is the time diff between:

```
D1108 08:51:57.630728531      18 grpc_ares_wrapper.cc:605]   (c-ares resolver) request:0x1069ef0 c-ares grpc_dns_lookup_ares_locked_impl name=dont-care-since-wont-be-resolved.test.com:1234, default_port=https

```

and

```
D1108 08:51:57.646033435      18 grpc_ares_ev_driver.cc:157] (c-ares resolver) request:0x1069ef0 grpc_ares_ev_driver_create_locked

```

... which is surprisingly long (greater than 10ms, and so would be enough to have the call's 10ms deadline expire before the DNS resolution timer fired, causing the test to get deadline exceeded vs. unavailable and fail). Note that we only <i>start</i> the query timeout <i>after</i> this time period (in `grpc_ares_ev_driver_start_locked`), and so naturally the query timeout doesn't have a chance to kick in.

FWIW during that time is when we call into the c-ares library for the first time to send off initial queries.

**Comment by apolcyn** [comment] 2019-11-08 19:16
A log-timestamp binary search for where the time is coming from shows that 10s of milliseconds are coming from a call to `SplitHostPort`, when ran under `dbg` mode. This likely still points to raising the timeout as the right fix.

```
[ RUN      ] CancelDuringAresQuery.TestHitDeadlineAndDestroyChannelDuringAresResolutionWithQueryTimeoutIsGraceful
D1108 19:13:10.602496284      18 cancel_ares_query_test.cc:387] hello - apolcyn
D1108 19:13:10.602557891      18 cancel_ares_query_test.cc:287] TestCancelActiveDNSQuery. query timeout setting: 1
D1108 19:13:10.603236089      18 dns_resolver_ares.cc:175]   (c-ares resolver) resolver:0x20e0b90 AresDnsResolver::StartLocked() is called.
D1108 19:13:10.603259387      18 grpc_ares_wrapper.cc:615]   (c-ares resolver) request:0x20e4e30 c-ares grpc_dns_lookup_ares_locked_impl name=dont-care-since-wont-be-resolved.test.com:1234, default_port=https
D1108 19:13:10.603266143      18 grpc_ares_wrapper.cc:458]   c-ares inner_resolve_as_ip_literal_locked TOP
D1108 19:13:10.634109293      18 grpc_ares_wrapper.cc:461]   c-ares inner_resolve_as_ip_literal_locked SplitHostPort DONE
D1108 19:13:10.634145202      18 grpc_ares_wrapper.cc:481]   c-ares JoinHostPort TOP
D1108 19:13:10.634153384      18 grpc_ares_wrapper.cc:484]   c-ares inner_resolve_as_ip_literal_locked begin
D1108 19:13:10.634174148      18 grpc_ares_wrapper.cc:495]   c-ares inner_resolve_as_ip_literal_locked done
D1108 19:13:10.634182511      18 grpc_ares_wrapper.cc:624]   (c-ares resolver) request:0x20e4e30 c-ares maybe_resolve_localhost_manually_locked name=dont-care-since-wont-be-resolved.test.com:1234, default_port=https
D1108 19:13:10.634192776      18 grpc_ares_wrapper.cc:634]   (c-ares resolver) request:0x20e4e30 c-ares target_matches_localhost name=dont-care-since-wont-be-resolved.test.com:1234, default_port=https
D1108 19:13:10.634199515      18 grpc_ares_wrapper.cc:645]   (c-ares resolver) request:0x20e4e30 c-ares continue_lookup name=dont-care-since-wont-be-resolved.test.com:1234, default_port=https
D1108 19:13:10.634206693      18 grpc_ares_ev_driver.cc:155] (c-ares resolver) request:0x20e4e30 grpc_ares_ev_driver_create_locked before ares_init_options
D1108 19:13:10.634614454      18 grpc_ares_ev_driver.cc:157] (c-ares resolver) request:0x20e4e30 grpc_ares_ev_driver_create_locked after ares_init_options
D1108 19:13:10.634623152      18 grpc_ares_ev_driver.cc:159] (c-ares resolver) request:0x20e4e30 grpc_ares_ev_driver_create_locked
D1108 19:13:10.634633672      18 grpc_ares_wrapper.cc:381]   (c-ares resolver) request:0x20e4e30 Using DNS server [::1]:30866
D1108 19:13:10.634724469      18 grpc_ares_wrapper.cc:160]   (c-ares resolver) request:0x20e4e30 create_hostbyname_request_locked host:dont-care-since-wont-be-resolved.test.com port:53764 is_balancer:0
D1108 19:13:10.634908964      18 grpc_ares_wrapper.cc:160]   (c-ares resolver) request:0x20e4e30 create_hostbyname_request_locked host:dont-care-since-wont-be-resolved.test.com port:53764 is_balancer:0
D1108 19:13:10.635008493      18 grpc_ares_ev_driver.cc:394] (c-ares resolver) request:0x20e4e30 new fd: c-ares fd: 11
D1108 19:13:10.635015472      18 grpc_ares_ev_driver.cc:98]  (c-ares resolver) request:0x20e4e30 Ref ev_driver 0x20e4ed0
D1108 19:13:10.635019983      18 grpc_ares_ev_driver.cc:409] (c-ares resolver) request:0x20e4e30 notify read on: c-ares fd: 11
D1108 19:13:10.635026857      18 grpc_ares_ev_driver.cc:467] (c-ares resolver) request:0x20e4e30 ev_driver=0x20e4ed0 grpc_ares_ev_driver_start_locked. timeout in 46 ms
D1108 19:13:10.635030789      18 grpc_ares_ev_driver.cc:98]  (c-ares resolver) request:0x20e4e30 Ref ev_driver 0x20e4ed0
D1108 19:13:10.635064163      18 grpc_ares_ev_driver.cc:232] (c-ares resolver) request:0x20e4e30 ev_driver=0x20e4ed0. next ares process poll time in 1000 ms
D1108 19:13:10.635069930      18 grpc_ares_ev_driver.cc:98]  (c-ares resolver) request:0x20e4e30 Ref ev_driver 0x20e4ed0
D1108 19:13:10.635077950      18 dns_resolver_ares.cc:445]   (c-ares resolver) resolver:0x20e0b90 Started resolving. pending_request_:0x20e4e30
test/cpp/naming/cancel_ares_query_test.cc:365: Failure
Expected equality of these values:
  status
    Which is: 4
  expected_status_code
    Which is: 14
D1108 19:13:10.635420325      22 grpc_ares_ev_driver.cc:249] (c-ares resolver) request:0x20e4e30 ev_driver=0x20e4ed0 on_timeout_locked. driver->shutting_down=0. err="No Error"
D1108 19:13:10.635456600      22 grpc_ares_ev_driver.cc:105] (c-ares resolver) request:0x20e4e30 Unref ev_driver 0x20e4ed0
D1108 19:13:10.635468490      22 grpc_ares_ev_driver.cc:315] (c-ares resolver) request:0x20e4e30 readable on c-ares fd: 11
D1108 19:13:10.635477677      22 grpc_ares_wrapper.cc:243]   (c-ares resolver) request:0x20e4e30 on_hostbyname_done_locked host=dont-care-since-wont-be-resolved.test.com C-ares status is not ARES_SUCCESS: DNS query cancelled
D1108 19:13:10.635494188      22 grpc_ares_wrapper.cc:243]   (c-ares resolver) request:0x20e4e30 on_hostbyname_done_locked host=dont-care-since-wont-be-resolved.test.com C-ares status is not ARES_SUCCESS: DNS query cancelled
D1108 19:13:10.635505242      22 grpc_ares_ev_driver.cc:105] (c-ares resolver) request:0x20e4e30 Unref ev_driver 0x20e4ed0
D1108 19:13:10.635511343      22 grpc_ares_ev_driver.cc:119] (c-ares resolver) request:0x20e4e30 delete fd: c-ares fd: 11
D1108 19:13:10.635519070      22 grpc_ares_ev_driver.cc:451] (c-ares resolver) request:0x20e4e30 ev driver stop working
D1108 19:13:10.635527443      22 grpc_ares_ev_driver.cc:105] (c-ares resolver) request:0x20e4e30 Unref ev_driver 0x20e4ed0
D1108 19:13:10.635541786      22 grpc_ares_ev_driver.cc:278] (c-ares resolver) request:0x20e4e30 ev_driver=0x20e4ed0 on_ares_backup_poll_alarm_locked. driver->shutting_down=1. err="Cancelled"
D1108 19:13:10.635550146      22 grpc_ares_ev_driver.cc:105] (c-ares resolver) request:0x20e4e30 Unref ev_driver 0x20e4ed0
D1108 19:13:10.635554820      22 grpc_ares_ev_driver.cc:108] (c-ares resolver) request:0x20e4e30 destroy ev_driver 0x20e4ed0
D1108 19:13:10.635632561      22 dns_resolver_ares.cc:166]   (c-ares resolver) resolver:0x20e0b90 destroying AresDnsResolver
[  FAILED  ] CancelDuringAresQuery.TestHitDeadlineAndDestroyChannelDuringAresResolutionWithQueryTimeoutIsGraceful (33 ms)
[----------] 1 test from CancelDuringAresQuery (33 ms total)

[----------] Global test environment tear-down
[==========] 1 test from 1 test suite ran. (104 ms total)
[  PASSED  ] 0 tests.
[  FAILED  ] 1 test, listed below:
[  FAILED  ] CancelDuringAresQuery.TestHitDeadlineAndDestroyChannelDuringAresResolutionWithQueryTimeoutIsGraceful

 1 FAILED TEST

```

**Comment by apolcyn** [comment] 2019-11-14 04:31
Should be fixed by https://github.com/grpc/grpc/pull/21024

**Closed by apolcyn** 2019-11-14 04:31 UTC
Labels: infra/BUILDPONY, kind/bug, lang/c++, platform/Windows, priority/P2
