### ISSUE TITLE
Not able to compile or create rpm from grpcio-1.38.0.tar.gz

### ISSUE THREAD

**Issue by aafak** [grpc/grpc#26413] opened 2021-06-02 11:03 UTC
### What version of gRPC and what language are you using?
grpc version: 1.38.0
Language: python

### What operating system (Linux, Windows,...) and version?
Linux: centos7

### What runtime / compiler are you using (e.g. python version or version of gcc)
```
[root@masternode grpcio-1.38.0]# python3
Python 3.6.8 (default, Nov 16 2020, 16:55:22)
[GCC 4.8.5 20150623 (Red Hat 4.8.5-44)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>>
[root@masternode ~]# gcc --version
gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-44)
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
[root@masternode ~]#
```

### What did you do?
Please provide either 1) A unit test for reproducing the bug or 2) Specific steps for us to follow to reproduce the bug. If there’s not enough information to debug the problem, gRPC team may close the issue at their discretion. You’re welcome to re-open the issue once you have a reproduction.
Downloaded the tar.gz file from https://pypi.org/project/grpcio/1.38.0/#files
and then try creating rpm using command:

```
python3 setup.py bdist_rpm
```

### What did you expect to see?
rpm creation

### What did you see instead?

```
distutils.errors.DistutilsExecError: command 'gcc' failed with exit status 1
```

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

See [TROUBLESHOOTING.md](https://github.com/grpc/grpc/blob/master/TROUBLESHOOTING.md) for how to diagnose problems better.

### Anything else we should know about your project / environment?

Steps:
Download : https://files.pythonhosted.org/packages/8c/34/7dafc9052bd9b2b41c5a8912aeeca01e179d16de17e9c275633d4b807330/grpcio-1.38.0.tar.gz

```
tar -xvzf grpcio-1.38.0.tar.gz
cd grpcio-1.38.0
python3 setup.py bdist_rpm
```

error:
```
gcc -pthread -DNDEBUG -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -fPIC -D_WIN32_WINNT=1536 -DGPR_BACKWARDS_COMPATIBILITY_MODE=1 -DHAVE_CONFIG_H=1 -DGRPC_ENABLE_FORK_SUPPORT=1 -DPyMODINIT_FUNC=extern "C" __attribute__((visibility ("default"))) PyObject* -DGRPC_POSIX_FORK_ALLOW_PTHREAD_ATFORK=1 -Isrc/python/grpcio -Iinclude -I. -Ithird_party/abseil-cpp -Ithird_party/address_sorting/include -Ithird_party/cares -Ithird_party/cares/cares -Ithird_party/cares/config_linux -Ithird_party/re2 -Ithird_party/boringssl-with-bazel/src/include -Ithird_party/upb -Isrc/core/ext/upb-generated -Isrc/core/ext/upbdefs-generated -Ithird_party/xxhash -Ithird_party/zlib -I/usr/include/python3.6m -c third_party/boringssl-with-bazel/src/crypto/hrss/asm/poly_rq_mul.S -o python_build/temp.linux-x86_64-3.6/third_party/boringssl-with-bazel/src/crypto/hrss/asm/poly_rq_mul.o -std=c++11 -std=gnu99 -fvisibility=hidden -fno-wrapv -fno-exceptions -pthread
creating None
creating None/tmp
creating None/tmp/tmpotdkc3kz
gcc -pthread -DNDEBUG -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -fPIC -I/usr/include/python3.6m -c /tmp/tmpotdkc3kz/a.c -o None/tmp/tmpotdkc3kz/a.o
Traceback (most recent call last):
  File "/usr/lib64/python3.6/distutils/unixccompiler.py", line 127, in _compile
    extra_postargs)
  File "/root/aafak/grpcio/grpcio-1.38.0/python_build/bdist.linux-x86_64/rpm/BUILD/grpcio-1.38.0/src/python/grpcio/_spawn_patch.py", line 54, in _commandfile_spawn
    _classic_spawn(self, command)
  File "/usr/lib64/python3.6/distutils/ccompiler.py", line 909, in spawn
    spawn(cmd, dry_run=self.dry_run)
  File "/usr/lib64/python3.6/distutils/spawn.py", line 36, in spawn
    _spawn_posix(cmd, search_path, dry_run=dry_run)
  File "/usr/lib64/python3.6/distutils/spawn.py", line 159, in _spawn_posix
    % (cmd, exit_status))
distutils.errors.DistutilsExecError: command 'gcc' failed with exit status 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/aafak/grpcio/grpcio-1.38.0/python_build/bdist.linux-x86_64/rpm/BUILD/grpcio-1.38.0/src/python/grpcio/commands.py", line 286, in build_extensions
    build_ext.build_ext.build_extensions(self)
  File "/usr/lib64/python3.6/distutils/command/build_ext.py", line 448, in build_extensions
    self._build_extensions_serial()
  File "/usr/lib64/python3.6/distutils/command/build_ext.py", line 473, in _build_extensions_serial
    self.build_extension(ext)
  File "/usr/lib/python3.6/site-packages/setuptools/command/build_ext.py", line 199, in build_extension
    _build_ext.build_extension(self, ext)
  File "/usr/lib64/python3.6/distutils/command/build_ext.py", line 533, in build_extension
    depends=ext.depends)
  File "/root/aafak/grpcio/grpcio-1.38.0/python_build/bdist.linux-x86_64/rpm/BUILD/grpcio-1.38.0/src/python/grpcio/_parallel_compile_patch.py", line 59, in _parallel_compile
    _compile_single_file, objects)
  File "/usr/lib64/python3.6/multiprocessing/pool.py", line 266, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/usr/lib64/python3.6/multiprocessing/pool.py", line 644, in get
    raise self._value
  File "/usr/lib64/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/usr/lib64/python3.6/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "/root/aafak/grpcio/grpcio-1.38.0/python_build/bdist.linux-x86_64/rpm/BUILD/grpcio-1.38.0/src/python/grpcio/_parallel_compile_patch.py", line 54, in _compile_single_file
    self._compile(obj, src, ext, cc_args, extra_postargs, pp_opts)
  File "/usr/lib64/python3.6/distutils/unixccompiler.py", line 129, in _compile
    raise CompileError(msg)
distutils.errors.CompileError: command 'gcc' failed with exit status 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "setup.py", line 525, in <module>
    cmdclass=COMMAND_CLASS,
  File "/usr/lib/python3.6/site-packages/setuptools/__init__.py", line 129, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib64/python3.6/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib64/python3.6/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/usr/lib64/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/usr/lib64/python3.6/distutils/command/build.py", line 135, in run
    self.run_command(cmd_name)
  File "/usr/lib64/python3.6/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/lib64/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/usr/lib/python3.6/site-packages/setuptools/command/build_ext.py", line 78, in run
    _build_ext.run(self)
  File "/usr/lib64/python3.6/distutils/command/build_ext.py", line 339, in run
    self.build_extensions()
  File "/root/aafak/grpcio/grpcio-1.38.0/python_build/bdist.linux-x86_64/rpm/BUILD/grpcio-1.38.0/src/python/grpcio/commands.py", line 291, in build_extensions
    "Failed `build_ext` step:\n{}".format(formatted_exception))
commands.CommandError: Failed `build_ext` step:
Traceback (most recent call last):
  File "/usr/lib64/python3.6/distutils/unixccompiler.py", line 127, in _compile
    extra_postargs)
  File "/root/aafak/grpcio/grpcio-1.38.0/python_build/bdist.linux-x86_64/rpm/BUILD/grpcio-1.38.0/src/python/grpcio/_spawn_patch.py", line 54, in _commandfile_spawn
    _classic_spawn(self, command)
  File "/usr/lib64/python3.6/distutils/ccompiler.py", line 909, in spawn
    spawn(cmd, dry_run=self.dry_run)
  File "/usr/lib64/python3.6/distutils/spawn.py", line 36, in spawn
    _spawn_posix(cmd, search_path, dry_run=dry_run)
  File "/usr/lib64/python3.6/distutils/spawn.py", line 159, in _spawn_posix
    % (cmd, exit_status))
distutils.errors.DistutilsExecError: command 'gcc' failed with exit status 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/aafak/grpcio/grpcio-1.38.0/python_build/bdist.linux-x86_64/rpm/BUILD/grpcio-1.38.0/src/python/grpcio/commands.py", line 286, in build_extensions
    build_ext.build_ext.build_extensions(self)
  File "/usr/lib64/python3.6/distutils/command/build_ext.py", line 448, in build_extensions
    self._build_extensions_serial()
  File "/usr/lib64/python3.6/distutils/command/build_ext.py", line 473, in _build_extensions_serial
    self.build_extension(ext)
  File "/usr/lib/python3.6/site-packages/setuptools/command/build_ext.py", line 199, in build_extension
    _build_ext.build_extension(self, ext)
  File "/usr/lib64/python3.6/distutils/command/build_ext.py", line 533, in build_extension
    depends=ext.depends)
  File "/root/aafak/grpcio/grpcio-1.38.0/python_build/bdist.linux-x86_64/rpm/BUILD/grpcio-1.38.0/src/python/grpcio/_parallel_compile_patch.py", line 59, in _parallel_compile
    _compile_single_file, objects)
  File "/usr/lib64/python3.6/multiprocessing/pool.py", line 266, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/usr/lib64/python3.6/multiprocessing/pool.py", line 644, in get
    raise self._value
  File "/usr/lib64/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/usr/lib64/python3.6/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "/root/aafak/grpcio/grpcio-1.38.0/python_build/bdist.linux-x86_64/rpm/BUILD/grpcio-1.38.0/src/python/grpcio/_parallel_compile_patch.py", line 54, in _compile_single_file
    self._compile(obj, src, ext, cc_args, extra_postargs, pp_opts)
  File "/usr/lib64/python3.6/distutils/unixccompiler.py", line 129, in _compile
    raise CompileError(msg)
distutils.errors.CompileError: command 'gcc' failed with exit status 1

error: Bad exit status from /var/tmp/rpm-tmp.S4zjQa (%build)


RPM build errors:
    Bad exit status from /var/tmp/rpm-tmp.S4zjQa (%build)
error: command 'rpmbuild' failed with exit status 1
[root@masternode grpcio-1.38.0]#
```

Log files attahed:

[rpm_creation.log](https://github.com/grpc/grpc/files/6584123/rpm_creation.log)
[console_stdoutput.log](https://github.com/grpc/grpc/files/6584140/console_stdoutput.log)

**Comment by gnossen** [comment] 2021-06-02 17:22
Looks like the root of the issue is this:

```
src/core/ext/xds/file_watcher_certificate_provider_factory.cc: In member function 'virtual std::string grpc_core::FileWatcherCertificateProviderFactory::Config::ToString() const':
src/core/ext/xds/file_watcher_certificate_provider_factory.cc:50:73: error: no matching function for call to 'StrFormat(const char [24], const string&)'
         absl::StrFormat("certificate_file=\"%s\", ", identity_cert_file_));
                                                                         ^
src/core/ext/xds/file_watcher_certificate_provider_factory.cc:50:73: note: candidate is:
In file included from src/core/ext/xds/file_watcher_certificate_provider_factory.cc:23:0:
third_party/abseil-cpp/absl/strings/str_format.h:338:34: note: template<class ... Args> std::string absl::lts_20210324::StrFormat(absl::lts_20210324::FormatSpec<Args ...>&, const Args& ...)
 ABSL_MUST_USE_RESULT std::string StrFormat(const FormatSpec<Args...>& format,
                                  ^
third_party/abseil-cpp/absl/strings/str_format.h:338:34: note:   template argument deduction/substitution failed:
src/core/ext/xds/file_watcher_certificate_provider_factory.cc:50:73: note:   mismatched types 'absl::lts_20210324::FormatSpec<Args ...>' and 'const char [24]'
         absl::StrFormat("certificate_file=\"%s\", ", identity_cert_file_));
                                                                         ^
src/core/ext/xds/file_watcher_certificate_provider_factory.cc:54:71: error: no matching function for call to 'StrFormat(const char [24], const string&)'
         absl::StrFormat("private_key_file=\"%s\", ", private_key_file_));
                                                                       ^
src/core/ext/xds/file_watcher_certificate_provider_factory.cc:54:71: note: candidate is:
In file included from src/core/ext/xds/file_watcher_certificate_provider_factory.cc:23:0:
third_party/abseil-cpp/absl/strings/str_format.h:338:34: note: template<class ... Args> std::string absl::lts_20210324::StrFormat(absl::lts_20210324::FormatSpec<Args ...>&, const Args& ...)
 ABSL_MUST_USE_RESULT std::string StrFormat(const FormatSpec<Args...>& format,
                                  ^
third_party/abseil-cpp/absl/strings/str_format.h:338:34: note:   template argument deduction/substitution failed:
src/core/ext/xds/file_watcher_certificate_provider_factory.cc:54:71: note:   mismatched types 'absl::lts_20210324::FormatSpec<Args ...>' and 'const char [24]'
         absl::StrFormat("private_key_file=\"%s\", ", private_key_file_));
                                                                       ^
src/core/ext/xds/file_watcher_certificate_provider_factory.cc:58:72: error: no matching function for call to 'StrFormat(const char [27], const string&)'
         absl::StrFormat("ca_certificate_file=\"%s\", ", root_cert_file_));
                                                                        ^
src/core/ext/xds/file_watcher_certificate_provider_factory.cc:58:72: note: candidate is:
In file included from src/core/ext/xds/file_watcher_certificate_provider_factory.cc:23:0:
third_party/abseil-cpp/absl/strings/str_format.h:338:34: note: template<class ... Args> std::string absl::lts_20210324::StrFormat(absl::lts_20210324::FormatSpec<Args ...>&, const Args& ...)
 ABSL_MUST_USE_RESULT std::string StrFormat(const FormatSpec<Args...>& format,
                                  ^
third_party/abseil-cpp/absl/strings/str_format.h:338:34: note:   template argument deduction/substitution failed:
src/core/ext/xds/file_watcher_certificate_provider_factory.cc:58:72: note:   mismatched types 'absl::lts_20210324::FormatSpec<Args ...>' and 'const char [27]'
         absl::StrFormat("ca_certificate_file=\"%s\", ", root_cert_file_));
                                                                        ^
src/core/ext/xds/file_watcher_certificate_provider_factory.cc:61:70: error: no matching function for call to 'StrFormat(const char [24], const grpc_millis&)'
       absl::StrFormat("refresh_interval=%ldms}", refresh_interval_ms_));
                                                                      ^
src/core/ext/xds/file_watcher_certificate_provider_factory.cc:61:70: note: candidate is:
In file included from src/core/ext/xds/file_watcher_certificate_provider_factory.cc:23:0:
third_party/abseil-cpp/absl/strings/str_format.h:338:34: note: template<class ... Args> std::string absl::lts_20210324::StrFormat(absl::lts_20210324::FormatSpec<Args ...>&, const Args& ...)
 ABSL_MUST_USE_RESULT std::string StrFormat(const FormatSpec<Args...>& format,
                                  ^
third_party/abseil-cpp/absl/strings/str_format.h:338:34: note:   template argument deduction/substitution failed:
src/core/ext/xds/file_watcher_certificate_provider_factory.cc:61:70: note:   mismatched types 'absl::lts_20210324::FormatSpec<Args ...>' and 'const char [24]'
       absl::StrFormat("refresh_interval=%ldms}", refresh_interval_ms_));
```

**Comment by gnossen** [comment] 2021-06-02 19:08
@aafak Admittedly, I've never use `bdist_rpm` before. So far, I haven't been able to successfully build an RPM in the `centos:latest` docker image on either `1.38.0` or `1.37.1`, though my error seems to be different from yours. But `bdist_wheel` does seem to work on both versions, so my initial suspicion that the `absl` source files weren't included doesn't seem to be right.

Could you please confirm the following for me?
 - Are you able to successfully run `bdist_rpm` on `1.37.1`?
 - Are you able to successfully run `bdist_wheel` on `1.38.0`?

And, if possible, can you please provide a reproduction case using, e.g., docker?

**Comment by aafak** [comment] 2021-06-03 07:07
Hi @gnossen Thanks for looking into the issue:
Are you able to successfully run bdist_rpm on 1.37.1? -> No, i was getting the same error 

Are you able to successfully run bdist_wheel on 1.38.0? -> No, getting following error

[root@masternode grpcio]# cd grpcio-1.38.0/
[root@masternode grpcio-1.38.0]# ls
etc      LICENSE   PKG-INFO            README.md         setup.cfg  src
include  Makefile  PYTHON-MANIFEST.in  requirements.txt  setup.py   third_party
[root@masternode grpcio-1.38.0]# python3 setup.py bdist_wheel
Found cython-generated files...
usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
   or: setup.py --help [cmd1 cmd2 ...]
   or: setup.py --help-commands
   or: setup.py cmd --help

error: invalid command 'bdist_wheel'


My doubts was on the following logs:
creating None
creating None/tmp
**creating None/tmp/tmpekhkqlqv**    # This path will not be avialable
gcc -pthread -DNDEBUG -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -fPIC -I/usr/include/python3.6m -c /tmp/tmpekhkqlqv/a.c -o **None/tmp/tmpekhkqlqv/a.o**


-o None/tmp/tmpekhkqlqv/a.o, That Seems that it's attemping to work in an invalid directory, and same is noticed by the issue: https://github.com/grpc/grpc/issues/25112, but i tried the following patch as well, does not worked for me

diff --git a/include/grpc/impl/codegen/port_platform.h b/include/grpc/impl/codegen/port_platform.h
index 33f8a1a59d..a1e812500e 100644
--- a/include/grpc/impl/codegen/port_platform.h
+++ b/include/grpc/impl/codegen/port_platform.h
@@ -168,7 +168,7 @@
 #endif /* _LP64 */
 #ifdef __GLIBC__
 #define GPR_POSIX_CRASH_HANDLER 1
-#define GPR_LINUX_PTHREAD_NAME 1
+#define GPR_LINUX_PTHREAD_NAME 0
 #include <linux/version.h>
 #else /* musl libc */
 #define GPR_MUSL_LIBC_COMPAT 1


can you please provide a reproduction case using, e.g., docker?-> I was running it on Centos7 VM,

Note: I was able to create RPM for protobuf and grpcio-tools packages by using the same command(python3 setup.py bdist_rpm), it is working fine

**Comment by aafak** [comment] 2021-06-04 09:56
In ubuntu, i could do the python3 setup.py bdist_wheel, it ran successfully

**Comment by SchrodingerZhu** [comment] 2021-06-08 00:13
gcc was too old.

**Comment by syslogic** [comment] 2021-09-10 16:29
CentOS 7 is the problem ...while CentOS 8 kernel is built with a later version of `gcc`.

**Comment by XuanWang-Amos** [comment] 2023-04-11 22:11
Closing this issue since we're no longer support versions below 1.46.0, if this issue still exist, please open a new issue.

**Closed by XuanWang-Amos** 2023-04-11 22:11 UTC
Labels: kind/bug, lang/Python, priority/P2
