### ISSUE TITLE
many cloud_to_cloud interop tests failing with go server

### ISSUE THREAD

**Issue by markdroth** [grpc/grpc#12723] opened 2017-09-26 20:02 UTC
https://sponge.corp.google.com/target?id=5e73c255-517c-445f-a5ab-f1dde04f0006&target=github/grpc&searchFor=&show=ALL&sortBy=STATUS

One random example is the cloud_to_cloud:c++:go_server:ping_pong test, which failed like this:

```
Failure
I0926 17:45:08.468904085       1 client.cc:91]               Testing these cases: ping_pong
E0926 17:45:08.471428320       1 interop_client.cc:695]      DoPingPong(): stream->Write() failed. i: 0
```

**Comment by menghanl** [comment] 2017-09-27 17:40
This was caused by https://github.com/grpc/grpc-go/pull/1539. The PR has been reverted in https://github.com/grpc/grpc-go/pull/1541.
Closing this issue now.

**Closed by menghanl** 2017-09-27 17:40 UTC
Labels: infra/BUILDPONY
