### ISSUE TITLE
RECV_STATUS_ON_CLIENT (with OK status) shows up in the completion queue before RECV_MESSAGE

### ISSUE THREAD

**Issue by jcanizales** [grpc/grpc#6207] opened 2016-04-18 19:00 UTC
See logs at #6117.

**Comment by hsaliak** [comment] 2016-04-19 19:05
@nicolasnoble could you comment on this issue?

**Comment by dgquintas** [comment] 2016-04-20 02:20
Maybe related: https://travis-ci.org/grpc/grpc/jobs/124356162

**Comment by makdharma** [comment] 2016-04-20 16:24
Here's the relevant lines from client log.

I0418 10:34:35.088334000 4508401664 call.c:1473] grpc_call_start_batch(call=0x7f823a00ce00, ops=0x7f8239542000, nops=1, tag=0x7f82395414a0, reserved=0x0)
I0418 10:34:35.088488000 4508401664 call.c:1185] ops[0]: SEND_INITIAL_METADATA
I0418 10:34:35.089161000 4508401664 call.c:1473] grpc_call_start_batch(call=0x7f823a00ce00, ops=0x7f82397bae30, nops=1, tag=0x7f82397bae80, reserved=0x0)
I0418 10:34:35.089326000 4508401664 call.c:1185] ops[0]: RECV_INITIAL_METADATA ptr=0x7f8239542730
I0418 10:34:35.089773000 4508401664 call.c:1473] grpc_call_start_batch(call=0x7f823a00ce00, ops=0x7f82397bae30, nops=1, tag=0x7f82397baf30, reserved=0x0)
I0418 10:34:35.089921000 4508401664 call.c:1185] ops[0]: RECV_STATUS_ON_CLIENT metadata=0x7f82394c6f98 status=0x7f82394c6f80 details=0x7f82394c6f88
I0418 10:34:35.090397000 123145303453696 call.c:1473] grpc_call_start_batch(call=0x7f823a00ce00, ops=0x7f823bb00dc0, nops=1, tag=0x7f823bb00e10, reserved=0x0)
I0418 10:34:35.090563000 123145303453696 call.c:1185] ops[0]: SEND_MESSAGE ptr=0x7f82394c7240
I0418 10:34:35.187737000 123145305063424 completion_queue.c:346] RETURN_EVENT[0x7f823960c130]: OP_COMPLETE: tag:0x7f82395414a0 OK
I0418 10:34:35.187854000 123145305063424 completion_queue.c:346] RETURN_EVENT[0x7f823960c130]: OP_COMPLETE: tag:0x7f823bb00e10 OK
I0418 10:34:35.187946000 123145303453696 call.c:1473] grpc_call_start_batch(call=0x7f823a00ce00, ops=0x7f82394ca760, nops=1, tag=0x7f82394c7350, reserved=0x0)
I0418 10:34:35.188004000 123145303453696 call.c:1185] ops[0]: SEND_CLOSE_FROM_CLIENT
I0418 10:34:35.188339000 123145305063424 completion_queue.c:346] RETURN_EVENT[0x7f823960c130]: OP_COMPLETE: tag:0x7f82394c7350 OK
I0418 10:34:35.575792000 123145305063424 completion_queue.c:346] RETURN_EVENT[0x7f823960c130]: OP_COMPLETE: tag:0x7f82397bae80 OK
I0418 10:34:35.576128000 123145303453696 call.c:1473] grpc_call_start_batch(call=0x7f823a00ce00, ops=0x7f8239548ba0, nops=1, tag=0x7f8239548bf0, reserved=0x0)
I0418 10:34:35.576259000 123145303453696 call.c:1185] ops[0]: RECV_MESSAGE ptr=0x7f8239548b10
I0418 10:34:35.576852000 123145305063424 completion_queue.c:346] RETURN_EVENT[0x7f823960c130]: OP_COMPLETE: tag:0x7f82397baf30 OK
/Users/makarandd/Work/gitx/grpc_flake_debug/src/objective-c/tests/InteropTests.m:100: error: -[InteropTestsRemote testEmptyUnaryRPC] : ((error) == nil) failed: "Error Domain=io.grpc Code=13 "The writer finished without producing any value." UserInfo={NSLocalizedDescription=The wriI0418 10:34:35.577315000 123145305063424 completion_queue.c:346] RETURN_EVENT[0x7f823960c130]: OP_COMPLETE: tag:0x7f8239548bf0 OK

**Comment by nicolasnoble** [comment] 2016-04-20 21:15
So... I'm not sure this is a problem. Or at least, I don't see that as an issue. The SEND_CLOSE is a half close. You're basically sending to the server the notification you're done with sending any further queries, and you're getting the acknowledgement of that. You can still receive replies after that point however, which is what is happening here.

**Comment by jcanizales** [comment] 2016-04-20 23:37
The problem is unrelated to SEND_CLOSE. It's RECV_STATUS_ON_CLIENT (with OK status) showing up in the completion queue before RECV_MESSAGE

**Comment by jcanizales** [comment] 2016-04-20 23:38
For the problem that causes, see #6117.

**Comment by ctiller** [comment] 2016-04-21 23:48
Does the RECV_MESSAGE contain a non-null pointer?

**Comment by makdharma** [comment] 2016-04-22 16:23
Here are the relevant lines from the log. Seems like RECV_MESSAGE has non-null ptr (just from the log print).
I0418 10:34:35.088334000 4508401664 call.c:1473] grpc_call_start_batch(call=0x7f823a00ce00, ops=0x7f8239542000, nops=1, tag=0x7f82395414a0, reserved=0x0)
I0418 10:34:35.088488000 4508401664 call.c:1185] ops[0]: SEND_INITIAL_METADATA
I0418 10:34:35.089161000 4508401664 call.c:1473] grpc_call_start_batch(call=0x7f823a00ce00, ops=0x7f82397bae30, nops=1, tag=0x7f82397bae80, reserved=0x0)
I0418 10:34:35.089326000 4508401664 call.c:1185] ops[0]: RECV_INITIAL_METADATA ptr=0x7f8239542730
I0418 10:34:35.089773000 4508401664 call.c:1473] grpc_call_start_batch(call=0x7f823a00ce00, ops=0x7f82397bae30, nops=1, tag=0x7f82397baf30, reserved=0x0)
I0418 10:34:35.089921000 4508401664 call.c:1185] ops[0]: RECV_STATUS_ON_CLIENT metadata=0x7f82394c6f98 status=0x7f82394c6f80 details=0x7f82394c6f88
I0418 10:34:35.090397000 123145303453696 call.c:1473] grpc_call_start_batch(call=0x7f823a00ce00, ops=0x7f823bb00dc0, nops=1, tag=0x7f823bb00e10, reserved=0x0)
I0418 10:34:35.090563000 123145303453696 call.c:1185] ops[0]: SEND_MESSAGE ptr=0x7f82394c7240
I0418 10:34:35.187737000 123145305063424 completion_queue.c:346] RETURN_EVENT[0x7f823960c130]: OP_COMPLETE: tag:0x7f82395414a0 OK
I0418 10:34:35.187854000 123145305063424 completion_queue.c:346] RETURN_EVENT[0x7f823960c130]: OP_COMPLETE: tag:0x7f823bb00e10 OK
I0418 10:34:35.187946000 123145303453696 call.c:1473] grpc_call_start_batch(call=0x7f823a00ce00, ops=0x7f82394ca760, nops=1, tag=0x7f82394c7350, reserved=0x0)
I0418 10:34:35.188004000 123145303453696 call.c:1185] ops[0]: SEND_CLOSE_FROM_CLIENT
I0418 10:34:35.188339000 123145305063424 completion_queue.c:346] RETURN_EVENT[0x7f823960c130]: OP_COMPLETE: tag:0x7f82394c7350 OK
I0418 10:34:35.575792000 123145305063424 completion_queue.c:346] RETURN_EVENT[0x7f823960c130]: OP_COMPLETE: tag:0x7f82397bae80 OK
I0418 10:34:35.576128000 123145303453696 call.c:1473] grpc_call_start_batch(call=0x7f823a00ce00, ops=0x7f8239548ba0, nops=1, tag=0x7f8239548bf0, reserved=0x0)
I0418 10:34:35.576259000 123145303453696 call.c:1185] ops[0]: RECV_MESSAGE ptr=0x7f8239548b10
I0418 10:34:35.576852000 123145305063424 completion_queue.c:346] RETURN_EVENT[0x7f823960c130]: OP_COMPLETE: tag:0x7f82397baf30 OK
/Users/makarandd/Work/gitx/grpc_flake_debug/src/objective-c/tests/InteropTests.m:100: error: -[InteropTestsRemote testEmptyUnaryRPC] : ((error) == nil) failed: "Error Domain=io.grpc Code=13 "The writer finished without producing any value." UserInfo={NSLocalizedDescription=The wriI0418 10:34:35.577315000 123145305063424 completion_queue.c:346] RETURN_EVENT[0x7f823960c130]: OP_COMPLETE: tag:0x7f8239548bf0 OK

**Comment by jcanizales** [comment] 2016-04-22 17:01
That's for the `start_batch`. As of the event received in the cq, the log only shows this:
```
I0418 10:34:35.577315000 123145305063424 completion_queue.c:346] RETURN_EVENT[0x7f823960c130]: OP_COMPLETE: tag:0x7f8239548bf0 OK
```
A response is expected in this RPC in any case.

**Comment by ctiller** [comment] 2016-04-22 21:41
So if the out byte buffer pointer for RECV_MESSAGE is null (IE `*grpc_op::data::recv_message==NULL`), then we've got end of stream, and that's completely legal to come after the return of an OK status.

**Comment by jcanizales** [comment] 2016-04-22 21:50
If it is null, the problem is no response was produced by the server library before sending the OK status.

If it isn't null, the problem is the ordering of events in the completion queue.

Makarand's log at #6117 has the bytes read from the socket; I'm not sure how to decode them.

**Comment by makdharma** [comment] 2016-04-27 23:27
Confirmed (by adding a log printf in GRPCCall.m:197) that the grpc_byte_buffer* returned with the RECV_MESSAGE callback is non-null. ctiller@ will attempt to decode the raw bytes from this log - https://github.com/grpc/grpc/files/224378/failed_log.txt

**Comment by deljero2** [comment] 2016-05-03 16:57
Following this from https://github.com/grpc/grpc/issues/6002, any update on this issue?

**Comment by jcanizales** [comment] 2016-05-11 21:11
@bexc FYI

**Comment by makdharma** [comment] 2016-05-17 21:27
I tried to reproduce this problem from the latest build but unable to reproduce. It is quite possible that the underlying root cause is fixed by some PR already.

**Comment by jcanizales** [comment] 2016-07-01 17:10
Hi @aa57779111, what version of gRPC are you using?

**Comment by aa57779111** [comment] 2016-07-02 14:51
@jcanizales 0.13.0,

**Comment by jcanizales** [comment] 2016-07-04 17:37
0.14 was just released a few days ago; would you mind trying it? I think this bug was solved sometime between the two versions.

Notice that to use 0.14, the local podspecs to generate code from .proto files has changed a bit. Refer to the updated template at https://github.com/grpc/grpc/tree/release-0_14/src/objective-c#cocoapods

**Comment by aa57779111** [comment] 2016-07-05 04:27
@jcanizales  hi , I have another problem. I have been upgraded to 0.14.0, but There is an error, in xxxxservice.pbrpc.h, google/protobuf/Descriptor.pbobjc.h file not found, Is not the configuration of what I have less
![snip20160705_4](https://cloud.githubusercontent.com/assets/8300449/16573926/d6138e70-42ab-11e6-811a-a8e6010ee289.png)

**Comment by jcanizales** [comment] 2016-07-06 03:10
Oh, that's a bug in the code generator! Could you please file a new issue for it and attach that image?

(Also, I'm curious: What are you importing `"google/protobuf/descriptor.proto"` for?)

**Comment by aa57779111** [comment] 2016-07-06 15:05
@jcanizales Thank you very much.This `"google/protobuf/descriptor.proto"` degradation processing,
We don't need it now. so remove it. grpc now is 0.14.0, but BoringSSL has a error , openssl/arm_arch.h file not found.

![boringsslerror](https://cloud.githubusercontent.com/assets/8300449/16622772/dfab1444-43cd-11e6-96f3-15074afd2a8c.png)

**Comment by jcanizales** [comment] 2016-07-07 01:26
Hi @aa57779111, please don't reuse the same thread for problems that are different to the original one, instead open a new Issue. Otherwise, when I want to follow up with you I have no way to find this thread and have to spend a lot of time just searching for it.

**Comment by jcanizales** [comment] 2016-07-07 01:27
(It will also prevent sending notifications to people that were subscribed to the original Issue, but have nothing to do with the new one you've found).

**Comment by aa57779111** [comment] 2016-07-07 02:07
I'm sorry to have caused you trouble.I will open a new Issue for that, Thank you once again.

**Comment by jtattermusch** [comment] 2017-12-11 22:32
No activity here for >1 year, closing.

**Closed by jtattermusch** 2017-12-11 22:32 UTC
Labels: area/core, disposition/cannot reproduce, priority/P2
