### ISSUE TITLE
grpc 1.43.1 server error : benign_reclaimer

### ISSUE THREAD

**Issue by lsh235** [grpc/grpc#29696] opened 2022-05-16 06:19 UTC
`static void post_benign_reclaimer(grpc_chttp2_transport* t) {
  if (!t->benign_reclaimer_registered) {
    t->benign_reclaimer_registered = true;
    GRPC_CHTTP2_REF_TRANSPORT(t, "benign_reclaimer");
    t->memory_owner.PostReclaimer(
        grpc_core::ReclamationPass::kBenign,
        [t](absl::optional<grpc_core::ReclamationSweep> sweep) {
          if (sweep.has_value()) {
            GRPC_CLOSURE_INIT(&t->benign_reclaimer_locked,
                              benign_reclaimer_locked, t,
                              grpc_schedule_on_exec_ctx);
            t->active_reclamation = std::move(*sweep);
            t->combiner->Run(&t->benign_reclaimer_locked, GRPC_ERROR_NONE);
          } else {
            **GRPC_CHTTP2_UNREF_TRANSPORT(t, "benign_reclaimer");**
          }
        });
  }
}`

wmic:root\cli>cpu list brief /format:list
Caption=Intel64 Family 6 Model 165 Stepping 5
DeviceID=CPU0
Manufacturer=GenuineIntel
MaxClockSpeed=2904
Name=Intel(R) Core(TM) i7-10700 CPU @ 2.90GHz
SocketDesignation=CPUSocket

grpc build
cmake -G "Visual Studio 15 2017" -A Win32 ../..
cmake_install.cmake Release -> Debug change

ide
visual studio 2017

sdk
10.0.17763.0

I built version 1.43.1 of grpc and used it well. However, at some point, the error occurs on the server.
![image](https://user-images.githubusercontent.com/57898747/168530842-5b0bcd40-ee5b-47c8-b75c-cf41b8528650.png)
![image](https://user-images.githubusercontent.com/57898747/168530785-50dc71c4-675b-4ee5-8440-6ed601f2f82e.png)

Please let me know if you know the solution Thank you.

**Comment by drfloob** [comment] 2022-05-17 18:48
Are you running an unmodified version of the greeter example? Without seeing the application code that generates this crash, it's tough to determine if this is a gRPC bug or not.

**Comment by lsh235** [comment] 2022-05-18 00:20
> Greetinger 예제의 수정되지 않은 버전을 실행하고 있습니까? 이 충돌을 생성하는 애플리케이션 코드를 보지 않고는 이것이 gRPC 버그인지 여부를 판별하기 어렵습니다.

Yes, I'm using an unmodified code.
I used the code in "examples/cpp/helloworld" as instructed here in "https://grpc.io/docs/languages/cpp/quickstart/".

I will let you know if I need to let you know more information.
It's my first time asking a question on git hub, so please understand if I'm clumsy.
I hope you have a nice day.

**Comment by lsh235** [comment] 2022-05-18 00:22
I pressed the wrong thing.

**Comment by lsh235** [comment] 2022-05-18 00:23
I pressed the wrong thing.

**Comment by teenccu** [comment] 2022-06-18 16:45
Hello,

I am having the same issue as I updated the libraries from grpcv1.46.3 .
For creating the static libraries I followed the instructions in 
https://github.com/grpc/grpc/blob/master/BUILDING.md
To create visual studio projects/soln file I did 
cmake -B .build -DCMAKE_INSTALL_PREFIX=install -G "Visual Studio 15 2017" -T v141
I built the project by building ALL_BUILD project  using windows sdk was 10.0.14393.0 to generate the static libraries.
Installation is done by the INSTALL project.
When I build my application with these libraries my client/server both are crashing when the client object is going out of scope and trying to destroy the _stub.
![image](https://user-images.githubusercontent.com/63601028/174448248-b675aea0-0b9a-493d-9182-cdb04639eefc.png)

However, I did not see the issue from some existing libraries from v1.38

Thanks for any help.

**Comment by 03530038** [comment] 2022-08-29 07:44
I also have the same problem with the x86 version of grpc v1.48.0. (The x64 version did not have any problems)

GRPC Version
	v1.48.0 (Win32)
OS
	Windows 10 2016 LTSB
IDE
	Visual Studio 2017 15.9.49
SDK
	10.0.17763.0
	
・When grpc is installed as _vcpkg install grpc[codegen]_
・create an sln file with _cmake .. -G "Visual Studio 15 2017"_ from the source code and create a static library with _cmake --build . --config Release_
In both cases, building the application ("example/cpp/helloworld") with these libraries crashes both client and server on client exit.
Is there a workaround for using it with the grpc x86 version?

![image](https://user-images.githubusercontent.com/90310262/187150283-51540919-43d0-4939-8723-22fed2fa9a3e.png)

**Comment by lsh235** [comment] 2022-08-29 09:11
@teenccu @03530038 Sorry for the late reply. In my case, I solved it by lowering the version. 
I think it was the 1.3x version.

**Comment by 03530038** [comment] 2022-08-30 04:54
@lsh235 
Thank you for the information. I've confirmed that v1.42 is fine in my case, so I'll use that version

**Comment by qing666888** [comment] 2022-10-12 11:28
I also have the same problem with the x86 version of grpc v1.49.0
![1665574050445](https://user-images.githubusercontent.com/5969529/195331056-a911f815-87f1-4e8e-96bc-a1751d00a83a.png)

**Comment by drfloob** [comment] 2022-10-19 17:55
Based on the screenshots provided, I believe this is a duplicate of https://github.com/grpc/grpc/issues/29979, regarding a visual studio bug with certain non-English locales. It seems the fix was incomplete, since it landed in the 1.47.x versions and later. The visual studio build configuration likely needs to be modified to build with `/utf-8`. If anyone would like to experiment and propose a fix, that would be appreciated.

**Comment by qing666888** [comment] 2022-11-04 06:30
> @lsh235 Thank you for the information. I've confirmed that v1.42 is fine in my case, so I'll use that version
![image](https://user-images.githubusercontent.com/5969529/199906470-fc31cad2-1fd3-4a80-a8cf-82a26fa71a89.png)
no version 1.42.0，v1.41.0 is fine in my case

**Comment by drfloob** [comment] 2023-04-25 19:47
Thanks for confirming!

**Closed by drfloob** 2023-04-25 19:47 UTC
Labels: disposition/help wanted
