### ISSUE TITLE
Choose docgen solution and set it up

### ISSUE THREAD

**Issue by jcanizales** [grpc/grpc#2582] opened 2015-07-21 21:40 UTC
Maybe Cocoadocs?

**Comment by jcanizales** [comment] 2015-08-02 21:12
Note: AFNetworking hosts its docs in Cocoadocs, and seems to generate them with [appledoc](http://gentlebytes.com/appledoc/)?

**Comment by jayantkolhe** [comment] 2015-08-13 20:08
Closing as dupe of #2853

**Closed by jayantkolhe** 2015-08-13 20:08 UTC
Labels: ObjC, wrapped languages
