### ISSUE TITLE
GLIBCXX_3.4.29 not found in v1.41.0

### ISSUE THREAD

**Issue by rlarss** [grpc/grpc#27503] opened 2021-09-28 14:26 UTC
### What version of gRPC and what language are you using?
1.41.0 | Python3.9

### What operating system (Linux, Windows,...) and version?
Docker image Debian bullseye-slim on a Raspberry Pi 4.

### What runtime / compiler are you using (e.g. python version or version of gcc)
python3.9, gcc=4:10.2.1-1

### What did you do?
```python
root@7c9a2680c3ca:/# pip install grpcio==1.41.0 grpcio-tools==1.41.0
Collecting grpcio==1.41.0
  Using cached grpcio-1.41.0-cp39-cp39-linux_armv7l.whl (48.3 MB)
Collecting grpcio-tools==1.41.0
  Using cached grpcio_tools-1.41.0-cp39-cp39-linux_armv7l.whl (36.6 MB)
Requirement already satisfied: six>=1.5.2 in /usr/lib/python3/dist-packages (from grpcio==1.41.0) (1.16.0)
Requirement already satisfied: protobuf<4.0dev,>=3.5.0.post1 in /usr/local/lib/python3.9/dist-packages (from grpcio-tools==1.41.0) (3.18.0)
Requirement already satisfied: setuptools in /usr/lib/python3/dist-packages (from grpcio-tools==1.41.0) (52.0.0)
Installing collected packages: grpcio, grpcio-tools
  Attempting uninstall: grpcio
    Found existing installation: grpcio 1.38.1
    Uninstalling grpcio-1.38.1:
      Successfully uninstalled grpcio-1.38.1
  Attempting uninstall: grpcio-tools
    Found existing installation: grpcio-tools 1.38.1
    Uninstalling grpcio-tools-1.38.1:
      Successfully uninstalled grpcio-tools-1.38.1
Successfully installed grpcio-1.41.0 grpcio-tools-1.41.0
root@7c9a2680c3ca:/# python3 -c "from grpc_tools import _protoc_compiler"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: /usr/lib/arm-linux-gnueabihf/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by /usr/local/lib/python3.9/dist-packages/grpc_tools/_protoc_compiler.cpython-39-arm-linux-gnueabihf.so)
```

### What did you expect to see?
Expected GLIBCXX_3.4.29 to be found.

### What did you see instead?
GLIBCXX_3.4.29 was not found.

### Anything else we should know about your project / environment?
```python
root@7c9a2680c3ca:/# ls /usr/lib/arm-linux-gnueabihf/libstdc++.so.6
libstdc++.so.6       libstdc++.so.6.0.28
```

**Comment by XuanWang-Amos** [comment] 2023-11-09 18:52
Close as duplicate of #34888

**Closed by XuanWang-Amos** 2023-11-09 18:52 UTC
Labels: kind/bug, lang/Python, priority/P2
