### ISSUE TITLE
grpc_connectivity_state was GRPC_CHANNEL_READY, but GRPC completion queue AsyncNext next status was always TIMEOUT

### ISSUE THREAD

**Issue by calvinzhangclx** [grpc/grpc#29136] opened 2022-03-17 13:48 UTC
### What version of gRPC and what language are you using?
version: 1.14.1
language: C++

### What operating system (Linux, Windows,...) and version?
system: Linux

### What runtime / compiler are you using (e.g. python version or version of gcc)
gcc: 5.4.0

### What did you do?
Please provide either 1) A unit test for reproducing the bug or 2) Specific steps for us to follow to reproduce the bug. If there’s not enough information to debug the problem, gRPC team may close the issue at their discretion. You’re welcome to re-open the issue once you have a reproduction.

The steps to reproduce the issue(can't be reproduced every time):
1. Make grpc client connect to collector and stream fine;
2. Make a network issue between client and collector(we can simulate this, like when client sends data to collector, but collector gives no response);
3. While network issue happens, keep checking the next status of completion queue(before this have add a tag to the completion queue). The next status of completion queue will always be TIMEOUT, but the channel state is GRPC_CHANNEL_READY;
4. After a while recovering the network, in most cases the previously grpc connection can recover. But sometimes, the grpc connection can't recover, the next status of completion queue was still TIMEOUT.
### What did you expect to see?
After network recovered, the AsyncNext() should return GOT_EVENT for the previous completion queue tag.

### What did you see instead?
After network recovered, the AsyncNext() didn't return GOT_EVENT for the previous completion queue tag. It kept returning TIMEOUT.

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

See [TROUBLESHOOTING.md](https://github.com/grpc/grpc/blob/master/TROUBLESHOOTING.md) for how to diagnose problems better.

**Comment by calvinzhangclx** [comment] 2022-03-24 05:41
Hi @markdroth , below is my code. I simplify it. Just FYI. Thanks.

**Code Begin**
`enum cq_tag {CONNECT, READ, WRITE, WRITE_DONE, FINISH};
enum next_status {
    SHUTDOWN,   ///< The completion queue has been shutdown and fully-drained
    GOT_EVENT,  ///< Got a new event; \a tag will be filled in with its
                ///< associated value; \a ok indicating its success.
    TIMEOUT,    ///< deadline was reached.
    UNKNOWN
};

std::unique_ptr<ClientAsyncReaderWriter<IPPacket, IPPacket>> readWriter;
IPPacket *ptr_request;
CompletionQueue cq;

bool get_cq_status (cq_tag tag, next_status* status)
{
    bool ok = false;
    void* got_tag;
    std::chrono::system_clock::time_point deadline = std::chrono::system_clock::now() + std::chrono::milliseconds(5000);
    CompletionQueue::NextStatus asyncStatus;

    asyncStatus = cq.AsyncNext(&got_tag, &ok, deadline);

    if (asyncStatus == CompletionQueue::SHUTDOWN) {
        *status = SHUTDOWN;
        return false;
    }
    else if (asyncStatus == CompletionQueue::GOT_EVENT) {
        *status = GOT_EVENT;
        if (ok && (got_tag == (void*)tag)){
            return true;
        }
        if (!ok && (got_tag == (void*)tag)) {
            return false;
        }
    }
    else if (asyncStatus == grpc::CompletionQueue::TIMEOUT) {
        *status = TIMEOUT;
        return false;
    }
    *status = UNKNOWN;
    return false;
}

bool Tunnel()
{
	// other processes such as connect, read to establish the connection between client and collector

	while (!p_dialout_data->parsed_response.empty())
	{
		ptr_request = new IPPacket(); 
		ptr_request->set_packet(p_dialout_data->parsed_response);
		readWriter->Write(*ptr_request, (void*)WRITE);
		if (get_cq_status(WRITE, &nx_status)) {
			// success process
		}
		else {
			if (SHUTDOWN == nx_status) {
				// shutdown process
				return false;
			}
			if (TIMEOUT == nx_status) {
				// timeout process, after network issue recovered in 1min, the next status was always timeout
				while (TIMEOUT == nx_status) {
					get_cq_status(WRITE, &nx_status);
					sleep(5);
				}
			}
			else {
				// other process
				return false;
			}
		}
		usleep(10);
	}
	
	return true;
}`
**Code End**

**Comment by calvinzhangclx** [comment] 2022-03-25 00:53
Hi @markdroth , another issue will happen if we ran into the TIMEOUT issue. While the completion queue status was TIMEOUT, the GRPC will not send keepalive packet.

**Comment by yashykt** [comment] 2022-03-29 19:57
v1.14 is really old. Can you try this with the latest version please? There have been a good number of fixes in this code since then.

**Comment by yashykt** [comment] 2022-03-29 21:06
Well, actually, this reminded me of https://github.com/grpc/proposal/blob/master/A18-tcp-user-timeout.md which was intended to fix this exact bug. I believe using the latest version would fix it for you. I'm gonna go ahead and close this down but please feel free to comment here or open a new bug if this doesn't work for you (since that might be a different bug altogether).

**Closed by yashykt** 2022-03-29 21:06 UTC
Labels: kind/bug, lang/c++, priority/P2, untriaged

**Comment by calvinzhangclx** [comment] 2022-03-31 03:10
Thank you very much @yashykt . I'll take a look at the bug you mentioned and will also try to use the latest version.
