### ISSUE TITLE
Error loading native libs (1.18.0) and error with incorrect symbol

### ISSUE THREAD

**Issue by ltcmelo** [grpc/grpc#18737] opened 2019-04-12 01:35 UTC
### What version of gRPC and what language are you using?
 
I've tried both 1.18.0 and 1.19.0.
 
### What operating system (Linux, Windows,...) and version?
 
OSX and Windows.
  
### What did you do?

This is a simplified structure of my project.

- coredriver (.NET **Core** 2.x)
- fwdriver (.NET **Framework** 4.6.2)
- sharedlib (.NET **Standard** 2.0)

The shared library makes use of gRPC - by means of a NuGet package `Grpc`. A build/run for .NET *Core* works smoothly. However, for .NET Framework I'm having problems.

The build goes well and the *native libraries* are placed properly in the output/publish directory, together with the other DLLs. But when I run the application I get the following exception:

```
System.IO.FileNotFoundException: Error loading native library. Not found in any of the possible locations: C:\Windows\Microsoft.Net\assembly\GAC_MSIL\Grpc.Core\v4.0_1.0.0.0__d754f35622e28bad\grpc_csharp_ext.x86.dll,C:\Windows\Microsoft.Net\assembly\GAC_MSIL\Grpc.Core\v4.0_1.0.0.0__d754f35622e28bad\runtimes/win/native\grpc_csharp_ext.x86.dll,C:\Windows\Microsoft.Net\assembly\GAC_MSIL\Grpc.Core\v4.0_1.0.0.0__d754f35622e28bad\../..\runtimes/win/native\grpc_csharp_ext.x86.dll
   at Grpc.Core.Internal.UnmanagedLibrary.FirstValidLibraryPath(String[] libraryPathAlternatives)
   at Grpc.Core.Internal.UnmanagedLibrary..ctor(String[] libraryPathAlternatives)
   at Grpc.Core.Internal.NativeExtension.LoadUnmanagedLibrary()
   at Grpc.Core.Internal.NativeExtension.LoadNativeMethods()
   at Grpc.Core.Internal.NativeExtension..ctor()
   at Grpc.Core.Internal.NativeExtension.Get()
   at Grpc.Core.GrpcEnvironment.GrpcNativeInit()
   at Grpc.Core.GrpcEnvironment..ctor()
   at Grpc.Core.GrpcEnvironment.AddRef()
   at Grpc.Core.Channel..ctor(String target, ChannelCredentials credentials, IEnumerable`1 options)
   at Grpc.Core.Channel..ctor(String host, Int32 port, ChannelCredentials credentials, IEnumerable`1 options)
```

I'm surprised by the search path for loading... I googled around and found numerous reports with this trace, with slight variations: [here](https://github.com/grpc/grpc/issues/12570), [there](https://github.com/grpc/grpc/issues/5589), [again](https://github.com/grpc/grpc/issues/17451), etc. Most of them are for older versions of gRPC. Nevertheless, I gave it a try by adding an explicit NuGet reference of `Grpc.Core` (in the dependent project as well). Didn't work...

I even considered upgrading to 1.19.0, but I then get this exception:

```
 System.MissingMethodException: Method not found: 'Void Grpc.Core.CallOptions..ctor(Grpc.Core.Metadata, System.Nullable`1<System.DateTime>, System.Threading.CancellationToken, Grpc.Core.WriteOptions, Grpc.Core.ContextPropagationToken, Grpc.Core.CallCredentials)'.
         at io.shiftleft.generic2cpg.infra.GrpcLogger..ctor()
```
 
Before I dig further, is there (still) any issue in this area?

**Comment by ltcmelo** [comment] 2019-04-12 18:04
I made a little progress here: Reading the error with a bit more care I realized that, while there was an attempt to load the gRPC lib `grpc_csharp_ext.x86.dll`, I actually had version `grpc_csharp_ext.x64.dll` in that directory. It seems that there's some platform mismatch going on if _Any CPU_ is specified. When I make a build for a particular target, then the native lib is properly discovered.

**Comment by jtattermusch** [comment] 2019-04-15 10:33
Can you provide an example project that reproduces the problem?
Things should work in both 32bit and 64bit just fine.

FTR, this is the code that looks for grpc_csharp_ext.dll https://github.com/grpc/grpc/blob/d5769552c6db5dea7c6c7c4e3d8aa6a0ab5368e8/src/csharp/Grpc.Core/Internal/NativeExtension.cs#L83

**Comment by ltcmelo** [comment] 2019-04-15 18:04
> Can you provide an example project that reproduces the problem?

A basic project that instantiates a gRPC logger, with the specifications I described above is enough for me to reproduce the issue. For completeness, I'm running Windows 10 Pro with VS 2017 for this issue.

**Comment by fractus** [comment] 2019-05-12 11:54
@jtattermusch This seems to be related to the netcoreapp version; it fails for 2.2 but works for 2.1 (in the csproj file.) See output from Win64 below and attached a minimal project to replicate it. Same behaviour on WSL.

[JustRunGrpc.zip](https://github.com/grpc/grpc/files/3170026/JustRunGrpc.zip)

```
/c/temp/JustRunGrpc
$ dotnet run

Unhandled Exception: System.IO.FileNotFoundException: Error loading native library. Not found in any of the possible locations: C:\temp\JustRunGrpc\bin\Debug\netcoreapp2.2\grpc_csharp_ext.x64.dll,C:\temp\JustRunGrpc\bin\Debug\netcoreapp2.2\runtimes/win/native\grpc_csharp_ext.x64.dll,C:\temp\JustRunGrpc\bin\Debug\netcoreapp2.2\../..\runtimes/win/native\grpc_csharp_ext.x64.dll
   at Grpc.Core.Internal.UnmanagedLibrary.FirstValidLibraryPath(String[] libraryPathAlternatives)
   at Grpc.Core.Internal.UnmanagedLibrary..ctor(String[] libraryPathAlternatives)
   at Grpc.Core.Internal.NativeExtension.LoadUnmanagedLibrary()
   at Grpc.Core.Internal.NativeExtension.LoadNativeMethods()
   at Grpc.Core.Internal.NativeExtension..ctor()
   at Grpc.Core.Internal.NativeExtension.Get()
   at Grpc.Core.GrpcEnvironment.GrpcNativeInit()
   at Grpc.Core.GrpcEnvironment..ctor()
   at Grpc.Core.GrpcEnvironment.AddRef()
   at Grpc.Core.Server..ctor(IEnumerable`1 options)
   at JustRunGrpc.Program.Main(String[] args) in C:\temp\JustRunGrpc\Program.cs:line 11


/c/temp/JustRunGrpc
$ dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   2.2.202
 Commit:    8a7ff6789d

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.15063
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.2.202\

Host (useful for support):
  Version: 2.2.3
  Commit:  6b8ad509b6

.NET Core SDKs installed:
  2.1.2 [C:\Program Files\dotnet\sdk]
  2.2.104 [C:\Program Files\dotnet\sdk]
  2.2.105 [C:\Program Files\dotnet\sdk]
  2.2.202 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.2.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.2.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.0.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```

**Comment by fractus** [comment] 2019-05-13 12:30
Another observation: If the `CopyLocalLockFileAssemblies` property is set to true in csproj, the run fails.

```
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp2.2</TargetFramework>
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
  </PropertyGroup>
```

**Comment by ArnoldHorshack** [comment] 2019-06-12 13:35
Hi, also had this issue - maybe a trivial instance that only I was stupid enough to run into - but playing with the google ads examples  I moved some of the examples into a separate class library, called them from a console program and got the grpc error.  It showed up in the references in the class library but still gave the error.  Finally figured it had to also be in the console program.  Probably obvious to other but I missed it, so figured I throw this solution into the mix. Overall the program is great,so thankd

**Comment by jtattermusch** [comment] 2019-06-24 15:35
@ltcmelo  seems that you've resolved your issue.

@fractus  I used your example and I wasn't able to make it fail with the JustRunGrpc example you provided. I was able to make it fail after setting `<CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>` though. I filed https://github.com/grpc/grpc/issues/19448.

**Comment by jtattermusch** [comment] 2019-06-24 15:35
Closing the original issue as "cannot reproduce"

**Closed by jtattermusch** 2019-06-24 15:35 UTC
Labels: kind/bug, lang/C#, priority/P3
