### ISSUE TITLE
gcc make failded due to shadowed declaration？

### ISSUE THREAD

**Issue by Zazakas** [grpc/grpc#11867] opened 2017-07-18 00:40 UTC
Hi，@markdroth  I moved here from https://github.com/grpc/grpc/pull/10845#issuecomment-315825585 .

 while building grpc I got：

Compiling src/core/ext/filters/client_channel/client_channel.c
src/core/ext/filters/client_channel/client_channel.c: In function ‘lookup_external_connectivity_watcher’:
src/core/ext/filters/client_channel/client_channel.c:1459:40: error: declaration of ‘on_complete’ shadows a global declaration [-Werror=shadow]
src/core/ext/filters/client_channel/client_channel.c:1243:13: error: shadowed declaration is here [-Werror=shadow]
### What version of gRPC and what language are you using?
 using branch 1.4.x
 
### What operating system (Linux, Windows, …) and version?
 uname -a
Linux （branchcode） 3.4-9-rtai-686-pae #1 SMP PREEMPT Debian 3.4.55-4（branchcode） i686 GNU/Linux
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
At first I used gcc 4.7 and got this erro, then I manually update gcc to 4.8.4, the problem persists.

but  using the same gcc 4.8.4 version on Ubuntu 14.04.1 , and the same downloaded code by copy paste ,the build succeeded.
 
### What did you do?
I fllowed the  https://github.com/grpc/grpc/blob/master/INSTALL.md  , and during the make process.
and  "curl -L https://grpc.io/release"  yields 1.4.x. 

### Anything else we should know about your project / environment?
I run linux in a virtual machine on my laptop

**Comment by markdroth** [comment] 2017-07-18 14:41
I don't understand what you mean by this:

> but using the same gcc 4.8.4 version on Ubuntu 14.04.1 , and the same downloaded code by copy paste ,the build succeeded.

In particular, what do you mean by "the same downloaded code by copy paste"?  What exactly did you download, and what did you copy and paste?

@dgquintas, don't we run portability tests for the release branches before we cut a release?  If so, it's not clear to me how this could slip through.

**Comment by Zazakas** [comment] 2017-07-19 00:48
@markdroth  ,sorry for the confusing expression. 
At first I  compliled the code on the Debian system follow the instruction ( https://github.com/grpc/grpc/blob/master/INSTALL.md ), but failed .

And while on Ubuntu 14.04.1 ,since I have already checkcout the code using git on Debian. So I copy the source code form my Debian to Ubuntu and start form Line 4( the make line).
1 ~~$ git clone -b $(curl -L https://grpc.io/release) https://github.com/grpc/grpc~~ 
2 ~~$ cd grpc~~
3 ~~$ git submodule update --init~~
4 $ make
5  $ [sudo] make install  

 and succeeded.

**Comment by markdroth** [comment] 2017-07-19 14:36
So you're saying that the same version of gcc succeeded on Ubuntu but failed on Debian?  That seems like an environment issue, then, not a bug on our side.

**Comment by dgquintas** [comment] 2017-07-19 19:00
Yes, we do run portability tests continuously.

**Comment by Zazakas** [comment] 2017-07-20 00:36
Ok,the whole picture is:
1 I trie to build grpc on **Debian**  (build-in gcc 4.7.X) . Failed
2 I moved to Ubuntu 14.04 (gcc 4.8.4). Succeed
3 So I guessed it could be the problem of gcc, so I manually compliled and installed gcc 4.8.4 on Debian.
4 Again I failed on Debian using gcc 4.8.4

So, I guess I should properly install or configure gcc 4.8.4 on Debian ;
or try it on Ubuntu 10.04......

But could somebody give me a clue why this should happen?

**Comment by Zazakas** [comment] 2017-07-20 03:17
So I tried a fresh install of Debian : 
 uname -a
Linux debian 3.4-9-rtai-686-pae #1 SMP PREEMPT Debian 3.4.55-4linuxcnc i686 GNU/Linux

and failed:
src/core/ext/filters/client_channel/client_channel.c: In function ‘lookup_external_connectivity_watcher’:
src/core/ext/filters/client_channel/client_channel.c:1459:40: error: declaration of ‘on_complete’ shadows a global declaration [-Werror=shadow]
src/core/ext/filters/client_channel/client_channel.c:1243:13: error: shadowed declaration is here [-Werror=shadow]


gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/i486-linux-gnu/4.7/lto-wrapper
Target: i486-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Debian 4.7.2-5' --with-bugurl=file:///usr/share/doc/gcc-4.7/README.Bugs --enable-languages=c,c++,go,fortran,objc,obj-c++ --prefix=/usr --program-suffix=-4.7 --enable-shared --enable-linker-build-id --with-system-zlib --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --with-gxx-include-dir=/usr/include/c++/4.7 --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --enable-gnu-unique-object --enable-plugin --enable-objc-gc --enable-targets=all --with-arch-32=i586 --with-tune=generic --enable-checking=release --build=i486-linux-gnu --host=i486-linux-gnu --target=i486-linux-gnu
Thread model: posix
gcc version 4.7.2 (Debian 4.7.2-5)

**Comment by dgquintas** [comment] 2017-07-21 20:35
Interesting. I can repro on ubuntu 14.04 after installing `gcc-4.7` and `g++-4.7`. This is a false alarm (and probably why 4.8 no longer reports it). I'll make some changes to prevent this issue for any 4.7 users out there.

The cause: function `lookup_external_connectivity_watcher` on line 1458 has an `on_complete` argument, which becomes a symbol within the scope of that function. In addition, static function `on_complete`, declared on line 1243 introduces another symbol by the same name (in this case, a static function, which is the same as a global in the context of this .c file). These symbols are clearly of different types (one's a pointer variable, the other one is a function). However, the compiler simply looks at the symbol names and believes the function argument is being shadowed by the static function.

**Comment by dgquintas** [comment] 2017-07-21 20:41
Also, @vjpai has just informed me that we don't officially support gcc 4.7 anymore, 4.8 being the minimum.

**Comment by dgquintas** [comment] 2017-07-21 20:54
In light of what @vjpai commented on #11909, I'm closing this issue with "working as intended".

**Closed by dgquintas** 2017-07-21 20:54 UTC

**Comment by nicolasnoble** [comment] 2017-08-02 17:37
The sad part here is that Debian Wheezy (the affected distribution here) is still on LTS for a little less than a year.

**Comment by Zazakas** [comment] 2017-08-03 00:07
And the sadest part is: after fix this problem per https://github.com/grpc/grpc/pull/11909 . Another problem is coming up:

Compiling src/cpp/server/health/default_health_check_service.cc
src/cpp/server/health/default_health_check_service.cc: In constructor ‘grpc::DefaultHealthCheckService::DefaultHealthCheckService()’:
src/cpp/server/health/default_health_check_service.cc:134:17: error: ‘class std::map<std::basic_string<char>, bool>’ has no member named ‘emplace’
make: *** [/home/andrew/grpc/objs/opt/src/cpp/server/health/default_health_check_service.o] Error 1

Probalby I should give up Debian Wheezy.

**Comment by vjpai** [comment] 2017-08-03 00:37
gRPC 1.0.x happily supports gcc all the way down to version 4.4 . gRPC 1.1 and beyond have a minimum requirement of gcc 4.8.
