### ISSUE TITLE
Enum zero-value does not pass from C++ to Python server.

### ISSUE THREAD

**Issue by denis-trofimov** [grpc/grpc#11846] opened 2017-07-17 15:13 UTC
Enum zero-value does not pass from C++ to Python server. Maybe **any** server.
Non-zero values got pass to server
Enum zero-value got received from Python server by C++ client.
### What version of gRPC and what language are you using?
```
gRPC from github , compiled with included protobuf
commit 9a69478498232b6b42169f8a1a389b51fb4e03ec
Merge: 1b4be41a72 9104884a19
Author: Nathaniel Manista <nathaniel@google.com>
Date:   Sat Jun 24 21:46:07 2017 -0700
 ```
```
pip freeze 
grpc==0.3.post19
grpcio==1.4.0
grpcio-tools==1.4.0
protobuf==3.3.0
```
### What operating system (Linux, Windows, …) and version?
 
Linux
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
```
gcc: 4:6.3.0-2ubuntu1 on client
server
Python 2.7.13 (default, Jan 19 2017, 14:48:08) 
[GCC 6.3.0 20170118] on linux2
```
 
## cyclop.proto
```javascript
syntax = "proto3";


// A Person corresponds to Person ORM.
message Person {
    uint32 id = 1;
    string first_name = 2;
    string last_name = 3;
    string patronymic = 4;
    // A person`s sex.
    enum Sex {
        MALE =0;
        FEMALE = 1;
    }
    Sex sex = 5;
    // A birthday date.
    string birthday = 6;

    // A status of a person record.
    enum Status {
        VALID = 0;
        ARCHIVE = 1;
        BLACK = 2;
    }
    Status person_status = 7;

    // An iris code(s).
    Code code = 8;
}

// A responce for CRUD operations.
message CRUDResponse {
    // A result of operation .
    enum Status {
        SUCCESS = 0;
        FAIL = 1;
    }
    Status status = 1;
}

// A client oriented service.
service PersonService {
    // RPC on click button `Record`.
    rpc CreatePerson(Person) returns (CRUDResponse) {}
}
```
## Client processing QML UI
PersonServiceClient.h
```cpp
#pragma once
#include <iostream>
#include <memory>
#include <string>

#include <QObject>
#include <QString>
#include <QDate>
#include <grpc++/grpc++.h>
#include "cyclop.grpc.pb.h"

using grpc::Channel;
using cyclop::PersonService;

class PersonServiceClient : public QObject {
    Q_OBJECT

public:
    PersonServiceClient(QObject* pobj /*=0*/, std::shared_ptr<Channel> channel)
        : QObject(pobj), stub_(PersonService::NewStub(channel)) {}


public slots:
    //Create Person
    void createPerson(QString first_name, QString last_name,
                      QString patronymic, quint32 sex,
                      QDate birthday, quint32 person_status);
};
```
PersonServiceClient.cpp
```cpp
#include "PersonServiceClient.h"

using grpc::Channel;
using grpc::ClientContext;
using grpc::Status;
using cyclop::CRUDResponse;
using cyclop::Capture;
using cyclop::Person;

void PersonServiceClient::createPerson(QString first_name, QString last_name,
                                       QString patronymic,
                                       quint32 sex, QDate birthday,
                                       quint32 person_status)
{
    std::cout << "createPerson user input:" <<
                 " first_name=" << first_name.toStdString() <<
                 ", last_name=" << last_name.toStdString() <<
                 ", patronymic=" << patronymic.toStdString() <<
                 ", sex=" << sex <<
                 ", birthday=" << birthday.toString(Qt::ISODate).toStdString() <<
                 ", person_status=" << person_status <<
                 std::endl;

    // Data we are sending to the server.
    Person request;
    request.set_first_name(first_name.toStdString());
    request.set_last_name(last_name.toStdString());
    request.set_patronymic(patronymic.toStdString());

    // Convert quint32 sex to cyclop::Person_Sex.
    switch (sex) {
    case 0:
        request.set_sex(cyclop::Person_Sex_MALE);
        break;
    case 1:
        request.set_sex(cyclop::Person_Sex_FEMALE);
        break;
    default:
        // TODO: throw
        break;
    }
    request.set_sex(static_cast< ::cyclop::Person_Sex >(quint8(sex)));
    request.set_birthday(birthday.toString(Qt::ISODate).toStdString());

    // Convert quint32 sex to cyclop::Person_Status_VALID.
    switch (person_status) {
    case 0:
        request.set_person_status(cyclop::Person_Status_VALID);
        break;
    case 1:
        request.set_person_status(cyclop::Person_Status_ARCHIVE);
        break;
    case 2:
        request.set_person_status(cyclop::Person_Status_BLACK);
        break;
    default:
        // TODO: throw
        break;
    }

    std::cout << ", Person_Sex_IsValid=" << cyclop::Person_Sex_IsValid(sex) <<
                 ", Person_Status_IsValid=" << cyclop::Person_Status_IsValid(person_status) <<
                 ", Person_Sex_Name=" << cyclop::Person_Sex_Name(request.sex()) <<
                 ", Person_Status_Name=" << cyclop::Person_Status_Name(request.person_status()) <<

                 std::endl;

    // Container for the data we expect from the server.
    CRUDResponse response;

    // Context for the client. It could be used to convey extra information to
    // the server and/or tweak certain RPC behaviors.
    ClientContext context;

    // The actual RPC.
    Status status = stub_->CreatePerson(&context, request, &response);

    // Act upon its status.
    if (status.ok()) {
        switch (response.status()) {
        case cyclop::CRUDResponse_Status_FAIL:
        {
            this->setStatus(QString(tr("!")));
            break;
        }
        case cyclop::CRUDResponse_Status_SUCCESS:
        {
            this->setStatus(QString(tr(".")));
            break;
        }
        }
    }
    else {
        this->setStatus(QString::fromStdString(status.error_message()));
    }
}
```
## Server
```python
class PersonService(cyclop_pb2_grpc.PersonServiceServicer):

    def CreatePerson(self, request, context):
        """RPC on click button `Record`."""
        print("CreatePerson request")
        print(request)

        if (CAPTURE_STATUS == cyclop_pb2.Capture.FULLOK):
            return cyclop_pb2.CRUDResponse(status=cyclop_pb2.CRUDResponse.SUCCESS)
        else:
            return cyclop_pb2.CRUDResponse(status=cyclop_pb2.CRUDResponse.FAIL)
```

### What did you expect to see?
from client std::cout
```cpp
createPerson user input: first_name=2, last_name=1, patronymic=3, sex=0, birthday=, person_status=0
, Person_Sex_IsValid=1, Person_Status_IsValid=1, Person_Sex_Name=MALE, Person_Status_Name=VALID
```
python server
```python
CreatePerson request
first_name: "2"
last_name: "1"
patronymic: "3"
sex: MALE
person_status: ACTIVE
```
### What did you see instead?
python server
```python
CreatePerson request
first_name: "2"
last_name: "1"
patronymic: "3"
```

Results are equal if use:
```cpp
    switch (sex) {
    case 0:
        request.set_sex(cyclop::Person_Sex_MALE);
        break;
    case 1:
        request.set_sex(cyclop::Person_Sex_FEMALE);
        break;
    default:
        // TODO: throw
        break;
    }
```
Or use:
```cpp
    request.set_sex(static_cast< ::cyclop::Person_Sex >(quint8(sex)));
```

I blame this generated code in cyclop.pb.cc:
```cc

void Person::MergeFrom(const Person& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:cyclop.Person)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.first_name().size() > 0) {

    first_name_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.first_name_);
  }
  if (from.last_name().size() > 0) {

    last_name_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.last_name_);
  }
  if (from.patronymic().size() > 0) {

    patronymic_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.patronymic_);
  }
  if (from.birthday().size() > 0) {

    birthday_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.birthday_);
  }
  if (from.has_code()) {
    mutable_code()->::cyclop::Code::MergeFrom(from.code());
  }
  if (from.id() != 0) {
    set_id(from.id());
  }
  if (from.sex() != 0) {
    set_sex(from.sex());
  }
  if (from.person_status() != 0) {
    set_person_status(from.person_status());
  }
}
```

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

**Comment by nathanielmanistaatgoogle** [comment] 2017-07-19 18:09
@denis-trofimov: you've reported this as a problem between a C++ client and a Python server. Have you confirmed that it does not exist between a C++ client and a C++ server? Have you confirmed that it does not exist between a Python client and a Python server?

**Comment by denis-trofimov** [comment] 2017-07-19 18:45
Hi @nathanielmanistaatgoogle 
I ask reasonable questions. I don't check others because it is outside my use case at work. 
I did workaround just for now, add a dummy key with zero value for all messages I send from CPP. It works just fine. 
```javascript
enum Sex {
        SEX0 = 0;
        MALE = 1;
        FEMALE = 2;
    }
```

**Comment by nathanielmanistaatgoogle** [comment] 2017-07-19 21:12
Could the problem be that the zero values are simply not printed by your server-side `print(request)`? What happens if you print `request.sex` in your server-side Python code? Could it be that the problem is that zero values passed from client to server, but that they simply aren't printed?

**Comment by denis-trofimov** [comment] 2017-07-19 21:45
As it prints `sex: FEMALE` I don't check python server generated code. But it could also be a server flaw, but not in my custom code, as you can see. It just prints given request as a dict.

**Comment by nathanielmanistaatgoogle** [comment] 2017-07-19 21:51
Aside from what is printed to the console, in what way is you program behaving incorrectly because of this defect? If the client-side code assigns the zero value of an enum to a field of the request, does the server-side code not see the zero value of the enum assigned to the field when it reads the request?

**Comment by yang-g** [comment] 2017-07-19 21:56
This may be working as intended. In proto3, enum default value is 0 and if you are using default value, it does not go on the wire. I do not know about python but maybe it does not (cannot) distinguish whether you did not set the value or set to default. If you do not want MALE to be default, you should do your workaround like `UNKNOWN = 0`.

See: https://developers.google.com/protocol-buffers/docs/proto3#default

**Comment by denis-trofimov** [comment] 2017-07-19 22:20
@y-zeng yes the most plausible it is not goes over wire.
https://developers.google.com/protocol-buffers/docs/reference/python-generated#enum
For Python, it is not working as I want it. *smile* 
If I look for 'sex' in request it will be false (not checked yet)
The simple example show d is a dict in Python.
```python
Python 2.7.13 (default, Jan 19 2017, 14:48:08) 
[GCC 6.3.0 20170118] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> d = {'sex': 0}
>>> print d
{'sex': 0}
>>> 'some' in d
False
```

**Comment by denis-trofimov** [comment] 2017-07-19 22:23
@y-zeng  I checked that  good idea it to set unique names for dummy fields. There would be names conflict otherwise, I have example at work.

**Comment by y-zeng** [comment] 2017-07-19 22:51
@denis-trofimov You probably wanted to mention @yang-g?

**Comment by denis-trofimov** [comment] 2017-07-20 07:35
@y-zeng Yes , sorry it was 1 A.M. and I was sleepy.

**Comment by nathanielmanistaatgoogle** [comment] 2017-07-20 14:13
Closing since I think this is a Protocol Buffers issue rather than a gRPC issue: whatever behavior you're seeing that is a problem, you see the behavior when you simply serialize and deserialize a message (possibly writing it to your filesystem and reading it back if you need to cross a programming language barrier), right?

It's not the case that transmitting the message via gRPC is required to demonstrate the problem, right?

@xfxyjwf and @anandolee, what do you make of what's reported here?

**Closed by nathanielmanistaatgoogle** 2017-07-20 14:13 UTC
Labels: lang/c++, lang/Python

**Comment by denis-trofimov** [comment] 2017-07-21 11:58
@nathanielmanistaatgoogle Should I put this issue up in Protocol Buffers describing it from the start? What do you recommend?

**Comment by nathanielmanistaatgoogle** [comment] 2017-07-21 14:33
Yes, I'd recommend [filing an issue with Protocol Buffers](https://github.com/google/protobuf/issues) with a minimal reproduction that doesn't involve gRPC.
