### ISSUE TITLE
Python thread throwing exception when passed a stream as arg

### ISSUE THREAD

**Issue by sulliwane** [grpc/grpc#9360] opened 2017-01-17 09:19 UTC
If I create the stream object and then pass it to the thread, it will throw:
```python
stream = stub.GetStream(md.Empty())

def stream_worker(thestream):
    for elem in thestream:
        logging.info(elem)

mythread = Thread(
    target=stream_worker,
    args=(stream),
 )
mythread.start()
```
the error:
```
Exception in thread Thread-2:
Traceback (most recent call last):
  File "~/.pyenv/versions/3.6.0/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "~/.pyenv/versions/3.6.0/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "~/myproject/.venv/lib/python3.6/site-packages/grpc/_channel.py", line 341, in __next__
    return self._next()
  File "~/myproject/.venv/lib/python3.6/site-packages/grpc/_channel.py", line 335, in _next
    raise self
grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with (StatusCode.CANCELLED, Cancelled)>
```
If I create the stream in the thread, then no problem:
```python
def stream_worker():
    stream = stub.GetStream(md.Empty())
    for elem in thestream:
        logging.info(elem)

mythread = Thread(
    target=stream_worker,
 )
mythread.start()
```
@nathanielmanistaatgoogle Any idea why it's not possible to start the thread with the stream already created as an argument? 
thanks!

**Comment by nathanielmanistaatgoogle** [comment] 2017-01-17 14:36
@sulliwane: what your code doesn't show but what I'd really like to know is what's happening in your first thread after launching the second thread. If your stub and channel go out of scope and are garbage-collected they will cancel all in-flight RPCs outstanding on them. Could that be the cause of the `StatusCode.CANCELLED` status that you are observing?

**Comment by sulliwane** [comment] 2017-01-18 04:53
So basically I have a class **GrpcClient** that wraps the grpc stub methods, and all of its streaming methods will first get the stream, and then delegate the ```for elem in stream``` loop into a thread, using ```add_worker(stream)```:
```python
class GrpcClient:
    def __init__(self):
        self.__stub = self.get_grpc_stub()

    def get_grpc_stub(self):
        auth_plugin = GrpcAuthPlugin()
        metadata_auth = grpc.metadata_call_credentials(auth_plugin, None)
        ssl_creds = grpc.ssl_channel_credentials(None, None, None)
        channel_creds = grpc.composite_channel_credentials(
            ssl_creds,
            metadata_auth,
        )
        channel = grpc.secure_channel(
            self.server_url,
            channel_creds,
        )
        return md.SmartwinFuturesMdStub(channel)

    def add_worker(self, stream):
        def stream_worker(thestream):
            for elem in thestream:
                logging.info(elem)
        mythread = Thread(
            target=stream_worker,
            args=(stream),
        )
        mythread.start()

    def getStream(self):
        stream = stub.GetStream(md.Empty())
        self.add_worker(stream)

""" The main loop """"
myClient = GrpcClient()
myClient.getStream()
```
I don't think that my stub is going out of scope as it is attached to the grpcClient instance (which is living in the main thread).

But I will try to come up with a code sample that makes my problem reproducible (my mistake is probably less obvious than I thought) and I'll update the issue after that.

**Comment by nathanielmanistaatgoogle** [comment] 2017-01-18 18:25
What happens in "The main loop" after "myClient.getStream()"? Is that where your main thread runs out of things to do?

**Comment by nathanielmanistaatgoogle** [comment] 2017-01-18 19:52
Punting; there's nothing here that should hold up the release of `1.1.0`.

**Comment by nathanielmanistaatgoogle** [comment] 2017-01-19 22:14
@ctiller, @dgquintas: look at the way the issue reporter is seeing status code `grpc.StatusCode.CANCELLED` and status details string "`Cancelled`". I _suspect_ that what's happening is the user is allowing the `grpc.Channel` object to be garbage-collected while the RPC is active and that's causing `grpc_channel_destroy` to be called while there is still a live RPC. Please confirm that in the case of `grpc_channel_destroy` being called while an RPC is active that status details string "`Cancelled`" is what's used for the killed-at-that-time RPC? **Most importantly, how feasible would it be to isolate that circumstance and change the status details string to something like "`RPC cancelled as part of grpc_channel_destroy`"?**

**Comment by dgquintas** [comment] 2018-06-26 21:02
It this issue still relevant? Closing for now, please reopen if so.

**Closed by dgquintas** 2018-06-26 21:02 UTC
Labels: area/core, kind/question, lang/Python, priority/P2
