### ISSUE TITLE
Test failure: Java components in grpc_interop_alts

### ISSUE THREAD

**Issue by lidizheng** [grpc/grpc#19278] opened 2019-06-06 22:27 UTC
Mirrored issue in grpc-java repo: https://github.com/grpc/grpc-java/issues/5847

All Java related test cases are failed.

Test log link: https://source.cloud.google.com/results/invocations/855044aa-72b9-4329-b92b-bc8b277b77f2/targets/grpc%2Fcore%2Fpull_request%2Flinux%2Fgrpc_interop_alts/log

Error parts:
```
Jun 06, 2019 9:16:06 PM io.grpc.netty.NettyChannelBuilder buildTransportFactory
WARNING: Both EventLoopGroup and ChannelType should be provided or neither should be, otherwise client may not start. Not provided values will use Nio (NioSocketChannel, NioEventLoopGroup) for compatibility. This will cause an Exception in the future.
Exception in thread "main" java.lang.AssertionError: io.grpc.StatusRuntimeException: UNKNOWN
	at io.grpc.testing.integration.AbstractInteropTest.pingPong(AbstractInteropTest.java:744)
	at io.grpc.testing.integration.TestServiceClient.runTest(TestServiceClient.java:271)
	at io.grpc.testing.integration.TestServiceClient.run(TestServiceClient.java:214)
	at io.grpc.testing.integration.TestServiceClient.main(TestServiceClient.java:72)
Caused by: io.grpc.StatusRuntimeException: UNKNOWN
	at io.grpc.Status.asRuntimeException(Status.java:533)
	at io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onClose(ClientCalls.java:442)
	at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
	at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
	at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
	at io.grpc.internal.CensusStatsModule$StatsClientInterceptor$1$1.onClose(CensusStatsModule.java:700)
	at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
	at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
	at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
	at io.grpc.internal.CensusTracingModule$TracingClientInterceptor$1$1.onClose(CensusTracingModule.java:399)
	at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:500)
	at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:65)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.close(ClientCallImpl.java:592)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.access$700(ClientCallImpl.java:508)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:632)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: io.netty.handler.codec.DecoderException: java.lang.IndexOutOfBoundsException: End index: 128 >= 44
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:472)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:278)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1408)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:930)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:682)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:617)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:534)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:906)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	... 1 more
Caused by: java.lang.IndexOutOfBoundsException: End index: 128 >= 44
	at com.google.protobuf.ByteString.checkRange(ByteString.java:1249)
	at com.google.protobuf.ByteString.copyTo(ByteString.java:649)
	at com.google.protobuf.ByteString.copyTo(ByteString.java:632)
	at io.grpc.alts.internal.AltsHandshakerClient.getKey(AltsHandshakerClient.java:139)
	at io.grpc.alts.internal.AltsTsiHandshaker.createFrameProtector(AltsTsiHandshaker.java:178)
	at io.grpc.alts.internal.AltsTsiHandshaker.createFrameProtector(AltsTsiHandshaker.java:193)
	at io.grpc.alts.internal.NettyTsiHandshaker.createFrameProtector(NettyTsiHandshaker.java:150)
	at io.grpc.alts.internal.TsiHandshakeHandler.decode(TsiHandshakeHandler.java:126)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:502)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:441)
	... 17 more
Shutting down
```

**Comment by yihuazhang** [comment] 2019-06-06 22:31
I believe it is the duplicate of https://github.com/grpc/grpc/issues/19271#event-2395097372, which is already fixed.

**Closed** 2019-06-06 22:32 UTC
Labels: area/test, kind/bug, lang/Java
