### ISSUE TITLE
Net Core 3.0: DNS resolution failed

### ISSUE THREAD

**Issue by ComptonAlvaro** [grpc/grpc#21425] opened 2019-12-09 10:09 UTC
I am using Grpc.Core v2.25.0 and Windows 10 1909 in the service computer.

The service and client works correctly if I run both in the same computer, but if I run the client in another computer, I get the error "DNS resolution failed".

I am also using SSL certificates, that I have create with OpenSsl. But how in the same computer it works as expected, I guess that this part is correct too.

I don't know it would be needed more information or code, so if it is needed, I will add all the needed information.

Thanks.

[GestorAplicaciones.zip](https://github.com/grpc/grpc/files/3964759/GestorAplicaciones.zip)

EDIT: I add my project. Just run both, service and client and try to do a ping with the button. It will throw the exception of DNS.

EDIT 02: I have realize that the problem is in the client, and perhaps, I am not sure, it is related with TLS certificates.

If I use this code to create the client:

` var channel = GrpcChannel.ForAddress(_serviceAddress);
            Gestor.GestorClient client = new Gestor.GestorClient(channel);
            var client = new Gestor.GestorClient(channel);`

I get the error that the services doesn't accept the connection.

However, if I use this what to create the client:
`
            KeyCertificatePair keypair = new KeyCertificatePair(_clientCertificate, _clientPrivateKey);
            SslCredentials sslCreds = new SslCredentials(_caCertificate, keypair);
            Channel channel = new Channel(_serviceAddress, sslCreds);
            var client = new Gestor.GestorClient(channel);`

Then, I get the error with the DNS.

however the certificates I am sure they are correctly created. Anyway, all is in the code that I have attached in this issue.

Thanks.

**Comment by jtattermusch** [comment] 2019-12-13 14:19
Please include code that reproduces the problem and the exact output of your problem, otherwise there is nothing we can do.

From what I can tell, the problem is likely to be in your setup (e.g. using wrong hostname) rather than a bug in gRPC.

Also see https://github.com/grpc/grpc/blob/master/TROUBLESHOOTING.md to get more debug logs.

**Comment by muxi** [comment] 2020-05-05 18:45
Since there's no further information provided we are closing this issue. Feel free to reopen if any new information can be provided.

**Closed by muxi** 2020-05-05 18:45 UTC
Labels: kind/bug, lang/C#, priority/P2
