### ISSUE TITLE
MSAN failure: //test/cpp/end2end:grpclb_end2end_test@poller=poll

### ISSUE THREAD

**Issue by apolcyn** [grpc/grpc#17913] opened 2019-02-02 02:00 UTC
```
[ RUN      ] SingleBalancerTest.Fallback
I0201 23:27:15.622191652      18 grpclb_end2end_test.cc:609] starting backend server on port 29793
I0201 23:27:15.622852376     128 server_builder.cc:280]      Synchronous server. Num CQs: 1, Min pollers: 1, Max Pollers: 2, CQ timeout (msec): 10000
I0201 23:27:15.624167907      18 grpclb_end2end_test.cc:614] backend server startup complete
I0201 23:27:15.624686338      18 grpclb_end2end_test.cc:609] starting backend server on port 29794
I0201 23:27:15.625515006     130 server_builder.cc:280]      Synchronous server. Num CQs: 1, Min pollers: 1, Max Pollers: 2, CQ timeout (msec): 10000
I0201 23:27:15.626890524      18 grpclb_end2end_test.cc:614] backend server startup complete
I0201 23:27:15.627321334      18 grpclb_end2end_test.cc:609] starting backend server on port 29795
I0201 23:27:15.628027802     132 server_builder.cc:280]      Synchronous server. Num CQs: 1, Min pollers: 1, Max Pollers: 2, CQ timeout (msec): 10000
I0201 23:27:15.629439434      18 grpclb_end2end_test.cc:614] backend server startup complete
I0201 23:27:15.629955566      18 grpclb_end2end_test.cc:609] starting backend server on port 29796
I0201 23:27:15.631104304     134 server_builder.cc:280]      Synchronous server. Num CQs: 1, Min pollers: 1, Max Pollers: 2, CQ timeout (msec): 10000
I0201 23:27:15.632496095      18 grpclb_end2end_test.cc:614] backend server startup complete
I0201 23:27:15.632771784      18 grpclb_end2end_test.cc:609] starting balancer server on port 29797
I0201 23:27:15.633437447     136 server_builder.cc:280]      Synchronous server. Num CQs: 1, Min pollers: 1, Max Pollers: 2, CQ timeout (msec): 10000
I0201 23:27:15.634645946      18 grpclb_end2end_test.cc:614] balancer server startup complete
I0201 23:27:15.643792807      18 subchannel.cc:1020]         New connected subchannel at 0x704000006f00 for subchannel 0x71500002a300
I0201 23:27:15.647010732     137 grpclb_end2end_test.cc:219] LB[0x712000023a00]: BalanceLoad
I0201 23:27:15.648114636     137 grpclb_end2end_test.cc:227] LB[0x712000023a00]: received initial message 'initial_request {
  name: "application_target_name"
}
'
I0201 23:27:15.648373363     137 grpclb_end2end_test.cc:344] LB[0x712000023a00]: sleeping for 2000 ms...
I0201 23:27:16.445813340      32 subchannel.cc:1020]         New connected subchannel at 0x7040000012c0 for subchannel 0x715000028280
I0201 23:27:16.445813337      18 subchannel.cc:1020]         New connected subchannel at 0x704000000f40 for subchannel 0x715000028000
I0201 23:27:16.463407558      18 grpclb_end2end_test.cc:834] ========= BEFORE FIRST BATCH ==========
I0201 23:27:16.474410725      18 grpclb_end2end_test.cc:836] ========= DONE WITH FIRST BATCH ==========
I0201 23:27:23.649835349     137 grpclb_end2end_test.cc:348] LB[0x712000023a00]: Woke up! Sending response 'server_list {
  servers {
    ip_address: "\177\000\000\001"
    port: 29795
    load_balance_token: "token020"
  }
  servers {
    ip_address: "\177\000\000\001"
    port: 29796
    load_balance_token: "token021"
  }
}
'
I0201 23:27:23.663380293      32 subchannel.cc:1020]         New connected subchannel at 0x704000003780 for subchannel 0x715000028c80
I0201 23:27:23.669797888      32 subchannel.cc:1020]         New connected subchannel at 0x704000012000 for subchannel 0x715000028a00
==18==WARNING: MemorySanitizer: use-of-uninitialized-value
    #0 0x7fba4bc61cc1 in grpc_transport_destroy_stream(grpc_transport*, grpc_stream*, grpc_closure*) /proc/self/cwd/src/core/lib/transport/transport.cc:198:14
    #1 0x7fba4b88da73 in destroy_call_elem(grpc_call_element*, grpc_call_final_info const*, grpc_closure*) /proc/self/cwd/src/core/lib/channel/connected_channel.cc:174:3
    #2 0x7fba4b83d596 in grpc_call_stack_destroy(grpc_call_stack*, grpc_call_final_info const*, grpc_closure*) /proc/self/cwd/src/core/lib/channel/channel_stack.cc:217:5
    #3 0x7fba4d793bf8 in grpc_core::(anonymous namespace)::SubchannelCallDestroy(void*, grpc_error*) /proc/self/cwd/src/core/ext/filters/client_channel/subchannel.cc:128:3
    #4 0x7fba4b9c2908 in exec_ctx_run(grpc_closure*, grpc_error*) /proc/self/cwd/src/core/lib/iomgr/exec_ctx.cc:40:3
    #5 0x7fba4b9c1d70 in grpc_core::ExecCtx::Flush() /proc/self/cwd/src/core/lib/iomgr/exec_ctx.cc:148:9
    #6 0x8e996c in grpc_core::ExecCtx::~ExecCtx() /proc/self/cwd/./src/core/lib/iomgr/exec_ctx.h:108:5
    #7 0x7fba4bb3e36a in grpc_call_unref /proc/self/cwd/src/core/lib/surface/call.cc:596:1
    #8 0x7fba4e29c658 in grpc::ClientContext::~ClientContext() /proc/self/cwd/src/cpp/client/client_context.cc:67:5
    #9 0x632843 in grpc::testing::(anonymous namespace)::GrpclbEnd2endTest::SendRpc(grpc::testing::EchoResponse*, int, bool) /proc/self/cwd/test/cpp/end2end/grpclb_end2end_test.cc:581:3
    #10 0x63e903 in grpc::testing::(anonymous namespace)::GrpclbEnd2endTest::WaitForBackend(unsigned long) /proc/self/cwd/test/cpp/end2end/grpclb_end2end_test.cc:498:13
    #11 0x681c97 in grpc::testing::(anonymous namespace)::SingleBalancerTest_Fallback_Test::TestBody() /proc/self/cwd/test/cpp/end2end/grpclb_end2end_test.cc:850:5
    #12 0x12e0078 in void testing::internal::HandleSehExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) /proc/self/cwd/external/com_github_google_googletest/googletest/src/gtest.cc:2402:10
    #13 0x113fad7 in void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) /proc/self/cwd/external/com_github_google_googletest/googletest/src/gtest.cc:2438:14
    #14 0xeab566 in testing::Test::Run() /proc/self/cwd/external/com_github_google_googletest/googletest/src/gtest.cc:2474:5
    #15 0xeb930b in testing::TestInfo::Run() /proc/self/cwd/external/com_github_google_googletest/googletest/src/gtest.cc:2656:11
    #16 0xecf4c4 in testing::TestCase::Run() /proc/self/cwd/external/com_github_google_googletest/googletest/src/gtest.cc:2774:28
    #17 0xf816e1 in testing::internal::UnitTestImpl::RunAllTests() /proc/self/cwd/external/com_github_google_googletest/googletest/src/gtest.cc:4649:43
    #18 0x1317923 in bool testing::internal::HandleSehExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) /proc/self/cwd/external/com_github_google_googletest/googletest/src/gtest.cc:2402:10
    #19 0x1160baf in bool testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) /proc/self/cwd/external/com_github_google_googletest/googletest/src/gtest.cc:2438:14
    #20 0xf7dfb8 in testing::UnitTest::Run() /proc/self/cwd/external/com_github_google_googletest/googletest/src/gtest.cc:4257:10
    #21 0x7cae05 in RUN_ALL_TESTS() /proc/self/cwd/external/com_github_google_googletest/googletest/include/gtest/gtest.h:2233:46
    #22 0x4f3e81 in main /proc/self/cwd/test/cpp/end2end/grpclb_end2end_test.cc:1572:23
    #23 0x7fba4504982f in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2082f)
    #24 0x47b0c8 in _start (/b/f/w/bazel-out/k8-fastbuild/bin/test/cpp/end2end/grpclb_end2end_test@poller=poll.runfiles/com_github_grpc_grpc/test/cpp/end2end/grpclb_end2end_test+0x47b0c8)
  Uninitialized value was stored to memory at
    #0 0x7fba4bc61b84 in grpc_transport_destroy_stream(grpc_transport*, grpc_stream*, grpc_closure*) /proc/self/cwd/src/core/lib/transport/transport.cc:197
    #1 0x7fba4b88da73 in destroy_call_elem(grpc_call_element*, grpc_call_final_info const*, grpc_closure*) /proc/self/cwd/src/core/lib/channel/connected_channel.cc:174:3
    #2 0x7fba4b83d596 in grpc_call_stack_destroy(grpc_call_stack*, grpc_call_final_info const*, grpc_closure*) /proc/self/cwd/src/core/lib/channel/channel_stack.cc:217:5
    #3 0x7fba4d793bf8 in grpc_core::(anonymous namespace)::SubchannelCallDestroy(void*, grpc_error*) /proc/self/cwd/src/core/ext/filters/client_channel/subchannel.cc:128:3
    #4 0x7fba4b9c2908 in exec_ctx_run(grpc_closure*, grpc_error*) /proc/self/cwd/src/core/lib/iomgr/exec_ctx.cc:40:3
    #5 0x7fba4b9c1d70 in grpc_core::ExecCtx::Flush() /proc/self/cwd/src/core/lib/iomgr/exec_ctx.cc:148:9
    #6 0x8e996c in grpc_core::ExecCtx::~ExecCtx() /proc/self/cwd/./src/core/lib/iomgr/exec_ctx.h:108:5
    #7 0x7fba4bb3e36a in grpc_call_unref /proc/self/cwd/src/core/lib/surface/call.cc:596:1
    #8 0x7fba4e29c658 in grpc::ClientContext::~ClientContext() /proc/self/cwd/src/cpp/client/client_context.cc:67:5
    #9 0x632843 in grpc::testing::(anonymous namespace)::GrpclbEnd2endTest::SendRpc(grpc::testing::EchoResponse*, int, bool) /proc/self/cwd/test/cpp/end2end/grpclb_end2end_test.cc:581:3
    #10 0x63e903 in grpc::testing::(anonymous namespace)::GrpclbEnd2endTest::WaitForBackend(unsigned long) /proc/self/cwd/test/cpp/end2end/grpclb_end2end_test.cc:498:13
    #11 0x681c97 in grpc::testing::(anonymous namespace)::SingleBalancerTest_Fallback_Test::TestBody() /proc/self/cwd/test/cpp/end2end/grpclb_end2end_test.cc:850:5
    #12 0x12e0078 in void testing::internal::HandleSehExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) /proc/self/cwd/external/com_github_google_googletest/googletest/src/gtest.cc:2402:10
    #13 0x113fad7 in void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) /proc/self/cwd/external/com_github_google_googletest/googletest/src/gtest.cc:2438:14
    #14 0xeab566 in testing::Test::Run() /proc/self/cwd/external/com_github_google_googletest/googletest/src/gtest.cc:2474:5
    #15 0xeb930b in testing::TestInfo::Run() /proc/self/cwd/external/com_github_google_googletest/googletest/src/gtest.cc:2656:11
    #16 0xecf4c4 in testing::TestCase::Run() /proc/self/cwd/external/com_github_google_googletest/googletest/src/gtest.cc:2774:28
    #17 0xf816e1 in testing::internal::UnitTestImpl::RunAllTests() /proc/self/cwd/external/com_github_google_googletest/googletest/src/gtest.cc:4649:43
    #18 0x1317923 in bool testing::internal::HandleSehExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) /proc/self/cwd/external/com_github_google_googletest/googletest/src/gtest.cc:2402:10
    #19 0x1160baf in bool testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) /proc/self/cwd/external/com_github_google_googletest/googletest/src/gtest.cc:2438:14
  Uninitialized value was created by a heap deallocation
    #0 0x4a0869 in __interceptor_free /tmp/clang-build/src/compiler-rt/lib/msan/msan_interceptors.cc:221:3
    #1 0x7fba4b77cada in gpr_free /proc/self/cwd/src/core/lib/gpr/alloc.cc:77:3
    #2 0x7fba4d7bcc90 in grpc_core::(anonymous namespace)::ConnectionDestroy(void*, grpc_error*) /proc/self/cwd/src/core/ext/filters/client_channel/subchannel.cc:983:3
    #3 0x7fba4b9c2908 in exec_ctx_run(grpc_closure*, grpc_error*) /proc/self/cwd/src/core/lib/iomgr/exec_ctx.cc:40:3
    #4 0x7fba4b9c1d70 in grpc_core::ExecCtx::Flush() /proc/self/cwd/src/core/lib/iomgr/exec_ctx.cc:148:9
    #5 0x7fba4b989ecd in pollset_work(grpc_pollset*, grpc_pollset_worker**, long) /proc/self/cwd/src/core/lib/iomgr/ev_poll_posix.cc:1133:49
    #6 0x7fba4b9ba3cc in pollset_work(grpc_pollset*, grpc_pollset_worker**, long) /proc/self/cwd/src/core/lib/iomgr/ev_posix.cc:321:21
    #7 0x7fba4b9e235a in grpc_pollset_work(grpc_pollset*, grpc_pollset_worker**, long) /proc/self/cwd/src/core/lib/iomgr/pollset.cc:48:10
    #8 0x7fba4d5cdc5b in run_poller(void*, grpc_error*) /proc/self/cwd/src/core/ext/filters/client_channel/backup_poller.cc:122:7
    #9 0x7fba4b9c2908 in exec_ctx_run(grpc_closure*, grpc_error*) /proc/self/cwd/src/core/lib/iomgr/exec_ctx.cc:40:3
    #10 0x7fba4b9c1d70 in grpc_core::ExecCtx::Flush() /proc/self/cwd/src/core/lib/iomgr/exec_ctx.cc:148:9
    #11 0x7fba4baaeb8b in run_some_timers() /proc/self/cwd/src/core/lib/iomgr/timer_manager.cc:139:30
    #12 0x7fba4baadf31 in timer_main_loop() /proc/self/cwd/src/core/lib/iomgr/timer_manager.cc:245:9
    #13 0x7fba4baadd10 in timer_thread(void*) /proc/self/cwd/src/core/lib/iomgr/timer_manager.cc:292:3
    #14 0x7fba4b7bcea9 in grpc_core::(anonymous namespace)::ThreadInternalsPosix::ThreadInternalsPosix(char const*, void (*)(void*), void*, bool*)::'lambda'(void*)::operator()(void*) const /proc/self/cwd/src/core/lib/gprpp/thd_posix.cc:100:27
    #15 0x7fba4b7bc499 in grpc_core::(anonymous namespace)::ThreadInternalsPosix::ThreadInternalsPosix(char const*, void (*)(void*), void*, bool*)::'lambda'(void*)::__invoke(void*) /proc/self/cwd/src/core/lib/gprpp/thd_posix.cc:74:25
    #16 0x7fba4632b6b9 in start_thread (/lib/x86_64-linux-gnu/libpthread.so.0+0x76b9)
SUMMARY: MemorySanitizer: use-of-uninitialized-value /proc/self/cwd/src/core/lib/transport/transport.cc:198:14 in grpc_transport_destroy_stream(grpc_transport*, grpc_stream*, grpc_closure*)
Exiting
```

https://source.cloud.google.com/results/invocations/e6da9147-60ad-4fb3-b754-27f888b17bb7/targets/%2F%2Ftest%2Fcpp%2Fend2end:grpclb_end2end_test@poller%3Dpoll/log

**Comment by AspirinSJL** [comment] 2019-02-20 18:32
Duplicate of https://github.com/grpc/grpc/issues/17911.

**Closed by AspirinSJL** 2019-02-20 18:32 UTC
Labels: infra/BUILDPONY, infra/Bazel, lang/core
