### ISSUE TITLE
Eagerly type check channel args in Python

### ISSUE THREAD

**Issue by JackOfMostTrades** [grpc/grpc#16549] opened 2018-09-03 21:03 UTC
Minor thing, but the wrong argument type to options in python's grpc.[in]secure_channel causes a segfault (which was more difficult to debug than a python exception's stack trace would have been ;) ).

### What version of gRPC and what language are you using?
1.14.2, Python 
 
### What operating system (Linux, Windows, …) and version?
Linux, Ubuntu 18
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
Python 2.7.15rc1
 
### What did you do?
```
$ pip freeze | grep grpc
grpcio==1.14.2
grpcio-tools==1.14.2
$ python
Python 2.7.15rc1 (default, Apr 15 2018, 21:51:34) 
[GCC 7.3.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import grpc
>>> grpc.insecure_channel('example.com', options={"foo": "bar"})
ValueError: too many values to unpack (expected 2)
Exception ValueError: 'too many values to unpack (expected 2)' in 'grpc._cython.cygrpc._ArgumentProcessor.c' ignored
Segmentation fault (core dumped)
``` 

### What did you expect to see?
A python exception raised
 
### What did you see instead?
A segmentation fault

### Anything else we should know about your project / environment?
This was on a Ubuntu 18 system with Ubuntu's packaged version of python 2.7.

**Comment by mehrdada** [comment] 2018-10-15 17:07
@lidizheng fixed this in #16864. @JackOfMostTrades Can you try tomorrow's nightlies and let us know if the issue is satisfactorily addressed? I'm closing this issue now, but feel free to ping with feedback.

**Closed by mehrdada** 2018-10-15 17:07 UTC
Labels: disposition/help wanted, kind/enhancement, lang/Python, priority/P2
