### ISSUE TITLE
Failed: build_docker_http2

### ISSUE THREAD

**Issue by apolcyn** [grpc/grpc#25679] opened 2021-03-10 23:14 UTC
Bottom of the log:

```
Entering 'third_party/protobuf'
Submodule 'third_party/protobuf' (https://github.com/google/protobuf.git) registered for path 'third_party/protobuf'
Cloning into '/var/local/git/grpc/third_party/protobuf'...
Submodule path 'third_party/protobuf': checked out 'd7e943b8d2bc444a8c770644e73d090b486f8b37'
Entering 'third_party/protoc-gen-validate'
Submodule 'third_party/protoc-gen-validate' (https://github.com/envoyproxy/protoc-gen-validate.git) registered for path 'third_party/protoc-gen-validate'
Cloning into '/var/local/git/grpc/third_party/protoc-gen-validate'...
Submodule path 'third_party/protoc-gen-validate': checked out '872b28c457822ed9c2a5405da3c33f386ac0e86f'
Entering 'third_party/re2'
Submodule 'third_party/re2' (https://github.com/google/re2.git) registered for path 'third_party/re2'
Cloning into '/var/local/git/grpc/third_party/re2'...
Submodule path 'third_party/re2': checked out 'aecba11114cf1fac5497aeb844b6966106de3eb6'
Entering 'third_party/udpa'
Submodule 'third_party/udpa' (https://github.com/cncf/udpa.git) registered for path 'third_party/udpa'
Cloning into '/var/local/git/grpc/third_party/udpa'...
Submodule path 'third_party/udpa': checked out 'cc1b757b3eddccaaaf0743cbb107742bb7e3ee4f'
Entering 'third_party/zlib'
Submodule 'third_party/zlib' (https://github.com/madler/zlib) registered for path 'third_party/zlib'
Cloning into '/var/local/git/grpc/third_party/zlib'...
Submodule path 'third_party/zlib': checked out 'cacf7f1d4e3d44d871b605da3b647f07d718623f'
go: cannot find main module, but found .git/config in /var/local/git/grpc
	to create a module there, run:
	cd ../.. && go mod init
```

Seen in: https://github.com/grpc/grpc/pull/25672

**Comment by markdroth** [comment] 2021-03-11 23:09
Duplicate of #25660.

**Closed by markdroth** 2021-03-11 23:09 UTC
Labels: kind/bug, priority/P2
