### ISSUE TITLE
Doing an async request within an async server terminates the server

### ISSUE THREAD

**Issue by sjoerdvandenbos-prodrive** [grpc/grpc#32211] opened 2023-01-26 12:42 UTC
### What version of gRPC and what language are you using?
Python=3.11.1, gRPC=1.51.1

### What operating system (Linux, Windows,...) and version?
Windows 10 Enterprise 22H2

### What runtime / compiler are you using (e.g. python version or version of gcc)
Python 3.11.1 (tags/v3.11.1:a7a450f, Dec  6 2022, 19:58:39) [MSC v.1934 64 bit (AMD64)]

### What did you do?
I have provided a minimal reproducible example at https://github.com/sjoerdvandenbos-prodrive/grpc-asyncio-mre.
After installing the prerequisites, run the following commands each in a separate terminal
```shell
python hidden_server.py
python public_server.py
python client.py
```

### What did you expect to see?
on the public server:
3 logging events and a server that continues to serve

on the client:
A log printing "Hello from public."

on the hidden server:
nothing

### What did you see instead?
on the client:
.virtualenvs\minimum-reproducible-example-Gqdcx3Dk\Lib\site-packages\grpc\aio\_call.py", line 290, in __await__
    raise _create_rpc_error(self._cython_call._initial_metadata,
grpc.aio._call.AioRpcError: <AioRpcError of RPC that terminated with:
        status = StatusCode.UNKNOWN
        details = "Stream removed"
        debug_error_string = "UNKNOWN:Error received from peer ipv4:127.0.0.1:50051 {grpc_message:"Stream removed", grpc_status:2, created_time:"2023-01-26T10:49:50.3265439+00:00"}"

on the public server:
3 logging events and a server that crashed without throwing an exception

on the hidden server:
nothing

The interesting part happens on exiting the with block in public_server.py at line 17. I have reproduced this error without with block. In that case the exception happens when calling channel.close(). In both cases a function is called with the name _close():
https://github.com/grpc/grpc/blob/d14020d4e272770cd38af4ecc59e2b9e2161cd8f/src/python/grpcio/grpc/aio/_channel.py#L302

From here the critical part is line 315: task = task.get_stack(limit=1). This operation often fails the second iteration of the above task loop (line 313). The definition is found at asyncio.tasks.Task.get_stack() (line 154). This method simply returns base_tasks._task_get_stack(). found at asyncio.base_tasks._task_get_stack() (line 32). Here when reaching line 53, or alternatively upon debug inspection of task._coro.cr_frame, the frame disappears and the server crashes, at least this is what happens in my actual code, but it does not happen in this MRE in debug mode.

### Anything else we should know about your project / environment?
When changing the last line in public_server.py to:
asyncio.run(serve(), debug=True)
the problem stops. Alternatively when running this in vscode debug mode without break points, the code also runs without issues.

**Comment by sjoerdvandenbos-prodrive** [comment] 2023-01-27 09:02
I have reproduced the bug on Mac with the following, slightly different, error from the client.py

Traceback (most recent call last):
  File "/Users/evdb/projects/grpc-asyncio-mre/client.py", line 20, in <module>
    asyncio.run(do_request())
  File "/Users/evdb/.pyenv/versions/3.11.1/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/Users/evdb/.pyenv/versions/3.11.1/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/evdb/.pyenv/versions/3.11.1/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/Users/evdb/projects/grpc-asyncio-mre/client.py", line 14, in do_request
    response = await stub.DoPublicRequest(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/evdb/.local/share/virtualenvs/grpc-asyncio-mre-DT2oXjHD/lib/python3.11/site-packages/grpc/aio/_call.py", line 290, in __await__
    raise _create_rpc_error(self._cython_call._initial_metadata,
grpc.aio._call.AioRpcError: <AioRpcError of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "Socket closed"
	debug_error_string = "UNKNOWN:Error received from peer ipv6:%5B::1%5D:50051 {grpc_message:"Socket closed", grpc_status:14, created_time:"2023-01-26T16:16:49.632599-05:00"}"

**Comment by gnossen** [comment] 2023-01-27 17:49
@XuanWang-Amos Can you please try the reproduction? Fingers crossed that this also applies to Linux. It will be much easier to track down if that's the case.

**Comment by XuanWang-Amos** [comment] 2023-01-27 17:50
sure, I'll take a look.

**Comment by sjoerdvandenbos-prodrive** [comment] 2023-02-01 08:14
> sure, I'll take a look.

Were you able to reproduce on Linux?

**Comment by XuanWang-Amos** [comment] 2023-02-01 19:40
Sorry about the delay, I just tried using my Linux machine but unfortunately can't reproduce the issue, can you try run the example again with following debug flags?
`GRPC_VERBOSITY=debug GRPC_TRACE=all,-timer,-timer_check`

**Comment by XuanWang-Amos** [comment] 2023-02-02 00:31
Just tried on my Mac (with python 3.9.6 and grpc 1.51.1) but also not able to reproduce.

**Comment by sjoerdvandenbos-prodrive** [comment] 2023-02-02 09:28
[client_logs.LOG](https://github.com/grpc/grpc/files/10567310/client_logs.LOG)
[hidden_logs.LOG](https://github.com/grpc/grpc/files/10567311/hidden_logs.LOG)
[public_logs.LOG](https://github.com/grpc/grpc/files/10567312/public_logs.LOG)

I set the 2 environment variables and called the scripts like you asked, the calls are in the logs at the very top. The bottom is the last output before the script shutdown. As you can see, I only needed to ctrl-C terminate the hidden server. The public server shutdown on its own, so I think that means that the bug is reproduced.

**Comment by sjoerdvandenbos-prodrive** [comment] 2023-02-02 09:59
I managed to reproduce on Ubuntu 22.04 (WSL 2)

Server output:
![image](https://user-images.githubusercontent.com/123633921/216293051-6d7a66d2-7d86-42cc-816e-3654f1e9008f.png)

Client output:
![image](https://user-images.githubusercontent.com/123633921/216293231-9bb6a1d5-3305-43e5-a8d9-3d33ffc7c545.png)

will try on an actual Linux next.

**Comment by ZhuLegend** [comment] 2023-02-06 12:55
I met the same error on mac(macOS 13.1, python 3.11.1, grpc 1.15.1), but when I use python 3.9.16, the program runs correctly. Maybe this error is related to some change in the latest version of python?

**Comment by sjoerdvandenbos-prodrive** [comment] 2023-02-16 13:22
Hi @XuanWang-Amos this looks like a really hard problem, do you have any updates?

**Comment by XuanWang-Amos** [comment] 2023-02-16 17:43
Hi, sorry for the delay, we don't have Windows machine for testing so it will be hard for us to reproduce if it only happens on Windows (or WSL).

We do have Mac tho, I'll try reproduce it on Mac today and update here.

**Comment by XuanWang-Amos** [comment] 2023-02-16 19:04
Able to reproduce on macOS 13.2.1, python 3.11.1 and grpc 1.15.1, no errors in core logs, will need some time to check what's wrong.

I'm currently working on something else, so I might take a little longer to respond. If anyone else is having the same issue, please let me know and we can re-evaluate the priority. Thank you for your understanding.

**Comment by XuanWang-Amos** [comment] 2023-04-06 21:17
I took a look again, like you mentioned in description, the error is a segmentation fault caused by `task.get_stack(limit=1)` call.

The root cause is actually the same with https://github.com/grpc/grpc/issues/31441 which was found in Python 3.11.x (Related CPython issue: [Segfault on frame.f_back when frame is created with PyFrame_New()](https://github.com/python/cpython/issues/99110)).

The suggestion here is still one of the following:
* Downgrading to a 3.10.X interpreter.
* Waiting until the fix makes it into a released version of CPython.

Closing this one since there are no action items on our side, please let us know if you have other questions.

**Closed by XuanWang-Amos** 2023-04-06 21:17 UTC
Labels: kind/bug, lang/Python, platform/Windows, priority/P2
