### ISSUE TITLE
Client returns unknown error when server returns two identical headers.

### ISSUE THREAD

**Issue by yang-g** [grpc/grpc#10354] opened 2017-03-29 06:05 UTC
If somehow the server returns two content-type:application/grpc headers, the C++ client returns an grpc status with unknown error and status message "stream removed".

**Comment by ncteisen** [comment] 2017-12-13 01:59
How are you seeing this. I tried to recreate this scenario by adding duplicate metadata in http_server_filter, but I am seeing the client get this error:
```
{"created":"@1513130172.002935000","description":"Error received from peer","file":"src/core/lib/surface/call.cc","file_line":1147,"grpc_message":"Received RST_STREAM with error code 2","grpc_status":13}
``` 

Which is caused by the server transport noticing the duplicated metadata:
```
{"created":"@1513130172.002825000","description":"Failed sending initial metadata","file":"src/core/ext/filters/http/server/http_server_filter.cc","file_line":89,"referenced_errors":[{"created":"@1513130172.002824000","description":"Unallowed duplicate metadata","file":"src/core/lib/transport/metadata_batch.cc","file_line":111,"key":"content-type","value":"application/grpc"}]}
```

**Comment by yang-g** [comment] 2017-12-13 06:49
Sorry but I do not remember...

**Comment by ncteisen** [comment] 2017-12-13 16:42
Ok, going to close this for now

**Closed by ncteisen** 2017-12-13 16:42 UTC
Labels: lang/c++
