### ISSUE TITLE
Exceptions raised by signal handlers on the main thread while unary RPCs are in flight cause deadlock in Channel.close()

### ISSUE THREAD

**Issue by knuesel** [grpc/grpc#19973] opened 2019-08-16 12:46 UTC
### What version of gRPC and what language are you using?

 1.23.0
 
### What operating system (Linux, Windows,...) and version?
 
Ubuntu 18.04 with Linux 5.0.0
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
 
 Python 3.6.8

### What did you do?

Run the following client code and press `Ctrl-C` while stuck in the `SayHello()` call:

```python
import grpc

import hello_pb2 as pb
import hello_pb2_grpc as grpcpb

with grpc.insecure_channel('localhost:50051') as channel:
    stub = grpcpb.GreeterStub(channel)

    try:
        print('Calling SayHello()...')

        # The channel.close() call fails to interrupt the following:
        reply = stub.SayHello(pb.HelloRequest(), wait_for_ready=True)

        # It does interrupt the following though:
        #future = stub.SayHello.future(pb.HelloRequest(), wait_for_ready=True)
        #reply = future.result()

        print('Reply:', reply)

    except KeyboardInterrupt:
        print('\nInterrupted.')

    print('Closing channel...')
    channel.close()
    print('Channel closed')
```

The .proto file being:

```protobuf
syntax = "proto3";

package hello;

service Greeter {
  rpc SayHello (HelloRequest) returns (HelloReply);
}

message HelloRequest {}

message HelloReply {
  string message = 1;
}
```

### What did you expect to see?
 
When pressing `Ctrl-C`, the `channel.close()` call should abort the `SayHello()` call, so the program should terminate.

As the documentation says:

> Closing the Channel will immediately terminate all RPCs active with the Channel and it is not valid to invoke new RPCs with the Channel.

### What did you see instead?

The program gets stuck in the `channel.close()` call.

Pressing `Ctrl-C` two more times terminates the program with the following output:

```
Calling SayHello()...
^C
Interrupted.
Closing channel...
^C^CTraceback (most recent call last):
  File "hello-client.py", line 25, in <module>
    channel.close()
  File "/home/j/.local/lib/python3.6/site-packages/grpc/_channel.py", line 1088, in close
    self._close()
  File "/home/j/.local/lib/python3.6/site-packages/grpc/_channel.py", line 1072, in _close
    self._channel.close(cygrpc.StatusCode.cancelled, 'Channel closed!')
  File "src/python/grpcio/grpc/_cython/_cygrpc/channel.pyx.pxi", line 488, in grpc._cython.cygrpc.Channel.close
  File "src/python/grpcio/grpc/_cython/_cygrpc/channel.pyx.pxi", line 371, in grpc._cython.cygrpc._close
  File "src/python/grpcio/grpc/_cython/_cygrpc/channel.pyx.pxi", line 394, in grpc._cython.cygrpc._close
  File "/usr/lib/python3.6/threading.py", line 295, in wait
    waiter.acquire()
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "hello-client.py", line 26, in <module>
    print('Channel closed')
  File "/home/j/.local/lib/python3.6/site-packages/grpc/_channel.py", line 1084, in __exit__
    self._close()
  File "/home/j/.local/lib/python3.6/site-packages/grpc/_channel.py", line 1072, in _close
    self._channel.close(cygrpc.StatusCode.cancelled, 'Channel closed!')
  File "src/python/grpcio/grpc/_cython/_cygrpc/channel.pyx.pxi", line 488, in grpc._cython.cygrpc.Channel.close
  File "src/python/grpcio/grpc/_cython/_cygrpc/channel.pyx.pxi", line 371, in grpc._cython.cygrpc._close
  File "src/python/grpcio/grpc/_cython/_cygrpc/channel.pyx.pxi", line 408, in grpc._cython.cygrpc._close
  File "/usr/lib/python3.6/threading.py", line 295, in wait
    waiter.acquire()
KeyboardInterrupt
```

There is no problem when using the asynchronous API and blocking on `future.result()` (see the commented lines in the code).

**Comment by gnossen** [comment] 2019-08-16 16:45
@knuesel Thank you for the report and comprehensive reproduction case! Since you're reporting this issue the day after `1.23.0` was released, I was worried we had introduced a regression. However, I'm able to reproduce with every version since `wait_for_ready` was introduced.

**Comment by gnossen** [comment] 2019-08-19 20:48
It looks like what was happening was our call to [`PyErr_CheckSignals` in the completion queue poll loop](https://github.com/grpc/grpc/blob/master/src/python/grpcio/grpc/_cython/_cygrpc/completion_queue.pyx.pxi#L46) was allowing arbitrary Python code to run, with the possibility of raising an exception. But the surrounding code wasn't written to expect Python exceptions. I have a test and fix for this that will be up shortly.

**Closed** 2019-08-20 17:03 UTC
Labels: kind/bug, lang/Python, priority/P2
