### ISSUE TITLE
grpc c++ fails to compile (zlib)

### ISSUE THREAD

**Issue by Serapke** [grpc/grpc#13640] opened 2017-12-05 13:54 UTC
I'm trying to install gRPC for C++ by building from sources. I followed the steps but when I try to run 'make', I get a compilation error.
 
### What version of gRPC and what language are you using?
 
Tried 1.7.x
 
### What operating system (Linux, Windows, …) and version?
 
Compute Engine
GNU/Linux
Ubuntu 17.10

### What runtime / compiler are you using (e.g. python version or version of gcc)
 
C++
 
### What did you do?

```
 $ git clone -b $(curl -L https://grpc.io/release) https://github.com/grpc/grpc
 $ cd grpc
 $ git submodule update --init
 $ make
```
 
### What did you expect to see?
 
I expected the code to compile.
 
### What did you see instead?
 
[C]       Compiling third_party/zlib/infback.c
third_party/zlib/infback.c: In function ‘inflateBack’:
third_party/zlib/infback.c:479:25: error: this statement may fall through [-Werror=implicit-fallthrough=]
             state->mode = LEN;
             ~~~~~~~~~~~~^~~~~
third_party/zlib/infback.c:481:9: note: here
         case LEN:
         ^~~~
cc1: all warnings being treated as errors
Makefile:2564: recipe for target '/home/serapinas_m1/grpc/objs/opt/third_party/zlib/infback.o' failed
make: *** [/home/serapinas_m1/grpc/objs/opt/third_party/zlib/infback.o] Error 1

**Comment by bryantrobbins** [comment] 2017-12-11 07:34
I have the same version of ubuntu (17.10) on a VM, and get the same result on 1.7.x.

From some brief digging, this seems to be caused by gcc v 7+ (I have 7.2.0) enabling the reported -Wimplicit-fallthrough warning by default. When I add "-Wno-implicit-fallthrough" to the CPPFLAGS entry in the Makefile manually (line 330), I get past that error.

I then ran into a different gcc 7+ error, which may be fixed by this PR but is not merged to the v1.7.x branch yet: https://github.com/grpc/grpc/pull/12653.

It looks like we may need to back down to gcc < 7 for a build at the moment (or further modify the Makefile). Can anyone confirm the expected level of support for gcc 7 and/or ETA for compatibility in the 1.7.x branch?

**Comment by isheff** [comment] 2018-01-03 23:43
I have been able to reproduce the same error on a clean Ubuntu 17.10 VM, whose entire history is:
```
sudo apt-get install curl git build-essential autoconf libtool libgflags-dev libgtest-dev clang libc++-dev
git clone -b $(curl -L https://grpc.io/release) https://github.com/grpc/grpc
cd grpc
git submodule update --init
make
```

The `make` results in:

```
$ make
[MAKE]    Generating /home/user/grpc/libs/opt/pkgconfig/grpc.pc
[MAKE]    Generating /home/user/grpc/libs/opt/pkgconfig/grpc_unsecure.pc
[MAKE]    Generating cache.mk
make: Circular /home/user/grpc/libs/opt/libares.a <- /home/user/grpc/libs/opt/libz.a dependency dropped.
[C]       Compiling third_party/cares/cares/ares__close_sockets.c
[C]       Compiling third_party/cares/cares/ares__get_hostent.c
[C]       Compiling third_party/cares/cares/ares__read_line.c
[C]       Compiling third_party/cares/cares/ares__timeval.c
[C]       Compiling third_party/cares/cares/ares_cancel.c
[C]       Compiling third_party/cares/cares/ares_create_query.c
[C]       Compiling third_party/cares/cares/ares_data.c
[C]       Compiling third_party/cares/cares/ares_destroy.c
[C]       Compiling third_party/cares/cares/ares_expand_name.c
[C]       Compiling third_party/cares/cares/ares_expand_string.c
[C]       Compiling third_party/cares/cares/ares_fds.c
[C]       Compiling third_party/cares/cares/ares_free_hostent.c
[C]       Compiling third_party/cares/cares/ares_free_string.c
[C]       Compiling third_party/cares/cares/ares_getenv.c
[C]       Compiling third_party/cares/cares/ares_gethostbyaddr.c
[C]       Compiling third_party/cares/cares/ares_gethostbyname.c
[C]       Compiling third_party/cares/cares/ares_getnameinfo.c
[C]       Compiling third_party/cares/cares/ares_getopt.c
[C]       Compiling third_party/cares/cares/ares_getsock.c
[C]       Compiling third_party/cares/cares/ares_init.c
[C]       Compiling third_party/cares/cares/ares_library_init.c
[C]       Compiling third_party/cares/cares/ares_llist.c
[C]       Compiling third_party/cares/cares/ares_mkquery.c
[C]       Compiling third_party/cares/cares/ares_nowarn.c
[C]       Compiling third_party/cares/cares/ares_options.c
[C]       Compiling third_party/cares/cares/ares_parse_a_reply.c
[C]       Compiling third_party/cares/cares/ares_parse_aaaa_reply.c
[C]       Compiling third_party/cares/cares/ares_parse_mx_reply.c
[C]       Compiling third_party/cares/cares/ares_parse_naptr_reply.c
[C]       Compiling third_party/cares/cares/ares_parse_ns_reply.c
[C]       Compiling third_party/cares/cares/ares_parse_ptr_reply.c
[C]       Compiling third_party/cares/cares/ares_parse_soa_reply.c
[C]       Compiling third_party/cares/cares/ares_parse_srv_reply.c
[C]       Compiling third_party/cares/cares/ares_parse_txt_reply.c
[C]       Compiling third_party/cares/cares/ares_platform.c
[C]       Compiling third_party/cares/cares/ares_process.c
[C]       Compiling third_party/cares/cares/ares_query.c
[C]       Compiling third_party/cares/cares/ares_search.c
[C]       Compiling third_party/cares/cares/ares_send.c
[C]       Compiling third_party/cares/cares/ares_strcasecmp.c
[C]       Compiling third_party/cares/cares/ares_strdup.c
[C]       Compiling third_party/cares/cares/ares_strerror.c
[C]       Compiling third_party/cares/cares/ares_timeout.c
[C]       Compiling third_party/cares/cares/ares_version.c
[C]       Compiling third_party/cares/cares/ares_writev.c
[C]       Compiling third_party/cares/cares/bitncmp.c
[C]       Compiling third_party/cares/cares/inet_net_pton.c
[C]       Compiling third_party/cares/cares/inet_ntop.c
[C]       Compiling third_party/cares/cares/windows_port.c
[AR]      Creating /home/user/grpc/libs/opt/libares.a
[C]       Compiling third_party/zlib/adler32.c
[C]       Compiling third_party/zlib/compress.c
[C]       Compiling third_party/zlib/crc32.c
[C]       Compiling third_party/zlib/deflate.c
[C]       Compiling third_party/zlib/gzclose.c
[C]       Compiling third_party/zlib/gzlib.c
[C]       Compiling third_party/zlib/gzread.c
[C]       Compiling third_party/zlib/gzwrite.c
[C]       Compiling third_party/zlib/infback.c
third_party/zlib/infback.c: In function ‘inflateBack’:
third_party/zlib/infback.c:479:25: error: this statement may fall through [-Werror=implicit-fallthrough=]
             state->mode = LEN;
             ~~~~~~~~~~~~^~~~~
third_party/zlib/infback.c:481:9: note: here
         case LEN:
         ^~~~
cc1: all warnings being treated as errors
Makefile:2569: recipe for target '/home/user/grpc/objs/opt/third_party/zlib/infback.o' failed
make: *** [/home/user/grpc/objs/opt/third_party/zlib/infback.o] Error 1
```

**Comment by isheff** [comment] 2018-01-03 23:54
I tried `make CFLAGS='-Wno-implicit-fallthrough'` only to get a different error:

```
$ make CFLAGS='-Wno-implicit-fallthrough'
[MAKE]    Generating /home/user/grpc/libs/opt/pkgconfig/grpc.pc
[MAKE]    Generating /home/user/grpc/libs/opt/pkgconfig/grpc_unsecure.pc
[MAKE]    Generating cache.mk
make: Circular /home/user/grpc/libs/opt/libares.a <- /home/user/grpc/libs/opt/libz.a dependency dropped.
[C]       Compiling third_party/cares/cares/ares__close_sockets.c
[C]       Compiling third_party/cares/cares/ares__get_hostent.c
[C]       Compiling third_party/cares/cares/ares__read_line.c
[C]       Compiling third_party/cares/cares/ares__timeval.c
[C]       Compiling third_party/cares/cares/ares_cancel.c
[C]       Compiling third_party/cares/cares/ares_create_query.c
[C]       Compiling third_party/cares/cares/ares_data.c
[C]       Compiling third_party/cares/cares/ares_destroy.c
[C]       Compiling third_party/cares/cares/ares_expand_name.c
[C]       Compiling third_party/cares/cares/ares_expand_string.c
[C]       Compiling third_party/cares/cares/ares_fds.c
[C]       Compiling third_party/cares/cares/ares_free_hostent.c
[C]       Compiling third_party/cares/cares/ares_free_string.c
[C]       Compiling third_party/cares/cares/ares_getenv.c
[C]       Compiling third_party/cares/cares/ares_gethostbyaddr.c
[C]       Compiling third_party/cares/cares/ares_gethostbyname.c
[C]       Compiling third_party/cares/cares/ares_getnameinfo.c
[C]       Compiling third_party/cares/cares/ares_getopt.c
[C]       Compiling third_party/cares/cares/ares_getsock.c
[C]       Compiling third_party/cares/cares/ares_init.c
[C]       Compiling third_party/cares/cares/ares_library_init.c
[C]       Compiling third_party/cares/cares/ares_llist.c
[C]       Compiling third_party/cares/cares/ares_mkquery.c
[C]       Compiling third_party/cares/cares/ares_nowarn.c
[C]       Compiling third_party/cares/cares/ares_options.c
[C]       Compiling third_party/cares/cares/ares_parse_a_reply.c
[C]       Compiling third_party/cares/cares/ares_parse_aaaa_reply.c
[C]       Compiling third_party/cares/cares/ares_parse_mx_reply.c
[C]       Compiling third_party/cares/cares/ares_parse_naptr_reply.c
[C]       Compiling third_party/cares/cares/ares_parse_ns_reply.c
[C]       Compiling third_party/cares/cares/ares_parse_ptr_reply.c
[C]       Compiling third_party/cares/cares/ares_parse_soa_reply.c
[C]       Compiling third_party/cares/cares/ares_parse_srv_reply.c
[C]       Compiling third_party/cares/cares/ares_parse_txt_reply.c
[C]       Compiling third_party/cares/cares/ares_platform.c
[C]       Compiling third_party/cares/cares/ares_process.c
[C]       Compiling third_party/cares/cares/ares_query.c
[C]       Compiling third_party/cares/cares/ares_search.c
[C]       Compiling third_party/cares/cares/ares_send.c
[C]       Compiling third_party/cares/cares/ares_strcasecmp.c
[C]       Compiling third_party/cares/cares/ares_strdup.c
[C]       Compiling third_party/cares/cares/ares_strerror.c
[C]       Compiling third_party/cares/cares/ares_timeout.c
[C]       Compiling third_party/cares/cares/ares_version.c
[C]       Compiling third_party/cares/cares/ares_writev.c
[C]       Compiling third_party/cares/cares/bitncmp.c
[C]       Compiling third_party/cares/cares/inet_net_pton.c
[C]       Compiling third_party/cares/cares/inet_ntop.c
[C]       Compiling third_party/cares/cares/windows_port.c
[AR]      Creating /home/user/grpc/libs/opt/libares.a
[C]       Compiling third_party/zlib/adler32.c
[C]       Compiling third_party/zlib/compress.c
[C]       Compiling third_party/zlib/crc32.c
[C]       Compiling third_party/zlib/deflate.c
[C]       Compiling third_party/zlib/gzclose.c
[C]       Compiling third_party/zlib/gzlib.c
third_party/zlib/gzlib.c: In function ‘gz_open’:
third_party/zlib/gzlib.c:14:17: error: implicit declaration of function ‘lseek’; did you mean ‘fseek’? [-Werror=implicit-function-declaration]
 #  define LSEEK lseek
                 ^
third_party/zlib/gzlib.c:252:9: note: in expansion of macro ‘LSEEK’
         LSEEK(state->fd, 0, SEEK_END);  /* so gzoffset() is correct */
         ^~~~~
cc1: all warnings being treated as errors
Makefile:2569: recipe for target '/home/user/grpc/objs/opt/third_party/zlib/gzlib.o' failed
make: *** [/home/user/grpc/objs/opt/third_party/zlib/gzlib.o] Error 1

```

**Comment by isheff** [comment] 2018-01-04 21:26
I have made an example Ubuntu 17.10 VirtualBox VM, in which everything has been set up, and `make` has failed, available at https://blacker.caltech.edu/~isheff/Generic_Ubuntu_2_grpc_does_not_compile.ova .

Username: user
Password: xyzzy

The complete history of this machine is as follows:
```
sudo apt-get install curl git build-essential autoconf libtool libgflags-dev libgtest-dev clang libc++-dev
git clone -b $(curl -L https://grpc.io/release) https://github.com/grpc/grpc
cd grpc
git submodule update --init
make
```

**Comment by jtattermusch** [comment] 2018-01-23 11:41
This is duplicate of https://github.com/grpc/grpc/issues/13854 (ubuntu 17.10 has gcc 7.2)

**Closed by jtattermusch** 2018-01-23 11:41 UTC
Labels: kind/customer issue, priority/P2
