### ISSUE TITLE
flow control bug in python grpcio >= 1.4.0

### ISSUE THREAD

**Issue by wjackson** [grpc/grpc#11966] opened 2017-07-28 04:40 UTC
### Description

There seems to be a flow control bug in the python client as of `1.4.0`. 

Before `1.4.0` (`1.3.5` for example) a slow client of a streaming method would cause back pressure that was only relieved when the client consumed enough messages to allow room for another block of messages from the server. Just what we'd expect.

As of `1.4.0` the back pressure seems to be relieved whenever the client consumes ***any*** message. That results in the server sending new blocks of messages much more frequently than it should. The server gets way ahead of the client and the client memory use grows continuously until it crashes. In fact, the faster the client consumes messages the faster it's memory usage grows (so long as the server is still producing faster than the client is consuming.)

I also found the bug on the `1.4.x` and `master` branches as of now. I'm assuming it's a client side bug because varying the version or language (I tried go) on the server side doesn't seem to make a difference.

OS: Fedora 25
Python: 2.7.13

### Example Code

These examples use `route_guide.proto` and the associated generated python code in the `examples` directory of this repo.

server.py:
```python
from __future__ import print_function
from concurrent import futures
import time
import grpc
import route_guide_pb2
import route_guide_pb2_grpc

_ONE_DAY_IN_SECONDS = 60 * 60 * 24

class RouteGuideServicer(route_guide_pb2_grpc.RouteGuideServicer):

    def RouteChat(self, request_iterator, context):
        i = 0
        while True:
            print("%d: %d" % (time.time(), i))
            yield route_guide_pb2.RouteNote(
                message = "X" * (32*1024),
            )
            i += 1

def serve():
    server = grpc.server(futures.ThreadPoolExecutor(max_workers=10))
    route_guide_pb2_grpc.add_RouteGuideServicer_to_server(
            RouteGuideServicer(), server)
    server.add_insecure_port('[::]:50051')
    server.start()
    try:
        while True:
            time.sleep(_ONE_DAY_IN_SECONDS)
    except KeyboardInterrupt:
        server.stop(0)

if __name__ == '__main__':
    serve()
```

client.py:
```python
from __future__ import print_function
import time
import grpc
import route_guide_pb2
import route_guide_pb2_grpc

def guide_route_chat(stub):
    i = 0
    for response in stub.RouteChat(iter(())):
        print("%d: %d" % (time.time(), i))
        time.sleep(10)
        i += 1

def run():
    channel = grpc.insecure_channel('localhost:50051')
    stub = route_guide_pb2_grpc.RouteGuideStub(channel)
    guide_route_chat(stub)

if __name__ == '__main__':
    run()
```

### 1.3.5 Output (Working)

```
$ python client.py
1501214899: 0
1501214909: 1
1501214919: 2
1501214929: 3
1501214939: 4
1501214949: 5
1501214959: 6
```
```
$ python server.py
1501214899: 0
1501214899: 1
1501214899: 2
1501214899: 3
1501214929: 4
1501214929: 5
1501214929: 6
1501214959: 7
1501214959: 8
1501214959: 9
1501214959: 10

```

### 1.4.0 Output (Broken)

```
$ python client.py
1501214672: 0
1501214682: 1
1501214692: 2
1501214702: 3
1501214712: 4
1501214722: 5
1501214732: 6
```
```
$ python server.py
1501214672: 0
1501214672: 1
1501214672: 2
1501214672: 3
1501214682: 4
1501214682: 5
1501214682: 6
1501214692: 7
1501214692: 8
1501214692: 9
1501214702: 10
1501214702: 11
1501214702: 12
1501214702: 13
1501214712: 14
1501214712: 15
1501214712: 16
1501214712: 17
1501214722: 18
1501214722: 19
1501214722: 20
1501214722: 21
1501214722: 22
1501214732: 23
1501214732: 24
1501214732: 25
1501214732: 26
1501214732: 27

```

**Comment by nathanielmanistaatgoogle** [comment] 2017-09-14 21:55
Thank you for the report. A flow control bug would be both very surprising and very concerning.

Are you able to reproduce the problem with [our recent metadata leak fix](https://github.com/grpc/grpc/pull/12466) patched in?

If you run with the `GRPC_TRACE=all` and `GRPC_VERBOSITY=DEBUG` environment variables are you able to draw any further insights into what might be happening?

**Comment by wjackson** [comment] 2017-09-15 22:59
Sadly #12466 didn't fix this issue. I may have found the problem commit though.

I created the test below and bisected. That identified this commit: f036076 *Fix flow control problem*.  I verified that if I revert that on the v1.4.x branch the problem goes away. 

I don't think I have enough context to try to fix `chttp2_transport.c` in it's current form so hopefully someone else can have a look.

Here's the test I used for bisecting:

```python
from __future__ import print_function
import sys
from concurrent import futures
import time
import threading
import grpc
import route_guide_pb2
import route_guide_pb2_grpc

_ONE_DAY_IN_SECONDS = 60 * 60 * 24

sent_count = 0
recv_count = 0

class RouteGuideServicer(route_guide_pb2_grpc.RouteGuideServicer):
    def RouteChat(self, request_iterator, context):
        global sent_count
        while True:
            yield route_guide_pb2.RouteNote(
                message = "X" * (32*1024),
            )
            sent_count += 1

def serve():
    server = grpc.server(futures.ThreadPoolExecutor(max_workers=10))
    route_guide_pb2_grpc.add_RouteGuideServicer_to_server(
            RouteGuideServicer(), server)
    server.add_insecure_port('[::]:50051')
    server.start()
    try:
        while True:
            time.sleep(_ONE_DAY_IN_SECONDS)
    except KeyboardInterrupt:
        server.stop(0)

def run_client():
    global recv_count
    channel = grpc.insecure_channel('localhost:50051')
    stub = route_guide_pb2_grpc.RouteGuideStub(channel)

    req = route_guide_pb2.RouteNote(message="msg")
    for response in stub.RouteChat(iter([req])):
        recv_count += 1

        # if we get to 20 without failing then success!
        if recv_count > 20:
            sys.exit(0)

        # if spread b/w sent an recv get's too big then fail
        spread = sent_count - recv_count
        if spread > 10:
            sys.exit(1)

        time.sleep(.001)

if __name__ == '__main__':
    server_t = threading.Thread(target=serve)
    server_t.daemon = True
    server_t.start()
    time.sleep(.1)
    run_client()
`

**Comment by ncteisen** [comment] 2017-09-18 13:06
Does the problem exist at HEAD? There was a big flow control re write
recently (see here <https://github.com/grpc/grpc/pull/11720>)

**Comment by wjackson** [comment] 2017-09-18 15:58
Yep. I continue to see the problem post #11720.

Should be easy to replicate using the example code I posted. As @nathanielmanistaatgoogle mentioned, a flow control bug would be pretty surprising (especially one that's existed since 1.4.0) so I'm curious to know if this is reproducible by devs that work on the flow control part of this project.

**Comment by nathanielmanistaatgoogle** [comment] 2017-09-19 16:44
Thank you for the investigation, @wjackson!

Minor simplification: why instantiate a request message at all? Why not just pass `iter(())` in your RPC invocation?

What's clear to me is that there absolutely is a defect because one side of an RPC shouldn't be able to so easily OOM the other side. What's not yet clear to me is that your demonstration has awareness of how large the flow control window is - there _is_ such a window, and it does allow the service-side application _some_ freedom to get ahead of the client. Can your reproduction code make judgements like "the flow control window must have been no more than `<integer>` bytes at the start of the RPC but now appears to have grown to at least `<integer>` bytes"?

@muxi: what do you make of @wjackson's indication that the defect seems to have been introduced in [f03607658a00f63e16363433466b6675efb4ca46](https://github.com/grpc/grpc/commit/f03607658a00f63e16363433466b6675efb4ca46)?

**Comment by nathanielmanistaatgoogle** [comment] 2017-09-19 16:47
@wjackson: have you yet tried patching in [pull request 12636](https://github.com/grpc/grpc/pull/12636)?

@ctiller: should @wjackson have any expectation that [pull request 12636](https://github.com/grpc/grpc/pull/12636) contains a fix for this issue?

**Comment by nathanielmanistaatgoogle** [comment] 2017-09-19 16:51
@wjackson: is the flow control window size settable with a channel argument? If so, have you tried setting it explicitly?

**Comment by wjackson** [comment] 2017-09-19 22:59
@nathanielmanistaatgoogle no luck with pull request #12636 :(

**Comment by muxi** [comment] 2017-09-19 23:15
Interesting. The changes in that commit is supposed to make a narrower throttle instead of allowing more data to be sent. I am curious how that made more server data flow.

**Comment by ncteisen** [comment] 2017-09-20 00:33
Muxi, your commit would allow more data to be sent I think, since it is
calling incoming_byte_stream_update_flow_control less restrictively (IIRC
it was fixing the issue that the gRPC specific header was not being counted
for the client's flow control, thus stalling out and deadlocking
eventually).

The logic changed a bit since my overhaul. As soon as I return to the
office (away for the rest of the week on a recruiting trip), I plan to
reproduce the issue with a c end2end test, and then fix it.

**Comment by muxi** [comment] 2017-09-20 00:45
Thanks Noah. Let me know when you start with this and we can debug this together.

**Comment by wjackson** [comment] 2017-12-05 18:09
Fyi, I just tested this on v1.8.0-pre2 and the problem is still there.

**Comment by nathanielmanistaatgoogle** [comment] 2018-01-17 22:58
@wjackson: are you able to express your defect reproduction in the form of a failing unit test added to the codebase in a pull request? It sounds like the problem you're having is still present but I'd like to see something much more like a smoking gun. It would be very interesting if you were able to show us something like a failing assertion statement that clearly identifies exactly what happened (message pulled from stream source? message delivered to stream sink?) that should not have happened.

**Comment by wjackson** [comment] 2018-01-19 20:16
@nathanielmanistaatgoogle: I'd be up for working on that but I'd rather not spend the time unless that's something that really would be helpful. And I'm a little skeptical that the form of the example code is the blocker to a fix here.

I'm guessing my understanding of the issue is just wrong because if the situation really is as bleak as the example code suggests I would think you'd be getting lots of loud complaints. So it'd be nice to get some feedback before diving into the project of writing low-level unit tests to exercise the bug:

- Does the example code not successfully demonstrate the problem for you?
- Do all slow-subscribers not leak like crazy?
- Is the slow-subscriber case super rare or unimportant for some reason?
- Is there a reason why my example code is a slow-subscriber-special-case and not a slow-subscriber-general-case?
- Have devs worked on this but then been blocked because they don't have a low-level unit test showing the problem?

**Comment by srini100** [comment] 2018-03-30 16:55
Looks like same as #12383. This should now be fixed with #14747. Closing this issue.

**Closed by srini100** 2018-03-30 16:55 UTC
Labels: area/core, disposition/requires reporter action, kind/bug, lang/Python, priority/P1

**Comment by wjackson** [comment] 2018-03-30 17:47
I just tested. Yes this seems to fix the issue. Thanks!

**Comment by srini100** [comment] 2018-03-30 18:11
@wjackson  Thanks for testing and apologies for dropping this on the floor for so long.
