### ISSUE TITLE
python_linux_opt_native.py34.test.health_check._health_servicer_test.HealthServicerTest flakes with StatusCode.UNIMPLEMENTED

### ISSUE THREAD

**Issue by adelez** [grpc/grpc#10806] opened 2017-04-21 23:22 UTC
https://grpc-testing.appspot.com/job/gRPC_master_linux/2175/testReport/junit/(root)/python_linux_opt_native/py34_test_health_check__health_servicer_test_HealthServicerTest/

**Comment by adelez** [comment] 2017-04-21 23:34
++ dirname /var/local/git/grpc/tools/run_tests/helper_scripts/run_python.sh
+ cd /var/local/git/grpc/tools/run_tests/helper_scripts/../../..
++ realpath py34/bin/python
+ PYTHON=/var/local/git/grpc/py34/bin/python3.4
++ pwd
+ ROOT=/var/local/git/grpc
+ /var/local/git/grpc/py34/bin/python3.4 /var/local/git/grpc/src/python/grpcio_tests/setup.py test_lite
running test_lite
Running       health_check._health_servicer_test.HealthServicerTest.test_empty_service
[95mTesting gRPC Python...
[0m[92mSUCCESS       health_check._health_servicer_test.HealthServicerTest.test_empty_service
[0mRunning       health_check._health_servicer_test.HealthServicerTest.test_not_found_service
[92mSUCCESS       health_check._health_servicer_test.HealthServicerTest.test_not_found_service
[0mRunning       health_check._health_servicer_test.HealthServicerTest.test_not_serving_service
[91mERROR         health_check._health_servicer_test.HealthServicerTest.test_not_serving_service
[0mRunning       health_check._health_servicer_test.HealthServicerTest.test_serving_service
[92mSUCCESS       health_check._health_servicer_test.HealthServicerTest.test_serving_service
[0mRunning       health_check._health_servicer_test.HealthServicerTest.test_unknown_serivce
[92mSUCCESS       health_check._health_servicer_test.HealthServicerTest.test_unknown_serivce
[0m5 tests finished:
	4 successful
	1 unsuccessful
	0 skipped
	0 expected failures
	0 unexpected successes
Interrupted Tests:
	[]

Errors/Failures: 
[91mhealth_check._health_servicer_test.HealthServicerTest.test_not_serving_service[0m
[1mtraceback:[0m
Traceback (most recent call last):
  File "/usr/lib/python3.4/unittest/case.py", line 58, in testPartExecutor
    yield
  File "/usr/lib/python3.4/unittest/case.py", line 577, in run
    testMethod()
  File "/var/local/git/grpc/src/python/grpcio_tests/tests/health_check/_health_servicer_test.py", line 82, in test_not_serving_service
    resp = self._stub.Check(request)
  File "/var/local/git/grpc/py34/lib/python3.4/site-packages/grpc/_channel.py", line 507, in __call__
    return _end_unary_response_blocking(state, call, False, deadline)
  File "/var/local/git/grpc/py34/lib/python3.4/site-packages/grpc/_channel.py", line 455, in _end_unary_response_blocking
    raise _Rendezvous(state, None, None, deadline)
grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with (StatusCode.UNIMPLEMENTED, Method not found!)>

[1mstdout:[0m

[1mstderr:[0m


Unexpected successes: []
Test failure

**Comment by nathanielmanistaatgoogle** [comment] 2017-06-07 21:13
I'm going to call this a duplicate of [issue 10049](https://github.com/grpc/grpc/issues/10049).

**Closed by nathanielmanistaatgoogle** 2017-06-07 21:13 UTC
Labels: BUILDPONY, python
