### ISSUE TITLE
Listen to grpc_channel state on GRPCHost, so a failed channel isn't reused

### ISSUE THREAD

**Issue by jcanizales** [grpc/grpc#5614] opened 2016-03-05 00:19 UTC
Some HTTP/2 servers send a `go_away` to streams that are idle for too long, at which point the stream can't be used again by the client. This is supposed to surface in the C library as the `grpc_channel` transitioning to one of the failure states. `GRPCHost` has to listen to state changes and, on failure, release its `GRPCChannel` so that the `grpc_channel` it wraps isn't reused, and is properly destroyed.

We need the following test:

1. Client connects to server (completing an RPC to make sure the connection was established).
2. Server sends `go_away` on that stream after the RPC is completed.
3. Client sends another RPC to the same host.

The second RPC wouldn't currently succeed, and this fix has to make it succeed.

**Comment by ctiller** [comment] 2016-03-05 00:21
I'd argue that you should not release the grpc_channel unless you see fatal
failure.

**Comment by jcanizales** [comment] 2016-03-05 00:25
Is that what it'll transition to upon receiving a `go_away`? My understanding is after the server sends that, the stream can't be reused.

**Comment by ctiller** [comment] 2016-03-05 00:34
A transport can't be reused, but a channel can reconnect to a new backend.

**Comment by jcanizales** [comment] 2016-03-05 01:02
> can

Are you trying to tell me the C layer is expected to take care of goaways automatically, and so this is a bug that should be filed for core? The problem here isn't necessarily having to pick a different backend.

**Comment by ctiller** [comment] 2016-03-05 01:13
So grpc streams (the individual calls) are going to finish upon disconnect,
but a grpc channel will reconnect upon the next new call being started.

**Comment by jcanizales** [comment] 2016-03-05 01:32
Ah, that's not what people are seeing. I'll CC you on the internal tracker.

**Comment by hsaliak** [comment] 2016-04-29 18:43
Duplicate of #5851, let's continue the discussion there.

**Closed by hsaliak** 2016-04-29 18:43 UTC
Labels: ObjC
