### ISSUE TITLE
New Failure: httpscli_test (and httpcli_test)

### ISSUE THREAD

**Issue by dgquintas** [grpc/grpc#13650] opened 2017-12-05 22:47 UTC
- Test: httpscli_test
- Poll Strategy: poll
- URL: https://kokoro2.corp.google.com/job/grpc/job/ubuntu/job/master/job/grpc_basictests_c_cpp_dbg/611

**Comment by jtattermusch** [comment] 2018-02-21 11:14
Recent occurences:
https://sponge.corp.google.com/invocation?id=5f6206f5-37e6-4e40-b8e8-b935f34b416f
https://sponge.corp.google.com/invocation?id=b3676043-0a72-415c-920b-c354563f8eb1
https://sponge.corp.google.com/invocation?id=72bfb84a-c961-4eae-9ba0-9b2655cff5dd

**Comment by jtattermusch** [comment] 2018-03-12 11:10
still seeing this on master

**Comment by yashykt** [comment] 2018-03-13 21:39
It's difficult to reproduce this locally. I'll try logging stuff so we get more information.

**Comment by jtattermusch** [comment] 2018-03-19 14:36
After adding the extra logging information in #14700, the response status is `0` - which doesn't correspond to any HTTP status code. To me, this looks a bit like a race condition (seeing response that's not fully set yet?) - but I'm just guessing.
```
Failure
D0318 09:19:05.323453261   15284 ev_posix.cc:142]            Using polling engine: poll
D0318 09:19:05.323581647   15284 dns_resolver.cc:331]        Using native dns resolver
D0318 09:19:10.325374393   15284 test_config.cc:391]         test slowdown factor: sanitizer=1, fixture=1, poller=1, total=1
D0318 09:19:10.325682682   15284 ev_posix.cc:142]            Using polling engine: poll
D0318 09:19:10.325716183   15284 dns_resolver.cc:331]        Using native dns resolver
I0318 09:19:10.325752137   15284 httpscli_test.cc:70]        test_get
I0318 09:19:10.325757067   15284 httpscli_test.cc:73]        requesting from localhost:26407
I0318 09:19:25.326871020   16003 httpscli_test.cc:52]        response status 0
E0318 09:19:25.326893496   16003 httpscli_test.cc:53]        assertion failed: response->status == 200
```

**Comment by yashykt** [comment] 2018-03-23 23:52
It might also just be an error returned httpcli library. For example, the server was not yet started.

**Comment by jtattermusch** [comment] 2018-05-10 11:53
This is still happening, a few recent occurrences:
https://source.cloud.google.com/results/invocations/61c24fe5-3f64-4f9c-b295-4a6ecaf146ba
https://source.cloud.google.com/results/invocations/0dda749c-888d-4eb6-afc2-7edaff6927d5
https://source.cloud.google.com/results/invocations/bef71cc2-b582-44c1-87db-d5e4d3a6a938

A more careful look at the logs reveals two things:
It returns response == 0  because the request has timed out (timeout set to 15secs in the test)
```
I0421 23:18:05.258969568   14514 httpcli_test.cc:68]         test_get
I0421 23:18:05.259000679   14514 httpcli_test.cc:71]         requesting from localhost:30213
... 15sec wait here....
I0421 23:19:20.259763060   14517 httpcli_test.cc:50]         response status 0
E0421 23:19:20.259784984   14517 httpcli_test.cc:51]         assertion failed: response->status == 200
```

The server has definitely already started, as we've seen cases where the GET request succeeds and a subsequent POST to the same server fails:
```
I0506 09:38:12.160643462   14602 httpcli_test.cc:68]         test_get
I0506 09:38:12.160684216   14602 httpcli_test.cc:71]         requesting from localhost:14568
127.0.0.1 - - [06/May/2018 09:38:12] "GET /get HTTP/1.0" 200 -
I0506 09:38:12.161980400   14602 httpcli_test.cc:50]         response status 200
I0506 09:38:12.162001820   14602 httpcli_test.cc:107]        test_post
I0506 09:38:12.162006204   14602 httpcli_test.cc:110]        posting to localhost:14568
I0506 09:39:27.162667024   14606 httpcli_test.cc:50]         response status 0
E0506 09:39:27.162693533   14606 httpcli_test.cc:51]         assertion failed: response->status == 200
```

So it looks like this just needs more debugging. 
@yashykt  what have we done to rootcause this? This flake has been open for several months and it keeps coming up.

**Comment by yashykt** [comment] 2018-05-11 19:51
Yeah you're right. I'll spend some more time on this next week.

**Comment by yashykt** [comment] 2018-05-23 22:40
UPDATE - I spent some some more time on this. Reading the code doesn't make the reason for the error obvious. I'll add additional statements to log the error too.

**Comment by jtattermusch** [comment] 2018-06-05 07:41
We have two more occurrences since the extra logging was added:
https://source.cloud.google.com/results/invocations/661de751-a603-49bf-907a-685e0a0fce86/targets/github%2Fgrpc%2Fc_linux_dbg_native_x64_clang3.6/tests
https://source.cloud.google.com/results/invocations/bb781006-62ba-4bfa-b043-d8fa69c19843/targets/github%2Fgrpc%2Fc_linux_dbg_native/tests

```
D0601 03:57:05.923713395   12355 ev_posix.cc:145]            Using polling engine: poll-cv
D0601 03:57:05.923802363   12355 dns_resolver.cc:339]        Using native dns resolver
D0601 03:57:11.925838538   12355 test_config.cc:391]         test slowdown factor: sanitizer=1, fixture=1, poller=5, total=5
D0601 03:57:11.926084078   12355 ev_posix.cc:145]            Using polling engine: poll-cv
D0601 03:57:11.926115527   12355 dns_resolver.cc:339]        Using native dns resolver
I0601 03:57:11.926157581   12355 httpscli_test.cc:71]        test_get
I0601 03:57:11.926164187   12355 httpscli_test.cc:74]        requesting from localhost:20804
I0601 03:58:26.927426571   13346 httpscli_test.cc:52]        response status=0 error={"created":"@1527825506.927349048","description":"Failed HTTP requests to all targets","file":"src/core/lib/http/httpcli.cc","file_line":202,"referenced_errors":[{"created":"@1527825506.927185582","description":"Failed HTTP/1 client request","file":"src/core/lib/http/httpcli.cc","file_line":112,"referenced_errors":[{"created":"@1527825506.927163457","description":"Failed to connect to remote host: FD shutdown","file":"src/core/lib/iomgr/ev_poll_posix.cc","file_line":469,"grpc_status":14,"os_error":"Timeout occurred","referenced_errors":[{"created":"@1527825506.927137467","description":"connect() timed out","file":"src/core/lib/iomgr/tcp_client_posix.cc","file_line":114}],"target_address":"ipv6:[::1]:20804"},{"created":"@1527825506.927330346","description":"Failed to connect to remote host: FD shutdown","file":"src/core/lib/iomgr/ev_poll_posix.cc","file_line":469,"grpc_status":14,"os_error":"Timeout occurred","referenced_errors":[{"created":"@1527825506.927320988","description":"connect() timed out","file":"src/core/lib/iomgr/tcp_client_posix.cc","file_line":114}],"target_address":"ipv4:127.0.0.1:20804"}]}]}
E0601 03:58:26.927464243   13346 httpscli_test.cc:54]        assertion failed: response->status == 200
*******************************
Caught signal SIGABRT
```

```
D0604 12:35:00.163066597   14016 ev_posix.cc:145]            Using polling engine: poll
D0604 12:35:00.163172355   14016 dns_resolver.cc:339]        Using native dns resolver
D0604 12:35:05.164942560   14016 test_config.cc:391]         test slowdown factor: sanitizer=1, fixture=1, poller=1, total=1
D0604 12:35:05.165236152   14016 ev_posix.cc:145]            Using polling engine: poll
D0604 12:35:05.165262542   14016 dns_resolver.cc:339]        Using native dns resolver
I0604 12:35:05.165302678   14016 httpscli_test.cc:71]        test_get
I0604 12:35:05.165307491   14016 httpscli_test.cc:74]        requesting from localhost:13829
I0604 12:35:20.166601048   14968 httpscli_test.cc:52]        response status=0 error={"created":"@1528115720.166487373","description":"Failed HTTP requests to all targets","file":"src/core/lib/http/httpcli.cc","file_line":202,"referenced_errors":[{"created":"@1528115720.166350912","description":"Failed HTTP/1 client request","file":"src/core/lib/http/httpcli.cc","file_line":112,"referenced_errors":[{"created":"@1528115720.166331482","description":"Failed to connect to remote host: FD shutdown","file":"src/core/lib/iomgr/ev_poll_posix.cc","file_line":469,"grpc_status":14,"os_error":"Timeout occurred","referenced_errors":[{"created":"@1528115720.166302849","description":"connect() timed out","file":"src/core/lib/iomgr/tcp_client_posix.cc","file_line":114}],"target_address":"ipv6:[::1]:13829"},{"created":"@1528115720.166479985","description":"Failed to connect to remote host: FD shutdown","file":"src/core/lib/iomgr/ev_poll_posix.cc","file_line":469,"grpc_status":14,"os_error":"Timeout occurred","referenced_errors":[{"created":"@1528115720.166472943","description":"connect() timed out","file":"src/core/lib/iomgr/tcp_client_posix.cc","file_line":114}],"target_address":"ipv4:127.0.0.1:13829"}]}]}
E0604 12:35:20.166639838   14968 httpscli_test.cc:54]        assertion failed: response->status == 200
*******************************
Caught signal SIGABRT
```

**Comment by yashykt** [comment] 2018-06-05 18:45
Based on the extra logging, we are not able to connect to the server. We are either getting an EINPROGRESS or an EWOULDBLOCK on the syscall. It is most likely an issue like all the ephemeral ports on the server being used up which means too many connections.

The reason why I think EINPROGRESS is unlikely because 15 seconds should be a sufficient amount of time for connect to finish.

**Comment by yashykt** [comment] 2018-10-25 22:18
haven't seen any new reports on this. Closing this

**Comment by jtattermusch** [comment] 2018-10-26 09:56
Quick search reveals that this problem is still happening regularly (despite it's rather low flakiness rate).

```
select * from jenkins_test_results.aggregate_results where
  job_name like '%linux%basictests%'  # you can filter job name here
  and test_name like '%http%cli_test%'  # choose a test name you are interested in
  and timestamp > '2018-10-01 00:00'
  and result != 'PASSED'
order by timestamp desc
limit 1000
```

There are 6 occurrences in October:
https://source.cloud.google.com/results/invocations/6ddbb301-a7be-4cf3-b15a-a55072d1616f 
https://source.cloud.google.com/results/invocations/03f7cc70-7008-41e6-b67a-ddf8b6c9a559
https://source.cloud.google.com/results/invocations/6bc6e29f-4f29-44b7-a248-cb3d7fef900d
https://source.cloud.google.com/results/invocations/65a47e9c-58d1-4ff4-af62-13f2985ee6be
https://source.cloud.google.com/results/invocations/ad533c6e-2162-4836-82a9-2398e708b487

Let's actually fix what's wrong with the test, otherwise issue like this will keep haunting us forever.

**Comment by jtattermusch** [comment] 2019-03-08 08:02
According to historical data, we seen this in the past 3 months.

**Closed by jtattermusch** 2019-03-08 08:02 UTC
Labels: infra/BUILDPONY, infra/New Failure, kind/bug, lang/core, priority/P2
