### ISSUE TITLE
Cannot build the project

### ISSUE THREAD

**Issue by Teo-NTBU** [grpc/grpc#18973] opened 2019-05-07 09:13 UTC
### What version of gRPC and what language are you using?
 v1.20.0
 
### What operating system (Linux, Windows,...) and version?
 Ubuntu 16,04
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
 gcc version 7.4.0
 
### What did you do?
If possible, provide a recipe for reproducing the error. Try being specific and include code snippets if helpful.
I wanna build the grpc. So I followed the instruction below but failed.
```
 $ git clone -b $(curl -L https://grpc.io/release) https://github.com/grpc/grpc
 $ cd grpc
 $ git submodule update --init

 $ bazel build :all           // failed to build with bazel
 $ make                         // failed to build with make
```

### What did you expect to see?
Build success
 
### What did you see instead?
bazel version is 0.25.0 and I see below
```
DEBUG: Rule 'io_bazel_rules_python' indicated that a canonical reproducible form can be obtained by modifying arguments shallow_since = "1523916428 -0700"
DEBUG: Rule 'org_pubref_rules_protobuf' indicated that a canonical reproducible form can be obtained by modifying arguments commit = "1623a5a083f2a702bd62692d059353b4e06f3a5e", shallow_since = "1532967846 +0000" and dropping ["tag"]
ERROR: /home/tkang/.cache/bazel/_bazel_tkang/b88b6304c1d575a21c75620fa90cf18c/external/org_pubref_rules_protobuf/protobuf/internal/proto_compile.bzl:771:21: Traceback (most recent call last):
        File "/home/tkang/.cache/bazel/_bazel_tkang/b88b6304c1d575a21c75620fa90cf18c/external/org_pubref_rules_protobuf/protobuf/internal/proto_compile.bzl", line 761
                rule(implementation = _proto_compile_..., <3 more arguments>)
        File "/home/tkang/.cache/bazel/_bazel_tkang/b88b6304c1d575a21c75620fa90cf18c/external/org_pubref_rules_protobuf/protobuf/internal/proto_compile.bzl", line 770, in rule
                attr.label_list(allow_files = FileType([".proto"...))
        File "/home/tkang/.cache/bazel/_bazel_tkang/b88b6304c1d575a21c75620fa90cf18c/external/org_pubref_rules_protobuf/protobuf/internal/proto_compile.bzl", line 771, in attr.label_list
                FileType([".proto"])
FileType function is not available. You may use a list of strings instead. You can temporarily reenable the function by passing the flag --incompatible_disallow_filetype=false
ERROR: error loading package '': in /home/tkang/.cache/bazel/_bazel_tkang/b88b6304c1d575a21c75620fa90cf18c/external/org_pubref_rules_protobuf/python/rules.bzl: in /home/tkang/.cache/bazel/_bazel_tkang/b88b6304c1d575a21c75620fa90cf18c/external/org_pubref_rules_protobuf/protobuf/rules.bzl: Extension file 'protobuf/internal/proto_compile.bzl' has errors
ERROR: error loading package '': in /home/tkang/.cache/bazel/_bazel_tkang/b88b6304c1d575a21c75620fa90cf18c/external/org_pubref_rules_protobuf/python/rules.bzl: in /home/tkang/.cache/bazel/_bazel_tkang/b88b6304c1d575a21c75620fa90cf18c/external/org_pubref_rules_protobuf/protobuf/rules.bzl: Extension file 'protobuf/internal/proto_compile.bzl' has errors
INFO: Elapsed time: 0.057s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)
```

gnu make version is 4.1 and I see below
```
[MAKE]    Generating cache.mk
[HOSTLD]  Linking /home/tkang/grpc/bins/opt/grpc_cpp_plugin
/usr/bin/ld: warning: libprotobuf.so.18, needed by //usr/local/lib/libprotoc.so, may conflict with libprotobuf.so.9
/usr/bin/ld: /home/tkang/grpc/objs/opt/src/compiler/cpp_plugin.o: undefined reference to symbol '_ZNK6google8protobuf16MethodDescriptor11output_typeEv'
//usr/local/lib/libprotobuf.so.18: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
Makefile:16450: recipe for target '/home/tkang/grpc/bins/opt/grpc_cpp_plugin' failed
make: *** [/home/tkang/grpc/bins/opt/grpc_cpp_plugin] Error 1
```
 
Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

See [TROUBLESHOOTING.md](https://github.com/grpc/grpc/blob/master/TROUBLESHOOTING.md) for how to diagnose problems better.

**Comment by nicolasnoble** [comment] 2019-05-08 19:30
Bazel-side is a duplicate of #18947, protobuf-side is, as your compiler is saying, a conflict between the version of protobuf you have installed on your system which is incompatible. Remove it, and it'll work.

**Closed by nicolasnoble** 2019-05-08 19:30 UTC
Labels: lang/c++

**Comment by Teo-NTBU** [comment] 2019-05-09 01:07
Thanks, there were some protobuf library packages pre-installed on ubuntu 16.04.
The following fixed the issue.
```
sudo apt remove libprotobuf-dev libprotobuf9v5
```

For Bazel-side i am gonna check the issue you mentioned. Thanks.

**Comment by monellz** [comment] 2019-05-25 07:40
Is the Bazel-side really a duplicate of  #18947 ?  I can't find the solution for Bazel-side...
