### ISSUE TITLE
Optional boolean values

### ISSUE THREAD

**Issue by curtiscook** [grpc/grpc#33181] opened 2023-05-18 18:57 UTC
### What version of gRPC and what language are you using?
grpcio + grpcio tools 1.54.2 
Python

### What operating system (Linux, Windows,...) and version?
OSX, Linux (Docker)

### What runtime / compiler are you using (e.g. python version or version of gcc)
Python 3.11

### What did you do?
Create a proto message with an optional boolean value

```
message Foo {
  string uuid = 1;
  optional bool bar = 2;
}
```

### What did you expect to see?
Proto3 dropped required fields, and additionally I had marked the boolean field as optional, I expect to see:

```
python -m grpc_tools.protoc -I../proto/ --python_out=. --pyi_out=. --grpc_python_out=. ../<path_to>/my.proto
```
```
class Foo(_message.Message):
    __slots__ = ["bar", "uuid"]
    BAR_FIELD_NUMBER: _ClassVar[int]
    UUID_FIELD_NUMBER: _ClassVar[int]
    bar: bool
    uuid: str
    def __init__(self, uuid: _Optional[str] = ..., bar: _Optional[bool] = ...) -> None: ...
```

### What did you see instead?

The boolean is not marked as optional
```
class Foo(_message.Message):
    __slots__ = ["bar", "uuid"]
    BAR_FIELD_NUMBER: _ClassVar[int]
    UUID_FIELD_NUMBER: _ClassVar[int]
    bar: bool
    uuid: str
    def __init__(self, uuid: _Optional[str] = ..., bar: bool = ...) -> None: ...
```

**Comment by XuanWang-Amos** [comment] 2024-01-10 19:22
I tried it locally and able to reproduce this issue.

But it's not related to grpc, the issue is on the protocol buffer compiler side, please consider open a bug to [Protobuf team](https://github.com/protocolbuffers/protobuf).

Closing this issue since it's not related to gRPC, feel free to comment with the issue on Protobuf team.

**Closed by XuanWang-Amos** 2024-01-10 19:22 UTC
Labels: kind/bug, lang/Python, priority/P2
