### ISSUE TITLE
C# Clean Cancellation

### ISSUE THREAD

**Issue by ndglover** [grpc/grpc#8277] opened 2016-10-04 13:55 UTC
Hi,

I'm trying to understand the best way to cancel a streaming call from the client. I'm noticing some strange behaviour IMO.

1. When passing a cancellation token into the streaming method call like below you get an RPCException when this token is cancelled. There is even a unit test for this _FibWithCancel_. My understanding was this is how you indicate to the server you'd like to cancel the request so why should it generate an exception? 
`client.Fib(new FibArgs { Limit = 0 }, cancellationToken: cts.Token)`

Further more by passing in a CancellationToken.None you get no RPCException and it behaves more like I'd expect so I'm not really sure what benefit this token has.

2. Regardless of what you do above the server will not complete until it tries to send the next message and checks the state of it's cancellation token usually something like:
`while (!ct.IsCancellationRequested && await call.ResponseStream.MoveNext())`

If the stream ticks very slowly or not at all this could be sometime.

3. When the server does tick it then falls into the _ServerCallHandler_ and the method `await asyncCall.SendStatusFromServerAsync(status, context.ResponseTrailers, null).ConfigureAwait(false);`  throws an Operation is not valid due to the current state of the object. Should it not check the context here to see if the call has been cancelled?

My application is sending around 1500 streaming requests and then cancelling them from the client before sending another batch with different parameters. What I'm seeing as a result of above is a huge amount of exceptions and a significant lag whilst these happen.

It's possible I'm doing something wrong but would like some clarification from the experts please.

Thanks

**Comment by ndglover** [comment] 2016-10-13 07:44
@jtattermusch any thoughts on this?

**Comment by jtattermusch** [comment] 2016-10-13 15:00
On Tue, Oct 4, 2016 at 3:55 PM, ndglover <notifications@github.com> wrote:

> Hi,
>
> I'm trying to understand the best way to cancel a streaming call from the
> client. I'm noticing some strange behaviour IMO.
>
>    1. When passing a cancellation token into the streaming method call
>    like below you get an RPCException when this token is cancelled. There is
>    even a unit test for this *FibWithCancel*. My understanding was this
>    is how you indicate to the server you'd like to cancel the request so why
>    should it generate an exception? client.Fib(new FibArgs { Limit = 0 },
>    cancellationToken: cts.Token)
>
>
Well, yes, getting an RPCException with StatusCode "Cancelled" on the
client side when you cancel your call is the intended behavior (you
shouldn't get StatusCode.OK because that indicates that the call has
finished normally). If you want your calls to finish with an OK status,
just don't cancel them (client can indicate he is done by closing the
request stream, and a cooperating server can react on request stream being
closed by finishing the call with OK status - which actually might be the
"Clean" behavior you are talking about).


>
>
> Further more by passing in a CancellationToken.None you get no
> RPCException and it behaves more like I'd expect so I'm not really sure
> what benefit this token has.
>
If you pass CancellationToken.None to a call on the client side, that means
you are not planning to ever cancel the call and you are effectively giving
up the opportunity to cancel it. This behavior is in agreement with how
cancellation token is used throughout the .NET framework and is to be
expected by the users.


>
>    1. Regardless of what you do above the server will not complete until
>    it tries to send the next message and checks the state of it's cancellation
>    token usually something like: while (!ct.IsCancellationRequested &&
>    await call.ResponseStream.MoveNext())
>
> I don't understand if this code is intended to be run on server or on
client. On client, you shouldn't really be checking the cancellation token
because you are the one emitting the cancellation. Just catch the
RPCException (you need to do that anyway, because you need to handle other
call errors somehow).


>
>
> If the stream ticks very slowly or not at all this could be sometime.
>
>    1. When the server does tick it then falls into the *ServerCallHandler*
>    and the method await asyncCall.SendStatusFromServerAsync(status,
>    context.ResponseTrailers, null).ConfigureAwait(false); throws an
>    Operation is not valid due to the current state of the object. Should it
>    not check the context here to see if the call has been cancelled?
>
> My application is sending around 1500 streaming requests and then
> cancelling them from the client before sending another batch with different
> parameters. What I'm seeing as a result of above is a huge amount of
> exceptions and a significant lag whilst these happen.
>
Just close your streaming call cleanly (requestStream.CompleteAsync() on
client) and have your server return OK status when there aren't any more
requests from client. Cancellations are to be used for forcing termination
of outstanding calls due to unexpected circumstances, you shouldn't rely on
them for handling the basic workflow in your application.

**Comment by jtattermusch** [comment] 2016-10-13 15:02
I think in your case, you are just misusing the cancellation API for something that can be handled in a better way. Hopefully my explanation is helpful. I'm going to close this now, feel free to reopen if you believe there are still some issues to discuss.

**Closed by jtattermusch** 2016-10-13 15:02 UTC
Labels: C#

**Comment by ndglover** [comment] 2016-10-14 12:49
@jtattermusch thanks for looking into this for me, much appreciated. Unfortunately I've had a look at your comments and suggestions and I'm still not clear how I can cancel cleanly. I hope you are right and I'm misusing the API but could you clarify the following a little more for me please?

To illustrate the issue I'm facing I've modified Math example server and client example code as per below. In this use case there is no request stream for me to call _CompleteAsync_ on. It looks like this is only exposed from the bidirectional streaming API and even then the server will still throw in _SendStatusFromServerAsync_

Aside from using the cancellation token I can't see how the client can cancel a streaming response from the server. In my scenario the server stream will live as long as the client keeps it open, it won't be enumerating some data collection and then completing. 

If I accept the fact an RPCException will be thrown on the client then I have to check the cancellation token to know if I can ignore the exception since it's expected or it's something I need to deal with.

Similarly on the server it seems I can't avoid throwing an exception from the _SendStatusFromServerAsync_

Hopefully I'm missing something but would much appreciate your opinion and expertise.

Server
`
public override async Task Fib(FibArgs request, IServerStreamWriter<Num> responseStream, ServerCallContext context)
        {
            var limit = request.Limit > 0 ? request.Limit : long.MaxValue;
            var fibEnumerator = FibInternal(limit).GetEnumerator();

            // Keep streaming the sequence until the call is cancelled.
            // Use CancellationToken from ServerCallContext to detect the cancellation.
            while (!context.CancellationToken.IsCancellationRequested && fibEnumerator.MoveNext())
            {
                await responseStream.WriteAsync(fibEnumerator.Current);
                await Task.Delay(1000);
            }
        }
`

Client
`
public static async Task FibExample2(Math.MathClient client)
        {
            var cts = new CancellationTokenSource();
            using (var call = client.Fib(new FibArgs { Limit = 5 }, Metadata.Empty, null, cts.Token))
            {
                while (!cts.Token.IsCancellationRequested && await call.ResponseStream.MoveNext())
                {
                    Console.WriteLine(call.ResponseStream.Current);
                    cts.Cancel(); //Cancel after first response
                }
            }
        }
`

**Comment by jtattermusch** [comment] 2016-10-17 09:07
Ok, I see. So in your case, you are using a server streaming call (unary request, streaming response). Semantically, that means you are sending a single request for the server to do something (send you a list of responses based on the params you've sent). If you later change your mind, you need to cancel the call (which results in throwing and RpcException, and that makes sense, because an OK status code would indicate that the request was fulfilled fully and that is not true).

If you need the client to indicate that he wants to stop a subscription cleanly, just use a duplex streaming call  (at which point you'll have access to requestStream.CompleteAsync()) instead of a server-streaming call. As far as I can tell, everything on gRPC side is working as intended, but perhaps you want to consider switching you service definition to a bi-di streaming call.

**Comment by ndglover** [comment] 2016-10-17 16:40
@jtattermusch I could switch to use duplex streaming and this would give me a better way to cancel from the client since I wouldn't get this RPCException. However from what I can see it would still generate an warning on the server, is this expected? Or more specifically is there a better way I can handle this?

To give you an example
Client

```
public static async Task DivManyExample2(Math.MathClient client)
        {
            var cts = new CancellationTokenSource();
            using (var call = client.DivMany(Metadata.Empty, null, cts.Token))
            {
                var completed = false;
                await call.RequestStream.WriteAsync(new DivArgs {Dividend = 10, Divisor = 3});
                while (!completed && await call.ResponseStream.MoveNext())
                {
                    Console.WriteLine(call.ResponseStream.Current);
                    await call.RequestStream.CompleteAsync(); //effectively cancel after first response
                    completed = true;
                }
            }
        }
```

Server
```
public override async Task DivMany(IAsyncStreamReader<DivArgs> requestStream, IServerStreamWriter<DivReply> responseStream, ServerCallContext context)
        {
            await requestStream.ForEachAsync(async divArgs =>
            {
                //Send Response
                await responseStream.WriteAsync(DivInternal(divArgs));

                //Simulate pause during which time client cancels
                await Task.Delay(TimeSpan.FromSeconds(1));

                var cancelRequested = context.CancellationToken.IsCancellationRequested;
                if (!cancelRequested)
                {
                    //We don't go here because the client has cancelled
                    await responseStream.WriteAsync(DivInternal(divArgs));
                }
            });
        }
```

We then end up in the Server.cs around line 326 in my source which throws an exception _"Operation is not valid due to the current state of the object_"

![image](https://cloud.githubusercontent.com/assets/2682997/19446435/9c1e7c20-9490-11e6-9142-dccb5fa01ada.png)

**Comment by jtattermusch** [comment] 2016-10-18 07:50
As explained before, if you want the call to finish without an RPC exception just *don't cancel it* and *don't use any cancellation api on the serverside* (the examples you are posting still contain that). 

On server side, just await requestStream.MoveNext() until it is false (that means client has closed the stream), perhaps do that on a Task and set a flag "clientHasClosed".  After that happens, 
just return from the serverside handler and that will result in returning Ok status to the client.

**Comment by ndglover** [comment] 2016-10-18 08:31
I am not using any cancellation api on the serverside in my latest example above. At least I don't believe I am. Where do you see this?

I need to complete these streams somehow to avoid a memory leak/overhead. The streams are long lived (i.e. have no natural end, think market data or polling a DB for changes etc), and will never complete unless the client _cancels /completes_ them. If the client calls _RequestStream.CompleteAsync()_ as per my example above then sure there is no exception on the client. However there is still an exception on the server regardless of what I do. The server tries to send back the status OK but the client call has completed so it logs this as a warning.

**Comment by jtattermusch** [comment] 2016-10-18 09:07
On Tue, Oct 18, 2016 at 10:32 AM, ndglover <notifications@github.com> wrote:

> I am not using any cancellation api on the serverside in my latest example
> above. At least I don't believe I am. Where do you see this?
>

You are checking value of
context.CancellationToken.IsCancellationRequested (that's
clearly part of cancellation API IMHO). Not saying that you rely on this in
your example, but it's misleading.

>                 I need to complete these streams somehow to avoid a
> memory leak/overhead. The streams are long lived (i.e. have no natural end,
> think market data or polling a DB for changes etc), and will never complete
> unless the client *cancels /completes* them. If the client calls
> *RequestStream.CompleteAsync()* as per my example above then sure there
> is no exception on the client. However there is still an exception on the
> server regardless of what I do.
>
If the client completes with completeAsync, it doesn't mean that the call
has finished, the server still needs to finish the call by sending the
status (happens when you return from the serverside handler). So basically
- I think you are wrong in saying that exception is thrown on the
serverside if the client closes the stream cleanly (and in case you are
right, that's a bug, but we do have tests for this so I have a very hard
time believing this).

> The server tries to send back the status OK but the client call has
> completed so it logs this as a warning.
>
That's only if the call has actually been cancelled, if client closes
cleanly, the call is alive until server decides to finish it.

**Comment by ndglover** [comment] 2016-10-18 09:21
Eats large piece of humble pie.... Yes please accept my apologies, the additional check for the cancellation token was the issue. Well part of it anyway, the second ```await responseStream.WriteAsync(DivInternal(divArgs));``` was throwing. So having two writes inside a single response is clearly an issue if the request has been cancelled. 

Really appreciate your help on this, thanks for clearing it up.

**Comment by jtattermusch** [comment] 2016-10-18 09:34
Np, glad that you were able to successfully sort this out.

**Comment by ndglover** [comment] 2016-10-18 17:30
@jtattermusch Yikes, After much deliberation I think I'm back in the same place. As you said the call won't finish until I return from the serverside handler and I'll never return from this handler for these long lived queries. So in order for me to return and clean up any resources the only way I know the client has cancelled is to look at the _ServerCallContext_. I feel like I need a hook into the fact the client called CompleteAsync but I don't have one.
```
public override async Task DivMany(IAsyncStreamReader<DivArgs> requestStream, IServerStreamWriter<DivReply> responseStream, ServerCallContext context)
        {
            while (await requestStream.MoveNext())
            {
                try
                {
                    //Fake query that might never return
                    await CreateLongRunningQueryThatNeedsToDisposeOfExpensiveResource(requestStream.Current, responseStream);
                }
                catch (Exception ex)
                {
                    //Swallow task cancelled
                    //Console.WriteLine($"Server Error {ex}");
                }
            }
        }

        public async Task CreateLongRunningQueryThatNeedsToDisposeOfExpensiveResource(DivArgs divArgs, IServerStreamWriter<DivReply> responseStream)
        {
            //1. Create resource that must be disposed
            var results = Task.Delay(TimeSpan.FromDays(1));            
            
            //2. Query it
            await results;

            //3.Write results to response stream
            await responseStream.WriteAsync(new DivReply());
        }
```

**Comment by ndglover** [comment] 2016-10-19 09:56
Hi, I've created a few unit tests to display the problem I'm facing.

```
public class MathServiceImplNu : Math.MathBase
    {
        public const long DividendThatReturns = 5;
        public const long DividendThatWaits = 10;

        public class ExpensiveResource : IDisposable
        {
            public async Task DoWork(IServerStreamWriter<DivReply> responseStream, long argument, CancellationToken token)
            {
                if (argument == DividendThatReturns)
                    await responseStream.WriteAsync(new DivReply() {Quotient = 1, Remainder = 1});
                else
                    await Task.Delay(TimeSpan.FromDays(1), token);

                Console.WriteLine("I have some results");
            }

            public void Dispose()
            {
                Console.WriteLine("Disposed ExpensiveResource");
            }
        }

        public override async Task DivMany(IAsyncStreamReader<DivArgs> requestStream, IServerStreamWriter<DivReply> responseStream, ServerCallContext context)
        {
            while (await requestStream.MoveNext())
            {
                var request = requestStream.Current;
                using (var resource = new ExpensiveResource())
                {
                    await resource.DoWork(responseStream, request.Dividend, context.CancellationToken);
                }
            }
        }
    }

    public class CompleteCleanlyTests
    {
        const string Host = "localhost";
        Server _server;
        Channel _channel;
        Math.MathClient _client;

        [SetUp]
        public void Init()
        {
            _server = new Server
            {
                Services = { Math.BindService(new MathServiceImplNu()) },
                Ports = { { Host, ServerPort.PickUnused, ServerCredentials.Insecure } }
            };
            _server.Start();
            _channel = new Channel(Host, _server.Ports.Single().BoundPort, ChannelCredentials.Insecure);
            _client = new Math.MathClient(_channel);
        }

        [TearDown]
        public void Shutdown()
        {
            _server.ShutdownAsync().Wait();
            Console.WriteLine("Shutdown Server");
        }

        [Test]
        public async Task Will_Never_Complete()
        {
            var call = _client.DivMany(Metadata.Empty, null, CancellationToken.None);
            await call.RequestStream.WriteAsync(new DivArgs { Dividend = MathServiceImplNu.DividendThatWaits, Divisor = 3 });
            var completed = Task.Run(async () =>
            {
                await Task.Delay(100); 
                Console.WriteLine("Completing Stream");
                await call.RequestStream.CompleteAsync();
            });

            while (await call.ResponseStream.MoveNext())
            {
                
            }

            await completed;
            _channel.ShutdownAsync().Wait();
        }

        [Test]
        public async Task Completes_But_With_Exceptions()
        {
            var cts = new CancellationTokenSource();
            var call = _client.DivMany(Metadata.Empty, null, cts.Token);
            await call.RequestStream.WriteAsync(new DivArgs { Dividend = MathServiceImplNu.DividendThatWaits, Divisor = 3 });
            var completed = Task.Run(async () =>
            {
                await Task.Delay(100); //assume we have results by now
                Console.WriteLine("Completing Stream");
                await call.RequestStream.CompleteAsync();
                cts.Cancel();
            });

            while (await call.ResponseStream.MoveNext())
            {

            }

            await completed;
            _channel.ShutdownAsync().Wait();
        }

        [Test]
        public async Task Working_Test()
        {
            var call = _client.DivMany(Metadata.Empty, null, CancellationToken.None);
            await call.RequestStream.WriteAsync(new DivArgs { Dividend = MathServiceImplNu.DividendThatReturns, Divisor = 3 });
            DivReply response = null;

            var completed = Task.Run(async () =>
            {
                await Task.Delay(100); //assume we have results by now
                Console.WriteLine("Completing Stream");
                await call.RequestStream.CompleteAsync();
            });

            while (await call.ResponseStream.MoveNext())
            {
                response = call.ResponseStream.Current;
            }

            await completed;
            await _channel.ShutdownAsync();

            Assert.IsNotNull(response);
            Assert.AreEqual(1, response.Quotient);
            Assert.AreEqual(1, response.Remainder);
        }
    }

```

**Comment by gazialankus** [comment] 2017-01-31 21:39
I have been getting the "Operation is not valid due to the current state of the object" exception or experiencing hangs and I figured out the correct client ritual for ending a rpc call with a bidirectional stream. 

This is how your client code needs to be: 

1. Use `call.RequestStream` and `call.ResponseStream` to your heart's content. After your last write to `call.RequestStream`, go to the step below.
2. Use `call.RequestStream.CompleteAsync();` to close `call.RequestStream`. **_If you don't do this step, the next step results in a hang._**
3. Consume what's left in `call.ResponseStream` by something like `while(await call.ResponseStream.MoveNext());`. **_If you don't do this step, you get an exception in the server side and a warning in the client side._** 

Here are the outputs you get in step 3 if you don't consume what's left in `call.ResponseStream`: 

On the client side: 
```
W0201 00:34:15.441516 Grpc.Core.Channel Channel shutdown was called but there are still 1 active calls for that channel.
```

On the server side: 
```
W0201 00:34:15.739214 Grpc.Core.Server Exception while handling RPC. System.InvalidOperationException: Operation is not valid due to the current state of the object.
   at Grpc.Core.Internal.AsyncCallServer`2.SendStatusFromServerAsync(Status status, Metadata trailers, Tuple`2 optionalWrite)
   at Grpc.Core.Internal.DuplexStreamingServerCallHandler`2.<HandleCall>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Grpc.Core.Server.<HandleCallAsync>d__34.MoveNext()
```

Hope this helps someone.
