### ISSUE TITLE
Python: future.result() returns None

### ISSUE THREAD

**Issue by alamaison** [grpc/grpc#6509] opened 2016-05-10 15:09 UTC
We have an intermittent issue where futures return `None` from `result()` instead of the expected reponse message.  We can't reproduce it on demand, so instead we added logging to dump as much info as possible when it happens:
```python
stub = foo_pb2.beta_create_Foo_stub(channel)
future = stub.DoFoo.future(foo_pb2.FooRequest(name='you'), _TIMEOUT_SECONDS,
                           metadata=some_metadata)
result = future.result()
if result is None:
    logging.warning("Got bad result from the future, running: %s. \n"
                    "Future had exception: %s. \n"
                    "Future had traceback: %s. \n"
                    "Future had _up_initial_metadata: %s. \n"
                    "Future had _up_payload: %s. \n"
                    "Future had _up_allowance: %s. \n"
                    "Future had _up_completion: %s. \n"
                    "Future had _down_initial_metadata: %s. \n"
                    "Future had _down_allowance: %s. \n"
                    "Future had _down_terminal_metadata: %s. \n"
                    "Future had _down_code: %s. \n"
                    "Future had _down_details: %s. \n"
                    "Future had _termination: %s. \n",
                    future.running(),
                    future.exception(),
                    future.traceback(),
                    future._up_initial_metadata,
                    future._up_payload,
                    future._up_allowance,
                    future._up_completion,
                    future._down_initial_metadata,
                    future._down_allowance,
                    future._down_terminal_metadata,
                    future._down_code,
                    future._down_details,
                    future._termination)
```
This logs:
```
Got bad result from the future, running: False. 
Future had exception: None. 
Future had traceback: None. 
Future had _up_initial_metadata: _Awaited(kind=<Kind.ARRIVED: 'arrived'>, value=<grpc._cython.cygrpc.Metadata object at 0x7f3028612aa0>). 
Future had _up_payload: None. 
Future had _up_allowance: 1. 
Future had _up_completion: _Awaited(kind=<Kind.ARRIVED: 'arrived'>, value=_Completion(terminal_metadata=<grpc._cython.cygrpc.Metadata object at 0x7f3028612af0>, code=<StatusCode.OK: 0>, message='')). 
Future had _down_initial_metadata: _Transitory(kind=<Kind.GONE: 'gone'>, value=None). 
Future had _down_allowance: 1. 
Future had _down_terminal_metadata: _Transitory(kind=<Kind.GONE: 'gone'>, value=None). 
Future had _down_code: _Transitory(kind=<Kind.GONE: 'gone'>, value=None). 
Future had _down_details: _Transitory(kind=<Kind.GONE: 'gone'>, value=None). 
Future had _termination: _Termination(terminated=True, abortion=None, abortion_error=None). 
```

For comparison, this is what the same logging finds on a successful request:
```
running: False. 
Future had exception: None. 
Future had traceback: None. 
Future had _up_initial_metadata: _Awaited(kind=<Kind.ARRIVED: 'arrived'>, value=<grpc._cython.cygrpc.Metadata object at 0x7f7e1c610a00>). 
Future had _up_payload: foo_thing {
  <elided>
}
. 
Future had _up_allowance: 0. 
Future had _up_completion: _Awaited(kind=<Kind.ARRIVED: 'arrived'>, value=_Completion(terminal_metadata=<grpc._cython.cygrpc.Metadata object at 0x7f7e1c610aa0>, code=<StatusCode.OK: 0>, message='')). 
Future had _down_initial_metadata: _Transitory(kind=<Kind.GONE: 'gone'>, value=None). 
Future had _down_allowance: 1. 
Future had _down_terminal_metadata: _Transitory(kind=<Kind.GONE: 'gone'>, value=None). 
Future had _down_code: _Transitory(kind=<Kind.GONE: 'gone'>, value=None). 
Future had _down_details: _Transitory(kind=<Kind.GONE: 'gone'>, value=None). 
Future had _termination: _Termination(terminated=True, abortion=None, abortion_error=None). 
```

It seems to happen more often when the network is under strain.  It happens least often locally.  Other than that we have no insight at all.

Any suggestions?

cc @GlobeGitter @csdigi

**Comment by alamaison** [comment] 2016-05-10 15:10
The issue might also be related to #6360.  Before we started using futures we used to intermittent StopIteration exceptions.

**Comment by nathanielmanistaatgoogle** [comment] 2016-06-13 23:30
@kpayson64: how comfortable would we be saying "this has been fixed on master as of 8 June and will be fixed in the upcoming 0.15 release" and closing this issue?

**Comment by kpayson64** [comment] 2016-06-13 23:33
@nathanielmanistaatgoogle 
I put together a quick test and was unable to reproduce it, the code that was responsible for future has been completely replaced, and the likely related issue #6360 is definitely fixed, so I'm pretty comfortable that this has been resolved.

**Comment by nathanielmanistaatgoogle** [comment] 2016-06-13 23:38
@alamaison: thank you for the report!

**Closed** 2016-06-13 23:38 UTC
Labels: bug, python, to close
