### ISSUE TITLE
Python performance

### ISSUE THREAD

**Issue by edelmane** [grpc/grpc#11270] opened 2017-05-22 21:48 UTC
Please answer these questions before submitting your issue. 
 
### Should this be an issue in the gRPC issue tracker?
 Yes
 
### What version of gRPC and what language are you using?
 1.1.3 in Python
 
### What operating system (Linux, Windows, …) and version?
 Amazon Linux 2012 on an EC2 instance
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
 Python 2.7.8
 
### What did you do?
Trying to test raw throughput of a GRPC call, I multi-thread (16 threads) send calls from my client to a GRPC endpoint. I have this endpoint do nothing but immediately return the response. The GRPC sever is configured with 32 workers. The client and server were configured to send and receive on the localhost between two separate processes. It takes about 65 seconds to get through sending and receiving the response of 100,000 messages. This seems slow.
 
### What did you expect to see?
Expected to be able to get through 100,000 messages much quicker. 
 
### What did you see instead?
It took 65 seconds to churn through 100,000 messages.

**Comment by nathanielmanistaatgoogle** [comment] 2017-06-07 21:28
Closing as a duplicate of [issue 7950](https://github.com/grpc/grpc/issues/7950) - we have some benchmarks with which we're satisfied for the moment and we have some aspirations to improve efficiency in the future.

Thank you for the very detailed report though!

**Closed by nathanielmanistaatgoogle** 2017-06-07 21:28 UTC
Labels: performance, python
