### ISSUE TITLE
windows_x64_vs2015: Failure on tests.vsprojects/x64/Debug/h2_compress_nosec_test.exe large_metadata

### ISSUE THREAD

**Issue by vjpai** [grpc/grpc#6170] opened 2016-04-13 21:48 UTC
tests.vsprojects/x64/Debug/h2_compress_nosec_test.exe large_metadata (from grpc.tests)

Failing for the past 1 build (Since Unstable#1550 )
Took 6.1 sec.
Error Message

Failure
Standard Output

D0413 18:07:04.443000000  1416 test_config.c:278] test slowdown: machine=1.000000 build=1.000000 total=1.000000
I0413 18:07:04.444000000  1416 large_metadata.c:55] test_request_with_large_metadata/chttp2/fullstack_compression
E0413 18:07:10.302000000  1416 cq_verifier.c:248] event not found: OP_COMPLETE: tag:0000000000000001 OK
E0413 18:07:10.302000000  1416 cq_verifier.c:251] have tags: 0000000000000065
Abort handler called.
*** 0: 000000013F4C4130  - 0000000000000000
*** 1: 000000013F4C469C  - 0000000000000000
*** 2: 000000013F5AB238  - 0000000000000000
*** 3: 000000013F569D99  - 0000000000000000
*** 4: 000000013F64B538  - 0000000000000000
*** 5: 000000013F53BA2B  - 0000000000000000
*** 6: 000000013F53C09D  - 0000000000000000
*** 7: 000000013F5238A8  - 0000000000000000
*** 8: 000000013F4BAD0C  - 0000000000000000
*** 9: 000000013F5523A4  - 0000000000000000
*** 10: 000000013F55223E  - 0000000000000000
*** 11: 000000013F5520FE  - 0000000000000000
*** 12: 000000013F5523C9  - 0000000000000000
*** 13: 00000000779859ED BaseThreadInitThunk - 00000000779859E0
*** 14: 0000000077ABB371 RtlUserThreadStart - 0000000077ABB350

**Comment by stanley-cheung** [comment] 2016-04-14 15:57
Dupe of #6006?

**Comment by vjpai** [comment] 2016-04-15 14:36
Not a dup - #6006 was on master, but this was on portability master.

**Closed** 2016-04-27 20:49 UTC
Labels: BUILDPONY, P1, Windows
