### ISSUE TITLE
cmake: can't install(build) on windows

### ISSUE THREAD

**Issue by allanruin** [grpc/grpc#11616] opened 2017-06-27 12:32 UTC
Please answer these questions before submitting your issue. 
 
### Should this be an issue in the gRPC issue tracker?
 yes. I think build issue should be report in gRPC issue tracker.

### What version of gRPC and what language are you using?
 I tried latest release version `v1.4.x` and the 'current' (`master`) version, but get the same error.
 
### What operating system (Linux, Windows, …) and version?
 I'm using windows7(x64) Pro,SP1.
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
 I use TDM-GCC-64's c++ compiler to compile the code.
 
### What did you do?

I would like to build gRPC (so I could use it), and I  proceed as your doc indicated:
Install CMake.    
Install Active State Perl (choco install activeperl)    
Install Ninja (choco install ninja)     
Install Go (choco install golang)     
Install yasm and add it to PATH (choco install yasm)     
Run these commands in the repo root directory    

then I tried this 
> md .build
> cd .build
> call "%VS140COMNTOOLS%..\..\VC\vcvarsall.bat" x64
> cmake .. -GNinja -DCMAKE_BUILD_TYPE=Release
> cmake --build .

Then I get the below error:`CMake Error: CMake can not determine linker language for target: cares`.total message output as below:

     cmake .. -GNinja -DCMAKE_BUILD_TYPE=Release
    -- The C compiler identification is GNU 5.1.0
    -- The CXX compiler identification is GNU 5.1.0
    -- Check for working C compiler: C:/TDM-GCC-64/bin/gcc.exe
    -- Check for working C compiler: C:/TDM-GCC-64/bin/gcc.exe -- works
    -- Detecting C compiler ABI info
    -- Detecting C compiler ABI info - done
    -- Detecting C compile features
    -- Detecting C compile features - done
    -- Check for working CXX compiler: C:/TDM-GCC-64/bin/c++.exe
    -- Check for working CXX compiler: C:/TDM-GCC-64/bin/c++.exe -- works
    -- Detecting CXX compiler ABI info
    -- Detecting CXX compiler ABI info - done
    -- Detecting CXX compile features
    -- Detecting CXX compile features - done
    CMake Warning at CMakeLists.txt:106 (message):
      gRPC_ZLIB_PROVIDER is "module" but ZLIB_ROOT_DIR is wrong

    CMake Warning at CMakeLists.txt:109 (message):
      gRPC_INSTALL will be forced to FALSE because gRPC_ZLIB_PROVIDER is "module"

    You have called ADD_LIBRARY for library cares without any source files. This typically indicates a problem with your CMakeLists.txt file
    CMake Warning at CMakeLists.txt:179 (message):
      gRPC_PROTOBUF_PROVIDER is "module" but PROTOBUF_ROOT_DIR is wrong

    CMake Warning at CMakeLists.txt:216 (message):
      gRPC_SSL_PROVIDER is "module" but BORINGSSL_ROOT_DIR is wrong

    CMake Warning at CMakeLists.txt:240 (message):
      gRPC_GFLAGS_PROVIDER is "module" but GFLAGS_ROOT_DIR is wrong

    CMake Warning at CMakeLists.txt:260 (message):
      gRPC_BENCHMARK_PROVIDER is "module" but BENCHMARK_ROOT_DIR is wrong

    -- Configuring done
    CMake Error at CMakeLists.txt:319 (add_custom_command):
      Error evaluating generator expression:

        $<TARGET_FILE:>

      Expression syntax not recognized.
    Call Stack (most recent call first):
      CMakeLists.txt:2855 (protobuf_generate_grpc_cpp)

    CMake Error at CMakeLists.txt:319 (add_custom_command):
      Error evaluating generator expression:

        $<TARGET_FILE:>

      Expression syntax not recognized.
    Call Stack (most recent call first):
      CMakeLists.txt:2985 (protobuf_generate_grpc_cpp)

    CMake Error at CMakeLists.txt:319 (add_custom_command):
      Error evaluating generator expression:

        $<TARGET_FILE:>

      Expression syntax not recognized.
    Call Stack (most recent call first):
      CMakeLists.txt:2855 (protobuf_generate_grpc_cpp)

    CMake Error at CMakeLists.txt:319 (add_custom_command):
      Error evaluating generator expression:

        $<TARGET_FILE:>

      Expression syntax not recognized.
    Call Stack (most recent call first):
      CMakeLists.txt:2985 (protobuf_generate_grpc_cpp)

    CMake Error at CMakeLists.txt:319 (add_custom_command):
      Error evaluating generator expression:

        $<TARGET_FILE:>

      Expression syntax not recognized.
    Call Stack (most recent call first):
      CMakeLists.txt:2855 (protobuf_generate_grpc_cpp)

    CMake Error at CMakeLists.txt:319 (add_custom_command):
      Error evaluating generator expression:

        $<TARGET_FILE:>

      Expression syntax not recognized.
    Call Stack (most recent call first):
      CMakeLists.txt:2985 (protobuf_generate_grpc_cpp)

    CMake Error: CMake can not determine linker language for target: cares
    -- Generating done
    -- Build files have been written to: D:/proj/grpc/tmp/grpc/.build

**Comment by akoolenbourke** [comment] 2017-07-03 22:43
Just FYI, I get the same issue when attempting to CMake for Visual Studio 2017 (cmake .. -G "Visual Studio 15 Win64" -DMAKE_BUILD_TYPE=Release)

Am using CMake version 3.9.0-rc5

The only other difference to the instructions was a different vcvarsall.bat. This is the correct one for VS2017 -> call "%VS150COMNTOOLS%..\..\VC\auxiliary\build\vcvarsall.bat" x64

**Comment by atisman89** [comment] 2017-10-15 12:59
Same error here. Any solution or workaround?

**Comment by jtattermusch** [comment] 2017-11-29 17:03
Just realized what's wrong here: You haven't updated the submodules in your git clone.
Please see improved instructions here: https://github.com/grpc/grpc/pull/13526  (doing git clone --recursive) or here https://github.com/grpc/grpc/pull/13548 (running `git submodule update --init`).

This issue is basically a dupe of https://github.com/grpc/grpc/issues/13509. Please reopen if you are still seeing issues.

**Closed by jtattermusch** 2017-11-29 17:03 UTC
Labels: area/build, kind/customer issue, platform/Windows
