### ISSUE TITLE
no package config files generated for grpc cmake build on linux

### ISSUE THREAD

**Issue by timofey-retailnext** [grpc/grpc#12968] opened 2017-10-12 02:46 UTC
Please answer these questions before submitting your issue. 
 
### What version of gRPC and what language are you using?
 1.6.x (1.6.6 now)
 
### What operating system (Linux, Windows, …) and version?
x86_64/linux  (Fedora 25, Centos 7, Ubuntu 14 & 16)
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
gcc 7.2.x
 
### What did you do?
If possible, provide a recipe for reproducing the error. Try being specific and include code snippets if helpful.
native (gnu) make build of grpc produces package config files: <install>/lib/pkgconfig/grpc*.pc files;
cmake build of grpc does NO produce them ... (only cmake config files in <install>/lib/pkgconfig/cmake/).
 
### What did you expect to see?
a set of grpc*.pc files in <install>/lib/pkgconfig  directory
 
### What did you see instead?
no such files
 
Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

**Comment by jtattermusch** [comment] 2018-03-28 12:11
duplicate of https://github.com/grpc/grpc/issues/10727.

**Closed by jtattermusch** 2018-03-28 12:11 UTC
Labels: area/packaging & distribution
