### ISSUE TITLE
DNS resolving is too primitive.

### ISSUE THREAD

**Issue by nicolasnoble** [grpc/grpc#702] opened 2015-02-21 06:12 UTC
We need to rewrite the async DNS resolver. Potentially using something c-ares-like.

**Comment by jtattermusch** [comment] 2016-04-21 22:58
still an issue?

**Comment by dgquintas** [comment] 2016-11-16 00:19
@y-zeng is this a duplicate of the work you've been doing lately?

**Comment by y-zeng** [comment] 2016-11-16 01:13
Yes, let's use this issue to track the work.

**Comment by vjpai** [comment] 2017-06-20 20:49
This issue is done now, right? Please close if so.

**Comment by y-zeng** [comment] 2017-06-20 22:22
Implementation of the async DNS resolver is done, but it's still not the default DNS resolver.

**Closed as completed** 2017-12-11 22:26 UTC
Labels: area/core, disposition/to close, area/client channel
