### ISSUE TITLE
SSL Handshake fails with multiple machines and certificate signed by Intermediate CA

### ISSUE THREAD

**Issue by blingdaag** [grpc/grpc#20895] opened 2019-11-01 04:40 UTC
### What version of gRPC and what language are you using?
gRPC version 2.23.0
C#

### What operating system (Linux, Windows,...) and version?
Windows Server 2016

### What runtime / compiler are you using (e.g. python version or version of gcc)
dotnet core 2.2.3

### What did you do?
Machine1 - Server
Machine2 - Client
RootCA->IntermediateCA->SslCertificate (both client and server)

-RootCA and IntermediateCA are the same on both machines

To generate the "SslCredentials" and "SslServerCredentials" objects, I do the following:
- Read up the SslCertificate and its Private key from the certificate store via x509Chain. This way I can extract all the any IntermediateCAs all the way up the chain until I get to the RootCA. I then use the SslCertificate and its Private to create the "**keyCertificatePairs**" parameter for both the "SslCredentials" and "SslServerCredentials" objects
- I combine all the IntermediateCAs with the RootCA to create the "**rootCertificates**" parameter for the "SslCredentials" and "SslServerCredentials" objects.

### What did you expect to see?
I expected everything to work

### What did you see instead?
I saw the following:
```
I1031 18:34:47.577562 0 T:\src\github\grpc\workspace_csharp_ext_windows_x86\src\core\tsi\ssl_transport_security.cc:217:                 LOOP - TLS client read_server_certifi  - !!!!!!
I1031 18:34:47.578561 0 T:\src\github\grpc\workspace_csharp_ext_windows_x86\src\core\tsi\ssl_transport_security.cc:217:                 LOOP - TLS client read_certificate_st  - !!!!!!
I1031 18:34:47.579556 0 T:\src\github\grpc\workspace_csharp_ext_windows_x86\src\core\tsi\ssl_transport_security.cc:217:                 LOOP - TLS client verify_server_certi  - !!!!!!
E1031 18:34:47.579556 0 T:\src\github\grpc\workspace_csharp_ext_windows_x86\src\core\tsi\ssl_transport_security.cc:1237: Handshake failed with fatal error SSL_ERROR_SSL: error:1000007d:SSL routines:**OPENSSL_internal:CERTIFICATE_VERIFY_FAILED.**
D1031 18:34:47.580563 0 T:\src\github\grpc\workspace_csharp_ext_windows_x86\src\core\lib\security\transport\security_handshaker.cc:176: Security handshake failed: {"created":"@1572572087.581000000","description":"Handshake failed","file":"T:\src\github\grpc\workspace_csharp_ext_windows_x86\src\core\lib\security\transport\security_handshaker.cc","file_line":291,"tsi_code":10,"tsi_error":"**TSI_PROTOCOL_FAILURE"**}
I1031 18:34:47.586566 0 T:\src\github\grpc\workspace_csharp_ext_windows_x86\src\core\lib\channel\handshaker.cc:131: handshake_manager 00E1AA38: error={"created":"@1572572087.581000000","description":"Handshake failed","file":"T:\src\github\grpc\workspace_csharp_ext_windows_x86\src\core\lib\security\transport\security_handshaker.cc","file_line":291,"tsi_code":10,"tsi_error":"TSI_PROTOCOL_FAILURE"} shutdown=0 index=2, args={endpoint=00000000, args=00000000 {size=0: (null)}, read_buffer=00000000 (length=0), exit_early=0}
I1031 18:34:47.587565 0 T:\src\github\grpc\workspace_csharp_ext_windows_x86\src\core\lib\channel\handshaker.cc:164: handshake_manager 00E1AA38: handshaking complete -- scheduling on_handshake_done with error={"created":"@1572572087.581000000","description":"Handshake failed","file":"T:\src\github\grpc\workspace_csharp_ext_windows_x86\src\core\lib\security\transport\security_handshaker.cc","file_line":291,"tsi_code":10,"tsi_error":"TSI_PROTOCOL_FAILURE"}
```

### Anything else we should know about your project / environment?
**Interestingly** 
- This works locally with the IntermediateCA but not accross machine boundaries.
- This seems to work accross machine boundaries if there is no IntermediateCA.  
- I have tried creating the **rootCertificates** in different orders such as adding the IntermediateCAs first and vice-versa with no luck.
- I am using **native** DNS resolver as the **ares** would not work for me whenever hostnames were used for the certificates.

**Comment by jtattermusch** [comment] 2019-11-08 08:43
Reassigning to @yihuazhang  as this is SSL handshake related and it's not C# specific.

I would help if you could provide the exact commands you ran to generate the certificates.
(and also a snippet of code that reproduces the problem).

**Comment by blingdaag** [comment] 2019-11-08 19:57
I do have a question that may give some idea as to what happening.

Since I'm using self-signed certificates, is it possible to use them across
machines workout sharing the certificate authority? Meaning, machine 1
creates it's own CA and SSL certificates and machine 2 does the same.

Will this work or do they have to have a common CA that is used for signing
each certificate (client and server certificates)? Hopefully my questions
make sense.

Thanks for all your help!

**Comment by yihuazhang** [comment] 2020-05-05 20:34
I think the main issue is to make sure each endpoint owns the public key of CA that signs its peer's certificate. If two peers generate self-signed certificates, it is not possible for them to carry out a TLS handshake because they do not know the public key of each other's CA. I think ` TSI_PROTOCOL_FAILURE` explains the SSH handshake failure because of the above reason.

**Closed** 2020-05-05 20:44 UTC
Labels: kind/bug, lang/C#, priority/P2
