### ISSUE TITLE
cloud_to_cloud:node:ruby_server:large_unary timeout

### ISSUE THREAD

**Issue by dgquintas** [grpc/grpc#13130] opened 2017-10-24 17:24 UTC
https://sponge.corp.google.com/target?id=03fbaf7f-f1d7-4e71-acf4-5595107a947c&target=grpc/ubuntu/pull_request/grpc_interop_tocloud&searchFor=&show=ALL&sortBy=STATUS

```
2017-10-20 16:25:01,936 START: cloud_to_cloud:node:ruby_server:large_unary
...
2017-10-20 16:28:10,870 TIMEOUT: cloud_to_cloud:node:ruby_server:large_unary [pid=3125, time=188.9sec]
```

**Comment by yashykt** [comment] 2017-11-02 19:51
Also saw a timeout with cloud_to_cloud:node:csharp_server:large_unary
```
2017-11-02 11:26:37,534 TIMEOUT: cloud_to_cloud:node:csharp_server:large_unary [pid=3191, time=183.5sec]
```

**Comment by jtattermusch** [comment] 2017-11-06 15:11
Dupe of https://github.com/grpc/grpc/issues/13253

**Closed by jtattermusch** 2017-11-06 15:11 UTC
Labels: infra/BUILDPONY
