### ISSUE TITLE
Support for asyncio server-side in Python

### ISSUE THREAD

**Issue by mitar** [grpc/grpc#14876] opened 2018-03-29 22:52 UTC
[asyncio](https://docs.python.org/3/library/asyncio.html) is a now standard way to write asynchronous code in Python 3. It would be great if GRPC could be compiled into an asyncio version of the server code/interface.

There seems to be some prior work done here and it seems this is not too substantial: https://gist.github.com/seglberg/0b4487b57b4fd425c56ad72aba9971be

For now, I would love to see at least the server side. Client could also be, but somebody should open a separate issue for this.

Related: #6046

**Comment by NoAnyLove** [comment] 2018-05-31 03:40
Would like to have real async support in gRPC Python, instead of just a wrapper around ThreadPoolExecutor. Any plan on this?

**Comment by nathanielmanistaatgoogle** [comment] 2018-06-14 17:56
Yes this is something we want to do but... closing this issue as a duplicate of [issue 6046](https://github.com/grpc/grpc/issues/6046).

**Closed by nathanielmanistaatgoogle** 2018-06-14 17:56 UTC
Labels: area/concurrency, kind/enhancement, lang/Python, priority/P2
