### ISSUE TITLE
Do not copy protos across languages

### ISSUE THREAD

**Issue by a11r** [grpc/grpc#1250] opened 2015-04-10 17:52 UTC
- test.proto and messages.proto are have multiple copies across different languages. Only some copying is justified (e.g., when testing compiler plugins.) The rest need to move to a common directory.

**Comment by soltanmm** [comment] 2015-04-11 00:58
See #526.

**Comment by nathanielmanistaatgoogle** [comment] 2015-04-11 01:59
Closing this as a duplicate of #526.

**Closed by nathanielmanistaatgoogle** 2015-04-11 01:59 UTC
Labels: cleanup
