### ISSUE TITLE
Native libraries (grpc_csharp_ext.*.dll) not copied to output directory when using Grpc.Core with .NET Standard library

### ISSUE THREAD

**Issue by code-pug** [grpc/grpc#22804] opened 2020-04-28 10:19 UTC
Apologies if this is a by design or as expected, but I'm seeing some unexpected behaviour.

I'm using the gRPC libraries in an app with plugins. The server is actually implemented in one of the plugins, which is a .NET Standard library.

The problem I'm having is that it seems that the native libraries are not copied to any bin directory. If they are copied manually, everything works as expected. (Excellent job on the library by the way!)

It seems pretty simple to reproduce:

1) Open Visual Studio 2019 and create a new .NET Standard library project.
2) Add the 'Grpc.Core' NuGet package (2.28.1) to the project.

At this stage, I understand the .NET Standard libraries will only output their own DLL without dependencies, so understanding this blog: https://weblog.west-wind.com/posts/2019/Apr/30/NET-Core-30-SDK-Projects-Controlling-Output-Folders-and-Content, I add the following step:

3) Add the CopyLocalLockFileAssemblies element to the .csproj file

And finally 

4) Build

The final project file looks like this:

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
  </PropertyGroup>

  <PropertyGroup>
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Grpc.Core" Version="2.28.1" />
  </ItemGroup>

</Project>
```

But I still don't get the native DLLs.

![image](https://user-images.githubusercontent.com/122284/80476007-af96da00-8941-11ea-880c-03816be59a00.png)

Interestingly enough, if I change this to a .NET Core project by updating the project file from _netstandard2.0_ to netcoreapp3.1, it appears to output the runtimes in a separate folder:

![image](https://user-images.githubusercontent.com/122284/80476226-fdabdd80-8941-11ea-85d6-a0430ef91918.png)

Presumably this is then something to do with consuming the NuGet package in a .NET Standard library? Is there any suggested workaround or anything to help my understand this behavior?

**Comment by vivainio** [comment] 2020-05-05 12:17
Easiest workaround is probably to add PackageReference to Grpc.Core in some package that will be outputting to the final output path

**Comment by jtattermusch** [comment] 2020-05-06 15:20
I think what breaks this is the `<CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>` property. (can you verify that without it things are working as expected?) Why do you need it?

**Comment by jtattermusch** [comment] 2020-05-06 15:22
@code-pug  can you provide a project that reproduces the issue? (e.g. in form of a github repo).

**Comment by code-pug** [comment] 2020-05-07 11:55
@jtattermusch So, I mentioned that without adding it, I only get the DLL built by the project, nothing else. Adding it adds the grpc.core and grpc.core.api dlls, but not the native DLLs. 

I can add a github repo, but really, as mentioned in the original post, it's just File > New Project, Add NuGet package, compile. :)

I'll see if I can get some time together to do it, but I can't promise it'll be this week or next (I'm working on other priorities now).

Thanks for the help though.

**Comment by code-pug** [comment] 2020-05-07 11:56
@vivainio Thanks for the workaround. If/when I pick this back up, I think I might consider a 'Plugin Collector' project, or similar, which would resolve this.

**Comment by jtattermusch** [comment] 2020-05-07 16:03
Is this perhaps an instance of #11279 (see comment 
https://github.com/grpc/grpc/issues/11279#issuecomment-529307953 )
Can you try the workaround with `<PrivateAssets>None</PrivateAssets>`?

**Comment by jtattermusch** [comment] 2020-05-07 16:15
@code-pug  I've looked at your example more closely and I think I now understand what the problem is.

I think this is a general problem with how native runtimes work in .NET.
- if you build a class library (e.g. netstandard2.0), the `dotnet build` knows it's not an executable, so it doesn't bother copying the `runtimes` directory, because it knows that such library can be only run when included in an actual executable project (e.g. `netcoreapp2.1`)
- as soon as you include your class library in an executable project, the dotnet build will copy the native libraries under `runtimes` folder exactly as it should (which is also something you confirmed by your experiment)

In another words, everything is working as intended and it's not a gRPC bug, but how .NET native runtimes work by design.
As a workaround, you can use this suggestion https://github.com/grpc/grpc/issues/22804#issuecomment-624020604.

Closing as "working as intended".

**Closed by jtattermusch** 2020-05-07 16:15 UTC
Labels: kind/question, lang/C#, priority/P2

**Comment by code-pug** [comment] 2020-05-11 12:39
> @code-pug I've looked at your example more closely and I think I now understand what the problem is.
> 
> I think this is a general problem with how native runtimes work in .NET.
> 
> * if you build a class library (e.g. netstandard2.0), the `dotnet build` knows it's not an executable, so it doesn't bother copying the `runtimes` directory, because it knows that such library can be only run when included in an actual executable project (e.g. `netcoreapp2.1`)
> * as soon as you include your class library in an executable project, the dotnet build will copy the native libraries under `runtimes` folder exactly as it should (which is also something you confirmed by your experiment)
> 
> In another words, everything is working as intended and it's not a gRPC bug, but how .NET native runtimes work by design.
> As a workaround, you can use this suggestion [#22804 (comment)](https://github.com/grpc/grpc/issues/22804#issuecomment-624020604).
> 
> Closing as "working as intended".

Another link which discusses a similar issue with similar outcomes: https://stackoverflow.com/questions/56154884/nuget-package-not-copying-native-dlls-on-build
