### ISSUE TITLE
./tools/run_tests/run_tests.py fails with "php does not support multiple build configurations"

### ISSUE THREAD

**Issue by jcanizales** [grpc/grpc#1040] opened 2015-03-13 22:01 UTC
We should fix it or amend the documentation in CONTRIBUTING.md.

**Comment by jcanizales** [comment] 2015-03-13 22:12
Note, this is running on a Mac from master.

**Comment by murgatroid99** [comment] 2015-03-13 22:18
So, this is caused by a change I made a week or two ago to run_tests.py. Basically, I modified it so that we could run it with different configurations and scripting languages (`-l node -c dbg`, for example). But because all of the build steps run before all of the tests, running it with multiple configurations would only actually run the tests with the last one. Rather than make the test output misleading, I made it throw an error.

So, basically, we should probably do some more work on run_tests.py, and we should also probably change CONTRIBUTING,md.

**Comment by ctiller** [comment] 2015-03-14 01:14
How about we just change the default configs to just opt?

**Comment by nicolasnoble** [comment] 2015-03-16 05:18
I agree with @ctiller. It makes sense to change the default configs to just opt here.

**Comment by nicolasnoble** [comment] 2015-03-17 07:06
I have changed the run_tests.py script to only run opt by default. Could you confirm this is fixed and close the issue if it is ?

**Comment by murgatroid99** [comment] 2015-03-18 17:02
I can run `run_tests.py` without this sort of error, so I'd say it's fixed.

**Closed by murgatroid99** 2015-03-18 17:02 UTC
Labels: php, wrapped languages
