### ISSUE TITLE
Setting a message size > 1 Gb will crash a Python-based gRPC server

### ISSUE THREAD

**Issue by wihl** [grpc/grpc#19221] opened 2019-06-03 21:25 UTC
### What version of gRPC and what language are you using?

1.21.1 Python 
 
### What operating system (Linux, Windows,...) and version?

gLinux (rodete 201905RD3-1), also tried with latest Mac OS X Mojave
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
 
gLinux: Python 3.6.5, OSX: Python 3.7.2
 
### What did you do?
If possible, provide a recipe for reproducing the error. Try being specific and include code snippets if helpful.

Requested a stream of (2 Gb - 1) with a gRPC message size of (2 Gb - 1)
 
See https://github.com/wihl/grpc-msgs

### What did you expect to see?

Successful message transmission. 
 
### What did you see instead?

The Python Server crashed with:

```
[libprotobuf FATAL google/protobuf/wire_format.cc:740] CHECK failed: (output->ByteCount()) == (expected_endpoint): : Protocol message serialized to a size different from what was originally expected.  Perhaps it was modified by another thread during serialization?
terminate called after throwing an instance of 'google::protobuf::FatalException'
  what():  CHECK failed: (output->ByteCount()) == (expected_endpoint): : Protocol message serialized to a size different from what was originally expected.  Perhaps it was modified by another thread during serialization?
Aborted
```
 
Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

Run the server with (note: Python3):
`python3 route_guide_server.py`

Run the client with (note: Python2, though this is immaterial to the problem):
`python route_guide_client.py -b 2147483647 -n 1 -m 2147483647`

I ran the server under Python3 in case it was a Python 2 problem.

See [TROUBLESHOOTING.md](https://github.com/grpc/grpc/blob/master/TROUBLESHOOTING.md) for how to diagnose problems better.
 
### Anything else we should know about your project / environment?

If I set the message size smaller like 1 Gb, it will work, e.g.
 `python route_guide_client.py -b 1000000000 -n 1 -m 1000000050`

Per @srini100's request, see https://github.com/grpc/grpc/issues/19122

**Comment by lidizheng** [comment] 2019-06-04 20:44
@wihl Originally, the ProtoBuf size limit is 64MB. And there is a compile time flag `-DPROTOBUF_PYTHON_ALLOW_OVERSIZE_PROTOS` see [code](https://github.com/protocolbuffers/protobuf/blob/60b66a119d17f0a2a595a231bea87cd4f4cf2689/python/google/protobuf/pyext/message.cc#L1905). With the flag enabled, the library will raise the size limit to 2GB `INT_MAX`.

It is possible that the 1GB limit is due to undefined behavior without setting the flag and operating proto message over 64MB. Can you please try:

1) Compile the ProtoBuf Python library with the flag (you can use [setup.py](https://github.com/protocolbuffers/protobuf/blob/master/python/setup.py) or their Bazel target or internal Blaze target);
2) Run the large size proto transport test again.

**Comment by lidizheng** [comment] 2019-06-04 22:52
@wihl One more finding I forgot to mention that for different device, the limitation of the size of proto is different. We observe the limit approaching 2GB on work stations, and similar 1GB limit on laptop. Can you try your reproduction code on other environment to make sure this is a problem with gRPC Python?

**Comment by wihl** [comment] 2019-06-05 02:05
@lidizheng I mentioned that I already tried it on a gLinux workstation and a regular (non Google) OSX machine. Is there another environment you'd like me to test?

**Comment by lidizheng** [comment] 2019-06-05 17:51
@wihl Sorry, I overlooked your the environment part.

I can still reproduce the error on whatever machine for message size ~ 2GiB. Your reproduction code is very easy to use :)

For 2GiB - random value, I observed no server crash at 1.81GiB on my Macbook Pro in 170 seconds.
```
lidiz-macbookpro:python lidiz$ python route_guide_client.py -b 1947483646 -n 1 -m 2047483646
Message size too large; skipping repeat rows.
-------------- call stream ----------------
 1947483646 bytes per row, 1 rows
elapsed time:169.594
```

And on desktop, I observed the number can go higher to 1.999GiB.
```
lidiz@ddev:python$ python route_guide_client.py -b 2146483631 -n 1 -m 2147483647
Message size too large; skipping repeat rows.
-------------- call stream ----------------
 2037483647 bytes per row, 1 rows
elapsed time:31.889
```

I will focus on the message size ~ 2GiB then.

**Comment by lidizheng** [comment] 2019-06-05 18:27
@whil I bisected the largest possible value on both my laptop and workstation. The largest message size without crash is 2147483630 (=2GiB - 18b), and the server handles them fine on both machines. 

Notably, the server memory usage is around 3.6GB. As long as the machine have enough memory space, I think the test will pass. The server is able to handle 8 concurrent one-row streaming RPC with message size of 2147483630.

Can you give more detail to help me locate the restriction around 1GB?

**Comment by lidizheng** [comment] 2019-09-03 17:42
Closing for now, feel free to reopen for updates.

**Closed by lidizheng** 2019-09-03 17:42 UTC
Labels: disposition/requires reporter action, kind/bug, lang/Python, priority/P2
