### ISSUE TITLE
per_rpc_creds interop test fails for php and php7 against prod 

### ISSUE THREAD

**Issue by adelez** [grpc/grpc#7889] opened 2016-08-26 18:17 UTC
https://grpc-testing.appspot.com/job/gRPC_interop_master/6958/console
Last successful build is 6866
Warning! PATH is not properly set up, '/usr/local/rvm/gems/ruby-2.1.8/bin' is not available,
         usually this is caused by shell initialization files - check them for 'PATH=...' entries,
         it might also help to re-add RVM to your dotfiles: 'rvm get stable --auto-dotfiles',
         to fix temporarily in this shell session run: 'rvm use ruby-2.1.8'.
Using /usr/local/rvm/gems/ruby-2.1.8
stdin: is not a tty
Running test case per_rpc_creds
Call did not complete successfully

**Comment by stanley-cheung** [comment] 2016-08-26 18:21
Dupe of #7881

**Closed by stanley-cheung** 2016-08-26 18:21 UTC
