### ISSUE TITLE
error ref counts in grpc_closure_list_append

### ISSUE THREAD

**Issue by amoldeshpande** [grpc/grpc#10943] opened 2017-05-02 04:27 UTC
I'm getting a crash  in grpc_exec_ctx_flush on the GRPC_ERROR_UNREF line (80). The root of the problem seems to be this call stack:

```
 > x!grpc_closure_list_append(grpc_closure_list * closure_list, grpc_closure * closure, grpc_error * error) Line 60	
 > x!exec_ctx_sched(grpc_exec_ctx * exec_ctx, grpc_closure * closure, grpc_error * error) Line 109	
 > x!grpc_closure_sched(grpc_exec_ctx * exec_ctx, grpc_closure * c, grpc_error * error) Line 149	
 > x!finish(grpc_exec_ctx * exec_ctx, internal_request * req, grpc_error * error) Line 109	
 > x!on_resolved(grpc_exec_ctx * exec_ctx, void * arg, grpc_error * error) Line 248	
 > x!closure_wrapper(grpc_exec_ctx * exec_ctx, void * arg, grpc_error * error) Line 116	
 > x!grpc_exec_ctx_flush(grpc_exec_ctx * exec_ctx) Line 80	
 > x!closure_exec_thread_func(void * ignored) Line 95	
 > x!thread_body(void * v) Line 72	
```
*grpc_exec_ctx_flush* is going through the last closure in the context.
with this call stack, the *closure_list_append* function will put the error back on the *closure_list* without incrementing the refcount.

*grpc_exec_ctx_flush* will  (on popping out of this stack ), free the error ref, and the loop will go back to the newly added closure. However, now we have an error that has been freed because no one in the above stack added a reference.  
From reading https://github.com/grpc/grpc/blob/master/doc/core/grpc-error.md  it seems like *grpc_closure_list_append* should be adding references to errors (since it is not a callback).

However, if that's true, I don't understand how any of this ever works.  What am I missing ?

**Comment by ncteisen** [comment] 2017-05-02 05:43
Hi, thanks for looking into this! _ grpc_closure_list_append_ and _ grpc_exec_ctx_flush_ are actually working as expected, though I can see where the confusion comes in. 

Let's start three back from the end of the trace at _exec_ctx_sched_. Since it does not have the signature of a callback, it has ownership of the error. That means it either has to manually unref the error, or pass along the ownership to another function that will eventually unref it.

_exec_ctx_sched_ passes along the ownership to _grpc_closure_list_append_, which does not have the signature of a callback, and thus takes to ownership. Now _grpc_closure_list_append_ has the responsibility of unreffing the error. If the closure is null, it does this immediately. If not, it defers the eventual unreffing by holding onto the error in the actual closure struct. The eventual unreffing is done by _grpc_exec_ctx_flush_ after invoking the callback.

This means that the bug occurs higher up in the code. If you want to look into it further, than uncomment [this line
](https://github.com/grpc/grpc/blob/master/src/core/lib/iomgr/error.h#L167) and set the env variable GRPC_VERBOSITY=DEBUG. You will be able to track the refs and unrefs the error gets. Most likely a certain code path missed a ref and broke the error ownership semantics.

Alternatively, could you give us a way to reproduce this crash? Then we can take a look and track this down. Thanks for catch this one!

**Comment by amoldeshpande** [comment] 2017-05-02 14:21
ok,  *grpc_closure_list_append* has the responsibility of unreffing the error,but *grpc_exec_ctx_flush* is going to unref this same error when the callback returns (line 79/80 of exec_ctx.c). I am not seeing how that would ever work without adding refcounts at the point of ownership transfer. 

anyway I will turn on debugging and dig deeper.

As far as reproing, I'm just calling grpc::GetDefaultCredentials() without any environment variables set. It seems to be crashing in the resolver while attempting to detect if it's running on GCE.  I'm running on Windows.

Will let you know what I find.

**Comment by amoldeshpande** [comment] 2017-05-02 21:01
After beating my head against the wall, I installed on linux and ran the following  piece of code

```
#include <grpc++/grpc++.h>

int main(int argc, char**argv) {


	auto creds = grpc::GoogleDefaultCredentials();
return 0;

}
```
And it crashes in exactly the same way. If I add a grpc_init() call at the top of main,  I can still see the abort in gdb, but not if I run the executable outside gdb.  I don't know enough about linux to understand why.

here's the log output from Windows, which basically tells me what I already know. 
```
D0502 09:00:12.337000000 12340 error.c:335] 0000020C8E7F9CB0 create [i:\github\grpc\src\core\lib\iomgr\resolve_address_windows.c:106]
D0502 09:00:12.337000000 12340 error.c:226] realloc 0000020C8E7F9CB0 -> 0000020C8E809A70
D0502 09:00:29.159000000 12340 error.c:194] 0000020C8E809A70: 1 -> 0 [i:\github\grpc\src\core\lib\iomgr\exec_ctx.c:80 grpc_exec_ctx_flush]
E0502 09:00:37.804000000 20436 google_default_credentials.c:299] Could not create google default credentials.
D0502 09:00:37.804000000 12340 error.c:194] 0000020C8E809A70: -2459565876494606883 -> -2459565876494606884 [i:\github\grpc\src\core\lib\iomgr\exec_ctx.c:80 grpc_exec_ctx_flush]
E0502 09:00:37.804000000 12340 sync.c:118] assertion failed: prior > 0

```

**Comment by ncteisen** [comment] 2017-05-03 06:30
Found it! Thanks for the repro. I verified the fix on Linux. Would you mind pulling my branch down and verifying on Windows too? Fix is in #10972/

**Comment by ncteisen** [comment] 2017-05-03 06:32
As you probably experienced, these can be super tricky to find since the missing ref usually happens far away from the final unref that crashes the program. I've got a WIP that adds some tracing to closures to make finding these crashes a bit less painful. Check it out at #10767. I used it to find this one.

**Comment by amoldeshpande** [comment] 2017-05-03 13:56
yep, that fixes it, thanks. 

If I may say so, the rules on refcounting are convoluted and prone to such errors (no pun intended). 
The simple rule should be that if a function needs an object to exists past its lifetime, it needs to add a reference (and have  way to release said reference when not needed).  Creation being an implicit addref.

The current way of random functions adding or not adding references because of what they do (rather than how the use the object) strikes me as quite fragile.

I found Apple's guidelines for Core Foundation quite good in this regard especially with naming conventions for functions. Or Microsoft's COM memory management guidelines from way back in the day as well. 

This is an already-solved problem in the C world.  But I suppose every one of us thinks they know a better way to write software :-)

Anyway, that's all academic. Thanks for fixing this bug so quickly.

**Closed** 2017-05-03 15:24 UTC
Labels: bug, core, requires reporter action
