### ISSUE TITLE
csharp's custom_metadata test flaky

### ISSUE THREAD

**Issue by muxi** [grpc/grpc#9825] opened 2017-02-22 17:53 UTC
Failed in this test:
https://grpc-testing.appspot.com/job/gRPC_interop_pull_requests/11557/consoleFull
```
csharpcoreclr_server:custom_metadata
csharp_server:custom_metadata
```

**Comment by dgquintas** [comment] 2017-02-22 18:19
So that we can find issues, please name the failing tests cases explicitly, ideally in the title:

```
tests.cloud_to_cloud:java:csharp_server:custom_metadata
tests.cloud_to_cloud:java:csharpcoreclr_server:custom_metadata
tests.cloud_to_cloud:java:csharp_server:large_unary
```

**Comment by jtattermusch** [comment] 2017-02-27 11:43
Duplicate of https://github.com/grpc/grpc/issues/9762

**Closed by jtattermusch** 2017-02-27 11:43 UTC
Labels: BUILDPONY

**Comment by jtattermusch** [comment] 2017-02-27 11:45
FTR, the logs were:

```
 Gradle is no longer run automatically. Make sure to run
'./gradlew installDist -PskipCodegen=true' or
'./gradlew :grpc-interop-testing:installDist -PskipCodegen=true' after any
changes. -PskipCodegen=true is optional, but requires less setup.
Running test custom_metadata
Feb 22, 2017 2:08:25 AM io.netty.util.internal.MacAddressUtil defaultMachineId
WARNING: Failed to find a usable hardware address from the network interfaces; using random bytes: 0b:0c:ed:28:bd:d6:23:68
Exception in thread "main" io.grpc.StatusRuntimeException: INTERNAL: Connection closed with unknown cause
	at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:227)
	at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:208)
	at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:141)
	at io.grpc.testing.integration.TestServiceGrpc$TestServiceBlockingStub.unaryCall(TestServiceGrpc.java:408)
	at io.grpc.testing.integration.AbstractInteropTest.customMetadata(AbstractInteropTest.java:962)
	at io.grpc.testing.integration.TestServiceClient.runTest(TestServiceClient.java:264)
	at io.grpc.testing.integration.TestServiceClient.run(TestServiceClient.java:197)
	at io.grpc.testing.integration.TestServiceClient.main(TestServiceClient.java:81)
Shutting down

FAILED: cloud_to_cloud:java:csharpcoreclr_server:custom_metadata [ret=1, pid=2151]
```
