### ISSUE TITLE
LocalSubchannelPool and GlobalSubchannelPool should provide more than one instance of an unique socket address

### ISSUE THREAD

**Issue by zhengdehui** [grpc/grpc#25062] opened 2020-12-28 06:42 UTC
Currently, `LocalSubchannelPool` and `GlobalSubchannelPool` are used in client channel making TCP connection to upstream servers. However, only one `Subchannel` instance will be returned by one unique endpoint socket addr (e.g. 192.168.1.2:8080), which means if the client uses a singleton Channel object, all requests of a unique endpoint will go through the same TCP connection. 
Usually in the upstream server, the data of one TCP connection will be handled by one IO thread. 
So this could cause the IO thread of the upstream server to be the performance bottle neck of the GRPC invocation.

I suggest to provide a new parameter 'grpc.subchannel_pool.per_connection_instance', to make one unique endpoint socket addr to have more than one Subchannel instance, and pick Subchannel instance by random/round-robin in each invocation

**Comment by firebook** [comment] 2021-01-05 06:36
We meet same problem, hope to have a solution

**Comment by markdroth** [comment] 2021-01-12 18:22
I think this is a duplicate of #21386.  There is also some related discussion in #7957.

**Closed by markdroth** 2021-01-12 18:22 UTC
Labels: area/client channel, kind/enhancement, lang/core, priority/P2
