### ISSUE TITLE
(dbg, c, windows): Failure on tests.vsprojects/Debug/h2_compress_nosec_test.exe compressed_payload

### ISSUE THREAD

**Issue by vjpai** [grpc/grpc#6168] opened 2016-04-13 21:33 UTC
Error Message

Failure
Standard Output

D0413 02:55:21.433000000  4508 test_config.c:278] test slowdown: machine=1.000000 build=1.000000 total=1.000000
I0413 02:55:21.435000000  4508 compressed_payload.c:60] test_invoke_request_with_exceptionally_uncompressed_payload/chttp2/fullstack_compression
E0413 02:55:27.031000000  4508 cq_verifier.c:248] event not found: OP_COMPLETE: tag:00000001 OK
E0413 02:55:27.031000000  4508 cq_verifier.c:251] have tags: 00000065
Abort handler called.
*** 0: 00000000013B6EEF  - 0000000000000000
*** 1: 00000000013B73F7  - 0000000000000000
*** 2: 0000000001418279  - 0000000000000000
*** 3: 00000000014121A4  - 0000000000000000
*** 4: 0000000001482EF6  - 0000000000000000
*** 5: 00000000013F85F3  - 0000000000000000
*** 6: 00000000013F8EFD  - 0000000000000000
*** 7: 00000000013F9190  - 0000000000000000
*** 8: 00000000013F0BD7  - 0000000000000000
*** 9: 00000000013B134A  - 0000000000000000
*** 10: 000000000141250A  - 0000000000000000
*** 11: 000000000141265D  - 0000000000000000
*** 12: 0000000075C8338A BaseThreadInitThunk - 0000000075C83378
*** 13: 0000000077129A02 RtlInitializeExceptionChain - 000000007712999F
*** 14: 00000000771299D5 RtlInitializeExceptionChain - 000000007712999F

**Comment by stanley-cheung** [comment] 2016-04-14 15:59
Dupe of #5885?

**Comment by vjpai** [comment] 2016-04-15 14:35
Not a dup - this was on master, but #5885 was on portability master. I should have included the URL.

**Closed** 2016-04-27 20:49 UTC
Labels: BUILDPONY, core, P1, Windows
