### ISSUE TITLE
Flake: Kokoro - interop cloud_to_prod:default:php:large_unary

### ISSUE THREAD

**Issue by vjpai** [grpc/grpc#12067] opened 2017-08-03 22:57 UTC
https://sponge.corp.google.com/target?id=73835ec6-1b39-46cf-bfb6-30ab59fe2dcb&target=grpc/ubuntu/pull_request/grpc_interop_toprod&searchFor=&show=ALL&sortBy=STATUS

**Comment by jtattermusch** [comment] 2017-11-06 15:21
Dupe of #10763

**Closed by jtattermusch** 2017-11-06 15:21 UTC
Labels: infra/BUILDPONY, lang/php
