### ISSUE TITLE
java 9 not supported?

### ISSUE THREAD

**Issue by onesea** [grpc/grpc#13182] opened 2017-10-30 02:29 UTC
/root/grpc-kotlin-hello/proto/src/main/java/io/grpc/examples/helloworld/GreeterGrpc.java:23: error: cannot find symbol
@javax.annotation.Generated(
                 ^
  symbol:   class Generated
  location: package javax.annotation
1 error

FAILURE: Build failed with an exception.

**Comment by ejona86** [comment] 2017-11-01 17:45
This is a duplicate of grpc/grpc-java#3633.

**Closed by ejona86** 2017-11-01 17:45 UTC
Labels: lang/Java
