### ISSUE TITLE
Objc GRXWriter writerWithValueSupplier may influence other RPC call

### ISSUE THREAD

**Issue by gfxcc** [grpc/grpc#8131] opened 2016-09-17 20:00 UTC
If I use sleep(1) in GRXWriter, every rpc call will be influenced
`synWithRequestsWriter` send packages to server once a second since I used `[NSThread sleepForTimeInterval:1.0f];`
`obtain_billsWithRequest` should received 400 records as soon as possible. But it receives records once a second too.
I checked the server (update to 1.0.0 cpp), it works fine. Every data were sent in a second. If I remove `[NSThread sleepForTimeInterval:1.0f];`, everything works fine.

This problem happened when I update to 1.0.0
Same code works fine on 0.12.0

I wrote blow code in a new project to test this problem. It did exist.

`

```
    GRXWriter *_requestsWriter = [GRXWriter writerWithValueSupplier:^id() {
        Inf *test1 = [Inf message];
        test1.information = @"1";
        [NSThread sleepForTimeInterval:1.0f];
        return test1;
    }];

    Greeter *service = [[Greeter alloc] initWithHost:kHostAddress];

    [service synWithRequestsWriter:_requestsWriter eventHandler:^(BOOL done, Syn_data *response, NSError *error) {
        if (!done) {
            NSLog(@"in syning");
        } else if (error) {
            NSLog(@"Finished with error: %@", error);
        } else {
            _requestsWriter.state = GRXWriterStateStarted;
            NSLog(@"%li", (long)_requestsWriter.state);
        }
    }];


    Greeter *client = [[Greeter alloc] initWithHost:kHostAddress];
    Bill_request *request = [Bill_request message];
    request.username = @"1";
    request.start = @"0";
    request.amount = @"all";

    [client obtain_billsWithRequest:request eventHandler:^(BOOL done, Share_inf *note, NSError *error) {
        if (!done) {
            NSLog(@"get %@", note.billId);
        } else if (error) {

        } else {
            NSLog(@"Chat ended.");
        }
    }];
```

`

@jcanizales

**Comment by jcanizales** [comment] 2016-09-20 01:20
Yeah, the proximal cause of this is that `[GRXWriter writerWithValueSupplier:]` expects all values to be immediately available. So it calls the passed block (the supplier) in the same thread where its `startWithWriteable:` method is called, not expecting it to block.

I think the easiest way to achieve what you're trying to do is, instead of sending the thread to sleep within the block, pause the writer. Then schedule a block to un-pause it after the delay you want. And finally return the value.

Turning that into a generic transformation to apply on a `GRXWriter` looks like a fun exercise too :)

**Comment by gfxcc** [comment] 2016-09-20 02:52
Could you tell me how to pause the writer as you said?
I tried `_requestsWriter.state = GRXWriterStatePaused;`. It does not work.

**Comment by jcanizales** [comment] 2016-09-20 05:03
You'll need to define `_requestsWriter` as a `__block` variable. See the two first paragraphs of this comment for an explanation why: https://github.com/grpc/grpc/issues/6113#issuecomment-246557368

**Comment by gfxcc** [comment] 2016-09-27 04:16
I tried that, but doesn't work.


`        __block GRXWriter *_requestsWriter;
        _requestsWriter = [GRXWriter writerWithValueSupplier:^id() {
            
            Inf *test1 = [Inf message];
            test1.information = @"1";
            //[NSThread sleepForTimeInterval:1.0f];
            _requestsWriter.state = GRXWriterStatePaused;
            return test1;
        }];`

**Comment by jcanizales** [comment] 2016-09-27 04:29
Can you elaborate?

And remember that you'll want to unpause the writer too.

**Comment by gfxcc** [comment] 2016-09-27 04:46
Actually, the writer never paused.......

I also test that on an new project.

`

        __block GRXWriter *_requestsWriter;
        _requestsWriter = [GRXWriter writerWithValueSupplier:^id() {
            
            Inf *test1 = [Inf message];
            test1.information = @"1";
            //[NSThread sleepForTimeInterval:1.0f];
            _requestsWriter.state = GRXWriterStatePaused;
            return test1;
        }];
        
    
        _requestsWriter.state = GRXWriterStatePaused;
        //NSLog(@"test");
        //[_requestsWriter startWithWriteable:writable];
        Greeter *service = [[Greeter alloc] initWithHost:kHostAddress];
        
        [service synWithRequestsWriter:_requestsWriter eventHandler:^(BOOL done, Syn_data *response, NSError *error) {
            if (!done) {
                NSLog(@"in syning");
                _requestsWriter.state = GRXWriterStatePaused;
            } else if (error) {
                NSLog(@"Finished with error: %@", error);

            } else {
                _requestsWriter.state = GRXWriterStateStarted;
                NSLog(@"%li", (long)_requestsWriter.state);
            }
        }];

`

**Comment by gfxcc** [comment] 2016-09-30 19:25
@jcanizales
sorry for bothering you
But I want know the problem I met caused by my mistake?
Or that was a bug, I have to wait for new release.

**Comment by jcanizales** [comment] 2016-10-01 19:55
Hi, sorry for the delay, I've been swamped this week. I'm going to copy your code into a test project and debug it to see what's going on.

**Comment by jcanizales** [comment] 2016-10-04 03:55
When I try this in a playground the result is as expected:

```swift
import PlaygroundSupport
import RxLibrary
import Foundation

PlaygroundPage.current.needsIndefiniteExecution = true

var writer : GRXWriter! = nil
writer = GRXWriter {
  writer.state = .paused
  DispatchQueue.main.after(walltime: .now() + 1) {
    writer.state = .started
  }
  return "infinite"
}!

var i = 0
writer.start(with: GRXWriteable { (done, value, error) in
  i += 1
  print(value)
  if (!done && i == 5) {
    writer.finishWithError(nil)
  }
})
```

The output is:
```
Optional(infinite)
Optional(infinite)
Optional(infinite)
Optional(infinite)
Optional(infinite)
nil
```
with 1s passing between each line.

**Comment by jcanizales** [comment] 2016-10-04 03:58
The following is equivalent, pausing in the writeable block instead of the writer supplier:

```swift
import PlaygroundSupport
import RxLibrary
import Foundation

PlaygroundPage.current.needsIndefiniteExecution = true

let writer = GRXWriter(container: [0, 1, 2, 3])!

writer.start(with: GRXWriteable { (done, value, error) in
  print(value)
  if (!done) {
    writer.state = .paused
    DispatchQueue.main.after(walltime: .now() + 1) {
      writer.state = .started
    }
  }
})
```
It outputs:
```
Optional(0)
Optional(1)
Optional(2)
Optional(3)
nil
```
with 1s passing between each line.

**Comment by jcanizales** [comment] 2016-10-04 04:04
Looking at your code, in this part:
```objective-c
[service synWithRequestsWriter:_requestsWriter
                  eventHandler:^(BOOL done, Syn_data *response, NSError *error) {
  if (!done) {
    _requestsWriter.state = GRXWriterStatePaused;
  } else if (error) {
    ;
  } else {
    _requestsWriter.state = GRXWriterStateStarted;
  }
}];
```

You're only resuming the writer (setting its state to `GRXWriterStateStarted`) when `done == YES`. That condition only happens when the server finishes the RPC (successfully, or due to an error). So if your server is waiting for more input, it will never happen (and if/when it happens, it'll be too late anyway, as the RPC is already over).

**Comment by gfxcc** [comment] 2016-11-27 18:41
Hi, I resumed my project and met this problem again.
I am not sure why you did not meet this problem in Swift.

I try to debug it by myself and I do get something.

call `__block GRXWriter *requestsWriter`    (`requestsWriter.state = GRXWriterStatePaused;` executed at this time)
                            |
                            ˇ
will call `- (void)writeValue:(id)value` in `GRPCCall.m`
```
- (void)writeValue:(id)value {
  // TODO(jcanizales): Throw/assert if value isn't NSData.

  // Pause the input and only resume it when the C layer notifies us that writes
  // can proceed.
  @synchronized(_requestWriter) {
    _requestWriter.state = GRXWriterStatePaused;
  }

  __weak GRPCCall *weakSelf = self;
  dispatch_async(_callQueue, ^{
    [weakSelf writeMessage:value withErrorHandler:^{
      [weakSelf finishWithError:[NSError errorWithDomain:kGRPCErrorDomain
                                                    code:GRPCErrorCodeInternal
                                                userInfo:nil]];
    }];
  });
}
```
during this process, it will set `state` to `GRXWriterStatePaused` again
                            |
                            ˇ
then, `_callQueue` will call `- (void)writeMessage:(NSData *)message withErrorHandler:(void (^)())errorHandler;
` in GRPCCall.m
```
// Only called from the call queue. The error handler will be called from the
// network queue if the write didn't succeed.
- (void)writeMessage:(NSData *)message withErrorHandler:(void (^)())errorHandler {

  __weak GRPCCall *weakSelf = self;
  void(^resumingHandler)(void) = ^{
    // Resume the request writer.
    GRPCCall *strongSelf = weakSelf;
    if (strongSelf) {
      @synchronized(strongSelf->_requestWriter) {
        strongSelf->_requestWriter.state = GRXWriterStateStarted;
      }
    }
  };
  [_wrappedCall startBatchWithOperations:@[[[GRPCOpSendMessage alloc] initWithMessage:message
                                                                              handler:resumingHandler]]
                            errorHandler:errorHandler];
}
```
which will set `strongSelf->_requestWriter.state = GRXWriterStateStarted;` and resume the state.

For thoes reason, the state will keep changing between `GRXWriterStateStarted-> GRXWriterStatePaused-> GRXWriterStateStarted   `  even I never tried to resume it.

So, try to pause GRXWriter is impossible.......... since `writeMessage` will resume it automatically.
@jcanizales

**Comment by jcanizales** [comment] 2017-01-10 20:17
@muxi, can you take a look?

**Comment by muxi** [comment] 2017-01-13 06:02
@jcanizales - @gfxcc's analysis seems to be right. `GRPCCall`'s state seems to be overwritten when `SEND_MESSAGE` op is complete. I am thinking of a solution to always add a `GRXBufferedPipe` between `GRPCCall` and requestWriter.  It acts as a message-to-be-sent queue for `GRPCCall` when a `SEND_MESSAGE` is still pending complete. What do you think?

**Comment by jcanizales** [comment] 2017-01-13 11:43
The problem with adding a BufferedPipe in between is that it drops the control flow information that the server is telling the client. Say I want to write a long stream of big bytes chunks: Right now, the server will automatically control when are further writes allowed. With a BufferedPipe in between, the writer would dump everything into the pipe, wasting memory and sometimes leading to an OOM situation. In general, using `GRXBufferedPipe` for things other than testing is very suspect, as its docs explain.

What we want here is something I can add in front of a Writer, that gives more than one party the ability to pause. So that only when all parties set their state to `Started`, the original writer is set to `Started`; and as soon as any of the parties set their state to `Paused`, the original writer is set to `Paused`. A logical OR for pauses, and a logical AND for starts.

We can think about how to bake it in automatically for RPC requests, because the instinctive way of pausing a request is indeed to set its state to `Paused`, not to have the foresight to do some trick before passing it to the service object.

@gfxcc The reason I couldn't reproduce in that Swift snippet is that I didn't invoke any `GRPCCall` with it! Your analysis is right, and I'm sorry for the confusion.

**Comment by muxi** [comment] 2017-01-14 00:07
A more sophisticated state control sounds great. I think there is a way to wrap the states so that it is as instinctive to user as pausing and hide all the foresights inside.

**Comment by acoroian** [comment] 2017-02-07 18:44
Same thing is happening to me where the writer does not pause. Is there anything i can do to this code to make the requestWriter pause after it sends the request?

```swift
func listenForMessages() {
        let request = MessagesListenRequest()
        
        var isFirstPush = true
        var requestWriter : GRXWriter! = nil
        requestWriter = GRXWriter {
            if(!isFirstPush) {
                requestWriter.state = .paused
            }
            isFirstPush = false
            return request
        }
       
        listenMessagesCall = self.conversationsService?.rpcTolisten_conversation(withRequestsWriter: requestWriter!, eventHandler: { (done, message, error) in
            print("REQUEST", done, message, error)
            
            if (done) {
                print("Stream closed.")
            }
        })
        
        startCall(call: listenMessagesCall)
    }
```

**Comment by muxi** [comment] 2017-02-07 18:58
Hi @acoroian, I think adding a GRXBufferedPipe after your GRXWriter could be a temp fix for this issue. We will deliver a better fix in later releases.

**Comment by jcanizales** [comment] 2017-02-07 21:30
I think this issue should be kept open until the real fix is done.

**Comment by muxi** [comment] 2017-02-07 21:32
Yep. So I removed `to close` tag ;-)

**Comment by gfxcc** [comment] 2019-09-05 14:41
Still needed?

**Comment by sashabaranov** [comment] 2019-11-04 16:12
So… It here some final solution with example code? I've just tried GRXWriter with paused state and GRXBufferedPipe — both did not work out. [Docs](https://grpc.io/docs/tutorials/basic/objective-c/) are also obscure.

**Comment by muxi** [comment] 2019-11-08 01:43
First, I apologize that this issue stayed idle for such a long time. In the mean time, gRPC API has evolved and RxLibrary has been deprecated for users, preferring a new interface (see [example usages](https://github.com/grpc/grpc/tree/master/examples/objective-c)). While the deprecated API still works, we do recommend users to use the new interface. However, if you are still interested in using RxLibrary the way in this issue, a contribution for fix is welcome and we will look at it.

**Comment by stanley-cheung** [comment] 2020-05-05 19:59
We acknowledge this to be a valid feature request but since no one has come forward to implement this, we are going to close it for now while maintaining the label/Help wanted to indicate that this can be picked up as future work.

**Closed by stanley-cheung** 2020-05-05 19:59 UTC
Labels: disposition/help wanted, kind/bug, lang/ObjC, priority/P2
