### ISSUE TITLE
Grpc.Tools: Protobuf Compile fails for .NetCore 3.1 WPF

### ISSUE THREAD

**Issue by ax-meyer** [grpc/grpc#23173] opened 2020-06-10 12:25 UTC
### What version of gRPC and what language are you using?
gRPC & gRPC.Tools v2.29.0 nuget packages, C#

### What operating system (Linux, Windows,...) and version?
Windows 10 1809

### What runtime / compiler are you using (e.g. python version or version of gcc)
NetCore SDK 3.1

### What did you do?
* Created the project
* Added GRPC & GRPC.Tools nuget packages
* Added protofile to project
* Added ` <Protobuf Include="proto_filename.proto" />` to the .csproj
* Added `using <proto_namespace>;` to a cs file - Intellisense auto-completes the namespace
* Build

### What did you expect to see?
Automatic compilation of the proto file into a cs source and a sucessfull build.

### What did you see instead?
Build fails with `Namespace <proto_namespace> not found, are you missing an assebmly reference` error.
In the folder `obj/Debug/netcoreapp3.1` the file `proto_filename.cs` is created, but it is empty.

### Workaround
In general, the proto-compilation works on my system. My current workaround is to create another project `ProtoCompilationDummy.csproj`  as a `netstandard2.0` project, add the proto file there, and reference this project from my netcore3.1 project.

This works fine, proto compilation runs fine, and I can use the proto namespace.

# **EDIT**

I created an example here: https://github.com/ax-meyer/GRPC_Bug23173_Demo
And after the testing, I need to specify: It does **not work** for .netCore 3.1 **WPF** Apps - it actually **does work** for -netCore 3.1 **Console** Apps.

I included 4 examples in the repo, console app and WPF app, and each with "direct" compilation and "indirect" compilation by referencing the dummy project.

**Comment by jtattermusch** [comment] 2020-06-22 12:09
Can you provide an example project (e.g. as a github repo) that suffers from this issue?  Finding out what's wrong is going to be much easier that way.

**Comment by jtattermusch** [comment] 2020-06-22 12:11
CC @JunTaoLuo  any reason why the codegen could be broken in netcoreapp3.1 apps?
(also this issue sounds a bit familiar?)

**Comment by ax-meyer** [comment] 2020-06-22 12:53
> 
> 
> Can you provide an example project (e.g. as a github repo) that suffers from this issue? Finding out what's wrong is going to be much easier that way.

I created an example here: https://github.com/ax-meyer/GRPC_Bug23173_Demo
And after the testing, I need to specify: It does **not work** for .netCore 3.1 **WPF** Apps - it actually **does work** for -netCore 3.1 **Console** Apps.

I included 4 examples in the repo, console app and WPF app, and each with "direct" compilation and "indirect" compilation by referencing the dummy project.

**Comment by jtattermusch** [comment] 2020-06-22 14:11
Ok, if it's only broken in WPF apps, then this seems to be a duplicate of https://github.com/grpc/grpc/issues/20402.
The recommended workaround is to create an intermediate netstandard2.0 library that contains all the protos (basically what you've done).

**Closed by jtattermusch** 2020-06-22 14:11 UTC
Labels: kind/bug, lang/C#, priority/P2

**Comment by ax-meyer** [comment] 2020-06-22 14:16
> 
> 
> Ok, if it's only broken in WPF apps, then this seems to be a duplicate of #20402.
> The recommended workaround is to create an intermediate netstandard2.0 library that contains all the protos (basically what you've done).

Oh, ok, sorry I missed the old issue. 
Thanks!
