### ISSUE TITLE
flake: //test/cpp/end2end:xds_end2end_test@poller=epoll1[k8-fastbuild]

### ISSUE THREAD

**Issue by jtattermusch** [grpc/grpc#22018] opened 2020-02-14 08:47 UTC
https://source.cloud.google.com/results/invocations/0166accb-9344-4072-8603-588fc80f4f8b/targets/%2F%2Ftest%2Fcpp%2Fend2end:xds_end2end_test@poller%3Depoll1/tests

```
test/cpp/end2end/xds_end2end_test.cc:2418
Value of: seen_drop_rate
Expected: (is >= 0.07) and (is <= 0.13)
  Actual: 0.066 (of type double)
```

**Comment by markdroth** [comment] 2020-02-14 15:21
Duplicate of #21230.

**Closed by markdroth** 2020-02-14 15:21 UTC
Labels: infra/BUILDPONY, kind/bug, lang/c++, priority/P2
