### ISSUE TITLE
error MSB6004: The specified task executable location "/linux_x64/protoc" is invalid.

### ISSUE THREAD

**Issue by plachta11b** [grpc/grpc#34306] opened 2023-09-11 15:22 UTC
### Error message

`/root/.nuget/packages/grpc.tools/2.58.0/build/_protobuf/Google.Protobuf.Tools.targets(291,5): error MSB6004: The specified task executable location "/linux_x64/protoc" is invalid.`

### What version of gRPC and what language are you using?

2.58.0 (affects more versions)

### What operating system (Linux, Windows,...) and version?

Linux

### What runtime / compiler are you using (e.g. python version or version of GCC)

MSBuild version 17.8.0-preview-23367-03+0ff2a83e9 for .NET
dotnet/sdk/8.0.100-preview.7.23376.3

### What did you do?

I added `<TargetFrameworks>net6.0;net8.0</TargetFrameworks>` to the .csproj and then I could not build the project then.

It needs to be `<TargetFrameworks></TargetFrameworks>` or no TargetFrameworks to make it work. I thought that `<TargetFrameworks>net6.0</TargetFrameworks>` would work.

### Anything else we should know about your project / environment?

My env is a mess. Building C++, C#, Py, and Ts GRPC application variants. Something could collide.

The empty Protobuf_PackagedToolsPath variable causes this issue. There is a comment `<!-- TODO(kkm): Do not use Protobuf_PackagedToolsPath, roll gRPC's own. -->` that looks suspicious. [Some issue with Protobuf_PackagedToolsPath missing](https://github.com/dotnet/vscode-csharp/issues/3313).

This is a low priority for me. Removing TargetFrameworks fixes the error.

**Comment by tonydnewell** [comment] 2023-09-12 09:19
@plachta11b I'm not sure why setting the targets would affect the setting of the property `Protobuf_PackagedToolsPath`.

I don't think the information in the reference issue with OmniSharp is correct on the evaluation of the properties. While this does seem similar I think something else is happening. See https://learn.microsoft.com/en-us/visualstudio/msbuild/build-process-overview?view=vs-2022#execution-phase for how properties are evaluated when a targets is executed - the `Protobuf_PackagedToolsPath` should have been set before the targets are executed.

I see you are using a preview version of MSBuild. Have you tried with a released version?

How are you running MSBuild (from command line, from another tool, etc)?

Are you able to provide a small and complete example - e.g. a minimal .csproj ?

**Comment by tonydnewell** [comment] 2023-09-12 10:10
I'm unable to reproduce this issue.

Project file:
```XML
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFrameworks>net6.0;net8.0</TargetFrameworks>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Google.Protobuf" Version="3.23.0" />
    <PackageReference Include="Grpc" Version="2.46.6" />
    <PackageReference Include="Grpc.Tools" Version="2.58.0" PrivateAssets="All" />
  </ItemGroup>

  <ItemGroup>
    <Protobuf Include="greet.proto" />
  </ItemGroup>

</Project>
```

Building:
```bash
dotnet-install) tony@grpc-ub20-04:~/work/is34306$ dotnet --list-sdks
6.0.413 [/home/tony/.dotnet/sdk]
7.0.400 [/home/tony/.dotnet/sdk]
8.0.100-preview.7.23376.3 [/home/tony/.dotnet/sdk]
(dotnet-install) tony@grpc-ub20-04:~/work/is34306$ dotnet build
MSBuild version 17.8.0-preview-23367-03+0ff2a83e9 for .NET
  Determining projects to restore...
  All projects are up-to-date for restore.
/home/tony/.dotnet/sdk/8.0.100-preview.7.23376.3/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.RuntimeIdentifierInference.targets(314,5): message NETSDK1057: You are using a preview version of .NET. See: https://aka.ms/dotnet-support-policy [/home/tony/work/is34306/is34306.csproj::TargetFramework=net6.0]
/home/tony/.dotnet/sdk/8.0.100-preview.7.23376.3/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.RuntimeIdentifierInference.targets(314,5): message NETSDK1057: You are using a preview version of .NET. See: https://aka.ms/dotnet-support-policy [/home/tony/work/is34306/is34306.csproj::TargetFramework=net8.0]
  is34306 -> /home/tony/work/is34306/bin/Debug/net8.0/is34306.dll
  is34306 -> /home/tony/work/is34306/bin/Debug/net6.0/is34306.dll

Build succeeded.
    0 Warning(s)
    0 Error(s)

```

**Comment by plachta11b** [comment] 2023-09-12 13:27
Hi @tonydnewell, thank you for looking into this. I am able to compile your project file. The line I had to add to reproduce the error was `<TargetFramework>net6.0</TargetFramework>`. I had both <TargetFrameworks>net6.0;net8.0</TargetFrameworks> and <TargetFramework>net6.0</TargetFramework> as the default option that was causing this. There needs to be both `TargetFrameworks` and `TargetFramework` to reproduce the error.

Using just `dotnet build` command from the terminal that runs MSBuild in the background.

**Comment by plachta11b** [comment] 2023-09-13 06:14
I was using `<TargetFramework>` to set the default framework for the dotnet run command. Now I will have to use `--framework` flag or replace TargetFramework in ci/cd for all project files during build/publish as a dirty workaround. Still not sure what is the root cause, but if it is an MSBuild issue, then I am for issue closure in the hope that no one else will encounter this.

**Comment by tonydnewell** [comment] 2023-09-13 08:54
I've opened an issue with MSBuild: https://github.com/dotnet/msbuild/issues/9216

**Comment by tonydnewell** [comment] 2023-09-13 10:06
@plachta11b I still don't understand why you've got both `<TargetFramework>` and `<TargetFrameworks>`. You should only have one. Even if there wasn't a bug and the documentation was correct then `<TargetFrameworks>` would be ignored anyway:

> Use the TargetFrameworks property when you want your app to target multiple platforms. For a list of valid target framework monikers, see [Target frameworks in SDK-style projects](https://learn.microsoft.com/en-us/dotnet/standard/frameworks#supported-target-frameworks).
> **Note:  This property is ignored if TargetFramework (singular) is specified.**

**Comment by plachta11b** [comment] 2023-09-13 10:36
@tonydnewell dotnet cli tool doesn't select framework automatically. There needs to be a framework specified before app execution (could be done with `--framework` flag). It is a small issue. I reported this issue mainly because I lost some time debugging the error `The specified task executable location "/linux_x64/protoc" is invalid.` for which I didn't see any link to the framework option at that time.

**Comment by apolcyn** [comment] 2023-11-08 16:22
Closing since this is not a Grpc.Tools issue

**Closed by apolcyn** 2023-11-08 16:22 UTC
Labels: kind/bug, lang/C#, priority/P2
