### ISSUE TITLE
C# client throws StatusCode=Unknown Detail="Stream removed"

### ISSUE THREAD

**Issue by wanton7** [grpc/grpc#15623] opened 2018-06-02 11:56 UTC
### What version of gRPC and what language are you using?
 1.12 C# both client and server
 
### What operating system (Linux, Windows, …) and version?
 Windows Server 2014
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
 C# .Net Framework 4.7.2
  
### What did you expect to see?
 
Not crashing with Grpc.Core.RpcException
 
### What did you see instead?

``` 
Type:
Grpc.Core.RpcException

Message:
Status(StatusCode=Unknown, Detail="Stream removed")

StackTrace:
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Grpc.Core.Internal.AsyncCall`2.UnaryCall(TRequest msg)
   at Grpc.Core.DefaultCallInvoker.BlockingUnaryCall[TRequest,TResponse](Method`2 method, String host, CallOptions options, TRequest request)
   at Grpc.Core.Interceptors.InterceptingCallInvoker.<BlockingUnaryCall>b__3_0[TRequest,TResponse](TRequest req, ClientInterceptorContext`2 ctx)
   at Grpc.Core.ClientBase.ClientBaseConfiguration.ClientBaseConfigurationInterceptor.BlockingUnaryCall[TRequest,TResponse](TRequest request, ClientInterceptorContext`2 context, BlockingUnaryCallContinuation`2 continuation)
   at Grpc.Core.Interceptors.InterceptingCallInvoker.BlockingUnaryCall[TRequest,TResponse](Method`2 method, String host, CallOptions options, TRequest request)
   at Removed.Rpc.FileServer.FileServerClient.DirectoryCreate(DirectoryCreateRequest request, CallOptions options)
```

### Anything else we should know about your project / environment?

We created file server with gRPC and are getting these errors. This error might happen because there is a firewall between client and server. I think it will disconnect connection after it has been idle for a while and then first call from client to server will throw this exception client side. First call to gRPC in the morning is the one that fails. No errors are logged in server side. Second call works.

We are using ChannelCredentials.Insecure.

Is there some sort of retry system in gRPC that we could use to fix this problem?

**Comment by amitwaisel** [comment] 2018-06-03 10:02
Maybe related to #15506 ?

**Comment by jtattermusch** [comment] 2018-06-04 13:32
We are working on adding a built-in retry support for the grpc stack (if configured properly, your calls will get automatically retried by grpc library if they fail with a retriable status).  @markdroth   what is the status of the retry support?

Alternatively, you can implement the retry support yourself in your client code.

**Comment by wanton7** [comment] 2018-06-05 06:21
@jtattermusch if I would do retry myself can I do it in single place or do I have to wrap every call I make with try/catch?

**Comment by Ezra5** [comment] 2018-06-05 11:04
I am also having this issue, although I get it 100% of the time. I'm redoing the project from scratch to see if it's easily reproduced.
This is on Windows 10, also with ChannelCredentials.Insecure,

**Comment by markdroth** [comment] 2018-06-05 15:08
The core of the retry functionality is implemented, but there are still some problems with it, and we've had to put the remainder of that work on the back burner temporarily due to other priorities.  I would suggest not relying on it until we have time to finish the work.

**Comment by wanton7** [comment] 2018-06-05 15:36
Btw why does disconnected connection give StatusCode.Unknown and not something like StatusCode.Unavailable?

If I only want to retry "Stream removed" (try/catch) is it safe to rely on that "Stream removed" text?

**Comment by shlomiw** [comment] 2018-06-11 06:50
Hi, we also started to get these errors in the last few days.
We're using Spanner and sometimes queries gets these RpcException "Stream removed" errors. 
Please advise, thanks.

**Comment by mehrdada** [comment] 2018-06-11 17:23
For the record, we have seen this reports of this on the Python side as well which I originally attributed to retries but I have some doubts that this might be an additional bug. It'd be great for someone from core who knows the expected semantics as implemented today should weigh in (I had expected UNAVAILABLE, as opposed to other status codes, UNKNOWN in the following case, for the expected failure case): https://stackoverflow.com/questions/50689396/grpc-python-how-to-add-idle-time-for-client

**Comment by Wisgary** [comment] 2018-06-19 00:11
Side question, will this retry layer handle "GOAWAY received" errors?

**Comment by Wisgary** [comment] 2018-06-19 17:42
@jtattermusch 

Hi Jan!
You mentioned building a retry interceptor. I was trying to make one but hit a snag. Trying to mark the AsyncUnaryCall interceptor override as async (so I can await the call and catch resulting errors) seems like it should work because AsyncUnaryCall implements GetAwaiter - but I get this error when building instead:

      Error	CS1983	The return type of an async method must be void, Task or Task<T>

As far as I can tell, this is because the class also needs to have an AsyncMethodBuilder specified. Is this something that just needs fixing, or is there some other way to achieve what I want via interceptors? (be able to catch the error, inspect it for retry-ableness, and retry or fail accordingly)?

And as a side question, will this future retry layer handle "GOAWAY received" errors?

**Comment by vadimi** [comment] 2018-06-19 17:51
@Wisgary this is how I'm using interceptors to retry `AsyncUnaryCall` (but also waiting on retries in grpc core):

```csharp
public override AsyncUnaryCall<TResponse> AsyncUnaryCall<TRequest, TResponse>(
    TRequest request,
    ClientInterceptorContext<TRequest, TResponse> context,
    AsyncUnaryCallContinuation<TRequest, TResponse> continuation)
{
    var retryCount = 0;

    async Task<TResponse> RetryCallback(Task<TResponse> responseTask)
    {
        var response = responseTask;
        if (!response.IsFaulted)
        {
            return response.Result;
        }

        retryCount++;

        if (retryCount == RetryCount)
        {
            return response.Result;
        }

        await Task.Delay(_retryTimeout.NextRetryTimeout).ConfigureAwait(false);
        var result = continuation(request, context).ResponseAsync.ContinueWith(RetryCallback).Unwrap();
        return result.Result;
    }

    var responseContinuation = continuation(request, context);
    var responseAsync = responseContinuation.ResponseAsync.ContinueWith(RetryCallback);

    return new AsyncUnaryCall<TResponse>(
        responseAsync.Result,
        responseContinuation.ResponseHeadersAsync,
        responseContinuation.GetStatus,
        responseContinuation.GetTrailers,
        responseContinuation.Dispose);
}
```
Hope this helps.

**Comment by Wisgary** [comment] 2018-06-19 23:06
@vadimi 

Thanks!! This helped us get something that we think seems to be working - we're still playing around with it. We made one change near the end - we replaced the responseAsync.Result call with a responseasync.Unwrap() to avoid blocking there for the result. Thanks for sharing!

**Comment by simonz130** [comment] 2018-06-22 18:42
I've also faced this exact bug. The client is xunit test written in C#, running on Windows 10. The server is .NET Core 2.0 (also C#) running in docker container based on debian distro of linux.

**Comment by srini100** [comment] 2018-06-25 18:57
@simonz130  @vadimi @Wisgary @shlomiw
Can anyone provide a simple reproduction?

**Comment by vadimi** [comment] 2018-06-25 19:09
It’s hard to provide a simple reproduction, but here is my setup. I run gRPC services in AWS and I have a Network Load Balancer (basically L4) between my client and service. NLB has 350 second IDLE timeout, right after that timeout with no active RPCs connection gets terminated by NLB and I get “Stream removed” exception. Immediate retry solves it, but it’s unclear why the error code is Unknown, but not Unavailable, so handling this retry requires some additional logic.

**Comment by simonz130** [comment] 2018-07-02 17:57
I suspect that in my case it could have been because there were two different processes listening on the same port. When killing one of the processes, things looked better.

**Comment by ricardopieper** [comment] 2018-07-03 02:28
I'm having this problem as well. Running on a docker container, the C# client throws a Stream Removed error. 

Meanwhile, the java client throws  Network closed for unknown reason. Running them locally or in different physical machines in a network runs fine, on Docker it explodes.

**Comment by tassi-yuzukko** [comment] 2018-07-20 00:37
I am having the same problem. In my case, I tried published [example written in C#](https://grpc.io/docs/quickstart/csharp.html#using-visual-studio-xamarin-studio-or-mondevelop-ides)(I cloned the repository, built `GreeterServer` and `GreeterClient` and ran them.) and then the `GreeterClient` throwed the above exception.

my environment is bellows:

* using C# 
* using Visual Studio 2017
* grpc version is 1.13.1

**Comment by Kwoth** [comment] 2018-09-23 02:51
@ricardopieper Thank you so much. That was my issue too.

**Comment by jtattermusch** [comment] 2018-10-24 09:54
Hi all, I spent some time trying to reproduce the problem without success. Additional information would be helpful from those able to reproduce:
- please include there exact exception thrown (this issue is only about "StatusCode=Unknown Detail="Stream removed")
- the flakiness rate you are observing (it looks like this is happening only occasionally)
- is your use case accessing Google APIs or are you accessing your own server (in case it's your own server, please include info about network topology, is there a proxy?). Are you using a plain gRPC library or a google api client library built on top of gRPC?
- what's your platform (it seems like this might be happening mostly with Windows 10 clients, but the data is very unclear).
- what is gRPC C# version you are using?
- when possible, please include additional trace logs (see https://github.com/grpc/grpc/blob/master/TROUBLESHOOTING.md) for instructions.

**Comment by jtattermusch** [comment] 2018-10-24 10:01
FTR, the only place in C core code where "Stream removed" error is coming from is here:
https://github.com/grpc/grpc/blob/fe431b4d8ad24c2fc9981f4b9fc28ab75020c410/src/core/ext/transport/chttp2/transport/chttp2_transport.cc#L2226

**Comment by jtattermusch** [comment] 2018-10-24 10:03
I also went through the log of recent windows unit test failures and didn't see the "Stream removed" problem anywhere.

**Comment by wanton7** [comment] 2018-10-24 10:04
I was using plain C# library for both client and server. Both client and server where running in different servers running Windows Server 2012 OS.
I can't test that server anymore, our company rewrote everything made made with gRPC to use ASP.NET Core & SignalR instead.

**Comment by veatcha** [comment] 2019-01-17 19:48
@markdroth - related to this comment above, is the retry functionality still in this same state where if we're looking for that, we should roll our own?  I looked through the release notes back to through June, and didn't see any reference to it...

> The core of the retry functionality is implemented, but there are still some problems with it, and we've had to put the remainder of that work on the back burner temporarily due to other priorities. I would suggest not relying on it until we have time to finish the work.

Thanks...

**Comment by markdroth** [comment] 2019-01-17 21:21
Yeah, no changes on the status of the retry code.  I'm hoping we can get back to it toward the end of this year, but we'll see what happens.

**Comment by Wisgary** [comment] 2019-03-21 07:49
I wanted to give a quick update, I can get these stream removed errors to happen in our environment while sending some load combined with kicking servers. It becomes especially easy to repro using one of our stress tests which is:

1 Stress client (secure credentials)
5 back-end servers
1 L4 LB in between them

May be related and perhaps even partially the cause (maybe I am doing naughty things here) that to ensure the backend machines got to spread the load I created multiple clients/channels and round robin through them internally in the test tool. I send around 2k TPS, and I start to see these errors happen whenever servers Shutdown - usually coupled with some Internal/GOAWAY RpcExceptions as well. The retry interceptor we use can catch these and make them invisible to the client, but I have seen this special one pop up from time to time when our retry interceptor tries to salvage the original call:

System.ObjectDisposedException: Safe handle has been closed
   at System.Runtime.InteropServices.SafeHandle.DangerousAddRef(Boolean& success)
   at System.StubHelpers.StubHelpers.SafeHandleAddRef(SafeHandle pHandle, Boolean& success)
   at Grpc.Core.Internal.ChannelSafeHandle.CreateCall(CallSafeHandle parentCall, ContextPropagationFlags propagationMask, CompletionQueueSafeHandle cq, String method, String host, Timespec deadline, CallCredentialsSafeHandle credentials)
   at Grpc.Core.Internal.AsyncCall`2.CreateNativeCall(CompletionQueueSafeHandle cq)
   at Grpc.Core.Internal.AsyncCall`2.Initialize(CompletionQueueSafeHandle cq)
   at Grpc.Core.Internal.AsyncCall`2.UnaryCallAsync(TRequest msg)
   at Grpc.Core.Calls.AsyncUnaryCall[TRequest,TResponse](CallInvocationDetails`2 call, TRequest req)
   at Grpc.Core.DefaultCallInvoker.AsyncUnaryCall[TRequest,TResponse](Method`2 method, String host, CallOptions options, TRequest request)
   at Grpc.Core.Interceptors.InterceptingCallInvoker.<AsyncUnaryCall>b__4_0[TRequest,TResponse](TRequest req, ClientInterceptorContext`2 ctx)
   at [Snip].RetryInterceptor.<>c__DisplayClass14_0`2.<AsyncUnaryCall>b__1(Task _) in RetryInterceptor.cs:line 78

**Comment by srajkovic** [comment] 2019-05-09 18:33
We're seeing this issue as well, when making requests against the Google PubSub API. Particularly seeing it on calling SubscriberServiceApiClient.CreateSubscriptionAsync. We were not seeing it prior to upgrading to Grpc.Core 1.13.1 and Google.Cloud.PubSub.V1 1.0.0 from 1.41 and 1.0.0-beta12 respectively.

**Comment by jtattermusch** [comment] 2019-05-15 12:59
> We're seeing this issue as well, when making requests against the Google PubSub API. Particularly seeing it on calling SubscriberServiceApiClient.CreateSubscriptionAsync. We were not seeing it prior to upgrading to Grpc.Core 1.13.1 and Google.Cloud.PubSub.V1 1.0.0 from 1.41 and 1.0.0-beta12 respectively.

@srajkovic  the comment thread for this issue is becoming very long, so it's not fully clear what you're referring to as "this issue". Can you provide more info about your setup (platform, etc.), additional logs and describe the pattern that you're seeing in detail. Any useful information in the logs? An ability to reproduce reliably would be super helpful as so far we don't really have much to work with to be able to debug and rootcause this problem.

**Comment by jtattermusch** [comment] 2019-05-15 13:04
> I wanted to give a quick update, I can get these stream removed errors to happen in our environment while sending some load combined with kicking servers. It becomes especially easy to repro using one of our stress tests which is:
> 
> 1 Stress client (secure credentials)
> 5 back-end servers
> 1 L4 LB in between them
> 
> May be related and perhaps even partially the cause (maybe I am doing naughty things here) that to ensure the backend machines got to spread the load I created multiple clients/channels and round robin through them internally in the test tool. I send around 2k TPS, and I start to see these errors happen whenever servers Shutdown - usually coupled with some Internal/GOAWAY RpcExceptions as well. The retry interceptor we use can catch these and make them invisible to the client, but I have seen this special one pop up from time to time when our retry interceptor tries to salvage the original call:
> 
> ```
> System.ObjectDisposedException: Safe handle has been closed
>    at System.Runtime.InteropServices.SafeHandle.DangerousAddRef(Boolean& success)
>    at System.StubHelpers.StubHelpers.SafeHandleAddRef(SafeHandle pHandle, Boolean& success)
>    at Grpc.Core.Internal.ChannelSafeHandle.CreateCall(CallSafeHandle parentCall, ContextPropagationFlags propagationMask, CompletionQueueSafeHandle cq, String method, String host, Timespec deadline, CallCredentialsSafeHandle credentials)
>    at Grpc.Core.Internal.AsyncCall`2.CreateNativeCall(CompletionQueueSafeHandle cq)
>    at Grpc.Core.Internal.AsyncCall`2.Initialize(CompletionQueueSafeHandle cq)
>    at Grpc.Core.Internal.AsyncCall`2.UnaryCallAsync(TRequest msg)
>    at Grpc.Core.Calls.AsyncUnaryCall[TRequest,TResponse](CallInvocationDetails`2 call, TRequest req)
>    at Grpc.Core.DefaultCallInvoker.AsyncUnaryCall[TRequest,TResponse](Method`2 method, String host, CallOptions options, TRequest request)
>    at Grpc.Core.Interceptors.InterceptingCallInvoker.<AsyncUnaryCall>b__4_0[TRequest,TResponse](TRequest req, ClientInterceptorContext`2 ctx)
>    at [Snip].RetryInterceptor.<>c__DisplayClass14_0`2.<AsyncUnaryCall>b__1(Task _) in RetryInterceptor.cs:line 78
> ```
> 
> Both my client and server are C#, running on Windows 10, 1.18 but we'll try 1.19 soon.

I believe what you're seeing might be a different problem than what others are reporting - the original one seems to be connected to serving google apis.
I don't quite understand what your setup does from the description, but the stack trace you posted seems to indicate that are trying to start a call on a channel that's already been disposed.
It's not clear what you mean by "shutting down servers"? do you use ShutdownAsync() or KillAsync()?

**Comment by srajkovic** [comment] 2019-05-15 17:06
### What version of gRPC and what language are you using?
1.13.1 C# client

### What operating system (Linux, Windows, …) and version?
Windows Server 2016

### What runtime / compiler are you using (e.g. python version or version of gcc)
C# .Net Framework 4.6.2

### What did you expect to see?
Not crashing with Grpc.Core.RpcException

### What did you see instead?
Type:
Grpc.Core.RpcException

Message:
Status(StatusCode=Unknown, Detail="Stream removed")

StackTrace:
```
Grpc.Core.RpcException: Status(StatusCode=Unknown, Detail="Stream removed")
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.
   at Google.Api.Gax.Grpc.ApiCallRetryExtensions.<>c__DisplayClass0_0`2.<<WithRetry>b__0>d.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at <call site of SubscriberServiceApiClient.CreateSubscriptionAsync in our code>
```

### Anything else we should know about your project / environment?
We are using Google Cloud PubSub and trying to pull messages from there. I don't have any more really helpful logs besides the timestamps since I can't reproduce it locally. It only happens once per thousands of attempts. I can give you those if they'd help you/the team that owns the public PubSub infra to root cause.

**Comment by srajkovic** [comment] 2019-05-23 19:44
We saw this over 120 times today so far, the most we've seen of any day since updating to 1.13.1. Any thoughts?

**Comment by jtattermusch** [comment] 2019-05-24 07:43
@srajkovic 
Unrelated to the problem but you should be using a more recent version of gRPC - 1.13.1 is pretty old.

Can you provide the response headers you received from pubsub? There might be some info that's useful for debugging.
Since you cannot reproduce locally, can you create an example project that reproduces the problem when ran against cloud pubsub? I'm afraid without a reproduction or some extra details we can't really do much.

**Comment by thomashahn2019** [comment] 2019-05-24 10:09
We have this problem as well a lot in the last time

**Comment by aaronhudon-ts** [comment] 2019-05-24 16:06
@thomashahn2019 I've encountered the behavior in C# using v1.20.1 
To work around the issue, catch `RpcException` when calling `MoveNext`, and then re-create the stream request.

**Comment by srajkovic** [comment] 2019-05-29 19:15
We're using 1.13.1 because that's what is being used by PubSub 1.0.0.0, we didn't pick that version.

How would I get the response headers? Are they part of `RpcException.Trailers`? Any particular way of filtering that list that would get you the most potentially helpful data? 

I'll see what I can do about getting a repro, but not sure what's actually causing it. Most I can try is just to see if I can get it from repeatedly calling that endpoint.

**Comment by jtattermusch** [comment] 2019-06-24 12:18
@srajkovic  https://www.nuget.org/packages/Google.Cloud.PubSub.V1/1.0.0 depends on grpc >=1.13.1, can you update gRPC to the latest stable and see if you still reproduce.

Because I don't know what the problem is yet and I am unable to reproduce, it's hard for me to tell which logs would be helpful. But trying a few different traces from https://github.com/grpc/grpc/blob/master/TROUBLESHOOTING.md and seeing if they contain something interesting (compared to the case where the call passes)

**Comment by jtattermusch** [comment] 2019-06-24 12:29
Looks like more users have reported a similar issue, but I'm not sure if what they are experiencing is actually the same problem or not. In the meantime, I wasn't able to reproduce nor I was able to determine which setup I have to try to actually be able to reproduce (different users are reporting different things).
To be able to solve this problem, I'll need either a reproduction (=code) with very detailed instructions about how to setup the scenario that fails (OS, platform, flakiness rate, grpc version range where this happens etc., see https://github.com/grpc/grpc/issues/15623#issuecomment-432592307)
or detailed logs (see https://github.com/grpc/grpc/blob/master/TROUBLESHOOTING.md) that can point me in the right direction. Without these, I can't really do much here.

**Comment by PavelPZ** [comment] 2019-08-04 12:17
I created 20-lines-of-code-repository on https://github.com/PavelPZ/GrcpError, using **Microsoft.NETCore.App 3.0.0-preview7-27912-14**

Can you reproduce it?

Running on:
```
Microsoft Visual Studio Community 2019 Preview
Version 16.3.0 Preview 1.0
VisualStudio.16.Preview/16.3.0-pre.1.0+29123.89
Microsoft .NET Framework
Version 4.7.03056

Installed Version: Community

Application Insights Tools for Visual Studio Package   9.1.00611.1
Application Insights Tools for Visual Studio

ASP.NET and Web Tools 2019   16.3.34.53219
ASP.NET and Web Tools 2019

ASP.NET Web Frameworks and Tools 2019   16.3.34.53219
For additional information, visit https://www.asp.net/

Azure App Service Tools v3.0.0   16.3.34.53219
Azure App Service Tools v3.0.0

Azure Functions and Web Jobs Tools   16.3.34.53219
Azure Functions and Web Jobs Tools

C# Tools   3.3.0-beta1-19360-03+7d47461d2ddd32defbc51c2cf0e75a3fef16c3d7
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

IntelliCode Extension   1.0
IntelliCode Visual Studio Extension Detailed Info

Microsoft Azure Tools   2.9
Microsoft Azure Tools for Microsoft Visual Studio 0x10 - v2.9.20626.2

Microsoft Continuous Delivery Tools for Visual Studio   0.4
Simplifying the configuration of Azure DevOps pipelines from within the Visual Studio IDE.

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft Library Manager   1.0
Install client-side libraries easily to any web project

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Microsoft Visual Studio Tools for Containers   1.1
Develop, run, validate your ASP.NET Core applications in the target environment. F5 your application directly into a container with debugging, or CTRL + F5 to edit & refresh your app without having to rebuild the container.

NuGet Package Manager   5.2.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/

ProjectServicesPackage Extension   1.0
ProjectServicesPackage Visual Studio Extension Detailed Info

ResourcePackage Extension   1.0
ResourcePackage Visual Studio Extension Detailed Info

ResourcePackage Extension   1.0
ResourcePackage Visual Studio Extension Detailed Info

SQL Server Data Tools   16.0.61906.28070
Microsoft SQL Server Data Tools

TypeScript Tools   16.0.10627.2001
TypeScript Tools for Microsoft Visual Studio

Visual Basic Tools   3.3.0-beta1-19360-03+7d47461d2ddd32defbc51c2cf0e75a3fef16c3d7
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual F# Tools 10.4 for F# 4.6   16.3.0-beta.19321.6+5289eb027336eb4c1ea70eaff246f42ca5584b4d
Microsoft Visual F# Tools 10.4 for F# 4.6

Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

Visual Studio Tools for Containers   1.0
Visual Studio Tools for Containers
```

**Comment by PavelPZ** [comment] 2019-08-04 16:49
gRpc server in example above sends similar error when using DART client:
```
    final channel= grpc.ClientChannel('localhost', port: 5001, 
        options: grpc.ChannelOptions(credentials: grpc.ChannelCredentials.insecure()));
    final cl = utils.GreeterClient(channel);
    var resp = await cl.sayHello(utils.HelloRequest()..name = 'Name from client');
```
with error: **gRPC Error (2, HTTP/2 error: Connection error: Connection is being forcefully terminated. (errorCode: 10))**

**Comment by dingzeng** [comment] 2019-08-31 14:03
**What version of gRPC and what language are you using?**
DotnetCore Client
```
<PackageReference Include="Google.Protobuf" Version="3.9.1" />
<PackageReference Include="Grpc" Version="2.23.0" />
<PackageReference Include="Grpc.Tools" Version="2.23.0">
```
DotnetCore Server
```
<PackageReference Include="Grpc.AspNetCore" Version="0.1.22-pre3" />
```

**What operating system (Linux, Windows, …) and version?**
Windows 10

**What runtime / compiler are you using (e.g. python version or version of gcc)**
C# dotnetcore

**What did you expect to see?**
Not crashing with Grpc.Core.RpcException

**What did you see instead?**
Status(StatusCode=Unknown, Detail="Stream removed")

**Anything else we should know about your project / environment?**
It's all here：[https://github.com/dingzeng/AspnetcoreGrpcDemo/tree/stream_removed](https://github.com/dingzeng/AspnetcoreGrpcDemo/tree/stream_removed)

**Comment by panoti** [comment] 2019-09-21 20:45
I think this error is the same as #708

**Comment by anand-raju** [comment] 2019-10-14 18:15
> The core of the retry functionality is implemented, but there are still some problems with it, and we've had to put the remainder of that work on the back burner temporarily due to other priorities. I would suggest not relying on it until we have time to finish the work.

@markdroth :  Is this work finished? 
I was running some tests with Grpc.Core v2.23.0 C# library. The stream removed exception would happen when the client uses a channel with a stream that isn't usable anymore. I noticed that just retrying using the same channel resulted in a successful gRPC call. So it looks like the library has in-built reconnect logic but not retry. Although I couldn't trace the source code for this.

**Comment by markdroth** [comment] 2019-10-15 14:23
No, the retry functionality in C-core is not yet complete.  Unfortunately, we don't yet have an ETA for it, since we've been pulled off onto some other priorities.

**Comment by jtattermusch** [comment] 2019-11-12 09:00
Looks like we don't have a useful reproduction for this problem and there's mixed/incomplete information about how and when the issue is happening. See context https://github.com/grpc/grpc/issues/15623#issuecomment-504988666

I'm going to close this issue as not actionable, but I'm happy to reopen as soon as someone provides a reproduction I can work with.

**Closed by jtattermusch** 2019-11-12 09:00 UTC
Labels: kind/enhancement, lang/C#, priority/P2

**Comment by ahmedalejo** [comment] 2019-11-26 01:15
> I was having the same problem. In my case my server was listening to localhost instead of 0.0.0.0. Not really related to this issue I think.
@ricardopieper thanks this was my issue, it wasn´t that intuitive.

I hosted the service via the gRPC server, which worked
```csharp
const string Host = "0.0.0.0";
const int Port = 5001;

var server = new Server
{
    Services = { Contracts.MathServer.BindService(new MathServer()) },
    Ports = { { Host, Port, ServerCredentials.Insecure } }
};
server.Start();

Console.WriteLine("MathServer listening on port " + Port);

Console.WriteLine("Press any key to stop the server...");
Console.ReadKey();

server.ShutdownAsync().Wait();
```
Then tried hosting in ASP.NET Core on .NET 3.0 which also worked.

```csharp
.UseKestrel(c => c.ListenAnyIP(5001))
```
Hosting with gRPC server(no logging, no authentication, no interceptors) had round trip times below a 300 nanosecond, while and using ASP.NET Core hosting(logging, DI, middle-ware, no registered controllers e.t.c) had lowest round trip time of 6 milliseconds.

**Comment by Sket4** [comment] 2019-12-01 07:15
In my case the error was fixed after changing the port. For some reason, another app was listening on the same port, but in IPv4 instead of IPv6:
![image](https://user-images.githubusercontent.com/1878560/69910835-f203cb80-1422-11ea-9b17-f964ee774de0.png)
