### ISSUE TITLE
gRPC Python 1.8.2 Library incompatibility with fork()

### ISSUE THREAD

**Issue by zunger-humu** [grpc/grpc#13873] opened 2017-12-22 22:49 UTC
This bug is essentially the same as the previously-closed [bug 12455](https://github.com/grpc/grpc/issues/12455). That bug was closed because it was fixed in 1.7.0... except we now have at least two ways to repro it in 1.8.2. :(

Basic summary of the bug: If a gRPC channel is (1) used at least once and (2) still in scope when you call fork(), and the subprocess tries to open a gRPC channel as well, then all RPC's on that channel will hang. Apparently, some global state is leaking across fork() boundaries in a bad way.

### What version of gRPC and what language are you using?
 
gRPC 1.8.2, Python 3.6
 
### What operating system (Linux, Windows, …) and version?
 
Repro'ed on OS X 10.13.2
 
### What runtime / compiler are you using (e.g. python version or version of gcc)

Python 3.6.2
 
### What did you do?

Here is a minimal repro using the GCP datastore client:

```
import multiprocessing

from google.cloud import datastore


def causeTrouble(where: str):
    client = datastore.Client(project='dev-storage-humu', namespace='aquarium')
    client.get(client.key('c', 'aquarium'))
    # The call to get() hangs forever; this line is never reached.
    print('OK')


if __name__ == '__main__':
    # Create a datastore client and do an RPC on it.
    client = datastore.Client(project='dev-storage-humu', namespace='aquarium')
    client.get(client.key('c', 'aquarium'))

    # Kick off a child process while the first client is still in scope.
    process = multiprocessing.Process(target=causeTrouble,
                                      args=['child process'])
    process.start()
```

- If you change this so that it doesn't call client.get() from main, just creating the client and then forking, it works fine.
- If you change this so that instead of creating the client and calling client.get() directly, it calls causeTrouble() before forking, it also works fine. (NB that Python has eager GC, so the difference between the two is that the client is no longer in scope if you do it this other way)
- In another server, I worked around this by calling subprocess.run() instead of multiprocessing.Process(); since subprocess() does a fork() + exec(), it has no state surviving across the process boundary. However, the call to exec() strictly limits the communication with the parent process, basically making all of the multiprocessing library unusable.

If you kill it while it's hanging, you get this stack trace:

```
Traceback (most recent call last):
  File "/Users/zunger/.pyenv/versions/3.6.2/lib/python3.6/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/Users/zunger/.pyenv/versions/3.6.2/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "minimal_repro.py", line 8, in causeTrouble
    client.get(client.key('c', 'aquarium'))
  File "/Users/zunger/src/humu/servers/squeegee/server/.build/venv/lib/python3.6/site-packages/google/cloud/datastore/client.py", line 309, in get
    deferred=deferred, transaction=transaction)
  File "/Users/zunger/src/humu/servers/squeegee/server/.build/venv/lib/python3.6/site-packages/google/cloud/datastore/client.py", line 356, in get_multi
    transaction_id=transaction and transaction.id,
  File "/Users/zunger/src/humu/servers/squeegee/server/.build/venv/lib/python3.6/site-packages/google/cloud/datastore/client.py", line 138, in _extended_lookup
    project, read_options, key_pbs)
  File "/Users/zunger/src/humu/servers/squeegee/server/.build/venv/lib/python3.6/site-packages/google/cloud/datastore/_gax.py", line 115, in lookup
    return super(GAPICDatastoreAPI, self).lookup(*args, **kwargs)
  File "/Users/zunger/src/humu/servers/squeegee/server/.build/venv/lib/python3.6/site-packages/google/cloud/gapic/datastore/v1/datastore_client.py", line 204, in lookup
    return self._lookup(request, options)
  File "/Users/zunger/src/humu/servers/squeegee/server/.build/venv/lib/python3.6/site-packages/google/gax/api_callable.py", line 452, in inner
    return api_caller(api_call, this_settings, request)
  File "/Users/zunger/src/humu/servers/squeegee/server/.build/venv/lib/python3.6/site-packages/google/gax/api_callable.py", line 438, in base_caller
    return api_call(*args)
  File "/Users/zunger/src/humu/servers/squeegee/server/.build/venv/lib/python3.6/site-packages/google/gax/api_callable.py", line 376, in inner
    return a_func(*args, **kwargs)
  File "/Users/zunger/src/humu/servers/squeegee/server/.build/venv/lib/python3.6/site-packages/google/gax/retry.py", line 121, in inner
    return to_call(*args)
  File "/Users/zunger/src/humu/servers/squeegee/server/.build/venv/lib/python3.6/site-packages/google/gax/retry.py", line 68, in inner
    return a_func(*updated_args, **kwargs)
  File "/Users/zunger/src/humu/servers/squeegee/server/.build/venv/lib/python3.6/site-packages/grpc/_channel.py", line 484, in __call__
    credentials)
  File "/Users/zunger/src/humu/servers/squeegee/server/.build/venv/lib/python3.6/site-packages/grpc/_channel.py", line 478, in _blocking
    _handle_event(completion_queue.poll(), state,
  File "src/python/grpcio/grpc/_cython/_cygrpc/completion_queue.pyx.pxi", line 100, in grpc._cython.cygrpc.CompletionQueue.poll
```

On b/12455, @katbusch reported that simply _importing_ certain libraries prior to fork (e.g. `from google.cloud import bigquery`) was sufficient to trigger this bug. Presumably they do enough initialization on import to trigger this.

That makes workarounds where we pre-fork a pile of worker processes and pass them jobs as needed more difficult, although possible as a short-term measure.
 
### Anything else we should know about your project / environment?

The use case which necessitates this is that we have a server (which uses GCP features extensively, e.g. for storage) that needs to fork off subprocesses in which to run long-running operations. (It's basically an analysis pipeline manager) Since Python is heavily reliant on fork() for parallelization (thanks to the GIL there's no real 'parallelism' in its threading) this is the main approach possible.

**Comment by zunger-humu** [comment] 2017-12-24 01:47
Pinging @ctiller per his remark on Twitter.

Also recognizing that this is almost certainly a huge PITA to fix, because threads and fork() don't really play well together. Unfortunately, Python's menu of options for parallelism is very small: threads don't really do the right thing in CPython, multiprocessing brings in all these fun fork() issues, and subprocess fork()+exec()'s which means API's are fundamentally nasty and slow. Sigh. I'm working on libraries to at least somewhat mitigate the latter now...

**Comment by ctiller** [comment] 2017-12-24 02:10
I'll try the experiment next week if nobody gets there first, but my gut feeling on this (given everything @zunger-humu has mentioned) is that we could just replace the subchannel index AVL at fork time and be good here. It's the one place I can think of (tonight at least) where we carry global state across forks in a way that would cause this.

The real problem is likely somewhere else, and we should study and understand that at some.point also.

**Comment by leonshaw** [comment] 2017-12-30 05:36
Had similar issue on the server side. When I call os.fork() in the working thread, the child process would hang and never return from os.fork().
I did some debug. It shows that in cpython posix implementation of os.fork(), it calls PyOS_AfterFork, where local objects of other threads gets GC-ed since there's only one thread (the current one) after fork. When the grpc server object in main thread is being deleted, it trys to stop itself, and stuck in a call to shutdown_event.wait().
I worked around this using subprocess.Popen instead of os.fork+exec, where the fork+exec is completed in C and no GC is needed, given preexec_fn is None.
I wonder if grpc server could check current thread ID to determine if it really need to stop gracefully on deletion.

**Comment by leonshaw** [comment] 2017-12-30 06:02
oops, not sure if my issue is related to this. If not, I'll open a new one.

**Comment by explicitcall** [comment] 2018-01-14 15:16
reproducible for me with grpc 1.8.4 and Python 3.6.4

**Comment by kpayson64** [comment] 2018-01-17 22:51
To summarize the issue described here:  Creating an RPC channel and then forking will not work.  This is a known limitation, and while we would like to support this use case, there are no immediate plans to support this behavior.

Closing this issue as there are no immediate plans to support this.

**Comment by zunger-humu** [comment] 2018-01-17 22:57
Notes for people who come across this bug in the future:

  - If you create an RPC channel, then fork, uses of that channel in the child process will likely hang. This includes spawning any processes with the multiprocessing library.
  - If you create an RPC channel, fork, and exec, then everything is OK. This includes spawning processes with the subprocess library.
  - If you need to use the multiprocessing library, consider creating a set of worker threads before setting up any RPC channels.

**Comment by jboning** [comment] 2018-01-18 21:50
> If you create an RPC channel, fork, and exec, then everything is OK. This includes spawning processes with the subprocess library.

This turns out not to be true; the fork/exec might work or fail nondeterministically. See #13998.

**Comment by explicitcall** [comment] 2018-01-18 22:16
I hope this is fixed soon, not supporting multiprocessing in Python bindings makes gRPC (and Google Cloud SDK, which relies on it) basically useless in Python. Multi-core processing is required for a lot of data and CPU-intensive algorithms, e.g. machine learning. A lot of widely used libraries (SciKit-Learn, pandas) don't release GIL, which makes fork/exec/multiprocessing the only option. @kpayson64 please consider reopening the issue. Thanks.

**Comment by aamitdb** [comment] 2018-01-19 23:33
> If you create an RPC channel, fork, and exec, then everything is OK. This includes spawning processes with the subprocess library.

```
"""The Python implementation of the GRPC helloworld.Greeter client."""

from __future__ import print_function

import grpc
import subprocess32
import time


def call_subproc():
  o = subprocess32.check_output(["echo", "1"])

def make_channel_with_message():
  channel = grpc.insecure_channel('localhost:50051')

if __name__ == '__main__':
  subprocess32.check_output(["echo", "Hello World!"])
  for i in range(1000000):
    call_subproc()
    make_channel_with_message()
    if i % 100 == 0:
      print(time.time())
```

Reliably segfaults the child process for me (even without a server up), so this does not seem accurate. This is only since 1.7, before that it worked.

**Comment by thomas-kiry** [comment] 2018-01-20 15:21
I hope this will be fixed soon as well. It should make things a lot easier for us. +1 for reopening this issue.

**Comment by jayantkolhe** [comment] 2018-01-25 00:15
Reopening based on these comments. We might not support fork completely, but lets investigate this further to see if we have a solution...

**Comment by mehrdada** [comment] 2018-01-25 01:20
Related: https://github.com/grpc/grpc/issues/14055

**Comment by remram44** [comment] 2018-01-26 17:39
I am running into this without any gRPC code in the subprocess, without any Google APIs in either process. I am using a ton of scipy/ML packages so this might be hard to pinpoint, but the issue is definitely not limited to people using gRPC across fork.

**Comment by dvaldivia** [comment] 2018-02-05 23:08
A workaround for those in need might be to downgrade to `grpcio==1.4.0` , however it'd be nice if this is fixed in newer versions as well

**Comment by dvaldivia** [comment] 2018-02-05 23:20
I found another work around with `grpcio==1.8.1` you can set the flag `GRPC_ENABLE_FORK_SUPPORT` to `true` and it will work

**Comment by remram44** [comment] 2018-02-05 23:23
Oh my god what is this nonsense

Where is this documented?

Does the environment variable work with other versions or only `1.8.1`?

**Comment by dvaldivia** [comment] 2018-02-06 20:12
@remram44 I tried `1.8.2` and `1.9.0` without success, also it seems like this problem only happens on `macOS` not on `Linux`

**Comment by martin-xia** [comment] 2018-02-21 20:56
I had the same issue, i had to downgrade to 1.8.1 and set the flag @dvaldivia put

**Comment by evanj** [comment] 2018-03-12 18:08
I ran into a new variant of this that I haven't seen until we updated to grpc 1.10: occasionally a subprocess will log the following error to stderr, which is problematic since I'm using fork+exec to capture stdout and stderr from a subprocess, and this message pollutes the output. I suspect this is because I am calling `subprocess.Popen` with `close_fds=True`, so before calling `exec()` it attempts to close everything except stdin, stderr, stdout. I bet the grpc post-fork handler in the child starts some thread which is unhappy when its epoll descriptor is closed.

Setting the environment variable `GRPC_ENABLE_FORK_SUPPORT=false` seems to make this go away. At least previously it was reproducible within about ~5 forks, and I just ran it for 100 times and did not see it. I may attempt to create a "subprocess proxy" to avoid the need for setting this variable ...

The error I see is:

```
E0312 17:48:23.712781235    1283 backup_poller.cc:122]       Run client channel backup poller: {"created":"@1520876903.712729767","description":"pollset_work","file":"src/core/lib/iomgr/ev_epoll1_linux.cc","file_line":229,"referenced_errors":[{"created":"@1520876903.712726941","description":"OS Error","errno":9,"file":"src/core/lib/iomgr/ev_epoll1_linux.cc","file_line":654,"os_error":"Bad file descriptor","syscall":"epoll_wait"}]}
```

**Comment by ericgribkoff** [comment] 2018-05-18 20:43
I'm going to mark this closed, as the fixes for the use case discussed here are now in place: namely, allowing fork() iff the parent process has not yet initiated a gRPC connection (full documentation on the present state of things at https://github.com/grpc/grpc/blob/master/doc/fork_support.md). 

Let's continue to use https://github.com/grpc/grpc/issues/15334 to track adding more general fork support to gRPC.

**Closed by ericgribkoff** 2018-05-18 20:43 UTC
Labels: area/concurrency, lang/Python, priority/P2

**Comment by jeffreybrowning** [comment] 2018-10-17 23:43
v1.15.0 solves this -- updating this ticket to save other three or four clicks

**Comment by remram44** [comment] 2018-10-18 18:01
Thanks on behalf of all of us watching this ticket, that was closed back in May basically as "wontfix".

**Comment by jeffreybrowning** [comment] 2018-10-25 17:39
Including the `GRPC_ENABLE_FORK_SUPPORT` env variable in our codebase resulted in broken fork() calls for other libraries that create processes/threads (in our case, Amazon KCL's threads would not die). 

Here be dragons.

**Comment by jeffreybrowning** [comment] 2018-10-26 00:48
@ericgribkoff still diagnosing the issue, but if I get some time to suss it out I will certainly open a new issue.
