### ISSUE TITLE
C# Grpc.Tools: can't build when using xmlns import local namespace

### ISSUE THREAD

**Issue by tianvan** [grpc/grpc#18624] opened 2019-04-03 08:41 UTC
### What version of gRPC and what language are you using?

gRPC 1.19.0 
 
### What operating system (Linux, Windows,...) and version?

 Windows 10 1809
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
 
Dotnet gRPC.Tools
 
### What did you do?

In WPF project, using PackageReference manage package, add proto files, change .csproj files, anything is fine, until edit XAML, using xamlns import namespace, build failure.
 
### What did you expect to see?
 
Project build succceed
 
### What did you see instead?
 
Proto files were not compiled, resulting in project build failed.

![image](https://user-images.githubusercontent.com/10600430/55464715-4bb2bc80-562e-11e9-88d7-0257136ee511.png)

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

#### Build Succeed

```xaml
<UserControl x:Class="RealtimeImage.RealtimeImage"
             xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
             xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
             xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
             xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
             xmlns:skia="clr-namespace:SkiaSharp.Views.WPF;assembly=SkiaSharp.Views.WPF"
             mc:Ignorable="d"
             d:DesignHeight="450"
             d:DesignWidth="800">
</UserControl>
```

#### Build Failed

```xaml
<UserControl x:Class="RealtimeImage.RealtimeImage"
             xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
             xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
             xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
             xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"

             xmlns:converters="clr-namespace:RealtimeImage.Converters"

             xmlns:skia="clr-namespace:SkiaSharp.Views.WPF;assembly=SkiaSharp.Views.WPF"
             mc:Ignorable="d"
             d:DesignHeight="450"
             d:DesignWidth="800">
</UserControl>
```
 
### Anything else we should know about your project / environment?

package management style: packagereference, but my project is wpf library.

**Comment by yashykt** [comment] 2019-04-10 19:14
I did not understand the issue. I am guessing more information is required here, but I'll leave it upto @jtattermusch .

**Comment by jtattermusch** [comment] 2019-04-11 08:48
I also don't quite understand the question. But based on the error messages it looks like this isn't really related to Grpc.Tools at all.

**Comment by tianvan** [comment] 2019-04-12 07:14
> I also don't quite understand the question. But based on the error messages it looks like this isn't really related to Grpc.Tools at all.

maybe Grpc.Tools can't handle this scenario. I identified the problem by comment code line by line

**Comment by tianvan** [comment] 2019-04-12 07:54
> I also don't quite understand the question. But based on the error messages it looks like this isn't really related to Grpc.Tools at all.

I create a project, maybe can help you locate the problem [Project Link](https://github.com/tianvan/GrpcToolsBuildIssue)

**Comment by pdb2000** [comment] 2019-06-05 18:25
I had the same problem with gRPC 1.21. Any news on this?

**Comment by jtattermusch** [comment] 2019-11-12 11:07
You're trying to use Grpc.Tools in a WPF project and I think this is a dupe of https://github.com/grpc/grpc/issues/20402.

The workaround instructions are here:
https://docs.microsoft.com/en-us/aspnet/core/grpc/troubleshoot?view=aspnetcore-3.0#wpf-projects-unable-to-generate-grpc-c-assets-from-proto-files

**Closed by jtattermusch** 2019-11-12 11:07 UTC
Labels: kind/question, lang/C#, priority/P3
