### ISSUE TITLE
Grpc.Tools: Code Generation fails with VS2019 when proto files are added outside of project path

### ISSUE THREAD

**Issue by yadavvineet** [grpc/grpc#23583] opened 2020-07-23 03:24 UTC
### What version of gRPC and what language are you using?
.net core 3.1 VS 2019.

### What operating system (Linux, Windows,...) and version?
Windows 10 x64

### What runtime / compiler are you using (e.g. python version or version of gcc)
VS2019 grpc using .net core

### What did you do?

- Created a grpc project using the default template. 
- Created another proto file and moved messages in the new proto. 
- Created Server Stub. WORKS FINE
- Used Add Connected Service to generate stubs
- Tried creating client Stub. Works fine when using single non-referenced file.
- Tried creating client stub where service.proto imports messages.proto. This **fails** with error proto not found.
- Moved the protos outside of server project, one level up at solution level. 
- Tried generating stubs. Both Server and Client **fails** saying proto not found. 
- Tried importing using "**../**xyz/a.proto". That also fails.

### What did you expect to see?

- Soft links (virtual) links are added in project when adding via Add Connected Service. 
- Code should be generated for the protos as long as there relative path and import paths are correct.

### What did you see instead?

Code not generated with visual studio giving error that proto file cannot be found.
![image](https://user-images.githubusercontent.com/7949851/88249439-26820b80-ccc2-11ea-8a9f-4e8c6d6854de.png)

### Anything else we should know about your project / environment?
Copying the proto files manually in client project works fine, only in case of virtual link it gives error.

**Comment by yadavvineet** [comment] 2021-01-07 16:21
Hey Guys, any updates over here, This is very important from code re usability, considering all the proto files have to copied and cannot be reused. Problem creeps when proto needs to be updated. 

This affects the general physical design and solution structure as well. Please consider..

**Comment by jtattermusch** [comment] 2021-01-08 14:04
Can you please provide a minimal reproduction, ideally in a form of a github repository with ready-to-run code? It would make it easier for us to reproduce the issue you're experiencing.

**Comment by jtattermusch** [comment] 2021-03-18 11:46
This PR https://github.com/grpc/grpc/pull/22869 has revamped the way files outside of project path are handled as part of another fix. 
Since there is no reproduction, I'm going to assume that this problem is fixed by that PR (see that's PR thread where it mentions "ProtoRoot")

**Closed by jtattermusch** 2021-03-18 11:46 UTC
Labels: kind/bug, lang/C#, priority/P2
