### ISSUE TITLE
grpc_csharp_ext.x64.dll loading issue on Windows 10 x64 machine with VS2017 and GRPC v1.4.1

### ISSUE THREAD

**Issue by searope** [grpc/grpc#11914] opened 2017-07-22 23:54 UTC
**Error message**: Error loading native library "C:\...\WebApp\bin\grpc_csharp_ext.x64.dll"
**Stack**:    at Grpc.Core.Internal.UnmanagedLibrary..ctor(String[] libraryPathAlternatives)
   at Grpc.Core.Internal.NativeExtension.Load()
   at Grpc.Core.Internal.NativeExtension..ctor()
   at Grpc.Core.Internal.NativeExtension.Get()
   at Grpc.Core.GrpcEnvironment.GrpcNativeInit()
   at Grpc.Core.GrpcEnvironment..ctor()
   at Grpc.Core.GrpcEnvironment.AddRef()
   at Grpc.Core.Channel..ctor(String target, ChannelCredentials credentials, IEnumerable`1 options)
   at Google.Api.Gax.Grpc.ChannelPool.GetChannel(ServiceEndpoint endpoint, ChannelCredentials credentials)
   at Google.Cloud.Vision.V1.ImageAnnotatorClient.Create(ServiceEndpoint endpoint, ImageAnnotatorSettings settings)
   at WebApp.Api.UploadController.GetTags(String fullPath) in C:\...\WebApp\Api\UploadController.cs:line 52
   at WebApp.Api.UploadController.<PostFormData>d__0.MoveNext() in C:\...\WebApp\Api\UploadController.cs:line 39

**Comment by searope** [comment] 2017-07-23 00:04
This test app runs without any exceptions
`    class Program
    {
        static void Main(string[] args)
        {
            var credentials = new Grpc.Core.SslCredentials();
            var channel = new Grpc.Core.Channel("127.0.0.1:50052", credentials, new List<ChannelOption>(){new ChannelOption("one", 1)});
        }
    }
`

**Comment by searope** [comment] 2017-07-23 00:11
When I've switched from IIS to IIS Express the issue has gone. Any suggestions?

**Comment by jtattermusch** [comment] 2017-12-13 23:28
I think this is a duplicate of https://github.com/grpc/grpc/issues/12570.

**Closed by jtattermusch** 2017-12-13 23:28 UTC
Labels: lang/C#, platform/Windows
