### ISSUE TITLE
failfast for python client?

### ISSUE THREAD

**Issue by mirzazadeh** [grpc/grpc#15731] opened 2018-06-13 06:31 UTC
It seems disabling failfast for python clients is not implemented. Would be nice to have it.
As a workaround, I tried calling `channel._channel.check_connectivity_state(True)` but it is not as effective (and also it is not async).

**Comment by mehrdada** [comment] 2018-06-13 17:28
Dupe of https://github.com/grpc/grpc/issues/6770

**Comment by nathanielmanistaatgoogle** [comment] 2018-06-13 17:28
@mirzazadeh: this smells like a duplicate of [issue 6770](https://github.com/grpc/grpc/issues/6770); do you agree?

**Closed by mehrdada** 2018-06-13 17:28 UTC
Labels: kind/enhancement, lang/Python

**Comment by mirzazadeh** [comment] 2018-06-13 18:48
Yes, I agree, but IMO this is not P2. It makes grpc python client quite unreliable. Unless there is a good workaround.

**Comment by mehrdada** [comment] 2018-06-13 18:55
@mirzazadeh  Let's take the discussion to the original issue #6770. It's better to have it unified there.

I'd be interested in hearing more about your scenario in which you see gRPC Python as unreliable in comments on #6770.

While I feel your pain, as you can see in the issue tracker, we have not had *that many* requests to add this urgently in the past two years. We, being an open source project, are also be quite happy to review and accept patches if you have additional cycles and can help us out there.
