### ISSUE TITLE
Explicitly close client connection C++

### ISSUE THREAD

**Issue by pavel-odintsov** [grpc/grpc#3855] opened 2015-10-15 20:55 UTC
Hello!

I have implemented gRPC server and client.

But after client's app finished connection is not closed correctly:
```bash
netstat -apnt|grep 50051
tcp6       0      0 :::50051                :::*                    LISTEN      13563/api_server

./fastnetmon_api_client get_banlist
./fastnetmon_api_client get_banlist
./fastnetmon_api_client get_banlist

netstat -apnt|grep 50051
tcp6       0      0 :::50051                :::*                    LISTEN      14597/api_server
tcp6       0      0 127.0.0.1:51574         127.0.0.1:50051         TIME_WAIT   -               
tcp6       0      0 127.0.0.1:51576         127.0.0.1:50051         TIME_WAIT   -               
tcp6       0      0 127.0.0.1:51575         127.0.0.1:50051         TIME_WAIT   -               
```

Could I close connection to gRPC server explicitly?

Client's source code: https://github.com/pavel-odintsov/fastnetmon/blob/1fe6fbc077861de443475d0e9940a4a403d77805/src/fastnetmon_api_client.cpp

**Comment by ctiller** [comment] 2015-10-15 21:19
It's supposed to die once the stub is destroyed (and any outstanding calls
finished): my reading of your code says it's doing the right thing, so this
is a bug.

**Comment by pavel-odintsov** [comment] 2015-10-17 16:29
Thanks for attention! Waiting for fix :)

**Comment by ctiller** [comment] 2015-12-15 20:22
There have been many fixes around this lately: is it still a problem for you?

**Comment by pavel-odintsov** [comment] 2015-12-16 11:03
Hello!

I have pulled recent commit e5cdbea1530a99a95fd3d032e7d69a19c61a0d16.

And bug still reproduces:
```bash
root@filter /usr/src/gobgp/tools/grpc/cpp # LD_LIBRARY_PATH=".:/opt/grpc/lib:/opt/protobuf_3.0.0_alpha4/lib" ./gobgp_api_client
We received: Peer AS: 65001
Peer router id: 213.133.111.200
Peer flops: 0
BGP state: BGP_FSM_ESTABLISHED
root@filter /usr/src/gobgp/tools/grpc/cpp # netstat -apnt|grep 8080
tcp6       0      0 :::8080                 :::*                    LISTEN      4504/gobgpd     
tcp6       0      0 127.0.0.1:44282         127.0.0.1:8080          TIME_WAIT   -               
root@filter /usr/src/gobgp/tools/grpc/cpp # LD_LIBRARY_PATH=".:/opt/grpc/lib:/opt/protobuf_3.0.0_alpha4/lib" ./gobgp_api_client
We received: Peer AS: 65001
Peer router id: 213.133.111.200
Peer flops: 0
BGP state: BGP_FSM_ESTABLISHED
root@filter /usr/src/gobgp/tools/grpc/cpp # netstat -apnt|grep 8080
tcp6       0      0 :::8080                 :::*                    LISTEN      4504/gobgpd     
tcp6       0      0 127.0.0.1:44282         127.0.0.1:8080          TIME_WAIT   -               
tcp6       0      0 127.0.0.1:44283         127.0.0.1:8080          TIME_WAIT   -               
root@filter /usr/src/gobgp/tools/grpc/cpp # LD_LIBRARY_PATH=".:/opt/grpc/lib:/opt/protobuf_3.0.0_alpha4/lib" ./gobgp_api_client
We received: Peer AS: 65001
Peer router id: 213.133.111.200
Peer flops: 0
BGP state: BGP_FSM_ESTABLISHED
root@filter /usr/src/gobgp/tools/grpc/cpp # netstat -apnt|grep 8080
tcp6       0      0 :::8080                 :::*                    LISTEN      4504/gobgpd     
tcp6       0      0 127.0.0.1:44282         127.0.0.1:8080          TIME_WAIT   -               
tcp6       0      0 127.0.0.1:44283         127.0.0.1:8080          TIME_WAIT   -               
tcp6       0      0 127.0.0.1:44284         127.0.0.1:8080          TIME_WAIT   -               
root@filter /usr/src/gobgp/tools/grpc/cpp # LD_LIBRARY_PATH=".:/opt/grpc/lib:/opt/protobuf_3.0.0_alpha4/lib" ./gobgp_api_client
We received: Peer AS: 65001
Peer router id: 213.133.111.200
Peer flops: 0
BGP state: BGP_FSM_ESTABLISHED
root@filter /usr/src/gobgp/tools/grpc/cpp # netstat -apnt|grep 8080
tcp6       0      0 :::8080                 :::*                    LISTEN      4504/gobgpd     
tcp6       0      0 127.0.0.1:44282         127.0.0.1:8080          TIME_WAIT   -               
tcp6       0      0 127.0.0.1:44285         127.0.0.1:8080          TIME_WAIT   -               
tcp6       0      0 127.0.0.1:44283         127.0.0.1:8080          TIME_WAIT   -               
tcp6       0      0 127.0.0.1:44284         127.0.0.1:8080          TIME_WAIT   -       
```

**Comment by y-zeng** [comment] 2016-04-27 02:10
If we are talking about the state `TIME_WAIT`, I think it's not caused by an improper closing of the connection. According to [RFC 793](https://tools.ietf.org/html/rfc793#page-23), the active closer has to stay in `TIME-WAIT` for 2MSL when closing the connection. It seems a socket in `TIME-WAIT` cannot be forcibly closed.

Netcat gives the same result.

```
$ nc -l -k 50051 &
[1] 63077
$ echo "foo" | nc localhost 50051 -q 1
foo
$ echo "foo" | nc localhost 50051 -q 1
foo
$ echo "foo" | nc localhost 50051 -q 1
foo
$ netstat -apnt | grep 50051
tcp        0      0 0.0.0.0:50051           0.0.0.0:*               LISTEN      63077/nc        
tcp        0      0 127.0.0.1:57831         127.0.0.1:50051         TIME_WAIT   -               
tcp        0      0 127.0.0.1:57835         127.0.0.1:50051         TIME_WAIT   -               
tcp        0      0 127.0.0.1:57837         127.0.0.1:50051         TIME_WAIT   -  
```

Other references: [Normal Close Sequence](https://tools.ietf.org/html/rfc793#page-39) in RFC 793

**Closed** 2016-05-17 18:18 UTC
Labels: c++, P1, to close
