### ISSUE TITLE
Cocoapod [Objc]: Multiple build commands for output file atm.h

### ISSUE THREAD

**Issue by sibinlutoken** [grpc/grpc#12081] opened 2017-08-04 18:40 UTC
I have this warning when I install grpc-core in Cocoapod for Objective-C

Warning: Multiple build commands for output file /Users/sibinlu/Library/Developer/Xcode/DerivedData/TokenSdk-evedrlabtrqlplfttygtmhicvsqs/Build/Products/Debug-iphonesimulator/gRPC-Core/atm.h

I can see grpc-core.podspec include more than 1 atm.h file in different path. It could be the issue. Can some one help to fix this issue?

**Comment by thassss** [comment] 2017-08-10 21:41
I am also experiencing this issue.

**Comment by thassss** [comment] 2017-09-28 22:26
@muxi Is there any chance of fixing this? I'm still seeing this on Xcode 9 w/ High Sierra.

**Comment by muxi** [comment] 2017-09-28 22:51
We are actively working on this issue (and other warnings). ETA is around 2 weeks. Will update.

**Comment by muxi** [comment] 2017-10-04 21:49
Unfortunately it seems our effort of working around it was actually not working. The problem is due to a known issue of Cocoapods (https://github.com/CocoaPods/CocoaPods/issues/4496). We have not found another way to workaround this problem right now other than contributing to Cocoapods a fix, which would take a while. Let me know if you have any idea on a workaround or would like to help with it.

**Comment by muxi** [comment] 2017-10-12 19:23
Closing this issue as we do not have plan to contribute to Cocoapods soon. Let us know if you got an idea of workaround of this issue and we can reopen.

**Closed by muxi** 2017-10-12 19:23 UTC
Labels: lang/ObjC

**Comment by thassss** [comment] 2017-10-26 16:45
I was able to get rid of the warnings in my project by putting this post install script in my Podfile.

```
post_install do |installer|
	installer.pods_project.targets.each do |target|
		if target.name == 'gRPC-Core'
			headers = target.headers_build_phase.files
			headers_to_delete = headers.find_all do |header|
				[
					'include/grpc/impl/codegen/atm.h',
					'include/grpc/impl/codegen/atm_gcc_atomic.h',
					'include/grpc/impl/codegen/atm_gcc_sync.h',
					'include/grpc/impl/codegen/atm_windows.h',
					'include/grpc/impl/codegen/byte_buffer_reader.h',
					'include/grpc/impl/codegen/connectivity_state.h',
					'include/grpc/impl/codegen/port_platform.h',
					'include/grpc/impl/codegen/slice.h',
					'include/grpc/impl/codegen/status.h',
					'include/grpc/impl/codegen/sync.h',
					'include/grpc/impl/codegen/sync_generic.h',
					'include/grpc/impl/codegen/sync_posix.h',
					'include/grpc/impl/codegen/sync_windows.h',
					'src/core/ext/filters/load_reporting/load_reporting.h'
				].include? header.file_ref.path
            end
            headers_to_delete.each do |file|
                puts 'Removing header file: ' + file.file_ref.path
                headers.delete file
			end
		end
		if target.name == 'BoringSSL'
			headers = target.headers_build_phase.files
			headers_to_delete = headers.find_all do |header|
				[
				'crypto/digest/internal.h',
				'crypto/internal.h',
				'crypto/aes/internal.h',
				'crypto/bio/internal.h',
				'crypto/bn/internal.h',
				'crypto/bytestring/internal.h',
				'crypto/cipher/internal.h',
				'crypto/conf/internal.h',
				'crypto/curve25519/internal.h',
				'crypto/des/internal.h',
				'crypto/ec/internal.h',
				'crypto/evp/internal.h',
				'crypto/modes/internal.h',
				'crypto/newhope/internal.h',
				'crypto/pkcs8/internal.h',
				'crypto/poly1305/internal.h',
				'crypto/rand/internal.h',
				'crypto/rsa/internal.h',
				'crypto/x509/internal.h'
				].include? header.file_ref.path
			end
			headers_to_delete.each do |file|
				puts 'Removing header file: ' + file.file_ref.path
				headers.delete file
			end
		end
	end
end
```

**Comment by muxi** [comment] 2017-10-26 19:02
Thanks @thassss. It is a good local fix for someone who really want to get rid of this warning and do not mind hacking their Podfile. The PR by @paulb777 above will resolve this problem from inside Cocoapods.
