### ISSUE TITLE
Can't use this package with electron

### ISSUE THREAD

**Issue by stephenplusplus** [grpc/grpc#8199] opened 2016-09-25 14:02 UTC
_From @Uhsac on September 25, 2016 11:14_

Hello,

I'm trying to make a simple file upload for one of my electron project but I have an error at the start that come from google-cloud package.

It looks like the problem come from grpc but as it arrive after installing google-cloud I opened the issue here. If you prefer I can open an other one on grpc github project.

#### Environment details

  - OS: Elementary OS Loki (Based on Ubuntu 16.04)
  - Node.js version: Electron 1.3.3 (So Node 6.3)
  - npm version: 3.10.3
  - google-cloud-node version: 0.40.0

#### Steps to reproduce

``` js
const gcloud = require('google-cloud')
const config = require('../../config')

const storage = gcloud.storage({
  credentials: config.credentials,
  projectId: config.projectId
})

const bucket = storage.bucket(config.storageBucket)

async function saveFile(filePath, data) {
  const file = bucket.file(filePath)

  await new Promise((resolve, reject) =>
    file.save(data, err => err ? reject(err) : resolve())
  )
}
exports.saveFile = saveFile
```

Result:

```
App threw an error during load
Error: .../node_modules/grpc/src/node/extension_binary/grpc_node.node: undefined symbol: GENERAL_NAME_free
    at Error (native)
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:168:20)
    at Object.Module._extensions..node (module.js:583:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:168:20)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (.../node_modules/grpc/src/node/src/grpc_extension.js:38:15)
```

I tried to install the package following this http://electron.atom.io/docs/tutorial/using-native-node-modules/ but it don't help.

Thanks for your help.

_Copied from original issue: GoogleCloudPlatform/google-cloud-node#1621_

**Comment by murgatroid99** [comment] 2016-09-26 17:10
gRPC currently does not work out of the box with electron, at least on Unix systems. Issue #6138 has some workarounds that some people have had success with so far. For now, I'm going to close this issue as a duplicate of that one.

**Closed by murgatroid99** 2016-09-26 17:10 UTC
Labels: node
