### ISSUE TITLE
PHP memory leaks

### ISSUE THREAD

**Issue by idevz** [grpc/grpc#8074] opened 2016-09-13 08:45 UTC
when I run the PHP example both `route_guide_client.php` and `greeter_client.php` have an memory leaks like this:

``` zsh
➜  php php greeter_client.php
Hello world
[Tue Sep 13 16:45:01 2016]  Script:  '/media/psf/code/src/grpc/examples/php/greeter_client.php'
/tmp/pear/temp/grpc/src/php/ext/grpc/timeval.c(235) :  Freeing 0x7F5345863690 (16 bytes), script=/media/psf/code/src/grpc/examples/php/greeter_client.php
[Tue Sep 13 16:45:01 2016]  Script:  '/media/psf/code/src/grpc/examples/php/greeter_client.php'
/tmp/pear/temp/grpc/src/php/ext/grpc/timeval.c(74) :  Freeing 0x7F53458636C0 (16 bytes), script=/media/psf/code/src/grpc/examples/php/greeter_client.php
[Tue Sep 13 16:45:01 2016]  Script:  '/media/psf/code/src/grpc/examples/php/greeter_client.php'
/tmp/pear/temp/grpc/src/php/ext/grpc/call.c(246) :  Freeing 0x7F53458637E0 (16 bytes), script=/media/psf/code/src/grpc/examples/php/greeter_client.php
Last leak repeated 1 time
[Tue Sep 13 16:45:01 2016]  Script:  '/media/psf/code/src/grpc/examples/php/greeter_client.php'
/tmp/pear/temp/grpc/src/php/ext/grpc/call.c(242) :  Freeing 0x7F5345863AB0 (16 bytes), script=/media/psf/code/src/grpc/examples/php/greeter_client.php
Last leak repeated 1 time
[Tue Sep 13 16:45:01 2016]  Script:  '/media/psf/code/src/grpc/examples/php/greeter_client.php'
/tmp/pear/temp/grpc/src/php/ext/grpc/call.c(89) :  Freeing 0x7F5345863AE0 (16 bytes), script=/media/psf/code/src/grpc/examples/php/greeter_client.php
Last leak repeated 1 time
[Tue Sep 13 16:45:01 2016]  Script:  '/media/psf/code/src/grpc/examples/php/greeter_client.php'
/tmp/pear/temp/grpc/src/php/ext/grpc/byte_buffer.c(71) :  Freeing 0x7F5345863B70 (14 bytes), script=/media/psf/code/src/grpc/examples/php/greeter_client.php
/media/psf/code/src/php-7.0.10/Zend/zend_alloc.c(2518) : Actual location (location was relayed)
[Tue Sep 13 16:45:01 2016]  Script:  '/media/psf/code/src/grpc/examples/php/greeter_client.php'
/media/psf/code/src/php-7.0.10/Zend/zend_API.c(1061) :  Freeing 0x7F53458B2000 (56 bytes), script=/media/psf/code/src/grpc/examples/php/greeter_client.php
Last leak repeated 1 time
[Tue Sep 13 16:45:01 2016]  Script:  '/media/psf/code/src/grpc/examples/php/greeter_client.php'
/media/psf/code/src/php-7.0.10/Zend/zend_objects.c(162) :  Freeing 0x7F53458C0A00 (40 bytes), script=/media/psf/code/src/grpc/examples/php/greeter_client.php
Last leak repeated 1 time
=== Total 13 memory leaks detected ===
```

here is part of my PHP-ini

``` zsh
➜  php php -v
PHP 7.0.10 (cli) (built: Sep  6 2016 15:16:56) ( NTS DEBUG )
Copyright (c) 1997-2016 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2016 Zend Technologies
➜  php php --ri grpc

grpc

grpc support => enabled
```

**Comment by idevz** [comment] 2016-09-20 04:16
Did anyone meet this issue？

**Comment by idevz** [comment] 2016-09-20 04:26
Did anyone meet this issue？

**Comment by thinkerou** [comment] 2016-09-20 06:49
Hi, @idevz I will deal it.

**Comment by idevz** [comment] 2016-10-07 22:57
@thinkerou Thanks a lot, I'll try later. : )

**Comment by idevz** [comment] 2016-10-08 07:12
hi, @thinkerou, I found your PR isn't Merged right now? Could you please give me an IM account to contact you?

**Comment by thinkerou** [comment] 2016-10-09 00:40
You can use the branch:
https://github.com/thinkerou/grpc/tree/fix_php_mem_leak

2016-10-08 15:13 GMT+08:00 周晶 <notifications@github.com>:

**Comment by chrisgillis** [comment] 2016-11-15 00:17
Any word on this one? +1

**Comment by vjpai** [comment] 2016-11-16 00:19
@stanley-cheung any update here? Is this relevant for 1.1 ? Need it backported to 1.0.x?

**Comment by mdhheydari** [comment] 2016-11-26 13:52
@stanley-cheung, @thinkerou Does #8154 fix this? If it does, can I ask you to review and merge it?
I have a real memory leak issue right now and I have to restart my php-fpms every 5 minutes.

**Comment by thinkerou** [comment] 2016-11-30 02:14
@mdhheydari it's OK when I test it, but you should use [the branch](https://github.com/thinkerou/grpc/tree/fix_php_mem_leak) to test, the code needs @stanley-cheung review, thanks.

**Comment by michaelcurry** [comment] 2017-01-04 23:54
Looking 👀  for an update on this issue.  Is there a timeline for this issue being worked on or pull request merged?

**Closed** 2017-01-11 23:11 UTC
Labels: FOR DISCUSSION, php

**Comment by michaelcurry** [comment] 2017-01-12 20:12
Thanks @thinkerou  & @stanley-cheung 

rebuilt and tested on my local and we are about to push this to prod.  Looks like everything is working as intended.
