### ISSUE TITLE
gRPC doesn't compile on FreeBSD

### ISSUE THREAD

**Issue by nicolasnoble** [grpc/grpc#15010] opened 2018-04-11 00:25 UTC
```
src/core/lib/gpr/arena.cc:131:42: error: static_cast from 'nullptr_t' to 'gpr_atm' (aka 'long') is not allowed
      if (!gpr_atm_rel_cas(&z->next_atm, static_cast<gpr_atm>(NULL),
```

Didn't gpr_atm used to be a intptr_t ? This invalid cast seems weird.

**Comment by markdroth** [comment] 2018-04-11 15:48
I can't reproduce this.  Building with clang-6.0.0 works fine on my desktop.

**Comment by markdroth** [comment] 2018-04-11 15:57
I notice that a similar problem is being reported with an earlier version of clang in #14881.  Both that and grpc/grpc-node#267 are from users on FreeBSD, so I suspect that this is a FreeBSD problem of some sort.  Perhaps FreeBSD defines `intptr_t` differently than Linux?

**Comment by markdroth** [comment] 2018-04-11 16:01
More details in googlei18n/sfntly#67.  I'm pretty sure this is a FreeBSD problem of some sort, but I don't have time to look into the details.

**Comment by parliament718** [comment] 2018-06-30 17:29
I'm also affected by this issue.

FreeBSD 11.1-RELEASE-p11
node v9.10.1

**Comment by zipitup** [comment] 2018-07-05 08:16
Me too on FreeBSD 11.1 p11:

 CXX(target) Release/obj.target/gpr/deps/grpc/src/core/lib/gpr/arena.o
../deps/grpc/src/core/lib/gpr/arena.cc:131:42: error: static_cast from 'nullptr_t' to 'gpr_atm' (aka 'long') is not allowed
      if (!gpr_atm_rel_cas(&z->next_atm, static_cast<gpr_atm>(NULL),
                                         ^~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
gmake: *** [gpr.target.mk:181: Release/obj.target/gpr/deps/grpc/src/core/lib/gpr/arena.o] Error 1

gyp ERR! build error
gyp ERR! stack Error: `gmake` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:237:12)
gyp ERR! System FreeBSD 11.1-RELEASE-p11

**Comment by thomasbuesser** [comment] 2018-07-17 18:46
does anybody have a solution for this? it prevents me from using gitlab....

**Comment by mrmarbury** [comment] 2018-07-20 08:49
same problem here on FreeBSD 11.2 ... trying to install chef-dk gems and some deps

**Comment by rdnn** [comment] 2018-07-23 02:52
Experiencing the same issue as others which is affecting building Rocket.Chat on FreeBSD.

```
../deps/grpc/src/core/lib/gpr/arena.cc:131:42: error: static_cast from 'nullptr_t' to 'gpr_atm' (aka 'long') is not allowed
      if (!gpr_atm_rel_cas(&z->next_atm, static_cast<gpr_atm>(NULL),
                                         ^~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
gmake: *** [gpr.target.mk:187: Release/obj.target/gpr/deps/grpc/src/core/lib/gpr/arena.o] Error 1
gmake: Leaving directory '/usr/local/rocketchat/bundle/programs/server/npm/node_modules/grpc/build'
gyp ERR! build error 
gyp ERR! stack Error: `gmake` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System FreeBSD 11.1-RELEASE-p4```

**Comment by sreecha** [comment] 2018-07-25 19:42
`gpr_atm` is is still of type `intptr_t` - so I am not sure why the above static cast fails.

**Comment by sreecha** [comment] 2018-07-25 19:54
As of https://github.com/grpc/grpc/pull/16069, the code in arena.cc has change and we are no longer doing that `static_cast` .

Also did a search in rest of grpc code and we aren't doing this anywhere else.

https://github.com/grpc/grpc/pull/16069 was just merged yesterday and so it will make it in to the next release :(

**Comment by sreecha** [comment] 2018-07-25 23:08
@nicolasnoble : Can I close this issue?

**Comment by sreecha** [comment] 2018-08-16 18:34
Yes, this can be closed.

**Closed by sreecha** 2018-08-16 18:34 UTC
Labels: kind/bug, lang/core, priority/P2
