### ISSUE TITLE
MacOS arm64 support for grpc.tools package

### ISSUE THREAD

**Issue by rosebyte** [grpc/grpc#37325] opened 2024-07-28 08:11 UTC
Hello, it seems the protoc for MacOS is available now. Are we going to add related build target for dotnet `grpc.tools` package? Currently, there is a kill-switch in the `ProtoToolsPlatform.cs` file:

```csharp
// Use x64 on macosx arm64 until a native protoc is shipped
if (Os == "macosx" && Cpu == "arm64")
{
    Cpu = "x64";
}
```
 I guess the idea was to use the x64 protoc through rosetta, however, I'm just getting a path not found error:
 
 > MSB6003 : The specified task executable "~/.nuget/packages/grpc.tools/2.64.0/tools/macosx_x64/protoc"

Shall I remove it as we have the protoc shipped or I do miss something?

**Comment by tonydnewell** [comment] 2024-07-29 07:53
Duplicate of https://github.com/grpc/grpc/issues/36836

`Grpc.Tools` only supports x64 binaries for MacOS - but these should work on MacOS arm64 when using Rosetta.
See [BUILD-INTEGRATION.md](https://github.com/grpc/grpc/blob/master/src/csharp/BUILD-INTEGRATION.md#getting-started)

See also https://github.com/grpc/grpc/issues/32006#issuecomment-1369942650

**Closed** 2024-09-25 16:39 UTC
Labels: kind/enhancement, lang/C#, priority/P2
