### ISSUE TITLE
python EmptyMessageTest failure (linux dbg)

### ISSUE THREAD

**Issue by jtattermusch** [grpc/grpc#10960] opened 2017-05-02 21:20 UTC
https://grpc-testing.appspot.com/job/gRPC_pull_requests_linux/5118/testReport/junit/(root)/python_linux_dbg_native/py27_test_unit__empty_message_test_EmptyMessageTest/

```
[91mERROR         unit._empty_message_test.EmptyMessageTest.testUnaryUnary
[0m4 tests finished:
	3 successful
	1 unsuccessful
	0 skipped
	0 expected failures
	0 unexpected successes
Interrupted Tests:
	[]

Errors/Failures: 
[91munit._empty_message_test.EmptyMessageTest.testUnaryUnary[0m
[1mtraceback:[0m
Traceback (most recent call last):
  File "/usr/lib/python2.7/unittest/case.py", line 329, in run
    testMethod()
  File "/var/local/git/grpc/src/python/grpcio_tests/tests/unit/_empty_message_test.py", line 116, in testUnaryUnary
    response = self._channel.unary_unary(_UNARY_UNARY)(_REQUEST)
  File "/var/local/git/grpc/py27/local/lib/python2.7/site-packages/grpc/_channel.py", line 507, in __call__
    return _end_unary_response_blocking(state, call, False, deadline)
  File "/var/local/git/grpc/py27/local/lib/python2.7/site-packages/grpc/_channel.py", line 455, in _end_unary_response_blocking
    raise _Rendezvous(state, None, None, deadline)
_Rendezvous: <_Rendezvous of RPC that terminated with (StatusCode.UNAVAILABLE, Endpoint read failed)>

[1mstdout:[0m

[1mstderr:[0m


Unexpected successes: []
Test failure
```

**Comment by nathanielmanistaatgoogle** [comment] 2017-05-02 21:22
Resolving as a duplicate of [issue 10142](https://github.com/grpc/grpc/issues/10142).

**Closed by nathanielmanistaatgoogle** 2017-05-02 21:22 UTC
Labels: BUILDPONY, python
