### ISSUE TITLE
Timeout: c_windows_dbg_native.vsprojects/Debug/concurrent_connectivity_test.exe

### ISSUE THREAD

**Issue by murgatroid99** [grpc/grpc#11188] opened 2017-05-17 16:53 UTC
https://grpc-testing.appspot.com/job/gRPC_master_windows/2548/testReport/junit/(root)/c_windows_dbg_native/vsprojects_Debug_concurrent_connectivity_test_exe/

**Comment by dgquintas** [comment] 2017-07-16 04:58
Actually, still happening:

```
2017-07-14 20:02:40,530 D0714 19:57:40.500000000  3196 test_config.c:388] test slowdown factor: sanitizer=1, fixture=1, poller=1, total=1
D0714 19:57:40.500000000  3196 dns_resolver.c:301] Using native dns resolver
D0714 19:57:40.500000000  3196 concurrent_connectivity_test.c:180] Wave 1
I0714 19:57:41.593000000  3036 subchannel.c:682] Connect failed: {"created":"@1500087461.593000000","description":"OS Error","file":"T:\src\github\grpc\workspace_c_windows_dbg_native\vsprojects\..\src\core\lib\iomgr\tcp_client_windows.c","file_line":105,"os_error":"No connection could be made because the target machine actively refused it.\r\n","syscall":"ConnectEx","wsa_error":10061}
D0714 19:57:41.875000000  3196 concurrent_connectivity_test.c:190] Wave 2
2017-07-14 20:02:40,530 TIMEOUT: vsprojects/Debug/concurrent_connectivity_test.exe [pid=3612]
```

**Comment by jtattermusch** [comment] 2017-07-31 13:54
This is still happening on Kokoro.
It only happens in the Debug version (opt/Release is not flaky). 
On kokoro, the test is set as "flaky" based on historical data, but still fails.

**Comment by jtattermusch** [comment] 2017-08-01 11:15
#12016  should improve how often we see this issue on Kokoro, but it doesn't address the root cause.

**Comment by jtattermusch** [comment] 2017-08-10 11:03
This has been suppressed by https://github.com/grpc/grpc/pull/12016.

**Comment by jtattermusch** [comment] 2017-08-24 14:49
Seen here after switching to cmake build:
https://sponge.corp.google.com/target?id=5add19b1-67fd-4938-a3cc-a6e2ca76e8a1&target=github/grpc/c_windows_dbg_native&searchFor=&show=FAILED&sortBy=STATUS

```

2017-08-23 09:53:27,285 D0823 09:48:27.285000000  3564 test_config.c:388] test slowdown factor: sanitizer=1, fixture=1, poller=1, total=1


D0823 09:48:27.300000000  3564 dns_resolver.c:301] Using native dns resolver


D0823 09:48:27.300000000  3564 concurrent_connectivity_test.c:180] Wave 1


I0823 09:48:28.363000000  1080 subchannel.c:683] Connect failed: {"created":"@1503506908.363000000","description":"OS Error","file":"T:\src\github\grpc\workspace_c_windows_dbg_native\src\core\lib\iomgr\tcp_client_windows.c","file_line":105,"os_error":"No connection could be made because the target machine actively refused it.\r\n","syscall":"ConnectEx","wsa_error":10061}


D0823 09:48:28.707000000  3564 concurrent_connectivity_test.c:190] Wave 2




2017-08-23 09:53:27,285 TIMEOUT: cmake/build/Debug/concurrent_connectivity_test.exe [pid=1560]
```

**Comment by jtattermusch** [comment] 2018-01-09 18:22
Reopening. It's failing 14% of grpc/windows/master/grpc_basictests_dbg builds (but doesn't seem to happen nearly as often on opt configuration).

**Comment by jtattermusch** [comment] 2018-01-09 18:23
https://sponge.corp.google.com/target?id=dcf7cb6c-8100-4aef-a4b3-4ff16993bb16&target=github/grpc/c_windows_dbg_native&searchFor=&show=FAILED&sortBy=STATUS

**Comment by jtattermusch** [comment] 2018-01-10 11:10
This is actually not timing out now, but crashing:
```
D0108 20:07:53.135000000  3424 test_config.cc:388] test slowdown factor: sanitizer=1, fixture=1, poller=1, total=1
D0108 20:07:53.135000000  3424 dns_resolver.cc:294] Using native dns resolver
D0108 20:07:53.135000000  3424 concurrent_connectivity_test.cc:179] Wave 1
I0108 20:07:54.198000000  5388 subchannel.cc:679] Connect failed: {"created":"@1515470874.198000000","description":"OS Error","file":"T:\src\github\grpc\workspace_c_windows_dbg_native\src\core\lib\iomgr\tcp_client_windows.cc","file_line":105,"os_error":"No connection could be made because the target machine actively refused it.\r\n","syscall":"ConnectEx","wsa_error":10061}
D0108 20:07:54.573000000  3424 concurrent_connectivity_test.cc:190] Wave 2
E0108 20:08:25.635000000  4236 concurrent_connectivity_test.cc:102] assertion failed: ev.type == GRPC_OP_COMPLETE
```

**Comment by dgquintas** [comment] 2018-01-10 17:56
It'd be really helpful to bisect to identify on which commit it started
crashing.

**Comment by jtattermusch** [comment] 2018-01-11 16:51
@dgquintas  I'm not sure it ever stopped failing to be honest. I'm trying to find the root cause in the debugger instead. What I know instead:

In "Wave 2" (using a real gRPC server), 
all the client threads finish successfully (and on time), and server shutdown is requested 
https://github.com/grpc/grpc/blob/53430532ce765aa1aa96656b00015914598838ae/test/core/surface/concurrent_connectivity_test.cc#L207.

The shutdown confirmation is never delivered to  cq_next here though: https://github.com/grpc/grpc/blob/53430532ce765aa1aa96656b00015914598838ae/test/core/surface/concurrent_connectivity_test.cc#L101

When attempting to shutdown the server, `maybe_finish_shutdown` is invoked a few times,
but always exits prematurely because  the server still has an active listener that needs to be destroyed first. 
https://github.com/grpc/grpc/blob/def31f952700aad3a9da280c003ebfb3e8e14087/src/core/lib/surface/server.cc#L659

So overall, it seems that https://github.com/grpc/grpc/blob/94e676e10f8c739289924b8458a246699e3623ce/src/core/ext/transport/chttp2/server/chttp2_server.cc#L213  never gets called - and I don't know why that is yet. Suggestions are welcome.

**Comment by jtattermusch** [comment] 2018-01-29 12:24
Not seen since Jan 9, closing the issue.

**Closed by jtattermusch** 2018-01-29 12:24 UTC
Labels: area/core, infra/BUILDPONY, infra/Kokoro, platform/Windows, priority/P1
