### ISSUE TITLE
PHP MacOS build failure (due to PHP preinstallation failure?)

### ISSUE THREAD

**Issue by donnadionne** [grpc/grpc#27901] opened 2021-11-01 20:27 UTC
```
I/usr/local/opt/php@7.3/include -DGRPC_PHP_DEBUG -DHAVE_CONFIG_H -Wno-parentheses-equality -c /Volumes/BuildData/tmpfs/src/github/grpc/workspace_php7_macos_dbg_native/src/php/ext/grpc/byte_buffer.c  -fno-common -DPIC -o .libs/byte_buffer.o
/Volumes/BuildData/tmpfs/src/github/grpc/workspace_php7_macos_dbg_native/src/php/ext/grpc/byte_buffer.c:19:10: fatal error: 'php.h' file not found
#include <php.h>
         ^~~~~~~
1 error generated.
make: *** [byte_buffer.lo] Error 1
real         6.39
user         3.04
sys          1.88

2021-11-01 11:33:48,769 FAILED: tools/run_tests/helper_scripts/build_php.sh [ret=2, pid=12837, time=6.4sec]
2021-11-01 11:33:48,769 FAILED: Some tests failed
```

Failure link
https://source.cloud.google.com/results/invocations/8b315adb-8ff8-49b4-ad41-8451a3b31916/log

**Comment by stanley-cheung** [comment] 2021-11-01 23:12
This happens from time to time - it's due to the kokoro mac instances somehow suddenly seem to have lost the standard PHP installation (binary & headers). The problem goes away after a while - potentially some sort of kokoro base-image mismatch. This only happens to Kokoro Mac instances.

If this persists, we probably should log a bug to the Kokoro team.

**Comment by jtattermusch** [comment] 2021-11-02 09:46
CC @dennycd  since he's been seeing a potentially similar problem  (disappearing headers) for objc tests.

**Comment by jtattermusch** [comment] 2021-11-02 09:53
Note that PHP is pre-installed into the MacOS workers VMs by a script just before the build starts, so it might be that the script just failed to install PHP (which is why php.h might later be missing).

excerpt from the log:
```
...
Error: php@7.3: Failed to download resource "glib"
Download failed: https://download.gnome.org/sources/glib/2.70/glib-2.70.1.tar.xz
++ true
+++ LDFLAGS
tools/internal_ci/helper_scripts/prepare_build_macos_rc: line 180: LDFLAGS: command not found
++ export 'LDFLAGS=-L/usr/local/opt/php@7.3/lib '
++ LDFLAGS='-L/usr/local/opt/php@7.3/lib '
+++ CPPFLAGS
tools/internal_ci/helper_scripts/prepare_build_macos_rc: line 181: CPPFLAGS: command not found
++ export 'CPPFLAGS=-I/usr/local/opt/php@7.3/include '
++ CPPFLAGS='-I/usr/local/opt/php@7.3/include '
++ export 'PATH=/usr/local/opt/php@7.3/bin:/usr/local/opt/php@7.3/sbin:/Users/kbuilder/.rvm/gems/ruby-2.6.3/bin:/Users/kbuilder/.rvm/gems/ruby-2.6.3@global/bin:/Users/kbuilder/.rvm/rubies/ruby-2.6.3/bin:/Library/Frameworks/Python.framework/Versions/3.7/bin:/Library/Frameworks/Python.framework/Versions/3.6/bin:/Library/Frameworks/Python.framework/Versions/3.5/bin:/Library/Frameworks/Python.framework/Versions/2.7/bin:/opt/google-cloud-sdk/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/share/dotnet:~/.dotnet/tools:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/Applications/CMake.app/Contents/bin:/Applications/Unity/Unity.app/MacOS:/Users/kbuilder/Library/Android/sdk/platform-tools:/Users/kbuilder/Library/Android/sdk/tools/bin:/Users/kbuilder/.rvm/bin'
++ PATH='/usr/local/opt/php@7.3/bin:/usr/local/opt/php@7.3/sbin:/Users/kbuilder/.rvm/gems/ruby-2.6.3/bin:/Users/kbuilder/.rvm/gems/ruby-2.6.3@global/bin:/Users/kbuilder/.rvm/rubies/ruby-2.6.3/bin:/Library/Frameworks/Python.framework/Versions/3.7/bin:/Library/Frameworks/Python.framework/Versions/3.6/bin:/Library/Frameworks/Python.framework/Versions/3.5/bin:/Library/Frameworks/Python.framework/Versions/2.7/bin:/opt/google-cloud-sdk/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/share/dotnet:~/.dotnet/tools:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/Applications/CMake.app/Contents/bin:/Applications/Unity/Unity.app/MacOS:/Users/kbuilder/Library/Android/sdk/platform-tools:/Users/kbuilder/Library/Android/sdk/tools/bin:/Users/kbuilder/.rvm/bin'
++ mkdir -p /usr/local/lib/php/pecl
++ date
```

Indeed, the pre-install script continues if PHP installation fails:
https://github.com/grpc/grpc/blob/7c7fb9e525b947a35633b972957135fd313ec345/tools/internal_ci/helper_scripts/prepare_build_macos_rc#L179
(see `brew install php@7.3 || true`)

If failing to pre-install PHP prevents the job from passing, it's probably easier to fail as soon as PHP installation fails, at least the error will not be cryptic them.

**Comment by jtattermusch** [comment] 2021-11-02 09:58
Also see https://github.com/grpc/grpc/pull/26665/files#diff-75c50f44a9c4cdc19746e18742ff429dfd4615ee16874578e501e4be606dcbcfR146 which adds the `|| true` for PHP installation (but doesn't explain why).

**Comment by markdroth** [comment] 2021-11-02 14:36
This is blocking the 1.42 branch cut.  We need to get this resolved ASAP.  What's the fastest way to fix this?

**Comment by jtattermusch** [comment] 2021-11-02 14:47
Some more insights: From the build history it looks like this has been failing for about 2 days now and wasn't caused by any change in our repository AFAICT. 
The exact error the PHP installation was generating has been changing, but it's always a failure to pre-install PHP (followed by a failure to build since php.h is missing).

**Comment by jtattermusch** [comment] 2021-11-02 15:07
One problem I'm seeing in my experiment is 
```
==> Downloading https://ftp.gnu.org/gnu/gdbm/gdbm-1.22.tar.gz
curl: (60) SSL certificate problem: certificate has expired
More details here: https://curl.haxx.se/docs/sslcerts.html

curl performs SSL certificate verification by default, using a "bundle"
 of Certificate Authority (CA) public keys (CA certs). If the default
 bundle file isn't adequate, you can specify an alternate file
 using the --cacert option.
If this HTTPS server uses a certificate signed by a CA represented in
 the bundle, the certificate verification probably failed due to a
 problem with the certificate (it might be expired, or the name might
 not match the domain name in the URL).
If you'd like to turn off curl's verification of the certificate, use
 the -k (or --insecure) option.
HTTPS-proxy has similar options --proxy-cacert and --proxy-insecure.
Trying a mirror...
==> Downloading https://ftpmirror.gnu.org/gdbm/gdbm-1.22.tar.gz
curl: (60) SSL certificate problem: certificate has expired
More details here: https://curl.haxx.se/docs/sslcerts.html

curl performs SSL certificate verification by default, using a "bundle"
 of Certificate Authority (CA) public keys (CA certs). If the default
 bundle file isn't adequate, you can specify an alternate file
 using the --cacert option.
If this HTTPS server uses a certificate signed by a CA represented in
 the bundle, the certificate verification probably failed due to a
 problem with the certificate (it might be expired, or the name might
 not match the domain name in the URL).
If you'd like to turn off curl's verification of the certificate, use
 the -k (or --insecure) option.
HTTPS-proxy has similar options --proxy-cacert and --proxy-insecure.
Error: php@7.3: Failed to download resource "gdbm"
Download failed: https://ftpmirror.gnu.org/gdbm/gdbm-1.22.tar.gz
```

**Comment by veblush** [comment] 2021-11-02 16:30
Yeah, this is caused by php installation failure.

```
++ brew install php@7.3
Warning: You are using macOS 10.14.
We (and Apple) do not provide support for this old version.
You will encounter build failures with some formulae.
Please create pull requests instead of asking for help on Homebrew's GitHub,
Twitter or any other official channels. You are responsible for resolving
any issues you experience while you are running this
old version.
... (omitted)
==> Downloading https://download.gnome.org/sources/glib/2.70/glib-2.70.1.tar.xz
curl: (60) SSL certificate problem: certificate has expired
More details here: https://curl.haxx.se/docs/sslcerts.html

curl performs SSL certificate verification by default, using a "bundle"
 of Certificate Authority (CA) public keys (CA certs). If the default
 bundle file isn't adequate, you can specify an alternate file
 using the --cacert option.
If this HTTPS server uses a certificate signed by a CA represented in
 the bundle, the certificate verification probably failed due to a
 problem with the certificate (it might be expired, or the name might
 not match the domain name in the URL).
If you'd like to turn off curl's verification of the certificate, use
 the -k (or --insecure) option.
HTTPS-proxy has similar options --proxy-cacert and --proxy-insecure.
Error: php@7.3: Failed to download resource "glib"
Download failed: https://download.gnome.org/sources/glib/2.70/glib-2.70.1.tar.xz
```

I guess this is a problem of using out-dated certificate. [SO](https://apple.stackexchange.com/questions/393481/homebrew-cask-download-failure-ssl-certificate-problem-certificate-has-expired) might be relevant.

**Comment by jtattermusch** [comment] 2021-11-04 08:49
Fixed by https://github.com/grpc/grpc/pull/27923

**Closed by jtattermusch** 2021-11-04 08:49 UTC
Labels: kind/bug, priority/P0/RELEASE BLOCKER
