### ISSUE TITLE
Unhandled ExecuteBatchError leaves gRPC AsyncIO API in a permanently degraded state

### ISSUE THREAD

**Issue by jecknig** [grpc/grpc#31570] opened 2022-11-07 16:21 UTC
### What version of gRPC and what language are you using?

grpcio version 1.47.0
Python version 3.8.10

### What operating system (Linux, Windows,...) and version?

Docker image: python:3.8-slim-bullseye

### What runtime / compiler are you using (e.g. python version or version of gcc)

Docker container is running on Google Kubernetes Engine, Version 1.22.15-gke.100, in zone europe-west4-a.

### What did you do?

We have a GRPC API deployed on Kubernetes, which uses the gRPC AsyncIO API, and defines two simple RPCs, one which serves around 200 requests per minute, per replica, another which is just called by a readiness probe, once per 5 seconds and per replica. 2 Replica are deployed.

The API was running fine for about a year. But recently, we had an incident, in which both replica logged the same error message, almost at the same time:
```
Task exception was never retrieved
future: <Task finished name='Task-105440' coro=<<coroutine without __name__>()> exception=ExecuteBatchError('Failed "execute_batch": (<grpc._cython.cygrpc.SendInitialMetadataOperation object at 0x7fe69cc0c4a0>, <grpc._cython.cygrpc.SendMessageOperation object at 0x7fe69cb6f5b0>, <grpc._cython.cygrpc.SendStatusFromServerOperation object at 0x7fe69ca84ee0>)')>
Traceback (most recent call last):
  File "src/python/grpcio/grpc/_cython/_cygrpc/aio/server.pyx.pxi", line 705, in _handle_exceptions
  File "src/python/grpcio/grpc/_cython/_cygrpc/aio/server.pyx.pxi", line 682, in grpc._cython.cygrpc._handle_exceptions
  File "src/python/grpcio/grpc/_cython/_cygrpc/aio/server.pyx.pxi", line 796, in _handle_rpc
  File "src/python/grpcio/grpc/_cython/_cygrpc/aio/server.pyx.pxi", line 547, in _handle_unary_unary_rpc
  File "src/python/grpcio/grpc/_cython/_cygrpc/aio/server.pyx.pxi", line 452, in _finish_handler_with_unary_response
  File "src/python/grpcio/grpc/_cython/_cygrpc/aio/callback_common.pyx.pxi", line 98, in execute_batch
grpc._cython.cygrpc.ExecuteBatchError: Failed "execute_batch": (<grpc._cython.cygrpc.SendInitialMetadataOperation object at 0x7fe69cc0c4a0>, <grpc._cython.cygrpc.SendMessageOperation object at 0x7fe69cb6f5b0>, <grpc._cython.cygrpc.SendStatusFromServerOperation object at 0x7fe69ca84ee0>)
```

### What did you expect to see?

I would have expected one of these two things to happen:
- The exception is re-raised by `grpcio` to the surrounding python code, so that it can decide how to handle the exception (e.g. don't catch it, and let Kubernetes restart the pod as a result)
- The exception is handled gracefully by `grpcio`, and the API continues serving requests as before, with the same response times as before.

### What did you see instead?

- The API did continue serving requests, but at permanently degraded performance (i.e. much slower response times). The incident could only be resolved by restarting the API pods manually.

### Anything else we should know about your project / environment?

Unfortunately, I can't give detailed instructions on how to reproduce the exact circumstances of this bug, since it happened more or less randomly for us, after the API had already been running fine for around a year. However, the bug occured almost simultaneously
in both replica of the API. This leads us to believe, it was some infrastructure-related issue that triggered the exception.

Possibly related to #31527 or #31043.

**Comment by gnossen** [comment] 2022-12-16 20:15
@XuanWang-Amos Ping on this.

**Comment by XuanWang-Amos** [comment] 2022-12-21 19:49
I'm currently investigating this issue, looks like this error is on server side, will need some time to dig into this.

**Comment by njhill** [comment] 2022-12-27 05:06
Just a note to say that I also encountered this recently with 1.51.1 and python 3.9.

**Comment by XuanWang-Amos** [comment] 2023-01-10 17:45
The error message `Failed "execute_batch"` indicates that we encountered some issue in gRPC core and it failed to process the operations passed from gRPC python to gRPC core, in order to further debug this issue, we'll need additional logs from core.

**To everyone who have the similar issue, please include two environment flags while starting gRPC and paste logs so we can help further debug:**
`GRPC_VERBOSITY=debug GRPC_TRACE=all,-timer,-timer_check`

In the meanwhile, I'll create a PR to enhance the error message so we can have more information on python layer too.

**Comment by njhill** [comment] 2023-01-20 00:02
@XuanWang-Amos I was able to repro with the extra debug turned on, please see attached log. I'm pretty sure this is related to the client closing/abandoning the call early.

[pygrpc-debug.log.gz](https://github.com/grpc/grpc/files/10462068/pygrpc-debug.log.gz)

**Comment by AMontagu** [comment] 2023-01-21 12:19
I can confirm that we have this issue whit grpc web when client reload web page while the stream is running

**Comment by XuanWang-Amos** [comment] 2023-01-23 23:37
Thanks for the log, looks like client received RST_STREAM with error code 8:
```
UNKNOWN:Error received from peer unix: {grpc_message:"Received RST_STREAM with error code 8", grpc_status:1, created_time:"2023-01-19T23:19:28.385297862+00:00"}
```

[RST_STREAM with error code 8](https://github.com/grpc/grpc/blob/3ec0e29bcf48e5774a1b124f0edf581b7ca40055/doc/PROTOCOL-HTTP2.md#errors) should be mapped to CANCELLED when sent by a server, from our code, we handle it by throwing an `ExecuteBatchError` [here](https://github.com/grpc/grpc/blob/master/src/python/grpcio/grpc/_cython/_cygrpc/aio/callback_common.pyx.pxi#L88), so far looks correct, but when we process this error in `server.pyx.pxi`, we [only considered client side cancel and raising it otherwise](https://github.com/grpc/grpc/blob/master/src/python/grpcio/grpc/_cython/_cygrpc/aio/server.pyx.pxi#L700-L705), thus this Exception was left unhandled in event loop.

We'll discuss internally to see how should we proceed from here.

**Comment by cprajakta** [comment] 2023-03-21 09:52
@XuanWang-Amos - Any updates on this? We are also facing similar issue on our end as mentioned in the description.

**Comment by XuanWang-Amos** [comment] 2023-04-06 17:04
A PR was merged so that we'll no longer throw `ExecuteBatchError`: https://github.com/grpc/grpc/pull/32551.

But it's unclear if that will also fix the degraded performance issue, I'm adding `requires reporter action` label so it will be automatically close in one month, but feel free to comment here if the performance issue still exist.

**Comment by XuanWang-Amos** [comment] 2023-08-24 22:33
Looks like it's not happening anymore, closing this issue now.

Again, feel free to comment here if the performance issue still exist.

**Closed by XuanWang-Amos** 2023-08-24 22:33 UTC
Labels: kind/bug, lang/Python, priority/P2

**Comment by MasakiMu319** [comment] 2025-01-10 16:25
### What version of gRPC and what language are you using?
grpcio version 1.66.1
Python version 3.11.11

### What operating system (Linux, Windows,...) and version?
MacOS 15.3 Beta (24D5040f)

### What runtime / compiler are you using (e.g. python version or version of gcc)
cpython-311 on Mac

### What did you do?
This is an internal microservice we use to provide streaming response content to the central service. Recently, we observed that when the central service fails to properly release the gRPC connection with the microservice that provides streaming content, this microservice acts as the server and encounters the following error:
```bash
ExecuteBatchError raised in core by servicer method [/book.v1.BookService/get_book_content]
Traceback (most recent call last):
  File "src/python/grpcio/grpc/_cython/_cygrpc/aio/server.pyx.pxi", line 689, in grpc._cython.cygrpc._handle_exceptions
  File "src/python/grpcio/grpc/_cython/_cygrpc/aio/server.pyx.pxi", line 838, in _handle_rpc
  File "src/python/grpcio/grpc/_cython/_cygrpc/aio/server.pyx.pxi", line 587, in _handle_unary_stream_rpc
  File "src/python/grpcio/grpc/_cython/_cygrpc/aio/server.pyx.pxi", line 505, in _finish_handler_with_stream_responses
  File "src/python/grpcio/grpc/_cython/_cygrpc/aio/server.pyx.pxi", line 143, in write
  File "src/python/grpcio/grpc/_cython/_cygrpc/aio/callback_common.pyx.pxi", line 148, in _send_message
  File "src/python/grpcio/grpc/_cython/_cygrpc/aio/callback_common.pyx.pxi", line 99, in execute_batch
grpc._cython.cygrpc.ExecuteBatchError: Failed "execute_batch": (<grpc._cython.cygrpc.SendMessageOperation object at 0x105b79cb0>,)
```

We observed that there was indeed an error consistent with our guess in the logs after enabling `GRPC_VERBOSITY=debug GRPC_TRACE=all,-timer,-timer_check`: `sending a message on a closed stream` :
```
I0000 00:00:1736524052.877239 3526716 completion_queue.cc:698] cq_end_op_for_next(cq=0x109b1c9d0, tag=0x109decb48, error=UNKNOWN:Attempt to send message after stream was closed. {created_time:"2025-01-10T23:47:32.877113+08:00"}, done=true, done_arg=0x109ba8340, storage=0x109ba8390)
I0000 00:00:1736524052.877257 3526716 completion_queue.cc:703] Operation failed: tag=0x109decb48, error=UNKNOWN:Attempt to send message after stream was closed. {created_time:"2025-01-10T23:47:32.877113+08:00"}
```

However, this error seems to belong to the error thrown by the gRPC core, and our try-exception logic doesn't seem to capture it properly. Moreover, it indeed causes the AsyncIO API to be in a permanently degraded state. 

Therefore, I chose to raise a new issue under this topic. The log file is attached: [output.log.zip](https://github.com/user-attachments/files/18379789/output.log.zip)

Thank you for your assistance. @XuanWang-Amos
