### ISSUE TITLE
Example Python contains lots of duplicated 'import' calls

### ISSUE THREAD

**Issue by tedivm** [grpc/grpc#6923] opened 2016-06-16 04:23 UTC
You can see this directly in the ["route_guide" example](https://github.com/grpc/grpc/blob/release-0_14/examples/python/route_guide/route_guide_pb2.py#L362), where it includes the `route_guide_pb2` module (even though it *is* the `route_guide_pb2` module) eight times in each function that includes it.

I'm seeing it four times in each service I'm generating.

**Comment by thinkerou** [comment] 2016-06-16 11:27
You should update code at first and use `sh run_codegen.sh` command, it will gen new route_guide_pb2.py which have not **duplicted import**.

**Comment by nathanielmanistaatgoogle** [comment] 2016-06-17 21:24
Retitled issue - the code generator no longer generates duplicate imports, but we have yet to refresh [the example code that you linked](https://github.com/grpc/grpc/blob/release-0_14/examples/python/route_guide/route_guide_pb2.py#L362).

**Comment by nathanielmanistaatgoogle** [comment] 2016-06-22 17:59
Closing as a duplicate of [issue 4977](https://github.com/grpc/grpc/issues/4977).

**Closed by nathanielmanistaatgoogle** 2016-06-22 17:59 UTC
Labels: cleanup, protoc plugins, python
