### ISSUE TITLE
ServerServiceDefinition lift class restriction

### ISSUE THREAD

**Issue by bjornbouetsmith** [grpc/grpc#24685] opened 2020-11-06 11:35 UTC
### Is your feature request related to a problem? Please describe.
I am trying to convert our current client/server solution to gRPC and for that I am doing a POC.

But using our existing datacontracts I immediately got bitten by this:

```
public Builder AddMethod<TRequest, TResponse>(
                Method<TRequest, TResponse> method,
                UnaryServerMethod<TRequest, TResponse> handler)
                    where TRequest : class
                    where TResponse : class
            {
                duplicateDetector.Add(method.FullName, null);
                addMethodActions.Add((serviceBinder) => serviceBinder.AddMethod(method, handler));
                return this;
            }
```

And that stopped me - since we use structs mixed with classes and.

Basically I am trying to create my own Method definitions and not use protobuf and apparently AddMethod requires that the Request and Response classes have to classes.

### Describe the solution you'd like
Remove the class constraint and allow structs to be used as messages

### Describe alternatives you've considered
None - since changing our existing contracts to use classes will impact the performance of our current solution, since classes gets allocated on the slower heap instead of on the stack

**Comment by jtattermusch** [comment] 2020-12-01 15:41
Looks like this is a duplicate of https://github.com/grpc/grpc/issues/22605.

**Closed by jtattermusch** 2020-12-01 15:41 UTC
Labels: kind/enhancement, lang/C#, priority/P2
