### ISSUE TITLE
Something is wrong with "Basic Tests C/C++ MacOS" test since Jul 28

### ISSUE THREAD

**Issue by stanley-cheung** [grpc/grpc#23661] opened 2020-07-29 06:43 UTC
I am not sure what exactly is wrong, but vast majority of the "Basic Tests C/C++ MacOS" PR tests failed today.

Kokoro job: grpc/core/pull_request/macos/grpc_basictests_c_cpp

Dashboard: https://fusion.corp.google.com/projectanalysis/history/KOKORO/prod%3Agrpc%2Fcore%2Fpull_request%2Fmacos%2Fgrpc_basictests_c_cpp

Vast majority of builds start failing since about 10am PDT Jul 28, 2020.

---

A few runs failed with the following error:

```
2020-07-28 13:41:13,502 FAILED: bins/opt/client_callback_end2end_test --gtest_filter=ClientCallbackEnd2endTest/ClientCallbackEnd2endTest.SequentialGenericRpcsAsBidiWithReactorReuse/6  GRPC_POLL_STRATEGY=poll
```

```
D0728 13:38:55.396281000 140735574311808 ev_posix.cc:173]              Using polling engine: poll
D0728 13:38:55.397595000 140735574311808 lb_policy_registry.cc:40]     registering LB policy factory for "grpclb"
D0728 13:38:55.397632000 140735574311808 lb_policy_registry.cc:40]     registering LB policy factory for "cds_experimental"
D0728 13:38:55.397658000 140735574311808 lb_policy_registry.cc:40]     registering LB policy factory for "eds_experimental"
D0728 13:38:55.397677000 140735574311808 lb_policy_registry.cc:40]     registering LB policy factory for "lrs_experimental"
D0728 13:38:55.397700000 140735574311808 lb_policy_registry.cc:40]     registering LB policy factory for "priority_experimental"
D0728 13:38:55.397718000 140735574311808 lb_policy_registry.cc:40]     registering LB policy factory for "weighted_target_experimental"
D0728 13:38:55.397744000 140735574311808 lb_policy_registry.cc:40]     registering LB policy factory for "xds_routing_experimental"
D0728 13:38:55.397769000 140735574311808 lb_policy_registry.cc:40]     registering LB policy factory for "pick_first"
D0728 13:38:55.397788000 140735574311808 lb_policy_registry.cc:40]     registering LB policy factory for "round_robin"
D0728 13:38:55.397811000 140735574311808 dns_resolver_ares.cc:507]     Using ares dns resolver
[waiter.cc : 223] RAW: pthread_mutex_destroy failed: 16
```
https://source.cloud.google.com/results/invocations/2017febf-dd19-44f4-8766-8012e8768234/targets/github%2Fgrpc%2Frun_tests%2Fcpp_macos_opt_native/tests

---

Another common failure seems to be `TIMEOUT: bins/opt/async_end2end_test` (this error seems to be most common):

https://source.cloud.google.com/results/invocations/e998ca07-4f04-4efd-b7c7-d97566048cd6/targets/github%2Fgrpc%2Frun_tests%2Fcpp_macos_opt_native/tests

```
2020-07-28 19:09:58,743 TIMEOUT: bins/opt/async_end2end_test --gtest_filter=AsyncEnd2end/AsyncEnd2endTest.SimpleClientStreamingWithCoalescingApi/8  GRPC_POLL_STRATEGY=poll [pid=28339, time=302.2sec]
2020-07-28 19:09:58,777 FAILED: bins/opt/async_end2end_test --gtest_filter=AsyncEnd2end/AsyncEnd2endTest.SimpleClientStreamingWithCoalescingApi/8  GRPC_POLL_STRATEGY=poll
```

---

A few runs failed super early with:

```
+ echo 'Running run_tests.py in workspace workspace_c_macos_dbg_native'
Running run_tests.py in workspace workspace_c_macos_dbg_native
+ python workspace_c_macos_dbg_native/tools/run_tests/run_tests.py -t -j 4 -x ../run_tests/c_macos_dbg_native/sponge_log.xml --report_suite_name c_macos_dbg_native -l c -c dbg --iomgr_platform native --max_time 3600
2020-07-28 16:22:03,420 START: make
2020-07-28 16:22:05,058 Makefile:13686: *** multiple target patterns.  Stop.

2020-07-28 16:22:05,058 FAILED: make [ret=2, pid=4652, time=1.6sec]
2020-07-28 16:22:05,058 FAILED: Some tests failed
```

https://g3c.corp.google.com/results/invocations/241ff744-d7d1-4398-a5d9-d00ec4e1c318/targets/github%2Fgrpc%2Ftoplevel_run_tests_invocations%2Frun_tests_c_macos_dbg_native;config=default/tests

---

Another common error seems to be that it just said "Tool failed":

https://source.cloud.google.com/results/invocations/a923e956-6914-4ca5-aea5-cfa4e797b42a/targets

**Comment by jtattermusch** [comment] 2020-07-29 10:10
The `client_callback_end2end_test` should have been fixed by the revert here: https://github.com/grpc/grpc/pull/23651
The corresponding internal bug is here: b/161724973

The `async_end2end_test` failures seem new and we only started seeing them very recently:

The first failure I see is from 2020-07-28 14:57:12 UTC
![image](https://user-images.githubusercontent.com/9939684/88787580-5d5d9300-d194-11ea-80df-4903c92e71b8.png)

**Comment by markdroth** [comment] 2020-07-29 22:45
Esun, could this be related to the absl synchronization change?

**Comment by jtattermusch** [comment] 2020-07-30 08:23
Actually both, `client_callback_end2end_test` and `async_end2end_test` breakages seem new.
The old client_callback_end2end_test flake has been fixed by #23651 but there is a new flake that only started very recenty:

![image](https://user-images.githubusercontent.com/9939684/88899530-76c31580-d24e-11ea-8b92-247ece2ebc54.png)

**Comment by jtattermusch** [comment] 2020-07-30 09:18
This is very likely caused by https://github.com/grpc/grpc/pull/23372 (see my analysis in b/162484508) and I've also found that the PR has caused other breakages.

**Closed** 2020-07-31 00:00 UTC
Labels: disposition/BUILDCOP, kind/bug, lang/c++, priority/P1, priority/P2

**Comment by stanley-cheung** [comment] 2020-08-01 00:53
Verified that "Basic Tests C/C++ MacOS" is green for both pull_request and master now.
