### ISSUE TITLE
generate_projects.sh requires git submodules to be initted

### ISSUE THREAD

**Issue by Capstan** [grpc/grpc#24654] opened 2020-11-03 19:03 UTC
re: https://github.com/grpc/grpc/blob/596dcc555de7f9d23c1b5170fdb880564c0d2f14/src/boringssl/gen_build_yaml.py#L24

Despite the [build instructions](https://github.com/grpc/grpc/blob/master/BUILDING.md#clone-the-repository-including-submodules) stating

> You only need to worry about downloading submodules if you're building with something else than `bazel` (e.g. `cmake`).

if you try to regenerate the projects by calling `tools/buildgen/generate_projects.sh`, you will get an error like:

```
  File "src/boringssl/gen_build_yaml.py", line 26, in <module>
    with open(sources_path, 'r') as s:
FileNotFoundError: [Errno 2] No such file or directory: '/…/grpc/third_party/boringssl-with-bazel/sources.json'
```

if you have not initialized the submodules.

Is there a way to get these sources the way bazel gets them, or is this an outlier, and should require those submodules to be inited? It seems that `tools/buildgen/generate_projects.sh` does end up calling `bazel` repeatedly as a part of its execution…

**Comment by markdroth** [comment] 2020-12-01 01:02
I suspect the build instructions are just out of date.  Nico and/or Jan, can you please take a look?  Thanks!

**Comment by jtattermusch** [comment] 2020-12-01 16:06
@Capstan    yes, `tools/buildgen/generate_projects.sh` requires the submodules to be initialized (that's a hard requirement due to what it does and it would be very hard to change - feel free to inspect its internals yourself).

Nevertheless, I believe the documentation is not incorrect - AFAIK you really don't need the submodules initialized to be able to build with bazel (e.g. `bazel build //test/...` - you can try that).  That doesn't mean that you won't need the submodule for other development tasks (such as regenerating the generated code with `tools/buildgen/generate_projects.sh`) -  generate_projects.sh does call bazel internally, but that's an implementation detail - the bazel build itself doesn't need the submodules at all.

**Comment by jtattermusch** [comment] 2021-03-18 11:09
Closing as things are working as intended.  `tools/buildgen/generate_projects.sh` only needs to be run by contributors (you don't need it to build from source) and if you're contributing to grpc, running `git submodule update --init` doesn't seem like much to ask ;-).

**Closed by jtattermusch** 2021-03-18 11:09 UTC
Labels: area/build, kind/internal cleanup, lang/other, priority/P2
