### ISSUE TITLE
[build failure] FAILED: run_tests_python_macos_opt_native

### ISSUE THREAD

**Issue by AspirinSJL** [grpc/grpc#14965] opened 2018-04-06 16:48 UTC
Looks like the build fails because we can't install some Python packages.

https://sponge.corp.google.com/target?id=6df9b7f8-977b-463b-b507-37ed614fd480&target=grpc/core/pull_request/macos/grpc_basictests_opt&searchFor=&show=FAILED&sortBy=STATUS

```
+ python3.4 -m virtualenv py34_native
Using base prefix '/Library/Frameworks/Python.framework/Versions/3.4'
New python executable in /Volumes/BuildData/tmpfs/src/github/grpc/workspace_python_macos_opt_native/py34_native/bin/python3.4
Also creating executable in /Volumes/BuildData/tmpfs/src/github/grpc/workspace_python_macos_opt_native/py34_native/bin/python
Installing setuptools, pip, wheel...
  Complete output from command /Volumes/BuildData/t...native/bin/python3.4 - setuptools pip wheel:
  Collecting setuptools
  Using cached setuptools-39.0.1-py2.py3-none-any.whl
Collecting pip
  HTTP error 403 while getting https://pypi.python.org/packages/ac/95/a05b56bb975efa78d3557efa36acaf9cf5d2fd0ee0062060493687432e03/pip-9.0.3-py2.py3-none-any.whl#md5=d512ceb964f38ba31addb8142bc657cb (from https://pypi.python.org/simple/pip/) (requires-python:>=2.6,!=3.0.*,!=3.1.*,!=3.2.*)
  Could not install requirement pip from https://pypi.python.org/packages/ac/95/a05b56bb975efa78d3557efa36acaf9cf5d2fd0ee0062060493687432e03/pip-9.0.3-py2.py3-none-any.whl#md5=d512ceb964f38ba31addb8142bc657cb because of error 403 Client Error: Brownout of Legacy TLS for url: https://pypi.python.org/packages/ac/95/a05b56bb975efa78d3557efa36acaf9cf5d2fd0ee0062060493687432e03/pip-9.0.3-py2.py3-none-any.whl
Could not install requirement pip from https://pypi.python.org/packages/ac/95/a05b56bb975efa78d3557efa36acaf9cf5d2fd0ee0062060493687432e03/pip-9.0.3-py2.py3-none-any.whl#md5=d512ceb964f38ba31addb8142bc657cb because of HTTP error 403 Client Error: Brownout of Legacy TLS for url: https://pypi.python.org/packages/ac/95/a05b56bb975efa78d3557efa36acaf9cf5d2fd0ee0062060493687432e03/pip-9.0.3-py2.py3-none-any.whl for URL https://pypi.python.org/packages/ac/95/a05b56bb975efa78d3557efa36acaf9cf5d2fd0ee0062060493687432e03/pip-9.0.3-py2.py3-none-any.whl#md5=d512ceb964f38ba31addb8142bc657cb (from https://pypi.python.org/simple/pip/) (requires-python:>=2.6,!=3.0.*,!=3.1.*,!=3.2.*)
----------------------------------------
...Installing setuptools, pip, wheel...done.
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/virtualenv.py", line 2328, in <module>
    main()
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/virtualenv.py", line 713, in main
    symlink=options.symlink)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/virtualenv.py", line 945, in create_environment
    download=download,
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/virtualenv.py", line 901, in install_wheel
    call_subprocess(cmd, show_stdout=False, extra_env=env, stdin=SCRIPT)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/virtualenv.py", line 797, in call_subprocess
    % (cmd_desc, proc.returncode))
OSError: Command /Volumes/BuildData/t...native/bin/python3.4 - setuptools pip wheel failed with error code 1
+ python -m virtualenv -p python3.4 py34_native
Using base prefix '/Library/Frameworks/Python.framework/Versions/3.4'
New python executable in /Volumes/BuildData/tmpfs/src/github/grpc/workspace_python_macos_opt_native/py34_native/bin/python3.4
Not overwriting existing python script /Volumes/BuildData/tmpfs/src/github/grpc/workspace_python_macos_opt_native/py34_native/bin/python (you must use /Volumes/BuildData/tmpfs/src/github/grpc/workspace_python_macos_opt_native/py34_native/bin/python3.4)
Installing setuptools, pip, wheel...done.
Running virtualenv with interpreter /usr/local/bin/python3.4
++ script_realpath py34_native/bin/python
+++ command -v realpath
++ '[' -x /usr/local/bin/realpath ']'
++ realpath py34_native/bin/python
+ VENV_PYTHON=/Volumes/BuildData/tmpfs/src/github/grpc/workspace_python_macos_opt_native/py34_native/bin/python3.4
+ case "$VENV" in
+ /Volumes/BuildData/tmpfs/src/github/grpc/workspace_python_macos_opt_native/py34_native/bin/python3.4 -m pip install --upgrade pip==9.0.1
Collecting pip==9.0.1
  Using cached pip-9.0.1-py2.py3-none-any.whl
Installing collected packages: pip
  Found existing installation: pip 9.0.3
    Uninstalling pip-9.0.3:
      Successfully uninstalled pip-9.0.3
Successfully installed pip-9.0.1
You are using pip version 9.0.1, however version 9.0.3 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
+ /Volumes/BuildData/tmpfs/src/github/grpc/workspace_python_macos_opt_native/py34_native/bin/python3.4 -m pip install setuptools
Requirement already satisfied: setuptools in ./py34_native/lib/python3.4/site-packages
You are using pip version 9.0.1, however version 9.0.3 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
+ /Volumes/BuildData/tmpfs/src/github/grpc/workspace_python_macos_opt_native/py34_native/bin/python3.4 -m pip install cython
Collecting cython
  HTTP error 403 while getting https://pypi.python.org/packages/65/78/da1a997402336c3fdccbe9301618003feff7f4f3110c95a0fe7a68a2eee7/Cython-0.28.1-cp34-cp34m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl#md5=9199b0d61483526a0b9c376cd1152d3a (from https://pypi.python.org/simple/cython/)
  Could not install requirement cython from https://pypi.python.org/packages/65/78/da1a997402336c3fdccbe9301618003feff7f4f3110c95a0fe7a68a2eee7/Cython-0.28.1-cp34-cp34m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl#md5=9199b0d61483526a0b9c376cd1152d3a because of error 403 Client Error: Brownout of Legacy TLS for url: https://pypi.python.org/packages/65/78/da1a997402336c3fdccbe9301618003feff7f4f3110c95a0fe7a68a2eee7/Cython-0.28.1-cp34-cp34m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl
Could not install requirement cython from https://pypi.python.org/packages/65/78/da1a997402336c3fdccbe9301618003feff7f4f3110c95a0fe7a68a2eee7/Cython-0.28.1-cp34-cp34m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl#md5=9199b0d61483526a0b9c376cd1152d3a because of HTTP error 403 Client Error: Brownout of Legacy TLS for url: https://pypi.python.org/packages/65/78/da1a997402336c3fdccbe9301618003feff7f4f3110c95a0fe7a68a2eee7/Cython-0.28.1-cp34-cp34m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl for URL https://pypi.python.org/packages/65/78/da1a997402336c3fdccbe9301618003feff7f4f3110c95a0fe7a68a2eee7/Cython-0.28.1-cp34-cp34m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl#md5=9199b0d61483526a0b9c376cd1152d3a (from https://pypi.python.org/simple/cython/)
You are using pip version 9.0.1, however version 9.0.3 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.

2018-04-05 11:36:46,114 FAILED: /Volumes/BuildData/tmpfs/src/github/grpc/workspace_python_macos_opt_native/tools/run_tests/helper_scripts/build_python.sh [ret=1, pid=75195, time=8.5sec]
2018-04-05 11:36:46,119 FAILED: Some tests failed

2018-04-05 11:36:46,152 FAILED: run_tests_python_macos_opt_native [ret=1, pid=64035, time=425.1sec]
```

**Comment by nathanielmanistaatgoogle** [comment] 2018-04-06 17:08
I think this is a duplicate of [issue 14815](https://github.com/grpc/grpc/issues/14815) but @matt-kwong, @mehrdada, and @kpayson64 would be able to confirm.

**Comment by mehrdada** [comment] 2018-04-06 17:09
Looks like it to me as well. Closing as a dupe--please reopen if you think otherwise.

**Closed by mehrdada** 2018-04-06 17:09 UTC
Labels: infra/BUILDPONY, lang/Python, platform/macOS
