### ISSUE TITLE
python_linux_opt_native.py27.test.protoc_plugin._split_definitions_test.SplitCommonTest

### ISSUE THREAD

**Issue by murgatroid99** [grpc/grpc#11170] opened 2017-05-16 22:23 UTC
https://grpc-testing.appspot.com/job/gRPC_master_linux/2409/testReport/junit/(root)/python_linux_opt_native/py27_test_protoc_plugin__split_definitions_test_SplitCommonTest/

```
Traceback (most recent call last):
  File "/usr/lib/python2.7/unittest/case.py", line 329, in run
    testMethod()
  File "/var/local/git/grpc/src/python/grpcio_tests/tests/protoc_plugin/_split_definitions_test.py", line 150, in testCall
    response = stub.Call(request)
  File "/var/local/git/grpc/py27/local/lib/python2.7/site-packages/grpc/_channel.py", line 507, in __call__
    return _end_unary_response_blocking(state, call, False, deadline)
  File "/var/local/git/grpc/py27/local/lib/python2.7/site-packages/grpc/_channel.py", line 455, in _end_unary_response_blocking
    raise _Rendezvous(state, None, None, deadline)
_Rendezvous: <_Rendezvous of RPC that terminated with (StatusCode.UNIMPLEMENTED, Method not found!)>
```

**Comment by nathanielmanistaatgoogle** [comment] 2017-05-16 22:36
I think this a duplicate of [issue 10049](https://github.com/grpc/grpc/issues/10049).

**Closed by nathanielmanistaatgoogle** 2017-05-16 22:36 UTC
Labels: BUILDPONY, python
