### ISSUE TITLE
Makefile install generates incorrect so version links

### ISSUE THREAD

**Issue by wpbrown** [grpc/grpc#10942] opened 2017-05-02 03:56 UTC
The .so major version symlinks are correctly generated in the build directory for non-core libraries like libgrpc++.so.1 However the make install creates incorrect links (libgrpc++.so.3) for release 1.3.0. Building against this links .so.1 and then fails to find .so.1 at runtime.

The problem appears to be in the Makefile template. During install the core version is always pulled:
```
$(Q) ln -sf $(SHARED_PREFIX)${lib.name}$(SHARED_VERSION_${lang_to_var[lib.language]}).$(SHARED_EXT_${lang_to_var[lib.language]}) $(prefix)/lib/lib${lib.name}.so.${settings.core_version.major}
```
where as during build the lang_to_var mapping is used to get the cpp_version.
```
$(Q) ln -sf $(SHARED_PREFIX)${lib.name}$(SHARED_VERSION_${lang_to_var[lib.language]}).$(SHARED_EXT_${lang_to_var[lib.language]}) ${out_libbase}.so.${settings.get(lang_to_var[lib.language].lower() + '_version').major}
```

**Comment by pva** [comment] 2017-06-09 08:52
BTW, is build from Makefile supported or should we use cmake instead?

**Comment by jeffmendoza** [comment] 2017-06-13 00:22
Looks like the problem is here: https://github.com/grpc/grpc/blob/master/templates/Makefile.template#L1337

The `settings.core_version.major` is used for symlinks, this is correct for C but not C++. (Why are the versions different?).

For some unknown reason, I got the correct symlinks with `make install` on debian, but not on fedora.
```
[fedora@fedora helloworld]$ ls -l /usr/local/lib/libgrpc++.*
-rwxr-xr-x. 1 root root 1809138 Jun 12 23:54 /usr/local/lib/libgrpc++.a
lrwxrwxrwx. 1 root root      18 Jun 12 23:54 /usr/local/lib/libgrpc++.so -> libgrpc++.so.1.3.2
-rwxr-xr-x. 1 root root  737272 Jun 12 23:54 /usr/local/lib/libgrpc++.so.1.3.2
lrwxrwxrwx. 1 root root      18 Jun 12 23:54 /usr/local/lib/libgrpc++.so.3 -> libgrpc++.so.1.3.2
```

```
jeffmendoza@debian:~$ ls -l /usr/local/lib/libgrpc++.*
-rwxr-xr-x 1 root root 1805448 Jun  8 22:18 /usr/local/lib/libgrpc++.a
lrwxrwxrwx 1 root root      18 Jun  8 22:18 /usr/local/lib/libgrpc++.so -> libgrpc++.so.1.3.2
lrwxrwxrwx 1 root root      14 Jun  8 22:04 /usr/local/lib/libgrpc++.so.1 -> libgrpc++.so.3
-rwxr-xr-x 1 root root  733240 Jun  8 22:18 /usr/local/lib/libgrpc++.so.1.3.2
lrwxrwxrwx 1 root root      18 Jun  8 22:18 /usr/local/lib/libgrpc++.so.3 -> libgrpc++.so.1.3.2
```

**Comment by d1xlord** [comment] 2017-07-03 07:00
Having issue with Fedora, have to manually create symlinks for it to work

**Comment by DJWalker42** [comment] 2017-10-20 11:32
Same issue when building on OpenSuse 13.2 following the install from source instructions. 

I think this might be confusion between the version numbers of 'libgrpc' and 'libgrpc++' which are different, in my case: 
```
> ls -l /usr/local/lib
lrwxrwxrwx. 1 root root        16 Oct 20 08:25 libgrpc.so -> libgrpc.so.4.0.0
lrwxrwxrwx. 1 root root        18 Oct 20 08:37 libgrpc++.so -> libgrpc++.so.1.6.7
-rwxr-xr-x. 1 root root    336568 Oct 20 08:37 libgrpc++.so.1.6.7
lrwxrwxrwx. 1 root root        16 Oct 20 08:25 libgrpc.so.4 -> libgrpc.so.4.0.0
lrwxrwxrwx. 1 root root        18 Oct 20 08:37 libgrpc++.so.4 -> libgrpc++.so.1.6.7
-rwxr-xr-x. 1 root root   2283504 Oct 20 08:25 libgrpc.so.4.0.0
```
As you can see 'libgrpc' has a major version of 4 whereas 'libgrpc++' has major version of 1. 

In the (current) Makefile template [here](https://github.com/grpc/grpc/blob/master/templates/Makefile.template#L1337) you have the following code:
```
  ifeq ($(SYSTEM),MINGW32)
  	$(Q) $(INSTALL) $(LIBDIR)/$(CONFIG)/lib${lib.name}$(SHARED_VERSION_${lang_to_var[lib.language]})-dll.a $(prefix)/lib/lib${lib.name}.a
  else ifneq ($(SYSTEM),Darwin)
  	$(Q) ln -sf $(SHARED_PREFIX)${lib.name}$(SHARED_VERSION_${lang_to_var[lib.language]}).$(SHARED_EXT_${lang_to_var[lib.language]}) $(prefix)/lib/lib${lib.name}.so.${settings.core_version.major}
  	$(Q) ln -sf $(SHARED_PREFIX)${lib.name}$(SHARED_VERSION_${lang_to_var[lib.language]}).$(SHARED_EXT_${lang_to_var[lib.language]}) $(prefix)/lib/lib${lib.name}.so
  endif
```
which sets the shared library name using the variable `${settings.core_version.major}`. On my OpenSuse system this generates the following lines in the Makefile for the 'libgrpc++' soft link creation: 

```
ifeq ($(SYSTEM),MINGW32)
	$(Q) $(INSTALL) $(LIBDIR)/$(CONFIG)/libgrpc++$(SHARED_VERSION_CPP)-dll.a $(prefix)/lib/libgrpc++.a
else ifneq ($(SYSTEM),Darwin)
	$(Q) ln -sf $(SHARED_PREFIX)grpc++$(SHARED_VERSION_CPP).$(SHARED_EXT_CPP) $(prefix)/lib/libgrpc++.so.4
	$(Q) ln -sf $(SHARED_PREFIX)grpc++$(SHARED_VERSION_CPP).$(SHARED_EXT_CPP) $(prefix)/lib/libgrpc++.so
endif
```
which is wrong for the libgrpc++ library (should be 1 not 4)


Further on in the Makefile template, found [here](https://github.com/grpc/grpc/blob/master/templates/Makefile.template#L1597), the code reads 
```
  ifeq ($(SYSTEM),Darwin)
  	$(Q) ${ld} ${ldflags} -L$(LIBDIR)/$(CONFIG) -install_name $(SHARED_PREFIX)${lib.name}$(SHARED_VERSION_${lang_to_var[lib.language]}).$(SHARED_EXT_${lang_to_var[lib.language]}) -dynamiclib -o ${out_libbase}.$(SHARED_EXT_${lang_to_var[lib.language]}) ${common}${link_libs}
  else
  	$(Q) ${ld} ${ldflags} -L$(LIBDIR)/$(CONFIG) -shared -Wl,-soname,lib${lib.name}.so.${settings.get(lang_to_var[lib.language].lower() + '_version').major} -o ${out_libbase}.$(SHARED_EXT_${lang_to_var[lib.language]}) ${common}${link_libs}
  	$(Q) ln -sf $(SHARED_PREFIX)${lib.name}$(SHARED_VERSION_${lang_to_var[lib.language]}).$(SHARED_EXT_${lang_to_var[lib.language]}) ${out_libbase}.so.${settings.get(lang_to_var[lib.language].lower() + '_version').major}
  	$(Q) ln -sf $(SHARED_PREFIX)${lib.name}$(SHARED_VERSION_${lang_to_var[lib.language]}).$(SHARED_EXT_${lang_to_var[lib.language]}) ${out_libbase}.so
  endif
```
This uses `${settings.get(lang_to_var[lib.language].lower() + '_version').major}` to obtain the major version.  On my OpenSuse system this generates the following lines for the 'libgrpc++' linking variables:
```
ifeq ($(SYSTEM),Darwin)
	$(Q) $(LDXX) $(LDFLAGS) -L$(LIBDIR)/$(CONFIG) -install_name $(SHARED_PREFIX)grpc++$(SHARED_VERSION_CPP).$(SHARED_EXT_CPP) -dynamiclib -o $(LIBDIR)/$(CONFIG)/libgrpc++$(SHARED_VERSION_CPP).$(SHARED_EXT_CPP) $(LIBGRPC++_OBJS) $(ZLIB_MERGE_LIBS) $(CARES_MERGE_LIBS) $(LDLIBSXX) $(LDLIBS_PROTOBUF) $(LDLIBS) -lgrpc -lgpr
else
	$(Q) $(LDXX) $(LDFLAGS) -L$(LIBDIR)/$(CONFIG) -shared -Wl,-soname,libgrpc++.so.1 -o $(LIBDIR)/$(CONFIG)/libgrpc++$(SHARED_VERSION_CPP).$(SHARED_EXT_CPP) $(LIBGRPC++_OBJS) $(ZLIB_MERGE_LIBS) $(CARES_MERGE_LIBS) $(LDLIBSXX) $(LDLIBS_PROTOBUF) $(LDLIBS) -lgrpc -lgpr
	$(Q) ln -sf $(SHARED_PREFIX)grpc++$(SHARED_VERSION_CPP).$(SHARED_EXT_CPP) $(LIBDIR)/$(CONFIG)/libgrpc++$(SHARED_VERSION_CPP).so.1
	$(Q) ln -sf $(SHARED_PREFIX)grpc++$(SHARED_VERSION_CPP).$(SHARED_EXT_CPP) $(LIBDIR)/$(CONFIG)/libgrpc++$(SHARED_VERSION_CPP).so
endif
```
This tries to used the shared library that is referenced by the correctly named link `libgrpc++.so.1` (correct as in the major version number of the actual library is 1) but the actual link is the incorrectly named 'libgrpc++.so.4`.

**Comment by DJWalker42** [comment] 2017-10-20 13:03
After rereading @jeffmendoza's comment I noticed that the debian build has the extra soft link `libgrpc++.so.1 -> libgrpc++.so.3` which makes the library lookup work and looks like a patch. So I checked my OpenSuse 13.2 build and found similar double indirections:
```
> ls -l /usr/local/lib/libgrpc++*
-rwxr-xr-x 1 root root  981912 Oct 19 10:14 /usr/local/lib/libgrpc++.a
lrwxrwxrwx 1 root root      18 Oct 19 10:14 /usr/local/lib/libgrpc++.so -> libgrpc++.so.1.6.7
lrwxrwxrwx 1 root root      14 Oct 19 10:14 /usr/local/lib/libgrpc++.so.1 -> libgrpc++.so.4
-rwxr-xr-x 1 root root  314112 Oct 19 10:14 /usr/local/lib/libgrpc++.so.1.6.7
lrwxrwxrwx 1 root root      18 Oct 19 10:14 /usr/local/lib/libgrpc++.so.4 -> libgrpc++.so.1.6.7
-rwxr-xr-x 1 root root 4322516 Oct 19 10:14 /usr/local/lib/libgrpc++_cronet.a
lrwxrwxrwx 1 root root      25 Oct 19 10:14 /usr/local/lib/libgrpc++_cronet.so -> libgrpc++_cronet.so.1.6.7
lrwxrwxrwx 1 root root      21 Oct 19 10:14 /usr/local/lib/libgrpc++_cronet.so.1 -> libgrpc++_cronet.so.4
-rwxr-xr-x 1 root root 1001860 Oct 19 10:14 /usr/local/lib/libgrpc++_cronet.so.1.6.7
lrwxrwxrwx 1 root root      25 Oct 19 10:14 /usr/local/lib/libgrpc++_cronet.so.4 -> libgrpc++_cronet.so.1.6.7
-rwxr-xr-x 1 root root  280744 Oct 19 10:14 /usr/local/lib/libgrpc++_error_details.a
lrwxrwxrwx 1 root root      32 Oct 19 10:14 /usr/local/lib/libgrpc++_error_details.so -> libgrpc++_error_details.so.1.6.7
lrwxrwxrwx 1 root root      28 Oct 19 10:14 /usr/local/lib/libgrpc++_error_details.so.1 -> libgrpc++_error_details.so.4
-rwxr-xr-x 1 root root 1523388 Oct 19 10:14 /usr/local/lib/libgrpc++_error_details.so.1.6.7
lrwxrwxrwx 1 root root      32 Oct 19 10:14 /usr/local/lib/libgrpc++_error_details.so.4 -> libgrpc++_error_details.so.1.6.7
-rwxr-xr-x 1 root root  446224 Oct 19 10:14 /usr/local/lib/libgrpc++_reflection.a
lrwxrwxrwx 1 root root      29 Oct 19 10:14 /usr/local/lib/libgrpc++_reflection.so -> libgrpc++_reflection.so.1.6.7
lrwxrwxrwx 1 root root      25 Oct 19 10:14 /usr/local/lib/libgrpc++_reflection.so.1 -> libgrpc++_reflection.so.4
-rwxr-xr-x 1 root root 1728596 Oct 19 10:14 /usr/local/lib/libgrpc++_reflection.so.1.6.7
lrwxrwxrwx 1 root root      29 Oct 19 10:14 /usr/local/lib/libgrpc++_reflection.so.4 -> libgrpc++_reflection.so.1.6.7
-rwxr-xr-x 1 root root  871830 Oct 19 10:14 /usr/local/lib/libgrpc++_unsecure.a
lrwxrwxrwx 1 root root      27 Oct 19 10:14 /usr/local/lib/libgrpc++_unsecure.so -> libgrpc++_unsecure.so.1.6.7
lrwxrwxrwx 1 root root      23 Oct 19 10:14 /usr/local/lib/libgrpc++_unsecure.so.1 -> libgrpc++_unsecure.so.4
-rwxr-xr-x 1 root root  268852 Oct 19 10:14 /usr/local/lib/libgrpc++_unsecure.so.1.6.7
lrwxrwxrwx 1 root root      27 Oct 19 10:14 /usr/local/lib/libgrpc++_unsecure.so.4 -> libgrpc++_unsecure.so.1.6.7
```
These extra links are missing from the Scientific Linux build hence why it fails to find the shared libraries. Though why those extra links are missing is a mystery; comparing the generated Makefile on the OpenSuse OS to that generated on the Scientific Linux OS gave no insight (`diff` of the two files resulted in null output, i.e. the files are the same).

**Comment by sreecha** [comment] 2018-07-18 17:54
@wpbrown , is this issue still relevant ?

**Comment by sreecha** [comment] 2018-08-16 22:28
Closing this based on the update on 10/24/2017
>>Update 2017-10-24:
My issue was in my environment setup. Links were missing because the dynamic load library was not looking in /usr/local/lib for the shared libraries. I fixed this by appending /usr/local/lib to the /etc/ld.so.conf file.

**Closed by sreecha** 2018-08-16 22:28 UTC
Labels: area/build, infra/buildgen, kind/bug, lang/c++, priority/P3
