### ISSUE TITLE
Unity Package: System.Memory.dll version mismatch

### ISSUE THREAD

**Issue by discodonut** [grpc/grpc#21908] opened 2020-02-04 23:14 UTC
### What version of gRPC and what language are you using?
grpc_unity_package.2.27.0-dev
C#

### What operating system (Linux, Windows,...) and version?
Windows 10 2004

### What runtime / compiler are you using (e.g. python version or version of gcc)
Unity 2019.3.0f6

### What did you do?
I downloaded the last unity package (2.27.0) from https://packages.grpc.io/, extracted it to the Asset/Plugins folder.

### What did you expect to see?
The plugin to work.

### What did you see instead?
The Google.Protobuf dll failed to load with the following messages:
```
Error: Could not load signature of Google.Protobuf.ByteString:get_Span due to: Could not load file or assembly 'System.Memory, Version=4.0.1.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. assembly:System.Memory, Version=4.0.1.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51 type:<unknown type> member:(null) signature:<none>
Unloading broken assembly Assets/Plugins/Google.Protobuf/lib/net45/Google.Protobuf.dll, this assembly can cause crashes in the runtime
```
It appears that Google.Protobuf.dll has an assembly reference to version 4.0.1.0 (4.5.2)of System.Memory, but Grpc.Core has a reference to version 4.0.1.1 (4.5.3), and that's the version that is included in the unity package, so the version used by Protobuf is missing.

### Anything else we should know about your project / environment?
I tried upgrading the reference in the Google.Protobuf project to 4.0.1.1 in Visual Studio, but it gave the following error:
```
Severity	Code	Description	Project	File	Line	Suppression State
Error	NU1202	Package System.Memory 4.5.3 is not compatible with netstandard1.0 (.NETStandard,Version=v1.0). Package System.Memory 4.5.3 supports:
  - netcoreapp2.1 (.NETCoreApp,Version=v2.1)
  - netstandard1.1 (.NETStandard,Version=v1.1)
  - netstandard2.0 (.NETStandard,Version=v2.0)	Google.Protobuf	<removed>\code\protobuf\csharp\src\Google.Protobuf\Google.Protobuf.csproj	1	
```

Downgrading the version used by Grpc seemed to work locally, but that seems less than desirable. Unity doesn't seem to support loading multiple versions of the same dll or bindingRedirects.

**Comment by filharveyrobin** [comment] 2020-02-12 23:27
when you say downgrading "the version used by Grpc". What did you do here, as I'm coming across this error as well.

**Comment by discodonut** [comment] 2020-02-13 01:46
I cloned the repo, opened the Grpc solution, then chose “manage nuget
packages” and chose the earlier version. I had to do it on Grpc.Core.Api
first, then Grpc.Core, due to a similar error.

**Comment by filharveyrobin** [comment] 2020-02-13 22:52
Can you possibly share the compiled packages, as I'm still having issues after building.

**Comment by filharveyrobin** [comment] 2020-02-13 23:22
Got it.

**Comment by teiserse** [comment] 2020-02-19 10:57
Hi, I'm still waiting for the fix in repo, but changing the versions manually doesn't seem to be working for me. I follow the instructions to compile the .dlls for C#, but running `build_unitypackage.bat` just leaves me with the error:
```
C:\Users\Edvinas Teiserskis\Documents\grpc\src\csharp>copy /Y nativelibs\csharp_ext_linux_x86\libgrpc_csharp_ext.so unitypackage\unitypackage_skeleton\Plugins\Grpc.Core\runtimes\linux\x86\libgrpc_csharp_ext.so   || goto :error
The system cannot find the path specified.
```
I don't see this file or any of the other ones copied over by the .bat file anywhere, and the only reference I can see to `libgrpc` is within the C# `Grpc.Core.csproj` file, which isn't leading me anywhere. Can someone point me where I'm going wrong?

**Comment by filharveyrobin** [comment] 2020-02-20 23:56
Would be nice to have official released working build. Also with the ones I've build seem to be having issues with Async RPC calls, it is freezing, I'm assuming this is due to my builds.

**Comment by filharveyrobin** [comment] 2020-02-24 21:23
Still seeing the same issue in 2.28.0

**Comment by Codes-Breaker** [comment] 2020-02-25 04:34
I just downloaded 2.28.0, and it happens to me as well... Unity Version: 2019.3.0f1

**Comment by Codes-Breaker** [comment] 2020-02-25 12:11
`Error: Could not load signature of Google.Protobuf.ByteString:get_Span due to: Could not load file or assembly 'System.Memory, Version=4.0.1.0, Culture=neutral, PublicKeyToken=' or one of its dependencies. assembly:System.Memory, Version=4.0.1.0, Culture=neutral, PublicKeyToken= type:<unknown type> member:(null) signature:<none>`
`Unloading broken assembly Assets/Plugins/Google.Protobuf/lib/net45/Google.Protobuf.dll, this assembly can cause crashes in the runtime
`

**Comment by LiorBanai** [comment] 2020-03-09 10:41
Same issue with latest nightly (grpc_unity_package.2.29.0-dev) and  unity 2019.3.0f6

**Comment by LiorBanai** [comment] 2020-03-10 18:12
FYI,
downgrading to grpc_unity_package.2.26.0-dev is working without errors.

**Comment by clu-osi** [comment] 2020-03-22 05:04
Same issue with the grpc_unity_package.2.29.0-dev and Unity 2019.3.5f1

**Comment by ice-github** [comment] 2020-04-20 23:02
I've checked grpc_unity_package.2.26.0-dev+Unity 2019.3.9f1 works.
https://packages.grpc.io/archive/2019/12/a02d6b9be81cbadb60eed88b3b44498ba27bcba9-edd81ac6-e3d1-461a-a263-2b06ae913c3f/index.xml

**Comment by truenoldor** [comment] 2020-05-20 09:20
No version works in unity 2020. Has anyone found a solution? depending on the version of grpc and system.memory - various errors. But if i add System.Runtime.CompilerServices.Unsafe.dll into Plugins, always get a Multiple precompiled assemblies error(with com.unity.collections). Also downloaded using NuGet. This did not help, although he selected the appropriate versions. still guilty of everything - com.unity.collections..

**Comment by andywatts** [comment] 2020-06-05 19:11
> No version works in unity 2020. Has anyone found a solution? depending on the version of grpc and system.memory - various errors. But if i add System.Runtime.CompilerServices.Unsafe.dll into Plugins, always get a Multiple precompiled assemblies error(with com.unity.collections). Also downloaded using NuGet. This did not help, although he selected the appropriate versions. still guilty of everything - com.unity.collections..

I moved collections from packageCache to the projects Packages folder.
I then deleted it's CompilerServices.Unsafe.dll.
It appears to fallback onto the grpc unsafe.dll in plugins.

**Comment by acrigney** [comment] 2020-06-19 02:07
This is a general bug that is happening to many people.

**Comment by discodonut** [comment] 2020-06-23 18:37
I was able to use ILMerge to merge the correct System.Runtime.CompilerServices.Unsafe.dll into the GRPC dlls (with the unsafe dll marked as internal), and that solved my problem, but then we moved away from using Gprc.

**Comment by acrigney** [comment] 2020-06-24 00:54
Wow I had this problem and I had no luck with using the assembly resolving
events. But ILMerge sounds complex?

**Comment by discodonut** [comment] 2020-06-24 01:12
It is, but I was able to write a script that did this:
1. Download Grpc and Google.Protobuf using the nuget command line tool, this pulls in dependent dlls.
2. Copy out all netstandard2.0 dlls to into their own subfolder, one folder for all Grpc dlls, one for Google.protobuf dlls.
3. Call ILMerge on each set of dlls with -internalize with exclude Grpc* and Google* respectively.

This will give you two new merged dlls, one for Grpc and one for Protobuf that can then be used in Unity.  It does mean that you will essentially have multiple copies of the dependent dlls in your project.  I'll see if I can release the script I wrote, but I don't see it as a good long-term solution.

**Comment by acrigney** [comment] 2020-06-24 01:22
Brilliant mate thanks heaps! Many people have had this bug, did you raise
it with microsoft, I will.

**Comment by SonnyAD** [comment] 2020-07-24 07:49
Hey @discodonut would you mind sharing your script?

**Comment by discodonut** [comment] 2020-07-31 19:01
My apologies for the delay:
https://gist.github.com/discodonut/d88279f956c1f353b96aab465f4eecf5

This has many caveats:
- It will only run on Windows due to ILMerge
- I have not tested the generated .dlls on any platform other than Windows
- The version numbers are all hardcoded just to avoid breaking the script if something changes

This script was really meant to be a band-aid until this bug could be fixed, not a true fix.

**Comment by jtattermusch** [comment] 2020-10-27 11:57
The originally reported issue looks like the same problem as https://github.com/grpc/grpc/pull/23198 was trying to solve.

I think the problem is solved by https://github.com/protocolbuffers/protobuf/pull/7940 (see https://github.com/grpc/grpc/pull/23198#issuecomment-716544310)

**Closed by jtattermusch** 2020-10-27 11:57 UTC
Labels: kind/bug, lang/C#, priority/P2

**Comment by freezy** [comment] 2021-02-22 12:26
Correct me if I'm wrong, but every time Unity (or GRPC, or Protobuf, for that matter) bumps `System.Memory` we will have the same problem over and over, no?

Wouldn't be bundling the deps with ILMerge/ILRepack like @discodonut described be a much more stable solution? If so, having it in CI instead of everybody having to figure it out for itself would be awesome! :)
