### ISSUE TITLE
Provide binaries as part of releases

### ISSUE THREAD

**Issue by peter-edge** [grpc/grpc#18260] opened 2019-03-05 22:02 UTC
### What version of gRPC and what language are you using?
 
v1.19.0

All supported languages
 
### What operating system (Linux, Windows,...) and version?
 
All
 
### What runtime / compiler are you using (e.g. python version or version of gcc)

N/A 
 

### What did you expect to see?
 
I would love if there were binaries included with each release for `grpc_.*_plugin` similar to how `protoc` is released at https://github.com/protocolbuffers/protobuf/releases. The build takes a long time, and this would help a lot of people. I searched existing GitHub issues for this request because I assumed this has been filed before, but I was surprised that I couldn't find an equivalent issue (maybe I've missed something).

I'm sure this has been considered and brought up before in some manner, but I want to say I do think this would be highly valuable, and it would be great if we could do this for future releases.

**Comment by nicolasnoble** [comment] 2019-03-05 23:03
These are the `grpc-tools` packages provided for each language. 

https://pypi.org/project/grpcio-tools/
https://rubygems.org/gems/grpc-tools/
https://www.npmjs.com/package/grpc-tools

**Comment by peter-edge** [comment] 2019-03-06 02:25
That's just for Python, Ruby, and Node, and uses language-specific install mechanisms. There's a bunch more from this repo as well:

```
grpc_cpp_plugin
grpc_csharp_plugin
grpc_node_plugin
grpc_objective_c_plugin
grpc_php_plugin
grpc_python_plugin
grpc_ruby_plugin
```

**Comment by zejji** [comment] 2019-03-06 10:31
A definite +1 from me. For the life of me I can't get the grpc_php_plugin to build and it's not realistic to expect users to debug the mammoth makefile when encountering environment-specific errors.

**Comment by johanbrandhorst** [comment] 2019-03-06 15:12
Definitely would make it easier to get started working with polyglot gRPC environments if you could get all the generators + protoc from the release page.

**Comment by nicolasnoble** [comment] 2019-03-06 16:04
I was giving you a few examples. All of them except for the C++ one should be available in their individual package corresponding to each language.

**Comment by peter-edge** [comment] 2019-03-06 16:09
The above doesn't cover:

- objective_c (which is special-cased and already being released partially with GitHub Releases)
- php
- csharp
- cpp

The above also requires usage of individual installation methods. Our goal here is to have this available, similar to `protoc`, from GitHub Releases. Is there a reason not to do this?

Some examples of what people are doing now to get around this:

- https://github.com/znly/docker-protobuf/blob/master/Dockerfile#L26 is building from source, which takes a long time
- https://github.com/uber/prototool/blob/dev/Dockerfile#L95 is relying on Alpine's edge testing repository to get around the build time, but this is not released on the same schedule as gRPC

**Comment by nicolasnoble** [comment] 2019-03-06 16:26
The reason is it's difficult to set up build pipelines. Doing a grpc release involves a lot of moving pieces due to the amount of languages and platforms. Adding a new vector of things to do isn't something that I am keen of burdening our team with, especially if this is a duplicate of what already exists in another form.

I am fairly certain there is a c# nugget package for grpc-tools, as well as a pecl one for php. If we are distributing a precompiled binary package for grpc in a language, there should be a corresponding grpc-tools package next to it, and this is usually documented in the corresponding quickstart document.

For example, in c#: https://grpc.io/docs/quickstart/csharp.html

> The example in this walkthrough already adds the necessary dependencies for you (Grpc, Grpc.Tools and Google.Protobuf NuGet packages).

**Comment by peter-edge** [comment] 2019-03-06 16:47
I can understand not wanting to burden the team, for sure. I might be missing something, but this doesn't seem like a huge task though.

You're already distributing one binary with GitHub Releases, the objective_c binary for Darwin https://github.com/grpc/grpc/releases/tag/v1.19.0 so this means there is already a pipeline to add binaries to GitHub Releases in some form. This just needs to be expanded to include the rest, and at least across Darwin and Linux. Since you're already compiling these for those language packages, that means the build process for released binaries is there as well for some of the other languages.

This would be hugely helpful, as at least speaking for myself, I've been hacking around the fact that there are no pre-compiled binaries for years, and I'm sure others have been too (see above). It's a one-time cost, and since there's already a pipeline to do so for one binary, it shouldn't be that difficult to do the rest.

Even if there is C#, that still leaves php and cpp not compiled.

**Comment by nicolasnoble** [comment] 2019-03-06 17:03
As I said, there should be one for php. C++ is the only exception because working with grpc in C++ requires compiling from source anyway. If there are missing packages beside C++, this should be the bug to report. 

Yes, there is existing pipeline for each package system, each in their own individual paradigm. Some may use docker. Some will require a certain version of the building tools incompatible with other languages. So the build is completely fragmented and siloed per language, which keeps it to a certain level of simplicity. 

Doing a final cross platform and polyglot gathering-and-publishing system however is not easy.

At the end of the day, you only want a single point of download instead of having to do `pip install ...`, `gem install ...` `npm install ...` for each language.

**Comment by peter-edge** [comment] 2019-03-06 17:17
This means I have to install pip, gem, npm, and any other language tools just to get the binaries for gRPC. This is way more complicated than the typical `curl` that I can do for other binaries, including `protoc`.

Lots of people are generating stubs in locations other than where the stubs are actually being used. This is a pretty common use case, including for integration testing. I think there's pretty bountiful evidence that a lot of people want this https://github.com/search?l=Makefile&q=grpc%2Fgrpc+make+plugins&type=Code and this would be very useful. People don't want to have to install other language tools to just get the gRPC binary, that's just as complicated as building from source, if not moreso.

**Comment by nicolasnoble** [comment] 2019-03-06 18:01
So you're saying you DO understand the complexity of the task you're asking us to accomplish.

**Comment by peter-edge** [comment] 2019-03-06 18:03
I mentioned I can understand not wanting to burden a team with unnecessary and difficult work, I am not sure this is unnecessary and I guess I don't understand the complexity here.

If this won't be fixed, we can close this issue, it was just a suggestion. I do think many in the community want this, however, and it's not the best that we have to work around this not being done.

**Comment by nicolasnoble** [comment] 2019-03-06 18:20
The request is still a valid one, despite its difficulty, which is why I didn't close it with a "won't fix".

**Comment by mehrdada** [comment] 2019-03-08 07:55
Binaries are built on master and put on https://packages.grpc.io every day, but not for specific builds. That should be good enough for many use-cases.

**Comment by peter-edge** [comment] 2019-03-08 08:10
People want the binary that matches the version of the library they are using. Master does not cover this.

That link also just provides the packages described above that we have explained why they are not adequate.

What we want is binaries for every release on GitHub Releases.

If this issue won’t be addressed, let’s close this.

**Comment by mehrdada** [comment] 2019-03-08 08:46
@peter-edge Fair point about `master`, but that can be addressed by adding releases to the pipeline. Should not be that much work.

I think you are mistaken about the latter point though: there are also a `protoc`+plugins zip/tar file that specifically contain the plugins (click on a Build ID and look at the first section). For example: 
https://packages.grpc.io/archive/2019/03/b52bac7888731e14a470fb19fd6e6cab4069c8d2-1ea8591d-4139-4fb1-bbdc-81efd0695e56/protoc/grpc-protoc_linux_x64-1.20.0-dev.tar.gz

**Comment by peter-edge** [comment] 2019-03-08 08:57
Ah yes I am - sorry about that. I’m on my phone, do those tarballs contain
all the grpc_.*_plugin binaries produced by make plugins? If so, then yep,
adding releases to the pipeline solves the problem! It would be a big help.

**Comment by mehrdada** [comment] 2019-03-08 09:02
@peter-edge Yes they contain `protoc` from the protobuf submodule in the repo at the commit point, plus all seven plugins that you can build with `make` for macOS, Linux, and Windows. The code underlying these rarely change so for quick testing where you don't have the tools this should be enough but I agree that the release pipeline should be changed to put releases on `packages.grpc.io` and then download from there and ship to the respective package managers.

**Comment by peter-edge** [comment] 2019-03-08 15:53
As described above, there are many use cases, one of which would be docker image building. I would never use master for plugin binaries and a stable release point for the library.

**Comment by mehrdada** [comment] 2019-03-08 19:55
@peter-edge I created https://github.com/grpc/grpc/issues/18307 to serve as a direct action item that would resolve this issue as well. @nicolasnoble I think we can close this issue in favor of that one. (cc: @jtattermusch fyi)

**Comment by peter-edge** [comment] 2019-03-08 19:57
Sgtm!

**Comment by srini100** [comment] 2019-03-13 22:14
Closing this in favor of  #18307.

**Closed by srini100** 2019-03-13 22:14 UTC
