### ISSUE TITLE
memory leak in GRPC client when receiving protobuf messages with multiple variables

### ISSUE THREAD

**Issue by bkbrookshire** [grpc/grpc#6290] opened 2016-04-26 14:11 UTC
A memory leak is being observed in the GRPC client when the protobuf message uses more than one variable.

Example proto message:
message Feature {
  // The name of the feature.
  string name = 1;

  // The point where the feature is detected.
  Point location = 2;
}

The helloworld example does not exhibit the memory leak since its protobuf HelloReply message only has one member (message).   However, using the route_guide example the leak can easily be seen.

Modify the grpc python example  (examples/python/route_guide/route_guide_client.py)  run function to continuously call the guide_get_feature().  This can be run against any route_guide server (tested against c++ and python with the same result).

def run():
  channel = implementations.insecure_channel('localhost', 50051)
  stub = route_guide_pb2.beta_create_RouteGuide_stub(channel)
  print("-------------- GetFeature --------------")
  while True:
    guide_get_feature(stub)

Expectation:
Steady state memory usage.

Actual:
Memory usage continuously grows

**Comment by sunwangme** [comment] 2016-05-05 09:53
nobody want to fix it?

**Comment by zj8487** [comment] 2016-05-16 08:21
@bkbrookshire have you solve the issue?

**Comment by bkbrookshire** [comment] 2016-05-16 10:29
No, I have not found the root cause.

**Comment by alamaison** [comment] 2016-05-25 17:57
Maybe this will be fixed by #6711.  Perhaps the leak doesn't happen with one field because the message is small enough to fit in the inline slice.  Once you add a second field it has to allocate a slice and it leaks that one.  Just a thought.

**Comment by nathanielmanistaatgoogle** [comment] 2016-06-17 21:53
Closing as a duplicate of [issue 5913](https://github.com/grpc/grpc/issues/5913).

**Closed by nathanielmanistaatgoogle** 2016-06-17 21:53 UTC
Labels: bug, python
