### ISSUE TITLE
aarch64 grpc Python package must be imported _before_ pyzmq

### ISSUE THREAD

**Issue by hanxiao** [grpc/grpc#26457] opened 2021-06-10 10:51 UTC
### What version of gRPC and what language are you using?

grpcio 1.38, 
Python 3.7,3.8,3.9

### What operating system (Linux, Windows,...) and version?

Armv8 Linux

### What runtime / compiler are you using (e.g. python version or version of gcc)

Python 3.7,3.8,3.9

### What did you do?

Here is a Dockerfile you can reproduce the bug

```dockerfile
# 3.7, 3.8, 3.9, all the same
ARG PY_VERSION=3.7

FROM python:${PY_VERSION}-slim

RUN pip install pyzmq grpcio

# zmq first and grpc second wont work!
# low-level error throws from the grpc package
# #5 0.217 free(): invalid pointer
# #5 0.219 Aborted
RUN python -c "import zmq, grpc"

# changing the order will work!
RUN python -c "import grpc, zmq"

```

Run docker build
```bash
docker buildx build --platform linux/arm64 -f bug.Dockerfile -t jinaai/grpcarm64:latest .
```

Will throw
```
------
 > [3/4] RUN python -c "import zmq, grpc":
#7 0.256 free(): invalid pointer
#7 0.257 Aborted
------
```

Notice that (1) the above low-level error is thrown from `grpc` (2) changing the import order will work
```diff
- RUN python -c "import zmq, grpc"
+ RUN python -c "import grpc, zmq"
```

### What did you expect to see?

I expect import orders should be completely irrelevant.

### Anything else we should know about your project / environment?

I found this bug when developing [Jina](https://github.com/jina-ai/jina), where `grpc` and `zmq` are used jointly. Note that this bug does not appear for `amd64` package.

For reference, I will post a [mirror issue on pyzmq project page](https://github.com/zeromq/pyzmq/issues/1546). But this bug seems more like a `grpc` bug rather than a `zmq` bug, as the error throws from `grpc`.

**Comment by jtattermusch** [comment] 2021-06-10 11:12
This is duplicate of https://github.com/grpc/grpc/issues/26279 (and we have a fix that will be released soon).

**Closed by jtattermusch** 2021-06-10 11:12 UTC
Labels: kind/bug, priority/P2
