### ISSUE TITLE
ObjC - Error returned from gRPC library should be more easily consumed

### ISSUE THREAD

**Issue by EliSchleifer** [grpc/grpc#3447] opened 2015-09-23 23:13 UTC
We should have an easier accessor to handle gRPC errors of NSError domain ios.grpc

Current errors look like this
Error Domain=io.grpc Code=13 "Internal error encountered." UserInfo=.... 

We could add a category method to NSError -> error.grpc_code that's typed as the NSEnum, so one gets switch autocompletion etc.

**Comment by jcanizales** [comment] 2015-09-23 23:19
Dupe of #3448

**Closed by jcanizales** 2015-09-23 23:19 UTC
