### ISSUE TITLE
interop matrix broken on master.

### ISSUE THREAD

**Issue by jtattermusch** [grpc/grpc#15147] opened 2018-04-23 06:06 UTC
https://source.cloud.google.com/results/invocations/42e7a546-b421-4f42-ad81-4d4ce64d265e/targets/github%2Fgrpc/tests

`bash: py27/bin/python: No such file or directory`

Probably introduced by https://github.com/grpc/grpc/pull/15115.

**Comment by jtattermusch** [comment] 2018-04-23 06:06
CC @adelez

**Comment by kpayson64** [comment] 2018-04-23 15:44
@mehrdada 
This can be fixed by modifying the Python matrix script to look at py27_native/bin/python

Will probably need to be backported to 1.11.0

**Comment by mehrdada** [comment] 2018-04-23 15:48
@kpayson64 I'm curious what's the root cause for the failure?

**Comment by adelez** [comment] 2018-04-24 05:32
Now all versions have this problem: https://fusion.corp.google.com/runanalysis/test/prod%3Agrpc%2Fcore%2Fmaster%2Flinux%2Fgrpc_interop_matrix/prod%3Agrpc%2Fcore%2Fmaster%2Flinux%2Fgrpc_interop_matrix/KOKORO/f7b56525-f3ae-4985-adda-a928f40984f9/1524531184143/prod%3Agrpc%2Fcore%2Fmaster%2Flinux%2Fgrpc_interop_matrix%20Build%20%2314/Target%20Transitions?target=github/grpc

**Closed** 2018-04-24 06:48 UTC
Labels: area/interop, priority/P1
