### ISSUE TITLE
The Jenkins artifact build job is failing to build docker images for the python artifacts

### ISSUE THREAD

**Issue by murgatroid99** [grpc/grpc#11371] opened 2017-06-01 19:39 UTC
https://grpc-testing.appspot.com/view/Artifacts/job/gRPC_build_artifacts/140

```
++ dirname tools/run_tests/dockerize/build_and_run_docker.sh
+ cd tools/run_tests/dockerize/../../..
++ pwd
+ git_root=/home/jenkins/workspace/gRPC_build_artifacts/platform/linux
+ cd -
/home/jenkins/workspace/gRPC_build_artifacts/platform/linux
++ basename tools/dockerfile/grpc_artifact_python_manylinux_x64
++ sha1sum tools/dockerfile/grpc_artifact_python_manylinux_x64/Dockerfile
++ cut -f1 '-d '
+ DOCKER_IMAGE_NAME=grpc_artifact_python_manylinux_x64_c048dbe29b2f9bd2277da1ea18cfd23377fcd5f9
+ '[' quay.io/pypa/manylinux1_x86_64 '!=' '' ']'
+ docker pull quay.io/pypa/manylinux1_x86_64
Using default tag: latest
latest: Pulling from pypa/manylinux1_x86_64
2068b24f564b: Already exists
d38e97296e4b: Pulling fs layer
ca9a0f625f59: Pulling fs layer
d38e97296e4b: Verifying Checksum
d38e97296e4b: Download complete
ca9a0f625f59: Verifying Checksum
ca9a0f625f59: Download complete
failed to register layer: link /var/lib/docker/overlay/a5f5b4d03cf46a065b282470d1f9b968f37172d5a4f64defdd32f472e92f1c0b/root/var/lib/yum/yumdb/h/561cfee96459ea0fa4aa4c12de9fd3a362a4baeb-hmaccalc-0.9.6-4.el5-x86_64/checksum_type /var/lib/docker/overlay/2b9f687765641dbdebfc30140178133c9898c8709bd73ca71dc3145ba3281cd7/tmproot068808681/var/lib/yum/yumdb/h/561cfee96459ea0fa4aa4c12de9fd3a362a4baeb-hmaccalc-0.9.6-4.el5-x86_64/checksum_type: too many links
```

**Comment by jtattermusch** [comment] 2017-06-02 18:21
Looks like some docker issue, I'd try rebooting linux worker14 (once a current job finishes there)

**Comment by jtattermusch** [comment] 2017-06-02 21:47
the issue is happening on other workers too

**Comment by kpayson64** [comment] 2017-06-05 20:32
It looks like this might be related to a full docker cache.  I'm clearing it out and trying to build again.

**Comment by matt-kwong** [comment] 2017-06-05 20:42
It was a Docker/VM issue, fixed in https://grpc-testing.appspot.com/view/Artifacts/job/gRPC_build_artifacts/169/#showFailuresLink

**Closed by matt-kwong** 2017-06-05 20:42 UTC
Labels: build, python, RELEASE BLOCKER
