### ISSUE TITLE
[C++] Support LZ4 compression algorithm

### ISSUE THREAD

**Issue by bluenight1994** [grpc/grpc#34356] opened 2023-09-14 21:50 UTC
### Is your feature request related to a problem? Please describe.
Is there a way to use compression algorithm like LZ4 in payload compression in gRPC C++? currently looks like only GZIP and INFLATE is supported as per https://grpc.github.io/grpc/cpp/compression__types_8h.html#ab9de0f68bfb1ef8ed09bd00643db14c9.

### Describe the solution you'd like
Enable LZ4 compression algorithm.

### Additional context
In our recent benchmark, we have seen LZ4 compression helped us to reduce call latency and network traffic. GZIP does not provides benefit according to testing. We have a dependency service which is using gRPC C++, so want to check if we can have LZ4 compression support.

**Comment by drfloob** [comment] 2023-09-14 22:01
Duplicate of https://github.com/grpc/grpc/issues/29767, an open feature request.

**Closed by drfloob** 2023-09-14 22:01 UTC
Labels: kind/enhancement, lang/c++, priority/P2, untriaged
