### ISSUE TITLE
example python script failed, ImportError: No module named grpc.beta

### ISSUE THREAD

**Issue by coconut73** [grpc/grpc#5617] opened 2016-03-05 04:16 UTC
Installed gpb3.0beta2 from third_party/protobuf and python libs:
Installing easy_install-3.5 script to /usr/local/bin                       
Installing easy_install script to /usr/local/bin                           

After installing gpb python, shows protobuf==3.0.0a4:
Using /usr/local/lib/python2.7/dist-packages
Searching for six==1.10.0                   
Best match: six 1.10.0                      
Processing six-1.10.0-py2.7.egg             
six 1.10.0 is already the active version in easy-install.pth

Using /usr/local/lib/python2.7/dist-packages/six-1.10.0-py2.7.egg
Finished processing dependencies for protobuf==3.0.0a4           
root@rpt-reg-grpc-ubuntu02:/opt/jvision/grpc/third_party/protobuf/python#

grpc install: 
root@rpt-reg-grpc-ubuntu02:/opt/jvision/grpc# make install               
[INSTALL] Installing public C headers                                    
[MAKE]    Generating cache.mk                                            
[STRIP]   Stripping libgpr.a                                             
[STRIP]   Stripping libgrpc.a                                            
[STRIP]   Stripping libgrpc_unsecure.a                                   
[INSTALL] Installing C pkg-config files                                  
[INSTALL] Installing libgpr.a                                            
[INSTALL] Installing libgrpc.a                                           
[INSTALL] Installing libgrpc_unsecure.a                                  
[STRIP]   Stripping libgpr.so                                            
[STRIP]   Stripping libgrpc.so                                           
[STRIP]   Stripping libgrpc_unsecure.so                                  
[INSTALL] Installing libgpr.so.0.11.0.0                                  
[INSTALL] Installing libgrpc.so.0.11.0.0                                 
[INSTALL] Installing libgrpc_unsecure.so.0.11.0.0                        
[INSTALL] Installing public C++ headers                                  
[STRIP]   Stripping libgrpc++.a                                          
[STRIP]   Stripping libgrpc++_unsecure.a                                 
[INSTALL] Installing C++ pkg-config files                                
[INSTALL] Installing libgrpc++.a                                         
[INSTALL] Installing libgrpc++_unsecure.a                                
[STRIP]   Stripping libgrpc++.so                                         
[STRIP]   Stripping libgrpc++_unsecure.so                                
[INSTALL] Installing libgrpc++.so.0.11.0.0                               
[INSTALL] Installing libgrpc++_unsecure.so.0.11.0.0                      
[INSTALL] Installing grpc protoc plugins                                 
[INSTALL] Installing root certificates                                   
Your system looks ready to go.                                           

root@rpt-reg-grpc-ubuntu02:/opt/jvision/grpc# 

root@rpt-reg-grpc-ubuntu02:/opt/jvision/grpc/examples/python/helloworld# python greeter_client.py
Traceback (most recent call last):
  File "greeter_client.py", line 32, in <module>
    from grpc.beta import implementations
ImportError: No module named grpc.beta

**Comment by royalharsh** [comment] 2016-03-05 05:41
the error might be because you are using python-3.5. One fix might be to use `python2.7 /usr/bin/pip install grpcio` to install grpcio using python2.7.

**Comment by coconut73** [comment] 2016-03-05 07:35
No, I am using python 2.7, I tried install grpc+gpb on ubuntu and centos,
same error... it's driving me nuts.

root@rpt-reg-grpc-ubuntu02:/opt/jvision/grpc/examples/python/helloworld#
python -V
Python 2.7.6

**Comment by soltanmm** [comment] 2016-03-05 20:41
What is the full list of steps that you followed to install gRPC Python?

**Comment by soltanmm** [comment] 2016-03-05 20:45
Also, what is `gpb`? No such package exists.

**Comment by soltanmm** [comment] 2016-03-05 20:52
I have a strong feeling that you never actually installed `grpcio`, or that an error occurred during installation. `make install` is a step unrelated to the Python installation process at both `release-0_13` and `master` branches.

That said, it would take a very strange environment (not impossible, just unlikely) to end up in a situation where `grpcio` was successfully `pip install`'d and yet the packages failed to be accessible. Could you please provide the output of `pip install $REPO_ROOT` where `$REPO_ROOT` is wherever you checked out the code from? Additionally please provide the git branch and/or commit number.

Or if you installed from PyPI, please indicate the output of the relevant command (e.g. `pip install grpcio`; make note of any additional flags you may have used).

**Comment by coconut73** [comment] 2016-03-06 07:33
After installing based on grpcio and python 2.7 virtualenv etc. now it
seems working.
I do hope the overall installation guidance be improved from github, right
now it's very vague and sometime inconsistent
Thanks.

**Comment by pgrosu** [comment] 2016-03-06 10:02
@coconut73 Think of it as a fun learning journey - you will find some really cool things :)

**Comment by spf2** [comment] 2016-03-14 17:41
I had the same problem using pypi (pip install grpcio).  I had to do ```touch venv/lib/python2.7/site-packages/grpc/__init__.py``` so that python would see the module.

**Comment by nathanielmanistaatgoogle** [comment] 2016-03-18 15:17
Closing this issue in response to "After installing based on grpcio and python 2.7 virtualenv etc. now it seems working.".

**Closed by nathanielmanistaatgoogle** 2016-03-18 15:17 UTC
Labels: python

**Comment by afshinm** [comment] 2016-11-23 12:51
I had the same problem. After uninstalling and installing `grpcio` it worked fine.

**Comment by honeytidy** [comment] 2017-05-18 09:48
like @afshinm said:
`pip install grpcio` worked for me.

**Comment by zhengzhuo2017** [comment] 2017-08-11 05:57
it works fine After uninstalling and installing grpcio.

**Comment by gzpan** [comment] 2018-01-13 14:26
Though a closed issue, I would like to share my solution here...
My solution is: creat a __init__.py file in directory 'grpc' or ask someone else send his __init__.py to you.
Someone encounter "No module named grpc.beta" because no such a init file in
corresponding directory.(just check your grpc directory and you will understand)

**Comment by AswathKiruba** [comment] 2018-03-06 21:09
I am still having this issue, even after uninstalling and installing grpcio. Could you please let me know what needs to be done.

**Comment by nathanielmanistaatgoogle** [comment] 2018-03-06 21:13
@AswathKiruba: in the environment in which you're having this trouble, what is the output of `pip freeze`? Within the Python interpreter, what is the output of `dir(grpc)`?

**Comment by AswathKiruba** [comment] 2018-03-07 14:26
@nathanielmanistaatgoogle: Thanks for your reply. The output of pip freeze is
alabaster==0.7.10
anaconda-client==1.6.5
anaconda-navigator==1.6.9
anaconda-project==0.8.0
asn1crypto==0.22.0
astroid==1.5.3
astropy==2.0.2
Babel==2.5.0
backports-abc==0.5
backports.functools-lru-cache==1.4
backports.shutil-get-terminal-size==1.0.0
backports.ssl-match-hostname==3.5.0.1
beautifulsoup4==4.6.0
bitarray==0.8.1
bkcharts==0.2
blaze==0.11.3
bleach==1.5.0
bokeh==0.12.10
boto==2.48.0
Bottleneck==1.2.1
cdecimal==2.3
certifi==2018.1.18
cffi==1.10.0
chardet==3.0.4
click==6.7
cloudpickle==0.4.0
clyent==1.2.2
colorama==0.3.9
conda==4.4.10
conda-build==3.0.27
conda-verify==2.0.0
configparser==3.5.0
contextlib2==0.5.5
cryptography==2.0.3
cycler==0.10.0
Cython==0.26.1
cytoolz==0.8.2
dask==0.15.3
datashape==0.5.4
decorator==4.1.2
distributed==1.19.1
docutils==0.14
entrypoints==0.2.3
enum34==1.1.6
et-xmlfile==1.0.1
fastcache==1.0.2
filelock==2.0.12
Flask==0.12.2
Flask-Cors==3.0.3
funcsigs==1.0.2
functools32==3.2.3.post2
futures==3.1.1
gevent==1.2.2
glob2==0.5
gmpy2==2.0.8
greenlet==0.4.12
grin==1.2.1
h5py==2.7.1
heapdict==1.0.0
html5lib==0.9999999
idna==2.6
imageio==2.2.0
imagesize==0.7.1
ipaddress==1.0.18
ipykernel==4.6.1
ipython==5.4.1
ipython-genutils==0.2.0
ipywidgets==7.0.0
isort==4.2.15
itsdangerous==0.24
jdcal==1.3
jedi==0.10.2
Jinja2==2.9.6
jsonschema==2.6.0
jupyter-client==5.1.0
jupyter-console==5.2.0
jupyter-core==4.3.0
jupyterlab==0.27.0
jupyterlab-launcher==0.4.0
lazy-object-proxy==1.3.1
llvmlite==0.20.0
locket==0.2.0
lxml==4.1.0
Markdown==2.6.9
MarkupSafe==1.0
matplotlib==2.1.2
mccabe==0.6.1
mistune==0.7.4
mock==2.0.0
mpmath==0.19
msgpack-python==0.4.8
multipledispatch==0.4.9
navigator-updater==0.1.0
nbconvert==5.3.1
nbformat==4.4.0
networkx==2.0
nltk==3.2.4
nose==1.3.7
notebook==5.0.0
numba==0.35.0+10.g143f70e90.dirty
numexpr==2.6.2
numpy==1.13.3
numpydoc==0.7.0
odo==0.5.1
olefile==0.44
openpyxl==2.4.8
packaging==16.8
pandas==0.22.0
pandocfilters==1.4.2
partd==0.3.8
path.py==10.3.1
pathlib2==2.3.0
patsy==0.4.1
pbr==3.1.1
pep8==1.7.0
pexpect==4.2.1
pickleshare==0.7.4
Pillow==5.0.0
pkginfo==1.4.1
ply==3.10
prompt-toolkit==1.0.15
protobuf==3.4.1
psutil==5.4.0
ptyprocess==0.5.2
py==1.4.34
pycairo==1.13.3
pycodestyle==2.3.1
pycosat==0.6.3
pycparser==2.18
pycrypto==2.6.1
pycurl==7.43.0
pydicom==0.9.9
pyflakes==1.6.0
Pygments==2.2.0
pylint==1.7.4
pyodbc==4.0.17
pyOpenSSL==17.2.0
pyparsing==2.2.0
PySocks==1.6.7
pytest==3.2.1
python-dateutil==2.6.1
pytz==2017.2
PyWavelets==0.5.2
PyYAML==3.12
pyzmq==16.0.2
QtAwesome==0.4.4
qtconsole==4.3.1
QtPy==1.3.1
requests==2.18.4
rope==0.10.5
ruamel-yaml==0.11.14
scandir==1.6
scikit-image==0.13.0
scikit-learn==0.19.1
scipy==1.0.0
seaborn==0.8
simplegeneric==0.8.1
singledispatch==3.4.0.3
six==1.11.0
snowballstemmer==1.2.1
sortedcollections==0.5.3
sortedcontainers==1.5.7
Sphinx==1.6.3
sphinxcontrib-websupport==1.0.1
spyder==3.2.4
SQLAlchemy==1.1.13
statsmodels==0.8.0
subprocess32==3.2.7
sympy==1.1.1
tables==3.4.2
tblib==1.3.2
tensorflow==1.4.1
tensorflow-tensorboard==0.4.0
terminado==0.6
testpath==0.3.1
toolz==0.8.2
tornado==4.5.2
traitlets==4.3.2
typing==3.6.2
unicodecsv==0.14.1
urllib3==1.22
wcwidth==0.1.7
webencodings==0.5.1
Werkzeug==0.12.2
widgetsnbextension==3.0.2
wrapt==1.10.11
xlrd==1.1.0
XlsxWriter==1.0.2
xlwt==1.3.0
zict==0.1.3

From above libraries, I could see that gRPC is not installed. But on pip installation, it shows successfully installed (pip install grpcio):

Requirement already satisfied: grpcio in /usr/local/lib/python2.7/dist-packages
Requirement already satisfied: six>=1.5.2 in /usr/lib/python2.7/dist-packages (from grpcio)
Requirement already satisfied: enum34>=1.0.4 in /usr/local/lib/python2.7/dist-packages (from grpcio)
Requirement already satisfied: protobuf>=3.5.0.post1 in /usr/local/lib/python2.7/dist-packages (from grpcio)
Requirement already satisfied: futures>=2.2.0 in /usr/local/lib/python2.7/dist-packages (from grpcio)
Requirement already satisfied: setuptools in /usr/lib/python2.7/dist-packages (from protobuf>=3.5.0.post1->grpcio)

**Comment by nathanielmanistaatgoogle** [comment] 2018-03-07 15:11
@AswathKiruba: are you able to work in a virtual environment? If so, are you able to reproduce the trouble you're having there?

**Comment by AswathKiruba** [comment] 2018-03-07 15:25
@nathanielmanistaatgoogle : I am trying the same in my virtual environment. Will keep you posted. Thank you.

**Comment by AswathKiruba** [comment] 2018-03-08 14:58
@nathanielmanistaatgoogle  gRPC is working fine. The issue was with the installation. Thank you for your time.
