### ISSUE TITLE
Unify ruby metadata key downcasing behavior

### ISSUE THREAD

**Issue by jtattermusch** [grpc/grpc#3891] opened 2015-10-20 01:28 UTC
Pull request #3740 and #3890 introduced some ad-hoc downcasing of metadata keys. gRPC ruby should have a better story for working with metadata keys. Most wrapped languages automatically downcase and check metadata keys. As of now, ruby only downcases metadata keys in some use cases (e.g. when you use metadata updater) so it's unclear to user which behavior will be used. 

Also ruby doesn't give an early warning about using an illegal metadata key. Instead, the RPCs using illegal metadata keys just hang forever (or time out eventually), but that seems to be covered by issue #3154

**Comment by murgatroid99** [comment] 2015-10-20 01:29
This seems like a duplicate of #3154.

**Comment by jtattermusch** [comment] 2015-10-20 01:36
Updated this issue to make it clear it's about making metadata key downcasing uniform.

**Comment by tbetbetbe** [comment] 2015-10-26 05:37
IIRC, we agreed that: 
1) it was preferred for wrapped languages not to duplicate checks being done in the core. 
  - this make its clearer where metadata-related errors come from (instead of splitting between core and implementation)
  - has potential performance gains for keys that are error-free, as we only do detailed checking in the error path
2) there should be robust error reporting/checking when metadata checks failed.

The auto down-casing + checking contradict 1); I'd like to confirm that we're don't care about 1) anymore before going ahead with this.  @ctiller, PTAL.
 
2) will be covered by the resolution of #3154 

> Pull request #3740 and #3890 introduced some ad-hoc downcasing of metadata keys.
This is specific to auth-specific rather than ad-hoc.  This will become clearer in the new ruby auth API PR

**Comment by jtattermusch** [comment] 2015-10-26 14:45
I think we agreed that we won't be checking metadata values, for metadata keys, it's fine to provide any kind of logic will simplify usage.

I agree that #3154 is a acceptable resolution to this. Right now, it looks like whenever invalid metadata is sent to core, the RPC just hangs forever.

**Comment by tbetbetbe** [comment] 2015-10-26 23:11
>  for metadata keys, it's fine to provide any kind of logic will simplify usage.

So is this bug just about the fact that RPC hangs forever if the key is invalid ?

**Comment by jtattermusch** [comment] 2015-10-26 23:53
I think the downcasing behavior provided by C# and Node makes a lot of sense (especially because of the fail-early semantics) and would prefer if all wrapped languages had the same behavior, but I don't insist on what the solution should be. So, yes, this issue might be as simple as resolving hang on invalid metadata key.

**Comment by ctiller** [comment] 2015-10-27 06:44
C++ will not be adopting any automatic conversion. We'd previously agreed
that no wrapped languages would, but I guess not documented it anywhere.

If wrapped languages are indeed planning on automatic conversion, I'd
strongly encourage that lookups on the receiving side be case
insensitive... Lookup(key, Send(key, value)) must give value for all
accepted keys in my view.

**Comment by murgatroid99** [comment] 2016-01-05 22:31
google/google-auth-library-ruby#57 would simplify this.

**Closed** 2016-01-12 21:06 UTC
Labels: P1, ruby
