### ISSUE TITLE
C# ConnectAsync is randomly very slow (native resolver on Windows is slow to resolve non-existent "local" DNS names).

### ISSUE THREAD

**Issue by topsterde** [grpc/grpc#28403] opened 2021-12-22 14:53 UTC
### What version of gRPC and what language are you using?
2.42.0 C#

### What operating system (Linux, Windows,...) and version?
Windows 10 21H2

### What runtime / compiler are you using (e.g. python version or version of gcc)
Visual Studio 2017 -  2022

### What did you do?
I have created an application that makes one valid connection and several invalid connections (not available host names).
Due to multiple invalid connections, the ConnectAsync call becomes randomly very slow.

### What did you expect to see?
I always expect a fast ConnectAsync() within 1s to a localhost grpc server.

### What did you see instead?

Randomly very slow times of ConnectAsync():

```
Run: 0; ConnectAsync(): 00:00:06.8709278
Run: 1; ConnectAsync(): 00:00:02.0701909
Run: 2; ConnectAsync(): 00:00:00.0108878
Run: 3; ConnectAsync(): 00:00:00.0118987
Run: 4; ConnectAsync(): 00:00:07.7775978
Run: 5; ConnectAsync(): 00:00:04.5538642
Run: 6; ConnectAsync(): 00:00:00.0052104
Run: 7; ConnectAsync(): 00:00:13.9308440
Run: 8; ConnectAsync(): 00:00:00.0077341
Run: 9; ConnectAsync(): 00:00:00.0044947
```

Customized Client code in Greeter Example which generates this console output:
[GrpcConnectTest.zip](https://github.com/grpc/grpc/files/7763303/GrpcConnectTest.zip)

### Anything else we should know about your project / environment?

In my scenario, i need:
- GRPC_DNS_RESOLVER: native
- ConnectAsync() for some internal checks

**Comment by jtattermusch** [comment] 2022-04-04 09:57
@rburns1293 can you please check whether you can reproduce and provide extra details (e.g. whether the problem is unique to windows)

**Comment by jtattermusch** [comment] 2022-04-04 10:00
Also, as always, can you run with GRPC_VERBOSITY=debug and possibly with some `GRPC_TRACE=` (e.g. GRPC_TRACE=connectivity_status) and see if the logs provide any useful insights?

See here:
https://github.com/grpc/grpc/blob/master/TROUBLESHOOTING.md

**Comment by tonydnewell** [comment] 2022-08-15 14:22
This does appear to only be an issue with the Windows native DNS resolver when using short name (localnames) and not FQDNs. The c-ares resolver works OK, and it works OK on Linux.  I've attached three traces:

- one with native DNS resolver
- one with native DNS resolver and FQDN
- one with c-ares DNS resolver

Traces using `GRPC_TRACE=dns_resolver,connectivity_state,executor`

[trace-cares-dns.txt](https://github.com/grpc/grpc/files/9337756/trace-cares-dns.txt)
[trace-native-dns.txt](https://github.com/grpc/grpc/files/9337758/trace-native-dns.txt)
[trace-native-dns-fqdn.txt](https://github.com/grpc/grpc/files/9337759/trace-native-dns-fqdn.txt)

**Comment by tonydnewell** [comment] 2022-08-16 09:15
More info. This is a c-core issue with the Windows native DNS resolver.  I've reproduced the slow DNS lookups with a standalone C program.

- Windows DNS resolver is slow when looking up a non-existent local name (but fast with FQDN)
- c-core treats "host not found" as a transient error and goes into a back off retry loop retrying the lookups
- c-core has a limited thread pool (src/core/lib/iomgr/executor.cc) that does the DNS lookups and thus slowing down other DNS lookup waiting their turn with the thread pool

**Comment by jtattermusch** [comment] 2022-08-16 10:09
> * FQDN

CC @apolcyn @yashykt 

These are interesting findings, thanks! It sounds like possible workarounds are:
- use a fully qualified domain name instead of a local name
- use c-ares resolver if possible (there are things that don't work well with c-ares on windows so this might not be always possible).

@tonydnewell  can you please confirm (and add more workarounds if you can think of any).

**Comment by jtattermusch** [comment] 2022-08-16 10:14
@tonydnewell  @apolcyn  since there are known workarounds (e.g. use FQDN) and the problem with slow resolution seems to be caused by behavior of Windows itself (which we can do very little about), I suggest closing this?

**Comment by tonydnewell** [comment] 2022-08-23 08:33
The workarounds are to use c-ares resolver or a FQDN.  Further investigation indicates that Windows is trying NetBIOS name resolution when a local name is given and this may involve broadcasting to the LAN and waiting for responses if the name is not found by other means - this is what is slow.

**Closed** 2022-08-24 08:52 UTC
Labels: kind/bug, lang/C#, lang/core, priority/P2
