### ISSUE TITLE
Jenkins failed with IllegalArgumentException: Comparison method violates its general contract!

### ISSUE THREAD

**Issue by stanley-cheung** [grpc/grpc#3959] opened 2015-10-26 17:13 UTC
For example: https://grpc-testing.appspot.com/job/gRPC_master/12475/console

```
> git checkout -f 9698e7636acb397401abfb8b406a8f33cd3246ea
 > git rev-list 9698e7636acb397401abfb8b406a8f33cd3246ea # timeout=10
 > git remote # timeout=10
 > git submodule init # timeout=10
 > git submodule sync # timeout=10
 > git config --get remote.origin.url # timeout=10
 > git submodule update --init --recursive
FATAL: Comparison method violates its general contract!
java.lang.IllegalArgumentException: Comparison method violates its general contract!
	at java.util.TimSort.mergeLo(TimSort.java:747)
	at java.util.TimSort.mergeAt(TimSort.java:483)
	at java.util.TimSort.mergeCollapse(TimSort.java:410)
	at java.util.TimSort.sort(TimSort.java:214)
	at java.util.TimSort.sort(TimSort.java:173)
	at java.util.Arrays.sort(Arrays.java:659)
	at java.util.Collections.sort(Collections.java:217)
	at org.codehaus.groovy.runtime.DefaultGroovyMethods.sort(DefaultGroovyMethods.java:8200)
	at org.codehaus.groovy.runtime.DefaultGroovyMethods.sort(DefaultGroovyMethods.java:8164)
	at org.codehaus.groovy.runtime.dgm$728.invoke(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite$PojoMetaMethodSiteNoUnwrapNoCoerce.invoke(PojoMetaMethodSite.java:271)
	at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite.call(PojoMetaMethodSite.java:53)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:116)
	at org.jenkinsci.plugins.ScriptRunner.run(ScriptRunner.groovy:29)
	at org.jenkinsci.plugins.ScriptRunner$run.call(Unknown Source)
	at org.jenkinsci.plugins.GroovyScriptMES.decideOrder(GroovyScriptMES.groovy:62)
	at org.jenkinsci.plugins.GroovyScriptMES$decideOrder.callCurrent(Unknown Source)
	at org.jenkinsci.plugins.BaseMES.run(BaseMES.groovy:51)
	at hudson.matrix.MatrixBuild$MatrixBuildExecution.doRun(MatrixBuild.java:352)
	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:537)
	at hudson.model.Run.execute(Run.java:1741)
	at hudson.matrix.MatrixBuild.run(MatrixBuild.java:301)
	at hudson.model.ResourceController.execute(ResourceController.java:98)
	at hudson.model.Executor.run(Executor.java:410)
Finished: FAILURE
```

**Comment by jtattermusch** [comment] 2015-11-12 13:10
Duplicate of #3736

**Closed by jtattermusch** 2015-11-12 13:10 UTC
Labels: Jenkins
