### ISSUE TITLE
test flake: c_linux_dbg_native.bins/dbg/h2_full_nosec_test registered_call GRPC_POLL_STRATEGY=epollsig

### ISSUE THREAD

**Issue by jtattermusch** [grpc/grpc#11178] opened 2017-05-17 06:56 UTC
https://grpc-testing.appspot.com/job/gRPC_pull_requests_linux/5446/testReport/junit/(root)/c_linux_dbg_native/bins_dbg_h2_full_nosec_test_registered_call_GRPC_POLL_STRATEGY_epollsig/

```
0x65 GRPC_OP_COMPLETE success=1 test/core/end2end/tests/registered_call.c:160




*******************************
Caught signal SIGABRT
bins/dbg/h2_full_nosec_test[0x4daf69]
/lib/x86_64-linux-gnu/libpthread.so.0(+0xf890)[0x7f4bf9aac890]
/lib/x86_64-linux-gnu/libc.so.6(gsignal+0x37)[0x7f4bf9727067]
/lib/x86_64-linux-gnu/libc.so.6(abort+0x148)[0x7f4bf9728448]
bins/dbg/h2_full_nosec_test[0x4333c9]
bins/dbg/h2_full_nosec_test[0x433573]
bins/dbg/h2_full_nosec_test[0x424ba1]
bins/dbg/h2_full_nosec_test[0x4250d9]
bins/dbg/h2_full_nosec_test[0x425160]
bins/dbg/h2_full_nosec_test[0x404580]
bins/dbg/h2_full_nosec_test[0x40331b]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf5)[0x7f4bf9713b45]
bins/dbg/h2_full_nosec_test[0x402fa9]
```

**Comment by yang-g** [comment] 2017-05-17 18:00
Duplicate of #10653

**Closed by yang-g** 2017-05-17 18:00 UTC
Labels: BUILDPONY, core
