### ISSUE TITLE
Xamarin Forms or Xamarin.iOS support

### ISSUE THREAD

**Issue by marualderete** [grpc/grpc#15971] opened 2018-07-10 12:28 UTC
### What version of gRPC and what language are you using?
grpc 1.13.0
grpc.tools 1.13.0
protobuf 3.6.0
Xamarin Forms 3.1.0.583944
Net standard 2.x
 
### What operating system (Linux, Windows, …) and version?
 windows 10
  
Hi guys, I need to know if grpc has support for Xamarin.Forms, I'm particulary interested in iOS.
I tried to follow the CSharp client samples but at the end in ejecution time an error is thrown:

'Error while loading assemblies:' '/myUser/Library/Caches/Xamarin/mtbs/builds/App.iOS/.../bin/iPhoneSimulator/Debug/grpc_csharp_ext.x64.dll'

Any thoughts about it? I'm stuck on this, and really want to use grpc on my app

**Comment by jzeferino** [comment] 2018-07-17 11:10
@migueldeicaza since the existing Nuget Package is from grpc, even if I can successfully compile for iOS how can I add the result binary to an existing project?

**Comment by jtattermusch** [comment] 2018-07-19 14:07
@marualderete   Xamarin as a platform is not supported yet by gRPC C#, but we have an ongoing effort towards adding it.
The umbrella issue for adding Xamarin support is here: https://github.com/grpc/grpc/issues/1620.
Some very promising changes that will bring Xamarin.Android support (and lay foundations for Xamarin.iOS support) are here: https://github.com/grpc/grpc/pull/15969. Stay tuned!

I'll close this issue as it's basically a dupe of #1620.

**Closed** 2018-07-19 14:08 UTC
Labels: kind/question, lang/C#, platform/Windows, platform/iOS
