### ISSUE TITLE
something about gRPC performance

### ISSUE THREAD

**Issue by GuoJing** [grpc/grpc#5618] opened 2016-03-06 17:03 UTC
I had a simple gRPC server based on Python.

In my code, I have one channel and now I find out channel will control and keep connection alive, I can do nothing with channel. If lots of requests, channel will open more than one connection for me. (looks like that it is)

Now I'm testing the performance, If I create 10 process and 10 thread, each on call gRPC server 100 times, looks like:

1. if client is closed, server will not stop, it will process the rest requests from the client
2. looks like there is a queue or something like that
3. the later request in the queue will be slow (1st will be 0.0001s, maybe the 10000 one will be 2s)
4. some times there will be ExpirationError or NetworkError

Is there anything wrong? or how could I test the performance? any suggestion on deploy?

**Comment by nathanielmanistaatgoogle** [comment] 2016-06-06 23:23
Closing as a duplicate of [issue 5594](https://github.com/grpc/grpc/issues/5594).

**Closed by nathanielmanistaatgoogle** 2016-06-06 23:23 UTC
Labels: python
