### ISSUE TITLE
Build failure on MacOS

### ISSUE THREAD

**Issue by piano-man** [grpc/grpc#24660] opened 2020-11-04 07:29 UTC
### What version of gRPC and what language are you using?
1.33.1

### What operating system (Linux, Windows,...) and version?
MacOS Catalina

### What did you do?
1) Followed the steps provided on https://grpc.io/docs/languages/cpp/quickstart/ to build grpc.
2) Get this warning **"MACOSX_RPATH is not specified for the following targets: zlib"** after running 
```
       cmake -DgRPC_INSTALL=ON \
      -DgRPC_BUILD_TESTS=OFF \
      -DCMAKE_INSTALL_PREFIX=$MY_INSTALL_DIR \
      ../..
```
3) The build finally fails with: **CMake Error at third_party/zlib/cmake_install.cmake:49 (file):
  file cannot create directory: /lib.  Maybe need administrative privileges.**

4) Tried with sudo, still the same result.

### What did you expect to see?
No errors

### What did you see instead?
Build Failure

### Anything else we should know about your project / environment?
Cmake version: 3.18.4

**Comment by harshitpassi** [comment] 2020-11-05 11:14
Can confirm, I got the same error!
![Screenshot 2020-11-05 at 3 14 01 AM](https://user-images.githubusercontent.com/25246097/98234213-f67b1300-1f14-11eb-817e-741d0dc0f731.png)

**Comment by catterer** [comment] 2020-11-15 13:19
I had the same problem when I ran `cmake` first without `MY_INSTALL_DIR`. Cmake [caches](https://github.com/madler/zlib/blob/cacf7f1d4e3d44d871b605da3b647f07d718623f/CMakeLists.txt#L12) install path for zlib and consequent builds fail even though you run them with proper install dir. Did you try to `rm -rf cmake/build` and run it from scratch?

**Comment by AxxlForce** [comment] 2020-12-04 15:51
same problem here. rm -rf cmake/build didn't help, running as root and disabling SIP neither

**Comment by LeviSchuck** [comment] 2020-12-19 02:14
I had this too while following [the guide](https://grpc.io/docs/languages/cpp/quickstart/) for v1.34.0

**Comment by boanerges317** [comment] 2021-07-16 21:48
I faced a similar issue on Mac. 

I had missed the following steps. Doing those, Deleting the contents of the build directory, running cmake and building again, solved the issue. 

```
$ export MY_INSTALL_DIR=$HOME/.local
$ mkdir -p $MY_INSTALL_DIR
$ export PATH="$MY_INSTALL_DIR/bin:$PATH"
```

**Comment by midannii** [comment] 2021-11-27 06:14
same problem with me on Mac.
I didn't miss all steps. `sudo` didn't help me 
here's  my error message

```
CMake Error at third_party/zlib/cmake_install.cmake:49 (file):
  file cannot create directory: /lib.  Maybe need administrative privileges.
Call Stack (most recent call first):
  cmake_install.cmake:2134 (include)

make: *** [install] Error 1

```

**Comment by Sunnycheey** [comment] 2022-02-25 04:22
@midannii 

Have you solved the problem?

**Comment by jna3** [comment] 2022-05-02 20:15
i encountered similar issue today, /third_party/zlib/.cmake_install.cmake was the issue. Every instance of INSTALL DESTINATION is not using the CMAKE_INSTALL_PREFIX that it's supposed to.

**Comment by veblush** [comment] 2022-05-23 23:15
Would you give us all command you ran when encountering this problem because we cannot reproduce this problem on MacOS. I'm closing this issue first but please feel free to reopen it if required.

**Closed by veblush** 2022-05-23 23:15 UTC
Labels: kind/bug, lang/core, priority/P2, area/build, untriaged

**Comment by DmitriiGorelov** [comment] 2023-07-01 05:33
I had the same issue under Windows when installing the grpc using VisualStudio. 
After restarting VisualStudio with admin privileges, the install process ran through. But the destination of some 3rd party libraries has changed to C:/Program Files (x86)/grpc/lib
I think there is a problem in their own cmake files (som paths are not updated by CMAKE_INSTALL_PREFIX automatically).
So I think I have to manually copy the files from C:/Program Files (x86)/grpc/lib to the folder I gave as CMAKE_INSTALL_PREFIX .
