### ISSUE TITLE
Re-enable bazel test: //test/core/iomgr:tcp_server_posix_test: (disabled because of "unable to configure socket")

### ISSUE THREAD

**Issue by adelez** [grpc/grpc#15610] opened 2018-06-01 18:43 UTC
https://source.cloud.google.com/results/invocations/fb344df5-4b54-4a05-ace3-6e78351198ab/targets/%2F%2Ftest%2Fcore%2Fiomgr:tcp_server_posix_test@poller%3Depoll1/log

```
D0601 15:44:39.537852159 18 test_config.cc:391] test slowdown factor: sanitizer=1, fixture=1, poller=1, total=1
E0601 15:44:39.542083829 18 tcp_server_posix_test.cc:373] Failed to connect to [fe80::42:acff:fe12:2%251101]:41437: {"created":"@1527867879.542060484","description":"OS Error","errno":99,"file":"test/core/iomgr/tcp_server_posix_test.cc","file_line":246,"os_error":"Cannot assign requested address","syscall":"connect"}
E0601 15:44:39.543124686 18 tcp_server_posix_test.cc:322] grpc_tcp_server_add_port: {"created":"@1527867879.543069412","description":"Failed to add listener: [fe80::42:acff:fe12:2%251101]:57859","file":"src/core/lib/iomgr/tcp_server_utils_posix_ifaddrs.cc","file_line":155,"referenced_errors":[{"created":"@1527867879.543064992","description":"Unable to configure socket","fd":8,"file":"src/core/lib/iomgr/tcp_server_utils_posix_common.cc","file_line":214,"referenced_errors":[{"created":"@1527867879.543054727","description":"OS Error","errno":99,"file":"src/core/lib/iomgr/tcp_server_utils_posix_common.cc","file_line":187,"os_error":"Cannot assign requested address","syscall":"bind"}]}]}
E0601 15:44:39.543169388 18 tcp_server_posix_test.cc:322] assertion failed: GRPC_LOG_IF_ERROR( "grpc_tcp_server_add_port", grpc_tcp_server_add_port(s, &resolved_addr, &svr_port))
```

**Comment by adelez** [comment] 2018-06-01 19:40
Seems to happen quite often.

**Comment by matt-kwong** [comment] 2018-06-01 23:08
The last time this passed on master was in https://source.cloud.google.com/results/invocations/27319652-2a5e-490d-bc76-fa9ddadcdbba/targets. The subsequent master build that failed was https://source.cloud.google.com/results/invocations/a1a2d544-a38c-4b8e-bb63-d261685ab674/targets, but there wasn't anything merged between these two runs.

**Comment by adelez** [comment] 2018-06-01 23:13
I'm checking with the Foundry team to see if this has to do with the rollout of port isolation.

**Comment by adelez** [comment] 2018-06-02 00:14
I don't think this is related to Foundry. I can reproduce with running a local bazel test.

**Comment by adelez** [comment] 2018-06-02 00:16
@dgquintas , assigning to you for triaging.

**Comment by adelez** [comment] 2018-06-12 00:18
With #15716, this bug is no longer blocking Bazel tests. However, we can't close until Foundry solves the underlying issue and the test gets added back.

**Comment by jtattermusch** [comment] 2018-09-14 14:03
What exactly the socket option that this test requests?

**Comment by jtattermusch** [comment] 2018-10-04 10:57
FTR The test was marked as manual here:
https://github.com/grpc/grpc/pull/15716/files#diff-b081353917051bb7d44e58fd9e95e4fdR230

**Comment by jtattermusch** [comment] 2018-11-20 12:02
A simple way of reproducing manually (to verify it its fixed):
```
bazel --bazelrc=tools/remote_build/manual.bazelrc test --config=opt //test/core/iomgr:tcp_server_posix_test
```

**Comment by jtattermusch** [comment] 2019-01-08 17:11
This issue seem to be the root cause: 
https://github.com/moby/moby/issues/38491

Also see internal bug (b/109797594)

**Closed** 2019-01-09 09:46 UTC
Labels: infra/BUILDPONY, infra/Bazel, infra/bazel test failures, kind/bug, lang/core, priority/P3
