### ISSUE TITLE
python_plugin_test not yet running on Travis

### ISSUE THREAD

**Issue by ctiller** [grpc/grpc#866] opened 2015-02-27 05:08 UTC
I'm trying to get #864 up to test Python on Travis, but tests seem to be failing (see: https://travis-ci.org/grpc/grpc/builds/52375291).... hoping someone with some Python-Fu can pick this up.

**Comment by nathanielmanistaatgoogle** [comment] 2015-02-27 18:18
@soltanmm, this appears to be coming from the python_plugin_test and having something to do with the path at which the python used in the test expects to find gRPC.

**Comment by jtattermusch** [comment] 2015-02-27 18:44
My progress so far:
1. I've commented out the python_plugin_test and it's failing anyway, so the problem is more substantial (locally, things work) - let's get the rest working and get back to python_plugin_test
2. I've added apt-get install pip dependency
3. build_python.sh fails after that (I suspect it wasn't really working before)

https://travis-ci.org/grpc/grpc/builds/52457683

**Comment by nathanielmanistaatgoogle** [comment] 2015-03-03 21:55
(Retitled to reflect the narrowed scope of outstanding work.)

@soltanmm, please sync with @murgatroid99 about proto-in-the-travis-test-environment. This issue may not be immediately actionable; it may be that we have to wait for configuration changes before we get to run python_plugin_test on travis.

**Comment by soltanmm** [comment] 2015-03-06 18:50
I believe this has been addressed.

**Comment by nathanielmanistaatgoogle** [comment] 2015-03-10 19:43
Yep, I agree that this was addressed by #965.

**Closed by nathanielmanistaatgoogle** 2015-03-10 19:43 UTC
Labels: P1, python
