### ISSUE TITLE
SIGFPE in the hello world client when making the rpc call

### ISSUE THREAD

**Issue by gaultier** [grpc/grpc#18948] opened 2019-05-03 08:10 UTC
### What version of gRPC and what language are you using?
 1.19.0 with C++. Newer versions (HEAD) also have the same behavior. 
 
### What operating system (Linux, Windows,...) and version?
Ubuntu 18.04 running in Docker for Mac (version 2.0.0.3 (31259))  on OSX (Mojave).
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
 g++ (Ubuntu 7.4.0-1ubuntu1~18.04) 7.4.0
 
### What did you do?
Summary: install the grpc libraries, clone this repo, compile the hello world client and run it. It is killed with the signal SIGFPE of type FPE_INTDIV (division by zero). Here is a dockerfile to do just that:

Dockerfile.grpc:

```
FROM ubuntu:18.04

RUN apt update -y && apt install -y --no-install-recommends \
    g++ \
    git \
    libgrpc++-dev \
    libprotobuf-dev \
    make \
    pkg-config \
    protobuf-compiler \
    protobuf-compiler-grpc \ 
    strace \
    && rm -rf /var/lib/apt/lists/*

# grpc++ was deprecated and renamed to grpcpp
RUN mkdir /usr/include/grpcpp
RUN ln -s /usr/include/grpc++/grpc++.h /usr/include/grpcpp/grpcpp.h

WORKDIR /tmp
RUN git clone -c http.sslVerify=false https://github.com/grpc/grpc
WORKDIR /tmp/grpc 
RUN git checkout v1.19.0

WORKDIR /tmp/grpc/examples/cpp/helloworld
RUN make greeter_client
```

Build docker image: `docker build -t grpc - < Dockerfile.grpc`

Run it:  `docker run -it grpc /tmp/grpc/examples/cpp/helloworld/greeter_client; echo $?`
It outputs: `136` which is SIGFPE.

Troubleshoot with strace: ` docker run --cap-add SYS_PTRACE -it grpc strace /tmp/grpc/examples/cpp/helloworld/greeter_client`
It outputs: `--- SIGFPE {si_signo=SIGFPE, si_code=FPE_INTDIV, si_addr=0x7f4eb0aa5f38} ---
+++ killed by SIGFPE +++`

Troubleshoot with gdb: `docker run --cap-add SYS_PTRACE -it grpc gdb /tmp/grpc/examples/cpp/helloworld/greeter_client` and then type `run` in the gdb repl.
It outputs: `Program received signal SIGFPE, Arithmetic exception.
0x00007f0aa9fe8f38 in grpc_slice_intern () from /usr/lib/libgrpc++.so.1`
Backtrace (obtained by typing `bt` in gdb after the program crashed): 
```
#0  0x00007f9bc7f90f38 in grpc_slice_intern () from /usr/lib/libgrpc++.so.1
#1  0x00007f9bc7f96a1a in grpc_channel_register_call ()
   from /usr/lib/libgrpc++.so.1
#2  0x000055d91c197c82 in grpc::RpcMethod::RpcMethod(char const*, grpc::RpcMethod::RpcType, std::shared_ptr<grpc::ChannelInterface> const&) ()
#3  0x000055d91c195f2f in helloworld::Greeter::Stub::Stub(std::shared_ptr<grpc::ChannelInterface> const&) ()
#4  0x000055d91c195e80 in helloworld::Greeter::NewStub(std::shared_ptr<grpc::ChannelInterface> const&, grpc::StubOptions const&) ()
#5  0x000055d91c1a01ea in GreeterClient::GreeterClient(std::shared_ptr<grpc::Channel>) ()
#6  0x000055d91c19ff14 in main ()
```

### What did you expect to see?
The normal hello world output and a 0 exit code.
 
### What did you see instead?
Exit code 136.
 
### Anything else we should know about your project / environment?
Works on OSX with grpc 1.19 (i.e same version as in the container) and same hello world example.

**Comment by nicolasnoble** [comment] 2019-05-03 15:46
This report doesn't make a lot of sense. You're saying you're using grpc 1.19, but then you're using a .deb package...?

Where does this package come from? I can see a 1.16 package up on the repositories, but no 1.19 yet. The compilation of this package is probably the fault here.

**Comment by gaultier** [comment] 2019-05-03 19:32
Sorry if it was not entirely clear from the dockerfile. The library comes from the Debian package, the example from the git repository on the tag 1.19. 
The makefile for the hello world example (in the grocery repository) compiles the example and only the example, not the library, and links it against the grpc library found by pkg-config i.e installed system wide.

**Comment by nicolasnoble** [comment] 2019-05-03 19:49
Right, so the actual library you have system-wide isn't 1.19, and that's the important part because that's where your callstack fails.

At that point, we're not vendoring that Debian package you're using, and we're not seeing this issue with the general release we have. We can't really support vendored packages unless we know better how this is built.

But you should actually try to build grpc directly into your Dockerfile instead of installing the vendored package, to see if you can reproduce the issue. If you can't, I'd recommend filing an issue on the Debian bug tracker so they can assess the issue knowing their differences between our codebase and their package.

One example of a Dockerfile that builds gRPC can be found here: https://github.com/grpc/grpc-docker-library/blob/master/1.12.0/cxx/Dockerfile - of course, update the tag to 1.20, but the gist of it should be the same.

**Comment by gaultier** [comment] 2019-05-08 11:03
Indeed, building from source with 1.20 works, something must be wrong with the debian package.

**Comment by a11r** [comment] 2019-05-22 17:38
Closing this issue.

**Closed by a11r** 2019-05-22 17:38 UTC
Labels: disposition/requires reporter action
