### ISSUE TITLE
objc tests broken on master

### ISSUE THREAD

**Issue by jtattermusch** [grpc/grpc#16817] opened 2018-10-09 15:25 UTC
Failing 100% of builds

Examples:
https://source.cloud.google.com/results/invocations/663383c3-983d-4dbb-8464-f2dfbc89f54e/targets
https://source.cloud.google.com/results/invocations/9f639d6d-e9e5-471a-a3ed-03b597100800/targets/github%2Fgrpc%2Fobjc_macos_dbg_native/tests
https://source.cloud.google.com/results/invocations/3d28384f-c0ae-4d8c-b7be-fe50843b5058/targets/github%2Fgrpc%2Fobjc_macos_dbg_native/tests

```
Test Suite 'Selected tests' failed at 2018-10-08 21:20:47.944.
	 Executed 70 tests, with 5 failures (0 unexpected) in 2.521 (2.532) seconds
2018-10-08 21:20:47.945573-0700 xctest[92091:944674] *** Assertion failure in -[XCTestCase _enqueueFailureWithDescription:inFile:atLine:expected:breakWhenDequeued:](), /Library/Caches/com.apple.xbs/Sources/XCTest_Sim/XCTest-13764/Sources/XCTestFramework/Core/XCTestCase.m:399
2018-10-08 21:20:47.946010-0700 xctest[92091:944674] *** Assertion failure in -[XCTestCase _enqueueFailureWithDescription:inFile:atLine:expected:breakWhenDequeued:](), /Library/Caches/com.apple.xbs/Sources/XCTest_Sim/XCTest-13764/Sources/XCTestFramework/Core/XCTestCase.m:399
2018-10-08 21:20:47.947957-0700 xctest[92091:944674] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Unable to report test assertion failure '((response) equal to (expected)) failed: throwing "Unable to report test assertion failure '((response) equal to (expected)) failed: ("<RMTStreamingOutputCallResponse 0x7fd208803c10>: {
    payload {
      type: 1
      body: "\000\000\000\000\000\000\000\000\000"
    }
}") is not equal to ("<RMTStreamingOutputCallResponse 0x7fd208802490>: {
    payload {
      body: "\000\000\000\000\000\000\000\000\000"
    }
}")' from /Volumes/BuildData/tmpfs/src/github/grpc/workspace_objc_macos_dbg_native/src/objective-c/tests/InteropTests.m:323 because it was raised inside test case -[InteropTestsRemote testServerStreamingRPC] which has no associated XCTestRun object. This may happen when test cases are constructed and invoked independently of standard XCTest infrastructure, or when the test has already finished."' from /Volumes/BuildData/tmpfs/src/github/grpc/workspace_objc_macos_dbg_native/src/objective-c/tests/InteropTests.m:323 because it was raised inside test case -[InteropTestsRemote testServerStreamingRPC] which has no associated XCTestRun object. This may happen when test cases are constructed and invoked independently of standard XCTest infrastructure, or when the test has already finished.'
*** First throw call stack:
(
	0   CoreFoundation                      0x000000010353f12b __exceptionPreprocess + 171
	1   libobjc.A.dylib                     0x0000000102bd3f41 objc_exception_throw + 48
	2   CoreFoundation                      0x00000001035442f2 +[NSException raise:format:arguments:] + 98
	3   Foundation                          0x000000010256a3db -[NSAssertionHandler handleFailureInFunction:file:lineNumber:description:] + 165
	4   XCTest                              0x0000000102aa778f -[XCTestCase _enqueueFailureWithDescription:inFile:atLine:expected:breakWhenDequeued:] + 1034
	5   XCTest                              0x0000000102ab0f6c _XCTFailureHandler + 408
	6   AllTests                            0x00000001189fcdb4 __38-[InteropTests testServerStreamingRPC]_block_invoke + 6260
	7   AllTests                            0x0000000118b91651 __80-[ProtoRPC initWithHost:method:requestsWriter:responseClass:responsesWriteable:]_block_invoke_2 + 139
	8   AllTests                            0x0000000118b923e2 __57-[GRXConcurrentWriteable enqueueValue:completionHandler:]_block_invoke + 63
	9   libdispatch.dylib                   0x0000000109f30177 _dispatch_call_block_and_release + 12
	10  libdispatch.dylib                   0x0000000109f311ba _dispatch_client_callout + 8
	11  libdispatch.dylib                   0x0000000109f3b3a4 _dispatch_main_queue_callback_4CF + 1260
	12  CoreFoundation                      0x0000000103501e39 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 9
	13  CoreFoundation                      0x00000001034c6462 __CFRunLoopRun + 2402
	14  CoreFoundation                      0x00000001034c5889 CFRunLoopRunSpecific + 409
	15  XCTest                              0x0000000102aea4ad -[XCTWaiter waitForExpectations:timeout:enforceOrder:] + 545
	16  XCTest                              0x0000000102aec8ed +[XCTWaiter waitForExpectations:timeout:enforceOrder:] + 91
	17  XCTest                              0x0000000102afd600 -[XCTTestRunSession runTestsAndReturnError:] + 555
	18  XCTest                              0x0000000102a93af1 -[XCTestDriver runTestsAndReturnError:] + 314
	19  XCTest                              0x0000000102af5190 _XCTestMain + 619
	20  xctest                              0x000000010219e591 xctest + 9617
	21  libdyld.dylib                       0x0000000109fa5d81 start + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException
Test Suite 'Selected tests' started at 2018-10-08 21:21:03.727
Test Suite 'AllTests.xctest' started at 2018-10-08 21:21:03.728
Test Suite 'AllTests.xctest' passed at 2018-10-08 21:21:03.728.
	 Executed 0 tests, with 0 failures (0 unexpected) in 0.000 (0.000) seconds
Test Suite 'Selected tests' passed at 2018-10-08 21:21:03.729.
	 Executed 0 tests, with 0 failures (0 unexpected) in 0.000 (0.002) seconds
Failed with code 65.
kill -9 `jobs -p` ; echo "EXIT TIME:  $(date)"
jobs -p
date
EXIT TIME:  Mon Oct  8 21:21:08 PDT 2018
```

**Comment by jtattermusch** [comment] 2018-10-09 15:37
This might actually be related to https://github.com/grpc/grpc/issues/16818 - IIRC the objc test are using the prod backend for interop tests to perform testing (that itself is less than ideal and should be fixed, but it is what it is).

**Comment by muxi** [comment] 2018-10-09 23:49
Confirmed it's a duplicate of #16818 and the root cause is found. Closing.

**Closed by muxi** 2018-10-09 23:49 UTC
Labels: infra/BUILDPONY, lang/ObjC, priority/P1
