### ISSUE TITLE
FAILED: cloud_to_prod_auth:gateway_v4:csharpcoreclr:compute_engine_creds

### ISSUE THREAD

**Issue by apolcyn** [grpc/grpc#12204] opened 2017-08-16 21:53 UTC
fails with unavailable

```
2017-08-16 14:03:47,420 D0816 21:03:46.613530 Grpc.Core.Internal.UnmanagedLibrary Attempting to load native library "/var/local/git/grpc/src/csharp/Grpc.IntegrationTesting.Client/bin/Debug/netcoreapp1.0/libgrpc_csharp_ext.x64.so"
D0816 21:03:46.665086 Grpc.Core.Internal.NativeExtension gRPC native library loaded successfully.
running compute_engine_creds

Unhandled Exception: System.AggregateException: One or more errors occurred. (Status(StatusCode=Unavailable, Detail="Endpoint read failed")) ---> Grpc.Core.RpcException: Status(StatusCode=Unavailable, Detail="Endpoint read failed")
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Grpc.Core.Internal.AsyncCall`2.UnaryCall(TRequest msg)
   at Grpc.Core.Calls.BlockingUnaryCall[TRequest,TResponse](CallInvocationDetails`2 call, TRequest req)
   at Grpc.Core.DefaultCallInvoker.BlockingUnaryCall[TRequest,TResponse](Method`2 method, String host, CallOptions options, TRequest request)
   at Grpc.Core.Internal.InterceptingCallInvoker.BlockingUnaryCall[TRequest,TResponse](Method`2 method, String host, CallOptions options, TRequest request)
   at Grpc.Testing.TestService.TestServiceClient.UnaryCall(SimpleRequest request, CallOptions options)
   at Grpc.Testing.TestService.TestServiceClient.UnaryCall(SimpleRequest request, Metadata headers, Nullable`1 deadline, CancellationToken cancellationToken)
   at Grpc.IntegrationTesting.InteropClient.RunComputeEngineCreds(TestServiceClient client, String defaultServiceAccount, String oauthScope)
   at Grpc.IntegrationTesting.InteropClient.<RunTestCaseAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Grpc.IntegrationTesting.InteropClient.<Run>d__4.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at Grpc.IntegrationTesting.InteropClient.<>c.<Run>b__3_1(ClientOptions options)
   at CommandLine.ParserResultExtensions.WithParsed[T](ParserResult`1 result, Action`1 action)
   at Grpc.IntegrationTesting.InteropClient.Run(String[] args)
   at Grpc.IntegrationTesting.Client.Program.Main(String[] args)

2017-08-16 14:03:47,420 FAILED: cloud_to_prod_auth:gateway_v4:csharpcoreclr:compute_engine_creds [ret=139, pid=26496]
```

sponge log in https://kokoro.corp.google.com/job/grpc/job/ubuntu/job/pull_request/job/grpc_interop_toprod/1139/

**Comment by adelez** [comment] 2017-09-06 17:06
duplicate of #12261. Closing this one because 12261 has more failures.

**Closed by adelez** 2017-09-06 17:06 UTC
Labels: infra/test env flake, lang/C#/CoreCLR
