### ISSUE TITLE
Error: Failed to connect before the deadline / Error: The async function encountered an error

### ISSUE THREAD

**Issue by Robbilie** [grpc/grpc#11411] opened 2017-06-05 21:18 UTC
### Should this be an issue in the gRPC issue tracker?
 
Create new issues for bugs and feature requests. An issue needs to be actionable. General gRPC discussions and usage questions belong to:
- [grpc.io mailing list](https://groups.google.com/forum/#!forum/grpc-io)
- [StackOverflow, with `grpc` tag](http://stackoverflow.com/questions/tagged/grpc)
 
*Please don't double post your questions in more locations, we are monitoring both channels and the time spent de-duplicating questions can is better spent answering more user questions.*
 
### What version of gRPC and what language are you using?
 1.3.7 / node
 
### What operating system (Linux, Windows, …) and version?
 Linux / Debian Stretch
 
 
### What did you do?
created new grpc client and basically did this:
```
grpc.getClientChannel(this.client).watchConnectivityState(0, 5000, (err) => {
	console.log("e", err); // Error: The async function encountered an error
})
grpc.waitForClientReady(this.client, 5000, err => {
	console.log("g", err); // Error: Failed to connect before the deadline
})
```
 
### What did you expect to see?
 Get no errors, it actually works and i can use the client. The "async" error is what triggers the deadline error, it comes instantly and not after 5s, it comes from the node c++ code.
 
### What did you see instead?
The two errors mentioned before
 
### Anything else we should know about your project / environment?
Why are there no error events emitted :(

**Comment by Robbilie** [comment] 2017-06-05 21:26
actually polling the connectivityState with the watchconnectivitystate always returns that error, even though after making the first request with the grpc client it changes the state to 2

**Comment by murgatroid99** [comment] 2017-06-05 22:33
First, `watchConnectivityState` is an undocumented private function. Please don't use it in production. Second, the problem is that the arguments to these functions should be deadlines, not timeouts. The argument `5000` corresponds to a date in the past, so the function is correctly reporting that the deadline has passed.

You should instead construct a deadline from the current time:

```js
var deadline = new Date();
deadline.setSeconds(deadline.getSeconds() + 5);
grpc.waitForClientReady(this.client, deadline, callback)
```

**Comment by Robbilie** [comment] 2017-06-05 22:51
ok wow that at least fixes the error :D 
i know its undocumented, just used it to get the error the waitForClientReady got internally :)

now, is the grpc client supposed to (successfully) reconnect?
i run the grpc server in a docker container and when i kill it the client goes back to the connecting state, i got it to reconnect sometimes but usually its stuck in that state, any idea?

**Comment by murgatroid99** [comment] 2017-06-05 22:57
If the client disconnects, then later there is a server that is listening at the same address on the same port, the client should be able to reconnect automatically. In situations where you say the client is "stuck in that state", what exactly do you observe? Have you tried making a new request when that happens?

**Comment by Robbilie** [comment] 2017-06-05 23:02
i request with setInterval 5s and its not reconnecting, localhost:50051, although earlier i had it reconnect somehow, i dont have the code anymore though :/

**Comment by murgatroid99** [comment] 2017-06-05 23:49
To be clear, when I said "make a new request", I meant that you should call a server method with the client. Just calling `getConnectivityState` alone will not make it connect.

**Comment by Robbilie** [comment] 2017-06-06 00:58
yes i know that you meant that :)

**Comment by Robbilie** [comment] 2017-06-07 14:03
any idea why its stuck for me? :)

**Comment by murgatroid99** [comment] 2017-06-09 19:56
I'm trying to reproduce the failure you're seeing. When you try to make new requests after the server restarts, are you seeing those requests fail with any particular error? In my own tests, I'm seeing "Connect failed".

**Comment by murgatroid99** [comment] 2017-06-09 20:03
Actually, upon further investigation, that error was due to a mistake in the test setup. I put together a test that connects a client to a server and makes a request, then shuts down the server and starts a new one on the same port, then the client makes another request. I see both requests succeed.

So, I'm going to need more information about your own setup to properly reproduce the failure you are seeing.

**Comment by Robbilie** [comment] 2017-06-09 20:51
setup is a grpc server in go running in a docker container which binds to port 50051 on localhost which the nodejs grpc client connects to. i then proceed to docker kill the container while the node app keeps making requests. they dont error from what i can see, they dont even timeout (if thats a thing if you dont set a deadline). i then proceed to start a new docker container with the exact same command and the node app, still running, doesnt finish the old ones nor succeeds doing the new ones (last time i checked the grpc client was in CONNECTING state). restarting the node app obviously fixes it…

**Comment by murgatroid99** [comment] 2017-06-15 23:32
I tried doing something similar with a Node client and server, and what I'm seeing is that it can take several seconds for the client to reconnect after it observes the connection drop, but it does reconnect, and the pending calls do finish.

**Comment by murgatroid99** [comment] 2017-06-15 23:38
@ctiller There is something weird going on here. I am observing that it takes a client *much* longer to reconnect to a restarted server if the client makes a call on that channel while the server is down. In other words, I tried two different things: first:

 1. Connect client to running server and make call.
 2. Stop server and make a call from the client. This fails with a "Connect failed" status.
 3. Start a new identical server on the same port, then make another call from the client. This succeeds after several seconds.

Second:

 1. Connect client to running server and make call.
 2. Stop server.
 3. Start a new identical server on the same port, then make another call from the client. This succeeds almost immediately.

Do you have any idea what's going on here?

**Comment by murgatroid99** [comment] 2017-06-16 00:25
I figured it out (somewhat). The gRPC C core has a connection retry backoff mechanism. If you make a call while the server is down, and the connection is rejected, the core will wait to retry the connection again, and the default wait time is 20 seconds. So even if you start a new call immediately after the server starts up, the connection won't be reestablished until 20 seconds after the previous attempt.

This can be modified with channel arguments (the third argument to a client constructor is an object mapping channel argument keys to values). The arguments `"grpc.initial_reconnect_backoff_ms"`, `"grpc.min_reconnect_backoff_ms"`, and `"grpc.max_reconnect_backoff_ms"` can be used to modify this behavior. They are documented [here](https://github.com/grpc/grpc/blob/master/include/grpc/impl/codegen/grpc_types.h#L236).

**Comment by Robbilie** [comment] 2017-06-16 11:50
and does it "fix" the issue?
it did not reconnect after 20s for me so i guess since i continue to do calls the 20s are being postponed on and on…?

**Comment by murgatroid99** [comment] 2017-06-19 21:29
It shouldn't do that. In my tests, the client reconnected 20 seconds after the first call that was made while the server was unavailable. If your client never reconnects, I'm not exactly sure what's going on. Are you sure that the server actually restarted successfully? Are you able to connect to that server with another client?

Have you tried the suggested fix? Did it make any difference with your situation?

**Comment by Robbilie** [comment] 2017-06-19 21:48
i am indeed able to connect to the same server with another client so it successfully starts

by fix you are referring to the channel arguments? havent tried them yet

**Comment by Robbilie** [comment] 2017-06-19 23:47
its weird, the current code reconnects perfectly fine…

**Comment by murgatroid99** [comment] 2017-06-19 23:55
In that case, it seems like you experienced a transient failure. I will close this issue until someone experiences it again.

**Closed by murgatroid99** 2017-06-19 23:56 UTC
Labels: node
