### ISSUE TITLE
Hello world fails on clang

### ISSUE THREAD

**Issue by jeroen** [grpc/grpc#8195] opened 2016-09-24 21:09 UTC
**Update**:  The `make` problem from v1.0 seems to be fixed in master and it builds but fails to run:

<img width="809" alt="screen shot 2016-09-24 at 11 17 36 pm" src="https://cloud.githubusercontent.com/assets/216319/18811354/1b0228c0-82ad-11e6-939c-d17ea4277b50.png">

This is standard macOS 10.12 compiler from Xcode 8. I use `grpc` from [homebrew-grpc](https://github.com/grpc/homebrew-grpc)

```
Jeroens-MacBook-Pro:helloworld jeroen$ brew info grpc
grpc/grpc/grpc: stable 1.0.0, HEAD
gRPC is the next generation open source RPC library and framework
http://www.grpc.io/
/usr/local/Cellar/grpc/1.0.0 (169 files, 8.9M) *
  Built from source on 2016-09-24 at 21:41:30
From: https://github.com/grpc/homebrew-grpc/blob/master/Formula/grpc.rb
==> Dependencies
Build: pkg-config ✔
Required: openssl ✔, google-protobuf ✔
==> Options
--with-plugins
    Also install gRPC protoc plugins.
--HEAD
    Install HEAD version
```

```
Jeroens-MacBook-Pro:~ jeroen$ gcc --version
Configured with: --prefix=/Library/Developer/CommandLineTools/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 8.0.0 (clang-800.0.38)
Target: x86_64-apple-darwin16.0.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
```

```
Jeroens-MacBook-Pro:~ jeroen$ clang --version
Apple LLVM version 8.0.0 (clang-800.0.38)
Target: x86_64-apple-darwin16.0.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
```

**Comment by thinkerou** [comment] 2016-09-25 02:32
Please your gcc version is?
And my is:

	➜  helloworld git:(master) ✗ gcc -v
	Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
	Apple LLVM version 7.3.0 (clang-703.0.31)
	Target: x86_64-apple-darwin15.0.0
	Thread model: posix
	InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
	➜  helloworld git:(master) ✗ g++ -v
	Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
	Apple LLVM version 7.3.0 (clang-703.0.31)
	Target: x86_64-apple-darwin15.0.0
	Thread model: posix
	InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
	➜  helloworld git:(master) ✗

**Comment by jeroenooms** [comment] 2016-09-25 08:01
OK I updated the post with this info.

**Comment by zinuga** [comment] 2016-09-27 19:08
@makdharma can you help here?

**Comment by makdharma** [comment] 2016-09-29 16:19
@jcanizales probably knows more.

**Comment by jcanizales** [comment] 2016-09-29 17:43
This is the C++ client and server, right? @yang-g is it failing in the Mac tests, and do the tests use these versions of clang and gcc?

**Comment by yang-g** [comment] 2017-12-12 00:02
I think this is a duplicate of #7830 or #10909. It should have been fixed.

**Closed by yang-g** 2017-12-12 00:02 UTC
Labels: area/build, lang/c++
