### ISSUE TITLE
FAILED: bins/opt/grpclb_end2end_test --gtest_filter=UpdatesTest.UpdateBalancersRepeated  GRPC_POLL_STRATEGY=poll

### ISSUE THREAD

**Issue by ZhouyihaiDing** [grpc/grpc#15351] opened 2018-05-13 01:28 UTC
https://source.cloud.google.com/results/invocations/bfe8362c-7895-4b87-8c8a-3a388b993da0/targets
```
I0512 15:58:19.233241000 123145567985664 grpclb_end2end_test.cc:324]   LB[0x7f9df4409e80]: sleeping for 0 ms...
I0512 15:58:19.233278000 123145567985664 grpclb_end2end_test.cc:328]   LB[0x7f9df4409e80]: Woke up! Sending response 'server_list {
  servers {
    ip_address: "\177\000\000\001"
    port: 30441
  }
}
'
test/cpp/end2end/grpclb_end2end_test.cc:560: Failure
      Expected: response.message()
      Which is: ""
To be equal to: kRequestMessage_
      Which is: "Live long and prosper."
I0512 15:58:19.233375000 123145567985664 grpclb_end2end_test.cc:270]   LB[0x7f9df4409e80]: done
I0512 15:58:21.373642000 140736657064896 grpclb_end2end_test.cc:154]   Backend: shut down
I0512 15:58:21.373698000 140736657064896 grpclb_end2end_test.cc:604]   backend about to shutdown
I0512 15:58:21.374174000 140736657064896 grpclb_end2end_test.cc:607]   backend shutdown completed
I0512 15:58:21.374200000 140736657064896 grpclb_end2end_test.cc:154]   Backend: shut down
I0512 15:58:21.374215000 140736657064896 grpclb_end2end_test.cc:604]   backend about to shutdown
I0512 15:58:21.374571000 140736657064896 grpclb_end2end_test.cc:607]   backend shutdown completed
I0512 15:58:21.374598000 140736657064896 grpclb_end2end_test.cc:154]   Backend: shut down
I0512 15:58:21.374614000 140736657064896 grpclb_end2end_test.cc:604]   backend about to shutdown
I0512 15:58:21.374966000 140736657064896 grpclb_end2end_test.cc:607]   backend shutdown completed
I0512 15:58:21.374990000 140736657064896 grpclb_end2end_test.cc:154]   Backend: shut down
I0512 15:58:21.375005000 140736657064896 grpclb_end2end_test.cc:604]   backend about to shutdown
I0512 15:58:21.375272000 140736657064896 grpclb_end2end_test.cc:607]   backend shutdown completed
I0512 15:58:21.375297000 140736657064896 grpclb_end2end_test.cc:285]   LB[0x7f9df4409e80]: shut down
I0512 15:58:21.375311000 140736657064896 grpclb_end2end_test.cc:604]   balancer about to shutdown
I0512 15:58:21.375469000 123145559400448 subchannel.cc:646]            Connect failed: {"created":"@1526165901.375433000","description":"Failed to connect to remote host: OS Error","errno":61,"file":"src/core/lib/iomgr/tcp_client_posix.cc","file_line":201,"os_error":"Connection refused","syscall":"connect","target_address":"ipv4:127.0.0.1:30441"}
I0512 15:58:21.375491000 123145559400448 subchannel.cc:470]            Subchannel 0x7f9df68026b0: Retry in 999 milliseconds
I0512 15:58:21.375850000 140736657064896 grpclb_end2end_test.cc:607]   balancer shutdown completed
I0512 15:58:21.375875000 140736657064896 grpclb_end2end_test.cc:285]   LB[0x7f9df46009d0]: shut down
I0512 15:58:21.375891000 140736657064896 grpclb_end2end_test.cc:604]   balancer about to shutdown
I0512 15:58:21.376176000 140736657064896 grpclb_end2end_test.cc:607]   balancer shutdown completed
I0512 15:58:21.376197000 140736657064896 grpclb_end2end_test.cc:285]   LB[0x7f9df4600cb0]: shut down
I0512 15:58:21.376207000 140736657064896 grpclb_end2end_test.cc:604]   balancer about to shutdown
I0512 15:58:21.376490000 140736657064896 grpclb_end2end_test.cc:607]   balancer shutdown completed
I0512 15:58:21.377504000 123145559400448 subchannel.cc:646]            Connect failed: {"created":"@1526165901.377467000","description":"Failed to connect to remote host: OS Error","errno":61,"file":"src/core/lib/iomgr/tcp_client_posix.cc","file_line":201,"os_error":"Connection refused","syscall":"connect","target_address":"ipv4:127.0.0.1:6656"}
[  FAILED  ] UpdatesTest.UpdateBalancersRepeated (20028 ms)
[----------] 1 test from UpdatesTest (20028 ms total)
[----------] Global test environment tear-down
[==========] 1 test from 1 test case ran. (20028 ms total)
[  PASSED  ] 0 tests.
[  FAILED  ] 1 test, listed below:
[  FAILED  ] UpdatesTest.UpdateBalancersRepeated
```

**Comment by AspirinSJL** [comment] 2018-05-22 22:01
Duplicate of #14673.

**Closed by AspirinSJL** 2018-05-22 22:01 UTC
Labels: infra/BUILDPONY, kind/bug, lang/c++, priority/P2
