### ISSUE TITLE
Multiple qps timeouts/failures

### ISSUE THREAD

**Issue by muxi** [grpc/grpc#9499] opened 2017-01-30 08:49 UTC
In https://grpc-testing.appspot.com/job/gRPC_performance_pull_requests/8839/consoleFull

Failed tests include:
ruby_protobuf_sync_streaming_qps_unconstrained
ruby_protobuf_sync_unary_qps_unconstrained
ruby_protobuf_unary_ping_pong
node_protobuf_async_unary_qps_unconstrained
node_protobuf_unary_ping_pong
csharp_generic_async_streaming_ping_pong
csharp_protobuf_async_streaming_ping_pong
csharp_protobuf_async_unary_ping_pong
csharp_protobuf_sync_to_async_unary_ping_pong
csharp_protobuf_async_unary_qps_unconstrained
csharp_to_cpp_protobuf_sync_unary_ping_pong
csharp_to_cpp_protobuf_async_streaming_ping_pong

**Comment by dgquintas** [comment] 2017-01-30 23:35
Seen again #9508

**Comment by dgquintas** [comment] 2017-02-07 05:23
This is happening repeatedly in the performance tests. 

Test instances that fail usually have:
```
Connect failed: {"created":"@1486406714.156364046","description":"Failed to connect to remote host: OS Error","errno":111,"file":"src/core/lib/iomgr/tcp_client_posix.c","file_line":236,"os_error":"Connection refused","syscall":"connect","target_address":"ipv4:127.0.0.1:10100"}
```
(see https://grpc-testing.appspot.com/job/gRPC_performance_pull_requests/9062/consoleFull)

**Comment by apolcyn** [comment] 2017-02-09 00:42
failure for `node_protobuf_async_unary_qps_unconstrained` seen in
https://grpc-testing.appspot.com/job/gRPC_performance_pull_requests/9137/testReport/

pr #9612 against master

**Comment by adelez** [comment] 2017-02-11 05:56
Timeout happened with  
benchmarks.qps_json_driver.quit and
benchmarks.qps_json_driver.cpp_protobuf_sync_streaming_qps_unconstrained_secure_500kib_resource_quota
https://grpc-testing.appspot.com/job/gRPC_performance_pull_requests/9206/#showFailuresLink

**Comment by dgquintas** [comment] 2017-02-11 06:09
@apolcyn is the related fix we discussed recently in?

**Comment by apolcyn** [comment] 2017-02-11 07:40
yeah the failures in the original post at top should be fixed now

**Comment by dgquintas** [comment] 2017-02-22 18:26
Duplicate of #9399 and #9668

**Closed by dgquintas** 2017-02-22 18:26 UTC
Labels: BUILDPONY, P0
