### ISSUE TITLE
C# HelloWorld ShutDownAsync Error

### ISSUE THREAD

**Issue by dalebrubaker** [grpc/grpc#7105] opened 2016-06-28 09:34 UTC
Windows 10. VS2015 Clone of master today.
After following instructions and running GreeterServer then GreeterClient, I get:
Greeting: Hello you
E0628 05:31:08.927776 0 c:\jenkins\workspace\gRPC_build_artifacts\architecture\x86\language\csharp\platform\windows\vsprojects\..\src\core\ext\transport\chttp2\transport\chttp2_transport.c:1810: close_transport: {"created":"@1467106268.927000000","description":"End of TCP stream","file":"c:\jenkins\workspace\gRPC_build_artifacts\architecture\x86\language\csharp\platform\windows\vsprojects\..\src\core\lib\iomgr\tcp_windows.c","file_line":179}

**Comment by jtattermusch** [comment] 2016-06-29 22:51
Duplicate of https://github.com/grpc/grpc/issues/7078.

**Closed by jtattermusch** 2016-06-29 22:52 UTC
