### ISSUE TITLE
gRPC module fails to build "Protobuf C++ gencode is built with a incompatible version"

### ISSUE THREAD

**Issue by chokychou** [grpc/grpc#36416] opened 2024-04-20 23:59 UTC
### What version of gRPC and what language are you using?
`C++`
bazel_dep(name = "grpc", version = "1.62.1")
bazel_dep(name = "protobuf", version = "26.0")
bazel_dep(name = "rules_cc", version = "0.0.9")

### What operating system (Linux, Windows,...) and version?
windows subsystem for linux
```
PRETTY_NAME="Ubuntu 22.04.4 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.4 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy
```

### What runtime / compiler are you using (e.g. python version or version of gcc)
```
$ gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/libexec/gcc/x86_64-linux-gnu/13/lto-wrapper
OFFLOAD_TARGET_NAMES=nvptx-none:amdgcn-amdhsa
OFFLOAD_TARGET_DEFAULT=1
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 13.1.0-8ubuntu1~22.04' --with-bugurl=file:///usr/share/doc/gcc-13/README.Bugs --enable-languages=c,ada,c++,go,d,fortran,objc,obj-c++,m2,rust --prefix=/usr --with-gcc-major-version-only --program-suffix=-13 --program-prefix=x86_64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/libexec --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --enable-bootstrap --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-plugin --enable-default-pie --with-system-zlib --enable-libphobos-checking=release --with-target-system-zlib=auto --enable-objc-gc=auto --enable-multiarch --disable-werror --enable-cet --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-offload-targets=nvptx-none=/build/gcc-13-IvzKaI/gcc-13-13.1.0/debian/tmp-nvptx/usr,amdgcn-amdhsa=/build/gcc-13-IvzKaI/gcc-13-13.1.0/debian/tmp-gcn/usr --enable-offload-defaulted --without-cuda-driver --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu --with-build-config=bootstrap-lto-lean --enable-link-serialization=2
Thread model: posix
Supported LTO compression algorithms: zlib zstd
gcc version 13.1.0 (Ubuntu 13.1.0-8ubuntu1~22.04) 
```

### What did you do?
I am trying to build do a `cc_grpc_library` build. With below files

**BUILD**
``` 
load(
    "@grpc//bazel:cc_grpc_library.bzl",
    "cc_grpc_library",
)

proto_library(
    name = "sample_proto",
    srcs = ["sample.proto"],
)

cc_proto_library(
    name = "sample_cc_proto",
    deps = [":sample_proto"],
)

cc_grpc_library(
    name = "sample_cc_grpc",
    srcs = [":sample_proto"],
    grpc_only = True,
    deps = [":sample_cc_proto"],
)
```

**.bazelrc**
```
common -c opt --enable_bzlmod
build  --cxxopt='-std=c++17' --host_cxxopt='-std=c++17'
```

**MODULE.bazel**
```
# =========================================
# Bazel module dependencies
# =========================================
bazel_dep(name = "bazel_skylib", version = "1.5.0")
bazel_dep(name = "grpc", version = "1.62.1")
bazel_dep(name = "platforms", version = "0.0.8")
bazel_dep(name = "protobuf", version = "26.0")
bazel_dep(name = "rules_cc", version = "0.0.9")
bazel_dep(name = "rules_proto", version = "6.0.0-rc3")
bazel_dep(name = "zlib", version = "1.3")
bazel_dep(name = "googleapis", version = "0.0.0-20240326-1c8d509c5")
bazel_dep(name = "googletest", version = "1.14.0.bcr.1", repo_name = "com_google_googletest")
bazel_dep(name = "google_benchmark", version = "1.8.3")

# =========================================
# Cpp dependencies
# =========================================

bazel_dep(name = "abseil-cpp", version = "20240116.2")
bazel_dep(name = "rules_foreign_cc", version = "0.10.1")
bazel_dep(name = "glog", version = "0.7.0")
```

**WOKRSPACE.bzl**
```
load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")


http_archive(
    name = "com_github_grpc_grpc",
    urls = [
        "https://github.com/grpc/grpc/archive/refs/tags/v1.62.0.tar.gz",
    ],
    strip_prefix = "grpc-1.62.0",
)
load("@com_github_grpc_grpc//bazel:grpc_deps.bzl", "grpc_deps")
grpc_deps()
load("@com_github_grpc_grpc//bazel:grpc_extra_deps.bzl", "grpc_extra_deps")
grpc_extra_deps()
```

### What did you expect to see?
Expect a successful build. 

### What did you see instead?
```
In file included from bazel-out/k8-opt-exec-ST-13d3ddad9198/bin/external/com_google_protobuf/src/google/protobuf/util/_virtual_includes/time_util/google/protobuf/util/time_util.h:30,
                 from external/com_google_protobuf/src/google/protobuf/util/time_util.cc:8:
bazel-out/k8-opt-exec-ST-13d3ddad9198/bin/external/com_google_protobuf/src/google/protobuf/_virtual_includes/duration_proto/google/protobuf/duration.pb.h:15:2: error: #error "Protobuf C++ gencode is built with an incompatible version of"
   15 | #error "Protobuf C++ gencode is built with an incompatible version of"
      |  ^~~~~
bazel-out/k8-opt-exec-ST-13d3ddad9198/bin/external/com_google_protobuf/src/google/protobuf/_virtual_includes/duration_proto/google/protobuf/duration.pb.h:16:2: error: #error "Protobuf C++ headers/runtime. See"
   16 | #error "Protobuf C++ headers/runtime. See"
      |  ^~~~~
bazel-out/k8-opt-exec-ST-13d3ddad9198/bin/external/com_google_protobuf/src/google/protobuf/_virtual_includes/duration_proto/google/protobuf/duration.pb.h:17:2: error: #error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
   17 | #error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
      |  ^~~~~
In file included from bazel-out/k8-opt-exec-ST-13d3ddad9198/bin/external/com_google_protobuf/src/google/protobuf/util/_virtual_includes/time_util/google/protobuf/util/time_util.h:31:
bazel-out/k8-opt-exec-ST-13d3ddad9198/bin/external/com_google_protobuf/src/google/protobuf/_virtual_includes/timestamp_proto/google/protobuf/timestamp.pb.h:15:2: error: #error "Protobuf C++ gencode is built with an incompatible version of"
   15 | #error "Protobuf C++ gencode is built with an incompatible version of"
      |  ^~~~~
bazel-out/k8-opt-exec-ST-13d3ddad9198/bin/external/com_google_protobuf/src/google/protobuf/_virtual_includes/timestamp_proto/google/protobuf/timestamp.pb.h:16:2: error: #error "Protobuf C++ headers/runtime. See"
   16 | #error "Protobuf C++ headers/runtime. See"
      |  ^~~~~
bazel-out/k8-opt-exec-ST-13d3ddad9198/bin/external/com_google_protobuf/src/google/protobuf/_virtual_includes/timestamp_proto/google/protobuf/timestamp.pb.h:17:2: error: #error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
   17 | #error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
      |  ^~~~~
bazel-out/k8-opt-exec-ST-13d3ddad9198/bin/external/com_google_protobuf/src/google/protobuf/_virtual_includes/duration_proto/google/protobuf/duration.pb.h: In member function 'virtual google::protobuf::Duration* google::protobuf::Duration::New(google::protobuf::Arena*) const':
bazel-out/k8-opt-exec-ST-13d3ddad9198/bin/external/com_google_protobuf/src/google/protobuf/_virtual_includes/duration_proto/google/protobuf/duration.pb.h:146:41: error: 'DefaultConstruct' is not a member of 'google::protobuf::Message'
  146 |     return ::google::protobuf::Message::DefaultConstruct<Duration>(arena);
      |                                         ^~~~~~~~~~~~~~~~
bazel-out/k8-opt-exec-ST-13d3ddad9198/bin/external/com_google_protobuf/src/google/protobuf/_virtual_includes/duration_proto/google/protobuf/duration.pb.h:146:66: error: expected primary-expression before '>' token
  146 |     return ::google::protobuf::Message::DefaultConstruct<Duration>(arena);
      |                                                                  ^
bazel-out/k8-opt-exec-ST-13d3ddad9198/bin/external/com_google_protobuf/src/google/protobuf/_virtual_includes/timestamp_proto/google/protobuf/timestamp.pb.h: In member function 'virtual google::protobuf::Timestamp* google::protobuf::Timestamp::New(google::protobuf::Arena*) const':
bazel-out/k8-opt-exec-ST-13d3ddad9198/bin/external/com_google_protobuf/src/google/protobuf/_virtual_includes/timestamp_proto/google/protobuf/timestamp.pb.h:146:41: error: 'DefaultConstruct' is not a member of 'google::protobuf::Message'
  146 |     return ::google::protobuf::Message::DefaultConstruct<Timestamp>(arena);
      |                                         ^~~~~~~~~~~~~~~~
bazel-out/k8-opt-exec-ST-13d3ddad9198/bin/external/com_google_protobuf/src/google/protobuf/_virtual_includes/timestamp_proto/google/protobuf/timestamp.pb.h:146:67: error: expected primary-expression before '>' token
  146 |     return ::google::protobuf::Message::DefaultConstruct<Timestamp>(arena);
      |                                                                   ^
Target //:sample_cc_grpc failed to build
```

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

See [TROUBLESHOOTING.md](https://github.com/grpc/grpc/blob/master/TROUBLESHOOTING.md) for how to diagnose problems better.

**Comment by veblush** [comment] 2024-04-23 19:35
Thank you for the report but gRPC doesn't support bzlmod officially. But we're willing to accept the fixes for this issue.

**Comment by veblush** [comment] 2024-04-23 19:57
I'm closing this as a duplicate of https://github.com/grpc/grpc/issues/35271

**Closed by veblush** 2024-04-23 19:57 UTC
Labels: kind/bug, disposition/help wanted, lang/c++, priority/P2, area/build
