### ISSUE TITLE
cross compile grpc on android but stuck in pollset_work function

### ISSUE THREAD

**Issue by boyiliao9102** [grpc/grpc#12665] opened 2017-09-21 04:34 UTC
Please answer these questions before submitting your issue. 
 
### Should this be an issue in the gRPC issue tracker?
 
Create new issues for bugs and feature requests. An issue needs to be actionable. General gRPC discussions and usage questions belong to:
- [grpc.io mailing list](https://groups.google.com/forum/#!forum/grpc-io)
- [StackOverflow, with `grpc` tag](http://stackoverflow.com/questions/tagged/grpc)
 
*Please don't double post your questions in more locations; we are monitoring both channels, and the time spent de-duplicating questions is better spent answering more user questions.*
 
### What version of gRPC and what language are you using?
 git clone follow  googlesamples/assistant-sdk-cpp  README.md   "git clone -b $(curl -L https://grpc.io/release) https://github.com/grpc/grpc" 
 
### What operating system (Linux, Windows, …) and version?
 use ubuntu 14.04 as host , and porting  using android-ndk-r15c-linux-x86_64.zip SDK
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
 arm-linux-androideabi-gcc (GCC) 4.9.x 20150123 (prerelease)

 
### What did you do?
If possible, provide a recipe for reproducing the error. Try being specific and include code snippets if helpful.
 
I use ndk r15 standalone toolchain and porting google assistant-sdk-cpp with grpc to android arm platform.

I also port curl and ssl packages to make it works. after got the run_assistant and run on arm android platform, i found it stuck in

std::shared_ptr> stream(std::move(assistant->Converse(&context))); in run_assistant.cc function.

And i keep tracing the source , i found it stuck at " r = grpc_poll_function(pfds, pfd_count, timeout);" in pollset_work() function in ev_poll_posix.c.

Because grpc_poll_function is from the system poll point.

Is this the Android issue, or porting issue ?

### What did you expect to see?
to make sure,  is ndk limitation or grpc prting issue ? 
 
### What did you see instead?
 
Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).
 
i printf out the message to verify the code running step, i found when it ran here "grpc_poll_function(pfds, pfd_count, timeout);" in pollset_work() function in ev_poll_posix.c."
it will stuck, it will not move on.

**Comment by ericgribkoff** [comment] 2018-01-27 01:49
gRPC C++ should work fine on Android (see https://github.com/grpc/grpc/pull/14193). Are you still having this issue with up-to-date versions of the assistant sdk and gRPC? From the information you've provided it sounds like the issue is more likely with the assistant sdk rather than something specific to gRPC.

@nicolasnoble Feel free to reassign this issue to me (I somehow lost my privileges to assign issues or PRs on this repo)

**Comment by ericgribkoff** [comment] 2019-02-20 19:24
Closing as presumably obsolete. We know build C++ for Android as part of our CI

**Closed by ericgribkoff** 2019-02-20 19:24 UTC
Labels: area/build, kind/bug, lang/c++, priority/P2
