### ISSUE TITLE
A strange crash

### ISSUE THREAD

**Issue by SarielTang** [grpc/grpc#22505] opened 2020-03-28 09:36 UTC
![image](https://user-images.githubusercontent.com/12050371/77820067-86084a00-711a-11ea-9c75-f0e133e63b44.png)
The crash information is shown above.

**Comment by SarielTang** [comment] 2020-03-30 09:23
We have promotion from 3 to 5 o'clock, so the crashes are concentrated in this period.

**Comment by stanley-cheung** [comment] 2020-04-02 00:43
@SarielTang Can you share how we can reproduce this issue please? Is there an xcode project you can share?

**Comment by SarielTang** [comment] 2020-04-07 02:38
Sorry, we also happen occasionally, I don't know how to reproduce.

**Comment by stanley-cheung** [comment] 2020-05-07 04:09
still an issue

**Comment by yulin-liang** [comment] 2021-03-31 22:28
Closing since we are not hearing response. We can reopen if necessary.

**Closed by yulin-liang** 2021-03-31 22:28 UTC
Labels: kind/bug, lang/ObjC, priority/P2
