### ISSUE TITLE
MetadataFlagsTest failed

### ISSUE THREAD

**Issue by karthikravis** [grpc/grpc#23707] opened 2020-07-31 17:43 UTC
https://source.cloud.google.com/results/invocations/b6a2dd77-49ad-4540-911d-dce4546bdb6d/log

Errors/Failures:
unit._metadata_flags_test.MetadataFlagsTest.test_call_wait_for_ready_enabled
traceback:
Traceback (most recent call last):
  File "/usr/lib/python3.7/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/usr/lib/python3.7/unittest/case.py", line 615, in run
    testMethod()
  File "/var/local/git/grpc/src/python/grpcio_tests/tests/unit/_metadata_flags_test.py", line 245, in test_call_wait_for_ready_enabled
    server.add_insecure_port(addr)
  File "/var/local/git/grpc/py37_native/lib/python3.7/site-packages/grpc/_server.py", line 962, in add_insecure_port
    address, _add_insecure_port(self._state, _common.encode(address)))
  File "/var/local/git/grpc/py37_native/lib/python3.7/site-packages/grpc/_common.py", line 166, in validate_port_binding_result
    raise RuntimeError(_ERROR_MESSAGE_PORT_BINDING_FAILED % address)
RuntimeError: Failed to bind to address localhost:39219; set GRPC_VERBOSITY=debug environment variable to see detailed error message.

stdout:

stderr:
E0730 19:50:34.699882581   28647 server_chttp2.cc:40]        {"created":"@1596138634.699814614","description":"No address added out of total 2 resolved","file":"src/core/ext/transport/chttp2/server/chttp2_server.cc","file_line":310,"referenced_errors":[{"created":"@1596138634.699791179","description":"Unable to configure socket","fd":11,"file":"src/core/lib/iomgr/tcp_server_utils_posix_common.cc","file_line":215,"referenced_errors":[{"created":"@1596138634.699786328","description":"Address already in use","errno":98,"file":"src/core/lib/iomgr/tcp_server_utils_posix_common.cc","file_line":188,"os_error":"Address already in use","syscall":"bind"}]},{"created":"@1596138634.699809114","description":"Unable to configure socket","fd":11,"file":"src/core/lib/iomgr/tcp_server_utils_posix_common.cc","file_line":215,"referenced_errors":[{"created":"@1596138634.699805135","description":"Address already in use","errno":98,"file":"src/core/lib/iomgr/tcp_server_utils_posix_common.cc","file_line":188,"os_error":"Address already in use","syscall":"bind"}]}]}

Unexpected successes: []
Test failure

2020-07-30 19:50:34,851 FAILED: py37_native.test.unit._metadata_flags_test.MetadataFlagsTest [ret=1, pid=27326, time=2.9sec]

**Comment by lidizheng** [comment] 2020-08-03 19:08
This flake is caused by the race condition between obtaining an unused port and assigning it to a server. There isn't a better way to fix this issue. This race wasn't revealed before because Python doesn't check port binding result until recently. Technically, this flake rate should be low.

Please reopen if there is an evidence of high flake rate.

**Closed by lidizheng** 2020-08-03 19:08 UTC
Labels: disposition/BUILDCOP, kind/bug, lang/Python, priority/P2
