### ISSUE TITLE
Multi Language Linux Protoc Bazel Issue

### ISSUE THREAD

**Issue by ncteisen** [grpc/grpc#13461] opened 2017-11-20 18:06 UTC
Failed test [logs](https://sponge.corp.google.com/target?id=90c900eb-18e8-4413-8e89-f697e3a427b4&target=github/grpc/sanity_linux_dbg_native&searchFor=&show=FAILED&sortBy=STATUS)

```
Failure
Extracting Bazel installation...
...................
____Loading package: 
____Loading package: tools/defaults
____Loading package: @bazel_tools//tools/genrule
____Loading package: @local_config_cc//
ERROR: /var/local/git/grpc/third_party/protobuf/BUILD:283:1: in cc_library rule //:protoc_lib: cycle in dependency graph:
.-> //:protoc_lib
|   //:protobuf
|   //:src/google/protobuf/unittest_custom_options.pb.h
|   //:cc_test_protos_genproto
|   //:protoc
`-- //:protoc_lib.
ERROR: Loading of target '//:protoc_lib' failed; build aborted.
ERROR: Evaluation of query "deps(//:protoc_lib)" failed due to BUILD file errors.
Traceback (most recent call last):
  File "tools/distrib/python/check_grpcio_tools.py", line 25, in <module>
    check_protoc_lib_deps_content = make.get_deps()
  File "/var/local/git/grpc/tools/distrib/python/make_grpcio_tools.py", line 89, in get_deps
    cc_files_output = bazel_query(BAZEL_DEPS_PROTOC_LIB_QUERY)
  File "/var/local/git/grpc/tools/distrib/python/make_grpcio_tools.py", line 83, in bazel_query
    output = subprocess.check_output([BAZEL_DEPS, query])
  File "/usr/lib/python2.7/subprocess.py", line 573, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command '['/var/local/git/grpc/tools/distrib/python/bazel_deps.sh', '//:protoc_lib']' returned non-zero exit status 7
```

Looks like a Bazel failure due to protoc artifacts. I have seen this locally and fixed it by `git clean -xfd`-ing the protobuf submodule. Don't know why this would happen on a linux worker though

**Comment by mehrdada** [comment] 2017-11-20 21:52
Dupe of #13404.

Just submitted https://github.com/grpc/grpc/pull/13463 which should fix the issue

**Closed by mehrdada** 2017-11-20 21:52 UTC
