### ISSUE TITLE
grpcio fails to install as a dependency from pyhelm

### ISSUE THREAD

**Issue by joaocc** [grpc/grpc#14563] opened 2018-03-01 21:44 UTC
### What version of gRPC and what language are you using?
Python 3.6.4
Trying to install 0.3.post19
 
### What operating system (Linux, Windows, …) and version?
Darwin HSz-MBP-J 16.7.0 Darwin Kernel Version 16.7.0: Thu Jan 11 22:59:40 PST 2018; root:xnu-3789.73.8~1/RELEASE_X86_64 x86_64
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
Python 3.6.4
 
### What did you do?
Tried to install grpcio (as a requirement from pyhelm)
 
### What did you expect to see?
package installing correctly
 
### What did you see instead?
```
ip3 install --upgrade pyhelm grpcio
Collecting pyhelm
  Using cached pyhelm-0.0.1.dev33.tar.gz
Requirement already up-to-date: grpcio in /usr/local/lib/python3.6/site-packages
Collecting grpc==0.3.post19 (from pyhelm)
  Using cached grpc-0.3-19.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/x0/0fb1ckx53f58_t_yh8shttm80000gp/T/pip-build-2kh5qcw4/grpc/setup.py", line 7, in <module>
        version_tuple = __import__('grpc').VERSION
      File "/private/var/folders/x0/0fb1ckx53f58_t_yh8shttm80000gp/T/pip-build-2kh5qcw4/grpc/grpc/__init__.py", line 6, in <module>
        from .rpc import *
      File "/private/var/folders/x0/0fb1ckx53f58_t_yh8shttm80000gp/T/pip-build-2kh5qcw4/grpc/grpc/rpc.py", line 141
        except OSError, ex:
                      ^
    SyntaxError: invalid syntax

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/x0/0fb1ckx53f58_t_yh8shttm80000gp/T/pip-build-2kh5qcw4/grpc/
```
Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).
 
### Anything else we should know about your project / environment?
Not sure if this is relevant...
```
$ pip3 install  grpcio
Requirement already satisfied: grpcio in /usr/local/lib/python3.6/site-packages
Requirement already satisfied: protobuf>=3.5.0.post1 in /usr/local/lib/python3.6/site-packages (from grpcio)
Requirement already satisfied: six>=1.5.2 in /usr/local/lib/python3.6/site-packages (from grpcio)
Requirement already satisfied: setuptools in /usr/local/lib/python3.6/site-packages (from protobuf>=3.5.0.post1->grpcio)
```

**Comment by joaocc** [comment] 2018-03-02 12:49
being addressed here https://github.com/flaper87/pyhelm/issues/9

**Comment by mehrdada** [comment] 2018-03-02 17:10
Probably a dupe of https://github.com/grpc/grpc/issues/14573 and should be fixed now. Please retry (ensure pip is not using previously cached package if it is failing). Let us know if that is fixed for you.

**Comment by mehrdada** [comment] 2018-03-02 17:19
@joaocc I just tried installing on macOS, and it seems like there's a misconception here: `grpc` package is not us at all :-)

This gRPC project is served under `grpcio` PyPI package, not `grpc`.  I see `pip` install ends up fetching `grpcio` too, but it is depending on a very old version of that, and but nevertheless that's not where it is failing. It's failing on `grpc` compilation, which is not us (wrong number!).

**Closed by mehrdada** 2018-03-02 17:19 UTC
Labels: lang/Python, platform/macOS

**Comment by joaocc** [comment] 2018-03-02 20:22
lol. you are right. sorry about the confusion.
