### ISSUE TITLE
Getting Internal Error (GOAWAY) when server goes down

### ISSUE THREAD

**Issue by cw-pratik** [grpc/grpc#14109] opened 2018-01-22 06:44 UTC
### What version of gRPC and what language are you using?
 
Upgrading gRPC version from 1.1.0 to 1.8.0 

### What operating system (Linux, Windows, …) and version?
 
Windows
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
 
using c# .Net framework 4.5.2
 
### What did you do?

We were using gRPC 1.1.0 on our production servers since a long time. We had done some stress testing and found out that having multiple channels per server gave us better results. So if we have two servers A and B. Then we would create 5 Channels each for server A and server B. And then make calls to the servers in round robin fashion. This gave us a pretty good throughput.

Then we upgraded our servers and clients to 1.8.0 some time back. Everything worked fine when the servers were working. But when one of the server went down we started getting Internal RPC error. 

```
ERROR [51] ExceptionHandler LogException - Grpc.Core.RpcException: Status(StatusCode=Internal, Detail="GOAWAY received")
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Grpc.Core.Internal.AsyncCall`2.UnaryCall(TRequest msg)
   at Grpc.Core.DefaultCallInvoker.BlockingUnaryCall[TRequest,TResponse](Method`2 method, String host, CallOptions options, TRequest request)
   at Grpc.Core.Internal.InterceptingCallInvoker.BlockingUnaryCall[TRequest,TResponse](Method`2 method, String host, CallOptions options, TRequest request)
   at EditCMSWindowsService.Messages.EditCMSGrpcService.EditCMSGrpcServiceClient.GetArticleViewsCount(GrpcInt request, CallOptions options)
```
 
Strangely this error did not occur every time, and when it did, it would on random clients. 
And sometimes this error is also seen when the server is actually up.

Then when I was trying to recreate this error, I found out that this error was easily reproduced when I created a lot of instances (10) to the same server. Also the state of the clients was constantly idle instead of transient failure or connecting.

As soon as I created only one instance to the server the errors went away.

We also have servers and clients running on goLang. This issue is not there on those servers.

I also have a few questions:

1) Is using multiple instances of the channel to the same server the correct thing to do?
2) If yes, the above thing needs to be fixed.
3) If no. Then there is a lot of overhead in thread management when there are a large number of calls. What is the best way to mitigate that.

**Comment by Thaina** [comment] 2018-02-06 03:13
Using firestore from google cloud dotnet and got this error too. Using it on aws lambda that is serverless might be related

**Comment by jtattermusch** [comment] 2019-02-18 14:53
Is this still a problem?

**Comment by cw-pratik** [comment] 2019-02-19 04:12
Give me a day..will check again and let you know

**Comment by Wisgary** [comment] 2019-03-21 21:53
This hits me as well in virtually the same scenario. Very easy to repro without shutting down the server by using max_age. I actually just posted a comment yesterday on a separate thread as I had not seen this one, as well as a post on groups. 

[Group post](https://groups.google.com/forum/#!topic/grpc-io/6BuN-YNCm1Y)
See also my comment on [#15623](https://github.com/grpc/grpc/issues/15623#issuecomment-475137396)

**Comment by jaaant** [comment] 2019-08-08 08:07
We're also getting these errors every now and then.

**gRPC version and language:** 1.18.0, C++

**Operating system:** Windows 10

**Compiler:** Visual Studio 2017

We're running two gRPC servers side by side in the same program. At the end of the program, the servers are shut down one after another, and occasionally a client connected to the server that is shut down first receives error code 13 (INTERNAL) with message "GOAWAY received" as a response to a call.

We've also seen the following error messages during server shutdown, logged over 500 times by each server. Each error has a different tag, and the errors from different servers have different creation times, but otherwise the messages are all identical. The error messages can occur even when the internal error doesn't, so they may not actually be related.

`<path>\src\core\lib\surface\completion_queue.cc, 701: Operation failed: tag=00000162B92FAF90, error={"created":"@1564660008.259000000","description":"Server Shutdown","file":"<path>\src\core\lib\surface\server.cc","file_line":1345}`

**Comment by jtattermusch** [comment] 2019-11-12 08:48
@jaaant   can you come up with code that reliably reproduces the problem?

**Comment by jaaant** [comment] 2019-11-14 09:26
The following code reproduces the internal error. Run the server, then the client; when the server shuts down after the timeout, the client gets the error on its next call.

Server:
```
#include "service/service.grpc.pb.h"
#include "grpcpp\grpcpp.h"
#include <iostream>

using namespace grpc;
using namespace std;

class ServiceImpl : public test::MyService::Service {
  Status DoStuff(ServerContext* c, const test::Request* req, test::Response* res) override {
    return Status::OK;
  }
};

unique_ptr<Server> BuildServer(string addr) {
  ServerBuilder builder;
  builder.RegisterService(new ServiceImpl());
  builder.AddListeningPort(addr, InsecureServerCredentials());
  return builder.BuildAndStart();
}

int main() {
  auto server1 = BuildServer("0.0.0.0:5000");
  auto server2 = BuildServer("0.0.0.0:5001");
  cout << "Servers running." << endl;

  Sleep(10*1000);

  cout << "Shutting down." << endl;
  server1->Shutdown();
  server2->Shutdown();

  return 0;
}
```

Client:
```
#include "service/service.grpc.pb.h"
#include "grpcpp\grpcpp.h"
#include <iostream>

using namespace grpc;
using namespace std;

int main() {
  auto channel = CreateChannel("localhost:5000", InsecureChannelCredentials());
  auto client = test::MyService::NewStub(channel);

  Status status = Status::OK;
  while(status.error_code() == StatusCode::OK) {
    test::Response response;
    status = client->DoStuff(new ClientContext(), {}, &response);
    Sleep(1000);
  }

  cout << status.error_code() << ": " << status.error_message() << endl;

  return 0;
}
```

.proto:
```
syntax = "proto3";

package test;

message Request { int32 id = 1; }
message Response { int32 id = 1; }
service MyService {
  rpc DoStuff( Request ) returns( Response );
}
```

**Comment by apolcyn** [comment] 2020-05-05 18:46
@jtattermusch have time to take a look at this?

**Comment by jtattermusch** [comment] 2020-05-07 16:31
@jaaant  could you provide simple runnable project that reproduces the problem (ideally as e.g. a git repo)? I would make reproducing the problem much easier.

**Comment by jaaant** [comment] 2020-05-11 07:33
@jtattermusch A Visual Studio project is now at https://github.com/jaaant/GrpcServerShutdownTest.

**Comment by rburns1293** [comment] 2022-04-06 01:31
The behavior isn't completely surprising. The server is likely rejecting a client request made during a server shutdown. This is so the client and server can shutdown gracefully. A GOAWAY isn't the most transparent error from this older version, however using Grpc.Core from the head and running the test below (which recreates the case of making a request to a server shutting down) results in an error that would be clearer for your logs. 
```
---> Grpc.Core.RpcException : Status(StatusCode="Unavailable", Detail="End of TCP stream", DebugException="Grpc.Core.Internal.CoreErrorDetailException: {"created":"@1649207509.096000000","description":"Error received from peer ipv6:[::1]:56306","file":"C:\Users\rburn\Workspace\internalGoAway\grpc\src\core\lib\surface\call.cc","file_line":950,"grpc_message":"End of TCP stream","grpc_status":14}")
```

Test: 
``` C#
        [Test]
        public async Task InternalGoAway()
        {
            // Make a single request. 
            channel = new Channel(Host, port, ChannelCredentials.Insecure);
            client = new TestService.TestServiceClient(channel);
            Task makeCall = Task.Run(async () => {
                Console.WriteLine("Starting Call 1.");
                await client.UnaryCallAsync(new SimpleRequest());
                Console.WriteLine("Finished Call 1");
            });
            var channel2 = new Channel(Host, port, ChannelCredentials.Insecure);
            var client2 = new TestService.TestServiceClient(channel);

            Task shutdownServer = Task.Run(async () => {
                Console.WriteLine("Starting Server shutdown...");
                await server.ShutdownAsync();
                Console.WriteLine("Server shutdown!");
                server = null;
            });

            Console.WriteLine("Wait...");
            await Task.Delay(5000);
            Console.WriteLine("Wait done!");

            // Attempt a new call
            try 
            {
                Console.WriteLine("Starting Call 2.");
                await client2.UnaryCallAsync(new SimpleRequest());
                Console.WriteLine("Finished Call 2.");
            } catch (RpcException e) {
                Console.WriteLine("Exception thrown!");
                shutdownServer.Wait();
                makeCall.Wait();
                Assert.Fail(e.Message);
            }

            shutdownServer.Wait();
            makeCall.Wait();
        }

        private class EchoImpl : Testing.TestServiceImpl {
            public override async Task<SimpleResponse> UnaryCall(SimpleRequest request, ServerCallContext context)
            {
                await Task.Delay(10000);
                return new SimpleResponse();
            }
        }
    }
```

Console Output: 
```
Starting Call 1.
Wait...
Starting Server shutdown...
Server shutdown!
Wait done!
Starting Call 2.
Exception thrown.
```

**Comment by jaaant** [comment] 2022-04-06 06:46
Getting an error at the client when the server is shut down is not at all surprising, and it's not even difficult to handle once you know that's the cause.

What's worrying is that this is specifically an Internal error, which according to the documentation "Means some invariants expected by underlying System has been broken. If you see one of these errors, Something is very broken." It looks like the server can end up in an illegal state somehow, and that could have worse consequences than an uninformative error message.

We at least don't have any acute problems related to this issue. But seeing this kind of error occur at all is troubling.

**Comment by jtattermusch** [comment] 2022-04-06 12:36
> Getting an error at the client when the server is shut down is not at all surprising, and it's not even difficult to handle once you know that's the cause.
> 
> What's worrying is that this is specifically an Internal error, which according to the documentation "Means some invariants expected by underlying System has been broken. If you see one of these errors, Something is very broken." It looks like the server can end up in an illegal state somehow, and that could have worse consequences than an uninformative error message.

Can you try whether you're still getting the Internal error with the newest version of gRPC? The handling of the error when a server being shut down closes the connection on you might have improved since the time the issue has been filed (the issue is quite old).
Looking at the [status code](https://github.com/grpc/grpc/blob/master/doc/statuscodes.md) documentation though, I still don't think occasionally getting "Internal" status as error code when trying to connect to a server that's in the process of being shutdown is a bug per se. There might be (and probably there is) some inherent cornercase in the server shutdown sequence that prevents handling all possible timings and situations (e.g. if you're very unlucky, you can successfully connect to the server side socket just before it's being closed by the server, and it that case the server would just hang up on the client and it's virtually impossible to differentiate this situations from other things that might go wrong, it just sees that something went "very bad"). So I don't think we can say that occasionally getting "Internal" error code when connecting to a server that's shutting down is categorically wrong.

So unless you are consistently seeing the "Internal" error in a situation that's clearly detectable by the client and should clearly use a different status code (and looks like that's not the case based on the repro from @rburns1293), I'm going to close this issue (since at this point we can't really do much).

> 
> We at least don't have any acute problems related to this issue. But seeing this kind of error occur at all is troubling.

**Closed by jtattermusch** 2022-04-06 12:36 UTC
Labels: kind/bug, lang/c++, lang/C#, platform/Windows, priority/P2, untriaged

**Comment by jaaant** [comment] 2022-04-07 11:05
Sorry, I haven't worked with gRPC for a long time now and don't have any of the libraries ready for testing. The reproduction code I provided earlier is still available if someone else want to take a look.

In case I wasn't clear, I'm not really worried about an unclear error message in a situation where we don't know the exact cause of failure. But both the [reference documentation](https://grpc.github.io/grpc/cpp/namespacegrpc.html#aff1730578c90160528f6a8d67ef5c43ba0ae30536146394965fd8ad64c2d414f3) and the document you linked agree that this error code means a breach of invariant. Barring a hardware failure or similar problem that prevents the program from being executed as written, that's supposed to literally never happen. In that sense, getting this error code really is categorically wrong in any situation, and tells us that the program is not working correctly. Or if you're actually throwing these errors in expected situations, the documentation should be amended.
