### ISSUE TITLE
PHP:  pecl install error

### ISSUE THREAD

**Issue by s1lver** [grpc/grpc#22554] opened 2020-04-02 16:33 UTC
### What version of gRPC and what language are you using?
gRPC 1.27
gRPC 1.28RC2
gRPC 1.28.0

PHP 7.2.8

### What operating system (Linux, Windows,...) and version?
RHEL 7

### What runtime / compiler are you using (e.g. python version or version of gcc)
gcc 4.8.5

I use command
`sudo pecl install grpc-1.27.0.tgz`
and
`sudo pecl install grpc-1.28.0RC2.tgz`
and 
`sudo pecl install grpc-1.28.0.tgz`

I get an error
```
In function 'grpc_error* grpc_set_socket_tcp_user_timeout(int, const grpc_channel_args*, bool)
/var/tmp/grpc/src/core/lib/iomgr/socket_utils_common_posix.cc: In function 'grpc_error* grpc_set_socket_tcp_user_timeout(int, const grpc_channel_args*, bool)':
/var/tmp/grpc/src/core/lib/iomgr/socket_utils_common_posix.cc:325:42: error: 'TCP_USER_TIMEOUT' was not declared in this scope
     if (0 != setsockopt(fd, IPPROTO_TCP, TCP_USER_TIMEOUT, &timeout,
/var/tmp/grpc/src/core/lib/iomgr/socket_utils_common_posix.cc:330:42: error: 'TCP_USER_TIMEOUT' was not declared in this scope
     if (0 != getsockopt(fd, IPPROTO_TCP, TCP_USER_TIMEOUT, &newval, &len)) {

make: *** [src/core/lib/iomgr/socket_utils_common_posix.lo] Error 1

ERROR:  `make` failed
```

**Comment by stanley-cheung** [comment] 2020-04-03 22:56
@s1lver Thanks for the report. Does this work prior to 1.27.0?

**Comment by Lola150716** [comment] 2020-04-04 03:51
GTI

**Comment by Lola150716** [comment] 2020-04-04 03:52
> GTI

**Comment by Lola150716** [comment] 2020-04-04 03:58
>    ##@`
Duplicate of #`

**Comment by Lola150716** [comment] 2020-04-04 03:59
Duplicate of # #21773

**Comment by stanley-cheung** [comment] 2020-04-04 04:14
Hm, doesn't look like this is a duplicate of #21773.

**Comment by s1lver** [comment] 2020-04-05 09:40
> @s1lver Thanks for the report. Does this work prior to 1.27.0?

I didn't check

**Comment by s1lver** [comment] 2020-04-06 05:37
I check 1.25 and 1.26 version - same error

**Comment by stanley-cheung** [comment] 2020-04-10 01:03
@s1lver So we did some research on this. Turns out - the minimum requirement for `gcc` has been recently set to 4.9+. See https://grpc.io/about/. The bump of requirement from 4.8 to 4.9 happened at PR #21671, which is picked up by the PHP extension by version 1.27.0 and after.

But when we test the install with gcc 4.9, in RHEL 7, with PHP 7.2, we ran into another error, but almost the same we found in this PHP issue: https://bugs.php.net/bug.php?id=75852.

```
In file included from /usr/include/php/Zend/zend.h:328:0,
                 from /usr/include/php/main/php.h:35,
                 from /var/tmp/grpc/src/php/ext/grpc/byte_buffer.c:19:
/usr/include/php/Zend/zend_operators.h: In function 'fast_long_increment_function':

/usr/include/php/Zend/zend_operators.h:446:2: error: implicit declaration of function '__builtin_saddl_overflow' [-Werror=implicit-function-declaration]
  if (UNEXPECTED(__builtin_saddl_overflow(Z_LVAL_P(op1), 1, &lresult))) {
  ^
/usr/include/php/Zend/zend_operators.h: In function 'fast_long_decrement_function':
/usr/include/php/Zend/zend_operators.h:500:2: error: implicit declaration of function '__builtin_ssubl_overflow' [-Werror=implicit-function-declaration]
  if (UNEXPECTED(__builtin_ssubl_overflow(Z_LVAL_P(op1), 1, &lresult))) {
  ^

/var/tmp/grpc/src/php/ext/grpc/byte_buffer.c: At top level:
cc1: error: unrecognized command line option "-Wno-parentheses-equality" [-Werror]
cc1: all warnings being treated as errors
make: *** [src/php/ext/grpc/byte_buffer.lo] Error 1
ERROR: `make' failed
```

The error comes from some PHP source file, not from our grpc extension. Reading that issue, looks like for PHP 7.2, you actually have to upgrade gcc to version 5 at least. We tried the `pear` version 1.10.9+ but didn't have success. We do have success after upgrading gcc to version 5.

So can you try that out please? Thanks.

**Closed** 2020-05-05 18:16 UTC
Labels: kind/bug, priority/P1
