### ISSUE TITLE
When a custom IOMGR is used, fork handles must be skipped

### ISSUE THREAD

**Issue by pfreixes** [grpc/grpc#19961] opened 2019-08-15 05:35 UTC
The current version of master does not skip the fork handles if the `iomgr` does not match with the one provided by default by the gRPC library [1]

Since current code is actually warning that any `iomgr` that is not `poll` and nor `epoll1` is not currently supported, what I would expect is having the fork handles skipped.

This is creating some friction with the addition of the new  experimental `Aio` module [2] which uses its own fork handles [3] based on the following rules:

- Timer background threads are stopped since they are not used
when the Asyncio custom iomgr is used.
- Executor thread background is disabled, all callbacks are executed
within the same thread used by the Asyncio loop.
- Any forked process is responsible for starting the gRPC
library, `Aio` module guarantees that the gRPC is gracefully stopped before returning the
control back to the forked process.

### Suggestions for solving the issue
There are at least two different ways for solving that issue, by:

- Having the core library skipping the fork handles if the `iomgr` can not be matched with the supported ones
- Promoting the `Fork::Enable` [4] as a first citizen function, providing the interface for the implementation for disabling the fork handles in the core library.

[1] https://github.com/grpc/grpc/blob/master/src/core/lib/iomgr/fork_posix.cc#L68
[2] https://github.com/grpc/grpc/pull/19960
[3] https://github.com/grpc/grpc/pull/19960/files#diff-0fe140df36d45de59f70c52194cc8d6aR70
[4] https://github.com/grpc/grpc/blob/master/src/core/lib/gprpp/fork.h#L88

**Comment by pfreixes** [comment] 2019-09-02 15:08
@guantaol WDYT?

**Comment by guantaol** [comment] 2019-09-17 00:40
Since the issue is related to Python asyncio, assign it to Lidi for triage.

**Comment by lidizheng** [comment] 2019-09-17 18:05
@pfreixes To me, the first solution is more neat. The core should handle the error correctly, instead of just warning users.

**Comment by lidizheng** [comment] 2020-03-16 16:12
We still want this.

**Comment by markdroth** [comment] 2020-05-05 18:33
Since we're moving away from the iomgr APIs, this doesn't seem like something we should be putting effort into.

**Closed by markdroth** 2020-05-05 18:33 UTC
Labels: kind/enhancement, lang/core, priority/P2

**Comment by pfreixes** [comment] 2020-05-05 22:17
Yeps that can be closed, and anything related to the custom IOMGR
