### ISSUE TITLE
cloud_to_cloud:node:python_server:large_unary timeout

### ISSUE THREAD

**Issue by dgquintas** [grpc/grpc#13129] opened 2017-10-24 17:23 UTC
https://sponge.corp.google.com/target?id=03fbaf7f-f1d7-4e71-acf4-5595107a947c&target=grpc/ubuntu/pull_request/grpc_interop_tocloud&searchFor=&show=ALL&sortBy=STATUS

```
2017-10-20 16:24:01,728 START: cloud_to_cloud:node:python_server:large_unary
...
2017-10-20 16:27:10,738 TIMEOUT: cloud_to_cloud:node:python_server:large_unary [pid=19052, time=189.0sec]
```

**Comment by murgatroid99** [comment] 2017-10-25 21:16
This is probably related to #13130. This failure has also been seen with a Node client and a C++ server: https://sponge.corp.google.com/target?id=96b2d46f-48bb-4125-a231-2cec4e5a69c3&target=grpc/ubuntu/pull_request/grpc_interop_tocloud&searchFor=&show=ALL&sortBy=STATUS

**Comment by jtattermusch** [comment] 2017-11-06 15:10
Dupe of https://github.com/grpc/grpc/issues/13253.

**Closed by jtattermusch** 2017-11-06 15:10 UTC
Labels: infra/BUILDPONY
