### ISSUE TITLE
Protobuf Submodule Reference Broken

### ISSUE THREAD

**Issue by jedimasterjonny** [grpc/grpc#26809] opened 2021-07-28 15:19 UTC
### What version of gRPC and what language are you using?
`1.38.0`

### What operating system (Linux, Windows,...) and version?
N/A

### What runtime / compiler are you using (e.g. python version or version of gcc)
N/A

### What did you do?
Cloned the GRPC repo recursively using

```
 git clone --recurse-submodules --shallow-submodules https://github.com/grpc/grpc.git
```

### What did you expect to see?
A successful checkout

### What did you see instead?
```
...
fatal: remote error: upload-pack: not our ref 436bd7880e458532901c58f4d9d1ea23fa7edd52
fatal: the remote end hung up unexpectedly
Fetched in submodule path 'third_party/protobuf', but it did not contain 436bd7880e458532901c58f4d9d1ea23fa7edd52. Direct fetching of that commit failed.
```

Also, navigating to that submodule (`third_party/protobuf @ 436bd78`) from the GitHub web UI returns a 404 confirming the dead link.

**Comment by typetetris** [comment] 2021-07-28 15:21
Also hitting this problem, seems like [protobuf](https://github.com/google/protobuf.git) is now something else?

**Comment by jedimasterjonny** [comment] 2021-07-28 15:28
Looks like this is the new home of protobuf: https://github.com/protocolbuffers/protobuf

**Comment by typetetris** [comment] 2021-07-28 15:30
That is really unfortunate.

If this repos stays renamed, building an old version of grpc will be not pleasant ...

**Comment by rnwhitehead** [comment] 2021-07-28 15:51
> That is really unfortunate.
> 
> If this repos stays renamed, building an old version of grpc will be not pleasant ...

I'm using the zip file now rather than git to fetch the source - and it's actually much faster to fetch it.

**Comment by typetetris** [comment] 2021-07-28 15:59
> > That is really unfortunate.
> > If this repos stays renamed, building an old version of grpc will be not pleasant ...
> 
> I'm using the zip file now rather than git to fetch the source - and it's actually much faster to fetch it.

Just downloaded [grpc-1.33.2.zip](https://codeload.github.com/grpc/grpc/zip/refs/tags/v1.33.2) and it didn't contain files in `third_party/protobuf`. Am I missing something?

**Comment by rnwhitehead** [comment] 2021-07-28 16:07
Sorry, I spoke too soon. I couldn't get the canned sources to build, either.
Richard

________________________________

**Comment by drfloob** [comment] 2021-07-28 16:40
Duplicate of https://github.com/grpc/grpc/pull/26811, which tracks the fix as well. A protobuf repository change broke many open source tools.

**Closed by drfloob** 2021-07-28 16:40 UTC
Labels: kind/bug, priority/P2

**Comment by cjcobb23** [comment] 2021-07-28 17:20
https://github.com/ripple/rippled is also affected by this. Why is the issue closed? Is the fix merged?

**Comment by drfloob** [comment] 2021-07-28 19:15
This is closed as a duplicate. There were a few reports discussing the gRPC-specific problem, and it's easier to keep track of one (see #26811 ). The protobuf team is working on solving the root cause.
