### ISSUE TITLE
No file grpc_python_plugin.exe in Release 0.12.0

### ISSUE THREAD

**Issue by wanghaiqing2015** [grpc/grpc#4938] opened 2016-01-28 10:54 UTC
RT.

**Comment by soltanmm** [comment] 2016-01-28 16:02
So, two problems:
1) Windows support isn't quite here yet for Python; it should land next version.
2) The gRPC `protoc` plugin and `protoc` aren't packaged in Python PyPI. If you've installed the core and plugin packages and cannot run them some other way, then we need information on how you've acquired them. It seems that you've provided that in #4937, so I'm closing this as a duplicate of that bug for now. Feel free to reopen if that's not the case!

**Closed by soltanmm** 2016-01-28 16:02 UTC
