### ISSUE TITLE
qps drops in benchmark from 1.6.0 to 1.7.2

### ISSUE THREAD

**Issue by BusyJay** [grpc/grpc#13723] opened 2017-12-12 09:45 UTC
Hi, I run following command for version v1.6.0 and version 1.7.2:
```
$ python2.7 tools/run_tests/run_performance_tests.py -l c++ -r generic_async_streaming_ping_pong
```

The results show that qps drops from 33k to 22k on my machine. This can be reproduced reliably. Is it expected?

```
$ uname -a
Linux 4.14.3-300.fc27.x86_64 #1 SMP Mon Dec 4 17:18:27 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by overvenus** [comment] 2018-01-09 11:24
Because the default event engine changes from `epollsig` to `epoll1` in 1.7.x. https://github.com/grpc/grpc/commit/0fda880c752c827d82a05c645b129f75760ffa2a

Set the environment variable `GRPC_POLL_STRATEGY=epollsig` to specify the event engine.

**Comment by sreecha** [comment] 2018-05-15 23:31
Unable to reproduce this. Could you try with the latest release? (The polling engine has changed. We use `epollex` engine by default and fall back to `epoll1` if you have an older kernel)

**Comment by sreecha** [comment] 2018-06-06 17:28
I would also like to add that qps changes (increases or decreases) for individual benchmarks will vary for different polling engines. When rolling out a new polling engine, we look at the overall performance wins across all the benchmarks..

**Comment by sreecha** [comment] 2018-06-06 17:29
I am closing this issue. Please reopen the issue if you see significant regression with the latest polling engine enabled by default (i.e `epollex`).

**Closed by sreecha** 2018-06-06 17:29 UTC
Labels: area/performance, kind/customer issue, lang/core, priority/P2
