### ISSUE TITLE
make grpc_php_plugin error!!!

### ISSUE THREAD

**Issue by NVD-R** [grpc/grpc#15474] opened 2018-05-20 20:31 UTC
i try to run `$ make grpc_php_plugin` but the error of below is result:

> 

> make: Circular /home/navid/grpc/libs/opt/libares.a <- /home/navid/grpc/libs/opt/libaddress_sorting.a dependency dropped.
> [C]       Compiling third_party/cares/cares/ares_init.c
> third_party/cares/cares/ares_init.c: In function ‘ares_dup’:
> third_party/cares/cares/ares_init.c:301:17: error: argument to ‘sizeof’ in ‘strncpy’ call is the same expression as the source; did you mean to use the size of the destination? [-Werror=sizeof-pointer-memaccess]
>            sizeof(src->local_dev_name));
>                  ^
> third_party/cares/cares/ares_init.c: At top level:
> cc1: error: unrecognized command line option ‘-Wno-invalid-source-encoding’ [-Werror]
> cc1: all warnings being treated as errors
> make: *** [Makefile:2782: /home/navid/grpc/objs/opt/third_party/cares/cares/ares_init.o] Error 1

**Comment by nicolasnoble** [comment] 2018-05-20 22:09
What is your build environment ? Compiler name and version ? Operating system ?

**Comment by NVD-R** [comment] 2018-05-22 16:58
g++ (GCC) 8.1.1 20180502 (Red Hat 8.1.1-1)
4.16.7-300.fc28.x86_64 (fedora)
PHP 7.2.5 (cli) (built: Apr 24 2018 15:09:50) ( NTS )

**Comment by NVD-R** [comment] 2018-05-23 16:54
any body can help me?

**Comment by nicolasnoble** [comment] 2018-05-23 17:08
Duplicate of #15520.

**Comment by ncteisen** [comment] 2018-05-30 18:43
Closing as duplicate

**Closed by ncteisen** 2018-05-30 18:43 UTC
