### ISSUE TITLE
cannot make grpc_cli

### ISSUE THREAD

**Issue by perezd** [grpc/grpc#17781] opened 2019-01-21 23:23 UTC
### What version of gRPC and what language are you using?

Attempted with tag v1.18.0 
 
### What operating system (Linux, Windows, …) and version?
uname -a:
```
Linux computron 4.18.0-13-generic #14-Ubuntu SMP Wed Dec 5 09:04:24 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
 ```
### What runtime / compiler are you using (e.g. python version or version of gcc)
 gcc -v:
```
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/8/lto-wrapper
OFFLOAD_TARGET_NAMES=nvptx-none
OFFLOAD_TARGET_DEFAULT=1
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 8.2.0-7ubuntu1' --with-bugurl=file:///usr/share/doc/gcc-8/README.Bugs --enable-languages=c,ada,c++,go,brig,d,fortran,objc,obj-c++ --prefix=/usr --with-gcc-major-version-only --program-suffix=-8 --program-prefix=x86_64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-libmpx --enable-plugin --enable-default-pie --with-system-zlib --with-target-system-zlib --enable-objc-gc=auto --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-offload-targets=nvptx-none --without-cuda-driver --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 8.2.0 (Ubuntu 8.2.0-7ubuntu1) 
```

### What did you do?

git clone, submodule init, make -sj8 grpc_cli

### What did you expect to see?
 
/bins/opt/grpc_cli built
 
### What did you see instead?

This failure: 
```
[C]       Compiling third_party/cares/cares/ares_init.c
third_party/cares/cares/ares_init.c: In function ‘ares_dup’:
third_party/cares/cares/ares_init.c:301:17: error: argument to ‘sizeof’ in ‘strncpy’ call is the same expression as the source; did you mean to use the size of the destination? [-Werror=sizeof-pointer-memaccess]
           sizeof(src->local_dev_name));
                 ^
third_party/cares/cares/ares_init.c: At top level:
cc1: error: unrecognized command line option ‘-Wno-invalid-source-encoding’ [-Werror]
cc1: all warnings being treated as errors
make: *** [Makefile:2947: /home/perezd/src/grpc/objs/opt/third_party/cares/cares/ares_init.o] Error 1
```

**Comment by perezd** [comment] 2019-01-22 00:19
This seems related, maybe need a version bump? https://github.com/c-ares/c-ares/issues/210

**Comment by perezd** [comment] 2019-01-22 01:00
Current workaround:
``` 
make CFLAGS='-g -O2 -w' CXXFLAGS='-g -O2 -w' -sj8 grpc_cli
```

**Comment by yang-g** [comment] 2019-02-20 18:22
Thanks for the work-around. @apolcyn should we update cares to resolve this?

**Comment by yang-g** [comment] 2019-02-20 18:23
This is a duplicate of #18064

**Closed by yang-g** 2019-02-20 18:23 UTC
Labels: area/core, kind/bug, lang/core, priority/P2
