### ISSUE TITLE
[C# Grpc.Tools] Protoc tool detects MacOS Big Sur as Linux and fails 

### ISSUE THREAD

**Issue by tmarkovski** [grpc/grpc#24760] opened 2020-11-14 23:46 UTC
My project build worked just before upgrading to Big Sur. After upgrade, I started seeing the below error.

### What version of gRPC and what language are you using?
Grpc.Tools 2.33.1
C#

### What operating system (Linux, Windows,...) and version?
macOS Big Sur 11.0.1

### What runtime / compiler are you using (e.g. python version or version of gcc)
.NET SDK 3.1.401

### What did you do?
Add Protobuf files in .csproj using `<Protobuf>`

### What did you expect to see?
Build success

It appears the MsBuild tasks for Os detection return `linux` instead. I added this task in my csproj to debug the problem
```
  <Target Name="Print_Protobuf_ToolsOs" AfterTargets="Protobuf_ResolvePlatform">
    <Message Text="Protobuf_ToolsOs = $(Protobuf_ToolsOs)" />
  </Target>
```

Output
```
  Protobuf_ToolsOs = linux
_Protobuf_CoreCompile:
```

Points to output from https://github.com/grpc/grpc/blob/014a2a0d54849fff795efbcb96b18416cbd7e189/src/csharp/Grpc.Tools/ProtoToolsPlatform.cs#L34

### What did you see instead?
"/Users/geddoff/Git/streetcred-devops/didcomm-extension-grpc/dotnet/Library/DIDComm.Messaging.gRPC/DIDComm.Messaging.gRPC.csproj" (Build target) (1:4) ->
(_Protobuf_CoreCompile target) -> 
  **/Users/geddoff/.nuget/packages/grpc.tools/2.33.1/build/_protobuf/Google.Protobuf.Tools.targets(280,5): error MSB6006: "/Users/geddoff/.nuget/packages/grpc.tools/2.33.1/tools/linux_x64/protoc" exited with code 255.** [/Users/geddoff/Git/streetcred-devops/didcomm-extension-grpc/dotnet/Library/DIDComm.Messaging.gRPC/DIDComm.Messaging.gRPC.csproj]

### Non-standard MsBuild SDK used in project file

I use MSBuild.Sdk.Extras in the Project file for building Xamarin targets

```
<Project Sdk="MSBuild.Sdk.Extras/2.1.2">

  <PropertyGroup>
    <TargetFrameworks>netstandard2.1;xamarinios10</TargetFrameworks>
  </PropertyGroup>
```

[Link to repo with code](https://github.com/trinsic-id/didcomm-extension-grpc/blob/main/dotnet/Library/DIDComm.Messaging.gRPC/DIDComm.Messaging.gRPC.csproj)

**Comment by wbuck** [comment] 2020-11-15 03:55
I'm currently suffering from the same issue (after upgrading to Big Sur).

>Target GenerateTargetFrameworkMonikerAttribute:
  Skipping target "GenerateTargetFrameworkMonikerAttribute" because all output files are up-to-date with respect to the input files.
Target _Protobuf_CoreCompile:
    /Users/wbuckley/.nuget/packages/grpc.tools/2.33.1/tools/linux_x64/protoc --csharp_out=obj/Debug/net5.0/Proto --plugin=protoc-gen-grpc=/Users/wbuckley/.nuget/packages/grpc.tools/2.33.1/tools/linux_x64/grpc_csharp_plugin --grpc_out=obj/Debug/net5.0/Proto --grpc_opt=no_server --proto_path=/Users/wbuckley/.nuget/packages/grpc.tools/2.33.1/build/native/include --proto_path=. --dependency_out=obj/Debug/net5.0/24131f3e1ac0aa6b_inspection.protodep --error_format=msvs Proto/inspection.proto
    /Users/wbuckley/.nuget/packages/grpc.tools/2.33.1/build/_protobuf/Google.Protobuf.Tools.targets(280,5): error MSB6006: "/Users/wbuckley/.nuget/packages/grpc.tools/2.33.1/tools/linux_x64/protoc" exited with code 255.
Done building target "_Protobuf_CoreCompile" in project "WebCommon.csproj" -- FAILED.

**Comment by tmarkovski** [comment] 2020-11-15 14:13
Interesting. I have further info, based on your comment. Using this configuration in the CSPROJ

```
<Project Sdk="MSBuild.Sdk.Extras/2.1.2">
  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
```

I am able to build this using `dotnet build`, but not using `msbuild`. This doesn't solve my problem, as I have to multi target different frameworks, so I cannot use `dotnet build`, but this does explain why building using VS fails, which uses MsBuild.

**Comment by wbuck** [comment] 2020-11-15 14:25
@tmarkovski Unfortunately it also looks like OmniSharp uses MSBuild which is causing my build to fail in VSCode which causes a ton of red squiggles and broken intellisense.

**Comment by tmarkovski** [comment] 2020-11-15 14:42
Yikes. This seems either a problem with MsBuild or MsBuild.Extras package.

In the meantime, I was able to get past this problem by setting environment variable `PROTOBUF_TOOLS_OS = macosx`.
I got hinted about this [here](https://github.com/grpc/grpc/blob/014a2a0d54849fff795efbcb96b18416cbd7e189/src/csharp/Grpc.Tools/build/_protobuf/Google.Protobuf.Tools.targets#L86) while trying to figure out why the target `_ProtoCompile` fails.

**Comment by briosheje** [comment] 2020-11-15 14:46
Same problem with .NET SDK 5.0 with visual studio on MacOS big sur: even a new gRPC service project does not compile and does not automatically add needed packages as well (not that it's related to this repository, though).

**Comment by wbuck** [comment] 2020-11-15 14:47
@tmarkovski Oh, I like your solution better than mine (I just copied and renamed the `macosx_x64` to `linux_x64`)

**Comment by tmarkovski** [comment] 2020-11-15 14:56
Until a fix is out, you can also just drop this in your project file under `PropertyGroup`.

```
<Protobuf_ToolsOs Condition="'$([MSBuild]::IsOsPlatform(OSX))'">macosx</Protobuf_ToolsOs>
```

**Comment by briosheje** [comment] 2020-11-15 14:59
> Until a fix is out, you can also just drop this in your project file under `PropertyGroup`. This way you won't need to set environment variable, and it will work when compiling the project under different platforms.
> 
> ```
> <Protobuf_ToolsOs Condition="'$([MSBuild]::IsOsPlatform(OSX))'">macosx</Protobuf_ToolsOs>
> ```

Thanks, works like a charm :)

**Comment by tmarkovski** [comment] 2020-11-15 16:19
Related and a possible duplicate of https://github.com/grpc/grpc/issues/24529

**Comment by imarinmed** [comment] 2020-11-16 14:41
Thank you for the mention to my ticket thread, @tmarkovski! It really seems MacOS developers updated Clang and this provoked some non-compliance with `zlib` parse when building `grpc` in a current Catalina, Big Sur (`>10.15`, `11.0`, I'd say) environment.

Your solution may even indeed to help me solve my own problem in a more elegant way: currently I build my project in a Linux environment to avoid having to build it over Mac, but it gives my collaborators quite the headache to parallel like this too often.

**Comment by jtattermusch** [comment] 2020-11-16 15:15
Closing as duplicate of https://github.com/grpc/grpc/issues/24529

**Closed by jtattermusch** 2020-11-16 15:15 UTC
Labels: kind/bug, lang/C#, priority/P1
