### ISSUE TITLE
Ruby Gem 1.8.6 broken on Ruby 2.1 (OS X)

### ISSUE THREAD

**Issue by blowmage** [grpc/grpc#14277] opened 2018-02-01 20:35 UTC
### What version of gRPC and what language are you using?

Ruby grpc gem 1.8.6
 
### What operating system (Linux, Windows, …) and version?
 
OS X
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
 
Ruby 2.1
 
### What did you do?

Requiring the gem on Ruby 2.1 produces the following error:

`LoadError: cannot load such file -- grpc/grpc_c`
 
The gem `grpc-1.8.6-universal-darwin.gem` is missing the precompiled file for Ruby 2.1.

Compare the `universal-darwin` gem:

```
$ tree grpc-1.8.6-universal-darwin/data/src/ruby/lib
├── grpc
│   ├── 2.0
│   │   └── grpc_c.bundle
│   ├── 2.2
│   │   └── grpc_c.bundle
│   ├── 2.3
│   │   └── grpc_c.bundle
│   ├── 2.4
│   │   └── grpc_c.bundle
│   ├── core
│   │   └── time_consts.rb
│   ├── errors.rb
│   ├── generic
│   │   ├── active_call.rb
│   │   ├── bidi_call.rb
│   │   ├── client_stub.rb
│   │   ├── interceptor_registry.rb
│   │   ├── interceptors.rb
│   │   ├── rpc_desc.rb
│   │   ├── rpc_server.rb
│   │   └── service.rb
│   ├── google_rpc_status_utils.rb
│   ├── grpc.rb
│   ├── logconfig.rb
│   ├── notifier.rb
│   └── version.rb
└── grpc.rb

7 directories, 20 files
```

To the `x86_64-linux` gem:

```
$ tree grpc-1.8.6-x86_64-linux/data/src/ruby/lib
├── grpc
│   ├── 2.0
│   │   └── grpc_c.so
│   ├── 2.1
│   │   └── grpc_c.so
│   ├── 2.2
│   │   └── grpc_c.so
│   ├── 2.3
│   │   └── grpc_c.so
│   ├── 2.4
│   │   └── grpc_c.so
│   ├── core
│   │   └── time_consts.rb
│   ├── errors.rb
│   ├── generic
│   │   ├── active_call.rb
│   │   ├── bidi_call.rb
│   │   ├── client_stub.rb
│   │   ├── interceptor_registry.rb
│   │   ├── interceptors.rb
│   │   ├── rpc_desc.rb
│   │   ├── rpc_server.rb
│   │   └── service.rb
│   ├── google_rpc_status_utils.rb
│   ├── grpc.rb
│   ├── grpc_c.so
│   ├── logconfig.rb
│   ├── notifier.rb
│   └── version.rb
└── grpc.rb

8 directories, 22 files
```

The other platform gems have a precompiled file for all supported language versions, and don't appear to be affected. This same issue happened recently in google/protobuf#4235 and is likely related.

**Comment by blowmage** [comment] 2018-02-01 20:35
cc @geigerj

**Comment by geigerj** [comment] 2018-02-01 20:38
@apolcyn Could you take a look?

**Comment by geigerj** [comment] 2018-02-01 20:45
cc @jbolinger

**Comment by apolcyn** [comment] 2018-02-01 21:04
this is caused by https://github.com/grpc/grpc/pull/13930/files#diff-aef7b9afe0f7f86545849c31559d1f1bL50, which updates master and 1.9.x to build against ruby 2.1.6 instead of ruby 2.1.5 (which was a bad idea, since it breaks the mac package builds on old branches which share the same build environment, with ruby 2.16 instead of ruby 2.1.5 available).

WIP on reverting that change and updating mac package build environment

**Comment by apolcyn** [comment] 2018-02-02 02:43
1.8.7 was just pushed, which has the fix for this

**Closed by apolcyn** 2018-02-02 02:43 UTC

**Comment by blowmage** [comment] 2018-02-02 17:27
Confirming that we have a successful build on OS X with Ruby 2.1 using grpc gem version 1.8.7. Thanks all!
