### ISSUE TITLE
Grpc.Core.Internal.PlatformApis throws FileNotFoundException

### ISSUE THREAD

**Issue by giammin** [grpc/grpc#20251] opened 2019-09-13 09:52 UTC
### What version of gRPC and what language are you using?

C# Grpc.Core 1.22.0

### What operating system (Linux, Windows,...) and version?

Windows 10

### What runtime / compiler are you using (e.g. python version or version of gcc)

netstandard2.0

netcoreapp2.2

### What did you do?

just using google cloud firestore c# library

### Bug

3 exception every time i start my app:

FileNotFoundExeption for Xamarin.IOs, UnityEngine and Mono

the part in Grpc.Core.Internal.PlatformApis which identify the platform is wrong and inefficent.

it just try to get the type: 
`var unityApplicationClass = Type.GetType(UnityEngineApplicationClassName);`

without checking if the assembly is present and this throw a FileNotFoundException

this will always throw 3 exception in every platform

**Comment by jtattermusch** [comment] 2019-11-14 10:32
Do you have any suggestions for how to improve the Unity platform check?

Btw, according to the documentation https://docs.microsoft.com/en-us/dotnet/api/system.type.gettype?view=netframework-4.8#System_Type_GetType_System_String_,

the `Type.GetType(UnityEngineApplicationClassName); ` doesn't throw when the type is not found - it only returns a null (which is consistent with the behavior I'm seeing = no exception). Can you provide better instructions for how to reproduce the FileNotFoundException?

**Comment by sreejit-a** [comment] 2020-05-01 00:32
We were facing issue too for one of our application - the exact stack trace was 

The type initializer for 'Grpc.Core.Internal.PlatformApis' threw an exception. ---> 
System.TypeInitializationException: The type initializer for 'Grpc.Core.Internal.PlatformApis' threw an exception. ---> 
System.IO.FileLoadException: Could not load file or assembly 'UnityEngine' or one of its dependencies. An argument was out of its legal range. (Exception from HRESULT: 0x80131502) ---> System.ArgumentOutOfRangeException: Length cannot be less than zero. Parameter name: length at System.String.Substring(Int32 startIndex, Int32 length) 
at Common.OnResolveAssembly(Object sender, ResolveEventArgs args) 
at System.AppDomain.OnAssemblyResolveEvent(RuntimeAssembly assembly, String assemblyFullName) 
 at System.RuntimeTypeHandle.GetTypeByName(String name, Boolean throwOnError, Boolean ignoreCase, Boolean reflectionOnly, StackCrawlMarkHandle stackMark, IntPtr pPrivHostBinder, Boolean loadTypeFromPartialName, ObjectHandleOnStack type) 
 at System.RuntimeTypeHandle.GetTypeByName(String name, Boolean throwOnError, Boolean ignoreCase, Boolean reflectionOnly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean loadTypeFromPartialName) 
 at System.RuntimeType.GetType(String typeName, Boolean throwOnError, Boolean ignoreCase, Boolean reflectionOnly, StackCrawlMark& stackMark) at System.Type.GetType(String typeName) 
 at Grpc.Core.Internal.PlatformApis..cctor() 

Found out that our app had a delegate registered on 
`AppDomain.CurrentDomain.AssemblyResolve += CurrentDomain_AssemblyResolve`. 

So, when PlatformApis invoke

`Type.GetType(UnityEngineApplicationClassName);`

The delegate fires as this type could not be resolved and this delegate attempted to load from another location and the assembly was missing there too, and this exception was thrown.

Looking at stack trace from @edvher I see the same stack there as well -

at ManagedLoader.AssemblyResolveHandler(Object sender, ResolveEventArgs args)
at System.AppDomain.OnAssemblyResolveEvent(RuntimeAssembly assembly, String

**Comment by edvher** [comment] 2020-05-01 10:57
> 
> 
> We were facing this issue too for one of our application - the exact stack trace was
> 
> The type initializer for 'Grpc.Core.Internal.PlatformApis' threw an exception. --->
> System.TypeInitializationException: The type initializer for 'Grpc.Core.Internal.PlatformApis' threw an exception. --->
> System.IO.FileLoadException: Could not load file or assembly 'UnityEngine' or one of its dependencies. An argument was out of its legal range. (Exception from HRESULT: 0x80131502) ---> System.ArgumentOutOfRangeException: Length cannot be less than zero. Parameter name: length at System.String.Substring(Int32 startIndex, Int32 length)
> at Common.OnResolveAssembly(Object sender, ResolveEventArgs args)
> at System.AppDomain.OnAssemblyResolveEvent(RuntimeAssembly assembly, String assemblyFullName)
> at System.RuntimeTypeHandle.GetTypeByName(String name, Boolean throwOnError, Boolean ignoreCase, Boolean reflectionOnly, StackCrawlMarkHandle stackMark, IntPtr pPrivHostBinder, Boolean loadTypeFromPartialName, ObjectHandleOnStack type)
> at System.RuntimeTypeHandle.GetTypeByName(String name, Boolean throwOnError, Boolean ignoreCase, Boolean reflectionOnly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean loadTypeFromPartialName)
> at System.RuntimeType.GetType(String typeName, Boolean throwOnError, Boolean ignoreCase, Boolean reflectionOnly, StackCrawlMark& stackMark) at System.Type.GetType(String typeName)
> at Grpc.Core.Internal.PlatformApis..cctor()
> 
> Found out that our app had a delegate registered on
> `AppDomain.CurrentDomain.AssemblyResolve += CurrentDomain_AssemblyResolve`.
> 
> So, when PlatformApis invoke
> 
> `Type.GetType(UnityEngineApplicationClassName);`
> 
> The delegate fires as this type could not be resolved and this delegate attempted to load from another location and the assembly was missing there too, and this exception was thrown.
> 
> Looking at stack trace from @edvher I see the same stack there as well -
> 
> at ManagedLoader.AssemblyResolveHandler(Object sender, ResolveEventArgs args)
> at System.AppDomain.OnAssemblyResolveEvent(RuntimeAssembly assembly, String

hi sreejit,
how did you solve the problem?

**Comment by edvher** [comment] 2020-05-01 11:10
@sreejit-a 

> 
> 
> We were facing this issue too for one of our application - the exact stack trace was
> 
> The type initializer for 'Grpc.Core.Internal.PlatformApis' threw an exception. --->
> System.TypeInitializationException: The type initializer for 'Grpc.Core.Internal.PlatformApis' threw an exception. --->
> System.IO.FileLoadException: Could not load file or assembly 'UnityEngine' or one of its dependencies. An argument was out of its legal range. (Exception from HRESULT: 0x80131502) ---> System.ArgumentOutOfRangeException: Length cannot be less than zero. Parameter name: length at System.String.Substring(Int32 startIndex, Int32 length)
> at Common.OnResolveAssembly(Object sender, ResolveEventArgs args)
> at System.AppDomain.OnAssemblyResolveEvent(RuntimeAssembly assembly, String assemblyFullName)
> at System.RuntimeTypeHandle.GetTypeByName(String name, Boolean throwOnError, Boolean ignoreCase, Boolean reflectionOnly, StackCrawlMarkHandle stackMark, IntPtr pPrivHostBinder, Boolean loadTypeFromPartialName, ObjectHandleOnStack type)
> at System.RuntimeTypeHandle.GetTypeByName(String name, Boolean throwOnError, Boolean ignoreCase, Boolean reflectionOnly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean loadTypeFromPartialName)
> at System.RuntimeType.GetType(String typeName, Boolean throwOnError, Boolean ignoreCase, Boolean reflectionOnly, StackCrawlMark& stackMark) at System.Type.GetType(String typeName)
> at Grpc.Core.Internal.PlatformApis..cctor()
> 
> Found out that our app had a delegate registered on
> `AppDomain.CurrentDomain.AssemblyResolve += CurrentDomain_AssemblyResolve`.
> 
> So, when PlatformApis invoke
> 
> `Type.GetType(UnityEngineApplicationClassName);`
> 
> The delegate fires as this type could not be resolved and this delegate attempted to load from another location and the assembly was missing there too, and this exception was thrown.
> 
> Looking at stack trace from @edvher I see the same stack there as well -
> 
> at ManagedLoader.AssemblyResolveHandler(Object sender, ResolveEventArgs args)
> at System.AppDomain.OnAssemblyResolveEvent(RuntimeAssembly assembly, String

hi @sreejit-a 
how did you solve the problem?

**Comment by sreejit-a** [comment] 2020-05-01 15:53
> @sreejit-a
> 
> > We were facing this issue too for one of our application - the exact stack trace was
> > The type initializer for 'Grpc.Core.Internal.PlatformApis' threw an exception. --->
> > System.TypeInitializationException: The type initializer for 'Grpc.Core.Internal.PlatformApis' threw an exception. --->
> > System.IO.FileLoadException: Could not load file or assembly 'UnityEngine' or one of its dependencies. An argument was out of its legal range. (Exception from HRESULT: 0x80131502) ---> System.ArgumentOutOfRangeException: Length cannot be less than zero. Parameter name: length at System.String.Substring(Int32 startIndex, Int32 length)
> > at Common.OnResolveAssembly(Object sender, ResolveEventArgs args)
> > at System.AppDomain.OnAssemblyResolveEvent(RuntimeAssembly assembly, String assemblyFullName)
> > at System.RuntimeTypeHandle.GetTypeByName(String name, Boolean throwOnError, Boolean ignoreCase, Boolean reflectionOnly, StackCrawlMarkHandle stackMark, IntPtr pPrivHostBinder, Boolean loadTypeFromPartialName, ObjectHandleOnStack type)
> > at System.RuntimeTypeHandle.GetTypeByName(String name, Boolean throwOnError, Boolean ignoreCase, Boolean reflectionOnly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean loadTypeFromPartialName)
> > at System.RuntimeType.GetType(String typeName, Boolean throwOnError, Boolean ignoreCase, Boolean reflectionOnly, StackCrawlMark& stackMark) at System.Type.GetType(String typeName)
> > at Grpc.Core.Internal.PlatformApis..cctor()
> > Found out that our app had a delegate registered on
> > `AppDomain.CurrentDomain.AssemblyResolve += CurrentDomain_AssemblyResolve`.
> > So, when PlatformApis invoke
> > `Type.GetType(UnityEngineApplicationClassName);`
> > The delegate fires as this type could not be resolved and this delegate attempted to load from another location and the assembly was missing there too, and this exception was thrown.
> > Looking at stack trace from @edvher I see the same stack there as well -
> > at ManagedLoader.AssemblyResolveHandler(Object sender, ResolveEventArgs args)
> > at System.AppDomain.OnAssemblyResolveEvent(RuntimeAssembly assembly, String
> 
> hi @sreejit-a
> how did you solve the problem?

We fixed by changing the assembly resolve delegate to not throw an exception and return a null type.

**Comment by jtattermusch** [comment] 2020-05-07 11:37
Ok so it looks like that the root cause for the problem was:
1. a custom assembly resolver was registered in the affected application
2. when grpc code checks whether or not it's running on unity, it does `var unityApplicationClass = Type.GetType(UnityEngineApplicationClassName);`, which with combination with the custom assembly resolver has thrown an exception.

Looks like this is not really a problem in gRPC code, but in the custom assembly resolver you used. Closing.

**Closed by jtattermusch** 2020-05-07 11:37 UTC
Labels: kind/bug, lang/C#, priority/P2
