### ISSUE TITLE
Rust language port.

### ISSUE THREAD

**Issue by kkimdev** [grpc/grpc#9316] opened 2017-01-11 19:03 UTC
Rust is very close to C++ in terms of machine abstraction and has a straightforward C ffi, so shouldn't be too hard to support Rust.  What's gRPC team's stance on this?  Would you take Rust port contribution?

**Comment by tbillington** [comment] 2017-01-13 05:34
https://github.com/stepancheg/grpc-rust already works (for the most part).

**Comment by kkimdev** [comment] 2017-01-13 06:22
Yes so I was using that, but to my understanding it barely implements basic stuff.  For example there is no metadata support.  And since we don't have much resource to maintain it, it will be more beneficial to rely on gRPC core lib so that we can get all the updates for free.

**Comment by ctiller** [comment] 2017-01-18 16:43
If someone wanted to step up and raise a rust implementation to our quality
bar (the bulk of the work will be in getting testing integrated, and
interop test suites implemented), I suspect we'd gladly pull the wrapper
into the main repository and assume maintenance responsibility.

I suspect it'll take at least a couple of quarters of full time work for
someone to get to a place where that integration can truly be called
complete.

**Comment by kkimdev** [comment] 2017-01-18 18:50
Thanks.  Btw, I tried Rust bind-generator https://github.com/servo/rust-bindgen .  It worked well with `grpc.h`, but it had a few issues with `grpc++.h`.

```
bindgen /usr/local/include/grpc++/grpc++.h --whitelist-type="grpc::.*" -- -x c++ -std=c++1y
```

1. Dealing with `decltype`, this is a known issue https://github.com/servo/rust-bindgen/issues/381
2. A few classes weren't generated that prevents compiling, e.g. `std::basic_string`, I don't know why yet.

@emilio FYI

**Comment by emilio** [comment] 2017-01-18 23:53
Yeah, C++ usually requires a bit more effort than throwing bindgen at it, because of the complexity of the language and some corners that libclang doesn't handle gracefully.

I'm happy to try reproducing this when I find the time to hack on bindgen, will file an upstream issue so I don't forget about it.

**Comment by tbillington** [comment] 2017-01-19 00:15
Tagging @stepancheg to make sure they're aware of this issue.

**Comment by kkimdev** [comment] 2017-01-19 00:47
Note: `perl -pi -e 'BEGIN{undef $/;} s/^pub(\n |.)*?decltype.*?;$//mg' generated.rs` to filter out leaked `decltype`.

**Comment by kkimdev** [comment] 2017-01-21 20:29
@ctiller One question:  We can use `grpc.h` or `grpc++.h` interface (assuming we manage to get our bind-generator work with `grpc++.h`).  Do you have any insight on which route would be better?  If using `grpc++.h` can substantially reduce the work and ongoing maintanace work, I think we should consider that instead of using `grpc.h`.

**Comment by tbillington** [comment] 2017-02-21 02:26
What about making c bindings from grpc-go and using that from rust, or is that a bit crazy :) ?

**Comment by ctiller** [comment] 2017-02-21 03:02
I'd be awestruck seeing it, but I suspect I could also find more productive
uses of my own time ;)

**Comment by tbillington** [comment] 2017-02-21 03:10
@ctiller I think it's not totally crazy. It gives stable c bindings, which should be much easier to run bindgen over instead of c++. You wouldn't even notice that it's go instead of c from the rust side.

**Comment by aajtodd** [comment] 2017-11-10 15:59
There is also this implementation which wraps grpc core

https://github.com/pingcap/grpc-rs

**Comment by aajtodd** [comment] 2018-02-08 14:27
Found what appears to be another work in progress. 

https://github.com/tower-rs/tower-grpc/

I would assume the pingcap version, which wraps grpc core, would be the easiest to officially maintain but I haven't weighed the pros and cons of each library.

**Comment by ChrisCates** [comment] 2018-06-26 00:11
Hey guys.
I can start working on it.

I can have it on my github... 
And you guys can give reviews on it until it's good for alpha testing before it can be official?

**Comment by GitStonic** [comment] 2018-11-02 16:20
Question any gRPC lib for rust that supports load balancing? If so can one of you guys link it to me pweas

**Comment by JMurph2015** [comment] 2018-12-16 22:03
Any progress on getting an official port?

**Comment by ChrisCates** [comment] 2018-12-16 23:09
@JMurph2015, didn't really hear anything from the Google team... I'm open to working on it, as a lot of it is just trivial parsing of `.proto` files to interact with via TCP/HTTP. However, going back and forth with the Google team to ensure everything is Google compliant and not getting paid for it doesn't give me an incentive to work on it... If there was some sort of reward bounty for completing this project, I can move it up my priority queue.

@GitStonic, if you are looking to do load balancing. You should be deploying multiple gRPC nodes via something like Kuburnetes and then creating upstreams via NGINX or your load balancer of choice.

**Comment by vankofalcon** [comment] 2019-03-12 13:30
I'll definitely love to see Rust in the supported languages!

**Comment by mimoo** [comment] 2019-08-19 23:59
any updates from Google? Or what are the main Rust libraries at the moment?

**Comment by ChrisCates** [comment] 2019-08-20 00:09
@mimoo, no updates. Not sure how any one can start the project if no one is willing to do code review.

If you're looking for an alternative, check out: https://github.com/stepancheg/grpc-rust, but, it's missing a lot of features.

**Comment by overthetop** [comment] 2019-09-24 15:50
Actually I can not use any of the hot google cloud products like BigTable with Rust, simply because they rely on grpc for the transport. So this is actually a really big blocker for GCP to support Rust developers!

**Comment by pepsighan** [comment] 2019-11-14 08:40
[Tonic](https://github.com/hyperium/tonic) seems to be a promising port of grpc by hyperium. Good days ahead for rust.

**Comment by siddontang** [comment] 2019-11-14 08:45
Why not try https://github.com/tikv/grpc-rs?

It is a Rust wrapper and has been widely used in production.

**Comment by pepsighan** [comment] 2019-11-16 05:32
> Why not try https://github.com/tikv/grpc-rs?
Because it is a Rust wrapper. A pure rust solution is most likely to be safe.

**Comment by tbillington** [comment] 2019-11-16 06:09
Also metadata. Everyone always seems to forget metadata...

**Comment by liufuyang** [comment] 2020-02-25 06:59
Would it be possible to let google support on repos such as https://github.com/danburkert/prost and https://github.com/hyperium/tonic, and eventually provide cloud APIs for Rust? 🤔

**Comment by stanley-cheung** [comment] 2020-05-05 19:53
We acknowledge this to be a valid feature request but since no one has come forward to implement this, we are going to close it for now while maintaining the label/Help wanted to indicate that this can be picked up as future work.

**Closed by stanley-cheung** 2020-05-05 19:53 UTC
Labels: kind/enhancement, lang/other, priority/P2

**Comment by arjunyel** [comment] 2020-07-14 13:31
@stanley-cheung the owner of Tonic has said they're willing to upstream their gRPC implementation but they need some guidance https://github.com/hyperium/tonic/issues/149

Could this be reopened and is it possible to assist @LucioFranco with getting this merged into the main repo?

Thanks for everyone's help and time!

**Comment by kaushalyap** [comment] 2020-08-09 06:38
@stanley-cheung Please reopen this issue as @arjunyel mentioned

**Comment by liufuyang** [comment] 2020-11-26 12:25
Maybe we should ask [Amazon](https://aws.amazon.com/blogs/opensource/why-aws-loves-rust-and-how-wed-like-to-help/) for some help on this? Never really know why google seems not paying much attention to the Rust community.

**Comment by allanger** [comment] 2021-11-06 15:34
Any news on this?

**Comment by LucioFranco** [comment] 2021-11-08 16:46
If there is interest, I think tonic could be upstreamed. That said, tonic is not based on the regular grpc c stack and differentiates a bit from the more traditional gRPC implementations. I am happy to coordinate/chat with grpc maintainers/owners about this.

**Comment by JMurph2015** [comment] 2021-12-28 17:23
@liufuyang

There are some other internal blockers about how Rust is used in general at Google as far as I understand.  So until that is sorted, committing to a particular implementation of gRPC in Rust is complicated because when it is upstreamed it becomes the gRPC project's responsibility.  A toy example is that the Google-standard linting for Rust might not be finalized, so while they would want something that passed lint, they wouldn't know what that even looks like yet.

**Comment by reji-zero** [comment] 2023-01-25 09:35
Im curious, are there any updates on this??

**Comment by saman3d** [comment] 2024-06-16 08:08
seems like gRPC team started to work on a native rust implementation extending [tonic](https://github.com/hyperium/tonic) library.
[gRPC team announcement](https://groups.google.com/g/grpc-io/c/ExbWWLaGHjI/m/TJssglLiBgAJ)
