### ISSUE TITLE
lnk2019 error

### ISSUE THREAD

**Issue by anatoliy266** [grpc/grpc#15058] opened 2018-04-13 13:41 UTC
What version of gRPC and what language are you using?
clean master branch/ c++

What operating system (Linux, Windows, …) and version?
Windows 10

What runtime / compiler are you using (e.g. python version or version of gcc)
Qt creator 4.6.0 + Visual c++ compiler 15.0 (x86)

What did you do?
Try to build console app with async grpc server using helloworld example.

What did you expect to see?
succesful build app
 
### Anything else we should know about your project / environment?

I linking all of libs from grpc build, except for those that the compiler obviously swore(-lssl_decrepit
-ldflags_static
-lrc4_extra 
-lcrypto_base
-lgrpc++_unsecure 
-lgrpc_unsecure )

this helped fix about 100 linking errors, and now there are only 2 of them:

main.obj:-1: ошибка: LNK2019: unauthorized external character reference "public: __thiscall grpc::ServerBuilder::~ServerBuilder(void)" (??1ServerBuilder@grpc@@QAE@XZ) in function __unwindfunclet$?Run@ServerImpl@@QAEXXZ$1

and 

main.obj:-1: ошибка: LNK2019: unauthorized external character reference "public: class std::unique_ptr<class grpc::Server,struct std::default_delete<class grpc::Server> > __thiscall grpc::ServerBuilder::BuildAndStart(void)" (?BuildAndStart@ServerBuilder@grpc@@QAE?AV?$unique_ptr@VServer@grpc@@U?$default_delete@VServer@grpc@@@std@@@std@@XZ) in function "public: void __thiscall ServerImpl::Run(void)" (?Run@ServerImpl@@QAEXXZ)

**Comment by TCDigi** [comment] 2018-05-04 15:04
Hello,

Same problem for me with Visual c++ compiler 15.0 (x64) and gRPC 1.11.0. It works fine in 1.10.0 but impossible to link against the 1.11.0. I tried all the generated lib.

Erreur	LNK2019	symbole externe non résolu "public: __cdecl grpc::ServerBuilder::~ServerBuilder(void)" (??1ServerBuilder@grpc@@QEAA@XZ) référencé dans la fonction "public: __cdecl sparte::GrpcServer::GrpcServer(class std::shared_ptr<class sparte::ConfigManager> const &,class std::shared_ptr<class sparte::VbsUnitaryFeaturesScheduler> const &,class std::shared_ptr<class sparte::VbsPermanentFeaturesManager> const &)" (??0GrpcServer@sparte@@QEAA@AEBV?$shared_ptr@VConfigManager@sparte@@@std@@AEBV?$shared_ptr@VVbsUnitaryFeaturesScheduler@sparte@@@3@AEBV?$shared_ptr@VVbsPermanentFeaturesManager@sparte@@@3@@Z)	Vbs3Plugin	C:\Travail\SPARTE\Dev\Heroes\trunk\Externals\Vbs3Plugin\build\vs2015\GrpcServer.obj	1	

Erreur	LNK2019	symbole externe non résolu "public: class std::unique_ptr<class grpc::Server,struct std::default_delete<class grpc::Server> > __cdecl grpc::ServerBuilder::BuildAndStart(void)" (?BuildAndStart@ServerBuilder@grpc@@QEAA?AV?$unique_ptr@VServer@grpc@@U?$default_delete@VServer@grpc@@@std@@@std@@XZ) référencé dans la fonction "public: __cdecl sparte::GrpcServer::GrpcServer(class std::shared_ptr<class sparte::ConfigManager> const &,class std::shared_ptr<class sparte::VbsUnitaryFeaturesScheduler> const &,class std::shared_ptr<class sparte::VbsPermanentFeaturesManager> const &)" (??0GrpcServer@sparte@@QEAA@AEBV?$shared_ptr@VConfigManager@sparte@@@std@@AEBV?$shared_ptr@VVbsUnitaryFeaturesScheduler@sparte@@@3@AEBV?$shared_ptr@VVbsPermanentFeaturesManager@sparte@@@3@@Z)	Vbs3Plugin	C:\Travail\SPARTE\Dev\Heroes\trunk\Externals\Vbs3Plugin\build\vs2015\GrpcServer.obj	1

**Comment by nicolasnoble** [comment] 2018-05-15 23:04
Duplicate of #15359 - closing this one.

**Closed by nicolasnoble** 2018-05-15 23:04 UTC
Labels: area/build, lang/c++, platform/Windows

**Comment by TCDigi** [comment] 2018-06-29 09:53
This compilation problem is fix in 1.13.0 ?
