### ISSUE TITLE
C# native memory leak on Grpc.Core.RpcException throw

### ISSUE THREAD

**Issue by amitwaisel** [grpc/grpc#12425] opened 2017-09-07 16:20 UTC
[Server - C# with gRPC v1.3.6, on Windows]
[Client - Node.JS with gRPC v1.3.8, on Linux]

Scenario description:
The client opens many gRPC streams with the C# server. On internal errors, the C# server closes the relevant streams by throwing `Grpc.Core.RpcException`, passing the exception description over the `status` field, using encoded base64 stream (due to the lack of ability to pass complex exception data over the `RpcException`):

```C#
public static RpcException GenerateRpcException(MyInternalException ex)
{
    // MyInternalException is a protobuf message - so it is serialized using protobuf's ToByteString()
    var exceptioninfo_base64 = ex.Request.ToByteString().ToBase64();
    var exception_magic = "client exception";
    var exception_details = string.Join("|", exception_magic, exceptioninfo_base64);
    var status = new Grpc.Core.Status(StatusCode.Unknown, exception_details);
    return new Grpc.Core.RpcException(status);
}
```

While analyzing the virtual memory of the C# server process, after running for a long time (handling hundreds of thousands of exceptions) I found that many **GBs** (!!) of **native heap buffers** are leaked - and all contain the strings that are indicative to the internal `RpcException` ("client exception!XXXXXX") - meaning the `RpcException`'s `status` field is leaked.
Those buffers are **not** part of the GC heap - meaning they are native memory segments, and not managed memory.

@jtattermusch is it related to #11434 ?

Thanks!

**Comment by jtattermusch** [comment] 2017-09-11 09:15
I'm looking into the memory leak now. 

Btw, you are mentioning "due to the lack of ability to pass complex exception data over the RpcException" - this is possible now, see https://github.com/grpc/grpc/pull/12120

**Comment by jtattermusch** [comment] 2017-09-11 09:32
I looked into the issues you're describing and I'm pretty sure that you're seeing what was fixed by #11436. Please upgrade at least to v1.4.0 to get the fix  (and I also recommend upgrading to the newest version).

**Closed by jtattermusch** 2017-09-11 09:32 UTC
Labels: lang/C#

**Comment by amitwaisel** [comment] 2017-09-16 09:55
@jtattermusch after updating the C# server to version 1.6.0, I began experiencing grpc disconnections from both C++ and NodeJS clients. According to the NodeJS error, the error is

> GRPC ERROR!!! 14 {"message":"Endpoint read failed","stack":"Error: Endpoint read failed\n    at ClientReadableStream._emitStatusIfDone (node_modules/grpc/src/node/src/client.js:270:19)\n    at ClientReadableStream._receiveStatus (node_modules/grpc/src/node/src/client.js:248:8)\n    at node_modules/grpc/src/node/src/client.js:720:12"}

Any ideas why it began to happen?
Thanks

**Comment by jtattermusch** [comment] 2017-09-18 09:50
@amitwaisel  
I'm not sure, can you please file a separate issue for this and describe what you're seeing in more detail?  Btw, from the link you posted it is not entirely clear to me that the problem is the C# server.
