### ISSUE TITLE
RPCs are sometimes very slow on Linux

### ISSUE THREAD

**Issue by jtattermusch** [grpc/grpc#3332] opened 2015-09-11 22:23 UTC
RPC done by Helloworld sometimes does strange pauses.

To reproduce:
1. run GreeterServer, you will get message that it is listening (verified by netstat).
2. run GreeterClient. It sometimes finishes the RPC instantly but often times it takes 10s or more before I receive the call completion (the RPC is trivial, should return immediately).

I see similar behavior in routeguide example as well, sometimes the first call finishes and some of the subsequent calls gets stuck.

Not sure if that's related, but when I try this entire thing inside docker, the call never finishes.

This log indicates the call was actually initiated and it's C core where the execution is stuck.
```
GRPC_TRACE=batch,surface mono GreeterClient.exe
I09/11/2015 22:09:23 140254182201216 src/core/surface/call.c:1584: grpc_call_start_batch(call=0x2560430, ops=0x7ffc2214d110, nops=6, tag=0x2667470)
I09/11/2015 22:09:23 140254182201216 src/core/surface/call.c:1584: ops[0]: SEND_INITIAL_METADATA
I09/11/2015 22:09:23 140254182201216 src/core/surface/call.c:1584: ops[1]: SEND_MESSAGE ptr=0x2561710
I09/11/2015 22:09:23 140254182201216 src/core/surface/call.c:1584: ops[2]: SEND_CLOSE_FROM_CLIENT
I09/11/2015 22:09:23 140254182201216 src/core/surface/call.c:1584: ops[3]: RECV_INITIAL_METADATA ptr=0x26674b0
I09/11/2015 22:09:23 140254182201216 src/core/surface/call.c:1584: ops[4]: RECV_MESSAGE ptr=0x26674c8
I09/11/2015 22:09:23 140254182201216 src/core/surface/call.c:1584: ops[5]: RECV_STATUS_ON_CLIENT metadata=0x26674d0 status=0x26674e8 details=0x26674f0
```

**Comment by nicolasnoble** [comment] 2015-09-11 22:30
I'd say this is a duplicate of #3319 ?

**Comment by yang-g** [comment] 2015-09-11 22:33
#3203 may be related as well.

**Comment by ctiller** [comment] 2015-09-12 17:55
Looked into this a little on Friday. Still CNR locally but its high on my
list presently.

**Comment by ctiller** [comment] 2015-09-16 17:59
I'm still unable to reproduce this (but working on it).

In the meantime, could you patch in #3350, and run with `GRPC_TRACE=tcp`

**Comment by ctiller** [comment] 2015-09-17 00:08
Should be fixed

**Closed by ctiller** 2015-09-17 00:08 UTC
Labels: C#, core
