### ISSUE TITLE
New Failure: bm_fullstack_streaming_ping_pong --benchmark_filter=BM_StreamingPingPongMsgs<MinInProcessCHTTP2, NoOpMutator, NoOpMutator>$

### ISSUE THREAD

**Issue by dgquintas** [grpc/grpc#13691] opened 2017-12-08 23:18 UTC
- Test: bm_fullstack_streaming_ping_pong --benchmark_filter=BM_StreamingPingPongMsgs<MinInProcessCHTTP2, NoOpMutator, NoOpMutator>$
- Poll Strategy: epollex
- URL: https://kokoro2.corp.google.com/job/grpc/job/ubuntu/job/sanitizer/job/grpc_cpp_asan/186

**Comment by jtattermusch** [comment] 2018-02-01 16:48
I think this is a duplicate of https://github.com/grpc/grpc/issues/13445 (already closed).

**Closed by jtattermusch** 2018-02-01 16:48 UTC
Labels: infra/BUILDPONY, infra/New Failure
