### ISSUE TITLE
gRPC C# server reflection FileDescriptor dependencies doesn't include package name of proto file

### ISSUE THREAD

**Issue by ashu82492** [grpc/grpc#21200] opened 2019-11-14 06:27 UTC
I have implemented a gRPC service in .NET Core and Enabled gRPC server reflection on it as mentioned in https://github.com/grpc/grpc/blob/master/doc/csharp/server_reflection.md
It's working fine if all proto files of the services have the same package defined. But if proto files have different package name then it doesn't work.
Example:
I have two proto files.
`test.proto`

    package test;
    service testService
    {
        rpc getTest(google.protobuf.Empty) returns(TestResponse)
    }
    message TestResponse
    {
        string Name = 1;
    }

and `empty.proto`  .I have included this file from `protocolbuffers/protobuf` repository wtih package name "google.protobuf"

https://github.com/protocolbuffers/protobuf/blob/master/src/google/protobuf/empty.proto

### What version of gRPC and what language are you using?
Grpc.Reflection 2.25.0
Grpc.Core 2.25.0

### What operating system (Linux, Windows,...) and version?
Tried on Windows 8.1 and Ubuntu

### What did you do?
I am testing server-reflection using grpcui (https://github.com/fullstorydev/grpcui), it produces the error

    Failed to compute set of methods to expose: Symbol not found: test.testService
    caused by: File not found: empty.proto

I tried to debug the code for both Grpc.Reflection library and grpcui.

https://github.com/grpc/grpc/blob/3f108fc5f57a529b0d2912b8b7af952b8117933e/src/csharp/Grpc.Reflection/ReflectionServiceImpl.cs#L109-L124

I found that when calling method `ServerReflectionInfo` with `ServerReflectionRequest.MessageRequestOneofCase.FileContainingSymbol`, 
property `SerializedData`(line 122) doesn't contain descriptor dependency full name. So on the client-side (grpcui) receives dependency name as "**empty.proto**" although it should 
receive "**google/protobuf/empty.proto**".

https://github.com/grpc/grpc/blob/3f108fc5f57a529b0d2912b8b7af952b8117933e/src/csharp/Grpc.Reflection/SymbolRegistry.cs#L54-L59

Now if I call `ServerReflectionRequest.MessageRequestOneofCase.FileByFilename` with received dependency "**empty.proto**", it returns not found error.
Because `filesByName` Dictionary contains "google.protobuf.empty.proto" as Key, not "empty.proto".

### What did you expect to see?
I expect that `ServerReflectionRequest.MessageRequestOneofCase.FileContainingSymbol` request should return dependencies with Full name (including package name)
OR the Dictionary keys should not have the package name in their keys.

OR I am missing something here and doing it the wrong way, please help me to correct it.

**Comment by cw-ashutoshsharma** [comment] 2019-11-15 06:39
https://github.com/jhump/protoreflect/blob/10815c273d3f96493752e245336d4b29ce8715a8/grpcreflect/client.go#L296-L302

Here `depName` variable has value "**empty.proto**", it should be "**google/protobuf/empty.proto**"

**Comment by yashykt** [comment] 2020-05-05 17:48
Hi, from the description, there doesn't seem to be an obvious actionable bug to the gRPC repo. For questions in general, please redirect them to a wider community like stack-overflow. Thanks!

Please re-open if I'm mistaken.

**Comment by jtattermusch** [comment] 2020-05-06 15:31
I'll take a look.

**Comment by ashu82492** [comment] 2020-05-06 17:49
The file `empty.proto` has to be inside a directory structure same as package name. For my case, the issue got resolved when I put the file inside `./google/protobuf/` directory as the package for the proto file is `google.protobif`

**Comment by jtattermusch** [comment] 2020-05-07 11:12
@ashu82492   

> I found that when calling method ServerReflectionInfo with ServerReflectionRequest.MessageRequestOneofCase.FileContainingSymbol,
property SerializedData(line 122) doesn't contain descriptor dependency full name. So on the client-side (grpcui) receives dependency name as "empty.proto" although it should
receive "google/protobuf/empty.proto".

Can you provide your .proto file that imports empty.proto? Have you imported "empty.proto" as `import "google/protobuf/any.proto";` (the way you should) or as `import "empty.proto";` (which is wrong).

Your description doesn't make it fully clear what you've done (ideally you would have provided a project that reproduces the issue), but it seems unlikely that fileDescriptor.SerializedData would include wrong data.

**Comment by jtattermusch** [comment] 2020-05-07 11:16
Closing because it seems that `test.proto` mentioned in the description imports `empty.proto` in and incorrect way (it should imported as `import "google/protobuf/any.proto";`, so that the filename is preserved correctly in the descriptor)

**Closed by jtattermusch** 2020-05-07 11:16 UTC
Labels: kind/bug, lang/C#, priority/P2

**Comment by ashu82492** [comment] 2020-05-07 16:54
@jtattermusch Yes, you are right. I imported it in an incorrect way (same as you have mentioned).
Thanks.

**Comment by Blackclaws** [comment] 2022-08-16 19:05
Just wanted to leave a comment here because I faced a similar issue. I imported everything according to the correct path, however I didn't set ProtoRoot but just used
```
<Protobuf Include="../../PathToProtos/**/*.proto" />
```
This unfortunately sets the Name of the file to just the filename itself. You need to include the ProtoRoot directive and set it to the PathToProtos in this example.

Maybe this helps someone that's stuck on a similar issue.
