### ISSUE TITLE
grpcio 1.6 python client stuck under multiprocessing

### ISSUE THREAD

**Issue by dong-matroid** [grpc/grpc#12489] opened 2017-09-11 21:41 UTC
With grpcio 1.6 on ubuntu 14.04 and python 2.7, grpc client stuck when calling via python multiprocessing. 

Code demonstrate the stuck:
```
import os
import time
import sys
import multiprocessing

from grpc.beta import implementations
import tensorflow as tf

sys.path.append('/home/ubuntu/src/python')
from protos import inception_inference_pb2


networkId = '58a23401292bd68c5302d666'


def run_grpc(network_id):
  hostport = 'localhost:9000'
  host, port = 'localhost', 9000
  channel = implementations.insecure_channel(host, int(port))
  stub = inception_inference_pb2.beta_create_InceptionService_stub(channel)
  request = inception_inference_pb2.ModelRequest()
  request.network_id = network_id
  response = None
  print('do_model_info 2 %s %s' % (hostport, network_id))
  result_future = stub.ModelInfo.future(request, 2.0)
  print('do_model_info 3 %s %s' % (hostport, network_id))
  response = result_future.result()
  print('do_model_info 4 %s %s' % (hostport, network_id))
  print(response)


run_grpc(networkId)

t = multiprocessing.Process(target=run_grpc, args=(networkId,))
t.start()
```

Directly calling run_grpc works, however with multiprocessing, it stuck:
```
python grpc16_stuck.py
do_model_info 2 localhost:9000 58a23401292bd68c5302d666
do_model_info 3 localhost:9000 58a23401292bd68c5302d666
do_model_info 4 localhost:9000 58a23401292bd68c5302d666
message: "Servable not found for request: Latest(58a23401292bd68c5302d666). Failed to lookup session bundle for 58a23401292bd68c5302d666."

do_model_info 2 localhost:9000 58a23401292bd68c5302d666
do_model_info 3 localhost:9000 58a23401292bd68c5302d666
```
The code works fine under grpcio 1.4.0. I think any grpc service should be able to reproduce this issue.

**Comment by ex4sperans** [comment] 2017-09-13 11:49
I got the similar situation. I create an instance of gRPC server in a serarate (forked) process, and then send a message to this server from the parent process. Works fine for 1.4.0, hangs in 1.6.0.

**Comment by lukesneeringer** [comment] 2017-09-13 14:48
We got another issue that I am pretty sure is the same thing: https://github.com/GoogleCloudPlatform/google-cloud-python/issues/3946

Also had an report to Cloud Support that Vision hung, also in celery. That customer confirmed this morning that downgrading to grpcio 1.4.0 solved it.

**Comment by nathanielmanistaatgoogle** [comment] 2017-09-13 15:34
Closing this as a duplicate of [issue 12455](https://github.com/grpc/grpc/issues/12455) - reopen if that's not appropriate?

**Closed by nathanielmanistaatgoogle** 2017-09-13 15:34 UTC
Labels: lang/Python

**Comment by lukesneeringer** [comment] 2017-09-14 15:13
I concur that they are probably the same.
