### ISSUE TITLE
Make gRPC work with Xamarin?

### ISSUE THREAD

**Issue by jgeewax** [grpc/grpc#4117] opened 2015-11-12 12:27 UTC
Long shot, I know, but it'd be really nice if we could figure out how to make our C# libraries work with Xamarin on iOS and Android devices...

**Comment by jtattermusch** [comment] 2015-11-13 13:42
I agree Xamarin support would be nice. This is duplicate of https://github.com/grpc/grpc/issues/1620 though, so closing this.

**Closed by jtattermusch** 2015-11-13 13:42 UTC
