### ISSUE TITLE
Intermittent crash at grpc::GrpcLibraryCodegen::GrpcLibraryCodegen(bool) in grpc_library.h:45

### ISSUE THREAD

**Issue by dconeybe** [grpc/grpc#29843] opened 2022-05-31 19:32 UTC
### What version of gRPC and what language are you using?
1.28.0 and 1.44.0

### What operating system (Linux, Windows,...) and version?
iOS

### What runtime / compiler are you using (e.g. python version or version of gcc)
Xcode 13.3, 13.4 (possibly others)

### What did you do?
Issue is intermittent; no concrete steps to reproduce.
One of the classes in Firestore has a `grpc::CompletionQueue grpc_queue_` member variable ([link](https://github.com/firebase/firebase-ios-sdk/blob/1658c4051e742d88105a6b23ffb4f8fabb0c00f0/Firestore/core/src/remote/datastore.h#L201)). Its initialization occasionally causes a crash.

### What did you expect to see?
No crash.

### What did you see instead?
Intermittent crash:
```
Crashed: com.google.firebase.firestore
0  FirebaseFirestore              0x2ed90 grpc::GrpcLibraryCodegen::GrpcLibraryCodegen(bool) + 45 (grpc_library.h:45)
1  FirebaseFirestore              0x2ec54 grpc::CompletionQueue::CompletionQueue(grpc_completion_queue_attributes const&) + 253 (completion_queue.h:253)
2  FirebaseFirestore              0x2c954 firebase::firestore::remote::Datastore::Datastore(firebase::firestore::core::DatabaseInfo const&, std::__1::shared_ptr<firebase::firestore::util::AsyncQueue> const&, std::__1::shared_ptr<firebase::firestore::credentials::CredentialsProvider<firebase::firestore::credentials::AuthToken, firebase::firestore::credentials::User> >, std::__1::shared_ptr<firebase::firestore::credentials::CredentialsProvider<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > >, firebase::firestore::remote::ConnectivityMonitor*, firebase::firestore::remote::FirebaseMetadataProvider*) + 104 (datastore.cc:104)
3  FirebaseFirestore              0x63204 firebase::firestore::core::FirestoreClient::Initialize(firebase::firestore::credentials::User const&, firebase::firestore::api::Settings const&) + 958 (shared_ptr.h:958)
4  FirebaseFirestore              0x844c firebase::firestore::util::AsyncQueue::ExecuteBlocking(std::__1::function<void ()> const&) + 997 (atomic:997)
5  FirebaseFirestore              0x133414 firebase::firestore::util::Task::ExecuteAndRelease() + 491 (function.h:491)
6  libdispatch.dylib              0x481c _dispatch_client_callout + 20
7  libdispatch.dylib              0xc004 _dispatch_lane_serial_drain + 620
8  libdispatch.dylib              0xcc00 _dispatch_lane_invoke + 404
9  libdispatch.dylib              0x174bc _dispatch_workloop_worker_thread + 764
10 libsystem_pthread.dylib        0x37a4 _pthread_wqthread + 276
11 libsystem_pthread.dylib        0xa74c start_wqthread + 8
```

### Anything else we should know about your project / environment?

I am from the Firestore team and am investigating this crash that was reported by a customer against Firestore. Full details are available at https://github.com/firebase/firebase-ios-sdk/issues/9462. I can't see anything wrong with the code. This looks like a bug of some sort in grpc. Any thoughts would be greatly appreciated. Thank you!

**Comment by veblush** [comment] 2022-06-07 19:37
Would you check whether gRPC objects are created as static variables?

**Comment by dennycd** [comment] 2022-06-07 21:03
FYI this looks like the same issue as reported from https://github.com/grpc/grpc/issues/29500 which also occurs on 13.3.x and up.  Will look into this a bit further from gRPC/iOS side.

**Comment by dconeybe** [comment] 2022-06-13 14:30
@veblush No, the gRPC objects are _not_ created as static variables.

@dennycd That linked issue does indeed look like the same issue. The reporter of that issue mentioned that the crash only happens when their app is installed via MDM; the Firestore users (from which this issue originated) also report the same observation. Thank you for taking a look.

**Comment by veblush** [comment] 2022-10-11 19:53
@dconeybe Isn't the case where an instance enclosing gRPC objects is statically created?

**Comment by ondrejkorol** [comment] 2022-11-13 12:03
Any news, please? This is still the issue for iOS 14.

**Comment by dconeybe** [comment] 2022-11-23 21:51
@veblush I've confirmed that gRPC objects are dynamically created at runtime.

I've debugged this code for hours today and the only explanation is that `g_glip` is null when it is checked in the `GrpcLibraryCodegen` constructor: https://github.com/grpc/grpc/blob/93e689448564585c8ea8b8135481c2dc41b737bb/include/grpcpp/impl/codegen/grpc_library.h#L45-L47

The _only_ explanation that I can think of is that this may be a case of the "Static Initialization Order Fiasco". What if all of the `GrpcLibraryInitializer` constructors, https://github.com/grpc/grpc/blob/93e689448564585c8ea8b8135481c2dc41b737bb/include/grpcpp/impl/grpc_library.h#L41-L45,  happen to run _before_ `g_glip` gets default-initialized to null here: https://github.com/grpc/grpc/blob/93e689448564585c8ea8b8135481c2dc41b737bb/src/cpp/codegen/codegen_init.cc#L30

I don't even know if that's possible, but it's all I can come up with. Thoughts?

**Comment by dconeybe** [comment] 2022-11-23 22:28
Nevermind. I don't think my theory about the "Static Initialization Order Fiasco" makes sense. The memory for `g_glip` will be static initialized to zero before any constructors of `GrpcLibraryInitializer` are run (https://en.cppreference.com/w/cpp/language/initialization).

**Comment by dconeybe** [comment] 2022-12-02 16:47
Another thing that could be at fault is the "summon" method on `GrpcLibraryInitializer`:

https://github.com/grpc/grpc/blob/93e689448564585c8ea8b8135481c2dc41b737bb/include/grpcpp/impl/grpc_library.h#L52-L54

It's documented "to force the linker to reference this class". But couldn't that "summon" method be optimized away? It's an inline method with no side effects, which is a perfect candidate for being completely removed. Would it make sense to instead use something like Google Benchmark's "DoNotOptimize" and "ClobberMemory" functions?

https://github.com/google/benchmark/blob/main/docs/user_guide.md#preventing-optimization

Is it possible that something is getting optimized away, and therefore `grpc::g_glip` is failing to get initialized?

**Comment by veblush** [comment] 2022-12-15 18:24
@dconeybe I'm not experience on iOS specific matter of handling this static variables so I'd like to get help from @sampajano .

**Comment by ctiller** [comment] 2022-12-15 23:05
@ralphchung didn't we delete that variable recently?

**Comment by ralphchung** [comment] 2022-12-16 01:53
@ctiller Yes, but it does not seem to be released so far. Looking at this issue, it reminds me of the problem we had when trying to remove `GrpcLibrarayCodegen`. Would that be related?

**Comment by dconeybe** [comment] 2023-01-06 02:41
Update: One customer claims that this patch to grpc fixed the crashes for them:
https://gist.github.com/dconeybe/31892c1d5c6b1c7d366947a46ee0207a

Basically, it changes the raw pointers for `CoreCodegenInterface` and `GrpcLibraryInterface` to an instance of a class with a constexpr constructor (so it is initialized at compile time, avoiding any "Static Initialization Order Fiasco" issues) and a member `std::atomic<T*>` object that stores the pointer to the CoreCodegenInterface or GrpcLibraryInterface.

Does this provide any insights?

**Comment by ralphchung** [comment] 2023-01-06 06:26
@dconeybe Thank you for providing this. From what I know now, we hope to avoid the use of `std::atmoic<>` to prevent any possible overheads. I am wondering if using the constexpr constructor with a raw pointer member variable is possible. But no matter what, the global pointers `g_core_codegen_interface` and `g_glip` have been removed in the upstream, which means we are not dealing with such issues in the future.

@ctiller Please correct me if I am wrong.

**Comment by veblush** [comment] 2023-01-17 20:48
As gRPC removed `GrpcLibraryCodegen` which might happen to fix this issue, I think we can close this issue.

**Closed by veblush** 2023-01-17 20:48 UTC
Labels: kind/bug, lang/core, priority/P2, platform/iOS, untriaged

**Comment by gyulavoros** [comment] 2023-02-14 20:04
@dconeybe do you have any news here? Has Firestore picked up this change in any recent version updates?

**Comment by dconeybe** [comment] 2023-02-15 16:22
@gyulavoros Firestore is unable to upgrade its grpc version due to supporting C++11. The latest grpc versions require a minimum of C++14. Firestore plans to drop C++11 support later this year (no firm date has been announced yet though) at which point it will upgrade its grpc dependency and this issue should go away.

Until then you can try the hacky workaround documented at https://github.com/firebase/firebase-ios-sdk/issues/9462#issuecomment-1341250988. So far one customer has reported that the workaround fixes their crash: https://github.com/firebase/firebase-ios-sdk/issues/10622#issuecomment-1372299314.

**Comment by dimovskidamjan** [comment] 2023-11-02 12:19
@dconeybe if it helps, I have a way to consistently reproduce this crash running on an iOS 14 sim via Xcode 15, using the latest version of the lib from Cocoapods. On app launch on any iOS 14 sim I get a crash here:
<img width="626" alt="Screenshot 2023-11-02 at 13 18 51" src="https://github.com/grpc/grpc/assets/9072054/9f7c9386-2912-4a56-a67b-a3ec39eff736">
which I think is in line with some of your previous discoveries in this thread. If I can do anything to help you debug and/or fix this let me know.

**Comment by dconeybe** [comment] 2023-11-02 13:35
Thanks for the note, @dimovskidamjan. Firestore has now dropped C++11 support, which has unblocked Firestore from upgrading its grpc dependency. Once the dependency is upgraded, the problematic code that you referenced will not even exist. In fact, Firestore is highly motivated to upgrade its grpc dependency to pick up https://github.com/grpc/grpc/pull/34416, which fixes another crash. There are some other issues blocking the upgrade but we are actively working through it. I'll try to remember to post back here once the upgrade occurs; however, we will include it in the release notes so you can check there as well. Sorry I don't have any better news, but I hope this gives you some hope.

**Comment by dimovskidamjan** [comment] 2023-11-02 13:50
No problem @dconeybe, fortunately, we are able to drop iOS 14 support on our project before it goes live so it will not be an issue in production. Glad to hear it's been resolved in the meantime 👍
