### ISSUE TITLE
Failure: Unavailale status in cloud_to_prod:default:ruby:large_unary

### ISSUE THREAD

**Issue by apolcyn** [grpc/grpc#12568] opened 2017-09-14 04:46 UTC
```
2017-09-12 14:39:00,218 WAITING: ETA 32.3 sec; 192 queued, 12 jobs running, 82 complete, 0 failed
2017-09-12 14:39:00,420 /var/local/git/grpc/src/ruby/lib/grpc/generic/active_call.rb:31:in `check_status': 14:Endpoint read failed (GRPC::Unavailable)
	from /var/local/git/grpc/src/ruby/lib/grpc/generic/active_call.rb:171:in `attach_status_results_and_complete_call'
	from /var/local/git/grpc/src/ruby/lib/grpc/generic/active_call.rb:363:in `request_response'
	from /var/local/git/grpc/src/ruby/lib/grpc/generic/client_stub.rb:152:in `request_response'
	from /var/local/git/grpc/src/ruby/lib/grpc/generic/service.rb:170:in `block (3 levels) in rpc_stub_class'
	from src/ruby/pb/test/client.rb:668:in `perform_large_unary'
	from src/ruby/pb/test/client.rb:267:in `large_unary'
	from src/ruby/pb/test/client.rb:758:in `call'
	from src/ruby/pb/test/client.rb:758:in `main'
	from src/ruby/pb/test/client.rb:763:in `<main>'
I, [2017-09-12T21:38:59.816587 #68]  INFO -- : ... connecting securely to 216.239.32.254:443

2017-09-12 14:39:00,420 FAILED: cloud_to_prod:default:ruby:large_unary [ret=1, pid=10083]
```

https://sponge.corp.google.com/target?id=03e1be58-0a62-4c84-bd84-644cafa01e9c&target=grpc/ubuntu/pull_request/grpc_interop_toprod&searchFor=&show=ALL&sortBy=STATUS

**Comment by AspirinSJL** [comment] 2017-10-06 16:22
Similar issue in csharp
https://sponge.corp.google.com/target?tab=Test+Log&attempt=1&sortBy=STATUS&show=ALL&id=244e872b-47d0-40c4-b9df-05e87bd5b4a4&target=grpc/ubuntu/pull_request/grpc_interop_toprod&searchFor=

```
2017-10-05 15:29:02,339 D1005 22:29:01.569670 Grpc.Core.Internal.UnmanagedLibrary Attempting to load native library "/var/local/git/grpc/src/csharp/Grpc.IntegrationTesting.Client/bin/Debug/netcoreapp1.0/libgrpc_csharp_ext.x64.so"
D1005 22:29:01.668561 Grpc.Core.Internal.NativeExtension gRPC native library loaded successfully.
running large_unary

Unhandled Exception: System.AggregateException: One or more errors occurred. (Status(StatusCode=Unavailable, Detail="Endpoint read failed")) ---> Grpc.Core.RpcException: Status(StatusCode=Unavailable, Detail="Endpoint read failed")
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Grpc.Core.Internal.AsyncCall`2.UnaryCall(TRequest msg)
   at Grpc.Core.Calls.BlockingUnaryCall[TRequest,TResponse](CallInvocationDetails`2 call, TRequest req)
   at Grpc.Core.DefaultCallInvoker.BlockingUnaryCall[TRequest,TResponse](Method`2 method, String host, CallOptions options, TRequest request)
   at Grpc.Core.Internal.InterceptingCallInvoker.BlockingUnaryCall[TRequest,TResponse](Method`2 method, String host, CallOptions options, TRequest request)
   at Grpc.Testing.TestService.TestServiceClient.UnaryCall(SimpleRequest request, CallOptions options)
   at Grpc.Testing.TestService.TestServiceClient.UnaryCall(SimpleRequest request, Metadata headers, Nullable`1 deadline, CancellationToken cancellationToken)
   at Grpc.IntegrationTesting.InteropClient.RunLargeUnary(TestServiceClient client)
   at Grpc.IntegrationTesting.InteropClient.<RunTestCaseAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Grpc.IntegrationTesting.InteropClient.<Run>d__4.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at Grpc.IntegrationTesting.InteropClient.<>c.<Run>b__3_1(ClientOptions options)
   at CommandLine.ParserResultExtensions.WithParsed[T](ParserResult`1 result, Action`1 action)
   at Grpc.IntegrationTesting.InteropClient.Run(String[] args)
   at Grpc.IntegrationTesting.Client.Program.Main(String[] args)

2017-10-05 15:29:02,340 FAILED: cloud_to_prod:gateway_v4:csharpcoreclr:large_unary [ret=139, pid=22394]
```

**Comment by jtattermusch** [comment] 2017-11-06 15:16
Dupe of #10763

**Closed by jtattermusch** 2017-11-06 15:16 UTC
Labels: infra/BUILDPONY
