### ISSUE TITLE
Timed out: //test/cpp/end2end:client_lb_end2end_test@poller=poll-cv

### ISSUE THREAD

**Issue by markdroth** [grpc/grpc#16482] opened 2018-08-28 18:52 UTC
https://source.cloud.google.com/results/invocations/bc5874a0-fef6-49e3-a18b-0a50b72f5e35/targets/%2F%2Ftest%2Fcpp%2Fend2end:client_lb_end2end_test@poller%3Dpoll-cv/log

```
exec ${PAGER:-/usr/bin/less} "$0" || exit 1
Executing tests from //test/cpp/end2end:client_lb_end2end_test@poller=poll-cv
-----------------------------------------------------------------------------
+ export GRPC_POLL_STRATEGY=poll-cv
+ shift
+ test/cpp/end2end/client_lb_end2end_test
D0828 15:57:03.056240492      18 test_config.cc:391]         test slowdown factor: sanitizer=1, fixture=1, poller=5, total=5
[==========] Running 20 tests from 1 test case.
[----------] Global test environment set-up.
[----------] 20 tests from ClientLbEnd2endTest
[ RUN      ] ClientLbEnd2endTest.PickFirst
[       OK ] ClientLbEnd2endTest.PickFirst (5 ms)
[ RUN      ] ClientLbEnd2endTest.PickFirstProcessPending
[       OK ] ClientLbEnd2endTest.PickFirstProcessPending (2 ms)
[ RUN      ] ClientLbEnd2endTest.PickFirstBackOffInitialReconnect
[       OK ] ClientLbEnd2endTest.PickFirstBackOffInitialReconnect (1618 ms)
[ RUN      ] ClientLbEnd2endTest.PickFirstBackOffMinReconnect
[       OK ] ClientLbEnd2endTest.PickFirstBackOffMinReconnect (11001 ms)
[ RUN      ] ClientLbEnd2endTest.PickFirstResetConnectionBackoff
[       OK ] ClientLbEnd2endTest.PickFirstResetConnectionBackoff (105 ms)
[ RUN      ] ClientLbEnd2endTest.PickFirstUpdates
[       OK ] ClientLbEnd2endTest.PickFirstUpdates (8 ms)
[ RUN      ] ClientLbEnd2endTest.PickFirstUpdateSuperset
[       OK ] ClientLbEnd2endTest.PickFirstUpdateSuperset (4 ms)
[ RUN      ] ClientLbEnd2endTest.PickFirstManyUpdates
test/cpp/end2end/client_lb_end2end_test.cc:232: Failure
Value of: success
  Actual: false
Expected: true
From (null):-1
Error: Deadline Exceeded 
test/cpp/end2end/client_lb_end2end_test.cc:232: Failure
Value of: success
  Actual: false
Expected: true
From (null):-1
Error: Deadline Exceeded 
test/cpp/end2end/client_lb_end2end_test.cc:232: Failure
Value of: success
  Actual: false
Expected: true
From (null):-1
Error: Deadline Exceeded 
test/cpp/end2end/client_lb_end2end_test.cc:232: Failure
Value of: success
  Actual: false
Expected: true
From (null):-1
Error: Deadline Exceeded 
test/cpp/end2end/client_lb_end2end_test.cc:232: Failure
Value of: success
  Actual: false
Expected: true
From (null):-1
Error: Deadline Exceeded 
test/cpp/end2end/client_lb_end2end_test.cc:232: Failure
Value of: success
  Actual: false
Expected: true
From (null):-1
Error: Deadline Exceeded 
test/cpp/end2end/client_lb_end2end_test.cc:232: Failure
Value of: success
  Actual: false
Expected: true
From (null):-1
Error: Deadline Exceeded 
test/cpp/end2end/client_lb_end2end_test.cc:232: Failure
Value of: success
  Actual: false
Expected: true
From (null):-1
Error: Deadline Exceeded 
test/cpp/end2end/client_lb_end2end_test.cc:232: Failure
Value of: success
  Actual: false
Expected: true
From (null):-1
Error: Deadline Exceeded 
test/cpp/end2end/client_lb_end2end_test.cc:232: Failure
Value of: success
  Actual: false
Expected: true
From (null):-1
Error: Deadline Exceeded 
test/cpp/end2end/client_lb_end2end_test.cc:232: Failure
Value of: success
  Actual: false
Expected: true
From (null):-1
Error: Deadline Exceeded 
test/cpp/end2end/client_lb_end2end_test.cc:232: Failure
Value of: success
  Actual: false
Expected: true
From (null):-1
Error: Deadline Exceeded 
test/cpp/end2end/client_lb_end2end_test.cc:232: Failure
Value of: success
  Actual: false
Expected: true
From (null):-1
Error: Deadline Exceeded 
test/cpp/end2end/client_lb_end2end_test.cc:232: Failure
Value of: success
  Actual: false
Expected: true
From (null):-1
Error: Deadline Exceeded 
test/cpp/end2end/client_lb_end2end_test.cc:232: Failure
Value of: success
  Actual: false
Expected: true
From (null):-1
Error: Deadline Exceeded 
test/cpp/end2end/client_lb_end2end_test.cc:232: Failure
Value of: success
  Actual: false
Expected: true
From (null):-1
Error: Deadline Exceeded 
test/cpp/end2end/client_lb_end2end_test.cc:232: Failure
Value of: success
  Actual: false
Expected: true
From (null):-1
Error: Deadline Exceeded 
test/cpp/end2end/client_lb_end2end_test.cc:232: Failure
Value of: success
  Actual: false
Expected: true
From (null):-1
Error: Deadline Exceeded 
test/cpp/end2end/client_lb_end2end_test.cc:232: Failure
Value of: success
  Actual: false
Expected: true
From (null):-1
Error: Deadline Exceeded 
test/cpp/end2end/client_lb_end2end_test.cc:232: Failure
Value of: success
  Actual: false
Expected: true
From (null):-1
Error: Deadline Exceeded 
test/cpp/end2end/client_lb_end2end_test.cc:232: Failure
Value of: success
  Actual: false
Expected: true
From (null):-1
Error: Deadline Exceeded 
test/cpp/end2end/client_lb_end2end_test.cc:232: Failure
Value of: success
  Actual: false
Expected: true
From (null):-1
Error: Deadline Exceeded 
test/cpp/end2end/client_lb_end2end_test.cc:232: Failure
Value of: success
  Actual: false
Expected: true
From (null):-1
Error: Deadline Exceeded 
test/cpp/end2end/client_lb_end2end_test.cc:232: Failure
Value of: success
  Actual: false
Expected: true
From (null):-1
Error: Deadline Exceeded 
test/cpp/end2end/client_lb_end2end_test.cc:232: Failure
Value of: success
  Actual: false
Expected: true
From (null):-1
Error: Deadline Exceeded 
test/cpp/end2end/client_lb_end2end_test.cc:232: Failure
Value of: success
  Actual: false
Expected: true
From (null):-1
Error: Deadline Exceeded 
test/cpp/end2end/client_lb_end2end_test.cc:232: Failure
Value of: success
  Actual: false
Expected: true
From (null):-1
Error: Deadline Exceeded 
test/cpp/end2end/client_lb_end2end_test.cc:232: Failure
Value of: success
  Actual: false
Expected: true
From (null):-1
Error: Deadline Exceeded 
test/cpp/end2end/client_lb_end2end_test.cc:232: Failure
Value of: success
  Actual: false
Expected: true
From (null):-1
Error: Deadline Exceeded 
test/cpp/end2end/client_lb_end2end_test.cc:232: Failure
Value of: success
  Actual: false
Expected: true
From (null):-1
Error: Deadline Exceeded 
test/cpp/end2end/client_lb_end2end_test.cc:232: Failure
Value of: success
  Actual: false
Expected: true
From (null):-1
Error: Deadline Exceeded 
test/cpp/end2end/client_lb_end2end_test.cc:232: Failure
Value of: success
  Actual: false
Expected: true
From (null):-1
Error: Deadline Exceeded 
test/cpp/end2end/client_lb_end2end_test.cc:232: Failure
Value of: success
  Actual: false
Expected: true
From (null):-1
Error: Deadline Exceeded 
test/cpp/end2end/client_lb_end2end_test.cc:232: Failure
Value of: success
  Actual: false
Expected: true
From (null):-1
Error: Deadline Exceeded 
test/cpp/end2end/client_lb_end2end_test.cc:232: Failure
Value of: success
  Actual: false
Expected: true
From (null):-1
Error: Deadline Exceeded 
test/cpp/end2end/client_lb_end2end_test.cc:232: Failure
Value of: success
  Actual: false
Expected: true
From (null):-1
Error: Deadline Exceeded 
test/cpp/end2end/client_lb_end2end_test.cc:232: Failure
Value of: success
  Actual: false
Expected: true
From (null):-1
Error: Deadline Exceeded 
test/cpp/end2end/client_lb_end2end_test.cc:232: Failure
Value of: success
  Actual: false
Expected: true
From (null):-1
Error: Deadline Exceeded 
test/cpp/end2end/client_lb_end2end_test.cc:232: Failure
Value of: success
  Actual: false
Expected: true
From (null):-1
Error: Deadline Exceeded 
test/cpp/end2end/client_lb_end2end_test.cc:232: Failure
Value of: success
  Actual: false
Expected: true
From (null):-1
Error: Deadline Exceeded 
test/cpp/end2end/client_lb_end2end_test.cc:232: Failure
Value of: success
  Actual: false
Expected: true
From (null):-1
Error: Deadline Exceeded 
test/cpp/end2end/client_lb_end2end_test.cc:232: Failure
Value of: success
  Actual: false
Expected: true
From (null):-1
Error: Deadline Exceeded 
test/cpp/end2end/client_lb_end2end_test.cc:232: Failure
Value of: success
  Actual: false
Expected: true
From (null):-1
Error: Deadline Exceeded 
test/cpp/end2end/client_lb_end2end_test.cc:232: Failure
Value of: success
  Actual: false
Expected: true
From (null):-1
Error: Deadline Exceeded 
```

**Comment by mhaidrygoog** [comment] 2018-08-29 16:46
Facing similar issue, except the poller is epollsig
https://source.cloud.google.com/results/invocations/eb97ea91-fae4-4b55-ab28-43592ad60503/targets/%2F%2Ftest%2Fcpp%2Fend2end:client_lb_end2end_test@poller%3Depollsig/tests

**Comment by jtattermusch** [comment] 2018-08-31 07:32
Dupe of #16123.

**Closed by jtattermusch** 2018-08-31 07:32 UTC
Labels: infra/BUILDPONY, kind/internal cleanup, lang/core, priority/P2
