### ISSUE TITLE
Run client channel backup poller

### ISSUE THREAD

**Issue by ne1llee** [grpc/grpc#22508] opened 2020-03-29 14:34 UTC
### What version of gRPC and what language are you using?
python2.7 grpcio==1.27.2

### What operating system (Linux, Windows,...) and version?
centos 7.5

### What did you do?
Python USES multiple threads to access the golang server.

### What did you see instead?

E0329 22:23:15.190887644   34406 backup_poller.cc:132]       Run client channel backup poller: {"created":"@1585491795.190833305","description":"pollset_work","file":"src/core/lib/iomgr/ev_epoll1_l
inux.cc","file_line":242,"referenced_errors":[{"created":"@1585491795.190824118","description":"Bad file descriptor","errno":9,"file":"src/core/lib/iomgr/ev_epoll1_linux.cc","file_line":731,"os_err
or":"Bad file descriptor","syscall":"epoll_wait"}]}

### Anything else we should know about your project / environment?
centos7.5
server: go 1.13.4
client: python2.7 grpcio==1.27.2

**Comment by qtvspa** [comment] 2020-09-01 02:10
I'm facing similar issue on macOS
- server: java
- client: python3.7, grpcio-tools==1.31.0

error logs

- E0901 10:09:09.880056268     125 backup_poller.cc:132]       Run client channel backup poller: {"created":"@1598926149.880029397","description":"pollset_work","file":"src/core/lib/iomgr/ev_epollex_linux.cc","file_line":321,"referenced_errors":[{"created":"@1598926149.880027174","description":"Bad file descriptor","errno":9,"file":"src/core/lib/iomgr/ev_epollex_linux.cc","file_line":948,"os_error":"Bad file descriptor","syscall":"epoll_wait"}]}
  | E0901 10:09:14.880105530     108 backup_poller.cc:132]       Run client channel backup poller: {"created":"@1598926154.880080877","description":"pollset_work","file":"src/core/lib/iomgr/ev_epollex_linux.cc","file_line":321,"referenced_errors":[{"created":"@1598926154.880074373","description":"Bad file descriptor","errno":9,"file":"src/core/lib/iomgr/ev_epollex_linux.cc","file_line":948,"os_error":"Bad file descriptor","syscall":"epoll_wait"}]}
  | E0901 10:09:19.880048521     125 backup_poller.cc:132]       Run client channel backup poller: {"created":"@1598926159.880015964","description":"pollset_work","file":"src/core/lib/iomgr/ev_epollex_linux.cc","file_line":321,"referenced_errors":[{"created":"@1598926159.880013688","description":"Bad file descriptor","errno":9,"file":"src/core/lib/iomgr/ev_epollex_linux.cc","file_line":948,"os_error":"Bad file descriptor","syscall":"epoll_wait"}]}

**Comment by mwtian** [comment] 2022-01-03 22:41
Also seeing the same error, with python 3.7 & grpcio 1.42.0.

**Comment by lidizheng** [comment] 2022-01-04 18:05
There are many probable causes for `Bad file descriptor`. We might need a reproduce snippet to investigate. Can someone provide one with the latest gRPC release?

**Comment by mwtian** [comment] 2022-01-04 18:17
So far we have only observed this occasionally in a large cluster. Will try to see if it can be reproduced reliably. One question about `grpc_client_channel_backup_poll_interval_ms`, what is the downside of disabling backup polling, e.g. is it higher tail latency?

**Comment by lidizheng** [comment] 2022-01-04 18:19
CC @yashykt who might have the best knowledge about pollers.

**Comment by yashykt** [comment] 2022-01-04 23:35
@drfloob @nicolasnoble are the ones who are actively working in this space at the moment and might have the best answer here.

**Comment by drfloob** [comment] 2022-02-14 18:43
> One question about grpc_client_channel_backup_poll_interval_ms, what is the downside of disabling backup polling?

The backup poller was originally added to work around an issue when applications used the sync API, but didn't make fairly frequent calls. In these cases, channels would sometimes disconnect and go unnoticed because nothing was polling the fds (the sync API does not require applications to loan threads for CQ polling), and subsequent calls would fail instead of gracefully being queued while the channel attempted to reconnect (or better, having the channel attempt to reconnect before the next call was even made). Disabling the backup poller could reintroduce these issues, though I'm not sure how Python integrates with core in this respect.

There's nothing terribly special about the backup poller fds, I'd be surprised if this is a failing of the backup poller itself. Does this happen mostly in long-running processes with infrequent calls? I'd still be interested to see how this is reproduced.

These sorts of issues *may* be solved by the transparent retry feature that rolled out recently, and note that the backup poller will be removed altogether sometime this year when we replace gRPC's low-level I/O layer (search EventEngine, if you're interested).

**Comment by mwtian** [comment] 2022-02-14 19:31
@drfloob Thanks for the details! I believe `long-running processes with infrequent calls` fits the environment where the error happens. We don't have the repro yet. Looking forward to when this is no longer an issue!

**Comment by troymyname** [comment] 2022-07-14 10:59
Hi all. I am having a similar issue on my Linux machine. Was anyone able to reproduce this problem? Is there a way to bypass this problem?

**Comment by tgpfeiffer** [comment] 2022-07-14 11:22
I think this is caused by the problem described in https://github.com/grpc/grpc/blob/master/doc/fork_support.md

I don't have the code any more, but I was very much able to reproduce this when launching a subprocess after gRPC use. Changing from the `epoll1` backend to the `poll` backend (see https://grpc.github.io/grpc/core/md_doc_core_grpc-polling-engines.html) solved the problem for us. (We also tried to set the `GRPC_ENABLE_FORK_SUPPORT` environment variable to fix a related issue, but unfortunately ran into https://github.com/grpc/grpc/issues/18075#issuecomment-1150833429 then.)

**Comment by moveingsun** [comment] 2022-08-29 22:33
i'm facing the same issue here, with grpcio==1.47.0, when i set the `GRPC_ENABLE_FORK_SUPPORT=False` and `GRPC_POLL_STRATEGY=poll`, with python multiple processing the pubsub client will hang when trying to push to topic. And it won't hang when i remove the `GRPC_ENABLE_FORK_SUPPORT=False` from environment.

**Comment by drfloob** [comment] 2022-09-21 19:08
@tgpfeiffer @moveingsun those are separate issues. For python multiprocessing, you need to enable fork support and use the `poll` poller, otherwise you can expect occasional (non-deterministic) hangs on fork since threads will not be shut down pre-fork otherwise.

It's been 9 months without a repro for the original issue, and no comment back about the retry feature, so this is mostly non-actionable at the moment. Closing, and will reopen if this becomes actionable.

**Closed by drfloob** 2022-09-21 19:08 UTC
Labels: kind/bug, lang/Python, priority/P2

**Comment by dshivashankar1994** [comment] 2023-08-16 16:17
> These sorts of issues may be solved by the transparent retry feature that rolled out recently, and note that the backup poller will be removed altogether sometime this year when we replace gRPC's low-level I/O layer (search EventEngine, if you're interested).

@drfloob, Is this done ? I'm still observing the issue but not reproducible consistently and I don't have a simple reproducer too

**Comment by hsebik** [comment] 2024-02-15 15:43
I had same issue as well it hits very occasionally, 
I am using 
nvidia/cuda:12.3.1-runtime-ubuntu20.04 base docker image and
google-cloud-storage==2.14.0
google-cloud-pubsub==2.19.4
then
grpcio==1.60.1

```
pthread_create failed: Resource temporarily unavailable
Run client channel backup poller: UNKNOWN:pollset_work {created_time:"2024-02-15T15:13:56.838815587+00:00", children:[UNKNOWN:Bad file descriptor {syscall:"epoll_wait", os_error:"Bad file descriptor", errno:9, created_time:"2024-02-15T15:13:56.838744382+00:00"}]}
```
