### ISSUE TITLE
Can't build by Bazel as an external imported project.

### ISSUE THREAD

**Issue by renning22** [grpc/grpc#12122] opened 2017-08-08 20:55 UTC
Please answer these questions before submitting your issue. 
 
### Should this be an issue in the gRPC issue tracker?
 
Create new issues for bugs and feature requests. An issue needs to be actionable. General gRPC discussions and usage questions belong to:
- [grpc.io mailing list](https://groups.google.com/forum/#!forum/grpc-io)
- [StackOverflow, with `grpc` tag](http://stackoverflow.com/questions/tagged/grpc)
 
*Please don't double post your questions in more locations; we are monitoring both channels, and the time spent de-duplicating questions is better spent answering more user questions.*
 
### What version of gRPC and what language are you using?
 1.4.3
 
### What operating system (Linux, Windows, …) and version?
 Linux
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
Bazel 0.4.5
 
### What did you do?
If possible, provide a recipe for reproducing the error. Try being specific and include code snippets if helpful.

Import grpc as an external repo by git_repository, then can't build.

 
### What did you expect to see?
 Build successful.
 
### What did you see instead?

❯❯❯ bazel build @com_github_grpc_grpc//:grpc
ERROR: /usr/local/google/home/ningr/.cache/bazel/_bazel_ningr/5cdbcab7751afe004080d5ce1e95b149/external/com_github_grpc_grpc/BUILD:1008:1: no such target '//external:cares': target 'cares' not declared in package 'external' (did you mean 'ceres'?) defined by /usr/local/google/home/ningr/redwood_gob/WORKSPACE and referenced by '@com_github_grpc_grpc//:grpc_resolver_dns_ares'.
ERROR: Analysis of target '@com_github_grpc_grpc//:grpc' failed; build aborted.

ERROR: /usr/local/google/home/ningr/.cache/bazel/_bazel_ningr/5cdbcab7751afe004080d5ce1e95b149/external/com_github_grpc_grpc/bazel/BUILD:41:1: missing mandatory positional argument 'well_known_protos' while calling cc_grpc_library(name, srcs, deps, proto_only, well_known_protos, generate_mock, use_external = False, **kwargs).
ERROR: package contains errors: bazel.
ERROR: error loading package '@com_github_grpc_grpc//bazel': Package 'bazel' contains errors.

 
Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

**Comment by junghoahnsc** [comment] 2017-08-09 17:49
I have the same issue.

**Comment by riverhxz** [comment] 2017-08-10 06:44
the same issue when i  build //tensorflow-serving/model_servers:tensorflow_model_server.

**Comment by kirilg** [comment] 2017-08-10 22:04
+1 when building TensorFlow Serving after syncing TF to head.

Is there any any way to configure grpc to use a default 'cares' package without having to provide our own binding?

**Comment by nicolasnoble** [comment] 2017-08-14 21:27
The point of Bazel is to be fully hermetic. When building a subproject using Bazel, you HAVE to provide source code bindings for all of its dependencies. That's both a pro and a con of Bazel. So, I'd say, "working as intended".

Since TensorFlow uses gRPC as a subproject, they are binding all of its dependencies in their workspace script. If they have updated the gRPC submodule without providing bindings for c-ares, that's a bug in TensorFlow, not gRPC.

**Comment by kirilg** [comment] 2017-08-14 21:48
It would be nice for users of gRPC if you provide default implementations of everything so we don't need to provide additional bindings (or make them optional for advanced users rather than mandatory for everyone).

As I understand it, you're using [this](https://github.com/grpc/grpc/tree/master/third_party/cares) implementation and have to provide your own BUILD file. We wouldn't be able to use it directly in our WORKSPACE since it's just a directory in your repo rather than a whole git_repository, and we wouldn't be able to use the actual [cares repo](https://github.com/c-ares/c-ares/tree/7691f773af79bf75a62d1863fd0f13ebf9dc51b1) because it's not a Bazel project with a BUILD file. What's the recommended way to include this binding?

**Comment by nicolasnoble** [comment] 2017-08-14 22:05
You can see what we are doing in our own [WORKSPACE ](https://github.com/grpc/grpc/blob/master/WORKSPACE#L85)file: 

```
new_local_repository(
    name = "submodule_cares",
    path = "third_party/cares",
    build_file = "third_party/cares/cares.BUILD",
)
```

Feel free to steal our `cares.BUILD` file and associated configuration files (the generated .h files) and use the same exact submodule sha1. Basically, you'd need to duplicate 3 or 4 files into your project, and that'd be it.

**Comment by renning22** [comment] 2017-08-15 20:19
It would be a bonus if those default dependency bindings used in WORKSPACE are packed into a function and put in a bzl file. This will be super convenient for importing.

Something like:

```
load("//bazel/deps.bzl", "bind_grpc_deps")
bind_grpc_deps()
```

(Here is an example from rules_protobuf, https://github.com/pubref/rules_protobuf/blob/master/WORKSPACE)

**Comment by nicolasnoble** [comment] 2017-08-15 23:06
I don't really have any problem with this, save it that right now we're actually using the submodules themselves from the disk, and not actual git submodules from within git. Once thing that I've been anal about in the past (and I still am tbh), is making sure we have everything in sync and that people don't change the submodules by mistake. Therefore we have that test script here: https://github.com/grpc/grpc/blob/master/tools/run_tests/sanity/check_submodules.sh

I feel it should be possible to test the list of submodules from the bzl file too, but I'm not 100% sure how. What do you think ?

**Comment by renning22** [comment] 2017-08-28 21:35
Yes, it's possible to verify the hash code of imported repositories by bazel.
(Example: https://github.com/pubref/rules_protobuf/blob/master/protobuf/internal/require.bzl#L17)

And it will be nice to use "new_git_repository" (rather than "new_local_repository") to let bazel download/manage those 3rd-party dependencies. It'll be easier to import grpc from other bazel project. People can simply copy/paste those "new_git_repository" into their own WORKSPACE files.

WDYT?

**Comment by jwpowell055** [comment] 2017-10-17 02:26
Any movement on this topic? It'd be great to be able to use Bazel to build a project that uses gRPC without extra workarounds to get gRPC to build.

**Comment by qiaohaijun** [comment] 2017-11-02 08:15
+1 
I have the same issue when building tensorflow_serving 1.3.0

**Comment by renning22** [comment] 2017-11-02 20:18
Hi @nicolasnoble, I can work on this.
Make Bazel build not rely on git submodules, and use the identical version of dependencies listed [here](https://github.com/grpc/grpc/blob/master/tools/run_tests/sanity/check_submodules.sh). Please assign this bug to me.

**Comment by renning22** [comment] 2017-11-21 00:03
I've drafted a PR (https://github.com/grpc/grpc/pull/13468) for the fix. Please take a look. @nicolasnoble

**Comment by nictuku** [comment] 2018-01-09 03:01
Hi @renning22, this seems to mostly work except for things like the `grpc_cli`. Here's what I get when I try to build it:

```
bazel build @com_github_grpc_grpc//test/cpp/util:grpc_cli
```

Current output:

```
ERROR: (12-27 21:49:06.225) /Users/yves/workspace/cache/b632e528b7657b271e4465cc6ae42619/external/com_github_grpc_grpc/src/proto/grpc/reflection/v1alpha/BUILD:21:1: output 'external/com_github_grpc_grpc/src/proto/grpc/reflection/v1alpha/proto/grpc/reflection/v1alpha/reflection.pb.h' was not created.
ERROR: (12-27 21:49:06.226) /Users/yves/workspace/cache/b632e528b7657b271e4465cc6ae42619/external/com_github_grpc_grpc/src/proto/grpc/reflection/v1alpha/BUILD:21:1: output 'external/com_github_grpc_grpc/src/proto/grpc/reflection/v1alpha/proto/grpc/reflection/v1alpha/reflection.pb.cc' was not created.
ERROR: (12-27 21:49:06.227) /Users/yves/workspace/cache/b632e528b7657b271e4465cc6ae42619/external/com_github_grpc_grpc/src/proto/grpc/reflection/v1alpha/BUILD:21:1: not all outputs were created or valid.
ERROR: (12-27 21:49:06.239) /Users/yves/workspace/cache/b632e528b7657b271e4465cc6ae42619/external/com_github_grpc_grpc/src/proto/grpc/reflection/v1alpha/BUILD:21:1: output 'external/com_github_grpc_grpc/src/proto/grpc/reflection/v1alpha/proto/grpc/reflection/v1alpha/reflection.grpc.pb.h' was not created.
ERROR: (12-27 21:49:06.240) /Users/yves/workspace/cache/b632e528b7657b271e4465cc6ae42619/external/com_github_grpc_grpc/src/proto/grpc/reflection/v1alpha/BUILD:21:1: output 'external/com_github_grpc_grpc/src/proto/grpc/reflection/v1alpha/proto/grpc/reflection/v1alpha/reflection.grpc.pb.cc' was not created.
Target @com_github_grpc_grpc//test/cpp/util:grpc_cli failed to build

Full details and repro steps (including cloneable repository) here: https://github.com/nictuku/grpc-cli-bazel-test

**Comment by sreecha** [comment] 2018-08-16 18:17
I am closing this since the PR https://github.com/grpc/grpc/pull/13468 is closed

**Closed by sreecha** 2018-08-16 18:17 UTC
Labels: area/build, infra/Bazel, lang/c++, priority/P1
