### ISSUE TITLE
C#: Missing symbols for gRPC NuGet packages

### ISSUE THREAD

**Issue by smflorentino** [grpc/grpc#13851] opened 2017-12-21 03:53 UTC
The new default location for NuGet symbol packages, smbsrc.net, does not have any recent gRPC symbol packages. Following the instructions on https://tripleemcoder.com to view all symbol packages, we see most releases are missing.
`nuget list Grpc.Core -prerelease -allversions -source https://nuget.smbsrc.net/`

Result:
Grpc.Core 0.12.0-at-0JHZCS
Grpc.Core 0.13.0-at-0KZSUI
Grpc.Core 0.13.1-at-0NGHH3
Grpc.Core 0.13.1-pre-at-0NB0NJ
Grpc.Core 0.5.0-at-0CC5BJ
Grpc.Core 0.5.1-at-0CC5BN
Grpc.Core 0.6.0-at-0CC5BQ
Grpc.Core 0.6.1-at-0CC5BR
Grpc.Core 0.7.0-at-0G8UBW
Grpc.Core 0.7.1-at-0G91SC
Grpc.Core.Testing 1.2.0-at-15ONAR
Grpc.Core.Testing 1.2.0-at-16PQFH
Grpc.Core.Testing 1.2.0-pre1-at-15DM2Y
Grpc.Core.Testing 1.2.2-at-16GG6Y
Grpc.Core.Testing 1.2.2-at-16PQ7C

**Comment by jtattermusch** [comment] 2017-12-30 14:08
I think this is a dupe of https://github.com/grpc/grpc/issues/9521

**Closed by jtattermusch** 2017-12-30 14:08 UTC
