### ISSUE TITLE
Small flakiness appearing in C# test set: Grpc.Core.Tests.ClientServerTest

### ISSUE THREAD

**Issue by apolcyn** [grpc/grpc#12238] opened 2017-08-21 19:56 UTC
On current master (commit 71c468b566259a5ed18cf8e1f166bad7e4b878d9) running tests locally on linux, multiple tests in the `Grpc.Core.Tests.ClientServerTest` test set appear to flake with:

```
TearDown : System.AggregateException : One or more errors occurred.
  ----> System.Exception : Shutdown check: Detected 1 pending batch completions.
```

in about 1 out of 5000 runs (when run_tests.py is ran locally).

PR #11566 saw a failure in `StatusDetailIsUtf8` (https://grpc-testing.appspot.com/job/gRPC_pull_requests_macos/7475/), but a couple of other tests in that suite appear to flake with the same error at about the same frequency.

Failing tests (which all throw the exception above), appear to include:
* `Grpc.Core.Tests.ClientServerTest.ClientStreamingCall_CancelAfterBegin`
* `Grpc.Core.Tests.ClientServerTest.ServerCallContext_HostAndMethodPresent`
* `Grpc.Core.Tests.ClientServerTest.Channel_ConnectAsync`
* `Grpc.Core.Tests.ClientServerTest.StatusDetailIsUtf8`

This is reproduceable in linux with: `tools/run_tests/run_tests.py -l csharp -r ClientServerTest -n inf -a 20`

... leading to example test failure stack trace:

```
NUnitLite 3.6.0 (.NET 4.5)
Copyright (C) 2017 Charlie Poole

Runtime Environment
   OS Version: Unix 4.4.0.75
  CLR Version: 4.0.30319.42000

Test Files
    .../grpc/src/csharp/Grpc.Core.Tests/bin/Release/net45/Grpc.Core.Tests.exe

Test Filters
    Test: Grpc.Core.Tests.ClientServerTest

D0821 11:28:00.811392 Grpc.Core.Internal.UnmanagedLibrary Attempting to load native library ".../grpc/src/csharp/Grpc.Core.Tests/bin/Release/net45/libgrpc_csharp_ext.x64.so"
D0821 11:28:00.906247 Grpc.Core.Internal.NativeExtension gRPC native library loaded successfully.
I0821 11:28:00.907872 139749525104384 src/core/lib/iomgr/ev_epollsig_linux.c:71: epoll engine will be using signal: 40
D0821 11:28:00.907920 139749525104384 src/core/lib/iomgr/ev_posix.c:111: Using polling engine: epollsig
D0821 11:28:00.907982 139749525104384 src/core/ext/filters/client_channel/resolver/dns/native/dns_resolver.c:301: Using native dns resolver
=> Grpc.Core.Tests.ClientServerTest.AsyncUnaryCall_EchoMetadata
D0821 11:28:01.336006 139749525104384 src/core/lib/iomgr/ev_posix.c:111: Using polling engine: epollsig
D0821 11:28:01.336056 139749525104384 src/core/ext/filters/client_channel/resolver/dns/native/dns_resolver.c:301: Using native dns resolver
=> Grpc.Core.Tests.ClientServerTest.Channel_ConnectAsync
D0821 11:28:01.574981 139749525104384 src/core/lib/iomgr/ev_posix.c:111: Using polling engine: epollsig
D0821 11:28:01.575040 139749525104384 src/core/ext/filters/client_channel/resolver/dns/native/dns_resolver.c:301: Using native dns resolver
=> Grpc.Core.Tests.ClientServerTest.Channel_WaitForStateChangedAsync
D0821 11:28:01.855042 139749525104384 src/core/lib/iomgr/ev_posix.c:111: Using polling engine: epollsig
D0821 11:28:01.855093 139749525104384 src/core/ext/filters/client_channel/resolver/dns/native/dns_resolver.c:301: Using native dns resolver
=> Grpc.Core.Tests.ClientServerTest.ClientStreamingCall
D0821 11:28:02.330337 139749525104384 src/core/lib/iomgr/ev_posix.c:111: Using polling engine: epollsig
D0821 11:28:02.330420 139749525104384 src/core/ext/filters/client_channel/resolver/dns/native/dns_resolver.c:301: Using native dns resolver
W0821 11:28:02.525247 Grpc.Core.Server Exception while handling RPC. System.InvalidOperationException: Operation is not valid due to the current state of the object.
  at Grpc.Core.Utils.GrpcPreconditions.CheckState (Boolean condition) <0x41777d40 + 0x00027> in <filename unknown>:0 
  at Grpc.Core.Internal.AsyncCallServer`2[TRequest,TResponse].SendStatusFromServerAsync (Status status, Grpc.Core.Metadata trailers, System.Tuple`2 optionalWrite) <0x417816f0 + 0x00153> in <filename unknown>:0 
  at Grpc.Core.Internal.ClientStreamingServerCallHandler`2+<HandleCall>d__4[TRequest,TResponse].MoveNext () <0x4179b7c0 + 0x00953> in <filename unknown>:0 
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () <0x7f19f953a2a0 + 0x00029> in <filename unknown>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) <0x7f19f9538170 + 0x000a7> in <filename unknown>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) <0x7f19f95380f0 + 0x0006b> in <filename unknown>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) <0x7f19f95380a0 + 0x0003a> in <filename unknown>:0 
  at System.Runtime.CompilerServices.ConfiguredTaskAwaitable+ConfiguredTaskAwaiter.GetResult () <0x7f19f95386e0 + 0x00012> in <filename unknown>:0 
  at Grpc.Core.Server+<HandleCallAsync>d__39.MoveNext () <0x4177c560 + 0x003e5> in <filename unknown>:0 
=> Grpc.Core.Tests.ClientServerTest.ClientStreamingCall_CancelAfterBegin
D0821 11:28:02.591161 139749525104384 src/core/lib/iomgr/ev_posix.c:111: Using polling engine: epollsig
D0821 11:28:02.591216 139749525104384 src/core/ext/filters/client_channel/resolver/dns/native/dns_resolver.c:301: Using native dns resolver
W0821 11:28:02.720376 Grpc.Core.Server Exception while handling RPC. System.InvalidOperationException: Operation is not valid due to the current state of the object.
  at Grpc.Core.Utils.GrpcPreconditions.CheckState (Boolean condition) <0x41777d40 + 0x00027> in <filename unknown>:0 
  at Grpc.Core.Internal.AsyncCallServer`2[TRequest,TResponse].SendStatusFromServerAsync (Status status, Grpc.Core.Metadata trailers, System.Tuple`2 optionalWrite) <0x417816f0 + 0x00153> in <filename unknown>:0 
  at Grpc.Core.Internal.ClientStreamingServerCallHandler`2+<HandleCall>d__4[TRequest,TResponse].MoveNext () <0x4179b7c0 + 0x00953> in <filename unknown>:0 
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () <0x7f19f953a2a0 + 0x00029> in <filename unknown>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) <0x7f19f9538170 + 0x000a7> in <filename unknown>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) <0x7f19f95380f0 + 0x0006b> in <filename unknown>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) <0x7f19f95380a0 + 0x0003a> in <filename unknown>:0 
  at System.Runtime.CompilerServices.ConfiguredTaskAwaitable+ConfiguredTaskAwaiter.GetResult () <0x7f19f95386e0 + 0x00012> in <filename unknown>:0 
  at Grpc.Core.Server+<HandleCallAsync>d__39.MoveNext () <0x4177c560 + 0x003e5> in <filename unknown>:0 
=> Grpc.Core.Tests.ClientServerTest.ClientStreamingCall_ServerSideReadAfterCancelNotificationReturnsNull
D0821 11:28:02.796032 139749525104384 src/core/lib/iomgr/ev_posix.c:111: Using polling engine: epollsig
D0821 11:28:02.796089 139749525104384 src/core/ext/filters/client_channel/resolver/dns/native/dns_resolver.c:301: Using native dns resolver
=> Grpc.Core.Tests.ClientServerTest.DuplexStreamingCall
D0821 11:28:03.297268 139749525104384 src/core/lib/iomgr/ev_posix.c:111: Using polling engine: epollsig
D0821 11:28:03.297325 139749525104384 src/core/ext/filters/client_channel/resolver/dns/native/dns_resolver.c:301: Using native dns resolver
=> Grpc.Core.Tests.ClientServerTest.ServerCallContext_AuthContextNotPopulated
D0821 11:28:03.639099 139749525104384 src/core/lib/iomgr/ev_posix.c:111: Using polling engine: epollsig
D0821 11:28:03.639145 139749525104384 src/core/ext/filters/client_channel/resolver/dns/native/dns_resolver.c:301: Using native dns resolver
=> Grpc.Core.Tests.ClientServerTest.ServerCallContext_HostAndMethodPresent
D0821 11:28:03.990304 139749525104384 src/core/lib/iomgr/ev_posix.c:111: Using polling engine: epollsig
D0821 11:28:03.990361 139749525104384 src/core/ext/filters/client_channel/resolver/dns/native/dns_resolver.c:301: Using native dns resolver
=> Grpc.Core.Tests.ClientServerTest.ServerCallContext_PeerInfoPresent
D0821 11:28:04.447240 139749525104384 src/core/lib/iomgr/ev_posix.c:111: Using polling engine: epollsig
D0821 11:28:04.447283 139749525104384 src/core/ext/filters/client_channel/resolver/dns/native/dns_resolver.c:301: Using native dns resolver
=> Grpc.Core.Tests.ClientServerTest.ServerStreamingCall
D0821 11:28:04.721090 139749525104384 src/core/lib/iomgr/ev_posix.c:111: Using polling engine: epollsig
D0821 11:28:04.721148 139749525104384 src/core/ext/filters/client_channel/resolver/dns/native/dns_resolver.c:301: Using native dns resolver
=> Grpc.Core.Tests.ClientServerTest.ServerStreamingCall_EndOfStreamIsIdempotent
D0821 11:28:05.062373 139749525104384 src/core/lib/iomgr/ev_posix.c:111: Using polling engine: epollsig
D0821 11:28:05.062428 139749525104384 src/core/ext/filters/client_channel/resolver/dns/native/dns_resolver.c:301: Using native dns resolver
=> Grpc.Core.Tests.ClientServerTest.ServerStreamingCall_ErrorCanBeAwaitedTwice
D0821 11:28:05.414305 139749525104384 src/core/lib/iomgr/ev_posix.c:111: Using polling engine: epollsig
D0821 11:28:05.414369 139749525104384 src/core/ext/filters/client_channel/resolver/dns/native/dns_resolver.c:301: Using native dns resolver
=> Grpc.Core.Tests.ClientServerTest.ServerStreamingCall_TrailersFromMultipleSourcesGetConcatenated
D0821 11:28:05.627396 139749525104384 src/core/lib/iomgr/ev_posix.c:111: Using polling engine: epollsig
D0821 11:28:05.627444 139749525104384 src/core/ext/filters/client_channel/resolver/dns/native/dns_resolver.c:301: Using native dns resolver
=> Grpc.Core.Tests.ClientServerTest.StatusDetailIsUtf8
D0821 11:28:05.850840 139749525104384 src/core/lib/iomgr/ev_posix.c:111: Using polling engine: epollsig
D0821 11:28:05.850888 139749525104384 src/core/ext/filters/client_channel/resolver/dns/native/dns_resolver.c:301: Using native dns resolver
=> Grpc.Core.Tests.ClientServerTest.UnaryCall
D0821 11:28:06.076644 139749525104384 src/core/lib/iomgr/ev_posix.c:111: Using polling engine: epollsig
D0821 11:28:06.076690 139749525104384 src/core/ext/filters/client_channel/resolver/dns/native/dns_resolver.c:301: Using native dns resolver
=> Grpc.Core.Tests.ClientServerTest.UnaryCall_ServerHandlerSetsStatus
D0821 11:28:06.329645 139749525104384 src/core/lib/iomgr/ev_posix.c:111: Using polling engine: epollsig
D0821 11:28:06.329701 139749525104384 src/core/ext/filters/client_channel/resolver/dns/native/dns_resolver.c:301: Using native dns resolver
=> Grpc.Core.Tests.ClientServerTest.UnaryCall_ServerHandlerSetsStatusAndTrailers
D0821 11:28:06.629065 139749525104384 src/core/lib/iomgr/ev_posix.c:111: Using polling engine: epollsig
D0821 11:28:06.629145 139749525104384 src/core/ext/filters/client_channel/resolver/dns/native/dns_resolver.c:301: Using native dns resolver
W0821 11:28:06.723154 Grpc.Core.Internal.UnaryServerCallHandler`2 Exception occured in handler. System.Exception: This was thrown on purpose by a test
  at Grpc.Core.Tests.ClientServerTest+<>c.<UnaryCall_ServerHandlerThrows>b__7_0 (System.String request, Grpc.Core.ServerCallContext context) <0x417be580 + 0x0002b> in <filename unknown>:0 
  at Grpc.Core.Tests.MockServiceHelper.<.ctor>b__14_0 (System.String request, Grpc.Core.ServerCallContext context) <0x41781160 + 0x0002d> in <filename unknown>:0 
  at Grpc.Core.Internal.UnaryServerCallHandler`2+<HandleCall>d__4[TRequest,TResponse].MoveNext () <0x4177cee0 + 0x0072e> in <filename unknown>:0 
W0821 11:28:06.724422 Grpc.Core.Internal.UnaryServerCallHandler`2 Exception occured in handler. System.Exception: This was thrown on purpose by a test
  at Grpc.Core.Tests.ClientServerTest+<>c.<UnaryCall_ServerHandlerThrows>b__7_0 (System.String request, Grpc.Core.ServerCallContext context) <0x417be580 + 0x0002b> in <filename unknown>:0 
  at Grpc.Core.Tests.MockServiceHelper.<.ctor>b__14_0 (System.String request, Grpc.Core.ServerCallContext context) <0x41781160 + 0x0002d> in <filename unknown>:0 
  at Grpc.Core.Internal.UnaryServerCallHandler`2+<HandleCall>d__4[TRequest,TResponse].MoveNext () <0x4177cee0 + 0x0072e> in <filename unknown>:0 
=> Grpc.Core.Tests.ClientServerTest.UnaryCall_ServerHandlerThrows
D0821 11:28:06.783480 139749525104384 src/core/lib/iomgr/ev_posix.c:111: Using polling engine: epollsig
D0821 11:28:06.783534 139749525104384 src/core/ext/filters/client_channel/resolver/dns/native/dns_resolver.c:301: Using native dns resolver
=> Grpc.Core.Tests.ClientServerTest.UnaryCall_ServerHandlerThrowsRpcException
D0821 11:28:07.052962 139749525104384 src/core/lib/iomgr/ev_posix.c:111: Using polling engine: epollsig
D0821 11:28:07.053022 139749525104384 src/core/ext/filters/client_channel/resolver/dns/native/dns_resolver.c:301: Using native dns resolver
=> Grpc.Core.Tests.ClientServerTest.UnaryCall_ServerHandlerThrowsRpcExceptionWithTrailers
D0821 11:28:07.419834 139749525104384 src/core/lib/iomgr/ev_posix.c:111: Using polling engine: epollsig
D0821 11:28:07.419891 139749525104384 src/core/ext/filters/client_channel/resolver/dns/native/dns_resolver.c:301: Using native dns resolver
=> Grpc.Core.Tests.ClientServerTest.UnknownMethodHandler

Errors, Failures and Warnings

1) Error : Grpc.Core.Tests.ClientServerTest.StatusDetailIsUtf8
TearDown : System.AggregateException : One or more errors occurred.
  ----> System.Exception : Shutdown check: Detected 1 pending batch completions.
--TearDown
  at System.Threading.Tasks.Task.ThrowIfExceptional (Boolean includeTaskCanceledExceptions) <0x7f19f95db790 + 0x00037> in <filename unknown>:0 
  at System.Threading.Tasks.Task.Wait (Int32 millisecondsTimeout, CancellationToken cancellationToken) <0x7f19f95dce10 + 0x000c7> in <filename unknown>:0 
  at System.Threading.Tasks.Task.Wait () <0x7f19f95dcd00 + 0x00028> in <filename unknown>:0 
  at Grpc.Core.Tests.ClientServerTest.Cleanup () <0x4178b410 + 0x00052> in <filename unknown>:0 
  at (wrapper managed-to-native) System.Reflection.MonoMethod:InternalInvoke (System.Reflection.MonoMethod,object,object[],System.Exception&)
  at System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) <0x7f19f96ef2f0 + 0x000a1> in <filename unknown>:0 
--Exception
  at Grpc.Core.Internal.DebugStats.DebugWarning (System.String message) <0x417ba1b0 + 0x00043> in <filename unknown>:0 
  at Grpc.Core.Internal.DebugStats.CheckOK () <0x417912e0 + 0x00073> in <filename unknown>:0 
  at Grpc.Core.GrpcEnvironment+<ShutdownAsync>d__43.MoveNext () <0x41790000 + 0x005f3> in <filename unknown>:0 
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () <0x7f19f953a2a0 + 0x00029> in <filename unknown>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) <0x7f19f9538170 + 0x000a7> in <filename unknown>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) <0x7f19f95380f0 + 0x0006b> in <filename unknown>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) <0x7f19f95380a0 + 0x0003a> in <filename unknown>:0 
  at System.Runtime.CompilerServices.ConfiguredTaskAwaitable+ConfiguredTaskAwaiter.GetResult () <0x7f19f95386e0 + 0x00012> in <filename unknown>:0 
  at Grpc.Core.GrpcEnvironment+<ReleaseAsync>d__15.MoveNext () <0x4178c770 + 0x00414> in <filename unknown>:0 
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () <0x7f19f953a2a0 + 0x00029> in <filename unknown>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) <0x7f19f9538170 + 0x000a7> in <filename unknown>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) <0x7f19f95380f0 + 0x0006b> in <filename unknown>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) <0x7f19f95380a0 + 0x0003a> in <filename unknown>:0 
  at System.Runtime.CompilerServices.ConfiguredTaskAwaitable+ConfiguredTaskAwaiter.GetResult () <0x7f19f95386e0 + 0x00012> in <filename unknown>:0 
  at Grpc.Core.Server+<ShutdownInternalAsync>d__32.MoveNext () <0x4178d560 + 0x00784> in <filename unknown>:0 

Run Settings
    Number of Test Workers: 1
    Work Directory: .../grpc
    Internal Trace: Off

Test Run Summary
  Overall result: Failed
  Test Count: 22, Passed: 21, Failed: 1, Warnings: 0, Inconclusive: 0, Skipped: 0
    Failed Tests - Failures: 0, Errors: 1, Invalid: 0
  Start time: 2017-08-21 18:28:00Z
    End time: 2017-08-21 18:28:07Z
    Duration: 7.035 seconds

FAILED: csharp.Grpc.Core.Tests.ClientServerTest [ret=1, pid=131767]
```

**Comment by jtattermusch** [comment] 2017-08-24 14:51
Seen for csharp.Grpc.IntegrationTesting.GeneratedServiceBaseTest
https://sponge.corp.google.com/target?id=5add19b1-67fd-4938-a3cc-a6e2ca76e8a1&target=github/grpc/csharp_windows_dbg_native&searchFor=&show=FAILED&sortBy=STATUS

**Comment by jtattermusch** [comment] 2017-12-06 17:46
The problem seems to be:
```
1) Error : Grpc.Core.Tests.ClientServerTest.Channel_ConnectAsync
TearDown : System.AggregateException : One or more errors occurred.
  ----> System.Exception : Shutdown check: Detected 1 pending batch completions.
```
I am able to reproduce locally. Investigating.

**Comment by jtattermusch** [comment] 2017-12-07 15:40
It looks like this is what's happening:
1. channel is created, that immediately starts RunConnectivityWatcherAsync (which runs grpc_channel_watch_connectivity_state in a loop).
2. the test succeeds, 
3. as part of cleanup, the grpc_channel_shutdown is called, which immediately results in channel state change that wakes up RunConnectivityWatcherAsync, and that one immediately invokes 
grpc_channel_watch_connectivity_state which registers a completion in a cq. 
4. that completion gets never returned from cq.next(), even though cq will be shutdown shortly.

So this looks like some kind of race between invoking grpc_channel_shutdown and grpc_channel_watch_connectivity_state, that results in the watch_connectivity_state completion to never be returned from the cq.

**Comment by gnossen** [comment] 2021-04-21 14:38
Saw this again: https://source.cloud.google.com/results/invocations/159eda11-2d32-4ebc-8be4-054b0a47558f/targets/github%2Fgrpc%2Frun_tests%2Fcsharp_windows_opt_native_default_coreclr%2Fcsharp.Grpc.Core.Tests.ClientServerTest/tests

**Comment by jtattermusch** [comment] 2022-02-14 11:57
Occurrences in last 100 days:





1 | grpc/core/master/windows/grpc_basictests_csharp | 15454 | https://source.cloud.google.com/results/invocations/9ec3432c-4531-4f4d-8d73-120961cda180 | csharp.mono.Grpc.Core.Tests.ClientServerTest | csharp | windows | opt | default | native | FAILED | 2022-02-04 21:25:54 UTC | 3.53 | 1.0 | 1.0 | 1 |  
2 | grpc/core/master/windows/grpc_basictests_csharp | 15293 | https://source.cloud.google.com/results/invocations/bb4aa7a4-1cef-4c8d-abca-4d612ef5781a | csharp.mono.Grpc.Core.Tests.ClientServerTest | csharp | windows | opt | default | native | FAILED | 2022-01-26 13:38:43 UTC | 3.2 | 1.0 | 1.0 | 1 |  
3 | grpc/core/master/windows/grpc_basictests_csharp | 15260 | https://source.cloud.google.com/results/invocations/407f00cb-9fc7-473d-8773-fe08772fcc48 | csharp.coreclr.Grpc.Core.Tests.ClientServerTest | csharp | windows | dbg | default | native | FAILED | 2022-01-25 09:40:41 UTC | 0.91 | 1.0 | 1.0 | 19 |  
4 | grpc/core/master/linux/grpc_basictests_csharp | 15031 | https://source.cloud.google.com/results/invocations/8d8b82dd-acd8-421c-84b2-0acbe3bb2df7 | csharp.Grpc.Core.Tests.ClientServerTest | csharp | linux | opt | coreclr | native | FAILED | 2021-12-03 07:16:24 UTC | 35.33 | 1.0 | 1.0 | 1

<br class="Apple-interchange-newline">

**Comment by jtattermusch** [comment] 2022-04-06 11:44
Closing in favor of b/228296470 (we're going to track test flakiness in buganizer going forward).

**Closed by jtattermusch** 2022-04-06 11:44 UTC
Labels: kind/bug, lang/C#, disposition/BUILDNURSE, toolchain/.NET Core
