### ISSUE TITLE
py files placed in wrong path by grpcio-tools when parent path has '.'

### ISSUE THREAD

**Issue by godsarmy** [grpc/grpc#17762] opened 2019-01-18 15:00 UTC
### What version of gRPC and what language are you using?
 
python 1.18.0
 
### What operating system (Linux, Windows, …) and version?
 
Linux
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
 
python 2.7.10

### What did you do?
If possible, provide a recipe for reproducing the error. Try being specific and include code snippets if helpful.

I am trying to create python library for containerd

```
$ python -m grpc_tools.protoc -I vendor/github.com/gogo/protobuf/ -I vendor --python_out=python --grpc_python_out=python vendor/github.com/containerd/containerd/api/services/tasks/v1/tasks.proto

$ ls python/github.com/containerd/containerd/api/services/tasks/v1/tasks_pb2_grpc.py
python/github.com/containerd/containerd/api/services/tasks/v1/tasks_pb2_grpc.py

$ ls python/github/com/containerd/containerd/api/services/tasks/v1/tasks_pb2.py
python/github/com/containerd/containerd/api/services/tasks/v1/tasks_pb2.py
```

 
### What did you expect to see?

i would expect to see both pb2.py and pb2_grpc.py created in the same path github/com

### What did you see instead?
 
see tasks_pb2.py was created in github/com while tasks_pb2_grpc.py was created in github.com

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

See https://github.com/grpc/grpc/blob/master/TROUBLESHOOTING.md for how to diagnose problems better.

**Comment by gnossen** [comment] 2019-01-18 18:20
Looks like a duplicate of https://github.com/grpc/grpc/issues/10790. Moving discussion to that thread

**Closed by gnossen** 2019-01-18 18:20 UTC
Labels: area/protoc plugins, kind/bug, lang/Python
