### ISSUE TITLE
INVALID_ARGUMENT "Log entry with size 549.3K exceeds maximum size of 256.0K"

### ISSUE THREAD

**Issue by ayyoubelamrani4** [grpc/grpc#32983] opened 2023-05-02 16:57 UTC
### What version of gRPC and what language are you using?

grpcio==1.54.0

### What operating system (Linux, Windows,...) and version?

PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"

### What runtime / compiler are you using (e.g. python version or version of GCC)

python 3.11

### What did you do?

Not sure how to reproduce it, it just appears from nowhere in the Kubernetes logs.

### What did you expect to see?

No error

### What did you see instead?

`debug_error_string = "UNKNOWN:Error received from peer ipv4:###### {created_time:"2023-05-02T15:51:18.651402661+00:00", grpc_status:3, grpc_message:"Log entry with size 549.3K exceeds maximum size of 256.0K"}"`

### Anything else we should know about your project / environment?

Django framework with GCP logging.

**Comment by XuanWang-Amos** [comment] 2023-08-24 19:40
Looks like the maximum value for a GCP log entry is 256K: https://cloud.google.com/logging/quotas

You might need to reduce the size of the object you're logging.

Since it's expected behavior, I'm closing this issue, please let us know if you need other help.

**Closed by XuanWang-Amos** 2023-08-24 19:40 UTC
Labels: kind/bug, lang/Python, priority/P2
