### ISSUE TITLE
Memory leak in GRPC python client!

### ISSUE THREAD

**Issue by zj8487** [grpc/grpc#6619] opened 2016-05-17 10:40 UTC
Hi, all,
I use grpc python client (0.13 or 0.14version) with golang server. and I found the memory of python client will grow and grow.

 [The demo](https://github.com/zj8487/helloworld) show how i use grpc client.

And only thing you need do is run the server, client and watching the memory of the client progress.

several hours will needed. and the memory of python client will grow without decrese

**Comment by zj8487** [comment] 2016-05-17 10:41
@nathanielmanistaatgoogle

**Comment by nathanielmanistaatgoogle** [comment] 2016-05-17 15:25
Thank you for the report! Marking this a duplicate of [issue 5913](https://github.com/grpc/grpc/issues/5913).

We're working on some pretty dramatic improvements to gRPC Python that should land in the next few weeks.

**Comment by zj8487** [comment] 2016-05-18 00:57
@nathanielmanistaatgoogle thanks for your response, but i saw the mentioned issue only indicates the memory leak on server side. Are you sure the memory leak on client side is also working?

**Comment by nathanielmanistaatgoogle** [comment] 2016-06-15 03:27
For anyone else stumbling across this: the defect identified here was fixed in [pull request 6711](https://github.com/grpc/grpc/pull/6711).

**Comment by zj8487** [comment] 2016-06-15 08:48
great done

**Comment by zj8487** [comment] 2016-07-01 02:47
Hi, @nathanielmanistaatgoogle ,

I use grpcio(0.15.0). and I found the memory of python client will still grow and grow.

 [The demo](https://github.com/zj8487/helloworld) show how i use grpc.

**Comment by nathanielmanistaatgoogle** [comment] 2016-07-02 11:15
@zj8487: your demo at [this point](https://github.com/zj8487/helloworld/tree/7e6a1c595f96373ecb35790016a1f7211a2e4d6e) seems pretty complicated - are you able to strip any of it away and still maintain demonstration of unbounded memory growth? Also are you able to do any Python-level analysis of what is residing in the memory that is being leaked? What kinds of Python objects, if it is Python objects that are being leaked?

**Comment by zj8487** [comment] 2016-07-02 11:38
@nathanielmanistaatgoogle 
Thanks your response, I will strip the demo and do some Python-level analysis and the post it here this weekend

**Comment by zj8487** [comment] 2016-07-03 13:20
@nathanielmanistaatgoogle   [The demo](https://github.com/zj8487/helloworld) is updated.


**The output indicates the memory of client is growing slowly.**


The memory of the process of the **begin time** is shown as follow:
![1_meitu_1](https://cloud.githubusercontent.com/assets/5138447/16545658/b5236530-4163-11e6-89bb-d0d6a6a88d36.jpg)


The memory of the process of the **end time** is shown as follow:
![2_meitu_2](https://cloud.githubusercontent.com/assets/5138447/16545299/56a99ef2-4159-11e6-87a1-f9bd2439447d.jpg)


**But the python objects of the process show there is no python object leak**

The python objects of the process at the **begin time** as follow:
```
_The gc infomation when request count is 170000_
gc: collecting generation 0...
gc: objects in each generation: 13725 72 23009
gc: done, 0.0021s elapsed.
gc: collecting generation 0...
gc: objects in each generation: 4296 10322 23009
gc: done, 0.0008s elapsed.
gc: collecting generation 0...
gc: objects in each generation: 839 14600 23009
gc: done, 0.0002s elapsed.
```

The python objects of the process at the **end time** as follow:
```
_The gc infomation when request count is 21610000_
gc: collecting generation 0...
gc: objects in each generation: 4023 0 23009
gc: done, 0.0030s elapsed.
gc: collecting generation 0...
gc: objects in each generation: 4414 0 23009
gc: done, 0.0020s elapsed.
gc: collecting generation 0...
gc: objects in each generation: 4239 0 23009
gc: done, 0.0011s elapsed.
gc: collecting generation 0...
```

**Comment by nathanielmanistaatgoogle** [comment] 2016-07-03 14:31
@zj8487: thank you for your investigation. What version of Python are you using?

In your code I notice that you're using [`stub.SayHello.future(<arguments>)`](https://github.com/zj8487/helloworld/blob/5d872ba47f57a337381d0a5ee076d1e68412e86f/greeter_client.py#L71) to make asynchronous requests - is this necessary for demonstrating the memory leak or can it be changed? If you change that line to `ignored_response = stub.SayHello(<arguments>)`, does the memory leak continue to manifest?

Also I notice that [your callback](https://github.com/zj8487/helloworld/blob/5d872ba47f57a337381d0a5ee076d1e68412e86f/greeter_client.py#L52) doesn't seem to print anything, but it does call a few methods on the `Future` object passed to it (`code`, `exception`, and `result`). Are these calls part of demonstrating the memory leak? What happens if you change the body of your callback to just `pass`?

Have you tried reproducing the leak using the (new) [GA API](https://github.com/grpc/grpc/blob/release-0_15/src/python/grpcio/grpc/__init__.py)? You may have to rerun the code generator to produce a helloworld_pb2.py that includes the non-`beta` classes and functions.

**Comment by zj8487** [comment] 2016-07-04 01:15
@nathanielmanistaatgoogle :Thank you for your response.

**What version of Python are you using?**
```
python2.7.x
```
**Dose synchronous requests leak?**
```
I tried the synchronous requests yesterday, and i did not notice the memory grow.
```
**Why did not print something in the callback? **
```
just not want some useless output
```

**Have you tried reproducing the leak using the (new) GA API?**
```
Not yet, i will try it today.
```
**What happens if you change the body of your callback to just pass?**
```
I will try today!
```

**Comment by zj8487** [comment] 2016-07-04 02:07
**Have you tried reproducing the leak using the (new) GA API?**
```
I notice that the client side just use ```insecure_channel```.
and i use it with GA interface. and the momory still grow.

```

**Comment by nathanielmanistaatgoogle** [comment] 2016-07-04 04:09
[This pull request](https://github.com/grpc/grpc/pull/7177) shows how to generate a new helloworld_pb2.py. Make sure you have the latest [grpcio](https://pypi.python.org/pypi/grpcio) and [grpcio-tools](https://pypi.python.org/pypi/grpcio-tools) installed in your Python environment.

**Comment by zj8487** [comment] 2016-07-04 06:37
I update **the client to use the GA API** and notice two things:

1.  The memory of client is still growing.

2. If the server raise error, the memory of client grows more quickly

```
class Greeter(helloworld_pb2.BetaGreeterServicer):

    def SayHello(self, request, context):
        raise NameError("test err1111111111111111")
```

**Comment by nathanielmanistaatgoogle** [comment] 2016-07-04 06:56
[I'm not yet seeing your latest code](https://github.com/zj8487/helloworld/blob/master/greeter_client.py)?

**Comment by zj8487** [comment] 2016-07-04 07:09
I will update to right now

**Comment by nathanielmanistaatgoogle** [comment] 2016-07-04 07:50
Let's keep working toward the smallest possible code that demonstrates the defect. If the defect still manifests when the body of your callback is reduced to just "pass", go ahead and reduce the body of your callback to just "pass". If you eliminate adding the callback to the future, does the leak still take place? Timeouts are not required in the GA API - if you eliminate passing a timeout, does the leak still take place?

**Comment by zj8487** [comment] 2016-07-04 08:39
@nathanielmanistaatgoogle

timeout is eliminated for all the following test

case 1: ```The body of your callback is reduced to just pass```
**the memory is growing**

```
def grpc_done_cb(future_response):
    pass


def run():
    channel = insecure_channel('localhost:50051')
    stub = helloworld_pb2.GreeterStub(channel)
    counter = 1
    while True:
        response = stub.SayHello.future(helloworld_pb2.HelloRequest(name='you'))
        response.add_done_callback(grpc_done_cb)
        time.sleep(0.0004)
        counter += 1
        if counter % 10000 == 0:
            print("============================================================Print the request count:", counter)
```

case 2: ```Eliminate adding the callback to the future```
**the memory is not growing**

```
def run():
    channel = insecure_channel('localhost:50051')
    stub = helloworld_pb2.GreeterStub(channel)
    counter = 1
    while True:
        response = stub.SayHello.future(helloworld_pb2.HelloRequest(name='you'))
        time.sleep(0.0004)
        counter += 1
        if counter % 10000 == 0:
            print("============================================================Print the request count:", counter)

```

**Comment by nathanielmanistaatgoogle** [comment] 2016-07-04 08:43
What's the rate of memory leak in bytes/second? Does the code you just posted demonstrate the fastest leak?

**Comment by zj8487** [comment] 2016-07-04 08:54
all the following test is based on ```The body of callback is reduced to just pass```

case 1: The server's method raise a error
**nearly 3072bytes per 30 second**
```
class Greeter(helloworld_pb2.BetaGreeterServicer):

    def SayHello(self, request, context):
        raise NameError("test err1111111111111111")

```
case 2: The server's method return normally
**can not  notice a memory growing in a short time. maybe it need a long time to check**
```
class Greeter(helloworld_pb2.BetaGreeterServicer):

    def SayHello(self, request, context):
        #raise NameError("test err1111111111111111")
        return helloworld_pb2.HelloReply(message='Hello, %s!' % request.name)
```

**Comment by nathanielmanistaatgoogle** [comment] 2016-07-04 09:18
What's with the `sleep` in your code? Is that critical to demonstrating the leak?

**Comment by zj8487** [comment] 2016-07-04 09:19
it is just want to control the speed of request.

**Comment by nathanielmanistaatgoogle** [comment] 2016-07-04 09:21
Can you increase the rate of leak by lowering the sleep time?

**Comment by zj8487** [comment] 2016-07-04 09:23
Now i am test the case ``` The server's method return normally based on the body of callback is reduced to just pass```

I will test it several hours later for a short sleep time

**Comment by nathanielmanistaatgoogle** [comment] 2016-07-04 09:48
If you change `'you'` to `'you'*100000`, does the rate of leak increase?

**Comment by zj8487** [comment] 2016-07-04 09:52
I will test it several hours later too

**Comment by zj8487** [comment] 2016-07-04 10:01
All the following test is based on ```The body of callback is reduced to just pass```

case 1: The server's method raise a error
**The speed of memory grow more quick if the error string is more longer**
```
class Greeter(helloworld_pb2.BetaGreeterServicer):

    def SayHello(self, request, context):
        raise NameError("test err1111111111111111")

```
case 2: The server's method return normally
**The speed of memory grow more quick if the message is more longer**
```
class Greeter(helloworld_pb2.BetaGreeterServicer):

    def SayHello(self, request, context):
        return helloworld_pb2.HelloReply(message='Hello, %s!' % request.name)
```


@nathanielmanistaatgoogle 
still need test the case: ```lowering the sleep time ```?

**Comment by zj8487** [comment] 2016-07-04 10:05
another issue:```Ctrl + C``` can not make the client to exit

```
Traceback (most recent call last):
  File "greeter_client.py", line 70, in <module>
    run()
  File "greeter_client.py", line 61, in run
    response = stub.SayHello.future(helloworld_pb2.HelloRequest(name='you'))
  File "/home/jian/.virtualenvs/landlord/local/lib/python2.7/site-packages/grpc/_channel.py", line 477, in future
    request, timeout, metadata)
  File "/home/jian/.virtualenvs/landlord/local/lib/python2.7/site-packages/grpc/_channel.py", line 440, in _prepare
    state = _RPCState(_UNARY_UNARY_INITIAL_DUE, None, None, None, None)
  File "/home/jian/.virtualenvs/landlord/local/lib/python2.7/site-packages/grpc/_channel.py", line 109, in __init__
    self.due = set(due)
KeyboardInterrupt
^C^CE0704 17:57:48.988460597   29195 chttp2_transport.c:1810]    close_transport: {"created":"@1467626268.959884871","description":"Failed parsing HTTP/2","file":"src/core/ext/transport/chttp2/transport/chttp2_transport.c","file_line":1726,"referenced_errors":[{"created":"@1467626268.959881826","description":"EOF","file":"src/core/lib/iomgr/tcp_posix.c","file_line":233}]}
^C^C^C

```

**Comment by nathanielmanistaatgoogle** [comment] 2016-07-04 10:10
I'm able to reproduce the leak with no `sleep` at all, so no need to experiment with varying values for the sleep.

I've just noticed that the server's memory is also growing, though not as rapidly as the client's.

If you're able to work from source [the `Ctrl-C` issue is fixed there](https://github.com/grpc/grpc/issues/3820).

**Comment by soltanmm** [comment] 2016-07-05 02:13
I can't do this at the moment (and may not try it tomorrow - kinda sick), but: it might be worth inspecting the `gc` module to see which Python/Cython types are leaking and who owns the leaked instances (reference cycle vs. dangling root, if it's the Cython `Buffer` type then who's holding on, etc.).

**Comment by pgrosu** [comment] 2016-07-05 03:02
Sorry to hear you're not feeling well Masood, and hope you'll get better soon.

~p

**Comment by zj8487** [comment] 2016-07-08 08:31
Is there any plan to release a version for the issue recently?

**Comment by zj8487** [comment] 2016-07-12 01:42
any progress on this issue?

**Comment by nathanielmanistaatgoogle** [comment] 2016-07-12 17:48
@kpayson64, @soltanmm: running [this module](https://github.com/nathanielmanistaatgoogle/grpc/blob/3ce379d21cce3fadcc916623518ab1492002de35/leak.py) demonstrates the leak - either of you want to take over from here? Given that the leak rate scales with the size of the request object used, I strongly suspect we're looking for leaked request data.

**Comment by kpayson64** [comment] 2016-07-12 17:51
@nathanielmanistaatgoogle 
I can look into this one.

**Comment by soltanmm** [comment] 2016-07-13 00:22
@kpayson64 Just decided to take a quick shallow pass. [Here's some stuff that came out of it.](https://github.com/grpc/grpc/files/360474/leak.zip)

It's that `gc` thing I mentioned earlier; it shows that we're at least leaking `OperationTag`s, which IIRC are supposed to be *roots* in our (supposedly) DAG of references. Didn't look into it in much depth, though.

**Comment by kpayson64** [comment] 2016-07-13 01:00
@soltanmm @nathanielmanistaatgoogle 
I think this example is behaving as intended.  The allocated memory we see between iterations is needed, we cannot possibly free our request/metadata until the call completes because it is used by the c-core.

In the loop, if we change
```
response_future = multi_callable.future(request)
response_future.add_done_callback(_callback)
```

to 
```
response_future = multi_callable.future(request)
response_future.add_done_callback(_callback)
response_future.result()
```

The leak is gone.  I think the memory leak issue is just a result of creating requests far faster than they can be serviced, which is an application and not grpc issue.

**Comment by soltanmm** [comment] 2016-07-13 01:07
Then I'd expect that if you replaced the `response_future.result()` with a `time.sleep()` of sufficient duration the symptoms of a leak would disappear... (can't check now)

**Comment by nathanielmanistaatgoogle** [comment] 2016-07-13 01:09
@kpayson64: I'm open to counterargument, and I haven't yet looked at the output of what @soltanmm posted, but my thinking was that since the `response_future` is reassigned in each iteration of the loop, the garbage collector should deallocate the previous loop iteration's value (and thus cancel its RPC and free all its memory) before assigning the current loop iteration's value to the local field (or perhaps a few Python interpreter instructions later). Now as you may have heard me remark in the office yesterday: I no longer speak with confidence about Python memory semantics. What mistake am I making in telling that story?

**Comment by soltanmm** [comment] 2016-07-13 01:12
That was only a note of what I'd expect would validate/nullify the hypothesis that it's an application error in the rate of service. :-/

**Comment by kpayson64** [comment] 2016-07-13 01:18
@soltanmm 
```time.sleep(0.005)``` Seems to keep the memory stable at 1%

@nathanielmanistaatgoogle 
That's the direction I would like to go, but currently we track all our managed calls.  Its should be possible to remove this state tracking though, similar to what was done in #7157

**Comment by nathanielmanistaatgoogle** [comment] 2016-07-13 01:23
@kpayson64: agreed. Let's toss some logging into demonstration to see the size of the call management tracking?

**Comment by zj8487** [comment] 2016-07-13 01:23
Hi, all
I do not agree with the leak is triggered by a rapid call.
in fact, the frequency of call in my product is very slow. but the  memory will grow dramaticlly in a daily period.

**Comment by kpayson64** [comment] 2016-07-13 02:06
@zj8487 
In the example you provided, the sleep period was 0.0004 seconds.  Are you able to reproduce the issue with the example code over a long period of time with a sleep period of 0.01 seconds?

**Comment by soltanmm** [comment] 2016-07-13 02:12
@kpayson64 I guess I'm convinced that the `leak.py` code may not demonstrate a leak from the sleep results, but I tried adding `response_future.result()` and found that the process hung rather than looped (which I guess is expected given infinite timeout).

**Comment by zj8487** [comment] 2016-07-13 02:24
@kpayson64
I will try the example with a sleep period was 0.1 seconds with several days for a watch. and it will begin in later of today.

**Comment by zj8487** [comment] 2016-07-18 03:15
@kpayson64 
I tried the test with ```with a sleep period was 0.1 seconds with several days for a watch``` and i did not noticed a memory leak util now.

**Comment by zj8487** [comment] 2016-07-19 02:52
Hi all,
the memory is grow in my production, and i finally find the difference with the demo i write here.
the key difference is i used ```channel.subscribe(connectivity_update, try_to_connect=True)``` in my production

and i updated the [demo](https://github.com/zj8487/helloworld) 
```
     channel = insecure_channel('localhost:50051')
     channel.subscribe(connectivity_update, try_to_connect=True) # added for reproduce the leak
```

**Comment by zj8487** [comment] 2016-07-19 02:52
@nathanielmanistaatgoogle @kpayson64

**Comment by kpayson64** [comment] 2016-07-19 17:07
@zj8487 
I was able to verify that there is a leak with a sleep period of 0.1 seconds.  I'll need to investigate further.

**Comment by hsaliak** [comment] 2016-07-28 21:39
@kpayson64 have you had a chance to dig into this further?

**Comment by kpayson64** [comment] 2016-07-28 21:56
@hsaliak  Not really.  This seems like a really subtle memory leak, so I was planning on building a valgrind compatible Python to get to the bottom of it but I haven't had a chance.  I can re-prioritize if this feels like a GA bug.

**Comment by nathanielmanistaatgoogle** [comment] 2017-01-18 19:46
Punting; I don't see any reason to block `1.1.0` on resolving this.

This seems like it could also use reassessment. @zj8487, are you still seeing this leak? Are you still able to reproduce it with the most-recently-released `grpcio`?

**Comment by zj8487** [comment] 2017-01-19 08:06
@nathanielmanistaatgoogle yes i can, but i can only schedule the test at the bottom of the month!

**Comment by zj8487** [comment] 2017-02-04 09:48
***env***
1, grpcio version:1.1.0 from pip install grpcio

2, All the following test is based on the [demo](https://github.com/zj8487/helloworld) 
 and changes: ```'you' to 'you'*100000```

3, test on mac. i do not have the env of ubuntu now

***case 1: The server's method raise a error***
**not saw memory leak**

```
class Greeter(helloworld_pb2.BetaGreeterServicer):

    def SayHello(self, request, context):
        raise NameError("test err1111111111111111")

```

***case 2: The server's method return normally***
**not saw memory leak**

```
class Greeter(helloworld_pb2.BetaGreeterServicer):

    def SayHello(self, request, context):
        return helloworld_pb2.HelloReply(message='Hello, %s!' % request.name)
```

**Comment by kpayson64** [comment] 2017-02-06 20:18
@zj8487 
This is great!  It sounds like we can close out this issue then?

**Comment by zj8487** [comment] 2017-02-07 06:42
@kpayson64 maybe it is. The memory usage is stable now with the [demo](https://github.com/zj8487/helloworld)!

**Closed** 2017-03-06 17:38 UTC
Labels: bug, python
