### ISSUE TITLE
Hello World C++ client "hangs" with invalid hostname

### ISSUE THREAD

**Issue by ericgribkoff** [grpc/grpc#14187] opened 2018-01-25 23:35 UTC
If you modify the gRPC "Hello World" `greeter_client.cc` client to point to a non-existent hostname and then run it, the user experience is that gRPC "hangs". Turning on `GRPC_VERBOSITY=DEBUG`, we see that the DNS resolver is in the expected backoff state and continues to retry (for a long time, maybe forever?) but the blocking stub's `SayHello` method does not return. From the discussion on #13627, this might indeed be the correct behavior, but for a user trying out gRPC for the first time who makes a typo in their hostname, the user experience is not so great - gRPC seems to have gotten stuck.

The answer might be simply that the examples should have a deadline set, but given the discussion in #13627 seems to be ongoing in regard to the correct behavior for `wait_for_ready=false` RPCs when DNS resolution fails, I wanted to get some feedback on this. (It's also the case that the C++ examples have localhost hard-coded, so maybe DNS resolution can't really fail, but the same issue comes up with e.g. our interop test client)

cc @markdroth

**Comment by markdroth** [comment] 2018-01-25 23:42
Duplicate of #13627.

**Closed by markdroth** 2018-01-25 23:42 UTC
