### ISSUE TITLE
Google.Protobuf.Tools and Grpc.Tools proto compilation is only supported by default in a C# project (extension .csproj)

### ISSUE THREAD

**Issue by jozefizso** [grpc/grpc#20515] opened 2019-10-07 19:47 UTC
### What version of gRPC and what language are you using?
grpc 1.18.0

### What operating system (Linux, Windows,...) and version?
Windows

### What runtime / compiler are you using (e.g. python version or version of gcc)
.NET Framework 4.7.2  
Grpc.Tools 1.18.0

### What did you do?
When I open .NET project in VS 2017 and/or 2019 and I run build, Grpc.Tools often reports this error: **Google.Protobuf.Tools proto compilation is only supported by default in a C# project (extension .csproj)**

This error is mostly reported on a project which was recently checked out and it's nuget packages are missing. After restoring packages and running build, msbuild will likely report this error.

When I run **Build** > **Build Solution** several times in a row, the project finally build correctly. As I change the **.proto** file in the project and run **Build** again, I got the error message again.

This causes issues with build machines which do clean builds and are thus failing the build. And it causes to developers as they local builds are often reported as failed.

### What did you expect to see?
Project should build correctly.

### What did you see instead?

msbuild error: **Google.Protobuf.Tools proto compilation is only supported by default in a C# project (extension .csproj)**

Full build log: https://gist.github.com/jozefizso/383d6d1346a0ffcd8dde5e5955384070

**Comment by jozefizso** [comment] 2019-10-07 19:57
Moved to https://github.com/protocolbuffers/protobuf/issues/6740 as it seams more appropriate place for this issue.

**Comment by jtattermusch** [comment] 2019-10-14 07:05
Looks like this is impacting Grpc.Tools as well: https://github.com/protocolbuffers/protobuf/issues/6740#issuecomment-539180466

**Comment by jtattermusch** [comment] 2020-04-30 12:47
I can actually reproduce this issue with VS2019 by getting a clean checkout of the helloworld example in a "classic" csproj: 

1 get a clean checkout of https://github.com/grpc/grpc/tree/master/examples/csharp/HelloworldLegacyCsproj
2. open https://github.com/grpc/grpc/blob/master/examples/csharp/HelloworldLegacyCsproj/Greeter.sln in VS2019
3. click "Build solution", I get the error `Google.Protobuf.Tools proto compilation is only supported by default in a C# project (extension .csproj)`

As described above, after a few rebuild attempts this problem goes away by itself and I can build just fine from that moment onward. (I can even clean and rebuild and things just continue working fine)

I don't know what's causing the problem and it almost looks like a VS or msbuild bug. 
The problem doesn't affect the new dotnet-style projects so I don't think it's realistic to expect that this it's going to be fixed.
The workaround is just to wait a few minutes / attempts until the builds starts working normally.

**Comment by jtattermusch** [comment] 2020-04-30 12:51
Btw, the actual error message is coming from here: https://github.com/grpc/grpc/blob/b179868110bc9f771aec1c2f44951f1e9c713ac4/src/csharp/Grpc.Tools/build/_protobuf/Google.Protobuf.Tools.targets#L53

**Comment by jtattermusch** [comment] 2020-05-15 18:35
One possible workaround is to add 
```
<PropertyGroup>
    <Protobuf_Generator>CSharp</Protobuf_Generator>
</PropertyGroup>
```
to your csproj file to force using the C# generator (and to silence the warning). Feel free to try that and report back if that worked.

**Comment by jtattermusch** [comment] 2020-05-18 15:23
Closing this a I suspect a msbuild bug, it only affect the legacy .csproj projects and there is a know workaround (the build starts working after a few retries).

**Closed by jtattermusch** 2020-05-18 15:23 UTC
Labels: kind/bug, lang/C#, priority/P2

**Comment by NeverMorewd** [comment] 2023-03-28 10:03
> One possible workaround is to add
> 
> ```
> <PropertyGroup>
>     <Protobuf_Generator>CSharp</Protobuf_Generator>
> </PropertyGroup>
> ```
> 
> to your csproj file to force using the C# generator (and to silence the warning). Feel free to try that and report back if it worked.

Did not work for me.But I found a workaround is to reload the project.
