### ISSUE TITLE
Updating grpc ruby gem to use google-protobuf v3.5

### ISSUE THREAD

**Issue by coolguru** [grpc/grpc#15187] opened 2018-04-25 18:56 UTC
Please answer these questions before submitting your issue. 
 
### Should this be an issue in the gRPC issue tracker?
Yes
 
### What version of gRPC and what language are you using?
 v1.11.0

**Comment by apolcyn** [comment] 2018-04-26 06:49
@coolguru you can you grpc with `google-protobuf` 3.5.x.

grpc has a dependency on `google-protobuf ~> 3.1`, allowing it to pick up any `google-protobuf` package from 3.1 and up to but not including the (not yet present) 4.0.

Closing since I believe there's no issue, please reopen if the problem is something different.

**Closed by apolcyn** 2018-04-26 06:49 UTC
Labels: lang/ruby
