### ISSUE TITLE
FLAKE: csharp_macos_opt_native

### ISSUE THREAD

**Issue by adelez** [grpc/grpc#12940] opened 2017-10-10 21:56 UTC
https://sponge.corp.google.com/target?id=a1d076cd-f8a7-49f1-9bac-32147796f008&target=github/grpc/csharp_macos_dbg_native&searchFor=&show=FAILED&sortBy=STATUS

Failures were caused by
Expected: 9999-12-31 23:59:59.9999999
  But was:  2017-11-04 15:55:14.1342021

**Comment by jtattermusch** [comment] 2017-10-11 06:30
Dupe of https://github.com/grpc/grpc/issues/12931

**Closed by jtattermusch** 2017-10-11 06:30 UTC
