### ISSUE TITLE
Windows shared build failed

### ISSUE THREAD

**Issue by hongnod** [grpc/grpc#22576] opened 2020-04-03 14:18 UTC
### What version of gRPC and what language are you using?
v1.28.x C++
### What operating system (Linux, Windows,...) and version?
Windows10 1909

### What runtime / compiler are you using (e.g. python version or version of gcc)
vs2019 16.5.1/16.5.2
### What did you do?
 Try to build and install gRPC
 1、Static build  with： cmake ..\.. -GNinja -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX =A/B/C/static
 2、Shared build with：  cmake ..\.. -GNinja -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=ON -DCMAKE_INSTALL_PREFIX =A/B/C/shared

### What did you expect to see?
 Both build with success

### What did you see instead?
1、static build success
2、share build failed with error
Errors are：
CMake Error: install(EXPORT "gRPCTargets" ...) includes target "absl_bad_optional_access" which requires target "abseil_dll" that is not in any export set.
CMake Error: install(EXPORT "gRPCTargets" ...) includes target "absl_base" which requires target "abseil_dll" that is not in any export set.
CMake Error: install(EXPORT "gRPCTargets" ...) includes target "absl_int128" which requires target "abseil_dll" that is not in any export set.
CMake Error: install(EXPORT "gRPCTargets" ...) includes target "absl_log_severity" which requires target "abseil_dll" that is not in any export set.
CMake Error: install(EXPORT "gRPCTargets" ...) includes target "absl_raw_logging_internal" which requires target "abseil_dll" that is not in any export set.
CMake Error: install(EXPORT "gRPCTargets" ...) includes target "absl_spinlock_wait" which requires target "abseil_dll" that is not in any export set.
CMake Error: install(EXPORT "gRPCTargets" ...) includes target "absl_str_format_internal" which requires target "abseil_dll" that is not in any export set.
CMake Error: install(EXPORT "gRPCTargets" ...) includes target "absl_strings" which requires target "abseil_dll" that is not in any export set.
CMake Error: install(EXPORT "gRPCTargets" ...) includes target "absl_strings_internal" which requires target "abseil_dll" that is not in any export set.
CMake Error: install(EXPORT "gRPCTargets" ...) includes target "absl_throw_delegate" which requires target "abseil_dll" that is not in any export set.
-- Generating done
CMake Generate step failed.  Build files cannot be regenerated correctly.
Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

See [TROUBLESHOOTING.md](https://github.com/grpc/grpc/blob/master/TROUBLESHOOTING.md) for how to diagnose problems better.

### Anything else we should know about your project / environment?
none

**Comment by Jacob-Matchuny** [comment] 2020-05-15 13:56
I'm also having the same issue. Is this caused by not adding `abseil_dll` to `gRPC_ABSL_USED_TARGETS`? @nicolasnoble

**Comment by gureedo** [comment] 2020-06-03 08:46
Any updates?

**Comment by Luisa223** [comment] 2020-06-30 17:50
Any suggestions to this issue? Getting the same output

**Comment by a62mds** [comment] 2020-07-09 18:18
Also seeing the same issue

**Comment by erikrenberg** [comment] 2020-07-30 09:05
I see the same issue with v1.30.2 and MSVC 19.26.28806.0. (VS 2019 16.6.5).

**Comment by pm-energid** [comment] 2020-08-07 22:13
I hope we can get a working windows dll build some day!

**Comment by phidahl** [comment] 2020-09-08 12:54
Did someone get it working? I have the same issue with v1.31.1 on Windows 10 here. There should be a way, since it is mentioned in the build instructions to use "-DBUILD_SHARED_LIBS=ON"

**Comment by pm-energid** [comment] 2020-09-08 13:55
I tried building it for a little while. It seems that the CMake scripts for building dependencies are also broken when building shared libraries on windows.

**Comment by tgergo1** [comment] 2020-09-28 13:45
Any updates on this? If it's an abseil issue #23723 might help on it? 
I find it hard that to believe that no one could figure this out, there must be some solution.

**Comment by erikrenberg** [comment] 2020-09-29 06:36
Perhaps not related to this issue, but I though I should mention that you can use vcpkg (https://github.com/microsoft/vcpkg) to build build grpc 1.31.1 (the latest version vcpkg supports at the time of writing) with VS 16.7. I did that a couple of weeks ago without any issues.

**Comment by pm-energid** [comment] 2020-09-29 19:09
> Any updates on this? If it's an abseil issue #23723 might help on it?
> I find it hard that to believe that no one could figure this out, there must be some solution.

I don't think that #23723 alone would help. It seems that the cmake scripts in grpc repository to perform the external project build of abseil aren't working for DLL targets as expected. If you build abseil directly (it builds successfully when built independently) and then provide path to the build, cmake can proceed further from there.

**Comment by meztez** [comment] 2020-10-27 02:47
Change `CMakeLists.txt` in `.\third_party\abseil-cpp`. Comment out these statements

```
# when absl is included as subproject (i.e. using add_subdirectory(abseil-cpp))
# in the source tree of a project that uses it, install rules are disabled.
# if(NOT "^${CMAKE_SOURCE_DIR}$" STREQUAL "^${PROJECT_SOURCE_DIR}$")
#  set(ABSL_ENABLE_INSTALL FALSE)
# else()
  set(ABSL_ENABLE_INSTALL TRUE)
# endif()
```

**Comment by zl973320887** [comment] 2020-12-11 06:16
cmake ../ -DgRPC_BUILD_TESTS=OFF **-DABSL_ENABLE_INSTALL=TRUE** -DBUILD_SHARED_LIBS=ON

**Comment by hongnod** [comment] 2020-12-18 05:22
> cmake ../ -DgRPC_BUILD_TESTS=OFF **-DABSL_ENABLE_INSTALL=TRUE** -DBUILD_SHARED_LIBS=ON

I tried without success.

**Comment by Caiptain1** [comment] 2021-01-11 11:24
> cmake ../ -DgRPC_BUILD_TESTS=OFF **-DABSL_ENABLE_INSTALL=TRUE** -DBUILD_SHARED_LIBS=ON

Makes the problem go way, thanks.

**Comment by drfloob** [comment] 2022-06-16 01:58
I believe this was fixed in https://github.com/grpc/grpc/pull/26802

**Closed by drfloob** 2022-06-16 01:58 UTC
Labels: kind/bug, disposition/help wanted, lang/c++, priority/P2, untriaged
