### ISSUE TITLE
Keepalive watchdog timeout on slow connections

### ISSUE THREAD

**Issue by Green7** [grpc/grpc#22963] opened 2020-05-15 12:15 UTC
### What version of gRPC and what language are you using?

I have a server in Golang (grpc v1.29.1) and a client in C# (grpc v.2.29.0)

### What operating system (Linux, Windows,...) and version?

Windows 10

### What runtime / compiler are you using (e.g. python version or version of gcc)

Go 1.13.5, MSVS 2019

### What did you do?

I have a server in Golang and a client in C#.
I want to quickly detect the lack of connection to the server.
So in C# I set the keepalive parameters for the channel:
```
var timeout = 10000;      
var options = new List<ChannelOption>
{
  new ChannelOption("grpc.keepalive_time_ms", timeout),
  new ChannelOption("grpc.keepalive_timeout_ms", timeout),
  new ChannelOption("grpc.keepalive_permit_without_calls", 1),
  new ChannelOption("grpc.http2.max_pings_without_data", 0),
  new ChannelOption("grpc.http2.min_time_between_pings_ms", timeout)
};
```

Then this channel is used to establish a one-way server stream and to invoke unary RPC calls
(stream is created in async task, also RPC calls are async tasks).
Data is sent sporadically via stream, mainly I call RPC.

Everything works well but the problem starts if the connection between the client and server is slow.
In this situation, if RPC returns more data, the request takes a long time and stream (on which nothing is sent) gets a "keepalive watchdog timeout" error. 

How to solve this problem ?

**Comment by Green7** [comment] 2020-05-15 16:36
I checked and the error occurs even without using stream. Single RPC is enough. Here is a minimal example:

Server in go: hello server modified to return more data:

```
package main

import (
	"context"
	"log"
	"math/rand"
	"net"

	pb "grpcerror/helloworld"

	"google.golang.org/grpc"
)

const (
	port = ":50051"
)

// server is used to implement helloworld.GreeterServer.
type server struct {
	pb.UnimplementedGreeterServer
}

// SayHello implements helloworld.GreeterServer
func (s *server) SayHello(ctx context.Context, in *pb.HelloRequest) (*pb.HelloReply, error) {
	log.Printf("Received: %v", in.GetName())
	return &pb.HelloReply{Message: createRandString(1024 * 100)}, nil
}

func createRandString(n int) string {
	const letterBytes = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ"
	b := make([]byte, n)
	for i := range b {
		b[i] = letterBytes[rand.Intn(len(letterBytes))]
	}
	return string(b)
}

func main() {
	lis, err := net.Listen("tcp", port)
	if err != nil {
		log.Fatalf("failed to listen: %v", err)
	}
	s := grpc.NewServer()
	pb.RegisterGreeterServer(s, &server{})
	if err := s.Serve(lis); err != nil {
		log.Fatalf("failed to serve: %v", err)
	}
}

```

Client in C#: calling the server RPC in loop:


```
using Grpc.Core;
using Helloworld;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;

namespace GreeterClient
{
	internal class Program
	{
		public static async Task Main(string[] args)
		{
			int timeout = 3000;
			var options = new List<ChannelOption>
			{
				new ChannelOption("grpc.keepalive_time_ms", timeout),
				new ChannelOption("grpc.keepalive_timeout_ms", timeout),
				new ChannelOption("grpc.keepalive_permit_without_calls", 1),
				new ChannelOption("grpc.http2.max_pings_without_data", 0),
				new ChannelOption("grpc.http2.min_time_between_pings_ms", timeout)
			};

			Channel channel = new Channel("192.168.248.115:50051", ChannelCredentials.Insecure, options);

			var client = new Greeter.GreeterClient(channel);
			String user = "you";

			for (int i = 0; i < 100; i++)
			{
				var reply = await client.SayHelloAsync(new HelloRequest { Name = user });
				Console.WriteLine("Greeting: " + reply.Message);
			}
			channel.ShutdownAsync().Wait();
			Console.WriteLine("Press any key to exit...");
			Console.ReadKey();
		}
	}
}
```
I started the server on the local network. For the server I set the transmission limit to 5KB / s (via the NetLimiter 4 application).  After several calls, the client reported "keepalive watchdog timeout" error.

**Comment by jtattermusch** [comment] 2020-05-25 05:48
@Green7  would you be able to provide a runnable reproduction in form of a VS project (ideally as a github repository). That would make it easier to reproduce the issue and decide what next.

Also, from the description you've provided it's not clear to me that there is actually any problem.
If a keepalive ping fails to be delivered on time, the connection will be terminated (and you'll need to reconnect) and that is working as expected. So without further evidence, it seems that the http2 pings are just delayed more than their allowed timeout and the connection dies - in which case you can try to reconnect and try again (or you can increase your GRPC_ARG_KEEPALIVE_TIMEOUT_MS)

See here for more info https://github.com/grpc/grpc/blob/master/doc/keepalive.md

Does this also happen on linux or is it windows specific?
Does this only happen on C# client vs Go server or also with other servers (e.g. C# server).

**Comment by Green7** [comment] 2020-05-25 13:07
@jtattermusch 

Here is repo with test projects https://github.com/Green7/GrpcWatchdogTimeout  (You must change the server address in the client code).
I started the server on a Windows 10 virtual machine with https://www.netlimiter.com installed. The send/receive limit for the server application was set to 5KB/s. The limit may be higher, but then you have to wait longer for the error.

> If a keepalive ping fails to be delivered on time, the connection will be terminated (and you'll need to reconnect) and that is working as expected. 

Yes, I can reconnect but in this situation I have to authenticate again, initiate streams, repeat the aborted operations, etc. A lot of unnecessary operations when nothing really happened. The worst thing is that the user must wait a long time for the result of the operation because I start it again instead of finishing it.

>  in which case you can try to reconnect and try again (or you can increase your GRPC_ARG_KEEPALIVE_TIMEOUT_MS)

Increasing GRPC_ARG_KEEPALIVE_TIMEOUT_MS does not solve the problem. In my application I need to detect disconnected connections as soon as possible. If I increase GRPC_ARG_KEEPALIVE_TIMEOUT_MS, the disconnection detection time will increase.

> Does this also happen on linux or is it windows specific?
> Does this only happen on C# client vs Go server or also with other servers (e.g. C# server).

I tested only on Windows. 
I tested all configurations: server in c # and golang and client in c# and golang. Problem has always occurred, but it appears that he is less frequent in Golang.

**Comment by jtattermusch** [comment] 2020-05-26 10:48
TBH I don't understand what is the behavior you're asking for.
- you are explicitly enabling a feature that sends pings on a connection and is supposed to kill the connection if those pings are not delivered on time (so that you can detect a disconnect)
- at the same time you are complaining about that feature killing your connection and that you need to restart your RPC, but that is exactly what you configured for.

So it looks like you're asking for the impossible - you either set a tight keepalive timeouts and detect a broken connection quickly OR you set a more lenient keepalive timeout and make your connections less likely to disconnect due to a missed keepalive. For obvious reasons, there's no way to have both at the same time. There is also no "magic" algorithm that would allow you to detect stalled connections quickly without any false positives (in general it's impossible to know know if the peer/network is just slow or if the connection has become broken - both situations look the same to the client).

I'm going to close this issue as  "working as intended" because there's no evidence of erroneous behavior.

**Closed by jtattermusch** 2020-05-26 10:48 UTC
Labels: kind/bug, lang/C#, priority/P2

**Comment by Green7** [comment] 2020-05-26 11:12
I had the impression that keep alive ping should only be sent if there is no other activity.
This is what the golang documentation suggests:
https://github.com/grpc/grpc-go/blob/f5cae43845b8b054a2173bb83c660ef944f7c71b/Documentation/keepalive.md

> When there's no activity on a connection (note that an ongoing stream results in no activity when there's no message being sent), after Time, a ping will be sent by the client

But in my case there is activity: the client receives the data sent by the server, and at this point the connection is interrupted by client keep alive watchdog. So the connection works but is interrupted by the watchdog.
Should it work like that?

**Comment by jtattermusch** [comment] 2020-05-29 07:00
@yashykt  can you please answer the last question?

**Comment by yashykt** [comment] 2020-06-02 20:13
Sorry I was about to answer this last week, but my attention got diverted

**Comment by yashykt** [comment] 2020-06-02 20:23
https://github.com/grpc/grpc/blob/b16ce8d621a3ed470dfdb5bdc769ac9036f4ef76/src/core/ext/transport/chttp2/transport/chttp2_transport.cc#L2573 on receiving bytes, gRPC Core does reset the keepalive timer but if the ping was already sent out, then it won't reset the watchdog timer and it will expect to have received the ping ACK within the timeout duration.

**Comment by yashykt** [comment] 2020-06-02 20:36
It might make sense for gRPC to reset the watchdog timer too on receiving bytes

**Comment by yashykt** [comment] 2020-06-02 20:38
Given that currently, gRPC does not currently reset the watchdog timer on receiving bytes, it might make sense to write some application level logic to mimic pings.

**Comment by Green7** [comment] 2020-06-03 15:06
@yashykt you're probably right. Here is part of my log (keepalive_time_ms and keepalive_timeout_ms set to 3000):

> 16:04:48.480217 tcp_windows.cc:253: win_read
> 16:04:51.479674 writing.cc:125: CLIENT: Ping sent
> 16:04:51.479826 chttp2_transport.cc:2823: Start keepalive ping
> 16:04:54.324056 tcp_windows.cc:216: READ
> 16:04:54.328248 chttp2_transport.cc:798 state WRITING -> IDLE [finish writing]
> 16:04:54.479675 Keepalive watchdog fired. Closing transport.

So  at 16:04:51.47 we sent ping, at 16:04:54.32 we received the data and right after that watchdog was fired.
Is there a chance that this will be corrected? 
I think that:
`grpc_timer_cancel(&t->keepalive_watchdog_timer);`
chttp2_transport line 2574 would solve the problem.
Unfortunately I don't have a C ++ environment ready to compile and check this patch.

**Comment by yashykt** [comment] 2020-06-09 20:08
@Green7 I'll put it in my queue :)

**Comment by Green7** [comment] 2020-06-09 20:17
@yashykt thank you :) I'm waiting for the update.

**Comment by Green7** [comment] 2020-07-06 17:43
@yashykt Any progress ?

**Comment by yashykt** [comment] 2020-07-07 05:02
It'll probably be after I am able to merge in https://github.com/grpc/grpc/pull/23313

**Comment by Green7** [comment] 2020-07-07 07:16
would be great.

**Comment by benaranguren** [comment] 2020-12-21 22:58
@yashykt @Green7 what is the latest on the attempt to reset the watchdog timer when any data is received.

**Comment by Green7** [comment] 2020-12-23 12:54
I just checked my test app with the latest C# version (2.34.0) and problem still exist. From what I can see (I'm not 100% sure)  there are no code changes in chttp2_transport for solving this problem. 
@yashykt please could you say something about it?

**Comment by yashykt** [comment] 2020-12-24 10:34
I'm sorry for the delay. This item keeps getting pushed back. At this point, it might be better for someone else to jump in on this.

FYI, on reading https://github.com/grpc/proposal/blob/master/A8-client-side-keepalive.md, the original algorithm does not specify resetting the timeout on receiving bytes as an optimization, so it might be something that needs to be discussed with other languages too. 

Also, to be clear, gRPC Core's implementation already follows the guidance of the keepalive timer being measured from the last byte read. Resetting the keepalive timer should be sufficient to deal with slow connections. If the round trip latency itself is a problem here, then we can simply increase the keepalive timer period. 

(Note that I'm not arguing against resetting the watchdog timer. I'm simply noting that the problem that we are trying to solve in this case seems to be better solved by just increasing the timer period.)

**Comment by Green7** [comment] 2020-12-30 09:18
> (Note that I'm not arguing against resetting the watchdog timer. I'm simply noting that the problem that we are trying to solve in this case seems to be better solved by just increasing the timer period.)

As I wrote before: Increasing timer period does not solve the problem. In my application I need to detect disconnected connections as soon as possible. If I increase timer period, the disconnection detection time also will increase  :(

**Comment by aligokalppeker** [comment] 2024-01-22 20:40
How is this kept closed? even if the issue persists. I just get it with slow network connections. very strange...

**Comment by ElderOrb** [comment] 2024-03-19 15:48
Is there workaround for this issue?

**Comment by ElderOrb** [comment] 2024-03-19 15:52
@Green7 how did you solve an issue? Patched with your changes? 

@yashykt if no fix is planned, can you please expose some API allowing cancelling watchdog timer periodically while data is transmitted over slow network?

**Comment by Green7** [comment] 2024-03-19 19:19
@ElderOrb Unfortunately, I didn't find a solution. I chose the period timer to work as best as possible. I haven't checked the changes in the sources, maybe something has been improved?

**Comment by ElderOrb** [comment] 2024-03-19 21:06
> @ElderOrb Unfortunately, I didn't find a solution. I chose the period timer to work as best as possible. I haven't checked the changes in the sources, maybe something has been improved?

Tried most recent version available via nuget - still same issue. Thinking about switching to streaming call and pass file in chunks - maybe it will make keepalive timer to behave properly..
