### ISSUE TITLE
The C# interop docker image failed to build

### ISSUE THREAD

**Issue by murgatroid99** [grpc/grpc#11413] opened 2017-06-05 23:55 UTC
https://grpc-testing.appspot.com/job/gRPC_interop_pull_requests/14526/console

```
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 mono-devel : Depends: libmono-system-runtime4.0-cil (>= 2.10.1) but it is not going to be installed
              Depends: libmono-system-servicemodel4.0a-cil (>= 3.2.3) but it is not going to be installed
              Depends: libmono-system-web-services4.0-cil (>= 1.0) but it is not going to be installed
              Depends: libmono-cil-dev (= 5.0.1.1-0xamarin5+debian7b1) but it is not going to be installed
              Recommends: msbuild but it is not going to be installed
 nuget : Depends: libnuget-core-cil (= 2.12+mono-0xamarin5+debian7b1) but it is not going to be installed
[91mE: Unable to correct problems, you have held broken packages.
[0mRemoving intermediate container 4f3b39f1733f
The command '/bin/sh -c apt-get update && apt-get -y dist-upgrade && apt-get install -y     mono-devel     ca-certificates-mono     nuget     && apt-get clean' returned a non-zero code: 100
+ exit 100

2017-06-05 20:51:23,840 FAILED: build_docker_csharpcoreclr [ret=100, pid=9500]
```

**Comment by jtattermusch** [comment] 2017-06-07 04:26
Duplicate of https://github.com/grpc/grpc/issues/11357

**Closed by jtattermusch** 2017-06-07 04:26 UTC
Labels: C#, interop
