### ISSUE TITLE
@google-cloud/speech Segmentation fault

### ISSUE THREAD

**Issue by stephenplusplus** [grpc/grpc#9283] opened 2017-01-09 19:25 UTC
_From @pepperkick on January 8, 2017 3:40_

#### Environment details

  - OS: Windows Bash Ubuntu 16.04
  - Node.js version:  7.4.0
  - npm version: 4.0.5
  - google-cloud-node version: @google-cloud/speech 0.5.0

#### Steps to reproduce

```js
const speech = require('@google-cloud/speech')({
    projectId: projectId,
    keyFilename: __dirname + "/../configs/google_key.json"
});

var speechStream = speech.createRecognizeStream({
    config: {
      encoding: 'LINEAR16',
      sampleRate: 16000
    },
    singleUtterance: false,
    interimResults: false
});

speechStream.write(/*PCM data*/);

speechStream.on("error", console.error);
speechStream.on("data", console.log);
```

Error I get when I speak
```
E0108 09:02:21.575912200   23765 ev_epoll_linux.c:1523]      pollset_work: {"created":"@1483846341.575866100","description":"pollset_work_and_unlock","file":"../src/core/lib/iomgr/ev_epoll_linux.c","file_line":258,"referenced_errors":[{"created":"@1483846341.575849300","description":"OS Error","errno":38,"file":"../src/core/lib/iomgr/ev_epoll_linux.c","file_line":1362,"os_error":"Function not implemented","syscall":"epoll_wait() epoll fd: 22 failed with error: 38 (Function not implemented)"}]}
E0108 09:02:21.578664300   23765 completion_queue.c:385]     Completion queue next failed: {"created":"@1483846341.575866100","description":"pollset_work_and_unlock","file":"../src/core/lib/iomgr/ev_epoll_linux.c","file_line":258,"referenced_errors":[{"created":"@1483846341.575849300","description":"OS Error","errno":38,"file":"../src/core/lib/iomgr/ev_epoll_linux.c","file_line":1362,"os_error":"Function not implemented","syscall":"epoll_wait() epoll fd: 22 failed with error: 38 (Function not implemented)"}]}
E0108 09:02:21.578733800   23764 ev_epoll_linux.c:1523]      pollset_work: {"created":"@1483846341.575866100","description":"pollset_work_and_unlock","file":"../src/core/lib/iomgr/ev_epoll_linux.c","file_line":258,"referenced_errors":[{"created":"@1483846341.575843700","description":"OS Error","errno":38,"file":"../src/core/lib/iomgr/ev_epoll_linux.c","file_line":1362,"os_error":"Function not implemented","syscall":"epoll_wait() epoll fd: 22 failed with error: 38 (Function not implemented)"}]}
E0108 09:02:21.590499200   23764 completion_queue.c:385]     Completion queue next failed: {"created":"@1483846341.575866100","description":"pollset_work_and_unlock","file":"../src/core/lib/iomgr/ev_epoll_linux.c","file_line":258,"referenced_errors":[{"created":"@1483846341.575843700","description":"OS Error","errno":38,"file":"../src/core/lib/iomgr/ev_epoll_linux.c","file_line":1362,"os_error":"Function not implemented","syscall":"epoll_wait() epoll fd: 22 failed with error: 38 (Function not implemented)"}]}
Segmentation fault (core dumped)
```

_Copied from original issue: GoogleCloudPlatform/google-cloud-node#1907_

**Comment by stephenplusplus** [comment] 2017-01-09 19:25
@jgeewax any idea who can help with this, someone from the Speech team maybe?

**Comment by stephenplusplus** [comment] 2017-01-09 19:25
_From @jgeewax on January 9, 2017 17:25_

I think this is a gRPC fault, right?

**Comment by stephenplusplus** [comment] 2017-01-09 19:25
Could be! @murgatroid99 should we move this issue over to grpc?

**Comment by stephenplusplus** [comment] 2017-01-09 19:25
_From @murgatroid99 on January 9, 2017 18:26_

Yes, this would be good to move to gRPC. It does look like a gRPC problem. The "Function not implemented" bit makes me suspect that this is an issue with trying to use the epoll API on Windows Bash Ubuntu.

**Comment by ctiller** [comment] 2017-01-09 19:32
Looks like we need better platform detection for when to use epoll.
Any information on which grpc library was used here?

**Comment by murgatroid99** [comment] 2017-01-09 21:35
I would bet on Node gRPC version 1.0.1, just because that's been out for a while. And it's running on Node 7, which means they probably compiled on that system, because we don't have Node 7 precompiled binaries yet.

**Comment by ctiller** [comment] 2017-01-09 21:51
So to get a fix in flight, I'll need:
- version of gRPC (I can believe 1.0.1, but need confirmation: pre-1.0 is
likely broken and the fix will be to update)
- a debug log (run with GRPC_VERBOSITY=DEBUG set in the environment) --
there's a line saying 'Using polling engine: ' that I need to see

**Comment by hsaliak** [comment] 2017-01-25 21:44
@stephenplusplus have you got a chance to provide the information requested by Craig?

**Comment by stephenplusplus** [comment] 2017-01-25 21:45
This issue was actually reported by @pepperkick originally.

**Comment by pepperkick** [comment] 2017-01-27 08:41
Hello,

I downgraded to Node 6 to fix this issue for app (I was not aware of this issue page until I got tagged, sorry).

Anyway,

I got Node 7.4 again today and installed @google-cloud/speech with this command

`npm install @google-cloud/speech  --loglevel info`

Not sure if you want this but here is the npmlog
[npmlog.txt](https://github.com/grpc/grpc/files/734699/npmlog.txt)

**gRPC v1.0.1** was installed

Running my app with this command

`GRPC_VERBOSITY=DEBUG NODE_ENV=development nodejs .`

Got this along with the app log

`
I0127 14:00:02.418056800    9115 ev_epoll_linux.c:85]        epoll engine will be using signal: 36 
D0127 14:00:02.418539600    9115 ev_posix.c:106]             Using polling engine: epoll
`

and got this when google speech tries to recognize something

`
E0127 14:04:35.569946200    9122 ev_epoll_linux.c:1523]      pollset_work: {"created":"@1485506075.569910800","description":"pollset_work_and_unlock","file":"../src/core/lib/iomgr/ev_epoll_linux.c","file_line":258,"referenced_errors":[{"created":"@1485506075.569898600","description":"OS Error","errno":38,"file":"../src/core/lib/iomgr/ev_epoll_linux.c","file_line":1362,"os_error":"Function not implemented","syscall":"epoll_wait() epoll fd: 20 failed with error: 38 (Function not implemented)"}]}
E0127 14:04:35.572098800    9122 completion_queue.c:385]     Completion queue next failed: {"created":"@1485506075.569910800","description":"pollset_work_and_unlock","file":"../src/core/lib/iomgr/ev_epoll_linux.c","file_line":258,"referenced_errors":[{"created":"@1485506075.569898600","description":"OS Error","errno":38,"file":"../src/core/lib/iomgr/ev_epoll_linux.c","file_line":1362,"os_error":"Function not implemented","syscall":"epoll_wait() epoll fd: 20 failed with error: 38 (Function not implemented)"}]}
E0127 14:04:35.572176300    9123 ev_epoll_linux.c:1523]      pollset_work: {"created":"@1485506075.569914500","description":"pollset_work_and_unlock","file":"../src/core/lib/iomgr/ev_epoll_linux.c","file_line":258,"referenced_errors":[{"created":"@1485506075.569905200","description":"OS Error","errno":38,"file":"../src/core/lib/iomgr/ev_epoll_linux.c","file_line":1362,"os_error":"Function not implemented","syscall":"epoll_wait() epoll fd: 20 failed with error: 38 (Function not implemented)"}]}
E0127 14:04:35.579229400    9123 completion_queue.c:385]     Completion queue next failed: {"created":"@1485506075.569914500","description":"pollset_work_and_unlock","file":"../src/core/lib/iomgr/ev_epoll_linux.c","file_line":258,"referenced_errors":[{"created":"@1485506075.569905200","description":"OS Error","errno":38,"file":"../src/core/lib/iomgr/ev_epoll_linux.c","file_line":1362,"os_error":"Function not implemented","syscall":"epoll_wait() epoll fd: 20 failed with error: 38 (Function not implemented)"}]}
I0127 14:04:35.682677800    9127 subchannel.c:642]           Connect failed: {"created":"@1485506075.682607400","description":"Failed to set TCP_NODELAY","file":"../src/core/lib/iomgr/socket_utils_common_posix.c","file_line":206}
I0127 14:04:35.685302100    9127 subchannel.c:647]           Retry in 0.999736000 seconds
I0127 14:04:35.687373000    9127 subchannel.c:642]           Connect failed: {"created":"@1485506075.687269000","description":"Failed to set TCP_NODELAY","file":"../src/core/lib/iomgr/socket_utils_common_posix.c","file_line":206}
I0127 14:04:35.691099700    9127 subchannel.c:647]           Retry in 0.999751000 seconds
I0127 14:04:35.692191400    9127 subchannel.c:642]           Connect failed: {"created":"@1485506075.692124200","description":"Failed to set TCP_NODELAY","file":"../src/core/lib/iomgr/socket_utils_common_posix.c","file_line":206}
I0127 14:04:35.694681700    9127 subchannel.c:647]           Retry in 0.999865000 seconds
I0127 14:04:35.695646000    9127 subchannel.c:642]           Connect failed: {"created":"@1485506075.695576100","description":"Failed to set TCP_NODELAY","file":"../src/core/lib/iomgr/socket_utils_common_posix.c","file_line":206}
I0127 14:04:35.709812800    9127 subchannel.c:647]           Retry in 0.999867000 seconds
Segmentation fault (core dumped)
`

(Sorry, not sure how to exactly format the log properly in markdown)

Hope this helps!
Thank You

**Comment by murgatroid99** [comment] 2017-01-31 01:43
grpc@1.1.0 has been published to npm, and it includes some significant low-level changes. Can you update your dependencies and see if this problem is still present?

**Comment by pepperkick** [comment] 2017-01-31 06:40
@murgatroid99 same issue with grpc@1.1.0 too.

**Comment by murgatroid99** [comment] 2017-01-31 19:20
That's very surprising, because grpc@1.1.0 should never call any epoll functions.

**Comment by pepperkick** [comment] 2017-01-31 19:43
I just updated gprc through npm I guess I have to rebuild. I will start fresh and confirm.

**Comment by murgatroid99** [comment] 2017-01-31 19:47
You should be able to do `npm update grpc --update-binary`, or possibly `npm install grpc@1.1`. Unfortunately, due to GoogleCloudPlatform/google-cloud-node#1946, you may actually just experience different failures until the next patch release.

**Comment by pepperkick** [comment] 2017-01-31 20:03
Updated to grpc@1.1.0 again and rebuild google cloud speech.

GRPC_VERBOSITY=DEBUG still gives ` Using polling engine: epoll` when app has started.

```
I0201 01:28:59.691433900    5421 ev_epoll_linux.c:85]        epoll engine will be using signal: 36
D0201 01:28:59.691829500    5421 ev_posix.c:106]             Using polling engine: epoll
```

Is there any way to confirm that the app is using v1.1.0 and not the old one (I did remove the old one from modules, but still want to confirm)

**Comment by murgatroid99** [comment] 2017-02-02 18:53
It might be best to do a clean reinstall, just to make sure it's up to date.

**Comment by pepperkick** [comment] 2017-02-02 20:20
Installed fresh, no more "polling engine" log and does not crash anymore.

**Comment by murgatroid99** [comment] 2017-02-03 21:34
OK. I'm going to close this for now.

**Closed by murgatroid99** 2017-02-03 21:34 UTC
Labels: node, requires reporter clarification

**Comment by RomanYankovsky** [comment] 2017-03-04 18:27
Sorry, I'm not sure if I have to create a new issue, or reopen this one, but my problem is pretty much the same. You said _grpc@1.1.0 should never call any epoll functions_, but it looks like it still does.

**Steps to reproduce**

```js
const PubSub = require('@google-cloud/pubsub')

const pubsub = PubSub({
  projectId: 'GCP:test',
  keyFilename: null
})

pubsub.createTopic('test')
```
**The error is:**
```$ GRPC_VERBOSITY=DEBUG nodejs grpc-test.js
I0304 21:16:10.337025100   18338 ev_epoll_linux.c:93]        epoll engine will be using signal: 40
D0304 21:16:10.337879200   18338 ev_posix.c:105]             Using polling engine: epoll
D0304 21:16:10.466422500   18338 completion_queue_threadpool.cc:177] Called CompletionQueueNext
E0304 21:16:10.471868000   18348 ev_epoll_linux.c:1675]      pollset_work: {"created":"@1488651370.471840300","description":"pollset_work_and_unlock","file":"../src/core/lib/iomgr/ev_epoll_linux.c","file_line":284,"referenced_errors":[{"created":"@1488651370.471833200","description":"OS Error","errno":38,"file":"../src/core/lib/iomgr/ev_epoll_linux.c","file_line":1508,"os_error":"Function not implemented","syscall":"epoll_wait() epoll fd: 15 failed with error: 38 (Function not implemented)"}]}
E0304 21:16:10.472469300   18348 completion_queue.c:463]     Completion queue next failed: {"created":"@1488651370.471840300","description":"pollset_work_and_unlock","file":"../src/core/lib/iomgr/ev_epoll_linux.c","file_line":284,"referenced_errors":[{"created":"@1488651370.471833200","description":"OS Error","errno":38,"file":"../src/core/lib/iomgr/ev_epoll_linux.c","file_line":1508,"os_error":"Function not implemented","syscall":"epoll_wait() epoll fd: 15 failed with error: 38 (Function not implemented)"}]}
I0304 21:16:10.473769400   18344 subchannel.c:694]           Connect failed: {"created":"@1488651370.473738600","description":"Failed to set TCP_NODELAY","file":"../src/core/lib/iomgr/socket_utils_common_posix.c","file_line":207}
Segmentation fault (core dumped)
```
**Environment details**

- OS: Windows Bash Ubuntu 14.04
- Node.js version: 6.10.0
- npm version: 3.10.10
- google-cloud-node version: @google-cloud/pubsub 0.8.1
- grpc version: 1.1.2

**Comment by murgatroid99** [comment] 2017-03-06 18:09
Right. The changes that caused the library to not use epoll in 1.1.0 had to be reverted in 1.1.2 because of some bugs (not related to epoll). I am hoping to reintroduce those changes soon.

This problem is specific to Windows Bash Ubuntu. Basically, it looks like Linux, and gRPC gets the gRPC binary for Linux, but it contains an incomplete implementation of epoll, which gRPC requires internally. I would recommend trying to downgrade gRPC to 1.1.1.

**Comment by akshithasriraman** [comment] 2017-04-04 18:56
It appears like grpc 1.1.1 also calls epoll functions. I installed grpc 1.1.1 on a fresh VM (git clone -b v1.2.0 https://github.com/grpc/grpc) . Running the app with GRPC_VERBOSITY=DEBUG still gives "Using polling engine: epoll"

```
I0404 18:49:35.712894432   16553 ev_epoll_linux.c:93]        epoll engine will be using signal: 40
D0404 18:49:35.712996115   16553 ev_posix.c:107]             Using polling engine: epoll
```

**Comment by murgatroid99** [comment] 2017-04-04 19:03
gRPC 1.2.0 on Node should not use epoll at all. How exactly did you install the module from the cloned repository?

**Comment by akshithasriraman** [comment] 2017-04-04 20:28
I installed it using:
```
git submodule update --init
make
[sudo] make install
```

**Comment by murgatroid99** [comment] 2017-04-04 21:52
That only installs the C and C++ libraries. You should instead do something like `npm install path/to/grpc` or possibly `npm link path/to/grpc` in the directory that has a dependency on grpc. You do still want to update the submodules

**Comment by akshithasriraman** [comment] 2017-04-05 02:11
Thank you for your responses!
Sorry, I'm not sure if I should create a new issue or continue posting here. But, my issue is slightly different. I'm using grpc C++ libraries in a custom application. When my server polls very often using the AsyncNext API (cq_->AsyncNext(&tag, &ok, gpr_time_0(GPR_CLOCK_REALTIME)), I see the following messages.

```
E0405 01:53:03.093792143    1384 ev_epoll_linux.c:1178]      pollset_kick: {"created":"@14913
57183.093770948","description":"Kick Failure","file":"src/core/lib/iomgr/ev_epoll_linux.c","f
ile_line":258,"referenced_errors":[{"created":"@1491357183.093767473","description":"OS Error
","errno":11,"file":"src/core/lib/iomgr/ev_epoll_linux.c","file_line":1091,"os_error":"Resour
ce temporarily unavailable","syscall":"pthread_kill"}]}

E0405 01:53:03.093826733    1384 completion_queue.c:295]     Kick failed: {"created":"@149135
7183.093770948","description":"Kick Failure","file":"src/core/lib/iomgr/ev_epoll_linux.c","fi
le_line":258,"referenced_errors":[{"created":"@1491357183.093767473","description":"OS Error"
,"errno":11,"file":"src/core/lib/iomgr/ev_epoll_linux.c","file_line":1091,"os_error":"Resourc
e temporarily unavailable","syscall":"pthread_kill"}]}
```

These aren't errors per say, as the program finishes without segfaults. However, encountering these exceptions degrades the application's throughput.
I noticed a similar issue mentioned in a github gist - https://gist.github.com/braoru/6803f9104bfa5900bd169a0c73b5af9e

Does this look like a gRPC fault?

The above trace was generated when I used grpc v1.0.0. However, I see the same messages for grpc v1.1.1 as well.

**Comment by ctiller** [comment] 2017-04-05 02:24
Sree - since this means the RT signal queue is full, can we just swallow
the error in this case?

**Comment by amir1981** [comment] 2017-04-09 07:42
Hi, I am getting the same when compiling c++ example:
 https://github.com/GoogleCloudPlatform/cpp-docs-samples
I installed grpc from : https://github.com/grpc/grpc/blob/master/INSTALL.md
I am using Ubuntu

Here is what I get:

ubuntu:./transcribe -b 16000 resources/audio.raw
I0409 00:33:20.978353048  127950 ev_epoll_linux.c:94]        epoll engine will be using signal: 40
D0409 00:33:20.978505327  127950 ev_posix.c:107]             Using polling engine: epoll
Segmentation fault (core dumped)

any solution? 
thanks
