### ISSUE TITLE
gRPC name resolution of kubernetes service failing in python client

### ISSUE THREAD

**Issue by chakradarraju-strings** [grpc/grpc#17705] opened 2019-01-13 10:17 UTC
### What version of gRPC and what language are you using?
 gRPC version: 1.17.1
Python
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
 python3.6.7
 
### What did you do?
start a kubernetes grpc service
stub = ExampleStub(grpc.insecure_channel('k8s-service-name:port'))
stub.Call(message)
 
### What did you expect to see?
 Call to succeed and return response
 
### What did you see instead?
I    File "/usr/local/lib/python3.6/dist-packages/grpc/_channel.py", line 547, in __call__
 
I      return _end_unary_response_blocking(state, call, False, None)
 
I    File "/usr/local/lib/python3.6/dist-packages/grpc/_channel.py", line 466, in _end_unary_response_blocking
 
I      raise _Rendezvous(state, None, None, deadline)
 
I  grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with:
 
I  	status = StatusCode.UNAVAILABLE
 
I  	details = "Name resolution failure"
 
I  	debug_error_string = "{"created":"@1547369499.577869788","description":"Failed to create subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":2706,"referenced_errors":[{"created":"@1547369499.577866272","description":"Name resolution failure","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":3035,"grpc_status":14}]}"
 
I  >
 
Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

See https://github.com/grpc/grpc/blob/master/TROUBLESHOOTING.md for how to diagnose problems better.
 
### Anything else we should know about your project / environment?
I tried nslookup as mentioned in https://kubernetes.io/docs/tasks/administer-cluster/dns-debugging-resolution/
resolution works as expected.

Let me know if what other details I've to attach.

**Comment by gnossen** [comment] 2019-01-14 17:25
Hi, @chakradarraju-strings. Could you please try setting the following environment variables within your client environment and post the results?

```
GRPC_VERBOSITY=debug
GRPC_TRACE=client_channel
```

**Comment by ericgribkoff** [comment] 2019-01-14 17:33
Duplicate of https://github.com/grpc/grpc/issues/15106, let's move discussion to that open issue

**Closed by ericgribkoff** 2019-01-14 17:33 UTC
Labels: disposition/requires reporter action, lang/Python
