### ISSUE TITLE
Make unexpected RST_STREAM return UNAVAILABLE

### ISSUE THREAD

**Issue by kpayson64** [grpc/grpc#9177] opened 2016-12-20 18:27 UTC
Hello, I'm recently seeing RST_STREAM exceptions which should also probably be classified as Unavailable rather than Internal.

Seen in ruby, but it likely a c-core issue

cc @timanovsky
```
Google::cloud::InternalError: 13:{"created":"@1476172369.098617688","description":"RST_STREAM","file":"src/core/ext/transport/chttp2/transport/frame_rst_stream.c","file_line":107,"http2_error":2} -> GRPC::BadStatus: 13:{"created":"@1476172369.098617688","description":"RST_STREAM","file":"src/core/ext/transport/chttp2/transport/frame_rst_stream.c","file_line":107,"http2_error":2} (code[Fixnum]=13) (details[String]="{\"created\":\"@1476172369.098617688\",\"description\":\"RST_STREAM\",\"file\":\"src/core/ext/transport/chttp2/transport/frame_rst_stream.c\",\"file_line\":107,\"http2_error\":2}") (metadata[Hash]={})```

**Comment by ericgribkoff** [comment] 2017-03-01 15:36
`RST_STREAM` causing gRPC `INTERNAL` error is the intended behavior for most `RST_STREAM` error codes. `UNAVAILABLE` should only be returned when the `RST_STREAM` error code is `REFUSED_STREAM`.

This is documented in the [http2 transport mapping: errors section of the spec](https://github.com/grpc/grpc/blob/master/doc/PROTOCOL-HTTP2.md#errors), and was actually fixed for https://github.com/grpc/grpc/issues/9142. We have tests for this behavior in [the http2 interop tests](https://github.com/grpc/grpc/blob/master/doc/negative-http2-interop-test-descriptions.md).

We don't have a test for the `RST_STREAM` with `REFUSED_STREAM` error code case, but I just ran this manually and the expected UNAVAILABLE error is returned. I think we can close this issue.

**Comment by timanovsky** [comment] 2017-03-01 18:31
@ericgribkoff what is the error code in the exception above?

**Comment by ericgribkoff** [comment] 2017-03-01 18:46
It looks like `http2_error: 2` is included in the error message, indicating the `RST_STREAM` was received with an `INTERNAL_ERROR` error code (https://http2.github.io/http2-spec/#ErrorCodes). This is correctly being mapped to gRPC `INTERNAL`.

**Comment by timanovsky** [comment] 2017-03-01 18:53
ok

**Closed** 2017-03-02 01:27 UTC
Labels: core
