### ISSUE TITLE
GRPC python client cpu 100% sometimes

### ISSUE THREAD

**Issue by charlesld** [grpc/grpc#21371] opened 2019-12-04 13:17 UTC
### What version of gRPC and what language are you using?

1.25.0  python client  
install by pip  and package is  grpcio-1.25.0-cp27-cp27mu-manylinux1_x86_64.whl

### What operating system (Linux, Windows,...) and version?
debian 7

### What runtime / compiler are you using (e.g. python version or version of gcc)
python 2.7.3   
emm. is a old python project  running in old linux , for some reason , we need transfer old communicator to new grpc   
project start all  func thread by thread , include grpc client write in a while loop.

### What did you do?

![image](https://user-images.githubusercontent.com/23304239/70145899-0cb49980-16dc-11ea-855b-bacaf30ff4ae.png)

simple but stream both server and client . 

I define proto file as this 

```shell
service AgentNotify {
  rpc SendHeartBeat ( stream HeartBeatRequest) returns (stream HeartBeatReply) {}
}
message HeartBeatRequest {
  string request = 1;
  string msgId = 2;
}
message HeartBeatReply {
  string reply = 1;
  string TimeStamp = 2;  
}
```
generate code cmd 
```shell
python -m grpc_tools.protoc --proto_path=./ --python_out=./ --grpc_python_out=./ heartbeat.proto
```

and the grpc client code like this 

```python
class channel:
    def init(self):
            self.stub = heartbeat_pb2_grpc.AgentNotifyStub(self.channel)
            response_iterator = self.stub.SendHeartBeat(self.gen_heartbeat())
            for response in response_iterator:
                xxxx

    def gen_heartbeat(self):
        while self.channel_alive:
            try:
                hb = self.request_queue.get(timeout=10)
            except Empty:
                continue
            hb_string = json.dumps(hb)
            request = heartbeat_pb2.HeartBeatRequest(request=hb_string)
            yield request
```

### What did you expect to see?
running with no problem

### What did you see instead?
python client message send thread stop in stuck for some often, and cpu running in 100% mode.  but the tcp connection was still keep with server.
before add grpc . project runs well, and when turn grpc switch on,  the project was lay down to  the street(扑街),  short time may in few minitus, and longer may in some hours.

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

See [TROUBLESHOOTING.md](https://github.com/grpc/grpc/blob/master/TROUBLESHOOTING.md) for how to diagnose problems better.

**Comment by charlesld** [comment] 2019-12-04 14:02
![image](https://user-images.githubusercontent.com/23304239/70148375-02e16500-16e1-11ea-9001-c98741918ec3.png)


@nathanielmanistaatgoogle  I see this issue  [#14911](https://github.com/grpc/grpc/issues/14911)  ,  was python grpc sdk got  some  err can cause cpu 100?

**Comment by lidizheng** [comment] 2019-12-04 18:42
@charlesld Can you help us by creating a full reproduce case for this issue? By "thread stop in stuck", do you mean there is no traffic go through? Or simply because 100% CPU usage?

**Comment by charlesld** [comment] 2019-12-05 02:16
Hi, @lidizheng  when cpu 100% , no traffic , and whole project stop running，seems empty loop was running。
I will  continue watching this ,and feed back.

**Comment by lidizheng** [comment] 2019-12-05 02:30
@charlesld Still, I'm not entirely sure what is the behavior here, please try to create a minimal reproduction case that can trigger the bug you are describing.

**Comment by charlesld** [comment] 2019-12-05 12:28
Hi, @lidizheng seems  I've found some reason why the problem.

1. I use `result=os.popen(cmd)`   with a very high freq to fetch some app status.
2. When starting an application, the application will be blocked with a very high probability
3. I add log everywhere , then I found some stuck point when `os.open`
4. I change `os.open` to this code
```python
pipe = subprocess.Popen(cmd,shell=True,stdout=subprocess.PIPE)
lines = pipe.stdout.readlines()
pipe.stdout.close()
```
5. Fine . it's much better , and programs rarely get blocked
6. Throughout the afternoon, I  only found one endpoint was blocked, so I printed the stack information and flame chart with `py-spy`. I found  `grpc._channel` and `subprocess` may  have some system-level signal contention or  dead lock or something??  (because when  CPU100  they cost the same CPU time)

> stack info

![image](https://user-images.githubusercontent.com/23304239/70234356-6f209f00-179b-11ea-8b73-056e0ae43876.png)

> flame info 

![image](https://user-images.githubusercontent.com/23304239/70235035-fc182800-179c-11ea-8aaa-59f0d6b71630.png)


        [flame file link here   ](https://pan.baidu.com/s/1No4VQ5TwAu8tlxlIPWOcrQ)
        and file link code  is : **rc1k**

7. So I guess , the bug was here.

**Comment by charlesld** [comment] 2019-12-05 12:48
last comment , I use debain 9 and python 2.7.13

**Comment by lidizheng** [comment] 2019-12-05 19:27
Both `os.popen` and `subprocss.Popen` will trigger our fork handlers. The CPython implementation of those command is not ideal before 3.7 that it is using fork + exec pattern.

To make fork work properly, we registered a bunch of logic pre-fork and post-fork to manage FD / locks / threads. If you call a command with a very high frequency, it is likely to trigger some sort of data race.

So, can you try to set the environment variable `GRPC_ENABLE_FORK_SUPPORT=0`? If possible, please upgrade to Python 3.7+.

**Comment by charlesld** [comment] 2019-12-06 11:51
THx @lidizheng 
![image](https://user-images.githubusercontent.com/23304239/70321224-bc674400-1861-11ea-99c9-ee0e3bf62c07.png)

Emm.   I've modified this variable ， and  I am watching the effect。

**Comment by charlesld** [comment] 2019-12-12 06:36
@lidizheng  was `GRPC_ENABLE_FORK_SUPPORT` default set to `1`. I close it on my runtime , and it worked!

**Comment by lidizheng** [comment] 2019-12-12 21:38
@charlesld By default, it is turned on. Glad to see the deadlock not appearing again.

If the solution is acceptable, please close this issue.

**Comment by charlesld** [comment] 2019-12-13 02:37
Fine, thx again~~ @lidizheng 
![image](https://user-images.githubusercontent.com/23304239/70765076-8f9cba80-1d94-11ea-9504-fcce12db2ad2.png)

**Closed** 2019-12-13 02:38 UTC
Labels: disposition/requires reporter action, kind/bug, lang/Python, priority/P2
