### ISSUE TITLE
census_statistics_multiple_writers_circular_buffer_test seems broken

### ISSUE THREAD

**Issue by ctiller** [grpc/grpc#1775] opened 2015-05-27 23:45 UTC
Output from running on my laptop (continues 'forever'):

D0527 16:40:42.506037000 140735288091408 test_config.c:52] test slowdown: machine=1.000000 build=1.000000 total=1.000000
Starting test: multiple writers circular log
   Record size: 7
   Writer: 0
   Writer: 1
   Writer: 2
   Writer: 3
   Writer: 4
   Reader starting
   Writer 1: 1048576 out of 10485760 written
   Writer 2: 1048576 out of 10485760 written
   Writer 1: 2097153 out of 10485760 written
   Writer 2: 2097153 out of 10485760 written
   Writer 0: 1048576 out of 10485760 written
   Writer 1: 3145730 out of 10485760 written
   Writer 2: 3145730 out of 10485760 written
   Writer 3: 1048576 out of 10485760 written
   Writer 4: 1048576 out of 10485760 written
   Writer 1: 4194307 out of 10485760 written
   Writer 2: 4194307 out of 10485760 written
   Writer 1: 5242884 out of 10485760 written
   Writer 2: 5242884 out of 10485760 written
   Writer 0: 2097153 out of 10485760 written
   Writer 1: 6291461 out of 10485760 written
   Writer 2: 6291461 out of 10485760 written
   Writer 3: 2097153 out of 10485760 written
   Writer 4: 2097153 out of 10485760 written
   Writer 1: 7340038 out of 10485760 written
   Writer 2: 7340038 out of 10485760 written
   Writer 1: 8388615 out of 10485760 written
   Writer 2: 8388615 out of 10485760 written
   Writer 1: 9437192 out of 10485760 written
   Writer 0: 3145730 out of 10485760 written
   Writer 2: 9437192 out of 10485760 written
   Writer 4: 3145730 out of 10485760 written
   Writer 3: 3145730 out of 10485760 written
   Writer done: 1
   Writer done: 2
   Writer 4: 4194307 out of 10485760 written
   Writer 0: 4194307 out of 10485760 written
   Writer 3: 4194307 out of 10485760 written
   Writer 4: 5242884 out of 10485760 written
   Writer 0: 5242884 out of 10485760 written
   Writer 3: 5242884 out of 10485760 written
   Writer 4: 6291461 out of 10485760 written
   Writer 0: 6291461 out of 10485760 written
   Writer 3: 6291461 out of 10485760 written
   Writer 4: 7340038 out of 10485760 written
   Writer 0: 7340038 out of 10485760 written
   Writer 3: 7340038 out of 10485760 written
   Writer 4: 8388615 out of 10485760 written
   Writer 3: 8388615 out of 10485760 written
   Writer 0: 8388615 out of 10485760 written
   Writer 4: 9437192 out of 10485760 written
   Writer 3: 9437192 out of 10485760 written
   Writer 0: 9437192 out of 10485760 written
   Writer done: 4
   Writer done: 3
   Writer done: 0
   Reader: 49669804 out of 52428800 read
   Reader: 49669804 out of 52428800 read
   Reader: 49669804 out of 52428800 read
   Reader: 49669804 out of 52428800 read
   Reader: 49669804 out of 52428800 read
   Reader: 49669804 out of 52428800 read
   Reader: 49669804 out of 52428800 read
   Reader: 49669804 out of 52428800 read
   Reader: 49669804 out of 52428800 read
   Reader: 49669804 out of 52428800 read
   Reader: 49669804 out of 52428800 read
   Reader: 49669804 out of 52428800 read
   Reader: 49669804 out of 52428800 read
   Reader: 49669804 out of 52428800 read
   Reader: 49669804 out of 52428800 read
   Reader: 49669804 out of 52428800 read
   Reader: 49669804 out of 52428800 read
   Reader: 49669804 out of 52428800 read
   Reader: 49669804 out of 52428800 read
   Reader: 49669804 out of 52428800 read
   Reader: 49669804 out of 52428800 read
   Reader: 49669804 out of 52428800 read
   Reader: 49669804 out of 52428800 read
   Reader: 49669804 out of 52428800 read
   Reader: 49669804 out of 52428800 read
   Reader: 49669804 out of 52428800 read
   Reader: 49669804 out of 52428800 read
   Reader: 49669804 out of 52428800 read
   Reader: 49669804 out of 52428800 read
   Reader: 49669804 out of 52428800 read
   Reader: 49669804 out of 52428800 read
   Reader: 49669804 out of 52428800 read
   Reader: 49669804 out of 52428800 read
   Reader: 49669804 out of 52428800 read
   Reader: 49669804 out of 52428800 read
   Reader: 49669804 out of 52428800 read
   Reader: 49669804 out of 52428800 read
   Reader: 49669804 out of 52428800 read
   Reader: 49669804 out of 52428800 read
   Reader: 49669804 out of 52428800 read
   Reader: 49669804 out of 52428800 read
   Reader: 49669804 out of 52428800 read
   Reader: 49669804 out of 52428800 read
   Reader: 49669804 out of 52428800 read
   Reader: 49669804 out of 52428800 read
   Reader: 49669804 out of 52428800 read
   Reader: 49669804 out of 52428800 read
   Reader: 49669804 out of 52428800 read
   Reader: 49669804 out of 52428800 read
   Reader: 49669804 out of 52428800 read
   Reader: 49669804 out of 52428800 read
   Reader: 49669804 out of 52428800 read
   Reader: 49669804 out of 52428800 read
   Reader: 49669804 out of 52428800 read
   Reader: 49669804 out of 52428800 read
   Reader: 49669804 out of 52428800 read
   Reader: 49669804 out of 52428800 read
   Reader: 49669804 out of 52428800 read
   Reader: 49669804 out of 52428800 read
   Reader: 49669804 out of 52428800 read
   Reader: 49669804 out of 52428800 read
   Reader: 49669804 out of 52428800 read
   Reader: 49669804 out of 52428800 read
   Reader: 49669804 out of 52428800 read
   Reader: 49669804 out of 52428800 read
   Reader: 49669804 out of 52428800 read
   Reader: 49669804 out of 52428800 read
   Reader: 49669804 out of 52428800 read
   Reader: 49669804 out of 52428800 read
   Reader: 49669804 out of 52428800 read
   Reader: 49669804 out of 52428800 read
   Reader: 49669804 out of 52428800 read
   Reader: 49669804 out of 52428800 read
   Reader: 49669804 out of 52428800 read
   Reader: 49669804 out of 52428800 read
   Reader: 49669804 out of 52428800 read
   Reader: 49669804 out of 52428800 read
   Reader: 49669804 out of 52428800 read
   Reader: 49669804 out of 52428800 read
   Reader: 49669804 out of 52428800 read
   Reader: 49669804 out of 52428800 read
   Reader: 49669804 out of 52428800 read
   Reader: 49669804 out of 52428800 read
   Reader: 49669804 out of 52428800 read

**Comment by jayantkolhe** [comment] 2015-07-31 23:08
does this still repro?

**Comment by a-veitch** [comment] 2015-08-02 21:03
At the moment, this test is not being executed. I left the issue open, since we will need to reintroduce this code as part of the census implementation. (Although, for the record, I couldn't reproduce this myself at the time).

**Comment by a-veitch** [comment] 2016-02-05 22:42
This is obsolete. Closing.

**Closed by a-veitch** 2016-02-05 22:42 UTC
Labels: bug
