### ISSUE TITLE
Undefined symbols on MacOS Sierra

### ISSUE THREAD

**Issue by sab24** [grpc/grpc#8803] opened 2016-11-20 17:46 UTC
I have the following error:

[MAKE]    Generating cache.mk
[LD]      Linking /Users/user/Downloads/grpc/grpc/libs/opt/libgrpc.dylib
Undefined symbols for architecture x86_64:
  "_grpc_global_wakeup_fd", referenced from:
      _grpc_init_poll_posix in ev_poll_posix.o
      _grpc_init_poll_cv_posix in ev_poll_posix.o
      _pollset_work in ev_poll_posix.o
      _kick_poller in ev_poll_posix.o
      _shutdown_engine in ev_poll_posix.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [/Users/user/Downloads/grpc/grpc/libs/opt/libgrpc.dylib] Error 1

grpc_global_wakeup_fd seems to be defined in ev_epoll_linux.c and ev_poll_posix.c but they are not compiled on MacOS?

The commands I used were:
git clone -b $(curl -L http://grpc.io/release) https://github.com/grpc/grpc
cd grpc
git submodule update --init
rm -r ./third_party/nanopb
git checkout master
cd third_party
cd protobuf
git checkout master
cd ../..
make

The last successful version that compiled was ea3b568b8 before the merge with upcoming/master in 43944082. 

The command that fails is

 cc -L/opt/local/lib -g   \
 -fPIC  \
 -Llibs/opt \
 -L/opt/local/lib \
 -L/usr/local/lib \
 -L/opt/local/lib  \
 -L/Users/user/Downloads/grpc/grpc/libs/opt \
 -install_name libgrpc.dylib \
 -dynamiclib \
 -o /Users/user/Downloads/grpc/grpc/libs/opt/libgrpc.dylib \
 /Users/user/Downloads/grpc/grpc/objs/opt/src/core/lib/surface/init.o \
 /Users/user/Downloads/grpc/grpc/objs/opt/src/core/lib/channel/channel_args.o \
 /Users/user/Downloads/grpc/grpc/objs/opt/src/core/lib/channel/channel_stack.o \
 /Users/user/Downloads/grpc/grpc/objs/opt/src/core/lib/channel/channel_stack_builder.o \
 /Users/user/Downloads/grpc/grpc/objs/opt/src/core/lib/channel/compress_filter.o \
 /Users/user/Downloads/grpc/grpc/objs/opt/src/core/lib/channel/connected_channel.o \
 /Users/user/Downloads/grpc/grpc/objs/opt/src/core/lib/channel/deadline_filter.o \
 /Users/user/Downloads/grpc/grpc/objs/opt/src/core/lib/channel/handshaker.o \
 /Users/user/Downloads/grpc/grpc/objs/opt/src/core/lib/channel/http_client_filter.o \
 /Users/user/Downloads/grpc/grpc/objs/opt/src/core/lib/channel/http_server_filter.o \
 /Users/user/Downloads/grpc/grpc/objs/opt/src/core/lib/channel/message_size_filter.o \
 /Users/user/Downloads/grpc/grpc/objs/opt/src/core/lib/compression/compression.o \
 /Users/user/Downloads/grpc/grpc/objs/opt/src/core/lib/compression/message_compress.o \
 /Users/user/Downloads/grpc/grpc/objs/opt/src/core/lib/debug/trace.o \
 /Users/user/Downloads/grpc/grpc/objs/opt/src/core/lib/http/format_request.o \
 /Users/user/Downloads/grpc/grpc/objs/opt/src/core/lib/http/httpcli.o \
 /Users/user/Downloads/grpc/grpc/objs/opt/src/core/lib/http/parser.o \
 /Users/user/Downloads/grpc/grpc/objs/opt/src/core/lib/iomgr/closure.o \
 /Users/user/Downloads/grpc/grpc/objs/opt/src/core/lib/iomgr/combiner.o \
 /Users/user/Downloads/grpc/grpc/objs/opt/src/core/lib/iomgr/endpoint.o \
 /Users/user/Downloads/grpc/grpc/objs/opt/src/core/lib/iomgr/endpoint_pair_posix.o \
 /Users/user/Downloads/grpc/grpc/objs/opt/src/core/lib/iomgr/endpoint_pair_uv.o \
 /Users/user/Downloads/grpc/grpc/objs/opt/src/core/lib/iomgr/endpoint_pair_windows.o \
 /Users/user/Downloads/grpc/grpc/objs/opt/src/core/lib/iomgr/error.o \
 /Users/user/Downloads/grpc/grpc/objs/opt/src/core/lib/iomgr/ev_epoll_linux.o \
 /Users/user/Downloads/grpc/grpc/objs/opt/src/core/lib/iomgr/ev_poll_posix.o \
 /Users/user/Downloads/grpc/grpc/objs/opt/src/core/lib/iomgr/ev_posix.o \
 /Users/user/Downloads/grpc/grpc/objs/opt/src/core/lib/iomgr/exec_ctx.o \
 /Users/user/Downloads/grpc/grpc/objs/opt/src/core/lib/iomgr/executor.o \
 /Users/user/Downloads/grpc/grpc/objs/opt/src/core/lib/iomgr/iocp_windows.o \
 /Users/user/Downloads/grpc/grpc/objs/opt/src/core/lib/iomgr/iomgr.o \
 /Users/user/Downloads/grpc/grpc/objs/opt/src/core/lib/iomgr/iomgr_posix.o \
 /Users/user/Downloads/grpc/grpc/objs/opt/src/core/lib/iomgr/iomgr_uv.o \
 /Users/user/Downloads/grpc/grpc/objs/opt/src/core/lib/iomgr/iomgr_windows.o \
 /Users/user/Downloads/grpc/grpc/objs/opt/src/core/lib/iomgr/load_file.o \
 /Users/user/Downloads/grpc/grpc/objs/opt/src/core/lib/iomgr/network_status_tracker.o \
 /Users/user/Downloads/grpc/grpc/objs/opt/src/core/lib/iomgr/polling_entity.o \
 /Users/user/Downloads/grpc/grpc/objs/opt/src/core/lib/iomgr/pollset_set_uv.o \
 /Users/user/Downloads/grpc/grpc/objs/opt/src/core/lib/iomgr/pollset_set_windows.o \
 /Users/user/Downloads/grpc/grpc/objs/opt/src/core/lib/iomgr/pollset_uv.o \
 /Users/user/Downloads/grpc/grpc/objs/opt/src/core/lib/iomgr/pollset_windows.o \
 /Users/user/Downloads/grpc/grpc/objs/opt/src/core/lib/iomgr/resolve_address_posix.o \
 /Users/user/Downloads/grpc/grpc/objs/opt/src/core/lib/iomgr/resolve_address_uv.o \
 /Users/user/Downloads/grpc/grpc/objs/opt/src/core/lib/iomgr/resolve_address_windows.o \
 /Users/user/Downloads/grpc/grpc/objs/opt/src/core/lib/iomgr/resource_quota.o \
 /Users/user/Downloads/grpc/grpc/objs/opt/src/core/lib/iomgr/sockaddr_utils.o \
 /Users/user/Downloads/grpc/grpc/objs/opt/src/core/lib/iomgr/socket_mutator.o \
 /Users/user/Downloads/grpc/grpc/objs/opt/src/core/lib/iomgr/socket_utils_common_posix.o \
 /Users/user/Downloads/grpc/grpc/objs/opt/src/core/lib/iomgr/socket_utils_linux.o \
 /Users/user/Downloads/grpc/grpc/objs/opt/src/core/lib/iomgr/socket_utils_posix.o \
 /Users/user/Downloads/grpc/grpc/objs/opt/src/core/lib/iomgr/socket_utils_uv.o \
 /Users/user/Downloads/grpc/grpc/objs/opt/src/core/lib/iomgr/socket_utils_windows.o \
 /Users/user/Downloads/grpc/grpc/objs/opt/src/core/lib/iomgr/socket_windows.o \
 /Users/user/Downloads/grpc/grpc/objs/opt/src/core/lib/iomgr/tcp_client_posix.o \
 /Users/user/Downloads/grpc/grpc/objs/opt/src/core/lib/iomgr/tcp_client_uv.o \
 /Users/user/Downloads/grpc/grpc/objs/opt/src/core/lib/iomgr/tcp_client_windows.o \
 /Users/user/Downloads/grpc/grpc/objs/opt/src/core/lib/iomgr/tcp_posix.o \
 /Users/user/Downloads/grpc/grpc/objs/opt/src/core/lib/iomgr/tcp_server_posix.o \
 /Users/user/Downloads/grpc/grpc/objs/opt/src/core/lib/iomgr/tcp_server_uv.o \
 /Users/user/Downloads/grpc/grpc/objs/opt/src/core/lib/iomgr/tcp_server_windows.o \
 /Users/user/Downloads/grpc/grpc/objs/opt/src/core/lib/iomgr/tcp_uv.o \
 /Users/user/Downloads/grpc/grpc/objs/opt/src/core/lib/iomgr/tcp_windows.o \
 /Users/user/Downloads/grpc/grpc/objs/opt/src/core/lib/iomgr/time_averaged_stats.o \
 /Users/user/Downloads/grpc/grpc/objs/opt/src/core/lib/iomgr/timer_generic.o \
 /Users/user/Downloads/grpc/grpc/objs/opt/src/core/lib/iomgr/timer_heap.o \
 /Users/user/Downloads/grpc/grpc/objs/opt/src/core/lib/iomgr/timer_uv.o \
 /Users/user/Downloads/grpc/grpc/objs/opt/src/core/lib/iomgr/udp_server.o \
 /Users/user/Downloads/grpc/grpc/objs/opt/src/core/lib/iomgr/unix_sockets_posix.o \
 /Users/user/Downloads/grpc/grpc/objs/opt/src/core/lib/iomgr/unix_sockets_posix_noop.o \
 /Users/user/Downloads/grpc/grpc/objs/opt/src/core/lib/iomgr/wakeup_fd_cv.o \
 /Users/user/Downloads/grpc/grpc/objs/opt/src/core/lib/iomgr/wakeup_fd_eventfd.o \
 /Users/user/Downloads/grpc/grpc/objs/opt/src/core/lib/iomgr/wakeup_fd_nospecial.o \
 /Users/user/Downloads/grpc/grpc/objs/opt/src/core/lib/iomgr/wakeup_fd_pipe.o \
 /Users/user/Downloads/grpc/grpc/objs/opt/src/core/lib/iomgr/wakeup_fd_posix.o \
 /Users/user/Downloads/grpc/grpc/objs/opt/src/core/lib/iomgr/workqueue_uv.o \
 /Users/user/Downloads/grpc/grpc/objs/opt/src/core/lib/iomgr/workqueue_windows.o \
 /Users/user/Downloads/grpc/grpc/objs/opt/src/core/lib/json/json.o \
 /Users/user/Downloads/grpc/grpc/objs/opt/src/core/lib/json/json_reader.o \
 /Users/user/Downloads/grpc/grpc/objs/opt/src/core/lib/json/json_string.o \
 /Users/user/Downloads/grpc/grpc/objs/opt/src/core/lib/json/json_writer.o \
 /Users/user/Downloads/grpc/grpc/objs/opt/src/core/lib/slice/percent_encoding.o \
 /Users/user/Downloads/grpc/grpc/objs/opt/src/core/lib/slice/slice.o \
 /Users/user/Downloads/grpc/grpc/objs/opt/src/core/lib/slice/slice_buffer.o \
 /Users/user/Downloads/grpc/grpc/objs/opt/src/core/lib/slice/slice_string_helpers.o \
 /Users/user/Downloads/grpc/grpc/objs/opt/src/core/lib/surface/alarm.o \
 /Users/user/Downloads/grpc/grpc/objs/opt/src/core/lib/surface/api_trace.o \
 /Users/user/Downloads/grpc/grpc/objs/opt/src/core/lib/surface/byte_buffer.o \
 /Users/user/Downloads/grpc/grpc/objs/opt/src/core/lib/surface/byte_buffer_reader.o \
 /Users/user/Downloads/grpc/grpc/objs/opt/src/core/lib/surface/call.o \
 /Users/user/Downloads/grpc/grpc/objs/opt/src/core/lib/surface/call_details.o \
 /Users/user/Downloads/grpc/grpc/objs/opt/src/core/lib/surface/call_log_batch.o \
 /Users/user/Downloads/grpc/grpc/objs/opt/src/core/lib/surface/channel.o \
 /Users/user/Downloads/grpc/grpc/objs/opt/src/core/lib/surface/channel_init.o \
 /Users/user/Downloads/grpc/grpc/objs/opt/src/core/lib/surface/channel_ping.o \
 /Users/user/Downloads/grpc/grpc/objs/opt/src/core/lib/surface/channel_stack_type.o \
 /Users/user/Downloads/grpc/grpc/objs/opt/src/core/lib/surface/completion_queue.o \
 /Users/user/Downloads/grpc/grpc/objs/opt/src/core/lib/surface/event_string.o \
 /Users/user/Downloads/grpc/grpc/objs/opt/src/core/lib/surface/lame_client.o \
 /Users/user/Downloads/grpc/grpc/objs/opt/src/core/lib/surface/metadata_array.o \
 /Users/user/Downloads/grpc/grpc/objs/opt/src/core/lib/surface/server.o \
 /Users/user/Downloads/grpc/grpc/objs/opt/src/core/lib/surface/validate_metadata.o \
 /Users/user/Downloads/grpc/grpc/objs/opt/src/core/lib/surface/version.o \
 /Users/user/Downloads/grpc/grpc/objs/opt/src/core/lib/transport/byte_stream.o \
 /Users/user/Downloads/grpc/grpc/objs/opt/src/core/lib/transport/connectivity_state.o \
 /Users/user/Downloads/grpc/grpc/objs/opt/src/core/lib/transport/mdstr_hash_table.o \
 /Users/user/Downloads/grpc/grpc/objs/opt/src/core/lib/transport/metadata.o \
 /Users/user/Downloads/grpc/grpc/objs/opt/src/core/lib/transport/metadata_batch.o \
 /Users/user/Downloads/grpc/grpc/objs/opt/src/core/lib/transport/pid_controller.o \
 /Users/user/Downloads/grpc/grpc/objs/opt/src/core/lib/transport/service_config.o \
 /Users/user/Downloads/grpc/grpc/objs/opt/src/core/lib/transport/static_metadata.o \
 /Users/user/Downloads/grpc/grpc/objs/opt/src/core/lib/transport/timeout_encoding.o \
 /Users/user/Downloads/grpc/grpc/objs/opt/src/core/lib/transport/transport.o \
 /Users/user/Downloads/grpc/grpc/objs/opt/src/core/lib/transport/transport_op_string.o \
 /Users/user/Downloads/grpc/grpc/objs/opt/src/core/ext/transport/chttp2/server/secure/server_secure_chttp2.o \
 /Users/user/Downloads/grpc/grpc/objs/opt/src/core/ext/transport/chttp2/transport/bin_decoder.o \
 /Users/user/Downloads/grpc/grpc/objs/opt/src/core/ext/transport/chttp2/transport/bin_encoder.o \
 /Users/user/Downloads/grpc/grpc/objs/opt/src/core/ext/transport/chttp2/transport/chttp2_plugin.o \
 /Users/user/Downloads/grpc/grpc/objs/opt/src/core/ext/transport/chttp2/transport/chttp2_transport.o \
 /Users/user/Downloads/grpc/grpc/objs/opt/src/core/ext/transport/chttp2/transport/frame_data.o \
 /Users/user/Downloads/grpc/grpc/objs/opt/src/core/ext/transport/chttp2/transport/frame_goaway.o \
 /Users/user/Downloads/grpc/grpc/objs/opt/src/core/ext/transport/chttp2/transport/frame_ping.o \
 /Users/user/Downloads/grpc/grpc/objs/opt/src/core/ext/transport/chttp2/transport/frame_rst_stream.o \
 /Users/user/Downloads/grpc/grpc/objs/opt/src/core/ext/transport/chttp2/transport/frame_settings.o \
 /Users/user/Downloads/grpc/grpc/objs/opt/src/core/ext/transport/chttp2/transport/frame_window_update.o \
 /Users/user/Downloads/grpc/grpc/objs/opt/src/core/ext/transport/chttp2/transport/hpack_encoder.o \
 /Users/user/Downloads/grpc/grpc/objs/opt/src/core/ext/transport/chttp2/transport/hpack_parser.o \
 /Users/user/Downloads/grpc/grpc/objs/opt/src/core/ext/transport/chttp2/transport/hpack_table.o \
 /Users/user/Downloads/grpc/grpc/objs/opt/src/core/ext/transport/chttp2/transport/huffsyms.o \
 /Users/user/Downloads/grpc/grpc/objs/opt/src/core/ext/transport/chttp2/transport/incoming_metadata.o \
 /Users/user/Downloads/grpc/grpc/objs/opt/src/core/ext/transport/chttp2/transport/parsing.o \
 /Users/user/Downloads/grpc/grpc/objs/opt/src/core/ext/transport/chttp2/transport/status_conversion.o \
 /Users/user/Downloads/grpc/grpc/objs/opt/src/core/ext/transport/chttp2/transport/stream_lists.o \
 /Users/user/Downloads/grpc/grpc/objs/opt/src/core/ext/transport/chttp2/transport/stream_map.o \
 /Users/user/Downloads/grpc/grpc/objs/opt/src/core/ext/transport/chttp2/transport/varint.o \
 /Users/user/Downloads/grpc/grpc/objs/opt/src/core/ext/transport/chttp2/transport/writing.o \
 /Users/user/Downloads/grpc/grpc/objs/opt/src/core/ext/transport/chttp2/alpn/alpn.o \
 /Users/user/Downloads/grpc/grpc/objs/opt/src/core/lib/http/httpcli_security_connector.o \
 /Users/user/Downloads/grpc/grpc/objs/opt/src/core/lib/security/context/security_context.o \
 /Users/user/Downloads/grpc/grpc/objs/opt/src/core/lib/security/credentials/composite/composite_credentials.o \
 /Users/user/Downloads/grpc/grpc/objs/opt/src/core/lib/security/credentials/credentials.o \
 /Users/user/Downloads/grpc/grpc/objs/opt/src/core/lib/security/credentials/credentials_metadata.o \
 /Users/user/Downloads/grpc/grpc/objs/opt/src/core/lib/security/credentials/fake/fake_credentials.o \
 /Users/user/Downloads/grpc/grpc/objs/opt/src/core/lib/security/credentials/google_default/credentials_generic.o \
 /Users/user/Downloads/grpc/grpc/objs/opt/src/core/lib/security/credentials/google_default/google_default_credentials.o \
 /Users/user/Downloads/grpc/grpc/objs/opt/src/core/lib/security/credentials/iam/iam_credentials.o \
 /Users/user/Downloads/grpc/grpc/objs/opt/src/core/lib/security/credentials/jwt/json_token.o \
 /Users/user/Downloads/grpc/grpc/objs/opt/src/core/lib/security/credentials/jwt/jwt_credentials.o \
 /Users/user/Downloads/grpc/grpc/objs/opt/src/core/lib/security/credentials/jwt/jwt_verifier.o \
 /Users/user/Downloads/grpc/grpc/objs/opt/src/core/lib/security/credentials/oauth2/oauth2_credentials.o \
 /Users/user/Downloads/grpc/grpc/objs/opt/src/core/lib/security/credentials/plugin/plugin_credentials.o \
 /Users/user/Downloads/grpc/grpc/objs/opt/src/core/lib/security/credentials/ssl/ssl_credentials.o \
 /Users/user/Downloads/grpc/grpc/objs/opt/src/core/lib/security/transport/client_auth_filter.o \
 /Users/user/Downloads/grpc/grpc/objs/opt/src/core/lib/security/transport/handshake.o \
 /Users/user/Downloads/grpc/grpc/objs/opt/src/core/lib/security/transport/secure_endpoint.o \
 /Users/user/Downloads/grpc/grpc/objs/opt/src/core/lib/security/transport/security_connector.o \
 /Users/user/Downloads/grpc/grpc/objs/opt/src/core/lib/security/transport/server_auth_filter.o \
 /Users/user/Downloads/grpc/grpc/objs/opt/src/core/lib/security/transport/tsi_error.o \
 /Users/user/Downloads/grpc/grpc/objs/opt/src/core/lib/security/util/b64.o \
 /Users/user/Downloads/grpc/grpc/objs/opt/src/core/lib/security/util/json_util.o \
 /Users/user/Downloads/grpc/grpc/objs/opt/src/core/lib/surface/init_secure.o \
 /Users/user/Downloads/grpc/grpc/objs/opt/src/core/lib/tsi/fake_transport_security.o \
 /Users/user/Downloads/grpc/grpc/objs/opt/src/core/lib/tsi/ssl_transport_security.o \
 /Users/user/Downloads/grpc/grpc/objs/opt/src/core/lib/tsi/transport_security.o \
 /Users/user/Downloads/grpc/grpc/objs/opt/src/core/ext/transport/chttp2/client/secure/secure_channel_create.o \
 /Users/user/Downloads/grpc/grpc/objs/opt/src/core/ext/client_channel/channel_connectivity.o \
 /Users/user/Downloads/grpc/grpc/objs/opt/src/core/ext/client_channel/client_channel.o \
 /Users/user/Downloads/grpc/grpc/objs/opt/src/core/ext/client_channel/client_channel_factory.o \
 /Users/user/Downloads/grpc/grpc/objs/opt/src/core/ext/client_channel/client_channel_plugin.o \
 /Users/user/Downloads/grpc/grpc/objs/opt/src/core/ext/client_channel/connector.o \
 /Users/user/Downloads/grpc/grpc/objs/opt/src/core/ext/client_channel/default_initial_connect_string.o \
 /Users/user/Downloads/grpc/grpc/objs/opt/src/core/ext/client_channel/http_connect_handshaker.o \
 /Users/user/Downloads/grpc/grpc/objs/opt/src/core/ext/client_channel/initial_connect_string.o \
 /Users/user/Downloads/grpc/grpc/objs/opt/src/core/ext/client_channel/lb_policy.o \
 /Users/user/Downloads/grpc/grpc/objs/opt/src/core/ext/client_channel/lb_policy_factory.o \
 /Users/user/Downloads/grpc/grpc/objs/opt/src/core/ext/client_channel/lb_policy_registry.o \
 /Users/user/Downloads/grpc/grpc/objs/opt/src/core/ext/client_channel/parse_address.o \
 /Users/user/Downloads/grpc/grpc/objs/opt/src/core/ext/client_channel/resolver.o \
 /Users/user/Downloads/grpc/grpc/objs/opt/src/core/ext/client_channel/resolver_factory.o \
 /Users/user/Downloads/grpc/grpc/objs/opt/src/core/ext/client_channel/resolver_registry.o \
 /Users/user/Downloads/grpc/grpc/objs/opt/src/core/ext/client_channel/subchannel.o \
 /Users/user/Downloads/grpc/grpc/objs/opt/src/core/ext/client_channel/subchannel_index.o \
 /Users/user/Downloads/grpc/grpc/objs/opt/src/core/ext/client_channel/uri_parser.o \
 /Users/user/Downloads/grpc/grpc/objs/opt/src/core/ext/transport/chttp2/server/insecure/server_chttp2.o \
 /Users/user/Downloads/grpc/grpc/objs/opt/src/core/ext/transport/chttp2/server/insecure/server_chttp2_posix.o \
 /Users/user/Downloads/grpc/grpc/objs/opt/src/core/ext/transport/chttp2/client/insecure/channel_create.o \
 /Users/user/Downloads/grpc/grpc/objs/opt/src/core/ext/transport/chttp2/client/insecure/channel_create_posix.o \
 /Users/user/Downloads/grpc/grpc/objs/opt/src/core/ext/lb_policy/grpclb/grpclb.o \
 /Users/user/Downloads/grpc/grpc/objs/opt/src/core/ext/lb_policy/grpclb/load_balancer_api.o \
 /Users/user/Downloads/grpc/grpc/objs/opt/src/core/ext/lb_policy/grpclb/proto/grpc/lb/v1/load_balancer.pb.o \
 /Users/user/Downloads/grpc/grpc/objs/opt/third_party/nanopb/pb_common.o \
 /Users/user/Downloads/grpc/grpc/objs/opt/third_party/nanopb/pb_decode.o \
 /Users/user/Downloads/grpc/grpc/objs/opt/third_party/nanopb/pb_encode.o \
 /Users/user/Downloads/grpc/grpc/objs/opt/src/core/ext/lb_policy/pick_first/pick_first.o \
 /Users/user/Downloads/grpc/grpc/objs/opt/src/core/ext/lb_policy/round_robin/round_robin.o \
 /Users/user/Downloads/grpc/grpc/objs/opt/src/core/ext/resolver/dns/native/dns_resolver.o \
 /Users/user/Downloads/grpc/grpc/objs/opt/src/core/ext/resolver/sockaddr/sockaddr_resolver.o \
 /Users/user/Downloads/grpc/grpc/objs/opt/src/core/ext/load_reporting/load_reporting.o \
 /Users/user/Downloads/grpc/grpc/objs/opt/src/core/ext/load_reporting/load_reporting_filter.o \
 /Users/user/Downloads/grpc/grpc/objs/opt/src/core/ext/census/base_resources.o \
 /Users/user/Downloads/grpc/grpc/objs/opt/src/core/ext/census/context.o \
 /Users/user/Downloads/grpc/grpc/objs/opt/src/core/ext/census/gen/census.pb.o \
 /Users/user/Downloads/grpc/grpc/objs/opt/src/core/ext/census/gen/trace_context.pb.o \
 /Users/user/Downloads/grpc/grpc/objs/opt/src/core/ext/census/grpc_context.o \
 /Users/user/Downloads/grpc/grpc/objs/opt/src/core/ext/census/grpc_filter.o \
 /Users/user/Downloads/grpc/grpc/objs/opt/src/core/ext/census/grpc_plugin.o \
 /Users/user/Downloads/grpc/grpc/objs/opt/src/core/ext/census/initialize.o \
 /Users/user/Downloads/grpc/grpc/objs/opt/src/core/ext/census/mlog.o \
 /Users/user/Downloads/grpc/grpc/objs/opt/src/core/ext/census/operation.o \
 /Users/user/Downloads/grpc/grpc/objs/opt/src/core/ext/census/placeholders.o \
 /Users/user/Downloads/grpc/grpc/objs/opt/src/core/ext/census/resource.o \
 /Users/user/Downloads/grpc/grpc/objs/opt/src/core/ext/census/trace_context.o \
 /Users/user/Downloads/grpc/grpc/objs/opt/src/core/ext/census/tracing.o \
 /Users/user/Downloads/grpc/grpc/objs/opt/src/core/plugin_registry/grpc_plugin_registry.o \
 -lm  \
 -lz \
 -lz \
 /Users/user/Downloads/grpc/grpc/libs/opt/libgpr.a \
  -lssl \
 -lcrypto

**Comment by ncteisen** [comment] 2016-11-22 20:17
Duplicate of #8766

**Comment by nathanielmanistaatgoogle** [comment] 2016-11-22 20:49
Closing as a duplicate of [issue 8766](https://github.com/grpc/grpc/issues/8766).

**Closed by nathanielmanistaatgoogle** 2016-11-22 20:49 UTC
Labels: duplicate, MacOS
