### ISSUE TITLE
Provide a debian package for installing core grpc

### ISSUE THREAD

**Issue by jtattermusch** [grpc/grpc#662] opened 2015-02-20 19:30 UTC

**Comment by tbetbetbe** [comment] 2015-05-08 21:09
Paraphrasing rom @nicolasnoble as a starting point for what should be built:

In true debian packages fashion, there has to be at least 5 packages built out of the source tree: 
- [ ] grpc: ~ `make static_c shared_c`
- [ ] grpc-dev: ~ `make static_c shared_c`
- [ ] grpc++: ~ `make static_cxx shared_cxx`
- [ ] grpc++-dev: ~ `make static_cxx shared_cxx`
- [ ] grpc-plugins: ~ `make plugins`

- The grpc and grpc-dev packages would, in fact, be the result of the C-core compilation; these do NOT depend on protobuf at all, only OpenSSL.
- The grpc++, grpc++-dev and grpc-plugins are the ones that depend on protobuf.
- grpc-plugins should also depend on the protoc package - it wouldn't have any other dependency than protobuf and protoc. 
- grpc++ and grpc++-dev wouldn't have any other dependency than grpc and grpc-dev.

**Comment by andrewpollock** [comment] 2015-05-21 04:44
I've made good progress today. I have a package building, I just need to get it Lintian-clean, and then figure out how to generate a pull request.

I've also filed an ITP: http://bugs.debian.org/786375

**Comment by andrewpollock** [comment] 2015-05-21 23:51
I've made contact with the protobuf package maintainer, and also another Debian Developer who was also working on packaging grpc. I think we're going to be able to join forces to a degree. The protobuf package maintainer has said I can prepare a package of protobuf 3 for targeting to experimental, so I'll work on that also.

**Comment by andrewpollock** [comment] 2015-05-21 23:54
I've made contact with the Debian maintainer of protobuf and also my ITP flushed out another Debian Developer who was also working on packaging grpc. I think we're going to join forces.

The protobuf maintainer is open to me working on packaging protobuf 3 and targeting it to experimental, so the next time I do some 20% work, I'll look into that.

**Comment by andrewpollock** [comment] 2015-06-29 06:51
Okay so the packaging is in a pretty good state now. How far off is a 1.0 release that is vaguely stable? If it's far off, I'm inclined to upload 0.9.1 to experimental as a starting point, and then work on getting protobuf 3 into experimental.

**Comment by nicolasnoble** [comment] 2015-06-30 00:54
We definitely would like to have a 0.9.x package uploaded to experimental. We're most likely to have ~0.11.x for Beta before we have a 1.0.x release.

With the NPN fallback, which means that gRPC no longer requires OpenSSL 1.0.2+, we can even make Debian unstable, or Ubuntu packages.

**Comment by nicolasnoble** [comment] 2015-07-13 20:32
I think this one is done.

**Comment by andrewpollock** [comment] 2015-08-04 01:51
I've just built and uploaded 0.10 to Debian unstable. It will appear at https://ftp-master.debian.org/new.html shortly.

FYI, I had to build with tests disabled because chttp2_socket_pair_with_grpc_trace_invoke_large_request_test kept failing. I'm not sure if the Debian autobuilders build with tests enabled or not, but this failing test will be a problem if they do and it fails there.

**Comment by jgeewax** [comment] 2015-08-04 19:11
@andrewpollock Where can I download the .deb file...? I see listings of contents, etc but no file itself.

/cc @dhermes

**Comment by dhermes** [comment] 2015-08-27 18:02
https://packages.debian.org/unstable/libgrpc-dev
http://http.us.debian.org/debian/pool/main/g/grpc/libgrpc-dev_0.10.0-1_amd64.deb

**Comment by tbetbetbe** [comment] 2015-08-31 13:51
FYI: the package is now part of debian-testing: https://packages.debian.org/testing/libgrpc-dev which is much more stable.

Please note that if you download the .deb file directly and attempt to use it on non-testing system, there is s significant risk of a failure occurring due to incorrect dependencies

**Comment by dhermes** [comment] 2015-08-31 16:19
Which dependencies are also in `testing`? `libgrpc0` seems to be the only one that `libgrpc-dev` depends on.

**Comment by tbetbetbe** [comment] 2015-08-31 18:11
The risk is related to mismatches between [libgrpc0's dependencies](https://packages.debian.org/unstable/main/libgrpc0) and the target system.

**Comment by dhermes** [comment] 2015-08-31 18:54
So we're still at a point where real users on real machines should not / can not install via `apt-get`?

Which dependencies pose a problem? Is `dep: libssl1.0.0 (>= 1.0.2~beta3)` one of them? (I thought the upstream SSL issue was resolved with the NPN / ALPN support.)

**Comment by andrewpollock** [comment] 2015-08-31 21:38
Grpc won't transition into testing if all of its dependencies aren't also
installable in testing.

**Comment by dhermes** [comment] 2015-08-31 21:40
@andrewpollock I'm interpreting that as "it can't have any dependencies in stable (or in unstable)". Is that not correct?

**Comment by nicolasnoble** [comment] 2015-08-31 21:45
I would argue that real users on real machines are widely using testing or even unstable versions of Debian. I'll just take some time for the package to trickle down into stable. But as of right now, a lot of people can use it using apt-get.

**Comment by dhermes** [comment] 2015-09-01 18:05
Where's the data for that assertion?

Also, it's still unclear if "all of its dependencies aren't also installable in testing" means that it can't have any stable dependencies.

**Comment by dhermes** [comment] 2015-09-01 18:20
Cool! I didn't know popcon existed!

**Comment by andrewpollock** [comment] 2015-09-03 01:15
Let me try and think of another way to word this...

Okay, the grpc binary packages have a set of dependencies. These are mostly calculated automatically at build time. For additional explicit dependencies, they're normally unversioned unless there's a particular reason to declare an explicit version (and that will then impact on installability based on which distributions that explicit versioned dependency can be satisfied on).

Here's a snippet from debian/control:

~~~
Package: libgrpc-dev
Depends: libgrpc0 (= ${binary:Version}), ${misc:Depends}

Package: libgrpc0
Depends: ${shlibs:Depends}, ${misc:Depends}
~~~

When the package gets built (in unstable, because that's the entry point for packages), this gets expanded by debhelper out to be

~~~
Package: libgrpc-dev
Depends: libgrpc0 (= 0.10.2-2)

Package: libgrpc0
Depends: libc6 (>= 2.17), libgoogle-perftools4, libssl1.0.0 (>= 1.0.2~beta3), zlib1g (>= 1:1.1.4)
~~~

So in terms of when the package can and will transition from unstable to testing, it depends on a few factors:

1) No new release-critical severity bugs were opened against it whilst it was in unstable
2) The "urgency" of the upload (set in the changelog, normally set to low == 10 days)
3) The availability of all of its dependencies in testing

So you can see here that libgrpc0 has a few additional dependencies. You can check on what versions are available in testing with the rmadison tool:

~~~
$ rmadison -u debian -s testing libc6 libgoogle-perftools4 libssl1.0.0 zlib1g
debian:
 libc6                | 2.19-19           | stretch | amd64, arm64, armel, armhf, i386, mips, mipsel, powerpc, ppc64el, s390x
 libgoogle-perftools4 | 2.2.1-0.2         | stretch | amd64, arm64, armel, armhf, i386, powerpc, ppc64el
 libssl1.0.0          | 1.0.2d-1          | stretch | amd64, arm64, armel, armhf, i386, mips, mipsel, powerpc, ppc64el, s390x
 zlib1g               | 1:1.2.8.dfsg-2+b1 | stretch | amd64, arm64, armel, armhf, i386, mips, mipsel, powerpc, ppc64el, s390x
~~~

So you can see here that all of the versions are >= than the dependencies declared, so only criteria 1 and 2 above will apply to the timing of the package transitioning into testing.

Practically, a more holistic package overview is available at http://packages.qa.debian.org/grpc

**Comment by andrewpollock** [comment] 2015-09-03 01:19
And just to update this bug on the current state of things, we have:

C bindings in unstable and testing, and backported to stable (i.e. in jessie-backports)
C# bindings in progress

Once I've backported 0.10.2 to jessie I'll be focusing my attention on updating the protobuf package so that the C++ bindings can be packaged.

**Comment by tbetbetbe** [comment] 2015-09-04 21:58
Closing this issue - the necessary work has been completed:

- There is an installable package for [debian stable](https://packages.debian.org/search?keywords=grpc&searchon=names&section=all&suite=jessie-backports)
- The install instructions for users have been updated to reflect this #3246
- C# bindings are a separate issue tracked at #3087 

Please feel free to re-open if there omissions; it's also makes sense to post to this issue to continue any of the discussions that we've started on it.

**Comment by dhermes** [comment] 2015-09-10 20:41
FYI, when adding jessie-backports to my machine, after `apt-get update` I got a warning that isn't great to see:

```
W: GPG error: http://http.debian.net jessie-backports InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 8B48AD6246925553 NO_PUBKEY 7638D0442B90D010
```

**Comment by dhermes** [comment] 2015-09-19 17:15
I can't re-open for some reason.

I finally got around to running `sudo apt-get install libgrpc-dev` and got another scary message

```
WARNING: The following packages cannot be authenticated!
  libgrpc0 libgrpc-dev
Install these packages without verification? [y/N]
```

then when trying to installing the beta (`0.11.0b0`) library it failed:
https://gist.github.com/dhermes/bec8ab731349c175f7d1

/cc @nathanielmanistaatgoogle

**Comment by tbetbetbe** [comment] 2015-09-26 14:58
> WARNING: The following packages cannot be authenticated!

That is related to the early warning about jessie backports
That's the thing that really needs investigating

> W: GPG error: http://http.debian.net jessie-backports 

At the moment, we're not able to reproduce this, and it'd be useful to have more details about your machine's set-up to help diagnose the problem

**Comment by tbetbetbe** [comment] 2015-09-26 15:00
> https://gist.github.com/dhermes/bec8ab731349c175f7d1

Can you try this again ? It's likely that were trying to install the beta python package against the alpha debian package.  That should no longer be the case.

**Comment by dhermes** [comment] 2015-09-28 18:17
RE: My (laptop) machine's set-up, it's running Ubuntu 14.04 and it's a standard Lenovo PC (nothing fancy other than upgraded RAM). The warnings happened on both my desktop and laptop (identical OS and settings).

I can bring my laptop in to see you guys if you like?

----

Yeah I talked to @nathanielmanistaatgoogle after posting this and he told me that `0.11.0b0` would only work with the core stuff from `HEAD`.

I have no issue getting alpha installed for local dev, which is fine for now. I was trying to update my codebase to use the beta API but will hold off until it hits the packaging pipelines.

**Comment by blowmage** [comment] 2015-10-05 17:26
I am able to reproduce this using vagrant with Ubuntu 12.04.5 LTS. Here is my repo: https://github.com/blowmage/grpc-travis

jessie-backports is added during the provisioning step. Here is the output:

```
$ vagrant up
Bringing machine 'default' up with 'vmware_fusion' provider...
==> default: Cloning VMware VM: 'hashicorp/precise64'. This can take some time...
==> default: Checking if box 'hashicorp/precise64' is up to date...
==> default: Verifying vmnet devices are healthy...
==> default: Preparing network adapters...
==> default: Starting the VMware VM...
==> default: Waiting for machine to boot. This may take a few minutes...
    default: SSH address: 172.16.79.157:22
    default: SSH username: vagrant
    default: SSH auth method: private key
    default: 
    default: Vagrant insecure key detected. Vagrant will automatically replace
    default: this with a newly generated keypair for better security.
    default: 
    default: Inserting generated public key within guest...
    default: Removing insecure key from the guest if its present...
    default: Key inserted! Disconnecting and reconnecting using new SSH key...
==> default: Machine booted and ready!
==> default: Forwarding ports...
    default: -- 22 => 2222
==> default: Configuring network adapters within the VM...
==> default: Waiting for HGFS kernel module to load...
==> default: Enabling and configuring shared folders...
    default: -- /Users/blowmage/google/codez/grpc-travis: /vagrant
==> default: Running provisioner: shell...
    default: Running: /var/folders/wc/9kwrhyz522768kw3z062s40r0000gn/T/vagrant-shell20151005-45285-8pmisb.sh
==> default: stdin: is not a tty
==> default: deb http://http.debian.net/debian jessie-backports main
==> default: W
==> default: : 
==> default: GPG error: http://http.debian.net jessie-backports InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 8B48AD6246925553 NO_PUBKEY 7638D0442B90D010
==> default: E
==> default: : 
==> default: Unable to correct problems, you have held broken packages.
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.
```

**Comment by dhermes** [comment] 2015-10-05 19:30
Is there a way to `apt-key adv --keyserver FOO --recv-key KEYNAME` for `jessie-backports` or just for `http.debian.net`?

Maybe this is it:
http://ftp.us.debian.org/debian/dists/jessie-backports/Release.gpg

**Comment by nathanielmanistaatgoogle** [comment] 2015-11-23 17:31
@tbetbetbe: should this be broken into five separate issues, one for each of grpc, grpc-dev, grpc++, grpc++-dev, and grpc-plugins? @dhermes is keen to follow the progress on grpc-plugins.

**Comment by dhermes** [comment] 2015-11-23 17:32
Yes. @nathanielmanistaatgoogle and I just built some generated `*_pb2.py` files today and had to use Linuxbrew to actually get them generated.

**Comment by grapemix** [comment] 2016-01-17 09:06
For Ubuntu 14.04, I got a temp solution. 

Goto: http://packages.ubuntu.com/wily/libgrpc-dev

Download libgrpc0_0.10.2-1_amd64.deb libgrpc-dev_0.10.2-1_amd64.deb libssl1.0.0_1.0.2d-0ubuntu1.2_amd64.deb

and install all of them. No need to update other deb pkg. And don't have to wait for the fix.

**Comment by andrewpollock** [comment] 2016-01-19 06:56
@dhermes you're adding a *Debian* repository to an Ubuntu installation by the looks of it. Ubuntu doesn't ship Debian's archive signing keys by default. Try installing the debian-archive-keyring package and see if an apt-get update is happier about the jessie-backports repository, but really, you're doing it wrong by adding a Debian jessie-targeted APT repository to an Ubuntu system.

**Comment by dhermes** [comment] 2016-01-19 06:58
I am certainly out of my depth there. How would you like Ubuntu users to install `grpc`?

**Comment by blowmage** [comment] 2016-01-19 07:08
@dhermes I found that I can skip the warning by adding `--force-yes` to the command.

```
sudo apt-get install libgrpc-dev -y --force-yes
```

¯\\\_(ツ)\_/¯

**Comment by dhermes** [comment] 2016-01-19 07:10
Ha. That misses the point a bit :grinning:

**Comment by andrewpollock** [comment] 2016-01-21 01:52
@dhermes I don't have a particularly good answer for you at this time unfortunately. The most technically correct option at this time would be to grab the source package from Debian and build it on Ubuntu, but that's far from convenient, and assumes a level of packaging knowledge.

**Closed** 2016-01-21 01:53 UTC
Labels: packaging & distribution

**Comment by dhermes** [comment] 2016-01-21 01:56
Is there a reason you closed this? The install story for `libgrpc` certainly isn't "fixed" in any meaningful way. (Though maybe there is something coming down the pipe that I don't know about?)

**Comment by andrewpollock** [comment] 2016-01-21 01:59
The bug was "Provide a debian package for installing core grpc". I've done that. There's one available for Debian for quite some time now. Feel free to open a new bug for an Ubuntu package. Unfortunately I don't have the bandwidth to (and there isn't really the same mechanism) to provide a package for Ubuntu. Happy to continue the conversation on an appropriate bug though.

**Comment by dhermes** [comment] 2016-01-21 02:02
Got it. My bad for trying to re-purpose the issue.

**Comment by grapemix** [comment] 2016-02-15 07:29
For Ubuntu 14.04,  here is the COMPLETE instruction for the grpcio and protobuf installation:

http://packages.ubuntu.com/xenial/libgrpc-dev

Download libgrpc0_0.11.1-1_amd64.deb libgrpc-dev_0.11.1-1_amd64.deb libssl1.0.0_1.0.2d-0ubuntu1.2_amd64.deb

and install all of them. Not willy as last time I claimed, it is xenial. I am sorry for the confusion.

Then install instruction as below:

  $ sudo pip install -U grpcio==0.11.0b1
  $ # Since this "hello, world" example uses protocol buffers:
  $ sudo pip install -U protobuf==3.0.0a3
  $ # Clone the repository to get the example code:
  $ git clone https://github.com/grpc/grpc
  $ # Navigate to the "hello, world" Python example:
  $ cd grpc/examples/python/helloworld

**Comment by eddelbuettel** [comment] 2016-08-19 15:51
Any news on this?  I would love to play with gRPC from C++.  I built a (somewhat rough and ready) set of protocbuf3 packages in my launchpad PPA, see [more here in an email to the official pkg maintainers](http://lists.alioth.debian.org/pipermail/pkg-protobuf-devel/Week-of-Mon-20160815/000070.html).

**Comment by andrewpollock** [comment] 2016-08-30 04:46
I'm packaging v1.0 as we speak. Once I've uploaded it, given that protobuf3
has landed too, I'll try to add some additional language bindings.

**Comment by eddelbuettel** [comment] 2016-08-30 10:21
Happy to test, particularly C++, as soon as you have it.

**Comment by elazarl** [comment] 2016-11-07 12:08
@andrewpollock 

For some reason in the `debian/sid` branch, we do not have a build dependency for protobuf 3, but to any protobuf version, which by default is 2.9. Is that intentional? Seems like a pbuilder build would result erroneous build, even though the build might succeed.
