### ISSUE TITLE
gRPC threads hang after ClientReaderWriter calls Finish() 

### ISSUE THREAD

**Issue by Frankie0701** [grpc/grpc#25685] opened 2021-03-11 03:14 UTC
### What version of gRPC and what language are you using?
grpc 1.36 c++

### What operating system (Linux, Windows,...) and version?
Oracle Linux Server (version 7.5)

### What runtime / compiler are you using (e.g. python version or version of gcc)
gcc 8.2.0

### What did you do?
We're using grpc to communicate between two parties (java on server and c++ on client). On the client application, compiled static grpc libraries(.a files) are used. And this happens when we upgrade from v1.21 to v1.36

### What did you expect to see?
grpc can be closed properly

### What did you see instead?
Following code works before the upgrade, while now we can see grpc threads hang after this piece of code is executed and m_grpcStream goes to destruction.  
`while (m_grpcStream->Read(&serverMsg)) {`
      `// do something`
`}`
`m_grpcStream->WritesDone();`
`context.TryCancel();`
`grpc::Status status = m_grpcStream->Finish();`

These are the threads still running after m_grpcStream destructor is called.
> 2 threads: 0x7fffb8ffe700 (LWP 29387), 0x7fffb87fd700 (LWP 29388)
=============================================================================================================================================================
syscall
absl::lts_2020_02_25::synchronization_internal::Waiter::Wait(absl::lts_2020_02_25::synchronization_internal::KernelTimeout)
AbslInternalPerThreadSemWait
absl::lts_2020_09_23::synchronization_internal::PerThreadSem::Wait(absl::lts_2020_09_23::synchronization_internal::KernelTimeout)
absl::lts_2020_09_23::Mutex::DecrementSynchSem(absl::lts_2020_09_23::Mutex*, absl::lts_2020_09_23::base_internal::PerThreadSynch*, absl::lts_2020_09_23::sync
..hronization_internal::KernelTimeout)
absl::lts_2020_09_23::CondVar::WaitCommon(absl::lts_2020_09_23::Mutex*, absl::lts_2020_09_23::synchronization_internal::KernelTimeout)
absl::lts_2020_09_23::CondVar::Wait(absl::lts_2020_09_23::Mutex*)
gpr_cv_wait
grpc_core::Executor::ThreadMain(void*)
grpc_core::(anonymous namespace)::ThreadInternalsPosix::ThreadInternalsPosix(char const*, void (*)(void*), void*, bool*, grpc_core::Thread::Options const&)::
..{lambda(void*)#1}::operator()(void*) const
grpc_core::(anonymous namespace)::ThreadInternalsPosix::ThreadInternalsPosix(char const*, void (*)(void*), void*, bool*, grpc_core::Thread::Options const&)::
..{lambda(void*)#1}::_FUN(void*)
start_thread
clone
1 thread: 0x7fffe57fe700 (LWP 28976)
=============================================================================================================================================================
syscall
absl::lts_2020_02_25::synchronization_internal::Waiter::Wait(absl::lts_2020_02_25::synchronization_internal::KernelTimeout)
AbslInternalPerThreadSemWait
absl::lts_2020_09_23::synchronization_internal::PerThreadSem::Wait(absl::lts_2020_09_23::synchronization_internal::KernelTimeout)
absl::lts_2020_09_23::Mutex::DecrementSynchSem(absl::lts_2020_09_23::Mutex*, absl::lts_2020_09_23::base_internal::PerThreadSynch*, absl::lts_2020_09_23::sync
..hronization_internal::KernelTimeout)
absl::lts_2020_09_23::CondVar::WaitCommon(absl::lts_2020_09_23::Mutex*, absl::lts_2020_09_23::synchronization_internal::KernelTimeout)
absl::lts_2020_09_23::CondVar::Wait(absl::lts_2020_09_23::Mutex*)
gpr_cv_wait
stop_threads()
grpc_timer_manager_set_threading(bool)
grpc_shutdown_internal_locked()
grpc_shutdown
grpc::internal::GrpcLibrary::shutdown()
grpc::CompletionQueue::~CompletionQueue()
GrpcAgent::~GrpcAgent()
GrpcAgent::~GrpcAgent()
1 thread: 0x7fffb6fff700 (LWP 29391)
=============================================================================================================================================================
syscall
absl::lts_2020_02_25::synchronization_internal::Waiter::Wait(absl::lts_2020_02_25::synchronization_internal::KernelTimeout)
AbslInternalPerThreadSemWait
absl::lts_2020_09_23::synchronization_internal::PerThreadSem::Wait(absl::lts_2020_09_23::synchronization_internal::KernelTimeout)
absl::lts_2020_09_23::Mutex::DecrementSynchSem(absl::lts_2020_09_23::Mutex*, absl::lts_2020_09_23::base_internal::PerThreadSynch*, absl::lts_2020_09_23::sync
..hronization_internal::KernelTimeout)
absl::lts_2020_09_23::CondVar::WaitCommon(absl::lts_2020_09_23::Mutex*, absl::lts_2020_09_23::synchronization_internal::KernelTimeout)
absl::lts_2020_09_23::CondVar::Wait(absl::lts_2020_09_23::Mutex*)
gpr_cv_wait
wait_until(long)
timer_main_loop()
timer_thread(void*)
grpc_core::(anonymous namespace)::ThreadInternalsPosix::ThreadInternalsPosix(char const*, void (*)(void*), void*, bool*, grpc_core::Thread::Options const&)::
..{lambda(void*)#1}::operator()(void*) const
grpc_core::(anonymous namespace)::ThreadInternalsPosix::ThreadInternalsPosix(char const*, void (*)(void*), void*, bool*, grpc_core::Thread::Options const&)::
..{lambda(void*)#1}::_FUN(void*)
start_thread
clone

### Anything else we should know about your project / environment?
Our client application is an executable plug-in running inside a complex engine , it works as a shared library which can be dynamically loaded into the engine to be executed.
Our client application doesn't have its own process, the process is owned by the engine

**Comment by drfloob** [comment] 2021-03-12 19:42
Looks like this is duplicate of https://github.com/grpc/grpc/issues/25020, where you and your teammate are also discussing this and related init/shutdown problems. I'll close this in favor of the other.

It might be worthwhile to see if you can create a minimal reproducible example to showcase this problem. Do I understand correctly that you upgraded gRPC _with no other code changes_ on your end, and this problem occurs? If you did make other changes, you can try reverting them to test the gRPC upgrade in isolation.

**Comment by Frankie0701** [comment] 2021-03-15 06:06
Hi @drfloob ,
#25020 and this one are not the same issue, that happens during init, and both versions have this issue. While for this ticket, grpc shutdown is fine in v1.21. But now it doesn't, we can see grpc threads hang. This is a new issue due to grpc upgrade.

> Do I understand correctly that you upgraded gRPC with no other code changes on your end, and this problem occurs?

yes, there is no code change after the upgrade, so we are expecting shutdown works as what is was.
Since our application is not a standalone one as mentioned, it's like an extension of a more complex system and doesn't have its own process, we will try our best to see if this can be reproduced by a simpler example. Much appreciated if you can also have a try on your side.
`    ChannelArguments channelArgs;`
`    channelArgs.SetInt(GRPC_ARG_KEEPALIVE_TIME_MS, KEEPALIVE_TIME_MS);`
`    channelArgs.SetInt(GRPC_ARG_KEEPALIVE_TIMEOUT_MS, KEEPALIVE_TIMEOUT_MS);`
`    channelArgs.SetInt(GRPC_ARG_KEEPALIVE_PERMIT_WITHOUT_CALLS, 1);`
`    channelArgs.SetInt(GRPC_ARG_SERVER_HANDSHAKE_TIMEOUT_MS, HANDSHAKE_TIMEOUT_MS);`
`    channelArgs.SetCompressionAlgorithm(GRPC_COMPRESS_GZIP);`
`    std::shared_ptr<grpc::ChannelCredentials> channelCreds;`
`    auto channel = grpc::CreateCustomChannel(m_agentAddress, channelCreds, channelArgs);`
`    std::unique_ptr<AgentService::Stub> stub = AgentService::NewStub(channel);`
`    ClientContext context;`
`    m_grpcStream = stub->Stream(&context);`
`    while (m_grpcStream->Read(&serverMsg))`
`    {`
`         // do something`
`    }`
`    m_grpcStream->WritesDone();`
`    context.TryCancel();`
`    grpc::Status status = m_grpcStream->Finish();`
`    if (status.ok())`
`    {`
`	  // do something`
`    }`
the application hang when m_grpcStream goes to destruction after this piece of code

**Comment by drfloob** [comment] 2021-03-16 01:48
@veblush We had shutdown race condition issues that were fixed in the past, you might have some other insights here.

@yashykt pinging for visibility, if you discover anything in the other thread that could help here too.

> yes, there is no code change after the upgrade, so we are expecting shutdown works as what is was.

How interesting. I don't see anything obviously wrong with your example code here. If it is a gRPC problem, it might be worth trying to replicate this behavior in your environment with gRPC versions between 1.21 and 1.36. Otherwise, maybe this uncovered some other race condition in your system?

**Comment by veblush** [comment] 2021-03-18 03:13
One thing that looks really strange to me is

```
syscall
absl::lts_2020_02_25::synchronization_internal::Waiter::Wait(absl::lts_2020_02_25::synchronization_internal::KernelTimeout)
AbslInternalPerThreadSemWait
absl::lts_2020_09_23::synchronization_internal::PerThreadSem::Wait(absl::lts_2020_09_23::synchronization_internal::KernelTimeout)
```

How come it use both `absl::lts_2020_02_25` and `absl::lts_2020_09_23`? It should one of them exclusively.

**Comment by Frankie0701** [comment] 2021-03-18 04:02
Good catch, we learned that the system which our application runs on is also using absl, looks like that should be the root cause. Thanks for the help!

**Closed** 2021-03-29 06:09 UTC
Labels: kind/bug, priority/P2
