### ISSUE TITLE
c_windows_opt_native.vsprojects/Release/h2_http_proxy_test.exe connectivity

### ISSUE THREAD

**Issue by kpayson64** [grpc/grpc#10107] opened 2017-03-10 23:35 UTC
Seen on v1.2.x:
```
D0310 19:53:02.548000000 92676 test_config.c:393] test slowdown factor: sanitizer=1, fixture=1, poller=1, total=1
I0310 19:53:02.556000000 92676 http_proxy_fixture.c:440] Proxy address: localhost:1228
D0310 19:53:02.556000000 95600 connectivity.c:55] verifying
D0310 19:53:02.658000000 92676 connectivity.c:97] watching
I0310 19:53:02.659000000 93628 http_connect_handshaker.c:319] Connecting to server localhost:1154 via HTTP proxy ipv4:127.0.0.1:1228
I0310 19:53:03.653000000 93628 http_proxy_fixture.c:134] HTTP proxy server connect: {"created":"@1489175583.653000000","description":"OS Error","file":"C:\jenkins\workspace\gRPC_pr_win\workspace_c_windows_opt_native\vsprojects\..\src\core\lib\iomgr\tcp_client_windows.c","file_line":120,"os_error":"No connection could be made because the target machine actively refused it.\r\n","syscall":"ConnectEx","wsa_error":10061}
I0310 19:53:03.653000000 93628 subchannel.c:705] Connect failed: {"created":"@1489175583.653000000","description":"End of TCP stream","file":"C:\jenkins\workspace\gRPC_pr_win\workspace_c_windows_opt_native\vsprojects\..\src\core\lib\iomgr\tcp_windows.c","file_line":190}
I0310 19:53:03.653000000 93628 http_connect_handshaker.c:319] Connecting to server localhost:1154 via HTTP proxy ipv6:[::1]:1228
I0310 19:53:04.653000000 93628 http_proxy_fixture.c:134] HTTP proxy server connect: {"created":"@1489175584.653000000","description":"OS Error","file":"C:\jenkins\workspace\gRPC_pr_win\workspace_c_windows_opt_native\vsprojects\..\src\core\lib\iomgr\tcp_client_windows.c","file_line":120,"os_error":"No connection could be made because the target machine actively refused it.\r\n","syscall":"ConnectEx","wsa_error":10061}
I0310 19:53:04.653000000 93628 subchannel.c:705] Connect failed: {"created":"@1489175584.653000000","description":"End of TCP stream","file":"C:\jenkins\workspace\gRPC_pr_win\workspace_c_windows_opt_native\vsprojects\..\src\core\lib\iomgr\tcp_windows.c","file_line":190}
I0310 19:53:04.653000000 93628 subchannel.c:501] Retry immediately
I0310 19:53:04.653000000 93628 subchannel.c:453] Failed to connect to channel, retrying
D0310 19:53:04.653000000 92676 connectivity.c:129] *** STARTING SERVER ***
I0310 19:53:04.653000000 93628 http_connect_handshaker.c:319] Connecting to server localhost:1154 via HTTP proxy ipv4:127.0.0.1:1228
D0310 19:53:04.656000000 92676 connectivity.c:134] *** STARTED SERVER ***
D0310 19:53:04.656000000 92676 connectivity.c:151] *** SHUTTING DOWN SERVER ***
E0310 19:53:07.658000000 92676 cq_verifier.c:200] assertion failed: e->success == ev->success
Abort handler called.
*** 0: 0000000001072D6E  - 0000000000000000
*** 1: 000000000107305A  - 0000000000000000
*** 2: 00000000011A2AEB  - 0000000000000000
*** 3: 00000000010DEF13  - 0000000000000000
*** 4: 00000000010DF0E9  - 0000000000000000
*** 5: 00000000010C4BEE  - 0000000000000000
*** 6: 0000000001071239  - 0000000000000000
*** 7: 00000000011A2C1C  - 0000000000000000
*** 8: 000000007651336A BaseThreadInitThunk - 0000000076513358
*** 9: 00000000778C9902 RtlInitializeExceptionChain - 00000000778C989F
*** 10: 00000000778C98D5 RtlInitializeExceptionChain - 00000000778C989F
```

**Comment by apolcyn** [comment] 2017-03-23 17:17
dbg config failure seen in https://grpc-testing.appspot.com/job/gRPC_pr_win/3750/testReport/junit/(root)/c_windows_dbg_native/vsprojects_Debug_h2_http_proxy_test_exe_connectivity/

```
D0322 23:28:57.584000000 290240 connectivity.c:134] *** STARTED SERVER ***
D0322 23:28:57.584000000 290240 connectivity.c:151] *** SHUTTING DOWN SERVER ***
E0322 23:29:00.586000000 290240 cq_verifier.c:200] assertion failed: e->success == ev->success
Abort handler called.
```

pr https://github.com/grpc/grpc/pull/9776 against master

**Comment by apolcyn** [comment] 2017-03-24 22:10
seen again on pr https://github.com/grpc/grpc/pull/10306 against v1.2.x

log in https://grpc-testing.appspot.com/job/gRPC_pr_win/3807/

**Comment by dgquintas** [comment] 2017-04-15 22:57
Duplicate of #9542

**Closed by dgquintas** 2017-04-15 22:57 UTC
Labels: BUILDPONY, Windows
