### ISSUE TITLE
SIGILL in cpp_macos_opt_native.bins/opt/async_end2end_test --gtest_filter=AsyncEnd2end/AsyncEnd2endTest.SimpleServerStreamingWithCoalescingApiWL/13  GRPC_POLL_STRATEGY=poll

### ISSUE THREAD

**Issue by apolcyn** [grpc/grpc#23669] opened 2020-07-29 20:32 UTC
log snippet:

```
0x0 + 4629037844
3   libsystem_c.dylib                   0x00007fff7a27f1bd __abort + 0
4   async_end2end_test                  0x000000010b687723 _ZN4absl14lts_2020_02_2520raw_logging_internal6RawLogENS0_11LogSeverityEPKciS4_z + 499
5   async_end2end_test                  0x000000010b6ab265 _ZN4absl14lts_2020_02_2524synchronization_internal6WaiterD2Ev + 53
6   async_end2end_test                  0x000000010b6aadff _ZN4absl14lts_2020_02_2524synchronization_internal21ReclaimThreadIdentityEPv + 31
7   libsystem_pthread.dylib             0x00007fff7a4ed163 _pthread_tsd_cleanup + 463
8   libsystem_pthread.dylib             0x00007fff7a4ecee9 _pthread_exit + 79
9   libsystem_pthread.dylib             0x00007fff7a4eb66c pthread_sigmask + 0
10  libsystem_pthread.dylib             0x00007fff7a4eb50d _pthread_body + 0
11  libsystem_pthread.dylib             0x00007fff7a4eabf9 thread_start + 13



*******************************
Caught signal SIGILL
0   async_end2end_test                  0x000000010b6560a3 _ZL13crash_handleriP9__siginfoPv + 291
1   libsystem_platform.dylib            0x00007fff7a4e1f5a _sigtramp + 26
2   ???                                 0x0000000113e98314 0x0 + 4629037844
3   libsystem_c.dylib                   0x00007fff7a27f1bd __abort + 0
4   async_end2end_test                  0x000000010b687723 _ZN4absl14lts_2020_02_2520raw_logging_internal6RawLogENS0_11LogSeverityEPKciS4_z + 499
5   async_end2end_test                  0x000000010b6ab265 _ZN4absl14lts_2020_02_2524synchronization_internal6WaiterD2Ev + 53
6   async_end2end_test                  0x000000010b6aadff _ZN4absl14lts_2020_02_2524synchronization_internal21ReclaimThreadIdentityEPv + 31
7   libsystem_pthread.dylib             0x00007fff7a4ed163 _pthread_tsd_cleanup + 463
8   libsystem_pthread.dylib             0x00007fff7a4ecee9 _pthread_exit + 79
9   libsystem_pthread.dylib             0x00007fff7a4eb66c pthread_sigmask + 0
10  libsystem_pthread.dylib             0x00007fff7a4eb50d _pthread_body + 0
11  libsystem_pthread.dylib             0x00007fff7a4eabf9 thread_start + 13



*******************************
Caught signal SIGILL
0   async_end2end_test                  0x000000010b6560a3 _ZL13crash_handleriP9__siginfoPv + 291
1   libsystem_platform.dylib            0x00007fff7a4e1f5a _sigtramp + 26
2   ???                                 0x0000000113e98314 0x0 + 4629037844
3   libsystem_c.dylib                   0x00007fff7a27f1bd __abort + 0
4   async_end2end_test                  0x000000010b687723 _ZN4absl14lts_2020_02_2520raw_logging_internal6RawLogENS0_11LogSeverityEPKciS4_z + 499
5   async_end2end_test                  0x000000010b6ab265 _ZN4absl14lts_2020_02_2524synchronization_internal6WaiterD2Ev + 53
6   async_end2end_test                  0x000000010b6aadff _ZN4absl14lts_2020_02_2524synchronization_internal21ReclaimThreadIdentityEPv + 31
7   libsystem_pthread.dylib             0x00007fff7a4ed163 _pthread_tsd_cleanup + 463
8   libsystem_pthread.dylib             0x00007fff7a4ecee9 _pthread_exit + 79
9   libsystem_pthread.dylib             0x00007fff7a4eb66c pthread_sigmask + 0
10  libsystem_pthread.dylib             0x00007fff7a4eb50d _pthread_body + 0
11  libsystem_pthread.dylib             0x00007fff7a4eabf9 thread_start + 13



*******************************
Caught signal SIGILL
0   async_end2end_test                  0x000000010b6560a3 _ZL13crash_handleriP9__siginfoPv + 291
1   libsystem_platform.dylib            0x00007fff7a4e1f5a _sigtramp + 26
2   ???                                 0x0000000113e98314 0x0 + 4629037844
3   libsystem_c.dylib                   0x00007fff7a27f1bd __abort + 0
4   async_end2end_test                  0x000000010b687723 _ZN4absl14lts_2020_02_2520raw_logging_internal6RawLogENS0_11LogSeverityEPKciS4_z + 499
5   async_end2end_test                  0x000000010b6ab265 _ZN4absl14lts_2020_02_2524synchronization_internal6WaiterD2Ev + 53
6   async_end2end_test                  0x000000010b6aadff _ZN4absl14lts_2020_02_2524synchronization_internal21ReclaimThreadIdentityEPv + 31
7   libsystem_pthread.dylib             0x00007fff7a4ed163 _pthread_tsd_cleanup + 463
8   libsystem_pthread.dylib             0x00007fff7a4ecee9 _pthread_exit + 79
9   libsystem_pthread.dylib             0x00007fff7a4eb66c pthread_sigmask + 0
10  libsystem_pthread.dylib             0x00007fff7a4eb50d _pthread_body + 0
11  libsystem_pthread.dylib             0x00007fff7a4eabf9 thread_start + 13



*******************************
Caught signal SIGILL
0   async_end2end_test                  0x000000010b6560a3 _ZL13crash_handleriP9__siginfoPv + 291
1   libsystem_platform.dylib            0x00007fff7a4e1f5a _sigtramp + 26
2   ???                                 0x0000000113e98314 0x0 + 4629037844
3   libsystem_c.dylib                   0x00007fff7a27f1bd __abort + 0
4   async_end2end_test                  0x000000010b687723 _ZN4absl14lts_2020_02_2520raw_logging_internal6RawLogENS0_11LogSeverityEPKciS4_z + 499
5   async_end2end_test                  0x000000010b6ab265 _ZN4absl14lts_2020_02_2524synchronization_internal6WaiterD2Ev + 53
6   async_end2end_test                  0x000000010b6aadff _ZN4absl14lts_2020_02_2524synchronization_internal21ReclaimThreadIdentityEPv + 31
7   libsystem_pthread.dylib             0x00007fff7a4ed163 _pthread_tsd_cleanup + 463
8   libsystem_pthread.dylib             0x00007fff7a4ecee9 _pthread_exit + 79
9   libsystem_pthread.dylib             0x00007fff7a4eb66c pthread_sigmask + 0
10  libsystem_pthread.dylib             0x00007fff7a4eb50d _pthread_body + 0
11  libsystem_pthread.dylib             0x00007fff7a4eabf9 thread_start + 13



*******************************
Caught signal SIGILL
0   async_end2end_test                  0x000000010b6560a3 _ZL13crash_handleriP9__siginfoPv + 291
1   libsystem_platform.dylib            0x00007fff7a4e1f5a _sigtramp + 26
2   ???                                 0x0000000113e98314 0x0 + 4629037844
3   libsystem_c.dylib                   0x00007fff7a27f1bd __abort + 0
4   async_end2end_test                  0x000000010b687723 _ZN4absl14lts_2020_02_2520raw_logging_internal6RawLogENS0_11LogSeverityEPKciS4_z + 499
5   async_end2end_test                  0x000000010b6ab265 _ZN4absl14lts_2020_02_2524synchronization_internal6WaiterD2Ev + 53
6   async_end2end_test                  0x000000010b6aadff _ZN4absl14lts_2020_02_2524synchronization_internal21ReclaimThreadIdentityEPv + 31
7   libsystem_pthread.dylib             0x00007fff7a4ed163 _pthread_tsd_cleanup + 463
8   libsystem_pthread.dylib             0x00007fff7a4ecee9 _pthread_exit + 79
9   libsystem_pthread.dylib             0x00007fff7a4eb66c pthread_sigmask + 0
10  libsystem_pthread.dylib             0x00007fff7a4eb50d _pthread_body + 0
11  libsystem_pthread.dylib             0x00007fff7a4eabf9 thread_start + 13



*******************************
Caught signal SIGILL
0   async_end2end_test                  0x000000010b6560a3 _ZL13crash_handleriP9__siginfoPv + 291
1   libsystem_platform.dylib            0x00007fff7a4e1f5a _sigtramp + 26
2   ???                                 0x0000000113e98314 0x0 + 4629037844
3   libsystem_c.dylib                   0x00007fff7a27f1bd __abort + 0
4   async_end2end_test                  0x000000010b687723 _ZN4absl14lts_2020_02_2520raw_logging_internal6RawLogENS0_11LogSeverityEPKciS4_z + 499
5   async_end2end_test                  0x000000010b6ab265 _ZN4absl14lts_2020_02_2524synchronization_internal6WaiterD2Ev + 53
6   async_end2end_test                  0x000000010b6aadff _ZN4absl14lts_2020_02_2524synchronization_internal21ReclaimThreadIdentityEPv + 31
7   libsystem_pthread.dylib             0x00007fff7a4ed163 _pthread_tsd_cleanup + 463
8   libsystem_pthread.dylib             0x00007fff7a4ecee9 _pthread_exit + 79
9   libsystem_pthread.dylib             0x00007fff7a4eb66c pthread_sigmask + 0
10  libsystem_pthread.dylib             0x00007fff7a4eb50d _pthread_body + 0
11  libsystem_pthread.dylib             0x00007fff7a4eabf9 thread_start + 13



*******************************
Caught signal SIGILL
0   async_end2end_test                  0x000000010b6560a3 _ZL13crash_handleriP
```

https://source.cloud.google.com/results/invocations/30c232c7-4c93-4c46-95a8-105075335f91/targets/github%2Fgrpc%2Frun_tests%2Fcpp_macos_opt_native/tests

seen in PR: https://github.com/grpc/grpc/pull/23639

**Comment by stanley-cheung** [comment] 2020-07-29 20:36
Tracking in #23661 I believe

**Comment by markdroth** [comment] 2020-07-29 22:45
Duplicate of #23661.

**Closed by markdroth** 2020-07-29 22:45 UTC
Labels: kind/bug, priority/P2
