### ISSUE TITLE
Attempting to JIT compile method '(wrapper native-to-managed) Grpc.Core.Internal.NativeMetadataCredentialsPlugin:NativeMetadataInterceptorHandler (intptr,intptr,intptr,intptr,intptr,int)' while running in aot-only mode

### ISSUE THREAD

**Issue by sandeepsipl** [grpc/grpc#18320] opened 2019-03-10 07:16 UTC
### What version of gRPC and what language are you using?
 
I'm using Grpc Version 1.19.0 
 
### What operating system (Linux, Windows,...) and version?
 
I'm building it on Mac OS 10.14.3 with Visual Studio 7.8.2 (Build 1)
 
### What runtime / compiler are you using (e.g. python version or version of gcc)

I'm using Xcode 10.1 

Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/include/c++/4.2.1
Apple LLVM version 10.0.0 (clang-1000.11.45.5)
Target: x86_64-apple-darwin18.2.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin 
 
### What did you do?
If possible, provide a recipe for reproducing the error. Try being specific and include code snippets if helpful.
 
### What did you expect to see?
 
As it is running fine on the simulator, it should work with iPhone device too.
 
### What did you see instead?
 
I'm getting the exception while create the DB using **var db = DatastoreDb.Create(projectId)**

Here is the exception:

{System.ExecutionEngineException: Attempting to JIT compile method '(wrapper native-to-managed) Grpc.Core.Internal.NativeMetadataCredentialsPlugin:NativeMetadataInterceptorHandler (intptr,intptr,intptr,intptr,intptr,int)' while running in aot-only mode. See https://docs.microsoft.com/xamarin/ios/internals/limitations for more information.

 at (wrapper managed-to-native) System.Object.__icall_wrapper_mono_delegate_to_ftnptr(object)
at (wrapper managed-to-native) Grpc.Core.Internal.NativeMethods+DllImportsFromStaticLib.grpcsharp_metadata_credentials_create_from_plugin(Grpc.Core.Internal.NativeMetadataInterceptor)
at Grpc.Core.Internal.NativeMetadataCredentialsPlugin..ctor (Grpc.Core.AsyncAuthInterceptor interceptor) [0x0003b] in T:\src\github\grpc\src\csharp\Grpc.Core\Internal\NativeMetadataCredentialsPlugin.cs:47 
at Grpc.Core.MetadataCredentials.ToNativeCredentials () [0x00000] in T:\src\github\grpc\src\csharp\Grpc.Core\CallCredentials.cs:80 
at Grpc.Core.CompositeChannelCredentials.CreateNativeCredentials () [0x00000] in T:\src\github\grpc\src\csharp\Grpc.Core\ChannelCredentials.cs:202 
at Grpc.Core.ChannelCredentials.<.ctor>b__2_0 () [0x00000] in T:\src\github\grpc\src\csharp\Grpc.Core\ChannelCredentials.cs:45 
at System.Lazy`1[T].CreateValue () [0x00081] in <2b439461a53d406abf16d6e5e34ece7f>:0 
at System.Lazy`1[T].LazyInitValue () [0x00080] in <2b439461a53d406abf16d6e5e34ece7f>:0 
at System.Lazy`1[T].get_Value () [0x0003a] in <2b439461a53d406abf16d6e5e34ece7f>:0 
at Grpc.Core.ChannelCredentials.GetNativeCredentials () [0x00000] in T:\src\github\grpc\src\csharp\Grpc.Core\ChannelCredentials.cs:80 
at Grpc.Core.Channel..ctor (System.String target, Grpc.Core.ChannelCredentials credentials, System.Collections.Generic.IEnumerable`1[T] options) [0x0007e] in T:\src\github\grpc\src\csharp\Grpc.Core\Channel.cs:77 
at Grpc.Core.Channel..ctor (System.String host, System.Int32 port, Grpc.Core.ChannelCredentials credentials, System.Collections.Generic.IEnumerable`1[T] options) [0x00000] in T:\src\github\grpc\src\csharp\Grpc.Core\Channel.cs:109 
 at Google.Api.Gax.Grpc.ChannelPool.GetChannel (Google.Api.Gax.Grpc.ServiceEndpoint endpoint, Grpc.Core.ChannelCredentials credentials) [0x0003a] in C:\Users\skeet\Test\Projects\gax-dotnet\releasebuild\Google.Api.Gax.Grpc\ChannelPool.cs:127 
at Google.Api.Gax.Grpc.ChannelPool.GetChannel (Google.Api.Gax.Grpc.ServiceEndpoint endpoint) [0x0001d] in C:\Users\skeet\Test\Projects\gax-dotnet\releasebuild\Google.Api.Gax.Grpc\ChannelPool.cs:93 
at Google.Cloud.Datastore.V1.DatastoreClient.Create (Google.Api.Gax.Grpc.ServiceEndpoint endpoint, Google.Cloud.Datastore.V1.DatastoreSettings settings) [0x00000] in C:\Users\jon\Test\Projects\google-cloud-dotnet\releasebuild\apis\Google.Cloud.Datastore.V1\Google.Cloud.Datastore.V1\DatastoreClient.cs:399 
at Google.Cloud.Datastore.V1.DatastoreDb.Create (System.String projectId, System.String namespaceId, Google.Cloud.Datastore.V1.DatastoreClient client) [0x00000] in C:\Users\jon\Test\Projects\google-cloud-dotnet\releasebuild\apis\Google.Cloud.Datastore.V1\Google.Cloud.Datastore.V1\DatastoreDb.cs:84 
at Kudos.ViewController.SaveToDB () [0x0000c] in /Users/sandeepmahajan/Documents/Projects/sury-kudos/SuryKudos/SuryKudos/ViewController.cs:75 }

**Comment by tylersouthard** [comment] 2019-03-10 20:03
See #18178, #17587, and #17051

**Comment by jtattermusch** [comment] 2019-03-11 06:35
This is a duplicate of #18178.

**Closed by jtattermusch** 2019-03-11 06:35 UTC
Labels: kind/bug, lang/C#
