### ISSUE TITLE
PHP: Support multiple persistent channels

### ISSUE THREAD

**Issue by jdpedrie** [grpc/grpc#15426] opened 2018-05-17 14:52 UTC
### What version of gRPC and what language are you using?

v1.12.0, PHP 5.x, PHP 7.x 

---

A user of Google Cloud PHP's Spanner client opened an [issue](https://github.com/GoogleCloudPlatform/google-cloud-php/issues/1052) regarding the limit documented [here](https://cloud.google.com/spanner/docs/sessions#create_and_size_the_session_cache) of 100 sessions per gRPC channel. The concern is that once concurrent connections to Spanner from a single PHP server exceed that limit, requests will begin to block, with no means of increasing that limit.

gRPC in PHP already supports use of a single persistent channel so that each request does not need to create its own channel. We'd like to propose extending this paradigm by adding an optional `numChannelsPerHost` argument, which will trigger creation of multiple persistent channels for a given hostname, held in a pool by the gRPC extension. As clients are created, the gRPC extension would allocate on a round-robin basis one of these persistent channels to each client, thus providing better support for high-concurrency applications.

For instance, if `numChannelsPerHost` was set to five, gRPC would maintain five persistent channels. This would increase the maximum number of concurrent connections from 100 (with one channel) to 500, with the load spread across all five open channels.

We believe that management of these channels must be done within the extension for a couple of reasons:

1. PHP applications are short-lived, and we create new gRPC clients on every request. As opposed to, for instance, [Google Cloud Go](https://github.com/GoogleCloudPlatform/google-cloud-go/blob/master/spanner/client.go#L162-L169), it is not possible for us to create a pool of connections within the application while still maintaining the limited latency required. Additionally, even if we were able to create a connection pool, due to the design of gRPC-PHP, each connection would either share the same persistent channel, or if each used a new channel, would invalidate the channel used by the previously created channel.
2. Sharing memory across PHP processes is difficult and often requires additional PHP extensions. Thus an application-side connection pool would be difficult or perhaps impossible to implement.

Thank you!

cc @stanley-cheung

**Comment by ZhouyihaiDing** [comment] 2018-05-17 16:16
cc @fengli79

**Comment by ZhouyihaiDing** [comment] 2018-06-07 00:27
Hi @jdpedrie. Thanks for the help!

I am working on solving this issue.

This issue looks like provide a way to manage channels. Adding this support in the PHP layer instead of c extension layer may offer more benefits. For example, if we can insert the channel management like plugin, this plugin can be implemented with many solutions, like create a new channel when the number of streams arrives 100, or create 10 channels for the same target in advance and do the round robin to spread the load as you described.

For your concerns:

1. I am not sure how much channel pool will affect the latency. Assume we can manage channels and inside it we push 10 channels into a global pool like `apcu`(Although `Channel` object doesn't have serialize/deserialize handler, we can save the argument because when `[target+ argument+hash[credentials]]` is the same, it will reuse the channel created before). When a request come, it fetch the argument for creating the channel, and then it will reuse the channel.

Also, for persistent channel reuse, if we provide different argument when creating the channel, it will create a new channel. Thus the channel management plugin can create channel like `new \Grpc\Channel($target, [..., channel_id => $channel_numbers_in_plugin])` which can create a new channel until the number arrives to 10.

2. Currently, channel can only be shared within the same PHP-FPM process. Within the plugin, when we push/fetch the channel to/from the pool, we can record which process this channel is created, so that it won't fetch the channel created by other process.

**Comment by ZhouyihaiDing** [comment] 2018-06-25 22:56
Hi @jdpedrie ,

Can you please provide me a sample for reproducing the issue?

I am trying to insert my fix([GCP extension)](https://github.com/ZhouyihaiDing/grpc/pull/21) into the spanner client, which will create a new channel and use it for the next RPC when all channels in the channel pool have active stream == 100. However, I have some problems when reproduce the original issue. 

I was trying to create >100 sessions and sending >100 `ExecuteStreamingSql` RPC without the fix, but the 101th RPC can still get the response OK without hanging/failing.

**Comment by ZhouyihaiDing** [comment] 2018-07-31 03:26
`Grpc\Gcp` [library](https://packagist.org/packages/google/grpc-gcp) is designed to support multiple persistent channels. When the number of concurrent streams exceed 100, and the new RPC is not supposed to use an existing channel(eg, some RPCs are bind with a session, which use the existing channel), we will create a new channel for this RPC.

I created [a test](https://github.com/GoogleCloudPlatform/grpc-gcp-php/pull/17) to mock 100 concurrent streams issue with/without `Grpc\Gcp` library if you are interested. Thanks!

**Comment by ZhouyihaiDing** [comment] 2018-08-03 22:09
Close this issue for the [`grpc-gcp`](https://packagist.org/packages/google/grpc-gcp) library solution.

**Closed by ZhouyihaiDing** 2018-08-03 22:09 UTC
Labels: kind/enhancement, lang/php, priority/P2
