### ISSUE TITLE
cloud_to_prod_auth:default:csharp:jwt_token_creds

### ISSUE THREAD

**Issue by dgquintas** [grpc/grpc#12628] opened 2017-09-19 03:17 UTC
https://grpc-testing.appspot.com/job/gRPC_interop_pull_requests/16762/testReport/junit/(root)/tests/cloud_to_prod_auth_default_csharp_jwt_token_creds/

```

Unhandled Exception:
System.AggregateException: One or more errors occurred. ---> Grpc.Core.RpcException: Status(StatusCode=Unavailable, Detail="Endpoint read failed")
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <204f770036d441bb8dfd3daba3550e83>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <204f770036d441bb8dfd3daba3550e83>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <204f770036d441bb8dfd3daba3550e83>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <204f770036d441bb8dfd3daba3550e83>:0 
  at System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () [0x00000] in <204f770036d441bb8dfd3daba3550e83>:0 
  at Grpc.Core.Internal.AsyncCall`2[TRequest,TResponse].UnaryCall (TRequest msg) [0x0017b] in <16380fc969bc48be8aa70b448274e3df>:0 
  at Grpc.Core.Calls.BlockingUnaryCall[TRequest,TResponse] (Grpc.Core.CallInvocationDetails`2[TRequest,TResponse] call, TRequest req) [0x00008] in <16380fc969bc48be8aa70b448274e3df>:0 
  at Grpc.Core.DefaultCallInvoker.BlockingUnaryCall[TRequest,TResponse] (Grpc.Core.Method`2[TRequest,TResponse] method, System.String host, Grpc.Core.CallOptions options, TRequest request) [0x0000b] in <16380fc969bc48be8aa70b448274e3df>:0 
  at Grpc.Core.Internal.InterceptingCallInvoker.BlockingUnaryCall[TRequest,TResponse] (Grpc.Core.Method`2[TRequest,TResponse] method, System.String host, Grpc.Core.CallOptions options, TRequest request) [0x00013] in <16380fc969bc48be8aa70b448274e3df>:0 
  at Grpc.Testing.TestService+TestServiceClient.UnaryCall (Grpc.Testing.SimpleRequest request, Grpc.Core.CallOptions options) [0x00007] in <a81b8c2bcb3c4b6e8635ef7e3f3c2ff3>:0 
  at Grpc.Testing.TestService+TestServiceClient.UnaryCall (Grpc.Testing.SimpleRequest request, Grpc.Core.Metadata headers, System.Nullable`1[T] deadline, System.Threading.CancellationToken cancellationToken) [0x0000f] in <a81b8c2bcb3c4b6e8635ef7e3f3c2ff3>:0 
  at Grpc.IntegrationTesting.InteropClient.RunJwtTokenCreds (Grpc.Testing.TestService+TestServiceClient client) [0x00037] in <a81b8c2bcb3c4b6e8635ef7e3f3c2ff3>:0 
  at Grpc.IntegrationTesting.InteropClient+<RunTestCaseAsync>d__6.MoveNext () [0x00594] in <a81b8c2bcb3c4b6e8635ef7e3f3c2ff3>:0 
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <204f770036d441bb8dfd3daba3550e83>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <204f770036d441bb8dfd3daba3550e83>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <204f770036d441bb8dfd3daba3550e83>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <204f770036d441bb8dfd3daba3550e83>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.GetResult () [0x00000] in <204f770036d441bb8dfd3daba3550e83>:0 
  at Grpc.IntegrationTesting.InteropClient+<Run>d__4.MoveNext () [0x001aa] in <a81b8c2bcb3c4b6e8635ef7e3f3c2ff3>:0 
   --- End of inner exception stack trace ---
  at System.Threading.Tasks.Task.ThrowIfExceptional (System.Boolean includeTaskCanceledExceptions) [0x00011] in <204f770036d441bb8dfd3daba3550e83>:0 
  at System.Threading.Tasks.Task.Wait (System.Int32 millisecondsTimeout, System.Threading.CancellationToken cancellationToken) [0x00043] in <204f770036d441bb8dfd3daba3550e83>:0 
  at System.Threading.Tasks.Task.Wait () [0x00000] in <204f770036d441bb8dfd3daba3550e83>:0 
  at Grpc.IntegrationTesting.InteropClient+<>c.<Run>b__3_1 (Grpc.IntegrationTesting.InteropClient+ClientOptions options) [0x0000e] in <a81b8c2bcb3c4b6e8635ef7e3f3c2ff3>:0 
  at CommandLine.ParserResultExtensions.WithParsed[T] (CommandLine.ParserResult`1[T] result, System.Action`1[T] action) [0x00011] in <c500474b04314b778910cf182873b214>:0 
  at Grpc.IntegrationTesting.InteropClient.Run (System.String[] args) [0x0003b] in <a81b8c2bcb3c4b6e8635ef7e3f3c2ff3>:0 
  at Grpc.IntegrationTesting.Client.Program.Main (System.String[] args) [0x00001] in <e772482f9bf14504882fff368d0e89f6>:0 
---> (Inner Exception #0) Grpc.Core.RpcException: Status(StatusCode=Unavailable, Detail="Endpoint read failed")
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <204f770036d441bb8dfd3daba3550e83>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <204f770036d441bb8dfd3daba3550e83>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <204f770036d441bb8dfd3daba3550e83>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <204f770036d441bb8dfd3daba3550e83>:0 
  at System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () [0x00000] in <204f770036d441bb8dfd3daba3550e83>:0 
  at Grpc.Core.Internal.AsyncCall`2[TRequest,TResponse].UnaryCall (TRequest msg) [0x0017b] in <16380fc969bc48be8aa70b448274e3df>:0 
  at Grpc.Core.Calls.BlockingUnaryCall[TRequest,TResponse] (Grpc.Core.CallInvocationDetails`2[TRequest,TResponse] call, TRequest req) [0x00008] in <16380fc969bc48be8aa70b448274e3df>:0 
  at Grpc.Core.DefaultCallInvoker.BlockingUnaryCall[TRequest,TResponse] (Grpc.Core.Method`2[TRequest,TResponse] method, System.String host, Grpc.Core.CallOptions options, TRequest request) [0x0000b] in <16380fc969bc48be8aa70b448274e3df>:0 
  at Grpc.Core.Internal.InterceptingCallInvoker.BlockingUnaryCall[TRequest,TResponse] (Grpc.Core.Method`2[TRequest,TResponse] method, System.String host, Grpc.Core.CallOptions options, TRequest request) [0x00013] in <16380fc969bc48be8aa70b448274e3df>:0 
  at Grpc.Testing.TestService+TestServiceClient.UnaryCall (Grpc.Testing.SimpleRequest request, Grpc.Core.CallOptions options) [0x00007] in <a81b8c2bcb3c4b6e8635ef7e3f3c2ff3>:0 
  at Grpc.Testing.TestService+TestServiceClient.UnaryCall (Grpc.Testing.SimpleRequest request, Grpc.Core.Metadata headers, System.Nullable`1[T] deadline, System.Threading.CancellationToken cancellationToken) [0x0000f] in <a81b8c2bcb3c4b6e8635ef7e3f3c2ff3>:0 
  at Grpc.IntegrationTesting.InteropClient.RunJwtTokenCreds (Grpc.Testing.TestService+TestServiceClient client) [0x00037] in <a81b8c2bcb3c4b6e8635ef7e3f3c2ff3>:0 
  at Grpc.IntegrationTesting.InteropClient+<RunTestCaseAsync>d__6.MoveNext () [0x00594] in <a81b8c2bcb3c4b6e8635ef7e3f3c2ff3>:0 
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <204f770036d441bb8dfd3daba3550e83>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <204f770036d441bb8dfd3daba3550e83>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <204f770036d441bb8dfd3daba3550e83>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <204f770036d441bb8dfd3daba3550e83>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.GetResult () [0x00000] in <204f770036d441bb8dfd3daba3550e83>:0 
  at Grpc.IntegrationTesting.InteropClient+<Run>d__4.MoveNext () [0x001aa] in <a81b8c2bcb3c4b6e8635ef7e3f3c2ff3>:0 <---

[ERROR] FATAL UNHANDLED EXCEPTION: System.AggregateException: One or more errors occurred. ---> Grpc.Core.RpcException: Status(StatusCode=Unavailable, Detail="Endpoint read failed")
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <204f770036d441bb8dfd3daba3550e83>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <204f770036d441bb8dfd3daba3550e83>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <204f770036d441bb8dfd3daba3550e83>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <204f770036d441bb8dfd3daba3550e83>:0 
  at System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () [0x00000] in <204f770036d441bb8dfd3daba3550e83>:0 
  at Grpc.Core.Internal.AsyncCall`2[TRequest,TResponse].UnaryCall (TRequest msg) [0x0017b] in <16380fc969bc48be8aa70b448274e3df>:0 
  at Grpc.Core.Calls.BlockingUnaryCall[TRequest,TResponse] (Grpc.Core.CallInvocationDetails`2[TRequest,TResponse] call, TRequest req) [0x00008] in <16380fc969bc48be8aa70b448274e3df>:0 
  at Grpc.Core.DefaultCallInvoker.BlockingUnaryCall[TRequest,TResponse] (Grpc.Core.Method`2[TRequest,TResponse] method, System.String host, Grpc.Core.CallOptions options, TRequest request) [0x0000b] in <16380fc969bc48be8aa70b448274e3df>:0 
  at Grpc.Core.Internal.InterceptingCallInvoker.BlockingUnaryCall[TRequest,TResponse] (Grpc.Core.Method`2[TRequest,TResponse] method, System.String host, Grpc.Core.CallOptions options, TRequest request) [0x00013] in <16380fc969bc48be8aa70b448274e3df>:0 
  at Grpc.Testing.TestService+TestServiceClient.UnaryCall (Grpc.Testing.SimpleRequest request, Grpc.Core.CallOptions options) [0x00007] in <a81b8c2bcb3c4b6e8635ef7e3f3c2ff3>:0 
  at Grpc.Testing.TestService+TestServiceClient.UnaryCall (Grpc.Testing.SimpleRequest request, Grpc.Core.Metadata headers, System.Nullable`1[T] deadline, System.Threading.CancellationToken cancellationToken) [0x0000f] in <a81b8c2bcb3c4b6e8635ef7e3f3c2ff3>:0 
  at Grpc.IntegrationTesting.InteropClient.RunJwtTokenCreds (Grpc.Testing.TestService+TestServiceClient client) [0x00037] in <a81b8c2bcb3c4b6e8635ef7e3f3c2ff3>:0 
  at Grpc.IntegrationTesting.InteropClient+<RunTestCaseAsync>d__6.MoveNext () [0x00594] in <a81b8c2bcb3c4b6e8635ef7e3f3c2ff3>:0 
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <204f770036d441bb8dfd3daba3550e83>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <204f770036d441bb8dfd3daba3550e83>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <204f770036d441bb8dfd3daba3550e83>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <204f770036d441bb8dfd3daba3550e83>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.GetResult () [0x00000] in <204f770036d441bb8dfd3daba3550e83>:0 
  at Grpc.IntegrationTesting.InteropClient+<Run>d__4.MoveNext () [0x001aa] in <a81b8c2bcb3c4b6e8635ef7e3f3c2ff3>:0 
   --- End of inner exception stack trace ---
  at System.Threading.Tasks.Task.ThrowIfExceptional (System.Boolean includeTaskCanceledExceptions) [0x00011] in <204f770036d441bb8dfd3daba3550e83>:0 
  at System.Threading.Tasks.Task.Wait (System.Int32 millisecondsTimeout, System.Threading.CancellationToken cancellationToken) [0x00043] in <204f770036d441bb8dfd3daba3550e83>:0 
  at System.Threading.Tasks.Task.Wait () [0x00000] in <204f770036d441bb8dfd3daba3550e83>:0 
  at Grpc.IntegrationTesting.InteropClient+<>c.<Run>b__3_1 (Grpc.IntegrationTesting.InteropClient+ClientOptions options) [0x0000e] in <a81b8c2bcb3c4b6e8635ef7e3f3c2ff3>:0 
  at CommandLine.ParserResultExtensions.WithParsed[T] (CommandLine.ParserResult`1[T] result, System.Action`1[T] action) [0x00011] in <c500474b04314b778910cf182873b214>:0 
  at Grpc.IntegrationTesting.InteropClient.Run (System.String[] args) [0x0003b] in <a81b8c2bcb3c4b6e8635ef7e3f3c2ff3>:0 
  at Grpc.IntegrationTesting.Client.Program.Main (System.String[] args) [0x00001] in <e772482f9bf14504882fff368d0e89f6>:0 
---> (Inner Exception #0) Grpc.Core.RpcException: Status(StatusCode=Unavailable, Detail="Endpoint read failed")
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <204f770036d441bb8dfd3daba3550e83>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <204f770036d441bb8dfd3daba3550e83>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <204f770036d441bb8dfd3daba3550e83>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <204f770036d441bb8dfd3daba3550e83>:0 
  at System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () [0x00000] in <204f770036d441bb8dfd3daba3550e83>:0 
  at Grpc.Core.Internal.AsyncCall`2[TRequest,TResponse].UnaryCall (TRequest msg) [0x0017b] in <16380fc969bc48be8aa70b448274e3df>:0 
  at Grpc.Core.Calls.BlockingUnaryCall[TRequest,TResponse] (Grpc.Core.CallInvocationDetails`2[TRequest,TResponse] call, TRequest req) [0x00008] in <16380fc969bc48be8aa70b448274e3df>:0 
  at Grpc.Core.DefaultCallInvoker.BlockingUnaryCall[TRequest,TResponse] (Grpc.Core.Method`2[TRequest,TResponse] method, System.String host, Grpc.Core.CallOptions options, TRequest request) [0x0000b] in <16380fc969bc48be8aa70b448274e3df>:0 
  at Grpc.Core.Internal.InterceptingCallInvoker.BlockingUnaryCall[TRequest,TResponse] (Grpc.Core.Method`2[TRequest,TResponse] method, System.String host, Grpc.Core.CallOptions options, TRequest request) [0x00013] in <16380fc969bc48be8aa70b448274e3df>:0 
  at Grpc.Testing.TestService+TestServiceClient.UnaryCall (Grpc.Testing.SimpleRequest request, Grpc.Core.CallOptions options) [0x00007] in <a81b8c2bcb3c4b6e8635ef7e3f3c2ff3>:0 
  at Grpc.Testing.TestService+TestServiceClient.UnaryCall (Grpc.Testing.SimpleRequest request, Grpc.Core.Metadata headers, System.Nullable`1[T] deadline, System.Threading.CancellationToken cancellationToken) [0x0000f] in <a81b8c2bcb3c4b6e8635ef7e3f3c2ff3>:0 
  at Grpc.IntegrationTesting.InteropClient.RunJwtTokenCreds (Grpc.Testing.TestService+TestServiceClient client) [0x00037] in <a81b8c2bcb3c4b6e8635ef7e3f3c2ff3>:0 
  at Grpc.IntegrationTesting.InteropClient+<RunTestCaseAsync>d__6.MoveNext () [0x00594] in <a81b8c2bcb3c4b6e8635ef7e3f3c2ff3>:0 
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <204f770036d441bb8dfd3daba3550e83>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <204f770036d441bb8dfd3daba3550e83>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <204f770036d441bb8dfd3daba3550e83>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <204f770036d441bb8dfd3daba3550e83>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.GetResult () [0x00000] in <204f770036d441bb8dfd3daba3550e83>:0 
  at Grpc.IntegrationTesting.InteropClient+<Run>d__4.MoveNext () [0x001aa] in <a81b8c2bcb3c4b6e8635ef7e3f3c2ff3>:0 <---


2017-09-18 19:51:14,750 FAILED: cloud_to_prod_auth:default:csharp:jwt_token_creds [ret=1, pid=23634]
```

Similar to #12618 and #12576

**Comment by jtattermusch** [comment] 2017-10-05 13:55
Basically dupe of https://github.com/grpc/grpc/issues/10763

**Closed by jtattermusch** 2017-10-05 13:55 UTC
Labels: infra/BUILDPONY
