### ISSUE TITLE
Unhelpful error reporting when connected to a non-gRPC server

### ISSUE THREAD

**Issue by timburks** [grpc/grpc#5443] opened 2016-02-26 19:41 UTC
When the Objective-C (and presumably also any C-based) client connects to a web server that doesn't support gRPC, a message is logged like this one:

E0226 11:35:01.485432000 123145302917120 parsing.c:472] Unknown frame type 50

Objective-C clients also receive an NSError object that, when logged, prints something like this:

2016-02-26 11:36:15.447 stickynotes[89409:5881572] ERROR: Error Domain=io.grpc Code=14 "" UserInfo={io.grpc.TrailersKey={
}, 

To a client application developer, this is fairly useless information. Stepping through the grpc code, I see that the actual server response is the following:

"P/1.1 400 Bad Request\r\nConnection: close\r\nDate: Fri, 26 Feb 2016 19:31:58 GMT\r\nContent-Length: 0\r\nContent-Type: text/plain; charset=utf-8\r\n\r\n\x03"

At a minimum, it would be good to log this server response (perhaps truncated for safety), and it would be even better to include a more descriptive message in the NSError object returned by the Objective C API.

**Comment by russmatney** [comment] 2016-03-11 23:50
Just hit this connecting to a grpc server from a nodejs client as well - would be nice to see a universal fix (rather than just for ObjC)

**Comment by ctiller** [comment] 2016-03-12 00:05
This is a duplicate of #49 (our oldest open issue!)

But yes, C core should stick some useful data in the error status that it
bubbles up. We've (clearly) been trying to get to it for a while... there
are some prerequisites needed to make this robust (#4672 springs to mind).

**Closed** 2016-04-21 23:31 UTC
Labels: core, duplicate, ObjC, to close
