### ISSUE TITLE
Ruby interop server uses 100% CPU

### ISSUE THREAD

**Issue by ejona86** [grpc/grpc#3427] opened 2015-09-23 06:21 UTC
As seen on GCE instances grpc-docker-server-* and locally with `docker run -it grpc/ruby`.

**Comment by JohanSJA** [comment] 2015-10-02 05:29
Noticed the same thing when running server using method `run_till_terminated`. CPU usage seems better when using plain `run`.

**Comment by jtattermusch** [comment] 2015-12-11 00:12
Seems to be duplicate of #4396, which has just been fixed..

**Closed by jtattermusch** 2015-12-11 00:12 UTC
Labels: ruby, wrapped languages
