### ISSUE TITLE
Cannot set custom data to `_ServiceContext` in aio grpc server interceptor

### ISSUE THREAD

**Issue by djanku** [grpc/grpc#24470] opened 2020-10-19 14:48 UTC
Hi! Recently I've switched to aio version of grpc and started rewriting our code. I came across a problem with server interceptors: it's impossible to add any kind of information to passed context! We use context for opentracing context e.g. After income metadata is processed we set `span` attribute to context in interceptor handler:
`context.span = span`
But it doesn't work anymore. Even `setattr` doesn't work. I think this is a bug.

Or is there any other way to set a custom data to `_ServicerContext` instance?

https://github.com/grpc/grpc/blob/master/src/python/grpcio/grpc/_cython/_cygrpc/aio/server.pyx.pxi#L113

**Comment by ewang** [comment] 2021-09-21 22:50
I think this is also the case in the non-AIO version. I think the lack of a way of attaching custom objects to the context object really limits the utility of the Python server interceptors. I've also implemented gRPC server interceptors in Go and there one has the built in context lib to attach additional data to the context.

Any plans to support this capability?

**Comment by jenstroeger** [comment] 2022-08-23 10:22
While it’s currently (I’m running [grpcio v1.45.0](https://github.com/grpc/grpc/releases/tag/v1.45.0)) possible to add data to a request context inside of an interceptor (using the [grpc-interceptor](https://github.com/d5h-foss/grpc-interceptor) package):
```python
context.dbsession = create_session()  # SQLA Session object.
```
it’s not possible to safely type that code because the context is a [`grpc.ServicerContext`](https://grpc.github.io/grpc/python/grpc.html?highlight=servicercontext#grpc.ServicerContext), thus yielding an error:
```
interceptors.py:102:9: error: "ServicerContext" has no attribute "dbsession"  [attr-defined]
```
For the time being, I [silenced this warning](https://mypy.readthedocs.io/en/stable/common_issues.html#spurious-errors-and-locally-silencing-the-checker) but ideally I would like to use a custom context class.<sup>*</sup> However, I suspect that would require extending the [Interceptor functionality](https://github.com/grpc/proposal/blob/master/L13-python-interceptors.md), perhaps using a [factory](https://en.wikipedia.org/wiki/Factory_%28object-oriented_programming%29)?

—————
<sup>*</sup> Somewhat related question [Add properties to context from decorator or ServiceInterceptor](https://stackoverflow.com/questions/58584032/grpc-add-properties-to-context-from-decorator-or-serviceinterceptor)

**Comment by justincely** [comment] 2023-01-26 03:29
Bump - really would like this feature.   And plans or thoughts on this?

**Comment by gnossen** [comment] 2023-02-01 21:37
@djanku (or anyone else commenting on this thread) Can I ask what your expected behavior is? Would you want objects added by a client to the context object to appear on the server side?

If so, could you use the contextvars module in conjunction with a serializing/deserializing interceptor to make this happen?

**Comment by Tette6969** [comment] 2023-02-02 11:27
Sorry

**Comment by justincely** [comment] 2023-02-24 20:48
Speaking at least for myself: I'd like for interceptors on any side of the connection to be able to add/modify bits of the metadata that is passed around.  E.g. interceptor 1 doing an auth call and sticking something about the user into the metadata for use in either interceptor 2 or the service itself.  It doesn't seem to be possible to do this right now, through the existing functionality.  

Another example of this type of thing is how Envoy handles it's filter mechanism (which feels very similar in design to these interceptors).  The filters themselves can operate on the request/response or even just pass internal metadata from one filter to another.  

Contextvars do work; that's actually what we're doing now to get around this limitation.  I don't know how well that will scale as the amount of things we want to pass around increases, but I'm guessing something in the interceptors themselves would be more performant.

**Comment by gnossen** [comment] 2023-03-01 21:42
I think there's a misunderstanding about what `_ServiceContext` is meant to be. This is not [the `context.Context` type from `Golang`](https://pkg.go.dev/context). This is a type that provides access to information not available on the request itself and providing the user with the ability to perform side-affecting actions during response handling. Instead, the equivalent of Golang's `context.Context` within Python _is_ [`contextvars`](https://docs.python.org/3/library/contextvars.html).

> Contextvars do work; that's actually what we're doing now to get around this limitation. I don't know how well that will scale as the amount of things we want to pass around increases

Any limitation that `contextvars` have, a hypothetical version of `_ServiceContext` that had the same capabilities would be subject to the same limitations.

> E.g. interceptor 1 doing an auth call and sticking something about the user into the metadata for use in either interceptor 2 or the service itself

This should be possible today using `contextvars` and if it isn't, we'd consider that a bug.

> but I'm guessing something in the interceptors themselves would be more performant.

I'd expect these two models to have roughly the same performance.

**Comment by jenstroeger** [comment] 2023-03-05 21:39
> Can I ask what your expected behavior is? Would you want objects added by a client to the context object to appear on the server side?

Not quite: on the server side we chain two interceptors before calling the request handler, e.g. request → interceptor _A_ → interceptor _B_ → request handler to produce a response that flows back up through the interceptors in reverse.

Now, _A_ and/or _B_ want to add some data for the request handler and currently we pop that into the context.

If I understand you correctly, though, the supported approach is using the [contextvars](https://docs.python.org/3/library/contextvars.html) package? In that case, does the context provide a unique id (e.g. [`id(context)`](https://docs.python.org/3/library/functions.html#id)) that we’d use to name that context?

**Comment by jenstroeger** [comment] 2023-03-06 22:26
I think a few examples would be helpful, thank you @gnossen! 

Regarding the ID I think I misunderstood the [`ContextVar`](https://docs.python.org/3/library/contextvars.html#contextvars.ContextVar) initializer: the name is not used to find the context var, so… nevermind.

**Comment by DarkMatter9309** [comment] 2023-03-14 20:37
Have a similar usecase where I am trying to pass information from a decorator to asyncio grpc function
https://stackoverflow.com/questions/75737633/asyncio-grpc-add-properties-to-context-from-decorator-or-server-interceptor

**Comment by jenstroeger** [comment] 2023-03-26 21:46
@gnossen @justincely I’m curious about the [contextvars](https://docs.python.org/3/library/contextvars.html) use.

I can’t quite make contextvars work for the gRPC server, to hand values down through interceptors to the actual handler function. I found a [comment in PEP-567](https://peps.python.org/pep-0567/#offloading-execution-to-other-threads) that seems to suggest to hook into the thread executor (I’m using [ThreadPoolExecutor](https://docs.python.org/3/library/concurrent.futures.html#concurrent.futures.ThreadPoolExecutor) at the moment) to ensure that contexts are copied.[^fn]

A working gRPC server example would be helpful!

[^fn]: Code like [this class](https://github.com/hellysmile/contextvars_executor/blob/master/contextvars_executor.py) or @kobybum [blog](https://kobybass.medium.com/python-contextvars-and-multithreading-faa33dbe953d) seems to support that requirement?

**Comment by XuanWang-Amos** [comment] 2023-03-29 20:48
To anyone who's interested, we plan to add those examples by end of April 14.

**Comment by jenstroeger** [comment] 2023-04-24 06:40
@XuanWang-Amos I looked at #32840 but that covers only examples for an `async` implementation using the [contextvars](https://docs.python.org/3/library/contextvars.html) package. Any plans to add an example for normal, non-async implementations?

**Comment by XuanWang-Amos** [comment] 2023-04-28 20:49
Hi, Sync implementation is more complex, currently we spawn both interceptor thread and the handler thread from main thread:
```
         Main thread
          /        \  
         /          \
    Interceptors   Hanlder
```

So we can't directly pass context from interceptors to handler using `contextVars`, we will discuss internally to see what's the recommended solution here.

**Comment by XuanWang-Amos** [comment] 2023-05-04 19:37
We talked internally and decided that we need to change the behavior of the sync implementation first (interceptors and handler should run in the same thread). Once we do that, we can add an example.

This is not a small change, and it's not urgent. We have other priorities right now so it might take a while. If you want this change sooner, please comment or give a 👍 here.

**Comment by jenstroeger** [comment] 2023-05-04 21:10
Thanks for the update, @XuanWang-Amos 

In the meantime, what’s the recommended approach to communicate custom extra data between interceptors and handlers — just attach that data to the `ServicerContext` as discussed above?

**Comment by XuanWang-Amos** [comment] 2023-05-04 21:57
> Thanks for the update, @XuanWang-Amos
> 
> In the meantime, what’s the recommended approach to communicate custom extra data between interceptors and handlers — just attach that data to the `ServicerContext` as discussed above?

While it might be possible to do so, it's not recommended.

As a workaround, you can consider pass data around using serialized [metadata](https://github.com/grpc/grpc/blob/master/src/python/grpcio/grpc/__init__.py#L1315).

**Comment by XuanWang-Amos** [comment] 2023-05-10 20:39
Closing this issue since we already added Async examples, we'll track sync stack progress in another issue: https://github.com/grpc/grpc/issues/33071

**Closed by XuanWang-Amos** 2023-05-10 20:39 UTC
Labels: kind/bug, lang/Python, priority/P2
