### ISSUE TITLE
[C#] server sending responseheader in unary call not received by the client until the whole response is returned

### ISSUE THREAD

**Issue by alexhcheng** [grpc/grpc#25682] opened 2021-03-11 00:44 UTC
### What version of gRPC and what language are you using?
2.26

### What operating system (Linux, Windows,...) and version?
Linux

### What runtime / compiler are you using (e.g. python version or version of gcc)
dotnet 3.1

### What did you do?
Client 
1. makes a unary request to the server.
2. call await response.ResponseHeaderAsync
3. call await response.ResponseAsync

Server
1. call await WriteResponseHeadersAsync()
2. do some heavy processing, then send the response

### What did you expect to see?
Client to get the header first
Then after a while get the response.

### What did you see instead?
ResponseHeaderAsync doesn't return until the server send the actual response.

**Comment by drfloob** [comment] 2021-03-11 17:24
It might be worth seeing if you could reproduce this with a more recent gRPC version. v2.26 was released in 2019. Some of the [ResponseHeaderAsync tests](https://github.com/grpc/grpc/blob/master/src/csharp/Grpc.Core.Tests/ResponseHeadersTest.cs#L65-L81) might be informative for you here as well, they exercise this behavior. I'm not sure we're looking at a bug here, this might be a better question for another forum (stackoverflow, or the grpc mailing list). @jtattermusch, please take a look, maybe my assessment is off.

**Comment by alexhcheng** [comment] 2021-06-04 16:24
hi @drfloob , i did try the latest build v2.38 and it has the same behavior.  Perhaps this is by design?  there is no way to send the responseheader back earlier in a unary call?

**Comment by jtattermusch** [comment] 2022-03-09 15:15
> hi @drfloob , i did try the latest build v2.38 and it has the same behavior. Perhaps this is by design? there is no way to send the responseheader back earlier in a unary call?

It should definitely be possible for the server to send the response headers independently from sending the first response (That is send response headers form the server side handler and receive them on the client regardless of how late you return the response from the server-side handler).
Can you please share a ready-to-run reproduction of the problem (e.g. as a github repo)? As @drfloob  has pointed out, we basically have a test that makes sure that the above works, so it would be interesting to see what is it that you're doing differently.

**Comment by rburns1293** [comment] 2022-03-11 02:45
The test below reproduces the issue. It'll only pass if the Computation delay is less than the 10s wait time of the ResponseHeadersAsync. 
```C#
public async Task ResponseHeadersAsync_UnaryCall()
        {
            helper.UnaryHandler = new UnaryServerMethod<string, string>(async (request, context) =>
            {
                await context.WriteResponseHeadersAsync(headers);
                Console.WriteLine("Header sent...");
                Console.WriteLine("Waiting for computation...");
                await Task.Delay(20000);
                return "PASS";
            });
            var call = Calls.AsyncUnaryCall(helper.CreateUnaryCall(), "");
            Metadata responseHeaders = null;
            Task t1 = Task.Run(async () => {
                Console.WriteLine("Waiting for header...");
                responseHeaders = await call.ResponseHeadersAsync;
                Console.WriteLine("Header received!");
            });
            Assert.True(t1.Wait(10000));
            Assert.AreEqual(headers.Count, responseHeaders.Count);
            Assert.AreEqual("ascii-header", responseHeaders[0].Key);
            Assert.AreEqual("abcdefg", responseHeaders[0].Value);

            Assert.AreEqual("PASS", await call.ResponseAsync);
        }
```

**Comment by jtattermusch** [comment] 2022-03-15 11:11
As posted above, we've been able to confirm the behavior reported by this issue.

While this is something that could be fixed (basically by internally splitting the HandleUnaryResponse handler into two separate handlers and registering two C-core operation batches while creating unary call instead of just one), it would be a relatively complex change to do so. It would probably also have some performance impact since it would increase the overhead for all unary calls (needing to register / process two completion notifications instead of just one). Given that Grpc.Core is currently in maintenance mode (see https://grpc.io/blog/grpc-csharp-future/) I don't think it's worth the work to invest into a fix (which can potentially introduce other issues or harm performance) now, also since this is also likely a behavior that doesn't affect many users (for most unary RPC, there's really no needed receive response headers and the response message is two separate events).

I think the best way forward is to simply keep the imperfect behavior for Unary and Client streaming calls the way it is (acknowledging the limitations in terms of receiving response headers in separately advance).

For the less frequent scenarios where you really need to be able to access the response headers prior to reading the response message, you can use a server-streaming or duplex streaming call as a workaround (for these  types of calls things behave the way they should and we have tests in place to ensure that).

**Closed by jtattermusch** 2022-03-15 11:11 UTC
Labels: kind/bug, lang/C#, priority/P2

**Comment by alexhcheng** [comment] 2022-03-15 15:49
thanks for following up on this @jtattermusch .
