### ISSUE TITLE
(opt, c, macos) failure:  h2_full_test_hpack_size

### ISSUE THREAD

**Issue by jtattermusch** [grpc/grpc#5715] opened 2016-03-11 17:00 UTC
https://grpc-testing.appspot.com/job/gRPC_master/15722/config=opt,language=c,platform=macos/testReport/junit/(root)/tests/bins_opt_h2_full_test_hpack_size/

```
D0311 04:49:59.043229000 140735177569024 hpack_encoder.c:532] set max table size from encoder to 100
D0311 04:49:59.043271000 140735177569024 hpack_encoder.c:532] set max table size from encoder to 0
D0311 04:49:59.044398000 140735177569024 hpack_table.c:254] Update hpack parser max size to 0
I0311 04:49:59.044431000 140735177569024 hpack_parser.c:922] MAX TABLE SIZE: 0
D0311 04:49:59.044461000 140735177569024 hpack_table.c:272] Update hpack parser table size to 0
E0311 04:50:14.309222000 140735177569024 cq_verifier.c:248] event not found: OP_COMPLETE: tag:0x1 OK
E0311 04:50:14.309247000 140735177569024 cq_verifier.c:251] have tags: 0x65



*******************************
Caught signal 6
  no backtrace
```

**Comment by ctiller** [comment] 2016-04-25 19:35
Can you do initial investigation here please @dgquintas?

**Comment by dgquintas** [comment] 2016-04-25 19:38
sure thing

**Comment by dgquintas** [comment] 2016-04-26 20:21
I've been unable to reproduce after several minutes of running over this test with plenty of antagonists (HEAD at a49e73090cf4e0543dc946eec0eb17dd880b3538). Waiting a couple more days to see if it surfaces again before closing...

**Comment by dgquintas** [comment] 2016-04-29 17:43
Not seen for a while, closing for now.

**Closed by dgquintas** 2016-04-29 17:43 UTC
Labels: BUILDPONY, core, MacOS, P1
