### ISSUE TITLE
build failing for dbg,python,windows

### ISSUE THREAD

**Issue by a11r** [grpc/grpc#6565] opened 2016-05-12 18:35 UTC
https://grpc-testing.appspot.com/job/gRPC_master/config=dbg,language=python,platform=windows/

**Comment by soltanmm** [comment] 2016-05-12 23:04
That was me flipping the switch, seeing if things worked, and apparently forgetting to turn it off again.

**Comment by soltanmm** [comment] 2016-05-12 23:07
Disabled; remaining work is basically a duplicate of #5163.

**Closed by soltanmm** 2016-05-12 23:07 UTC
