### ISSUE TITLE
Failure: tests.cloud_to_prod_auth:default:c++:jwt_token_creds (from grpc.tests)

### ISSUE THREAD

**Issue by AspirinSJL** [grpc/grpc#12576] opened 2017-09-14 17:05 UTC
https://grpc-testing.appspot.com/job/gRPC_interop_pull_requests/16630/testReport/junit/(root)/tests/cloud_to_prod_auth_default_c___jwt_token_creds/

https://grpc-testing.appspot.com/job/gRPC_interop_pull_requests/16630/console

```
Error Message

Failure
Stacktrace

I0914 00:38:13.730453147       1 client.cc:91]               Testing these cases: jwt_token_creds
E0914 00:38:13.742890147       1 interop_client.cc:143]      Error status code: 14 (expected: 0), message: Connect Failed
```

**Comment by jtattermusch** [comment] 2017-11-06 15:15
Looks like dupe of #10763.

**Closed by jtattermusch** 2017-11-06 15:15 UTC
Labels: infra/BUILDPONY
