### ISSUE TITLE
Objc test build failure

### ISSUE THREAD

**Issue by apolcyn** [grpc/grpc#17492] opened 2018-12-13 03:13 UTC
Lots of "foo has no symbols" in the log.

https://source.cloud.google.com/results/invocations/b5470a12-06dd-49a5-aebe-408ee4edc842/targets/github%2Fgrpc%2Fobjc_macos_opt_native/log

```
/Applications/Xcode_9.2.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: for architecture: x86_64 file: /Users/kbuilder/Library/Developer/Xcode/DerivedData/Tests-fbrsdwcwvahgdwfbkkumiqqzuyix/Build/Intermediates.noindex/Pods.build/Test-iphonesimulator/gRPC-Core.build/Objects-normal/x86_64/libgRPC-Core.a(tcp_server_utils_posix_noifaddrs.o) has no symbols
/Applications/Xcode_9.2.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: for architecture: x86_64 file: /Users/kbuilder/Library/Developer/Xcode/DerivedData/Tests-fbrsdwcwvahgdwfbkkumiqqzuyix/Build/Intermediates.noindex/Pods.build/Test-iphonesimulator/gRPC-Core.build/Objects-normal/x86_64/libgRPC-Core.a(tcp_server_windows.o) has no symbols
/Applications/Xcode_9.2.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: for architecture: x86_64 file: /Users/kbuilder/Library/Developer/Xcode/DerivedData/Tests-fbrsdwcwvahgdwfbkkumiqqzuyix/Build/Intermediates.noindex/Pods.build/Test-iphonesimulator/gRPC-Core.build/Objects-normal/x86_64/libgRPC-Core.a(tcp_uv.o) has no symbols
/Applications/Xcode_9.2.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: for architecture: x86_64 file: /Users/kbuilder/Library/Developer/Xcode/DerivedData/Tests-fbrsdwcwvahgdwfbkkumiqqzuyix/Build/Intermediates.noindex/Pods.build/Test-iphonesimulator/gRPC-Core.build/Objects-normal/x86_64/libgRPC-Core.a(tcp_windows.o) has no symbols
/Applications/Xcode_9.2.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: for architecture: x86_64 file: /Users/kbuilder/Library/Developer/Xcode/DerivedData/Tests-fbrsdwcwvahgdwfbkkumiqqzuyix/Build/Intermediates.noindex/Pods.build/Test-iphonesimulator/gRPC-Core.build/Objects-normal/x86_64/libgRPC-Core.a(thd_windows.o) has no symbols
/Applications/Xcode_9.2.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: for architecture: x86_64 file: /Users/kbuilder/Library/Developer/Xcode/DerivedData/Tests-fbrsdwcwvahgdwfbkkumiqqzuyix/Build/Intermediates.noindex/Pods.build/Test-iphonesimulator/gRPC-Core.build/Objects-normal/x86_64/libgRPC-Core.a(time_windows.o) has no symbols
/Applications/Xcode_9.2.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: for architecture: x86_64 file: /Users/kbuilder/Library/Developer/Xcode/DerivedData/Tests-fbrsdwcwvahgdwfbkkumiqqzuyix/Build/Intermediates.noindex/Pods.build/Test-iphonesimulator/gRPC-Core.build/Objects-normal/x86_64/libgRPC-Core.a(timer_uv.o) has no symbols
/Applications/Xcode_9.2.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: for architecture: x86_64 file: /Users/kbuilder/Library/Developer/Xcode/DerivedData/Tests-fbrsdwcwvahgdwfbkkumiqqzuyix/Build/Intermediates.noindex/Pods.build/Test-iphonesimulator/gRPC-Core.build/Objects-normal/x86_64/libgRPC-Core.a(tmpfile_msys.o) has no symbols
/Applications/Xcode_9.2.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: for architecture: x86_64 file: /Users/kbuilder/Library/Developer/Xcode/DerivedData/Tests-fbrsdwcwvahgdwfbkkumiqqzuyix/Build/Intermediates.noindex/Pods.build/Test-iphonesimulator/gRPC-Core.build/Objects-normal/x86_64/libgRPC-Core.a(tmpfile_windows.o) has no symbols
/Applications/Xcode_9.2.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: for architecture: x86_64 file: /Users/kbuilder/Library/Developer/Xcode/DerivedData/Tests-fbrsdwcwvahgdwfbkkumiqqzuyix/Build/Intermediates.noindex/Pods.build/Test-iphonesimulator/gRPC-Core.build/Objects-normal/x86_64/libgRPC-Core.a(unix_sockets_posix_noop.o) has no symbols
/Applications/Xcode_9.2.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: for architecture: x86_64 file: /Users/kbuilder/Library/Developer/Xcode/DerivedData/Tests-fbrsdwcwvahgdwfbkkumiqqzuyix/Build/Intermediates.noindex/Pods.build/Test-iphonesimulator/gRPC-Core.build/Objects-normal/x86_64/libgRPC-Core.a(wakeup_fd_eventfd.o) has no symbols
/Applications/Xcode_9.2.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: for architecture: x86_64 file: /Users/kbuilder/Library/Developer/Xcode/DerivedData/Tests-fbrsdwcwvahgdwfbkkumiqqzuyix/Build/Intermediates.noindex/Pods.build/Test-iphonesimulator/gRPC-Core.build/Objects-normal/x86_64/libgRPC-Core.a(wrap_memcpy.o) has no symbols
=== BUILD TARGET gRPC OF PROJECT Pods WITH CONFIGURATION Test ===
Check dependencies
Write auxiliary files
write-file /Users/kbuilder/Library/Developer/Xcode/DerivedData/Tests-fbrsdwcwvahgdwfbkkumiqqzuyix/Build/Intermediates.noindex/Pods.build/Test-iphonesimulator/gRPC.build/gRPC-all-non-framework-target-headers.hmap
write-file /Users/kbuilder/Library/Developer/Xcode/DerivedData/Tests-fbrsdwcwvahgdwfbkkumiqqzuyix/Build/Intermediates.noindex/Pods.build/Test-iphonesimulator/gRPC.build/gRPC-own-target-headers.hmap
write-file /Users/kbuilder/Library/Developer/Xcode/DerivedData/Tests-fbrsdwcwvahgdwfbkkumiqqzuyix/Build/Intermediates.noindex/Pods.build/Test-iphonesimulator/gRPC.build/gRPC.hmap
write-file /Users/kbuilder/Library/Developer/Xcode/DerivedData/Tests-fbrsdwcwvahgdwfbkkumiqqzuyix/Build/Intermediates.noindex/Pods.build/Test-iphonesimulator/gRPC.build/gRPC-project-headers.hmap
write-file /Users/kbuilder/Library/Developer/Xcode/DerivedData/Tests-fbrsdwcwvahgdwfbkkumiqqzuyix/Build/Intermediates.noindex/Pods.build/Test-iphonesimulator/gRPC.build/gRPC-all-target-headers.hmap
/bin/mkdir -p /Users/kbuilder/Library/Developer/Xcode/DerivedData/Tests-fbrsdwcwvahgdwfbkkumiqqzuyix/Build/Intermediates.noindex/Pods.build/Test-iphonesimulator/gRPC.build/Objects-normal/i386
write-file /Users/kbuilder/Library/Developer/Xcode/DerivedData/Tests-fbrsdwcwvahgdwfbkkumiqqzuyix/Build/Intermediates.noindex/Pods.build/Test-iphonesimulator/gRPC.build/Objects-normal/i386/gRPC.LinkFileList
write-file /Users/kbuilder/Library/Developer/Xcode/DerivedData/Tests-fbrsdwcwvahgdwfbkkumiqqzuyix/Build/Intermediates.noindex/Pods.build/Test-iphonesimulator/gRPC.build/gRPC-generated-files.hmap
/bin/mkdir -p /Users/kbuilder/Library/Developer/Xcode/DerivedData/Tests-fbrsdwcwvahgdwfbkkumiqqzuyix/Build/Intermediates.noindex/Pods.build/Test-iphonesimulator/gRPC.build/Objects-normal/x86_64
write-file /Users/kbuilder/Library/Developer/Xcode/DerivedData/Tests-fbrsdwcwvahgdwfbkkumiqqzuyix/Build/Intermediates.noindex/Pods.build/Test-iphonesimulator/gRPC.build/Objects-normal/x86_64/gRPC.LinkFileList
/Applications/Xcode_9.2.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: file: /Users/kbuilder/Library/Developer/Xcode/DerivedData/Tests-fbrsdwcwvahgdwfbkkumiqqzuyix/Build/Intermediates.noindex/Pods.build/Test-iphonesimulator/gRPC.build/Objects-normal/i386/GRPCCall+Cronet.o has no symbols
/Applications/Xcode_9.2.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: file: /Users/kbuilder/Library/Developer/Xcode/DerivedData/Tests-fbrsdwcwvahgdwfbkkumiqqzuyix/Build/Intermediates.noindex/Pods.build/Test-iphonesimulator/gRPC.build/Objects-normal/x86_64/GRPCCall+Cronet.o has no symbols
CreateUniversalBinary /Users/kbuilder/Library/Developer/Xcode/DerivedData/Tests-fbrsdwcwvahgdwfbkkumiqqzuyix/Build/Products/Test-iphonesimulator/gRPC/libgRPC.a normal i386\ x86_64
/Applications/Xcode_9.2.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: for architecture: i386 file: /Users/kbuilder/Library/Developer/Xcode/DerivedData/Tests-fbrsdwcwvahgdwfbkkumiqqzuyix/Build/Intermediates.noindex/Pods.build/Test-iphonesimulator/gRPC.build/Objects-normal/i386/libgRPC.a(GRPCCall+Cronet.o) has no symbols
/Applications/Xcode_9.2.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: for architecture: x86_64 file: /Users/kbuilder/Library/Developer/Xcode/DerivedData/Tests-fbrsdwcwvahgdwfbkkumiqqzuyix/Build/Intermediates.noindex/Pods.build/Test-iphonesimulator/gRPC.build/Objects-normal/x86_64/libgRPC.a(GRPCCall+Cronet.o) has no symbols
=== BUILD TARGET gRPC-ProtoRPC OF PROJECT Pods WITH CONFIGURATION Test ===
Check dependencies
Write auxiliary files
write-file /Users/kbuilder/Library/Developer/Xcode/DerivedData/Tests-fbrsdwcwvahgdwfbkkumiqqzuyix/Build/Intermediates.noindex/Pods.build/Test-iphonesimulator/gRPC-ProtoRPC.build/gRPC-ProtoRPC-generated-files.hmap
write-file /Users/kbuilder/Library/Developer/Xcode/DerivedData/Tests-fbrsdwcwvahgdwfbkkumiqqzuyix/Build/Intermediates.noindex/Pods.build/Test-iphonesimulator/gRPC-ProtoRPC.build/gRPC-ProtoRPC.hmap
write-file /Users/kbuilder/Library/Developer/Xcode/DerivedData/Tests-fbrsdwcwvahgdwfbkkumiqqzuyix/Build/Intermediates.noindex/Pods.build/Test-iphonesimulator/gRPC-ProtoRPC.build/gRPC-ProtoRPC-all-non-framework-target-headers.hmap
write-file /Users/kbuilder/Library/Developer/Xcode/DerivedData/Tests-fbrsdwcwvahgdwfbkkumiqqzuyix/Build/Intermediates.noindex/Pods.build/Test-iphonesimulator/gRPC-ProtoRPC.build/gRPC-ProtoRPC-all-target-headers.hmap
/bin/mkdir -p /Users/kbuilder/Library/Developer/Xcode/DerivedData/Tests-fbrsdwcwvahgdwfbkkumiqqzuyix/Build/Intermediates.noindex/Pods.build/Test-iphonesimulator/gRPC-ProtoRPC.build/Objects-normal/x86_64
write-file /Users/kbuilder/Library/Developer/Xcode/DerivedData/Tests-fbrsdwcwvahgdwfbkkumiqqzuyix/Build/Intermediates.noindex/Pods.build/Test-iphonesimulator/gRPC-ProtoRPC.build/Objects-normal/x86_64/gRPC-ProtoRPC.LinkFileList
/bin/mkdir -p /Users/kbuilder/Library/Developer/Xcode/DerivedData/Tests-fbrsdwcwvahgdwfbkkumiqqzuyix/Build/Intermediates.noindex/Pods.build/Test-iphonesimulator/gRPC-ProtoRPC.build/Objects-normal/i386
write-file /Users/kbuilder/Library/Developer/Xcode/DerivedData/Tests-fbrsdwcwvahgdwfbkkumiqqzuyix/Build/Intermediates.noindex/Pods.build/Test-iphonesimulator/gRPC-ProtoRPC.build/Objects-normal/i386/gRPC-ProtoRPC.LinkFileList
write-file /Users/kbuilder/Library/Developer/Xcode/DerivedData/Tests-fbrsdwcwvahgdwfbkkumiqqzuyix/Build/Intermediates.noindex/Pods.build/Test-iphonesimulator/gRPC-ProtoRPC.build/gRPC-ProtoRPC-project-headers.hmap
write-file /Users/kbuilder/Library/Developer/Xcode/DerivedData/Tests-fbrsdwcwvahgdwfbkkumiqqzuyix/Build/Intermediates.noindex/Pods.build/Test-iphonesimulator/gRPC-ProtoRPC.build/gRPC-ProtoRPC-own-target-headers.hmap
CreateUniversalBinary /Users/kbuilder/Library/Developer/Xcode/DerivedData/Tests-fbrsdwcwvahgdwfbkkumiqqzuyix/Build/Products/Test-iphonesimulator/gRPC-ProtoRPC/libgRPC-ProtoRPC.a normal i386\ x86_64
=== BUILD TARGET RemoteTest OF PROJECT Pods WITH CONFIGURATION Test ===
Check dependencies
Write auxiliary files
write-file /Users/kbuilder/Library/Developer/Xcode/DerivedData/Tests-fbrsdwcwvahgdwfbkkumiqqzuyix/Build/Intermediates.noindex/Pods.build/Test-iphonesimulator/RemoteTest.build/RemoteTest-own-target-headers.hmap
write-file /Users/kbuilder/Library/Developer/Xcode/DerivedData/Tests-fbrsdwcwvahgdwfbkkumiqqzuyix/Build/Intermediates.noindex/Pods.build/Test-iphonesimulator/RemoteTest.build/RemoteTest-all-target-headers.hmap
write-file /Users/kbuilder/Library/Developer/Xcode/DerivedData/Tests-fbrsdwcwvahgdwfbkkumiqqzuyix/Build/Intermediates.noindex/Pods.build/Test-iphonesimulator/RemoteTest.build/RemoteTest.hmap
write-file /Users/kbuilder/Library/Developer/Xcode/DerivedData/Tests-fbrsdwcwvahgdwfbkkumiqqzuyix/Build/Intermediates.noindex/Pods.build/Test-iphonesimulator/RemoteTest.build/RemoteTest-all-non-framework-target-headers.hmap
write-file /Users/kbuilder/Library/Developer/Xcode/DerivedData/Tests-fbrsdwcwvahgdwfbkkumiqqzuyix/Build/Intermediates.noindex/Pods.build/Test-iphonesimulator/RemoteTest.build/RemoteTest-project-headers.hmap
write-file /Users/kbuilder/Library/Developer/Xcode/DerivedData/Tests-fbrsdwcwvahgdwfbkkumiqqzuyix/Build/Intermediates.noindex/Pods.build/Test-iphonesimulator/RemoteTest.build/RemoteTest-generated-files.hmap
/bin/mkdir -p /Users/kbuilder/Library/Developer/Xcode/DerivedData/Tests-fbrsdwcwvahgdwfbkkumiqqzuyix/Build/Intermediates.noindex/Pods.build/Test-iphonesimulator/RemoteTest.build/Objects-normal/x86_64
write-file /Users/kbuilder/Library/Developer/Xcode/DerivedData/Tests-fbrsdwcwvahgdwfbkkumiqqzuyix/Build/Intermediates.noindex/Pods.build/Test-iphonesimulator/RemoteTest.build/Objects-normal/x86_64/RemoteTest.LinkFileList
/bin/mkdir -p /Users/kbuilder/Library/Developer/Xcode/DerivedData/Tests-fbrsdwcwvahgdwfbkkumiqqzuyix/Build/Intermediates.noindex/Pods.build/Test-iphonesimulator/RemoteTest.build/Objects-normal/i386
write-file /Users/kbuilder/Library/Developer/Xcode/DerivedData/Tests-fbrsdwcwvahgdwfbkkumiqqzuyix/Build/Intermediates.noindex/Pods.build/Test-iphonesimulator/RemoteTest.build/Objects-normal/i386/RemoteTest.LinkFileList
CreateUniversalBinary /Users/kbuilder/Library/Developer/Xcode/DerivedData/Tests-fbrsdwcwvahgdwfbkkumiqqzuyix/Build/Products/Test-iphonesimulator/RemoteTest/libRemoteTest.a normal i386\ x86_64
=== BUILD TARGET Pods-AllTests OF PROJECT Pods WITH CONFIGURATION Test ===
Check dependencies
Write auxiliary files
write-file /Users/kbuilder/Library/Developer/Xcode/DerivedData/Tests-fbrsdwcwvahgdwfbkkumiqqzuyix/Build/Intermediates.noindex/Pods.build/Test-iphonesimulator/Pods-AllTests.build/Pods-AllTests-all-non-framework-target-headers.hmap
write-file /Users/kbuilder/Library/Developer/Xcode/DerivedData/Tests-fbrsdwcwvahgdwfbkkumiqqzuyix/Build/Intermediates.noindex/Pods.build/Test-iphonesimulator/Pods-AllTests.build/Pods-AllTests-own-target-headers.hmap
write-file /Users/kbuilder/Library/Developer/Xcode/DerivedData/Tests-fbrsdwcwvahgdwfbkkumiqqzuyix/Build/Intermediates.noindex/Pods.build/Test-iphonesimulator/Pods-AllTests.build/Pods-AllTests.hmap
write-file /Users/kbuilder/Library/Developer/Xcode/DerivedData/Tests-fbrsdwcwvahgdwfbkkumiqqzuyix/Build/Intermediates.noindex/Pods.build/Test-iphonesimulator/Pods-AllTests.build/Pods-AllTests-project-headers.hmap
/bin/mkdir -p /Users/kbuilder/Library/Developer/Xcode/DerivedData/Tests-fbrsdwcwvahgdwfbkkumiqqzuyix/Build/Intermediates.noindex/Pods.build/Test-iphonesimulator/Pods-AllTests.build/Objects-normal/x86_64
write-file /Users/kbuilder/Library/Developer/Xcode/DerivedData/Tests-fbrsdwcwvahgdwfbkkumiqqzuyix/Build/Intermediates.noindex/Pods.build/Test-iphonesimulator/Pods-AllTests.build/Objects-normal/x86_64/Pods-AllTests.LinkFileList
write-file /Users/kbuilder/Library/Developer/Xcode/DerivedData/Tests-fbrsdwcwvahgdwfbkkumiqqzuyix/Build/Intermediates.noindex/Pods.build/Test-iphonesimulator/Pods-AllTests.build/Pods-AllTests-generated-files.hmap
/bin/mkdir -p /Users/kbuilder/Library/Developer/Xcode/DerivedData/Tests-fbrsdwcwvahgdwfbkkumiqqzuyix/Build/Intermediates.noindex/Pods.build/Test-iphonesimulator/Pods-AllTests.build/Objects-normal/i386
write-file /Users/kbuilder/Library/Developer/Xcode/DerivedData/Tests-fbrsdwcwvahgdwfbkkumiqqzuyix/Build/Intermediates.noindex/Pods.build/Test-iphonesimulator/Pods-AllTests.build/Objects-normal/i386/Pods-AllTests.LinkFileList
write-file /Users/kbuilder/Library/Developer/Xcode/DerivedData/Tests-fbrsdwcwvahgdwfbkkumiqqzuyix/Build/Intermediates.noindex/Pods.build/Test-iphonesimulator/Pods-AllTests.build/Pods-AllTests-all-target-headers.hmap
CreateUniversalBinary /Users/kbuilder/Library/Developer/Xcode/DerivedData/Tests-fbrsdwcwvahgdwfbkkumiqqzuyix/Build/Products/Test-iphonesimulator/libPods-AllTests.a normal i386\ x86_64
=== BUILD TARGET AllTests OF PROJECT Tests WITH CONFIGURATION Test ===
Check dependencies
Write auxiliary files
write-file /Users/kbuilder/Library/Developer/Xcode/DerivedData/Tests-fbrsdwcwvahgdwfbkkumiqqzuyix/Build/Intermediates.noindex/Tests.build/Test-iphonesimulator/AllTests.build/AllTests-project-headers.hmap
write-file /Users/kbuilder/Library/Developer/Xcode/DerivedData/Tests-fbrsdwcwvahgdwfbkkumiqqzuyix/Build/Intermediates.noindex/Tests.build/Test-iphonesimulator/AllTests.build/AllTests-own-target-headers.hmap
write-file /Users/kbuilder/Library/Developer/Xcode/DerivedData/Tests-fbrsdwcwvahgdwfbkkumiqqzuyix/Build/Intermediates.noindex/Tests.build/Test-iphonesimulator/AllTests.build/AllTests-generated-files.hmap
write-file /Users/kbuilder/Library/Developer/Xcode/DerivedData/Tests-fbrsdwcwvahgdwfbkkumiqqzuyix/Build/Intermediates.noindex/Tests.build/Test-iphonesimulator/AllTests.build/AllTests.hmap
write-file /Users/kbuilder/Library/Developer/Xcode/DerivedData/Tests-fbrsdwcwvahgdwfbkkumiqqzuyix/Build/Intermediates.noindex/Tests.build/Test-iphonesimulator/AllTests.build/AllTests-all-target-headers.hmap
write-file /Users/kbuilder/Library/Developer/Xcode/DerivedData/Tests-fbrsdwcwvahgdwfbkkumiqqzuyix/Build/Intermediates.noindex/Tests.build/Test-iphonesimulator/AllTests.build/Script-A441F71824DCB9D0CA297748.sh
chmod 0755 /Users/kbuilder/Library/Developer/Xcode/DerivedData/Tests-fbrsdwcwvahgdwfbkkumiqqzuyix/Build/Intermediates.noindex/Tests.build/Test-iphonesimulator/AllTests.build/Script-A441F71824DCB9D0CA297748.sh
write-file /Users/kbuilder/Library/Developer/Xcode/DerivedData/Tests-fbrsdwcwvahgdwfbkkumiqqzuyix/Build/Intermediates.noindex/Tests.build/Test-iphonesimulator/AllTests.build/Script-914ADDD7106BA9BB8A7E569F.sh
chmod 0755 /Users/kbuilder/Library/Developer/Xcode/DerivedData/Tests-fbrsdwcwvahgdwfbkkumiqqzuyix/Build/Intermediates.noindex/Tests.build/Test-iphonesimulator/AllTests.build/Script-914ADDD7106BA9BB8A7E569F.sh
/bin/mkdir -p /Users/kbuilder/Library/Developer/Xcode/DerivedData/Tests-fbrsdwcwvahgdwfbkkumiqqzuyix/Build/Intermediates.noindex/Tests.build/Test-iphonesimulator/AllTests.build/Objects-normal/x86_64
write-file /Users/kbuilder/Library/Developer/Xcode/DerivedData/Tests-fbrsdwcwvahgdwfbkkumiqqzuyix/Build/Intermediates.noindex/Tests.build/Test-iphonesimulator/AllTests.build/Objects-normal/x86_64/AllTests.LinkFileList
write-file /Users/kbuilder/Library/Developer/Xcode/DerivedData/Tests-fbrsdwcwvahgdwfbkkumiqqzuyix/Build/Intermediates.noindex/Tests.build/Test-iphonesimulator/AllTests.build/Script-F91611815A8913EDE136BCEC.sh
chmod 0755 /Users/kbuilder/Library/Developer/Xcode/DerivedData/Tests-fbrsdwcwvahgdwfbkkumiqqzuyix/Build/Intermediates.noindex/Tests.build/Test-iphonesimulator/AllTests.build/Script-F91611815A8913EDE136BCEC.sh
write-file /Users/kbuilder/Library/Developer/Xcode/DerivedData/Tests-fbrsdwcwvahgdwfbkkumiqqzuyix/Build/Intermediates.noindex/Tests.build/Test-iphonesimulator/AllTests.build/AllTests-all-non-framework-target-headers.hmap
Create product structure
/bin/mkdir -p /Users/kbuilder/Library/Developer/Xcode/DerivedData/Tests-fbrsdwcwvahgdwfbkkumiqqzuyix/Build/Products/Test-iphonesimulator/AllTests.xctest
ProcessInfoPlistFile /Users/kbuilder/Library/Developer/Xcode/DerivedData/Tests-fbrsdwcwvahgdwfbkkumiqqzuyix/Build/Products/Test-iphonesimulator/AllTests.xctest/Info.plist Info.plist
    builtin-infoPlistUtility /Volumes/BuildData/tmpfs/src/github/grpc/workspace_objc_macos_opt_native/src/objective-c/tests/Info.plist -expandbuildsettings -format binary -platform iphonesimulator -o /Users/kbuilder/Library/Developer/Xcode/DerivedData/Tests-fbrsdwcwvahgdwfbkkumiqqzuyix/Build/Products/Test-iphonesimulator/AllTests.xctest/Info.plist
ProcessProductPackaging "" /Users/kbuilder/Library/Developer/Xcode/DerivedData/Tests-fbrsdwcwvahgdwfbkkumiqqzuyix/Build/Intermediates.noindex/Tests.build/Test-iphonesimulator/AllTests.build/AllTests.xctest.xcent
Entitlements:
{
    "application-identifier" = "FAKETEAMID.gRPC.AllTests";
    "keychain-access-groups" =     (
        "FAKETEAMID.gRPC.AllTests"
    );
}
    builtin-productPackagingUtility -entitlements -format xml -o /Users/kbuilder/Library/Developer/Xcode/DerivedData/Tests-fbrsdwcwvahgdwfbkkumiqqzuyix/Build/Intermediates.noindex/Tests.build/Test-iphonesimulator/AllTests.build/AllTests.xctest.xcent
PhaseScriptExecution [CP]\ Check\ Pods\ Manifest.lock /Users/kbuilder/Library/Developer/Xcode/DerivedData/Tests-fbrsdwcwvahgdwfbkkumiqqzuyix/Build/Intermediates.noindex/Tests.build/Test-iphonesimulator/AllTests.build/Script-914ADDD7106BA9BB8A7E569F.sh
    /bin/sh -c /Users/kbuilder/Library/Developer/Xcode/DerivedData/Tests-fbrsdwcwvahgdwfbkkumiqqzuyix/Build/Intermediates.noindex/Tests.build/Test-iphonesimulator/AllTests.build/Script-914ADDD7106BA9BB8A7E569F.sh
ld: warning: directory not found for option '-F/Applications/Xcode_9.2.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator11.2.sdk/Developer/Library/Frameworks'
GenerateDSYMFile /Users/kbuilder/Library/Developer/Xcode/DerivedData/Tests-fbrsdwcwvahgdwfbkkumiqqzuyix/Build/Products/Test-iphonesimulator/AllTests.xctest.dSYM /Users/kbuilder/Library/Developer/Xcode/DerivedData/Tests-fbrsdwcwvahgdwfbkkumiqqzuyix/Build/Products/Test-iphonesimulator/AllTests.xctest/AllTests
    /Applications/Xcode_9.2.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/dsymutil /Users/kbuilder/Library/Developer/Xcode/DerivedData/Tests-fbrsdwcwvahgdwfbkkumiqqzuyix/Build/Products/Test-iphonesimulator/AllTests.xctest/AllTests -o /Users/kbuilder/Library/Developer/Xcode/DerivedData/Tests-fbrsdwcwvahgdwfbkkumiqqzuyix/Build/Products/Test-iphonesimulator/AllTests.xctest.dSYM
CpResource TestCertificates.bundle /Users/kbuilder/Library/Developer/Xcode/DerivedData/Tests-fbrsdwcwvahgdwfbkkumiqqzuyix/Build/Products/Test-iphonesimulator/AllTests.xctest/TestCertificates.bundle
PhaseScriptExecution [CP]\ Copy\ Pods\ Resources /Users/kbuilder/Library/Developer/Xcode/DerivedData/Tests-fbrsdwcwvahgdwfbkkumiqqzuyix/Build/Intermediates.noindex/Tests.build/Test-iphonesimulator/AllTests.build/Script-A441F71824DCB9D0CA297748.sh
    /bin/sh -c /Users/kbuilder/Library/Developer/Xcode/DerivedData/Tests-fbrsdwcwvahgdwfbkkumiqqzuyix/Build/Intermediates.noindex/Tests.build/Test-iphonesimulator/AllTests.build/Script-A441F71824DCB9D0CA297748.sh
/Users/kbuilder/Library/Developer/Xcode/DerivedData/Tests-fbrsdwcwvahgdwfbkkumiqqzuyix/Build/Products/Test-iphonesimulator/gRPC/gRPCCertificates.bundle
building file list ... done
gRPCCertificates.bundle/
gRPCCertificates.bundle/Info.plist
gRPCCertificates.bundle/roots.pem
gRPCCertificates.bundle/_CodeSignature/
gRPCCertificates.bundle/_CodeSignature/CodeDirectory
gRPCCertificates.bundle/_CodeSignature/CodeRequirements
gRPCCertificates.bundle/_CodeSignature/CodeRequirements-1
gRPCCertificates.bundle/_CodeSignature/CodeResources
gRPCCertificates.bundle/_CodeSignature/CodeSignature
sent 270019 bytes  received 186 bytes  540410.00 bytes/sec
total size is 269396  speedup is 1.00
PhaseScriptExecution [CP]\ Embed\ Pods\ Frameworks /Users/kbuilder/Library/Developer/Xcode/DerivedData/Tests-fbrsdwcwvahgdwfbkkumiqqzuyix/Build/Intermediates.noindex/Tests.build/Test-iphonesimulator/AllTests.build/Script-F91611815A8913EDE136BCEC.sh
    /bin/sh -c /Users/kbuilder/Library/Developer/Xcode/DerivedData/Tests-fbrsdwcwvahgdwfbkkumiqqzuyix/Build/Intermediates.noindex/Tests.build/Test-iphonesimulator/AllTests.build/Script-F91611815A8913EDE136BCEC.sh
mkdir -p /Users/kbuilder/Library/Developer/Xcode/DerivedData/Tests-fbrsdwcwvahgdwfbkkumiqqzuyix/Build/Products/Test-iphonesimulator/AllTests.xctest/Frameworks
Touch /Users/kbuilder/Library/Developer/Xcode/DerivedData/Tests-fbrsdwcwvahgdwfbkkumiqqzuyix/Build/Products/Test-iphonesimulator/AllTests.xctest
    /usr/bin/touch -c /Users/kbuilder/Library/Developer/Xcode/DerivedData/Tests-fbrsdwcwvahgdwfbkkumiqqzuyix/Build/Products/Test-iphonesimulator/AllTests.xctest
CodeSign /Users/kbuilder/Library/Developer/Xcode/DerivedData/Tests-fbrsdwcwvahgdwfbkkumiqqzuyix/Build/Products/Test-iphonesimulator/AllTests.xctest
Signing Identity:     "-"
    /usr/bin/codesign --force --sign - --timestamp=none /Users/kbuilder/Library/Developer/Xcode/DerivedData/Tests-fbrsdwcwvahgdwfbkkumiqqzuyix/Build/Products/Test-iphonesimulator/AllTests.xctest
** TEST FAILED **
```

seen on PR: https://github.com/grpc/grpc/pull/17470

**Comment by muxi** [comment] 2018-12-13 17:42
I did not find a "foo has no symbol" reference in the link provided. The failure looks like a duplicate of #16497

**Closed by muxi** 2018-12-13 17:42 UTC
Labels: lang/ObjC
