### ISSUE TITLE
A regression bug of grpc Python library: grpc_tools.protoc.ProtoFinder isn't set.

### ISSUE THREAD

**Issue by c-bata** [grpc/grpc#26631] opened 2021-07-08 05:52 UTC
### What version of gRPC and what language are you using?
1.38.1

### What operating system (Linux, Windows,...) and version?
macOS

### What runtime / compiler are you using (e.g. python version or version of gcc)
Python 3.9.0

### What did you do?

I found a bug that it raises ModuleNotFoundError by importing a protoc-generated module after upgraded `grpcio` to `1.38.1` from `1.33.2`. I created a repository for reproducing the bug.

https://github.com/c-bata/grpc-issue-proto-finder

```python
# example1.py in https://github.com/c-bata/grpc-issue-proto-finder
from foo import a_pb2_grpc

print("success")
```

Although this program won't raise ModuleNotFoundError on grpcio==1.33.2, this will raise ModuleNotFoundError on grpcio==1.38.1.

```
$ pip freeze | grep grpcio
grpcio==1.33.2
grpcio-tools==1.33.2
$ python example1.py 
success

$ pip install -U grpcio grpcio-tools
$ pip freeze | grep grpcio
grpcio==1.38.1
grpcio-tools==1.38.1
$ python example1.py 
Traceback (most recent call last):
  File "/Users/a14737/sandbox/protoc-bug-report-proto-finder/example1.py", line 5, in <module>
    from foo import a_pb2_grpc
  File "/Users/a14737/sandbox/protoc-bug-report-proto-finder/foo/a_pb2_grpc.py", line 5, in <module>
    import a_pb2 as a__pb2
ModuleNotFoundError: No module named 'a_pb2'
```

This exception is raised in a [protoc-generated Python module](https://github.com/c-bata/grpc-issue-proto-finder/blob/697abbe89ed72121129ed979ad4d15cd95d83eed/foo/a_pb2_grpc.py#L1-L5):

```python
# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import a_pb2 as a__pb2   # ModuleNotFoundError is raised here!!!
```

A related issue and a pull request are the followings:

* https://github.com/protocolbuffers/protobuf/issues/1491#issuecomment-772720912
* https://github.com/protocolbuffers/protobuf/pull/7470

### What did you expect to see?

In `grpcio==1.33.2`, it won't raise an exception because `grpc_tools.protoc.ProtoFinder` is set on `sys.meta_path` while importing `grpc` package.
https://github.com/grpc/grpc/blob/ede7923116f60078d7bab1b9f9cc3e399fbece81/tools/distrib/python/grpcio_tools/grpc_tools/protoc.py#L52-L64

But ProtoFinder is not set at `grpcio==1.38.1` due to the change of https://github.com/grpc/grpc/pull/24993.  If I explicitly imports `grpc_tools.protoc` before importing `a_pb2_grpc`, ModuleNotFoundError won't be raised.

```python
# example2.py in https://github.com/c-bata/grpc-issue-proto-finder
import grpc_tools.protoc

from foo import a_pb2_grpc

print("success")
```

This works fine with grpcio==1.38.1 because this program explicitly imports "grpc_tools.protoc" so that "grpc_tools.protoc.ProtoFinder" is set in sys.meta_path.

```
(venv) $ pip freeze | grep grpcio
grpcio==1.38.1
grpcio-tools==1.38.1

(venv) $ python example2.py 
success
```

I think this is a regression bug that is introduced by https://github.com/grpc/grpc/pull/24993,
and we need to import `grpc_tools.protoc` from the `grpc` package as in the previous version.

### What did you see instead?

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

See [TROUBLESHOOTING.md](https://github.com/grpc/grpc/blob/master/TROUBLESHOOTING.md) for how to diagnose problems better.

**Comment by c-bata** [comment] 2021-07-08 05:55
This bug is resolved by https://github.com/grpc/grpc/compare/master...c-bata:python-proto-finder?expand=1, but I'm not sure if it is the correct approach.

**Comment by c-bata** [comment] 2021-07-08 06:15
@gnossen @lidizheng This problem is seemingly caused by https://github.com/grpc/grpc/pull/24993. Could you check this?

**Comment by gnossen** [comment] 2021-07-09 17:55
Thanks for the comprehensive reproduction and in-depth research!

I think there's a faulty assumption here. The `ProtoFinder` class you mentioned is only used for _runtime_ code generation. Based on the fact that you have a [`codegen.py`](https://github.com/c-bata/grpc-issue-proto-finder/blob/e3e95feaf16dab8f9e332545f1e0f2e6d808733f/codegen.py) file invoking `protoc`, I'm assuming that's not what you're attempting to do. Instead, it seems you're using code generated ahead of time.

It's an interesting trick you've found that importing `grpc_tools.protoc` helps with getting imports to work correctly, but it's not the proper solution. The reason this is working for you is that `a.proto` is present in the same directory as `example2.py` and you have `grpcio-tools` installed. You also could delete your generated code (the `foo/` directory), and the following code would work:

```
import grpc

a_pb2, a_pb2_grpc = grpc.protos_and_services("a.proto")

msg = a_pb2.FooMessage()

print("success")
```

See [this example](https://github.com/grpc/grpc/blob/b97693d57231a4266742d9e33d1c7c576f96b65e/examples/python/no_codegen/greeter_client.py) for more details.

In `1.33.2`, you were unintentionally using this feature, even in `example1.py`. You can see this by deleting `a.proto` or uninstalling `grpcio-tools`. You'll fail to import `a_pb2_grpc`.

The solution to this difficulty in the way `_pb2.py` files do imports ultimately _is_ something like https://github.com/protocolbuffers/protobuf/pull/7470, but that PR has not been merged yet. In the meantime, you can modify `sys.path` to make the imports work without modifying your generated code.

```
import sys
sys.path.append("foo")

from foo import a_pb2_grpc

print("success")
```

Closing as "works as intended", but feel free to reopen if you need any more info.

**Closed by gnossen** 2021-07-09 17:55 UTC
Labels: kind/bug, lang/Python, priority/P2
