### ISSUE TITLE
where's the runtimes folder in Grpc.Core

### ISSUE THREAD

**Issue by springlight** [grpc/grpc#17080] opened 2018-11-02 03:51 UTC
in the Grpc.Core  ,the NativeExtension.cs，there's a sentence below
` string runtimesDirectory = string.Format("runtimes/{0}/native", GetPlatformString());`.

But I downloaded the grpc.zip，in my Grpc.Core copy,there's no this runtimes folder now ,could anybody tell me where can i find it please?

**Comment by BlackFrog1** [comment] 2018-11-06 22:45
Reading the full comment before that line of code:            

            // With dotnet cli project targeting netcoreapp1.0, projects will use Grpc.Core assembly directly in the location where it got restored
            // by nuget. We locate the native libraries based on known structure of Grpc.Core nuget package.
            // When "dotnet publish" is used, the runtimes directory is copied next to the published assemblies.
            string runtimesDirectory = string.Format("runtimes/{0}/native", GetPlatformString());
            var netCorePublishedAppStylePath = Path.Combine(assemblyDirectory, runtimesDirectory, GetNativeLibraryFilename());
            var netCoreAppStylePath = Path.Combine(assemblyDirectory, "../..", runtimesDirectory, GetNativeLibraryFilename());


            // Look for the native library in all possible locations in given order.
            string[] paths = new[] { classicPath, netCorePublishedAppStylePath, netCoreAppStylePath};


It's taking about where the Nuget package are located:
![grpc core](https://user-images.githubusercontent.com/550820/48098798-b54bad80-e1eb-11e8-85d1-947d40f25dad.png)

**Comment by jtattermusch** [comment] 2019-02-18 14:50
not sure what "grpc.zip" you are talking about, the official distribution channel for gRPC C# in nuget.org. The packages there definitely do contain the `runtimes` folder as always.

I'm going to close this as "cannot reproduce".

**Closed by jtattermusch** 2019-02-18 14:50 UTC
Labels: kind/question, lang/C#

**Comment by springlight** [comment] 2019-02-26 09:02
> not sure what "grpc.zip" you are talking about, the official distribution channel for gRPC C# in nuget.org. The packages there definitely do contain the `runtimes` folder as always.
> 
> I'm going to close this as "cannot reproduce".

ok ，Have already solved it,Thanks a lot
