### ISSUE TITLE
FLAKE: interop Kokoro cloud_to_prod:gateway_v4:csharp:large_unary

### ISSUE THREAD

**Issue by vjpai** [grpc/grpc#12030] opened 2017-08-02 06:45 UTC
https://sponge.corp.google.com/target?id=34193a77-65c7-4216-8236-fb0258844b8c&target=grpc/ubuntu/pull_request/grpc_interop_toprod&searchFor=&show=ALL&sortBy=STATUS

**Comment by jtattermusch** [comment] 2017-11-06 15:21
Dupe of #10763

**Closed by jtattermusch** 2017-11-06 15:21 UTC
Labels: infra/BUILDPONY
