### ISSUE TITLE
Tsan C failed because "No commit found for SHA"

### ISSUE THREAD

**Issue by adelez** [grpc/grpc#9680] opened 2017-02-11 05:46 UTC
START: Running test matrix.
START: run_tests_c_linux_tsan
PASSED: run_tests_c_linux_tsan [time=7582.9sec; retries=0:0]
SUCCESS: All run_tests.py instance finished successfully.
Recording test results
Setting commit status on GitHub for https://github.com/grpc/grpc/commit/30974be82f2b52cb25740dab5cbca75d00974b99
ERROR: [GitHub Commit Status Setter] - {"message":"No commit found for SHA: 30974be82f2b52cb25740dab5cbca75d00974b99","documentation_url":"https://developer.github.com/v3/repos/statuses/"}, setting build result to FAILURE

https://grpc-testing.appspot.com/job/gRPC_pull_requests_tsan_c/1943/console

**Comment by jtattermusch** [comment] 2017-02-18 04:19
Has this happened repeatedly? It looks like that the PR branch was force-pushed (rebase?) while the test was running, so once the test has finished, the commit SHA didn't exist because the original commit didn't exist anymore.

Closing as this seems like an expected behavior.

**Closed by jtattermusch** 2017-02-18 04:19 UTC
Labels: c, test

**Comment by adelez** [comment] 2017-02-23 22:47
Thanks for explaining, Jan!
