### ISSUE TITLE
C++ examples produce segmentation fault on Mac OS X 10.12.4

### ISSUE THREAD

**Issue by hadils** [grpc/grpc#11233] opened 2017-05-19 00:55 UTC
I get a segmentation fault on helloworld greeter_server and greeter_client right away. I built the grpc distribution according to the instructions from scratch.

I get one error during the build:

ld: warning: directory not found for option '-L/Users/hadilsabbagh/grpc/libs/opt/c-ares'
 
### What version of gRPC and what language are you using?
 Using C++
gRPC v.1.3.2
 
### What operating system (Linux, Windows, …) and version?
 
Mac OS X 10.12.4
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
 
 Hadil-Sabbaghs-MacBook-Pro:helloworld hadilsabbagh$ gcc --version
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 8.0.0 (clang-800.0.42.1)
Target: x86_64-apple-darwin16.5.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

### What did you do?
If possible, provide a recipe for reproducing the error. Try being specific and include code snippets if helpful.

cd examples/cpp/helloworld
LIBTOOL=glibtool LIBTOOLIZE=glibtoolize make
./greeter_server 
### What did you expect to see?
 I expected it to execute
 
### What did you see instead?
 
I0518 17:41:15.596738000 140736416801728 server_builder.cc:247]        Synchronous server. Num CQs: 1, Min pollers: 1, Max Pollers: 2147483647, CQ timeout (msec): 1000
Segmentation fault: 11

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

**Comment by ncteisen** [comment] 2017-05-19 01:06
Duplicate of #10909

**Closed by ncteisen** 2017-05-19 01:06 UTC
