### ISSUE TITLE
System.InvalidOperationException: Shutdown has already been called

### ISSUE THREAD

**Issue by AtosNicoS** [grpc/grpc#22750] opened 2020-04-23 08:54 UTC
### What version of gRPC and what language are you using?

Tested:
* 2.28.1 c# 7.3, Protobuf 3.11.4
* 1.20.0 c# 7.3, Protobuf 3.7.0

### What operating system (Linux, Windows,...) and version?
Windows

### What runtime / compiler are you using (e.g. python version or version of gcc)
Visual Studio 2019

### What did you do?
I will update the following information, whenever I have new information or better test cases.

* Open 4 channels. 2 channels connect to the same port. (A simpler setup might be possible)
* Start a server side streaming call, passing a cancellationtoken
* Receive an answer from the server side by accessing `call.ResponseStream.Current`.
* Add a delay inside the answer processing, to avoid calling `MoveNext()` to fast
* On a parallel Task cancel the Token first, then call `channel1.ShutdownAsync().ConfigureAwait(false)` on *all channels*
* The Delay task should now end and `MoveNext()` should be called again
* `System.InvalidOperationException: Shutdown has already been called` Is thrown.

### What did you expect to see?
An RPC Exception with StatusCode IsCancelled.

### What did you see instead?
The Invalidoperationexception should not happen. It is important to note here, that this issue can only be reproduced, if *all channels* are shutdown. I am using multiple channels, with multiple ports. Some clients connect to the same port, some to a different.

It seems that the `MoveNext()` method does not check the cancellationtoken first, but rather throws an error, if *all channels* are shut down. If still one channel is alive the error does not occur! Thatswhy I assume that this is a possible grpc but and not my wrong usage.

### Anything else we should know about your project / environment?

I currently have no simple reproducible testcase, nor am I using the latest version. I want to use this bugreport to collect information, maybe someone else also stumbles across this issue. The following code snippets demonstrates how to reproduce the bug:

```csharp
      protected async Task Test()
        {
            var channel1 = new Channel(_host, _port, ChannelCredentials.Insecure);
            var channel2 = new Channel(_host, _port, ChannelCredentials.Insecure);
            var userPresenceClient = new UserPresenceService.UserPresenceServiceClient(channel1);
            var otherClient = new ContactListService.ContactListServiceClient(channel2);
            
            var cts = new CancellationTokenSource();
            var token = cts.Token;

            var grpcCallTask = Task.Run(async () =>
            {
                try
                {
                    using (var call = userPresenceClient.SubscribeUserPresences(new SubscribeUserPresencesRequest(),
                        cancellationToken: token))
                    {
                        while (await call.ResponseStream.MoveNext(token))
                        {
                            var response = call.ResponseStream.Current;
                            await Task.Delay(8000);
                        }
                    }
                }
                catch (Exception e)
                {
                    // Add a breakpoint here to verify the thrown exception
                    throw;
                }
            });

            await Task.Delay(1000);
            cts.Cancel();
            cts.Dispose();

            channel1.ShutdownAsync().ConfigureAwait(false);
            channel2.ShutdownAsync().ConfigureAwait(false);
            try
            {
                await grpcCallTask;
            }
            catch (Exception e)
            {
                // Add a breakpoint here to verify the thrown exception
                throw;
            }
        }
```

A workaround for this issue:
```csharp
catch when (token.IsCancellationRequested)
{
    throw new OperationCanceledException();
}
```

**Comment by a11r** [comment] 2020-05-12 23:25
We are discouraging questions posted as issues here. Please feel free to post to stackoverflow.

**Comment by AtosNicoS** [comment] 2020-08-24 10:41
Well, this is no question, it is a bug report. At least I think so, if I am wrong, please explain me why.

**Comment by jtattermusch** [comment] 2022-04-29 09:21
I think we can classify this as "works as intended".
- Looks like you have an active call and you explicitly shutdown all the channels in your application (including the channel on which you started the call) and then expect the in-flight call to continue to work normally (Btw doing so actually prints a warning).
The correct usage pattern is to only shutdown the channel once all the calls on that channel have finished.
- Based on the documentation, the channel.ShutdownAsync() doesn't have to explicitly cancel all that call on a given chanel (since doing that would require extra tracking and have performance costs). If for whatever reason you want to get your calls automatically cancelled upon channel shutdown is requested, you can use channel.ShutdownToken and register it explicitly with the calls you start (`var call = client.InvokeFooBar(cancellationToken: channel.ShutdownToken)`). See relevant docs here: 
https://github.com/grpc/grpc/blob/730599bd5b68f12436907cd96ab3fb20579734e7/src/csharp/Grpc.Core.Api/ChannelBase.cs#L60

I think what's happening under the hood is that shutting down all the channels in your app removes the all the references to the "grpc environment" (what makes the entire grpc work) held internally and shuts it down. You then get the "Shutdown has already been called" error from one of the internal components of grpc (I think here: https://github.com/grpc/grpc/blob/730599bd5b68f12436907cd96ab3fb20579734e7/src/csharp/Grpc.Core/Internal/CompletionQueueSafeHandle.cs#L110)

As a side note, Grpc.Core is now in maintenance mode and we're only going to be doing critical fixes going forward and since you issue doesn't seem like an actual bug, but more as an inconvenience that can be easily avoided by correct usage, I'm going to close this.

**Closed by jtattermusch** 2022-04-29 09:21 UTC
Labels: kind/bug, lang/C#, priority/P2
