### ISSUE TITLE
Python grpc does not terminate in the event of an error despite Keyboard Interrupt

### ISSUE THREAD

**Issue by thunderboltsid** [grpc/grpc#4705] opened 2016-01-13 06:28 UTC
The python shell freezes instead of respecting SIGINT
![screen shot 2016-01-13 at 7 26 27 am](https://cloud.githubusercontent.com/assets/6081171/12286735/3281cbc2-b9c7-11e5-9157-f9d993274fd2.png)

**Comment by soltanmm** [comment] 2016-01-13 20:08
Duplicate of #4148.

**Closed by soltanmm** 2016-01-13 20:08 UTC
