### ISSUE TITLE
C++ helloworld example does not work properly

### ISSUE THREAD

**Issue by chenicel** [grpc/grpc#21273] opened 2019-11-22 11:59 UTC
### What version of gRPC and what language are you using?
1.25.0   c++

### What operating system (Linux, Windows,...) and version?
ubuntu18.04

### What runtime / compiler are you using (e.g. python version or version of gcc)
gcc7.4.0

### What did you do?
If possible, provide a recipe for reproducing the error. Try being specific and include code snippets if helpful.
Compiled/installed gRPC according to the installation instructions.
Compiled examples/cpp/helloworld example.
Tried running ./greeter_server
### What did you expect to see?
Received return information from the server

### What did you see instead?
```
D1122 19:58:44.703447994    7907 ev_posix.cc:174]            Using polling engine: epollex
D1122 19:58:44.703681146    7907 dns_resolver_ares.cc:503]   Using ares dns resolver
```
The client runs without any output

**Comment by yjkhtddx** [comment] 2019-11-29 10:45
I have the same problem
Server: BuildAndStart hangs
Client: CreateChannel hangs

Wireshark cannot grab any network packets to the destination IP

**Comment by yjkhtddx** [comment] 2019-12-05 02:16
https://github.com/grpc/grpc/issues/21280#issuecomment-558164977

It solves my problem in this way, but I'm not sure if this modification will generate other bugs.

**Comment by kingsenye** [comment] 2020-01-08 09:50
I have the same problem too~   what  shuod i do...

**Comment by l7l1l0l** [comment] 2020-01-13 10:36
I have the same problem too

**Comment by veblush** [comment] 2020-01-29 20:49
Duplicate of #21280

**Closed by veblush** 2020-01-29 20:49 UTC
Labels: kind/bug, priority/P2
