### ISSUE TITLE
The CMake build process is failed if BUILD_SHARED_LIBS is set to ON (on Mac)

### ISSUE THREAD

**Issue by hungptit** [grpc/grpc#25002] opened 2020-12-15 17:22 UTC
### What version of gRPC and what language are you using?

C++ build version v1.34.0

### What operating system (Linux, Windows,...) and version?

macos 19.6.0 Darwin Kernel Version 19.6.0: Thu Oct 29 22:56:45 PDT 2020; root:xnu-6153.141.2.2~1/RELEASE_X86_64 x86_64

### What runtime / compiler are you using (e.g. python version or version of gcc)

Configured with: --prefix=/Library/Developer/CommandLineTools/usr --with-gxx-include-dir=/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/c++/4.2.1
Apple clang version 12.0.0 (clang-1200.0.26.2)
Target: x86_64-apple-darwin19.6.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin

### What did you do?

```
cmake ../grpc/ -DBUILD_SHARED_LIBS=ON -DABSL_ENABLE_INSTALL=OFF
make -j9
```

### What did you expect to see?

The build process is succeeded.

### What did you see instead?

The build process is failed with many errors. Below is the sample output

```
[ 31%] Building CXX object third_party/re2/CMakeFiles/mimics_pcre_test.dir/re2/testing/mimics_pcre_test.cc.o
      bssl::internal::DeleterImpl<crypto_buffer_st, void>::Free(crypto_buffer_st*) in handshake.cc.o
      bssl::internal::DeleterImpl<crypto_buffer_st, void>::Free(crypto_buffer_st*) in handshake_client.cc.o
      bssl::internal::DeleterImpl<crypto_buffer_st, void>::Free(crypto_buffer_st*) in handshake_server.cc.o
      bssl::internal::DeleterImpl<crypto_buffer_st, void>::Free(crypto_buffer_st*) in ssl_asn1.cc.o
      bssl::ssl_cert_dup(bssl::CERT*) in ssl_cert.cc.o
      bssl::ssl_set_cert(bssl::CERT*, std::__1::unique_ptr<crypto_buffer_st, bssl::internal::Deleter<crypto_buffer_st> >) in ssl_cert.cc.o
      bssl::internal::DeleterImpl<crypto_buffer_st, void>::Free(crypto_buffer_st*) in ssl_cert.cc.o
      ...
  "_CRYPTO_BUFFER_init_CBS", referenced from:
      bssl::do_send_client_key_exchange(bssl::SSL_HANDSHAKE*) in handshake_client.cc.o
      bssl::do_read_client_certificate_verify(bssl::SSL_HANDSHAKE*) in handshake_server.cc.o
      bssl::check_leaf_cert_and_privkey(crypto_buffer_st*, evp_pkey_st*) in ssl_cert.cc.o
      bssl::ssl_cert_check_private_key(bssl::CERT const*, evp_pkey_st const*) in ssl_cert.cc.o
      bssl::ssl_on_certificate_selected(bssl::SSL_HANDSHAKE*) in ssl_cert.cc.o
      bssl::DC::Parse(crypto_buffer_st*, unsigned char*) in ssl_cert.cc.o
  "_CRYPTO_BUFFER_len", referenced from:
      bssl::ssl_verify_peer_cert(bssl::SSL_HANDSHAKE*) in handshake.cc.o
      bssl::do_send_server_certificate(bssl::SSL_HANDSHAKE*) in handshake_server.cc.o
      bssl::SSL_SESSION_to_bytes_full(ssl_session_st const*, cbb_st*, int) in ssl_asn1.cc.o
      bssl::ssl_add_cert_chain(bssl::SSL_HANDSHAKE*, cbb_st*) in ssl_cert.cc.o
      bssl::ssl_add_client_CA_list(bssl::SSL_HANDSHAKE*, cbb_st*) in ssl_cert.cc.o
      _SSL_get0_signed_cert_timestamp_list in ssl_lib.cc.o
      _SSL_get0_ocsp_response in ssl_lib.cc.o
      ...
  "_CRYPTO_BUFFER_new", referenced from:
      _SSL_CTX_use_certificate_ASN1 in ssl_cert.cc.o
      _SSL_use_certificate_ASN1 in ssl_cert.cc.o
      set_signed_cert_timestamp_list(bssl::CERT*, unsigned char const*, unsigned long) in ssl_cert.cc.o
      _SSL_CTX_set_ocsp_response in ssl_cert.cc.o
      _SSL_set_ocsp_response in ssl_cert.cc.o
      set_client_CA_list(std::__1::unique_ptr<stack_st_CRYPTO_BUFFER, bssl::internal::Deleter<stack_st_CRYPTO_BUFFER> >*, stack_st_X509_NAME const*, crypto_buffer_pool_st*) in ssl_x509.cc.o
      add_client_CA(std::__1::unique_ptr<stack_st_CRYPTO_BUFFER, bssl::internal::Deleter<stack_st_CRYPTO_BUFFER> >*, x509_st*, crypto_buffer_pool_st*) in ssl_x509.cc.o
      ...
     (maybe you meant: _sk_CRYPTO_BUFFER_new_null)
  "_CRYPTO_BUFFER_new_from_CBS", referenced from:
      bssl::do_read_certificate_status(bssl::SSL_HANDSHAKE*) in handshake_client.cc.o
      bssl::SSL_SESSION_parse(cbs_st*, bssl::SSL_X509_METHOD const*, crypto_buffer_pool_st*) in ssl_asn1.cc.o
      bssl::SSL_SESSION_parse_crypto_buffer(cbs_st*, std::__1::unique_ptr<crypto_buffer_st, bssl::internal::Deleter<crypto_buffer_st> >*, unsigned int, crypto_buffer_pool_st*) in ssl_asn1.cc.o
      bssl::ssl_parse_cert_chain(unsigned char*, std::__1::unique_ptr<stack_st_CRYPTO_BUFFER, bssl::internal::Deleter<stack_st_CRYPTO_BUFFER> >*, std::__1::unique_ptr<evp_pkey_st, bssl::internal::Deleter<evp_pkey_st> >*, unsigned char*, cbs_st*, crypto_buffer_pool_st*) in ssl_cert.cc.o
      bssl::ssl_parse_client_CA_list(ssl_st*, unsigned char*, cbs_st*) in ssl_cert.cc.o
      bssl::ext_sct_parse_serverhello(bssl::SSL_HANDSHAKE*, unsigned char*, cbs_st*) in t1_lib.cc.o
      bssl::tls13_process_certificate(bssl::SSL_HANDSHAKE*, bssl::SSLMessage const&, bool) in tls13_both.cc.o
      ...

```

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

See [TROUBLESHOOTING.md](https://github.com/grpc/grpc/blob/master/TROUBLESHOOTING.md) for how to diagnose problems better.

### Anything else we should know about your project / environment?

None

**Comment by jtattermusch** [comment] 2021-01-11 16:17
I'm able to reproduce this (on Mac) by running:
```
cd cmake/build
cmake -DBUILD_SHARED_LIBS:BOOL=ON ../..
make grpc -j2
```

Looks like the issue is that building of boringssl (`libcrypto.dylib` specifically) with BUILD_SHARED_LIBS=ON is broken (rather than the build of grpc itself).

**Comment by yashykt** [comment] 2024-04-09 19:53
sounds like something that should be raised with boringssl then. Closing it here.

**Closed by yashykt** 2024-04-09 19:53 UTC
Labels: kind/bug, priority/P2, untriaged
