### ISSUE TITLE
grpc_interop_tocloud and grpc_interop_toprod failed due to dart version mismatch

### ISSUE THREAD

**Issue by markdroth** [grpc/grpc#16577] opened 2018-09-07 18:34 UTC
https://source.cloud.google.com/results/invocations/4bd2b567-914c-463b-aad5-31ecfa485a39/targets/grpc%2Fcore%2Fpull_request%2Flinux%2Fgrpc_interop_tocloud/log

```
Resolving dependencies...
The current Dart SDK version is 2.0.0-dev.67.0.

Because interop requires SDK version >=2.0.0 <3.0.0, version solving failed.
+ EXITCODE=1
+ docker rm -f build_grpc_interop_dart_c62b2a43-9616-47fe-bfec-96d343c797d3
build_grpc_interop_dart_c62b2a43-9616-47fe-bfec-96d343c797d3
+ exit 1
```

**Comment by jtattermusch** [comment] 2018-09-08 01:27
Dupe of https://github.com/grpc/grpc/issues/16580 (already fixed).

**Closed by jtattermusch** 2018-09-08 01:27 UTC
Labels: infra/BUILDPONY, kind/internal cleanup, lang/other
