### ISSUE TITLE
Can I use a parameter bigger than 20MB in one call

### ISSUE THREAD

**Issue by psnbbgy** [grpc/grpc#7882] opened 2016-08-26 06:02 UTC
I use a grpc call like 

Status status = stub_->GetFeature(&context, point, feature);

And I want to use large point and feature instances bigger than 20MB.
I set the maxmessagesize with

ServerBuilder builder;
builder.SetMaxMessageSize(4000000000);

But it does not work, its error message is like this:

GetFeature rpc failed. error code: 13 error message: {"created":"@1472189931.403060508","description":"RST_STREAM","file":"src/core/ext/transport/chttp2/transport/frame_rst_stream.c","file_line":107,"http2_error":2}

Are there any setting to set for this? or it can not use such large parameter?

**Comment by psnbbgy** [comment] 2016-08-26 10:09
well, I find the answer, but I must change the code. have some method no need to rewrite source code?

**Comment by ejona86** [comment] 2016-08-26 19:37
Max message size is enforced for receiving, not sending. So changing the max message size on the server should resolve the issue.

gRPC is very fine with larger message sizes, but we want applications to be aware they may receive large messages.

> well, I find the answer, but I must change the code. have some method no need to rewrite source code?

No. The default is now 4MB, and if you want larger you need to override it. What code change made it work?

**Comment by psnbbgy** [comment] 2016-08-27 07:35
/grpc-master/src/core/lib/surface/channel.c DEFAULT_MAX_MESSAGE_LENGTH
this one parameter must be changed, or I can not transfer large parameter.

**Comment by ejona86** [comment] 2016-08-29 15:48
@yang-g, is there some bug with `ServerBuilder.SetMaxMessageSize()`?

**Comment by yang-g** [comment] 2016-08-29 16:39
@markdroth does your pr https://github.com/grpc/grpc/pull/7846 resolve this? Thanks.

**Comment by markdroth** [comment] 2016-08-29 16:52
I doubt that my PR resolves this.  The PR doesn't really change this check; it just moves it from one place in the code to another.

Looking at the code, though, I don't see why `DEFAULT_MAX_MESSAGE_LENGTH` needs to be changed.  Setting the value via `ServerBuilder::SetMaxMessageSize()` should work fine.

Let me see if I can put together a quick test to reproduce this.

**Comment by markdroth** [comment] 2016-08-29 17:14
@psnbbgy, I can't reproduce this problem.

I have a client that sends a 10MiB request to the server.  When I run the server without overriding max message size, the client fails with the error you're seeing.  However, when I call `ServerBuilder::SetMaxMessageSize()` to set the limit to 20MiB, the call succeeds.

Are you certain that you're setting the max message size on the server that your client is sending the request to?

**Comment by psnbbgy** [comment] 2016-08-30 06:15
@markdroth , I think my setting is wrong, I have set the max message size to 4000000000, it is out of the int range, and when I set it to 2000000000, it success.
and thank you for replying.
BTW can the grpc support the PB larger than 2GB?

**Comment by markdroth** [comment] 2016-08-30 14:16
It looks like our current API can't do that, because we encode the max message size as an int, so the maximum supported value is 2147483647.  Do you actually need to use a max size larger than that?  If so, we might need to make some API changes.

@ctiller, what do you think about changing channel args to use long instead of int?

**Comment by ctiller** [comment] 2016-08-30 15:08
We could, and we'd get to 4GiB and need a major revision number change on
our C API. At which point I'd fall back to: if your current problem doesn't
fit in 2GiB, your future problem isn't solved with 4GiB, and you probably
want to change some usage of the APIs.

I'd strongly encourage a design rethink here: aim for much smaller messages
(kilobytes to megabytes) and leverage streaming.

gRPC currently needs to hold the entire serialized message in memory before
deserialization, and so with multi gigabyte messages you're holding huge
amounts of memory hostage, especially compared to a stream.

**Comment by psnbbgy** [comment] 2016-08-31 07:12
@markdroth our Algorithm engineer has a idea about this. Maybe stream is a good idea, because when the PB size is above 1.5GB , the server always kill my process, and change the API may not help this.

**Comment by markdroth** [comment] 2016-08-31 14:21
Okay, then I'm going to close this issue.  Please let us know if you need anything else.

**Closed by markdroth** 2016-08-31 14:21 UTC
