### ISSUE TITLE
Build fails when deploying to App Engine under Node.JS v5.9.1

### ISSUE THREAD

**Issue by paulshapiro** [grpc/grpc#6156] opened 2016-04-13 00:04 UTC
Been trying to figure this out for the past couple hours and got recommended to open an issue here by some of the maintainers of gcloud.

I've added gcloud as a dependency of my Node.JS app and tried to deploy to App Engine but can't get the deploy to succeed. Times out waiting for the VMs to come up saying the code is unhealthy.

Digging through the logs, this is what I found:

```
module.js:440
return process.dlopen(module, path._makeLong(filename));
^
Error: Module version mismatch. Expected 47, got 46.
at Error (native)
at Object.Module._extensions..node (module.js:440:18)
at Module.load (module.js:357:32)
at Function.Module._load (module.js:314:12)
at Module.require (module.js:367:17)
at require (internal/module.js:16:19)
at Object.<anonymous> (/app/node_modules/gcloud/node_modules/grpc/src/node/src/grpc_extension.js:38:15)
at Module._compile (module.js:413:34)
at Object.Module._extensions..js (module.js:422:10)
at Module.load (module.js:357:32)
at Function.Module._load (module.js:314:12)
at Module.require (module.js:367:17)
at require (internal/module.js:16:19)
at Object.<anonymous> (/app/node_modules/gcloud/node_modules/grpc/src/node/src/client.js:54:12)
at Module._compile (module.js:413:34)
at Object.Module._extensions..js (module.js:422:10)
```

Was told it looks like grpc is failing to build under the relevant node version.

Here's that discussion thread/issue, which has a tad more info about the situation.

[https://github.com/GoogleCloudPlatform/gcloud-node/issues/1225](https://github.com/GoogleCloudPlatform/gcloud-node/issues/1225)

Help would be much appreciated!

**Comment by jmdobry** [comment] 2016-04-26 21:27
Duplicate of #6218?

**Comment by hsaliak** [comment] 2017-01-25 21:47
@paulshapiro is this still an issue you are running into?

**Comment by kpayson64** [comment] 2017-05-16 20:25
GoogleCloudPlatform/gcloud-node#1225 indicates that this issue has been resolved.

**Closed by kpayson64** 2017-05-16 20:25 UTC
Labels: node, requires reporter clarification
