### ISSUE TITLE
gRPC-1.45.1 does not compile with protobuf-3.20.0

### ISSUE THREAD

**Issue by coryan** [grpc/grpc#29297] opened 2022-04-02 14:27 UTC
### What version of gRPC and what language are you using?

C++, gRPC-1.45.1

### What operating system (Linux, Windows,...) and version?

The problem manifests in Linux, Windows, and macOS.

### What runtime / compiler are you using (e.g. python version or version of gcc)

This is not compiler or runtime specific.

### What did you do?

Try to compile gRPC-1.45.1 with Protobuf-3.20.0.  Using this [small program](https://github.com/grpc/grpc/files/8402716/protobuf-vs-grpc.tar.gz)

### What did you expect to see?

A successful build.

### What did you see instead?

Bazel errors:

```
ERROR: /usr/local/google/home/coryan/.cache/bazel/_bazel_coryan/1597fbe7e0d6911d6fc0820b75877b84/external/com_envoyproxy_protoc_gen_validate/validate/BUILD:28:17: Label '@com_google_protobuf//:protobuf_python' is duplicated in the 'deps' attribute of rule 'validate_py'
ERROR: /usr/local/google/home/coryan/.cache/bazel/_bazel_coryan/1597fbe7e0d6911d6fc0820b75877b84/external/envoy_api/envoy/config/core/v3/BUILD:7:18: Target '@com_envoyproxy_protoc_gen_validate//validate:validate_proto' contains an error and its package is in error and referenced by '@envoy_api//envoy/config/core/v3:pkg'
ERROR: Analysis of target '//:test' failed; build aborted: 
INFO: Elapsed time: 1.426s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (35 packages loaded, 9 targets configured)
```

**Comment by gnossen** [comment] 2022-04-04 17:45
This looks like an issue between Protobuf and the Envoy project. Envoy is using the protobuf repo's (private, internal) `py_proto_library` rule [here](https://github.com/envoyproxy/protoc-gen-validate/blob/dfcdc5ea103dda467963fb7079e4df28debcfd28/validate/BUILD#L28). It looks like this might have been caused by [this PR](https://github.com/protocolbuffers/protobuf/pull/9187) on protobuf.

In fact, it looks like [they are aware of the problem](https://github.com/protocolbuffers/protobuf/issues/9688) and [have already rolled the PR back](https://github.com/protocolbuffers/protobuf/pull/9187#issuecomment-1082333538). Going ahead and closing as this isn't really a gRPC issue.

**Closed by gnossen** 2022-04-04 17:45 UTC
Labels: kind/bug, lang/c++, priority/P2, area/build, infra/Bazel
