### ISSUE TITLE
py36_asyncio.test_aio.unit.call_test.TestUnaryStreamCall Nondeterministic Segfault on Windows

### ISSUE THREAD

**Issue by gnossen** [grpc/grpc#21520] opened 2019-12-19 01:20 UTC
```
T:\src\github\grpc\workspace_python_windows_opt_asyncio\tools\run_tests\helper_scripts\run_python.sh: line 25:  4764 Segmentation fault      $PYTHON "$ROOT/src/python/grpcio_tests/setup.py" "$2"

2019-12-18 15:29:08,030 FAILED: py36_asyncio.test_aio.unit.call_test.TestUnaryStreamCall [ret=139, pid=5880, time=15.0sec]
2019-12-18 15:29:08,250 PASSED: py36_asyncio.test_aio.unit.server_test.TestServer [time=15.2sec, retries=0:0]
2019-12-18 15:29:08,250 FAILED: py36_asyncio.test_aio.unit.call_test.TestUnaryStreamCall
2019-12-18 15:29:08,265 FAILED: Some tests failed

2019-12-18 15:29:08,358 FAILED: run_tests_python_windows_opt_asyncio [ret=2, pid=4700, time=642.6sec]
2019-12-18 15:29:08,375 FAILED: Some run_tests.py instances have failed.
```

https://source.cloud.google.com/results/invocations/9e357711-244d-43d6-9970-b54dcbf657d3/log

This apparently has ~20% flake rate at the moment.

**Comment by lidizheng** [comment] 2019-12-20 00:44
Spawned a win2016 VM, able to run tests, but unable to reproduce the segfault.

**Comment by lidizheng** [comment] 2020-01-15 18:52
After https://github.com/grpc/grpc/pull/21506, we haven't observed this flake are a while. Closing.

**Closed by lidizheng** 2020-01-15 18:52 UTC
Labels: kind/bug, lang/Python, priority/P2
