### ISSUE TITLE
C# .Net Core memory leak when using ForEachAsync streaming 

### ISSUE THREAD

**Issue by MedAnd** [grpc/grpc#9880] opened 2017-02-27 13:42 UTC
Testing simple client/server code using .Net Core but noticed massive memory leaks. Checking sample gRPC code could not see anything obvious.

global.json:

```
{
  "projects": [],
  "sdk": {
    "version": "1.0.0-preview2-003131"
  }
}
```

proto def:

```
message Ping {}
message Pong {}
rpc Stream (stream Ping) returns (stream Pong) {};
```

server code:

```
public override async Task Stream(IAsyncStreamReader<Ping> requestStream, IServerStreamWriter<Pong> responseStream, ServerCallContext context)
{
            await requestStream.ForEachAsync(ping =>
            {
                responseStream.WriteAsync(_pong);
                return Task.CompletedTask;
            });
}
```

client code:

```
for (var i = 0; i < 1000000; i++)
{
            await client.Stream().RequestStream.WriteAsync(ping);
}
```

**Comment by apolcyn** [comment] 2017-02-27 16:22
Haven't reproduced yet but is also the case with the latest 1.1.0?

**Comment by MedAnd** [comment] 2017-02-28 10:58
@apolcyn the memory leak was in 1.1.0, for example client project.json looks something like:

```
{
  "version": "1.0.0-*",

  "dependencies": {
    "Grpc.Core": "1.1.0",
    "Grpc.Tools": "1.1.0",
    "Google.Protobuf": "3.2.0",
    "NETStandard.Library": "1.6.1"
  },

  "frameworks": {
    "net46": {
      "dependencies": {
      }
    }
  },

  "runtimes": {
    "win7-x64": {}
  }
}
```

**Comment by jtattermusch** [comment] 2017-02-28 13:01
CC @jtattermusch.

**Comment by jtattermusch** [comment] 2017-02-28 16:14
@MedAnd , how did you diagnose that it is a leak?

**Comment by MedAnd** [comment] 2017-03-01 11:54
@jtattermusch I run the above client server sample sending a simple ping and pong message between processes and notice via task manager that memory for both client and server process starts at ~43mb and climbs to well of 3GB+ per process. Given the ping and pong messages have no data (see proto def)  I would assume simple test process should not be taking this much memory for streaming async operations?

Some more testing, when I change the client code to:

```
client.Stream().RequestStream.WriteOptions = new WriteOptions(WriteFlags.NoCompress);
for (var i = 0; i < messageCount; i++)
{
       using (var stream = client.Stream())
       {
              await stream.RequestStream.WriteAsync(ping);
       }
}
```

and server code to:

```
public override async Task Stream(IAsyncStreamReader<Ping> requestStream, IServerStreamWriter<Pong> responseStream, ServerCallContext context)
{
       responseStream.WriteOptions = new WriteOptions(WriteFlags.NoCompress);
       await requestStream.ForEachAsync(ping => responseStream.WriteAsync(_pong));
}
```

now both client and server processes never go above 80mb each... however CPU on a quad core i5-3570K is at 100% and the performance is horrible, i.e. the test is very slow to complete. I think this is due to the using (var stream = client.Stream()) which might be disposing and re-creating channels? 

Does the above indicate that the server (and thus server resources) are at the mercy of the client process, or rather a badly behaved client could cause excessive memory/CPU consumption on the server? Is my client code wrong, or is this a bug? 

Any insight greatly appreciated.

**Comment by jtattermusch** [comment] 2017-03-03 10:47
From looking at your code, the problem seems to be that you are actually creating a new streaming call in each cycle: 

```
for (var i = 0; i < 1000000; i++)
{
            await client.Stream().RequestStream.WriteAsync(ping);
}
```

instead you should be doing:

```
var call = client.Stream();  // creates the call that can stream messages
for (var i = 0; i < 1000000; i++)
{
            await call.RequestStream.WriteAsync(ping);  // send one message in each cycle
}
```

Btw, your "fix" also creates a new call in each cycle but prevents the memory leak because 

```
using (var stream = client.Stream())
{
}
```

Disposes the call once the using block ends (and because the call is still active by that time - you don't really close it yourself, the effect is actually cancelling the call)

**Closed by jtattermusch** 2017-03-03 10:47 UTC

**Comment by MedAnd** [comment] 2017-03-03 11:00
@jtattermusch with your change:

```
var call = client.Stream();  // creates the call that can stream messages
for (var i = 0; i < 1000000; i++)
{
            await call.RequestStream.WriteAsync(ping);  // send one message in each cycle
}
```

the server is now never called at all. Happy to provide the sample source code if that helps?

**Comment by jtattermusch** [comment] 2017-03-03 11:11
Sure, feel free to provide more examples, but I'm pretty sure that the code I'm suggesting would work.
Btw, there's more issues with your code:

On the server side you should have 
```
await requestStream.ForEachAsync(async ping =>
            {
                await responseStream.WriteAsync(_pong);  // only one write allowed at a time, so await the current write.
            });
```

Also, you are doing a ping pong but you are actually never reading the responses on the client side.
But I am pretty sure that the server side handler will get called.

**Comment by MedAnd** [comment] 2017-03-03 11:53
@jtattermusch attempted your suggested changes but still not working as expected so I've published the code for your consideration: https://github.com/MedAnd/gRPCSample

**Comment by jtattermusch** [comment] 2017-03-06 07:51
I'm pretty sure gRPC is behaving correctly.
It looks like the problem is that on the client side, you are only sending messages and you are never receiving them (which is bad in general, in the end you should always attempt to read from the responseStream to obtain the call status at least), but on the server-side you are trying to send a response for each received request. Because the client is not reading the responses at all, the flow control window will get filled very soon and the attempt to send a response will block unless you request reading messages on the client side (this is a mechanism to prevent overloading peers that aren't able to accept messages as quickly as you are sending them).
https://github.com/MedAnd/gRPCSample/blob/08cea43e9b435b418aa28f293b58c4b39b200581/Client/Program.cs#L37
https://github.com/MedAnd/gRPCSample/blob/08cea43e9b435b418aa28f293b58c4b39b200581/Server/gRPCServiceBase.cs#L21

If you want to benchmark one-way sending of messages, this would work:  start sending them from client the way you do, receive them on the server-side (but don't send anything back), calculate staticstics on the serverside and once the request stream is closed, send a summary message with all the statistics back to the client (or just print them).

**Comment by MedAnd** [comment] 2017-03-09 12:38
Appreciate the feedback @jtattermusch and will incorporate into my sample... 
Wondering if this is the team's offical perf dashboard: [GA gRPC Performance Multi-language](https://performance-dot-grpc-testing.appspot.com/explore?dashboard=5712453606309888)

**Comment by jtattermusch** [comment] 2017-03-09 13:47
Yes, it is an official perf dashboard, but for version v1.0.x (so >6months old). C# numbers have improved significantly since then.
Newer dashboards are linked from here:
http://www.grpc.io/docs/guides/benchmarking.html

specifically, you can take a look at 
[Multi-language performance dashboard @latest_release (lastest available stable release)](https://performance-dot-grpc-testing.appspot.com/explore?dashboard=5636470266134528)
