### ISSUE TITLE
SSL/TLS channel establish failure (C++)

### ISSUE THREAD

**Issue by mys007** [grpc/grpc#24918] opened 2020-12-05 22:09 UTC
### What version of gRPC and what language are you using?

C++: 1.33.1 (vcpkg) or 1.27.3 (conan)
Python: 1.34.0 or 1.27.2 (pip)

### What operating system (Linux, Windows,...) and version?

Windows 10

### What runtime / compiler are you using (e.g. python version or version of gcc)
 
Visual Studio 2017 (15.9.22)

### What did you do?

I want to setup encrypted communication with SSL (localhost). I started from synchronous C++ helloworld [examples](https://github.com/grpc/grpc/tree/master/examples/cpp/helloworld) and added secure channels as follows (relevant snippets, `std::string readfile(const std::string& filepath)` does what is suggests):

Client:
```c++
grpc::SslCredentialsOptions ssl_opts;
ssl_opts.pem_root_certs = readfile("server.crt");
auto credentials = grpc::SslCredentials(ssl_opts);
GreeterClient greeter(grpc::CreateChannel(target_str, credentials));
```

Server:
```c++
grpc::SslServerCredentialsOptions::PemKeyCertPair pkcp;
pkcp.private_key = readfile("server.key");
pkcp.cert_chain = readfile("server.crt");
grpc::SslServerCredentialsOptions ssl_opts;
ssl_opts.pem_root_certs = readfile("ca.crt");
ssl_opts.pem_key_cert_pairs.push_back(pkcp);
builder.AddListeningPort(server_address, grpc::SslServerCredentials(ssl_opts));
```

The keys were created exactly as in this [SO question](https://stackoverflow.com/questions/59199419/using-tensorflow-model-server-with-ssl-configuration).  As a proof that the setup and the keys are OK, I also created a Python equivalent of the above, starting from helloworld [examples](https://github.com/grpc/grpc/tree/master/examples/python/helloworld) and adding SSL as follows:

Client:
```python
with open("server.crt", "rb") as pem_root_certs:
   scc = grpc.ssl_channel_credentials(root_certificates=pem_root_certs.read())
with grpc.secure_channel('localhost:50051', scc) as channel:
```

Server:
```python
with open("server.crt", "rb") as cert_chain, open("server.key", "rb") as private_key, open("ca.crt", "rb") as pem_root_certs:
    server_credentials = grpc.ssl_server_credentials([(private_key.read(), cert_chain.read())], pem_root_certs.read())
server.add_secure_port('[::]:50051', server_credentials)
```

### What did you expect to see?

In both C++ and Python, the RPC call is successful with no errors logged.

### What did you see instead?

However, the channel is NOT encrypted with C++ pair of applications but is encrypted with Python pair! I used Wireshark and RawCap to find out. If I try to get Python to C++ talking, it fails with `Handshake failed with fatal error SSL_ERROR_SSL: error:100000f7:SSL routines:OPENSSL_internal:WRONG_VERSION_NUMBER` kind of [errors](https://github.com/grpc/grpc/issues/9538), which further hints on that the error is when one uses TLS client with plaintext server or vice versa.

Full logs (GRPC_TRACE=all , GRPC_VERBOSITY=debug) are attached: [client.log](https://github.com/grpc/grpc/files/5647934/client.log), [server.log](https://github.com/grpc/grpc/files/5647935/server.log)

**Comment by jiangtaoli2016** [comment] 2020-12-07 21:16
When you see `Handshake failed`, the channel is not established. The title of this issue is misleading.

I suspect the problem is that you did not generate key/cert correctly. Try to use the client and server test credentials here (https://github.com/grpc/grpc/tree/master/src/core/tsi/test_creds) and see if you still see problems.

**Comment by mys007** [comment] 2020-12-07 21:29
@jiangtaoli2016 I did see no |Handshake failed" message, there is also no message like that in the detailed logs I've attached. Moreover, the Python version works with the exact same keys/certs.

**Comment by jiangtaoli2016** [comment] 2020-12-07 21:47
Once you use SS credentials in gRPC, it won't fallback to insecure credentials. How did you know payload is not encrypted? From TCP dump?

How about for C++ client to C++ server, enable logs in both end and see what going on. You can enable logs via instructions below.
https://github.com/grpc/grpc/blob/master/TROUBLESHOOTING.md

**Comment by mys007** [comment] 2020-12-07 22:12
> Try to use the client and server test credentials here

I used `server0.key`, `server0.pem`, `ca.pem` and this made no difference.

> How did you know payload is not encrypted? From TCP dump?

Yes. I can see the endpoint and the Hello message in plaintext.

> How about for C++ client to C++ server, enable logs in both end and see what going on

These are exactly the logs which I've posted in the issue before.

**Comment by markdroth** [comment] 2020-12-08 18:54
That seems like a serious problem.  Upgrading priority.  I've asked Yash to take a look.

**Comment by jiangtaoli2016** [comment] 2020-12-08 18:59
cc @ZhenLian @yihuazhang to keep an eye on it.

**Comment by yashykt** [comment] 2020-12-08 22:01
I tried reproducing this by adding SSL credentials to the server and the client to the C++ hello world example.

On the server side, 
```
  constexpr char kServerCertPath[] = "src/core/tsi/test_creds/server1.pem";
  constexpr char kServerKeyPath[] = "src/core/tsi/test_creds/server1.key";  
  constexpr char kCaCertPath[] = "src/core/tsi/test_creds/ca.pem";  
  std::string identity_cert = ReadFile(kServerCertPath);
  std::string private_key = ReadFile(kServerKeyPath);  
  grpc::SslServerCredentialsOptions ssl_opts;
  ssl_opts.pem_key_cert_pairs.push_back({ReadFile(kServerKeyPath), ReadFile(kServerCertPath)});  
  ssl_opts.pem_root_certs =ReadFile(kCaCertPath);
  builder.AddListeningPort(server_address, grpc::SslServerCredentials(ssl_opts));
```

On the client side,
```
  constexpr char kCaCertPath[] = "src/core/tsi/test_creds/ca.pem";  
  grpc::SslCredentialsOptions ssl_opts;
  ssl_opts.pem_root_certs = ReadFile(kCaCertPath);
  grpc::ChannelArguments args;
  // Add this arg since the test certificates use a different name
  args.SetString(GRPC_SSL_TARGET_NAME_OVERRIDE_ARG, "foo.test.google.fr");
  GreeterClient greeter(grpc::CreateCustomChannel(
      target_str, grpc::SslCredentials(ssl_opts), args));
```

With this, SSL handshaking was performed properly and the data was sent in an encrypted manned.

```
[src/core/lib/security/transport/security_handshaker.cc:384]
I1208 13:56:05.207737018  115439 ssl_transport_security.cc:226]                 LOOP - TLS 1.3 client read_hello_retr  - !!!!!!
I1208 13:56:05.207772933  115439 ssl_transport_security.cc:226]                 LOOP - TLS 1.3 client read_server_hel  - !!!!!!
I1208 13:56:05.207944533  115439 ssl_transport_security.cc:226]                 LOOP - TLS 1.3 client read_encrypted_  - !!!!!!
I1208 13:56:05.207988221  115439 ssl_transport_security.cc:226]                 LOOP - TLS 1.3 client read_certificat  - !!!!!!
I1208 13:56:05.208001347  115439 ssl_transport_security.cc:226]                 LOOP - TLS 1.3 client read_server_cer  - !!!!!!
I1208 13:56:05.208112336  115439 ssl_transport_security.cc:226]                 LOOP - TLS 1.3 client read_server_cer  - !!!!!!
I1208 13:56:05.208360581  115439 ssl_transport_security.cc:226]                 LOOP - TLS 1.3 client read_server_fin  - !!!!!!
I1208 13:56:05.208421251  115439 ssl_transport_security.cc:226]                 LOOP - TLS 1.3 client send_end_of_ear  - !!!!!!
I1208 13:56:05.208432997  115439 ssl_transport_security.cc:226]                 LOOP - TLS 1.3 client send_client_enc  - !!!!!!
I1208 13:56:05.208441677  115439 ssl_transport_security.cc:226]                 LOOP - TLS 1.3 client send_client_cer  - !!!!!!
I1208 13:56:05.208452721  115439 ssl_transport_security.cc:226]                 LOOP - TLS 1.3 client complete_second  - !!!!!!
I1208 13:56:05.208516232  115439 ssl_transport_security.cc:226]                 LOOP -            TLS 1.3 client done  - !!!!!!
I1208 13:56:05.208532289  115439 ssl_transport_security.cc:226]                 LOOP - TLS client finish_client_hands  - !!!!!!
I1208 13:56:05.208561678  115439 ssl_transport_security.cc:226]                 LOOP -                TLS client done  - !!!!!!
I1208 13:56:05.208575630  115439 ssl_transport_security.cc:226]       HANDSHAKE DONE -                TLS client done  - !!!!!!
```

**Comment by yashykt** [comment] 2020-12-08 22:31
This might be an environment/set-up issue given that we have interop tests to make sure that security works as expected across languages.

I am not familiar with vcpkg or conan unfortunately. We usually recommend using bazel, or alternatively cmake. 
@mys007 would it be possible to run this example (with modifications) using bazel instead?

**Comment by yashykt** [comment] 2020-12-08 22:57
Shooting a bit in the dark based on what I see from the logs - 
The only handshaker that is invoked is the http_connect handshaker. The security handshakers are not invoked, which would suggest that that the security handshakers are not added which would suggest that security handshaker is not registered.

In a proper secure build that happens here -
https://github.com/grpc/grpc/blob/997dc017b9170ce05c23167ec1491d8996abee08/src/core/lib/surface/init_secure.cc#L81
with a call to `grpc_security_init()` during `grpc_init()`.

We also have another no-op implementation for `grpc_security_init()` at - https://github.com/grpc/grpc/blob/997dc017b9170ce05c23167ec1491d8996abee08/src/core/lib/surface/init_unsecure.cc#L27
which is only supposed to be used for insecure builds. If this is indeed a build related issue, then simply switching to bazel and using the provided BUILD file should solve it for you.

**Comment by mys007** [comment] 2020-12-09 11:47
Thank you so much for having looked into the issue! With the official cmake build setup it works (gRPC 1.33), the communication is encrypted. So I was trying to understand why. And it seems to be due to the ordering and/or choice of gRPC libs being linked to. When I remove `grpc++_unsecure.lib`, `grpc_unsecure.lib`, `grpc_cronet.lib` from the list, it works also for conan and vcpkg. But I find it largely intuitive that this influences the behavior of the code, rather than just solves compile time issues ("it compiles and starts, so it must have all it needs").

* Is there any documentation on linking? 
* I would suggests the silent no-op definitions in `init_unsecure.cc` are replaced with errors, as it is e.g. done with missing support for domain sockets in `unix_sockets_posix_noop.cc`.

**Comment by yashykt** [comment] 2020-12-15 14:16
> Is there any documentation on linking?
The BUILD file is pretty descriptive. What kind of documentation are you looking for?

> I would suggests the silent no-op definitions in init_unsecure.cc are replaced with errors, e.g. as it is done with missing support for domain sockets in unix_sockets_posix_noop.cc.
We cannot return an error from init_unsecure.cc since that is a valid path for insecure builds. We can potentially log a warning though.

**Comment by mys007** [comment] 2020-12-15 15:00
> What kind of documentation are you looking for?

I wish for a document I could refer to when I want to add gRPC to my C++ project and I need to know which lib files I should link to. As this thread shows, it's not trivial.

> We cannot return an error from init_unsecure.cc since that is a valid path for insecure builds.

This is quite unexpected to me, so...

> We can potentially log a warning though.

...that would be great!

**Comment by yashykt** [comment] 2020-12-24 05:48
> I wish for a document I could refer to when I want to add gRPC to my C++ project and I need to know which lib files I should link to. As this thread shows, it's not trivial.

I believe the BUILD file is an easy way to figure out the proper dependencies for various targets. I think what would be really useful in this case is a doc with instructions on building grpc with vcpkg. I will leave it to the build experts - @nicolasnoble and @veblush to decide whether vcpkg is something we want to add support for. (I suspect this might be one of those things where we need help from the community to help maintain.)

> We can potentially log a warning though.

> ...that would be great!

https://github.com/grpc/grpc/pull/25056 to add the log

Closing the bug since the issue itself has been resolved. (There is a potential follow-up feature request here for which a new thread should be started.)

**Closed by yashykt** 2020-12-24 05:48 UTC
Labels: disposition/requires reporter action, kind/bug, lang/c++, priority/P2

**Comment by mys007** [comment] 2020-12-24 23:15
Thanks, the log entry will surely be helpful to future users!
