### ISSUE TITLE
TIMEOUT: artifact build macos csharp ios

### ISSUE THREAD

**Issue by yashykt** [grpc/grpc#25029] opened 2020-12-17 20:59 UTC
Seen on #24956

https://source.cloud.google.com/results/invocations/109a4765-2911-4be5-80a0-e1d6093381e7/targets

**Comment by jtattermusch** [comment] 2022-02-14 12:23
Dupe of https://github.com/grpc/grpc/issues/27211

**Closed by jtattermusch** 2022-02-14 12:23 UTC
Labels: kind/bug, lang/C#, disposition/BUILDNURSE, priority/P2
