### ISSUE TITLE
Authenticate TLS client channel

### ISSUE THREAD

**Issue by noahdav** [grpc/grpc#23811] opened 2020-08-13 05:05 UTC
### What version of gRPC and what language are you using?
1.29.1

### What operating system (Linux, Windows,...) and version?
Windows

### What runtime / compiler are you using (e.g. python version or version of gcc)
MSVC 

### What did you do?
I am trying to validate the client TLS certificate during the channel connection not on every request.  This can be done in the rpc itself using the auth_context or by using an AuthMetadataProcessor.  Both of these options require that the client certificate is validated on each request.

By using the grpc_impl::experimental::TlsCredentialsOptions and specifying the server_authorization_check_config the client can easily validate the server.  How does the server perform similar operation to validate the client only during channel connection not on every request. 

### What did you see instead?
When setting the server_authorization_check_config on the TlsCredentialsOptions the callback is not called but instead grpc validates that this is not set when creating the ServerCredentials.

**Comment by markdroth** [comment] 2020-09-09 15:55
This looks like a duplicate of the same issue you filed in #23498.

**Closed by markdroth** 2020-09-09 15:55 UTC
Labels: kind/bug, priority/P2

**Comment by JScon01** [comment] 2020-09-09 15:58
I am not a Programmer. I’m a Disabled Veteran. Stop!

Jeffrey H. Conz
