### ISSUE TITLE
v1.57.0-pre1 does not build with bazel

### ISSUE THREAD

**Issue by nhawrysh** [grpc/grpc#33986] opened 2023-08-04 13:40 UTC
### What version of gRPC and what language are you using?
gRPC v1.57.0-pre1 C++

### What operating system (Linux, Windows,...) and version?
Windows 10 10.0.19045

### What runtime / compiler are you using (e.g. python version or version of gcc)
bazel

### What did you do?
Followed instructions here for windows https://github.com/grpc/grpc/blob/v1.57.0-pre1/BUILDING.md

### What did you expect to see?
Completed build

### What did you see instead?

```
ERROR: C:/users/nicolas.hawrysh/desktop/grpc/src/core/BUILD:35:14: Label '//src/core:ext/transport/binder/java/WORKSPACE' is invalid because '@binder_transport_android_helper//' is a subpackage
ERROR: C:/users/nicolas.hawrysh/desktop/grpc/BUILD:2785:16: Target '//src/core:lib/backoff/backoff.cc' contains an error and its package is in error and referenced by '//:backoff'
ERROR: C:/users/nicolas.hawrysh/desktop/grpc/BUILD:2785:16: Target '//src/core:lib/backoff/backoff.h' contains an error and its package is in error and referenced by '//:backoff'
ERROR: C:/users/nicolas.hawrysh/desktop/grpc/BUILD:2785:16: Target '//src/core:time' contains an error and its package is in error and referenced by '//:backoff'
ERROR: C:/users/nicolas.hawrysh/desktop/grpc/BUILD:2435:16: Target '//src/core:lib/config/config_vars.cc' contains an error and its package is in error and referenced by '//:config_vars'
ERROR: C:/users/nicolas.hawrysh/desktop/grpc/BUILD:2435:16: Target '//src/core:lib/config/config_vars_non_generated.cc' contains an error and its package is in error and referenced by '//:config_vars'
ERROR: C:/users/nicolas.hawrysh/desktop/grpc/BUILD:2435:16: Target '//src/core:lib/config/config_vars.h' contains an error and its package is in error and referenced by '//:config_vars'
ERROR: Analysis of target '//:config_vars' failed; build aborted: Analysis failed
```

**Comment by drfloob** [comment] 2023-08-08 19:57
I can't reproduce your problem with Windows 11 Pro, so either Windows 10 is an issue somehow, which I doubt, or there is some other variable we're missing in your environment.

```
$ git checkout v1.57.x
Switched to a new branch 'v1.57.x'
branch 'v1.57.x' set up to track 'upstream/v1.57.x'.

$ git pull
Already up to date.

$ git submodule update --init

$ bazel --version
bazel 5.4.1
  # tried also with bazel v6.3.2

$ cat $HOME/.bazelrc
startup --output_user_root="C:\\_bo"
startup --windows_enable_symlinks
build --enable_runfiles
build --config=windows_dbg
build --cxxopt='/wd4090'
build --cxxopt='/DEBUG:FASTLINK'

$ bazel build :all
Starting local Bazel server and connecting to it...
DEBUG: C:/_bo/ddkp74ac/external/upb/bazel/system_python.bzl:200:14: WARNING: python is not supported on Windows
INFO: Analyzed 177 targets (172 packages loaded, 5727 targets configured).
INFO: Found 177 targets...
INFO: From Compiling src/core/lib/slice/slice.cc:
C:\_bo\ddkp74ac\execroot\com_github_grpc_grpc\src\core\lib\slice\slice.cc(194) : warning C4700: uninitialized local variable 'slice' used
C:\_bo\ddkp74ac\execroot\com_github_grpc_grpc\src\core\lib\slice\slice.cc(213) : warning C4700: uninitialized local variable 'slice' used
INFO: From Compiling src/core/lib/event_engine/thread_pool/original_thread_pool.cc:
...
INFO: Elapsed time: 177.268s, Critical Path: 18.15s
INFO: 1833 processes: 151 internal, 1682 local.
INFO: Build completed successfully, 1833 total actions
```

**Comment by drfloob** [comment] 2023-08-08 21:21
I believe this is a duplicate of https://github.com/grpc/grpc/issues/33323. Please reopen the issue if my assumption about you using bazel v7.x is wrong, and you can reproduce this on bazel v5.x or 6.x.

**Closed by drfloob** 2023-08-08 21:21 UTC
Labels: kind/bug, lang/c++, priority/P2, disposition/requires reporter action, untriaged

**Comment by nhawrysh** [comment] 2023-08-16 14:23
Using bazel 6.3.2 and I am getting the following error:

cl.exe failed: error executing command (from target @com_google_protobuf//src/google/protobuf/util:delimited_message_util) C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.36.32532\bin\HostX64\x64\cl.exe /nologo /DCOMPILER_MSVC /DNOMINMAX /D_WIN32_WINNT=0x0601 /D_CRT_SECURE_NO_DEPRECATE ... (remaining 57 arguments skipped)
external/com_google_protobuf/src/google/protobuf/util/delimited_message_util.cc(34): fatal error C1083: Cannot open include file: 'google/protobuf/util/delimited_message_util.h': No such file or directory

I tried using v5.x as well and it's the same error where it can't find headers that do exist.

**Comment by drfloob** [comment] 2023-08-16 18:25
That is a very different error from the one you originally posted. Depending on whether your Windows development environment supports long filenames or not, you may want to try adding something like `--output_user_root=C::\_bo` to your bazel build command, or playing with Windows symlink support.

gRPC's CI builds successfully with Visual Studio 2019 maybe 100 times per day. You could try 2019 to see if that helps as well, but I imagine it will not.

**Comment by rubuslab** [comment] 2023-09-01 02:22
The same error reproduced on my windows 11.

**Comment by laramiel** [comment] 2023-12-06 00:05
https://github.com/bazelbuild/bazel/issues/18683
