### ISSUE TITLE
Rendezvous: <_Rendezvous of RPC that terminated with (StatusCode.UNAVAILABLE, Connect Failed)>

### ISSUE THREAD

**Issue by anoopmv** [grpc/grpc#12116] opened 2017-08-08 05:10 UTC
Please answer these questions before submitting your issue. 
 
### Should this be an issue in the gRPC issue tracker?
 Hope
Create new issues for bugs and feature requests. An issue needs to be actionable. General gRPC discussions and usage questions belong to:
- [grpc.io mailing list](https://groups.google.com/forum/#!forum/grpc-io)
- [StackOverflow, with `grpc` tag](http://stackoverflow.com/questions/tagged/grpc)
 
*Please don't double post your questions in more locations; we are monitoring both channels, and the time spent de-duplicating questions is better spent answering more user questions.*
 
### What operating system (Linux, Windows, …) and version?
 
 Linux 14.04
### What runtime / compiler are you using (e.g. python version or version of gcc)
 
 python version
### What did you do?
Rendezvous: <_Rendezvous of RPC that terminated with (StatusCode.UNAVAILABLE, Connect Failed)>

Traceback (most recent call last):
  File "greeter_client.py", line 48, in <module>
    run()
  File "greeter_client.py", line 43, in run
    response = stub.SayHello(helloworld_pb2.HelloRequest(name='you'))
  File "/usr/local/lib/python2.7/dist-packages/grpc/_channel.py", line 507, in __call__
    return _end_unary_response_blocking(state, call, False, deadline)
  File "/usr/local/lib/python2.7/dist-packages/grpc/_channel.py", line 455, in _end_unary_response_blocking
    raise _Rendezvous(state, None, None, deadline)
grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with (StatusCode.UNAVAILABLE, Connect Failed)>

 
### What did you expect to see?
 Server and Client should be pinging
 
### What did you see instead?
 Traceback (most recent call last):
  File "greeter_client.py", line 48, in <module>
    run()
  File "greeter_client.py", line 43, in run
    response = stub.SayHello(helloworld_pb2.HelloRequest(name='you'))
  File "/usr/local/lib/python2.7/dist-packages/grpc/_channel.py", line 507, in __call__
    return _end_unary_response_blocking(state, call, False, deadline)
  File "/usr/local/lib/python2.7/dist-packages/grpc/_channel.py", line 455, in _end_unary_response_blocking
    raise _Rendezvous(state, None, None, deadline)
grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with (StatusCode.UNAVAILABLE, Connect Failed)>

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).
 
### Anything else we should know about your project / environment?

No.

**Comment by nathanielmanistaatgoogle** [comment] 2017-08-25 18:56
Can you tell us anything more about your environment? Is there anything particular to your platform that would prevent one program from locally connecting to another?

What is the exact sequence of commands that reproduces the problem?

**Comment by nathanielmanistaatgoogle** [comment] 2017-09-13 20:54
Closing as a duplicate of [issue 9987](https://github.com/grpc/grpc/issues/9987).

**Closed by nathanielmanistaatgoogle** 2017-09-13 20:54 UTC
Labels: disposition/requires reporter action, lang/Python
