### ISSUE TITLE
ExpirationError in Python unary test on Travis

### ISSUE THREAD

**Issue by murgatroid99** [grpc/grpc#1536] opened 2015-05-08 21:08 UTC
This is the log:

```
ERROR: testUnaryUnary (__main__.EarlyAdopterImplementationsTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/grpc/grpc/python2.7_virtual_environment/lib/python2.7/site-packages/grpc/early_adopter/implementations_test.py", line 131, in testUnaryUnary
    math_pb2.DivArgs(divisor=divisor, dividend=dividend), _TIMEOUT)
  File "/home/travis/build/grpc/grpc/python2.7_virtual_environment/local/lib/python2.7/site-packages/grpc/framework/alpha/_reexport.py", line 158, in __call__
    self._underlying, request, timeout)
  File "/home/travis/build/grpc/grpc/python2.7_virtual_environment/local/lib/python2.7/site-packages/grpc/framework/alpha/_reexport.py", line 113, in _call_reexporting_errors
    raise _reexport_error(e)
ExpirationError
```

**Comment by nathanielmanistaatgoogle** [comment] 2015-05-08 21:11
How reproducible is this?

**Comment by jayantkolhe** [comment] 2015-05-21 21:46
Duplicate of #1670

**Closed by jayantkolhe** 2015-05-21 21:46 UTC
Labels: P1, python, Travis
