### ISSUE TITLE
cloud_to_cloud:node:python_server:large_unary and cloud_to_cloud:node:ruby_server:large_unary timeouts

### ISSUE THREAD

**Issue by markdroth** [grpc/grpc#13186] opened 2017-10-30 14:15 UTC
https://sponge.corp.google.com/target?id=fd6e1380-681f-444e-ba90-631ddc1909a9&target=github/grpc&searchFor=&show=ALL&sortBy=STATUS

The logs don't say anything even remotely interesting for either test -- just "Timeout".

**Comment by adelez** [comment] 2017-10-30 21:17
Assigning to Node team since both failures involve the Node client.
Can it also output more helpful information?

**Comment by murgatroid99** [comment] 2017-10-30 21:32
The core trace output is probably the best bet. If the client docker images were run with the "api" trace variable set, that might help.

**Comment by jtattermusch** [comment] 2017-11-06 15:11
Dupe of https://github.com/grpc/grpc/issues/13253.

**Closed by jtattermusch** 2017-11-06 15:11 UTC
Labels: infra/BUILDPONY
