### ISSUE TITLE
C# Project running in the same folder as "UnityEngine.dll" but not in a unity based runtime causes a runtime failure

### ISSUE THREAD

**Issue by Earthmark** [grpc/grpc#23334] opened 2020-06-27 02:46 UTC
### What version of gRPC and what language are you using?
C# Grpc 2.30.0

### What operating system (Linux, Windows,...) and version?
Windows 10 Pro OS build 19041.330

### What runtime / compiler are you using (e.g. python version or version of gcc)
dotnet framework 4.6.2

### What did you do?
Running a program that contains GRPC in a folder that contains `UnityEngine.dll`.

### What did you expect to see?
GRPC to run as normal.

### What did you see instead?
The type constructor for `Grpc.Core.Internal.PlatformApis` crashed with .
```
System.TypeInitializationException
  HResult=0x80131534
  Message=The type initializer for 'Grpc.Core.Internal.PlatformApis' threw an exception.
  Source=Grpc.Core
  StackTrace:
   at Grpc.Core.Internal.PlatformApis.get_IsXamarinIOS()
   at Grpc.Core.GrpcEnvironment.get_IsNativeShutdownAllowed()
   at Grpc.Core.GrpcEnvironment.GrpcNativeInit()
   at Grpc.Core.GrpcEnvironment..ctor()
   at Grpc.Core.GrpcEnvironment.AddRef()
   at Grpc.Core.Server..ctor(IEnumerable`1 options)
   at NetStandardLib.Program.Main() in E:\Dev\TestLib\Program.cs:line 19

Inner Exception 1:
TargetInvocationException: Exception has been thrown by the target of an invocation.
  StackTrace:
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.RuntimePropertyInfo.GetValue(Object obj, Object[] index)
   at Grpc.Core.Internal.PlatformApis..cctor()

Inner Exception 2:
SecurityException: ECall methods must be packaged into a system module.
  StackTrace:
   at UnityEngine.Application.get_platform()
```

### Anything else we should know about your project / environment?
This can be recreated by copying the `UnityEngine.dll` file from Unity next to a C# dotnet framework application, at which point running the application causes the failure. I did not test if adding the dll to any point in the assembly resolution paths would also cause the failure.

Here is a project, that when run demonstrates this failure:
[GrpcUnityFailure.zip](https://github.com/grpc/grpc/files/4839853/GrpcUnityFailure.zip)

It looks like the issue is that `Type.GetType(UnityEngineApplicationClassName);` will load the assembly if it's not already loaded, and then then invokes a unity-environment specific call with:
```
var platformProperty = unityApplicationClass.GetTypeInfo().GetProperty("platform");
var unityRuntimePlatform = platformProperty?.GetValue(null)?.ToString();
```
This call (`UnityEngine.Application.platform`) explodes because the program is not running in a unity context.

I can try to make a fix for this, but I figured y'all may have a preferred way it should be fixed, as it relates to security things and signals related to runtimes that I have not had experience with so far. If it's open season on this kind of bug though, I'll pick it up.

[Context for where the bug was discovered](https://github.com/Frooxius/NeosPublic/issues/719)

**Comment by jtattermusch** [comment] 2020-07-13 15:28
I think this is basically a duplicate of https://github.com/grpc/grpc/issues/18801? We need a better check for detecting if we are running on unity or not.

**Closed** 2020-07-13 16:15 UTC
Labels: area/build, kind/bug, lang/C#, priority/P2
