### ISSUE TITLE
error: invalid argument '-std=c++14' not allowed with 'C'

### ISSUE THREAD

**Issue by ryandesign** [grpc/grpc#33923] opened 2023-07-31 14:19 UTC
### What version of gRPC and what language are you using?

gRPC 1.48.0
Python

### What operating system (Linux, Windows,...) and version?

OS X 10.9 but I don't think the issue is OS specific

### What runtime / compiler are you using (e.g. python version or version of gcc)

Clang 16.0.6
Python 3.10.12

### What did you do?

Build the grpcio python module

### What did you expect to see?

Successful build

### What did you see instead?

```
clang: warning: argument unused during compilation: '-stdlib=libc++' [-Wunused-command-line-argument]
error: invalid argument '-std=c++14' not allowed with 'C'
```
```
distutils.errors.CompileError: command '/opt/local/bin/clang-mp-16' failed with exit code 1
```

[py310-grpcio.log](https://github.com/grpc/grpc/files/12215986/py310-grpcio.log)

### Anything else we should know about your project / environment?

I [reported this to MacPorts](https://trac.macports.org/ticket/62208) > 2 years ago but nothing has happened so I'm reporting it to you now.

**Comment by XuanWang-Amos** [comment] 2023-08-02 20:32
Hi, looks like we do have a [check here](https://github.com/grpc/grpc/blob/f10a8e3418e51230b0af86e880f82c8325a68abe/src/python/grpcio/commands.py#L281C45-L281C45) which suppose to ensure that the correct `-std=` will be used. Since we don't have a similar environment to reproduce, can you help check why the check is not working correctly on your side?

**Comment by mascguy** [comment] 2023-08-17 22:32
Since MacPorts is still at version 1.48.x, we didn't have the benefit of the following fix:

[PR 26480 - Respect CC variable in grpcio python build](https://github.com/grpc/grpc/pull/26480)

But with that in place, everything is good now.

So I think we can close this issue. @ryandesign ?

**Comment by gnossen** [comment] 2023-08-23 20:58
@mascguy Thanks for confirming!

**Closed by gnossen** 2023-08-23 20:58 UTC
Labels: kind/bug, lang/Python, priority/P2, disposition/requires reporter action
