### ISSUE TITLE
Cpp compile errors when building from source

### ISSUE THREAD

**Issue by teganburns** [grpc/grpc#11376] opened 2017-06-02 01:46 UTC
### Should this be an issue in the gRPC issue tracker?
I would think so.
 
### What version of gRPC and what language are you using?
latest commit on master: ec21e99322ec29f58c853d409adaf5aa2e4929ab
and release tar.gz of v1.0.0
 
### What operating system (Linux, Windows, …) and version?
GNU/Linux 
x86_64 
4.11.3-1-ARCH 
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
 GNU Make 4.2.1
Built for x86_64-unknown-linux-gnu

g++ (GCC) 7.1.1 20170528

gcc (GCC) 7.1.1 20170528
 
### What did you do?
previously installed and updated `autoconf` and `libtool` ( `build-essential` is preinstalled on arch )

*__First try__*: ( as per instructions https://github.com/grpc/grpc/tree/master/src/cpp#build-from-source )
1) git clone -b $(curl -L http://grpc.io/release) https://github.com/grpc/grpc
2) cd grpc/
3) git submodule update --init
4) make

*__Second try__*:
1) git clone https://github.com/grpc/grpc
2) cd grpc/
3) make

*__Third try__*:
1) wget https://github.com/grpc/grpc/archive/v1.0.0.tar.gz
2) tar -xvzf v1.0.0.tar.gz
3) cd grpc-1.0.0/
4) make

__Then commented out `-Werror` on line *358* for *v1.0.0*__
Line 358 in v1.0.0: 
`CPPFLAGS += -g -Wall -Wextra -Werror -Wno-long-long -Wno-unused-parameter`
 
### What did you expect to see?
 compiling without errors 
 
### What did you see instead?

---
__With `-Werror`__

[MAKE]    Generating /home/owner/Downloads/grpc-1.2.0/libs/opt/pkgconfig/grpc.pc
[MAKE]    Generating /home/owner/Downloads/grpc-1.2.0/libs/opt/pkgconfig/grpc_unsecure.pc
[MAKE]    Generating cache.mk
[C]       Compiling src/core/lib/profiling/basic_timers.c
[C]       Compiling src/core/lib/profiling/stap_timers.c
[C]       Compiling src/core/lib/support/alloc.c
[C]       Compiling src/core/lib/support/avl.c
[C]       Compiling src/core/lib/support/backoff.c
[C]       Compiling src/core/lib/support/cmdline.c
[C]       Compiling src/core/lib/support/cpu_iphone.c
[C]       Compiling src/core/lib/support/cpu_linux.c
[C]       Compiling src/core/lib/support/cpu_posix.c
[C]       Compiling src/core/lib/support/cpu_windows.c
[C]       Compiling src/core/lib/support/env_linux.c
[C]       Compiling src/core/lib/support/env_posix.c
[C]       Compiling src/core/lib/support/env_windows.c
[C]       Compiling src/core/lib/support/histogram.c
[C]       Compiling src/core/lib/support/host_port.c
[C]       Compiling src/core/lib/support/log.c
[C]       Compiling src/core/lib/support/log_android.c
[C]       Compiling src/core/lib/support/log_linux.c
[C]       Compiling src/core/lib/support/log_posix.c
[C]       Compiling src/core/lib/support/log_windows.c
[C]       Compiling src/core/lib/support/mpscq.c
[C]       Compiling src/core/lib/support/murmur_hash.c
src/core/lib/support/murmur_hash.c: In function ‘gpr_murmur_hash3’:
src/core/lib/support/murmur_hash.c:79:10: error: this statement may fall through [-Werror=implicit-fallthrough=]
       k1 ^= ((uint32_t)tail[2]) << 16;
       ~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/core/lib/support/murmur_hash.c:80:5: note: here
     case 2:
     ^~~~
src/core/lib/support/murmur_hash.c:81:10: error: this statement may fall through [-Werror=implicit-fallthrough=]
       k1 ^= ((uint32_t)tail[1]) << 8;
       ~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~
src/core/lib/support/murmur_hash.c:82:5: note: here
     case 1:
     ^~~~
cc1: all warnings being treated as errors
make: *** [Makefile:2366: /home/owner/Downloads/grpc-1.2.0/objs/opt/src/core/lib/support/murmur_hash.o] Error 1

----
__Without `-Werror`__

[MAKE]    Generating /home/owner/Downloads/grpc-1.0.0/libs/opt/pkgconfig/grpc.pc
[MAKE]    Generating /home/owner/Downloads/grpc-1.0.0/libs/opt/pkgconfig/grpc_unsecure.pc
[MAKE]    Generating cache.mk
[C]       Compiling src/core/lib/profiling/basic_timers.c
[C]       Compiling src/core/lib/profiling/stap_timers.c
[C]       Compiling src/core/lib/support/alloc.c
[C]       Compiling src/core/lib/support/avl.c
[C]       Compiling src/core/lib/support/backoff.c
[C]       Compiling src/core/lib/support/cmdline.c
[C]       Compiling src/core/lib/support/cpu_iphone.c
[C]       Compiling src/core/lib/support/cpu_linux.c
[C]       Compiling src/core/lib/support/cpu_posix.c
[C]       Compiling src/core/lib/support/cpu_windows.c
[C]       Compiling src/core/lib/support/env_linux.c
[C]       Compiling src/core/lib/support/env_posix.c
[C]       Compiling src/core/lib/support/env_windows.c
[C]       Compiling src/core/lib/support/histogram.c
[C]       Compiling src/core/lib/support/host_port.c
[C]       Compiling src/core/lib/support/log.c
[C]       Compiling src/core/lib/support/log_android.c
[C]       Compiling src/core/lib/support/log_linux.c
[C]       Compiling src/core/lib/support/log_posix.c
[C]       Compiling src/core/lib/support/log_windows.c
[C]       Compiling src/core/lib/support/murmur_hash.c
src/core/lib/support/murmur_hash.c: In function ‘gpr_murmur_hash3’:
src/core/lib/support/murmur_hash.c:79:10: warning: this statement may fall through [-Wimplicit-fallthrough=]
       k1 ^= ((uint32_t)tail[2]) << 16;
       ~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/core/lib/support/murmur_hash.c:80:5: note: here
     case 2:
     ^~~~
src/core/lib/support/murmur_hash.c:81:10: warning: this statement may fall through [-Wimplicit-fallthrough=]
       k1 ^= ((uint32_t)tail[1]) << 8;
       ~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~
src/core/lib/support/murmur_hash.c:82:5: note: here
     case 1:
     ^~~~
[C]       Compiling src/core/lib/support/slice.c
[C]       Compiling src/core/lib/support/slice_buffer.c
[C]       Compiling src/core/lib/support/stack_lockfree.c
[C]       Compiling src/core/lib/support/string.c
[C]       Compiling src/core/lib/support/string_posix.c
[C]       Compiling src/core/lib/support/string_util_windows.c
[C]       Compiling src/core/lib/support/string_windows.c
[C]       Compiling src/core/lib/support/subprocess_posix.c
[C]       Compiling src/core/lib/support/subprocess_windows.c
[C]       Compiling src/core/lib/support/sync.c
[C]       Compiling src/core/lib/support/sync_posix.c
[C]       Compiling src/core/lib/support/sync_windows.c
[C]       Compiling src/core/lib/support/thd.c
[C]       Compiling src/core/lib/support/thd_posix.c
[C]       Compiling src/core/lib/support/thd_windows.c
[C]       Compiling src/core/lib/support/time.c
[C]       Compiling src/core/lib/support/time_posix.c
[C]       Compiling src/core/lib/support/time_precise.c
[C]       Compiling src/core/lib/support/time_windows.c
[C]       Compiling src/core/lib/support/tls_pthread.c
[C]       Compiling src/core/lib/support/tmpfile_msys.c
[C]       Compiling src/core/lib/support/tmpfile_posix.c
[C]       Compiling src/core/lib/support/tmpfile_windows.c
[C]       Compiling src/core/lib/support/wrap_memcpy.c
[AR]      Creating /home/owner/Downloads/grpc-1.0.0/libs/opt/libgpr.a
[C]       Compiling src/core/lib/surface/init.c
[C]       Compiling src/core/lib/channel/channel_args.c
[C]       Compiling src/core/lib/channel/channel_stack.c
[C]       Compiling src/core/lib/channel/channel_stack_builder.c
[C]       Compiling src/core/lib/channel/compress_filter.c
[C]       Compiling src/core/lib/channel/connected_channel.c
[C]       Compiling src/core/lib/channel/http_client_filter.c
[C]       Compiling src/core/lib/channel/http_server_filter.c
[C]       Compiling src/core/lib/compression/compression.c
[C]       Compiling src/core/lib/compression/message_compress.c
[C]       Compiling src/core/lib/debug/trace.c
[C]       Compiling src/core/lib/http/format_request.c
[C]       Compiling src/core/lib/http/httpcli.c
[C]       Compiling src/core/lib/http/parser.c
[C]       Compiling src/core/lib/iomgr/closure.c
[C]       Compiling src/core/lib/iomgr/endpoint.c
[C]       Compiling src/core/lib/iomgr/endpoint_pair_posix.c
[C]       Compiling src/core/lib/iomgr/endpoint_pair_windows.c
[C]       Compiling src/core/lib/iomgr/error.c
[C]       Compiling src/core/lib/iomgr/ev_epoll_linux.c
[C]       Compiling src/core/lib/iomgr/ev_poll_and_epoll_posix.c
[C]       Compiling src/core/lib/iomgr/ev_poll_posix.c
[C]       Compiling src/core/lib/iomgr/ev_posix.c
[C]       Compiling src/core/lib/iomgr/exec_ctx.c
[C]       Compiling src/core/lib/iomgr/executor.c
[C]       Compiling src/core/lib/iomgr/iocp_windows.c
[C]       Compiling src/core/lib/iomgr/iomgr.c
[C]       Compiling src/core/lib/iomgr/iomgr_posix.c
[C]       Compiling src/core/lib/iomgr/iomgr_windows.c
[C]       Compiling src/core/lib/iomgr/load_file.c
[C]       Compiling src/core/lib/iomgr/network_status_tracker.c
[C]       Compiling src/core/lib/iomgr/polling_entity.c
[C]       Compiling src/core/lib/iomgr/pollset_set_windows.c
[C]       Compiling src/core/lib/iomgr/pollset_windows.c
[C]       Compiling src/core/lib/iomgr/resolve_address_posix.c
[C]       Compiling src/core/lib/iomgr/resolve_address_windows.c
[C]       Compiling src/core/lib/iomgr/sockaddr_utils.c
[C]       Compiling src/core/lib/iomgr/socket_utils_common_posix.c
[C]       Compiling src/core/lib/iomgr/socket_utils_linux.c
[C]       Compiling src/core/lib/iomgr/socket_utils_posix.c
[C]       Compiling src/core/lib/iomgr/socket_windows.c
[C]       Compiling src/core/lib/iomgr/tcp_client_posix.c
[C]       Compiling src/core/lib/iomgr/tcp_client_windows.c
[C]       Compiling src/core/lib/iomgr/tcp_posix.c
[C]       Compiling src/core/lib/iomgr/tcp_server_posix.c
[C]       Compiling src/core/lib/iomgr/tcp_server_windows.c
[C]       Compiling src/core/lib/iomgr/tcp_windows.c
[C]       Compiling src/core/lib/iomgr/time_averaged_stats.c
[C]       Compiling src/core/lib/iomgr/timer.c
[C]       Compiling src/core/lib/iomgr/timer_heap.c
[C]       Compiling src/core/lib/iomgr/udp_server.c
[C]       Compiling src/core/lib/iomgr/unix_sockets_posix.c
[C]       Compiling src/core/lib/iomgr/unix_sockets_posix_noop.c
[C]       Compiling src/core/lib/iomgr/wakeup_fd_eventfd.c
[C]       Compiling src/core/lib/iomgr/wakeup_fd_nospecial.c
[C]       Compiling src/core/lib/iomgr/wakeup_fd_pipe.c
[C]       Compiling src/core/lib/iomgr/wakeup_fd_posix.c
[C]       Compiling src/core/lib/iomgr/workqueue_posix.c
[C]       Compiling src/core/lib/iomgr/workqueue_windows.c
[C]       Compiling src/core/lib/json/json.c
[C]       Compiling src/core/lib/json/json_reader.c
src/core/lib/json/json_reader.c: In function ‘grpc_json_reader_run’:
src/core/lib/json/json_reader.c:193:27: warning: this statement may fall through [-Wimplicit-fallthrough=]
             reader->state = GRPC_JSON_STATE_VALUE_END;
             ~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~
src/core/lib/json/json_reader.c:196:11: note: here
           case GRPC_JSON_STATE_VALUE_END:
           ^~~~
[C]       Compiling src/core/lib/json/json_string.c
[C]       Compiling src/core/lib/json/json_writer.c
[C]       Compiling src/core/lib/surface/alarm.c
[C]       Compiling src/core/lib/surface/api_trace.c
[C]       Compiling src/core/lib/surface/byte_buffer.c
[C]       Compiling src/core/lib/surface/byte_buffer_reader.c
[C]       Compiling src/core/lib/surface/call.c
[C]       Compiling src/core/lib/surface/call_details.c
[C]       Compiling src/core/lib/surface/call_log_batch.c
[C]       Compiling src/core/lib/surface/channel.c
[C]       Compiling src/core/lib/surface/channel_init.c
[C]       Compiling src/core/lib/surface/channel_ping.c
[C]       Compiling src/core/lib/surface/channel_stack_type.c
[C]       Compiling src/core/lib/surface/completion_queue.c
[C]       Compiling src/core/lib/surface/event_string.c
[C]       Compiling src/core/lib/surface/lame_client.c
[C]       Compiling src/core/lib/surface/metadata_array.c
[C]       Compiling src/core/lib/surface/server.c
[C]       Compiling src/core/lib/surface/validate_metadata.c
[C]       Compiling src/core/lib/surface/version.c
[C]       Compiling src/core/lib/transport/byte_stream.c
[C]       Compiling src/core/lib/transport/connectivity_state.c
[C]       Compiling src/core/lib/transport/metadata.c
[C]       Compiling src/core/lib/transport/metadata_batch.c
[C]       Compiling src/core/lib/transport/static_metadata.c
[C]       Compiling src/core/lib/transport/transport.c
[C]       Compiling src/core/lib/transport/transport_op_string.c
[C]       Compiling src/core/ext/transport/chttp2/server/secure/server_secure_chttp2.c
[C]       Compiling src/core/ext/transport/chttp2/transport/bin_decoder.c
src/core/ext/transport/chttp2/transport/bin_decoder.c: In function ‘grpc_base64_decode_partial’:
src/core/ext/transport/chttp2/transport/bin_decoder.c:133:30: warning: this statement may fall through [-Wimplicit-fallthrough=]
           ctx->output_cur[1] = COMPOSE_OUTPUT_BYTE_1(ctx->input_cur);
                              ^
src/core/ext/transport/chttp2/transport/bin_decoder.c:134:9: note: here
         case 2:
         ^~~~
[C]       Compiling src/core/ext/transport/chttp2/transport/bin_encoder.c
[C]       Compiling src/core/ext/transport/chttp2/transport/chttp2_plugin.c
[C]       Compiling src/core/ext/transport/chttp2/transport/chttp2_transport.c
[C]       Compiling src/core/ext/transport/chttp2/transport/frame_data.c
[C]       Compiling src/core/ext/transport/chttp2/transport/frame_goaway.c
[C]       Compiling src/core/ext/transport/chttp2/transport/frame_ping.c
[C]       Compiling src/core/ext/transport/chttp2/transport/frame_rst_stream.c
[C]       Compiling src/core/ext/transport/chttp2/transport/frame_settings.c
[C]       Compiling src/core/ext/transport/chttp2/transport/frame_window_update.c
[C]       Compiling src/core/ext/transport/chttp2/transport/hpack_encoder.c
[C]       Compiling src/core/ext/transport/chttp2/transport/hpack_parser.c
[C]       Compiling src/core/ext/transport/chttp2/transport/hpack_table.c
[C]       Compiling src/core/ext/transport/chttp2/transport/huffsyms.c
[C]       Compiling src/core/ext/transport/chttp2/transport/incoming_metadata.c
[C]       Compiling src/core/ext/transport/chttp2/transport/parsing.c
[C]       Compiling src/core/ext/transport/chttp2/transport/status_conversion.c
[C]       Compiling src/core/ext/transport/chttp2/transport/stream_lists.c
[C]       Compiling src/core/ext/transport/chttp2/transport/stream_map.c
[C]       Compiling src/core/ext/transport/chttp2/transport/timeout_encoding.c
[C]       Compiling src/core/ext/transport/chttp2/transport/varint.c
src/core/ext/transport/chttp2/transport/varint.c: In function ‘grpc_chttp2_hpack_write_varint_tail’:
src/core/ext/transport/chttp2/transport/varint.c:54:17: warning: this statement may fall through [-Wimplicit-fallthrough=]
       target[4] = (uint8_t)((tail_value >> 28) | 0x80);
       ~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/core/ext/transport/chttp2/transport/varint.c:55:5: note: here
     case 4:
     ^~~~
src/core/ext/transport/chttp2/transport/varint.c:56:17: warning: this statement may fall through [-Wimplicit-fallthrough=]
       target[3] = (uint8_t)((tail_value >> 21) | 0x80);
       ~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/core/ext/transport/chttp2/transport/varint.c:57:5: note: here
     case 3:
     ^~~~
src/core/ext/transport/chttp2/transport/varint.c:58:17: warning: this statement may fall through [-Wimplicit-fallthrough=]
       target[2] = (uint8_t)((tail_value >> 14) | 0x80);
       ~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/core/ext/transport/chttp2/transport/varint.c:59:5: note: here
     case 2:
     ^~~~
src/core/ext/transport/chttp2/transport/varint.c:60:17: warning: this statement may fall through [-Wimplicit-fallthrough=]
       target[1] = (uint8_t)((tail_value >> 7) | 0x80);
       ~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/core/ext/transport/chttp2/transport/varint.c:61:5: note: here
     case 1:
     ^~~~
[C]       Compiling src/core/ext/transport/chttp2/transport/writing.c
[C]       Compiling src/core/ext/transport/chttp2/alpn/alpn.c
[C]       Compiling src/core/lib/http/httpcli_security_connector.c
[C]       Compiling src/core/lib/security/context/security_context.c
[C]       Compiling src/core/lib/security/credentials/composite/composite_credentials.c
[C]       Compiling src/core/lib/security/credentials/credentials.c
[C]       Compiling src/core/lib/security/credentials/credentials_metadata.c
[C]       Compiling src/core/lib/security/credentials/fake/fake_credentials.c
[C]       Compiling src/core/lib/security/credentials/google_default/credentials_posix.c
[C]       Compiling src/core/lib/security/credentials/google_default/credentials_windows.c
[C]       Compiling src/core/lib/security/credentials/google_default/google_default_credentials.c
[C]       Compiling src/core/lib/security/credentials/iam/iam_credentials.c
[C]       Compiling src/core/lib/security/credentials/jwt/json_token.c
[C]       Compiling src/core/lib/security/credentials/jwt/jwt_credentials.c
[C]       Compiling src/core/lib/security/credentials/jwt/jwt_verifier.c
src/core/lib/security/credentials/jwt/jwt_verifier.c: In function ‘pkey_from_jwk’:
src/core/lib/security/credentials/jwt/jwt_verifier.c:483:10: error: dereferencing pointer to incomplete type ‘RSA {aka struct rsa_st}’
       rsa->n = bignum_from_base64(validate_string_field(key_prop, "n"));
          ^~
make: *** [Makefile:2082: /home/owner/Downloads/grpc-1.0.0/objs/opt/src/core/lib/security/credentials/jwt/jwt_verifier.o] Error 1


 
### Anything else we should know about your project / environment?
  - Used 'yaourt' previously to build gRPC. (piece of cake!)
  - Attempted to compile personal project that worked before, there was a linking error for something gRPC related.
  - Figured something needed updated, so I attempted to update.
  - Got and error (same as first error from above). 
  - Removed packages and attempted to compile from scratch.

*__The same errors still occur when building on a fresh install.__*

**Comment by ramon-garcia** [comment] 2017-07-22 15:56
The problems with RSA is a duplicate of #8801  (compatibility with new OpenSSL 1.1 interfaces)

```
 src/core/lib/security/credentials/jwt/jwt_verifier.c:483:10: error: dereferencing pointer to incomplete type ‘RSA {aka struct rsa_st}’
 rsa->n = bignum_from_base64(validate_string_field(key_prop, "n"));
 ^~
```

**Comment by nicolasnoble** [comment] 2018-05-15 23:47
We fixed these a long while ago.

**Closed by nicolasnoble** 2018-05-15 23:47 UTC
Labels: area/build, kind/customer issue, lang/c++
