### ISSUE TITLE
gRPC Core: Integration with an existing (3rd-party) event loop.

### ISSUE THREAD

**Issue by chhsia0** [grpc/grpc#14565] opened 2018-03-01 21:59 UTC
### Should this be an issue in the gRPC issue tracker?

Yes.
 
### What version of gRPC and what language are you using?

C++, but I'm willing to directly use gRPC core, so a C++ wrapper for this is less of an issue.
 
### What operating system (Linux, Windows, …) and version?

Linux, but it would be nice if this feature can be supported on Windows as well.
 
### Description

Currently the gRPC core library provides `grpc_completion_queue` for handling asynchronous calls for both servers and clients. However, it encapsulates the event loop under the hood, which make it hard to integrate with a 3rd-party event loop. Ideally, if the core library provide an abstraction against the event loop, it would be much easier to plug in a 3rd-party event loop into gRPC so it can process both gRPC events as well as other external events.

A related issue for NodeJS is here: https://github.com/grpc/grpc/pull/8125

**Comment by chhsia0** [comment] 2018-03-01 22:05
I find that it might be worthy to borrow some ideas from http://sans-io.readthedocs.io/ :)

**Comment by yashykt** [comment] 2018-03-02 19:31
+ @sreecha

**Comment by sreecha** [comment] 2018-06-04 21:18
Assigning this to @kpayson64 who did some work to integrate gevent with grpc core.

**Comment by bjarnisig** [comment] 2019-03-27 17:11
Is there anything new to report for this issue?

**Comment by rwestphal** [comment] 2019-04-11 15:39
+1 to this.

I'd love to be able to integrate gRPC in the main event loop of my program, so that the RPCs are processed in the main pthread.

**Comment by guantaol** [comment] 2019-04-12 03:04
We are currently designing a new IOMgr interface for gRPC core, which can be used to easily integrate third-party event loop (by using the third-party event loop to implement this interface). We expect this new interface to land very soon.

**Comment by rwestphal** [comment] 2019-06-03 16:44
@guantaol that's great news! Do you have an ETA for this new interface?

**Comment by guantaol** [comment] 2019-06-07 03:55
@rwestphal We plan to publicize this new interface around the end of June, and finish its integration with the current grpc iomgr by the end of August. We will also provide an implementation based on libuv during the integration.

**Comment by rwestphal** [comment] 2019-06-07 03:58
@guantaol That's great news, looking forward to it!!

**Comment by metellius** [comment] 2019-08-12 12:55
@guantaol Has anything gone public yet? I'm trying to look for traces of iomgr work in git but can't see anything. Will there be a blog post about this when it goes out?

**Comment by vijaykalkoti** [comment] 2019-09-08 08:31
Is this feature available now ?

Could you please share more details on this feature?

**Comment by guantaol** [comment] 2019-09-17 01:02
Sorry for the delay.

We had a long discussion internally on how to fit the new interface for different platforms and polling models. The design is almost done, and I am currently adding the new interface to grpc repo.

**Comment by ForrestSu** [comment] 2019-11-12 11:04
I am looking for a solution for integrating grpc with libuv. 
Is this feature available now ?
Could you please share more details on this feature?

**Comment by guantaol** [comment] 2019-11-12 21:58
I am currently implementing the new IOMgr interface with libuv. It should be public in two to three weeks.

**Comment by eendru** [comment] 2019-12-12 07:27
Is there any updates ?

**Comment by pyssling** [comment] 2020-01-18 14:59
Just a small question, is this expected to work with boost io_context ? As I understand it boost asio io_context is headed for C++ ISO standardization, so it would be nice if gRPC layered nicely on top of this.

**Comment by RobertBColton** [comment] 2020-03-07 07:28
Is this not a duplicate of #14796?

**Comment by rwestphal** [comment] 2020-04-23 21:31
> Is there any updates ?

Apparently not. Unfortunately it seems resolving this issue is a very low priority to the grpc team.

**Comment by ThomsonTan** [comment] 2020-07-18 06:51
Is there any update about any kind of event loop integration?

**Comment by veblush** [comment] 2020-07-22 20:56
We've been working on this for a while and revisiting this to get better understanding of requirements. Since EvenetManager does two things; Polling and Executing callback handlers. I want to know which part you're interested more? Presumably building platform-independent (or dependent if you want to extend the platform gRPC supports) network layer isn't a focus here. So is this about getting events from gRPC and running the proper handlers on one of event loops given from users? or is it about customizing entire network layer to make gRPC run on top of other network system such as libuv or asio?

**Comment by dankegel** [comment] 2020-07-22 21:21
The use case is:
an existing library or app with an event loop that uses libuv or libevent
decides to add grpc support without throwing away all the old code.

A minimal solution would include two samples: one showing how to add grpc support to a simple http server for both libuv and libevent.

**Comment by pyssling** [comment] 2020-07-23 11:41
@veblush this is to avoid having to write our own event dispatching logic. Essentially most of our applications are not just serving gRPC requests, they are either UI applications (with a Qt event loop) or backend applications using for example a boost event loop (boost io_context). Today we solve gRPC integration through threads, gRPC runs on it's own thread - this is workable - but really ugly.

Polling and executing callbacks is pretty much it for us - but for other workloads that I've been involved with earlier it can also be a performance issue. Having to dedicate a whole thread for gRPC is not wanted - other network protocols don't require this - when serving a lot of requests constant context switches on every message become really bad.

In my view the current gRPC implementation is trying to do "too much" in the sense that it provides a whole infrastructure of threading and request handing that most protocol layers don't - normally these are left to things like libuv, libevent or boost asio in the C/C++ world.

**Comment by veblush** [comment] 2020-08-18 17:56
Thanks you @dankegel and @pyssling for the detail. I like to understand more about this.

- @dankegel, Why do you need to throw away the old code if you need to use gRPC? gRPC should be able to work independently.

- @pyssling Can you show me what your custom dispatch code look like? and why do you want to combine two dispatch logics (gRPC and your existing one like boost io_context) into one? Is this about the synchronization? 

- @pyssling If gRPC happens to use libuv, for example, how does help for the case using libevent or boost? Will this have the same problem anyway?

- Is this mainly for server? about request-handling threads? If you're using a gRPC client in a blocking way, is this relevant to this issue?

- Practically it's not feasible to support all popular event libraries so it should be like having a gRPC API which can be overridden by users for their event library. In this case, what API do you expect to use?

**Comment by dankegel** [comment] 2020-08-18 18:45
libwebsockets does support multiple event libraries; see https://libwebsockets.org/git/libwebsockets/tree/lib/event-libs
so there is precedent.

One would have to throw away the old code if grpc forced you to change event libraries.

**Comment by pyssling** [comment] 2020-08-18 22:46
@veblush I'm afraid I can't share that code with you at the moment - it would require a bit too much work to separate it. But the method used is quite simple:

We have a thread that calls m_completionQueue->Next( &tag, &ok ) . Once it receives the tag it will simply pass this tag to another thread that does the processing. I.e. we have a thread here that does quite little other than passing tags to the real event loop.

Our use-cases are purely async - consider a simple application that uses grpc northbound and has a database connection. It would use a boost asio eventloop to asynchronously receive requests. It would then do asynchronous writes to the database - for example using for example https://github.com/yandex/ozo . The thread is then free to process the next grpc request while waiting for the database, or receive a response from the database to a previous query. This sort of thing isn't possible with grpcs native event loop which would force you to work synchronously against the database.

We only use non-blocking (async), both on server and client. This guarantees responsiveness on the client (or avoids using request threads) and on the server it also allows for streaming responses to the client without blocking or using a whole thread.

I understand the complications of supporting multiple event loops - my main concern is actually with supporting boost asio - if things go according to plan on C++23 then boost asio will enter the C++ standard and I'm guessing most other event loops for C++ will slowly die-out. See https://isocpp.org/files/papers/n4771.pdf .

Of course, this may fail to become an ISO standard, but as it seems likely to become so this is what our company is committing to.

**Comment by Piruzzolo** [comment] 2020-11-05 18:06
Any news on this?

**Comment by markdroth** [comment] 2020-11-16 15:47
Closing this as a duplicate of #20194.

**Closed by markdroth** 2020-11-16 15:47 UTC
Labels: area/core, kind/enhancement, lang/core, priority/P2

**Comment by majianwei0705** [comment] 2020-12-23 09:27
IIs there any update about this？
