### ISSUE TITLE
Broken pipe exceptions are not retried (ruby)

### ISSUE THREAD

**Issue by timanovsky** [grpc/grpc#7663] opened 2016-08-08 17:15 UTC
After some testing (pretty low load) on  Heroku platform I've got several occurrences of the following error:

```
Gcloud::InternalError: 13:{"created":"@1470385322.049611107","description":"OS Error","errno":32,"file":"src/core/lib/iomgr/tcp_posix.c","file_line":340,"os_error":"Broken pipe","syscall":"sendmsg"}
```

`Exception.cause` being

```
GRPC::BadStatus: 13:{"created":"@1470385322.049611107","description":"OS Error","errno":32,"file":"src/core/lib/iomgr/tcp_posix.c","file_line":340,"os_error":"Broken pipe","syscall":"sendmsg"}
```

Looks like `EPIPE` error is not handled properly?

**Comment by murgatroid99** [comment] 2016-08-09 01:09
@ctiller Is anything weird going on here?

**Comment by timanovsky** [comment] 2016-08-15 07:48
Also, can `grpc` return more descriptive error codes? Why `BadStatus: 13` (which is `INTERNAL` error code) is returned in case of network problem? According to the doc https://cloud.google.com/datastore/docs/concepts/errors#error_codes `INTERNAL` should not be retried more than once, which is obviously is incorrect in case of network problem. I think semantically `INTERNAL` is server-internal error, and in case of network problems other code should be used

**Comment by timanovsky** [comment] 2016-09-14 16:23
Up. We are continuing to see this exception. Can it be wrapped into `UNAVAILABLE` code rather than `INTERNAL` ?

**Comment by timanovsky** [comment] 2016-09-19 20:12
Similar error `errno=104` (Connection reset by peer) is also reported as internal error rather than `UNAVAILABLE`

```
{"created":"@1474315110.500982132","description":"OS Error","errno":104,"file":"src/core/lib/iomgr/tcp_posix.c","file_line":340,"os_error":"Connection reset by peer","syscall":"sendmsg"} (code[Fixnum]=13) (details[String]="{\"created\":\"@1474315110.500982132\",\"description\":\"OS Error\",\"errno\":104,\"file\":\"src/core/lib/iomgr/tcp_posix.c\",\"file_line\":340,\"os_error\":\"Connection reset by peer\",\"syscall\":\"sendmsg\"}
```

**Comment by apolcyn** [comment] 2016-10-05 16:32
@pbennett could something be wrong/missing with the service running on the go server? From the stack trace, it looks like there is a call on the client that fails due to a status code-14 (server unavailable).

But in general, you can use the same stub across multiple calls, and the stub is thread safe as well. And actually, if it's possible to reuse a stub across multiple calls, then doing so should be encouraged. Grpc is designed to be able to multiplex many calls over a single connection, and reusing the stub across multiple calls takes advantage of this - (you should see much better performance by doing so, if it's relevant for your case).

**Comment by apolcyn** [comment] 2016-10-05 16:43
@pbennett sorry, scratched my comment, as the status code 14 should indicate something happening with the connection to the go server rather than higher up, in the go service.

**Comment by pbennett** [comment] 2016-10-05 17:59
The server is cranking along and continues to serve the same client when restarted with no issues.  It is mostly filling from an in-memory cache so the very simple requests are responded to extremely quickly.  Since the go server spawns off new goroutines for each request and in some of my cases wouldn't be getting more than 6 at a time (at the most) the notion that the server was 'unavailable' makes no sense at all.  Even making it so the client is completely synchronized and just uses a single client (from different threads but they would block themselves on a single mutex) I still run into it.
In many cases, it's getting the error as shown above where it's getting the 14 (nicely buried there. :() as part of just getting the 'return' status of the call.  The call on the server has already run and returned.
It's really odd.  If I have Ruby use no threads at all, then it seems fine.  Are there perhaps known networking/threading issues w/ grpc and ruby 2.0?

**Comment by apolcyn** [comment] 2016-10-05 18:45
@pbennett are you able to share a repro? Or details on the setup? OS, ruby version (2.0?), exact client stub configuration, type of call being made (server side streaming?), perhaps code for how calls are being made from the client? A quick check on ruby 2.0 of making multiple calls across the same ruby client stub, on concurrent threads, seems to work.

**Comment by pbennett** [comment] 2016-10-05 19:18
Windows 10, ruby 2.0p245(as I recall) 32-bit.  Private internal code for client/server.  There is streaming where the server receives streamed args as well as returning streams results.  The calls that fail can also be standard calls with no streaming (but repeating elements).
I'm going to give 2.2.x a whirl and see if it helps any.
(oh, and can I just say how infuriating it is that protobuf_c assumes that libgcc_s_sjlj-1.dll is in the path?)
...
yeah.. it looks like, no.

Here's the .proto:
```
service BuildData {
	rpc GetManifestClient(InitializeData) returns (ClientToken) { }
	rpc GetAll(ClientToken) returns (stream ManifestData) { }
	rpc GetByName(QueryData) returns (stream ManifestData) { }
	rpc GetByNameAndModType(QueryData) returns (stream ManifestData) { }
	rpc SetModule(ModuleUpdate) returns (DummyStatus) {}

	rpc GetDependencyClient(InitializeData) returns (ClientToken) { }
	rpc GetDependency(GetKey) returns (KVPair) { }
	rpc SetDependency(stream SetKV) returns (SetResponse) { }
}

message ClientToken {
    int64 token = 1;
}

message QueryData {
	ClientToken token = 1;
	string name = 2;
	string platform = 3;
	string tool = 4;
	string arch = 5;
	string build = 6;
}

message ManifestData {
    string name = 1;
    string type = 2;
    string platform = 3;
    string tool = 4;
    string arch = 5;
    string build = 6;
    string data = 7;
}

message ModuleUpdate {
	ClientToken token = 1;
	string comp_key = 2;
	string full_name = 3;
	string target_file = 4;
	string name = 5;
	string type = 6;
	string tier = 7;
	string privacy = 8;
	string platform = 9;
	string tool = 10;
	string arch = 11;
	string build = 12;
	string location = 13;
	string wix_uuid = 14;
	string data = 15;
	repeated string uses = 16;
	repeated string transitive_uses = 17;
}

message DummyStatus {
	bool Succeeded = 1;
}

message SetResponse {
}

message InitializeData {
	string tierDir = 1;
}

message GetKey {
	ClientToken token = 1;
	string depGroup = 2;
	string key = 3;
}

message SetKV {
	ClientToken token = 1;
	string depGroup = 2;
	KVPair kvPair = 3;
}

message KVPair {
	string key = 1;
	bytes value = 2;
}
```

**Comment by apolcyn** [comment] 2016-10-06 00:33
Haven't found the cause of this yet, but from the original error message, this is error should be getting generated by the client side native library.

(looks like error is bubbled up from https://github.com/grpc/grpc/blob/master/src/core/lib/iomgr/tcp_windows.c#L171).

cc @ctiller this looks like a transient tcp error, is there a known reason why the client app could cause this?

**Comment by pbennett** [comment] 2016-10-06 02:53
Does grpc see much testing under Windows?  Considering the grpc-tools gem is broken out of the gate for Ruby/Windows I'm leaning towards no?  Ruby code is generally pretty portable but I wonder if there's some networking edge case here.  It kind of seems like everything has actually worked but some piece is coming in after the fact and saying hey, wait, am I done(!?) and throwing an exception even though it was already properly cleaned up.  Saying the server is 'unavailable' is AFAICT definitely not right.

I just need an efficient cross-language rpc mechanism for localhost messaging and for my particular use case I just need that basic pipe.   I *really* just want to focus on the bigger problem at hand which isn't the plumbing.  :\
I tried thrift and it worked properly (I had to work around its client not being thread-safe) but it was significantly slower and also had some issues in its go server code.  So I tried grpc, ran into these issues, tried thrift, ran into its server issues, came back to grpc, spun on various tries of client changes (since its thread-safety rules weren't documented) and finally threw my hands up.
It may come down to writing a simple server and client to show the problem but project wise I've already spent way more time dealing with something that (I thought) should have been a non-issue than I'd like.  

If there's a bunch of people successfully using windows ruby clients w/ grpc (to go servers - maybe ruby<->ruby has some slight differences?) then I can try to see what I'm doing wrong but it sure 'seems' like things are kind of broken here somewhere.

**Comment by apolcyn** [comment] 2016-10-07 22:12
@pbennett are you able to provide context of what's happening on the server. From the error message on posted here, on the client, it should be likely that for some reason, the server end is shutting down the connection.

**Comment by timanovsky** [comment] 2016-10-11 13:28
Hello, I'm recently seeing `RST_STREAM` exceptions which should also probably be classified as Unavailable rather than Internal.
```
Google::cloud::InternalError: 13:{"created":"@1476172369.098617688","description":"RST_STREAM","file":"src/core/ext/transport/chttp2/transport/frame_rst_stream.c","file_line":107,"http2_error":2} -> GRPC::BadStatus: 13:{"created":"@1476172369.098617688","description":"RST_STREAM","file":"src/core/ext/transport/chttp2/transport/frame_rst_stream.c","file_line":107,"http2_error":2} (code[Fixnum]=13) (details[String]="{\"created\":\"@1476172369.098617688\",\"description\":\"RST_STREAM\",\"file\":\"src/core/ext/transport/chttp2/transport/frame_rst_stream.c\",\"file_line\":107,\"http2_error\":2}") (metadata[Hash]={})
```

**Comment by apolcyn** [comment] 2016-10-11 18:45
@timanovsky AFAIK that error should be due to some corruption of the http2 stream, rather than a transient network error. What language is the server, that this error code is sent from?

cc @murgatroid99 a 13 is a grpc-internal error right?

**Comment by timanovsky** [comment] 2016-10-11 18:46
@apolcyn It is google DataStore API v1

**Comment by pbennett** [comment] 2016-10-11 18:50
@apolcyn The server is a pretty simple Go grpc server and it never shuts down, continuing to run fine the entire time.

**Comment by apolcyn** [comment] 2016-10-12 19:14
@pbennett to update on the multi-threaded issue seen on windows ruby, I have not had success in reproducing.
For example, using 64 bit ruby 2.3.1 on windows 7, and a golang (v1.7.1) grpc server on the same machine, tweaking the "route_guide" example to use the same client stub across multiple threads with variations of:
```
Thread.abort_on_exception = true
stub = RouteGuide::Stub.new('localhost:10000', :this_channel_is_insecure)
. . .
th = []
200.times do
  th << Thread.new do
    run_list_features(stub)
  end
end
th.each { |t| t.join }
. . .
```

where `run_list_features` is in the example, looking like:
```
def run_list_features(stub)
  p 'ListFeatures'
  p '------------'
  resps = stub.list_features(LIST_FEATURES_RECT)
  resps.each do |r|
    p "- found '#{r.name}' at #{r.location.inspect}"
  end
end
```

..it seems to work fine. 
Is this at all representative of your usage of the client stub?

**Comment by pbennett** [comment] 2016-10-18 01:48
Using what versions of grpc?  I used only what's been officially released - getting the gem with gem install.  On the go side, probably 1.0.

**Comment by timanovsky** [comment] 2016-10-25 16:54
Guys, any plans to fix this? (so that i/o problems manifest as Unavailable rather than as Internal error)

**Comment by kpayson64** [comment] 2016-12-09 20:34
#8745 Addressed this, and will be included in the next release.

**Closed by kpayson64** 2016-12-09 20:34 UTC
Labels: ruby

**Comment by timanovsky** [comment] 2016-12-10 10:27
@kpayson64 I noticed you now handling `EPIPE`, that's great.
What about `RST_STREAM` ?
https://github.com/grpc/grpc/issues/7663#issuecomment-252916204

**Comment by FX-HAO** [comment] 2016-12-20 07:36
I get the following error on ubuntu container and osx:

    GRPC::BadStatus (14:{"created":"@1480919322.302156000","description":"OS Error","errno":54,"file":"src/core/lib/iomgr/tcp_posix.c","file_line":229,"grpc_status":14,"os_error":"Connection reset by peer","syscall":"recvmsg"})

ENV: Ruby 2.3.1p112, grpc 1.0.1, grpc-tools 1.0.1.

**Comment by kpayson64** [comment] 2016-12-20 18:31
@timanovsky I'm going to open a separate issue ```RST_STREAM```,  but I believe that issue may be harder to address. #9177

@FX-HAO Same with the issue you have reported.
#9179
