### ISSUE TITLE
gem install grpc:1.45.0  takes lot of time to complete

### ISSUE THREAD

**Issue by equivalent** [grpc/grpc#29489] opened 2022-04-25 12:11 UTC
### What version of gRPC and what language are you using?

Ruby 3.1.1 

`gem install grpc:1.45.0`

### What operating system (Linux, Windows,...) and version?

* M1 osx (no issue - all fine)
* AWS hosted Ubuntu 20.04 VM with 4GB Ram & SSD. => takes lot of time to finish install
* Docker image `FROM 3.1.1`  => takes lot of time to finish gem install

### What runtime / compiler are you using (e.g. python version or version of gcc)

MRI Ruby 3.1.1 

### What did you do?

we are using gem `google-cloud-web_risk` which depends on grpc gem. Now when we install `gem install grpc:1.45.0` in m1 macbook air it takes 2-3 minutes but finished reasonably soon.

When we try to run `gem install grpc:1.45.0` on Ubuntu VM (described above) it takes 5-10 minutes to finish 

But worst of all if we try to build Docker image (which we need to in order to deploy to prod) the `gem install grpc:1.45.0`  (alone) takes like 5-10 minutes,

```
FROM ruby:3.1.1
RUN gem install grpc:1.45.0 
```

...  and if the gem is defined as a part of a `Gemfile` for `bundle install` it takes even more time (like 20 )

### What did you expect to see?

Ideally this should be less time, or if you can pls provide some guide how to make this installation faster (e.g. how to precompile some core dependancy before the gem installed)

**Comment by equivalent** [comment] 2022-04-25 12:17
in our Docker build we kind of speed it up by doing : 

```
FROM ruby:3.1.1

# ...

RUN gem install grpc:1.45.0 # <<<< this is the trick
RUN gem install bundler:2.3.12 # optional

# Preinstall majority of gems
WORKDIR /tmp
ADD ./Gemfile Gemfile
ADD ./Gemfile.lock Gemfile.lock
RUN  bundle install  

ADD . /app
WORKDIR /app
RUN   bundle install  
 
# ...
CMD bin/rails s # not important
```

....so this will cache up the layer of grpc gem install for next docker build BUT doesn't solve the core issue that it takes a lot of time on fresh docker build

**Comment by asabourin** [comment] 2022-04-28 06:41
We're also experiencing the same issue, with `bundle` now taking more than 30 minutes to complete in Linux-based CI containers after upgrading from grpc 1.41 to 1.45 following upgrade of Ruby 3 to 3.1 (so not sure exactly whether ruby or grpc is the cause)

Inspecting the resulting container image we found the newer ones includes more than 1GB worth of source files in the installed gem folders (including a 567MB libgrpc.a), which doesn't seem right:
grpc_1 41_ruby_3 0:
<img width="650" alt="grpc_1 41_ruby_3 0" src="https://user-images.githubusercontent.com/192362/165692376-1bb2a891-4a90-4004-9396-e99df792c688.png">
grpc_1 45_ruby_3 1:
<img width="811" alt="grpc_1 45_ruby_3 1" src="https://user-images.githubusercontent.com/192362/165692359-38c47891-f103-4625-a1a6-628c6220bfc7.png">

**Comment by nrowegt** [comment] 2022-04-29 01:56
I ran into this today as well. Ruby 3.1.2, grpc 1.45.0. The issue of a long install is also present on the following versions:
`1.43.1`
`1.42.0`

This is with a local build, intel MBP 2019. I didn't try any versions prior to 1.42.0. Each time I killed it at 5 minutes in, I didn't wait to see how long the final build took.

**Comment by bipashant** [comment] 2022-05-09 01:58
took around 30 mins to get completed  🤷

**Comment by mroach** [comment] 2022-05-09 08:49
The `metadata` for the binary gem is disallowing Ruby 3.1. I suspect this causes bundler to ignore the binary gem and go for installation from source. Is there any reason gRPC can't be built for Ruby 3.1? I don't see an open issue referencing Ruby 3.1 build problems.

```yaml
 required_ruby_version: !ruby/object:Gem::Requirement
   requirements:
   - - ">="
     - !ruby/object:Gem::Version
       version: '2.5'
   - - "<"
     - !ruby/object:Gem::Version
       version: 3.1.dev
```

**Comment by mroach** [comment] 2022-05-11 13:27
This is listed as fixed in version 1.46.0 thanks to https://github.com/grpc/grpc/pull/29000

Now we just have to wait for that version to appear on rubygems.org

**Comment by haines** [comment] 2022-05-13 10:45
v1.46.2 is now on RubyGems with the fix 🎉

**Comment by fameoflight** [comment] 2022-06-29 00:39
This is still happening with 1.46.3

**Comment by skatkov** [comment] 2022-08-02 10:57
Running ruby 2.7 and grpc 1.46.3 -- takes 23 minutes on gitlab ci to install.

**Comment by ceritium** [comment] 2022-09-25 09:35
Hi, if you still have the problem, try adding the  `x86_64-linux` platform with `bundle lock --add-platform x86_64-linux`

**Comment by HegdeRama** [comment] 2022-09-28 08:01
Facing the same issue with  version: `1.49.1` as well, its been more than 60 mins, still its downloading.

**Comment by manu-crealytics** [comment] 2023-02-06 15:41
And once more. This time trying to install from Ruby 3.2.0 the latest `grpc` version available from RubyGems: 1.51.0. That one is still not precompiled for Ruby 3.2.0, only until Ruby 3.1.0.

Version 1.52.0 is precompiled for Ruby 3.2.0. But, unfortunately, it hasn't been published to RubyGems yet, even if it has already been tagged a few days ago. Hopefully it will be published soon. Until then, I'm using 1.52.0.pre2.

**Comment by rwojsznis** [comment] 2023-02-20 10:06
In case anyone comes here from _the search_ - also having similar problem:

<img width="288" alt="Screenshot 2023-02-20 at 11 04 27" src="https://user-images.githubusercontent.com/1527612/220074581-19d40e2b-c430-46ae-94f8-bd0f99209334.png">

`ruby 3.1.3p185`

I didn't investigated this further yet; might be related to the fact I'm using `aarch64` architecture 🤔

**Comment by dcrec1** [comment] 2023-04-30 07:13
I can confirm that this only happens in with `aarch64`, changed the platform to `amd64` and now Bundler is finishing very fast.

**Closed** 2023-06-25 20:00 UTC
Labels: kind/bug, lang/ruby, priority/P2

**Comment by santostiago** [comment] 2024-04-05 16:09
Installing the ruby gem with the version `1.62.0` on a 2020 MBP with an Intel processor: it's been 2' minutes, the processors are all maxed out, the fans are working over the clock, and it keeps spawning new processes.
It's been over 20 minutes and it's not yet finished.

**Comment by heyvito** [comment] 2024-08-16 11:04
Same on Apple's M-series, even using `linux/amd64` as the container platform.

**Comment by BooVeMan** [comment] 2025-01-07 13:16
Same on intel MBP for `1.68.1`, 15 minutes

**Comment by RoamingNoMaD** [comment] 2025-12-09 09:23
Same on Intel, Fedora Linux 42, it takes more than 20m with other deps in CI as well...
