### ISSUE TITLE
tests.cloud_to_cloud:ruby:c++_server:empty_unary flaked

### ISSUE THREAD

**Issue by adelez** [grpc/grpc#12064] opened 2017-08-03 19:17 UTC
https://grpc-testing.appspot.com/job/gRPC_interop_pull_requests/15871/testReport/junit/(root)/tests/cloud_to_cloud_ruby_c___server_empty_unary/

Stacktrace

ies/ruby-2.1.10/lib/ruby/2.1.0/x86_64-linux/date_core.so
7fa332b4e000-7fa332b50000 rw-p 00033000 00:7a 414                        /usr/local/rvm/rubies/ruby-2.1.10/lib/ruby/2.1.0/x86_64-linux/date_core.so
7fa332b50000-7fa332b51000 rw-p 00000000 00:00 0 
7fa332b51000-7fa332b57000 r-xp 00000000 00:7a 389                        /usr/local/rvm/rubies/ruby-2.1.10/lib/ruby/2.1.0/x86_64-linux/strscan.so
7fa332b57000-7fa332d57000 ---p 00006000 00:7a 389                        /usr/local/rvm/rubies/ruby-2.1.10/lib/ruby/2.1.0/x86_64-linux/strscan.so
7fa332d57000-7fa332d58000 rw-p 00006000 00:7a 389                        /usr/local/rvm/rubies/ruby-2.1.10/lib/ruby/2.1.0/x86_64-linux/strscan.so
7fa332d58000-7fa332d76000 r-xp 00000000 00:7a 378                        /usr/lib/x86_64-linux-gnu/libyaml-0.so.2.0.4
7fa332d76000-7fa332f75000 ---p 0001e000 00:7a 378                        /usr/lib/x86_64-linux-gnu/libyaml-0.so.2.0.4
7fa332f75000-7fa332f76000 r--p 0001d000 00:7a 378                        /usr/lib/x86_64-linux-gnu/libyaml-0.so.2.0.4
7fa332f76000-7fa332f77000 rw-p 0001e000 00:7a 378                        /usr/lib/x86_64-linux-gnu/libyaml-0.so.2.0.4
7fa332f77000-7fa332f7d000 r-xp 00000000 00:7a 376                        /usr/local/rvm/rubies/ruby-2.1.10/lib/ruby/2.1.0/x86_64-linux/psych.so
7fa332f7d000-7fa33317c000 ---p 00006000 00:7a 376                        /usr/local/rvm/rubies/ruby-2.1.10/lib/ruby/2.1.0/x86_64-linux/psych.so
7fa33317c000-7fa33317d000 rw-p 00005000 00:7a 376                        /usr/local/rvm/rubies/ruby-2.1.10/lib/ruby/2.1.0/x86_64-linux/psych.so
7fa33317d000-7fa333390000 r-xp 00000000 00:7a 241                        /var/local/git/grpc/src/ruby/lib/grpc/grpc_c.so
7fa333390000-7fa333590000 ---p 00213000 00:7a 241                        /var/local/git/grpc/src/ruby/lib/grpc/grpc_c.so
7fa333590000-7fa3335ab000 rw-p 00213000 00:7a 241                        /var/local/git/grpc/src/ruby/lib/grpc/grpc_c.so
7fa3335ab000-7fa3335b1000 rw-p 00000000 00:00 0 
7fa3335b1000-7fa3335b9000 r-xp 00000000 00:7a 210                        /usr/local/rvm/rubies/ruby-2.1.10/lib/ruby/2.1.0/x86_64-linux/stringio.so
7fa3335b9000-7fa3337b8000 ---p 00008000 00:7a 210                        /usr/local/rvm/rubies/ruby-2.1.10/lib/ruby/2.1.0/x86_64-linux/stringio.so
7fa3337b8000-7fa3337b9000 rw-p 00007000 00:7a 210                        /usr/local/rvm/rubies/ruby-2.1.10/lib/ruby/2.1.0/x86_64-linux/stringio.so
7fa3337b9000-7fa3337bc000 r-xp 00000000 00:7a 196                        /usr/local/rvm/rubies/ruby-2.1.10/lib/ruby/2.1.0/x86_64-linux/thread.so
7fa3337bc000-7fa3339bc000 ---p 00003000 00:7a 196                        /usr/local/rvm/rubies/ruby-2.1.10/lib/ruby/2.1.0/x86_64-linux/thread.so
7fa3339bc000-7fa3339bd000 rw-p 00003000 00:7a 196                        /usr/local/rvm/rubies/ruby-2.1.10/lib/ruby/2.1.0/x86_64-linux/thread.so
7fa3339bd000-7fa3339bf000 r-xp 00000000 00:7a 193                        /usr/local/rvm/rubies/ruby-2.1.10/lib/ruby/2.1.0/x86_64-linux/enc/trans/transdb.so
7fa3339bf000-7fa333bbf000 ---p 00002000 00:7a 193                        /usr/local/rvm/rubies/ruby-2.1.10/lib/ruby/2.1.0/x86_64-linux/enc/trans/transdb.so
7fa333bbf000-7fa333bc0000 rw-p 00002000 00:7a 193                        /usr/local/rvm/rubies/ruby-2.1.10/lib/ruby/2.1.0/x86_64-linux/enc/trans/transdb.so
7fa333bc0000-7fa333bc2000 r-xp 00000000 00:7a 191                        /usr/local/rvm/rubies/ruby-2.1.10/lib/ruby/2.1.0/x86_64-linux/enc/encdb.so
7fa333bc2000-7fa333dc1000 ---p 00002000 00:7a 191                        /usr/local/rvm/rubies/ruby-2.1.10/lib/ruby/2.1.0/x86_64-linux/enc/encdb.so
7fa333dc1000-7fa333dc2000 rw-p 00001000 00:7a 191                        /usr/local/rvm/rubies/ruby-2.1.10/lib/ruby/2.1.0/x86_64-linux/enc/encdb.so
7fa333dc2000-7fa333f63000 r-xp 00000000 00:7a 46                         /lib/x86_64-linux-gnu/libc-2.19.so
7fa333f63000-7fa334163000 ---p 001a1000 00:7a 46                         /lib/x86_64-linux-gnu/libc-2.19.so
7fa334163000-7fa334167000 r--p 001a1000 00:7a 46                         /lib/x86_64-linux-gnu/libc-2.19.so
7fa334167000-7fa334169000 rw-p 001a5000 00:7a 46                         /lib/x86_64-linux-gnu/libc-2.19.so
7fa334169000-7fa33416d000 rw-p 00000000 00:00 0 
7fa33416d000-7fa33426d000 r-xp 00000000 00:7a 114                        /lib/x86_64-linux-gnu/libm-2.19.so
7fa33426d000-7fa33446c000 ---p 00100000 00:7a 114                        /lib/x86_64-linux-gnu/libm-2.19.so
7fa33446c000-7fa33446d000 r--p 000ff000 00:7a 114                        /lib/x86_64-linux-gnu/libm-2.19.so
7fa33446d000-7fa33446e000 rw-p 00100000 00:7a 114                        /lib/x86_64-linux-gnu/libm-2.19.so
7fa33446e000-7fa334476000 r-xp 00000000 00:7a 181                        /lib/x86_64-linux-gnu/libcrypt-2.19.so
7fa334476000-7fa334675000 ---p 00008000 00:7a 181                        /lib/x86_64-linux-gnu/libcrypt-2.19.so
7fa334675000-7fa334676000 r--p 00007000 00:7a 181                        /lib/x86_64-linux-gnu/libcrypt-2.19.so
7fa334676000-7fa334677000 rw-p 00008000 00:7a 181                        /lib/x86_64-linux-gnu/libcrypt-2.19.so
7fa334677000-7fa3346a5000 rw-p 00000000 00:00 0 
7fa3346a5000-7fa3346a8000 r-xp 00000000 00:7a 44                         /lib/x86_64-linux-gnu/libdl-2.19.so
7fa3346a8000-7fa3348a7000 ---p 00003000 00:7a 44                         /lib/x86_64-linux-gnu/libdl-2.19.so
7fa3348a7000-7fa3348a8000 r--p 00002000 00:7a 44                         /lib/x86_64-linux-gnu/libdl-2.19.so
7fa3348a8000-7fa3348a9000 rw-p 00003000 00:7a 44                         /lib/x86_64-linux-gnu/libdl-2.19.so
7fa3348a9000-7fa33492a000 r-xp 00000000 00:7a 112                        /usr/lib/x86_64-linux-gnu/libgmp.so.10.2.0
7fa33492a000-7fa334b2a000 ---p 00081000 00:7a 112                        /usr/lib/x86_64-linux-gnu/libgmp.so.10.2.0
7fa334b2a000-7fa334b2b000 r--p 00081000 00:7a 112                        /usr/lib/x86_64-linux-gnu/libgmp.so.10.2.0
7fa334b2b000-7fa334b2c000 rw-p 00082000 00:7a 112                        /usr/lib/x86_64-linux-gnu/libgmp.so.10.2.0
7fa334b2c000-7fa334b44000 r-xp 00000000 00:7a 74                         /lib/x86_64-linux-gnu/libpthread-2.19.so
7fa334b44000-7fa334d43000 ---p 00018000 00:7a 74                         /lib/x86_64-linux-gnu/libpthread-2.19.so
7fa334d43000-7fa334d44000 r--p 00017000 00:7a 74                         /lib/x86_64-linux-gnu/libpthread-2.19.so
7fa334d44000-7fa334d45000 rw-p 00018000 00:7a 74                         /lib/x86_64-linux-gnu/libpthread-2.19.so
7fa334d45000-7fa334d49000 rw-p 00000000 00:00 0 
7fa334d49000-7fa334ff3000 r-xp 00000000 00:7a 179                        /usr/local/rvm/rubies/ruby-2.1.10/lib/libruby.so.2.1.0
7fa334ff3000-7fa3351f3000 ---p 002aa000 00:7a 179                        /usr/local/rvm/rubies/ruby-2.1.10/lib/libruby.so.2.1.0
7fa3351f3000-7fa3351fc000 rw-p 002aa000 00:7a 179                        /usr/local/rvm/rubies/ruby-2.1.10/lib/libruby.so.2.1.0
7fa3351fc000-7fa335221000 rw-p 00000000 00:00 0 
7fa335221000-7fa335241000 r-xp 00000000 00:7a 37                         /lib/x86_64-linux-gnu/ld-2.19.so
7fa3352e9000-7fa335438000 rw-p 00000000 00:00 0 
7fa33543a000-7fa33543b000 rw-p 00000000 00:00 0 
7fa33543b000-7fa33543c000 ---p 00000000 00:00 0 
7fa33543c000-7fa335441000 rw-p 00000000 00:00 0 
7fa335441000-7fa335442000 r--p 00020000 00:7a 37                         /lib/x86_64-linux-gnu/ld-2.19.so
7fa335442000-7fa335443000 rw-p 00021000 00:7a 37                         /lib/x86_64-linux-gnu/ld-2.19.so
7fa335443000-7fa335444000 rw-p 00000000 00:00 0 
7ffdf783c000-7ffdf803b000 rw-p 00000000 00:00 0                          [stack]
7ffdf81c8000-7ffdf81ca000 r--p 00000000 00:00 0                          [vvar]
7ffdf81ca000-7ffdf81cc000 r-xp 00000000 00:00 0                          [vdso]
ffffffffff600000-ffffffffff601000 r-xp 00000000 00:00 0                  [vsyscall]

**Comment by apolcyn** [comment] 2017-08-03 19:34
looking into the top of the stack trace:

```
017-08-03 18:52:26,686 START: cloud_to_cloud:ruby:c++_server:client_compressed_streaming
2017-08-03 18:52:26,690 /var/local/git/grpc/src/ruby/pb/src/proto/grpc/testing/messages_pb.rb:33: [BUG] Segmentation fault at 0x0000000a614000
ruby 2.1.10p492 (2016-04-01 revision 54464) [x86_64-linux]

-- Control frame information -----------------------------------------------
c:0008 p:---- s:0024 e:000023 CFUNC  :add_message
c:0007 p:0049 s:0020 E:0012e8 BLOCK  /var/local/git/grpc/src/ruby/pb/src/proto/grpc/testing/messages_pb.rb:33 [FINISH]
c:0006 p:---- s:0018 e:000017 CFUNC  :instance_eval
c:0005 p:---- s:0016 e:000015 CFUNC  :build
c:0004 p:0025 s:0013 E:001d08 TOP    /var/local/git/grpc/src/ruby/pb/src/proto/grpc/testing/messages_pb.rb:6 [FINISH]
c:0003 p:---- s:0011 e:000010 CFUNC  :require_relative
c:0002 p:0163 s:0007 E:000310 EVAL   src/ruby/pb/test/client.rb:41 [FINISH]
c:0001 p:0000 s:0002 E:0020a8 TOP    [FINISH]

-- Ruby level backtrace information ----------------------------------------
src/ruby/pb/test/client.rb:41:in `<main>'
src/ruby/pb/test/client.rb:41:in `require_relative'
/var/local/git/grpc/src/ruby/pb/src/proto/grpc/testing/messages_pb.rb:6:in `<top (required)>'
/var/local/git/grpc/src/ruby/pb/src/proto/grpc/testing/messages_pb.rb:6:in `build'
/var/local/git/grpc/src/ruby/pb/src/proto/grpc/testing/messages_pb.rb:6:in `instance_eval'
/var/local/git/grpc/src/ruby/pb/src/proto/grpc/testing/messages_pb.rb:33:in `block in <top (required)>'
/var/local/git/grpc/src/ruby/pb/src/proto/grpc/testing/messages_pb.rb:33:in `add_message'

-- C level backtrace information -------------------------------------------
/usr/local/rvm/rubies/ruby-2.1.10/lib/libruby.so.2.1(+0x1dc8cc) [0x7fa334f258cc] vm_dump.c:690
/usr/local/rvm/rubies/ruby-2.1.10/lib/libruby.so.2.1(+0x77ad3) [0x7fa334dc0ad3] strops.c:307
/usr/local/rvm/rubies/ruby-2.1.10/lib/libruby.so.2.1(rb_bug+0xb3) [0x7fa334dc1733] malloc.c:5168
/usr/local/rvm/rubies/ruby-2.1.10/lib/libruby.so.2.1(+0x156333) [0x7fa334e9f333] signal.c:824
/lib/x86_64-linux-gnu/libpthread.so.0(+0xf890) [0x7fa334b3b890] ../nptl/sysdeps/pthread/funlockfile.c:29
/usr/local/rvm/rubies/ruby-2.1.10/lib/libruby.so.2.1(rb_gc_mark+0x58) [0x7fa334de6898] wmemset.c:44
/usr/local/rvm/rubies/ruby-2.1.10/lib/libruby.so.2.1(+0x9b906) [0x7fa334de4906] ../sysdeps/x86_64/multiarch/../cacheinfo.c:277
/usr/local/rvm/rubies/ruby-2.1.10/lib/libruby.so.2.1(+0x9dec2) [0x7fa334de6ec2] mbrtowc.c:119
/usr/local/rvm/rubies/ruby-2.1.10/lib/libruby.so.2.1(+0xa01e3) [0x7fa334de91e3] ../stdlib/strtod_l.c:774
/usr/local/rvm/rubies/ruby-2.1.10/lib/libruby.so.2.1(+0xa1011) [0x7fa334dea011] ../stdlib/strtod_l.c:1632
/usr/local/rvm/gems/ruby-2.1.10/gems/google-protobuf-3.3.0-x86_64-linux/lib/google/2.1/protobuf_c.so(Descriptor_alloc+0x7c) [0x7fa33161053c]
/usr/local/rvm/rubies/ruby-2.1.10/lib/libruby.so.2.1(rb_obj_alloc+0x3e) [0x7fa334e2e01e] efgcvt.c:106
/usr/local/rvm/rubies/ruby-2.1.10/lib/libruby.so.2.1(rb_class_new_instance+0x11) [0x7fa334e2e471] efgcvt_r.c:235
/usr/local/rvm/gems/ruby-2.1.10/gems/google-protobuf-3.3.0-x86_64-linux/lib/google/2.1/protobuf_c.so(Builder_add_message+0x32) [0x7fa331613d12]
/usr/local/rvm/rubies/ruby-2.1.10/lib/libruby.so.2.1(+0x1d5952) [0x7fa334f1e952] vm_insnhelper.c:1510
/usr/local/rvm/rubies/ruby-2.1.10/lib/libruby.so.2.1(+0x1cace8) [0x7fa334f13ce8] insns.def:996
/usr/local/rvm/rubies/ruby-2.1.10/lib/libruby.so.2.1(+0x1cf558) [0x7fa334f18558] vm.c:1427
/usr/local/rvm/rubies/ruby-2.1.10/lib/libruby.so.2.1(+0x1d3d41) [0x7fa334f1cd41] vm.c:817
/usr/local/rvm/rubies/ruby-2.1.10/lib/libruby.so.2.1(rb_obj_instance_eval+0x21f) [0x7fa334f1e0bf] vm.c:848
/usr/local/rvm/rubies/ruby-2.1.10/lib/libruby.so.2.1(+0x1d0b7a) [0x7fa334f19b7a] vm_eval.c:118
/usr/local/rvm/rubies/ruby-2.1.10/lib/libruby.so.2.1(+0x1d1fd7) [0x7fa334f1afd7] vm_eval.c:50
/usr/local/rvm/gems/ruby-2.1.10/gems/google-protobuf-3.3.0-x86_64-linux/lib/google/2.1/protobuf_c.so(DescriptorPool_build+0x44) [0x7fa331610254]
/usr/local/rvm/rubies/ruby-2.1.10/lib/libruby.so.2.1(+0x1d5952) [0x7fa334f1e952] vm_insnhelper.c:1510
/usr/local/rvm/rubies/ruby-2.1.10/lib/libruby.so.2.1(+0x1cace8) [0x7fa334f13ce8] insns.def:996
/usr/local/rvm/rubies/ruby-2.1.10/lib/libruby.so.2.1(+0x1cf558) [0x7fa334f18558] vm.c:1427
/usr/local/rvm/rubies/ruby-2.1.10/lib/libruby.so.2.1(rb_iseq_eval+0x1b8) [0x7fa334f20568] vm.c:1653
/usr/local/rvm/rubies/ruby-2.1.10/lib/libruby.so.2.1(+0x8388e) [0x7fa334dcc88e] ../sysdeps/x86_64/multiarch/../strcmp.S:2240
/usr/local/rvm/rubies/ruby-2.1.10/lib/libruby.so.2.1(rb_require_safe+0x63e) [0x7fa334dce21e] ../sysdeps/x86_64/multiarch/../memcmp.S:208
/usr/local/rvm/rubies/ruby-2.1.10/lib/libruby.so.2.1(+0x1d5952) [0x7fa334f1e952] vm_insnhelper.c:1510
/usr/local/rvm/rubies/ruby-2.1.10/lib/libruby.so.2.1(+0x1cad85) [0x7fa334f13d85] insns.def:1025
/usr/local/rvm/rubies/ruby-2.1.10/lib/libruby.so.2.1(+0x1cf558) [0x7fa334f18558] vm.c:1427
/usr/local/rvm/rubies/ruby-2.1.10/lib/libruby.so.2.1(rb_iseq_eval_main+0x212) [0x7fa334f207e2] vm.c:1666
/usr/local/rvm/rubies/ruby-2.1.10/lib/libruby.so.2.1(+0x7ddaf) [0x7fa334dc6daf] malloc.c:4675
/usr/local/rvm/rubies/ruby-2.1.10/lib/libruby.so.2.1(ruby_exec_node+0x1d) [0x7fa334dc8f1d] ../sysdeps/x86_64/multiarch/../strcat.S:211
/usr/local/rvm/rubies/ruby-2.1.10/lib/libruby.so.2.1(ruby_run_node+0x1e) [0x7fa334dcb65e] ../sysdeps/x86_64/multiarch/../strcmp.S:716
ruby() [0x40089b]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf5) [0x7fa333de3b45] libc-start.c:287
ruby() [0x4008c9]

-- Other runtime information -----------------------------------------------

* Loaded script: src/ruby/pb/test/client.rb

```

from stack trace this looks like a dupe of https://github.com/grpc/grpc/issues/12042

**Closed by apolcyn** 2017-08-03 19:34 UTC
