### ISSUE TITLE
RA-TLS cert verification call back 

### ISSUE THREAD

**Issue by lili8808** [grpc/grpc#32198] opened 2023-01-25 13:00 UTC
I am Using RA-TLS certificate and private key in my gRPC server.py as you know with RA-TLS, there is no certificate chain anymore.There is only a self-signed certificate that the server generates on the fly (using a special RA-TLS function) and that the client verifies (using a special RA-TLS-specific callback). In other words, RA-TLS throws away the whole classic PKI infrastructure, with root CAs and cert chains.
I have  to find a function in gRPC that allows me to install my own verification callback. In OpenSSL, for example, this function is called SSL_CTX_set_cert_verify_callback(). In mbedTLS, for another example, this function is called mbedtls_ssl_conf_verify().
I read the documents and all needed root certificate or CA, is there any function in gRPC to have this verify_callback to verify RA-TLS certificate in client side?

**Comment by gnossen** [comment] 2023-04-05 16:44
This functionality does not currently exist. There is an issue open tracking the work of adding this. Closing this issue as a duplicate of https://github.com/grpc/grpc/issues/32635

**Closed by gnossen** 2023-04-05 16:44 UTC
Labels: kind/enhancement, lang/Python, priority/P2
