### ISSUE TITLE
Python unit.beta._not_found_test.NotFoundTest.test_future_stream_unary_not_found test is flaky

### ISSUE THREAD

**Issue by jtattermusch** [grpc/grpc#9309] opened 2017-01-11 12:22 UTC
https://grpc-testing.appspot.com/job/gRPC_pull_requests_linux/1799/testReport/junit/(root)/python_linux_opt/py27_test_unit_beta__not_found_test_NotFoundTest/

```
[0mRunning       unit.beta._not_found_test.NotFoundTest.test_future_stream_unary_not_found
[91mERROR         unit.beta._not_found_test.NotFoundTest.test_future_stream_unary_not_found
[0m2 tests finished:
	1 successful
	1 unsuccessful
	0 skipped
	0 expected failures
	0 unexpected successes
Interrupted Tests:
	[]

Errors/Failures: 
[91munit.beta._not_found_test.NotFoundTest.test_future_stream_unary_not_found[0m
[1mtraceback:[0m
Traceback (most recent call last):
  File "/usr/lib/python2.7/unittest/case.py", line 329, in run
    testMethod()
  File "/var/local/git/grpc/src/python/grpcio_tests/tests/unit/beta/_not_found_test.py", line 66, in test_future_stream_unary_not_found
    rpc_future.result()
  File "/var/local/git/grpc/py27/local/lib/python2.7/site-packages/grpc/beta/_client_adaptations.py", line 111, in result
    raise _abortion_error(rpc_error_call)
RemoteError: RemoteError(code=StatusCode.UNKNOWN, details="Exception iterating requests!")

[1mstdout:[0m

[1mstderr:[0m
ERROR:root:Exception iterating requests!
Traceback (most recent call last):
  File "/var/local/git/grpc/py27/local/lib/python2.7/site-packages/grpc/_channel.py", line 203, in consume_request_iterator
    request = next(request_iterator)
TypeError: list object is not an iterator


Unexpected successes: []
Test failure
```

**Comment by jtattermusch** [comment] 2017-01-13 07:21
Seen again: https://grpc-testing.appspot.com/job/gRPC_pull_requests_macos/1817/

**Comment by soltanmm-google** [comment] 2017-01-20 04:33
@nathanielmanistaatgoogle I'm still seeing this at master head:

```
Testing gRPC Python...
SUCCESS       unit.beta._not_found_test.NotFoundTest.test_blocking_unary_unary_not_found
Running       unit.beta._not_found_test.NotFoundTest.test_future_stream_unary_not_found
ERROR         unit.beta._not_found_test.NotFoundTest.test_future_stream_unary_not_found
2 tests finished:
	1 successful
	1 unsuccessful
	0 skipped
	0 expected failures
	0 unexpected successes
Interrupted Tests:
	[]

Errors/Failures: 
unit.beta._not_found_test.NotFoundTest.test_future_stream_unary_not_found
traceback:
Traceback (most recent call last):
  File "/usr/local/google/home/atash/src/grpc-2/py34/lib/python3.4/site-packages/grpc/beta/_client_adaptations.py", line 109, in result
    return self._future.result(timeout=timeout)
  File "/usr/local/google/home/atash/src/grpc-2/py34/lib/python3.4/site-packages/grpc/_channel.py", line 298, in result
    raise self
grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with (StatusCode.UNKNOWN, Exception iterating requests!)>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.4/unittest/case.py", line 58, in testPartExecutor
    yield
  File "/usr/lib/python3.4/unittest/case.py", line 577, in run
    testMethod()
  File "/usr/local/google/home/atash/src/grpc-2/src/python/grpcio_tests/tests/unit/beta/_not_found_test.py", line 66, in test_future_stream_unary_not_found
    rpc_future.result()
  File "/usr/local/google/home/atash/src/grpc-2/py34/lib/python3.4/site-packages/grpc/beta/_client_adaptations.py", line 111, in result
    raise _abortion_error(rpc_error_call)
grpc.framework.interfaces.face.face.RemoteError: RemoteError(code=StatusCode.UNKNOWN, details="Exception iterating requests!")

stdout:

stderr:
ERROR:root:Exception iterating requests!
Traceback (most recent call last):
  File "/usr/local/google/home/atash/src/grpc-2/py34/lib/python3.4/site-packages/grpc/_channel.py", line 203, in consume_request_iterator
    request = next(request_iterator)
TypeError: 'list' object is not an iterator


Unexpected successes: []
Test failure
FAILED: py34.test.unit.beta._not_found_test.NotFoundTest [ret=1, pid=19568]
FAILED: py34.test.unit.beta._not_found_test.NotFoundTest
```

**Comment by nathanielmanistaatgoogle** [comment] 2017-01-20 05:52
Bummer. I'll take another look.

**Comment by nathanielmanistaatgoogle** [comment] 2017-01-20 20:15
@soltanmm-google: at bd827887ffbb57a95990130f585913b13f44a5b7 this passed for me with `./tools/run_tests/run_tests.py --language=python --newline_on_success --regex=_not_found_test --runs_per_test=1000 --jobs=200`. Would you happen to have a means of reproducing a failure?

**Comment by nathanielmanistaatgoogle** [comment] 2017-02-08 23:12
Closing as this has not been confirmed to have been seen since the integration of [pull request 9310](https://github.com/grpc/grpc/pull/9310) which was authored to fix it.

**Closed by nathanielmanistaatgoogle** 2017-02-08 23:12 UTC
Labels: BUILDPONY, P1, python
