### ISSUE TITLE
Calling `grpc_extra_deps` twice in `WORKSPACE` fails.

### ISSUE THREAD

**Issue by p3achyjr** [grpc/grpc#32755] opened 2023-03-30 03:50 UTC
I have a project that pulls in tensorflow and google cloud as dependencies. Both of these dependencies call `grpc_extra_deps` at some point during their setup, which leads to the error 

```
go_register_toolchains: version set after go sdk rule declared (go_sdk)
```

Any options here? I've tried adding a call to `go_download_sdk` to the top of the WORKSPACE file to no avail. Since `grpc_extra_deps` forces the version to `1.18`, the go bazel rules believe that we are importing two different versions of go.

**Comment by veblush** [comment] 2023-04-11 19:44
I think this might be a duplicate of https://github.com/grpc/grpc/issues/32755. We're going to add an option to specify the  Golang version. If two deps pull in the same Golang, would it be enough for your problem?

**Comment by p3achyjr** [comment] 2023-04-11 23:11
Yes! That would work.

**Closed** 2023-06-20 19:40 UTC
Labels: kind/bug, lang/core, priority/P2, area/build
