### ISSUE TITLE
TIMEOUT: bm_fullstack_streaming_pump --benchmark_filter=BM_PumpStreamServerToClient<SockPair>/0$ GRPC_POLL_STRATEGY=epollex

### ISSUE THREAD

**Issue by markdroth** [grpc/grpc#13643] opened 2017-12-05 18:59 UTC
Seen in both opt and tsan:

https://sponge.corp.google.com/target?id=2372b9c4-4c3f-4ba9-9d94-389671761c24&target=github/grpc/c%2B%2B_linux_opt_native&searchFor=&show=ALL&sortBy=STATUS

```
Timeout
D1204 23:07:10.698270001   19773 ev_posix.cc:128]            Using polling engine: epollex
D1204 23:07:10.698363273   19773 dns_resolver.cc:307]        Using native dns resolver
Run on (32 X 2600 MHz CPU s)
2017-12-04 23:07:10
```

https://sponge.corp.google.com/target?id=dda1e6e2-34cf-4423-9b56-ef2af0827374&target=github/grpc/c%2B%2B_linux_tsan_native&searchFor=&show=ALL&sortBy=STATUS

```
Timeout
D1204 23:11:47.845452857    6874 ev_posix.cc:128]            Using polling engine: epollex
D1204 23:11:47.847424473    6874 dns_resolver.cc:307]        Using native dns resolver
Run on (32 X 2300 MHz CPU s)
2017-12-04 23:11:47
***WARNING*** Library was built as DEBUG. Timings may be affected.
```

**Comment by dgquintas** [comment] 2017-12-08 23:17
duplicate of #13429

**Closed by dgquintas** 2017-12-08 23:17 UTC
Labels: infra/BUILDPONY
