### ISSUE TITLE
Swift examples do not build

### ISSUE THREAD

**Issue by rsln-s** [grpc/grpc#6714] opened 2016-05-25 17:56 UTC
After following installation instructions from [here](https://github.com/grpc/grpc/tree/master/src/objective-c) (using `$ curl -fsSL https://goo.gl/getgrpc | bash -`), all of the swift examples fail to `pod install` with "missing required attribute":

![2016-05-22 15 20 49](https://cloud.githubusercontent.com/assets/11508369/15550510/c472c14e-22c2-11e6-8003-f25859a17ae9.png)

If you add bogus attributes, `pod install` runs successfully, but project doesn't build:

![2016-05-22 19 14 06](https://cloud.githubusercontent.com/assets/11508369/15550553/f98aaab8-22c2-11e6-9348-56ed7cffe353.png)

If you manually delete these lines, it throws 20+ errors and still doesn't build:

![2016-05-25 20 54 18](https://cloud.githubusercontent.com/assets/11508369/15550615/4e986586-22c3-11e6-981d-6f60bc4d80c4.png)
It looks to me like it incorrectly generates obj-c files from .proto and adds wrong fields:

![2016-05-25 20 54 31](https://cloud.githubusercontent.com/assets/11508369/15550633/69ccea0c-22c3-11e6-9070-2e1e17dfa9aa.png)

What do I do if I want to use gRPC in my iOS app (for use with TensorFlow serving)?

**Comment by namsoila** [comment] 2016-05-26 06:51
@rsln-s You do need to add the attributes due to the requirements set by the cocoapods upgrade.
I outlined the other error here that can be solved via podspec change if you do not have the required version of protobuf beta running.

https://github.com/grpc/grpc/issues/6646

With those edits you can build your own clean swift project. However, the podfile cannot use #use_frameworks when building.

**Comment by jcanizales** [comment] 2016-06-02 16:23
Wow @namsoila, thanks for responding! 👍 👍

**Comment by mehrdada** [comment] 2017-06-08 22:44
We are cleaning up the gRPC issue backlog and looks like this issue is no longer relevant (see grpc-swift repo). If you are still experiencing this issue, please re-open an issue with information on how to reproduce.

**Comment by jcanizales** [comment] 2017-06-08 22:53
To clarify: gRPC-ObjC _must_ work when used from a Swift app, even if gRPC-Swift exists now.

I think @rsln-s's issue is fixed now, though. @muxi should verify and close if so.

**Comment by mehrdada** [comment] 2017-06-08 23:06
@jcanizales You are absolutely right; however, the Swift code example in question is no longer shipped with the gRPC repository and the issue seems fixed. I'll hold for @muxi to close again, hopefully.

**Comment by mehrdada** [comment] 2017-06-15 17:50
I confirmed with @muxi and this is indeed fixed according to him.

**Closed by mehrdada** 2017-06-15 17:50 UTC
Labels: fixit
