### ISSUE TITLE
Grpc.Tools on Linux musl 

### ISSUE THREAD

**Issue by kant2002** [grpc/grpc#32150] opened 2023-01-19 13:02 UTC
### Is your feature request related to a problem? Please describe.
I try to create statically linked Grpc Api in C#, and use `mcr.microsoft.com/dotnet/sdk:7.0-alpine` Docker image. `dotnet publish -c Release -r linux-musl-x64` fails with following error
```
#15 5.096 /root/.nuget/packages/grpc.tools/2.49.0/build/_protobuf/Google.Protobuf.Tools.targets(280,5): error MSB6003: The specified task executable "/root/.nuget/packages/grpc.tools/2.49.0/tools/linux_x64/protoc" could not be run. System.ComponentModel.Win32Exception (2): An error occurred trying to start process '/root/.nuget/packages/grpc.tools/2.49.0/tools/linux_x64/protoc' with working directory '/app'. No such file or directory [/app/GrpcApi.csproj]
#15 5.096 /root/.nuget/packages/grpc.tools/2.49.0/build/_protobuf/Google.Protobuf.Tools.targets(280,5): error MSB6003:    at System.Diagnostics.Process.ForkAndExecProcess(ProcessStartInfo startInfo, String resolvedFilename, String[] argv, String[] envp, String cwd, Boolean setCredentials, UInt32 userId, UInt32 groupId, UInt32[] groups, Int32& stdinFd, Int32& stdoutFd, Int32& stderrFd, Boolean usesTerminal, Boolean throwOnNoExec) [/app/GrpcApi.csproj]
#15 5.096 /root/.nuget/packages/grpc.tools/2.49.0/build/_protobuf/Google.Protobuf.Tools.targets(280,5): error MSB6003:    at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo) [/app/GrpcApi.csproj]
#15 5.096 /root/.nuget/packages/grpc.tools/2.49.0/build/_protobuf/Google.Protobuf.Tools.targets(280,5): error MSB6003:    at Microsoft.Build.Utilities.ToolTask.ExecuteTool(String pathToTool, String responseFileCommands, String commandLineCommands) [/app/GrpcApi.csproj]
#15 5.096 /root/.nuget/packages/grpc.tools/2.49.0/build/_protobuf/Google.Protobuf.Tools.targets(280,5): error MSB6003:    at Microsoft.Build.Utilities.ToolTask.Execute() [/app/GrpcApi.csproj]
```

### Describe the solution you'd like
I think Nuget should provide additional `protoc` executable, suited for `linux-musl-x64` RID.

**Comment by tonydnewell** [comment] 2023-01-20 13:39
This is a duplicate of https://github.com/grpc/grpc/issues/24188

Grpc.Tools currently does not work on Alpine Linux. There is a workaround here https://github.com/grpc/grpc/issues/24188#issuecomment-1261974839

**Closed** 2023-01-20 14:20 UTC
Labels: kind/enhancement, lang/C#, priority/P2
