### ISSUE TITLE
PHP: startBatch is taking exceptionally long time

### ISSUE THREAD

**Issue by stanley-cheung** [grpc/grpc#14534] opened 2018-02-27 01:37 UTC
https://github.com/GoogleCloudPlatform/google-cloud-php/issues/819#issuecomment-368706559

This is a user-reported issue from the `google-cloud-php` repo. Tracking it here

**Comment by murgatroid99** [comment] 2018-02-27 01:45
That profile is misleading. The `Grpc\Call::startBatch` function includes the call to `grpc_completion_queue_pluck`, which includes all of the time waiting for network events.

**Comment by dwsupplee** [comment] 2018-02-27 03:08
@murgatroid99 Could you please expand on why the fact the profile includes waiting for network events is misleading? Is there any other data I could help provide?

**Comment by murgatroid99** [comment] 2018-02-27 17:44
What I mean, more specifically, is that a profile like that does not indicate that `startBatch` is a source of performance problems, because it adds together local run time and network latency. Honestly, though, I don't know what data would be more helpful.

**Comment by ZhouyihaiDing** [comment] 2018-03-06 01:20
Hi @dwsupplee ,
I run the same script provided by the upstream issue in my GCE for 100 times with both grpc and rest transport:
`for i in 'seq 1 100'; do php -q write-sub.php; done | tee result`
```
write-sub.php
<?php
$_num_inserts = 0;

require('vendor/autoload.php');
use Google\Cloud\PubSub\PubSubClient;

$projectId = 'grpcwebtesting';
$pubSub = new PubSubClient([
    'projectId' => $projectId,
    'transport' => 'rest'
]);
$_topic = $pubSub->topic('test');
$_start_time = microtime(true);
$_topic->publish([
    'data' => 'My new message. ('.time().')',
    'attributes' => [
        'location' => 'Test 123 - '.rand(1000,9999)
    ]
]);
$_end_time = microtime(true);
print ($_end_time-$_start_time)." ";

$_start_time = microtime(true);
$_topic->publish([
    'data' => 'My new message. ('.time().')',
    'attributes' => [
        'location' => 'Test 456 - '.rand(1000,9999)
    ]
]);
$_end_time = microtime(true);
print ($_end_time-$_start_time)." ";

$_start_time = microtime(true);
$_topic->publish([
    'data' => 'My new message. ('.time().')',
    'attributes' => [
        'location' => 'Test 789 - '.rand(1000,9999)
    ]
]);
$_end_time = microtime(true);
print ($_end_time-$_start_time)."\n";
```
I get the result like this:
REST:
```
0.21846413612366 0.05851411819458 0.051126956939697
0.14872694015503 0.070885896682739 0.10080695152283
0.14297699928284 0.16884303092957 0.10953092575073
0.16240119934082 0.056371212005615 0.055716037750244
0.13611316680908 0.059178113937378 0.061942100524902
0.13634896278381 0.10430002212524 0.067078828811646
0.18685793876648 0.11610007286072 0.056571006774902
0.22050094604492 0.067669153213501 0.069279909133911
0.13619589805603 0.056427001953125 0.058426141738892
0.25849318504333 0.11442804336548 0.14046382904053
0.14135813713074 0.13725209236145 0.10124683380127
0.14303994178772 0.055007934570312 0.10354804992676
0.15602684020996 0.062564849853516 0.14339089393616
0.15209603309631 0.058828830718994 0.055635929107666
0.15268588066101 0.062503099441528 0.10451984405518
0.14555191993713 0.054335117340088 0.057209968566895
0.137531042099 0.058938026428223 0.059720993041992
0.13925313949585 0.059509038925171 0.055071115493774
0.14344215393066 0.057697057723999 0.075208902359009
```
gRPC with protobuf c_extension:
```
0.19986414909363 0.014701843261719 0.012382030487061
0.17137289047241 0.012480020523071 0.011713981628418
0.16966485977173 0.011740922927856 0.012115001678467
0.1742959022522 0.0099990367889404 0.012738943099976
0.16153693199158 0.011291980743408 0.013216018676758
0.18629002571106 0.019361019134521 0.010370016098022
0.16714787483215 0.012462854385376 0.011173009872437
0.15705585479736 0.011788129806519 0.011378049850464
0.17034602165222 0.0096969604492188 0.0078780651092529
0.15086603164673 0.0075688362121582 0.016098976135254
0.18133592605591 0.011151075363159 0.011448860168457
0.17375707626343 0.012903928756714 0.0079920291900635
0.17534399032593 0.012880086898804 0.013008117675781
0.16156101226807 0.010257959365845 0.011096000671387
0.15987086296082 0.013827085494995 0.010673999786377
0.20808410644531 0.010999917984009 0.01102089881897
0.15847492218018 0.01154899597168 0.012151002883911
```
Both REST and gRPC transport have the same long latency for the initiate RPC. Although fetchAuthToken doesn't take much time as the discussion in the upstream issue, is it possible that the server do something time consuming like check the credentials or something else during the first RPC?
At the same time, I'll try to find what I can do to make the first RPC faster in the gRPC-PHP side.

**Comment by ZhouyihaiDing** [comment] 2018-03-07 18:40
According to the upstream issue, startBatch latency is introduced on the server side, not caused by gRPC.

**Comment by ZhouyihaiDing** [comment] 2018-03-10 02:42
Works above is for pubsub API.
I am working on the Bigtable API startBatch latency.

**Comment by axot** [comment] 2018-03-13 13:20
I found pecl-grpc v1.10.0 is much slower than v1.8.5 for the first connection.
(500ms vs 10ms)

**Comment by ZhouyihaiDing** [comment] 2018-03-13 17:11
Hi @axot ,
Can you please provide me more information about how to get the result?
I was tracing the request and got some data. I haven't report the number yet, but in general, the BigTable readRows request latency can be divided into 3 parts: 
1. fetch auth token. (50ms for the first connection, 0.1ms for the following rpc. I think it gets the help with cache)
2. send request to the server, backend process it, receive the response. (60ms-80ms for the first connection, 10ms-30ms for the following rpc)
3. gRPC initiate and process, like compress, prepare things to be sent. (60ms-70ms for the fist connection, 1ms for the following rpc)
I am verifying it with other cloud API like spanner. If it's correct, there are no more we can do for the 1 and 2 part, but to make 3 faster.

**Comment by axot** [comment] 2018-03-14 01:55
@ZhouyihaiDing , I'm testing Spanner in Tokyo region, more details in here
https://github.com/GoogleCloudPlatform/google-cloud-php/issues/819#issuecomment-372876349
 
And I found different behavior in 1.10.0.
```
PID   COMM       LADDR           LPORT RADDR           RPORT TX_KB RX_KB MS
17287 grpc_execu ::ffff:10.22.0.10 40944 ::ffff:172.217.31.138 443       6     5 195.23
17288 grpc_execu ::ffff:10.22.0.10 40414 ::ffff:172.217.31.170 443       6     5 168.02
17289 grpc_execu ::ffff:10.22.0.10 55504 ::ffff:216.58.220.234 443       6     5 191.55
```
This communication happens per request, but I can not find same communication in 1.8.5.

**Comment by ZhouyihaiDing** [comment] 2018-03-14 06:24
Thank you for your help, @axot !

I am running your code in GCE located in asia-northeast1-b with the spanner instance located in the same region. But I removed `APCu` cache part to focus tracing the latency. I already got some data and it doesn't show much difference like bigtable and pubsub, which gRPC initiation time takes 30-80ms for the first RPC and almost 0 for the following. I'll report the data together with bigtable after I double verify it. 

Can you please explain more about what `1.8.5 takes almost 200-300s` means? It's that the latency of a RPC or the total time this php-fpm process up?

I am going to trace the "`Persistent Connection`" thing, can you please offer me more information? I tried to run the script like 
`for i in {1..30}; do php -q spanner.php; done`
and it doesn't show much difference between `grpc-1.8.5` and `grpc-1.10.0`? So I guess you are running both grace versions in `php-fpm` mode, right? 
Persistent connection is supposed to work under php-fpm mode. I am not familiar with `APCu` and not sure will it conflict with the pool created by gRPC, I am going to check it. If after removing it the result remains the same, I'll check the changes between 1.8.5 and 1.10.0 in [this PR](https://github.com/grpc/grpc/pull/14149/files).

**Comment by axot** [comment] 2018-03-14 07:37
@ZhouyihaiDing I changed `ApcuAdapter` to `FilesystemAdapter`, it gets similar results without php-fpm.

```
$ php test.php
GRPC Version: 1.8.5
Warmup: 0.102 milliseconds
1 Query: 289.055 milliseconds
2 Query: 44.550 milliseconds
3 Query: 3.173 milliseconds
4 Query: 2.805 milliseconds
5 Query: 2.820 milliseconds
6 Query: 3.742 milliseconds
7 Query: 2.562 milliseconds
8 Query: 3.440 milliseconds
9 Query: 3.120 milliseconds
10 Query: 2.640 milliseconds
```

```
$ php test.php
GRPC Version: 1.10.0
Warmup: 0.142 milliseconds
1 Query: 1,010.479 milliseconds
2 Query: 40.580 milliseconds
3 Query: 5.322 milliseconds
4 Query: 5.111 milliseconds
5 Query: 3.875 milliseconds
6 Query: 3.675 milliseconds
7 Query: 4.429 milliseconds
8 Query: 4.414 milliseconds
9 Query: 4.724 milliseconds
10 Query: 5.713 milliseconds
```

As you can see, with `v1.10.0` `1 Query` took 3-4x times than `v1.8.5`.

> Can you please explain more about what 1.8.5 takes almost 200-300s means? It's that the latency of a RPC or the total time this php-fpm process up?

This is the total time of TCP session that open and close. So I think it is a normal behavior if using  `Persistent Connection` mode in `php-fpm`. So I guess in `1.10.0` `Persistent Connection` was freed after each request.

**Comment by axot** [comment] 2018-03-14 13:04
I made a flame-graph for comparison. You can download the original svg format here, may helpful.
[on-cpu-flame-graph.zip](https://github.com/grpc/grpc/files/1811136/on-cpu-flame-graph.zip)

Preview here.
1.8.5
![1 8 5 svg](https://user-images.githubusercontent.com/611054/37403878-91758372-27d3-11e8-9962-23cddba420c4.png)

1.10.0
![1 10 0 svg](https://user-images.githubusercontent.com/611054/37403884-9667c160-27d3-11e8-8595-9b68942003d0.png)

**Comment by dwsupplee** [comment] 2018-03-14 15:39
@ZhouyihaiDing sorry for the delayed response.

When run on GCE I see similar results as you mentioned. However, when I run the script 20 times on my local development machine I see the following (with an already cached auth token):

REST:
```
0.19489789009094 0.037225961685181 0.03973913192749
0.20339512825012 0.040876865386963 0.043087959289551
0.18250513076782 0.041792154312134 0.039877891540527
0.18628120422363 0.039862871170044 0.043469190597534
0.18130087852478 0.045254945755005 0.041988849639893
0.18522906303406 0.048583030700684 0.041409969329834
0.18882918357849 0.043915987014771 0.043264150619507
0.19993305206299 0.040619850158691 0.042426824569702
0.1882529258728 0.042854070663452 0.044863939285278
0.18107891082764 0.03930401802063 0.044710159301758
0.22000098228455 0.042585134506226 0.039599895477295
0.19017601013184 0.037634134292603 0.039781093597412
0.18644404411316 0.040591955184937 0.041887998580933
0.1916491985321 0.079386949539185 0.047858953475952
0.17888498306274 0.036967039108276 0.036783933639526
0.1844208240509 0.04079008102417 0.039869070053101
0.14662384986877 0.047139883041382 0.048990964889526
0.1927638053894 0.040356874465942 0.049510955810547
0.19094491004944 0.042094945907593 0.044947147369385
0.18920302391052 0.038762092590332 0.039801120758057
```

gRPC v1.8.5
```
0.33104181289673 0.038801908493042 0.056406021118164
0.31952714920044 0.050151109695435 0.059834003448486
0.32298302650452 0.045830011367798 0.059325933456421
0.35558605194092 0.046213865280151 0.058226108551025
0.33616590499878 0.065206050872803 0.0591721534729
0.31988501548767 0.07715106010437 0.055783033370972
0.32758903503418 0.055761098861694 0.055678129196167
0.35145688056946 0.057261943817139 0.045493125915527
0.33373785018921 0.049771785736084 0.044853925704956
0.34525799751282 0.057574987411499 0.047112941741943
0.34258317947388 0.064590930938721 0.048111200332642
0.32757592201233 0.053658008575439 0.062611103057861
0.33687496185303 0.04616904258728 0.071362972259521
0.34099984169006 0.064764022827148 0.038785219192505
0.3466169834137 0.05119800567627 0.048923015594482
0.33255505561829 0.057765007019043 0.046075105667114
0.33456301689148 0.053205966949463 0.043113946914673
0.32750296592712 0.047332048416138 0.059146881103516
0.33643794059753 0.044345855712891 0.052647113800049
0.37080717086792 0.054423093795776 0.044103860855103
```

There seems to be a considerable addition to latency on the first gRPC call in this case.  I have traced the code and from what I can tell an auth token is not being fetched. I will look a bit deeper to see what I can find.

**Comment by ZhouyihaiDing** [comment] 2018-03-14 21:59
Thanks @axot !
You are right, it seems there are regressions after gRPC-v1.9.0 and I am working on locating where the problem is.
So, to make it clear, in spanner, even in gRPC-v1.8.5, the first RPC(warm up) will take ~1000ms, right? Since the channel is persistent correctly, it saves latency to `289.055ms` later.  Your question is that the current gRPC-PHP has problem with persistent channel, right? Most time cost with '1000'ms warm up are waiting for the network events, which we can not do anything in gRPC part. I'll try to fix the persistent channel part so it will be saved to 289ms as like 1.8.5.

**Comment by ZhouyihaiDing** [comment] 2018-03-19 21:07
Duplicate of #14713. Close this issue in order to make the progress clear.
By tracing the request, startBatch latency for the first RPC is mostly caused by waiting the network event.
The new issue is that the persistent channel which should be cached to make the following rpc faster, doesn't work. I am working on adding the persistent channel management.

**Closed by ZhouyihaiDing** 2018-03-19 21:07 UTC
Labels: lang/php
