### ISSUE TITLE
Error messages are inscrutable

### ISSUE THREAD

**Issue by jerjou** [grpc/grpc#8019] opened 2016-09-07 17:05 UTC
When making a call to Google's [speech api](https://cloud.google.com/speech), it seems a server error was encountered: GoogleCloudPlatform/python-docs-samples#484. However, the error message (pasted below) is inscrutable, and we can only infer it was a server error... It'd be nice if the error messages were more human readable.

```
Traceback (most recent call last):
  File "speech_streaming.py", line 157, in <module>
    main()
  File "speech_streaming.py", line 149, in main
    request_stream(stop_audio), DEADLINE_SECS))
  File "speech_streaming.py", line 125, in listen_print_loop
    for resp in recognize_stream:
  File "/home/chiba/.pyenv/versions/anaconda3-4.1.0/envs/gasr/lib/python2.7/site-packages/grpc/beta/_client_adaptations.py", line 153, in next
    return self._next()
  File "/home/chiba/.pyenv/versions/anaconda3-4.1.0/envs/gasr/lib/python2.7/site-packages/grpc/beta/_client_adaptations.py", line 147, in _next
    raise _abortion_error(rpc_error_call)
grpc.framework.interfaces.face.face.AbortionError: AbortionError(code=StatusCode.INTERNAL, details="{"created":"@1472177364.848861732","description":"RST_STREAM","file":"src/core/ext/transport/chttp2/transport/frame_rst_stream.c","file_line":107,"http2_error":1}")
```

```
grpc.framework.interfaces.face.face.AbortionError: AbortionError(code=StatusCode.INTERNAL, details="{"created":"@1472207486.837745000","description":"RST_STREAM","file":"src/core/ext/transport/chttp2/transport/frame_rst_stream.c","file_line":107,"http2_error":1}")
E0826 12:31:27.196445000 140735186059264 chttp2_transport.c:1810] close_transport: {"created":"@1472207487.192932000","description":"Secure read failed","file":"src/core/lib/security/transport/secure_endpoint.c","file_line":157,"referenced_errors":[{"created":"@1472207487.192918000","description":"FD shutdown","file":"src/core/lib/iomgr/ev_poll_posix.c","file_line":427}]}
```

**Comment by nathanielmanistaatgoogle** [comment] 2016-09-08 16:55
I think that there are two things going on here and the first is much less severe than the second:

1. `grpc.framework.interfaces.face.face.AbortionError` is an awkwardly long class name. It has been superseded by `grpc.RpcError` in the GA API, although at the moment the GA API raises an instance of an internal subclass of `grpc.RpcError` with a slightly longer name, so there's still some "hey, what's this weird class I'm seeing?" going on.
2. That details string isn't giving you a clear idea of what went wrong or what you can do to fix the problem. It's not really a message or instruction and the references to source code don't help. I don't even see any indication of whether it was generated locally or whether it came across the wire from the server - do you? If you had to guess, how confident do you think you'd be about which side generated the string?

Please confirm this assessment? In particular is it `{"created":"@1472207486.837745000","description":"RST_STREAM","file":"src/core/ext/transport/chttp2/transport/frame_rst_stream.c","file_line":107,"http2_error":1}` that you are describing as "inscrutable" and wish were more human-readable?

**Comment by jerjou** [comment] 2016-09-08 17:17
I agree with your assessment, and that #2 is more severe than #1. `RpcError` is also a more informative name (the length of the path isn't that big a deal to me), and `StatusCode.INTERNAL` just sounds like a generic catch-all error (and doesn't tell me if it's an error internal to the grpc client or server). 

I just realized that the values for `description` and `http2_error` are from the http2 spec, which is reasonable. But until now I had assumed the error codes would look similar to http1, and just dismissed `"http2_error":1` as a default value or something. Perhaps something that said "There was an error communicating with the server" might have made me pay more attention to the error code? Or maybe if the symbol [PROTOCOL_ERROR](https://http2.github.io/http2-spec/#ErrorCodes) was used instead of an integer? (though that also doesn't really tell me if I did something wrong, or the server did..)

But yeah - my main indicator that this was an error from the server rather than the client was because the script used to work, then didn't for a bit, then did again.

**Comment by nathanielmanistaatgoogle** [comment] 2016-09-08 17:21
@jerjou: the authoritative definitions of status codes are [here](https://github.com/grpc/grpc/blob/master/doc/statuscodes.md).

@ctiller: how possible would it be to generate a friendlier details string?

**Comment by ctiller** [comment] 2016-09-08 17:22
I think this ends up duplicating #7439

**Comment by ctiller** [comment] 2016-09-08 17:22
(so... totally possible, needs someone to work on them)

**Comment by nathanielmanistaatgoogle** [comment] 2016-09-08 17:38
Closing as a duplicate of [issue 7439](https://github.com/grpc/grpc/issues/7439).

**Closed by nathanielmanistaatgoogle** 2016-09-08 17:38 UTC
Labels: core, python
