### ISSUE TITLE
Failure: c_windows_opt_native.cmake/build/Release/h2_http_proxy_nosec_test.exe hpack_size (from grpc.c_windows_opt_native)

### ISSUE THREAD

**Issue by AspirinSJL** [grpc/grpc#12547] opened 2017-09-13 17:33 UTC
https://grpc-testing.appspot.com/job/gRPC_pr_win/7684/testReport/junit/(root)/c_windows_opt_native/cmake_build_Release_h2_http_proxy_nosec_test_exe_hpack_size/

```
Error Message

Failure
Stacktrace

e\lib\iomgr\tcp_windows.c","file_line":183,"referenced_errors":[{"created":"@1505152458.207000000","description":"End of TCP stream","file":"C:\jenkins\workspace\gRPC_pr_win\workspace_c_windows_opt_native\src\core\lib\iomgr\tcp_windows.c","file_line":184}]}
D0911 17:54:18.207000000  3244 http_proxy_fixture.c:108] endpoints: 004E6C00 004E6D10
I0911 17:54:18.207000000  2432 hpack_size.c:182] Running test: test_size:e=1000:d=0/chttp2/fullstack
I0911 17:54:18.211000000  2432 http_proxy_fixture.c:497] Proxy address: localhost:12309
I0911 17:54:18.216000000  2840 http_connect_handshaker.c:305] Connecting to server localhost:17880 via HTTP proxy ipv4:127.0.0.1:12309
D0911 17:54:18.216000000  2840 http_proxy_fixture.c:341] on_read_request_done: 005577C8 "No Error"
I0911 17:54:18.306000000  2840 http_proxy_fixture.c:136] HTTP proxy server read: {"created":"@1505152458.306000000","description":"End of TCP stream","file":"C:\jenkins\workspace\gRPC_pr_win\workspace_c_windows_opt_native\src\core\lib\iomgr\tcp_windows.c","file_line":184}
I0911 17:54:18.306000000  2840 http_proxy_fixture.c:136] HTTP proxy client read: {"created":"@1505152458.306000000","description":"TCP stream shutting down","file":"C:\jenkins\workspace\gRPC_pr_win\workspace_c_windows_opt_native\src\core\lib\iomgr\tcp_windows.c","file_line":183,"referenced_errors":[{"created":"@1505152458.306000000","description":"End of TCP stream","file":"C:\jenkins\workspace\gRPC_pr_win\workspace_c_windows_opt_native\src\core\lib\iomgr\tcp_windows.c","file_line":184}]}
D0911 17:54:18.306000000  2840 http_proxy_fixture.c:108] endpoints: 004E6C00 004E6C88
I0911 17:54:18.306000000  2432 hpack_size.c:182] Running test: test_size:e=1000:d=100/chttp2/fullstack
I0911 17:54:18.310000000  2432 http_proxy_fixture.c:497] Proxy address: localhost:11740
I0911 17:54:18.313000000  1348 http_connect_handshaker.c:305] Connecting to server localhost:8559 via HTTP proxy ipv4:127.0.0.1:11740
D0911 17:54:18.313000000  1348 http_proxy_fixture.c:341] on_read_request_done: 005577C8 "No Error"
I0911 17:54:18.398000000  1348 http_proxy_fixture.c:136] HTTP proxy server read: {"created":"@1505152458.398000000","description":"End of TCP stream","file":"C:\jenkins\workspace\gRPC_pr_win\workspace_c_windows_opt_native\src\core\lib\iomgr\tcp_windows.c","file_line":184}
I0911 17:54:18.398000000  1348 http_proxy_fixture.c:136] HTTP proxy client read: {"created":"@1505152458.398000000","description":"TCP stream shutting down","file":"C:\jenkins\workspace\gRPC_pr_win\workspace_c_windows_opt_native\src\core\lib\iomgr\tcp_windows.c","file_line":183,"referenced_errors":[{"created":"@1505152458.398000000","description":"End of TCP stream","file":"C:\jenkins\workspace\gRPC_pr_win\workspace_c_windows_opt_native\src\core\lib\iomgr\tcp_windows.c","file_line":184}]}
D0911 17:54:18.399000000  1348 http_proxy_fixture.c:108] endpoints: 004E6C88 004E6C00
I0911 17:54:18.399000000  2432 hpack_size.c:182] Running test: test_size:e=1000:d=1000/chttp2/fullstack
I0911 17:54:18.402000000  2432 http_proxy_fixture.c:497] Proxy address: localhost:3128
I0911 17:54:18.406000000  6392 http_connect_handshaker.c:305] Connecting to server localhost:32065 via HTTP proxy ipv4:127.0.0.1:3128
D0911 17:54:18.406000000  6392 http_proxy_fixture.c:341] on_read_request_done: 00565768 "No Error"
I0911 17:54:18.487000000  6392 http_proxy_fixture.c:136] HTTP proxy server read: {"created":"@1505152458.487000000","description":"End of TCP stream","file":"C:\jenkins\workspace\gRPC_pr_win\workspace_c_windows_opt_native\src\core\lib\iomgr\tcp_windows.c","file_line":184}
I0911 17:54:18.487000000  6392 http_proxy_fixture.c:136] HTTP proxy client read: {"created":"@1505152458.487000000","description":"TCP stream shutting down","file":"C:\jenkins\workspace\gRPC_pr_win\workspace_c_windows_opt_native\src\core\lib\iomgr\tcp_windows.c","file_line":183,"referenced_errors":[{"created":"@1505152458.487000000","description":"End of TCP stream","file":"C:\jenkins\workspace\gRPC_pr_win\workspace_c_windows_opt_native\src\core\lib\iomgr\tcp_windows.c","file_line":184}]}
D0911 17:54:18.487000000  6392 http_proxy_fixture.c:108] endpoints: 004E6C00 004E6C88
I0911 17:54:18.488000000  2432 hpack_size.c:182] Running test: test_size:e=1000:d=32768/chttp2/fullstack
I0911 17:54:18.492000000  2432 http_proxy_fixture.c:497] Proxy address: localhost:1628
I0911 17:54:18.496000000  4916 http_connect_handshaker.c:305] Connecting to server localhost:25333 via HTTP proxy ipv4:127.0.0.1:1628
D0911 17:54:18.497000000  4916 http_proxy_fixture.c:341] on_read_request_done: 0054B990 "No Error"
I0911 17:54:18.581000000  4916 http_proxy_fixture.c:136] HTTP proxy server read: {"created":"@1505152458.581000000","description":"End of TCP stream","file":"C:\jenkins\workspace\gRPC_pr_win\workspace_c_windows_opt_native\src\core\lib\iomgr\tcp_windows.c","file_line":184}
I0911 17:54:18.581000000  4916 http_proxy_fixture.c:136] HTTP proxy client read: {"created":"@1505152458.581000000","description":"TCP stream shutting down","file":"C:\jenkins\workspace\gRPC_pr_win\workspace_c_windows_opt_native\src\core\lib\iomgr\tcp_windows.c","file_line":183,"referenced_errors":[{"created":"@1505152458.581000000","description":"End of TCP stream","file":"C:\jenkins\workspace\gRPC_pr_win\workspace_c_windows_opt_native\src\core\lib\iomgr\tcp_windows.c","file_line":184}]}
D0911 17:54:18.581000000  4916 http_proxy_fixture.c:108] endpoints: 004E6C88 004E6C00
I0911 17:54:18.581000000  2432 hpack_size.c:182] Running test: test_size:e=1000:d=4194304/chttp2/fullstack
I0911 17:54:18.585000000  2432 http_proxy_fixture.c:497] Proxy address: localhost:7721
I0911 17:54:18.589000000  7620 http_connect_handshaker.c:305] Connecting to server localhost:8602 via HTTP proxy ipv4:127.0.0.1:7721
D0911 17:54:18.589000000  7620 http_proxy_fixture.c:341] on_read_request_done: 0054B990 "No Error"
I0911 17:54:18.675000000  7620 http_proxy_fixture.c:136] HTTP proxy server read: {"created":"@1505152458.675000000","description":"End of TCP stream","file":"C:\jenkins\workspace\gRPC_pr_win\workspace_c_windows_opt_native\src\core\lib\iomgr\tcp_windows.c","file_line":184}
I0911 17:54:18.675000000  7620 http_proxy_fixture.c:136] HTTP proxy client read: {"created":"@1505152458.675000000","description":"TCP stream shutting down","file":"C:\jenkins\workspace\gRPC_pr_win\workspace_c_windows_opt_native\src\core\lib\iomgr\tcp_windows.c","file_line":183,"referenced_errors":[{"created":"@1505152458.675000000","description":"End of TCP stream","file":"C:\jenkins\workspace\gRPC_pr_win\workspace_c_windows_opt_native\src\core\lib\iomgr\tcp_windows.c","file_line":184}]}
D0911 17:54:18.675000000  7620 http_proxy_fixture.c:108] endpoints: 004E6C00 004E6C88
I0911 17:54:18.675000000  2432 hpack_size.c:182] Running test: test_size:e=32768:d=4096/chttp2/fullstack
I0911 17:54:18.679000000  2432 http_proxy_fixture.c:497] Proxy address: localhost:30141
I0911 17:54:18.683000000  6624 http_connect_handshaker.c:305] Connecting to server localhost:24511 via HTTP proxy ipv4:127.0.0.1:30141
D0911 17:54:18.683000000  6624 http_proxy_fixture.c:341] on_read_request_done: 0054B990 "No Error"
E0911 17:54:23.754000000  2432 cq_verifier.c:273] cq returned unexpected event: OP_COMPLETE: tag:00000001 OK
E0911 17:54:23.755000000  2432 cq_verifier.c:280] expected tags:
tag(101) GRPC_OP_COMPLETE success=1 C:\jenkins\workspace\gRPC_pr_win\workspace_c_windows_opt_native\test\core\end2end\tests\hpack_size.c:303

Abort handler called.
*** 0: 0000000001352D4C  - 0000000000000000
*** 1: 000000000135299D  - 0000000000000000
*** 2: 000000006EF84672 abort - 000000006EF84640
*** 3: 000000000131177B abort - 000000006EF84640
*** 4: 00000000012EDFEC abort - 000000006EF84640
*** 5: 00000000012EDB1F abort - 000000006EF84640
*** 6: 00000000012E1EC4 abort - 000000006EF84640
*** 7: 00000000012E120F abort - 000000006EF84640
*** 8: 000000000135CF76 abort - 000000006EF84640
*** 9: 00000000764F336A BaseThreadInitThunk - 00000000764F3358
*** 10: 0000000077309902 RtlInitializeExceptionChain - 000000007730989F
*** 11: 00000000773098D5 RtlInitializeExceptionChain - 000000007730989F
```

**Comment by yashykt** [comment] 2017-09-18 21:28
The same failure was also seen with 
bins/dbg/h2_http_proxy_test hpack_size GRPC_POLL_STRATEGY=epoll1

**Comment by dgquintas** [comment] 2017-09-24 01:53
Duplicate of #12394

**Closed by dgquintas** 2017-09-24 01:53 UTC
Labels: infra/BUILDPONY
