### ISSUE TITLE
make: *** No rule to make target /src/ruby/ext/grpc/objs/opt/third_party/zlib/adler32.o

### ISSUE THREAD

**Issue by bbuchalter** [grpc/grpc#25698] opened 2021-03-12 01:18 UTC
### What version of gRPC and what language are you using?
gRPC version: `HEAD`
Language: Ruby

### What operating system (Linux, Windows,...) and version?
macOS 11.2.1 (w/ Apple Silicon)

### What runtime / compiler are you using (e.g. python version or version of gcc)
```
$ ruby --version
ruby 2.7.2p137 (2020-10-01 revision 5445e04352) [arm64-darwin20]

$ gcc --version
Configured with: --prefix=/Library/Developer/CommandLineTools/usr --with-gxx-include-dir=/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/4.2.1
Apple clang version 12.0.0 (clang-1200.0.32.29)
Target: arm64-apple-darwin20.3.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
```

### What did you do?
Created a [simple Ruby gem](https://github.com/bbuchalter/test-grpc/blob/main/Gemfile#L8) that had a dependency configured on the `HEAD` of `grpc` and then ran `bundle install`

### What did you expect to see?
The `grpc` compiled Ruby's "native extensions" without error.

### What did you see instead?
```
Using grpc 1.37.0.dev from https://github.com/grpc/grpc.git (at master@d2c2d66)
/Users/brian.buchalter/.rubies/ruby-2.7.2/lib/ruby/2.7.0/rubygems/ext/builder.rb:167: warning: conflicting chdir during another chdir block
/Users/brian.buchalter/.rubies/ruby-2.7.2/lib/ruby/2.7.0/rubygems/ext/builder.rb:175: warning: conflicting chdir during another chdir block
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    current directory: /Users/brian.buchalter/.gem/ruby/2.7.2/bundler/gems/grpc-d2c2d66a03fc/src/ruby/ext/grpc
/Users/brian.buchalter/.rubies/ruby-2.7.2/bin/ruby -I /Users/brian.buchalter/.rubies/ruby-2.7.2/lib/ruby/2.7.0 -r ./siteconf20210311-60090-rfhz07.rb extconf.rb
Building internal gRPC into /Users/brian.buchalter/.gem/ruby/2.7.2/bundler/gems/grpc-d2c2d66a03fc/src/ruby/ext/grpc/libs/opt
make: *** No rule to make target `/Users/brian.buchalter/.gem/ruby/2.7.2/bundler/gems/grpc-d2c2d66a03fc/src/ruby/ext/grpc/objs/opt/third_party/zlib/adler32.o', needed by
`/Users/brian.buchalter/.gem/ruby/2.7.2/bundler/gems/grpc-d2c2d66a03fc/src/ruby/ext/grpc/libs/opt/libz.a'.  Stop.
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/Users/brian.buchalter/.rubies/ruby-2.7.2/bin/$(RUBY_BASE_NAME)

extconf failed, exit code 1

Gem files will remain installed in /Users/brian.buchalter/.gem/ruby/2.7.2/bundler/gems/grpc-d2c2d66a03fc for inspection.
Results logged to /Users/brian.buchalter/.gem/ruby/2.7.2/bundler/gems/extensions/arm64-darwin-20/2.7.0-static/grpc-d2c2d66a03fc/gem_make.out

An error occurred while installing grpc (1.37.0.dev), and Bundler cannot continue.
```

I could not find the `mkmf.log` the error message refers to. Would welcome guidance there.

**Comment by drfloob** [comment] 2021-03-12 17:42
This looks like a duplicate of https://github.com/grpc/grpc/issues/25669#issuecomment-796563819. Please check to be sure you're initializing the submodules.

**Closed by drfloob** 2021-03-12 17:42 UTC
Labels: kind/bug, priority/P2
