### ISSUE TITLE
Suggestion: Add CMake Build Script

### ISSUE THREAD

**Issue by Chilledheart** [grpc/grpc#1096] opened 2015-03-19 16:52 UTC
Although using Makefile as build script is pretty portable for most platforms, it looks like a horrible idea for maintenance.

  Currently, the Makefile has 12, 054 lines of code, and more than 30 targets. And if we want to do a modification on it such as add a new target, we need to learn one hundred or more local variables in the Makefile before starting and it seems still hard to do that.

  And there is another reason, i.e., we are using the latest openssl (1.0.2) and protobuf (3.0.0-alpha1) libraries which are not shipped with any linux distributions. So we need to build these specific libraries and link grpc with them instead of the vendor's ones. This means you need to either hard code these compiler flags or pass them before invoking `make`, if you are using Makefile.

  Using more advanced build system such as [cmake](http://cmake.org/), [autoconf](https://www.gnu.org/software/autoconf/), [gyp](https://code.google.com/p/gyp/) and [gn](https://code.google.com/p/chromium/wiki/gn) should make these problems easier to solve. What's more, here are the reasons why [cmake](http://cmake.org/) is better than others:
- being binary instead of being scripts (okay, [gn](https://code.google.com/p/chromium/wiki/gn) is binary as well)
- more portable, running most OSs such as Windows, Linux, Mac OS X, FreeBSD and more.
- easy to generate any project file in Unix Makefile, Visual Studio solutions, Xcode Project, Ninja and etc.
- active and rapid development, e.g. adding [Ninja](https://github.com/martine/ninja)'s console pool support once [Ninja](https://github.com/martine/ninja) 1.5 is out
- well-known and accepted by the community
- and more (if you find any important points missing here, welcome to address them!)

**Comment by vjpai** [comment] 2015-03-19 17:15
So, the current state of affairs should be addressed  in a hypothetical gRPC Developers handbook. One should not change the Makefile as it stands. Instead, change the Makefile.template and build.json and then run the tools/buildgen/generate_projects.sh script.

**Comment by vjpai** [comment] 2015-03-19 17:34
Sorry, I should have added that my response above is addressed in the bottom section of the CONTRIBUTING.md file.

**Comment by nicolasnoble** [comment] 2015-03-19 17:37
Various comments on this:

* The Makefile as it stands is a very good and quick build environment for us. It brings ease to the project as people don't need to install any kind of fancy tool to build. They just require gnu make for this, which is easy to acquire if it's not here.
* The project provides openssl and protobuf. The Makefile that exists here is smart enough to detect what you have on your system, and build the dependencies itself.
* as @vjpai mentioned, the Makefile is in fact already pre-generated. It's not expected from people to modify it directly - the templates are what's to change. See the templates directory, and the build.json file. Also see the tools/buildgen directory.
* I have absolutely no problem generating a CMakeLists.txt and subsequent *.cmake files. In fact, I think we really should do that. It's not on my priority list however. If anyone wants to submit a template for it, I'll accept the pull request gladly.

**Comment by chai2010** [comment] 2015-07-10 06:53
+1

**Comment by chai2010** [comment] 2015-07-14 02:29
I create a fork to support CMake build on windows:
https://github.com/chai2010/grpc-windows/tree/master/build-windows

**Comment by ctiller** [comment] 2016-05-05 19:31
Most of this is done in #4124, but it'll need some updating and a ruby build issue resolved.

**Comment by kangjoni76** [comment] 2016-06-12 10:09
+1

**Comment by dzenanz** [comment] 2016-11-02 19:18
Using CMake on Windows x64 with VS 2013 and 2015 still fails to compile with default options. Does anyone have an update?

**Comment by lighta** [comment] 2017-01-02 03:25
well @dzenanz this is dirty, but here are my diff I had to make it compile.
(I was crosscompiling so few change are for this, (such as moving stuff from if(MSVC) to if(WIN32)..
https://gist.github.com/lighta/16a7ac6a40fd2130a3c6b1eb7c185cee

About the vs2015 well, the issue is that their boringssl dependancies of openssl doesn't contain all the require file. idk who failed here but I suppose it was due to using a new hash of boringssl or something of that sort.
Anyway you can fix it like so :
Add those macro in grpc\vsprojects\global.props, (there needed for posix deprecated when building boringssl and zlib)
_CRT_SECURE_NO_DEPRECATE
_CRT_NONSTDC_NO_DEPRECATE

Add this macro for boringssl project:
WIN32_LEAN_AND_MEAN

Add this include for boringssl project:
$(SolutionDir)\..\third_party\boringssl\include

Turn off treat all warning as error on grpc++-reflection: -WX
Now should build.

**Comment by jtattermusch** [comment] 2017-03-07 13:30
gRPC is now buildable with CMake on both linux and windows and the build is continously tested.

**Closed by jtattermusch** 2017-03-07 13:30 UTC
Labels: buildgen, enhancement, help wanted

**Comment by Chilledheart** [comment] 2017-03-07 13:42
cheers!

**Comment by dzenanz** [comment] 2017-03-07 14:53
The project configures without errors and builds with Visual Studio normally. However, when I try to configure my project which uses gRPC I get following errors:
```
CMake Error at C:/Dev/gRPCgit/vs15/gRPCConfig.cmake:9 (include):
  include could not find load file:

    C:/Dev/gRPCgit/vs15/gRPCTargets.cmake
Call Stack (most recent call first):
  CMakeLists.txt:59 (find_package)


CMake Error at CMakeLists.txt:60 (get_target_property):
  get_target_property() called with non-existent target
  "gRPC::grpc_cpp_plugin".
```
Lines 59 and 60 from my CMakeLists.txt:
```cmake
  find_package(GRPC REQUIRED NO_MODULE)
  get_target_property(GRPC_CPP_PLUGIN gRPC::grpc_cpp_plugin IMPORTED_LOCATION_RELEASE)
```
This might have been caused by #9568.

**Comment by jtattermusch** [comment] 2017-03-08 10:03
@dzenanz  any suggestions on how to fix this?

**Comment by dzenanz** [comment] 2017-03-08 15:14
`gRPCTargets.cmake` needs to be generated in addition to `gRPCConfig.cmake`. Earlier versions of gRPC had this - unfortunately for many reasons those earlier versions could not be normally compiled via CMake.

**Comment by jtattermusch** [comment] 2017-03-15 19:49
@dzenanz a pull request would be welcome.
