### ISSUE TITLE
assertation failed: pthread:_mutex_lock(mu) == 0

### ISSUE THREAD

**Issue by jopedroliveira** [grpc/grpc#11184] opened 2017-05-17 15:57 UTC
Just got this error while using the grpc lib on C++ program. 
That program compilation went good but failed after run.

As far as I read, the error is quite familiar and some issues reported a solution... But in my case it remains unsolved.

sync posix.c:60] assertion failed: pthread_mutex_lock(mu) == 0

I'm running the master version of grpc on MacOs.

**Comment by ncteisen** [comment] 2017-05-17 16:42
This is a duplicate of #10909. Closing.

**Closed by ncteisen** 2017-05-17 16:42 UTC
Labels: bug, macOS
