### ISSUE TITLE
c_linux_opt_native.bins/opt/h2_full+pipe_nosec_test binary_metadata GRPC_POLL_STRATEGY=epollsig

### ISSUE THREAD

**Issue by murgatroid99** [grpc/grpc#11165] opened 2017-05-16 21:57 UTC
https://grpc-testing.appspot.com/job/gRPC_master_linux/2388/testReport/junit/(root)/c_linux_opt_native/bins_opt_h2_full_pipe_nosec_test_binary_metadata_GRPC_POLL_STRATEGY_epollsig/

```
D0514 02:09:35.253064402   17290 test_config.c:403]          test slowdown factor: sanitizer=1, fixture=1, poller=1, total=1
I0514 02:09:35.253180741   17290 ev_epollsig_linux.c:90]     epoll engine will be using signal: 40
D0514 02:09:35.253194801   17290 ev_posix.c:121]             Using polling engine: epollsig
D0514 02:09:35.253206531   17290 dns_resolver.c:316]         Using native dns resolver
I0514 02:09:35.253249366   17290 binary_metadata.c:53]       Running test: test_request_response_with_metadata_and_payload/chttp2/fullstack
E0514 02:09:45.265401667   17290 cq_verifier.c:228]          no event received, but expected:
0x65 GRPC_OP_COMPLETE success=1 test/core/end2end/tests/binary_metadata.c:207

*******************************
Caught signal SIGABRT
bins/opt/h2_full+pipe_nosec_test[0x49ae4e]
/lib/x86_64-linux-gnu/libpthread.so.0(+0xf890)[0x7f17db269890]
/lib/x86_64-linux-gnu/libc.so.6(gsignal+0x37)[0x7f17daee4067]
/lib/x86_64-linux-gnu/libc.so.6(abort+0x148)[0x7f17daee5448]
bins/opt/h2_full+pipe_nosec_test[0x426a38]
bins/opt/h2_full+pipe_nosec_test[0x4060e8]
bins/opt/h2_full+pipe_nosec_test[0x403aed]
bins/opt/h2_full+pipe_nosec_test[0x403115]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf5)[0x7f17daed0b45]
bins/opt/h2_full+pipe_nosec_test[0x403150]
Command terminated by signal 6
```

**Comment by yang-g** [comment] 2017-05-17 18:00
Duplicate of #10653

**Closed by yang-g** 2017-05-17 18:00 UTC
Labels: BUILDPONY, core
