### ISSUE TITLE
C++ API to identify when a CompletionQueue is shutting down

### ISSUE THREAD

**Issue by jeady** [grpc/grpc#5076] opened 2016-02-04 22:46 UTC
After initially registering a tag with a CompletionQueue by calling RegisterAsyncUnary, if Next sets ok=false, there's no indication whether this is because the CompletionQueue is shutting down or because there was some other error. Right now we just have to assume that the queue is shutting down, but it would be nice to do one of: 1) extend NextStatus with a state to indicate SHUTTING_DOWN before the final SHUTDOWN is returned, 2) provide a CompletionQueue::IsShuttingDown() method so we can assert that the CompletionQueue is shutting down when we receive ok=false on the initial connection as described above, or 3) document that when ok=false for the initial request, it means the CompletionQueue is shutting down and the caller should not try to re-register with the CompletionQueue.

This bit exists in the underlying grpc_completion_queue, which check fails on "!cc->shutdown_called" in grpc_cq_begin_op if you attempt to call RegisterAsyncUnary on a CompletionQueue that is shutting down, so it should be possible to expose it through the C++ API as well.

**Comment by yang-g** [comment] 2016-06-01 14:38
The rule is the user should do proper synchronization work to guarantee that after calling CompetionQueue::Shutdown, no more new registering should be done on the cq.

I am not sure I fully understand the ok=false part. I think when you call Next you should watch the return value to see whether the queue is fully drained.

It is possible to do 2) but I do not see it very useful.

Thanks.

**Comment by hsaliak** [comment] 2016-06-07 20:23
Closing this issue - working as intended. The API bloat is not worth the incremental value.

**Closed by hsaliak** 2016-06-07 20:23 UTC
Labels: c++
