### ISSUE TITLE
build issue: master/linux/grpc_interop_tocloud and master/linux/grpc_interop_toprod 

### ISSUE THREAD

**Issue by donnadionne** [grpc/grpc#25360] opened 2021-02-05 07:11 UTC
Both due to similar errors like:

Downloading install script: https://dot.net/v1/dotnet-install.sh => /var/local/git/grpc-dotnet/build/obj/dotnet-install.sh
dotnet-install: Note that the intended use of this script is for Continuous Integration (CI) scenarios, where:
dotnet-install: - The SDK needs to be installed without user interaction and without admin rights.
dotnet-install: - The SDK installation doesn't need to persist across multiple CI runs.
dotnet-install: To set up a development environment or to run apps, use installers rather than this script. Visit https://dotnet.microsoft.com/download to get the installer.

dotnet-install: Downloading primary link https://dotnetcli.azureedge.net/dotnet/Sdk/3.1.300/dotnet-sdk-3.1.300-linux-x64.tar.gz
/var/local/git/grpc-dotnet/build/obj/dotnet-install.sh: line 908: http_code: unbound variable

**Comment by jtattermusch** [comment] 2021-03-18 11:11
Seems basically a dupe of https://github.com/grpc/grpc/issues/25737 (and you don't provide a failure link so it's impossible to inspect more in detail).

**Closed by jtattermusch** 2021-03-18 11:11 UTC
Labels: disposition/BUILDNURSE, kind/bug, lang/all wrapped languages, priority/P2
