### ISSUE TITLE
Pip install fails on Mac OS X 10.9 (Mavericks)

### ISSUE THREAD

**Issue by francbartoli** [grpc/grpc#15057] opened 2018-04-13 08:50 UTC
I'm facing with this as a dependency package while installing [firebase-admin](https://github.com/firebase/firebase-admin-python) python package within a python virtual environment. However trying to get the grpcio package directly it still fails:

### Clean virtual environment
```
$ pyenv virtualenv grpcio                                         
Requirement already satisfied: setuptools in /Users/geobart/.pyenv/versions/grpcio/lib/python3.6/site-packages
Requirement already satisfied: pip in /Users/geobart/.pyenv/versions/grpcio/lib/python3.6/site-packages
```

### Install grpcio 
```
$ pip install --upgrade grpcio==1.10.1
Collecting grpcio==1.10.1
  Using cached grpcio-1.10.1.tar.gz
Collecting six>=1.5.2 (from grpcio==1.10.1)
  Using cached six-1.11.0-py2.py3-none-any.whl
Collecting protobuf>=3.5.0.post1 (from grpcio==1.10.1)
  Downloading protobuf-3.5.2.post1-cp36-cp36m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl (1.2MB)
    100% |████████████████████████████████| 1.2MB 532kB/s
Requirement already up-to-date: setuptools in /Users/geobart/.pyenv/versions/grpcio/lib/python3.6/site-packages (from protobuf>=3.5.0.post1->grpcio==1.10.1)
Installing collected packages: six, protobuf, grpcio
  Running setup.py install for grpcio ... error
    Complete output from command /Users/geobart/.pyenv/versions/grpcio/bin/python -u -c "import setuptools, tokenize;__file__='/private/var/folders/f5/k25ptqd12nq2mt4v3cdncgk00000gn/T/pip-build-r5rao_ei/grpcio/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /var/folders/f5/k25ptqd12nq2mt4v3cdncgk00000gn/T/pip-1_pr87q6-record/install-record.txt --single-version-externally-managed --compile --install-headers /Users/geobart/.pyenv/versions/grpcio/include/site/python3.6/grpcio:
    Found cython-generated files...
    running install
    running build
    running build_py
    running build_project_metadata
    creating python_build
    creating python_build/lib.macosx-10.9-x86_64-3.6
    creating python_build/lib.macosx-10.9-x86_64-3.6/grpc
    copying src/python/grpcio/grpc/__init__.py -> python_build/lib.macosx-10.9-x86_64-3.6/grpc
    copying src/python/grpcio/grpc/_auth.py -> python_build/lib.macosx-10.9-x86_64-3.6/grpc
    copying src/python/grpcio/grpc/_channel.py -> python_build/lib.macosx-10.9-x86_64-3.6/grpc
    copying src/python/grpcio/grpc/_common.py -> python_build/lib.macosx-10.9-x86_64-3.6/grpc
    copying src/python/grpcio/grpc/_grpcio_metadata.py -> python_build/lib.macosx-10.9-x86_64-3.6/grpc
    copying src/python/grpcio/grpc/_interceptor.py -> python_build/lib.macosx-10.9-x86_64-3.6/grpc
    copying src/python/grpcio/grpc/_plugin_wrapping.py -> python_build/lib.macosx-10.9-x86_64-3.6/grpc
    copying src/python/grpcio/grpc/_server.py -> python_build/lib.macosx-10.9-x86_64-3.6/grpc
    copying src/python/grpcio/grpc/_utilities.py -> python_build/lib.macosx-10.9-x86_64-3.6/grpc
    creating python_build/lib.macosx-10.9-x86_64-3.6/grpc/_cython
    copying src/python/grpcio/grpc/_cython/__init__.py -> python_build/lib.macosx-10.9-x86_64-3.6/grpc/_cython
    creating python_build/lib.macosx-10.9-x86_64-3.6/grpc/beta
    copying src/python/grpcio/grpc/beta/__init__.py -> python_build/lib.macosx-10.9-x86_64-3.6/grpc/beta
    copying src/python/grpcio/grpc/beta/_client_adaptations.py -> python_build/lib.macosx-10.9-x86_64-3.6/grpc/beta
    copying src/python/grpcio/grpc/beta/_metadata.py -> python_build/lib.macosx-10.9-x86_64-3.6/grpc/beta
    copying src/python/grpcio/grpc/beta/_server_adaptations.py -> python_build/lib.macosx-10.9-x86_64-3.6/grpc/beta
    copying src/python/grpcio/grpc/beta/implementations.py -> python_build/lib.macosx-10.9-x86_64-3.6/grpc/beta
    copying src/python/grpcio/grpc/beta/interfaces.py -> python_build/lib.macosx-10.9-x86_64-3.6/grpc/beta
    copying src/python/grpcio/grpc/beta/utilities.py -> python_build/lib.macosx-10.9-x86_64-3.6/grpc/beta
    creating python_build/lib.macosx-10.9-x86_64-3.6/grpc/framework
    copying src/python/grpcio/grpc/framework/__init__.py -> python_build/lib.macosx-10.9-x86_64-3.6/grpc/framework
    creating python_build/lib.macosx-10.9-x86_64-3.6/grpc/_cython/_cygrpc
    copying src/python/grpcio/grpc/_cython/_cygrpc/__init__.py -> python_build/lib.macosx-10.9-x86_64-3.6/grpc/_cython/_cygrpc
    creating python_build/lib.macosx-10.9-x86_64-3.6/grpc/framework/common
    copying src/python/grpcio/grpc/framework/common/__init__.py -> python_build/lib.macosx-10.9-x86_64-3.6/grpc/framework/common
    copying src/python/grpcio/grpc/framework/common/cardinality.py -> python_build/lib.macosx-10.9-x86_64-3.6/grpc/framework/common
    copying src/python/grpcio/grpc/framework/common/style.py -> python_build/lib.macosx-10.9-x86_64-3.6/grpc/framework/common
    creating python_build/lib.macosx-10.9-x86_64-3.6/grpc/framework/foundation
    copying src/python/grpcio/grpc/framework/foundation/__init__.py -> python_build/lib.macosx-10.9-x86_64-3.6/grpc/framework/foundation
    copying src/python/grpcio/grpc/framework/foundation/abandonment.py -> python_build/lib.macosx-10.9-x86_64-3.6/grpc/framework/foundation
    copying src/python/grpcio/grpc/framework/foundation/callable_util.py -> python_build/lib.macosx-10.9-x86_64-3.6/grpc/framework/foundation
    copying src/python/grpcio/grpc/framework/foundation/future.py -> python_build/lib.macosx-10.9-x86_64-3.6/grpc/framework/foundation
    copying src/python/grpcio/grpc/framework/foundation/logging_pool.py -> python_build/lib.macosx-10.9-x86_64-3.6/grpc/framework/foundation
    copying src/python/grpcio/grpc/framework/foundation/stream.py -> python_build/lib.macosx-10.9-x86_64-3.6/grpc/framework/foundation
    copying src/python/grpcio/grpc/framework/foundation/stream_util.py -> python_build/lib.macosx-10.9-x86_64-3.6/grpc/framework/foundation
    creating python_build/lib.macosx-10.9-x86_64-3.6/grpc/framework/interfaces
    copying src/python/grpcio/grpc/framework/interfaces/__init__.py -> python_build/lib.macosx-10.9-x86_64-3.6/grpc/framework/interfaces
    creating python_build/lib.macosx-10.9-x86_64-3.6/grpc/framework/interfaces/base
    copying src/python/grpcio/grpc/framework/interfaces/base/__init__.py -> python_build/lib.macosx-10.9-x86_64-3.6/grpc/framework/interfaces/base
    copying src/python/grpcio/grpc/framework/interfaces/base/base.py -> python_build/lib.macosx-10.9-x86_64-3.6/grpc/framework/interfaces/base
    copying src/python/grpcio/grpc/framework/interfaces/base/utilities.py -> python_build/lib.macosx-10.9-x86_64-3.6/grpc/framework/interfaces/base
    creating python_build/lib.macosx-10.9-x86_64-3.6/grpc/framework/interfaces/face
    copying src/python/grpcio/grpc/framework/interfaces/face/__init__.py -> python_build/lib.macosx-10.9-x86_64-3.6/grpc/framework/interfaces/face
    copying src/python/grpcio/grpc/framework/interfaces/face/face.py -> python_build/lib.macosx-10.9-x86_64-3.6/grpc/framework/interfaces/face
    copying src/python/grpcio/grpc/framework/interfaces/face/utilities.py -> python_build/lib.macosx-10.9-x86_64-3.6/grpc/framework/interfaces/face
    creating python_build/lib.macosx-10.9-x86_64-3.6/grpc/_cython/_credentials
    copying src/python/grpcio/grpc/_cython/_credentials/roots.pem -> python_build/lib.macosx-10.9-x86_64-3.6/grpc/_cython/_credentials
    running build_ext
    b'[C]       Compiling src/boringssl/err_data.c\n'
    b"In file included from src/boringssl/err_data.c:18:\nIn file included from /usr/local/Cellar/openssl/1.0.2o_1/include/openssl/err.h:115:\n/usr/local/Cellar/openssl/1.0.2o_1/include/openssl/e_os2.h:276:11: error: 'OPENSSL_EXPORT' macro redefined [-Werror]\n#  define OPENSSL_EXPORT extern\n          ^\nthird_party/boringssl/include/openssl/base.h:178:9: note: previous definition is here\n#define OPENSSL_EXPORT\n        ^\nIn file included from src/boringssl/err_data.c:18:\nIn file included from /usr/local/Cellar/openssl/1.0.2o_1/include/openssl/err.h:122:\n/usr/local/Cellar/openssl/1.0.2o_1/include/openssl/ossl_typ.h:83:31: error: redefinition of typedef 'ASN1_INTEGER' is a C11 feature [-Werror,-Wtypedef-redefinition]\ntypedef struct asn1_string_st ASN1_INTEGER;\n                              ^\nthird_party/boringssl/include/openssl/base.h:253:31: note: previous definition is here\ntypedef struct asn1_string_st ASN1_INTEGER;\n                              ^\nIn file included from src/boringssl/err_data.c:18:\nIn file included from /usr/local/Cellar/openssl/1.0.2o_1/include/openssl/err.h:122:\n/usr/local/Cellar/openssl/1.0.2o_1/include/openssl/ossl_typ.h:84:31: error: redefinition of typedef 'ASN1_ENUMERATED' is a C11 feature [-Werror,-Wtypedef-redefinition]\ntypedef struct asn1_string_st ASN1_ENUMERATED;\n                              ^\nthird_party/boringssl/include/openssl/base.h:249:31: note: previous definition is here\ntypedef struct asn1_string_st ASN1_ENUMERATED;\n                              ^\nIn file included from src/boringssl/err_data.c:18:\nIn file included from /usr/local/Cellar/openssl/1.0.2o_1/include/openssl/err.h:122:\n/usr/local/Cellar/openssl/1.0.2o_1/include/openssl/ossl_typ.h:85:31: error: redefinition of typedef 'ASN1_BIT_STRING' is a C11 feature [-Werror,-Wtypedef-redefinition]\ntypedef struct asn1_string_st ASN1_BIT_STRING;\n                              ^\nthird_party/boringssl/include/openssl/base.h:247:31: note: previous definition is here\ntypedef struct asn1_string_st ASN1_BIT_STRING;\n                              ^\nIn file included from src/boringssl/err_data.c:18:\nIn file included from /usr/local/Cellar/openssl/1.0.2o_1/include/openssl/err.h:122:\n/usr/local/Cellar/openssl/1.0.2o_1/include/openssl/ossl_typ.h:86:31: error: redefinition of typedef 'ASN1_OCTET_STRING' is a C11 feature [-Werror,-Wtypedef-redefinition]\ntypedef struct asn1_string_st ASN1_OCTET_STRING;\n                              ^\nthird_party/boringssl/include/openssl/base.h:254:31: note: previous definition is here\ntypedef struct asn1_string_st ASN1_OCTET_STRING;\n                              ^\nIn file included from src/boringssl/err_data.c:18:\nIn file included from /usr/local/Cellar/openssl/1.0.2o_1/include/openssl/err.h:122:\n/usr/local/Cellar/openssl/1.0.2o_1/include/openssl/ossl_typ.h:87:31: error: redefinition of typedef 'ASN1_PRINTABLESTRING' is a C11 feature [-Werror,-Wtypedef-redefinition]\ntypedef struct asn1_string_st ASN1_PRINTABLESTRING;\n                              ^\nthird_party/boringssl/include/openssl/base.h:255:31: note: previous definition is here\ntypedef struct asn1_string_st ASN1_PRINTABLESTRING;\n                              ^\nIn file included from src/boringssl/err_data.c:18:\nIn file included from /usr/local/Cellar/openssl/1.0.2o_1/include/openssl/err.h:122:\n/usr/local/Cellar/openssl/1.0.2o_1/include/openssl/ossl_typ.h:88:31: error: redefinition of typedef 'ASN1_T61STRING' is a C11 feature [-Werror,-Wtypedef-redefinition]\ntypedef struct asn1_string_st ASN1_T61STRING;\n                              ^\nthird_party/boringssl/include/openssl/base.h:257:31: note: previous definition is here\ntypedef struct asn1_string_st ASN1_T61STRING;\n                              ^\nIn file included from src/boringssl/err_data.c:18:\nIn file included from /usr/local/Cellar/openssl/1.0.2o_1/include/openssl/err.h:122:\n/usr/local/Cellar/openssl/1.0.2o_1/include/openssl/ossl_typ.h:89:31: error: redefinition of typedef 'ASN1_IA5STRING' is a C11 feature [-Werror,-Wtypedef-redefinition]\ntypedef struct asn1_string_st ASN1_IA5STRING;\n                              ^\nthird_party/boringssl/include/openssl/base.h:252:31: note: previous definition is here\ntypedef struct asn1_string_st ASN1_IA5STRING;\n                              ^\nIn file included from src/boringssl/err_data.c:18:\nIn file included from /usr/local/Cellar/openssl/1.0.2o_1/include/openssl/err.h:122:\n/usr/local/Cellar/openssl/1.0.2o_1/include/openssl/ossl_typ.h:90:31: error: redefinition of typedef 'ASN1_GENERALSTRING' is a C11 feature [-Werror,-Wtypedef-redefinition]\ntypedef struct asn1_string_st ASN1_GENERALSTRING;\n                              ^\nthird_party/boringssl/include/openssl/base.h:251:31: note: previous definition is here\ntypedef struct asn1_string_st ASN1_GENERALSTRING;\n                              ^\nIn file included from src/boringssl/err_data.c:18:\nIn file included from /usr/local/Cellar/openssl/1.0.2o_1/include/openssl/err.h:122:\n/usr/local/Cellar/openssl/1.0.2o_1/include/openssl/ossl_typ.h:91:31: error: redefinition of typedef 'ASN1_UNIVERSALSTRING' is a C11 feature [-Werror,-Wtypedef-redefinition]\ntypedef struct asn1_string_st ASN1_UNIVERSALSTRING;\n                              ^\nthird_party/boringssl/include/openssl/base.h:259:31: note: previous definition is here\ntypedef struct asn1_string_st ASN1_UNIVERSALSTRING;\n                              ^\nIn file included from src/boringssl/err_data.c:18:\nIn file included from /usr/local/Cellar/openssl/1.0.2o_1/include/openssl/err.h:122:\n/usr/local/Cellar/openssl/1.0.2o_1/include/openssl/ossl_typ.h:92:31: error: redefinition of typedef 'ASN1_BMPSTRING' is a C11 feature [-Werror,-Wtypedef-redefinition]\ntypedef struct asn1_string_st ASN1_BMPSTRING;\n                              ^\nthird_party/boringssl/include/openssl/base.h:248:31: note: previous definition is here\ntypedef struct asn1_string_st ASN1_BMPSTRING;\n                              ^\nIn file included from src/boringssl/err_data.c:18:\nIn file included from /usr/local/Cellar/openssl/1.0.2o_1/include/openssl/err.h:122:\n/usr/local/Cellar/openssl/1.0.2o_1/include/openssl/ossl_typ.h:93:31: error: redefinition of typedef 'ASN1_UTCTIME' is a C11 feature [-Werror,-Wtypedef-redefinition]\ntypedef struct asn1_string_st ASN1_UTCTIME;\n                              ^\nthird_party/boringssl/include/openssl/base.h:260:31: note: previous definition is here\ntypedef struct asn1_string_st ASN1_UTCTIME;\n                              ^\nIn file included from src/boringssl/err_data.c:18:\nIn file included from /usr/local/Cellar/openssl/1.0.2o_1/include/openssl/err.h:122:\n/usr/local/Cellar/openssl/1.0.2o_1/include/openssl/ossl_typ.h:94:31: error: redefinition of typedef 'ASN1_TIME' is a C11 feature [-Werror,-Wtypedef-redefinition]\ntypedef struct asn1_string_st ASN1_TIME;\n                              ^\nthird_party/boringssl/include/openssl/base.h:258:31: note: previous definition is here\ntypedef struct asn1_string_st ASN1_TIME;\n                              ^\nIn file included from src/boringssl/err_data.c:18:\nIn file included from /usr/local/Cellar/openssl/1.0.2o_1/include/openssl/err.h:122:\n/usr/local/Cellar/openssl/1.0.2o_1/include/openssl/ossl_typ.h:95:31: error: redefinition of typedef 'ASN1_GENERALIZEDTIME' is a C11 feature [-Werror,-Wtypedef-redefinition]\ntypedef struct asn1_string_st ASN1_GENERALIZEDTIME;\n                              ^\nthird_party/boringssl/include/openssl/base.h:250:31: note: previous definition is here\ntypedef struct asn1_string_st ASN1_GENERALIZEDTIME;\n                              ^\nIn file included from src/boringssl/err_data.c:18:\nIn file included from /usr/local/Cellar/openssl/1.0.2o_1/include/openssl/err.h:122:\n/usr/local/Cellar/openssl/1.0.2o_1/include/openssl/ossl_typ.h:96:31: error: redefinition of typedef 'ASN1_VISIBLESTRING' is a C11 feature [-Werror,-Wtypedef-redefinition]\ntypedef struct asn1_string_st ASN1_VISIBLESTRING;\n                              ^\nthird_party/boringssl/include/openssl/base.h:262:31: note: previous definition is here\ntypedef struct asn1_string_st ASN1_VISIBLESTRING;\n                              ^\nIn file included from src/boringssl/err_data.c:18:\nIn file included from /usr/local/Cellar/openssl/1.0.2o_1/include/openssl/err.h:122:\n/usr/local/Cellar/openssl/1.0.2o_1/include/openssl/ossl_typ.h:97:31: error: redefinition of typedef 'ASN1_UTF8STRING' is a C11 feature [-Werror,-Wtypedef-redefinition]\ntypedef struct asn1_string_st ASN1_UTF8STRING;\n                              ^\nthird_party/boringssl/include/openssl/base.h:261:31: note: previous definition is here\ntypedef struct asn1_string_st ASN1_UTF8STRING;\n                              ^\nIn file included from src/boringssl/err_data.c:18:\nIn file included from /usr/local/Cellar/openssl/1.0.2o_1/include/openssl/err.h:122:\n/usr/local/Cellar/openssl/1.0.2o_1/include/openssl/ossl_typ.h:98:31: error: redefinition of typedef 'ASN1_STRING' is a C11 feature [-Werror,-Wtypedef-redefinition]\ntypedef struct asn1_string_st ASN1_STRING;\n                              ^\nthird_party/boringssl/include/openssl/base.h:256:31: note: previous definition is here\ntypedef struct asn1_string_st ASN1_STRING;\n                              ^\nIn file included from src/boringssl/err_data.c:18:\nIn file included from /usr/local/Cellar/openssl/1.0.2o_1/include/openssl/err.h:122:\n/usr/local/Cellar/openssl/1.0.2o_1/include/openssl/ossl_typ.h:99:13: error: redefinition of typedef 'ASN1_BOOLEAN' is a C11 feature [-Werror,-Wtypedef-redefinition]\ntypedef int ASN1_BOOLEAN;\n            ^\nthird_party/boringssl/include/openssl/base.h:242:13: note: previous definition is here\ntypedef int ASN1_BOOLEAN;\n            ^\nIn file included from src/boringssl/err_data.c:18:\nIn file included from /usr/local/Cellar/openssl/1.0.2o_1/include/openssl/err.h:122:\n/usr/local/Cellar/openssl/1.0.2o_1/include/openssl/ossl_typ.h:100:13: error: redefinition of typedef 'ASN1_NULL' is a C11 feature [-Werror,-Wtypedef-redefinition]\ntypedef int ASN1_NULL;\n            ^\nthird_party/boringssl/include/openssl/base.h:243:13: note: previous definition is here\ntypedef int ASN1_NULL;\n            ^\nfatal error: too many errors emitted, stopping now [-ferror-limit=]\n20 errors generated.\nmake: *** [/private/var/folders/f5/k25ptqd12nq2mt4v3cdncgk00000gn/T/pip-build-r5rao_ei/grpcio/objs/opt/src/boringssl/err_data.o] Error 1\n"
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/f5/k25ptqd12nq2mt4v3cdncgk00000gn/T/pip-build-r5rao_ei/grpcio/setup.py", line 311, in <module>
        cmdclass=COMMAND_CLASS,
      File "/Users/geobart/.pyenv/versions/grpcio/lib/python3.6/site-packages/setuptools/__init__.py", line 129, in setup
        return distutils.core.setup(**attrs)
      File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/Users/geobart/.pyenv/versions/grpcio/lib/python3.6/site-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/command/install.py", line 545, in run
        self.run_command('build')
      File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/command/build.py", line 135, in run
        self.run_command(cmd_name)
      File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/Users/geobart/.pyenv/versions/grpcio/lib/python3.6/site-packages/setuptools/command/build_ext.py", line 78, in run
        _build_ext.run(self)
      File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/command/build_ext.py", line 339, in run
        self.build_extensions()
      File "/private/var/folders/f5/k25ptqd12nq2mt4v3cdncgk00000gn/T/pip-build-r5rao_ei/grpcio/src/python/grpcio/commands.py", line 278, in build_extensions
        raise Exception("make command failed!")
    Exception: make command failed!

    ----------------------------------------
Command "/Users/geobart/.pyenv/versions/grpcio/bin/python -u -c "import setuptools, tokenize;__file__='/private/var/folders/f5/k25ptqd12nq2mt4v3cdncgk00000gn/T/pip-build-r5rao_ei/grpcio/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /var/folders/f5/k25ptqd12nq2mt4v3cdncgk00000gn/T/pip-1_pr87q6-record/install-record.txt --single-version-externally-managed --compile --install-headers /Users/geobart/.pyenv/versions/grpcio/include/site/python3.6/grpcio" failed with error code 1 in /private/var/folders/f5/k25ptqd12nq2mt4v3cdncgk00000gn/T/pip-build-r5rao_ei/grpcio/
```
 
### Environment

- Mac OS X 10.9.5
- Python 3.6.5 (still happening with 2.7.13)
- pip 9.0.3
- openssl: stable 1.0.2o
- gcc --version
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 6.0 (clang-600.0.57) (based on LLVM 3.5svn)
Target: x86_64-apple-darwin13.4.0
Thread model: posix

**Comment by francbartoli** [comment] 2018-04-14 20:17
@nathanielmanistaatgoogle I know it is quite old but still works well for python development :)

**Comment by mehrdada** [comment] 2018-04-14 20:38
@francbartoli  I wonder if you can get it to compile by removing the `OpenSSL` tree installed by `brew` as it seems to be picking up those headers instead of the BoringSSL headers shipped inside the Python source package.  If that does not work, I am not sure what else we can do as I don't even have any old Macs lying around capable of running 10.9 to experiment. Looks like Apple no longer supports 10.9 (according to Wikipedia it's "unsupported as of September 2016"). We certainly do not have 10.9 running in our CI infrastructure to ensure our tests run and it won't regress, so it falls under *community support only*.

**Comment by mehrdada** [comment] 2018-04-20 17:38
There's a possibility that this shares root cause (Clang 6 build issues) with https://github.com/grpc/grpc-node/issues/267 and https://github.com/grpc/grpc/issues/15010

**Comment by francbartoli** [comment] 2018-04-21 08:10
Update: it does compile with py3. For now I'm going through a virtual environment with that version of python

**Comment by nicolasnoble** [comment] 2018-04-27 05:25
I would add that while we currently don't have any test for it, Mavericks should be in our supported matrix, at least in tier 2 or 3.

**Comment by nathanielmanistaatgoogle** [comment] 2018-05-15 00:51
Closing; I don't think we're going to take any action to fix issues on Mavericks without at least establishing that multiple users are affected and that "upgrade to Python 3" doesn't work as a resolution.

**Closed by nathanielmanistaatgoogle** 2018-05-15 00:51 UTC
Labels: area/build, lang/Python, platform/macOS, priority/P3
