### ISSUE TITLE
UnboundLocalError: local variable 'raw_response' referenced before assignment

### ISSUE THREAD

**Issue by kovan** [grpc/grpc#31227] opened 2022-10-04 03:41 UTC
### What version of gRPC and what language are you using?

1.49.0, Python

### What operating system (Linux, Windows,...) and version?

Linux on WSL

### What runtime / compiler are you using (e.g. python version or version of gcc)

Python 3.10.6

### What did you do?

I have no idea.

### What did you expect to see?

I am just going to leave the stack trace.
My code is failing and maybe it has something to do with this error:

```python

[generate] ----------------------------
[generate] Traceback (most recent call last):
[generate]   File "/app/videosdb/downloader.py", line 172, in _process_video
[generate]     _, video = await self.api.get_video_info(video_id)
[generate]   File "/app/videosdb/youtube_api.py", line 111, in get_video_info
[generate]     return await self._request_one(url, params)
[generate]   File "/app/videosdb/youtube_api.py", line 156, in _request_one
[generate]     item = await anext(generator)
[generate]   File "/app/videosdb/youtube_api.py", line 163, in generator
[generate]     async for page in pages:
[generate]   File "/app/videosdb/youtube_api.py", line 196, in _request_with_cache
[generate]     async for page in self.db.stream("cache/%s/pages" % cache_id):
[generate]   File "/home/appuser/.cache/pypoetry/virtualenvs/videosdb-9TtSrW0h-py3.10/lib/python3.10/site-packages/google/cloud/firestore_v1/async_collection.py", line 241, in stream
[generate]     async for d in query.stream(transaction=transaction, **kwargs):
[generate]   File "/home/appuser/.cache/pypoetry/virtualenvs/videosdb-9TtSrW0h-py3.10/lib/python3.10/site-packages/google/cloud/firestore_v1/async_query.py", line 264, in stream
[generate]     async for response in response_iterator:
[generate]   File "/home/appuser/.cache/pypoetry/virtualenvs/videosdb-9TtSrW0h-py3.10/lib/python3.10/site-packages/google/api_core/grpc_helpers_async.py", line 102, in _wrapped_aiter
[generate]     async for response in self._call:  # pragma: no branch
[generate]   File "/home/appuser/.cache/pypoetry/virtualenvs/videosdb-9TtSrW0h-py3.10/lib/python3.10/site-packages/grpc/aio/_call.py", line 323, in _fetch_stream_responses
[generate]     message = await self._read()
[generate]   File "/home/appuser/.cache/pypoetry/virtualenvs/videosdb-9TtSrW0h-py3.10/lib/python3.10/site-packages/grpc/aio/_call.py", line 346, in _read
[generate]     if raw_response is cygrpc.EOF:
[generate] UnboundLocalError: local variable 'raw_response' referenced before assignment

```

**Comment by lesnek** [comment] 2022-10-04 12:14
We encounter the same issue when we use graceful termination of the container.

[Here](https://github.com/grpc/grpc/blob/master/src/python/grpcio/grpc/aio/_call.py#L341) in _call.py it is excepted so the raw_response was never assigned.

We didn't encounter bigger as it is at the end of termination but it could be dangerous.

Can we ask for some default value of raw_response or better exception handling?

**Comment by kovan** [comment] 2022-10-06 16:19
I updated to version 0.49.1 of Python gRPC package, and same thing happens.

Looks like it happens when an operation is in some kind of waiting or pending state and it gets cancelled. 
This is a guess only, not a final diagnosis.

**Comment by gnossen** [comment] 2022-12-16 19:55
This code

```python
def foo():
    return 3

a = foo()
```

results in this bytecode:

```
  0           0 RESUME                   0

  1           2 LOAD_CONST               0 (<code object foo at 0x5614c2e6bfc0, file "example.py", line 1>)
              4 MAKE_FUNCTION            0
              6 STORE_NAME               0 (foo)

  4           8 PUSH_NULL
             10 LOAD_NAME                0 (foo)
             12 PRECALL                  0
             16 CALL                     0
             26 STORE_NAME               1 (a)
             28 LOAD_CONST               1 (None)
             30 RETURN_VALUE

Disassembly of <code object foo at 0x5614c2e6bfc0, file "example.py", line 1>:
  1           0 RESUME                   0

  2           2 LOAD_CONST               1 (3)
              4 RETURN_VALUE
```

If `foo()` raises an exception, the `STORE_NAME` instruction is never executed. I assume something similar is happening here.

But if we've reached [this line](https://github.com/grpc/grpc/blob/9e7c8bff5518cf86ab61210589b0bfca8cbc64c7/src/python/grpcio/grpc/aio/_call.py#L346), that would mean that we made it through [this call](https://github.com/grpc/grpc/blob/9e7c8bff5518cf86ab61210589b0bfca8cbc64c7/src/python/grpcio/grpc/aio/_call.py#L344) without an exception being raised. But this implies that [we received a status code of `OK`](https://github.com/grpc/grpc/blob/9e7c8bff5518cf86ab61210589b0bfca8cbc64c7/src/python/grpcio/grpc/aio/_call.py#L235), which is quite odd considering that there was an exception when receiving the message.

Can you please add any more logs you might have? Setting the following environment variables would also help us debug this issue:

```
export GRPC_VERBOSITY=DEBUG
export GRPC_TRACE=all,-timer,-timer_check
```

**Comment by kovan** [comment] 2022-12-16 20:41
Sorry, I can't provide logs because we refactored the code and is not happening anymore.

**Comment by XuanWang-Amos** [comment] 2022-12-21 19:36
Closing since it's not happening anymore, but if anyone see this please let us know and please include full logs.

**Closed by XuanWang-Amos** 2022-12-21 19:36 UTC
Labels: kind/bug, lang/Python, priority/P2, disposition/requires reporter action

**Comment by njhill** [comment] 2022-12-27 05:03
I also ran into this with 1.51.1, appears to be a race condition and I have proposed a fix in #31982.

**Comment by gnossen** [comment] 2023-01-04 01:30
It took me a while to figure out exactly what was going on here, but after finally reproducing it, I think I have a clear picture:

- The cancellation has to happen while [this call](https://github.com/grpc/grpc/blob/9e7c8bff5518cf86ab61210589b0bfca8cbc64c7/src/python/grpcio/grpc/aio/_call.py#L340) is in progress.
- A response with status code OK has to be received by the time [this line](https://github.com/grpc/grpc/blob/9e7c8bff5518cf86ab61210589b0bfca8cbc64c7/src/python/grpcio/grpc/aio/_call.py#L342) executes 
- [`self.cancel`](https://github.com/grpc/grpc/blob/9e7c8bff5518cf86ab61210589b0bfca8cbc64c7/src/python/grpcio/grpc/aio/_call.py#L343) is not called because [`self.cancelled()`](https://github.com/grpc/grpc/blob/9e7c8bff5518cf86ab61210589b0bfca8cbc64c7/src/python/grpcio/grpc/aio/_call.py#L342) returns False because it hasn't been manually cancelled and [it hasn't received a `CANCELLED` status](https://github.com/grpc/grpc/blob/a414dbd304aa14c7066a110e2ce4e6e1ff748fcf/src/python/grpcio/grpc/_cython/_cygrpc/aio/call.pyx.pxi#L233)
- `_raise_for_status` doesn't raise `asyncio.CancelledError` [here](https://github.com/grpc/grpc/blob/a414dbd304aa14c7066a110e2ce4e6e1ff748fcf/src/python/grpcio/grpc/aio/_call.py#L233) (as it was expected to) because `is_locally_cancelled` is False because we never called `call.cancel()` for the above mentioned reasons.

@njhill I think your PR is the right solution to this and I now have a (seemingly) deterministic unit test showing that it fixes the problem.

**Comment by njhill** [comment] 2023-01-04 03:09
Thanks @gnossen! And good job reproducing it.
