### ISSUE TITLE
client stuck with "StatusCode.INTERNAL, GOAWAY received" after server restarted

### ISSUE THREAD

**Issue by sammy-tam** [grpc/grpc#14088] opened 2018-01-19 19:35 UTC
Please answer these questions before submitting your issue. 
 
### Should this be an issue in the gRPC issue tracker?
Yes
 
### What version of gRPC and what language are you using?
 1.8.4
 
### What operating system (Linux, Windows, …) and version?
 Linux, OLE 7.2
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
 python 3.6.4
 
### What did you do?
Client is calling RPC Server every second, and while its running normally, restart RPC Server process.  (localhost) TWICE.
 
### What did you expect to see?
 Client be able to reconnect to server successfully.
 
### What did you see instead?
The first restart, it will always return (Internal, Connect Failed), as expected. 

Once this message is seen, restart the RPC Server again, it will return 
`<_Rendezvous of RPC that terminated with (StatusCode.INTERNAL, GOAWAY received)>`

Once it gets to this state, it is stuck forever.  I have tried all different options, including re-creating the channel and stub once this go away is received.  They seem to stay this way until I restart my client process.

**Comment by severin-lemaignan** [comment] 2018-01-22 15:21
Same issue here (same version of `grpc`). I can reproduce the issue with both Python 2.7 and Python 3.6.

MWE using the `helloworld` example provided with grpc:

```python
from concurrent import futures

import grpc

import helloworld_pb2
import helloworld_pb2_grpc

import greeter_server

def start_server():
  server = grpc.server(futures.ThreadPoolExecutor(max_workers=10))
  helloworld_pb2_grpc.add_GreeterServicer_to_server(greeter_server.Greeter(), server)
  server.add_insecure_port('[::]:50051')
  server.start()
  return server

class Client:
    def __init__(self):
      channel = grpc.insecure_channel('localhost:50051')
      self.stub = helloworld_pb2_grpc.GreeterStub(channel)

    def call(self):
      response = self.stub.SayHello(helloworld_pb2.HelloRequest(name='you'))
      print("Greeter client received: " + response.message)


if __name__ == '__main__':

    client = Client()

    server = start_server()
    client.call()
    server.stop(1).wait()

    server = start_server()
    client.call() # exception raised here!!
    server.stop(1).wait()
```

Output:
```
$ python mwe.py 
Greeter client received: Hello, you!
Traceback (most recent call last):
  File "mwe.py", line 53, in <module>
    client.call()
  File "mwe.py", line 40, in call
    response = self.stub.SayHello(helloworld_pb2.HelloRequest(name='you'))
  File "/home/slemaignan/.local/lib/python2.7/site-packages/grpc/_channel.py", line 484, in __call__
    return _end_unary_response_blocking(state, call, False, deadline)
  File "/home/slemaignan/.local/lib/python2.7/site-packages/grpc/_channel.py", line 434, in _end_unary_response_blocking
    raise _Rendezvous(state, None, None, deadline)
grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with (StatusCode.INTERNAL, GOAWAY received)>
```

**Comment by sammy-tam** [comment] 2018-01-23 16:30
I downgraded back to 1.7.3. and it doesn't seem to have this problem

**Comment by Thaina** [comment] 2018-02-06 06:24
Using firestore from GoogleCloudDotnet and got this error too

Using it on serverless aws lambda might be related

**Comment by clusby** [comment] 2018-02-14 16:11
I see the same thing - Python 2.7, grpc 1.9.1

I see the issue while using pytest for unit tests (multiple restarts of the server)

**Comment by ZurgInq** [comment] 2018-02-15 07:54
I see the same thing - Ruby 2.4.2, grpc 1.8.0

**Comment by Thaina** [comment] 2018-02-15 08:05
I had discussion with the team and it seem GOAWAY was an error that could be thrown when we try to spam API to the limit of short period

**Comment by lawrence-iviani** [comment] 2018-02-20 14:42
Hi There,
same here: Python  (Anaconda) 3.6.3, grpcio 1.8.3. 
I have some 3 services running with the same grpc server, and there are several testcases in 3 Unit Tests.
Every unittest start a server (at class setup) and stop at class tear down. This is repeated 3 times (one per UT). 
This happen since I have added a new test, the first test case fail for this reason:
<_Rendezvous of RPC that terminated with (StatusCode.INTERNAL, GOAWAY received)>
The other test cases run smoothly

**Comment by jtattermusch** [comment] 2018-02-26 15:53
@dgquintas   who would be the best person to look into this? It's almost certainly a C core issue (seen in multiple languages).

**Comment by dgquintas** [comment] 2018-02-26 17:56
This is very likely fixed by https://github.com/grpc/grpc/pull/13932, which will be part of the 1.10 release.

**Comment by jtattermusch** [comment] 2018-03-02 16:28
Can we get a confirmation that this was fixed?

**Comment by Disturbing** [comment] 2018-03-12 03:24
This error occurs after 2-3 days of a service running for me. This is the 3rd time I ran into it then googled the issue. No logs to help.

I upgraded to csharp v 1.10.0 across my dev cluster and will let you guys know this week if I have a confirmed issue resolved by end of the week.

Fingers crossed!

**Comment by ZurgInq** [comment] 2018-03-12 06:31
In my case, the problem resolved

Ruby 2.4.2, grpc 1.9.1

1. start server
2. run any requests - success
3. restart server
4. run any request - always failed with error "GOAWAY received" or "Deadline"

Ruby 2.4.2, grpc 1.10.0

1. start server
2. run any requests - success
3. restart server
4. run any requests - success

**Comment by Disturbing** [comment] 2018-03-20 06:50
CSharp server has been running for 10 days now without issues. My case is closed for the randomness of goaway happening after 2-3 days.

**Closed** 2018-03-20 07:12 UTC
Labels: area/core, lang/C#, lang/Python, lang/ruby, priority/P1
