### ISSUE TITLE
FLAKE: Kokoro - cloud_to_prod_auth:default:php7:per_rpc_creds

### ISSUE THREAD

**Issue by apolcyn** [grpc/grpc#11995] opened 2017-07-31 18:23 UTC
Also looks similar to https://github.com/grpc/grpc/issues/11967, in that the failure is unavailable - filing specific for php though.

```
2017-07-28 17:47:29,353 Running test case per_rpc_creds
Call did not complete successfully. Status object:
object(stdClass)#7 (3) {
  ["metadata"]=>
  array(0) {
  }
  ["code"]=>
  int(14)
  ["details"]=>
  string(20) "Endpoint read failed"
}

2017-07-28 17:47:29,353 FAILED: cloud_to_prod_auth:default:php7:per_rpc_creds [ret=1, pid=22811]
```

**Comment by adelez** [comment] 2017-07-31 20:43
Please post the link to the Internal CI result if you still have it.

**Comment by apolcyn** [comment] 2017-07-31 20:55
sponge log is that same is in

build page in https://kokoro.corp.google.com/job/grpc/job/ubuntu/job/pull_request/job/grpc_interop_toprod/194/https://kokoro.corp.google.com/job/grpc/job/ubuntu/job/pull_request/job/grpc_interop_toprod/194/

sponge failure log in https://sponge.corp.google.com/target?id=4134491f-6fad-4e3b-8273-a00062fdbd18&target=grpc/ubuntu/pull_request/grpc_interop_toprod&searchFor=&show=ALL&sortBy=STATUS

**Comment by ZhouyihaiDing** [comment] 2017-11-06 20:25
Dupe of #10763

**Closed by ZhouyihaiDing** 2017-11-06 20:25 UTC
Labels: kind/bug/flaky test, lang/php
