### ISSUE TITLE
Interop flake: cloud_to_cloud:java:http2_server:rst_after_data

### ISSUE THREAD

**Issue by vjpai** [grpc/grpc#12052] opened 2017-08-03 02:17 UTC
https://grpc-testing.appspot.com/job/gRPC_interop_pull_requests/15835/testReport/junit/(root)/tests/cloud_to_cloud_java_http2_server_rst_after_data/

Error Message

Failure
Stacktrace

Aug 02, 2017 6:22:47 PM io.grpc.testing.integration.Http2Client run
INFO: Running test rst_after_data
Exception in thread "main" java.lang.AssertionError: Operation timed out
	at io.grpc.testing.integration.Http2Client$Tester.rstAfterData(Http2Client.java:231)
	at io.grpc.testing.integration.Http2Client$Tester.access$400(Http2Client.java:201)
	at io.grpc.testing.integration.Http2Client.runTest(Http2Client.java:182)
	at io.grpc.testing.integration.Http2Client.run(Http2Client.java:167)
	at io.grpc.testing.integration.Http2Client.main(Http2Client.java:75)

**Comment by ericgribkoff** [comment] 2017-08-18 06:54
Same root cause as reported in https://github.com/grpc/grpc/issues/10390, and now fixed with a larger timeout in the Java client (https://github.com/grpc/grpc-java/pull/3333)

**Closed by ericgribkoff** 2017-08-18 06:54 UTC
Labels: infra/BUILDPONY, lang/Java
