### ISSUE TITLE
Very slow to start RPC's on Mac OS with grpc-0.11.0

### ISSUE THREAD

**Issue by TassoKarkanisADSK** [grpc/grpc#3319] opened 2015-09-10 20:01 UTC
I have a Mac Pro with 8 cores and 16 hyperthreads running Mac OS 10.10.5.  I compiled grpc-0.11.0 with make following the instructions.  I then compiled the greeter C++ example in examples/cpp/helloworld and started the server.  I ran the client (on the same machine) repeatedly with the following output:
    $ time ./greeter_client 
    Greeter received: Hello world
    
    real	0m2.468s
    user	0m0.402s
    sys	0m1.989s
    $ time ./greeter_client 
    Greeter received: Hello world
    
    real	0m12.009s
    user	0m2.092s
    sys	0m10.404s
    $ time ./greeter_client 
    Greeter received: Hello world
    
    real	0m10.992s
    user	0m1.907s
    sys	0m9.507s
    $ time ./greeter_client 
    Greeter received: Hello world
    
    real	0m10.005s
    user	0m1.784s
    sys	0m8.671s
    $ time ./greeter_client 
    Greeter received: Hello world
    
    real	0m8.947s
    user	0m1.571s
    sys	0m7.698s
    $ time ./greeter_client 
    Greeter received: Hello world
    
    real	0m3.009s
    user	0m0.509s
    sys	0m2.519s

Note that these trials have a high variation in real time, and some of them have very long system times.  During this time, "top" shows the greeter_client process as running at 105% CPU time.  When running under "dtruss", the greeter_client took 15 seconds and executed about 48,000 system calls.

We also tried grpc-0.11.0 on a MacBook Pro with the same OS version.  The execution times of the greeter client were not as bad, but it still took 4 seconds once in every 10 trials.

I would be happy to supply more information.  Just ask :-).

**Comment by ctiller** [comment] 2015-09-16 17:59
I'm still unable to reproduce this (but working on it).

In the meantime, could you patch in #3350, and run with `GRPC_TRACE=tcp`

**Comment by ctiller** [comment] 2015-09-16 17:59
(also: seems like a duplicate of #3319)

**Comment by ctiller** [comment] 2015-09-17 00:08
Should be fixed

**Closed by ctiller** 2015-09-17 00:08 UTC

**Comment by TassoKarkanisADSK** [comment] 2015-09-17 16:17
I cherry-picked your change 7a5149 into the branch release-0_11 and can confirm that the problem is fixed.  Thanks a lot!
