### ISSUE TITLE
Pub/Sub deadlocks processing

### ISSUE THREAD

**Issue by knodel12** [grpc/grpc#20955] opened 2019-11-06 14:25 UTC
We've recently encountered an issue where our background server to process incoming pub/sub messages stops processing them after some time running.  The only way to get to the server to response again is to reset the process.

The setup we have is a list of System.Threading.Timers that trigger a pull against the Pub/Sub subscriber process.  The timer fires, stops, processes what's available in the queue, and then resets the timer.  Upon the service shutting down, we dispose of all resources including the timer.  Since it's a windows service, a single thread begins all the timers and then keeps them in memory waiting for them to trigger.

We pulled a complete memory dump of the process, and it shows the following stack as the deadlock:

![image](https://user-images.githubusercontent.com/20692379/68306050-69d21680-006e-11ea-9153-f91580ffe433.png)
![image](https://user-images.githubusercontent.com/20692379/68306158-a0a82c80-006e-11ea-8f58-fae4d9fbb3cf.png)

![image](https://user-images.githubusercontent.com/20692379/68306315-ef55c680-006e-11ea-9ef7-40dd0b8fb801.png)

Can anybody provide suggestions on how to debug, or is there additional information needed?

**Comment by knodel12** [comment] 2019-11-11 14:21
We recorded some perfmon information as well.  When these dumps were taken, nearly all processes dropped down in CPU significantly, again indicating some type of deadlock.  At approximately 4:31 PM, you can see the processor drop to nothing.  Shortly after that time the dump stacks above were taken.


[PubSubPerfData_hangissue.xlsx](https://github.com/grpc/grpc/files/3831703/PubSubPerfData_hangissue.xlsx)

**Comment by knodel12** [comment] 2019-11-12 22:34
Updated comment above for accuracy.  The spreadsheet contained several days, listed exact day and approximate time.

**Comment by jtattermusch** [comment] 2019-11-21 14:06
Could this be an instance of https://github.com/grpc/grpc/pull/19311?

Can you reproduce consistently or does it happen randomly.
From the stacktrace you provided it's not obvious that this is actually a deadlock - it's likely just gRPC threads waiting in completion_queue_next() waiting for the next event (why the next event is not triggered is another question and it's hard to answer without knowing your code).

But I'd recommend testing if https://github.com/grpc/grpc/pull/19311 fixes the problem (I can provide you the nugets or they will eventually be uploaded to packages.grpc.io (make sure they contain the fix!).

**Comment by knodel12** [comment] 2019-11-25 14:39
@jtattermusch That does seem very related.  We haven't been able to reproduce in our test environments, as they are short lived, but if you can provide the nuget packages we can plan on updating our production servers with that package.  When is the planned official release for that pull request?

**Comment by jtattermusch** [comment] 2019-11-26 13:26
The "nightly build" nuget packages here contain the fix mentioned above https://packages.grpc.io/archive/2019/11/b4d69165524e715658976799832a588cf0cb9cf6-ddbbc56c-7404-4135-915d-a33965d02d53/index.xml

There's also available through this nuget feed: https://github.com/grpc/grpc/tree/master/src/csharp#nuget-development-feed-nightly-builds

**Comment by yashykt** [comment] 2020-05-05 19:08
Closing since there hasn't been any update from the user in quite some time.

**Closed by yashykt** 2020-05-05 19:08 UTC
Labels: kind/bug, lang/C#, platform/Windows, priority/P2
