### ISSUE TITLE
Failure of python_linux_opt_native.py34.test.interop._insecure_intraop_test.InsecureIntraopTest

### ISSUE THREAD

**Issue by apolcyn** [grpc/grpc#10832] opened 2017-04-25 01:01 UTC
log in https://grpc-testing.appspot.com/job/gRPC_master_linux/

failed on 4/24 at 7am, several runs have since passed.

```
Regression

python_linux_opt_native.py34.test.interop._insecure_intraop_test.InsecureIntraopTest (from grpc.python_linux_opt_native)

Failing for the past 1 build (Since Failed#2207 )
Took 1.9 sec.
Error Message

Failure
Standard Output

++ dirname /var/local/git/grpc/tools/run_tests/helper_scripts/run_python.sh
+ cd /var/local/git/grpc/tools/run_tests/helper_scripts/../../..
++ realpath py34/bin/python
+ PYTHON=/var/local/git/grpc/py34/bin/python3.4
++ pwd
+ ROOT=/var/local/git/grpc
+ /var/local/git/grpc/py34/bin/python3.4 /var/local/git/grpc/src/python/grpcio_tests/setup.py test_lite
running test_lite
Running       interop._insecure_intraop_test.InsecureIntraopTest.testCancelAfterBegin
[95mTesting gRPC Python...
[0m[92mSUCCESS       interop._insecure_intraop_test.InsecureIntraopTest.testCancelAfterBegin
[0mRunning       interop._insecure_intraop_test.InsecureIntraopTest.testCancelAfterFirstResponse
[92mSUCCESS       interop._insecure_intraop_test.InsecureIntraopTest.testCancelAfterFirstResponse
[0mRunning       interop._insecure_intraop_test.InsecureIntraopTest.testClientStreaming
[91mERROR         interop._insecure_intraop_test.InsecureIntraopTest.testClientStreaming
[0mRunning       interop._insecure_intraop_test.InsecureIntraopTest.testEmptyUnary
[92mSUCCESS       interop._insecure_intraop_test.InsecureIntraopTest.testEmptyUnary
[0mRunning       interop._insecure_intraop_test.InsecureIntraopTest.testLargeUnary
[92mSUCCESS       interop._insecure_intraop_test.InsecureIntraopTest.testLargeUnary
[0mRunning       interop._insecure_intraop_test.InsecureIntraopTest.testPingPong
[92mSUCCESS       interop._insecure_intraop_test.InsecureIntraopTest.testPingPong
[0mRunning       interop._insecure_intraop_test.InsecureIntraopTest.testServerStreaming
[92mSUCCESS       interop._insecure_intraop_test.InsecureIntraopTest.testServerStreaming
[0mRunning       interop._insecure_intraop_test.InsecureIntraopTest.testTimeoutOnSleepingServer
[92mSUCCESS       interop._insecure_intraop_test.InsecureIntraopTest.testTimeoutOnSleepingServer
[0m8 tests finished:
	7 successful
	1 unsuccessful
	0 skipped
	0 expected failures
	0 unexpected successes
Interrupted Tests:
	[]

Errors/Failures: 
[91minterop._insecure_intraop_test.InsecureIntraopTest.testClientStreaming[0m
[1mtraceback:[0m
Traceback (most recent call last):
  File "/usr/lib/python3.4/unittest/case.py", line 58, in testPartExecutor
    yield
  File "/usr/lib/python3.4/unittest/case.py", line 577, in run
    testMethod()
  File "/var/local/git/grpc/src/python/grpcio_tests/tests/interop/_intraop_test_case.py", line 51, in testClientStreaming
    methods.TestCase.CLIENT_STREAMING.test_interoperability(self.stub, None)
  File "/var/local/git/grpc/src/python/grpcio_tests/tests/interop/methods.py", line 470, in test_interoperability
    _client_streaming(stub)
  File "/var/local/git/grpc/src/python/grpcio_tests/tests/interop/methods.py", line 173, in _client_streaming
    response = stub.StreamingInputCall(requests)
  File "/var/local/git/grpc/py34/lib/python3.4/site-packages/grpc/_channel.py", line 631, in __call__
    return _end_unary_response_blocking(state, call, False, deadline)
  File "/var/local/git/grpc/py34/lib/python3.4/site-packages/grpc/_channel.py", line 455, in _end_unary_response_blocking
    raise _Rendezvous(state, None, None, deadline)
grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with (StatusCode.UNIMPLEMENTED, Method not found!)>

[1mstdout:[0m

[1mstderr:[0m


Unexpected successes: []
Test failure
```

**Comment by dgquintas** [comment] 2017-04-26 20:31
Happening on Master: https://grpc-testing.appspot.com/job/gRPC_master_linux/2225/testReport/junit/(root)/python_linux_opt_native/py27_test_interop__insecure_intraop_test_InsecureIntraopTest/

**Comment by nathanielmanistaatgoogle** [comment] 2017-04-26 20:47
This smells to me a lot like [issue 10049](https://github.com/grpc/grpc/issues/10049) which was very quiet and intermittent earlier this year. How reproducible is the problem described here? Is it anything close to deterministic?

**Comment by dgquintas** [comment] 2017-04-26 21:10
I can only point at the history
<https://grpc-testing.appspot.com/job/gRPC_master_linux/2225/testReport/junit/(root)/python_linux_opt_native/py27_test_interop__insecure_intraop_test_InsecureIntraopTest/history/>.
It seems it's been behaving itself lately, except for this last instance. I
haven't tried to reproduced locally with many runs, only reported the
failure seen on Master.

**Comment by nathanielmanistaatgoogle** [comment] 2017-05-16 22:37
Yeah, let's call this a duplicate of [issue 10049](https://github.com/grpc/grpc/issues/10049).

**Closed by nathanielmanistaatgoogle** 2017-05-16 22:37 UTC
Labels: BUILDPONY, python
