### ISSUE TITLE
AttributeError :'nonetype' object has no attribute 'code'

### ISSUE THREAD

**Issue by suraj1990** [grpc/grpc#7133] opened 2016-06-29 08:54 UTC
I am trying to run a python script which uses grpc. and I am getting the errors as seen in the screen shot attached. 
I have installed grpc using this command 'sudo pip install grpcio'

![grpcerror](https://cloud.githubusercontent.com/assets/5551707/16446387/ebc2db00-3e04-11e6-9944-c98704fc87c6.png)

**Comment by sukritiramesh** [comment] 2016-07-01 19:18
We have a similar issue reported at: https://github.com/tensorflow/serving/issues/114. Is there a recommended way to fix this?

**Comment by nathanielmanistaatgoogle** [comment] 2016-07-02 07:36
I see the problem and am working on a fix.

**Comment by nathanielmanistaatgoogle** [comment] 2016-07-02 07:37
In the meantime how does calling `result` and catching the raised exception work for you as a fix?

**Comment by nathanielmanistaatgoogle** [comment] 2016-07-02 08:24
Fix now in code review in [pull request 7224](https://github.com/grpc/grpc/pull/7224).

**Comment by nathanielmanistaatgoogle** [comment] 2016-07-07 21:56
Reopening; this has to be fixed on master as well as on release-0_15 before it should be considered fixed.

**Comment by jayantkolhe** [comment] 2016-07-08 20:36
[Pull request link](https://github.com/grpc/grpc/pull/7272)

**Comment by nathanielmanistaatgoogle** [comment] 2016-07-08 22:30
This was resolved on master in [pull request 7272](https://github.com/grpc/grpc/pull/7272).

**Closed by nathanielmanistaatgoogle** 2016-07-08 22:30 UTC
Labels: bug, P1, python

**Comment by kirilg** [comment] 2016-07-11 17:36
Just to confirm, since the issue is closed does that mean that this fix was pulled into release-0_15?
From https://github.com/tensorflow/serving/issues/114, xeb's last reply has a dockerfile that installed grpc version 0.15 to reproduce the bug, but it works with master at head.

If the fix is not in 0.15, what's the recommended solution? Ideally we wouldn't have to install from source if you have a new release planned soon.

**Comment by nathanielmanistaatgoogle** [comment] 2016-07-11 21:19
@kirilg: yes, this defect has been fixed on both [`release-0_15`](https://github.com/grpc/grpc/commits/release-0_15) and [`master`](https://github.com/grpc/grpc/commits/master). The defect will not appear in any future release, be it 0.15.1, 0.16, or 1.0. How painful is the workaround of [calling `result` and catching any raised exception](https://github.com/grpc/grpc/issues/7133#issuecomment-230089126)?

**Comment by kirilg** [comment] 2016-07-12 22:54
Thanks for confirming. So will the latest `pip install grpcio` contain the fix? Can you confirm whether or not https://gist.github.com/xeb/c831009eec6c850d98383f96ec8e303e#file-dockerfile-L38 should install the right version with the fix? I believe this Docker image reproduces the failure.

I can catch raised expections which should work, but I'm wondering if it's already expected to work in the latest gRPC from that docker image.

**Comment by nathanielmanistaatgoogle** [comment] 2016-07-12 23:00
@kirilg: no currently-published `grpcio` package contains the fix, but whatever `grpcio` package is published _next_ will.

My apologies for the defect; I blame [lack of test coverage](https://github.com/grpc/grpc/issues/6894).

**Comment by kirilg** [comment] 2016-07-12 23:02
Thanks. I think we can catch the exception in the meantime. Sent you a fix in TF Serving for review.
