### ISSUE TITLE
gRPC Unity package still doesn't work after 2.26 (Could not load signature of Google.Protobuf.ByteString:get_Span)

### ISSUE THREAD

**Issue by virtumonde** [grpc/grpc#25058] opened 2020-12-25 02:48 UTC
### What version of gRPC and what language are you using?
grpc_unity_package.2.35.0-dev202012021242 + grpc-protoc_macos_x64-1.35.0-dev from [here](https://packages.grpc.io/archive/2020/12/d7b70c3ea25c48ffdae7b8bd3c757594d4fff4b6-2be69c7e-9b25-4273-a7d4-3840da2d6723/index.xml).

### What operating system (Linux, Windows,...) and version?
MacOS Catalina 10.15.6

### What runtime / compiler are you using (e.g. python version or version of gcc)
Unity 2019.4.16f1 LTS

### What did you do?
I downloaded the last Unity package (2.35.0) from https://packages.grpc.io/, extracted it to the Asset/Plugins folder.

### What did you expect to see?
No errors, successful MacOS build.

### What did you see instead?
```
Error: Could not load signature of Google.Protobuf.ByteString:get_Span due to: Could not load file or assembly 'System.Memory, Version=4.0.1.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. assembly:System.Memory, Version=4.0.1.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51 type: member:(null) signature:
Unloading broken assembly Assets/Plugins/Google.Protobuf/lib/net45/Google.Protobuf.dll, this assembly can cause crashes in the runtime
```
I get those errors on every version after 2.26.

**Comment by rdcm** [comment] 2021-01-03 21:36
@virtumonde Could you suggest a workaround while 2.35 unity package broken?
I have a .proto file and need to generate a client for unity.

https://packages.grpc.io/archive/2019/12/a02d6b9be81cbadb60eed88b3b44498ba27bcba9-edd81ac6-e3d1-461a-a263-2b06ae913c3f/index.xml

This package does not raise any errors in the unity console, but the generated file is broken.

`protoc -I=./Assets/Protos --csharp_out=./Assets/Protos Assets/Protos/router.proto`

```
protoc --version
libprotoc 3.14.0
```

I think this error occurs because I use the latest protoc version.

**Comment by virtumonde** [comment] 2021-01-03 21:53
Hi @rdcm. I think you are not compiling using the protoc corresponding to ```grpc_unity_package.2.26.0-dev```. Download the ```protoc``` corresponding to your OS from [here](https://packages.grpc.io/archive/2019/12/a02d6b9be81cbadb60eed88b3b44498ba27bcba9-edd81ac6-e3d1-461a-a263-2b06ae913c3f/index.xml) (one of [these](https://imgur.com/ynouhCi)). I am also using ```2.26``` and after typing ```./protoc --version``` I get ```libprotoc 3.8.0```, not ```libprotoc 3.14.0```.

**Comment by rdcm** [comment] 2021-01-04 02:41
@virtumonde Yes, you right I did not see the `protoc` in the archive only plugins for different languages. Thanks!

**Comment by virtumonde** [comment] 2021-01-04 10:06
@rdcm Np! Is there a chance you're familiar with grpc-web? I have a problem with settings it up. It think it is related to Envoy.

**Comment by rdcm** [comment] 2021-01-04 12:21
Nope, for load balancing, I'm going to set up Nginx and I haven't any experience with Envoy.
If it will be interesting for you I can share the config when my application will be done.

**Comment by virtumonde** [comment] 2021-01-04 20:04
That would be great!

**Comment by jtattermusch** [comment] 2021-01-08 14:48
Looks like this issue is a duplicate of https://github.com/grpc/grpc/issues/21908

**Closed** 2021-02-11 13:57 UTC
Labels: kind/bug, lang/C#, priority/P2
