### ISSUE TITLE
No reconnect attempts with round_robin

### ISSUE THREAD

**Issue by c-bb** [grpc/grpc#11578] opened 2017-06-22 18:00 UTC
It appears that when using the `round_robin` client-side load-balancing policy, once a "subchannel" (i.e. one of the server instances) is down, the client never attempts to reconnect again.

This is easy to reproduce even in the trivial case of a single client and server, where the client makes repeated requests through a channel configured with `round_robin` that specifies only the single server instance. When bringing the server down and back up, the client is never again able to make a request to it.

Contrast this with the default ("pick first") load balancing policy: here, the client successfully reconnects.

I have tried reducing the `grpc.min_reconnect_backoff_ms` and `grpc.initial_reconnect_backoff_ms` config values, but to no avail.

I'm using gRPC 1.4.0. (In 1.3.1, this seemed to work at least partially, with the client periodically attempting to reconnect, although I often observed it not actually succeeding due to some spurious-seeming timeout error.)

Am I correct in thinking this is a bug? Or is it intentional that no reconnect attempts are ever made?

**Comment by dgquintas** [comment] 2017-06-23 21:51
Hi @c-bb , thanks for reporting this. I can reproduce locally and I'm currently investigating.

**Comment by dgquintas** [comment] 2017-06-23 22:06
I've identified the cause, a fix is in the works and will go in a 1.4.1 release. Thanks for the catch!

**Comment by dgquintas** [comment] 2017-06-24 00:46
@c-bb , I'll release 1.4.1 (maybe .2) on Monday. In the meantime, if you have the ability to compile from source, the changes to round_robin.c are pretty minimal, see [here](https://github.com/grpc/grpc/pull/11591/files#diff-529817bbf231ebce91318397959484d7)

**Comment by c-bb** [comment] 2017-06-26 13:24
Thanks, @dgquintas! I can confirm that your fix works for me.

One thing that still does not seem ideal to me is that the `round_robin` load balancer only reconnects if _all_ connections have gone down.

It would seems preferable to me if it periodically attempted to reconnect to _any_ failing subchannel.

As it stands, if a service lives on _n_ remote servers, all of which eventually undergo downtime/maintenance, then a (long-lived) client will gradually lose connectivity to more and more servers, until only one is left, and only when that one goes down, does it reconnect to all of them. Not especially great for load-balancing.

Admittedly slightly separate from the issue here; but I'm curious if there are any plans to change that behaviour as well? With some guidance I might even be able to contribute a pull request...

**Comment by dgquintas** [comment] 2017-06-26 17:17
@c-bb , I agree. We plan on changing this behavior shortly, hopefully over the following weeks, targetting 1.5. Feel free to file an issue for better tracking. The change is a bit tricky, as there are assumptions RR "inherited" from how pick first works that need to be revisited for this behavior. Let me come up with a roadmap of what needs to be changed and get back to you, thanks for offering to contribute :)

**Comment by vadimi** [comment] 2017-06-28 13:34
I'm having similar issues with gRPC C# 1.4.0. Is there a plan to publish 1.4.1 to NuGet?

**Comment by dgquintas** [comment] 2017-06-28 16:38
Yes. Release packages for all languages wrapping the C Core should go out today.

**Comment by dgquintas** [comment] 2017-06-29 03:05
The packages for all the wrapped languages are being pushed out. The release page is [here](https://github.com/grpc/grpc/releases/tag/v1.4.1). @vadimi the C# 1.4.1 NuGet will very likely be pushed early tomorrow ( @apolcyn @jtattermusch ).

**Comment by jtattermusch** [comment] 2017-06-29 10:47
@vadimi  the 1.4.1 C# nugets have just been pushed

**Comment by dgquintas** [comment] 2017-06-29 16:52
Closing this issue. Thanks everyone.

**Closed by dgquintas** 2017-06-29 16:52 UTC

**Comment by c-bb** [comment] 2017-06-29 16:54
Thank you for addressing this so quickly!
