### ISSUE TITLE
Cannot build gRPC on CentOS 8

### ISSUE THREAD

**Issue by coryan** [grpc/grpc#20529] opened 2019-10-08 19:38 UTC
### What version of gRPC and what language are you using?

1.24.1 and `master` both have this problem. I am using C++ but this is irrelevant I think.

### What operating system (Linux, Windows,...) and version?

Linux.

### What runtime / compiler are you using (e.g. python version or version of gcc)

GCC

### What did you do?

Try to compile gRPC. I used this Dockerfile:

[Dockerfile.centos-8.txt](https://github.com/grpc/grpc/files/3704219/Dockerfile.centos-8.txt)

with this command:

```sh
docker build --build-arg=GRPC_VERSION=master --build-arg=GRPC_ARCHIVE=master -t grpc-repro -f Dockerfile.centos-8 .
```

You can change the version to 1.23.1 and it works, 1.24.1 is also broken, in case that helps you narrow it down.

### What did you expect to see?

A successful build.

### What did you see instead?

The build failed.

### Anything else we should know about your project / environment?

Cannot think of anything.

**Comment by veblush** [comment] 2019-10-08 21:10
Build error is
```
In file included from ./src/core/tsi/alts/handshaker/transport_security_common_api.h:29,
                 from ./src/core/lib/security/credentials/alts/grpc_alts_credentials_options.h:26,
                 from ./src/core/lib/security/credentials/alts/alts_credentials.h:26,
                 from src/core/lib/security/credentials/alts/alts_credentials.cc:21:
src/core/ext/upb-generated/src/proto/grpc/gcp/transport_security_common.upb.h:12:10: fatal error: upb/generated_util.h: No such file or directory
 #include "upb/generated_util.h"
          ^~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make: *** [Makefile:3069: /var/tmp/build/grpc-1.24.1/objs/opt/src/core/lib/security/credentials/alts/alts_credentials.o] Error 1
```

**Comment by veblush** [comment] 2019-10-08 21:12
This is because it lacks third_party directories. Instead of getting `grpc_archive.tar.gz`, please `git clone` the gRPC repository and run `git submodule update --init --recursive` to get third_party libraries properly.

**Comment by veblush** [comment] 2019-10-08 21:13
I close this but please feel free to open this if this doesn't fix your problem.

**Closed by veblush** 2019-10-08 21:13 UTC
Labels: kind/bug, priority/P2

**Comment by jtattermusch** [comment] 2019-10-09 14:43
I think this is actually a dupe of https://github.com/grpc/grpc/issues/20392 and the problem is that we're not treating upb  as an external dependency in our cmake build (but we should, because it's part of our repo, but rather a submodule).

@veblush your analysis is correct, but we actually need to support from building from the tar.gz archive and not have people rely on submodules because otherwise our cmake installation is basically broken.
