### ISSUE TITLE
can we use nodejs client to call python server?

### ISSUE THREAD

**Issue by zxydaisy** [grpc/grpc#7606] opened 2016-08-02 06:44 UTC
```
I0802 03:11:51.854559428       1 http_server_filter.c:197]   OP[http-server:0x387e780]: RECV_INITIAL_METADATA
I0802 03:11:51.854788310       1 connected_channel.c:71]     OP[connected:0x387e798]: RECV_INITIAL_METADATA
I0802 03:11:51.855048082       1 parsing.c:591]              HTTP:1:HDR:SVR: :scheme: http
I0802 03:11:51.855273923       1 parsing.c:591]              HTTP:1:HDR:SVR: :method: POST
I0802 03:11:51.855534502       1 parsing.c:591]              HTTP:1:HDR:SVR: :path: /tensorflow.InceptionService/Classify
I0802 03:11:51.855764015       1 parsing.c:591]              HTTP:1:HDR:SVR: :authority: 43.254.53.118:30157
I0802 03:11:51.856007425       1 parsing.c:591]              HTTP:1:HDR:SVR: grpc-encoding: identity
I0802 03:11:51.856287871       1 parsing.c:591]              HTTP:1:HDR:SVR: grpc-accept-encoding: identity,deflate,gzip
I0802 03:11:51.856502489       1 parsing.c:591]              HTTP:1:HDR:SVR: te: trailers
I0802 03:11:51.856965789       1 parsing.c:591]              HTTP:1:HDR:SVR: content-type: application/grpc
I0802 03:11:51.856996939       1 parsing.c:591]              HTTP:1:HDR:SVR: user-agent: grpc-node/0.15.0 grpc-c/0.15.0 (osx; chttp2)
```

but we see the err: 

```
 be 94 a9 54 f9 3d 0a 26 fc ed 27 99 8e f8 1d 3e 29 52 a5 49 18 7f ff d9 'PRI * HTTP/2.0....SM...................................@.......................@.:scheme.http@.:method.POST@.:path%/tensorflow.InceptionService/Classify@.:authority.43.254.53.118:30157@.grpc-encoding.identity@.grpc-accept-encoding.identity,deflate,gzip@.te.trailers@.content-type.application/grpc@.user-agent,grpc-node/0.15.0 grpc-c/0.15.0 (osx; chttp2)..........................~.........JFIF.............C................................... $.' ",#..(7),01444.'9=82<.342...C...........2!.!22222222222222222222222222222222222222222222222222......d.d.."........................................5........................!..1A."Qaq..2......#BR.b.........................................................!1..2Q............?....'.x...]qo#..........|..mR..'J.yJ""......=.I......T....<.l....k..79.`....so......w&.a.q%..x.....*6.*..(.@.E..5....!x.}.1.)=.S..X?f6.;...H`....Ri6=%./...Lo.\.v......L.$......S^(..b../F.a..u.......m|...1m.#s..O$...jd.......aK.a......l5Ax,.y..g@.}.z.z....%.A.22I.M.....w.L].e.&IW.....U.>J.....R..........P.D..G..7......q...".......8c.-l4...O.]..!.......U...%...x.1.U...m..>$...vV;......Y..,..,."h.dlc;.a..`l:dQ...G....H3..]......}a..S...n<Q.;4L.e..... z.]....$s)...j|M5CsE.lQ..+.G.5...9#......
```

**Comment by nathanielmanistaatgoogle** [comment] 2016-08-09 11:11
Yes, you can use a Node client with a Python server.

Are you able to reproduce this problem using the latest versions of each library (`1.0.0-pre1` for Node and `1.0.0rc1` for Python)?

**Comment by murgatroid99** [comment] 2016-08-09 17:06
That doesn't look like an error. It just looks like normal HTTP2 headers. What is the actual failure you are seeing?

**Comment by nicolasnoble** [comment] 2016-09-16 21:10
@zxydaisy is this problem still active for you ?

**Comment by nathanielmanistaatgoogle** [comment] 2016-10-06 16:15
Closing as it has not been confirmed that there remains a problem here.

**Closed by nathanielmanistaatgoogle** 2016-10-06 16:15 UTC
Labels: node, python, requires reporter clarification
