### ISSUE TITLE
Add an interceptor channel for aio channel

### ISSUE THREAD

**Issue by ztqsteve** [grpc/grpc#36180] opened 2024-03-26 19:22 UTC
### Is your feature request related to a problem? Please describe.
I am trying to implement an async client-side interceptor class to simplify the way to use interceptors, which inherits `UnaryUnaryClientInterceptor`, `UnaryStreamClientInterceptor`, `StreamUnaryClientInterceptor`, `StreamStreamClientInterceptor` in the following way:
```python
class AsyncClientInterceptor(
    grpc_aio.UnaryUnaryClientInterceptor,
    grpc_aio.UnaryStreamClientInterceptor,
    grpc_aio.StreamUnaryClientInterceptor,
    grpc_aio.StreamStreamClientInterceptor,
    metaclass=abc.ABCMeta,
):
```
However, from https://github.com/grpc/grpc/blob/master/src/python/grpcio/grpc/aio/_channel.py#L349, the `if...elif...` interceptor type check block my way. Is it possible to either provide an async interceptor channel or update the logic to use `if ... if` instead of `if ... elif` for filling the interceptor lists?

### Describe the solution you'd like
An interceptor channel for `aio`

### Describe alternatives you've considered
Provide some flexibilities for aio Channel class
```python
class Channel(_base_channel.Channel):
    _loop: asyncio.AbstractEventLoop
    _channel: cygrpc.AioChannel
    _unary_unary_interceptors: List[UnaryUnaryClientInterceptor]
    _unary_stream_interceptors: List[UnaryStreamClientInterceptor]
    _stream_unary_interceptors: List[StreamUnaryClientInterceptor]
    _stream_stream_interceptors: List[StreamStreamClientInterceptor]

    def __init__(self, target: str, options: ChannelArgumentType,
                 credentials: Optional[grpc.ChannelCredentials],
                 compression: Optional[grpc.Compression],
                 interceptors: Optional[Sequence[ClientInterceptor]]):
        """Constructor.

        Args:
          target: The target to which to connect.
          options: Configuration options for the channel.
          credentials: A cygrpc.ChannelCredentials or None.
          compression: An optional value indicating the compression method to be
            used over the lifetime of the channel.
          interceptors: An optional list of interceptors that would be used for
            intercepting any RPC executed with that channel.
        """
        self._unary_unary_interceptors = []
        self._unary_stream_interceptors = []
        self._stream_unary_interceptors = []
        self._stream_stream_interceptors = []
        valid_classes = (UnaryUnaryClientInterceptor, UnaryStreamClientInterceptor,
                       StreamUnaryClientInterceptor, StreamStreamClientInterceptor)

        if interceptors is not None:
            for interceptor in interceptors:
                if not isinstance(interceptor, valid_classes):
                    msg = ' or '.join([x.__name__ for x in valid_classes])
                    raise ValueError(
                        f"Interceptor {interceptor} must be {msg}")
                if isinstance(interceptor, UnaryUnaryClientInterceptor):
                    self._unary_unary_interceptors.append(interceptor)
                if isinstance(interceptor, UnaryStreamClientInterceptor):
                    self._unary_stream_interceptors.append(interceptor)
                if isinstance(interceptor, StreamUnaryClientInterceptor):
                    self._stream_unary_interceptors.append(interceptor)
                if isinstance(interceptor, StreamStreamClientInterceptor):
                    self._stream_stream_interceptors.append(interceptor)
                

        self._loop = cygrpc.get_working_loop()
        self._channel = cygrpc.AioChannel(
            _common.encode(target),
            _augment_channel_arguments(options, compression), credentials,
            self._loop)
```

### Additional context
Add any other context about the feature request here.

**Comment by XuanWang-Amos** [comment] 2024-04-01 22:45
Closing this one as duplicate of https://github.com/grpc/grpc/issues/34537

**Closed by XuanWang-Amos** 2024-04-01 22:45 UTC
Labels: kind/enhancement, lang/Python, priority/P2
