### ISSUE TITLE
Incorrect platform protoc used with Mono on macOS Big Sur

### ISSUE THREAD

**Issue by mrward** [grpc/grpc#24529] opened 2020-10-22 10:59 UTC
### What version of gRPC and what language are you using?

grpc.tools/2.27.0

### What operating system (Linux, Windows,...) and version?

macOS 10.16.0 (Big Sur)

### What runtime / compiler are you using (e.g. python version or version of gcc)

Mono

### What did you do?

Created a gRPC project (from the .NET Core 3.1.403 SDK) with Visual Studio for Mac 8.8 - at some point the _Protobuf_CoreCompile will be run during a design time build - this fails.

The _Protobuf_CoreCompile MSBuild target fails since it is not using the macos_x64/protoc. The platform detection is not working on Big Sur.

arget _Protobuf_CoreCompile:
    /Users/user/.nuget/packages/grpc.tools/2.27.0/tools/linux_x64/protoc --csharp_out=obj/Debug/netcoreapp3.1 --plugin=protoc-gen-grpc=/Users/user/.nuget/packages/grpc.tools/2.27.0/tools/linux_x64/grpc_csharp_plugin --grpc_out=obj/Debug/netcoreapp3.1 --grpc_opt=no_client --proto_path=/Users/user/.nuget/packages/grpc.tools/2.27.0/build/native/include --proto_path=. --dependency_out=obj/Debug/netcoreapp3.1/1255d1a520d30ea4_greet.protodep --error_format=msvs Protos/greet.proto
    /Users/user/.nuget/packages/grpc.tools/2.27.0/build/_protobuf/Google.Protobuf.Tools.targets(264,5): error MSB6006: "/Users/user/.nuget/packages/grpc.tools/2.27.0/tools/linux_x64/protoc" exited with code 255.

### Investigation

The path to the protoc tool seems to be generated using information from the grpc msbuild task:

https://github.com/grpc/grpc/blob/04f6f3676ebf6f7dc94c4b178140ea95317fb7cb/src/csharp/Grpc.Tools/ProtoToolsPlatform.cs#L48

That uses the Platform class defined here:

https://github.com/grpc/grpc/blob/04f6f3676ebf6f7dc94c4b178140ea95317fb7cb/src/csharp/Grpc.Tools/Common.cs#L68-L88

This platform detection does not work on Big Sur since the libc.dylib file is removed. msbuild was originally doing the same thing, where it was checking ` File.Exists("/usr/lib/libc.dylib")` but msbuild was changed to use RuntimeInformation.IsOSPlatform(OSPlatform.OSX), as you can see in this commit:

https://github.com/mono/msbuild/commit/f048f95f8c67b4316d72f362ff2fa3dac67f58d4

Related issue:

https://github.com/dotnet/msbuild/issues/5454

On Mono you should be able to just use the RuntimeInformation instead of trying to check for the presense of libc.dylib.

**Comment by jtattermusch** [comment] 2020-10-27 11:52
Another place where we do platform detection (but slightly differently, this time for the Grpc.Core native extension):
https://github.com/grpc/grpc/blob/7fccdd7385386eda004d1ccf91c3aea41832b161/src/csharp/Grpc.Core/Internal/PlatformApis.cs#L65

**Comment by jtattermusch** [comment] 2020-10-27 11:52
@mrward  I don't have MacOS big sur machine at hand - if I make the changes, would you be able to test them?

**Comment by mrward** [comment] 2020-10-27 12:11
Whilst I do not have a Big Sur machine currently the VS Mac team has some so we can test the changes.

**Comment by tmarkovski** [comment] 2020-11-15 16:24
Until a fix is applied, can be resolved by adding this to your csproj file.

```
<Protobuf_ToolsOs Condition="'$([MSBuild]::IsOsPlatform(OSX))'">macosx</Protobuf_ToolsOs>
```

**Comment by isc30** [comment] 2020-11-15 18:41
We have been blocked the whole afternoon due to this, thanks for sharing the temporary fix!

**Comment by jtattermusch** [comment] 2020-11-16 15:44
I'm trying to figure out a way to fix this.
I can't just use `RuntimeInformation.IsOSPlatform(OSPlatform.OSX)` because it's not available under the net45 target where this is causing trouble (and under .NET core we are already using `RuntimeInformation.IsOSPlatform(OSPlatform.OSX)`)

Does this check still work of MacOS Big Sur?
https://github.com/grpc/grpc/blob/7fccdd7385386eda004d1ccf91c3aea41832b161/src/csharp/Grpc.Core/Internal/PlatformApis.cs#L65
(if so I can also use it in Grpc.Tools/Common.cs)

**Comment by jtattermusch** [comment] 2020-11-16 16:08
A speculative fix is here: 
https://github.com/grpc/grpc/pull/24768 (will only work if the GetUname() == "Darwin" check still works under big sur and that needs to be tested).

**Comment by tmarkovski** [comment] 2020-11-16 16:19
@jtattermusch It seems to work on Big Sur - https://ibb.co/qCTGns9

**Comment by jtattermusch** [comment] 2020-11-17 13:50
I just merged https://github.com/grpc/grpc/pull/24768, which should solve the problem. 
It would be good to get a confirmation. See the PR thread for adhoc build of Grpc.Tools package (or wait for the package to appear package.grpc.io).

**Closed** 2020-11-17 13:51 UTC
Labels: kind/bug, lang/C#, priority/P1

**Comment by jtattermusch** [comment] 2020-11-18 10:51
Fix confirmed: https://github.com/grpc/grpc/pull/24768#issuecomment-729162665
