### ISSUE TITLE
interop go docker image failure

### ISSUE THREAD

**Issue by makdharma** [grpc/grpc#10317] opened 2017-03-27 04:03 UTC
From: 
https://grpc-testing.appspot.com/job/gRPC_interop_pull_requests/12572/console
Error :
../../transport/http2_client.go:130: undefined: dialContext

**Comment by makdharma** [comment] 2017-03-27 18:11
Perhaps a dup of [grpc/grpc-go#1146](https://github.com/grpc/grpc-go/issues/1146)

**Comment by ncteisen** [comment] 2017-03-29 18:28
Closing as duplicate of grpc/grpc-go#1146

**Closed by ncteisen** 2017-03-29 18:28 UTC
Labels: BUILDPONY
