### ISSUE TITLE
grpcio-tools does not generate message objects

### ISSUE THREAD

**Issue by sdimovv** [grpc/grpc#31247] opened 2022-10-05 17:10 UTC
I might be missing something so feel free to correct me and close this if this is an expected behaviour with the newer versions of grpcio-tools.

### What version of gRPC and what language are you using?
Python, grpcio-tools==1.49.1, grpcio==1.49.1

### What operating system (Linux, Windows,...) and version?
Linux

### What runtime / compiler are you using (e.g. python version or version of gcc)
python 3.9.1

### What did you do?
Consider the following proto:

```
syntax = "proto3";

package pkg;

message Msg {
    string id = 1;
}
service Svc {
    rpc an_rpc(Msg) returns (Msg);
}
```
Using the command:
```
python -m grpc_tools.protoc -I proto --python_out=src/my_package/proto --grpc_python_out=src/my_package/proto proto/proto.proto
```

This produces the following `proto_pb2.py`:

```
# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()

DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fproto.proto\x12\x03pkg\"\x11\n\x03Msg\x12\n\n\x02id\x18\x01 \x01(\t2#\n\x03Svc\x12\x1c\n\x06\x61n_rpc\x12\x08.pkg.Msg\x1a\x08.pkg.Msgb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _MSG._serialized_start=24
  _MSG._serialized_end=41
  _SVC._serialized_start=43
  _SVC._serialized_end=78
# @@protoc_insertion_point(module_scope)
```

### What did you expect to see?
I expect to see a generated Msg message object.

Downgrading grpcio-tools to 1.46.0 fixes this:

```
# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()

DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fproto.proto\x12\x03pkg\"\x11\n\x03Msg\x12\n\n\x02id\x18\x01 \x01(\t2#\n\x03Svc\x12\x1c\n\x06\x61n_rpc\x12\x08.pkg.Msg\x1a\x08.pkg.Msgb\x06proto3')

_MSG = DESCRIPTOR.message_types_by_name['Msg']
Msg = _reflection.GeneratedProtocolMessageType('Msg', (_message.Message,), {
  'DESCRIPTOR' : _MSG,
  '__module__' : 'proto_pb2'
  # @@protoc_insertion_point(class_scope:pkg.Msg)
  })
_sym_db.RegisterMessage(Msg)

_SVC = DESCRIPTOR.services_by_name['Svc']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _MSG._serialized_start=24
  _MSG._serialized_end=41
  _SVC._serialized_start=43
  _SVC._serialized_end=78
# @@protoc_insertion_point(module_scope)
```

### What did you see instead?
No Msg message object being generated

### Anything else we should know about your project / environment?
N/A

**Comment by gnossen** [comment] 2022-10-05 17:21
Duplicate of https://github.com/grpc/grpc/issues/31097.

This is working as intended. 1.49.1 pulls in a breaking change in the Python Protobuf generated code. You'll notice that `grpcio-tools` now has a dependency on `protobuf>=4.21.6,<5.0dev` whereas `1.47.0`'s range was `protobuf>=3.12.0, < 4.0dev`.

Please reopen this issue if you have any problems running the new generated code with `protobuf>=4.21.6`.

**Closed by gnossen** 2022-10-05 17:21 UTC
Labels: kind/bug, lang/Python, priority/P2

**Comment by sdimovv** [comment] 2022-10-05 21:41
I see. Thanks.

Could you please provide me with a tutorial on how to create a simple client-server application with the new workflow?

**Comment by gnossen** [comment] 2022-10-05 21:46
The workflow should be the same. Please see [the greeter example](https://github.com/grpc/grpc/blob/master/examples/python/helloworld/greeter_client.py).

**Comment by sdimovv** [comment] 2022-10-05 21:57
If I understand correctly, the messages are now generated as `helloworld_pb2.pyi` but I do not get such a file when I generate with the following command:

```
python -m grpc_tools.protoc -I proto --python_out=src/mymodule/proto --grpc_python_out=src/mymodule/proto proto/myproto.proto
```

**Comment by gnossen** [comment] 2022-10-05 22:00
Ah, I see the confusion here. The issue isn't that message objects aren't getting generated, it's that _type information_ is now split out into a separate file.

The `.pyi` files only include type information. You'll need to use [the `--pyi_out` flag](https://github.com/grpc/grpc/blob/8cffd1044ea2e19760942347b54068decd45118a/examples/python/Makefile#L71) (same value as `--python_out`). I'll make sure the getting started guide gets updated to include this.

**Comment by sdimovv** [comment] 2022-10-05 22:04
Ah that makes sense.

Thanks.

**Comment by terwey** [comment] 2022-12-05 11:23
This breaking change seems to have occurred on `grpcio-tools` between version `v1.43.0` and `v1.44.0-rc1`
