### ISSUE TITLE
inconsistency in libgrpc++ soname

### ISSUE THREAD

**Issue by timofey-retailnext** [grpc/grpc#12764] opened 2017-09-29 03:19 UTC
### What version of gRPC and what language are you using?
1.6.3 C++
  
### What operating system (Linux, Windows, …) and version?
 Linux (Fedora 25, Ubuntu 14,15,etc)
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
 gnu make of grpc using clang compiler (with libstdc++ runtime)
 
### What did you do?
build results provide s set of libgrpc++*so.4 libraries, however "objdump -x" shows SONAME as libgrpc++.so.1. This produces link probblems in my application.
same applicable for all c++ libraries. in cotrast c libraries (ex. libgrpc) show SONAME as so.4
 
### What did you expect to see?
 match between c++ so file name and its SONAME header field
 
### What did you see instead?
file name: libgrpc++.so.4
SONAME: libgrpc++.so.1
 
Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

**Comment by minorhacks** [comment] 2017-10-10 01:11
This seems to be an issue with the Makefile.

The long version suffix is well-factored (e.g. `SHARED_EXT_CORE` => `so.4.0.0`) but the short version suffix is not, leading to duplication of strings matching `\.so\.[0-9]` throughout the file.

The filenames of the C++ libs when passed on the linker line are suffixed with `.so.1` (see [Makefile:4626 at tag `v1.6.6`](https://github.com/grpc/grpc/blob/v1.6.6/Makefile#L4626) but are suffixed with `.so.4` when the links are created (see [Makefile:2642 at tag `v1.6.6`](https://github.com/grpc/grpc/blob/v1.6.6/Makefile#L2642)) leading to this issue.

This probably happened because the short suffix is not well-factored and so someone bumped the version numbers of the C++ libraries in the link creation steps when they should have been left at `.so.1`.

@timofey-retailnext If you are interested, I can find a way to upload the patch I wrote for our org, but be aware that I'm not a makefile expert and haven't fixed the same issue for the C# libs or tested this on Windows/OSX. Otherwise, hopefully Google is watching this bug and a quick fix is imminent.

**Comment by timofey-retailnext** [comment] 2017-10-12 02:37
My understanding that makefile is generated (from bazel?). So it makes sense to change primary build source and then generate new makefile. Otherwise please simply fix grpc++ lib versions manually in makefile.
And please notice that grpc libs (C not C++?) use this "so.4"  versions and there are not problems with them, while grpc++ libs (C++?) have problems and must be converted to so.1 and so.1.6.6. 
Please simply use '\$(SHARED_EXT_CORE)' and ' \$(SHARED_EXT_CPP)' instead of hardcoded '.so.1' and '.so.4'

**Comment by timofey-retailnext** [comment] 2017-10-12 02:40
that's what I use to fix it in my build:
#for grpc 1.3.x and above (1.6.x now): fix soname and filename inconsistency for libgrpc++*.so.N
sed -i.bak -e "s|libgrpc++\([^\.]*\)\.so\.[0-9]|libgrpc++\1.so.1|g" Makefile

**Comment by minorhacks** [comment] 2017-10-12 05:43
Whoops - never occurred to me that the makefile would be generated (maybe I should, you know, read the top of the file?)

Looks like this means its an issue with the template, which might make it way easier to fix.

**Comment by sreecha** [comment] 2018-08-16 22:50
@timofey-retailnext : Would you be able to submit a PR for this?

**Comment by jtattermusch** [comment] 2018-11-16 10:41
This was fixed by #16832. The fix will be in the upcoming v1.17.0 release.

Also basically a duplicate of #10299

**Closed by jtattermusch** 2018-11-16 10:41 UTC
Labels: kind/bug, lang/c++, priority/P3
