### ISSUE TITLE
Failed Parsing HTTP/2 Python Server, NodeJS Client

### ISSUE THREAD

**Issue by heliumsoule** [grpc/grpc#7302] opened 2016-07-11 04:51 UTC
Hi,

I'm trying to connect a NodeJS client with a Python server under the following Proto file and receiving errors with the NodeJS client and Python server. 

The error message specifically is 
E0711 02:41:19.813383112 14901 chttp2_transport.c:1810]		close_transport: {"created": "@1468204879.813338761", "description" : **"Failed parsing HTTP/2"** , "file" : "src/core/ext/transport/chttp2/transport/chttp2_transport.c" , "file_line":1726, "referenced_errors": [{"created":"@1468204879.813336702","description":"EOF","file":src/core/lib/iomgr/tcp_posix.c","file_line":233}]}

The Python client and server work fine which lead me to think either the grpc library for NodeJS isn't proto3 compliant or there's an error in my .js code. Any help is really appreciated.

```
syntax = 'proto3';

package cnnclassify;

message ImgClassRequest {
    string filename = 1;
}

message ImgClassResponse {
    message ClassLikelihood {
        string class = 1;
        double prob = 2;
    }
    ClassLikelihood class_and_likelihood = 1;
}

service ClassificationServer {
    rpc ClassifyImage (ImgClassRequest) returns (ImgClassResponse) {}
}
```

The Python server

```
import time
import sys

sys.path.append('modules/python')
sys.path.append('modules/protobuf')

import pyluawrapper
import cnn_class_pb2 as cnnclass

_ONE_DAY_IN_SECONDS = 60 * 60 * 24

class ClassServerHandler(cnnclass.BetaClassificationServerServicer):
    def __init__(self):
        self.model = pyluawrapper.LutorpyTorch()
    
    def ClassifyImage(self, request, context):
        print("I received a request! %s" % request.filename)

class ProtobufServer(object):
    def __init__(self, handler):
        self.server = cnnclass.beta_create_ClassificationServer_server(handler)
        self.server.add_insecure_port('[::]:8000')

    def serve(self):
        self.server.start()
        try:
            while True:
                time.sleep(_ONE_DAY_IN_SECONDS)
        except KeyboardInterrupt:
            self.server.stop(0)

if __name__ == "__main__":
    class_server = ProtobufServer(ClassServerHandler())
    class_server.serve()

```
The NodeJS client
```
'use strict';

const PROTO_PATH = __dirname + '/modules/protobuf/cnn_class.proto';
console.log("The PROTO_PATH is", PROTO_PATH);

var grpc = require('grpc');
var class_proto = grpc.load(PROTO_PATH).cnnclassify;

function classify(filename) {
    let client = new class_proto.ClassificationServer('SERVER_LOC:8000',
                                         grpc.credentials.createInsecure());
    let request_data = {
        filename: filename
    };

    client.classifyImage(request_data, function(err, response) {
        console.log("The server sent back", response.class_and_likelihood);
    });
}
classify("Put an actual filename here");
```

**Comment by ctiller** [comment] 2016-07-11 05:57
It's a spurious message (my fault, fixed at head). Look deeper and the
message tells you EOF: the connection was closed.

**Comment by heliumsoule** [comment] 2016-07-11 06:06
Thanks for the quick response. Was it closed by the server on receiving the
request? That would lead me to think the data serialization on the client
wasn't done correctly. I suspect it may be that the node grpc module
doesn't handle proto3, but it should as the examples are written in it on
the grpc github repo.

If it was by the server on realizing that the return output of ClassiyImg
(currently void) doesn't match the expected output, then that is fine. But
I am unsure as to why the print statement didn't print.

**Comment by y-zeng** [comment] 2016-07-11 22:52
"Failed parsing HTTP2" was added to some error messages even when the error was not caused by the HTTP2 parsing failure. #7318 removes such unnecessary details.

**Comment by y-zeng** [comment] 2016-07-13 21:37
Fixed in `v1.0.x` branch

**Closed by y-zeng** 2016-07-13 21:37 UTC
Labels: core

**Comment by viccro** [comment] 2016-07-21 17:00
Hi guys,

I'm trying to run the Hello World example on the grpc docs, and getting this same sort of error when I start the server (`python greeting_server.py`) run the client (`python greeting_client.py`):

`E0721 12:03:37.914036000 123145306509312 chttp2_transport.c:1810] close_transport: {"created":"@1469117017.913989000","description":"Failed parsing HTTP/2","file":"src/core/ext/transport/chttp2/transport/chttp2_transport.c","file_line":1726,"referenced_errors":[{"created":"@1469117017.913981000","description":"EOF","file":"src/core/lib/iomgr/tcp_posix.c","file_line":233}]}`

on the server side, and on the client side:

`Greeter client received: Hello, you!
E0721 12:03:37.913974000 140735171469312 chttp2_transport.c:1810] close_transport: {"created":"@1469117017.913944000","description":"FD shutdown","file":"src/core/lib/iomgr/ev_poll_posix.c","file_line":427}`

I'm using the `v1.0.x` branch, and reran `make` and `make install`, but it still seems to be happening. Am I doing something dumb?

**Comment by y-zeng** [comment] 2016-07-21 18:55
Hi @viccro, could you check if the branch you were using was at the head of `v1.0.x`?

**Comment by viccro** [comment] 2016-07-21 19:47
Yes, I am.
