### ISSUE TITLE
How  to receive multiple data streams in a thread at the same time?

### ISSUE THREAD

**Issue by dreamyzhang** [grpc/grpc#9280] opened 2017-01-09 10:09 UTC
as follows,  h1, h2 can block each other.  how to parallel execution？

service test{
	rpc hello1() returns (stream string){}
	rpc hello2() returns (stream string){}
}
def  h1(stub):
	hs = stub.hello1()
	for h in hs:
	   print(h)
def h2(stub):
	hs = stub.hello2()
	for h in hs:
	   print(h) 

gevent.joinall( [ gevent.spawn(h1, stub), gevent.spawn(h2, stub)]

**Comment by nathanielmanistaatgoogle** [comment] 2017-01-10 22:24
[gRPC Python is not currently compatible with gevent](https://github.com/grpc/grpc/issues/4629). If it's just parallel RPCs that you want to make, what about calls like `stub.hello1.future()` and `stub.hello2.future()`?

(Closing this as a duplicate of [issue 4629](https://github.com/grpc/grpc/issues/4629).)

**Closed by nathanielmanistaatgoogle** 2017-01-10 22:24 UTC
Labels: python

**Comment by dreamyzhang** [comment] 2017-01-11 02:50
it is like the following.  In the main.py,  How should I use stub.hello1.future() and stub.hello2.future()?

test.proto
service test{
	rpc hello1(args) returns (stream string){}
	rpc hello2(args) returns (stream string){}
}

main.py
authMetaPlug =  MyAuthPlugin()
callCredentials = grpc.metadata_call_credentials(authMetaPlug, None)
creds = grpc.ssl_channel_credentials(None, None, None)
channel_creds = grpc.composite_channel_credentials(creds, callCredentials)
channel = grpc.secure_channel('markets.invesmart.net:50052', channel_creds)
stub = test_pb2.test(channel)
h1 = stub.hello1("hello1")
for h in h1:
	print(h)
h2 = stub.hello2("hello2")
for h in h2:
	print(h)

**Comment by dreamyzhang** [comment] 2017-01-11 03:15
AttributeError: '_UnaryStreamMultiCallable' object has no attribute 'future'   
do as you say, throw a exception.

**Comment by nathanielmanistaatgoogle** [comment] 2017-01-11 04:52
Ah, I didn't notice that your RPC methods are response-streaming, not response-unary. In that case there is no `.future` attribute. In that case `h1` and `h2` are iterator objects that block when asked to emit their next value and we don't have a mechanism for asynchronously registering interest in when that happens.

Consume them in different threads?

**Comment by dreamyzhang** [comment] 2017-01-12 05:31
yeah， I use multithreading for every data streams now, and  using a connection. it is no  problem?

**Comment by nathanielmanistaatgoogle** [comment] 2017-01-12 06:25
Multiple RPCs sharing a single connection? That is in fact exactly the intended use of gRPC.

**Comment by dreamyzhang** [comment] 2017-01-12 06:39
yeah，  I using the stub   like a global variable for multithreading .   I think I don't care about the lock, grpc will care this?

**Comment by nathanielmanistaatgoogle** [comment] 2017-01-12 17:39
[Boo to global variables](https://google.github.io/styleguide/pyguide.html#Global_variables) but yes, the `grpc.Channel` objects created by gRPC Python are internally synchronized and thus safe for lock-free use from concurrent threads.
