### ISSUE TITLE
bad_ssl_alpn_test flake on msan build

### ISSUE THREAD

**Issue by yashykt** [grpc/grpc#24093] opened 2020-09-09 21:05 UTC
https://source.cloud.google.com/results/invocations/6191ebe7-d6b2-4685-ad0a-4a8db92ccbed/targets/%2F%2Ftest%2Fcore%2Fbad_ssl:bad_ssl_alpn_test@poller%3Depoll1/log

seen on #24080

**Comment by markdroth** [comment] 2020-09-10 19:14
I'm guessing that this was ultimately caused by this line at the top of the file:

```
E0908 22:13:20.113004648      18 subprocess_posix.cc:61]     execv 'test/core/bad_ssl/bad_ssl_alpn��erver' failed: No such file or directory
```

Looks like the path name itself was bad somehow.  I have no idea how this might have happened, but since this is a security test, I am assigning to Jiangtao for triage on his team.

**Comment by jiangtaoli2016** [comment] 2020-09-10 23:40
bad_ssl_apln_server builds from test/core/bad_ssl/servers/alpn.c (which has not changed for a long time). The error log does not make sense to me. Do we have a culprit?

**Closed** 2022-09-28 00:56 UTC
Labels: kind/bug, lang/core, disposition/BUILDNURSE, priority/P2, untriaged
