### ISSUE TITLE
C++ server completion queue 'ok' flag is vague

### ISSUE THREAD

**Issue by hellishfire** [grpc/grpc#12300] opened 2017-08-26 03:11 UTC
Please answer these questions before submitting your issue. 
 
### Should this be an issue in the gRPC issue tracker?
 Yes.
 
### What version of gRPC and what language are you using?
 grpc 1.4.x release, c++ api
 
### What operating system (Linux, Windows, …) and version?
 N/A
 
### What did you do?
Created an async server, ran a loop on its completion queue, i.e. cq->Next(&tag, &ok), and sometimes got ok == false

### What did you expect to see?
Status code/message telling me why ok == false
 
### What did you see instead?
There's no way to tell what caused 'ok' to be false. From my experiments, it may be caused by server shutdown, or client side call time out, or client side stream close, or perhaps something else. After digging into the source codes, I found out that when something on the server side goes wrong in the underlying core, gRPC only sets a cancelled flag in ServerContext  (which can be queried with its IsCancelled() api), and swallows the actual status code of the error. So when ok == false, the only clue I can get is the cancelled flag, which isn't very helpful.

**Comment by yfinkelstein** [comment] 2017-08-31 00:35
@hellishfire  Thanks for filing this. I have the same complaint. In fact, we ended up having our own `is_is_shutdown` state variable to distinguish between ok=false caused by client connection reset or other issues mentioned above - in this situation we do need to re-register tag, - and ok=false caused by true shutdown when we don't want to re-register tags.

**Comment by tjb1216** [comment] 2017-09-11 03:29
+1, MARK

**Comment by vjpai** [comment] 2017-09-22 22:23
I gave this answer recently on the grpc-io forum, but should have also posted it here. Here goes:

Server-side request an RPC: ok indicates that the RPC has indeed been started. If it is false, the server has been Shutdown before this particular call got matched to an incoming RPC. This is actually the case that you were interested in, but I've gone ahead and documented the other cases below.

Client-side start an RPC: ok indicates that the RPC is going to go to the wire. If it is false, it not going to the wire. This would happen if the channel is either permanently broken or transiently broken but with the fail-fast option.

Client-side Write, Client-side WritesDone, Server-side Write, Server-side Finish, Server-side SendInitialMetadata (which is typically included in Write or Finish when not done explicitly): ok means that the data/metadata/status/etc is going to go to the wire. If it is false, it not going to the wire because the call is already dead (i.e., canceled, deadline expired, other side dropped the channel, etc).

Client-side Read, Server-side Read, Client-side RecvInitialMetadata (which is typically included in Read if not done explicitly): ok indicates whether there is a valid message that got read. If not, you know that there are certainly no more messages that can ever be read from this stream.

Client-side Finish: ok should always be true

Server-side AsyncNotifyWhenDone: ok should always be true

I won't close the issue until we document it more officially.

**Comment by vjpai** [comment] 2017-10-16 17:57
Merging this into #13019

**Closed** 2017-10-16 17:58 UTC
Labels: lang/c++

**Comment by ysammy** [comment] 2018-07-11 22:42
@vjpai For Client-side Read, what does it mean for there to be "certainly no more messages that can ever be read from this stream"? Which events (on the client, or on the server) can cause this condition?
