### ISSUE TITLE
I would like to know actual error cause in Python

### ISSUE THREAD

**Issue by igor-davidyuk** [grpc/grpc#25189] opened 2021-01-19 13:25 UTC
### Is your feature request related to a problem? Please describe.
I set up an experiment when a client tries to connect to the server with a rotten cert and gets rejected.
grpc.RpcError that I get looks like this:
`<_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses"
	debug_error_string = "{"created":"@1611061781.203478497","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":4142,"referenced_errors":[{"created":"@1611061781.203471320","description":"failed to connect to all addresses","file":"src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc","file_line":397,"grpc_status":14}]}"
`
But I see logs (set to debug mode), that show the actual reason for the connection failure:
`E0119 16:09:46.215369411   10574 ssl_transport_security.cc:1446] Handshake failed with fatal error SSL_ERROR_SSL: error:0400006b:RSA routines:OPENSSL_internal:BLOCK_TYPE_IS_NOT_01.
D0119 16:09:46.215463429   10574 security_handshaker.cc:184] Security handshake failed: {"created":"@1611061786.215437927","description":"Handshake failed","file":"src/core/lib/security/transport/security_handshaker.cc","file_line":307,"tsi_code":10,"tsi_error":"TSI_PROTOCOL_FAILURE"}
I0119 16:09:46.215605747   10574 subchannel.cc:1076]         Connect failed: {"created":"@1611061786.215437927","description":"Handshake failed","file":"src/core/lib/security/transport/security_handshaker.cc","file_line":307,"tsi_code":10,"tsi_error":"TSI_PROTOCOL_FAILURE"}`

### Describe the solution you'd like
I would like to have more information in the exception.

**Comment by markdroth** [comment] 2021-01-19 15:41
Duplicate of #22883.

**Closed by markdroth** 2021-01-19 15:41 UTC
Labels: kind/enhancement, priority/P2
