### ISSUE TITLE
NativeExtension.LoadUnmanagedLibrary() throws an exception with .NET Core single file deployment 

### ISSUE THREAD

**Issue by cristalink** [grpc/grpc#24650] opened 2020-11-03 10:00 UTC
### What version of gRPC and what language are you using?
Grpc.Core 2.27.0, included in Google.Cloud.Translate.V3. The issue seems to exist to the latest master branch, too.

### What operating system (Linux, Windows,...) and version?
Windows 10 Enterprise 64 bit

### What runtime / compiler are you using (e.g. python version or version of gcc)
N/A - Compiled NuGet package Google.Cloud.Translate.V3 (2.0.0)

### What did you do?
Please provide either 1) A unit test for reproducing the bug or 2) Specific steps for us to follow to reproduce the bug. If there’s not enough information to debug the problem, gRPC team may close the issue at their discretion. You’re welcome to re-open the issue once you have a reproduction.

I use Google.Cloud.Translate.V3 in a C# .NET Core 5.0 RC2 application published with single file deployment. The exception "Value cannot be null. (Parameter 'path1')" is raised on an attempt to initialize the Google Translation Service Client, see the call stack below.

   at System.IO.Path.Combine(String path1, String path2) in /_/src/libraries/System.Private.CoreLib/src/System/IO/Path.cs:line 325
   at Grpc.Core.Internal.NativeExtension.LoadUnmanagedLibrary()
   at Grpc.Core.Internal.NativeExtension.LoadNativeMethods()
   at Grpc.Core.Internal.NativeExtension..ctor()
   at Grpc.Core.Internal.NativeExtension.Get()
   at Grpc.Core.Internal.NativeMethods.Get()
   at Grpc.Core.GrpcEnvironment.GrpcNativeInit()
   at Grpc.Core.GrpcEnvironment..ctor()
   at Grpc.Core.GrpcEnvironment.AddRef()
   at Grpc.Core.Channel..ctor(String target, ChannelCredentials credentials, IEnumerable`1 options)
   at Google.Api.Gax.Grpc.GrpcCore.GrpcCoreAdapter.CreateChannelImpl(String endpoint, ChannelCredentials credentials, GrpcChannelOptions options)
   at Google.Api.Gax.Grpc.GrpcAdapter.CreateChannel(String endpoint, ChannelCredentials credentials, GrpcChannelOptions options)
   at Google.Api.Gax.Grpc.ClientBuilderBase`1.CreateChannel(String endpoint, ChannelCredentials credentials)
   at Google.Api.Gax.Grpc.ClientBuilderBase`1.CreateCallInvoker()
   at Google.Cloud.Translate.V3.TranslationServiceClientBuilder.BuildImpl()
   at Google.Cloud.Translate.V3.TranslationServiceClientBuilder.Build()
   at CopyTranslate.MainWindow..ctor() in [redacted]\MainWindow.xaml.cs:line 46

The exception seems to happen in https://github.com/grpc/grpc/blob/master/src/csharp/Grpc.Core/Internal/NativeExtension.cs:

private static UnmanagedLibrary LoadUnmanagedLibrary()
        {
            // TODO: allow customizing path to native extension (possibly through exposing a GrpcEnvironment property).
            // See https://github.com/grpc/grpc/pull/7303 for one option.
            var assemblyDirectory = Path.GetDirectoryName(GetAssemblyPath());

            // With "classic" VS projects, the native libraries get copied using a .targets rule to the build output folder
            // alongside the compiled assembly.
            // With dotnet cli projects targeting net45 framework, the native libraries (just the required ones)
            // are similarly copied to the built output folder, through the magic of Microsoft.NETCore.Platforms.
            var classicPath = Path.Combine(assemblyDirectory, GetNativeLibraryFilename());

GetAssemblyPath() in the above code returns null because Path.GetDirectoryName(GetAssemblyPath()) returns null because Assembly.Location and similar properties are unavailable with single file deployment, see https://docs.microsoft.com/en-us/dotnet/core/deploying/single-file.

To reproduce the issue, cause NativeMethods.LoadUnmanagedLibrary() to be called in any .NET Core 5.0 app deployed with single file deployment. 

### What did you expect to see?
The exception should not have occurred.

### What did you see instead?
The exception occurs.

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

See [TROUBLESHOOTING.md](https://github.com/grpc/grpc/blob/master/TROUBLESHOOTING.md) for how to diagnose problems better.

**Comment by jtattermusch** [comment] 2020-11-04 08:47
this is a dupe of https://github.com/grpc/grpc/issues/24266

**Closed by jtattermusch** 2020-11-04 08:47 UTC
Labels: kind/bug, priority/P2
