### ISSUE TITLE
FLAKE: bins/tsan/h2_http_proxy_test hpack_size GRPC_POLL_STRATEGY=epoll1

### ISSUE THREAD

**Issue by muxi** [grpc/grpc#12688] opened 2017-09-21 23:37 UTC
Failed in master and https://sponge.corp.google.com/target?id=3a0c73bf-a2d2-4861-a516-7a9a9cc150c3&target=github/grpc/c_linux_tsan_native&searchFor=&show=ALL&sortBy=STATUS
```
x7d5c0000f880
I0920 21:35:23.402915420   27109 hpack_size.c:182]           Running test: test_size:e=0:d=0/chttp2/fullstack
I0920 21:35:23.407354542   27109 http_proxy_fixture.c:497]   Proxy address: localhost:20855
I0920 21:35:23.447122996   27109 http_connect_handshaker.c:305] Connecting to server localhost:19529 via HTTP proxy ipv6:[::1]:20855
D0920 21:35:23.447330657    6307 http_proxy_fixture.c:341]   on_read_request_done: 0x7d8c0000e000 "No Error"
I0920 21:35:24.828532439    6307 http_proxy_fixture.c:136]   HTTP proxy client read: {"created":"@1505943324.828397859","description":"Socket closed","fd":12,"file":"src/core/lib/iomgr/tcp_posix.c","file_line":432,"target_address":"ipv6:[::1]:33564"}
I0920 21:35:24.828870109    6307 http_proxy_fixture.c:136]   HTTP proxy server read: {"created":"@1505943324.828619875","description":"FD Shutdown","file":"src/core/lib/iomgr/lockfree_event.c","file_line":182,"referenced_errors":[{"created":"@1505943324.828397859","description":"Socket closed","fd":12,"file":"src/core/lib/iomgr/tcp_posix.c","file_line":432,"target_address":"ipv6:[::1]:33564"}]}
D0920 21:35:24.828910706    6307 http_proxy_fixture.c:108]   endpoints: 0x7d5c0000f880 0x7d5c00019d00
I0920 21:35:25.831845972   27109 hpack_size.c:182]           Running test: test_size:e=0:d=100/chttp2/fullstack
I0920 21:35:25.838335492   27109 http_proxy_fixture.c:497]   Proxy address: localhost:17233
I0920 21:35:25.874205098    8192 http_connect_handshaker.c:305] Connecting to server localhost:26069 via HTTP proxy ipv6:[::1]:17233
D0920 21:35:25.874522893    8192 http_proxy_fixture.c:341]   on_read_request_done: 0x7d8c0000e000 "No Error"
I0920 21:35:27.388046957    8192 http_proxy_fixture.c:136]   HTTP proxy client read: {"created":"@1505943327.387912785","description":"Socket closed","fd":12,"file":"src/core/lib/iomgr/tcp_posix.c","file_line":432,"target_address":"ipv6:[::1]:35780"}
I0920 21:35:27.389377331    8192 http_proxy_fixture.c:136]   HTTP proxy server read: {"created":"@1505943327.389120326","description":"FD Shutdown","file":"src/core/lib/iomgr/lockfree_event.c","file_line":182,"referenced_errors":[{"created":"@1505943327.387912785","description":"Socket closed","fd":12,"file":"src/core/lib/iomgr/tcp_posix.c","file_line":432,"target_address":"ipv6:[::1]:35780"}]}
D0920 21:35:27.389422472    8192 http_proxy_fixture.c:108]   endpoints: 0x7d5c00035980 0x7d5c00019d00
I0920 21:35:28.390510594   27109 hpack_size.c:182]           Running test: test_size:e=0:d=1000/chttp2/fullstack
I0920 21:35:28.396147638   27109 http_proxy_fixture.c:497]   Proxy address: localhost:12417
I0920 21:35:28.432760360   27109 http_connect_handshaker.c:305] Connecting to server localhost:28897 via HTTP proxy ipv6:[::1]:12417
D0920 21:35:28.432978894    9770 http_proxy_fixture.c:341]   on_read_request_done: 0x7d8c0000e000 "No Error"
I0920 21:35:29.836788247    9770 http_proxy_fixture.c:136]   HTTP proxy client read: {"created":"@1505943329.836633448","description":"Socket closed","fd":12,"file":"src/core/lib/iomgr/tcp_posix.c","file_line":432,"target_address":"ipv6:[::1]:46948"}
I0920 21:35:29.837130456    9770 http_proxy_fixture.c:136]   HTTP proxy server read: {"created":"@1505943329.836883229","description":"FD Shutdown","file":"src/core/lib/iomgr/lockfree_event.c","file_line":182,"referenced_errors":[{"created":"@1505943329.836633448","description":"Socket closed","fd":12,"file":"src/core/lib/iomgr/tcp_posix.c","file_line":432,"target_address":"ipv6:[::1]:46948"}]}
D0920 21:35:29.837171696    9770 http_proxy_fixture.c:108]   endpoints: 0x7d5c0002e280 0x7d5c0002f080
I0920 21:35:30.838609843   27109 hpack_size.c:182]           Running test: test_size:e=0:d=32768/chttp2/fullstack
I0920 21:35:30.846607078   27109 http_proxy_fixture.c:497]   Proxy address: localhost:7562
I0920 21:35:30.878688200   27109 http_connect_handshaker.c:305] Connecting to server localhost:16192 via HTTP proxy ipv6:[::1]:7562
D0920 21:35:30.878943285   11356 http_proxy_fixture.c:341]   on_read_request_done: 0x7d8c0000e000 "No Error"
I0920 21:35:32.217461336   11356 http_proxy_fixture.c:136]   HTTP proxy server read: {"created":"@1505943332.217287168","description":"Socket closed","fd":13,"file":"src/core/lib/iomgr/tcp_posix.c","file_line":432,"target_address":"ipv6:[::1]:16192"}
I0920 21:35:32.217778269   11356 http_proxy_fixture.c:136]   HTTP proxy client read: {"created":"@1505943332.217508748","description":"FD Shutdown","file":"src/core/lib/iomgr/lockfree_event.c","file_line":182,"referenced_errors":[{"created":"@1505943332.217287168","description":"Socket closed","fd":13,"file":"src/core/lib/iomgr/tcp_posix.c","file_line":432,"target_address":"ipv6:[::1]:16192"}]}
D0920 21:35:32.217819344   11356 http_proxy_fixture.c:108]   endpoints: 0x7d5c00028080 0x7d5c00027980
I0920 21:35:33.220171090   27109 hpack_size.c:182]           Running test: test_size:e=0:d=4194304/chttp2/fullstack
I0920 21:35:33.234146077   27109 http_proxy_fixture.c:497]   Proxy address: localhost:2501
I0920 21:35:33.270653097   13375 http_connect_handshaker.c:305] Connecting to server localhost:14868 via HTTP proxy ipv6:[::1]:2501
D0920 21:35:33.270918227   13375 http_proxy_fixture.c:341]   on_read_request_done: 0x7d8c0000e000 "No Error"
I0920 21:35:34.710861664   13375 http_proxy_fixture.c:136]   HTTP proxy client read: {"created":"@1505943334.710718267","description":"Socket closed","fd":12,"file":"src/core/lib/iomgr/tcp_posix.c","file_line":432,"target_address":"ipv6:[::1]:45978"}
I0920 21:35:34.711189850   13375 http_proxy_fixture.c:136]   HTTP proxy server read: {"created":"@1505943334.710951670","description":"FD Shutdown","file":"src/core/lib/iomgr/lockfree_event.c","file_line":182,"referenced_errors":[{"created":"@1505943334.710718267","description":"Socket closed","fd":12,"file":"src/core/lib/iomgr/tcp_posix.c","file_line":432,"target_address":"ipv6:[::1]:45978"}]}
D0920 21:35:34.711228728   13375 http_proxy_fixture.c:108]   endpoints: 0x7d5c0002e980 0x7d5c00024500
I0920 21:35:35.712625274   27109 hpack_size.c:182]           Running test: test_size:e=100:d=4096/chttp2/fullstack
I0920 21:35:35.721639268   27109 http_proxy_fixture.c:497]   Proxy address: localhost:5730
I0920 21:35:35.749648944   27109 http_connect_handshaker.c:305] Connecting to server localhost:25395 via HTTP proxy ipv6:[::1]:5730
D0920 21:35:35.749887539   15127 http_proxy_fixture.c:341]   on_read_request_done: 0x7d8c0000e000 "No Error"
E0920 21:36:01.062825694   27109 cq_verifier.c:273]          cq returned unexpected event: OP_COMPLETE: tag:0x1 OK
E0920 21:36:01.062904462   27109 cq_verifier.c:280]          expected tags:
tag(101) GRPC_OP_COMPLETE success=1 test/core/end2end/tests/hpack_size.c:303




*******************************
Caught signal SIGABRT
==================
WARNING: ThreadSanitizer: signal-unsafe call inside of a signal (pid=27109)
    #0 malloc /llvm/projects/compiler-rt/lib/tsan/rtl/tsan_interceptors.cc:595 (h2_http_proxy_test+0x000000442d58)
    #1 <null> <null> (ld-linux-x86-64.so.2+0x00000000caad)
    #2 crash_handler /var/local/git/grpc/test/core/util/test_config.c:245:13 (h2_http_proxy_test+0x00000091a758)
    #3 __tsan::CallUserSignalHandler(__tsan::ThreadState*, bool, bool, bool, int, my_siginfo_t*, void*) /llvm/projects/compiler-rt/lib/tsan/rtl/tsan_interceptors.cc:1951 (h2_http_proxy_test+0x000000423ad6)
    #4 cq_verify /var/local/git/grpc/test/core/end2end/cq_verifier.c:282:7 (h2_http_proxy_test+0x00000051ce83)
    #5 simple_request_body /var/local/git/grpc/test/core/end2end/tests/hpack_size.c:304:3 (h2_http_proxy_test+0x0000004d71a2)
    #6 test_size /var/local/git/grpc/test/core/end2end/tests/hpack_size.c:378:5 (h2_http_proxy_test+0x0000004d64b6)
    #7 hpack_size /var/local/git/grpc/test/core/end2end/tests/hpack_size.c:392:7 (h2_http_proxy_test+0x0000004d6255)
    #8 grpc_end2end_tests /var/local/git/grpc/test/core/end2end/end2end_tests.c:376:7 (h2_http_proxy_test+0x0000004b1503)
    #9 main /var/local/git/grpc/test/core/end2end/fixtures/h2_http_proxy.c:122:5 (h2_http_proxy_test+0x0000004afb4c)

SUMMARY: ThreadSanitizer: signal-unsafe call inside of a signal (/lib64/ld-linux-x86-64.so.2+0xcaad) 
==================
```

**Comment by ctiller** [comment] 2017-09-21 23:40
Why are you assigning this to me?

**Comment by muxi** [comment] 2017-09-22 00:09
Thought original author might know at a glance... I can reassign.

**Comment by dgquintas** [comment] 2017-09-24 02:01
Duplicate of #12394

**Closed by dgquintas** 2017-09-24 02:01 UTC
Labels: infra/BUILDPONY
