### ISSUE TITLE
interop test failure: cloud_to_cloud :c++:java_server:large_unary

### ISSUE THREAD

**Issue by jtattermusch** [grpc/grpc#4461] opened 2015-12-15 06:09 UTC
```
I1215 02:24:23.591511737       1 client.cc:89]               Testing these cases: large_unary
I1215 02:24:23.593644870       1 interop_client.cc:273]      Sending a large unary rpc...
I1215 02:24:23.594385581       9 socket_utils_common_posix.c:148] Disabling AF_INET6 sockets because ::1 is not available.
D1215 02:24:23.600539505       1 frame_settings.c:243]       adding 983041 for initial_window change
E1215 02:24:23.612264459       1 interop_client.cc:164]      assertion failed: request->response_compression() == GetInteropCompressionTypeFromCompressionAlgorithm( inspector.GetCallCompressionAlgorithm())
```

https://grpc-testing.appspot.com/job/gRPC_interop_pull_requests/945/testReport/(root)/tests/cloud_to_cloud_c___java_server_large_unary/

**Comment by jtattermusch** [comment] 2015-12-15 06:09
Looks like this has to do with compression.

CC @ejona86

**Comment by jtattermusch** [comment] 2015-12-15 06:10
also https://grpc-testing.appspot.com/job/gRPC_interop_master/1680/testReport/

**Comment by ejona86** [comment] 2015-12-15 16:35
cc @carl-mastrangelo 

grpc/grpc-java#1271 was recently committed, which may fix this issue. We're also aware of grpc/grpc-java#1278

**Comment by carl-mastrangelo** [comment] 2015-12-15 19:18
Looks like the issue is that the rpc itself needs to be setting the compression algorithm, rather than being auto negotiated by the client.  The test checks that no compression happens by setting it to 0 in the call, but the java server still negotiates gzip.  I suspect this is because it is still in the accept headers, but I am not sure.

**Comment by ctiller** [comment] 2015-12-15 20:14
https://grpc-testing.appspot.com/job/gRPC_interop_master/1694/testReport/(root)/tests/cloud_to_cloud_c___java_server_large_unary/

**Comment by ctiller** [comment] 2015-12-15 20:15
Enabling the environment variable GRPC_TRACE=http might be a good way of debugging what the C++ client thinks it's receiving.

**Comment by ejona86** [comment] 2015-12-15 20:42
Yeah, that assert looks wrong, as it appears to be comparing a value in the response to the native gRPC compression. This seems related to some of my comments in grpc/grpc#3062 which haven't been addressed, but that I've also failed to push on getting fixed.

**Comment by dgquintas** [comment] 2015-12-15 22:05
I've just talked to @carl-mastrangelo . @ejona86 , let's reconvene after meeting, ~3:30

**Closed** 2016-03-01 22:53 UTC
Labels: BUILDPONY, c++, interop
