### ISSUE TITLE
[FLAKE] Basic Tests C/C++ MacOS

### ISSUE THREAD

**Issue by lidizheng** [grpc/grpc#20923] opened 2019-11-04 18:44 UTC
Test timeout after 7200s.
https://source.cloud.google.com/results/invocations/90b68e1b-9b9c-4d29-aa71-ec8e64dfaf39/targets/grpc%2Fcore%2Fpull_request%2Fmacos%2Fgrpc_basictests_c_cpp/log

**Comment by sheenaqotj** [comment] 2019-11-04 19:17
Esun suggested assigning to Jan since he configured a timeout in tools/internal_ci/macos/grpc_basictests_c_cpp.cfg

**Comment by jtattermusch** [comment] 2019-11-13 11:06
This is a dupe of https://github.com/grpc/grpc/issues/20694.

**Closed by jtattermusch** 2019-11-13 11:06 UTC
Labels: infra/BUILDPONY, kind/bug, lang/c++, platform/macOS, priority/P2
