### ISSUE TITLE
pollset_set_unref nested loop

### ISSUE THREAD

**Issue by ming535** [grpc/grpc#27397] opened 2021-09-18 08:06 UTC
### What version of gRPC and what language are you using?
grpc 1.26 c++

### What operating system (Linux, Windows,...) and version?
linux 3.10.0

### What runtime / compiler are you using (e.g. python version or version of gcc)
gcc 4.8.5

### What did you do?
Please provide either 1) A unit test for reproducing the bug or 2) Specific steps for us to follow to reproduce the bug. If there’s not enough information to debug the problem, gRPC team may close the issue at their discretion. You’re welcome to re-open the issue once you have a reproduction.

I was running into a nested loop in the coredump
`#1  0x000000000193b472 in pollset_set_unref (pss=0x7f868be1b608)
    at /blade-kv/deps/grpc-1.26.0/src/core/lib/iomgr/ev_epollex_linux.cc:1326
#2  0x000000000193b472 in pollset_set_unref (pss=0x7f85d8cb0688)
    at /blade-kv/deps/grpc-1.26.0/src/core/lib/iomgr/ev_epollex_linux.cc:1326
#3  0x000000000193b472 in pollset_set_unref (pss=0x7f85d8cb7e88)
    at /blade-kv/deps/grpc-1.26.0/src/core/lib/iomgr/ev_epollex_linux.cc:1326
#4  0x000000000193b472 in pollset_set_unref (pss=0x7f86821be408)
    at /blade-kv/deps/grpc-1.26.0/src/core/lib/iomgr/ev_epollex_linux.cc:1326
#5  0x000000000193b472 in pollset_set_unref (pss=0x7f868be1a708)
    at /blade-kv/deps/grpc-1.26.0/src/core/lib/iomgr/ev_epollex_linux.cc:1326
#6  0x000000000193b472 in pollset_set_unref (pss=0x7f85d8cbe088)
    at /blade-kv/deps/grpc-1.26.0/src/core/lib/iomgr/ev_epollex_linux.cc:1326
#7  0x000000000193b472 in pollset_set_unref (pss=0x7f868be1a308)
    at /blade-kv/deps/grpc-1.26.0/src/core/lib/iomgr/ev_epollex_linux.cc:1326
#8  0x000000000193b472 in pollset_set_unref (pss=0x7f85d8cbe988)
    at /blade-kv/deps/grpc-1.26.0/src/core/lib/iomgr/ev_epollex_linux.cc:1326`

It seems that this happens when there is client connection error:

I0917 14:13:19.325135442     474 subchannel.cc:1003]         Connect failed: {"created":"@1631859199.325095595","description":"Failed to connect to remote host: Connection refused","errno":111,"file":"/deps/grpc-1.26.0/src/core/lib/iomgr/tcp_client_posix.cc","file_line":200,"os_error":"Connection refused","syscall":"connect","target_address":"ipv4:192.168.67.220:2379"}
I0917 14:13:19.325182632     474 subchannel.cc:942]          Subchannel 0x7f868bb0b488: Retry in 998 milliseconds

### What did you expect to see?
no coredump

### What did you see instead?
coredump with infinite nested loop

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

See [TROUBLESHOOTING.md](https://github.com/grpc/grpc/blob/master/TROUBLESHOOTING.md) for how to diagnose problems better.

**Comment by yashykt** [comment] 2021-09-23 17:35
1.26 is pretty old. Please try it again with the latest release/ HEAD.

**Comment by ming535** [comment] 2021-09-24 08:08
Is there any known PR that is related to this issue?

**Comment by yashykt** [comment] 2021-10-06 23:22
I'm not sure but running from HEAD would be a good thing anyway just to cover all bases. Also, is there a way to reproduce this?

**Comment by yashykt** [comment] 2022-03-29 06:58
Closing since the epollex engine has now been deleted, and there hasn't been any other activity on the bug.

**Closed by yashykt** 2022-03-29 06:58 UTC
Labels: kind/bug, lang/c++, priority/P2, disposition/requires reporter action, untriaged
