### ISSUE TITLE
Provide a simple event-processing loop for C++ async API

### ISSUE THREAD

**Issue by vjpai** [grpc/grpc#7352] opened 2016-07-12 22:56 UTC
This most likely belongs as a grpc-ecosystem contribution, but it would be nice to have easier interfaces to the C++ async API for people who are used to callbacks rather than CQ-style work.

Suggested by https://groups.google.com/forum/#!topic/grpc-io/7P8QvBBNq_E

**Comment by kangjoni76** [comment] 2016-07-13 22:40
+1

**Comment by ctiller** [comment] 2016-07-15 00:26
There's a few design options here:
- future based (with a grpc::Future most likely), whereby you can write:
```c
grpc::future<MyProtoMessage> f = stream->AsyncRead();
// ... stuff
f.get();
```
- callback based
```c
stream->AsyncRead([](const MyProtoMessage& p) {
  // ...
});
```

The first would fit a little more naturally into the current API as backing threads are still provided by the application. The latter (or a future with a .then() method) would require backing threads provided and would need some work from @sreecha likely to generalize the thread pool work he's about to do.

**Comment by jinq0123** [comment] 2016-08-07 06:51
I am implementing gRpc with C++ callback interface. Both client and server use a callback to implement async API.

https://github.com/jinq0123/grpc

Greeter example seems OK.  Stream RPC is not ready. Route guide example is crashing. See examples/cpp_cb

```C++
  // Async client.
  helloworld::Greeter::Stub stub(channel);
  HelloRequest request;
  request.set_name("async_world");
  stub.AsyncSayHello(request, [](const helloworld::HelloReply& resp) {
      std::cout << "Async greeter received: " << resp.message() << std::endl;
    });
  stub.BlockingRun();
```

**Comment by lipixun** [comment] 2018-06-04 03:18
Just a friendly ping on this issue, does anyone still working on it? :)

**Comment by Bklyn** [comment] 2018-06-19 21:55
@jinq0123 your fork looks amazing and the programming model looks nicer than the "stock" GRPC interfaces; are you using this code actively?  It does not seem to have updated much since you commented here in 2016, but perhaps that just means it is very stable :)

**Comment by jinq0123** [comment] 2018-06-20 07:48
@Bklyn I am using grpc-go now. C++ grpc_cb is not yet ready for product usage, because it still has many things todo, such as tls, metadata and compress. But I hope the code is clean enough to be developed on by others.

**Comment by sreecha** [comment] 2018-08-23 18:39
Reassigning this back to @vjpai since he is working on the callback based API  (please reassign once we have a clearer idea on how this will look)

**Comment by yiakwy** [comment] 2019-02-22 15:22
I support for the future based solution. I used to implement async and await based on future for python.  It makes it possible for people to write async codes in a synchronous manner and easy to debug if your engine is robust enough.

**Comment by hcaseyal** [comment] 2019-02-22 16:32
@vjpai can you provide an update on the official status of the callback-based API?

**Comment by vjpai** [comment] 2019-03-13 05:28
Status update: we'll start the process of making the callback API non-experimental once #16504 and #16505 are resolved

**Comment by Bklyn** [comment] 2019-09-09 10:02
Bump

**Comment by vjpai** [comment] 2019-10-16 00:08
Since this particular issue is effectively about the iomgr, I'm reassigning to @guantaol

**Comment by uecasm** [comment] 2020-02-24 03:48
I think that this needs to be prioritised more; as it stands I can't consider gRPC to be a robust C++ networking library.  (Though many of the other ports are better in that regard, somewhat ironically.)

Streams are gRPC's main selling-point from other RPC systems, but implementing a sync server-side service returning a stream is obviously silly (it blocks a network worker thread potentially forever while waiting for the next application-side event to send -- multiplied by the number of clients and possible concurrent RPCs, this can't possibly scale) -- and RPCs that accept a stream (or are bidi) is just as bad.  Any kind of streaming RPC **must** be implemented as async, but the current interface of polling CompletionQueues is a barrier to entry, especially as there don't appear to be any realistic examples (multiple services or multiple RPCs).

Ideally this should have an async API modelled after Boost.Asio, since that's going to land in the C++ Standard via the Networking TS at some point (though still not quite C++20).

Or at the very least there ought to be some example code of how to wrap gRPC with Boost.Asio to provide that sort of interface.  Asio already has a completion queue of its own, so the concepts shouldn't be incompatible.

**Comment by DinoStray** [comment] 2020-03-10 22:26
The CQ-style is boring, how can I distinguish the "write done" event and the  "read done" event at the same time if I use bi stream?

**Comment by uecasm** [comment] 2020-03-11 09:06
You have to use two different tags.  If you're using the tag-is-a-pointer style that means you have to use two different objects.  There's many different ways you can do that.

FWIW, I did start on writing a bidi example that uses coroutines, just as an experiment.  Got a little way into it (but it's looking promising) before being distracted by something else, but hopefully I'll get back to it at some point.

**Comment by metellius** [comment] 2020-03-11 11:22
> The CQ-style is boring, how can I distinguish the "write done" event and the "read done" event at the same time if I use bi stream?

I have a helper class that just carries a virtual "invoke" function and a std::function callback. In the calldata objects I then have one for read-operations, write, finish, start and done. Every time I need to supply a tag for a grpc operation I specify the pointer to that helper, and when the callback is invoked it then has a pointer to the calldata object and also knows exactly what operation it's getting the grpc response to.

**Comment by Bklyn** [comment] 2020-05-06 11:48
Please don't close this!

**Comment by markdroth** [comment] 2020-05-06 15:56
Closing this as a duplicate of #20194.

**Closed by markdroth** 2020-05-06 15:56 UTC
Labels: kind/enhancement, lang/c++, priority/P2

**Comment by Bklyn** [comment] 2020-05-06 16:36
Woah!  Is the official callback API landing soon?!?!

**Comment by Bklyn** [comment] 2020-05-06 16:37
> I have a helper class that just carries a virtual "invoke" function and a std::function callback. In the calldata objects I then have one for read-operations, write, finish, start and done. Every time I need to supply a tag for a grpc operation I specify the pointer to that helper, and when the callback is invoked it then has a pointer to the calldata object and also knows exactly what operation it's getting the grpc response to.

@metellius any chance you could share this helper implementation?

**Comment by markdroth** [comment] 2020-05-06 16:48
@Bklyn I believe the only thing we're waiting for to make the callback API available in OSS is to have the libuv-based EventManager implementation.

**Comment by metellius** [comment] 2020-05-07 05:51
@Bklyn 
```
struct TagResponder
{
    std::function<void(bool)> cb;
    TagResponder(std::function<void(bool)> cb) : cb(cb) {}
};
struct CallData {
   grpc::ClientContext context;
   TagResponder onWrite;
   TagResponder onRead;
   TagResponder onFinish;

   CallData() :
     onRead([this] {
         // do something with read data
     })
   ....
};
void doSomeRead()
{
    callData->readerWriter->Read(&callData->readBuffer, &callData->onRead);
}
void eventLoop()
{
    bool ok;
    void * tag;
    while (true)
    {
        if (!cq->Next(&tag, &ok))
            break;
        logger().debug(5, "gateway: got tag, ok: {}", ok);
        auto tagResponder = static_cast<TagResponder*>(tag);
        tagResponder->cb(ok);
    }
}
```

**Comment by arthur-tacca** [comment] 2020-05-07 22:18
@metellius  Why not just use `std::function<void(bool)>` directly in place of `TagResponder` since that's the only data member? e.g. `static_cast<std::function<void(bool)>*>(tag)(ok);`? Or you could `typedef TagResponder std::function<void(bool)>`.

**Comment by metellius** [comment] 2020-05-08 12:27
> @metellius Why not just use `std::function<void(bool)>` directly in place of `TagResponder` since that's the only data member? e.g. `static_cast<std::function<void(bool)>*>(tag)(ok);`? Or you could `typedef TagResponder std::function<void(bool)>`.

I left out some other members we also use that carry a std::string that describes what tag it is and who it belongs to (useful in general to trace what grpc is up to), as well as a bool storing whether we it is pending a return from grpc or not (superuseful for catching early things like calling Read twice on the same rpc, which otherwise leads to misc asserts inside libgrpc that practically never tells me what exactly someone did wrong)

**Comment by npuichigo** [comment] 2020-12-06 10:50
@uecasm Is there any progress on the bidi example that uses coroutines? It’s cool that we can write grpc in c++ like c# using await/async maybe after c++20/23.

**Comment by uecasm** [comment] 2020-12-06 11:06
No, in the end I decided that gRPC just wasn't ready for production use in C++ and went with a different protocol for that project.

I might have another look at it once they finally implement the callback API; without that you're just fighting the library every step of the way.

**Comment by Bklyn** [comment] 2020-12-10 13:54
> No, in the end I decided that gRPC just wasn't ready for production use in C++ and went with a different protocol for that project.  I might have another look at it once they finally implement the callback API; without that you're just fighting the library every step of the way.

@uecasm I totally agree about the impedance mismatch w/the current gRPC APIs.  Care to comment on what you used instead of gRPC?

**Comment by uecasm** [comment] 2020-12-10 20:42
> Care to comment on what you used instead of gRPC?

Protobuf message queue over a hand-rolled TCP connection.  So not using the actual RPC parts in the end.

**Comment by Bklyn** [comment] 2021-10-29 18:01
@npuichigo These projects appear quite new, but very promising.  Thanks for the info!

**Comment by wendajiang** [comment] 2023-06-12 09:48
> #20194

Unfortunately, the asio async model look like be replaced by P2300 std::execution(sender/reciever model) :)

**Comment by uecasm** [comment] 2023-06-12 13:20
I really hope not.  Asio is needlessly complicated, but std::execution is much, much worse.

**Comment by wendajiang** [comment] 2023-06-12 15:39
> I really hope not. Asio is needlessly complicated, but std::execution is much, much worse.

Recently, I read the isocpp.org papersP2444r0,P2469,P2471,P2762 , it seems like more people prefer the std::execution proposal, and the committee would propel execution standardization at C++23，and the networking TS would be pending before so called "unified" async model standardization. Maybe networking delay to C++26 or later.

**Comment by flyish** [comment] 2024-10-22 10:04
This usage is really quite confusing, and I hope it can be improved.
