### ISSUE TITLE
python str/unicode error in metadata with grpc 1.8.0

### ISSUE THREAD

**Issue by r00tat** [grpc/grpc#13752] opened 2017-12-13 16:52 UTC
### What version of gRPC and what language are you using?
 
1.8.0, python 2.7
 
### What operating system (Linux, Windows, …) and version?
 
debian stretch (dockerized)
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
 
  * Python 2.7.13
  * grpcio==1.8.0
  * google-cloud-datastore==1.4.0

grpcio and google-cloud-datastore installed from pip without a version specified.
 
### What did you do?
If possible, provide a recipe for reproducing the error. Try being specific and include code snippets if helpful.

I'm using google-cloud-datastore in a python flask app, which is dockerized. Starting with today our CI tests fail with an `TypeError: Expected str, got unicode`. I traced it back to a new version (1.8.0, before 1.7.3) being available via pip.

### What did you expect to see?

Google Cloud Datastore queries working with Datastore or Datastore Emulator. 
 
### What did you see instead?

No queries or any other requests are possible against Cloud Datastore.

```
E1213 16:11:08.523933100       1 ev_epollex_linux.cc:1482]   Skipping epollex becuase GRPC_LINUX_EPOLL is not defined.
E1213 16:11:08.524041000       1 ev_epoll1_linux.cc:1261]    Skipping epoll1 becuase GRPC_LINUX_EPOLL is not defined.
E1213 16:11:08.524077200       1 ev_epollsig_linux.cc:1761]  Skipping epollsig becuase GRPC_LINUX_EPOLL is not defined.
TypeError: Expected str, got unicode
Exception TypeError: 'Expected str, got unicode' in 'grpc._cython.cygrpc._store_c_metadata' ignored
E1213 16:11:08.528453300       1 call.cc:1001]               validate_metadata: {"created":"@1513181468.528438800","description":"Metadata keys cannot be zero length","file":"src/core/lib/surface/validate_metadata.cc","file_line":66}
ERROR    2017-12-13 16:11:08,529 service.py: 34] something went bad: RetryError(Exception occurred in retry method that was not classified as transient, caused by metadata was invalid: [(u'x-goog-api-client', 'gl-python/2.7.13 gccl/1.4.0 gapic/0.15.3 gax/0.15.16 grpc/1.8.0')])
Traceback (most recent call last):
...
  File "/usr/local/lib/python2.7/dist-packages/google/api_core/page_iterator.py", line 186, in _items_iter
    for page in self._page_iter(increment=False):
  File "/usr/local/lib/python2.7/dist-packages/google/api_core/page_iterator.py", line 217, in _page_iter
    page = self._next_page()
  File "/usr/local/lib/python2.7/dist-packages/google/cloud/datastore/query.py", line 498, in _next_page
    query=query_pb,
  File "/usr/local/lib/python2.7/dist-packages/google/cloud/datastore/_gax.py", line 134, in run_query
    return super(GAPICDatastoreAPI, self).run_query(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/google/cloud/gapic/datastore/v1/datastore_client.py", line 258, in run_query
    return self._run_query(request, options)
  File "/usr/local/lib/python2.7/dist-packages/google/gax/api_callable.py", line 452, in inner
    return api_caller(api_call, this_settings, request)
  File "/usr/local/lib/python2.7/dist-packages/google/gax/api_callable.py", line 438, in base_caller
    return api_call(*args)
  File "/usr/local/lib/python2.7/dist-packages/google/gax/api_callable.py", line 376, in inner
    return a_func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/google/gax/retry.py", line 127, in inner
    ' classified as transient', exception)
RetryError: RetryError(Exception occurred in retry method that was not classified as transient, caused by metadata was invalid: [(u'x-goog-api-client', 'gl-python/2.7.13 gccl/1.4.0 gapic/0.15.3 gax/0.15.16 grpc/1.8.0')])
```

versions:
  * Python 2.7.13
  * grpcio==1.8.0
  * google-cloud-datastore==1.4.0

If i add the explicit requirement of grpcio==1.7.3 to my python requirements the tests succeed.
 

It seems like this one line is key:

```
Exception occurred in retry method that was not classified as transient, caused by metadata was invalid: [(u'x-goog-api-client', 'gl-python/2.7.13 gccl/1.4.0 gapic/0.15.3 gax/0.15.16 grpc/1.8.0')]
```
the user agent string x-google-api-client is a unicode string, not a byte string.

**Comment by mehrdada** [comment] 2017-12-13 16:57
@nathanielmanistaatgoogle likely related to your metadata change?

**Comment by nathanielmanistaatgoogle** [comment] 2017-12-13 17:24
Well, triggered by the metadata change, but not root-caused-by the metadata change. The defect is in... whatever is passing `unicode` values as metadata values; [metadata values must be `str` if the associated key does not end in `-bin` and must be `bytes` if the associated key does end in `-bin`](https://grpc.io/grpc/python/grpc.html#term-metadata). So `unicode` on Python 2.7 is never allowed.

**Comment by r00tat** [comment] 2017-12-13 17:28
@nathanielmanistaatgoogle So this is a bug for google-cloud-datastore?

**Comment by nathanielmanistaatgoogle** [comment] 2017-12-13 17:36
@r00tat: sounds like it to me, yes.

**Comment by r00tat** [comment] 2017-12-13 19:05
@nathanielmanistaatgoogle Can you point me towards the related changes, so I can help the datastore team to find the root of the issue?

**Comment by mehrdada** [comment] 2017-12-13 19:10
"More strict enforcement of type-correctness of metadata values. (#13672)" is the relevant item in the release notes.

**Comment by mehrdada** [comment] 2017-12-13 19:18
(FYI, I have temporarily disabled the 1.8.0 on PyPI while they fix or pin their dependencies)

**Comment by r00tat** [comment] 2017-12-13 19:19
Great! There is also the matching [issue on google-cloud-python](https://github.com/GoogleCloudPlatform/google-cloud-python/issues/4581).

Should we keep this issue open or close it as it is being fixed in google-cloud-python?

**Comment by mehrdada** [comment] 2017-12-13 19:22
Let's leave it open for a bit so duplicate ones would not be created. In the meantime I am re-releasing the "1.8.0" package on PyPI under "1.8.0-rc3", before enabling them as 1.8.0 again.

**Comment by jonparrott** [comment] 2017-12-13 19:23
@nathanielmanistaatgoogle can you clear something up for me?

On Py3 it should be `(bytes, str)` and on Py3 it should be `(str, str)`?  If so, that's really unfortunate and will require a `if PY2/PY3` branch in our code.

**Comment by jonparrott** [comment] 2017-12-13 19:24
@mehrdada are you deleting the `1.8.0` release? That's generally a big no-no.

**Comment by mehrdada** [comment] 2017-12-13 19:27
@jonparrott It is slightly unfortunately, but I will reupload the **exact** binary again after they fix the bug or pin the dependency version. The impact should be minimal (I have not sent the official release email yet) and stops the potential bleeding.

**Comment by alex2awesome** [comment] 2017-12-13 19:27
I'm getting this error as well, just coming across this thread. I'm confused about the cause — but I'll read the links you posted @nathanielmanistaatgoogle. In the meantime, what do you recommend doing? What is the timeline for a fix?

**Comment by r00tat** [comment] 2017-12-13 19:30
@alex2awesome Workaround is to reinstall your dependcies or run a `pip install` with the explicit grpcio version.

```
pip install --upgrade grpcio==1.7.3
```

**Comment by alex2awesome** [comment] 2017-12-13 19:32
Thanks @r00tat!! And this is an issue cause by unicode in an Entity's `key` values? That's just about the only place I can think of that unicode could creep in in my case — all my data is `int`s or `float`s. Or is unicode _anywhere_ in a datastore Entity?

**Comment by r00tat** [comment] 2017-12-13 19:36
The issue is related to the implementation of google-cloud-datastore or other google-cloud-python libraries. To be more specific the issue is related to the encoding of metadata in grpc requests, so not to your data being saved to datastore.

**Comment by mehrdada** [comment] 2017-12-13 19:46
@jonparrott re the question you asked @nathanielmanistaatgoogle, I leave the official guidance to him, but gRPC internally uses something like https://github.com/grpc/grpc/blob/master/src/python/grpcio/grpc/_common.py#L64

**Comment by r00tat** [comment] 2017-12-13 19:50
Maybe I'm getting this wrong, but shouldn't [_encode](https://github.com/grpc/grpc/pull/13672/files#diff-b04c749392fba3fdec9f89feed9c7811R29) being called on [line 36 of metadata.pyx.pxi](https://github.com/grpc/grpc/pull/13672/files#diff-5f94dacb2158bd65765e5c9225b4dc73R36) convert unicode to str?

```
+cdef bytes _encode(str native_string_or_none):
 +  if native_string_or_none is None:
 +    return b''
 +  elif isinstance(native_string_or_none, (bytes,)):
 +    return <bytes>native_string_or_none
 +  elif isinstance(native_string_or_none, (unicode,)):
 +    return native_string_or_none.encode('ascii')
 +  else:
 +    raise TypeError('Expected str, not {}'.format(type(native_string_or_none)))
```

**Comment by nathanielmanistaatgoogle** [comment] 2017-12-13 20:28
@r00tat: Note the `str` on the first line of what you quoted - I believe _that's_ what's doing the check and raising a `TypeError` (and the latter four lines of what you quoted are unreachable code that I should clean up...).

**Comment by nathanielmanistaatgoogle** [comment] 2017-12-13 20:33
@dhermes: yep, `str`, a so-called "native string" that is equivalent to `bytes` on Python 2 and `unicode` on Python 3. All keys should be `str` instances and all values should be either `str` instances or `bytes` instances depending on the respective absence or presence of the `-bin` suffix on the associated key.

**Comment by dhermes** [comment] 2017-12-13 20:42
@nathanielmanistaatgoogle I don't want to be a wet blanket, but **requiring** a string literal (i.e. `str`) for the first item in the pair seems like a bad API. Consider that in Python 2, string equality across `str` and `unicode` "just works". Throw in the fact that you **don't allow** a Python 2 string literal for the 2nd item (i.e. since it's `bytes`) makes it even worse.

**Comment by jonparrott** [comment] 2017-12-13 20:49
Yeah this is confusing, so ignoring the whole `*-bin` prefix you're telling me that on Python 2 we need to pass in `b'...'` for keys and values and on Python 3 it needs to be `u'...'`?

**Comment by dhermes** [comment] 2017-12-13 21:02
If I may clarify @jonparrott, this is what I understand:

## Python 2

```
Key                     | Value
------------------------+-----------------------
b'key'     or 'key'     | u'only-unicode'
b'key-bin' or 'key-bin' | b'bytes'        or 'literal-still-bytes'
```

## Python 3

```
Key                     | Value
------------------------+------------------------------------------
u'key'     or 'key'     | u'unicode'    or 'literal-still-unicode'
u'key-bin' or 'key-bin' | b'only-bytes'
```

**Comment by nathanielmanistaatgoogle** [comment] 2017-12-13 21:39
@dhermes: I think your upper-left corner is in error; I think the table (thanks for making it; visual aids are always such a treat) should be

## Python 2

```
Key                     | Value
------------------------+-----------------------
b'key'     or 'key'     | 'literal-still-bytes'
b'key-bin' or 'key-bin' | b'bytes'        or 'literal-still-bytes'
```

## Python 3

```
Key                     | Value
------------------------+------------------------------------------
u'key'     or 'key'     | u'unicode'    or 'literal-still-unicode'
u'key-bin' or 'key-bin' | b'only-bytes'
```

**Comment by jonparrott** [comment] 2017-12-13 21:43
So, this seems super silly to me. Why different types in Python 2 and 3? If we're going to be strict about types, please be strict on *text string* vs *byte string*. 

We can workaround this in our client library code, but it literally requires a branch on python 2 vs python 3 and that makes me sad.

**Comment by dhermes** [comment] 2017-12-13 22:06
Yes, the **keys** we'll probably always control in libraries but the values will come from users. In some cases, the value will be "text string" (i.e. `unicode`) because it comes as a `string` field of a protobuf message (which is defined to be `utf-8`). See one of our examples above, `u'projects/.../databases/(default)'`, which is **invalid** in Python 2.7 since not a string literal ([e.g. 1][1], [e.g. 2][2]).

[1]: https://github.com/googleapis/googleapis/blob/0c7f6f05a6c5e9b2768bc5b592ef2e18fe48bffc/google/firestore/v1beta1/document.proto#L39
[2]: https://github.com/googleapis/googleapis/blob/0c7f6f05a6c5e9b2768bc5b592ef2e18fe48bffc/google/firestore/v1beta1/document.proto#L119

**Comment by nathanielmanistaatgoogle** [comment] 2017-12-13 22:19
I can think of at least three things that influenced the current shape of the API:
* There was a forecast that authors were going to be writing a lot of string literal values for both metadata keys and metadata values and that idiomatic code wouldn't be cluttered with `b` and `u` prefixes.
* There's just one precise metadata type (as complex as it is) and authors can rely on the fact that (holding Python interpreter version constant) **metadata comes out of gRPC Python with exactly the type with which it was passed to gRPC Python**.
* keys are highly restricted (ASCII alphanumeric plus dashes, underscores, periods and... that might be it) and values are also restricted to a subset of ASCII (unless the associated key ends with `-bin`, in which case the value is arbitrary binary `bytes` and can be any content), so `unicode` doesn't seem to present as a useful component type because there's nothing that's representable in non-ASCII `unicode` that's useful as a part of gRPC metadata.

I'd really appreciate hearing your reactions to those points as users-of-gRPC Python:
* How often are you writing your metadata keys as literal values in your source code as opposed to getting them from somewhere else? How about your values? Are `u` and `b` prefixes cosmetically unattractive in your code or just an accepted part of developing for both language versions?
* If (for the moment assuming Python 2) you were allowed to pass a `unicode` metadata value on one side of an RPC and on the other side of the RPC the value was passed to you as `str`-`bytes`, would that be weird? Would that lead to bugs?

In the Beta API all metadata was just `bytes`. Was that better than the 1.0-and-later semantics only just now being enforced? Beyond what you've already said, what would you _like_ to see?

**Comment by dhermes** [comment] 2017-12-13 22:25
The distinction between bytes and unicode is just as relevant (if not more) than using a string literal or not. To be idiomatic in Python 2, a user can just `from __future__ import unicode_literals`. There is no avoiding `b'...'` or `u'...'` to make the distinction.

RE: "on the other side of the RPC", we **never** consume the metadata on the other side

Here are all the places we form keys (that I can currently find), they are all string literals:

- [`datastore`][1]

[1]: https://github.com/GoogleCloudPlatform/google-cloud-python/blob/460b6060b2ecd7e5f91c12745155e516e548801c/datastore/google/cloud/datastore/_gax.py#L41-L43

**Comment by mehrdada** [comment] 2017-12-13 22:30
@dhermes @nathanielmanistaatgoogle  Re your last point "on the other side of RPC", I'd like to point out that metadata can also be consumed by interceptors within the client side of the application.

**Comment by jonparrott** [comment] 2017-12-13 22:37
> How often are you writing your metadata keys as literal values in your source code as opposed to getting them from somewhere else? How about your values?

In client libraries and samples, almost *never* are we manually specifying metadata. It's all determined by our wrapping code (which injects our user-agent string) or derived from some other values (like in the case above where it puts in a resource prefix based on project ID).

> Are u and b prefixes cosmetically unattractive in your code or just an accepted part of developing for both language versions?

I don't care. Our house style for samples is to use `u` prefixes and move on with our lives. 

> If (for the moment assuming Python 2) you were allowed to pass a unicode metadata value on one side of an RPC and on the other side of the RPC the value was passed to you as str-bytes, would that be weird? Would that lead to bugs?

I don't typical consume the other side, but if we're following TCP guidelines in being liberal in what we accept and conservative in what we send, that seems *fine*.

> Beyond what you've already said, what would you like to see?

Just consistent types between Python 2 and 3. If I could express it using type annotations I would be totally fine with *any* of the following:

```
metadata: Tuple[Str, Bytes]
metadata: Tuple[Bytes, Bytes]
metadata: Tuple[Str, Str]
metadata: Tuple[Bytes, Bytes]
```

I'm not happy with the state of things now, which basically boils down to:

```
KeyType = Str if PY3 else Bytes
ValueType = Str if PY3 else Bytes
metadata: Tuple[KeyType, ValueType]
```

**Comment by jonparrott** [comment] 2017-12-13 22:40
> an also be consumed by interceptors within the client side of the application.

We have interceptors now?

**Comment by mehrdada** [comment] 2017-12-13 22:40
Yes, in, 1.8.0 (rc3).

**Comment by prometheanfire** [comment] 2017-12-14 19:13
@mehrdada removal of 1.8.0 just broke openstack gate :(

**Comment by mehrdada** [comment] 2017-12-14 19:17
@prometheanfire We are pushing a 1.8.1 as soon as it gets off the test and build queue and 1.8.0 will go up with it.

**Comment by jonparrott** [comment] 2017-12-14 19:19
@mehrdada this issue isn't resolved, so why are we republishing `1.8.0`?

**Comment by mehrdada** [comment] 2017-12-14 19:20
@jonparrott A patch by @nathanielmanistaatgoogle will resolve this in 1.8.1 so it should be safe to push 1.8.0 with it, I think, no?

**Comment by jonparrott** [comment] 2017-12-14 19:21
Yeah - I just never saw the patch (or a response to my comment above). :)

**Comment by mehrdada** [comment] 2017-12-14 19:22
https://github.com/grpc/grpc/pull/13784

**Comment by jonparrott** [comment] 2017-12-14 19:22
Cool, carry on. :)

**Comment by mehrdada** [comment] 2017-12-15 02:43
1.8.1 is out on PyPI and reverts the metadata behavior to pre-1.8. I am closing the issue now.

(PyPI does not let me reupload even the identical file I have as 1.8.0 so there's a hole there unfortunately)

**Closed by mehrdada** 2017-12-15 02:43 UTC
Labels: area/core, kind/bug, lang/Python, priority/P1
