### ISSUE TITLE
FLAKE: //test/cpp/common:timer_test on Windows

### ISSUE THREAD

**Issue by markdroth** [grpc/grpc#20436] opened 2019-10-02 14:41 UTC
https://source.cloud.google.com/results/invocations/cf8ca0e9-cb76-4fc7-9030-6896c1b6f190/targets/%2F%2Ftest%2Fcpp%2Fcommon:timer_test/log

```
Executing tests from //test/cpp/common:timer_test
-----------------------------------------------------------------------------
D1001 22:21:14.635000000 15236 test/core/util/test_config.cc:384] test slowdown factor: sanitizer=1, fixture=1, poller=1, total=1
[==========] Running 4 tests from 1 test suite.
[----------] Global test environment set-up.
[----------] 4 tests from TimerTest
[ RUN      ] TimerTest.NoTimers
D1001 22:21:14.643000000 15236 src/core/ext/filters/client_channel/resolver/dns/c_ares/dns_resolver_ares.cc:485] Using ares dns resolver
E1001 22:21:16.145000000 15236 test/cpp/common/timer_test.cc:72] assertion failed: wakeups == 1 || wakeups == 2
Abort handler called.
*** 0: 00007FF6E0FAB4F9  - 0000000000000000
*** 1: 00007FF6E0FAB987  - 0000000000000000
*** 2: 00007FFB66BBD09B raise - 00007FFB66BBCEC0
*** 3: 00007FFB66BBE131 abort - 00007FFB66BBE100
*** 4: 00007FF6E0F92671 abort - 00007FFB66BBE100
*** 5: 00007FF6E115B6BC abort - 00007FFB66BBE100
*** 6: 00007FF6E115B462 abort - 00007FFB66BBE100
*** 7: 00007FF6E114575A abort - 00007FFB66BBE100
*** 8: 00007FF6E1146185 abort - 00007FFB66BBE100
*** 9: 00007FF6E1146827 abort - 00007FFB66BBE100
*** 10: 00007FF6E114CFA2 abort - 00007FFB66BBE100
*** 11: 00007FF6E115B86C abort - 00007FFB66BBE100
*** 12: 00007FF6E115B652 abort - 00007FFB66BBE100
*** 13: 00007FF6E1146E44 abort - 00007FFB66BBE100
*** 14: 00007FF6E0F95021 abort - 00007FFB66BBE100
*** 15: 00007FF6E0F930EE abort - 00007FFB66BBE100
*** 16: 00007FF6E1195389 abort - 00007FFB66BBE100
*** 17: 00007FFB6CE24034 BaseThreadInitThunk - 00007FFB6CE24020
*** 18: 00007FFB77763691 RtlUserThreadStart - 00007FFB77763670
```

**Comment by jtattermusch** [comment] 2019-10-03 05:59
CC @jtattermusch

**Comment by jtattermusch** [comment] 2019-10-04 06:09
Some extra insights:
- this is not a new breakage, we just started running more windows tests due to enabling Windows bazel RBE tests (vast majority of tests are passing, but a few need to be fixed).
- I ran the timer_test manually a few times and I see a strange pattern. In some cases I get wakeups == 1 (tests passes) and in other cases I get wakeup = large number (>200). Something odd is going on.
https://github.com/grpc/grpc/blob/9b288b20c4e56f77e38d08b54881ece953f7c7e3/test/cpp/common/timer_test.cc#L72

Repro:
`~/bazel-0.29.1-windows-x86_64.exe test //test/cpp/common:timer_test`

**Comment by jtattermusch** [comment] 2019-10-04 07:42
I added some extra logs and the timer manager seems to do a series of very short
grpc_cv_wait (which is something that doesn't seem to be happening on linux) - this is probably how a large number of wakeups gets accumulated.
```
[ RUN      ] TimerTest.NoTimers                                                                                                                        
D1004 00:35:16.546000000 20120 src/core/ext/filters/client_channel/resolver/dns/c_ares/dns_resolver_ares.cc:485] Using ares dns resolver
E1004 00:35:16.554000000 20120 test/cpp/common/timer_test.cc:68] wakeups_start: 0                                                                              
E1004 00:35:16.554000000 19832 src/core/lib/iomgr/timer_manager.cc:188] sleep for a 1001 milliseconds                                                          
E1004 00:35:17.554000000 19832 src/core/lib/iomgr/timer_manager.cc:188] sleep for a 1 milliseconds                                                             
E1004 00:35:17.555000000 19832 src/core/lib/iomgr/timer_manager.cc:188] sleep for a 1 milliseconds                                                             
E1004 00:35:17.555000000 19832 src/core/lib/iomgr/timer_manager.cc:188] sleep for a 1 milliseconds                                                             
E1004 00:35:17.555000000 19832 src/core/lib/iomgr/timer_manager.cc:188] sleep for a 1001 milliseconds                                                          
E1004 00:35:18.054000000 20120 test/cpp/common/timer_test.cc:74] wakeups: 4                                                                                    
E1004 00:35:18.054000000 20120 test/cpp/common/timer_test.cc:75] assertion failed: wakeups == 1 \|\| wakeups == 2
--
```

**Comment by jtattermusch** [comment] 2019-10-04 08:21
The problem seems to be that:
1. timer_check returns the next value to wait for
2. wait_until  is supposed to wait until that time, but wakes up a little bit earlier (~a few millis)
3. the "next" time still hasn't elapsed so timer_check keeps returning the same value
4. wait_until keeps being run in what's basically a busy loop until "next" finally elapses at which point the next 1second sleep is scheduled again.

```
I1004 00:58:07.782000000 20852 src/core/lib/iomgr/timer_generic.cc:738] TIMER CHECK END: r=1; next=1015                                                       
E1004 00:58:07.782000000 20852 src/core/lib/iomgr/timer_manager.cc:188] sleep for a 1001 milliseconds (next: 1015)                                            
I1004 00:58:08.769000000 20852 src/core/lib/iomgr/timer_manager.cc:206] wait ended: was_timed:1 kicked:0                                                      
I1004 00:58:08.769000000 20852 src/core/lib/iomgr/timer_generic.cc:715] TIMER CHECK BEGIN: now=1013 next=9223372036854775807 tls_min=6 glob_min=1015          
I1004 00:58:08.769000000 20852 src/core/lib/iomgr/timer_generic.cc:738] TIMER CHECK END: r=1; next=1015                                                       
E1004 00:58:08.770000000 20852 src/core/lib/iomgr/timer_manager.cc:188] sleep for a 2 milliseconds (next: 1015)                                               
I1004 00:58:08.770000000 20852 src/core/lib/iomgr/timer_manager.cc:206] wait ended: was_timed:1 kicked:0                                                      
I1004 00:58:08.770000000 20852 src/core/lib/iomgr/timer_generic.cc:695] TIMER CHECK SKIP: now=1014 min_timer=1015                                             
E1004 00:58:08.770000000 20852 src/core/lib/iomgr/timer_manager.cc:188] sleep for a 1 milliseconds (next: 1015)                                               
I1004 00:58:08.770000000 20852 src/core/lib/iomgr/timer_manager.cc:206] wait ended: was_timed:1 kicked:0                                                      
I1004 00:58:08.771000000 20852 src/core/lib/iomgr/timer_generic.cc:695] TIMER CHECK SKIP: now=1014 min_timer=1015                                             
E1004 00:58:08.771000000 20852 src/core/lib/iomgr/timer_manager.cc:188] sleep for a 1 milliseconds (next: 1015)                                               
I1004 00:58:08.771000000 20852 src/core/lib/iomgr/timer_manager.cc:206] wait ended: was_timed:1 kicked:0                                                      
I1004 00:58:08.771000000 20852 src/core/lib/iomgr/timer_generic.cc:715] TIMER CHECK BEGIN: now=1015 next=9223372036854775807 tls_min=1015 glob_min=1015
```

https://github.com/grpc/grpc/blob/9b288b20c4e56f77e38d08b54881ece953f7c7e3/src/core/lib/iomgr/timer_manager.cc#L235

https://github.com/grpc/grpc/blob/9b288b20c4e56f77e38d08b54881ece953f7c7e3/src/core/lib/iomgr/timer_generic.cc#L695

**Comment by jtattermusch** [comment] 2019-10-04 08:23
Maybe related: https://github.com/grpc/grpc/issues/19947

**Comment by jtattermusch** [comment] 2019-10-04 08:24
@rmstar  will you be able to look into this? The test is failing often on master and it seems to be an actual bug.

**Comment by rmstar** [comment] 2019-10-04 18:44
Reassigning to owner to timer code @AspirinSJL

**Comment by jtattermusch** [comment] 2019-10-07 05:50
@AspirinSJL  this flake has a very high occurrence (~50%?), can you take a look?

**Comment by AspirinSJL** [comment] 2019-10-07 17:21
Is this reproducible on Linux?

**Comment by rmstar** [comment] 2019-10-07 21:08
@AspirinSJL AFAIK this has not been seen on Linux. This is a timer bug on Windows.

**Comment by jtattermusch** [comment] 2019-10-16 12:29
@rmstam @guantaol  Friendly ping. This has a high failure rate on Bazel RBE Windows tests and it also seems that something is wrong with our timer_manager code on windows (see my analysis above).

**Comment by guantaol** [comment] 2019-10-17 01:26
@jtattermusch In my check, Windows SleepConditionVariableCS also suffers from the spurious wakeup issue: https://docs.microsoft.com/en-us/windows/win32/api/synchapi/nf-synchapi-sleepconditionvariablecs#remarks. If I understand timer_manager.cc correctly, there is no predicate to exclude the spurious wakeup. So it looks that the assumption on g_wakeups is incorrect (it does not count the spurious wakeup of condition variables): https://github.com/grpc/grpc/blob/master/test/cpp/common/timer_test.cc#L69

**Comment by jtattermusch** [comment] 2019-10-17 06:11
@guantaol  I might be wrong, but IMHO the problem is not actually spurious wake-up.
A spurious wakeup would mean that we from time to time (= rarely enough) wake up spuriously and if nothing happened, we would go to sleep. In this case what we're observing in the test is that we wake up one time quantum too soon and because of a combination how timestamp rounding works and what arg we pass to the next sleep iteration, we just end up spinning for the rest of the time quantum (and we manage to check at least for a few hundred times, as observed by the test).

- I can totally imagine this would lead to performance problems under load (we don't know how often we spin like this). Therefore I think this should be investigated properly.
- I'm not an expert but I thought the  point of the g_wakeups  count test is to make sure that timer actually sleeps when it is supposed to sleep (= we're not spinning by accident, which is exactly what's happening). So I think the test is failing for a good reason.

**Comment by guantaol** [comment] 2019-10-23 01:04
I have an explanation for the extra wakeup on Windows, and it is related to how gpr_now(GPR_CLOCK_REALTIME) is implemented on Windows: https://github.com/grpc/grpc/blob/master/src/core/lib/gpr/time_windows.cc#L52. Since _ftime_s() only gives us the current time in a granularity of millisecond, and gpr_cv_wait() will call gpr_now(GPR_CLOCK_REALTIME) twice on Windows when calculating the relative deadline, in the worst case, the actual sleep time will be off by up to two milliseconds due to the rounding issues. In this case, we will have the extra wakeup from gpr_cv_wait() before the timer actually fires.

I agree g_wakeups is a good monitoring metric to avoid excessive wakeup in timer threads. However, its assumption in the test is too strict given the existing implementation of time APIs on Windows.

**Comment by jtattermusch** [comment] 2019-10-23 06:13
> I have an explanation for the extra wakeup on Windows, and it is related to how gpr_now(GPR_CLOCK_REALTIME) is implemented on Windows: https://github.com/grpc/grpc/blob/master/src/core/lib/gpr/time_windows.cc#L52. Since _ftime_s() only gives us the current time in a granularity of millisecond, and gpr_cv_wait() will call gpr_now(GPR_CLOCK_REALTIME) twice on Windows when calculating the relative deadline, in the worst case, the actual sleep time will be off by up to two milliseconds due to the rounding issues. In this case, we will have the extra wakeup from gpr_cv_wait() before the timer actually fires.
> 
> I agree g_wakeups is a good monitoring metric to avoid excessive wakeup in timer threads. However, its assumption in the test is too strict given the existing implementation of time APIs on Windows.

Thanks for the analysis. Yes, this definitely has to do with the windows timing code and the millisecond-only precision. But there's still seems to be a problem - there is not only "one or two " extra wakeups (which would be "fine"), when you add a log message to the test, you regularly get g_wakeups being a rather large number - I regularly get wakeup >200. (which means that the timer code just keeps spinning for those one or two milliseconds of remanining time and this very likely happens not just in the test, but in real applications as well). And it can be safely argued that if our timer manager code ends up spinning often, it can have bad performance consequences (and perhaps worse).

**Comment by rmstar** [comment] 2019-10-23 18:20
> And it can be safely argued that if our timer manager code ends up spinning often, it can have bad performance consequences (and perhaps worse).

This is correct. Please see internal bug 68708872 for possible consequences of timer thread spinning.

**Comment by guantaol** [comment] 2019-11-06 01:32
> > I have an explanation for the extra wakeup on Windows, and it is related to how gpr_now(GPR_CLOCK_REALTIME) is implemented on Windows: https://github.com/grpc/grpc/blob/master/src/core/lib/gpr/time_windows.cc#L52. Since _ftime_s() only gives us the current time in a granularity of millisecond, and gpr_cv_wait() will call gpr_now(GPR_CLOCK_REALTIME) twice on Windows when calculating the relative deadline, in the worst case, the actual sleep time will be off by up to two milliseconds due to the rounding issues. In this case, we will have the extra wakeup from gpr_cv_wait() before the timer actually fires.
> > I agree g_wakeups is a good monitoring metric to avoid excessive wakeup in timer threads. However, its assumption in the test is too strict given the existing implementation of time APIs on Windows.
> 
> Thanks for the analysis. Yes, this definitely has to do with the windows timing code and the millisecond-only precision. But there's still seems to be a problem - there is not only "one or two " extra wakeups (which would be "fine"), when you add a log message to the test, you regularly get g_wakeups being a rather large number - I regularly get wakeup >200. (which means that the timer code just keeps spinning for those one or two milliseconds of remanining time and this very likely happens not just in the test, but in real applications as well). And it can be safely argued that if our timer manager code ends up spinning often, it can have bad performance consequences (and perhaps worse).

I totally agree that the excessive wakeups of timer manager will lead to performance regression, however, do we have a measurement of how often this will happen and the real impact of these extra wakeups in a Windows application? I would like to fix this issue, but I do not think the fix should happen in timer_manager for two reasons:

1. Unless we change the implementation of time APIs on Windows (which is out of my expertise), I do not see a solution to eliminate the extra wakeups. If we sleep for a few extra milliseconds in gpr_cv_wait to accommodate the rounding issue on Windows, then it is sacrificing the performance on other platforms.
2. The timer manager will soon be replaced by the EventManager on all platforms. Thus, at this point, I do not think it is worthwhile to make any significant changes in the implementation of timer manager.

**Comment by jtattermusch** [comment] 2019-11-06 15:03
@guantaol 

so there's two problems:
- we have a test that's been highly flaky on master for a while and that's distracting all the collaborators and negatively affecting developer velocity. That test needs to be fixed one way or another ASAP (both the code and the test is owned by C core team, so you guys need to fix it).

- the reason why the test fails seems to be fairly well understood now and we agreed that there's potential for this causing a performance regression. We don't have a measurement that confirms that's a real problem but we still need to be careful. 

Can you discuss this problem in the C-core team standup and come up with a resolution?

**Comment by jtattermusch** [comment] 2019-11-06 15:21
I created https://github.com/grpc/grpc/pull/20956 to silence the flake.

**Comment by guantaol** [comment] 2019-11-07 18:25
> @guantaol
> 
> so there's two problems:
> 
> * we have a test that's been highly flaky on master for a while and that's distracting all the collaborators and negatively affecting developer velocity. That test needs to be fixed one way or another ASAP (both the code and the test is owned by C core team, so you guys need to fix it).
> * the reason why the test fails seems to be fairly well understood now and we agreed that there's potential for this causing a performance regression. We don't have a measurement that confirms that's a real problem but we still need to be careful.
> 
> Can you discuss this problem in the C-core team standup and come up with a resolution?

Thanks for the fix! We discussed this within the c-core team, and we agree that #20956 is probably the best solution we could achieve at the moment.

**Closed** 2019-11-08 06:48 UTC
Labels: infra/BUILDPONY, kind/bug, lang/c++, platform/Windows, priority/P1
