### ISSUE TITLE
CMake build under Apple silicon is failed for 1.35.0

### ISSUE THREAD

**Issue by Dmitry-Nikishov** [grpc/grpc#25226] opened 2021-01-21 10:56 UTC
### What version of gRPC and what language are you using?
1.35.0

### What operating system (Linux, Windows,...) and version?
MacOs BigSur

### What runtime / compiler are you using (e.g. python version or version of gcc)
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++

### What did you do?
Set the only one variable for CMake
CMAKE_OSX_ARCHITECTURES=x86_64

### What did you expect to see?
100% of targets built

### What did you see instead?
[ 92%] Building CXX object third_party/abseil-cpp/absl/random/CMakeFiles/absl_random_internal_randen_hwaes_impl.dir/internal/randen_hwaes.cc.o
error: unknown target CPU 'armv8-a+crypto'
note: valid target CPU values are: nocona, core2, penryn, bonnell, atom,
      silvermont, slm, goldmont, goldmont-plus, tremont, nehalem, corei7,
      westmere, sandybridge, corei7-avx, ivybridge, core-avx-i, haswell,
      core-avx2, broadwell, skylake, skylake-avx512, skx, cascadelake,
      cooperlake, cannonlake, icelake-client, icelake-server, tigerlake, knl,
      knm, k8, athlon64, athlon-fx, opteron, k8-sse3, athlon64-sse3,
      opteron-sse3, amdfam10, barcelona, btver1, btver2, bdver1, bdver2, bdver3,
      bdver4, znver1, znver2, x86-64
make[2]: *** [third_party/abseil-cpp/absl/random/CMakeFiles/absl_random_internal_randen_hwaes_impl.dir/internal/randen_hwaes.cc.o] Error 1
make[1]: *** [third_party/abseil-cpp/absl/random/CMakeFiles/absl_random_internal_randen_hwaes_impl.dir/all] Error 2

**Comment by drfloob** [comment] 2021-01-21 18:19
Duplicate of #23325

Currently we don't provide support for Apple Silicon (ARM on mac).

**Closed by drfloob** 2021-01-21 18:19 UTC
Labels: kind/bug, priority/P2
