### ISSUE TITLE
gRPC Python 1.6.0 Library Incompatibility with `fork()`

### ISSUE THREAD

**Issue by akashgangil** [grpc/grpc#12455] opened 2017-09-08 19:21 UTC
Please answer these questions before submitting your issue. 
 
### Should this be an issue in the gRPC issue tracker?
 
Create new issues for bugs and feature requests. An issue needs to be actionable. General gRPC discussions and usage questions belong to:
- [grpc.io mailing list](https://groups.google.com/forum/#!forum/grpc-io)
- [StackOverflow, with `grpc` tag](http://stackoverflow.com/questions/tagged/grpc)
 
*Please don't double post your questions in more locations; we are monitoring both channels, and the time spent de-duplicating questions is better spent answering more user questions.*
 
### What version of gRPC and what language are you using?
 1.6.0
 
### What operating system (Linux, Windows, …) and version?
 Linux
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
 python3.4
 
### What did you do?
If possible, provide a recipe for reproducing the error. Try being specific and include code snippets if helpful.
Run the hello world python grpc server and a python client
 
### What did you expect to see?
 Successful response from the server
 
### What did you see instead?
 2017-09-08 04:22:21,853 ERROR:Unable to connect to server
Traceback (most recent call last):
  File "bazel-out/local-fastbuild/bin/server/tmp_pyc/server.py", line 414, in getValue
  File "/usr/local/lib/python3.4/dist-packages/grpc/_channel.py", line 492, in __call__
    return _end_unary_response_blocking(state, call, False, deadline)
  File "/usr/local/lib/python3.4/dist-packages/grpc/_channel.py", line 440, in _end_unary_response_blocking
    raise _Rendezvous(state, None, None, deadline)
grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with (StatusCode.UNAVAILABLE, Endpoint read failed)>

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).
 This exact same client and server work with 1.4.0

**Comment by dnarc** [comment] 2017-09-11 21:15
I have a very similar problem that cropped up in the last few weeks on a Ubuntu 14.04 under python3 that was upgraded to grpcio 1.6 from grpcio 1.4 by pip3. The grpc server is still binding to the assigned port but client calls seem to never get accept()ed and the client hangs. I downgraded to the grpcio 1.4 package in python3 and my code resumed working.

**Comment by akashgangil** [comment] 2017-09-13 04:04
@nathanielmanistaatgoogle Could you please look at this one? It seems to be a P0 blocker for the release.

**Comment by nathanielmanistaatgoogle** [comment] 2017-09-13 04:10
This is very weird and concerning. Are you able to run with the GRPC_TRACE=all and GRPC_VERBOSITY=DEBUG environment variables set? Do you see possibly-significant differences between what they print when you run with each version?

**Comment by dnarc** [comment] 2017-09-13 04:25
Nathan, I'm just about to go to bed but I will do this tomorrow. I did run
with those two vars set when trying to debug my code with the 1.6 release
and it was just fast cycling through the event loop.

**Comment by dnarc** [comment] 2017-09-13 04:26
BTW, I think this is the same bug:

https://github.com/grpc/grpc/issues/12489

**Comment by akashgangil** [comment] 2017-09-13 04:40
I can confirm what @dnarc  said as I was running my grpc server in a different process too using the multiprocessing module.

**Comment by speedplane** [comment] 2017-09-13 15:54
Another bug report that is likely related: https://github.com/GoogleCloudPlatform/google-cloud-python/issues/3946

**Comment by dnarc** [comment] 2017-09-14 18:20
I'm pretty sure the issue is on the client/stub side when being called within a Future context. That's when I can most consistently reproduce the bug (Python 3.4, Ubuntu 14.04). 

I've added logs from a run from a non-working call using v1.6 versus a working call using v1.4.

I cut if from the logs but your libevent/libev selected epoll() as the eventing library if it matters.


[log.1-4-client.txt](https://github.com/grpc/grpc/files/1304048/log.1-4-client.txt)
[log.1-6-grpc-client.txt](https://github.com/grpc/grpc/files/1304007/log.1-6-grpc-client.txt)

**Comment by dnarc** [comment] 2017-09-14 23:54
Tried running with current 1.7.x, same behaviour. Also tried running with poll() instead of epoll() and saw no difference.

**Comment by dnarc** [comment] 2017-09-15 10:17
'git bisect' puts the blame on this commit:

ee4b14521380f8c387c27f4cd351565d0afa3d61

**Comment by kpayson64** [comment] 2017-09-15 16:08
The multiprocessing module uses fork() under the hood.  gRPC was not designed to work with fork, and if it was working before it was purely coincidental.

**Comment by dnarc** [comment] 2017-09-15 17:02
I can't speak for the other error cases linked in this bug report, but I am
using concurrent.futures rather than multiprocessing (although c.f forks as
well) and the grpc call entirely happens within the spawned process. This
is not a supported use case?

**Comment by burcarpat** [comment] 2017-09-15 18:58
Seems like we are observing the same issue.

We encountered this issue while trying to use `google-cloud-spanner==0.27.0`.  I have a short snippet (~50 lines) that reproduces the issue in a clean virtualenv on macOS Sierra 10.12.6 and Python 3.6.2 if there is interest (Though, it will require having a Spanner instance to run).  **The snippet in question also uses Python's standard multiprocessing module.**  I verified that if I pin the grpcio version to `grpcio==1.4.0` in the same clean virtualenv, things work fine.

Independently, I also reproduced the issue in our core codebase which is running Python 3.6.0 on both Google Compute Engine and Google Container Engine using standard Ubuntu images.

This is breaking a lot of stuff for us so I am more than happy to do whatever is needed to help solve the issue.

_Note: I am also very interested in understanding whether grpc, and thus all google-cloud libraries using grpc, are supposed to work with Python's standard multiprocessing or not._

**Comment by kpayson64** [comment] 2017-09-18 17:20
We intend to support ```fork()``` going forward for the 1.7 release.

The 1.6 release introduced more background threads at the c-level, which are not carried over to child processes after the fork() call.

In the interim,  pinning ```grpcio==1.4.0``` is the best workaround.

**Comment by lukesneeringer** [comment] 2017-09-18 22:04
Note: I am updating all libraries to pin to `< 1.6dev` for now.

**Comment by dnarc** [comment] 2017-09-19 17:31
OK, the current grpcio package in PyPi is still 1.6.

**Comment by lukesneeringer** [comment] 2017-09-19 21:56
Correct; I updated [google-gax](https://github.com/googleapis/gax-python) to require < 1.6, though.

**Comment by nathanielmanistaatgoogle** [comment] 2017-11-01 17:45
@kpayson64: are we sufficiently satisfied with the improvements in 1.7.0-and-later that we should close this issue with the resolution "1.6.x was what it was"?

**Comment by kpayson64** [comment] 2017-11-01 17:47
Yes, lets close this.  Client libraries should have been updated to 1.7 as well.

**Closed by kpayson64** 2017-11-01 17:47 UTC
Labels: kind/bug, lang/Python

**Comment by katbusch** [comment] 2017-11-01 21:14
I just upgraded to 1.7 and am still seeing an issue with multiprocessing.  It works on 1.4

**Comment by kpayson64** [comment] 2017-11-01 21:18
@katbusch 
Can you share a broken example?  Arbitrary forking behavior isn't supported, and maybe there is a way to restructure things to get around the issue.

**Comment by katbusch** [comment] 2017-11-01 21:22
Will take me a moment to test an example minimal enough to post but the general idea is

```
pool = multiprocessing.Pool(initializer={initializer calls grpc.insecure_channel}).
pool.map(fn that sends messages over channel)
```

**Comment by kpayson64** [comment] 2017-11-01 21:37
I just quickly created the following modification on 1.7 helloworld example:

```
import grpc
import multiprocessing

import helloworld_pb2
import helloworld_pb2_grpc

stub = None

def init_stub():
  global stub
  channel = grpc.insecure_channel('localhost:50051')
  stub = helloworld_pb2_grpc.GreeterStub(channel)

def run(unused_var):
  response = stub.SayHello(helloworld_pb2.HelloRequest(name='you'))
  print("Greeter client received: " + response.message)


if __name__ == '__main__':
  p = multiprocessing.Pool(5, initializer=init_stub)
  p.map(run, [1,2,3])
```

Output:
```
Greeter client received: Hello, you!
Greeter client received: Hello, you!
Greeter client received: Hello, you!
```

Which seems to be working as expected.
One thing to be careful to avoid is creating channels before forking.  Hopefully we will have support for that in the future, but it is currently unsupported.

**Comment by katbusch** [comment] 2017-11-02 15:22
I upgraded all my packages instead of just grpcio and it seems to be working now on 1.7 with the use-case I described!  Thanks for your help.

**Comment by katbusch** [comment] 2017-11-30 22:45
Update: I ran into this again, and it turns out that other packages break this as a side effect, perhaps by doing some initialization before the fork.  The libraries are google.cloud.storage and google.cloud.bigquery.

This fails but succeeds if the bigquery line is commented out:

```
import grpc
import echo_pb2, echo_pb2_grpc
from multiprocessing import Pool
from google.cloud import bigquery

stub = None

def init_stub():
    global stub
    channel = grpc.insecure_channel('localhost:50051')
    stub = echo_pb2_grpc.EchoStub(channel)

def run(number):
    response = stub.Echo(echo_pb2.StringMessage(value='hello {}'.format(number)))
    print("Greeter client received: " + response.value)

if __name__ == '__main__':
    pool = Pool(5, initializer=init_stub)
    pool.map(run, [1, 2, 3])
```

**Comment by katbusch** [comment] 2017-12-01 18:57
Another update: I can only reproduce this on mac, not on linux

**Comment by zunger-humu** [comment] 2017-12-22 22:26
I seem to be encountering the same bug using grpcio==1.8.2. Here's a minimal repro using datastore as the example, but you can do it with nearly anything:

```
import multiprocessing

from google.cloud import datastore


def causeTrouble(where: str):
    client = datastore.Client(project='dev-storage-humu', namespace='aquarium')
    client.get(client.key('c', 'aquarium'))
    # The call to get() hangs forever; this line is never reached.
    print('OK')


if __name__ == '__main__':
    # Create a datastore client and do an RPC on it.
    client = datastore.Client(project='dev-storage-humu', namespace='aquarium')
    client.get(client.key('c', 'aquarium'))

    # Kick off a child process while the first client is still in scope.
    process = multiprocessing.Process(target=causeTrouble,
                                      args=['child process'])
    process.start()
```

If the first client goes out of scope before you call Process() (e.g., if you call causeTrouble() from main instead of doing it right there) then this works correctly. (This was tested using Py3.6 on OSX, but I've seen similar issues running on GCP machines as well)

This is a pretty serious obstacle in my case, because I've got a server which uses all sorts of GCP systems, and it needs to fork subprocesses to do expensive asynchronous tasks, which also require those. Short of rearchitecting to pre-fork a bunch of processes before any of grpc is invoked, is there any way to deal with this?

Saying 'grpc is incompatible with fork()' feels like a pretty unsatisfying answer, especially given the lack of non-fork() based parallelism in Python.

**Comment by kpayson64** [comment] 2018-01-10 20:03
@zunger-humu 
The easiest way to deal with this is to wait to create the datastore client until after forking.

The following should work:
```
import multiprocessing

from google.cloud import datastore


def causeTrouble(where: str):
    client = datastore.Client(project='dev-storage-humu', namespace='aquarium')
    client.get(client.key('c', 'aquarium'))
    # The call to get() hangs forever; this line is never reached.
    print('OK')


if __name__ == '__main__':
    # Kick off a child process while the first client is still in scope.
    process = multiprocessing.Process(target=causeTrouble,
                                      args=['child process'])
    process.start()
``

**Comment by zunger-humu** [comment] 2018-01-11 01:49
Alas, that doesn't work in my case: the datastore client (and more
importantly, the objects which own it, as well as the various other gRPC
clients) are server-global, but the subprocesses need to be forked
on-demand.

This isn't a blocking issue for me right now, since I realized that for
other reasons I needed to switch from multiprocessing to using subprocess
directly (which does a fork+exec and so doesn't have this issue), but for
other users, pre-forking child processes may or may not work, depending on
what they're doing.

**Comment by mbarnathan** [comment] 2018-01-26 07:54
This appears to be causing RPCs to time out when running Google APIs from within celery tasks (I'm using -P eventlet, but other values appear to suffer the same issue as well). Downgrading to grpcio==1.4.0 works; no later version appears to.

**Comment by remram44** [comment] 2018-01-26 17:26
I am affected as well, I'm not using any Google APIs. It seems that a lot of packages trigger grpcio to explode when forking. 1.4.0 doesn't seem to work reliably.

Please, "don't use fork or multiprocessing" can't be an acceptable answer. Can we at least get a reopen here to show that you care? Should we open a new issue and link to this?

**Comment by katbusch** [comment] 2018-01-26 17:31
@remram44 I think this is now being tracked at the newly reopened https://github.com/grpc/grpc/issues/13873

**Comment by srini100** [comment] 2018-01-27 03:13
Confirming that fork() related issues are now being tracked in reopened [#13873](https://github.com/grpc/grpc/issues/13873). Please post  there.
