### ISSUE TITLE
Impossible to build

### ISSUE THREAD

**Issue by alanondra** [grpc/grpc#26559] opened 2021-06-25 19:35 UTC
### What version of gRPC and what language are you using?

PHP, grpc v1.38.1

### What operating system (Linux, Windows,...) and version?

OS X 11.4, Alpine Linux via Docker

### What runtime / compiler are you using (e.g. python version or version of gcc)

PECL or building from source

### What did you do?

I've tried running `pecl install grpc` and [building from source](https://github.com/grpc/grpc/blob/master/BUILDING.md).

### What did you expect to see?

A built and ready-to-use PHP extension within a reasonable timeframe.

### What did you see instead?

An entire workday wasted running slow and fruitless build processes, repeatedly ending up with about 1mb worth of meaningless garbage output before being truncated, ending with the following error message:

	failed to solve: rpc error: code = Unknown desc = executor failed running [/bin/sh -c pecl install grpc]: exit code: 1

**Comment by stanley-cheung** [comment] 2021-06-25 20:57
Where did you get version `1.38.1` for the pecl extension? https://pecl.php.net/package/grpc we only released version `1.38.0`.

Also, can you provide more information about your environment? What platform and how did you run the `pecl install grpc` command? Perhaps there are some missing dependencies somewhere in your environment. We have some basic tests that cover some basic environments and we didn't find any issue with version `1.38.0` and didn't get widespread report of failure. This seems like a one-off environment issue.

**Comment by stanley-cheung** [comment] 2021-06-25 20:59
If this is on Alpine linux, it could be a duplicate of #25250. It's bug in one of the dependencies that need to catch up. We are still following up there.

**Closed** 2022-04-07 05:50 UTC
Labels: kind/bug, lang/php, priority/P2
