### ISSUE TITLE
Can't run "helloworld" example with C++ [ MacOS Yosemite 10.10.5 ]

### ISSUE THREAD

**Issue by iceonepiece** [grpc/grpc#11151] opened 2017-05-16 16:55 UTC
when i run these commands
./greeter_server
```
I0516 23:51:50.366454000 140735199294208 server_builder.cc:247]        Synchronous server. Num CQs: 1, Min pollers: 1, Max Pollers: 2147483647, CQ timeout (msec): 1000
Segmentation fault: 11
```

./greeter_client
```
E0516 23:52:50.960269000 140735199294208 sync_posix.c:60]              assertion failed: pthread_mutex_lock(mu) == 0
Abort trap: 6
```

**Comment by ncteisen** [comment] 2017-05-16 18:05
Duplicate of #10909. The fix for now is to do a clean install of 1.2.x in which this problem does not exist. No one is actively looking into this at the moment, but it is on our radar. Closing.

**Closed by ncteisen** 2017-05-16 18:05 UTC
