### ISSUE TITLE
FLAKE: Kokoro - cloud_to_prod_auth:default:php7:oauth2_auth_token

### ISSUE THREAD

**Issue by apolcyn** [grpc/grpc#11996] opened 2017-07-31 18:27 UTC
Might be similar to https://github.com/grpc/grpc/issues/11967 and https://github.com/grpc/grpc/issues/11995, but this test failed with an `Unknown` status

```
Call did not complete successfully. Status object:
object(stdClass)#197 (3) {
  ["metadata"]=>
  array(0) {
  }
  ["code"]=>
  int(2)
  ["details"]=>
  string(0) ""
}

2017-07-28 17:47:29,422 FAILED: cloud_to_prod_auth:default:php7:oauth2_auth_token [ret=1, pid=22735]
```

**Comment by ZhouyihaiDing** [comment] 2017-11-06 20:25
Dupe of #10763

**Closed by ZhouyihaiDing** 2017-11-06 20:25 UTC
Labels: infra/test env flake, lang/php
