### ISSUE TITLE
Please add the latest version of libraries for Windows

### ISSUE THREAD

**Issue by OSPanel** [grpc/grpc#32627] opened 2023-03-15 19:08 UTC
Please add the latest version of libraries for Windows (TS version) for all supported PHP versions.
Currently, version 1.43.0 is the latest available for download in the PECL repository.

**Comment by alto-php** [comment] 2023-03-17 23:53
Duplicate of https://github.com/grpc/grpc/issues/32304

**Closed by alto-php** 2023-03-17 23:53 UTC
Labels: kind/enhancement, lang/php, priority/P2
