### ISSUE TITLE
Always get StatusCode.UNKNOWN, Stream removed to python server

### ISSUE THREAD

**Issue by AlexLuya** [grpc/grpc#14006] opened 2018-01-12 15:24 UTC
my data.proto likes this:

```
syntax = "proto3";
package rpc;
service Performer {
  rpc carryOut(Image) returns (Objects){}
}

message Objects{
    repeated Object objects=1;
}

message Object{
    string type=1;
}
```
and implementation like this:

```
class Performer(data_pb2_grpc.PerformerServicer):
    def __init__(self):
        pass

    def carryOut(self, req, cxt):
         objs=Objects()
         obj=objs.objects.add()
         obj.type='Person'
         return objs    
```
client request always get:

```
    self.res = self.client().carryOut(self.data()) 
  File "/usr/local/lib/python2.7/dist-packages/grpc/_channel.py", line 484, in __call__
    return _end_unary_response_blocking(state, call, False, deadline)
  File "/usr/local/lib/python2.7/dist-packages/grpc/_channel.py", line 434, in _end_unary_response_blocking
    raise _Rendezvous(state, None, None, deadline)
grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with (StatusCode.UNKNOWN, Stream removed)>
```
and server crash with error: Segmentation fault(written dump)

and it happens in a laptop with :

```
 ubuntu 16.04
 python 2.7.12
 grpcio==1.8.4
 grpcio-tools==1.8.4
```

**Comment by mehrdada** [comment] 2018-01-16 17:41
Seems like the root cause is your server process crashing. Can you try running the server using `GRPC_TRACE=all GRPC_VERBOSITY=debug` environment variables?

**Comment by mehrdada** [comment] 2018-02-27 22:19
I'm going to close this as it is not clear the bug is in gRPC as opposed to the application. Please feel free to reopen if additional evidence is available.

**Closed by mehrdada** 2018-02-27 22:19 UTC
Labels: area/core, disposition/requires reporter action, kind/bug, lang/Python, priority/P2

**Comment by jadekler** [comment] 2018-03-12 18:17
Was this happening on ARM (e.g. raspberry pi) / windows?
