### ISSUE TITLE
Python client is hung when sending a header in upper-case

### ISSUE THREAD

**Issue by adelez** [grpc/grpc#8814] opened 2016-11-22 00:31 UTC
Modify https://github.com/grpc/grpc/blob/master/src/python/grpcio_tests/tests/interop/methods.py#L47 and throw in some letters in upper-case.
Then run the python custom_metadata interop test.
The test eventually times out.

Expect to exit with exception.

Attached is the client log.
[test.txt](https://github.com/grpc/grpc/files/605141/test.txt)

**Comment by ncteisen** [comment] 2016-11-22 20:12
Caveat: not too familiar with cython, but I think the problem is:
https://github.com/grpc/grpc/blob/master/src/python/grpcio/grpc/_cython/_cygrpc/call.pyx.pxi#L62

Checking the result here and throwing an error seems like the right place to do it. I see that the return value of start_client_batch isn't ever checked in _channel.py.

The original error bubbles up from line [615 of call.c](https://github.com/grpc/grpc/blob/master/src/core/lib/surface/call.c#L615), which is called from grpc_call_start_batch.

**Comment by ncteisen** [comment] 2016-11-22 20:14
Happy to add this in, just want to make sure I am not totally off track here

**Comment by nathanielmanistaatgoogle** [comment] 2016-11-22 20:43
@ncteisen: You're right that the result of that call should be checked, but I think the right place to do it is one layer up at the many call sites of `start_client_batch` in `_channel.py`. For some of those sites raising an exception is appropriate but for a few others different error-handling is better.

**Comment by nathanielmanistaatgoogle** [comment] 2016-11-23 19:39
@ncteisen: when you're ready to open a pull request please open it against the `v1.0.x` branch.

**Comment by ncteisen** [comment] 2016-12-20 18:01
This was fixed for v1.0.x in #8995, and then upmerged in #8825

**Closed by ncteisen** 2016-12-20 18:01 UTC
Labels: enhancement, P3, python
