### ISSUE TITLE
C++ grpc client libraries not obeying DNS TTL

### ISSUE THREAD

**Issue by gmehrotr** [grpc/grpc#22897] opened 2020-05-07 18:28 UTC
### What version of gRPC and what language are you using?
I'm using gRPC 1.15.1 (c++)

### What operating system (Linux, Windows,...) and version?
Linux, CentOS7

### What runtime / compiler are you using (e.g. python version or version of gcc)
GCC

### What did you do?
Using grpc to for TTS requests, we see intermittment request failures since the grpc client library tries to make connection to stale IP address for the AWS load balancer.

AWS ELB load balancer would change its IP addresses frequently while its DNS name has the TTL set to 60 seconds. 

It looks like gRPC wouldn't be able to refresh the IP address of an AWS ELB load balancer until a connection with the old IP address fails.

### What did you expect to see?
gRPC client obeying DNS TTL from the server.

### What did you see instead?
DNS TTL was not respected and client kept using stale library address for LB causing request to fail.

Looking for any options we could configure in environmental variable or O.S which can make the gRPC client obey DNS caching rules or worst case any code changes we can do fix this issue.

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

See [TROUBLESHOOTING.md](https://github.com/grpc/grpc/blob/master/TROUBLESHOOTING.md) for how to diagnose problems better.

**Comment by markdroth** [comment] 2020-05-07 18:32
Duplicate of #12295.

**Closed by markdroth** 2020-05-07 18:32 UTC
Labels: kind/bug, priority/P2
