### ISSUE TITLE
Segmentation fault: 11 in macOS Catalina 10.15.7 using grpcio==1.34.0 and grpcio-tools==1.34.0

### ISSUE THREAD

**Issue by tanjuntao** [grpc/grpc#25137] opened 2021-01-12 16:40 UTC
### What version of gRPC and what language are you using?

`grpcio` version: 1.34.0
`grpcio-tools` version: 1.34.0
Python version: 3.8.5

### What operating system (Linux, Windows,...) and version?

macOS Catalina 10.15.7

### What runtime / compiler are you using (e.g. python version or version of gcc)

``` shell
tanjuntao@mbp:~$ python3 --version
Python 3.8.5
tanjuntao@mbp:~$ gcc --version
Configured with: --prefix=/Library/Developer/CommandLineTools/usr --with-gxx-include-dir=/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/4.2.1
Apple clang version 12.0.0 (clang-1200.0.32.2)
Target: x86_64-apple-darwin19.6.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
tanjuntao@mbp:~$ which python3
/usr/local/bin/python3
tanjuntao@mbp:~$ which gcc
/usr/bin/gcc
tanjuntao@mbp:~$
```

### What did you do?

Here is a snippet of my project hierarchy:

```
.
├── protos
│   └── lr.proto
├── service
│   ├── __init__.py
│   ├── lr_pb2.py
│   ├── lr_pb2_grpc.py
│   └── tst.py
└── test.py
```

My `.proto` file is defined in `protos` directory and inside `service` directory, I use `grpc_tools.protoc` to compile the `lr.proto`. Then I new an `__init__.py` in `service` to make it a python package. 

Here is the problem, the content of `service/tst.py` is :

``` python
import lr_pb2
import lr_pb2_grpc
```

When I run `python3 tst.py` in `iTerm2` terminal, I got the `Segmentation fault: 11` error.

I tried to debug this error, and the image below showed which line threw the error:
![image](https://user-images.githubusercontent.com/30660866/104328046-61a12100-5526-11eb-922b-aa087fbcf996.png)

I could not figure it out, so then I tried to add a `import grpc` sentence before `import lr_pb2` as reported in this issue #24897

``` python
import grpc
import lr_pb2
import lr_pb2_grpc
```

The error disappeared.

Below are some other things I have done.

**1. Test the same code in a Linux system**
I tested the same code in `Ubuntu 16.04 LTS` with `grpcio==1.34.0` and `grpcio-tools==1.34.0`, the result was whether I `import grpc` or not in `service/tst.py`, no segmentation fault error was reported.

**2. Degrade `grpcio` and `grpcio-tools` version**
I uninstalled `grpcio==1.34.0` and `grpcio-tools==1.34.0` with `pip3` and re-installed `grpcio==1.33.2` and `grpcio-tools==1.33.2`. Then I re-generate the `pb2` and `pb2_grpc` files under `service` directory.

Then I run `python3 tst.py` in terminal, the result was: whether `import grpc` was included in `tst.py` or not, there was no`segmentation fault: 11` error.

---

BTW, there is another question I am really curious about. I guess it's my misuse of gRPC instead of its own bug.

Here is what it is:

Outside `service`, the content of `test.py` is:

``` python
from service import lr_pb2
from service import lr_pb2_grpc
```

Whether I am using `grpcio==1.33.2` or `grpcio==1.34.0`, when I run `test.py` I always get this error:

```
Traceback (most recent call last):
  File "test.py", line 3, in <module>
    import service.lr_pb2_grpc as lr_pb2_grpc
  File "/Users/tanjuntao/Desktop/lr_grpc/service/lr_pb2_grpc.py", line 5, in <module>
    import lr_pb2 as lr__pb2
ModuleNotFoundError: No module named 'lr_pb2'
```

* When working with `grpcio==1.33.2`, I modify `lr_pb2_grpc.py` and change the import sentence from:

``` python
import lr_pb2 as lr__pb2
```

to:

``` python
import service.lr_pb2 as lr__pb2
```

And the error disappears.

* When working with `grpcio==1.34.0`, I need to modify the `lr_pb2_grpc.py` as above, I should also add a `import grpc` sentence before `import lr_pb2` in `test.py`. The `test.py` becomes:

``` python
import grpc
from service import lr_pb2
from service import lr_pb2_grpc
```

Only in this way, the error would disappear. If I do not include the `import grpc` sentence, `segmentation fault: 11` still arises.

### What did you expect to see?

No `segmentation fault :11` in macOS Catalina 10.15.7 when working with grpcio==1.34.0 and grpcio-tools==1.34.0.

### What did you see instead?

`Segmentation fault: 11`

### Anything else we should know about your project / environment?

Nope.

**Comment by gnossen** [comment] 2021-01-13 21:29
Duplicate of https://github.com/grpc/grpc/issues/24897. [1.34.1](https://pypi.org/project/grpcio/1.34.1/) was released earlier today, which should resolve this issue.

**Closed by gnossen** 2021-01-13 21:29 UTC
Labels: kind/bug, priority/P2

**Comment by gnossen** [comment] 2021-01-13 21:31
I see you added a usage question as well. Try adding the `service` directory to `sys.path` before attempting the import.

**Comment by tanjuntao** [comment] 2021-01-23 06:53
Thanks for your help, it works!
