### ISSUE TITLE
Windows VS-2015 build is broken -- "Cannot open include file: 'openssl/ssl.h: No such file or directory"

### ISSUE THREAD

**Issue by bretm151** [grpc/grpc#5340] opened 2016-02-21 06:12 UTC
I have a fresh git clone and am attempting to build grcp with MSVC 2015 on Windows 10. I cd'ed to vsprojects and ran build_v2015.bat, and captured the output in the attached file.

The first error is:
d:\src\grpc\third_party\boringssl\ssl\tls_record.c(109): fatal error C1083: Cannot open include file: 'openssl/ssl.h': No such file or directory [D:\src\grpc\vsprojects\vcxproj\boringssl\boringssl.vcxproj]

Thanks,

Bret

[output.txt](https://github.com/grpc/grpc/files/139471/output.txt)

**Comment by bretm151** [comment] 2016-02-21 06:14
HEAD is 17ddc83b33da0befa0d9f7395b04ea3ecaff6854

**Comment by goldenbull** [comment] 2016-02-21 08:08
To build with visual studio ,you should remove `boringssl` and `z` from `grpc.sln`. I already opened a same issue, see #4778

**Comment by soltanmm** [comment] 2016-02-23 03:19
Sans version (VS2015 vs. VS2013), this does sound like a duplicate of #4778 as @goldenbull mentioned. Feel free to comment there or to re-open here if you believe I'm in error!

**Closed by soltanmm** 2016-02-23 03:19 UTC

**Comment by goldenbull** [comment] 2016-02-23 05:43
Hi @bretm151 you can `msbuild` a specified project in the `.sln` using `/t` switch:
```
build_vs2015.bat grpc.sln /t:grpc /m
```
