### ISSUE TITLE
gRPC-C++ time.h fails to complie: fatal error: 'chrono' file not found

### ISSUE THREAD

**Issue by mtzfactory** [grpc/grpc#16798] opened 2018-10-06 08:50 UTC
Hi,

I'm building a react-native app that use Firebase (5.9.0), that depends on gRPC-cpp.
When I try to build the project if fails becasue the file __chrono.h__ cannot be found:

```
While building module 'QuartzCore' imported from /Users/mtz/Development/read_it_later___anterior/ios/build/Build/Products/Debug-iphonesimulator/include/React/RCTConvert.h:8:
While building module 'Darwin' imported from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator12.0.sdk/System/Library/Frameworks/QuartzCore.framework/Headers/CABase.h:11:
In file included from <module-includes>:33:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator12.0.sdk/usr/include/wchar.h:91:
In file included from ../../../ios/Pods/Headers/Public/gRPC-C++/grpcpp/support/time.h:22:
../../../ios/Pods/Headers/Public/gRPC-C++/grpcpp/impl/codegen/time.h:22:10: fatal error: 'chrono' file not found
#include <chrono>
         ^~~~~~~~
1 error generated.
While building module 'QuartzCore' imported from /Users/mtz/Development/read_it_later___anterior/ios/build/Build/Products/Debug-iphonesimulator/include/React/RCTConvert.h:8:
In file included from <module-includes>:1:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator12.0.sdk/System/Library/Frameworks/QuartzCore.framework/Headers/QuartzCore.h:9:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator12.0.sdk/System/Library/Frameworks/QuartzCore.framework/Headers/CoreAnimation.h:9:
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator12.0.sdk/System/Library/Frameworks/QuartzCore.framework/Headers/CABase.h:11:10: fatal error: could not build module 'Darwin'
#include <stdbool.h>
 ~~~~~~~~^
While building module 'QuartzCore' imported from /Users/mtz/Development/read_it_later___anterior/ios/build/Build/Products/Debug-iphonesimulator/include/React/RCTConvert.h:8:
While building module 'CoreFoundation' imported from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator12.0.sdk/System/Library/Frameworks/QuartzCore.framework/Headers/CABase.h:16:
In file included from <module-includes>:1:
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator12.0.sdk/System/Library/Frameworks/CoreFoundation.framework/Headers/CoreFoundation.h:16:10: fatal error: could not build module 'Darwin'
#include <sys/types.h>
 ~~~~~~~~^
While building module 'QuartzCore' imported from /Users/mtz/Development/read_it_later___anterior/ios/build/Build/Products/Debug-iphonesimulator/include/React/RCTConvert.h:8:
While building module 'CoreFoundation' imported from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator12.0.sdk/System/Library/Frameworks/QuartzCore.framework/Headers/CABase.h:16:
While building module 'Dispatch' imported from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator12.0.sdk/System/Library/Frameworks/CoreFoundation.framework/Headers/CFStream.h:20:
In file included from <module-includes>:1:
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator12.0.sdk/usr/include/dispatch/dispatch.h:25:10: fatal error: could not build module 'Darwin'
#include <Availability.h>
 ~~~~~~~~^
While building module 'QuartzCore' imported from /Users/mtz/Development/read_it_later___anterior/ios/build/Build/Products/Debug-iphonesimulator/include/React/RCTConvert.h:8:
While building module 'CoreFoundation' imported from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator12.0.sdk/System/Library/Frameworks/QuartzCore.framework/Headers/CABase.h:16:
While building module 'Dispatch' imported from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator12.0.sdk/System/Library/Frameworks/CoreFoundation.framework/Headers/CFStream.h:20:
While building module 'os_object' imported from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator12.0.sdk/usr/include/dispatch/dispatch.h:48:
In file included from <module-includes>:1:
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator12.0.sdk/usr/include/os/object.h:25:10: fatal error: could not build module 'Darwin'
#include <Availability.h>
 ~~~~~~~~^
1 error generated.
2 errors generated.
3 errors generated.
While building module 'QuartzCore' imported from /Users/mtz/Development/read_it_later___anterior/ios/build/Build/Products/Debug-iphonesimulator/include/React/RCTConvert.h:8:
While building module 'Foundation' imported from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator12.0.sdk/System/Library/Frameworks/QuartzCore.framework/Headers/CATransform3D.h:12:
In file included from <module-includes>:1:
/Applications/Xcode.app/Contents/Developer/
Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator12.0.sdk/System/Library/Frameworks/Foundation.framework/Headers/Foundation.h:6:10: fatal error: could not build module 'CoreFoundation'
#include <CoreFoundation/CoreFoundation.h>
 ~~~~~~~~^
While building module 'QuartzCore' imported from /Users/mtz/Development/read_it_later___anterior/ios/build/Build/Products/Debug-iphonesimulator/include/React/RCTConvert.h:8:
While building module 'Foundation' imported from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator12.0.sdk/System/Library/Frameworks/QuartzCore.framework/Headers/CATransform3D.h:12:
While building module 'ObjectiveC' imported from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator12.0.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSObject.h:6:
In file included from <module-includes>:1:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator12.0.sdk/usr/include/objc/./objc-exception.h:27:
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator12.0.sdk/usr/include/objc/objc.h:31:10: fatal error: could not build module 'Darwin'
#include <sys/types.h>      // for __DARWIN_NULL
 ~~~~~~~~^
1 error generated.
While building module 'QuartzCore' imported from /Users/mtz/Development/read_it_later___anterior/ios/build/Build/Products/Debug-iphonesimulator/include/React/RCTConvert.h:8:
While building module 'Foundation' imported from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator12.0.sdk/System/Library/Frameworks/QuartzCore.framework/Headers/CATransform3D.h:12:
While building module 'Security' imported from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator12.0.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSURLCredential.h:9:
In file included from <module-includes>:1:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator12.0.sdk/System/Library/Frameworks/Security.framework/Headers/Security.h:27:
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator12.0.sdk/System/Library/Frameworks/Security.framework/Headers/SecBase.h:27:10: fatal error: could not build module 'Darwin'
#include <TargetConditionals.h>
 ~~~~~~~~^
1 error generated.
While building module 'QuartzCore' imported from /Users/mtz/Development/read_it_later___anterior/ios/build/Build/Products/Debug-iphonesimulator/include/React/RCTConvert.h:8:
While building module 'Foundation' imported from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator12.0.sdk/System/Library/Frameworks/QuartzCore.framework/Headers/CATransform3D.h:12:
While building module 'CoreServices' imported from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator12.0.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSURLError.h:17:
In file included from <module-includes>:1:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator12.0.sdk/System/Library/Frameworks/CoreServices.framework/Headers/CoreServices.h:9:
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator12.0.sdk/System/Library/Frameworks/CoreServices.framework/Headers/UTCoreTypes.h:19:10: fatal error: could not build module 'CoreFoundation'
#include <CoreFoundation/CoreFoundation.h>
 ~~~~~~~~^
1 error generated.
4 errors generated.
While building module 'QuartzCore' imported from /Users/mtz/Development/read_it_later___anterior/ios/build/Build/Products/Debug-iphonesimulator/include/React/RCTConvert.h:8:
While building module 'OpenGLES' imported from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator12.0.sdk/System/Library/Frameworks/QuartzCore.framework/Headers/CAEAGLLayer.h:7:
In file included from <module-includes>:1:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator12.0.sdk/System/Library/Frameworks/OpenGLES.framework/Headers/EAGLDrawable.h:8:
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator12.0.sdk/System/Library/Frameworks/OpenGLES.framework/Headers/EAGL.h:8:10: fatal error: could not build module 'Foundation'
#include <Foundation/Foundation.h>
 ~~~~~~~~^
1 error generated.
10 errors generated.
In file included from /Users/mtz/Development/read_it_later___anterior/node_modules/react-native-firebase/ios/RNFirebase/converters/RCTConvert+UIBackgroundFetchResult.m:1:
In file included from /Users/mtz/Development/read_it_later___anterior/node_modules/react-native-firebase/ios/RNFirebase/converters/RCTConvert+UIBackgroundFetchResult.h:1:
/Users/mtz/Development/read_it_later___anterior/ios/build/Build/Products/Debug-iphonesimulator/include/React/RCTConvert.h:8:9: fatal error: could not build module 'QuartzCore'
#import <QuartzCore/QuartzCore.h>
 ~~~~~~~^


** BUILD FAILED **
```

### What version of gRPC and what language are you using?
 Objective-C (iOS)

Using gRPC (1.14.0)
Using gRPC-C++ (0.0.3)
Using gRPC-Core (1.14.0)
Using gRPC-ProtoRPC (1.14.0)
Using gRPC-RxLibrary (1.14.0)
 
### What operating system (Linux, Windows, …) and version?
 Mac OS Sierra
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
 XCode 10 (iOS)

**Comment by nicolasnoble** [comment] 2018-10-06 13:15
This file is part of the compiler's suite, so if you don't have it, it means something is wrong with your system.

**Comment by wilhuff** [comment] 2018-10-07 18:32
The issue here is that with Xcode's header map enabled, gRPC's time.h is found when sources do a `#include <time.h>`. In this case the translation unit is Objective-C, not C++, so the standard C++ headers aren't available and the build fails.

**Comment by mtzfactory** [comment] 2018-10-10 06:12
Hi,

Thanks for your comments, is there any solution? do you know how can I specify to Xcode that gRPC's should be compiled with C++?

**Comment by wilhuff** [comment] 2018-10-10 06:21
The problem isn't that gRPC is being mis-compiled. The problem is that react-native's `RCTConvert+UIBackgroundFetchResult.m` (and Objective-C file) is finding gRPC's time.h when it should be finding the system time.h.

A work-around for the moment would be to disable the header map in your project (as I mentioned in the other issue you filed).

**Comment by bharatbiswal** [comment] 2018-10-14 01:48
@wilhuff I disabled the "Use Header Maps", still i am getting the error.
I am using Xcode: 9.4.1
react-native-cli: 2.0.1
react-native: 0.57.1

![screen shot 2018-10-14 at 7 11 01 am](https://user-images.githubusercontent.com/1182376/46911691-4464fd00-cf81-11e8-9d3a-d0ff9dada43e.png)

**Comment by muxi** [comment] 2018-10-16 17:17
The problem is interesting since grpc c++ podspec specifically [disabled](https://github.com/grpc/grpc/blob/master/gRPC-C%2B%2B.podspec#L64) header map. I tried with a simple project that does `#include <time.h>` and I did not experience the compiler errors as you. I wonder if any special configuration in your project is triggering this problem.

@bharatbiswal would you be able to provide a minimum example that reproduces this?

**Comment by muxi** [comment] 2018-10-16 17:22
And my guess is that we likely can identify what the root cause is during the process of constructing a minimum reproduction.

**Comment by eamonwhiter73** [comment] 2018-10-24 22:43
I am having the same problem, see my post #18793 at the bottom. still looking for a solution.

**Comment by muxi** [comment] 2018-10-26 17:09
@eamonwhiter73 - I'm not sure if setting `Use Header Maps` to `No` for reactive's pod (or whatever pod that is including that `time.h`) would help or not. @bharatbiswal seems to set it to the app target, which I wonder if is the reason that it did not work. Also confirm it is set for `gRPC-C++`.

**Comment by eamonwhiter73** [comment] 2018-10-26 17:35
Thanks, I fixed it, I think maybe i did what you suggested, but I can't remember.

**Comment by FullstackJack** [comment] 2018-12-01 23:48
@eamonwhiter73 What did you do to fix it?

**Comment by CyrusZei** [comment] 2019-03-18 00:06
any update on this?

**Comment by CyrusZei** [comment] 2019-03-18 12:02
@mtzfactory how did you solve this ?

**Comment by CyrusZei** [comment] 2019-03-18 12:37
is there a way to disable it or "work around" this problem until it is fixed?

**Comment by CyrusZei** [comment] 2019-03-19 01:34
this worked for me

https://github.com/firebase/firebase-ios-sdk/issues/1916#issuecomment-474153045

**Comment by muxi** [comment] 2019-03-28 16:33
Looks like something outside gRPC. Closing this issue unless there's more concerns on gRPC's pod configurations.

**Closed by muxi** 2019-03-28 16:33 UTC
Labels: kind/bug, lang/ObjC, priority/P2
