### ISSUE TITLE
Trailers in RpcException cannot use UTF-8 Characters

### ISSUE THREAD

**Issue by Yukimir** [grpc/grpc#25888] opened 2021-04-06 10:54 UTC
### What version of gRPC and what language are you using?
C# 2.30.0
2.36.0 still have the same problem

### What operating system (Linux, Windows,...) and version?
Windows

### What runtime / compiler are you using (e.g. python version or version of gcc)
.Net Core 3.1

### What did you do?
Throw a new RpcException in GrpcService
```
throw new RpcException(new Status(StatusCode.Internal, ""), new Metadata
                {
                    { "ErrorCode", 400310 },
                    { "Message", "あああああ" }
                });
```

### What did you expect to see?
Client could catch the exception with Message "あああああ"

### What did you see instead?
`An unhandled exception has occurred while executing the request.` With No Log

### Anything else we should know about your project / environment?

If I change Message "あああああ" To 'aaaaa'，no problem happened.

**Comment by jtattermusch** [comment] 2021-04-08 12:38
I don't think the metadata entry values are allowed to be utf8.
See https://github.com/grpc/grpc/blob/master/doc/PROTOCOL-HTTP2.md

> `ASCII-Value → 1*( %x20-%x7E ) ; space and printable ASCII`

If you want to send non-ascii values as metadata value, you can use "binary metadata" and than store whatever data you want in the binary metadata value.

Note that the general status message allows to have utf8 message (as specified in the protcol spec).
FTR see e.g. this test: https://github.com/grpc/grpc/blob/7c5a7bd73b33899f85b88a9c6460933dd35f39b8/src/csharp/Grpc.Core.Tests/ClientServerTest.cs#L346

**Comment by jtattermusch** [comment] 2022-02-23 16:37
Closing as this is working as intended (metadata values for non-binary metadata can only be ASCII as pointed out above).
If you want to transfer a richer error status as part of trailers, you can use binary metadata and stored a serialized protobuf object - e.g. see https://github.com/grpc/grpc/blob/7c74d58cbecc8342c349cbf39eecb9aa0b666522/src/csharp/Grpc.IntegrationTesting/CustomErrorDetailsTest.cs#L119

**Closed by jtattermusch** 2022-02-23 16:37 UTC
Labels: kind/bug, lang/C#, priority/P2
