### ISSUE TITLE
Current setting for C++ standard in CMake is unsafe for ABI compatibility

### ISSUE THREAD

**Issue by Dlougach** [grpc/grpc#22125] opened 2020-02-25 13:42 UTC
(Not going to use the standard bug request form, because I am going to highlight a potential problem that would only become real with more use of Abseil).

Currently C++ standard is set for gRPC by appending `-std=c++11` to `CMAKE_CXX_FLAGS`. There are several problems with this approach:

1. If the user has CMAKE_CXX_STANDARD variable set (let's say, to 17) and includes gRPC with `add_subdirectory`, the command line for the calls will include both `-std=c++11` and `-std=c++17`. In this case the ordering of the flags makes both Clang and G++ use that C++17 (which is probably good), but this is relying on undocumented behavior.
2. With any dependency on Abseil library this becomes more dramatic. Abseil is ABI-incompatible between different C++ standard versions, because it conditionally aliases some of its classes to standard library instead of defining them. This means that if both gRPC and user's code want to depend on Abseil, they MUST use the same C++ standard.

Point 2 also means that if a user wants to install gRPC using `gRPC_INSTALL` option, they must specify C++ standard used.

Therefore, I suggest 2 changes:

1. There should be a way to set C++ standard used in gRPC CMake build. Perhaps this should be controlled by a variable that defaults to `CMAKE_CXX_STANDARD` and if it's not set - to 11.
2. Documentation on building/installing gRPC should somehow highlight the important of setting this variable for the first CMake invocation.

**Comment by veblush** [comment] 2020-02-27 04:50
Thank you for pointing this out. As you said, it'd be better to have a single control knob to decide the version of C++ and a comprehensive doc for this.

**Comment by veblush** [comment] 2020-02-27 04:51
@jtattermusch WDTY?

**Comment by vjpai** [comment] 2020-02-27 04:54
We have never promised ABI stability.

**Comment by veblush** [comment] 2020-02-27 04:57
@vjpai This is not about ABI guarantee but about consistency across the library. If a compiler setting is  not applied consistently, it may end up with a linker error or crash at run time. ([ref](https://abseil.io/docs/cpp/guides/options))

**Comment by jtattermusch** [comment] 2020-02-27 16:30
I have a very old PR that attempted to set CMAKE_CXX_STANDARD in a clean and portable way:
https://github.com/grpc/grpc/pull/15502/files#diff-af3b638bc2a3e6c650974192a53c7291R97

would that solve the problem? Perhaps we could revive that PR (now it would be easier because we are already on the right cmake_minimum_required version of cmake.

**Comment by veblush** [comment] 2020-02-29 05:37
@jtattermusch That would be great! Please revive that PR!

**Comment by jtattermusch** [comment] 2020-03-11 12:26
https://github.com/grpc/grpc/pull/15502 was merged

**Comment by veblush** [comment] 2020-03-12 16:15
Since a major change was merged, only documentation remains so the priority is bumped to P3.

**Comment by jtattermusch** [comment] 2020-05-08 13:16
https://github.com/grpc/grpc/pull/15502 was merged a while ago, hopefully that should be enough to address this issue?

**Comment by adrianimboden** [comment] 2020-05-09 03:14
Setting the CMAKE_CXX_STANDARD variable as it is done in #15502 does not address this issue at all.

The problem is that this library gets built with C++11 standard, but when used later from a C++17 Codebase (for example), then the linking fails in our case. More subtle failures are to be expected.
The reason for the link failures are functions which in C++11 are provided differently than in C++17 based on compile time checks.

Not setting this variable or at least providing a knob to set it from an add_subdirectory caller of grpc would be necessary to solve this problem.

In our build system, we use a patched variant of the source where we don't set the variable.

**Comment by Dlougach** [comment] 2020-05-09 09:51
I agree with adrianimboden. #15502 doesn't solve the problem, it actually upgrades the severity of it from a theoretical issue (as I've originally described) into a real-world problem. The way it should work is to set standard only if it hasn't already been set by the user.

As a workaround one may patch source during their build to ensure most options in absl/base/options.h are set to 0.

**Comment by jtattermusch** [comment] 2020-05-11 07:36
@adrianimboden  @Dlougach  can you provide a patch that would fix this issue then?

**Closed** 2020-05-19 07:05 UTC
Labels: kind/enhancement, lang/c++, priority/P3
