### ISSUE TITLE
C# Nugets: Can't step into Grpc code when debugging

### ISSUE THREAD

**Issue by gazialankus** [grpc/grpc#9521] opened 2017-01-31 16:03 UTC
I would like to step into C# grpc code but I can't.

I'm using grpc via NuGet in Visual Studio and it can't find Grpc.Core.pdb for 1.00.1.0. I configured to use symbolsource.org but it seems [the latest pdb it has is for 0.7.1](https://www.symbolsource.org/Public/Metadata/NuGet/Project/Grpc.Core). I'm not a NuGet expert, maybe I'm missing something. How can I step into grpc code?

![screenshot](https://cloud.githubusercontent.com/assets/412997/22469108/8ede46c6-e7d3-11e6-8e38-cbed6b9228ed.png)

**Comment by jtattermusch** [comment] 2017-04-10 09:09
Odd that this doesn't work because symbols should be pushed by nuget whenever the main packages are being uploaded. I tried to re-push symbol packages for 1.2.0 and 1.2.2, let's see if that helps.

**Comment by jtattermusch** [comment] 2017-04-28 13:46
I just published nugets for v1.3.0  and I am 100% positive that the .symbols nugets contain both .pdb files and the source code. And they were uploaded to https://nuget.smbsrc.net/.  Yet, I am still unable to step into the gRPC code in Visual Studio.

**Comment by jtattermusch** [comment] 2017-04-28 13:55
Actually, on https://www.symbolsource.org/ I can't really find up-to-date packages for several other popular projects - like Google.Protobuf, Newtonsoft.Json, Nodatime etc. That makes me think something is wrong with the symbol server rather than with gRPC symbol packages themselves.

https://www.symbolsource.org/Public/Metadata/NuGet/Project/Google.Protobuf
https://www.symbolsource.org/Public/Metadata/NuGet/Project/Nodatime

@jskeet   have you noticed the same problem for Google.Protobuf or Nodatime?

**Comment by jskeet** [comment] 2017-04-28 13:59
Haven't tried, to be honest - I'll see if I can find time this afternoon.

But yes, odd that it only has very old versions of *everything* - I agree it sounds like a server problem.

**Comment by jskeet** [comment] 2017-04-28 14:02
(The fact that the server takes *ages* to respond to any requests doesn't bode well for it, either.)

The "latest additions" referred to Hime.Redist 2.0.5, which appeared on nuget.org in September 2016...

**Comment by jtattermusch** [comment] 2017-05-02 14:35
FYI @chwarr (you mentioned this issue before)

**Comment by jskeet** [comment] 2017-05-05 17:19
NuGet now pushes to https://nuget.smbsrc.net/, not `symbolsource.org`. You'll need to set that up as the source in Visual Studio.

**Comment by jtattermusch** [comment] 2017-05-05 17:29
@jskeet  I tried setting https://nuget.smbsrc.net/ as a source in Visual Studio before. It doesn't work and in "Modules" window you can see the error:

```
SYMSRV:  https://nuget.smbsrc.net: not available
https://nuget.smbsrc.net: Symbols not found on symbol server.
```

**Comment by jskeet** [comment] 2017-05-05 17:35
See if http://stackoverflow.com/questions/41775237 helps you - it looks like it's pretty picky. (I'm not in a position to check right now though.)

**Comment by jtattermusch** [comment] 2017-05-05 17:39
Using https://nuget.smbsrc.net also doesn't help (I'm using VS2015). Is loading symbols working for you?

**Comment by jskeet** [comment] 2017-05-05 17:41
As I said, I'm not in a position to check right now. Will try to find time later (but it may well be Monday instead).

**Comment by jskeet** [comment] 2017-05-05 18:15
Okay, just tried, and had the same problems. Have appealed on Twitter...

**Comment by markbarks** [comment] 2017-05-27 19:28
I'm still having issues 3 weeks later. Wondering if anyone from symbol source is aware of this? 

random complaints below -- feel free to ignore :)
I'm coming recently to C# (after Python, Java, Go, etc etc) - I can't quite fathom the .net dependency management world. The documentation seems to be all over the place, and even on the [MS page](https://docs.microsoft.com/en-us/nuget/create-packages/symbol-packages) people are complaining about this issue, with no response. Surely it's a big deal if people can't debug through library code?

**Comment by jskeet** [comment] 2017-05-27 23:57
One option that's been suggested for google-cloud-dotnet is the new "Source Link" support:
https://github.com/GoogleCloudPlatform/google-cloud-dotnet/issues/923

I haven't tried it yet, but if nuget.smbsrc.net is basically broken, it might be worth moving to that. (I believe it will only help for VS2017 users, although I could be wrong.)

**Comment by smflorentino** [comment] 2018-01-03 20:05
Is there another way to obtain the symbols? Even if we have to build them ourselves? The issue is that recent ones are not being published anywhere, so we couldn't use them with an internal symbol server even if we wanted to.

My co-worker built gRPC from scratch but didn't get any symbols in the output.

**Comment by jskeet** [comment] 2018-01-03 22:47
Sourcelink has worked well for us in google-cloud-dotnet - @jtattermusch have you given it a shot in Grpc.Core?

**Comment by jtattermusch** [comment] 2018-01-08 15:25
With https://github.com/grpc/grpc/pull/13927, stepping into gRPC C# code now works.
- I've used https://github.com/ctaggart/SourceLink (SourceLink.Embed.AllSourceFiles)
- C# nugets for the next gRPC C# version (v1.9.x) will now contain PDB files for debugging and the source code is embedded in those PDB files.

Limitations:
- You need an IDE with Source Link support (VS2017+)  - see https://github.com/ctaggart/SourceLink for more info.
- PDBs with embedded sources are only supported in VS2017 Update 5 and later.

I tested with VS2017 5.5 and stepping into gRPC C# code has worked well with both old-style .NET45 projects and the new dotnet CLI .csproj projects.

**Closed by jtattermusch** 2018-01-08 15:25 UTC
Labels: area/packaging & distribution, lang/C#

**Comment by smflorentino** [comment] 2018-01-08 17:35
This is great! Thanks so much @jtattermusch.

**Comment by jtattermusch** [comment] 2018-01-25 07:54
I've pushed v1.9.0-pre2 nugets with #13927 in, feel free to test it.
