### ISSUE TITLE
[Aio] Unified Stub Call

### ISSUE THREAD

**Issue by lidizheng** [grpc/grpc#20001] opened 2019-08-20 15:47 UTC
This issue tracks the implementation of the unified stub call for gRPC Python. The new API should merge the previous 3 options into 1. For detailed design and rational, see:
https://github.com/lidizheng/proposal/blob/grpc-python-async-api/L58-python-async-api.md#unified-stub-call

**Comment by pfreixes** [comment] 2019-09-17 13:09
Hi, @lidizheng are you planning on working on this? If not, I would like to work on this.

**Comment by lidizheng** [comment] 2019-09-17 17:09
I'm planning to work on the server-side. I think you can start to work on this :)

**Comment by pfreixes** [comment] 2019-10-05 13:56
You can put this as in progress, thanks!

**Comment by pfreixes** [comment] 2019-10-08 21:30
HI,

It seems that having the unified stub call implemented and having interceptors asynchronous working together does not fit very well.

Remember that one of the foundations of the unified stub call was having the capacity of returning an _awaitable_ object which would give the freedom to the user for either waiting by using the normal `Asyncio` syntax, so having like this:

```python
response = await stub.call(...)
```

or by taking the call for later use it for canceling, getting the initial metadata or other asynchronous stuff that might provide the `grpc.aio.Call` object. So so having something like this:

```python
call = stub.call()
await asyncio.sleep(1)
if not call.canceled():
    response = await call
```

For doing so, we are forced to implement the `__call__` method of the `UnaryUnaryMultiCallable` as regular python function. Otherwise, Python resolves the `await` keyword against the coroutine. Having something like this:

```
response = await stub.call()
print(type(response)) <-- Call object !!!!
```

Once we stat **introduce the interceptors with the requirement of being asynchronous is when the API gets totally broken**, where the same stub called with or without interceptors would return totally different values, please take a look at the following snippet:

```python
import asyncio

class Call:
    def __init__(self, task):
        self._task = task

    def __await__(self):
        yield from self._task.__await__()

async def rpc():
    await asyncio.sleep(5)
    print("Slept for 5 seconds")

def call_rpc():
    # this would be the the UnaryUnaryMultiCallable.__call__ method
    return Call(asyncio.ensure_future(rpc()))

async def my_interceptor(continuation):
    return continuation()

async def call_rpc_with_interceptor():
    # this would be the the _UnaryUnaryMultiCallable.__call__ method published by interceptor
    return await my_interceptor(call_rpc)

async def main():
    await call_rpc()
    call = await call_rpc_with_interceptor()
    await call

asyncio.get_event_loop().run_until_complete(main())
```

This has two problems:

- Returned object by an interceptor channel and for a none intercepted channel is different
- Interceptors CAN'T inspect the return of the call without explicitly awaiting the call. The user would not be happy with this :)

For solving these two problems I'm proposing for running the interceptors within the wrapped task, please take a look at the following snippet:

```python
import asyncio

class Call:
    def __init__(self, task):
        self._task = task

    def __await__(self):
        yield from self._task.__await__()

async def rpc():
    await asyncio.sleep(5)
    print("Slept for 5 seconds")

def call_rpc():
    # this would be the the UnaryUnaryMultiCallable.__call__ method
    return Call(asyncio.ensure_future(rpc()))

async def call_rpc_within_an_interceptor_path():
    # this would be an internal method of UnaryUnaryMultiCallable which won't
    # wrap the rpc call to a task, task is created at the very begining by the interceptor
    return await rpc()

async def my_interceptor(continuation):
    return await continuation()

def call_rpc_with_interceptor():
    # this would be the the _UnaryUnaryMultiCallable.__call__ method published by interceptor
    return Call(asyncio.ensure_future(my_interceptor(call_rpc_within_an_interceptor_path)))

async def main():
    await call_rpc()
    await call_rpc_with_interceptor()

asyncio.get_event_loop().run_until_complete(main())
```

Since interceptor asynchronous calls are executed within the wrapped task, they can effectively become asynchronous and we can make the entrypoint `call_rpc_with_interceptor` totally synchronous. So both problems got solved.

This solution is not totally straightforward, there are at least two things thatt need to be solved. 

First, in my current design, I'm using an ad-hoc exception for communicating the `rpc` coroutine that the `call.cancel()` method was called. Using the ad-hoc exception seems to be the easy way for communicating also that was asked to be canceled and some grpc stauts code + details would need to be used. Following snippet shows how the Cython code would look like for accepting cancellation:

```python
            try:
                await self._waiter_call
            except AioCallLocallyCancelledError as err:
                details = str_to_bytes(err.details)
                self._references.append(details)
                c_details = <char *>details
                result = grpc_call_cancel_with_status(
                    call, err.error_code, c_details, NULL)
            except asyncio.CancelledError as err:
                with nogil:
                    result = grpc_call_cancel(
                        call, NULL)
```

The problem here is that the cancellation might be done before or after the call, during the interceptor's execution. The interceptors would be receiving this internal error.

We could address this by making the `AioCallLocallyCancelledError` exception a first citizen class which could be considered by the interceptors - maybe could be a derivated class of the `CancelledError` one.

Another solution would be saving the status of the call in some way within the `grpc.aio.Call` object, so a call to the `call.cancel()` will decide on using `AioCallLocallyCancelledError` or the `CancelledError` depending on the status.

Another problem will be with the data that is being returned to the interceptor.  In an ideal world, the interceptor would need to get as a result a `grpc.aio.Call` instance for the sake of simplicity, but in that solution presented would get the raw values that are not yet bound to a `Call` object - this would be done by the internals of the `Call.__await__`. We would need to figure out how we could make this information available in a more appropriate way for the interceptor matching the contract with the `grpc.aio.Call` object.

WDYT? @lidizheng @gnossen

**Comment by lidizheng** [comment] 2019-10-16 00:04
@pfreixes  Let me attempt to summarize your comment first, correct me if I miss something. There are essentially two issues here:
1. Returning `awaitable` breaks the function signature of client-side interceptors;
2. Proposing a cancellation implementation through exception.

### Returning `awaitable`

#### Should we make `grpc.aio.Call` a wrapper of scheduled task?

As I commented in https://github.com/grpc/proposal/pull/155#discussion_r334617997, I think this solution is valid and the performance overhead is acceptable.

#### Inject the interceptor within the `grpc.aio.Call` object

I think this is also a good solution. Once thing to note is that existing API is intercepting calls at Channel-level. If we want to keep the semantic, when we create MultiCallable object, we need to pass in some Channel state which contains the interceptors. Then the interceptors can be assembled in the `grpc.aio.Call` object. The code roughly like:

```Python
ContinuationType = Callable[[grpc.ClientCallDetails, Request], grpc.aio.Call[Response]]


class _ChannelState:
    interceptors: List[Interceptor]


def continuation_factory(previous_continuation: ContinuationType) -> ContinuationType:
    async def continuation(
            client_call_details: grpc.ClientCallDetails,
            request: Request) -> grpc.aio.Call[Response]:
        return await previous_continuation(client_call_details, request)

    return continuation


class UnaryUnaryMultiCallable(...):
    def __init__(self, channel_state:_ChannelState):
        self._channel_state = channel_state
        # The _actual_unary_unary_call is a pseudo function for perform the call. It can be either a member function, or a Cython function.
        self._logic = _actual_unary_unary_call  # ContinuationType

        # Assemble the interceptors
        for interceptor in self._channel_state.interceptors:
            continuation = continuation_factory(self._logic)
            self._logic = functools.partial(
                interceptor.intercept_unary_unary,
                continuation,
            )

    def __call__(self, request, ...):
        client_call_details = ...
        future = asyncio.ensure_future(
            self._logic(client_call_details, request)
        )
        return Call(future)


def intercept_channel(channel: grpc.aio.Channel, *interceptors: Interceptor):
        channel._channel_state.interceptors.extends(interceptors)
```

### Cancellation

#### Introducing `AioCallLocallyCancelledError`

Can you explain more about the rationale behind it? To me, the `code` and `details` can be passed in through by directly calling our our cancel API in `grpc.aio.Call`, and the cancel API will raise an `asyncio.CancelledError`. How does that sound?

```Python
call.cancel()  # Use default code, details
call.cancel(code=grpc.StatusCode.ALREADY_EXISTS, details="Object already created!")
```

#### Cancellation in Interceptor Context

The propagation of exception will effectively go through layers of interceptors, unless the user is explicitly shielding.

#### Return value of continuation is different than the normal call

If we make each continuation returns `grpc.aio.Call`, this should not be a headache anymore. One possible solution is proposed in above snippet.

**Comment by pfreixes** [comment] 2019-10-17 11:23
Hi @lidizheng let me answer to you the different open questions

> Should we make grpc.aio.Call a wrapper of scheduled task?

I think that we are on the same page, the `grpc.aio.Call` will wrapper the scheduled task for providing its own interface, like the `cancel` one, that will use the under the hood the interfaces provided by the `Task`, for example:

```python

class Call:

    def __init__(self, call, response_deserializer):
        self._code = None
        self._cancelled = False
        self._call = call
        self._response_deserializer = response_deserializer

    def cancel(self):
        if self._code is None:
            code = grpc.StatusCode.CANCELLED
            details = 'Locally cancelled by application!'
            self._call.set_exception(
                cygrpc.AioCallLocallyCancelledError(
                    _common.STATUS_CODE_TO_CYGRPC_STATUS_CODE[code], details))
            self._cancelled = True
            self._code = code
            return False
```

Note the usage of the `self._call.set_exception` method that is the API provided by the task.

>  inject the interceptor within the grpc.aio.Call object

Oks we are aligned that the solution would need from us thinking on how - you already proposed a likely implementation- the interceptors can be injected within the `grpc.aio.Call` code path

> Introducing AioCallLocallyCancel

Unfortunately, the `cancel` method provided by an Asyncio Task does not provide much freedom [1]. The following once would not work without having an extra plumbing for making available the `code` and the `details`.

```python
class Call:
    def __init__(self, call):
        self._call = call

    def cancel(self, code=None, details=None):
            self._call.cancel()
```

I will give a second thought on this

> Return value of continuation is different than the normal call

Let's have this discussion once we start implementing the client interceptors

So the question is how to make the `code` and `details` available in the context of the RPC execution? Remember that what we have basically is a task that is waiting for a result, which would receive a `CancelError` if the task is canceled.

```python
try:
    await future
except CancellError:
    # Here is where you would need the `code` and the `detail`
    grpc_call_cancel_with_status(call, code, detail, ...)
```

The goal of `AioCallLocallyCancel` it's basically piggyback on the `set_exception` capacity for sending the context as simple exception attributes,  for example:

```python
try:
    await future
except AioCallLocallyCancel as e:
    grpc_call_cancel_with_status(call, e.code, e.detail, ...)
    raise CancelledError from e
```

The main drawback of using this pattern is that in the use case of canceling the call when the code path is in the middle of interceptors, the interceptor will receive this weird and theoretically internal exception.

Another option will be basically making available the Call object within the RPC code path, having something like that

```python
try:
    await future
except CancellError:
    # self._aio_call will be an instance of the grpc.aio.Call object 
    grpc_call_cancel_with_status(call, self._aio_call.code, self._aio_call.details, ...)
```

**Comment by lidizheng** [comment] 2019-10-17 21:08
@pfreixes 

> Note the usage of the self._call.set_exception method that is the API provided by the task.

In current implementation, it raises `self` when RPC encounters error. And the `self` object has `code()` and `details()` method on its interface. WDYT about this alternative?

For me, I generally like to be cautious about introducing new interface. Especially exceptions, we are using one exception type that covers all situation right now. I felt like stronger rationale needed to break that contract.

> Unfortunately, the cancel method provided by an Asyncio Task does not provide much freedom [1]. The following once would not work without having an extra plumbing for making available the code and the details.

Where is the link to [1]? The plumbing doesn't look too bad to me. Rather, I think the issue is how do we define the semantic.

#### What are the expectations of `call.cancel()`?

This sections is up for discussion. The goal is to cancel the underlying RPC in C-Core, and notify `await` caller that the RPC is cancelled. I would vote for calling `task.cancel` instead of `set_exception`. Former option better preserved the cancellation semantic in AsyncIO, and works better with shielding and more native.

> So the question is how to make the code and details available in the context of the RPC execution? 

I think what `AioCallLocallyCancel` can do, the native `CancelledError` and `grpc.RpcError` can do the same thing. Maybe I am missing something? Here's my pseudo code:

```Python
class Call(..., asyncio.RpcError, asyncio.CancelledError):
    def __init__(self, call: asyncio.Task):
        self._call = call

    def cancel(self,
               code: grpc.StatusCode=grpc.StatusCode.CANCELLED,
               details: Text='Locally cancelled by application!'
            ) -> None:
        # Cancels underlying RPC
        grpc_call_cancel_with_status(..., code, details)

        self._code = code
        self._details = details

        # Generate cancellation exception
        self._call.set_exception(self)
    
    def __await__(self) -> Awaitable[Response]:
        # Just let the exception propagate
        return self._call.__await__()


async def my_application(stub):
    try:
        # Returns grpc.aio.Call
        with stub.StreamingHi() as call:
            result = await _other_io_tasks(await call.read())
            if not _result_is_ideal(result):
                call.cancel()
    except asyncio.RpcError as e:
        print(e.code())
        print(e.details())
```

**Comment by lidizheng** [comment] 2019-11-05 22:16
@pfreixes Should we close this issue? What would be the closing criteria?

**Comment by pfreixes** [comment] 2019-11-06 09:08
I didn't think about what would mean move an issue from `Done` to `Close`.

Maybe for now we can say that if an issue has not been reverted in the following days we could consider it as close? For example 1 week?

**Comment by lidizheng** [comment] 2019-11-06 19:01
By `Close`, I mean `Done` or completed. Okay.

**Comment by pfreixes** [comment] 2019-11-08 20:52
From I can see the board has its own `Done` state which does not match with the state of the issue :), so yes let's close it once the issue is put as done on the board. If gets reverted we will always have the chance of reopening the issue.

**Closed by pfreixes** 2019-11-08 20:52 UTC
Labels: area/api, kind/enhancement, lang/Python, priority/P2
