### ISSUE TITLE
`grpcio==1.8.x` release logs messages that shouldn't be there

### ISSUE THREAD

**Issue by dhermes** [grpc/grpc#13855] opened 2017-12-21 16:58 UTC
This happens consistently (i.e. every time) on the first call to `grpc.secure_channel` and logs three messages about the `GRPC_LINUX_EPOLL` environment variable.

```
$ python -m virtualenv --python=python3.6 venv
$ venv/bin/python -m pip install grpcio google-auth requests
$ venv/bin/python -m pip show grpcio
Name: grpcio
Version: 1.8.2
...
$ venv/bin/python
```
```python
>>> target = 'pubsub.googleapis.com:443'
>>> scopes = ('https://www.googleapis.com/auth/pubsub',),
>>> 
>>> import google.auth
>>> credentials, _ = google.auth.default(scopes=scopes)
>>> 
>>> import google.auth.transport.requests
>>> request = google.auth.transport.requests.Request()
>>> 
>>> import google.auth.transport.grpc
>>> metadata_plugin = google.auth.transport.grpc.AuthMetadataPlugin(
...     credentials, request)
>>> 
>>> import grpc
>>> google_auth_credentials = grpc.metadata_call_credentials(metadata_plugin)
>>> ssl_credentials = grpc.ssl_channel_credentials()
>>> composite_credentials = grpc.composite_channel_credentials(
...     ssl_credentials, google_auth_credentials)
>>> 
>>> # Now the logging message happens
... 
>>> channel = grpc.secure_channel(target, composite_credentials)
E1221 08:57:47.373061113   18747 ev_epollex_linux.cc:1482]   Skipping epollex becuase GRPC_LINUX_EPOLL is not defined.
E1221 08:57:47.373136726   18747 ev_epoll1_linux.cc:1261]    Skipping epoll1 becuase GRPC_LINUX_EPOLL is not defined.
E1221 08:57:47.373148066   18747 ev_epollsig_linux.cc:1761]  Skipping epollsig becuase GRPC_LINUX_EPOLL is not defined.
```

**Comment by mehrdada** [comment] 2017-12-21 21:21
@kpayson64 bug reports like this have been out since after 1.8.2. Might it be related to the recent changes you made?

@dhermes can you please let us know if you can reproduce the issue on 1.8.1 as well?

**Comment by dhermes** [comment] 2017-12-21 22:33
@mehrdada Sure thing. Using this script

```python
# issue_13855.py
import google.auth
import google.auth.transport.requests
import google.auth.transport.grpc
import grpc


def main():
    target = 'pubsub.googleapis.com:443'
    scopes = ('https://www.googleapis.com/auth/pubsub',),

    credentials, _ = google.auth.default(scopes=scopes)

    request = google.auth.transport.requests.Request()

    metadata_plugin = google.auth.transport.grpc.AuthMetadataPlugin(
        credentials, request)

    google_auth_credentials = grpc.metadata_call_credentials(metadata_plugin)
    ssl_credentials = grpc.ssl_channel_credentials()
    composite_credentials = grpc.composite_channel_credentials(
        ssl_credentials, google_auth_credentials)

    print('This should print before the logging.')
    channel = grpc.secure_channel(target, composite_credentials)


if __name__ == '__main__':
    main()
```

we see

## `1.8.0rc3`

```
$ python -m virtualenv --python=python3.6 venv-1.8.0
$ venv-1.8.0/bin/python -m pip install google-auth requests 'grpcio==1.8.0rc3'
$ venv-1.8.0/bin/python -m pip show grpcio
Name: grpcio
Version: 1.8.0rc3
...
$
$ venv-1.8.0/bin/python issue_13855.py
This should print before the logging.
E1221 14:30:52.024822376   13743 ev_epollex_linux.cc:1482]   Skipping epollex becuase GRPC_LINUX_EPOLL is not defined.
E1221 14:30:52.024841084   13743 ev_epoll1_linux.cc:1261]    Skipping epoll1 becuase GRPC_LINUX_EPOLL is not defined.
E1221 14:30:52.024853634   13743 ev_epollsig_linux.cc:1761]  Skipping epollsig becuase GRPC_LINUX_EPOLL is not defined.
```

## `1.8.1`

```
$ python -m virtualenv --python=python3.6 venv-1.8.1
$ venv-1.8.1/bin/python -m pip install google-auth requests 'grpcio==1.8.1'
$ venv-1.8.1/bin/python -m pip show grpcio
Name: grpcio
Version: 1.8.1
...
$
$ venv-1.8.1/bin/python issue_13855.py
This should print before the logging.
E1221 14:31:05.090153340   13849 ev_epollex_linux.cc:1482]   Skipping epollex becuase GRPC_LINUX_EPOLL is not defined.
E1221 14:31:05.090172585   13849 ev_epoll1_linux.cc:1261]    Skipping epoll1 becuase GRPC_LINUX_EPOLL is not defined.
E1221 14:31:05.090178939   13849 ev_epollsig_linux.cc:1761]  Skipping epollsig becuase GRPC_LINUX_EPOLL is not defined.
```

## `1.8.2`

```
$ python -m virtualenv --python=python3.6 venv-1.8.2
$ venv-1.8.2/bin/python -m pip install google-auth requests 'grpcio==1.8.2'
$ venv-1.8.2/bin/python -m pip show grpcio
Name: grpcio
Version: 1.8.2
...
$
$ venv-1.8.2/bin/python issue_13855.py
This should print before the logging.
E1221 14:31:13.943248602   13928 ev_epollex_linux.cc:1482]   Skipping epollex becuase GRPC_LINUX_EPOLL is not defined.
E1221 14:31:13.943281788   13928 ev_epoll1_linux.cc:1261]    Skipping epoll1 becuase GRPC_LINUX_EPOLL is not defined.
E1221 14:31:13.943291746   13928 ev_epollsig_linux.cc:1761]  Skipping epollsig becuase GRPC_LINUX_EPOLL is not defined.
```

**Comment by mehrdada** [comment] 2017-12-21 22:35
@dhermes  Thanks! The concentration of recent reports with 1.8.2 made me think they might be related, but it seems to have been a coincidence then.

**Comment by jaingaurav** [comment] 2017-12-28 12:52
@mehrdada: I believe https://github.com/grpc/grpc/pull/13281 introduced this new log message. It seems like the log level should be debug rather than error

**Comment by jaingaurav** [comment] 2018-01-02 17:37
@mehrdada: Thank you for the fix and putting out a new release. Could you please update the grpcio packages on pypi as well?

**Comment by mehrdada** [comment] 2018-01-02 17:50
I have yet to build the 1.8.3 on our build servers. There seems to be an infrastructure problem that we need to resolve before we can build the packages the proper way. Please stay tuned.

**Comment by mehrdada** [comment] 2018-01-03 00:32
1.8.3 has been published on PyPI. Closing. Please let me know if the issue persists.

**Closed by mehrdada** 2018-01-03 00:32 UTC
Labels: kind/bug, lang/Python

**Comment by jaingaurav** [comment] 2018-01-03 05:51
Thanks, @mehrdada. Tested and everything works great!
