### ISSUE TITLE
Lockfree stack bug exposed in Ruby tests

### ISSUE THREAD

**Issue by murgatroid99** [grpc/grpc#2550] opened 2015-07-20 21:39 UTC
The relevant information I have right now is the following stacktrace:

```
/usr/local/google/home/mlumish/.rvm/rubies/ruby-2.1.5/bin/../lib/libruby.so.2.1(+0x1e29ec) [0x7fb1136a19ec] vm_dump.c:690
/usr/local/google/home/mlumish/.rvm/rubies/ruby-2.1.5/bin/../lib/libruby.so.2.1(+0x77533) [0x7fb113536533] error.c:312
/usr/local/google/home/mlumish/.rvm/rubies/ruby-2.1.5/bin/../lib/libruby.so.2.1(rb_bug+0xb3) [0x7fb113537183] error.c:339
/usr/local/google/home/mlumish/.rvm/rubies/ruby-2.1.5/bin/../lib/libruby.so.2.1(+0x15a2ef) [0x7fb1136192ef] signal.c:812
/lib/x86_64-linux-gnu/libc.so.6(+0x36d40) [0x7fb113130d40] array.c:814
/usr/local/lib/libgpr.so.0(gpr_stack_lockfree_push+0x15) [0x7fb10cf9d255] ../../../../ext/grpc/rb_call.c:515
/usr/local/lib/libgrpc.so.0(grpc_completion_queue_pluck+0xe8) [0x7fb10d212068] enum.c:2440
/usr/local/google/home/mlumish/grpc/src/ruby/lib/grpc/grpc.so(+0x45f8) [0x7fb10d61a5f8] ../../../../ext/grpc/rb_completion_queue.c:66
/usr/local/google/home/mlumish/.rvm/rubies/ruby-2.1.5/bin/../lib/libruby.so.2.1(rb_thread_call_without_gvl+0x42) [0x7fb1136b0472] thread.c:1266
/usr/local/google/home/mlumish/grpc/src/ruby/lib/grpc/grpc.so(grpc_rb_completion_queue_pluck_event+0x8d) [0x7fb10d61a7bd] ../../../../ext/grpc/rb_completion_queue.c:157
/usr/local/google/home/mlumish/grpc/src/ruby/lib/grpc/grpc.so(+0x6090) [0x7fb10d61c090] ../../../../ext/grpc/rb_server.c:236
/usr/local/google/home/mlumish/.rvm/rubies/ruby-2.1.5/bin/../lib/libruby.so.2.1(+0x1cbd04) [0x7fb11368ad04] vm_insnhelper.c:1489
/usr/local/google/home/mlumish/.rvm/rubies/ruby-2.1.5/bin/../lib/libruby.so.2.1(+0x1d09c4) [0x7fb11368f9c4] insns.def:1028
/usr/local/google/home/mlumish/.rvm/rubies/ruby-2.1.5/bin/../lib/libruby.so.2.1(+0x1d462f) [0x7fb11369362f] vm.c:1398
/usr/local/google/home/mlumish/.rvm/rubies/ruby-2.1.5/bin/../lib/libruby.so.2.1(+0x1d7aea) [0x7fb113696aea] vm.c:817
/usr/local/google/home/mlumish/.rvm/rubies/ruby-2.1.5/bin/../lib/libruby.so.2.1(+0x1d82cb) [0x7fb1136972cb] vm.c:881
/usr/local/google/home/mlumish/.rvm/rubies/ruby-2.1.5/bin/../lib/libruby.so.2.1(+0x1d837a) [0x7fb11369737a] vm.c:900
/usr/local/google/home/mlumish/.rvm/rubies/ruby-2.1.5/bin/../lib/libruby.so.2.1(+0x871e0) [0x7fb1135461e0] proc.c:713
/usr/local/google/home/mlumish/.rvm/rubies/ruby-2.1.5/bin/../lib/libruby.so.2.1(+0x1cbd04) [0x7fb11368ad04] vm_insnhelper.c:1489
/usr/local/google/home/mlumish/.rvm/rubies/ruby-2.1.5/bin/../lib/libruby.so.2.1(+0x1d1305) [0x7fb113690305] insns.def:999
/usr/local/google/home/mlumish/.rvm/rubies/ruby-2.1.5/bin/../lib/libruby.so.2.1(+0x1d462f) [0x7fb11369362f] vm.c:1398
/usr/local/google/home/mlumish/.rvm/rubies/ruby-2.1.5/bin/../lib/libruby.so.2.1(+0x1d7aea) [0x7fb113696aea] vm.c:817
/usr/local/google/home/mlumish/.rvm/rubies/ruby-2.1.5/bin/../lib/libruby.so.2.1(+0x1d82cb) [0x7fb1136972cb] vm.c:881
/usr/local/google/home/mlumish/.rvm/rubies/ruby-2.1.5/bin/../lib/libruby.so.2.1(+0x1d837a) [0x7fb11369737a] vm.c:900
/usr/local/google/home/mlumish/.rvm/rubies/ruby-2.1.5/bin/../lib/libruby.so.2.1(+0x1ee0e0) [0x7fb1136ad0e0] thread.c:535
/usr/local/google/home/mlumish/.rvm/rubies/ruby-2.1.5/bin/../lib/libruby.so.2.1(+0x1ee54b) [0x7fb1136ad54b] thread_pthread.c:803
/lib/x86_64-linux-gnu/libpthread.so.0(+0x8182) [0x7fb112ee4182] /usr/local/google/home/mlumish/.rvm/rubies/ruby-2.1.5/include/ruby-2.1.0/ruby/ruby.h:1304
/lib/x86_64-linux-gnu/libc.so.6(clone+0x6d) [0x7fb1131f447d] parse.y:10331
```

**Comment by vjpai** [comment] 2015-07-21 18:15
I am looking into debugging this based on a conversation that Craig and I had. The issue is likely a bad use of the lock-free stack and we can debug that.

**Comment by ctiller** [comment] 2015-07-21 19:58
Reassigning since @vjpai admitted he's looking into this :)

**Closed** 2015-07-31 18:48 UTC
Labels: c
