### ISSUE TITLE
False warning when cancelling via CancellationToken

### ISSUE THREAD

**Issue by Donis-** [grpc/grpc#21390] opened 2019-12-05 13:48 UTC
### What version of gRPC and what language are you using?
C#
Nuget: Grpc.Core 2.25.0 (through protobuf-net.Grpc 1.0.13)

### What operating system (Linux, Windows,...) and version?
Windows 10
Version	10.0.18363 Build 18363

### What runtime / compiler are you using (e.g. python version or version of gcc)
Visual Studio 2019, .Net 4.8

### What did you do?
If possible, provide a recipe for reproducing the error. Try being specific and include code snippets if helpful.
Cancelling ServerStreaming RPC via a cancellation token from the client side.

Cancellation seems to be passed on to the server and disposed gets a true value in AsyncCallBase.cs via:
```
AsyncCallBase<IReadOnlyList<ProtocolHandlerSnapshot>, Tuple<string, string>>.ReleaseResources() in Grpc.Core.Internal, Grpc.Core.dll
AsyncCallBase<IReadOnlyList<ProtocolHandlerSnapshot>, Tuple<string, string>>.ReleaseResourcesIfPossible() in Grpc.Core.Internal, Grpc.Core.dll
AsyncCallServer<Tuple<string, string>, IReadOnlyList<ProtocolHandlerSnapshot>>.HandleFinishedServerside() in Grpc.Core.Internal, Grpc.Core.dll
AsyncCallServer<Tuple<string, string>, IReadOnlyList<ProtocolHandlerSnapshot>>.Grpc.Core.Internal.IReceivedCloseOnServerCallback.OnReceivedCloseOnServer() in Grpc.Core.Internal, Grpc.Core.dll
CallSafeHandle.<>c.<.cctor>b__33_6() in Grpc.Core.Internal, Grpc.Core.dll
BatchContextSafeHandle.Grpc.Core.Internal.IOpCompletionCallback.OnComplete() in Grpc.Core.Internal, Grpc.Core.dll
GrpcThreadPool.RunCompletionQueueEventCallback() in Grpc.Core.Internal, Grpc.Core.dll
GrpcThreadPool.<.ctor>b__15_0() in Grpc.Core.Internal, Grpc.Core.dll
QueueUserWorkItemCallback.WaitCallback_Context() in System.Threading, mscorlib.dll
ExecutionContext.RunInternal() in System.Threading, mscorlib.dll
ExecutionContext.Run() in System.Threading, mscorlib.dll
QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem() in System.Threading, mscorlib.dll
ThreadPoolWorkQueue.Dispatch() in System.Threading, mscorlib.dll
_ThreadPoolWaitCallback.PerformWaitCallback() in System.Threading, mscorlib.dll
[Native to Managed Transition]
[Application Domain Transition]
[Native to Managed Transition]
```

After disposed is set to true, the cancellation is passed on to the call site via AsyncCallServer.cs:234, the call site respects the token and finishes the call, but when 
```
ServerCallHandler.cs:142
await asyncCall.SendStatusFromServerAsync(status, context.ResponseTrailers, null).ConfigureAwait(false);
```
Is invoked in it throws on:
```
AsyncCallServer.cs:140
GrpcPreconditions.CheckState(!disposed);
```

Would it make sense to avoid calling AsyncCallServer.cs:234 if the operation was already cancelled?

### What did you expect to see?
No warnings when using cancellation.

### What did you see instead?
Warning from:
Server.cs:350
Logger.Warning(e, "Exception while handling RPC.");

```
System.InvalidOperationException: Operation is not valid due to the current state of the object.
   at Grpc.Core.Utils.GrpcPreconditions.CheckState(Boolean condition) in T:\src\github\grpc\src\csharp\Grpc.Core.Api\Utils\GrpcPreconditions.cs:line 90
   at Grpc.Core.Internal.AsyncCallServer`2.SendStatusFromServerAsync(Status status, Metadata trailers, Nullable`1 optionalWrite) in T:\src\github\grpc\src\csharp\Grpc.Core\Internal\AsyncCallServer.cs:line 141
   at Grpc.Core.Internal.ServerStreamingServerCallHandler`2.<HandleCall>d__4.MoveNext() in T:\src\github\grpc\src\csharp\Grpc.Core\Internal\ServerCallHandler.cs:line 147
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
   at Grpc.Core.Server.<HandleCallAsync>d__39.MoveNext() in T:\src\github\grpc\src\csharp\Grpc.Core\Server.cs:line 347
```

### Anything else we should know about your project / environment?
Nothing special.

**Comment by jtattermusch** [comment] 2019-12-13 14:25
I think your analysis is mostly correct, the issue itself is actually a duplicate of https://github.com/grpc/grpc/issues/13943.

**Closed by jtattermusch** 2019-12-13 14:25 UTC
Labels: kind/bug, lang/C#, priority/P2
