### ISSUE TITLE
nodejs method call expiration error with a desired timeout

### ISSUE THREAD

**Issue by Zerqkboo** [grpc/grpc#4573] opened 2015-12-24 10:12 UTC
Hi, when I used a grpc method to send message without any expiration setting, I can send it successfully. But It raised an error when I passed a deadline to the method. The codes like this:
```javascript
// var deadline = Infinity;    // when deadline is Infinity, the process is ok.
var deadline = new Date();
deadline.setSeconds(deadline.getSeconds() + 100000);

// stub is a grpc stub, and sendMessage is a method
stub.sendMessage(msg, function(error, status){    
    if(error) {
        console.log(error);
    }
    else {
        console.log('Send message successfully.');
    }
}, null, {deadline});
```
The immediate result is:
```
{ [Error: Deadline Exceeded] code: 4, metadata: Metadata { _internal_repr: {} } }
```

Do I make a mistake in using the method?

My environment is: win10, node v5.1.1, grpc 0_11_1

Thank u!

**Comment by murgatroid99** [comment] 2016-01-23 00:24
I suspect that this problem is caused by #4852 (specifically, I understand that `long` is 32 bits on Windows).

As a side note, would you mind telling me how you got the package to build on Windows? I have not yet managed to do that.

**Comment by Zerqkboo** [comment] 2016-01-25 04:10
@murgatroid99

Yes, it's not easy to build on windows. I did some hacks to make it. And all I did are belows:

1) Build grpc core using files under `grpc-release-0_11_1\vsprojects`
2) Modify `grpc-release-0_11_1\src\node\binding.gyp`:
```
{
  "targets" : [
    {
      'include_dirs': [
        "<!(node -e \"require('nan')\")",
		'../../include'
      ],
      'cflags': [
        '-std=c++0x',
        '-Wall',
        #'-pthread',
        '-g',
        '-zdefs',
        '-Werror',
        '-Wno-error=deprecated-declarations'
      ],
	  'defines': [
        'WIN32_LEAN_AND_MEAN'
       ],
      'configurations':{
        'Release':{
            'msvs_settings': {
                'VCCLCompilerTool': {
                    'RuntimeLibrary': '2', # multi threaded DLL
                },
            },
        },
      },
      'ldflags': [
        '-g'
      ],
	  'link_settings': {
        'libraries': [
        #  '-lpthread',
          '-lgrpc',
          '-lgpr',
          '-llibeay32',
          '-lssleay32',
          '-lzlib',
          '-lws2_32'
        ],
        'library_dirs': [
           '../../vsprojects/Release-DLL/',
           '../../vsprojects/packages/grpc.dependencies.openssl.1.0.2.3/build/native/lib/v120/Win32/Release/dynamic',
           '../../vsprojects/packages/grpc.dependencies.zlib.1.2.8.9/build/native/lib/v120/Win32/Release/dynamic/cdecl'
        ]
      },
      "conditions": [
        ['OS != "win"', {
          'variables': {
            'pkg_config_grpc': '<!(pkg-config --exists grpc >/dev/null 2>&1 && echo true || echo false)'
          },
          'conditions': [
            ['pkg_config_grpc == "true"', {
              'link_settings': {
                'libraries': [
                  '<!@(pkg-config --libs-only-l --static grpc)'
                ]
              },
              'cflags': [
                '<!@(pkg-config --cflags grpc)'
              ],
              'libraries': [
                '<!@(pkg-config --libs-only-L --static grpc)'
              ],
              'ldflags': [
                '<!@(pkg-config --libs-only-other --static grpc)'
              ]
              }, {
                'link_settings': {
                  'libraries': [
                    '-lpthread',
                    '-lgrpc',
                    '-lgpr'
                  ],
                },
                'conditions':[
                  ['OS != "mac"', {
                    'link_settings': {
                      'libraries': [
                        '-lrt'
                      ]
                    }
                  }]
                ]
              }
           ]
          ]
        }],
        ['OS == "mac"', {
          'xcode_settings': {
            'MACOSX_DEPLOYMENT_TARGET': '10.9',
            'OTHER_CFLAGS': [
              '-std=c++11',
              '-stdlib=libc++'
            ]
          }
        }]
      ],
      "target_name": "grpc",
      "sources": [
        "ext/byte_buffer.cc",
        "ext/call.cc",
        "ext/channel.cc",
        "ext/completion_queue_async_worker.cc",
        "ext/credentials.cc",
        "ext/node_grpc.cc",
        "ext/server.cc",
        "ext/server_credentials.cc",
        "ext/timeval.cc"
      ]
    }
  ]
}
```
The differences between the new binding.gyp and the origin can be seen here: 
![Uploading 20160125115821.png…]()

3) Modify `grpc-release-0_11_1\src\node\ext\node_grpc.cc`, just add an undef at line 45:
```
#undef ERROR
```

4) build it:
```
cd grpc-release-0_11_1\src\node
npm install
```
Then the results are under `grpc-release-0_11_1\src\node\build\Release`. And copy `zlib.dll, libeay32.dll, ssleay32.dll` to make them together with `grpc.node`, the package then is usable.

ps: my environments are: win10, vs2013, node 5.1.1

**Comment by murgatroid99** [comment] 2016-02-16 23:30
gRPC has been updated to work on Windows, so you can now just install it with `npm install grpc` without any modification. I believe that other changes I made should fix this problem. Can you check?

**Comment by Zerqkboo** [comment] 2016-02-19 03:02
@murgatroid99 Thanks. I think it has been fixed. Using grpc through npm is really cool. :)

**Comment by murgatroid99** [comment] 2016-02-19 03:10
Good. I'll close it for now. We can reopen if this comes up again.

**Closed by murgatroid99** 2016-02-19 03:10 UTC
Labels: node
