### ISSUE TITLE
Server code crashes when streaming to client that has disappeared

### ISSUE THREAD

**Issue by vjpai** [grpc/grpc#999] opened 2015-03-10 21:21 UTC
Imported from grpc-io , reported by Andrey Myznikov

The line preventing me from using application is in `grpc/src/server/server.cc:278` ( in function `void Server::PerformOpsOnCall()`)

```
 assertion failed:GRPC_CALL_OK == grpc_call_start_batch(call->call(), ops, nops, buf)
```

The example how to get this abort(): 
    I create clent and server pair, start server, start client,  then at client side begin receive stream of messages from server, and at some point manually kill the client (pressing Ctrl+C or by any other mean).
I expect to get some kind of error code at server side, but server just craches instead :( .

Sample code from Andrey 

The sample code to reproduce the problem:

/////////////////
// test.proto

```protobuf
syntax = "proto3";

package tester;

service Test {
  rpc ReadEvents (ReadEventsRequest) returns (stream TestEvent) {}
}

message ReadEventsRequest {
}

message TestEvent {
  string event_name = 1;
}
```

///////////////////////////
// client.cc

```c++
int main()
{
  grpc_init();

  TestEvent e;
  ClientContext context;

  unique_ptr<Test::Stub> tester(
      Test::NewStub(CreateChannel("localhost:7000", InsecureCredentials(), ChannelArguments())));

  unique_ptr<ClientReader<TestEvent>> rd =
        tester->ReadEvents(&context, ReadEventsRequest());

  printf("begin read\n");
  while ( rd->Read(&e) ) {
    printf("event: %s\n", e.event_name().c_str());
  }
  printf("end read\n");

  rd->Finish();

  grpc_shutdown();
  return 0;
}
```

///////////////////////
// server.cc

```c++
class TestService
  : public Test::Service
{
  unique_ptr<Server> server_;

public:

  TestService(const string & address) {
    ServerBuilder builder;
    builder.AddPort(address, InsecureServerCredentials());
    builder.RegisterService(this);
    server_ = builder.BuildAndStart();
  }

  void run() {
    server_->Wait();
  }

private:
  Status ReadEvents(ServerContext* context, const ReadEventsRequest* request, ServerWriter< TestEvent>* writer)
  {
    TestEvent e;
    char line[256];

    (void)(context); // unused
    (void)(request); // unused

    while ( fgets(line, sizeof(line) - 1, stdin) && strncmp(line, "quit", 4) != 0 ) {
      e.set_event_name(line);
      if ( !writer->Write(e) ) {
        fprintf(stderr,"leave\n");
        break;
      }
    }
    return Status::OK;
  }
};

int main()
{
  grpc_init();

  TestService service("localhost:7000");
  service.run();

  grpc_shutdown();

  return 0;
}
```

**Comment by ctiller** [comment] 2015-03-10 21:49
Just wanted to note that the assert here is wholly appropriate. The fact that it triggers is most likely a bug in the C++ wrapping layer, or possibly a bug in surface/call.c (less likely). The contact between core and wrappers is that wrappers should never do anything that causes an error to be returned from start batch.

**Comment by vjpai** [comment] 2015-03-10 22:38
I agree - the assert looks good. The problem is that we are even entering this code, just like the problem was in PR #920 . The failure is even taking place at the same point, so I'm pretty sure that this is just the synchronous streaming version of that. It just needs to be reproduced and fed to a stack trace.

**Comment by amyznikov** [comment] 2015-03-11 12:44
My unpretentious suggestion is that somewhere in the code there should be some checks if requested operation could be performed at all, and return error code (or just 'false' at worst resort) if operation can't be completed.
Unfortunately I am not familiar enough with low-level grpc API, but I expect that low-level API could provide information about it's current state to the high-level wrappers. Especially, I think that low level api MUST detect that client disappear, and there MUST be a way to inform application with loud error code about this.

**Comment by ctiller** [comment] 2015-03-11 22:50
So the error reporting mechanism in the core library is two fold:
- API misuse is reported via grpc_call_error codes as return values from functions such as grpc_call_send_batch - these failures indicate API misuse, which typically results from broken invariants in higher level code. We should _NEVER_ see these. Ordinarily we'd make these asserts in the C code, but for languages such as Python which have their own runtime exceptions, we want to translate these to them.
- Runtime errors - things such as trying to send on a disconnected channel - are reported via grpc_op_errors as part of the completion event for each queued operation. These are the error codes you're wondering about Andrey.

What I think is happening is we're somehow misclassifying an error condition and not reporting it up from surface/call.c in the correct fashion, leading to this assert.

**Comment by amyznikov** [comment] 2015-03-11 23:03
Ctiller, 
  yes, you right - looking into C++ code path originated from writer->Write(e) I do not see clearly checks for Runtime errors or for state of the call obect  before calling grpc_call_send_batch(). Actually the c++ code tries to send next chunk of data with no checking if call  is in appropriate state.

**Comment by amyznikov** [comment] 2015-03-15 23:50
The bug is originated from  line /grpc/src/core/surface/call.c:998
static void finish_batch(grpc_call *call, grpc_op_error result, void *tag) {
  grpc_cq_end_op_complete(call->cq, tag, call, do_nothing, NULL, GRPC_OP_OK);
}

The finish_batch() parameter 'result' comming from transport layer is ignored here, and queue completion status is always set to GRPC_OP_OK. This gives no way to get know for C++ high level code about error and return 'false' from writer->Write(). Passing 'result' into grpc_cq_end_op_complete() instead of GRPC_OP_OK solves problem with returning 'false' from writer->Write(), and loop finishes fine. 

But unfortunatelly this fix leads to next error in server.cc:143 after finishing loop : 
assertion failed: cq_.Pluck(&buf).
It is because of cq_.Pluck(&buf) returns 'false' and GPR_ASSERT(cq_.Pluck(&buf)) aborts server. 
Removing GPR_ASSERT() solves my problem with server crashing when client disappears.


So, I suggest that cq_.Pluck() CAN return 'false' on RUN-TIME errors. The C++ code MUST NOT abort or crash on RUN-TIME errors

**Comment by maxhawkins** [comment] 2015-04-05 06:25
Any updates on this issue? I'm still hitting that assert when I disconnect.

**Comment by larsonmpdx** [comment] 2015-05-14 20:36
I get this with a windows server but not a linux server

**Comment by amyznikov** [comment] 2015-05-14 21:29
It craches on linux too. In recent versions of code they changed the finish_batch() body passing '1' as result code, meaning 'success' always, independently on real deals: 
grpc/src/core/surface/call.c:1177  
static void finish_batch(grpc_call *call, int success, void *tag) {
  grpc_cq_end_op(call->cq, tag, call, 1);
}

As result, the writer->Write(e) never returns 'false'. And next call to Write() after grpc really detects tha client disappear leads to abort:
-----------------------------
amyznikov@jup:/home/projects/libgrpc/test/cpp/stream-test$ ./client 
begin read
event: event #1
event: event #2
event: event #3
event: event #4
event: event #5
^C
--------------------------------------
amyznikov@jup:/home/projects/libgrpc/test/cpp/stream-test$ ./server 
sending 'event #1'
sending 'event #2'
sending 'event #3'
sending 'event #4'
sending 'event #5'
sending 'event #6'
sending 'event #7'
E0515 00:28:56.882221147    1356 server.cc:312] assertion failed: GRPC_CALL_OK == grpc_call_start_batch(call->call(), ops, nops, buf)
Aborted (core dumped)
-----------------------------------------------------

It looks like intended behaviour - may be they use this for testing purposes. I don't know.

**Comment by ctiller** [comment] 2015-05-14 23:28
Looks like my fault. Will look tomorrow.

**Comment by amyznikov** [comment] 2015-05-19 14:57
Just tested the changes from https://github.com/grpc/grpc/pull/1625 - Server still crashes.

See my tester code on repo https://github.com/amyznikov/grpc-stream-tester.

**Comment by ctiller** [comment] 2015-05-19 16:29
Hey - thanks for the test code. I'm going to try and reproduce it as a self-running test, and fix from there.

**Comment by amyznikov** [comment] 2015-05-19 16:50
I can be easy to fix with two litle code changes mentioned in my early posts : finish_batch() and GPR_ASSERT(cq_.Pluck(&buf)).
I made this fix in my local branch used for my applications. 
But I preffer to get it working in mainstream code.

**Comment by ctiller** [comment] 2015-05-19 17:18
Yeah - I'm not sure it's the right fix. I can reproduce it here... testing
out a more complete fix. Going to need to work with the node folks to get
some bugs there fixed before this can be merged though.

**Comment by ctiller** [comment] 2015-05-19 17:45
Ok, reproduced and fixed. #1625 has been updated reflecting this (with a test that'll become part of our suite for every future commit).

**Comment by amyznikov** [comment] 2015-05-19 18:26
Confirm: recent code from ctiller's mmm-mmm-mmm-mmm branch fixes the crash.

**Closed** 2015-05-25 18:51 UTC
