### ISSUE TITLE
C++ Reference for ServerContextBase Missing from Documentation Website

### ISSUE THREAD

**Issue by AnthonyWharton** [grpc/grpc#22361] opened 2020-03-16 16:44 UTC
Please note that [I was asked to move this issue from the grpc.io respository (issue 105).](https://github.com/grpc/grpc.io/issues/105), so this is a copy from there with a few clarification edits.

**Describe the bug**
The following link in the public C++ documentation is broken: https://grpc.github.io/grpc/cpp/classgrpc__impl_1_1_server_context_base.html

**To Reproduce**
Go to: https://grpc.github.io/grpc/cpp/classgrpc__impl_1_1_server_context_base.html
Recieve a 404.

**Expected behavior**
The `ServerContextBase` documentation loads.

**Screenshots**
![image](https://user-images.githubusercontent.com/7091722/75679424-803c5780-5c87-11ea-8378-ef6acb96ac5b.png)

**Additional context**
It seems this page is being missed by Doxygen, or has not been transfered to the site.

An example page that contains the broken link is the documentation for [`ServerContext`](https://grpc.github.io/grpc/cpp/classgrpc__impl_1_1_server_context.html), which inherits from `ServerContextBase`.

**Comment by veblush** [comment] 2020-05-05 18:10
Closed this issue since I confirmed that the link is working now.

![Screenshot from 2020-05-05 11-09-06](https://user-images.githubusercontent.com/2793282/81100182-f5631d80-8ec0-11ea-91ab-057aeaee8d24.png)

**Closed by veblush** 2020-05-05 18:10 UTC
Labels: kind/bug, priority/P2
