### ISSUE TITLE
Trailer / Trailing metadata is not supported by web browsers

### ISSUE THREAD

**Issue by zayoo** [grpc/grpc#2786] opened 2015-08-04 20:46 UTC
No known web browser supports trailing metadata, although it seems to be natural to send trailer over HTTP/2. Chrome crashes the webpage when a header/trailer arrives after data frame. This is the only obstacle preventing us from sending gRPC calls with JavaScript in Chrome now.

I have successfully made gRPC calls with JavaScript in a patched version of gRPC (removing grpc-status and the trailer), but it breaks those applications that require grpc-status.

Possible solutions:
1. Move grpc-status to the header and eliminate the trailer, if functionally possible;
2. Do not send trailer if the client didn't send "te: trailer"; or
3. Ask Chromium and Chrome to support (or at least ignore instead of crash) trailer in HTTP/2.

**Comment by joelchen** [comment] 2015-08-05 05:04
Nice work on getting gRPC almost supported in Chrome. Would like to see gRPC supported in all major browsers. Do other browsers crash with your JavaScript?

**Comment by jcanizales** [comment] 2015-08-05 16:48
CC: @louiscryan

**Comment by zayoo** [comment] 2015-08-05 21:26
Chrome 44: Trailer causes ERR_SPDY_PROTOCOL_ERROR. JavaScript gRPC call currently requires removing the trailer.
Firefox 39: Works fine without problem.
Opera 31: Trailer causes some strange problem that is not investigated yet. JavaScript gRPC call currently requires removing the trailer.

Other browsers are not tested yet, but only browsers supporting HTTP/2 can potentially support JavaScript gRPC.

**Comment by alexander-yevsyukov** [comment] 2015-10-23 17:50
[Chromium team says](https://code.google.com/p/chromium/issues/detail?id=33325): “No plans to implement this”, and the issue is in the Archived status.

**Comment by AlexanderLitus** [comment] 2015-10-26 07:57
Chromium team currently have [issue "Implement HTTP/2 trailers"](https://code.google.com/p/chromium/issues/detail?id=422958) (in "Assigned" status).

**Comment by AlexanderLitus** [comment] 2015-10-27 09:44
Firefox team [says](https://support.mozilla.org/en-US/questions/1090654): "...apparently trailers are not supported right now in firefox (or rather silently discarded)...".

**Comment by zj8487** [comment] 2016-04-03 10:52
@zayoo 
Do you use your hacked GRPC with JavaScript now? and if it is possible, may you give me more detail on it?

**Comment by joeblew99** [comment] 2016-04-11 14:21
@zayoo 
Trailer support was fixed in Chrome 2 days ago :)
https://bugs.chromium.org/p/chromium/issues/detail?id=422958

Worth giving this another go..

**Closed** 2016-04-21 23:31 UTC
Labels: to close

**Comment by joeblew99** [comment] 2016-04-22 06:42
How to test ? I mean in the browser ( its in canary i guess only ?)

**Comment by IceMan81** [comment] 2016-07-06 21:45
@joeblew99 @nicolasnoble How did you test this in the browser?

**Comment by rleonhardt** [comment] 2016-08-23 07:41
Can somebody start a JavaScript client now in order to test which environments work and to file proper bug reports to browser developers?
Chromium (Desktop), WebView (Android), Safari / WebKit (iOS), Firefox ([Necko](https://support.mozilla.org/de/questions/1090654) library)

**Comment by louiscryan** [comment] 2016-11-08 20:26
Folks please review

https://github.com/grpc/grpc/issues/8682
