### ISSUE TITLE
UNAUTHENTICATED errors against Cloud Spanner emulator in v1.45.0

### ISSUE THREAD

**Issue by taka-oyama** [grpc/grpc#29233] opened 2022-03-28 04:48 UTC
We have seen this error before in v1.36 https://github.com/grpc/grpc/issues/25810

### What version of gRPC and what language are you using?

grpc v1.45.0
PHP

### What operating system (Linux, Windows,...) and version?

Alpine Linux

### What runtime / compiler are you using (e.g. python version or version of gcc)

PHP version: 8.0.17

### What did you do?

Update grpc from 1.44.0 to 1.45.0 and run it against Spanner Emulator.

### What did you expect to see?

No errors.

### What did you see instead?

```
Google\Cloud\Core\Exception\ServiceException: {
    "message": "Established channel does not have a sufficient security level to transfer call credential.",
    "code": 16,
    "status": "UNAUTHENTICATED",
    "details": []
}

/project/vendor/google/cloud-core/src/GrpcRequestWrapper.php:257
/project/vendor/google/cloud-core/src/GrpcRequestWrapper.php:146
/project/vendor/google/cloud-core/src/GrpcTrait.php:79
/project/vendor/google/cloud-spanner/src/Connection/Grpc.php:603
/project/vendor/google/cloud-spanner/src/Database.php:353
/project/vendor/google/cloud-spanner/src/Database.php:376
```

**Comment by PierrickVoulet** [comment] 2022-03-28 20:30
Same issue with https://github.com/googleads/google-ads-php as well.

**Comment by taka-oyama** [comment] 2022-04-05 06:45
Is anyone looking into this?

**Comment by stanley-cheung** [comment] 2022-04-05 21:22
@HannahShiSFB Can you please take a look?

**Comment by HannahShiSFB** [comment] 2022-04-05 22:50
Sure

**Comment by HannahShiSFB** [comment] 2022-04-13 23:56
This is caused by https://github.com/grpc/grpc/pull/25586 which removed insecure channel.

Regardless whether Spanner connects to emulator or production server, gax-php always create a CredentialsWrapper (https://github.com/googleapis/gax-php/blob/v1.12.0/src/GapicClientTrait.php#L434) and add it to callstack (https://github.com/googleapis/gax-php/blob/v1.12.0/src/GapicClientTrait.php#L610).
When creating gRPC calls, GrpcTransport calls CredentialsWrapper (https://github.com/googleapis/gax-php/blob/v1.12.0/src/Transport/GrpcTransport.php#L258-L259) to setup a callback for auth token, which requires secure level to be equal or higher than GRPC_PRIVACY_AND_INTEGRITY which doesn’t work on an insecure channel.

This PR uses an InsecureCredentialsWrapper which return null in getAuthorizationHeaderCallback so the credential callback will not be set, so this can work for emulator via an insecure channel.

**Comment by HannahShiSFB** [comment] 2022-04-14 00:05
@dennycd  @stanley-cheung I want to propose an easy fix of Spanner, but I can't fork https://github.com/googleapis/google-cloud-php and create a PR there. Could you help me with it? Thanks

**Comment by HannahShiSFB** [comment] 2022-04-14 15:15
> @HannahShiSFB I could probably help with it. Can you tell me what is the issue you're facing in creating a PR for `google-cloud-php` ?

Sure. I tried to fork the repo, but got a page said "No more forks can be created."

**Comment by HannahShiSFB** [comment] 2022-04-14 21:29
sorry for the confusing. It works now. I will create a PR right now

**Comment by PierrickVoulet** [comment] 2022-04-18 11:51
> sorry for the confusing. It works now. I will create a PR right now

@HannahShiSFB Could you provide the link to this PR?

**Comment by enumag** [comment] 2022-04-19 12:23
I'm getting the same error against firestore emulator as well. Is there any workaround I can use?

**Comment by enumag** [comment] 2022-04-19 12:38
Based on https://github.com/googleapis/google-cloud-php/issues/3911#issuecomment-1099226534 it seems the workaround is to downgrade grpc. It did solve the problem for me.

**Comment by HannahShiSFB** [comment] 2022-04-19 17:20
> @HannahShiSFB Could you provide the link to this PR?

Thx for waiting. It's https://github.com/googleapis/google-cloud-php/pull/5224

**Comment by dennycd** [comment] 2022-05-05 22:38
Closing the issue as it is fixed from cloud / spanner side.

**Closed by dennycd** 2022-05-05 22:38 UTC
Labels: kind/bug, lang/php, priority/P2
