### ISSUE TITLE
Setup.py libatomic checker doesn't take --root param into account

### ISSUE THREAD

**Issue by clementperon** [grpc/grpc#25362] opened 2021-02-05 16:57 UTC
Compiling the python package with Yocto create an error because aarch64-poky-linux-g++ is not found when running check_linker_need_libatomic().

This is due to the function take the correct CXX compiler but don't take into account the --root sysroot filesystem.

https://github.com/grpc/grpc/blob/master/setup.py#L175

**Comment by kacper-ka** [comment] 2022-02-14 13:33
I have stumbled upon a similar issue, also cross-compiling for a *Poky*-based custom distribution. However from what I have figured out the issue is caused by the fact that in *bitbake* environment `CXX` variable consists of not only the compiler (`arm-poky-linux-gnueabi-g++` in my case) but also several compiler flags: in my case full contents of `CXX` variable are:
```
arm-poky-linux-gnueabi-g++ -mthumb -mfpu=neon -mfloat-abi=hard -mcpu=cortex-a7 -fstack-protector-strong -O2 -D_FORTIFY_SOURCE=2 -Wformat -Wformat-security -Werror=format-security -Wdate-time --sysroot=<redacted>/build/tmp/work/cortexa7t2hf-neon-poky-linux-gnueabi/grpcio/1.43.0-r0/recipe-sysroot
```
The issue is directly caused by the mechanism of subprocess invocation in *Python*. [Here](setup.py#L204) the invocation fails, because the executable whose name is as `CXX` variable points is not found. That can be easily fixed by splitting the `CXX` variable and taking only the first element of the resulting array. Works for my case and the default as well.

**Closed** 2022-03-08 19:57 UTC
Labels: kind/bug, lang/Python, priority/P2
