### ISSUE TITLE
c++_linux_dbg.bins/dbg/json_run_localhost --scenarios_json '{"scenarios": [{"name": "cpp_protobuf_async_client_sync_server_streaming_qps_unconstrained_secure"

### ISSUE THREAD

**Issue by matt-kwong** [grpc/grpc#9150] opened 2016-12-16 22:19 UTC
Timeout in https://grpc-testing.appspot.com/job/gRPC_master_linux/802/

Details: https://grpc-testing.appspot.com/job/gRPC_master_linux/802/testReport/junit/(root)/c++_linux_dbg/bins_dbg_json_run_localhost___scenarios_json____scenarios______name____cpp_protobuf_async_client_sync_server_streaming_qps_unconstrained_secure____warmup_seconds___0___benchmark_seconds___1___num_servers___1___server_config_____async_server_threads___0___core_limit___0___security_params_____use_test_ca___true___server_host_override____foo_test_google_fr_____server_type____SYNC_SERVER_____num_clients___0___client_config_____client_type____ASYNC_CLIENT____security_params_____use_test_ca___true___server_host_override____foo_test_google_fr_____payload_config_____simple_params_____resp_size___0___req_size___0_____client_channels___64___async_client_threads___0___outstanding_rpcs_per_channel___100___rpc_type____STREAMING____load_params_____closed_loop_________histogram_params_____max_possible___60000000000_0___resolution___0_01_______GRPC_POLL_STRATEGY_poll_cv/

**Comment by jtattermusch** [comment] 2016-12-20 22:06
Seen again https://grpc-testing.appspot.com/job/gRPC_pull_requests_linux/1570/

**Comment by murgatroid99** [comment] 2017-01-03 18:45
Seen again https://grpc-testing.appspot.com/job/gRPC_master_linux/995/

**Comment by nathanielmanistaatgoogle** [comment] 2017-01-05 20:52
Seen again in `gRPC_master_linux`:

* [1006](https://grpc-testing.appspot.com/job/gRPC_master_linux/1006/testReport/junit/(root)/c++_linux_dbg/bins_dbg_json_run_localhost___scenarios_json____scenarios______name____cpp_protobuf_async_client_sync_server_streaming_qps_unconstrained_secure____warmup_seconds___0___benchmark_seconds___1___num_servers___1___server_config_____async_server_threads___0___core_limit___0___security_params_____use_test_ca___true___server_host_override____foo_test_google_fr_____server_type____SYNC_SERVER_____num_clients___0___client_config_____client_type____ASYNC_CLIENT____security_params_____use_test_ca___true___server_host_override____foo_test_google_fr_____payload_config_____simple_params_____resp_size___0___req_size___0_____client_channels___64___async_client_threads___0___outstanding_rpcs_per_channel___100___rpc_type____STREAMING____load_params_____closed_loop_________histogram_params_____max_possible___60000000000_0___resolution___0_01_______GRPC_POLL_STRATEGY_poll_cv/)
* [1011](https://grpc-testing.appspot.com/job/gRPC_master_linux/1011/testReport/junit/(root)/c++_linux_dbg/bins_dbg_json_run_localhost___scenarios_json____scenarios______name____cpp_protobuf_async_client_sync_server_streaming_qps_unconstrained_secure____warmup_seconds___0___benchmark_seconds___1___num_servers___1___server_config_____async_server_threads___0___core_limit___0___security_params_____use_test_ca___true___server_host_override____foo_test_google_fr_____server_type____SYNC_SERVER_____num_clients___0___client_config_____client_type____ASYNC_CLIENT____security_params_____use_test_ca___true___server_host_override____foo_test_google_fr_____payload_config_____simple_params_____resp_size___0___req_size___0_____client_channels___64___async_client_threads___0___outstanding_rpcs_per_channel___100___rpc_type____STREAMING____load_params_____closed_loop_________histogram_params_____max_possible___60000000000_0___resolution___0_01_______GRPC_POLL_STRATEGY_poll_cv/)
* [1012](https://grpc-testing.appspot.com/job/gRPC_master_linux/1012/testReport/junit/(root)/c++_linux_opt/bins_opt_json_run_localhost___scenarios_json____scenarios______name____cpp_protobuf_async_client_sync_server_streaming_qps_unconstrained_secure____warmup_seconds___0___benchmark_seconds___1___num_servers___1___server_config_____async_server_threads___0___core_limit___0___security_params_____use_test_ca___true___server_host_override____foo_test_google_fr_____server_type____SYNC_SERVER_____num_clients___0___client_config_____client_type____ASYNC_CLIENT____security_params_____use_test_ca___true___server_host_override____foo_test_google_fr_____payload_config_____simple_params_____resp_size___0___req_size___0_____client_channels___64___async_client_threads___0___outstanding_rpcs_per_channel___100___rpc_type____STREAMING____load_params_____closed_loop_________histogram_params_____max_possible___60000000000_0___resolution___0_01_______GRPC_POLL_STRATEGY_poll_cv/)
* [1013 (insecure rather than secure, but close enough, right?)](https://grpc-testing.appspot.com/job/gRPC_master_linux/1013/testReport/junit/(root)/c++_linux_dbg/bins_dbg_json_run_localhost___scenarios_json____scenarios______name____cpp_protobuf_async_client_sync_server_streaming_qps_unconstrained_insecure____warmup_seconds___0___benchmark_seconds___1___num_servers___1___server_config_____async_server_threads___0___core_limit___0___security_params___null___server_type____SYNC_SERVER_____num_clients___0___client_config_____client_type____ASYNC_CLIENT____security_params___null___payload_config_____simple_params_____resp_size___0___req_size___0_____client_channels___64___async_client_threads___0___outstanding_rpcs_per_channel___100___rpc_type____STREAMING____load_params_____closed_loop_________histogram_params_____max_possible___60000000000_0___resolution___0_01_______GRPC_POLL_STRATEGY_poll_cv/)
* [1017](https://grpc-testing.appspot.com/job/gRPC_master_linux/1017/testReport/junit/(root)/c++_linux_opt/bins_opt_json_run_localhost___scenarios_json____scenarios______name____cpp_protobuf_async_client_sync_server_streaming_qps_unconstrained_secure____warmup_seconds___0___benchmark_seconds___1___num_servers___1___server_config_____async_server_threads___0___core_limit___0___security_params_____use_test_ca___true___server_host_override____foo_test_google_fr_____server_type____SYNC_SERVER_____num_clients___0___client_config_____client_type____ASYNC_CLIENT____security_params_____use_test_ca___true___server_host_override____foo_test_google_fr_____payload_config_____simple_params_____resp_size___0___req_size___0_____client_channels___64___async_client_threads___0___outstanding_rpcs_per_channel___100___rpc_type____STREAMING____load_params_____closed_loop_________histogram_params_____max_possible___60000000000_0___resolution___0_01_______GRPC_POLL_STRATEGY_poll_cv/)
* 1018 (both [secure](https://grpc-testing.appspot.com/job/gRPC_master_linux/1018/testReport/junit/(root)/c++_linux_dbg/bins_dbg_json_run_localhost___scenarios_json____scenarios______name____cpp_protobuf_async_client_sync_server_streaming_qps_unconstrained_secure____warmup_seconds___0___benchmark_seconds___1___num_servers___1___server_config_____async_server_threads___0___core_limit___0___security_params_____use_test_ca___true___server_host_override____foo_test_google_fr_____server_type____SYNC_SERVER_____num_clients___0___client_config_____client_type____ASYNC_CLIENT____security_params_____use_test_ca___true___server_host_override____foo_test_google_fr_____payload_config_____simple_params_____resp_size___0___req_size___0_____client_channels___64___async_client_threads___0___outstanding_rpcs_per_channel___100___rpc_type____STREAMING____load_params_____closed_loop_________histogram_params_____max_possible___60000000000_0___resolution___0_01_______GRPC_POLL_STRATEGY_poll_cv/) and [insecure](https://grpc-testing.appspot.com/job/gRPC_master_linux/1018/testReport/junit/(root)/c++_linux_opt/bins_opt_json_run_localhost___scenarios_json____scenarios______name____cpp_protobuf_async_client_sync_server_streaming_qps_unconstrained_insecure____warmup_seconds___0___benchmark_seconds___1___num_servers___1___server_config_____async_server_threads___0___core_limit___0___security_params___null___server_type____SYNC_SERVER_____num_clients___0___client_config_____client_type____ASYNC_CLIENT____security_params___null___payload_config_____simple_params_____resp_size___0___req_size___0_____client_channels___64___async_client_threads___0___outstanding_rpcs_per_channel___100___rpc_type____STREAMING____load_params_____closed_loop_________histogram_params_____max_possible___60000000000_0___resolution___0_01_______GRPC_POLL_STRATEGY_poll_cv/))

**Comment by lyuxuan** [comment] 2017-01-12 06:32
#8770

**Comment by apolcyn** [comment] 2017-01-12 19:28
seen again in https://github.com/grpc/grpc/pull/9322

**Comment by dgquintas** [comment] 2017-01-23 16:59
Ping. @vjpai any leads on this issue?

**Comment by dgquintas** [comment] 2017-01-23 20:05
Seen again in #9446

**Comment by kpayson64** [comment] 2017-01-24 20:55
Seen again:
https://grpc-testing.appspot.com/job/gRPC_pull_requests_linux/2175/

**Comment by vjpai** [comment] 2017-01-24 21:43
@sreecha do you have any insights here? It is a sync server issue, afaict.

**Comment by sreecha** [comment] 2017-01-24 21:52
If I remember correctly, this only happens with poll-cv

**Comment by dgquintas** [comment] 2017-01-24 22:44
@sreecha has graciously volunteered to adjust the test so that when poll-cv is used, fewer number of cqs are created: the current value seems to be too large for poll-cv (and its underlying threads) to handle within reasonable time bounds.

**Comment by dgquintas** [comment] 2017-01-26 17:37
This is happen very often now, polluting the Jenkins results. @sreecha do you have an idea of the ETA for a fix or mitigation?

**Comment by sreecha** [comment] 2017-01-26 17:40
I am actively looking at this. Ill have an update by EOD today (and if this isn't resolved by tomorrow, I'll disable the test - but continue investigating the issue)

**Comment by dgquintas** [comment] 2017-01-26 17:42
Sounds good, thank you!

**Comment by dgquintas** [comment] 2017-02-01 17:48
#9485 disables this test while @sreecha investigates.

**Comment by apolcyn** [comment] 2017-02-03 03:34
seen again with insecure version of this scenario in https://grpc-testing.appspot.com/job/gRPC_pull_requests_linux/2466/testReport/junit/(root)/c++_linux_opt/bins_opt_json_run_localhost___scenarios_json____scenarios______name____cpp_protobuf_async_client_sync_server_streaming_qps_unconstrained_insecure____warmup_seconds___0___benchmark_seconds___1___num_servers___1___server_config_____async_server_threads___0___security_params___null___server_type____SYNC_SERVER_____num_clients___0___client_config_____client_type____ASYNC_CLIENT____security_params___null___payload_config_____simple_params_____resp_size___0___req_size___0_____client_channels___64___async_client_threads___0___outstanding_rpcs_per_channel___100___rpc_type____STREAMING____load_params_____closed_loop_________histogram_params_____max_possible___60000000000_0___resolution___0_01_______GRPC_POLL_STRATEGY_poll_cv/

pr https://github.com/grpc/grpc/pull/9553 against v1.1.x

**Comment by dgquintas** [comment] 2017-02-03 03:41
@sreecha can you replicate #9485 against 1.1.x?

**Comment by apolcyn** [comment] 2017-02-10 02:50
looks like secure/insecure version failed in https://grpc-testing.appspot.com/job/gRPC_pull_requests_linux/2614/

pr #9654 against v1.1.x

**Comment by dgquintas** [comment] 2017-02-28 22:24
And again: https://grpc-testing.appspot.com/job/gRPC_pull_requests_linux/3078/console

```
I0228 19:23:22.166078060   25687 qps_worker.cc:272]          RunServerBody: Mark response given
I0228 19:23:22.179214824   25689 qps_worker.cc:227]          RunClientBody: Mark response given
I0228 19:23:22.179307933   25686 driver.cc:397]              Running
E0228 19:23:22.932202277   25889 sync_posix.c:53]            assertion failed: pthread_mutex_destroy(mu) == 0
I0228 19:23:23.165915745   25686 driver.cc:411]              Finishing clients
E0228 19:23:23.410399462   25686 driver.cc:436]              Couldn't get final status from client 0
E0228 19:23:23.410461445   25686 driver.cc:444]              Client 0 had an error Endpoint read failed
I0228 19:23:23.410509568   25686 driver.cc:457]              Finishing servers
I0228 19:23:23.410750995   25687 qps_worker.cc:263]          RunServerBody: Message read
I0228 19:23:23.411004960   25687 qps_worker.cc:272]          RunServerBody: Mark response given
I0228 19:23:23.411029390   25686 driver.cc:471]              Received final status from server 0
I0228 19:23:23.411039765   25687 qps_worker.cc:275]          RunServerBody: Returning
I0228 19:23:24.412610234   25687 qps_worker.cc:145]          RunServer: Returning
I0228 19:23:24.413166602   25686 report.cc:81]               QPS: -nan
I0228 19:23:24.413194065   25686 report.cc:91]               QPS: -nan (-nan/server core)
I0228 19:23:24.413210178   25686 report.cc:96]               Latencies (50/90/95/99/99.9%-ile): 0.0/0.0/0.0/0.0/0.0 us
I0228 19:23:24.413217319   25686 report.cc:106]              Server system time: 206.59%
I0228 19:23:24.413221834   25686 report.cc:108]              Server user time:   110.20%
I0228 19:23:24.413225654   25686 report.cc:110]              Client system time: -nan%
I0228 19:23:24.413229256   25686 report.cc:112]              Client user time:   -nan%
I0228 19:23:24.413233758   25686 report.cc:117]              Server CPU usage: 48.97%
I0228 19:23:24.413624740   25681 json_run_localhost.cc:82]   driver: subprocess exited with status 1
D0228 19:23:28.016578045   25683 ev_posix.c:107]             Using polling engine: epoll
I0228 19:23:28.018757436   25681 json_run_localhost.cc:85]   worker: subprocess terminated with signal 6
E0228 19:23:28.018780219   25681 json_run_localhost.cc:138]  assertion failed: driver_join_status == 0
```

**Comment by apolcyn** [comment] 2017-03-10 18:20
seen again in https://grpc-testing.appspot.com/job/gRPC_pull_requests_tsan_cpp/2637/

pr https://github.com/grpc/grpc/pull/9986 against v1.2.x

from the log:
```
I0310 04:46:08.618881194     424 driver.cc:457]              Finishing servers
E0310 04:46:08.620453330     424 driver.cc:464]              Failed WritesDone for server 0
E0310 04:46:08.620539557     424 driver.cc:477]              Couldn't get final status from server 0
E0310 04:46:08.620722899     424 driver.cc:485]              Server 0 had an error OS Error
I0310 04:46:08.623191904     424 report.cc:81]               QPS: 6956.4
I0310 04:46:08.623224505     424 report.cc:91]               QPS: 6956.4 (inf/server core)
I0310 04:46:08.623248834     424 report.cc:96]               Latencies (50/90/95/99/99.9%-ile): 6033.7/60544.8/858163.9/872783.4/880662.4 us
I0310 04:46:08.623264244     424 report.cc:106]              Server system time: -nan%
I0310 04:46:08.623275049     424 report.cc:108]              Server user time:   -nan%
I0310 04:46:08.623284848     424 report.cc:110]              Client system time: 21.97%
I0310 04:46:08.623297324     424 report.cc:112]              Client user time:   277.26%
I0310 04:46:08.623308852     424 report.cc:117]              Server CPU usage: -nan%
```

**Comment by jtattermusch** [comment] 2017-09-09 20:43
9 months old -> not a P0

**Comment by jtattermusch** [comment] 2017-09-11 08:44
dupe of https://github.com/grpc/grpc/issues/12428.

**Closed by jtattermusch** 2017-09-11 08:44 UTC
Labels: infra/BUILDPONY, lang/c++
