### ISSUE TITLE
cloud_to_prod and cloud_to_prod_auth interop tests are flaky against "default" and "gateway_v4".

### ISSUE THREAD

**Issue by murgatroid99** [grpc/grpc#10763] opened 2017-04-20 16:56 UTC
Seen at https://grpc-testing.appspot.com/job/gRPC_interop_pull_requests/13464/ and https://grpc-testing.appspot.com/job/gRPC_interop_pull_requests/13477/.

They all seem to be reporting connection failures

**Comment by dapengzhang0** [comment] 2017-08-11 20:55
Looks I assigned to myself by mistake.

**Comment by apolcyn** [comment] 2017-08-23 23:30
some of these failures are unavailable, but seeing others fail with `Unknown` status:

```
object(stdClass)#522 (3) {
  ["metadata"]=>
  array(0) {
  }
  ["code"]=>
  int(2)
  ["details"]=>
  string(0) ""
}

2017-08-23 14:55:00,126 FAILED: cloud_to_prod_auth:default:php7:compute_engine_creds [ret=1, pid=25549]
```

```
Call did not complete successfully. Status object:
object(stdClass)#385 (3) {
  ["metadata"]=>
  array(0) {
  }
  ["code"]=>
  int(2)
  ["details"]=>
  string(0) ""
}

2017-08-23 14:55:00,192 FAILED: cloud_to_prod_auth:default:php7:jwt_token_creds [ret=1, pid=25611]
```

https://sponge.corp.google.com/target?id=c41e8c97-8ce4-4ce0-bc25-873846a1d95a&target=grpc/release/ubuntu/grpc_interop_toprod&searchFor=&show=ALL&sortBy=STATUS

**Comment by markdroth** [comment] 2017-09-05 15:01
Another slight variant of this from #12298:

https://grpc-testing.appspot.com/job/gRPC_interop_pull_requests/16298/testReport/junit/(root)/tests/cloud_to_prod_auth_default_php7_compute_engine_creds/

Here's the output:

```
Running test case compute_engine_creds
Call did not complete successfully. Status object:
object(stdClass)#522 (3) {
  ["metadata"]=>
  array(0) {
  }
  ["code"]=>
  int(14)
  ["details"]=>
  string(20) "Endpoint read failed"
}
```

**Comment by apolcyn** [comment] 2017-10-02 18:46
https://sponge.corp.google.com/target?id=e4bfd950-0211-493b-a1ff-8f059c5f5f0f&target=grpc/release/ubuntu/grpc_interop_toprod&searchFor=&show=ALL&sortBy=STATUS

many `gateway_v4:*` failed in this run (on 1.6.x branch) with `Unknown` status

**Comment by apolcyn** [comment] 2017-10-04 02:18
rather than an `unavailable` error, a `TIMEOUT: cloud_to_prod:gateway_v4:c++:server_streaming ` failure seen in https://sponge.corp.google.com/target?id=9c467327-2a07-4e89-84be-c69a42a74e0d&target=grpc/ubuntu/pull_request/grpc_interop_toprod&searchFor=&show=ALL&sortBy=STATUS

**Comment by jtattermusch** [comment] 2017-10-04 11:14
This really needs an assignee from C-core team (failures have been happening across multiple languages).
Assigning @yang-g  for now, feel free to reassign if busy or if there's a better fit.

**Comment by yang-g** [comment] 2017-10-04 17:40
I just saw the same failure with a go client:
2017-10-03 10:02:26,402 FATAL: 2017/10/03 17:02:26 &{0xc4204e00f0}.Recv() = rpc error: code = Unavailable desc = transport is closing
exit status 1

2017-10-03 10:02:26,402 FAILED: cloud_to_prod:gateway_v4:go:cancel_after_first_response [ret=1, pid=13762]

Will try to repro with a C++ client.

**Comment by yang-g** [comment] 2017-10-05 20:37
Java failure:
2017-10-04 13:05:00,124 Gradle is no longer run automatically. Make sure to run
'./gradlew installDist -PskipCodegen=true' or
'./gradlew :grpc-interop-testing:installDist -PskipCodegen=true' after any
changes. -PskipCodegen=true is optional, but requires less setup.
[jetty-alpn-agent] Using: alpn-boot-8.1.11.v20170118.jar
Running test cancel_after_first_response
Exception in thread "main" java.lang.RuntimeException: java.util.concurrent.ExecutionException: io.grpc.StatusRuntimeException: UNAVAILABLE
	at io.grpc.testing.integration.TestServiceClient.run(TestServiceClient.java:193)
	at io.grpc.testing.integration.TestServiceClient.main(TestServiceClient.java:66)
Caused by: java.util.concurrent.ExecutionException: io.grpc.StatusRuntimeException: UNAVAILABLE
	at com.google.common.util.concurrent.AbstractFuture.getDoneValue(AbstractFuture.java:476)
	at com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:455)
	at com.google.common.util.concurrent.AbstractFuture$TrustedFuture.get(AbstractFuture.java:79)
	at io.grpc.testing.integration.AbstractInteropTest.cancelAfterFirstResponse(AbstractInteropTest.java:719)
	at io.grpc.testing.integration.TestServiceClient.runTest(TestServiceClient.java:302)
	at io.grpc.testing.integration.TestServiceClient.run(TestServiceClient.java:189)
	... 1 more
Caused by: io.grpc.StatusRuntimeException: UNAVAILABLE
	at io.grpc.Status.asRuntimeException(Status.java:526)
	at io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onClose(ClientCalls.java:385)
	at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:41)
	at io.grpc.internal.CensusTracingModule$TracingClientInterceptor$1$1.onClose(CensusTracingModule.java:363)
	at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:443)
	at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:63)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.close(ClientCallImpl.java:525)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.access$600(ClientCallImpl.java:446)
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:557)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:107)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.IOException: Connection reset by peer
	at sun.nio.ch.FileDispatcherImpl.read0(Native Method)
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39)
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
	at sun.nio.ch.IOUtil.read(IOUtil.java:192)
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380)
	at io.netty.buffer.PooledUnsafeDirectByteBuf.setBytes(PooledUnsafeDirectByteBuf.java:288)
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1106)
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:343)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:123)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:645)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:580)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:497)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:459)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:138)
	... 1 more
Shutting down

2017-10-04 13:05:00,124 FAILED: cloud_to_prod:gateway_v4:java:cancel_after_first_response [ret=1, pid=14108]

**Comment by jtattermusch** [comment] 2017-10-17 18:18
@matt-kwong  has enabled retries for pull request runs, so we are not seeing this on PRs (or seeing fairly rarely), but problem persists on master.

**Comment by jtattermusch** [comment] 2017-11-06 14:43
as our failing cloud_to_cloud tests are covered by https://github.com/grpc/grpc/issues/13253, renaming this issue to only include **cloud to prod** tests.

Here's a list of recent to_prod failures:
```

grpc/ubuntu/master/grpc_interop_toprod | 88 | null | cloud_to_prod:java:default:ping_pong | cloud_to_prod | java | default | ping_pong | FAILED | 2017-11-03 22:04:49 UTC | 2.64 |  
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
2 | grpc/ubuntu/master/grpc_interop_toprod | 88 | null | cloud_to_prod:java:default:client_streaming | cloud_to_prod | java | default | client_streaming | FAILED | 2017-11-03 22:04:13 UTC | 2.61 |  
3 | grpc/ubuntu/master/grpc_interop_toprod | 88 | null | cloud_to_prod:java:default:cancel_after_first_response | cloud_to_prod | java | default | cancel_after_first_response | FAILED | 2017-11-03 22:04:10 UTC | 2.63 |  
4 | grpc/ubuntu/master/grpc_interop_toprod | 88 | null | cloud_to_prod:ruby:gateway_v4:large_unary | cloud_to_prod | ruby | gateway_v4 | large_unary | FAILED | 2017-11-03 22:04:51 UTC | 1.17 |  
5 | grpc/ubuntu/master/grpc_interop_toprod | 88 | null | cloud_to_prod:csharpcoreclr:gateway_v4:server_streaming | cloud_to_prod | csharpcoreclr | gateway_v4 | server_streaming | FAILED | 2017-11-03 22:04:10 UTC | 1.67 |  
6 | grpc/ubuntu/master/grpc_interop_toprod | 87 | null | cloud_to_prod_auth:go:gateway_v4:jwt_token_creds | cloud_to_prod_auth | go | gateway_v4 | jwt_token_creds | FAILED | 2017-11-03 17:39:57 UTC | 3.67 |  
7 | grpc/ubuntu/master/grpc_interop_toprod | 87 | null | cloud_to_prod:go:gateway_v4:large_unary | cloud_to_prod | go | gateway_v4 | large_unary | FAILED | 2017-11-03 17:40:11 UTC | 1.44 |  
8 | grpc/ubuntu/master/grpc_interop_toprod | 86 | null | cloud_to_prod:node:gateway_v4:server_streaming | cloud_to_prod | node | gateway_v4 | server_streaming | FAILED | 2017-11-03 16:19:20 UTC | 1.33 |  
9 | grpc/ubuntu/master/grpc_interop_toprod | 85 | null | cloud_to_prod_auth:javaokhttp:gateway_v4:compute_engine_creds | cloud_to_prod_auth | javaokhttp | gateway_v4 | compute_engine_creds | FAILED | 2017-11-03 15:39:24 UTC | 2.21 |  
10 | grpc/ubuntu/master/grpc_interop_toprod | 85 | null | cloud_to_prod_auth:javaokhttp:gateway_v4:jwt_token_creds | cloud_to_prod_auth | javaokhttp | gateway_v4 | jwt_token_creds | FAILED | 2017-11-03 15:39:25 UTC | 2.29 |  
11 | grpc/ubuntu/master/grpc_interop_toprod | 85 | null | cloud_to_prod_auth:java:gateway_v4:compute_engine_creds | cloud_to_prod_auth | java | gateway_v4 | compute_engine_creds | FAILED | 2017-11-03 15:39:37 UTC | 2.76 |  
12 | grpc/ubuntu/master/grpc_interop_toprod | 84 | null | cloud_to_prod:node:default:large_unary | cloud_to_prod | node | default | large_unary | FAILED | 2017-11-03 14:44:03 UTC | 1.92 |  
13 | grpc/ubuntu/master/grpc_interop_toprod | 84 | null | cloud_to_prod:javaokhttp:default:client_streaming | cloud_to_prod | javaokhttp | default | client_streaming | FAILED | 2017-11-03 14:44:17 UTC | 2.14 |  
14 | grpc/ubuntu/master/grpc_interop_toprod | 84 | null | cloud_to_prod:java:gateway_v4:server_streaming | cloud_to_prod | java | gateway_v4 | server_streaming | FAILED | 2017-11-03 14:43:54 UTC | 3.46 |  
15 | grpc/ubuntu/master/grpc_interop_toprod | 84 | null | cloud_to_prod:javaokhttp:default:server_streaming | cloud_to_prod | javaokhttp | default | server_streaming | FAILED | 2017-11-03 14:44:14 UTC | 2.15 |  
16 | grpc/ubuntu/master/grpc_interop_toprod | 83 | null | cloud_to_prod_auth:javaokhttp:gateway_v4:compute_engine_creds | cloud_to_prod_auth | javaokhttp | gateway_v4 | compute_engine_creds | FAILED | 2017-11-03 09:39:14 UTC | 3.99 |  
17 | grpc/ubuntu/master/grpc_interop_toprod | 83 | null | cloud_to_prod_auth:javaokhttp:gateway_v4:jwt_token_creds | cloud_to_prod_auth | javaokhttp | gateway_v4 | jwt_token_creds | FAILED | 2017-11-03 09:39:14 UTC | 4.11 |  
18 | grpc/ubuntu/master/grpc_interop_toprod | 83 | null | cloud_to_prod:php7:gateway_v4:ping_pong | cloud_to_prod | php7 | gateway_v4 | ping_pong | FAILED | 2017-11-03 09:39:09 UTC | 0.53 |  
19 | grpc/ubuntu/master/grpc_interop_toprod | 83 | null | cloud_to_prod_auth:node:gateway_v4:per_rpc_creds | cloud_to_prod_auth | node | gateway_v4 | per_rpc_creds | FAILED | 2017-11-03 09:39:15 UTC | 3.7 |  
20 | grpc/ubuntu/master/grpc_interop_toprod | 82 | null | cloud_to_prod:python:gateway_v4:client_streaming | cloud_to_prod | python | gateway_v4 | client_streaming | FAILED | 2017-11-03 07:40:29 UTC | 0.97 |  
21 | grpc/ubuntu/master/grpc_interop_toprod | 80 | null | cloud_to_prod:go:gateway_v4:large_unary | cloud_to_prod | go | gateway_v4 | large_unary | FAILED | 2017-11-02 15:00:38 UTC | 1.59 |  
22 | grpc/ubuntu/master/grpc_interop_toprod | 79 | null | cloud_to_prod:javaokhttp:default:empty_unary | cloud_to_prod | javaokhttp | default | empty_unary | FAILED | 2017-11-02 13:21:11 UTC | 1.78 |  
23 | grpc/ubuntu/master/grpc_interop_toprod | 79 | null | cloud_to_prod:javaokhttp:gateway_v4:large_unary | cloud_to_prod | javaokhttp | gateway_v4 | large_unary | FAILED | 2017-11-02 13:21:00 UTC | 1.69 |  
24 | grpc/ubuntu/master/grpc_interop_toprod | 79 | null | cloud_to_prod:javaokhttp:default:large_unary | cloud_to_prod | javaokhttp | default | large_unary | FAILED | 2017-11-02 13:21:07 UTC | 1.95 |  
25 | grpc/ubuntu/master/grpc_interop_toprod | 79 | null | cloud_to_prod:javaokhttp:default:ping_pong | cloud_to_prod | javaokhttp | default | ping_pong | FAILED | 2017-11-02 13:20:50 UTC | 1.72 |  
26 | grpc/ubuntu/master/grpc_interop_toprod | 78 | null | cloud_to_prod_auth:go:default:oauth2_auth_token | cloud_to_prod_auth | go | default | oauth2_auth_token | FAILED | 2017-11-02 08:03:27 UTC | 3.68 |  
27 | grpc/ubuntu/master/grpc_interop_toprod | 78 | null | cloud_to_prod_auth:python:default:jwt_token_creds | cloud_to_prod_auth | python | default | jwt_token_creds | FAILED | 2017-11-02 08:03:26 UTC | 3.06 |  
28 | grpc/ubuntu/master/grpc_interop_toprod | 77 | null | cloud_to_prod_auth:csharp:default:jwt_token_creds | cloud_to_prod_auth | csharp | default | jwt_token_creds | FAILED | 2017-11-02 03:00:38 UTC | 1.32 |  
29 | grpc/ubuntu/master/grpc_interop_toprod | 77 | null | cloud_to_prod_auth:java:default:jwt_token_creds | cloud_to_prod_auth | java | default | jwt_token_creds | FAILED | 2017-11-02 03:00:35 UTC | 2.93 |  
```

**Comment by adelez** [comment] 2017-11-06 23:06
Dashboard: https://performanceedit-dot-grpc-testing.appspot.com/explore?dashboard=5711255578869760.
You can see the failing ones in upper right corner. 
One suggestion was to retry in the client sides for this non-hermetic environment. An easier way to achieve this is simply set allow_flakes to true for cloud-to-prod tests, instead of changing all test clients.

**Comment by yang-g** [comment] 2017-12-13 17:24
I can repro. Seems like GFE is dropping the connection during client reading...

**Comment by AspirinSJL** [comment] 2018-04-06 17:15
A lot of cloud_to_prod and cloud_to_cloud tests are timing out now.

https://sponge.corp.google.com/target?id=5ba5eb0f-4a1f-4cb3-9f79-8ecc37f2aebb&target=grpc/core/pull_request/linux/grpc_interop_toprod&searchFor=&show=ALL&sortBy=STATUS

**Comment by adelez** [comment] 2018-04-06 17:51
@AspirinSJL , please file a new issue your latest finding. I don't think it's the same bug.

**Comment by AspirinSJL** [comment] 2018-04-06 18:30
Filed in #14969.

**Closed** 2018-04-26 03:56 UTC
Labels: infra/BUILDPONY, priority/P1
