### ISSUE TITLE
Python client get stuck if stub is not created inside a function

### ISSUE THREAD

**Issue by incidenthunter** [grpc/grpc#4969] opened 2016-01-29 19:42 UTC
Hello again :)

I don't know if is a bug or a feature but there is an unexpected behavior: If the stub is created in the `__main__` namespace, the process will be stuck in atexit() routines when quitting.

Example with [greeter_server.py](https://github.com/grpc/grpc/blob/release-0_11/examples/python/helloworld/greeter_server.py) running:

This client is ok, returns immediately:

```
$ cat greeter_client_ok.py
from grpc.beta import implementations
import helloworld_pb2

def run():
  channel = implementations.insecure_channel('localhost', 50051)
  stub = helloworld_pb2.beta_create_Greeter_stub(channel)
if __name__ == '__main__':
  run()
```

This one will never exit:

```
$ cat greeter_client_ko.py
from grpc.beta import implementations
import helloworld_pb2

channel = implementations.insecure_channel('localhost', 50051)
stub = helloworld_pb2.beta_create_Greeter_stub(channel)
```

When running it, now, it is stuck, so pressing ^C gives the following backtrace:

```
$ python greeter_client_ko.py
^C
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/usr/lib/python2.7/atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "/home/foo/.local/lib/python2.7/site-packages/concurrent/futures/thread.py", line 39, in _python_exit
    t.join(sys.maxint)
  File "/usr/lib/python2.7/threading.py", line 960, in join
    self.__block.wait(delay)
  File "/usr/lib/python2.7/threading.py", line 359, in wait
    _sleep(delay)
KeyboardInterrupt
Error in sys.exitfunc:
Traceback (most recent call last):
  File "/usr/lib/python2.7/atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "/home/foo/.local/lib/python2.7/site-packages/concurrent/futures/thread.py", line 39, in _python_exit
    t.join(sys.maxint)
  File "/usr/lib/python2.7/threading.py", line 960, in join
    self.__block.wait(delay)
  File "/usr/lib/python2.7/threading.py", line 359, in wait
    _sleep(delay)
KeyboardInterrupt
```

PS: I am running Debian Jessie on amd64, and grpc from the git master branch

**Comment by soltanmm** [comment] 2016-02-01 01:44
Haven't looked at it, but, it smells like something having to do with end-of-program garbage-collection behavior in Python being different than the usual, "Nobody knows me so I'll die now," behavior exhibited during the majority of runtime.

Note to self: try seeing what happens if one calls `grpc_shutdown` before calling some other `grpc_*_destroy` function.

**Comment by ctiller** [comment] 2016-02-01 01:59
If grpc_shutdown is called before all relevant destroy functions, in the
words of Spengler: it would be bad.

**Comment by soltanmm** [comment] 2016-02-01 02:17
Yeah, such a screwy sequence shouldn't happen to begin with, but, I'm curious about whether it'd be some sort of hang or a crash. If it's a hang then I have something to work with. If it's a crash then I'm left confused and have to dig...

**Comment by inconshreveable** [comment] 2016-02-05 22:44
This hangs:
```
import sys
from grpc.beta import implementations
import helloworld_pb2

class X:
  def __init__(self):
    self.ch = implementations.insecure_channel("127.0.0.1", 2024)
    self.svc = helloworld_pb2.beta_create_Greeter_stub(self.ch)

x = X()
```

This does not:
```
import sys
from grpc.beta import implementations
import helloworld_pb2

class X:
  def __init__(self):
    self.ch = implementations.insecure_channel("127.0.0.1", 2024)
    self.svc = helloworld_pb2.beta_create_Greeter_stub(self.ch)

def foo():
  x = X()

foo()
```
very much seems like something around globals cleanup at process termination

**Comment by GuoJing** [comment] 2016-02-07 18:02
This is a problem!

**Comment by GuoJing** [comment] 2016-02-07 18:30
May be one way but not the best way to solve:

```python
import atexit

global _client_impls
_client_impls = []

class X:
    def __init__(self):
        self.connect()

    def connect(self):
        self.ch = channel
        self.stub = stub(channel)
        _client_impls.append(self)

    def shutdown(self):
        del self.ch
        del self.stub

def exit_handler():
    print 'exit there'
    for i in _client_impls:
        i.shutdown()
        del i

atexit.register(exit_handler)
```

**Comment by GuoJing** [comment] 2016-02-08 07:48
@inconshreveable hi, your code is not working. Your function foo() return nothing and of course GC will del x. It's ok. If you return x, it still get stuck.

**Comment by sukritiramesh** [comment] 2016-05-12 17:51
Hello, we seem to have a similar issue in Tensorflow-Serving (reported: https://github.com/tensorflow/serving/issues/76). Example code related to this issue in: mnist_client.py in [tensorflow_serving/example](https://github.com/tensorflow/serving/tree/master/tensorflow_serving/example) with which I was able to reproduce this issue. Any ideas on how we might be able to fix it? Thanks!

**Comment by kpayson64** [comment] 2016-06-02 01:05
Drilling down into this issue:
On startup, the client stub submits a job to a ```future.ThreadPool``` that runs ```_Kernal.spin()``` in an infinite loop.  This job cannot complete until the client is shutdown, which happens when the stub is deleted.

However, ```future.ThreadPool``` has a shutdown hook that attempts to join all outstanding threads.  This happens before module-scope object deletion, and hangs.

@nathanielmanistaatgoogle Can we confirm that this behavior is gone after refactoring?

**Comment by GuoJing** [comment] 2016-06-02 02:05
Thanks for reply.

Yes, so I have to delete objects myself. That's not cool. And the one who import this lib should care about del object.

Right now I'm working with master, the grpcio version is 0.15.0.dev0, still a problem.

My solution is tricky but work, this solution work with 0.13.x, 0.15.x, but not for 0.14.x:

import atexit

# global channel

channel = new_channel()

class Obj(object):

    def __init__(self, channel):
        self.channel = channel

    def do_something(self):
       with new_stub(self.channel) as stub:
           stub.do_something()
           # call stub *_AutoIntermediary.__exit__*

    def shutdown(self):
        del self.channel
        self.channel = None

obj = Obj(channel)

# register atexit
# this is no good because if we are a lib or idk
# anything who import us cause a ateixt function register

@ateixt.register
def shutdown():
    obj.shutdown()

I think this should be fixed ASAP.

Thanks

GuoJing
-----------------------------
http://guojing.me <http://guojing.me/> 
The one who love coding.
--> ret <--
echo null
rm -rf /

**Comment by zj8487** [comment] 2016-06-02 02:56
really hope the issue can be fixed in the GA plan.

**Comment by GuoJing** [comment] 2016-06-02 08:25
hi

No offend, this is a very serious bug and not one cares about this for a long time.

I doubt if anyone in gRPC Python team is really using Python implement. Yeah, I know, maybe Google have SRE and all the servers always running and will NEVER down for a second. but we don't, may users don't.

I don't care if there is a bug deep in code (maybe), I just care why I can't stop my application, not only CTRL+C you know, If I have a wsgi application who include my code (of course I want everyone in our team include a client lib and cares nothing), will be blocked, and have to KILL the process.

This is no that hard if you guys cares, right? No one like this.

And because another bug:

https://github.com/grpc/grpc/issues/6730#issuecomment-223198543 <https://github.com/grpc/grpc/issues/6730#issuecomment-223198543>

I downgrade grpcio from 0.14.x to 0.13.1.

Please

Please care two thing before release:

1. I could quit my program normally
2. Reconnect server automatically should work - if it don't work, please do not block me (iomgr wait for stop), I can't quit anything, I have to kill -9

I think gRPC is a very good project and I do think is fast, high performance base on HTTP2.

Please let me run a Hello Word easily first.

Thanks and Best wishes

Sorry for poor English.

GuoJing
-----------------------------
http://guojing.me <http://guojing.me/> 
The one who love coding.
--> ret <--
echo null
rm -rf /

**Comment by nathanielmanistaatgoogle** [comment] 2016-06-06 17:14
@kpayson64: most of the answer to your question is "yes", but a small part of the answer to your question is ["well what's up with the `tearDown` method of `_rpc_test.RPCTest`?"](https://github.com/grpc/grpc/issues/6802).

**Comment by nathanielmanistaatgoogle** [comment] 2016-06-14 20:23
@kpayson64: will this be fixed by the integration of [pull request 6873](https://github.com/grpc/grpc/pull/6873) or will there be more to do?

**Comment by kpayson64** [comment] 2016-06-14 20:30
@nathanielmanistaatgoogle 
The primary issue here should already be resolved.  #6873 solves the general problem of stub shutdown in the event of an outstanding call, which doesn't seem to be the case here.

**Closed** 2016-06-14 20:39 UTC
Labels: P2, python

**Comment by dvaldivia** [comment] 2017-11-28 20:53
@GuoJing with your solution I'm getting an error
```
AttributeError: __exit__
```

Are you experiencing this on `grpc 1.7.0` ?

**Comment by dvaldivia** [comment] 2018-03-08 22:10
this is funny, it shows I unassigned @soltanmm on this issue, but I dont remember doing that

**Comment by nathanielmanistaatgoogle** [comment] 2018-03-08 22:20
@dvaldivia: GitHub sometimes tells lies. :-(

What actually happened is that you were the first to comment on the issue after @soltanmm left [the gRPC organization](http://github.com/grpc).
