### ISSUE TITLE
TIMEOUT: bins/opt/thread_stress_test --gtest_filter=AsyncClientEnd2endTest/3.ThreadStress GRPC_POLL_STRATEGY=epollex 

### ISSUE THREAD

**Issue by y-zeng** [grpc/grpc#13115] opened 2017-10-24 03:04 UTC
```
Timeout
D1024 02:20:52.892593773   26479 test_config.c:388]          test slowdown factor: sanitizer=1, fixture=1, poller=1, total=1
Note: Google Test filter = AsyncClientEnd2endTest/3.ThreadStress
[==========] Running 1 test from 1 test case.
[----------] Global test environment set-up.
[----------] 1 test from AsyncClientEnd2endTest/3, where TypeParam = grpc::testing::CommonStressTestAsyncServer<grpc::testing::CommonStressTestInproc<grpc::testing::EchoTestService::WithAsyncMethod_Echo<grpc::testing::EchoTestService::WithAsyncMethod_RequestStream<grpc::testing::EchoTestService::WithAsyncMethod_ResponseStream<grpc::testing::EchoTestService::WithAsyncMethod_BidiStream<grpc::testing::EchoTestService::WithAsyncMethod_Unimplemented<grpc::testing::EchoTestService::Service> > > > > > >
[ RUN      ] AsyncClientEnd2endTest/3.ThreadStress
D1024 02:20:52.893107902   26479 ev_posix.cc:135]            Using polling engine: epollex
D1024 02:20:52.893128377   26479 dns_resolver.cc:306]        Using native dns resolver
```

**Comment by dgquintas** [comment] 2017-11-09 00:02
Duplicate of #13148

**Closed by dgquintas** 2017-11-09 00:02 UTC
