### ISSUE TITLE
C#: fail to load libgrpc_csharp_ext.x64.so on alpine linux

### ISSUE THREAD

**Issue by careless6666** [grpc/grpc#29134] opened 2022-03-17 09:47 UTC
i use image 
mcr.microsoft.com/dotnet/aspnet:6.0.3-alpine3.15-amd64

with added 
RUN apk update && apk add libc6-compat 

and receive error 

```
ldd /app/runtimes/linux-x64/native/libgrpc_csharp_ext.x64.so
	/lib/ld-musl-x86_64.so.1 (0x7fe23e3e8000)
	libdl.so.2 => /lib/ld-musl-x86_64.so.1 (0x7fe23e3e8000)
	librt.so.1 => /lib/ld-musl-x86_64.so.1 (0x7fe23e3e8000)
	libpthread.so.0 => /lib/ld-musl-x86_64.so.1 (0x7fe23e3e8000)
	libm.so.6 => /lib/ld-musl-x86_64.so.1 (0x7fe23e3e8000)
	libstdc++.so.6 => /usr/lib/libstdc++.so.6 (0x7fe23d9ca000)
	libgcc_s.so.1 => /usr/lib/libgcc_s.so.1 (0x7fe23d9b0000)
	libc.so.6 => /lib/ld-musl-x86_64.so.1 (0x7fe23e3e8000)
Error loading shared library ld-linux-x86-64.so.2: No such file or directory (needed by /app/runtimes/linux-x64/native/libgrpc_csharp_ext.x64.so)
Error relocating /app/runtimes/linux-x64/native/libgrpc_csharp_ext.x64.so: __strdup: symbol not found
```

**Comment by jtattermusch** [comment] 2022-03-17 11:17
Closing as duplicate of https://github.com/grpc/grpc/issues/21446

**Closed by jtattermusch** 2022-03-17 11:17 UTC
Labels: kind/bug, lang/C#, priority/P3

**Comment by liiujinfu** [comment] 2022-10-26 10:15
you can add `RUN ln -s /lib/ld-musl-x86_64.so.1 /lib/ld-linux-x86-64.so.2`
ld-musl-x86_64.so.1 is compatible with ld-linux-x86-64.so.2.
