### ISSUE TITLE
Crashing after gRPC channel destruction.

### ISSUE THREAD

**Issue by amdm01** [grpc/grpc#22805] opened 2020-04-28 10:47 UTC
### What version of gRPC and what language are you using?
gRPC version: 1.27.3
language: C++

### What operating system (Linux, Windows,...) and version?
Windows 7 SP1

### What runtime / compiler are you using (e.g. python version or version of gcc)

MSVC x64 version 1925

### What did you do?

I create a gRPC channel:

```
int main()
{
	auto channel = grpc::CreateChannel("127.0.0.1:1338", grpc::InsecureChannelCredentials());
	return 0;
}
```

### What did you expect to see?

Program terminates normally.

### What did you see instead?

Memory writing access violation happens:

Exception thrown at 0x000000007774E4E4 (ntdll.dll) in main.exe: 0xC0000005: Access violation writing location 0x0000000000000024. 

Next are call stacks of two threads that are alive at the moment when exception is thrown:

'anonymous_namespace'::ThreadInternalsWindows::thread_body thread (here the access violation happens):

	ntdll.dll!000000007774e4e4()	Unknown
 	ntdll.dll!000000007774e40b()	Unknown
 	main.exe!__acrt_lock(__acrt_lock_id _Lock) Line 55	C++
 	main.exe!_free_dbg(void * block, int block_use) Line 1019	C++
 	main.exe!free(void * block) Line 32	C++
 	main.exe!windows_source_addr_factory_destroy(address_sorting_source_addr_factory * self) Line 78	C
 	main.exe!address_sorting_shutdown(...) Line 374	C
 	main.exe!grpc_resolver_dns_ares_shutdown() Line 524	C++
 	main.exe!grpc_shutdown_internal_locked() Line 180	C++
 	main.exe!grpc_shutdown_internal(void * __formal) Line 208	C++
 	main.exe!`anonymous namespace'::ThreadInternalsWindows::thread_body(void * v) Line 128	C++
 	[External Code]	

Main Thread thread:

 	[External Code]	
	main.exe!try_cor_exit_process(const unsigned int return_code) Line 90	C++
 	main.exe!exit_or_terminate_process(const unsigned int return_code) Line 143	C++
 	main.exe!common_exit(const int return_code, const _crt_exit_cleanup_mode cleanup_mode, const _crt_exit_return_mode return_mode) Line 282	C++
 	main.exe!exit(int return_code) Line 294	C++
 	[External Code]	

Looks like a race condition has place here. Next code works as it should:

```
int main()
{
	auto channel = grpc::CreateChannel("127.0.0.1:1338", grpc::InsecureChannelCredentials());
	channel.reset();
	std::this_thread::sleep_for(std::chrono::milliseconds(100));
	return 0;
}
```

**Comment by coryan** [comment] 2020-05-08 12:26
This might be a duplicate of #22479

**Comment by veblush** [comment] 2022-05-23 22:42
Yesh it seems to be a duplicate of https://github.com/grpc/grpc/issues/22479.

**Closed by veblush** 2022-05-23 22:42 UTC
Labels: kind/bug, lang/c++, priority/P2, untriaged
