### ISSUE TITLE
bm_fullstack_* tests are broken on linux dbg

### ISSUE THREAD

**Issue by jtattermusch** [grpc/grpc#21724] opened 2020-01-20 13:39 UTC
They started failing at 100% on master as soon as  https://github.com/grpc/grpc/pull/21680 was merged.

https://g3c.corp.google.com/results/invocations/b35685c4-2c0e-4785-ba81-a4cdcc2853a1/targets/github%2Fgrpc%2Frun_tests%2Fcpp_linux_dbg_native/tests

```
Running bins/dbg/bm_fullstack_streaming_ping_pong
Run on (32 X 2300 MHz CPU s)
CPU Caches:
  L1 Data 32K (x16)
  L1 Instruction 32K (x16)
  L2 Unified 256K (x16)
  L3 Unified 46080K (x1)
Load Average: 78.20, 101.23, 50.60
***WARNING*** Library was built as DEBUG. Timings may be affected.
I0117 22:39:02.264245336   30190 chttp2_transport.cc:1771]   fake:mock_server_endpoint: Sending goaway err={"created":"@1579300742.264227738","description":"Server shutdown","file":"src/core/lib/surface/server.cc","file_line":323,"grpc_status":0}
E0117 22:39:02.264345089   30190 completion_queue_cc.cc:44]  CompletionQueue shutdown being shutdown before its server.
E0117 22:39:02.264410594   30190 sync_posix.cc:65]           assertion failed: pthread_mutex_lock(mu) == 0
Command terminated by signal 6
```

**Comment by jtattermusch** [comment] 2020-01-20 13:41
This is failing 100% on master 
go/grpc-flaky
https://screenshot.googleplex.com/88manC2XgQf

**Comment by vjpai** [comment] 2020-01-21 16:52
The problem is that the BMs directly use the core server while using the C++ CQ. So we have a problem that the BMs actually shut down the server twice -- once explicitly at the core and then again at the C++ layer. I should look into changing this at the BM layer.

**Comment by jtattermusch** [comment] 2020-01-21 17:03
It is not clear to me why this hasn't been caught by the bazel tests (which run on PRs), but only by the run_tests.py tests - because it sounds that this kind of behavior shouldn't really be affected by the build system.

**Comment by vjpai** [comment] 2020-01-21 17:23
Agreed, this seems like a deterministic failure and I don't get why it wasn't seen at the PR.

**Comment by vjpai** [comment] 2020-01-21 17:32
Backing off my previous comment. It might not have been seen in the bazel build because the behavior presented is technically UB. It could be that the destruction of the CQ hadn't actually invalidated the memory of its lock so the UnregisterServer method call ended up completing successfully.

**Comment by vjpai** [comment] 2020-01-21 17:38
Ah, even more straightfoward answer. The microbenchmarks are declared as binaries, not tests, so they don't even get tested on PRs. Oops.

**Comment by jtattermusch** [comment] 2020-01-21 17:45
Sounds like if we want to get the bm_* stuff tested, we will need to setup a bazel version of them because over time we will be phasing out run_tests.py version of C/C++ tests (for now they are running on master, but they are no longer run on PRs; at some point we will get rid of them entirely)

**Comment by vjpai** [comment] 2020-01-21 19:05
@jtattermusch Yes, just did that.

**Comment by vjpai** [comment] 2020-01-27 21:42
I'm closing this here since this is no longer broken, but will continue working on #21739 to prevent future regressions here.

**Closed by vjpai** 2020-01-27 21:42 UTC
Labels: infra/BUILDPONY, kind/bug, lang/c++, priority/P1
