### ISSUE TITLE
Using grpcio==1.48.0 causes side effects in Python processes. 

### ISSUE THREAD

**Issue by tvalentyn** [grpc/grpc#30446] opened 2022-07-30 02:13 UTC
### What version of gRPC and what language are you using?

1.48.0

### What operating system (Linux, Windows,...) and version?
Linux (ubuntu, rodete)

### What runtime / compiler are you using (e.g. python version or version of gcc)
Python 3.7

### What did you do?

A recent release grpcio==1.48.0 causes a regression, which is manifests through side-effects where calls to subprocess.Popen() can gets stuck (and hang the process).
The reasons are not obvious, likely there some sort of memory corruption is happening.  
We are able to reliably repro the issue in one of our tests: https://github.com/apache/beam/issues/22533. 

Using git bisect + rebuilding grpc io points to https://github.com/grpc/grpc/commit/977ebbef0925e70867bb627d8cde50f4fcee45aa.

### Anything else we should know about your project / environment?

@chamikaramj or myself can provide more information about how to reproduce the issue by running our test.

**Comment by tvalentyn** [comment] 2022-07-30 02:13
cc: @ctiller

**Comment by tvalentyn** [comment] 2022-07-30 02:13
I wonder if we can consider rolling back the release (perhaps by pushing 1.49.0, that is effectively the same as 1.47.1 ?)

**Comment by chamikaramj** [comment] 2022-08-01 17:05
Instructions for reproducing using the Apache Beam test: https://github.com/apache/beam/issues/22533#issuecomment-1201473386

**Comment by gnossen** [comment] 2022-08-01 17:15
I've yanked 1.48.0 from PyPi. This should resolve the issue in the short term. I will work with @ctiller to ensure that the root cause is found and fixed before we proceed with a patch release.

@tvalentyn Please consider adding a test to your CI that uses our prereleases. This can be done with `pip install --pre grpcio`. While we have subprocess tests for Python, those tests are still passing. Let me know if you need more any information on how to go about doing this.

**Comment by tvalentyn** [comment] 2022-08-01 17:40
Yes, I filed https://github.com/apache/beam/issues/22540 for that.

**Comment by gnossen** [comment] 2022-08-15 17:10
Will be resolved by https://github.com/grpc/grpc/pull/30572

**Closed by gnossen** 2022-08-15 17:10 UTC
Labels: kind/bug, lang/Python, lang/core, priority/P2
