### ISSUE TITLE
Android Java client fails to connect to Python server

### ISSUE THREAD

**Issue by Slonegg** [grpc/grpc#11258] opened 2017-05-21 11:50 UTC
Android Java client can't connect to GRPC Python server:
```
Status{code=UNAVAILABLE, description=null, cause=java.io.IOException: PROTOCOL_ERROR invalid settings id: -509
at io.grpc.okhttp.internal.framed.Http2.ioException(Http2.java:589)
at io.grpc.okhttp.internal.framed.Http2.access$200(Http2.java:47)
at io.grpc.okhttp.internal.framed.Http2$Reader.readSettings(Http2.java:304)
at io.grpc.okhttp.internal.framed.Http2$Reader.nextFrame(Http2.java:162)
at io.grpc.okhttp.OkHttpClientTransport$ClientFrameHandler.run(OkHttpClientTransport.java:868)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
at java.lang.Thread.run(Thread.java:761)
```

Same symptoms as in this SO post: https://stackoverflow.com/questions/43827149/unavailable-grpc-failure-from-android-client-to-python-server#

**System Info**
Windows 10 x64
Python 3.6.1
GRPC version tried: 1.1.0, 1.2.0, 1.30 - doesn't work; 1.0.4 Python and 1.03 for Java - works
Android Studio 2.3.0
JRE 1.8.0_112
Python server serving localhost:50051 on Windows. Connecting to 10.0.02:50051 from Android emulator.

**Comment by nathanielmanistaatgoogle** [comment] 2017-05-23 16:48
Are you able to share with us the code that when run leads you to this problem?

**Comment by ejona86** [comment] 2017-05-24 00:18
This looks like in grpc-java's OkHttp transport. I've filed grpc/grpc-java#3032 for tracking the Java side of things. We'll have to figure out more what we want to do here.

**Comment by ejona86** [comment] 2017-05-24 00:44
@Slonegg, this should have worked with 1.1.0 and 1.2.0. We can agree that 1.3.0 seems like it would be broken. All versions of grpc-java OkHttp are broken, but we only believe 1.3.0 to trigger the problem.

**Comment by Slonegg** [comment] 2017-05-24 12:41
@ejona86 you right, it seems that problem is on Python side. So 1.2.0 and 1.30 works in Java. For python I have to use following set of dependencies, not only grpcio-tools package needs to be downgraded, but also grpcio and protobuf:
```
awscli
boto3==1.4.4
Cython==0.25.2
protobuf==3.0.0
grpcio==1.0.4
grpcio-tools==1.0.4
pytest==3.0.7
numpy==1.12.1
```

**Comment by Slonegg** [comment] 2017-05-24 12:42
@nathanielmanistaatgoogle it will be difficult to share code. But there is nothing there really, I've just started this project. I think implementing python server for one of android examples will trigger this problem.

**Comment by ejona86** [comment] 2017-05-24 15:43
@Slonegg, no need to share code. We've tracked this down enough we can take it from here.

BTW, when I said "worked with 1.1.0 and 1.2.0" I meant grpc-python 1.1.0 and 1.2.0.

**Comment by ejona86** [comment] 2017-05-24 15:45
Reassigning to @ctiller to figure out any code changes necessary for C core. grpc/grpc-java#3032 is to fix the root cause, but we need to figure out the story with pre-existing clients.

**Comment by kpayson64** [comment] 2018-05-15 23:33
OkHTTP clients are now interop-tested against c-core clients.

**Closed by kpayson64** 2018-05-15 23:33 UTC
Labels: kind/customer issue, lang/core, priority/P2
