### ISSUE TITLE
bins/dbg/status_conversion_test GRPC_POLL_STRATEGY=poll 

### ISSUE THREAD

**Issue by markdroth** [grpc/grpc#12960] opened 2017-10-11 18:47 UTC
https://sponge.corp.google.com/target?id=6d7e1c66-06e0-475f-affb-6b5656ecff78&target=github/grpc/c_macos_dbg_native&searchFor=&show=FAILED&sortBy=STATUS

```
Failure
D1009 12:22:28.659028000 140735261507584 test_config.c:388]            test slowdown factor: sanitizer=1, fixture=1, poller=1, total=1
E1009 12:22:28.659799000 140735261507584 status_conversion_test.c:133] assertion failed: grpc_http2_error_to_grpc_status(&my_exec_ctx, GRPC_HTTP2_CANCEL, after_deadline) == (GRPC_STATUS_DEADLINE_EXCEEDED)



*******************************
Caught signal SIGABRT
  no backtrace
```

**Comment by jtattermusch** [comment] 2017-10-26 10:42
Dupe of https://github.com/grpc/grpc/issues/13131.

**Closed by jtattermusch** 2017-10-26 10:42 UTC
Labels: infra/BUILDPONY
