### ISSUE TITLE
Reproducible "Fatal Python error: Aborted" when using grpc with google-cloud-iam

### ISSUE THREAD

**Issue by andrewsg** [grpc/grpc#30651] opened 2022-08-19 20:24 UTC
### What version of gRPC and what language are you using?
Python 3.8
grpcio==1.49.0rc1

### What operating system (Linux, Windows,...) and version?
Reproduces on OS X and Linux

### What runtime / compiler are you using (e.g. python version or version of gcc)
Python 3.8.5 (default, Jul 21 2020, 10:48:26)

### What did you do?
Ran the integration tests for google-python-storage, which includes use of the google-cloud-iam library for the system tests for the _signing module. Encountered fatal error. Reproduced locally by installing grpcio==1.49.0rc1 (does not reproduce with grpcio==1.47.0) and running tests locally as well.

### What did you expect to see?
Successful test.

### What did you see instead?
```
nox > py.test --quiet tests/system
...............Fatal Python error: Aborted

Current thread 0x00007f0b34777740 (most recent call first):
  File "/tmpfs/src/github/python-storage/.nox/system-3-8/lib/python3.8/site-packages/grpc/_channel.py", line 1478 in __init__
  File "/tmpfs/src/github/python-storage/.nox/system-3-8/lib/python3.8/site-packages/grpc/__init__.py", line 2004 in secure_channel
  File "/tmpfs/src/github/python-storage/.nox/system-3-8/lib/python3.8/site-packages/google/api_core/grpc_helpers.py", line 297 in create_channel
  File "/tmpfs/src/github/python-storage/.nox/system-3-8/lib/python3.8/site-packages/google/cloud/iam_credentials_v1/services/iam_credentials/transports/grpc.py", line 224 in create_channel
  File "/tmpfs/src/github/python-storage/.nox/system-3-8/lib/python3.8/site-packages/google/cloud/iam_credentials_v1/services/iam_credentials/transports/grpc.py", line 169 in __init__
  File "/tmpfs/src/github/python-storage/.nox/system-3-8/lib/python3.8/site-packages/google/cloud/iam_credentials_v1/services/iam_credentials/client.py", line 429 in __init__
  File "/tmpfs/src/github/python-storage/tests/system/test__signing.py", line 262 in test_create_signed_read_url_v4_w_access_token
  File "/tmpfs/src/github/python-storage/.nox/system-3-8/lib/python3.8/site-packages/_pytest/python.py", line 192 in pytest_pyfunc_call
  File "/tmpfs/src/github/python-storage/.nox/system-3-8/lib/python3.8/site-packages/pluggy/_callers.py", line 39 in _multicall
  File "/tmpfs/src/github/python-storage/.nox/system-3-8/lib/python3.8/site-packages/pluggy/_manager.py", line 80 in _hookexec
  File "/tmpfs/src/github/python-storage/.nox/system-3-8/lib/python3.8/site-packages/pluggy/_hooks.py", line 265 in __call__
  File "/tmpfs/src/github/python-storage/.nox/system-3-8/lib/python3.8/site-packages/_pytest/python.py", line 1761 in runtest
  File "/tmpfs/src/github/python-storage/.nox/system-3-8/lib/python3.8/site-packages/_pytest/runner.py", line 166 in pytest_runtest_call
  File "/tmpfs/src/github/python-storage/.nox/system-3-8/lib/python3.8/site-packages/pluggy/_callers.py", line 39 in _multicall
  File "/tmpfs/src/github/python-storage/.nox/system-3-8/lib/python3.8/site-packages/pluggy/_manager.py", line 80 in _hookexec
  File "/tmpfs/src/github/python-storage/.nox/system-3-8/lib/python3.8/site-packages/pluggy/_hooks.py", line 265 in __call__
  File "/tmpfs/src/github/python-storage/.nox/system-3-8/lib/python3.8/site-packages/_pytest/runner.py", line 259 in <lambda>
  File "/tmpfs/src/github/python-storage/.nox/system-3-8/lib/python3.8/site-packages/_pytest/runner.py", line 338 in from_call
  File "/tmpfs/src/github/python-storage/.nox/system-3-8/lib/python3.8/site-packages/_pytest/runner.py", line 258 in call_runtest_hook
  File "/tmpfs/src/github/python-storage/.nox/system-3-8/lib/python3.8/site-packages/_pytest/runner.py", line 219 in call_and_report
  File "/tmpfs/src/github/python-storage/.nox/system-3-8/lib/python3.8/site-packages/_pytest/runner.py", line 130 in runtestprotocol
  File "/tmpfs/src/github/python-storage/.nox/system-3-8/lib/python3.8/site-packages/_pytest/runner.py", line 111 in pytest_runtest_protocol
  File "/tmpfs/src/github/python-storage/.nox/system-3-8/lib/python3.8/site-packages/pluggy/_callers.py", line 39 in _multicall
  File "/tmpfs/src/github/python-storage/.nox/system-3-8/lib/python3.8/site-packages/pluggy/_manager.py", line 80 in _hookexec
  File "/tmpfs/src/github/python-storage/.nox/system-3-8/lib/python3.8/site-packages/pluggy/_hooks.py", line 265 in __call__
  File "/tmpfs/src/github/python-storage/.nox/system-3-8/lib/python3.8/site-packages/_pytest/main.py", line 347 in pytest_runtestloop
  File "/tmpfs/src/github/python-storage/.nox/system-3-8/lib/python3.8/site-packages/pluggy/_callers.py", line 39 in _multicall
  File "/tmpfs/src/github/python-storage/.nox/system-3-8/lib/python3.8/site-packages/pluggy/_manager.py", line 80 in _hookexec
  File "/tmpfs/src/github/python-storage/.nox/system-3-8/lib/python3.8/site-packages/pluggy/_hooks.py", line 265 in __call__
  File "/tmpfs/src/github/python-storage/.nox/system-3-8/lib/python3.8/site-packages/_pytest/main.py", line 322 in _main
  File "/tmpfs/src/github/python-storage/.nox/system-3-8/lib/python3.8/site-packages/_pytest/main.py", line 268 in wrap_session
  File "/tmpfs/src/github/python-storage/.nox/system-3-8/lib/python3.8/site-packages/_pytest/main.py", line 315 in pytest_cmdline_main
  File "/tmpfs/src/github/python-storage/.nox/system-3-8/lib/python3.8/site-packages/pluggy/_callers.py", line 39 in _multicall
  File "/tmpfs/src/github/python-storage/.nox/system-3-8/lib/python3.8/site-packages/pluggy/_manager.py", line 80 in _hookexec
  File "/tmpfs/src/github/python-storage/.nox/system-3-8/lib/python3.8/site-packages/pluggy/_hooks.py", line 265 in __call__
  File "/tmpfs/src/github/python-storage/.nox/system-3-8/lib/python3.8/site-packages/_pytest/config/__init__.py", line 164 in main
  File "/tmpfs/src/github/python-storage/.nox/system-3-8/lib/python3.8/site-packages/_pytest/config/__init__.py", line 187 in console_main
  File "/tmpfs/src/github/python-storage/.nox/system-3-8/bin/py.test", line 8 in <module>
nox > Command py.test --quiet tests/system failed with exit code -6
nox > Session system-3.8 failed.
```

### Anything else we should know about your project / environment?

A Google Cloud project, with credentials downloaded and referenced in the GOOGLE_APPLICATION_CREDENTIALS env variable, is needed to run cloud integration tests.

If reproduction is difficult please reach out (if a Googler is reading this, reach out internally). I will be on vacation from Aug. 24; secondary is @cojenco.

**Comment by gnossen** [comment] 2022-10-04 18:43
@andrewsg Can you please share reproduction instructions? Which repo should I pull? Should I just run `nox > py.test --quiet tests/system`?

**Comment by andrewsg** [comment] 2022-10-04 18:47
@gnossen Thanks for your response. In order to unblock our system tests we've pinned to a stable version. I'll produce fresh repro instructions that get around this.

**Comment by andrewsg** [comment] 2022-10-04 19:06
@gnossen This bug still repros against ==1.49.0rc1 but no longer repros against the most recent version. If you'd still like to investigate, I've created a branch grpcio-repro on the python-storage repo. Repro steps:

Configure Google Cloud authentication with a cloud project. I personally use a service account key with GOOGLE_APPLICATION_CREDENTIALS env variable set, as per https://developers.google.com/analytics/devguides/config/admin/v1/quickstart-client-libraries - other methods should also work.

Clone the python-storage repo and open the branch `grpcio-repro`.

Run the command `nox -s system 3.9` or replace 3.9 with another supported Python 3.x version you have installed such a 3.8.

Observe the crash as reported above.

**Comment by XuanWang-Amos** [comment] 2023-04-14 23:31
Thanks for the reply, I'm closing this issue since it's fixed in latest version.

Feel free to reopen it or file a new one If this happens again.

**Closed by XuanWang-Amos** 2023-04-14 23:31 UTC
Labels: kind/bug, lang/Python, priority/P2
