### ISSUE TITLE
grpc configures the root logger

### ISSUE THREAD

**Issue by luk** [grpc/grpc#17017] opened 2018-10-26 13:11 UTC
### What version of gRPC and what language are you using?
python / grpcio 1.16.0
 
### What operating system (Linux, Windows, …) and version?
 Linux / not relevant
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
not relevant
 
### What did you do?
Use grpcio, use `logging.basicConfig` to config the logger in my `main` entry point.
 
### What did you expect to see?
Grpc does not mess with the logging configuration.
 
### What did you see instead?
As of Commit a20e2073c1c53cbdd81a4fb750982a0b13e0c24e grpc configures the root logger. As documented in https://docs.python.org/3/library/logging.html#logging.basicConfig, subsequent calls to basicConfig will not do anything. This breaks logging configuration of many users of gprcio.
I would suggest to revert this  commit.

**Comment by pinchopanda** [comment] 2018-10-28 14:51
Facing Same Issue. Any workarounds?

**Comment by luk** [comment] 2018-10-29 07:36
We currently pinned the package to 1.15.0

**Comment by scotloach** [comment] 2018-10-30 02:06
I ran into this too, this causes big problems!

**Comment by nikhilk** [comment] 2018-10-30 20:38
+1 ... a library should not mess with application config associated with logging.

In my case, I am clearing out the handlers list before adding my own handler. And then also set logging level etc. for the root logger explicitly, after importing something in turn imports grpc. Ugly, and painfully found this, after this introduced a bunch of noise into the logs (since calling basicConfig adds a default log handler).

**Comment by srini100** [comment] 2018-10-30 23:40
Looks like this will need to be reverted along with the original change that introduced module level logger.
cc: @ghostwriternr

**Comment by nicolasnoble** [comment] 2018-10-30 23:43
Associated pull request for reference (where some discussion is happening there too): https://github.com/grpc/grpc/pull/16378

**Comment by gnossen** [comment] 2018-11-02 22:14
Resolved by https://github.com/grpc/grpc/pull/17064

**Comment by gnossen** [comment] 2018-11-02 22:14
https://github.com/grpc/grpc/pull/17064

**Closed by gnossen** 2018-11-02 22:14 UTC
Labels: lang/Python, priority/P1

**Comment by srini100** [comment] 2018-11-07 20:01
1.16.1rc1 with this fix is released. If no issues reported, expect the final release in about a week.
cc: @luk @nikhilk @scotloach @pinchopanda

**Comment by pinchopanda** [comment] 2018-11-08 11:20
@srini100 
Confirmed to be fixed on 1.16.1.rc1

**Comment by gnossen** [comment] 2018-11-15 16:47
Fix released as `1.16.1`.
