### ISSUE TITLE
iOS throws error and sometimes crash when enter background and go back foreground then send request

### ISSUE THREAD

**Issue by juxingzhutou** [grpc/grpc#3076] opened 2015-08-26 06:10 UTC
As we know, on iOS, after app enter background a few minutes,  it will stop work. Then if I make it go back to foreground and send a request to server, app will throws a error which code is GRPCErrorCodeUnavailable(14, == GRPC_STATUS_UNAVAILABLE) and sometime it will crash because 'gpr_mu_lock' assert fail.

Thank you for any help.

**Comment by juxingzhutou** [comment] 2015-08-27 15:33
I fix this issue by clean cached channels when app will enter foreground. But I think this maybe a bug about channel management when app enter background and need be fixed.

**Comment by sipdar** [comment] 2015-09-01 05:21
i have  same problem  How to clean cached channels when app will enter foreground.?

**Comment by juxingzhutou** [comment] 2015-09-01 08:36
First, add a method to Class `GRPCChannel` to clean the cached channels

In file 'GRPCChannel.m'

```
static NSMutableDictionary *channelCache;

@implementation GRPCChannel

+ (void)cleanupChannels {
    channelCache = [NSMutableDictionary dictionary];
}

+ (instancetype)channelToHost:(NSString *)host {
  // TODO(mlumish): Investigate whether a cache with strong links is a good idea
  static dispatch_once_t cacheInitialization;
  dispatch_once(&cacheInitialization, ^{
    channelCache = [NSMutableDictionary dictionary];
  });
  GRPCChannel *channel = channelCache[host];
  if (!channel) {
    channel = [[self alloc] initWithHost:host];
    channelCache[host] = channel;
  }
  return channel;
}
```

Then call this method in appdelegate

```
- (void)applicationWillEnterForeground:(UIApplication *)application {
    [GRPCChannel cleanupChannels];
}
```

**Comment by jcanizales** [comment] 2015-11-06 20:30
Hi @juxingzhutou and @sipdar, sorry that this issue fell through the cracks for so long.

Based on your detailed report and the workaround you found, I think I know how to fix this issue automatically, so that one doesn't have to remember and clean up the cached channels in the App Delegate.

Cheers,
Jorge

**Comment by xinqianli** [comment] 2016-03-04 09:29
@jcanizales any update? Is it fixed now? We have the same problem.

**Comment by jcanizales** [comment] 2016-03-11 20:48
Hi guys, sorry for the late response. https://github.com/grpc/grpc/pull/5720 will make this easier to solve, which is one of the reasons I did it first. After that and other two PRs are done, this is next on my plate.

**Comment by jcanizales** [comment] 2016-05-04 05:19
Here's how we can detect that the app is going to the background or coming back to the foreground: http://stackoverflow.com/a/9012734/3642676

**Comment by makdharma** [comment] 2016-06-16 17:10
I am not able to reproduce this bug. I modified the route_guide app (PR #6934) to show the log on the screen as a preliminary step. Then I switched back and forth between airplay mode, and switching on/off the wifi. The app does not crash. The bug may have been fixed with @jcanizales PR #5720, along with numerous fixes that went into C core in this area.

**Comment by makdharma** [comment] 2016-06-16 17:11
@xinqianli - Please confirm if you still see this problem after 0.14 release.

**Closed** 2016-06-20 23:56 UTC
Labels: bug, ObjC, P0, to close, wrapped languages

**Comment by xinqianli** [comment] 2016-06-24 15:04
@makdharma We do not reproduce the problem after upgrading to 0.14 release. Thanks;-)
