### ISSUE TITLE
grpc_python_plugin crashes in OpenForAppend.

### ISSUE THREAD

**Issue by yasushi-saito** [grpc/grpc#8820] opened 2016-11-22 05:37 UTC
With the combination of grpc 1.0.1, protobuf 3.0.2, and using bazel as a build system, grpc_python_plugin crashes in python_generator.cc:788

CodedOutputStream pb2_coded_out(pb2_output.get()); 

because pb2_output is null. Looking at the code, OpenForAppend isn't implemented for 
google::protobuf::compiler::GeneratorResponseContext. OpenForAppend always returns NULL. I'm not sure whether this is a bug in grpc or protobuf, but it needs fixing.

**Comment by soltanmm-google** [comment] 2016-11-22 21:17
Duplicate of https://github.com/grpc/grpc/issues/8753 .

**Closed by soltanmm-google** 2016-11-22 21:17 UTC
Labels: protoc plugins, python
