### ISSUE TITLE
C# Grpc - Error : "The "AdditionalProtocArguments" parameter is not supported by the "ProtoCompile" task. Verify the parameter exists on the task, and it is a settable public instance property."

### ISSUE THREAD

**Issue by Zethzer** [grpc/grpc#26116] opened 2021-04-28 22:58 UTC
### What version of gRPC and what language are you using?

Package "Grpc.AspNetCore" and its dependencies from Nuget in version 2.37.0 with C# language

### What operating system (Linux, Windows,...) and version?

Windows 10 20H2

### What runtime / compiler are you using (e.g. python version or version of gcc)

Visual Studio 2019 16.9.4

### What did you do?
I just upgrade the package Nuget from 2.36 to 2.37.

### What did you expect to see?
My client only proto file compile.

### What did you see instead?
My proto file on the server project configured on "Server only" compiles without any errors.

On the client side : I created a link via "Connected Services" to the proto file of the server side and configured on "Client only" don't want to compile with these errors :
![errors](https://user-images.githubusercontent.com/5558160/116482483-862aca00-a885-11eb-97d5-8112b748abd7.JPG)

I already try to copy the file instead of create a link via "Connected Services" and update the namespace. I have the same errors.

**Comment by nicovota** [comment] 2021-05-03 06:00
On our project we had the same error but only in conjunction with Newtonsoft.Json upgrade:

    <PackageReference Include="Newtonsoft.Json" Version="12.0.3" />
-->
    <PackageReference Include="Newtonsoft.Json" Version="13.0.1" />

**Comment by Zethzer** [comment] 2021-05-03 09:53
Hi ! I receive a notification of @nicovota with this message (but I can't see it on the issue) :
![Capture](https://user-images.githubusercontent.com/5558160/116862510-275aad00-ac05-11eb-8036-7e1b65fc2a26.JPG)
 
So, I try to remove the Newtonsoft.Json in version 13.0.1 (and all reference in the code). And clean/restore/build the project. I have the same build errors.

I try to install Newtonsoft.Json in version 12.0.3 like his screenshot and put back references in the code. Then clean/restore/build the project and it compiles fine. All works.

So maybe, there's a lead with Newtonsoft.Json in version 13.0.1. Maybe something conflicts with Grpc.AspNetCore in version 2.37.0.

**Comment by jtattermusch** [comment] 2021-05-05 10:47
From the error message it seems that somehow the Visual studio hasn't fully picked up the Grpc.Tools nuget package upgrade. 
The AdditionalProtocArguments has been added in version 2.37.0, but AFAIK it works just fine.
Have you tried restarting visual studio to see if it fixes the problem?

**Comment by ramondeklein** [comment] 2021-05-21 09:20
@jtattermusch I had the same problem. I upgraded the packages, while keeping Visual Studio open. Build failed with the error as listed in this issue. After restarting VS2019 it was fine...

**Comment by jtattermusch** [comment] 2021-06-23 11:52
From the testimonies it looks the problem is either
- not using a new-enough version of Grpc.Tools (AdditionalProtocArguments has been added in version 2.37.0)
- Visual Studio not picking up the newly added "AdditionalProtocArguments" attribute when the Grpc.Tools package is upgraded from pre-2.37.0 to 2.37.0 or higher (that's not a Grpc.Tools problem though and it can be solved by restarting VS).

Closing.

**Closed by jtattermusch** 2021-06-23 11:52 UTC
Labels: kind/bug, lang/C#, priority/P2
