### ISSUE TITLE
Bazel test flake //test/core/end2end:h2_full+workarounds_test@retry_streaming@poller=poll-cv

### ISSUE THREAD

**Issue by yashykt** [grpc/grpc#16473] opened 2018-08-28 00:46 UTC
This doesn't look like the usual connection issues we've been seeing on bazel.  

```
exec ${PAGER:-/usr/bin/less} "$0" || exit 1
Executing tests from //test/core/end2end:h2_full+workarounds_test@retry_streaming@poller=poll-cv
-----------------------------------------------------------------------------
D0827 22:19:10.149167525      20 test_config.cc:391]         test slowdown factor: sanitizer=1, fixture=1, poller=1, total=1
src/core/ext/filters/client_channel/lb_policy/subchannel_list.h:535:31: runtime error: downcast of address 0x7f4138001d90 which does not point to an object of type 'grpc_core::(anonymous namespace)::PickFirst::PickFirstSubchannelList'
0x7f4138001d90: note: object is of type 'grpc_core::SubchannelList<grpc_core::(anonymous namespace)::PickFirst::PickFirstSubchannelList, grpc_core::(anonymous namespace)::PickFirst::PickFirstSubchannelData>'
 41 7f 00 00  a8 32 33 01 00 00 00 00  28 e1 0c 02 00 00 00 00  01 00 00 00 00 00 00 00  50 19 00 38
              ^~~~~~~~~~~~~~~~~~~~~~~
              vptr for 'grpc_core::SubchannelList<grpc_core::(anonymous namespace)::PickFirst::PickFirstSubchannelList, grpc_core::(anonymous namespace)::PickFirst::PickFirstSubchannelData>'
E0827 22:19:10.153643862      20 cq_verifier.cc:235]         actual success does not match expected: tag(2) GRPC_OP_COMPLETE success=1 test/core/end2end/tests/retry_streaming.cc:206
*******************************
Caught signal SIGABRT
test/core/end2end/h2_full+workarounds_test[0x10f1654]
/lib/x86_64-linux-gnu/libpthread.so.0(+0x11390)[0x7f4149176390]
/lib/x86_64-linux-gnu/libc.so.6(gsignal+0x38)[0x7f4148123428]
/lib/x86_64-linux-gnu/libc.so.6(abort+0x16a)[0x7f414812502a]
test/core/end2end/h2_full+workarounds_test[0x6988bb]
test/core/end2end/h2_full+workarounds_test(_Z9cq_verifyP11cq_verifier+0x356)[0x694f46]
test/core/end2end/h2_full+workarounds_test[0x59e830]
test/core/end2end/h2_full+workarounds_test(_Z15retry_streaming24grpc_end2end_test_config+0xf4)[0x59d314]
test/core/end2end/h2_full+workarounds_test(_Z18grpc_end2end_testsiPPc24grpc_end2end_test_config+0x7ad8)[0x545aa8]
test/core/end2end/h2_full+workarounds_test(main+0x126)[0x53d6e6]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf0)[0x7f414810e830]
test/core/end2end/h2_full+workarounds_test(_start+0x29)[0x51cf69]
Aborted (core dumped)
```

Seen on #16469

**Comment by yashykt** [comment] 2018-09-05 18:58
Saw a similar bug in //test/core/end2end:h2_http_proxy_test@simple_request@poller=poll-cv
at #16562

**Comment by AspirinSJL** [comment] 2018-09-05 21:06
Duplicate of https://github.com/grpc/grpc/issues/15410

**Closed by AspirinSJL** 2018-09-05 21:06 UTC
Labels: area/core, infra/bazel test failures, kind/bug, lang/core, priority/P2
