### ISSUE TITLE
grpc_cpp_plugin not installed when installing grpc with cmake

### ISSUE THREAD

**Issue by ghost** [grpc/grpc#26120] opened 2021-04-29 09:56 UTC
### What version of gRPC and what language are you using?
v1.37.0

### What operating system (Linux, Windows,...) and version?
Linux - Ubuntu 18.04

### What runtime / compiler are you using (e.g. python version or version of gcc)
gcc - CMAKE

### What did you do?
I am trying to build grpc using cmake in my project like this,

FetchContent_Declare(
  gRPC
  GIT_REPOSITORY https://github.com/grpc/grpc
  GIT_TAG        v1.37.0
  )
set(FETCHCONTENT_QUIET OFF)
FetchContent_MakeAvailable(gRPC)

### What did you expect to see?
Looks like the grpc_cpp_plugin is not installed when I do this. This issue seems to be similar to https://github.com/grpc/grpc/issues/13841. But the steps in https://github.com/grpc/grpc/issues/13841 does not seem to install grpc_cpp_plugin. Is this issue fixed? Any work arounds?

**Comment by jtattermusch** [comment] 2021-05-05 10:12
Basically what @drfloob saying.

I'd be very surprised if grpc_cpp_plugin wasn't being installed by cmake (if the rights cmake flags are used), since we have a distribtest that installs gRPC c++ and then runs helloworld examples (which does require grpc_cpp_plugin to be available) - and that test is passing.
https://github.com/grpc/grpc/blob/9b87fb33bf61847ca05deb788532c2a182e93b26/test/distrib/cpp/run_distrib_test_cmake.sh#L69

So I think the chances are you're not passing the right cmake options (such as `-DgRPC_INSTALL=ON` or so).

**Comment by calvin2021y** [comment] 2021-08-03 08:01
not work even configure with:
```sh
gRPC_INSTALL:BOOL=ON
gRPC_INSTALL_BINDIR:STRING=bin
gRPC_INSTALL_CMAKEDIR:STRING=lib/cmake/grpc
gRPC_INSTALL_INCLUDEDIR:STRING=include
gRPC_INSTALL_LIBDIR:STRING=lib
```

**Comment by drfloob** [comment] 2022-02-09 21:58
I'm closing this as there hasn't been an update in months, and we can't reproduce the problem with the information given.

**Closed by drfloob** 2022-02-09 21:58 UTC
Labels: kind/bug, lang/c++, priority/P2, area/build

**Comment by julius-ziegler** [comment] 2022-08-30 12:59
I have the same problem and I can reproduce this with this script:
```
    git clone -b 'v1.48.0' https://github.com/grpc/grpc /tmp/grpc && \
    cd /tmp/grpc && \
    git submodule update --init && \
    mkdir -p cmake/build && \
    cd cmake/build && \
    cmake \
        -DBUILD_SHARED_LIBS=ON \
        -DgRPC_INSTALL=ON  \
        -DABSL_ENABLE_INSTALL=ON \
        ../.. && \
    make -j$(nproc) && \
    make install
```

**Comment by melhindi** [comment] 2022-09-07 18:29
@julius-ziegler there is no need to install grpc explicitly.
However, you have to register/discover the binaries that are built by FetchContent.
I found it helpful to have a look at the CMake configuration example that is provided with the examples: https://github.com/grpc/grpc/blob/master/examples/cpp/cmake/common.cmake
Especially, this line is important: https://github.com/grpc/grpc/blob/98a92544b7b5b2f70240811ae4281149db317d1a/examples/cpp/cmake/common.cmake#L92

Based on this observation, I created a PR for another project that provides a simple grpc cmake example. Feel free to have a look: https://github.com/faaxm/exmpl-cmake-grpc/pull/7
Hope this helps.

**Comment by HOYS** [comment] 2023-03-02 06:06
I do appreciate the FetchContent approach to grpc usage. It can be a pain to install separately. One issue I have currently with @melhindi 's approach is that Protobuf is never found. I'm unsure if this has to do with a version change to cmake from gRPC or what.

**Comment by mehrshad-kh** [comment] 2023-08-16 14:24
Just as a workaround, you could install grpc via Homebrew:
`brew install grpc`.
This will install `grpc_cpp_plugin`.
