### ISSUE TITLE
which version grpc will be compatible with protobuf 3.19.4

### ISSUE THREAD

**Issue by revanthvs5** [grpc/grpc#29892] opened 2022-06-03 14:19 UTC
Please share the latest version compatibility for grpc and protobuf.

Already installed protobuf: 3.19.4 for server language go

For client side installed:
grpc: 1.30.0
client language: php
OS: Ubuntu 18.04

Tried with multiple version(grpc and php package version) but no luck
List:
1.42.0
1.38.0

Getting below error:
Class 'Grpc\ChannelCredentials' not found

Tried \Grpc\ChannelCredentials also, but no luck.

In the below doc the version compatibility is only till grpc: 1.30.0 | protobuf: v3.12.2
https://github.com/grpc/grpc/tree/master/src/php

**Comment by s77rt** [comment] 2022-09-25 22:16
a duplicate of #28811
the docs are outdated. Just install perl extension and it should work.

**Closed** 2022-10-04 09:55 UTC
Labels: kind/question, lang/php, priority/P3
