### ISSUE TITLE
The 'Pods' target has transitive dependencies that include static binaries:

### ISSUE THREAD

**Issue by ceoacai** [grpc/grpc#4198] opened 2015-11-22 09:03 UTC
(/Users/xxx/workspace/xcode/iBBS-Swift/Pods/OpenSSL/lib/libcrypto.a and /Users/xxx/workspace/xcode/iBBS-Swift/Pods/OpenSSL/lib/libssl.a)

**Comment by bdotdub** [comment] 2015-11-24 17:18
This is a dupe of #4199

**Closed** 2015-11-24 18:20 UTC
