### ISSUE TITLE
C-Ares cannot find DNS Servers

### ISSUE THREAD

**Issue by ghost** [grpc/grpc#19954] opened 2019-08-14 23:07 UTC
### What version of gRPC and what language are you using?
 C# .Net Standard 2.0
 gRPC 1.21.0

### What operating system (Linux, Windows,...) and version?
 Windows 10 Version 1809
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
 
vbcs.exe via  MSBUILD
 
### What did you do?
If possible, provide a recipe for reproducing the error. Try being specific and include code snippets if helpful.

The client is unable to resolve DNS address of the server unless the GRPC_DNS_RESOLVER environment variable to "native".

### What did you expect to see?
 
I expected gRPC to work out of the box, I would not need to set the GRPC_DNS_RESOLVER environment  variable.
 
### What did you see instead?

C-Ares "Could not contact DNS servers" .
 
Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

Below are the gRPC logs, any help is greatly appreciated!
 
```
I0814 18:33:56.089860 0 T:\src\github\grpc\workspace_csharp_ext_windows_x64\src\core\ext\filters\client_channel\resolving_lb_policy.cc:318: resolving_lb=000002315BE67890: resolver transient failure: {"created":"@1565822036.090000000","description":"DNS resolution failed","file":"T:\src\github\grpc\workspace_csharp_ext_windows_x64\src\core\ext\filters\client_channel\resolver\dns\c_ares\dns_resolver_ares.cc","file_line":358,"grpc_status":14,"referenced_errors":[{"created":"@1565822036.088000000","description":"C-ares status is not ARES_SUCCESS: Could not contact DNS servers","file":"T:\src\github\grpc\workspace_csharp_ext_windows_x64\src\core\ext\filters\client_channel\resolver\dns\c_ares\grpc_ares_wrapper.cc","file_line":244,"referenced_errors":[{"created":"@1565822036.088000000","description":"C-ares status is not ARES_SUCCESS: Could not contact DNS servers","file":"T:\src\github\grpc\workspace_csharp_ext_windows_x64\src\core\ext\filters\client_channel\resolver\dns\c_ares\grpc_ares_wrapper.cc","file_line":244}]}]}
```

**Comment by apolcyn** [comment] 2019-08-14 23:24
As a first thing to check, are you able to try with the 2.23.0-pre1 release. In particular, this release includes this patch: https://github.com/grpc/grpc/pull/19397 (which would fix this if you might be hitting a related error to https://github.com/grpc/grpc/issues/18411#issuecomment-502216322).

**Comment by ObiBobCanobi** [comment] 2019-08-15 12:33
@apolcyn  Thank you for the quick response. Unfortunately, upgrading to 2.23.0-pre1 did not resolve the DNS issue. The log is below.  Is there other information I can collect to help pin point the root cause?

I0815 08:13:58.277055 0 T:\src\github\grpc\workspace_csharp_ext_windows_x64\src\core\ext\filters\client_channel\resolving_lb_policy.cc:260: resolving_lb=0000023E3B42B380: resolver transient failure: {"created":"@1565871238.278000000","description":"DNS resolution failed","file":"T:\src\github\grpc\workspace_csharp_ext_windows_x64\src\core\ext\filters\client_channel\resolver\dns\c_ares\dns_resolver_ares.cc","file_line":357,"grpc_status":14,"referenced_errors":[{"created":"@1565871238.266000000","description":"C-ares status is not ARES_SUCCESS: Could not contact DNS servers","file":"T:\src\github\grpc\workspace_csharp_ext_windows_x64\src\core\ext\filters\client_channel\resolver\dns\c_ares\grpc_ares_wrapper.cc","file_line":244,"referenced_errors":[{"created":"@1565871238.266000000","description":"C-ares status is not ARES_SUCCESS: Could not contact DNS servers","file":"T:\src\github\grpc\workspace_csharp_ext_windows_x64\src\core\ext\filters\client_channel\resolver\dns\c_ares\grpc_ares_wrapper.cc","file_line":244}]}]}

**Comment by apolcyn** [comment] 2019-08-15 17:26
Ok, next thing to check is can you run under the following environment variable settings:

* `GRPC_VERBOSITY=DEBUG`
* `GRPC_TRACE=api,cares_resolver,cares_address_sorting,client_channel`

and share the output?

**Comment by apolcyn** [comment] 2019-08-15 18:01
^ if it's doable, sharing those verbose logs from the 2.23.0-pre1 release would be most interesting

**Comment by ObiBobCanobi** [comment] 2019-08-15 19:13
@apolcyn  you got it. Here are the logs with 2.23.0-pre1. Thank you for the help!

[dnsFailureLogs.txt](https://github.com/grpc/grpc/files/3506867/dnsFailureLogs.txt)

**Comment by apolcyn** [comment] 2019-08-16 19:20
thanks for the logs, have some ideas but I'll have more time to dig in next week.

**Comment by ObiBobCanobi** [comment] 2019-09-04 17:54
@apolcyn  any luck?

**Comment by apolcyn** [comment] 2019-09-05 04:07
Sorry to let this hang. I've been too busy with other things over the last week, and am out of the office next week. So it may actually be ~2 weeks until I'd have time to dig in.

**Comment by AlekzanderDee** [comment] 2019-11-06 22:57
@apolcyn did you manage to get any progress on that? 

We see the same error in Python when gRPC client is pointed to the AWS network loadbalncer, and we pull on of the server instances out of the group:
```
Traceback (most recent call last):
  File "/Users/will/kraken_venv/lib/python3.6/site-packages/syntheseas/protobay/clients/kraken.py", line 90, in health_check
    health_check_response = self.stub.HealthCheck(health_check_request, metadata=self.metadata)
  File "/Users/will/kraken_venv/lib/python3.6/site-packages/grpc/_channel.py", line 565, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/Users/will/kraken_venv/lib/python3.6/site-packages/grpc/_channel.py", line 467, in _end_unary_response_blocking
    raise _Rendezvous(state, None, None, deadline)
grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "DNS resolution failed"
	debug_error_string = "{"created":"@1573079988.460198000","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":3528,"referenced_errors":[{"created":"@1573079988.460192000","description":"Resolver transient failure","file":"src/core/ext/filters/client_channel/resolving_lb_policy.cc","file_line":307,"referenced_errors":[{"created":"@1573079988.460191000","description":"DNS resolution failed","file":"src/core/ext/filters/client_channel/resolver/dns/c_ares/dns_resolver_ares.cc","file_line":358,"grpc_status":14,"referenced_errors":[{"created":"@1573079988.460174000","description":"C-ares status is not ARES_SUCCESS: Could not contact DNS servers","file":"src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_wrapper.cc","file_line":244,"referenced_errors":[{"created":"@1573079988.460155000","description":"C-ares status is not ARES_SUCCESS: Could not contact DNS servers","file":"src/core/ext/filters/client_channel/resolver/dns/c_ares/grpc_ares_wrapper.cc","file_line":244}]}]}]}]}"
```

**Comment by AlekzanderDee** [comment] 2020-05-04 23:47
any luck?

**Comment by mrtristan** [comment] 2020-05-08 18:23
i'm experiencing this issue as well. `GRPC_DNS_RESOLVER=native` does make it work.

on windows, trying to resolve an A record in an AWS private hosted zone http only.

**Comment by rustyx** [comment] 2020-08-19 12:30
Note that this error occurs also when incorrectly invoking `new Channel("https://host:port", ...)` instead of `new Channel("host:port", ...)`

**Comment by crshumate** [comment] 2021-07-02 23:02
A coworker on my team, who doesn't use GH, had to use `GRPC_DNS_RESOLVER=native` to get the .NET Firebase Admin SDK to properly connect to his DB instance. 

Would be nice if there was a more proper fix for this.

**Comment by jtattermusch** [comment] 2022-02-23 16:44
@apolcyn  can we either fix or close?

**Comment by jtattermusch** [comment] 2022-04-29 08:56
This issues seems to be more connected to C-core than the C# layer, so I'm adding the label accordingly (to avoid closing the issue as part of the cleanup following the move of gRPC C# to maintenance branch).

**Comment by piotr-jagiello** [comment] 2022-07-21 13:18
Almost certainly not the problem you're having, but maybe a helpful data point either way - got the same error on Linux from a Python client when trying to resolve "localhost" - turns out I didn't have any entry for localhost in /etc/hosts. Added this and the problem went away:
```
127.0.0.1        localhost
::1              localhost
127.0.1.1        myhostname
```

**Comment by tonydnewell** [comment] 2022-10-20 09:12
We have updated the documentation on NetBIOS and DNS and the use of _ares_ or _native_ DNS resolvers:
https://github.com/grpc/grpc/blob/master/doc/environment_variables.md

This may or may not have helped with this problem, but as the original poster no longer has a GitHub account we can't find out more.

@jtattermusch should we close as the original user has been deleted from GitHub?

**Closed** 2022-10-20 12:47 UTC
Labels: kind/bug, lang/C#, platform/Windows, lang/core, priority/P2

**Comment by lagefreitas** [comment] 2024-11-11 14:56
hello!

Just to add my two cents: it also worked for me by setting the to native the var in my **Python** code when calling **Google Cloud Vision API**:

```python
import os
os.environ["GRPC_DNS_RESOLVER"] = "native"
```

The error I was facing was:

```bash
503 DNS resolution failed for vision.googleapis.com:443: C-ares status is not ARES_SUCCESS qtype=AAAA name=vision.googleapis.com is_balancer=0: Timeout while contacting DNS servers
```

Thanks guys for sharing the solution.

Best, André Lage.
