### ISSUE TITLE
cloud to prod: Failed to build interop image build_docker_java

### ISSUE THREAD

**Issue by AspirinSJL** [grpc/grpc#15456] opened 2018-05-18 20:52 UTC
https://source.cloud.google.com/results/invocations/1294ff55-b56b-408a-90cf-1ba820cd65c3/log

```
2018-05-18 10:17:14,628 WAITING: ETA 128.1 sec; 0 queued, 1 jobs running, 12 complete, 2 failed (load 1.00)
2018-05-18 10:17:24,628 WAITING: ETA 129.0 sec; 0 queued, 1 jobs running, 12 complete, 2 failed (load 1.00)
2018-05-18 10:17:34,629 WAITING: ETA 129.8 sec; 0 queued, 1 jobs running, 12 complete, 2 failed (load 1.00)
2018-05-18 10:17:44,629 WAITING: ETA 130.6 sec; 0 queued, 1 jobs running, 12 complete, 2 failed (load 1.00)
2018-05-18 10:17:54,630 WAITING: ETA 131.5 sec; 0 queued, 1 jobs running, 12 complete, 2 failed (load 1.00)
2018-05-18 10:18:04,630 WAITING: ETA 132.3 sec; 0 queued, 1 jobs running, 12 complete, 2 failed (load 1.00)
2018-05-18 10:18:11,308 PASSED: build_docker_python [time=1594.1sec, retries=0:0]
2018-05-18 10:18:11,308 FAILED: Failed to build interop docker images.
stty: standard input: Inappropriate ioctl for device
[ID: 7195384] Build finished after 1689 secs, exit value: 1
Warning: Permanently added 'localhost' (ECDSA) to the list of known hosts.
Build script failed with exit code: 1
```

**Comment by jtattermusch** [comment] 2018-05-27 21:09
For the issue to be useful, it is important to know which docker images failed to build. Pasting the relevant part of the log:

```
> Task :grpc-context:compileJava
> Task :grpc-context:compileJava FAILED
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':grpc-context:compileJava'.
> Could not resolve all files for configuration ':grpc-context:errorprone'.
   > Could not resolve com.google.errorprone:error_prone_core:2.2.0.
     Required by:
         project :grpc-context
      > Could not resolve com.google.errorprone:error_prone_core:2.2.0.
         > Could not parse POM https://maven-central.storage-download.googleapis.com/repos/central/data/com/google/errorprone/error_prone_core/2.2.0/error_prone_core-2.2.0.pom
            > Could not resolve com.google.errorprone:error_prone_parent:2.2.0.
               > Could not resolve com.google.errorprone:error_prone_parent:2.2.0.
                  > Could not get resource 'https://maven-central.storage-download.googleapis.com/repos/central/data/com/google/errorprone/error_prone_parent/2.2.0/error_prone_parent-2.2.0.pom'.
                     > Could not HEAD 'https://maven-central.storage-download.googleapis.com/repos/central/data/com/google/errorprone/error_prone_parent/2.2.0/error_prone_parent-2.2.0.pom'.
                        > Read timed out
* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
* Get more help at https://help.gradle.org
BUILD FAILED in 1m 38s
1 actionable task: 1 executed
+ EXITCODE=1
+ docker rm -f build_grpc_interop_java_5e14034a-7a06-46b3-84b9-75d9065923e2
build_grpc_interop_java_5e14034a-7a06-46b3-84b9-75d9065923e2
+ exit 1
2018-05-18 09:56:23,425 FAILED: build_docker_java [ret=1, pid=21487, time=286.2sec]
```

**Comment by jtattermusch** [comment] 2018-05-27 21:12
basically a dupe of https://github.com/grpc/grpc/issues/13379.

**Closed by jtattermusch** 2018-05-27 21:12 UTC
Labels: area/build, infra/BUILDPONY, lang/Java

**Comment by AspirinSJL** [comment] 2018-05-27 23:46
I see. Thanks!
