### ISSUE TITLE
Python protoc compiler plugin segfaults

### ISSUE THREAD

**Issue by tudor** [grpc/grpc#8853] opened 2016-11-24 05:47 UTC
The Python protoc compiler segfaults with grpc compiled from trunk at 5ac82e2 (protobuf at 39f9b43)

I debugged a bit and the cause seems to be https://github.com/grpc/grpc/commit/d953959e2bafd645b6ed674861a310daba5f80ae#commitcomment-19947519

This happens on Ubuntu 16.04, but I suspect it would be the same on all platforms.

Repro: 

`/usr/local/bin/protoc --python_out=. --grpc_out=. --plugin=protoc-gen-grpc=/usr/local/bin/grpc_python_plugin foo.proto`

**Comment by tudor** [comment] 2016-11-24 05:52
Pasting from the commit comment, as linking to a commit comment doesn't seem to work:

**Comment by soltanmm-google** [comment] 2016-12-01 01:35
Duplicate of #8753.

**Closed by soltanmm-google** 2016-12-01 01:35 UTC
Labels: protoc plugins, python
