### ISSUE TITLE
failed: run_tests_grpc-node_macos_opt_native failing in 100% cases

### ISSUE THREAD

**Issue by ZhouyihaiDing** [grpc/grpc#12857] opened 2017-10-06 01:21 UTC
I think it's flaky.
From #12760 
https://kokoro.corp.google.com/job/grpc/job/macos/job/pull_request/job/grpc_basictests_opt/2662/
and #12797 
https://kokoro.corp.google.com/job/grpc/job/macos/job/pull_request/job/grpc_basictests_opt/2664/
```
[16:57:31] Error: Command failed: npm install --build-from-source --unsafe-perm
    at /Volumes/BuildData/tmpfs/src/github/grpc/grpc-node/node_modules/execa/index.js:236:11
    at process._tickCallback (node.js:438:9)

2017-10-05 16:57:31,376 FAILED: tools/run_tests/helper_scripts/run_grpc-node.sh [ret=1, pid=90369]
2017-10-05 16:57:31,377 FAILED: tools/run_tests/helper_scripts/run_grpc-node.sh
2017-10-05 16:57:31,383 FAILED: Some tests failed

2017-10-05 16:57:31,416 FAILED: run_tests_grpc-node_macos_opt_native [ret=2, pid=89555]
2017-10-05 16:57:31,420 START: run_tests_ruby_macos_opt_native
```

**Comment by jtattermusch** [comment] 2017-10-06 13:04
@ZhouyihaiDing  a few minor things:
- you need to include a sponge link (kokoro build links are ephemeral as kokoro only preserves X last builds)
- you need the "BUILDPONY" label so issue can be found by others.

**Comment by jtattermusch** [comment] 2017-10-06 13:05
This is failing in 100% cases on master.

The actual error message:
```
CXX(target) Release/obj.target/grpc/deps/grpc/src/core/ext/filters/max_age/max_age_filter.o
  CXX(target) Release/obj.target/grpc/deps/grpc/src/core/ext/filters/message_size/message_size_filter.o
  CXX(target) Release/obj.target/grpc/deps/grpc/src/core/ext/filters/workarounds/workaround_cronet_compression_filter.o
  CXX(target) Release/obj.target/grpc/deps/grpc/src/core/ext/filters/workarounds/workaround_utils.o
  CXX(target) Release/obj.target/grpc/deps/grpc/src/core/plugin_registry/grpc_plugin_registry.o
  LIBTOOL-STATIC Release/libgrpc.a
make: *** No rule to make target `Release/obj.target/gpr/deps/grpc/src/core/lib/profiling/basic_timers.o', needed by `Release/libgpr.a'.  Stop.
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/kbuilder/.nvm/versions/node/v4.8.4/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:12)
gyp ERR! System Darwin 15.6.0
```

https://sponge.corp.google.com/target?id=cfc1dd35-48f2-4717-9e85-4c8daeded791&target=github/grpc/grpc-node_macos_opt_native&searchFor=&show=FAILED&sortBy=STATUS

**Comment by jtattermusch** [comment] 2017-10-06 13:14
Probably started after https://github.com/grpc/grpc/pull/12692 got merged.
CC @yashykt

**Comment by yashykt** [comment] 2017-10-06 14:49
This is more of a Kokoro issue. It will be resolved once the previous object files are cleaned.

**Comment by jtattermusch** [comment] 2017-10-06 15:09
@yashykt  I haven't looked into it in-depth but I am pretty sure it's not a kokoro issue (there's a fresh worker each time the job runs, so there's no such thing as "cleaning up previous object files"). I think it will be resolved once changes from your PR are migrated over to grpc-node repo (we've had a similar case recently - see https://github.com/grpc/grpc/issues/12781).

**Comment by jtattermusch** [comment] 2017-10-06 15:12
I think it's more about how grpc-node tests are setup - basically major changes in C core need to be reflected in grpc-node repo immediatelly, otherwise the grpc-node tests will fail (I get why why want to run grpc-node tests on grpc/grpc, but the side effects of it are pretty unfortunate).
@murgatroid99  knows more about grpc-node tests.

**Comment by murgatroid99** [comment] 2017-10-06 16:28
That test script regenerates the binding.gyp file from this repo's build.yaml, so non-API-breaking changes in the C core should not cause that test to break. That other issue was different because it broke the core API.

And we think that that's a Kokoro problem because the failure was not reproducible on our own desktops.

**Comment by murgatroid99** [comment] 2017-10-06 17:15
@matt-kwong and @nicolasnoble are more familiar with the Kokoro testing stuff for grpc-node

**Comment by matt-kwong** [comment] 2017-10-06 19:03
It was a Docker issue. It didn't have Mako installed, so it couldn't regenerate binding.gyp in grpc/grpc-node, so it would use the old one. It was fine until now because nothing major changed.

**Closed** 2017-10-06 22:27 UTC
Labels: infra/BUILDPONY, priority/P1

**Comment by jtattermusch** [comment] 2017-10-09 10:25
Thanks for the fix!
