### ISSUE TITLE
cloud_to_cloud:node:c++_server:large_unary  TIMEOUT

### ISSUE THREAD

**Issue by dgquintas** [grpc/grpc#13220] opened 2017-11-01 18:25 UTC
https://sponge.corp.google.com/target?id=e033ec9e-0591-4462-98e2-29037fc2690a&target=github/grpc&searchFor=&show=ALL&sortBy=STATUS

**Comment by jtattermusch** [comment] 2017-11-06 15:10
Dupe of https://github.com/grpc/grpc/issues/13253

**Closed by jtattermusch** 2017-11-06 15:10 UTC
Labels: infra/BUILDPONY, lang/node
