### ISSUE TITLE
Cloud to Prod Auth Interop Tests are Failing

### ISSUE THREAD

**Issue by ncteisen** [grpc/grpc#9287] opened 2017-01-10 00:29 UTC
The cloud_to_prod_auth tests have been failing for a few days now. See https://grpc-testing.appspot.com/job/gRPC_interop_master/10220/#showFailuresLink.

**Comment by matt-kwong** [comment] 2017-01-10 17:44
This was an issue that was happening on grpc-canary-interop2 and was caused by me recreating the VM on Friday to resolve some other interop flake. It should be fixed now, but I'll leave this issue open so others can see why their interop pull request test was failing.

**Closed** 2017-01-11 22:04 UTC
Labels: interop
