### ISSUE TITLE
Gunicorn+Gevent Troubles

### ISSUE THREAD

**Issue by yaalaa** [grpc/grpc#15071] opened 2018-04-15 19:29 UTC
I use Python, Google App Engine Flexible VMs.

Here's the current `requiements.txt`
[requirements.txt](https://github.com/grpc/grpc/files/1913208/requirements.txt)

I've tried v1.11.0 (#14561 promises) a day ago and noticed Gunicorn workers get segfault at their start:
```
kernel: [ 735.355126] gunicorn[6538]: segfault at 30 ip 00007f17641970ca sp 00007ffe919a8bf0 error 4 in cygrpc.so[7f17640fb000+326000]
```
It's GAE Flexible VM log.

Today I've set to reproduce the issue with minimum code, the same Py modules:
( a ) locally on Mac
( b ) at GAE

Here's what I've got on Mac:
- no segfault
- no normal work, it seems workers get frozen forever

Here's the sources I use:
[arch_001.zip](https://github.com/grpc/grpc/files/1913237/arch_001.zip)
Start app by `PORT=8000 honcho start`

Note I've inserted patch suggested at #14561 at `post_fork` callback.

I hope I'd get some results with the same sources from GAE VM.

**Comment by kpayson64** [comment] 2018-04-16 17:34
I think the issue is where you are placing the event-loop shim.

I hacked up a hello-world example to use your config shown below, and it seems like things were working:

app.py
```
from __future__ import print_function

from gevent import monkey
monkey.patch_all()

import grpc.experimental.gevent
grpc.experimental.gevent.init_gevent()

import grpc

import helloworld_pb2
import helloworld_pb2_grpc

import flask


app = flask.Flask( __name__ )


@app.route( '/' )
def handle_root():
  channel = grpc.insecure_channel('localhost:50051')
  stub = helloworld_pb2_grpc.GreeterStub(channel)
  response = stub.SayHello(helloworld_pb2.HelloRequest(name='you'))
  return response.message
```

Note the placement of the monkey-patch.  Can you try doing the same thing with your app?

**Comment by yaalaa** [comment] 2018-04-16 19:06
Here you are:
[arch_002.zip](https://github.com/grpc/grpc/files/1916774/arch_002.zip)
Looks correct?

Nothing has changed, actually. Or, better say, you hit the nail on the head. Not sure.
Note in my code I've added the following line after the patch
```
print( 'GRPC patched' )
```

Steps:
- start app by `PORT=800 honcho start`
- get by `curl localhost:8000`

`curl` gives me: `curl: (52) Empty reply from server`
App gives me:
```
18:59:28 gunicorn.1 | [2018-04-16 18:59:28 +0300] [74037] [INFO] Starting gunicorn 19.7.1
18:59:28 gunicorn.1 | [2018-04-16 18:59:28 +0300] [74037] [DEBUG] Arbiter booted
18:59:28 gunicorn.1 | [2018-04-16 18:59:28 +0300] [74037] [INFO] Listening at: http://0.0.0.0:8000 (74037)
18:59:28 gunicorn.1 | [2018-04-16 18:59:28 +0300] [74037] [INFO] Using worker: gevent
18:59:28 gunicorn.1 | [2018-04-16 18:59:28 +0300] [74037] [INFO] gunicorn_config.pre_fork: worker (pid: [booting])
18:59:28 gunicorn.1 | [2018-04-16 18:59:28 +0300] [74040] [INFO] Booting worker with pid: 74040
18:59:28 gunicorn.1 | [2018-04-16 18:59:28 +0300] [74040] [INFO] gunicorn_config.post_fork: worker spawned (pid: 74040)
18:59:28 gunicorn.1 | [2018-04-16 18:59:28 +0300] [74037] [INFO] gunicorn_config.pre_fork: worker (pid: [booting])
18:59:28 gunicorn.1 | [2018-04-16 18:59:28 +0300] [74041] [INFO] Booting worker with pid: 74041
18:59:28 gunicorn.1 | [2018-04-16 18:59:28 +0300] [74041] [INFO] gunicorn_config.post_fork: worker spawned (pid: 74041)
18:59:28 gunicorn.1 | [2018-04-16 18:59:28 +0300] [74037] [INFO] gunicorn_config.pre_fork: worker (pid: [booting])
18:59:28 gunicorn.1 | [2018-04-16 18:59:28 +0300] [74042] [INFO] Booting worker with pid: 74042
18:59:28 gunicorn.1 | [2018-04-16 18:59:28 +0300] [74042] [INFO] gunicorn_config.post_fork: worker spawned (pid: 74042)
18:59:28 gunicorn.1 | [2018-04-16 18:59:28 +0300] [74037] [INFO] gunicorn_config.pre_fork: worker (pid: [booting])
18:59:28 gunicorn.1 | [2018-04-16 18:59:28 +0300] [74043] [INFO] Booting worker with pid: 74043
18:59:28 gunicorn.1 | [2018-04-16 18:59:28 +0300] [74043] [INFO] gunicorn_config.post_fork: worker spawned (pid: 74043)
18:59:28 gunicorn.1 | [2018-04-16 18:59:28 +0300] [74037] [DEBUG] 4 workers
18:59:28 gunicorn.1 | [2018-04-16 18:59:28 +0300] [74040] [INFO] gunicorn_config.post_worker_init:
18:59:29 gunicorn.1 | [2018-04-16 18:59:29 +0300] [74041] [INFO] gunicorn_config.post_worker_init:
18:59:29 gunicorn.1 | [2018-04-16 18:59:29 +0300] [74042] [INFO] gunicorn_config.post_worker_init:
18:59:29 gunicorn.1 | [2018-04-16 18:59:29 +0300] [74043] [INFO] gunicorn_config.post_worker_init:
18:59:39 gunicorn.1 | [2018-04-16 18:59:39 +0300] [74043] [DEBUG] GET /
18:59:40 gunicorn.1 | [2018-04-16 18:59:40 +0300] [74037] [INFO] gunicorn_config.pre_fork: worker (pid: [booting])
18:59:40 gunicorn.1 | [2018-04-16 18:59:40 +0300] [74056] [INFO] Booting worker with pid: 74056
18:59:40 gunicorn.1 | [2018-04-16 18:59:40 +0300] [74056] [INFO] gunicorn_config.post_fork: worker spawned (pid: 74056)
18:59:40 gunicorn.1 | [2018-04-16 18:59:40 +0300] [74056] [INFO] gunicorn_config.post_worker_init:

```

After that I trap app by `Ctrl+C` and get this:
```

^C19:01:15 system     | SIGINT received
19:01:15 system     | sending SIGTERM to gunicorn.1 (pid 74037)
19:01:15 gunicorn.1 | [2018-04-16 19:01:15 +0300] [74037] [INFO] Handling signal: term
19:01:15 gunicorn.1 | [2018-04-16 19:01:15 +0300] [74041] [INFO] Worker exiting (pid: 74041)
19:01:15 gunicorn.1 | [2018-04-16 19:01:15 +0300] [74041] [INFO] gunicorn_config.worker_exit:
19:01:15 gunicorn.1 | [2018-04-16 19:01:15 +0300] [74041] [DEBUG] 
19:01:15 gunicorn.1 | # Thread: (140736182567808)
19:01:15 gunicorn.1 | File: "/Users/lev/.python_venvs2/lumin05a/bin/gunicorn", line 11, in <module>
19:01:15 gunicorn.1 |   sys.exit(run())
19:01:15 gunicorn.1 | File: "/Users/lev/.python_venvs2/lumin05a/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 74, in run
19:01:15 gunicorn.1 |   WSGIApplication("%(prog)s [OPTIONS] [APP_MODULE]").run()
19:01:15 gunicorn.1 | File: "/Users/lev/.python_venvs2/lumin05a/lib/python2.7/site-packages/gunicorn/app/base.py", line 203, in run
19:01:15 gunicorn.1 |   super(Application, self).run()
19:01:15 gunicorn.1 | File: "/Users/lev/.python_venvs2/lumin05a/lib/python2.7/site-packages/gunicorn/app/base.py", line 72, in run
19:01:15 gunicorn.1 |   Arbiter(self).run()
19:01:15 gunicorn.1 | File: "/Users/lev/.python_venvs2/lumin05a/lib/python2.7/site-packages/gunicorn/arbiter.py", line 202, in run
19:01:15 gunicorn.1 |   self.manage_workers()
19:01:15 gunicorn.1 | File: "/Users/lev/.python_venvs2/lumin05a/lib/python2.7/site-packages/gunicorn/arbiter.py", line 544, in manage_workers
19:01:15 gunicorn.1 |   self.spawn_workers()
19:01:15 gunicorn.1 | File: "/Users/lev/.python_venvs2/lumin05a/lib/python2.7/site-packages/gunicorn/arbiter.py", line 611, in spawn_workers
19:01:15 gunicorn.1 |   self.spawn_worker()
19:01:15 gunicorn.1 | File: "/Users/lev/.python_venvs2/lumin05a/lib/python2.7/site-packages/gunicorn/arbiter.py", line 597, in spawn_worker
19:01:15 gunicorn.1 |   self.cfg.worker_exit(self, worker)
19:01:15 gunicorn.1 | File: "gunicorn_config.py", line 87, in worker_exit
19:01:15 gunicorn.1 |   for filename, lineno, name, line in traceback.extract_stack(stack):
19:01:15 gunicorn.1 | GRPC patched
19:01:15 gunicorn.1 | [2018-04-16 19:01:15 +0300] [74042] [INFO] Worker exiting (pid: 74042)
19:01:15 gunicorn.1 | [2018-04-16 19:01:15 +0300] [74042] [INFO] gunicorn_config.worker_exit:
19:01:15 gunicorn.1 | [2018-04-16 19:01:15 +0300] [74042] [DEBUG] 
19:01:15 gunicorn.1 | # Thread: (140736182567808)
19:01:15 gunicorn.1 | File: "/Users/lev/.python_venvs2/lumin05a/bin/gunicorn", line 11, in <module>
19:01:15 gunicorn.1 |   sys.exit(run())
19:01:15 gunicorn.1 | File: "/Users/lev/.python_venvs2/lumin05a/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 74, in run
19:01:15 gunicorn.1 |   WSGIApplication("%(prog)s [OPTIONS] [APP_MODULE]").run()
19:01:15 gunicorn.1 | File: "/Users/lev/.python_venvs2/lumin05a/lib/python2.7/site-packages/gunicorn/app/base.py", line 203, in run
19:01:15 gunicorn.1 |   super(Application, self).run()
19:01:15 gunicorn.1 | File: "/Users/lev/.python_venvs2/lumin05a/lib/python2.7/site-packages/gunicorn/app/base.py", line 72, in run
19:01:15 gunicorn.1 |   Arbiter(self).run()
19:01:15 gunicorn.1 | File: "/Users/lev/.python_venvs2/lumin05a/lib/python2.7/site-packages/gunicorn/arbiter.py", line 202, in run
19:01:15 gunicorn.1 |   self.manage_workers()
19:01:15 gunicorn.1 | File: "/Users/lev/.python_venvs2/lumin05a/lib/python2.7/site-packages/gunicorn/arbiter.py", line 544, in manage_workers
19:01:15 gunicorn.1 |   self.spawn_workers()
19:01:15 gunicorn.1 | File: "/Users/lev/.python_venvs2/lumin05a/lib/python2.7/site-packages/gunicorn/arbiter.py", line 611, in spawn_workers
19:01:15 gunicorn.1 |   self.spawn_worker()
19:01:15 gunicorn.1 | File: "/Users/lev/.python_venvs2/lumin05a/lib/python2.7/site-packages/gunicorn/arbiter.py", line 597, in spawn_worker
19:01:15 gunicorn.1 |   self.cfg.worker_exit(self, worker)
19:01:15 gunicorn.1 | File: "gunicorn_config.py", line 87, in worker_exit
19:01:15 gunicorn.1 |   for filename, lineno, name, line in traceback.extract_stack(stack):
19:01:15 gunicorn.1 | GRPC patched
19:01:15 gunicorn.1 | [2018-04-16 19:01:15 +0300] [74056] [INFO] Worker exiting (pid: 74056)
19:01:15 gunicorn.1 | [2018-04-16 19:01:15 +0300] [74056] [INFO] gunicorn_config.worker_exit:
19:01:15 gunicorn.1 | [2018-04-16 19:01:15 +0300] [74056] [DEBUG] 
19:01:15 gunicorn.1 | # Thread: (140736182567808)
19:01:15 gunicorn.1 | File: "/Users/lev/.python_venvs2/lumin05a/bin/gunicorn", line 11, in <module>
19:01:15 gunicorn.1 |   sys.exit(run())
19:01:15 gunicorn.1 | File: "/Users/lev/.python_venvs2/lumin05a/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 74, in run
19:01:15 gunicorn.1 |   WSGIApplication("%(prog)s [OPTIONS] [APP_MODULE]").run()
19:01:15 gunicorn.1 | File: "/Users/lev/.python_venvs2/lumin05a/lib/python2.7/site-packages/gunicorn/app/base.py", line 203, in run
19:01:15 gunicorn.1 |   super(Application, self).run()
19:01:15 gunicorn.1 | File: "/Users/lev/.python_venvs2/lumin05a/lib/python2.7/site-packages/gunicorn/app/base.py", line 72, in run
19:01:15 gunicorn.1 |   Arbiter(self).run()
19:01:15 gunicorn.1 | File: "/Users/lev/.python_venvs2/lumin05a/lib/python2.7/site-packages/gunicorn/arbiter.py", line 211, in run
19:01:15 gunicorn.1 |   self.manage_workers()
19:01:15 gunicorn.1 | File: "/Users/lev/.python_venvs2/lumin05a/lib/python2.7/site-packages/gunicorn/arbiter.py", line 544, in manage_workers
19:01:15 gunicorn.1 |   self.spawn_workers()
19:01:15 gunicorn.1 | File: "/Users/lev/.python_venvs2/lumin05a/lib/python2.7/site-packages/gunicorn/arbiter.py", line 611, in spawn_workers
19:01:15 gunicorn.1 |   self.spawn_worker()
19:01:15 gunicorn.1 | File: "/Users/lev/.python_venvs2/lumin05a/lib/python2.7/site-packages/gunicorn/arbiter.py", line 597, in spawn_worker
19:01:15 gunicorn.1 |   self.cfg.worker_exit(self, worker)
19:01:15 gunicorn.1 | File: "gunicorn_config.py", line 87, in worker_exit
19:01:15 gunicorn.1 |   for filename, lineno, name, line in traceback.extract_stack(stack):
19:01:15 gunicorn.1 | GRPC patched
19:01:16 gunicorn.1 | [2018-04-16 19:01:16 +0300] [74040] [INFO] Worker exiting (pid: 74040)
19:01:16 gunicorn.1 | [2018-04-16 19:01:16 +0300] [74040] [INFO] gunicorn_config.worker_exit:
19:01:16 gunicorn.1 | [2018-04-16 19:01:16 +0300] [74040] [DEBUG] 
19:01:16 gunicorn.1 | # Thread: (140736182567808)
19:01:16 gunicorn.1 | File: "/Users/lev/.python_venvs2/lumin05a/bin/gunicorn", line 11, in <module>
19:01:16 gunicorn.1 |   sys.exit(run())
19:01:16 gunicorn.1 | File: "/Users/lev/.python_venvs2/lumin05a/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 74, in run
19:01:16 gunicorn.1 |   WSGIApplication("%(prog)s [OPTIONS] [APP_MODULE]").run()
19:01:16 gunicorn.1 | File: "/Users/lev/.python_venvs2/lumin05a/lib/python2.7/site-packages/gunicorn/app/base.py", line 203, in run
19:01:16 gunicorn.1 |   super(Application, self).run()
19:01:16 gunicorn.1 | File: "/Users/lev/.python_venvs2/lumin05a/lib/python2.7/site-packages/gunicorn/app/base.py", line 72, in run
19:01:16 gunicorn.1 |   Arbiter(self).run()
19:01:16 gunicorn.1 | File: "/Users/lev/.python_venvs2/lumin05a/lib/python2.7/site-packages/gunicorn/arbiter.py", line 202, in run
19:01:16 gunicorn.1 |   self.manage_workers()
19:01:16 gunicorn.1 | File: "/Users/lev/.python_venvs2/lumin05a/lib/python2.7/site-packages/gunicorn/arbiter.py", line 544, in manage_workers
19:01:16 gunicorn.1 |   self.spawn_workers()
19:01:16 gunicorn.1 | File: "/Users/lev/.python_venvs2/lumin05a/lib/python2.7/site-packages/gunicorn/arbiter.py", line 611, in spawn_workers
19:01:16 gunicorn.1 |   self.spawn_worker()
19:01:16 gunicorn.1 | File: "/Users/lev/.python_venvs2/lumin05a/lib/python2.7/site-packages/gunicorn/arbiter.py", line 597, in spawn_worker
19:01:16 gunicorn.1 |   self.cfg.worker_exit(self, worker)
19:01:16 gunicorn.1 | File: "gunicorn_config.py", line 87, in worker_exit
19:01:16 gunicorn.1 |   for filename, lineno, name, line in traceback.extract_stack(stack):
19:01:16 gunicorn.1 | GRPC patched
19:01:16 gunicorn.1 | [2018-04-16 22:01:16 +0300] [74037] [INFO] Shutting down: Master
19:01:16 system     | gunicorn.1 stopped (rc=0)

```

If I get rid of the patch and use `grpcio==1.3.0` all works fine (more or less, you know).

Does it help?

**Comment by yaalaa** [comment] 2018-04-16 19:11
Here you are:
[arch_002.zip](https://github.com/grpc/grpc/files/1916856/arch_002.zip)

Looks correct?

Nothing has changed, actually. Or, better say, you hit the nail on the head. Not sure.
Note in my code I've added the following line after the patch
```
print( 'GRPC patched' )
```

Steps:
- start app by `PORT=8000 honcho start`
- get by `curl localhost:8000`

`curl` gives me: `curl: (52) Empty reply from server`
App gives me:
```
18:59:28 gunicorn.1 | [2018-04-16 18:59:28 +0300] [74037] [INFO] Starting gunicorn 19.7.1
18:59:28 gunicorn.1 | [2018-04-16 18:59:28 +0300] [74037] [DEBUG] Arbiter booted
18:59:28 gunicorn.1 | [2018-04-16 18:59:28 +0300] [74037] [INFO] Listening at: http://0.0.0.0:8000 (74037)
18:59:28 gunicorn.1 | [2018-04-16 18:59:28 +0300] [74037] [INFO] Using worker: gevent
18:59:28 gunicorn.1 | [2018-04-16 18:59:28 +0300] [74037] [INFO] gunicorn_config.pre_fork: worker (pid: [booting])
18:59:28 gunicorn.1 | [2018-04-16 18:59:28 +0300] [74040] [INFO] Booting worker with pid: 74040
18:59:28 gunicorn.1 | [2018-04-16 18:59:28 +0300] [74040] [INFO] gunicorn_config.post_fork: worker spawned (pid: 74040)
18:59:28 gunicorn.1 | [2018-04-16 18:59:28 +0300] [74037] [INFO] gunicorn_config.pre_fork: worker (pid: [booting])
18:59:28 gunicorn.1 | [2018-04-16 18:59:28 +0300] [74041] [INFO] Booting worker with pid: 74041
18:59:28 gunicorn.1 | [2018-04-16 18:59:28 +0300] [74041] [INFO] gunicorn_config.post_fork: worker spawned (pid: 74041)
18:59:28 gunicorn.1 | [2018-04-16 18:59:28 +0300] [74037] [INFO] gunicorn_config.pre_fork: worker (pid: [booting])
18:59:28 gunicorn.1 | [2018-04-16 18:59:28 +0300] [74042] [INFO] Booting worker with pid: 74042
18:59:28 gunicorn.1 | [2018-04-16 18:59:28 +0300] [74042] [INFO] gunicorn_config.post_fork: worker spawned (pid: 74042)
18:59:28 gunicorn.1 | [2018-04-16 18:59:28 +0300] [74037] [INFO] gunicorn_config.pre_fork: worker (pid: [booting])
18:59:28 gunicorn.1 | [2018-04-16 18:59:28 +0300] [74043] [INFO] Booting worker with pid: 74043
18:59:28 gunicorn.1 | [2018-04-16 18:59:28 +0300] [74043] [INFO] gunicorn_config.post_fork: worker spawned (pid: 74043)
18:59:28 gunicorn.1 | [2018-04-16 18:59:28 +0300] [74037] [DEBUG] 4 workers
18:59:28 gunicorn.1 | [2018-04-16 18:59:28 +0300] [74040] [INFO] gunicorn_config.post_worker_init:
18:59:29 gunicorn.1 | [2018-04-16 18:59:29 +0300] [74041] [INFO] gunicorn_config.post_worker_init:
18:59:29 gunicorn.1 | [2018-04-16 18:59:29 +0300] [74042] [INFO] gunicorn_config.post_worker_init:
18:59:29 gunicorn.1 | [2018-04-16 18:59:29 +0300] [74043] [INFO] gunicorn_config.post_worker_init:
18:59:39 gunicorn.1 | [2018-04-16 18:59:39 +0300] [74043] [DEBUG] GET /
18:59:40 gunicorn.1 | [2018-04-16 18:59:40 +0300] [74037] [INFO] gunicorn_config.pre_fork: worker (pid: [booting])
18:59:40 gunicorn.1 | [2018-04-16 18:59:40 +0300] [74056] [INFO] Booting worker with pid: 74056
18:59:40 gunicorn.1 | [2018-04-16 18:59:40 +0300] [74056] [INFO] gunicorn_config.post_fork: worker spawned (pid: 74056)
18:59:40 gunicorn.1 | [2018-04-16 18:59:40 +0300] [74056] [INFO] gunicorn_config.post_worker_init:

```

After that I trap app by `Ctrl+C` and get this:
```

^C19:01:15 system     | SIGINT received
19:01:15 system     | sending SIGTERM to gunicorn.1 (pid 74037)
19:01:15 gunicorn.1 | [2018-04-16 19:01:15 +0300] [74037] [INFO] Handling signal: term
19:01:15 gunicorn.1 | [2018-04-16 19:01:15 +0300] [74041] [INFO] Worker exiting (pid: 74041)
19:01:15 gunicorn.1 | [2018-04-16 19:01:15 +0300] [74041] [INFO] gunicorn_config.worker_exit:
19:01:15 gunicorn.1 | [2018-04-16 19:01:15 +0300] [74041] [DEBUG]
19:01:15 gunicorn.1 | # Thread: (140736182567808)
19:01:15 gunicorn.1 | File: "/.../bin/gunicorn", line 11, in <module>
19:01:15 gunicorn.1 |   sys.exit(run())
19:01:15 gunicorn.1 | File: "/.../lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 74, in run
19:01:15 gunicorn.1 |   WSGIApplication("%(prog)s [OPTIONS] [APP_MODULE]").run()
19:01:15 gunicorn.1 | File: "/.../lib/python2.7/site-packages/gunicorn/app/base.py", line 203, in run
19:01:15 gunicorn.1 |   super(Application, self).run()
19:01:15 gunicorn.1 | File: "/.../lib/python2.7/site-packages/gunicorn/app/base.py", line 72, in run
19:01:15 gunicorn.1 |   Arbiter(self).run()
19:01:15 gunicorn.1 | File: "/.../lib/python2.7/site-packages/gunicorn/arbiter.py", line 202, in run
19:01:15 gunicorn.1 |   self.manage_workers()
19:01:15 gunicorn.1 | File: "/.../lib/python2.7/site-packages/gunicorn/arbiter.py", line 544, in manage_workers
19:01:15 gunicorn.1 |   self.spawn_workers()
19:01:15 gunicorn.1 | File: "/.../lib/python2.7/site-packages/gunicorn/arbiter.py", line 611, in spawn_workers
19:01:15 gunicorn.1 |   self.spawn_worker()
19:01:15 gunicorn.1 | File: "/.../lib/python2.7/site-packages/gunicorn/arbiter.py", line 597, in spawn_worker
19:01:15 gunicorn.1 |   self.cfg.worker_exit(self, worker)
19:01:15 gunicorn.1 | File: "gunicorn_config.py", line 87, in worker_exit
19:01:15 gunicorn.1 |   for filename, lineno, name, line in traceback.extract_stack(stack):
19:01:15 gunicorn.1 | GRPC patched
19:01:15 gunicorn.1 | [2018-04-16 19:01:15 +0300] [74042] [INFO] Worker exiting (pid: 74042)
19:01:15 gunicorn.1 | [2018-04-16 19:01:15 +0300] [74042] [INFO] gunicorn_config.worker_exit:
19:01:15 gunicorn.1 | [2018-04-16 19:01:15 +0300] [74042] [DEBUG]
19:01:15 gunicorn.1 | # Thread: (140736182567808)
19:01:15 gunicorn.1 | File: "/.../bin/gunicorn", line 11, in <module>
19:01:15 gunicorn.1 |   sys.exit(run())
19:01:15 gunicorn.1 | File: "/.../lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 74, in run
19:01:15 gunicorn.1 |   WSGIApplication("%(prog)s [OPTIONS] [APP_MODULE]").run()
19:01:15 gunicorn.1 | File: "/.../lib/python2.7/site-packages/gunicorn/app/base.py", line 203, in run
19:01:15 gunicorn.1 |   super(Application, self).run()
19:01:15 gunicorn.1 | File: "/.../lib/python2.7/site-packages/gunicorn/app/base.py", line 72, in run
19:01:15 gunicorn.1 |   Arbiter(self).run()
19:01:15 gunicorn.1 | File: "/.../lib/python2.7/site-packages/gunicorn/arbiter.py", line 202, in run
19:01:15 gunicorn.1 |   self.manage_workers()
19:01:15 gunicorn.1 | File: "/.../lib/python2.7/site-packages/gunicorn/arbiter.py", line 544, in manage_workers
19:01:15 gunicorn.1 |   self.spawn_workers()
19:01:15 gunicorn.1 | File: "/.../lib/python2.7/site-packages/gunicorn/arbiter.py", line 611, in spawn_workers
19:01:15 gunicorn.1 |   self.spawn_worker()
19:01:15 gunicorn.1 | File: "/.../lib/python2.7/site-packages/gunicorn/arbiter.py", line 597, in spawn_worker
19:01:15 gunicorn.1 |   self.cfg.worker_exit(self, worker)
19:01:15 gunicorn.1 | File: "gunicorn_config.py", line 87, in worker_exit
19:01:15 gunicorn.1 |   for filename, lineno, name, line in traceback.extract_stack(stack):
19:01:15 gunicorn.1 | GRPC patched
19:01:15 gunicorn.1 | [2018-04-16 19:01:15 +0300] [74056] [INFO] Worker exiting (pid: 74056)
19:01:15 gunicorn.1 | [2018-04-16 19:01:15 +0300] [74056] [INFO] gunicorn_config.worker_exit:
19:01:15 gunicorn.1 | [2018-04-16 19:01:15 +0300] [74056] [DEBUG]
19:01:15 gunicorn.1 | # Thread: (140736182567808)
19:01:15 gunicorn.1 | File: "/.../bin/gunicorn", line 11, in <module>
19:01:15 gunicorn.1 |   sys.exit(run())
19:01:15 gunicorn.1 | File: "/.../lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 74, in run
19:01:15 gunicorn.1 |   WSGIApplication("%(prog)s [OPTIONS] [APP_MODULE]").run()
19:01:15 gunicorn.1 | File: "/.../lib/python2.7/site-packages/gunicorn/app/base.py", line 203, in run
19:01:15 gunicorn.1 |   super(Application, self).run()
19:01:15 gunicorn.1 | File: "/.../lib/python2.7/site-packages/gunicorn/app/base.py", line 72, in run
19:01:15 gunicorn.1 |   Arbiter(self).run()
19:01:15 gunicorn.1 | File: "/.../lib/python2.7/site-packages/gunicorn/arbiter.py", line 211, in run
19:01:15 gunicorn.1 |   self.manage_workers()
19:01:15 gunicorn.1 | File: "/.../lib/python2.7/site-packages/gunicorn/arbiter.py", line 544, in manage_workers
19:01:15 gunicorn.1 |   self.spawn_workers()
19:01:15 gunicorn.1 | File: "/.../lib/python2.7/site-packages/gunicorn/arbiter.py", line 611, in spawn_workers
19:01:15 gunicorn.1 |   self.spawn_worker()
19:01:15 gunicorn.1 | File: "/.../lib/python2.7/site-packages/gunicorn/arbiter.py", line 597, in spawn_worker
19:01:15 gunicorn.1 |   self.cfg.worker_exit(self, worker)
19:01:15 gunicorn.1 | File: "gunicorn_config.py", line 87, in worker_exit
19:01:15 gunicorn.1 |   for filename, lineno, name, line in traceback.extract_stack(stack):
19:01:15 gunicorn.1 | GRPC patched
19:01:16 gunicorn.1 | [2018-04-16 19:01:16 +0300] [74040] [INFO] Worker exiting (pid: 74040)
19:01:16 gunicorn.1 | [2018-04-16 19:01:16 +0300] [74040] [INFO] gunicorn_config.worker_exit:
19:01:16 gunicorn.1 | [2018-04-16 19:01:16 +0300] [74040] [DEBUG]
19:01:16 gunicorn.1 | # Thread: (140736182567808)
19:01:16 gunicorn.1 | File: "/.../bin/gunicorn", line 11, in <module>
19:01:16 gunicorn.1 |   sys.exit(run())
19:01:16 gunicorn.1 | File: "/.../lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 74, in run
19:01:16 gunicorn.1 |   WSGIApplication("%(prog)s [OPTIONS] [APP_MODULE]").run()
19:01:16 gunicorn.1 | File: "/.../lib/python2.7/site-packages/gunicorn/app/base.py", line 203, in run
19:01:16 gunicorn.1 |   super(Application, self).run()
19:01:16 gunicorn.1 | File: "/.../lib/python2.7/site-packages/gunicorn/app/base.py", line 72, in run
19:01:16 gunicorn.1 |   Arbiter(self).run()
19:01:16 gunicorn.1 | File: "/.../lib/python2.7/site-packages/gunicorn/arbiter.py", line 202, in run
19:01:16 gunicorn.1 |   self.manage_workers()
19:01:16 gunicorn.1 | File: "/.../lib/python2.7/site-packages/gunicorn/arbiter.py", line 544, in manage_workers
19:01:16 gunicorn.1 |   self.spawn_workers()
19:01:16 gunicorn.1 | File: "/.../lib/python2.7/site-packages/gunicorn/arbiter.py", line 611, in spawn_workers
19:01:16 gunicorn.1 |   self.spawn_worker()
19:01:16 gunicorn.1 | File: "/.../lib/python2.7/site-packages/gunicorn/arbiter.py", line 597, in spawn_worker
19:01:16 gunicorn.1 |   self.cfg.worker_exit(self, worker)
19:01:16 gunicorn.1 | File: "gunicorn_config.py", line 87, in worker_exit
19:01:16 gunicorn.1 |   for filename, lineno, name, line in traceback.extract_stack(stack):
19:01:16 gunicorn.1 | GRPC patched
19:01:16 gunicorn.1 | [2018-04-16 22:01:16 +0300] [74037] [INFO] Shutting down: Master
19:01:16 system     | gunicorn.1 stopped (rc=0)

```

If I get rid of the patch and use `grpcio==1.3.0` all works fine (more or less, you know).

Does it help?

**Comment by kpayson64** [comment] 2018-05-30 21:55
@yaalaa 
Using ```arch_002.zip``` I was able to run your example (substituting my own datastore project) without issue.

I'm closing this issue as I think it has been resolved.

**Comment by yaalaa** [comment] 2018-05-31 00:08
I guess it doesn't.
At least it doesn't work to me. Even v1.12.0.
Anyway `gunicorn` worker gets frozen.

Aren't you too fast in closing issue which has been stalled for 1.5m?
I've seen no help yet.
You _hello world_ work, mine doesn't.
It's good opportunity to close most of the issues.
Pity musings.

**Comment by kpayson64** [comment] 2018-06-01 00:15
I apologize for closing this out prematurely, it wasn't clear to me that this was still an issue.

I'm now convinced that this is a real issue, and have created a PR to fix it.

**Comment by kpayson64** [comment] 2018-06-05 01:14
1.12.1 has been pushed, and should fix this issue.

Please re-open if it is still a problem.

**Closed by kpayson64** 2018-06-05 01:14 UTC
Labels: lang/Python, priority/P2

**Comment by yaalaa** [comment] 2018-06-05 10:35
The flight seems ok for now.
Thank you very much.

BTW, I've finally decided to use custom Gunicorn worker class to patch GRPC.
```
import gunicorn.workers.ggevent


class CustomGeventWorker( gunicorn.workers.ggevent.GeventWorker ):

    def patch( self ):

        super( CustomGeventWorker, self ).patch()

        import grpc._cython.cygrpc
        grpc._cython.cygrpc.init_grpc_gevent()
        self.log.info( 'CustomGeventWorker.patch: patched grpc' )

```
