### ISSUE TITLE
gRPC connection leaks or segfault when using Ruby multi threading in Rails

### ISSUE THREAD

**Issue by hxiong388** [grpc/grpc#8983] opened 2016-12-06 23:29 UTC
Problem:
When using google-cloud-logging in a Rails app, which submits application logs asynchronously in child thread, the gRPC connections leak as the application exists and produces this error: 
`E1206 15:11:13.432928303    4090 network_status_tracker.c:48] Memory leaked as all network endpoints were not shut down`

We get this error message on Linux machines, and get a segmentation fault when doing the same thing on Mac OS. We suspect these two problems share same cause. [Original error discussion here](https://github.com/GoogleCloudPlatform/google-cloud-ruby/issues/1096).

I think this problem may be similar to #7849. But #7849 is for Python only, and this issue is intended for Ruby.

So far we're only able to reproduce this error or the segfault error in a Rails application. Please contact me offline and I can supply the sample Rails application and reproduction commands.

**Comment by apolcyn** [comment] 2016-12-08 20:54
This seem leak can be seen by also tweaking helloworld examples in the grpc repo.
The `greeter_server.rb` `say_hello` changed to: 
```
  def say_hello(hello_req, _unused_call)
     sleep 1
     Helloworld::HelloReply.new(message: "Hello #{hello_req.name}")
   end
``` 

and the client changed to: 
```
def run
    stub = Helloworld::Greeter::Stub.new('localhost:50051', :this_channel_is_insecure)
    user = ARGV.size > 0 ?  ARGV[0] : 'world'
    message = stub.say_hello(Helloworld::HelloRequest.new(name: user)).message
    p "Greeting: #{message}"
  end
  
  def main
    t = Thread.new { run }
    sleep 0.5
  end
```

this starts the call but also lets the ruby process begin exit and run GC on the unjoined thread.

this leaves the error:
`E1208 11:53:53.347635897   80628 network_status_tracker.c:48] Memory leaked as all network endpoints were not shut down`

Reproducing what's seen here in rails with stackdriver, logs from `GRPC_VERBOSITY=DEBUG GRPC_TRACE=all,-queue_pluck,-queue_timeout` show that there's and outstanding call that get's cancelled at the beginning of everything in grpc shutting down. 

In the real repro, I think grpc is getting written to by the async child thread in https://github.com/GoogleCloudPlatform/google-cloud-ruby/blob/970e6a22b222377b8d252099229673b202d20247/google-cloud-logging/lib/google/cloud/logging/async_writer.rb, correct? In that case, I don't think that thread joined as either, so looks this is similar to the tweaked example.

Still child threads shouldn't have to be joined - everything getting cleanup up on process end should probably be able to cancel the call and clean things up.

cc @murgatroid99

**Comment by apolcyn** [comment] 2016-12-16 17:22
closing as this seems to be the same issue as https://github.com/GoogleCloudPlatform/google-cloud-ruby/issues/1096, with same fix

**Closed by apolcyn** 2016-12-16 17:22 UTC
Labels: ruby
