### ISSUE TITLE
build_artifact.csharp_ext_macos_ios Failure

### ISSUE THREAD

**Issue by gnossen** [grpc/grpc#26182] opened 2021-05-05 22:55 UTC
```
/Applications/Xcode_11.3.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang: /Applications/Xcode_11.3.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang: cannot execute binary file
make: *** [/Volumes/BuildData/tmpfs/src/github/grpc/workspace_csharp_ext_macos_ios/objs/ios_arm64/third_party/cares/cares/ares_parse_mx_reply.o] Error 126
make: *** Waiting for unfinished jobs....
[C]       Compiling third_party/cares/cares/ares_parse_naptr_reply.c

2021-05-05 11:55:57,321 FAILED: build_artifact.csharp_ext_macos_ios [ret=2, pid=14214, time=596.3sec]
```

https://source.cloud.google.com/results/invocations/16ec2e0e-e763-4064-b7e4-09fab239bd44/log

**Comment by jtattermusch** [comment] 2022-02-14 12:22
Dupe of https://github.com/grpc/grpc/issues/27211

**Closed by jtattermusch** 2022-02-14 12:22 UTC
Labels: kind/bug, lang/C#, disposition/BUILDNURSE, priority/P2
