### ISSUE TITLE
gRPCTargets.cmake and gRPCTargets-noconfig.cmake are broken for cross compilation.

### ISSUE THREAD

**Issue by madscientist42** [grpc/grpc#17708] opened 2019-01-14 17:10 UTC
### What version of gRPC and what language are you using?
 
1.16.0  C++
 
### What operating system (Linux, Windows, …) and version?

Linux, Poky 2.5 (Sumo), Kernel version 4.9, aarch64
 
 
### What runtime / compiler are you using (e.g. python version or version of gcc)

GCC (7.3)
 
### What did you do?

Cross-compile a follow-on package dependent on gRPC that uses CMake to build with.   Cross-compilation, proper, with pretty much any toolchain where you may have two sets of sysroots, one native to provide non GCC/clang tools, and one for the target system will break with the current generated files.

### What did you expect to see?
 
That the build honored my toolchain.cmake  and compiled and linked against the right gRPC from the **_TARGET_** sysroot.
 
### What did you see instead?

The CMake that used your find_package helpers to find the gRPC libs attempting, incorrectly, against the **_NATIVE_** sysroot of the image build system.  This is primarily because the ground rules for CMake helpers isn't being followed and an improper method is being used to do this work.  

The problem begins with this part of the gRPCTargets.cmake file:

\# Compute the installation prefix relative to this file.
get_filename_component(_IMPORT_PREFIX "${CMAKE_CURRENT_LIST_FILE}" PATH)
get_filename_component(_IMPORT_PREFIX "${_IMPORT_PREFIX}" PATH)
get_filename_component(_IMPORT_PREFIX "${_IMPORT_PREFIX}" PATH)
get_filename_component(_IMPORT_PREFIX "${_IMPORT_PREFIX}" PATH)
if(_IMPORT_PREFIX STREQUAL "/")
  set(_IMPORT_PREFIX "")
endif()

There are very **_few_** contexts where this is a valid thing to do if you're trying to cross-compile.  You really don't want to base any pathing off of the current .cmake file like this because, except for a few exceptions in cross-compilation and compiling native on the desired target system (Python script generation...), this breaks all sorts of things.  Your scripting should not override the toolchain.cmake behaviors this way so that you can expect to have it cross-compile right under all conditions.
 
### Anything else we should know about your project / environment?

Nothing other than Yocto, an up-reved copy of the current upstream recipe to 1.16.0 (which is minor editing work).  Not that you actually "need" to do this.  This will break upon just about **_ANY_** cross-compile environment because it doesn't honor the toolchain.cmake specification file for full cross-compilation support.

**Comment by koolkhel** [comment] 2019-08-26 09:38
I seem to have the same problem. I have a custom Yocto recipe that I need to depend on gRPC. And it fails with:
```
recipe-sysroot/usr/lib/cmake/grpc/gRPCTargets.cmake:180 (message):
|   The imported target "gRPC::gpr" references the file
|
|      "/usr/lib/libgpr.so.4.0.0"
|
|   but this file does not exist.  Possible reasons include:
```
Which is quite reasonable, I don't have /usr/lib/libgpr.so.4.0.0, yet I have oe-workdir/recipe-sysroot/usr/lib/libgpr.so.4.0.0. No idea what to do, CMake files are a bit complex to me.

**Comment by koolkhel** [comment] 2019-09-02 08:38
As a workaround I was able to omit gRPC's CMake files from both toolchain and target (blacklisting them) and borrowing some CMake code from https://github.com/googleapis/google-cloud-cpp/blob/master/cmake/FindgRPC.cmake so that it "autodetects" gRPC libraries. Works for me now, but yes, official gRPC files are broken for cross-compilation still.

**Comment by madscientist42** [comment] 2019-09-06 16:55
So, I'm not the only one side-stepping this sort of stuff.  I'd have said something a while back, but fire-drills and all...  X-D

**Comment by madscientist42** [comment] 2019-09-06 16:58
CMake files are complex...?    X-D

Building up Yocto bitbakes against all sorts of broken build systems for stuff's the fun stuff...  X-D

**Comment by AspirinSJL** [comment] 2019-09-06 18:13
Duplicate of https://github.com/grpc/grpc/issues/16675

**Comment by koolkhel** [comment] 2019-09-06 19:40
@AspirinSJL sorry, but I think these issues are different. 1) environments: one is x86_64 and gcc 8.2 and CentOS, other is ARM and Yocto and GCC 7.1, 2) #17708 is not about boringSSL, it's about gRPC unavailable to link to using existing CMake files in cross-platform environment, 3) again, boringSSL is not relevant here

**Comment by zackgalbreath** [comment] 2019-12-03 20:56
Do you have any more details on how to reproduce this? I managed to cross-compile gRPC and its helloworld example for ARM locally after tweaking gRPC's CMake rules to better handle host vs. target protoc (PR forthcoming soon). This leads me to believe that this might be a Yocto-specific issue.

> get_filename_component(_IMPORT_PREFIX "${CMAKE_CURRENT_LIST_FILE}" PATH)
> get_filename_component(_IMPORT_PREFIX "${_IMPORT_PREFIX}" PATH)
> get_filename_component(_IMPORT_PREFIX "${_IMPORT_PREFIX}" PATH)
> get_filename_component(_IMPORT_PREFIX "${_IMPORT_PREFIX}" PATH)

These generated lines of code aren't something custom that gRPC is doing. They come directly from CMake here:

https://gitlab.kitware.com/cmake/cmake/blob/master/Source/cmExportInstallFileGenerator.cxx#L195

**Comment by zackgalbreath** [comment] 2019-12-19 18:29
We have a cross-compiling distribtest now:

https://github.com/grpc/grpc/blob/master/test/distrib/cpp/run_distrib_test_raspberry_pi.sh

Unless we get more details, I think this issue is safe to close.

**Closed** 2019-12-20 08:02 UTC
Labels: area/build, kind/bug, lang/c++, priority/P1
