### ISSUE TITLE
Document grpc-status-details-bin

### ISSUE THREAD

**Issue by dfawley** [grpc/grpc#24007] opened 2020-08-28 17:18 UTC
Moving from https://github.com/grpc/grpc-go/issues/2329 since this is a request for documentation that lives in this repo.

https://github.com/grpc/grpc/pull/12825 by @yang-g attempted to add this to the spec but it was never merged (closed and locked by stale bot).

This field is currently a supported feature of gRPC but its design / behavior is entirely undocumented.  We need a specification for this feature to refer to users and to verify that our implementations are correct and complete.  Unfortunately, since the current implementations (C/Java/Go/others?) were done without a spec/gRFC in place, we need to make sure the spec allows for all their behaviors.

**Comment by akshayjshah** [comment] 2023-10-20 16:12
@dfawley Given grpc/grpc-go#6662, is it possible to reassess the priority of this issue? It'd be really nice for the community to have the expected behavior of `grpc-status-details-bin` standardized (and ideally included in the conformance tests).

**Comment by jhump** [comment] 2024-05-22 17:02
> Unfortunately, since the current implementations (C/Java/Go/others?) were done without a spec/gRFC in place, we need to make sure the spec allows for all their behaviors.

FWIW, I think it would be preferred for the spec to actually be opinionated on the "correct" behavior and then any variance in existing implementations could be considered a bug and fixed in future releases.

Likely the most controversial decision that many implementations make is that the contents of `grpc-status-details-bin` _override_ the contents of `grpc-status` and `grpc-message`, in the event that they disagree on the status code and message text. I personally think that is the wrong behavior since it means that clients that do not look at `grpc-status-details-bin` would then report a different status code and error message than clients that do. It also means that a proxy would need to decode/unmarshal the `grpc-status-details-bin` data in order to accurately record metrics for RPC status, when it seems simpler and more sane to instead treat `grpc-status` as authoritative (especially since it is the only thing that has been documented in the spec up to this point).

**Comment by jhump** [comment] 2024-05-22 17:02
@markdroth, @yang-g: this issue has been assigned for over three and a half years. Is there any chance of addressing this in the near future?

**Comment by dfawley** [comment] 2024-05-22 17:32
At this point, it seems like the best course of action is to document the header as implementation dependent, and state that users should not ever include a `Status` proto in it that contradicts `grpc-status`.

C++ doesn't treat it specially at all.  Java does validation only when the client application requests it _as a `Status` proto_.  Go validates it while reading off the wire _if it is a `Status` proto_ (and converts to an `INTERNAL` error if there is a mismatch).

**Comment by akshayjshah** [comment] 2024-06-20 18:54
@dfawley Are you open to a PR to the specification with text similar to what you're describing? Just documenting that `grpc-status-details-bin` should contain a `Status` proto would be an improvement.

**Comment by dfawley** [comment] 2024-07-08 19:37
@akshayjshah FYI I made #37124 for this if you would like to review the wording.

**Closed** 2024-07-08 20:11 UTC
Labels: kind/bug, area/documentation, priority/P2, lang/other
