### ISSUE TITLE
SSL/TSI data corruption in C# server/client (language agnostic?)

### ISSUE THREAD

**Issue by amitwaisel** [grpc/grpc#8673] opened 2016-11-08 10:15 UTC
When using GRPC v1.0.1 client/server written in C#, When creating many **concurrent** connections to the same server, I experience errors and disconnections:

1. From time to time, a sessions gets disconnected due to **TSI data corruption** (All clients and the server run from the same process, so networking issues are impossible)
> E1108 10:44:26.660054 0 c:\jenkins\workspace\gRPC_build_artifacts\architecture\x86\language\csharp\platform\windows\vsprojects\..\src\core\lib\tsi\ssl_transport_security.c:453: Corruption detected.
E1108 10:44:26.660054 0 c:\jenkins\workspace\gRPC_build_artifacts\architecture\x86\language\csharp\platform\windows\vsprojects\..\src\core\lib\security\transport\secure_endpoint.c:176: Decryption error: TSI_DATA_CORRUPTED

2. As described in #8382, when creating over 5-6 encrypted connections **in parallel**, the already-connected sessions start to fail with those errors:
One of the sessions gets disconnected with this message:
> E1107 16:02:06.265602 0 c:\jenkins\workspace\gRPC_build_artifacts\architecture\x86\language\csharp\platform\windows\vsprojects..\src\core\lib\security\transport\handshake.c:128: Security handshake failed: {"created":"@1478527326.265000000","description":"Handshake read failed","file":"c:\jenkins\workspace\gRPC_build_artifacts\architecture\x86\language\csharp\platform\windows\vsprojects..\src\core\lib\security\transport\handshake.c","file_line":237,"referenced_errors":[{"created":"@1478527326.265000000","description":"**An established connection was aborted by the software in your host machine**.\r\n","file":"c:\jenkins\workspace\gRPC_build_artifacts\architecture\x86\language\csharp\platform\windows\vsprojects..\src\core\lib\iomgr\tcp_windows.c","file_line":171}]}
E1107 16:02:06.268611 0 c:\jenkins\workspace\gRPC_build_artifacts\architecture\x86\language\csharp\platform\windows\vsprojects..\src\core\ext\transport\chttp2\server\secure\server_secure_chttp2.c:119: Secure transport failed with error 1

All other connections get disconnected afterwards:
> E1107 16:02:06.271631 0 c:\jenkins\workspace\gRPC_build_artifacts\architecture\x86\language\csharp\platform\windows\vsprojects..\src\core\lib\security\transport\handshake.c:128: Security handshake failed: {"created":"@1478527326.271000000","description":"Handshake read failed","file":"c:\jenkins\workspace\gRPC_build_artifacts\architecture\x86\language\csharp\platform\windows\vsprojects..\src\core\lib\security\transport\handshake.c","file_line":237,"referenced_errors":[{"created":"@1478527326.271000000","description":"**End of TCP stream**","file":"c:\jenkins\workspace\gRPC_build_artifacts\architecture\x86\language\csharp\platform\windows\vsprojects..\src\core\lib\iomgr\tcp_windows.c","file_line":180}]}
E1107 16:02:06.273623 0 c:\jenkins\workspace\gRPC_build_artifacts\architecture\x86\language\csharp\platform\windows\vsprojects..\src\core\ext\transport\chttp2\server\secure\server_secure_chttp2.c:119: Secure transport failed with error 1

@apolcyn Setting `grpc.initial_reconnect_backoff_ms`, as you instructed, to either 100 or 1000 makes things worse.

**Comment by jtattermusch** [comment] 2016-11-08 15:58
To clarify the scope:
Is this happening only with C#? If this also happens with other languages, it's most likely an issue in C core.
Is it only Windows specific?

**Comment by amitwaisel** [comment] 2016-11-08 16:10
It happens when the server is C# (but it might happen on other languages) and the clients are either C++ or C# (happens in both cases). It was tested only on Windows.

**Comment by ctiller** [comment] 2016-11-08 16:14
Smells like a bug in the iomgr polling or endpoint code for Windows.
Confirming it does or doesn't happen on another platform would be helpful.

**Comment by jtattermusch** [comment] 2016-11-08 18:16
Btw, the error "An established connection was aborted by the software in your host machine" seems to be often associated with a windows firewall. Have you tried disabling it and re-running the test?

https://social.msdn.microsoft.com/Forums/en-US/212feb8f-cf96-4561-9953-40a21d21ea47/exception-an-established-connection-was-aborted-by-the-software-in-your-host-machine?forum=netfxnetcom

**Comment by rmartin7c** [comment] 2016-11-09 16:56
I'm seeing something similar from an iOS ObjC client. It happens intermittently, usually either on initial app startup and connection to the gRPC server, or else after the app resumes from background.

> E1109 11:47:53.498008000 123145302917120 handshake.c:128] Security handshake failed: {"created":"@1478710073.497969000","description":"Handshake read failed","file":"/Users/rmartin/src/POM-Chewy-iOS/Pods/gRPC-Core/src/core/lib/security/transport/handshake.c","file_line":237,"referenced_errors":[{"created":"@1478710073.497965000","description":"FD shutdown","file":"/Users/rmartin/src/POM-Chewy-iOS/Pods/gRPC-Core/src/core/lib/iomgr/ev_poll_posix.c","file_line":427}]}

**Comment by jtattermusch** [comment] 2016-11-09 18:36
If you don't mind, I'll restrict scope of this issue to "SSL/TSI data corruption" as we already have an issue filed for the parallel connects (#8382). I adjusted the name of this issue.

**Comment by jtattermusch** [comment] 2016-11-09 18:38
So far I wasn't able to reproduce the "TSI_DATA_CORRUPTED" issue. It makes me think that perhaps it might be causes by forcefully closing the connection if a connection attempt times out (and when only part of the data is sent?)

**Comment by jtattermusch** [comment] 2016-11-09 18:41
@rmartin7c  can you please check if what I commented on #8382 helps in your situation?

**Comment by rmartin7c** [comment] 2016-11-09 20:05
@jtattermusch we are trying to do so, but it doesn't appear that the grpc.initial_reconnect_backoff_ms channelArg is exposed in the ObjC wrapper. See [GRPCCall+ChannelArg.h](https://github.com/grpc/grpc/src/objective-c/GRPCClient/GRPCCall+ChannelArg.h). Do you have any advice on how to set this param in ObjC, or are we going to have to add a method manually to test this?

**Comment by amitwaisel** [comment] 2016-11-09 21:38
@jtattermusch It appears like the TSI_DATA_CORRUPTED error happens after all connections are initialized, and data was already sent on all subchannels successfully. I will try to change the channel's reconnect backoff and update you soon
@rmartin7c This channel argument is not formally exposed. Note that all exposed arguments are actually translated to a string that formed like "grpc.XXX" so you can, in fact, change inner arguments just by knowing the exact string that describe them. (That's the case in C#)

**Comment by amitwaisel** [comment] 2017-01-10 08:06
@jtattermusch Seems like the decryption errors happen when a large number of gRPC streams are active between the server and multiple clients.
Each one of the following errors (`TSI_INTERNAL_ERROR` and `TSI_DATA_CORRUPTED`) cause the connection to be dropped:

> E0109 19:55:23.606337 0 c:\jenkins\workspace\gRPC_build_artifacts\architecture\x86\language\csharp\platform\windows\vsprojects\..\src\core\lib\security\transport\secure_endpoint.c:176: Decryption error: TSI_INTERNAL_ERROR

> E0109 19:55:23.613337 0 c:\jenkins\workspace\gRPC_build_artifacts\architecture\x86\language\csharp\platform\windows\vsprojects\..\src\core\lib\security\transport\secure_endpoint.c:176: Decryption error: TSI_DATA_CORRUPTED

> E0110 00:28:25.214079 0 c:\jenkins\workspace\gRPC_build_artifacts\architecture\x86\language\csharp\platform\windows\vsprojects\..\src\core\lib\tsi\ssl_transport_security.c:425: error:1409442E:SSL routines:ssl3_read_bytes:tlsv1 alert protocol version

As for the encryption, `SslCredentials` are used. The server uses the CA certificate + server's certificate + server private key, and the client uses only the CA certificate + client's certificate.

Thanks

**Comment by amitwaisel** [comment] 2017-01-12 08:26
As far as I can tell, this issue happens because of some race condition in OpenSSL library, which is used only on Windows (issue #9085 describes the linkage spaghetti). gRPC uses version 1.0.2d which is over 1.5 years old, and might not support multithreading well (for example, I found a bug in memory release inside crypto/err.c, which is not well-thread-protected in version 1.0.2d).
After some manual work, I managed **linking gRPC libraries with BoringSSL** (on Windows) rather than OpenSSL.
1. C++ code requires linking with `ssl.lib` and `crypto.lib` instead of `libeay32.lib` and `ssleay32.lib`, and **building gRPC libraries with the corresponding BoringSSL headers**.
2. C# code requires rebuilding `grpc_csharp_ext.dll` (which is C++ code) with `ssl.lib` and `crypto.lib` and overriding `grpc_csharp_ext.[x86|x64].dll` from NuGet with the manually-built library, in the OutputDirectory.

Maybe this is the way to solve the issue in future gRPC releases? In any case, gRPC 1.0.1 (and even the master branch as far as I can tell) currently contains a mesh up of BoringSSL and OpenSSL (issue #9085 - links with OpenSSL from gRPC.dependencies.openssl..., but uses BoringSSL headers).
In addition, I have a feeling it might solve #8405 as well (as I said, I found a race condition in a heap-free function in OpenSSL, which causes heap corruption from time to time).

**Comment by jtattermusch** [comment] 2017-02-08 17:58
Update: After making major improvements to our cmake build on Windows, I am getting closer to a point where I will be able to produce grpc_csharp_ext.dll   that uses boringssl  instead of openssl. That will probably become the authoritative version of grpc_csharp_ext.dll  that will also be part of our C# packages.

**Comment by jtattermusch** [comment] 2017-02-10 23:11
This issue should be fixed once https://github.com/grpc/grpc/pull/9665 is merged.

**Comment by jtattermusch** [comment] 2017-02-11 00:23
#9665 just got merged, can you please verify the fix? You can use experimental nugets here:
https://grpc-testing.appspot.com/view/Artifacts/job/gRPC_build_packages/2747/platform=windows/

**Comment by jtattermusch** [comment] 2017-02-24 01:19
@amitwaisel  please let me know if this was fixed.

**Comment by jtattermusch** [comment] 2017-03-13 07:36
Got a confirmation from @amitwaisel  that this was fixed.

**Closed** 2017-03-13 07:36 UTC
Labels: C#, core, Version/1.0.x, Windows
