### ISSUE TITLE
PHP test EndToEndTest::testSimpleRequestBody fails with segmentation fault

### ISSUE THREAD

**Issue by murgatroid99** [grpc/grpc#2163] opened 2015-06-22 20:35 UTC
This seems to happen consistently in the Jenkins opt build:

```
Starting test 'EndToEndTest::testSimpleRequestBody'.
I0622 18:32:56.071212324    4969 call.c:1302] grpc_call_start_batch(call=0x201f060, ops=0x7ffd1e4815d0, nops=2, tag=0x201f060)
I0622 18:32:56.071232167    4969 call.c:1302] ops[0]: SEND_INITIAL_METADATA
I0622 18:32:56.071240251    4969 call.c:1302] ops[1]: SEND_CLOSE_FROM_CLIENT
Segmentation fault
```

An example log that shows this failure is [here](https://grpc-testing.appspot.com/job/gRPC%20pull%20requests/165/config=opt,language=php,platform=linux/console)

**Comment by stanley-cheung** [comment] 2015-06-22 21:14
dupe of #1920. Tracking that segfault there.

**Closed** 2015-06-22 21:15 UTC
Labels: bug, Jenkins, php, wrapped languages
