### ISSUE TITLE
GRPC_POLL_STRATEGY=poll bins/opt/end2end_test --gtest_filter=ProxyEnd2end/ProxyEnd2endTest.EchoDeadline/1

### ISSUE THREAD

**Issue by yang-g** [grpc/grpc#14174] opened 2018-01-25 04:36 UTC
Could not reproduce locally.

```
I0124 23:02:54.997640571    5513 subchannel.cc:603]          New connected subchannel at 0x9dfe90 for subchannel 0x7f5a0c0039b0
I0124 23:02:55.001032691    6018 subchannel.cc:603]          New connected subchannel at 0x7f59e8017240 for subchannel 0x7f5a0c006f70
test/cpp/end2end/end2end_test.cc:1338: Failure
Expected: (response.param().request_deadline() - sent_deadline.tv_sec) <= (1), actual: 2 vs 1
[  FAILED  ] ProxyEnd2end/ProxyEnd2endTest.EchoDeadline/1, where GetParam() = TestScenario{use_proxy=true, inproc=false, credentials='ssl'} (16 ms)
[----------] 1 test from ProxyEnd2end/ProxyEnd2endTest (16 ms total)
```

**Comment by jtattermusch** [comment] 2018-02-01 16:43
Duplicate of https://github.com/grpc/grpc/issues/10092 (which is already fixed)

**Closed by jtattermusch** 2018-02-01 16:43 UTC
Labels: infra/BUILDPONY
