### ISSUE TITLE
FLAKY: grpc/core/pull_request/macos/grpc_ios_binary_size

### ISSUE THREAD

**Issue by lidizheng** [grpc/grpc#17419] opened 2018-12-06 02:02 UTC
Test `grpc/core/pull_request/macos/grpc_ios_binary_size` is flaky, and recent 36 builds all failed.

https://fusion.corp.google.com/projectanalysis/current/KOKORO/prod%3Agrpc%2Fcore%2Fpull_request%2Fmacos%2Fgrpc_ios_binary_size

**Comment by lidizheng** [comment] 2018-12-06 02:02
CC @jtattermusch

**Comment by jtattermusch** [comment] 2018-12-06 08:13
Duplicate of https://github.com/grpc/grpc/issues/17420

**Closed by jtattermusch** 2018-12-06 08:13 UTC

**Comment by lidizheng** [comment] 2018-12-06 08:16
This issue is for ios binary size test flakyness. And #17420 is for cpp basic tests. Do they share the same root cause?
