### ISSUE TITLE
Local Client and remote server

### ISSUE THREAD

**Issue by skumari123** [grpc/grpc#30271] opened 2022-07-12 08:49 UTC
### Is your feature request related to a problem? Please describe.
A feature to connect to remote server from the local client.
I am getting the issue as:

Unhandled exception. Grpc.Core.RpcException: Status(StatusCode="Internal", Detail="Bad gRPC response. Response protocol downgraded to HTTP/1.1.")

### Describe the solution you'd like
I want the local client to be able to send the data to the remote server.

### Describe alternatives you've considered
I have tried using ChannelOptions as :
new GrpcChannelOptions { Credentials = ChannelCredentials.Insecure } in the GrpcChannel argument.
I used the IP address of the server for the url.
I dont see any proper blog or issue resolution on the topic anywhere.

### Additional context
Add any other context about the feature request here.

**Comment by tonydnewell** [comment] 2022-07-12 10:02
Can you give more information about the client and server? Are other clients able to connect to the server?  Is the server using TLS? Is there a firewall in between the client and the server?

Does the information in this issue help - https://github.com/grpc/grpc-dotnet/issues/682

**Comment by Hoover391github2** [comment] 2022-07-12 19:28
Hoover frequency code archive Library database encryptions for archive history and personal information https:// encryption everywhere

**Comment by tonydnewell** [comment] 2022-07-13 08:32
@skumari123 I expect this isn't a gRPC bug. It looks like your server isn't using HTTP/2.
If you think there is a bug then can give a complete example that allows us to reproduce the problem.

**Comment by skumari123** [comment] 2022-07-13 08:50
i am trying to connect the Grpc remote server from the local client but i
am not able to do so.There is a firewall here for the remote server.

when i am trying to execute the grpc client on the local desktop ,its not
able to run and the screen vanishes.
what can i do to overcome the firewall?Do i need to bypass it or Grpc
provides some way to do this?

**Comment by skumari123** [comment] 2022-07-14 20:15
This  issue got resolved.I had not installed dotnet in my local machine.I
installed it and it worked fine. For connecting to the remote desktop,i
used the code for https connection (i was facing invlaid certificate issue
too here,it got resolved using HttpClientHandler):

var httpHandler = new HttpClientHandler(); // Return true to allow
certificates that are untrusted/invalid

 httpHandler.ServerCertificateCustomValidationCallback =
HttpClientHandler.DangerousAcceptAnyServerCertificateValidator;

        Thread.Sleep(10000);
        Console.WriteLine("hi,client connected");

        var channel = GrpcChannel.ForAddress("https://{your ip address}",
            new GrpcChannelOptions { HttpHandler = httpHandler });

//You can insert the rest of the code for the client here..

Thanks a lot

**Comment by tonydnewell** [comment] 2022-07-15 08:22
@apolcyn can close this

**Closed** 2022-07-15 17:23 UTC
Labels: kind/enhancement, lang/C#, priority/P2
