### ISSUE TITLE
c++ benchmark worker failure around close at end of benchmark

### ISSUE THREAD

**Issue by apolcyn** [grpc/grpc#9016] opened 2016-12-09 00:47 UTC
running 
```
'--scenarios_json={"scenarios": [{"name": "cpp_protobuf_sync_streaming_qps_unconstrained_secure_500kib_resource_quota", "warmup_seconds": 5, "benchmark_seconds": 30, "num_servers": 1, "server_config": {"resource_quota_size": 512000, "async_server_threads": 0, "core_limit": 0, "security_params": {"use_test_ca": true, "server_host_override": "foo.test.google.fr"}, "server_type": "SYNC_SERVER"}, "client_config": {"client_type": "SYNC_CLIENT", "security_params": {"use_test_ca": true, "server_host_override": "foo.test.google.fr"}, "payload_config": {"simple_params": {"resp_size": 0, "req_size": 0}}, "client_channels": 64, "async_client_threads": 0, "outstanding_rpcs_per_channel": 16, "rpc_type": "STREAMING", "load_params": {"closed_loop": {}}, "histogram_params": {"max_possible": 60000000000.0, "resolution": 0.01}}, "num_clients": 0}]}'
```

seems to have some failures when the benchmark ends and connections close

test log in https://gist.github.com/apolcyn/802cf766ec3373542b19ea6a8d1a3533

**Comment by dgquintas** [comment] 2017-02-17 02:23
Duplicate of #9609

**Closed by dgquintas** 2017-02-17 02:23 UTC
Labels: c++
