### ISSUE TITLE
Fix C#'s `XMLDoc` generation via `GenerateDocCommentBodyImpl` inside `csharp_generator.cc`

### ISSUE THREAD

**Issue by Eagle3386** [grpc/grpc#31516] opened 2022-11-01 10:49 UTC
As kindly pointed out by @JamesNK over at grpc/grpc-dotnet#1928 as well as in @jtattermusch's comment:
https://github.com/grpc/grpc/blob/1b9ab1825104cc5d05b16529293caffb5f57975e/src/compiler/csharp_generator.cc#L41-L45
C#'s `XMLDoc` generation is done via the C# compiler.

Since the latter made the aforementioned comment about 7 years ago, the "massaged version" seems a bit "dusty" & I'd like to ask for a bit of attention/work on it as it seems that the reuse of said header is now possible.

Specially, I'd like to see improvements regarding these 2 replace statements:
https://github.com/grpc/grpc/blob/1b9ab1825104cc5d05b16529293caffb5f57975e/src/compiler/csharp_generator.cc#L57-L58

1. If `&` is already escaped, it shouldn't be done twice, i. e. `&amp;` must not be escaped as `&amp;amp;`.
My first idea is usage of a RegEx like `&[^a-z1-8]{2,};` (based on Wiki's [Char entity refs](https://en.wikipedia.org/wiki/List_of_XML_and_HTML_character_entity_references)) that _intentionally_ produces XML validation errors upon whitespace misusage, e. g. `dollars &euros` fails due to missing `;` while `dollar &euro;s` as well as `dollar & euros` succeed (the latter due to being escaped as `dollar &amp; euros`).

2. Such a RegEx usage would also help developers _heavily_ using `XMLDoc`'s cross-linking ability.
Because commenting `.proto` files like this:
```protobuf
// Represents a gRPC wrapper for .NET's <see langword="decimal" /> value type, containing the
// <see cref="Integer" /> &amp; <see cref="Fractional" /> part as separated properties of such
// a number in order to minimize errors due to rounding.
// Example: 12345.6789 => { integer = 12345, fractional = 678900000 }
// Adapted from https://learn.microsoft.com/en-us/dotnet/architecture/grpc-for-wcf-developers/protobuf-data-types#decimals
message GrpcDecimal
{
  // The integer part of the number.
  int64 integer = 1;

  // The fractional part of the number, using 10^-9 precision.
  sfixed32 fractional = 2;
}
```
currently lets the C# generator's `GenerateDocCommentBodyImpl` method translate it into this:
```csharp
/// <summary>
/// Represents a gRPC wrapper for .NET's &amp;lt;see langword="decimal" /> value type, containing the
/// &lt;see cref="Integer" /> &amp;amp; &lt;see cref="Fractional" /> part as separated properties of such
/// a number in order to minimize errors due to rounding.
/// Example: 12345.6789 => { integer = 12345, fractional = 678900000 }
/// Adapted from https://learn.microsoft.com/en-us/dotnet/architecture/grpc-for-wcf-developers/protobuf-data-types#decimals
/// </summary>
public sealed partial class GrpcDecimal : pb::IMessage<GrpcDecimal>
{
  // Code left out for brevity…

  /// <summary>The integer part of the number.</summary>
  public long Integer

  // Code left out for brevity…

  /// <summary>The fractional part of the number, using 10^-9 precision.</summary>
  public int Fractional

  // Code left out for brevity…
}
```

However, I expect the `<summary>` tag's translation to be at least like this:
```csharp
/// <summary>
/// Represents a gRPC wrapper for .NET's &amp; <see langword="decimal" /> value type, containing the
/// <see cref="Integer" /> &amp; <see cref="Fractional" /> part as separated properties of such
/// a number in order to minimize errors due to rounding.
/// Example: 12345.6789 => { integer = 12345, fractional = 678900000 }
/// Adapted from https://learn.microsoft.com/en-us/dotnet/architecture/grpc-for-wcf-developers/protobuf-data-types#decimals
/// </summary>
```

Though, ideally `GenerateDocCommentBodyImpl` translates other comment "keywords" like `Example:` (note the uppercase property names down below) or an URL like above as well:
```csharp
/// <example>12345.6789 => { Integer = 12345, Fractional = 678900000 }</example>
/// Adapted from <see href="https://learn.microsoft.com/en-us/dotnet/architecture/grpc-for-wcf-developers/protobuf-data-types#decimals">Protobuf Data Types # Decimals</see>
```

Please see [Recommended XML tags for C# documentation comments](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/xmldoc/recommended-tags) for further XML tags - it'll be purely _awesome_ if more or even all of them would be supported. 🤩

**Comment by jtattermusch** [comment] 2022-11-07 16:27
CC @tonydnewell

**Comment by tonydnewell** [comment] 2023-02-09 14:07
There are a few things that we could discuss here and decide how much work we want to do to improve the C# comment generation in `protoc` and the gRPC plugin.

- `proto` files are language independent so any C# specific markup in the comments `proto` files might not make sense when generated for other languages, e.g. your use of `<see cref="Integer" />`, for example, is C# specific.

- There isn't a defined format for comments in `proto` files. Some files, such as [well-known types](https://protobuf.dev/reference/protobuf/google.protobuf/) do appear to use markdown, but none of the language generators in `protoc` interpret this and just copy the comments as-is to the generated output. (There are a few language specific things like escaping nested comments and ampersand).
See [protoc issue #5022](https://github.com/protocolbuffers/protobuf/issues/5022)

- Some language generators completely ignore the comments (e.g C++, python, ruby)
See [protoc issue #5679](https://github.com/protocolbuffers/protobuf/issues/5679]) for discussion on no comments in C++ code.

- The C# comment generate code in `protoc` hasn't changed recently and the code copied into the gRPC plugin is the same. Doesn't seem to been changed since [protoc issue #832](https://github.com/protocolbuffers/protobuf/issues/832)

Quick fixes that we could do:
- use the same code in `protoc` without copying the code

- handle escaping of ampersands and < and > better:
	Java generator parses the comments a character at a time to do this and the C# code could do something similar
See https://github.com/protocolbuffers/protobuf/blob/f0dc78d7e6e331b8c6bb2d5283e06aa26883ca7c/src/google/protobuf/compiler/java/doc_comment.cc#L48

Note C# and Java generators handle this differently:
```
// Some comment <abc/> &amp; /*Nested comment*/
```
C# generator:
```C#
    /// <summary>
    /// Some comment &lt;abc/> &amp;amp; /*Nested comment*/
    /// </summary>
```
Java generator:
```java
  /**
   * <pre>
   * Some comment &lt;abc/&gt; &amp;amp; /&#42;Nested comment*&#47;
   * </pre>
   */
```

Any thoughts?
@Eagle3386 @jtattermusch @jskeet @JamesNK

**Comment by jskeet** [comment] 2023-02-10 08:08
I would definitely prefer to keep the comment formatting as it is - basically, a faithful representation of the comment in the .proto file, just represented in XML.

I've previously thought about how we might go about making it easier for generators to generate more appropriate in-language comments by "knowing" the expected format of the proto comments, but I haven't got as far as actual designs.

**Comment by tonydnewell** [comment] 2023-02-13 10:26
Some more observations:
- the `&` is being double encoded because the the user encoded it by hand in the comments in the first place  as `&amp;`. The solution is for the user not to encode it by hand in the comments as there no need for that.
- the `<` is encoded because we want to prevent generating malformed XML. We _could_ try and detect well formed XML tags and allow them through although to do that correctly with all corner cases handled would be a lot of work.

I think we should for now leave the comment handling as it is until there is a design (possible across languages) for what should be done. I'm happy for the discussion to continue here.

**Comment by Eagle3386** [comment] 2023-02-14 14:06
@tonydnewell 
> * `proto` files are language independent so any C# specific markup in the comments `proto` files might not make sense when generated for other languages, e.g. your use of `<see cref="Integer" />`, for example, is C# specific.

IMHO, it's not C# specific, but purely XMLDoc - which uses `///` as prefix on each line which in turn means that basically any language supporting the concept of double slashes for comments could use them.

However, I do understand your point. But writing proper documentation inside a `.proto` file only once & getting it carried over / transformed into the language's specific comment / documentation style greatly improves code documentation as well as developer coding lives.
I'd therefore like to suggest inclusion of something like a "referencing system" for commenting such fields/members/properties in the future - that would even help to standardize comments since you stated:
> * There isn't a defined format for comments in `proto` files.
> (…)

Though, I do struggle with your statement:
> Quick fixes that we could do:
> * use the same code in `protoc` without copying the code

Earlier, you suggested that `protoc`'s & the gRPC plugin's code regarding comment parsing _is_ already the same?!

Nonetheless, this:
> * handle escaping of ampersands and < and > better:
> Java generator parses the comments a character at a time to do this and the C# code could do something similar
> (…)

sounds like a good solution for correct parsing of `<` & `>` as well as escaping ampersands!
But please don't use `<pre>`-styled comments like the Java generator does - just escape the angle 

@jskeet
> I would definitely prefer to keep the comment formatting as it is - basically, a faithful representation of the comment in the .proto file, just represented in XML.

With all due respect, I am strongly against this as it's neither fish nor fowl with regards to both, good escaping as well as proper code documentation - with especially the latter being pretty much loved by every developer, no matter what the language is.

> I've previously thought about how we might go about making it easier for generators to generate more appropriate in-language comments by "knowing" the expected format of the proto comments, but I haven't got as far as actual designs.

Thanks for taking the time thus far. Maybe you could work on this in the not so distant future?
Until then, I still love to see the escaping improved as outlined above.

@tonydnewell 
> Some more observations:
> * the `&` is being double encoded because the the user encoded it by hand in the comments in the first place  as `&amp;`. The solution is for the user not to encode it by hand in the comments as there is no need for that.

While that's true, improving the parsing logic to "look ahead / behind" at least so much that it doesn't double such escaping anymore.

> * the `<` is encoded because we want to prevent generating malformed XML. We _could_ try and detect well formed XML tags and allow them through although to do that correctly with all corner cases handled would be a lot of work.

What corner cases do you see that you expect such an amount of work? To me, my initial "regex suggestion" didn't show introduction of many corner cases?! 🤔

> I think we should for now leave the comment handling as it is until there is a design (possible across languages) for what should be done. I'm happy for the discussion to continue here.

As stated above, please do at least some improvement to the escaping & don't let the whole idea of improve comment / documentation (written once, usable across specific languages) just "die" - because that's what I'm most afraid of. 😞

**Comment by tonydnewell** [comment] 2023-02-14 14:55
> What corner cases do you see that you expect such an amount of work? To me, my initial "regex suggestion" didn't show 
 > introduction of many corner cases?! 🤔

Off the top of my head: angle brackets in attribute values, CDATA blocks, tags spanning more than one line, ...

**Comment by jtattermusch** [comment] 2023-02-27 13:46
Due to the above discussion, I'm closing this as working as intended.

**Comment by Eagle3386** [comment] 2023-02-27 18:33
Please don't. 😟

**Closed** 2023-07-04 08:06 UTC
Labels: lang/C#, area/protoc plugins
