### ISSUE TITLE
Failure: tests.cloud_to_prod:default:node:large_unary

### ISSUE THREAD

**Issue by apolcyn** [grpc/grpc#12660] opened 2017-09-20 23:01 UTC
```
tests.cloud_to_prod:default:node:large_unary (from grpc.tests)

Error Message

Failure
Stacktrace

assert.js:586
assert.ifError = function ifError(err) { if (err) throw err; };
                                                  ^

Error: Endpoint read failed
    at /var/local/git/grpc/src/node/src/client.js:554:15tests.cloud_to_prod:default:node:large_unary
```

https://grpc-testing.appspot.com/job/gRPC_interop_pull_requests/16684/testReport/junit/(root)/tests/cloud_to_prod_default_node_large_unary/

**Comment by jtattermusch** [comment] 2017-12-14 17:54
Dupe of https://github.com/grpc/grpc/issues/10763

**Closed by jtattermusch** 2017-12-14 17:54 UTC
Labels: infra/BUILDPONY, lang/node
