### ISSUE TITLE
All python interop tests failing

### ISSUE THREAD

**Issue by markdroth** [grpc/grpc#21994] opened 2020-02-12 16:26 UTC
https://source.cloud.google.com/results/invocations/b6cc1f46-2762-4c49-b973-004395e3dcdb/targets/github%2Fgrpc%2Finterop_test/tests;group=tests;test=cloud_to_prod:python:default:large_unary:tls;row=1

```
Traceback (most recent call last):
  File "src/python/grpcio_tests/setup.py", line 22, in <module>
    import grpc_tools.command
ModuleNotFoundError: No module named 'grpc_tools'
```

**Comment by gnossen** [comment] 2020-02-12 18:20
Dupe of https://github.com/grpc/grpc/issues/21966. This should have been resolved by https://github.com/grpc/grpc/pull/21977. Try merging master into your branch.

**Closed by gnossen** 2020-02-12 18:20 UTC
Labels: kind/bug, lang/Python, priority/P2
