### ISSUE TITLE
grpc-node_macos_opt_native failure

### ISSUE THREAD

**Issue by markdroth** [grpc/grpc#18249] opened 2019-03-05 14:31 UTC
https://source.cloud.google.com/results/invocations/13d57852-6aa5-45ad-a696-a34ef10bbb6c/targets/github%2Fgrpc%2Fgrpc-node_macos_opt_native/tests

```
[96mnode_modules/@types/lodash/common/object.d.ts[0m:[93m1689[0m:[93m12[0m - [91merror[0m[90m TS2304: [0mCannot find name 'Exclude'.
[30;47m1689[0m         ): Exclude<TObject[TKey], undefined> | TDefault;
[30;47m    [0m [91m           ~~~~~~~[0m
[96mnode_modules/@types/lodash/common/object.d.ts[0m:[93m1766[0m:[93m12[0m - [91merror[0m[90m TS2304: [0mCannot find name 'Exclude'.
[30;47m1766[0m         ): Exclude<TObject[TKey], undefined> | TDefault;
[30;47m    [0m [91m           ~~~~~~~[0m
[96mnode_modules/@types/lodash/common/object.d.ts[0m:[93m1842[0m:[93m34[0m - [91merror[0m[90m TS2304: [0mCannot find name 'Exclude'.
[30;47m1842[0m         ): LoDashExplicitWrapper<Exclude<TObject[TKey], undefined> | TDefault>;
[30;47m    [0m [91m                                 ~~~~~~~[0m
npm ERR! Darwin 17.7.0
npm ERR! argv "/Users/kbuilder/.nvm/versions/node/v7.10.1/bin/node" "/Users/kbuilder/.nvm/versions/node/v7.10.1/bin/npm" "run" "compile"
npm ERR! node v7.10.1
npm ERR! npm  v4.2.0
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @grpc/proto-loader@0.4.0 compile: `tsc -p .`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @grpc/proto-loader@0.4.0 compile script 'tsc -p .'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the @grpc/proto-loader package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     tsc -p .
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs @grpc/proto-loader
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls @grpc/proto-loader
npm ERR! There is likely additional logging output above.
npm ERR! Please include the following file with any support request:
npm ERR!     /Users/kbuilder/.npm/_logs/2019-03-05T00_23_25_240Z-debug.log
npm ERR! Darwin 17.7.0
npm ERR! argv "/Users/kbuilder/.nvm/versions/node/v7.10.1/bin/node" "/Users/kbuilder/.nvm/versions/node/v7.10.1/bin/npm" "install" "--unsafe-perm"
npm ERR! node v7.10.1
npm ERR! npm  v4.2.0
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @grpc/proto-loader@0.4.0 prepare: `npm run compile`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @grpc/proto-loader@0.4.0 prepare script 'npm run compile'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the @grpc/proto-loader package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run compile
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs @grpc/proto-loader
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls @grpc/proto-loader
npm ERR! There is likely additional logging output above.
npm ERR! Please include the following file with any support request:
npm ERR!     /Users/kbuilder/.npm/_logs/2019-03-05T00_23_25_274Z-debug.log
[16:23:25] 'protobuf.install' errored after 5.55 s
[16:23:25] Error: Command failed: npm install --unsafe-perm
    at Promise.all.then.arr (/Volumes/BuildData/tmpfs/src/github/grpc/grpc-node/packages/proto-loader/node_modules/execa/index.js:231:11)
    at process._tickCallback (internal/process/next_tick.js:109:7)
[96mnode_modules/@types/lodash/common/object.d.ts[0m:[93m1689[0m:[93m12[0m - [91merror[0m[90m TS2304: [0mCannot find name 'Exclude'.
[30;47m1689[0m         ): Exclude<TObject[TKey], undefined> | TDefault;
[30;47m    [0m [91m           ~~~~~~~[0m
[96mnode_modules/@types/lodash/common/object.d.ts[0m:[93m1766[0m:[93m12[0m - [91merror[0m[90m TS2304: [0mCannot find name 'Exclude'.
[30;47m1766[0m         ): Exclude<TObject[TKey], undefined> | TDefault;
[30;47m    [0m [91m           ~~~~~~~[0m
[96mnode_modules/@types/lodash/common/object.d.ts[0m:[93m1842[0m:[93m34[0m - [91merror[0m[90m TS2304: [0mCannot find name 'Exclude'.
[30;47m1842[0m         ): LoDashExplicitWrapper<Exclude<TObject[TKey], undefined> | TDefault>;
[30;47m    [0m [91m                                 ~~~~~~~[0m
npm ERR! Darwin 17.7.0
npm ERR! argv "/Users/kbuilder/.nvm/versions/node/v7.10.1/bin/node" "/Users/kbuilder/.nvm/versions/node/v7.10.1/bin/npm" "run" "compile"
npm ERR! node v7.10.1
npm ERR! npm  v4.2.0
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @grpc/grpc-js@0.3.5 compile: `tsc -p .`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @grpc/grpc-js@0.3.5 compile script 'tsc -p .'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the @grpc/grpc-js package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     tsc -p .
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs @grpc/grpc-js
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls @grpc/grpc-js
npm ERR! There is likely additional logging output above.
npm ERR! Please include the following file with any support request:
npm ERR!     /Users/kbuilder/.npm/_logs/2019-03-05T00_23_25_858Z-debug.log
npm ERR! Darwin 17.7.0
npm ERR! argv "/Users/kbuilder/.nvm/versions/node/v7.10.1/bin/node" "/Users/kbuilder/.nvm/versions/node/v7.10.1/bin/npm" "install" "--unsafe-perm"
npm ERR! node v7.10.1
npm ERR! npm  v4.2.0
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @grpc/grpc-js@0.3.5 prepare: `npm run compile`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @grpc/grpc-js@0.3.5 prepare script 'npm run compile'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the @grpc/grpc-js package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run compile
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs @grpc/grpc-js
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls @grpc/grpc-js
npm ERR! There is likely additional logging output above.
npm ERR! Please include the following file with any support request:
npm ERR!     /Users/kbuilder/.npm/_logs/2019-03-05T00_23_25_892Z-debug.log
[16:23:25] 'js.core.install' errored after 6.18 s
[16:23:25] Error: Command failed: npm install --unsafe-perm
    at Promise.all.then.arr (/Volumes/BuildData/tmpfs/src/github/grpc/grpc-node/packages/grpc-js/node_modules/execa/index.js:231:11)
    at process._tickCallback (internal/process/next_tick.js:109:7)
```

**Comment by AspirinSJL** [comment] 2019-03-06 00:15
Also seen in Basic Tests Multi-language Linux

**Comment by AspirinSJL** [comment] 2019-03-06 00:18
Raising to P1 because this is happening on 5 test builds.

**Comment by AspirinSJL** [comment] 2019-03-06 00:21
Duplicate of https://github.com/grpc/grpc/issues/18245

**Closed by AspirinSJL** 2019-03-06 00:21 UTC
Labels: infra/BUILDPONY, kind/bug, priority/P1
