### ISSUE TITLE
FAILURE cpp mac opt: bins/opt/grpclb_end2end_test --gtest_filter=SingleBalancerTest.InitiallyEmptyServerlist GRPC_POLL_STRATEGY=poll

### ISSUE THREAD

**Issue by apolcyn** [grpc/grpc#14182] opened 2018-01-25 20:12 UTC
https://sponge.corp.google.com/target?id=6e6e8116-6179-4300-a4d3-eacf774e5ad6&target=github/grpc/cpp_macos_opt_native&searchFor=&show=FAILED&sortBy=STATUS

```
35172411392 grpclb_end2end_test.cc:535]   backend server startup complete
I0124 21:11:49.515432000 140735172411392 grpclb_end2end_test.cc:530]   starting backend server on port 27464
I0124 21:11:49.515519000 123145306058752 server_builder.cc:269]        Synchronous server. Num CQs: 1, Min pollers: 1, Max Pollers: 2, CQ timeout (msec): 10000
I0124 21:11:49.516155000 140735172411392 grpclb_end2end_test.cc:535]   backend server startup complete
I0124 21:11:49.517624000 140735172411392 grpclb_end2end_test.cc:530]   starting backend server on port 16475
I0124 21:11:49.517699000 123145307131904 server_builder.cc:269]        Synchronous server. Num CQs: 1, Min pollers: 1, Max Pollers: 2, CQ timeout (msec): 10000
I0124 21:11:49.518383000 140735172411392 grpclb_end2end_test.cc:535]   backend server startup complete
I0124 21:11:49.519899000 140735172411392 grpclb_end2end_test.cc:530]   starting balancer server on port 23511
I0124 21:11:49.519979000 123145308205056 server_builder.cc:269]        Synchronous server. Num CQs: 1, Min pollers: 1, Max Pollers: 2, CQ timeout (msec): 10000
I0124 21:11:49.520629000 140735172411392 grpclb_end2end_test.cc:535]   balancer server startup complete
I0124 21:11:49.521367000 140735172411392 subchannel.cc:603]            New connected subchannel at 0x7fe322f09fc0 for subchannel 0x7fe322f089d0
I0124 21:11:49.521681000 123145308741632 grpclb_end2end_test.cc:187]   LB[0x7fe322c0aba0]: BalanceLoad
I0124 21:11:49.522177000 123145308741632 grpclb_end2end_test.cc:191]   LB[0x7fe322c0aba0]: recv msg 'initial_request {
  name: "servername_not_used"
}
'
I0124 21:11:49.522203000 123145308741632 grpclb_end2end_test.cc:304]   LB[0x7fe322c0aba0]: sleeping for 0 ms...
I0124 21:11:49.522220000 123145308741632 grpclb_end2end_test.cc:310]   LB[0x7fe322c0aba0]: Woke up! Sending response ''
I0124 21:11:49.522280000 123145308741632 grpclb_end2end_test.cc:304]   LB[0x7fe322c0aba0]: sleeping for 500 ms...
I0124 21:11:50.032694000 123145308741632 grpclb_end2end_test.cc:310]   LB[0x7fe322c0aba0]: Woke up! Sending response 'server_list {
  servers {
    ip_address: "\177\000\000\001"
    port: 25599
  }
  servers {
    ip_address: "\177\000\000\001"
    port: 7944
  }
  servers {
    ip_address: "\177\000\000\001"
    port: 27464
  }
  servers {
    ip_address: "\177\000\000\001"
    port: 16475
  }
}
'
I0124 21:11:50.033368000 140735172411392 grpclb.cc:545]                Missing LB token for backend address 'ipv4:127.0.0.1:25599'. The empty token will be used instead
I0124 21:11:50.033392000 140735172411392 grpclb.cc:545]                Missing LB token for backend address 'ipv4:127.0.0.1:7944'. The empty token will be used instead
I0124 21:11:50.033406000 140735172411392 grpclb.cc:545]                Missing LB token for backend address 'ipv4:127.0.0.1:27464'. The empty token will be used instead
I0124 21:11:50.033647000 140735172411392 grpclb.cc:545]                Missing LB token for backend address 'ipv4:127.0.0.1:16475'. The empty token will be used instead
I0124 21:11:50.218946000 140735172411392 subchannel.cc:603]            New connected subchannel at 0x7fe322e0ac90 for subchannel 0x7fe322f0aa60
I0124 21:11:50.218996000 140735172411392 subchannel.cc:603]            New connected subchannel at 0x7fe322e03730 for subchannel 0x7fe322f0b5e0
I0124 21:11:50.219015000 140735172411392 subchannel.cc:603]            New connected subchannel at 0x7fe322e0acf0 for subchannel 0x7fe322f0b010
I0124 21:11:50.338173000 140735172411392 subchannel.cc:603]            New connected subchannel at 0x7fe3248011b0 for subchannel 0x7fe322f0c3e0
test/cpp/end2end/grpclb_end2end_test.cc:509: Failure
Value of: status.ok()
  Actual: false
Expected: true
code=4 message=Deadline Exceeded
test/cpp/end2end/grpclb_end2end_test.cc:511: Failure
      Expected: response.message()
      Which is: ""
To be equal to: kRequestMessage_
      Which is: "Live long and prosper."
test/cpp/end2end/grpclb_end2end_test.cc:636: Failure
Expected: (ellapsed_ms.count()) < (kCallDeadlineMs), actual: 2243 vs 1000
test/cpp/end2end/grpclb_end2end_test.cc:640: Failure
      Expected: 1U
      Which is: 1
To be equal to: backend_servers_[i].service_->request_count()
      Which is: 0
I0124 21:11:51.764583000 140735172411392 grpclb_end2end_test.cc:140]   Backend: shut down
I0124 21:11:51.764720000 140735172411392 grpclb_end2end_test.cc:554]   backend about to shutdown
I0124 21:11:51.764610000 123145308741632 grpclb_end2end_test.cc:250]   LB[0x7fe322c0aba0]: done
I0124 21:11:52.272355000 140735172411392 grpclb_end2end_test.cc:557]   backend shutdown completed
I0124 21:11:52.272416000 140735172411392 grpclb_end2end_test.cc:140]   Backend: shut down
I0124 21:11:52.272431000 140735172411392 grpclb_end2end_test.cc:554]   backend about to shutdown
I0124 21:11:52.380783000 140735172411392 grpclb_end2end_test.cc:557]   backend shutdown completed
I0124 21:11:52.380825000 140735172411392 grpclb_end2end_test.cc:140]   Backend: shut down
I0124 21:11:52.380836000 140735172411392 grpclb_end2end_test.cc:554]   backend about to shutdown
I0124 21:11:52.380958000 123145303375872 subchannel.cc:641]            Connect failed: {"created":"@1516857112.380788000","description":"Failed to connect to remote host: OS Error","errno":61,"file":"src/core/lib/iomgr/tcp_client_posix.cc","file_line":198,"os_error":"Connection refused","syscall":"connect","target_address":"ipv4:127.0.0.1:25599"}
I0124 21:11:52.381007000 123145303375872 subchannel.cc:466]            Subchannel 0x7fe322f0aa60: Retry in 673 milliseconds
I0124 21:11:52.381585000 140735172411392 grpclb_end2end_test.cc:557]   backend shutdown completed
I0124 21:11:52.381605000 140735172411392 grpclb_end2end_test.cc:140]   Backend: shut down
I0124 21:11:52.381617000 140735172411392 grpclb_end2end_test.cc:554]   backend about to shutdown
I0124 21:11:52.382724000 123145303375872 subchannel.cc:641]            Connect failed: {"created":"@1516857112.382682000","description":"Failed to connect to remote host: OS Error","errno":61,"file":"src/core/lib/iomgr/tcp_client_posix.cc","file_line":198,"os_error":"Connection refused","syscall":"connect","target_address":"ipv4:127.0.0.1:7944"}
I0124 21:11:52.382757000 123145303375872 subchannel.cc:641]            Connect failed: {"created":"@1516857112.382694000","description":"Failed to connect to remote host: OS Error","errno":61,"file":"src/core/lib/iomgr/tcp_client_posix.cc","file_line":198,"os_error":"Connection refused","syscall":"connect","target_address":"ipv4:127.0.0.1:27464"}
I0124 21:11:52.382785000 123145303375872 subchannel.cc:466]            Subchannel 0x7fe322f0b5e0: Retry in 998 milliseconds
I0124 21:11:52.382799000 123145303375872 subchannel.cc:466]            Subchannel 0x7fe322f0b010: Retry in 999 milliseconds
I0124 21:11:52.383467000 123145303375872 subchannel.cc:641]            Connect failed: {"created":"@1516857112.383446000","description":"Failed to connect to remote host: OS Error","errno":61,"file":"src/core/lib/iomgr/tcp_client_posix.cc","file_line":198,"os_error":"Connection refused","syscall":"connect","target_address":"ipv4:127.0.0.1:16475"}
I0124 21:11:52.383590000 123145303375872 subchannel.cc:466]            Subchannel 0x7fe322f0c3e0: Retry in 999 milliseconds
I0124 21:11:52.481585000 140735172411392 grpclb_end2end_test.cc:557]   backend shutdown completed
I0124 21:11:52.481639000 140735172411392 grpclb_end2end_test.cc:265]   LB[0x7fe322c0aba0]: shut down
I0124 21:11:52.481652000 140735172411392 grpclb_end2end_test.cc:554]   balancer about to shutdown
I0124 21:11:52.601735000 140735172411392 grpclb_end2end_test.cc:557]   balancer shutdown completed
[  FAILED  ] SingleBalancerTest.InitiallyEmptyServerlist (3248 ms)
[----------] 1 test from SingleBalancerTest (3248 ms total)

[----------] Global test environment tear-down
[==========] 1 test from 1 test case ran. (3248 ms total)
[  PASSED  ] 0 tests.
[  FAILED  ] 1 test, listed below:
[  FAILED  ] SingleBalancerTest.InitiallyEmptyServerlist

 1 FAILED TEST
D0124 21:11:52.751642000 140735172411392 ev_posix.cc:128]              Using polling engine: poll
D0124 21:11:52.751680000 140735172411392 dns_resolver.cc:294]          Using native dns resolver
```

**Comment by dgquintas** [comment] 2018-05-18 23:14
Reassigning, I don't have access to a mac to repro

**Comment by AspirinSJL** [comment] 2018-06-19 23:30
Duplicate of #15027.

**Closed by AspirinSJL** 2018-06-19 23:30 UTC
Labels: kind/bug, lang/c++, priority/P2
