### ISSUE TITLE
Broken bazel test: //test/cpp/naming:resolver_component_tests_runner_invoker

### ISSUE THREAD

**Issue by jtattermusch** [grpc/grpc#13621] opened 2017-12-04 14:23 UTC
https://source.cloud.google.com/results/invocation/05f9065e-93e5-4b35-ad1f-ab6bfa8b383a/targets/%2F%2Ftest%2Fcpp%2Fnaming:resolver_component_tests_runner_invoker?page=log

```
+ echo 'Retry health-check DNS query to local DNS server over tcp and udp'
Retry health-check DNS query to local DNS server over tcp and udp
+ RETRY=0
+ dig A health-check-local-dns-server-is-alive.resolver-tests.grpctestingexp. @localhost -p 49152 +tries=1 +timeout=1
+ grep 123.123.123.123
/tmp/botexec/bazel-out/k8-fastbuild/bin/test/cpp/naming/resolver_component_tests_runner_invoker.runfiles/__main__/test/cpp/naming/resolver_component_tests_runner: line 46: dig: command not found
+ RETRY=1
+ grep 123.123.123.123
+ dig A health-check-local-dns-server-is-alive.resolver-tests.grpctestingexp. @localhost -p 49152 +tries=1 +timeout=1 +tcp
/tmp/botexec/bazel-out/k8-fastbuild/bin/test/cpp/naming/resolver_component_tests_runner_invoker.runfiles/__main__/test/cpp/naming/resolver_component_tests_runner: line 47: dig: command not found
+ RETRY=1
+ [[ 1 == 0 ]]
+ sleep 0.1
+ (( i++ ))
+ (( i<30 ))
+ echo 'Retry health-check DNS query to local DNS server over tcp and udp'
Retry health-check DNS query to local DNS server over tcp and udp
+ RETRY=0
+ grep 123.123.123.123
+ dig A health-check-local-dns-server-is-alive.resolver-tests.grpctestingexp. @localhost -p 49152 +tries=1 +timeout=1
/tmp/botexec/bazel-out/k8-fastbuild/bin/test/cpp/naming/resolver_component_tests_runner_invoker.runfiles/__main__/test/cpp/naming/resolver_component_tests_runner: line 46: dig: command not found
+ RETRY=1
+ grep 123.123.123.123
+ dig A health-check-local-dns-server-is-alive.resolver-tests.grpctestingexp. @localhost -p 49152 +tries=1 +timeout=1 +tcp
/tmp/botexec/bazel-out/k8-fastbuild/bin/test/cpp/naming/resolver_component_tests_runner_invoker.runfiles/__main__/test/cpp/naming/resolver_component_tests_runner: line 47: dig: command not found
+ RETRY=1
+ [[ 1 == 0 ]]
+ sleep 0.1
```

**Comment by jtattermusch** [comment] 2017-12-04 14:23
Same problem for //test/cpp/naming:resolver_component_tests_runner_invoker_unsecure

**Comment by adelez** [comment] 2018-01-30 23:46
The latest error is https://source.cloud.google.com/results/invocations/f9642869-da7c-433c-81b0-569e151c6352/targets/%2F%2Ftest%2Fcpp%2Fnaming:resolver_component_tests_runner_invoker@poller%3Depoll1/log
exec ${PAGER:-/usr/bin/less} "$0" || exit 1
-----------------------------------------------------------------------------
+ export GRPC_POLL_STRATEGY=epoll1
+ shift
+ test/cpp/naming/resolver_component_tests_runner_invoker --test_bin_name=resolver_component_test --running_under_bazel=true
E0130 22:04:40.525895480      26 subprocess_posix.cc:60]     execv '/tmp/botexec/bazel-out/k8-opt/bin/test/cpp/naming/resolver_component_tests_runner_invoker@poller=epoll1.runfiles/__main__/test/cpp/naming/resolver_component_tests_runner' failed: No such file or directory
Aborted (core dumped)

**Comment by adelez** [comment] 2018-01-30 23:48
Same with resolver_component_tests_runner_invoker_unsecure:
https://source.cloud.google.com/results/invocations/f9642869-da7c-433c-81b0-569e151c6352/targets/%2F%2Ftest%2Fcpp%2Fnaming:resolver_component_tests_runner_invoker_unsecure@poller%3Depoll1/log

**Comment by adelez** [comment] 2018-01-31 19:29
After fixing the path issue to resolver_component_tests_runner, I landed at the same error as described in the original post: "dig: command not found"

**Comment by adelez** [comment] 2018-01-31 19:32
@apolcyn , could you please take a look at this issue? Thanks!

**Comment by apolcyn** [comment] 2018-02-01 04:56
Ack, looking into this again after being OOO earlier this week. There are two missing external deps causing the test to fail, one is `dig`, and the other is the `twisted` python package (and it's dependencies). Looking into a way to express this via bazel and/or adjust the environment of these test runs to make those dependencies available.

**Comment by adelez** [comment] 2018-02-08 19:40
Any updates?

**Comment by apolcyn** [comment] 2018-02-13 01:13
After some successful experimentation, my plan to get this test to run under bazel is:

1) Create a new category of "test-only" bazel dependencies (we need to add a bunch of 3rd-party bazel dependencies in order for this test to work, but we will not want all of those dependencies every time a consumer of grpc calls `grpc_deps()` to load grpc's build/run dependencies)

2) Create `new_http_archive` rules for the whole 3rd-party python dependency tree that this test needs. (the top level python deps that this test has are on the `twisted` and `pyyaml` packages).

3) Either create a new bazel dependency on the `dig` command <i>or</i> get the `dig` command installed on all of the docker images that foundry uses (if that's possible).

**Comment by adelez** [comment] 2018-03-12 18:37
Still not fixed: https://source.cloud.google.com/results/invocations/b2156621-1096-4a14-9342-cc7137c38893/targets

**Comment by apolcyn** [comment] 2018-03-12 20:18
I think the remaining issue here is related to https://github.com/grpc/grpc/issues/14677.

FTR `bazel test //test/cpp/naming:resolver_component_tests_runner_invoker` now works, but indeed
`bazel test //test/cpp/naming:resolver_component_tests_runner_invoker@poller=<poller>` is still broken.

I'm looking into how this can be fixed with the `@poller=` argument.

**Comment by apolcyn** [comment] 2018-03-12 20:43
The exact issue that this test has when running under `@poller=<poller>` is that the `=` sign in the `$TEST_SRCDIR` path (caused by `@poller=<poll>) conflicts with the way that flags are parsed in `https://github.com/grpc/grpc/blob/master/test/cpp/naming/resolver_component_tests_runner.sh#L21` (right now, that test is taking the field within the two `=` signs to be the value of each flag, incorrectly).

Looking into if this argument parsing conflict is specific to the test, or if it would apply to other flag parsers too.

**Closed** 2018-03-14 07:13 UTC
Labels: infra/BUILDPONY, infra/bazel test failures, priority/P1
