### ISSUE TITLE
py34.test.unit._compression_test.CompressionTest Failed

### ISSUE THREAD

**Issue by muxi** [grpc/grpc#9435] opened 2017-01-22 12:26 UTC
Failure appears in test: https://grpc-testing.appspot.com/job/gRPC_pull_requests_linux/2114/console
```
START: py34.test.unit._cython.cygrpc_test.InsecureServerInsecureClient
++ dirname /var/local/git/grpc/tools/run_tests/helper_scripts/run_python.sh
+ cd /var/local/git/grpc/tools/run_tests/helper_scripts/../../..
++ realpath -s py34/bin/python
+ PYTHON=/var/local/git/grpc/py34/bin/python
++ pwd
+ ROOT=/var/local/git/grpc
+ /var/local/git/grpc/py34/bin/python /var/local/git/grpc/src/python/grpcio_tests/setup.py test_lite
running test_lite
Running       unit._compression_test.CompressionTest.testStreaming
[95mTesting gRPC Python...
[0m[91mERROR         unit._compression_test.CompressionTest.testStreaming
[0mRunning       unit._compression_test.CompressionTest.testUnary
[92mSUCCESS       unit._compression_test.CompressionTest.testUnary
[0m2 tests finished:
	1 successful
	1 unsuccessful
	0 skipped
	0 expected failures
	0 unexpected successes
Interrupted Tests:
	[]

Errors/Failures: 
[91munit._compression_test.CompressionTest.testStreaming[0m
[1mtraceback:[0m
Traceback (most recent call last):
  File "/usr/lib/python3.4/unittest/case.py", line 58, in testPartExecutor
    yield
  File "/usr/lib/python3.4/unittest/case.py", line 577, in run
    testMethod()
  File "/var/local/git/grpc/src/python/grpcio_tests/tests/unit/_compression_test.py", line 132, in testStreaming
    for response in call:
  File "/var/local/git/grpc/py34/lib/python3.4/site-packages/grpc/_channel.py", line 368, in __next__
    return self._next()
  File "/var/local/git/grpc/py34/lib/python3.4/site-packages/grpc/_channel.py", line 362, in _next
    raise self
grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with (StatusCode.UNIMPLEMENTED, Method not found!)>

[1mstdout:[0m

[1mstderr:[0m


Unexpected successes: []
Test failure

FAILED: py34.test.unit._compression_test.CompressionTest [ret=1, pid=6435]
```

**Comment by nathanielmanistaatgoogle** [comment] 2017-05-16 22:36
I'm going to call this a duplicate of [issue 10049](https://github.com/grpc/grpc/issues/10049)... and even though I usually like to keep the oldest report around as the "root" issue to which all others are deduplicated, in this case there's more investigation history over there.

**Closed by nathanielmanistaatgoogle** 2017-05-16 22:36 UTC
Labels: BUILDPONY, flaky test, python
