### ISSUE TITLE
CallInvoker does not allow GRPC calls if used in service implementation

### ISSUE THREAD

**Issue by Falco20019** [grpc/grpc#11843] opened 2017-07-17 08:16 UTC
### What version of gRPC and what language are you using?
GRPC 1.4.1 C# from NuGet package
 
### What operating system (Linux, Windows, …) and version?
Windows 7 64-bit
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
C# compiler from within VS2015
 
### What did you do?
- Create an CallInvoker containing a GRPC call (like resolving a service name to a Channel).
- Create a client with this CallInvoker from within a GRPC service implemenetation
- Call a method on this client
 
### What did you expect to see?
The service name to be resolved and the method to finish.
 
### What did you see instead?
The call is getting stuck due to mixture of sync and async code if called from a GRPC thread.
This can only be circumvented by setting GrpcEnvironment.SetCompletionQueueCount(1) or having the name service in a separate process or AppDomain.

Only sync method calls possible, since CallInvoker interface is not async. So not mixing is not possible.
 
### Anything else we should know about your project / environment?
My project contains multiple microservices in one process. They communicate with other outside microservices and each other. So name resolution will definetly happen from within a GRPC thread.

I have no influence on the order of the services being started, so name resolution has to happen at call time. Otherwise I would have resolved the name async before the call. It would be best to have support for resolver plugins like described at https://github.com/grpc/grpc/blob/master/doc/naming.md or like in grpc-java.

I started discussion for this some days ago here: https://groups.google.com/forum/#!topic/grpc-io/ue9lvbprY2I

I assume, this should be irrelevant once grpclb is supported in the C# lib, since I could then just use https://github.com/grpc/grpc/blob/master/src/proto/grpc/lb/v1/load_balancer.proto ? Is there already a timeline when this would happen? In the easiest scenario, it would even be enough for now if C# lib has support for the name resolver as I assume that should be supported earlier since it does not rely on c-ares which is not supported on Windows as per https://github.com/grpc/proposal/blob/master/A5-grpclb-in-dns.md

**Comment by Falco20019** [comment] 2017-07-19 07:11
Another problem with the CallInvoker solution is that I would need to clone the already existing transient error functionality in case the service is not known yet. So really looking forward for name resolver support :)

**Comment by Falco20019** [comment] 2017-07-24 11:23
@jtattermusch please mark as lang/C#

**Comment by jtattermusch** [comment] 2017-07-24 11:49
Based on your description, it sounds like the problem is just "cannot invoke sync RPCs from service handler". You're right that that's currently not allowed (partly because writing such code is against async code best practices) and it boils down to gRPC C# threading model. We're currently considering changing that behavior in #11824, so please track that one for progress.

The other part of problem is that you're trying to implement an async name resolver in C# code (inside CallInvoker) which seems like a hack and shall be discussed under #11879.

It looks like #11824 and #11879 sufficiently cover this issue, so I'm going to close this.

**Closed by jtattermusch** 2017-07-24 11:49 UTC
Labels: lang/C#
