### ISSUE TITLE
Increased CPU consumption in gRPC version 1.47.0

### ISSUE THREAD

**Issue by cardslam** [grpc/grpc#30428] opened 2022-07-28 03:24 UTC
What version of gRPC and what language are you using?
- grpc 1.43.0, c++

What operating system (Linux, Windows,...) and version?
- Red Hat Enterprise Linux release 8.4 (Ootpa)
  Linux 7e66f658a816 5.4.0-122-generic #138-Ubuntu SMP Wed Jun 22 15:00:31 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

What runtime / compiler are you using (e.g. python version or version of gcc)
- gcc (GCC) 8.4.1 20200928 (Red Hat 8.4.1-1)

What did you do?
- I compared and tested grpc 1.43 and 1.47 versions.
  As a server/client implemented in async mode, each channel was opened and 1000 byte RPCs were transmitted 100 consecutively per second, for a total of 1 minute.
  After the transfer was completed, the cpu usage was measured with getrusage(), and it seems that the 1.47 version consumes about 17% more CPU.
  The same results were obtained when the test was repeated several times.

What I expect to know?
- Under the same conditions, can I find out why the CPU consumption varies by version of gRPC?
  Are there any options to reduce CPU consumption?

**Comment by veblush** [comment] 2022-08-02 19:30
@cardslam If you have a chance, would you give us some profiling data for this? Without the profiling data, it's hard to tell why the latest version takes more CPU.

**Comment by cardslam** [comment] 2022-08-05 09:47
@veblush Profile data is here

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/shx.kim/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/shx.kim/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">



ver | sum | server |   |   | client |   |  
-- | -- | -- | -- | -- | -- | -- | --
  |   | total | user | system | total | user | system
1.43.0 | 6.907669 | 3.807753 | 2.603304 | 1.204449 | 3.099916 | 2.238327 | 0.861589
1.47.0 | 8.121918 | 3.168665 | 2.282367 | 0.886298 | 4.953253 | 3.69821 | 1.255043



</body>

</html>

**Comment by mtwebster** [comment] 2022-09-01 16:34
Hi, I think I may  be suffering from this as well - I tried to narrow versions down, and it looks like 1.44.0 is ok, but starting at 1.46.0 the behavior started. I did not try 1.45, as it looks like it was pulled from distribution.

Python 3.10.4 (on Linux Mint 21/Ubuntu 22.04)**
I'm using it via python-grpcio (https://pypi.org/project/grpcio/).
The project I'm working on is [Warpinator](https://github.com/linuxmint/warpinator), a local network file transfer application.

Using 1.44.0 my idle CPU is around 1-3% on average.
With 1.46.* (and continuing in 1.47) I get from 10-25% on idle.

For me, this high CPU happens at idle. If there are multiple devices on a network running warpinator, they'll connect to one another, and remain connected (using grpc keepalives). This elevated cpu occurs with or without any peer connections.

I tried to narrow down the offending operations, but I don't have any debug symbols (I've been extracting from the wheel files).

Here is the perf data and a flamegraph generated from it in case if might be useful:
[python-grpc-1.46-cpu.tar.gz](https://github.com/grpc/grpc/files/9471605/python-grpc-1.46-cpu.tar.gz)

I'm more than willing to do more data collection (I'll build the binaries if needed so I can get symbols).

Thanks

---
** note:
Ordinarily we use the distro package manager's version of python-grpcio, but Mint/Ubuntu's current version - 1.30.2 - completely locks up, so for this distro alone, we've been bundling a newer version of python-grpc. It's reported against Ubuntu so far: https://bugs.launchpad.net/ubuntu/+source/grpc/+bug/1971114 - interestingly, Debian Buster has the same version, but has python 3.9, and it works fine there

**Comment by mtwebster** [comment] 2022-09-02 13:56
I tried to gather a bit more info, I ran the program with some GRPC_TRACE flags - 'api' was particularly useful:
[grpc-trace-api-1.44.0.log](https://github.com/grpc/grpc/files/9478406/grpc-trace-api-1.44.0.log)
[grpc-trace-api-1.48.1.log](https://github.com/grpc/grpc/files/9478408/grpc-trace-api-1.48.1.log)

Looking at the timestamps, the polling interval is about 200ms for 1.44, and 2ms for 1.48.1 - this could easily account for the extra CPU, but it's beyond me why it changed.. I do notice 1.44 uses `epollex` and 1.48.1 uses `epoll1`.

**Comment by mtwebster** [comment] 2022-09-22 15:06
I can also reproduce this using the python grpc example greeter_server.py:

```
GRPC_TRACE=api GRPC_VERBOSITY=info python3 ./greeter_server.py
```
![image](https://user-images.githubusercontent.com/262776/191783007-e1a6ec58-a676-4101-8368-466fcccc0fcf.png)

```
I0922 11:03:44.833264608  725490 completion_queue.cc:968]    grpc_completion_queue_next(cq=0x559f13c464d0, deadline=gpr_timespec { tv_sec: 1663859024, tv_nsec: 833262603, clock_type: 1 }, reserved=(nil))
I0922 11:03:44.834417010  725490 completion_queue.cc:968]    grpc_completion_queue_next(cq=0x559f13c464d0, deadline=gpr_timespec { tv_sec: 1663859024, tv_nsec: 834411809, clock_type: 1 }, reserved=(nil))
I0922 11:03:44.835558650  725490 completion_queue.cc:968]    grpc_completion_queue_next(cq=0x559f13c464d0, deadline=gpr_timespec { tv_sec: 1663859024, tv_nsec: 835554623, clock_type: 1 }, reserved=(nil))
I0922 11:03:44.836588228  725490 completion_queue.cc:968]    grpc_completion_queue_next(cq=0x559f13c464d0, deadline=gpr_timespec { tv_sec: 1663859024, tv_nsec: 836585837, clock_type: 1 }, reserved=(nil))
```

Is this the new normal?  Looking at commits here I guess this came about when epoll1 was dropped.

**Comment by veblush** [comment] 2022-10-11 18:34
Yeah this could be caused by dropping `epollex` happened in the past but it's not clear whether it actually introduced 17% overhead on the client (surprisingly your perf data showed that server load decreased) Anyway we're going to revamp this system by introducing this new [EventEngine](https://github.com/grpc/proposal/search?q=Event+Engine&type=issues). In the meantime, would you check whether this is caused by `epoll1`? you can switch to epoll1 by setting `GRPC_POLL_STRATEGY=epoll1` for the old versions such as 1.43.

**Comment by mtwebster** [comment] 2022-10-11 20:33
Interesting - 200ms with or without on 1.44.0:

```
GRPC_TRACE=api GRPC_VERBOSITY=info python3 ./greeter_server.py

I1011 16:20:19.619272326  143775 init.cc:123]                grpc_init(void)
I1011 16:20:19.619293707  143775 completion_queue.cc:513]    grpc_completion_queue_create_internal(completion_type=0, polling_type=0)
I1011 16:20:19.619302397  143775 init.cc:123]                grpc_init(void)
I1011 16:20:19.619310950  143775 server.cc:1460]             grpc_server_create(0x7f31eb531ba0, (nil))
I1011 16:20:19.619334388  143775 server.cc:1472]             grpc_server_register_completion_queue(server=0x55e9e616ff60, cq=0x55e9e6214450, reserved=(nil))
I1011 16:20:19.619637993  143775 server_chttp2.cc:41]        grpc_server_add_insecure_http2_port(server=0x55e9e616ff60, addr=[::]:50051)
I1011 16:20:19.619694716  143775 socket_utils_common_posix.cc:353] TCP_USER_TIMEOUT is available. TCP_USER_TIMEOUT will be used thereafter
I1011 16:20:19.619728468  143775 init.cc:123]                grpc_init(void)
I1011 16:20:19.619733077  143775 completion_queue.cc:513]    grpc_completion_queue_create_internal(completion_type=0, polling_type=1)
I1011 16:20:19.619737246  143775 server.cc:1472]             grpc_server_register_completion_queue(server=0x55e9e616ff60, cq=0x55e9e62863f0, reserved=(nil))
I1011 16:20:19.619740735  143775 server.cc:1502]             grpc_server_start(server=0x55e9e616ff60)
I1011 16:20:19.619757333  143775 completion_queue.cc:962]    grpc_completion_queue_next(cq=0x55e9e62863f0, deadline=gpr_timespec { tv_sec: 1665519619, tv_nsec: 619751680, clock_type: 1 }, reserved=(nil))
I1011 16:20:19.620868042  143775 init.cc:123]                grpc_init(void)
I1011 16:20:19.620876522  143775 init.cc:123]                grpc_init(void)
I1011 16:20:19.620880172  143775 call_details.cc:31]         grpc_call_details_init(details=0x7f31eb503060)
I1011 16:20:19.620883373  143775 metadata_array.cc:29]       grpc_metadata_array_init(array=0x7f31eb55e470)
I1011 16:20:19.620886894  143775 server.cc:1537]             grpc_server_request_call(server=0x55e9e616ff60, call=0x7f31eb53bbc0, details=0x7f31eb503060, initial_metadata=0x7f31eb55e470, cq_bound_to_call=0x55e9e6214450, cq_for_notification=0x55e9e6214450, tag=0x7f31eb55e440)
I1011 16:20:19.621004858  143779 completion_queue.cc:962]    grpc_completion_queue_next(cq=0x55e9e6214450, deadline=gpr_timespec { tv_sec: 1665519619, tv_nsec: 821002567, clock_type: 1 }, reserved=(nil))
I1011 16:20:19.822233963  143779 completion_queue.cc:962]    grpc_completion_queue_next(cq=0x55e9e6214450, deadline=gpr_timespec { tv_sec: 1665519620, tv_nsec: 22228846, clock_type: 1 }, reserved=(nil))
I1011 16:20:20.023499219  143779 completion_queue.cc:962]    grpc_completion_queue_next(cq=0x55e9e6214450, deadline=gpr_timespec { tv_sec: 1665519620, tv_nsec: 223494512, clock_type: 1 }, reserved=(nil))
I1011 16:20:20.224763690  143779 completion_queue.cc:962]    grpc_completion_queue_next(cq=0x55e9e6214450, deadline=gpr_timespec { tv_sec: 1665519620, tv_nsec: 424759028, clock_type: 1 }, reserved=(nil))
I1011 16:20:20.426031899  143779 completion_queue.cc:962]    grpc_completion_queue_next(cq=0x55e9e6214450, deadline=gpr_timespec { tv_sec: 1665519620, tv_nsec: 621000960, clock_type: 1 }, reserved=(nil))
```

```
> GRPC_POLL_STRATEGY=epoll1 GRPC_TRACE=api GRPC_VERBOSITY=info python3 ./greeter_server.py

I1011 16:19:55.111780219  143712 ev_epoll1_linux.cc:121]     grpc epoll fd: 3
I1011 16:19:55.111905822  143712 init.cc:123]                grpc_init(void)
I1011 16:19:55.111913101  143712 completion_queue.cc:513]    grpc_completion_queue_create_internal(completion_type=0, polling_type=0)
I1011 16:19:55.111919841  143712 init.cc:123]                grpc_init(void)
I1011 16:19:55.111926592  143712 server.cc:1460]             grpc_server_create(0x7fcb1b465880, (nil))
I1011 16:19:55.111952264  143712 server.cc:1472]             grpc_server_register_completion_queue(server=0x55eaa8e5df60, cq=0x55eaa8f02450, reserved=(nil))
I1011 16:19:55.112255711  143712 server_chttp2.cc:41]        grpc_server_add_insecure_http2_port(server=0x55eaa8e5df60, addr=[::]:50051)
I1011 16:19:55.112310776  143712 socket_utils_common_posix.cc:353] TCP_USER_TIMEOUT is available. TCP_USER_TIMEOUT will be used thereafter
I1011 16:19:55.112343464  143712 init.cc:123]                grpc_init(void)
I1011 16:19:55.112348245  143712 completion_queue.cc:513]    grpc_completion_queue_create_internal(completion_type=0, polling_type=1)
I1011 16:19:55.112352123  143712 server.cc:1472]             grpc_server_register_completion_queue(server=0x55eaa8e5df60, cq=0x55eaa8f743f0, reserved=(nil))
I1011 16:19:55.112355159  143712 server.cc:1502]             grpc_server_start(server=0x55eaa8e5df60)
I1011 16:19:55.112362262  143712 completion_queue.cc:962]    grpc_completion_queue_next(cq=0x55eaa8f743f0, deadline=gpr_timespec { tv_sec: 1665519595, tv_nsec: 112360192, clock_type: 1 }, reserved=(nil))
I1011 16:19:55.113430742  143712 init.cc:123]                grpc_init(void)
I1011 16:19:55.113435504  143712 init.cc:123]                grpc_init(void)
I1011 16:19:55.113438070  143712 call_details.cc:31]         grpc_call_details_init(details=0x7fcb1b437060)
I1011 16:19:55.113440860  143712 metadata_array.cc:29]       grpc_metadata_array_init(array=0x7fcb1b492470)
I1011 16:19:55.113443635  143712 server.cc:1537]             grpc_server_request_call(server=0x55eaa8e5df60, call=0x7fcb1b46fbc0, details=0x7fcb1b437060, initial_metadata=0x7fcb1b492470, cq_bound_to_call=0x55eaa8f02450, cq_for_notification=0x55eaa8f02450, tag=0x7fcb1b492440)
I1011 16:19:55.113560187  143716 completion_queue.cc:962]    grpc_completion_queue_next(cq=0x55eaa8f02450, deadline=gpr_timespec { tv_sec: 1665519595, tv_nsec: 313557918, clock_type: 1 }, reserved=(nil))
I1011 16:19:55.314816630  143716 completion_queue.cc:962]    grpc_completion_queue_next(cq=0x55eaa8f02450, deadline=gpr_timespec { tv_sec: 1665519595, tv_nsec: 514811724, clock_type: 1 }, reserved=(nil))
I1011 16:19:55.516056325  143716 completion_queue.cc:962]    grpc_completion_queue_next(cq=0x55eaa8f02450, deadline=gpr_timespec { tv_sec: 1665519595, tv_nsec: 716049705, clock_type: 1 }, reserved=(nil))
I1011 16:19:55.717322003  143716 completion_queue.cc:962]    grpc_completion_queue_next(cq=0x55eaa8f02450, deadline=gpr_timespec { tv_sec: 1665519595, tv_nsec: 917316147, clock_type: 1 }, reserved=(nil))
I1011 16:19:55.918599387  143716 completion_queue.cc:962]    grpc_completion_queue_next(cq=0x55eaa8f02450, deadline=gpr_timespec { tv_sec: 1665519596, tv_nsec: 113555456, clock_type: 1 }, reserved=(nil))
I1011 16:19:56.114838949  143716 completion_queue.cc:962]    grpc_completion_queue_next(cq=0x55eaa8f02450, deadline=gpr_timespec { tv_sec: 1665519596, tv_nsec: 314833606, clock_type: 1 }, reserved=(nil))
I1011 16:19:56.316077007  143716 completion_queue.cc:962]    grpc_completion_queue_next(cq=0x55eaa8f02450, deadline=gpr_timespec { tv_sec: 1665519596, tv_nsec: 516072306, clock_type: 1 }, reserved=(nil))
I1011 16:19:56.517336828  143716 completion_queue.cc:962]    grpc_completion_queue_next(cq=0x55eaa8f02450, deadline=gpr_timespec { tv_sec: 1665519596, tv_nsec: 717331951, clock_type: 1 }, reserved=(nil))
I1011 16:19:56.718604046  143716 completion_queue.cc:962]    grpc_completion_queue_next(cq=0x55eaa8f02450, deadline=gpr_timespec { tv_sec: 1665519596, tv_nsec: 918598635, clock_type: 1 }, reserved=(nil))
```

So I guess some regression from the actual epollex removal?

**Comment by allenporter** [comment] 2022-11-09 15:37
Some additional prior investigations into this: 
- https://github.com/googleapis/python-pubsub/issues/728
- https://github.com/home-assistant/core/issues/66983
- https://github.com/home-assistant/core/issues/72886

When i was previously playing with changing the polling strategy I got inconsistent results when changing to `epoll1` but then also observed that it did not solve the issue.

**Comment by veblush** [comment] 2022-11-15 20:47
It looks like it was caused by epollex removal. We're working to introduce a better model there so I'm closing this. Please feel free to reopen this if needed.

**Closed by veblush** 2022-11-15 20:47 UTC
Labels: kind/bug, priority/P3, untriaged

**Comment by allenporter** [comment] 2022-11-16 02:43
Hi @veblush,  Thanks for the update. Do you have somewhere I can track progress or a rough expectation for a release being targeted? I'd like to be able to give an update or set expectations to some upset end users. Not sure if this a long term effort or short term change.

**Comment by matejsp** [comment] 2023-03-10 14:10
Hi @veblush, is there any update regarding this issue? The better model that you mentioned in november?

**Comment by 4JustMe4** [comment] 2023-05-11 10:56
Hi @veblush, when is it worth waiting for some news?

**Comment by mtwebster** [comment] 2023-11-07 19:33
I didn't bisect which release this first occurred on, but I can no longer reproduce the excessive polling as of python-grpc 1.59, it's back to 200ms. Thanks!
