### ISSUE TITLE
[C#] Grpc.Tools 2.40.0-pre1 error

### ISSUE THREAD

**Issue by JamesNK** [grpc/grpc#27174] opened 2021-08-28 00:47 UTC
This issue - https://github.com/grpc/grpc/issues/26819 - is back in 2.40-pre1.

I think Grpc.Tools needs some kind of automated testing.

**Comment by jtattermusch** [comment] 2021-08-30 06:37
Good catch. Looks like https://github.com/grpc/grpc/pull/26896 was merged after the v1.40.x branch was cut.

We do have some test coverage for Grpc.Tools (e.g. here: https://github.com/grpc/grpc/blob/master/test/distrib/csharp/run_distrib_test_dotnetcli.sh, building DistribTestDotNet.csproj also includes Grpc.Tools codegen)
I'm going to investigate a bit why these tests didn't catch the problem.

**Comment by jtattermusch** [comment] 2021-08-30 07:24
Ok so I think the reason the distribtests didn't catch the problem is that they do include a codegen with Grpc.Tools, but it's only a simple one and it doesn't include any custom grpc_csharp_plugin options, so the for loop that's impacted by the bug never gets to run: 

https://github.com/grpc/grpc/pull/26896/files#diff-a84435c6492be9bfe4fe4663d238de49ffc1caeb462a601f690c2fc0bd049920R49
https://github.com/grpc/grpc/blob/013a45ccc4f0cc99532cb3148ca6ed3f60996711/test/distrib/csharp/DistribTest/DistribTestDotNet.csproj#L30

**Comment by jtattermusch** [comment] 2022-02-14 12:19
Closing with a note that we should improve the Grpc.Tools distribtests to catch similar problems in the future.

**Closed by jtattermusch** 2022-02-14 12:19 UTC
Labels: kind/bug, lang/C#, priority/P2
