### ISSUE TITLE
Decouple new connection timeout from time of next retry

### ISSUE THREAD

**Issue by jtattermusch** [grpc/grpc#8696] opened 2016-11-09 18:29 UTC
Context: #8382

In the current implementation the channel connection deadline and time of the next backoff attempt are the same value. That causes issues because a short initial backoff interval (which seems desirable) leads to a very short timeout for the first connection attempt.

For secure connections, this is even worse, because the entire SSL handshake is counted towards the deadline and if not finished on time, the connection gets closed (even though it is likely that the secure connection would be established correctly once we have the TCP/IP connection ready).
On windows, we are definitely seeing issues when creating many secure connections in parallel, but the issue itself is OS agnostic.

Suggestion: differentiate between "connection attempt timeout/deadline" and "time of next attempt if current attempt fails".

**Comment by jtattermusch** [comment] 2016-11-09 18:30
CC @apolcyn    

@yang-g  can you please assign this to the right person in C core team?

**Comment by yang-g** [comment] 2016-11-09 18:33
I talked with Craig about this before and yes we need to have a fix here.

**Comment by jtattermusch** [comment] 2016-11-09 18:53
https://github.com/grpc/grpc/blob/24e5f3756742e4f65cfefc6c88d10395f1ac92be/src/core/ext/client_channel/subchannel.c#L378

**Comment by markdroth** [comment] 2017-10-16 19:20
I think this is a duplicate of #12867.

**Closed by markdroth** 2017-10-16 19:20 UTC
Labels: area/core
