### ISSUE TITLE
TEST FLAKE: json_run_localhost:cpp_protobuf_sync_streaming_from_server_qps_unconstrained_insecure_low_thread_count GRPC_POLL_STRATEGY=epollsig

### ISSUE THREAD

**Issue by apolcyn** [grpc/grpc#16103] opened 2018-07-23 19:55 UTC
In `cpp_linux_tsan_native_x64_clang7_0`:

noticed on PR: https://github.com/grpc/grpc/pull/16092

```
...
I0723 17:36:45.955219164   23452 driver.cc:374]              Initiating
I0723 17:36:45.955675855   23463 qps_worker.cc:201]          RunClientBody: Message read
I0723 17:36:46.183333336   23463 qps_worker.cc:210]          RunClientBody: Mark response given
I0723 17:36:46.189135146   23452 driver.cc:395]              Warming up
I0723 17:36:46.189167935   23452 driver.cc:401]              Starting
I0723 17:36:46.189809199   23463 qps_worker.cc:201]          RunClientBody: Message read
I0723 17:36:46.192837012   23458 qps_worker.cc:249]          RunServerBody: Message read
I0723 17:36:46.206334936   23458 qps_worker.cc:258]          RunServerBody: Mark response given
I0723 17:36:46.213566155   23463 qps_worker.cc:210]          RunClientBody: Mark response given
I0723 17:36:46.218873668   23452 driver.cc:428]              Running
==================
WARNING: ThreadSanitizer: data race (pid=23450)
  Write of size 8 at 0x7ba000081f20 by thread T29:
    #0 memset /tmp/clang-build/src/compiler-rt/lib/tsan/../sanitizer_common/sanitizer_common_interceptors.inc:752:3 (qps_worker+0x79a599)
    #1 reuse_or_allocate_batch_control(grpc_call*, grpc_op const*, unsigned long) /var/local/git/grpc/src/core/lib/surface/call.cc:1179:5 (qps_worker+0xaaca54)
    #2 call_start_batch(grpc_call*, grpc_op const*, unsigned long, void*, int) /var/local/git/grpc/src/core/lib/surface/call.cc:1609:10 (qps_worker+0xaa8ddc)
    #3 grpc_call_start_batch /var/local/git/grpc/src/core/lib/surface/call.cc:1988:11 (qps_worker+0xaa8b5c)
    #4 grpc::Channel::PerformOpsOnCall(grpc::internal::CallOpSetInterface*, grpc::internal::Call*) /var/local/git/grpc/src/cpp/client/channel_cc.cc:130:3 (qps_worker+0xa91e39)
    #5 non-virtual thunk to grpc::Channel::PerformOpsOnCall(grpc::internal::CallOpSetInterface*, grpc::internal::Call*) /var/local/git/grpc/src/cpp/client/channel_cc.cc (qps_worker+0xa91f2c)
    #6 grpc::internal::Call::PerformOps(grpc::internal::CallOpSetInterface*) /var/local/git/grpc/include/grpcpp/impl/codegen/call.h:680:17 (qps_worker+0x7fe877)
    #7 grpc::ClientReader<grpc::testing::SimpleResponse>::Read(grpc::testing::SimpleResponse*) /var/local/git/grpc/include/grpcpp/impl/codegen/sync_stream.h:213:11 (qps_worker+0x917e6b)
    #8 grpc::testing::SynchronousStreamingFromServerClient::ThreadFuncImpl(grpc::testing::HistogramEntry*, unsigned long) /var/local/git/grpc/test/cpp/qps/client_sync.cc:355:30 (qps_worker+0x99ce94)
    #9 grpc::testing::SynchronousClient::ThreadFunc(unsigned long, grpc::testing::Client::Thread*) /var/local/git/grpc/test/cpp/qps/client_sync.cc:75:36 (qps_worker+0x9869f6)
    #10 grpc::testing::Client::Thread::ThreadFunc() /var/local/git/grpc/./test/cpp/qps/client.h:324:16 (qps_worker+0x9676d7)
    #11 void std::_Mem_fn<void (grpc::testing::Client::Thread::*)()>::operator()<, void>(grpc::testing::Client::Thread*) const /usr/lib/gcc/x86_64-linux-gnu/4.9/../../../../include/c++/4.9/functional:569:11 (qps_worker+0x969513)
    #12 void std::_Bind_simple<std::_Mem_fn<void (grpc::testing::Client::Thread::*)()> (grpc::testing::Client::Thread*)>::_M_invoke<0ul>(std::_Index_tuple<0ul>) /usr/lib/gcc/x86_64-linux-gnu/4.9/../../../../include/c++/4.9/functional:1699:18 (qps_worker+0x9693e5)
    #13 std::_Bind_simple<std::_Mem_fn<void (grpc::testing::Client::Thread::*)()> (grpc::testing::Client::Thread*)>::operator()() /usr/lib/gcc/x86_64-linux-gnu/4.9/../../../../include/c++/4.9/functional:1688:16 (qps_worker+0x969358)
    #14 std::thread::_Impl<std::_Bind_simple<std::_Mem_fn<void (grpc::testing::Client::Thread::*)()> (grpc::testing::Client::Thread*)> >::_M_run() /usr/lib/gcc/x86_64-linux-gnu/4.9/../../../../include/c++/4.9/thread:115:13 (qps_worker+0x968e8c)
    #15 <null> <null> (libstdc++.so.6+0xb696f)
  Previous read of size 1 at 0x7ba000081f20 by thread T102:
    #0 perform_stream_op_locked(void*, grpc_error*) /var/local/git/grpc/src/core/ext/transport/chttp2/transport/chttp2_transport.cc:1594:11 (qps_worker+0xce417b)
    #1 grpc_combiner_continue_exec_ctx() /var/local/git/grpc/src/core/lib/iomgr/combiner.cc:260:5 (qps_worker+0xa055c1)
    #2 grpc_core::ExecCtx::Flush() /var/local/git/grpc/src/core/lib/iomgr/exec_ctx.cc:131:17 (qps_worker+0x9cf48a)
    #3 GrpcExecutor::RunClosures(char const*, grpc_closure_list) /var/local/git/grpc/src/core/lib/iomgr/executor.cc:79:32 (qps_worker+0xa093ae)
    #4 GrpcExecutor::ThreadMain(void*) /var/local/git/grpc/src/core/lib/iomgr/executor.cc:191:22 (qps_worker+0xa09aa8)
    #5 grpc_core::(anonymous namespace)::ThreadInternalsPosix::ThreadInternalsPosix(char const*, void (*)(void*), void*, bool*)::{lambda(void*)#1}::operator()(void*) const /var/local/git/grpc/src/core/lib/gprpp/thd_posix.cc:100:27 (qps_worker+0xa9037c)
    #6 grpc_core::(anonymous namespace)::ThreadInternalsPosix::ThreadInternalsPosix(char const*, void (*)(void*), void*, bool*)::{lambda(void*)#1}::__invoke(void*) /var/local/git/grpc/src/core/lib/gprpp/thd_posix.cc:74:25 (qps_worker+0xa90218)
  Location is heap block of size 14695 at 0x7ba000080000 allocated by thread T29:
    #0 malloc /tmp/clang-build/src/compiler-rt/lib/tsan/rtl/tsan_interceptors.cc:666:5 (qps_worker+0x78f307)
    #1 gpr_malloc /var/local/git/grpc/src/core/lib/gpr/alloc.cc:57:7 (qps_worker+0xa87ea8)
    #2 gpr_malloc_aligned /var/local/git/grpc/src/core/lib/gpr/alloc.cc:93:13 (qps_worker+0xa8810f)
    #3 zalloc_aligned(unsigned long) /var/local/git/grpc/src/core/lib/gpr/arena.cc:92:15 (qps_worker+0xb43abf)
    #4 gpr_arena_alloc(gpr_arena*, unsigned long) /var/local/git/grpc/src/core/lib/gpr/arena.cc:127:35 (qps_worker+0xb43d28)
    #5 gpr_arena_alloc(gpr_arena*, unsigned long) /var/local/git/grpc/src/core/lib/gpr/arena.cc:140:12 (qps_worker+0xb43e9d)
    #6 grpc_core::ConnectedSubchannel::CreateCall(grpc_core::ConnectedSubchannel::CallArgs const&, grpc_subchannel_call**) /var/local/git/grpc/src/core/ext/filters/client_channel/subchannel.cc:818:7 (qps_worker+0xb22411)
    #7 create_subchannel_call(grpc_call_element*, grpc_error*) /var/local/git/grpc/src/core/ext/filters/client_channel/client_channel.cc:2566:61 (qps_worker+0xb0a28c)
    #8 pick_done(void*, grpc_error*) /var/local/git/grpc/src/core/ext/filters/client_channel/client_channel.cc:2618:5 (qps_worker+0xb0a03c)
    #9 exec_ctx_run(grpc_closure*, grpc_error*) /var/local/git/grpc/src/core/lib/iomgr/exec_ctx.cc:40:3 (qps_worker+0x9cf6e9)
    #10 grpc_core::ExecCtx::Flush() /var/local/git/grpc/src/core/lib/iomgr/exec_ctx.cc:128:9 (qps_worker+0x9cf473)
    #11 grpc_core::ExecCtx::~ExecCtx() /var/local/git/grpc/./src/core/lib/iomgr/exec_ctx.h:108:5 (qps_worker+0x9c0ed2)
    #12 grpc_call_start_batch /var/local/git/grpc/src/core/lib/surface/call.cc:1992:1 (qps_worker+0xaa8b71)
    #13 grpc::Channel::PerformOpsOnCall(grpc::internal::CallOpSetInterface*, grpc::internal::Call*) /var/local/git/grpc/src/cpp/client/channel_cc.cc:130:3 (qps_worker+0xa91e39)
    #14 non-virtual thunk to grpc::Channel::PerformOpsOnCall(grpc::internal::CallOpSetInterface*, grpc::internal::Call*) /var/local/git/grpc/src/cpp/client/channel_cc.cc (qps_worker+0xa91f2c)
    #15 grpc::internal::Call::PerformOps(grpc::internal::CallOpSetInterface*) /var/local/git/grpc/include/grpcpp/impl/codegen/call.h:680:17 (qps_worker+0x7fe877)
    #16 grpc::ClientReader<grpc::testing::SimpleResponse>::ClientReader<grpc::testing::SimpleRequest>(grpc::ChannelInterface*, grpc::internal::RpcMethod const&, grpc::ClientContext*, grpc::testing::SimpleRequest const&) /var/local/git/grpc/include/grpcpp/impl/codegen/sync_stream.h:258:11 (qps_worker+0x9176fc)
    #17 grpc::ClientReader<grpc::testing::SimpleResponse>* grpc::internal::ClientReaderFactory<grpc::testing::SimpleResponse>::Create<grpc::testing::SimpleRequest>(grpc::ChannelInterface*, grpc::internal::RpcMethod const&, grpc::ClientContext*, grpc::testing::SimpleRequest const&) /var/local/git/grpc/include/grpcpp/impl/codegen/sync_stream.h:167:16 (qps_worker+0x903e7e)
    #18 grpc::testing::BenchmarkService::Stub::StreamingFromServerRaw(grpc::ClientContext*, grpc::testing::SimpleRequest const&) /var/local/git/grpc/gens/src/proto/grpc/testing/benchmark_service.grpc.pb.cc:78:10 (qps_worker+0x901c21)
    #19 grpc::testing::BenchmarkService::Stub::StreamingFromServer(grpc::ClientContext*, grpc::testing::SimpleRequest const&) /var/local/git/grpc/gens/src/proto/grpc/testing/benchmark_service.grpc.pb.h:154:87 (qps_worker+0x9a33a3)
    #20 grpc::testing::SynchronousStreamingFromServerClient::InitThreadFuncImpl(unsigned long) /var/local/git/grpc/test/cpp/qps/client_sync.cc:345:17 (qps_worker+0x99ccc2)
    #21 grpc::testing::SynchronousClient::ThreadFunc(unsigned long, grpc::testing::Client::Thread*) /var/local/git/grpc/test/cpp/qps/client_sync.cc:69:10 (qps_worker+0x98699b)
    #22 grpc::testing::Client::Thread::ThreadFunc() /var/local/git/grpc/./test/cpp/qps/client.h:324:16 (qps_worker+0x9676d7)
    #23 void std::_Mem_fn<void (grpc::testing::Client::Thread::*)()>::operator()<, void>(grpc::testing::Client::Thread*) const /usr/lib/gcc/x86_64-linux-gnu/4.9/../../../../include/c++/4.9/functional:569:11 (qps_worker+0x969513)
    #24 void std::_Bind_simple<std::_Mem_fn<void (grpc::testing::Client::Thread::*)()> (grpc::testing::Client::Thread*)>::_M_invoke<0ul>(std::_Index_tuple<0ul>) /usr/lib/gcc/x86_64-linux-gnu/4.9/../../../../include/c++/4.9/functional:1699:18 (qps_worker+0x9693e5)
    #25 std::_Bind_simple<std::_Mem_fn<void (grpc::testing::Client::Thread::*)()> (grpc::testing::Client::Thread*)>::operator()() /usr/lib/gcc/x86_64-linux-gnu/4.9/../../../../include/c++/4.9/functional:1688:16 (qps_worker+0x969358)
    #26 std::thread::_Impl<std::_Bind_simple<std::_Mem_fn<void (grpc::testing::Client::Thread::*)()> (grpc::testing::Client::Thread*)> >::_M_run() /usr/lib/gcc/x86_64-linux-gnu/4.9/../../../../include/c++/4.9/thread:115:13 (qps_worker+0x968e8c)
    #27 <null> <null> (libstdc++.so.6+0xb696f)
  Thread T29 (tid=23595, running) created by thread T4 at:
    #0 pthread_create /tmp/clang-build/src/compiler-rt/lib/tsan/rtl/tsan_interceptors.cc:992:3 (qps_worker+0x790dd5)
    #1 std::thread::_M_start_thread(std::shared_ptr<std::thread::_Impl_base>) <null> (libstdc++.so.6+0xb6a90)
    #2 grpc::testing::Client::Thread::Thread(grpc::testing::Client*, unsigned long) /var/local/git/grpc/./test/cpp/qps/client.h:283:39 (qps_worker+0x965bd2)
    #3 grpc::testing::Client::StartThreads(unsigned long) /var/local/git/grpc/./test/cpp/qps/client.h:223:33 (qps_worker+0x944670)
    #4 grpc::testing::SynchronousStreamingClient<grpc::ClientReader<grpc::testing::SimpleResponse> >::SynchronousStreamingClient(grpc::testing::ClientConfig const&) /var/local/git/grpc/test/cpp/qps/client_sync.cc:155:5 (qps_worker+0x99c8d9)
    #5 grpc::testing::SynchronousStreamingFromServerClient::SynchronousStreamingFromServerClient(grpc::testing::ClientConfig const&) /var/local/git/grpc/test/cpp/qps/client_sync.cc:334:9 (qps_worker+0x9864af)
    #6 grpc::testing::CreateSynchronousClient(grpc::testing::ClientConfig const&) /var/local/git/grpc/test/cpp/qps/client_sync.cc:417:15 (qps_worker+0x985c55)
    #7 grpc::testing::CreateClient(grpc::testing::ClientConfig const&) /var/local/git/grpc/test/cpp/qps/qps_worker.cc:58:14 (qps_worker+0x7faff7)
    #8 grpc::testing::WorkerServiceImpl::RunClientBody(grpc::ServerContext*, grpc::ServerReaderWriter<grpc::testing::ClientStatus, grpc::testing::ClientArgs>*) /var/local/git/grpc/test/cpp/qps/qps_worker.cc:190:19 (qps_worker+0x8046de)
    #9 grpc::testing::WorkerServiceImpl::RunClient(grpc::ServerContext*, grpc::ServerReaderWriter<grpc::testing::ClientStatus, grpc::testing::ClientArgs>*) /var/local/git/grpc/test/cpp/qps/qps_worker.cc:113:18 (qps_worker+0x7fbf80)
    #10 grpc::Status std::_Mem_fn<grpc::Status (grpc::testing::WorkerService::Service::*)(grpc::ServerContext*, grpc::ServerReaderWriter<grpc::testing::ClientStatus, grpc::testing::ClientArgs>*)>::operator()<grpc::ServerContext*, grpc::ServerReaderWriter<grpc::testing::ClientStatus, grpc::testing::ClientArgs>*, void>(grpc::testing::WorkerService::Service*, grpc::ServerContext*&&, grpc::ServerReaderWriter<grpc::testing::ClientStatus, grpc::testing::ClientArgs>*&&) const /usr/lib/gcc/x86_64-linux-gnu/4.9/../../../../include/c++/4.9/functional:569:11 (qps_worker+0x93ac27)
    #11 std::_Function_handler<grpc::Status (grpc::testing::WorkerService::Service*, grpc::ServerContext*, grpc::ServerReaderWriter<grpc::testing::ClientStatus, grpc::testing::ClientArgs>*), std::_Mem_fn<grpc::Status (grpc::testing::WorkerService::Service::*)(grpc::ServerContext*, grpc::ServerReaderWriter<grpc::testing::ClientStatus, grpc::testing::ClientArgs>*)> >::_M_invoke(std::_Any_data const&, grpc::testing::WorkerService::Service*, grpc::ServerContext*, grpc::ServerReaderWriter<grpc::testing::ClientStatus, grpc::testing::ClientArgs>*) /usr/lib/gcc/x86_64-linux-gnu/4.9/../../../../include/c++/4.9/functional:2024:9 (qps_worker+0x93a83c)
    #12 std::function<grpc::Status (grpc::testing::WorkerService::Service*, grpc::ServerContext*, grpc::ServerReaderWriter<grpc::testing::ClientStatus, grpc::testing::ClientArgs>*)>::operator()(grpc::testing::WorkerService::Service*, grpc::ServerContext*, grpc::ServerReaderWriter<grpc::testing::ClientStatus, grpc::testing::ClientArgs>*) const /usr/lib/gcc/x86_64-linux-gnu/4.9/../../../../include/c++/4.9/functional:2439:14 (qps_worker+0x93c6c7)
    #13 grpc::Status std::_Bind<std::function<grpc::Status (grpc::testing::WorkerService::Service*, grpc::ServerContext*, grpc::ServerReaderWriter<grpc::testing::ClientStatus, grpc::testing::ClientArgs>*)> (grpc::testing::WorkerService::Service*, std::_Placeholder<1>, std::_Placeholder<2>)>::__call<grpc::Status, grpc::ServerContext*&&, grpc::ServerReaderWriter<grpc::testing::ClientStatus, grpc::testing::ClientArgs>*&&, 0ul, 1ul, 2ul>(std::tuple<grpc::ServerContext*&&, grpc::ServerReaderWriter<grpc::testing::ClientStatus, grpc::testing::ClientArgs>*&&>&&, std::_Index_tuple<0ul, 1ul, 2ul>) /usr/lib/gcc/x86_64-linux-gnu/4.9/../../../../include/c++/4.9/functional:1263:11 (qps_worker+0x93c4d2)
    #14 grpc::Status std::_Bind<std::function<grpc::Status (grpc::testing::WorkerService::Service*, grpc::ServerContext*, grpc::ServerReaderWriter<grpc::testing::ClientStatus, grpc::testing::ClientArgs>*)> (grpc::testing::WorkerService::Service*, std::_Placeholder<1>, std::_Placeholder<2>)>::operator()<grpc::ServerContext*, grpc::ServerReaderWriter<grpc::testing::ClientStatus, grpc::testing::ClientArgs>*, grpc::Status>(grpc::ServerContext*&&, grpc::ServerReaderWriter<grpc::testing::ClientStatus, grpc::testing::ClientArgs>*&&) /usr/lib/gcc/x86_64-linux-gnu/4.9/../../../../include/c++/4.9/functional:1321:17 (qps_worker+0x93c36b)
    #15 std::_Function_handler<grpc::Status (grpc::ServerContext*, grpc::ServerReaderWriter<grpc::testing::ClientStatus, grpc::testing::ClientArgs>*), std::_Bind<std::function<grpc::Status (grpc::testing::WorkerService::Service*, grpc::ServerContext*, grpc::ServerReaderWriter<grpc::testing::ClientStatus, grpc::testing::ClientArgs>*)> (grpc::testing::WorkerService::Service*, std::_Placeholder<1>, std::_Placeholder<2>)> >::_M_invoke(std::_Any_data const&, grpc::ServerContext*, grpc::ServerReaderWriter<grpc::testing::ClientStatus, grpc::testing::ClientArgs>*) /usr/lib/gcc/x86_64-linux-gnu/4.9/../../../../include/c++/4.9/functional:2024:9 (qps_worker+0x93bcf0)
    #16 std::function<grpc::Status (grpc::ServerContext*, grpc::ServerReaderWriter<grpc::testing::ClientStatus, grpc::testing::ClientArgs>*)>::operator()(grpc::ServerContext*, grpc::ServerReaderWriter<grpc::testing::ClientStatus, grpc::testing::ClientArgs>*) const /usr/lib/gcc/x86_64-linux-gnu/4.9/../../../../include/c++/4.9/functional:2439:14 (qps_worker+0x93ec25)
    #17 grpc::internal::TemplatedBidiStreamingHandler<grpc::ServerReaderWriter<grpc::testing::ClientStatus, grpc::testing::ClientArgs>, false>::RunHandler(grpc::internal::MethodHandler::HandlerParameter const&)::{lambda()#1}::operator()() const /var/local/git/grpc/include/grpcpp/impl/codegen/method_handler_impl.h:204:14 (qps_worker+0x93eaf5)
    #18 grpc::Status grpc::internal::CatchingFunctionHandler<grpc::internal::TemplatedBidiStreamingHandler<grpc::ServerReaderWriter<grpc::testing::ClientStatus, grpc::testing::ClientArgs>, false>::RunHandler(grpc::internal::MethodHandler::HandlerParameter const&)::{lambda()#1}>(grpc::internal::TemplatedBidiStreamingHandler<grpc::ServerReaderWriter<grpc::testing::ClientStatus, grpc::testing::ClientArgs>, false>::RunHandler(grpc::internal::MethodHandler::HandlerParameter const&)::{lambda()#1}&&) /var/local/git/grpc/include/grpcpp/impl/codegen/method_handler_impl.h:42:12 (qps_worker+0x93d1e7)
    #19 grpc::internal::TemplatedBidiStreamingHandler<grpc::ServerReaderWriter<grpc::testing::ClientStatus, grpc::testing::ClientArgs>, false>::RunHandler(grpc::internal::MethodHandler::HandlerParameter const&) /var/local/git/grpc/include/grpcpp/impl/codegen/method_handler_impl.h:203:21 (qps_worker+0x93b2c8)
    #20 grpc::Server::SyncRequest::CallData::Run(std::shared_ptr<grpc::Server::GlobalCallbacks> const&) /var/local/git/grpc/src/cpp/server/server_cc.cc:225:27 (qps_worker+0xa7991d)
    #21 grpc::Server::SyncRequestThreadManager::DoWork(void*, bool) /var/local/git/grpc/src/cpp/server/server_cc.cc:317:10 (qps_worker+0xa781e0)
    #22 grpc::ThreadManager::MainWorkLoop() /var/local/git/grpc/src/cpp/thread_manager/thread_manager.cc:155:9 (qps_worker+0xa836f0)
    #23 grpc::ThreadManager::WorkerThread::Run() /var/local/git/grpc/src/cpp/thread_manager/thread_manager.cc:42:13 (qps_worker+0xa83408)
    #24 grpc::ThreadManager::WorkerThread::WorkerThread(grpc::ThreadManager*)::$_0::operator()(void*) const /var/local/git/grpc/src/cpp/thread_manager/thread_manager.cc:36:69 (qps_worker+0xa842f4)
    #25 grpc::ThreadManager::WorkerThread::WorkerThread(grpc::ThreadManager*)::$_0::__invoke(void*) /var/local/git/grpc/src/cpp/thread_manager/thread_manager.cc:36:7 (qps_worker+0xa84298)
    #26 grpc_core::(anonymous namespace)::ThreadInternalsPosix::ThreadInternalsPosix(char const*, void (*)(void*), void*, bool*)::{lambda(void*)#1}::operator()(void*) const /var/local/git/grpc/src/core/lib/gprpp/thd_posix.cc:100:27 (qps_worker+0xa9037c)
    #27 grpc_core::(anonymous namespace)::ThreadInternalsPosix::ThreadInternalsPosix(char const*, void (*)(void*), void*, bool*)::{lambda(void*)#1}::__invoke(void*) /var/local/git/grpc/src/core/lib/gprpp/thd_posix.cc:74:25 (qps_worker+0xa90218)
  Thread T102 'default-executo' (tid=23570, running) created by thread T16 at:
    #0 pthread_create /tmp/clang-build/src/compiler-rt/lib/tsan/rtl/tsan_interceptors.cc:992:3 (qps_worker+0x790dd5)
    #1 grpc_core::(anonymous namespace)::ThreadInternalsPosix::ThreadInternalsPosix(char const*, void (*)(void*), void*, bool*) /var/local/git/grpc/src/core/lib/gprpp/thd_posix.cc:73:10 (qps_worker+0xa8ff26)
    #2 grpc_core::(anonymous namespace)::ThreadInternalsPosix* grpc_core::New<grpc_core::(anonymous namespace)::ThreadInternalsPosix, char const*&, void (*&)(void*), void*&, bool*>(char const*&, void (*&)(void*), void*&, bool*&&) /var/local/git/grpc/./src/core/lib/gprpp/memory.h:52:18 (qps_worker+0xa8fbe3)
    #3 grpc_core::Thread::Thread(char const*, void (*)(void*), void*, bool*) /var/local/git/grpc/src/core/lib/gprpp/thd_posix.cc:142:7 (qps_worker+0xa8fa04)
    #4 GrpcExecutor::Enqueue(grpc_closure*, grpc_error*, bool) /var/local/git/grpc/src/core/lib/iomgr/executor.cc:306:44 (qps_worker+0xa0a4f7)
    #5 default_enqueue_short(grpc_closure*, grpc_error*) /var/local/git/grpc/src/core/lib/iomgr/executor.cc:322:37 (qps_worker+0xa0a693)
    #6 grpc_closure_sched(char const*, int, grpc_closure*, grpc_error*) /var/local/git/grpc/./src/core/lib/iomgr/closure.h:298:5 (qps_worker+0x9c67eb)
    #7 write_action_begin_locked(void*, grpc_error*) /var/local/git/grpc/src/core/ext/transport/chttp2/transport/chttp2_transport.cc:994:5 (qps_worker+0xccf8e3)
    #8 grpc_combiner_continue_exec_ctx() /var/local/git/grpc/src/core/lib/iomgr/combiner.cc:276:7 (qps_worker+0xa057b9)
    #9 grpc_core::ExecCtx::Flush() /var/local/git/grpc/src/core/lib/iomgr/exec_ctx.cc:131:17 (qps_worker+0x9cf48a)
    #10 GrpcExecutor::RunClosures(char const*, grpc_closure_list) /var/local/git/grpc/src/core/lib/iomgr/executor.cc:79:32 (qps_worker+0xa093ae)
    #11 GrpcExecutor::ThreadMain(void*) /var/local/git/grpc/src/core/lib/iomgr/executor.cc:191:22 (qps_worker+0xa09aa8)
    #12 grpc_core::(anonymous namespace)::ThreadInternalsPosix::ThreadInternalsPosix(char const*, void (*)(void*), void*, bool*)::{lambda(void*)#1}::operator()(void*) const /var/local/git/grpc/src/core/lib/gprpp/thd_posix.cc:100:27 (qps_worker+0xa9037c)
    #13 grpc_core::(anonymous namespace)::ThreadInternalsPosix::ThreadInternalsPosix(char const*, void (*)(void*), void*, bool*)::{lambda(void*)#1}::__invoke(void*) /var/local/git/grpc/src/core/lib/gprpp/thd_posix.cc:74:25 (qps_worker+0xa90218)
SUMMARY: ThreadSanitizer: data race /var/local/git/grpc/src/core/lib/surface/call.cc:1179:5 in reuse_or_allocate_batch_control(grpc_call*, grpc_op const*, unsigned long)
==================
I0723 17:36:47.189308915   23452 driver.cc:442]              Finishing clients
D0723 17:36:47.191337673   23465 dns_resolver.cc:280]        Start resolving.
E0723 17:36:47.191469106   23452 driver.cc:467]              Couldn't get final status from client 0
E0723 17:36:47.191781858   23452 driver.cc:475]              Client 0 had an error OS Error
I0723 17:36:47.192128396   23452 driver.cc:488]              Finishing servers
I0723 17:36:47.192746881   23458 qps_worker.cc:249]          RunServerBody: Message read
I0723 17:36:47.197068274   23458 qps_worker.cc:258]          RunServerBody: Mark response given
I0723 17:36:47.197138781   23458 qps_worker.cc:261]          RunServerBody: Returning
I0723 17:36:47.198862213   23458 qps_worker.cc:128]          RunServer: Returning
I0723 17:36:47.199499477   23452 driver.cc:502]              Received final status from server 0
I0723 17:36:47.203880760   23452 report.cc:82]               QPS: -nan
...
```

https://source.cloud.google.com/results/invocations/c2ca96b1-4bd6-4e0b-8b0c-342da85295c8/targets/github%2Fgrpc%2Fcpp_linux_tsan_native_x64_clang7.0/tests

BigQuery shows that this test is failing at ~14%

**Comment by markdroth** [comment] 2019-03-08 23:20
Duplicate of #16369.

**Closed by markdroth** 2019-03-08 23:20 UTC
Labels: kind/bug, lang/core, priority/P2
