### ISSUE TITLE
Failed to deserialize response message.

### ISSUE THREAD

**Issue by CGQAQ** [grpc/grpc#20134] opened 2019-08-30 04:31 UTC
### What version of gRPC and what language are you using?
C#

### What operating system (Linux, Windows,...) and version?
Windows 7 x64

### What runtime / compiler are you using (e.g. python version or version of gcc)
.net 4.6

### What did you do?
[source code](https://github.com/2dust/v2rayN/blob/d0ca8b2996754eab826da6c1ce50ce157c6a42f3/v2rayN/v2rayN/Handler/StatisticsHandler.cs#L108)

### What did you expect to see?
normal return rpc

### What did you see instead?

```
Grpc.Core.RpcException: Status(StatusCode=Internal, Detail="Failed to deserialize response message.")
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Grpc.Core.Internal.AsyncCall`2.UnaryCall(TRequest msg)
   at Grpc.Core.DefaultCallInvoker.BlockingUnaryCall[TRequest,TResponse](Method`2 method, String host, CallOptions options, TRequest request)
   at Grpc.Core.Interceptors.InterceptingCallInvoker.<BlockingUnaryCall>b__3_0[TRequest,TResponse](TRequest req, ClientInterceptorContext`2 ctx)
   at Grpc.Core.ClientBase.ClientBaseConfiguration.ClientBaseConfigurationInterceptor.BlockingUnaryCall[TRequest,TResponse](TRequest request, ClientInterceptorContext`2 context, BlockingUnaryCallContinuation`2 continuation)
   at Grpc.Core.Interceptors.InterceptingCallInvoker.BlockingUnaryCall[TRequest,TResponse](Method`2 method, String host, CallOptions options, TRequest request)
   at v2rayN.Protos.Statistics.StatsService.StatsServiceClient.QueryStats(QueryStatsRequest request, CallOptions options)
   at v2rayN.Protos.Statistics.StatsService.StatsServiceClient.QueryStats(QueryStatsRequest request, Metadata headers, Nullable`1 deadline, CancellationToken cancellationToken)
   at v2rayN.Handler.StatisticsHandler.Run()
```

### Anything else we should know about your project / environment?
in Windows 10 x64 .Net 4.6 everything was ok, but windows 7 x64 .Net 6.4 will raise an exception

**Comment by raulpereztangelo** [comment] 2019-09-04 10:54
Happens to me in the Unity package too. Using osx.

1.21 was fine but from there on it fails with that message.

**Comment by jtattermusch** [comment] 2019-09-17 12:41
CGQAQ can you check the content of the response with (e.g. with help of a debugger) and see if that's a well formed protobuf message (equivalent to the one that you sent out on the server?).

**Comment by CGQAQ** [comment] 2019-09-17 12:56
It has been solved by another guy by add a **netstandard.dll** to windows 7 executable file, seems in the Windows 7, don't have some features that gRPC required

**Comment by jtattermusch** [comment] 2019-09-17 16:16
> It has been solved by another guy by add a **netstandard.dll** to windows 7 executable path, seems in the Windows 7, don't have some features that gRPC required

Can you provide a link?

**Comment by CGQAQ** [comment] 2019-09-17 16:41
> > It has been solved by another guy by add a **netstandard.dll** to windows 7 executable path, seems in the Windows 7, don't have some features that gRPC required
> 
> Can you provide a link?

Source code link above, master branch, is the fixed version

**Comment by jtattermusch** [comment] 2019-11-07 17:15
@raulpereztangelo  is this still a problem in the latest release?

**Comment by raulpereztangelo** [comment] 2019-11-07 18:12
> @raulpereztangelo is this still a problem in the latest release?

We updated two weeks ago and have no issues with that build, can't know the exact release we're using right now. If it helps I can come back to you tomorrow.

**Comment by anon17** [comment] 2020-04-13 16:48
I believe during deserialization happens an exception due to a missing dll, but it gets discarded and instead of it an RpcException is delivered to the caller. That said, RpcException has no constructor that accepts inner exception. Such loss of the source exception complicates diagnostic.

**Comment by anon17** [comment] 2020-04-13 17:00
[The deserialization exception is lost here](https://github.com/grpc/grpc/blob/master/src/csharp/Grpc.Core/Internal/AsyncCallBase.cs#L349)

**Comment by anon17** [comment] 2020-04-13 17:13
If RpcException delivered the source deserialization exception to the caller as [inner exception](https://docs.microsoft.com/en-us/dotnet/api/system.exception.innerexception), it would be self-explanatory to the caller.

**Comment by mikhailshilkov** [comment] 2020-04-16 11:09
I agree it's quite bad that the inner exception is lost. I got bitten by this `Failed to deserialize response message` while my actual exception was a much more descriptive `Google.Protobuf.InvalidProtocolBufferException: Protocol message had too many levels of nesting.  May be malicious.  Use CodedInputStream.SetRecursionLimit() to increase the depth limit.`. See https://github.com/grpc/grpc/issues/22682 for details.

**Comment by jtattermusch** [comment] 2020-05-18 15:50
Potentially we could expose the details of the deserialization error in the newly introduced "DebugErrorString" field: https://github.com/grpc/grpc/pull/22891

**Comment by kucint** [comment] 2021-09-03 12:11
I get the same error when running gRPC app from within VS2022 preview. If I switch to VS2019, the issue disappears.

**Comment by AqlaSolutions** [comment] 2021-09-03 15:07
@kucint I created a separate issue about VS2022 https://github.com/grpc/grpc/issues/27244

**Comment by Stevecaboose** [comment] 2021-09-03 17:12
@kucint I am also having this issue in vs2022 but not in 2019

**Comment by kova98** [comment] 2021-09-13 20:39
@AqlaSolutions the workaround posted there seems to do the trick. Thanks.

**Comment by xutongqing** [comment] 2021-09-15 22:50
when I use vs2022 .net 6.0-rc , I get the same error

**Comment by JamesNK** [comment] 2021-09-17 03:32
This issue is caused by VS2022 preview 3. It is fixed in VS2022 preview 4.

See https://developercommunity.visualstudio.com/t/Unable-to-Debug-grpc-server-code-with-pr/1503691 for more info.

**Closed** 2021-09-17 10:46 UTC
Labels: kind/bug, lang/C#, priority/P2
