### ISSUE TITLE
grpc 1.8.0 not compatible with ruby 2.5

### ISSUE THREAD

**Issue by anthraxx** [grpc/grpc#13903] opened 2018-01-03 09:34 UTC
### What version of gRPC and what language are you using?
 
1.8.0-x86-linux for ruby
 
### What operating system (Linux, Windows, …) and version?
 
Linux running Arch Linux on kernel 4.14.11
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
 
ruby 2.5
gcc 7.2.1
 
### What did you do?

Trying to install the gem for ruby 2.5
 
### What did you expect to see?
 
That grpc works with ruby 2.5
 
### What did you see instead?
 
```
Gem::RuntimeRequirementNotMetError: grpc requires Ruby version < 2.5, >= 2.0. The current ruby version is 2.5.0.
An error occurred while installing grpc (1.8.0), and Bundler cannot continue.
Make sure that `gem install grpc -v '1.8.0'` succeeds before bundling.
```
 
### Anything else we should know about your project / environment?

nothing special, just ruby 2.5

**Comment by anatol** [comment] 2018-01-03 22:18
I believe it is the same bug as https://github.com/grpc/grpc/issues/13908

The root cause is that some apps (like `metasploit`) install Installing `grpc 1.7.3 (x86_64-linux)`. But there is no prebuilt package for this ruby version at rubygems. Hence the failure.

**Comment by apolcyn** [comment] 2018-01-09 02:14
Closing since this is a dupe of https://github.com/grpc/grpc/issues/13908, please follow https://github.com/grpc/grpc/issues/13908 for progress (PR's are referencing that)

**Closed by apolcyn** 2018-01-09 02:14 UTC
Labels: lang/ruby
