### ISSUE TITLE
Flaky Ruby test: 

### ISSUE THREAD

**Issue by jcanizales** [grpc/grpc#2311] opened 2015-07-06 21:52 UTC
Seen at unrelated PR https://github.com/grpc/grpc/pull/2302.

https://grpc-testing.appspot.com/job/gRPC_pull_requests/587/config=dbg,language=ruby,platform=linux/console

```
D0706 18:18:15.299616865    6139 server.c:429] Waiting for all channels to close before destroying server
I0706 18:18:15.299874090    6139 completion_queue.c:229] RETURN_EVENT[0x4267890]: QUEUE_SHUTDOWN
...
I0706 18:18:15.304546673    6139 completion_queue.c:229] RETURN_EVENT[0x392a230]: QUEUE_SHUTDOWN
E0706 18:18:15.305227653    6139 metadata.c:371] assertion failed: ctx->mdtab_free == 0
/usr/local/rvm/rubies/ruby-2.1.5/bin/ruby -I/usr/local/rvm/gems/ruby-2.1.5/gems/rspec-core-3.3.1/lib:/usr/local/rvm/gems/ruby-2.1.5/gems/rspec-support-3.3.0/lib /usr/local/rvm/gems/ruby-2.1.5/gems/rspec-core-3.3.1/exe/rspec spec/generic/active_call_spec.rb spec/generic/client_stub_spec.rb spec/generic/rpc_desc_spec.rb spec/generic/rpc_server_pool_spec.rb spec/generic/rpc_server_spec.rb spec/generic/service_spec.rb spec/spec_helper.rb --tag server failed
rake aborted!
TypeError: no implicit conversion from nil to integer
/usr/local/rvm/gems/ruby-2.1.5/gems/rspec-core-3.3.1/lib/rspec/core/rake_task.rb:75:in `exit'
/usr/local/rvm/gems/ruby-2.1.5/gems/rspec-core-3.3.1/lib/rspec/core/rake_task.rb:75:in `run_task'
/usr/local/rvm/gems/ruby-2.1.5/gems/rspec-core-3.3.1/lib/rspec/core/rake_task.rb:87:in `block (2 levels) in define'
/usr/local/rvm/gems/ruby-2.1.5/gems/rspec-core-3.3.1/lib/rspec/core/rake_task.rb:85:in `block in define'
/usr/local/rvm/gems/ruby-2.1.5/bin/ruby_executable_hooks:15:in `eval'
/usr/local/rvm/gems/ruby-2.1.5/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => default => all => suite:server
(See full trace by running task with --trace)
FAILED: tools/run_tests/run_ruby.sh [ret=1, pid=5949]
FAILED: Some tests failed
+ DOCKER_FAILED=true
++ cat docker.cid
+ DOCKER_CID=22ee3381afd58bd114dad33fd8719b2bf4b50a03a5bbcfeccba56b0081861ddc
+ docker kill 22ee3381afd58bd114dad33fd8719b2bf4b50a03a5bbcfeccba56b0081861ddc
22ee3381afd58bd114dad33fd8719b2bf4b50a03a5bbcfeccba56b0081861ddc
+ docker cp 22ee3381afd58bd114dad33fd8719b2bf4b50a03a5bbcfeccba56b0081861ddc:/var/local/git/grpc/report.xml /home/jenkins/workspace/gRPC_pull_requests/config/dbg/language/ruby/platform/linux
+ docker rm 22ee3381afd58bd114dad33fd8719b2bf4b50a03a5bbcfeccba56b0081861ddc
22ee3381afd58bd114dad33fd8719b2bf4b50a03a5bbcfeccba56b0081861ddc
[copy-to-slave] Copying 'report.xml', excluding nothing, from 'file:/home/jenkins/workspace/gRPC_pull_requests/config/dbg/language/ruby/platform/linux/' on 'hudson.slaves.DumbSlave[grpc-jenkins-worker3]' to 'file:/home/jenkins/jenkins_home/jobs/gRPC_pull_requests/workspace/config/dbg/language/ruby/platform/linux/' on the master.
Recording test results
Build step 'Publish JUnit test result report' changed build result to UNSTABLE
Finished: UNSTABLE
```

**Comment by jcanizales** [comment] 2015-07-06 23:00
Travis got the exact same failure for that run, so maybe it's not a flake and Ruby is currently broken? https://travis-ci.org/grpc/grpc/jobs/69772550

**Comment by tbetbetbe** [comment] 2015-08-24 19:47
PTAL: @jayantkolhe, @hsaliak cannot reproduce locally after 20 iterations, removing Beta label

Note, I'm also aware that there were other issues related to the failure 'assertion failed: ctx->mdtab_free == 0' that actually got resolved, so I'd prefer to close this completely.

**Closed by tbetbetbe** 2015-08-24 19:47 UTC
Labels: cannot reproduce, ruby, wrapped languages
