### ISSUE TITLE
Python Client 1.0.0 suffers connection unavailable after service restarted

### ISSUE THREAD

**Issue by meomap** [grpc/grpc#8296] opened 2016-10-06 11:03 UTC
If I maintain an open channel connection and try to request after service restarted, the first attempt will always failed with error

```
<_Rendezvous of RPC that terminated with (StatusCode.UNAVAILABLE ...
```

to reproduce this, I modify `greeter-client.py` to request 2 times after service restarted

```
diff --git a/examples/python/helloworld/greeter_client.py b/examples/python/helloworld/greeter_client.py
index 44d42c1..9f6234a 100644
--- a/examples/python/helloworld/greeter_client.py
+++ b/examples/python/helloworld/greeter_client.py
@@ -31,7 +31,7 @@

 from __future__ import print_function

-import grpc
+import grpc, time

 import helloworld_pb2

@@ -41,7 +41,17 @@ def run():
   stub = helloworld_pb2.GreeterStub(channel)
   response = stub.SayHello(helloworld_pb2.HelloRequest(name='you'))
   print("Greeter client received: " + response.message)
-
+  print("Sleeping for 5 sec..., please restart service now")
+  time.sleep(5)
+  print("Service should be up by now, try to request again")
+  try:
+      response = stub.SayHello(helloworld_pb2.HelloRequest(name='you'))
+      print("Success on 1st attemp after service restart: " + response.message)
+  except Exception as ex:
+      print("Failed with error %r", ex)
+      print("Retry now ...")
+      response = stub.SayHello(helloworld_pb2.HelloRequest(name='you'))
+      print("Success on 2nd attempt after service restart: " + response.message)
```

here the output

```
Greeter client received: Hello, you!
Sleeping for 5 sec..., please restart service now
Service should be up by now, try to request again
Failed with error %r <_Rendezvous of RPC that terminated with (StatusCode.UNAVAILABLE, {"created":"@1475751516.250124000","description":"EOF","file":"src/core/lib/iomgr/tcp_posix.c","file_line":235,"grpc_status":14})>
Retry now ...
Success on 2nd attempt after service restart: Hello, you!
```

**Comment by bclermont** [comment] 2016-10-25 06:00
:+1:

**Comment by bclermont** [comment] 2016-11-17 08:09
Just updated everything and the problem seem still there... very annoying

**Comment by arthur-tacca** [comment] 2017-01-16 10:50
Maybe this makes sense in a wider context (upcoming load balancing features, or for clients of stateful servers). But it does not make sense in our narrow context ☺️ At the moment, every time we make a request we have to check the return code and retry (once) if the error is "service unavailable". Perhaps there could be a way to label a channel as being OK to reconnect over (so long as the disconnection happened while there were no outstanding requests, and so long as the first reconnection attempt succeeds) for naive clients like ours?

**Comment by ncteisen** [comment] 2017-01-24 18:39
This problem boils down to the c core, aka I can reproduce it with the other wrapped languages.

**Comment by ncteisen** [comment] 2017-01-24 18:48
However, there is probably no small fix for this at the moment. Without doing periodic health checks, there is no way for the client to know that its connection with the original server is no longer good. It needs that first failure to go through the process of remaking the connection.

Good news is that this will be fix once retry support is integrated in to the c core. That is an ongoing project and will be accomplished within the next three months

**Comment by mm-manu** [comment] 2017-08-10 17:00
@ncteisen is the retry feature already implemented?

**Comment by ncteisen** [comment] 2017-08-10 17:22
Not yet but it being very actively worked on! See #10684 to follow the development

**Comment by mm-manu** [comment] 2017-08-11 09:33
thanks

**Comment by kpayson64** [comment] 2017-12-11 21:44
Proper retry support is still a WIP, but we added a temporary workaround a while back where all channels will poll connectivity state, so this should not longer be an issue.

**Closed** 2017-12-11 22:25 UTC
Labels: area/core, disposition/to close, priority/P1

**Comment by ijl** [comment] 2017-12-11 23:18
@kpayson64 what version is needed to have the workaround? I don't see a mention in releases.

**Comment by kpayson64** [comment] 2017-12-11 23:28
@ijl
#11154 Was intended to address this issue, so anything 1.3.x or later should be able to reconnect.

**Comment by ijl** [comment] 2017-12-11 23:31
@kpayson64 thanks.
