### ISSUE TITLE
Channel not re-resolving hostname after failed connect attempt in gRPC v1.10.x

### ISSUE THREAD

**Issue by rainer-ibm** [grpc/grpc#15000] opened 2018-04-10 09:35 UTC
Please answer these questions before submitting your issue. 
 
### Should this be an issue in the gRPC issue tracker?
I don't know what the gRPC intended behavior is in this scenario. This is either a bug or a feature request.

### What version of gRPC and what language are you using?
I am using gRPC v1.10.x with C++
 
### What operating system (Linux, Windows, …) and version?
4.13.0-32-generic 16.04.1-Ubuntu
 
### What runtime / compiler are you using (e.g. python version or version of gcc)
gcc (Ubuntu 5.4.0-6ubuntu1~16.04.9) 5.4.0 20160609
 
#### Preparation
1. setup my system to have two additional IP addresses on the loopback interface: `10.0.1.17/24` and `10.0.1.18/24`
1. modify greeter_server example to be able to listen on different IP addresses, selectable via cli arguments
1. modify greeter_client example to connect to `grpctest:5001` and to send RPCs in a loop with 1 second delay.
1. add an entry to /etc/hosts: `10.0.1.17 grpctest`
#### Test
1. start the server listening on `10.0.1.17:5001`
1. start the greeter_client
=> successfully establishes the channel and RPCs arrive at the server
1. stop the server
=> client's channel goes into transient failure state and frequently tries to reconnect.
1. start the server listening on `10.0.1.18:5001`
=> client's connection attempts still fail
1. change the entry in /etc/hosts to `10.0.1.18 grpctest`
=> client still stuck in transient failure state and all connection attempts fail.

### What did you expect to see?
Expected the client to be able to recover the channel after the hostname was updated to the correct IP.

### What did you see instead?
Client's channel was stuck in TransientFailure <-> Connecting loop
 
### Anything else we should know about your project / environment?
This works flawlessly when the /etc/hosts entry is already changed at the time the server fails.
So it seems as if gRPC is only re-resolving the name when the channel has a transition from running to transient failure.

The goal is to develop a system, where one server monitors the other and provides the service if the monitored server fails. This leads to a "dead-time" after the first server fails until the backup becomes available and the name in the name-resolve system is updated.

I read  #14097 which describes a similar issue which should already be fixed in v1.10.x. However from this issue the following is not clear to me:
1. If the described problem was specific to DNS TTLs (which should be 0 in the case of /etc/hosts)
2. When re-resolving should be done:
   - Only once after a change from RUNNING to TRANSIENT_FAILURE
   - Or for each connection attempt when TTL expired.

**Comment by markdroth** [comment] 2018-04-12 15:32
Can you provide the log output when running your test with the environment variable `GRPC_TRACE=client_channel,pick_first` set?  Thanks!

**Comment by rainer-ibm** [comment] 2018-04-12 15:57
The trace mask you specified did not generate any additional output on stdout.
I tried with `GRPC_TRACE=all` instead. Here is the resulting output:
[traces.txt](https://github.com/grpc/grpc/files/1903956/traces.txt)
Please note that the client produces stdout output in the following form when run without traces enabled:
```
-----------------
Greeter received: Hello world 6
-----------------
Greeter received: Hello world 7
-----------------
14: Socket closed
RPC failed
-----------------
14: Connect Failed
RPC failed
```
If it is helpful I can send you the modified client and server example code. I will have to clean it up a little however.

**Comment by rainer-ibm** [comment] 2018-04-12 16:19
Here is my test example
[modified_greeter_example.zip](https://github.com/grpc/grpc/files/1904067/modified_greeter_example.zip) Warning: all files directly added to the archive => extract into a new folder

Run like this (assuming your system is set up with two IPs 10.0.1.[17|18] and /etc/hosts has an entry directing grpctest to 10.0.1.17):
1. ./greeter_server 10.0.1.17:5001
1. ./greeter_client grpctest:5001
1. kill the server and wait 2-3 seconds
1. ./greeter_server 10.0.1.18:5001
1. change /etc/hosts

**Comment by markdroth** [comment] 2018-06-06 17:55
Sorry for the delay on this.

The trace output doesn't contain the info I was looking for.  You may need to set `GRPC_VERBOSITY=DEBUG` in addition to `GRPC_TRACE=client_channel,pick_first`.

After you update /etc/hosts, there may be one more RPC failure, because the channel is already in CONNECTING state at that point and will not re-resolve the name until it transitions back into TRANSIENT_FAILURE state.  But after that, it should re-resolve, and subsequent RPCs should succeed.  Is that what you're seeing?  If so, this is probably working as intended.  If not, then there's probably some bug here, and the trace output I'm looking for should help me figure out what it is.

If you are seeing the behavior that I describe but want the channel to more proactively re-resolve, then this is probably the same issue as #12295.  The recommended way to deal with this right now is to use the server max connection age setting to periodically drop connections, which will force clients to re-resolve.

Ultimately, if you really want a system that very proactively responds to backend changes, then DNS is probably not a good fit for your use-case.  Instead, you should probably use some notification-based name resolution mechanism; for related discussion, see #13639.

**Comment by rainer-ibm** [comment] 2018-06-20 16:29
Hi, thanks for your reply.

I am seeing ALL subsequent RPC failing. no re-resolving happened. (I think I tested it with one RPC per second and waited for about 2 minutes after killing the first server and starting the backup)
I will repeat the experiment during the next days with GRPC_VERBOSITY=DEBUG and post the results.

Unfortunately I have little control over the way, backend changes are communicated in this use-case. We are currently working on using multiple channels (one for each redundant server) and actively resolving the hostname to decide which channel to use, to circumvent this problem.
I agree, that notification-based name resolution whould be the perfect solution. However gRPC's re-resolving for every connection attempt in TRANSIENT-FAILURE state should be sufficient and most straight forward.

**Comment by hacst** [comment] 2018-06-22 13:21
I think I am seing the same problem with grpc 1.12.1 in C++ . Azure lets the DNS name of dynamic ip resources that are not yet activated resolve to 255.255.255.255 with a TTL of 10. I just debugged a case where gRPC seems to have resolved during the period of creating the resource and activating it. This got the channel stuck trying to reconnect to 255.255.255.255.  It seemingly never attempts re-resolving even after several hours with lots of reconnection attempts. This was also on Ubuntu 16.04.

Here the grpc debug output of one of the many attempted re-connection phases with GRPC_TRACE=connectivity_state and GRPC_VERBOSITY=DEBUG: [reconnectionattempts.txt](https://github.com/grpc/grpc/files/2127718/reconnectionattempts.txt)

strace'ing the process shows it trying to connect to 255.255.255.255 in each attempt with this syscall sequence:
```
[pid  4155] socket(PF_INET6, SOCK_STREAM, IPPROTO_IP) = 22
[pid  4155] setsockopt(22, SOL_IPV6, IPV6_V6ONLY, [0], 4) = 0
[pid  4155] setsockopt(22, SOL_TCP, TCP_NODELAY, [1], 4) = 0
[pid  4155] getsockopt(22, SOL_TCP, TCP_NODELAY, [1], [4]) = 0
[pid  4155] connect(22, {sa_family=AF_INET6, sin6_port=htons(48000), inet_pton(AF_INET6, "::ffff:255.255.255.255", &sin6_addr), sin6_flowinfo=0, sin6_scope_id=0}, 28) = -1 ENETUNREACH (Network is unreachable)
```

Besides that short intermittent period where 255.255.255.255 was returned the DNS name was either not resolvable at all (until it was created) or pointed to a valid IP that could be resolved and connected to with other tools without issues. I telnet'ted into the grpc server port from the same machine with no issues while the grpc client was failing with unreachable.

Looks like a problem with TTL handling or re-resolution in general to me.

**Comment by hacst** [comment] 2018-07-13 14:10
Any update on this @markdroth ? Do you still need more information?

**Comment by rainer-ibm** [comment] 2018-07-13 14:58
Hi,
Sorry for the delay on my side...
Finally I remembered to repeat the test with markdroths environment variables set.
Here is the output: [debuglog.txt](https://github.com/grpc/grpc/files/2193108/debuglog.txt)
As previously guessed, this shows, that re-resolution is only tried once.

If you need any additional infos just let me know.
The problem is really easy to reproduce, just follow the steps in my previous post.

**Comment by sreecha** [comment] 2018-07-18 18:13
@dgquintas, is this similar to the issue you were looking at last week? (or is it the same issue? :) )

**Comment by dgquintas** [comment] 2018-07-18 20:12
Yes, this looks very similar to github.com/grpc/grpc/pull/15947 , which fixed things for Round Robin. I suspect the same change is needed in pick_first [here](https://github.com/grpc/grpc/blob/2d5e0f1e72cda4e7466f28fdeaf20eceabef00f3/src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc#L269). I'm verifying this and putting together a PR.

I suspect github.com/grpc/grpc/issues/15933 is also being affected by this.

**Comment by dgquintas** [comment] 2018-07-19 21:29
After talking to @markdroth and @ejona86 it seems we need to change the current behavior of pick first to re-resolve upon _all_ transitions into `TRANSIENT_FAILURE`, not just the ones from `READY`, as it is now the case. I've created https://github.com/grpc/grpc/issues/16070 to track this work.

**Comment by AspirinSJL** [comment] 2018-07-19 23:46
If my understanding is correct, we should re-resolve whenever the policy is going to `TRANSIENT_FAILURE`, not whenever a subchannel changes to `TRANSIENT_FAILURE`. Right? Otherwise there might be too many re-resolutions if the subchannel list is failing. If only 1 subchannel in the subchannel list fails, we still have other candidates so we don't have to re-resolve at that point.

**Comment by ejona86** [comment] 2018-07-20 00:38
> we should re-resolve whenever the policy is going to TRANSIENT_FAILURE, not whenever a subchannel changes to TRANSIENT_FAILURE

I think we need to do it more based on the subchannel.

> If only 1 subchannel in the subchannel list fails, we still have other candidates so we don't have to re-resolve at that point.

The problem is that round-robin then almost never refreshes. You have to wait until the very last backend is down before a re-resolve. This was previously a problem for C.

**Comment by dgquintas** [comment] 2018-07-20 01:38
At least for DNS, re-resolving a lot is not an issue due to caching.

**Comment by markdroth** [comment] 2018-07-20 14:30
I think we're already doing the right thing for round_robin.  The issue here is just pick_first.

I think pick_first should re-resolve whenever we finish attempting all addresses in the list and transition into TRANSIENT_FAILURE.  I don't think we should re-resolve when one individual address in the list fails if there are still more addresses in the list that we can attempt.

**Comment by AspirinSJL** [comment] 2018-07-25 16:39
Fix (https://github.com/grpc/grpc/pull/16076) is merged. Closing. @rainer-ibm Please re-open if this bug still exists. Thanks!

**Closed by AspirinSJL** 2018-07-25 16:39 UTC
Labels: area/client channel, kind/bug, lang/c++, priority/P1
