### ISSUE TITLE
Mac Big Sur - gem install grpc throws "implicit declaration of function 'write' is invalid in C99"

### ISSUE THREAD

**Issue by rgaufman** [grpc/grpc#25061] opened 2020-12-27 12:47 UTC
### What version of gRPC and what language are you using?
gRPC 1.34.0

### What operating system (Linux, Windows,...) and version?

```
Romans-MacBook-Pro-2.local ➜  bin  uname -a
Darwin Romans-MacBook-Pro-2.local 20.2.0 Darwin Kernel Version 20.2.0: Wed Dec  2 20:40:21 PST 2020; root:xnu-7195.60.75~1/RELEASE_ARM64_T8101 arm64
```

```
Romans-MacBook-Pro-2.local ➜  bin  ruby --version
ruby 3.0.0p0 (2020-12-25 revision 95aff21468) [arm64-darwin20]
```

### What runtime / compiler are you using (e.g. python version or version of gcc)
```
Romans-MacBook-Pro-2.local ➜  bin  python --version
Python 2.7.16
Romans-MacBook-Pro-2.local ➜  bin  gcc --version
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/4.2.1
Apple clang version 12.0.0 (clang-1200.0.32.28)
Target: arm64-apple-darwin20.2.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

### What did you do?

I am just trying to install the ruby gem

```
Romans-MacBook-Pro-2.local ➜  bin  gem install grpc
Building native extensions. This could take a while...
ERROR:  Error installing grpc:
	ERROR: Failed to build gem native extension.

    current directory: /opt/homebrew/lib/ruby/gems/3.0.0/gems/grpc-1.34.0/src/ruby/ext/grpc
/opt/homebrew/opt/ruby/bin/ruby -I /opt/homebrew/Cellar/ruby/3.0.0/lib/ruby/3.0.0 -r ./siteconf20201227-89501-jf2h5u.rb extconf.rb
Building internal gRPC into /opt/homebrew/lib/ruby/gems/3.0.0/gems/grpc-1.34.0/src/ruby/ext/grpc/libs/opt
[C]       Compiling third_party/zlib/adler32.c
[C]       Compiling third_party/zlib/compress.c
mkdir -p `dirname /opt/homebrew/lib/ruby/gems/3.0.0/gems/grpc-1.34.0/src/ruby/ext/grpc/objs/opt/third_party/zlib/compress.o`
[C]       Compiling third_party/zlib/crc32.c
mkdir -p `dirname /opt/homebrew/lib/ruby/gems/3.0.0/gems/grpc-1.34.0/src/ruby/ext/grpc/objs/opt/third_party/zlib/adler32.o`
mkdir -p `dirname /opt/homebrew/lib/ruby/gems/3.0.0/gems/grpc-1.34.0/src/ruby/ext/grpc/objs/opt/third_party/zlib/crc32.o`
[C]       Compiling third_party/zlib/gzclose.c
mkdir -p `dirname /opt/homebrew/lib/ruby/gems/3.0.0/gems/grpc-1.34.0/src/ruby/ext/grpc/objs/opt/third_party/zlib/gzclose.o`
[C]       Compiling third_party/zlib/deflate.c
[C]       Compiling third_party/zlib/gzlib.c
mkdir -p `dirname /opt/homebrew/lib/ruby/gems/3.0.0/gems/grpc-1.34.0/src/ruby/ext/grpc/objs/opt/third_party/zlib/gzlib.o`
mkdir -p `dirname /opt/homebrew/lib/ruby/gems/3.0.0/gems/grpc-1.34.0/src/ruby/ext/grpc/objs/opt/third_party/zlib/deflate.o`
[C]       Compiling third_party/zlib/gzread.c
mkdir -p `dirname /opt/homebrew/lib/ruby/gems/3.0.0/gems/grpc-1.34.0/src/ruby/ext/grpc/objs/opt/third_party/zlib/gzread.o`
[C]       Compiling third_party/zlib/gzwrite.c
mkdir -p `dirname /opt/homebrew/lib/ruby/gems/3.0.0/gems/grpc-1.34.0/src/ruby/ext/grpc/objs/opt/third_party/zlib/gzwrite.o`
[C]       Compiling third_party/zlib/inffast.c
[C]       Compiling third_party/zlib/inflate.c
[C]       Compiling third_party/zlib/inftrees.c
[C]       Compiling third_party/zlib/infback.c
mkdir -p `dirname /opt/homebrew/lib/ruby/gems/3.0.0/gems/grpc-1.34.0/src/ruby/ext/grpc/objs/opt/third_party/zlib/inftrees.o`
mkdir -p `dirname /opt/homebrew/lib/ruby/gems/3.0.0/gems/grpc-1.34.0/src/ruby/ext/grpc/objs/opt/third_party/zlib/inflate.o`
[C]       Compiling third_party/zlib/uncompr.c
mkdir -p `dirname /opt/homebrew/lib/ruby/gems/3.0.0/gems/grpc-1.34.0/src/ruby/ext/grpc/objs/opt/third_party/zlib/uncompr.o`
[C]       Compiling third_party/zlib/trees.c
mkdir -p `dirname /opt/homebrew/lib/ruby/gems/3.0.0/gems/grpc-1.34.0/src/ruby/ext/grpc/objs/opt/third_party/zlib/inffast.o`
[C]       Compiling third_party/zlib/zutil.c
mkdir -p `dirname /opt/homebrew/lib/ruby/gems/3.0.0/gems/grpc-1.34.0/src/ruby/ext/grpc/objs/opt/third_party/zlib/zutil.o`
mkdir -p `dirname /opt/homebrew/lib/ruby/gems/3.0.0/gems/grpc-1.34.0/src/ruby/ext/grpc/objs/opt/third_party/zlib/trees.o`
mkdir -p `dirname /opt/homebrew/lib/ruby/gems/3.0.0/gems/grpc-1.34.0/src/ruby/ext/grpc/objs/opt/third_party/zlib/infback.o`
clang -fdeclspec -Ithird_party/boringssl-with-bazel/src/include -Ithird_party/address_sorting/include -Ithird_party/cares -Ithird_party/cares/cares -DGPR_BACKWARDS_COMPATIBILITY_MODE -g -Wall -Wextra -DOSATOMIC_USE_INLINED=1 -Ithird_party/abseil-cpp -Ithird_party/re2 -Ithird_party/upb -Isrc/core/ext/upb-generated -Isrc/core/ext/upbdefs-generated -O2 -Wframe-larger-than=16384 -fPIC -I. -Iinclude -I/opt/homebrew/lib/ruby/gems/3.0.0/gems/grpc-1.34.0/src/ruby/ext/grpc/gens -DNDEBUG -DINSTALL_PREFIX=\"/usr/local\" -arch i386 -arch x86_64  -Ithird_party/zlib   -std=c99  -g   -fvisibility=hidden -MMD -MF /opt/homebrew/lib/ruby/gems/3.0.0/gems/grpc-1.34.0/src/ruby/ext/grpc/objs/opt/third_party/zlib/gzwrite.dep -c -o /opt/homebrew/lib/ruby/gems/3.0.0/gems/grpc-1.34.0/src/ruby/ext/grpc/objs/opt/third_party/zlib/gzwrite.o third_party/zlib/gzwrite.c
clang -fdeclspec -Ithird_party/boringssl-with-bazel/src/include -Ithird_party/address_sorting/include -Ithird_party/cares -Ithird_party/cares/cares -DGPR_BACKWARDS_COMPATIBILITY_MODE -g -Wall -Wextra -DOSATOMIC_USE_INLINED=1 -Ithird_party/abseil-cpp -Ithird_party/re2 -Ithird_party/upb -Isrc/core/ext/upb-generated -Isrc/core/ext/upbdefs-generated -O2 -Wframe-larger-than=16384 -fPIC -I. -Iinclude -I/opt/homebrew/lib/ruby/gems/3.0.0/gems/grpc-1.34.0/src/ruby/ext/grpc/gens -DNDEBUG -DINSTALL_PREFIX=\"/usr/local\" -arch i386 -arch x86_64  -Ithird_party/zlib   -std=c99  -g   -fvisibility=hidden -MMD -MF /opt/homebrew/lib/ruby/gems/3.0.0/gems/grpc-1.34.0/src/ruby/ext/grpc/objs/opt/third_party/zlib/gzread.dep -c -o /opt/homebrew/lib/ruby/gems/3.0.0/gems/grpc-1.34.0/src/ruby/ext/grpc/objs/opt/third_party/zlib/gzread.o third_party/zlib/gzread.c
clang -fdeclspec -Ithird_party/boringssl-with-bazel/src/include -Ithird_party/address_sorting/include -Ithird_party/cares -Ithird_party/cares/cares -DGPR_BACKWARDS_COMPATIBILITY_MODE -g -Wall -Wextra -DOSATOMIC_USE_INLINED=1 -Ithird_party/abseil-cpp -Ithird_party/re2 -Ithird_party/upb -Isrc/core/ext/upb-generated -Isrc/core/ext/upbdefs-generated -O2 -Wframe-larger-than=16384 -fPIC -I. -Iinclude -I/opt/homebrew/lib/ruby/gems/3.0.0/gems/grpc-1.34.0/src/ruby/ext/grpc/gens -DNDEBUG -DINSTALL_PREFIX=\"/usr/local\" -arch i386 -arch x86_64  -Ithird_party/zlib   -std=c99  -g   -fvisibility=hidden -MMD -MF /opt/homebrew/lib/ruby/gems/3.0.0/gems/grpc-1.34.0/src/ruby/ext/grpc/objs/opt/third_party/zlib/trees.dep -c -o /opt/homebrew/lib/ruby/gems/3.0.0/gems/grpc-1.34.0/src/ruby/ext/grpc/objs/opt/third_party/zlib/trees.o third_party/zlib/trees.c
clang -fdeclspec -Ithird_party/boringssl-with-bazel/src/include -Ithird_party/address_sorting/include -Ithird_party/cares -Ithird_party/cares/cares -DGPR_BACKWARDS_COMPATIBILITY_MODE -g -Wall -Wextra -DOSATOMIC_USE_INLINED=1 -Ithird_party/abseil-cpp -Ithird_party/re2 -Ithird_party/upb -Isrc/core/ext/upb-generated -Isrc/core/ext/upbdefs-generated -O2 -Wframe-larger-than=16384 -fPIC -I. -Iinclude -I/opt/homebrew/lib/ruby/gems/3.0.0/gems/grpc-1.34.0/src/ruby/ext/grpc/gens -DNDEBUG -DINSTALL_PREFIX=\"/usr/local\" -arch i386 -arch x86_64  -Ithird_party/zlib   -std=c99  -g   -fvisibility=hidden -MMD -MF /opt/homebrew/lib/ruby/gems/3.0.0/gems/grpc-1.34.0/src/ruby/ext/grpc/objs/opt/third_party/zlib/infback.dep -c -o /opt/homebrew/lib/ruby/gems/3.0.0/gems/grpc-1.34.0/src/ruby/ext/grpc/objs/opt/third_party/zlib/infback.o third_party/zlib/infback.c
clang -fdeclspec -Ithird_party/boringssl-with-bazel/src/include -Ithird_party/address_sorting/include -Ithird_party/cares -Ithird_party/cares/cares -DGPR_BACKWARDS_COMPATIBILITY_MODE -g -Wall -Wextra -DOSATOMIC_USE_INLINED=1 -Ithird_party/abseil-cpp -Ithird_party/re2 -Ithird_party/upb -Isrc/core/ext/upb-generated -Isrc/core/ext/upbdefs-generated -O2 -Wframe-larger-than=16384 -fPIC -I. -Iinclude -I/opt/homebrew/lib/ruby/gems/3.0.0/gems/grpc-1.34.0/src/ruby/ext/grpc/gens -DNDEBUG -DINSTALL_PREFIX=\"/usr/local\" -arch i386 -arch x86_64  -Ithird_party/zlib   -std=c99  -g   -fvisibility=hidden -MMD -MF /opt/homebrew/lib/ruby/gems/3.0.0/gems/grpc-1.34.0/src/ruby/ext/grpc/objs/opt/third_party/zlib/zutil.dep -c -o /opt/homebrew/lib/ruby/gems/3.0.0/gems/grpc-1.34.0/src/ruby/ext/grpc/objs/opt/third_party/zlib/zutil.o third_party/zlib/zutil.c
clang -fdeclspec -Ithird_party/boringssl-with-bazel/src/include -Ithird_party/address_sorting/include -Ithird_party/cares -Ithird_party/cares/cares -DGPR_BACKWARDS_COMPATIBILITY_MODE -g -Wall -Wextra -DOSATOMIC_USE_INLINED=1 -Ithird_party/abseil-cpp -Ithird_party/re2 -Ithird_party/upb -Isrc/core/ext/upb-generated -Isrc/core/ext/upbdefs-generated -O2 -Wframe-larger-than=16384 -fPIC -I. -Iinclude -I/opt/homebrew/lib/ruby/gems/3.0.0/gems/grpc-1.34.0/src/ruby/ext/grpc/gens -DNDEBUG -DINSTALL_PREFIX=\"/usr/local\" -arch i386 -arch x86_64  -Ithird_party/zlib   -std=c99  -g   -fvisibility=hidden -MMD -MF /opt/homebrew/lib/ruby/gems/3.0.0/gems/grpc-1.34.0/src/ruby/ext/grpc/objs/opt/third_party/zlib/inffast.dep -c -o /opt/homebrew/lib/ruby/gems/3.0.0/gems/grpc-1.34.0/src/ruby/ext/grpc/objs/opt/third_party/zlib/inffast.o third_party/zlib/inffast.c
clang -fdeclspec -Ithird_party/boringssl-with-bazel/src/include -Ithird_party/address_sorting/include -Ithird_party/cares -Ithird_party/cares/cares -DGPR_BACKWARDS_COMPATIBILITY_MODE -g -Wall -Wextra -DOSATOMIC_USE_INLINED=1 -Ithird_party/abseil-cpp -Ithird_party/re2 -Ithird_party/upb -Isrc/core/ext/upb-generated -Isrc/core/ext/upbdefs-generated -O2 -Wframe-larger-than=16384 -fPIC -I. -Iinclude -I/opt/homebrew/lib/ruby/gems/3.0.0/gems/grpc-1.34.0/src/ruby/ext/grpc/gens -DNDEBUG -DINSTALL_PREFIX=\"/usr/local\" -arch i386 -arch x86_64  -Ithird_party/zlib   -std=c99  -g   -fvisibility=hidden -MMD -MF /opt/homebrew/lib/ruby/gems/3.0.0/gems/grpc-1.34.0/src/ruby/ext/grpc/objs/opt/third_party/zlib/uncompr.dep -c -o /opt/homebrew/lib/ruby/gems/3.0.0/gems/grpc-1.34.0/src/ruby/ext/grpc/objs/opt/third_party/zlib/uncompr.o third_party/zlib/uncompr.c
clang -fdeclspec -Ithird_party/boringssl-with-bazel/src/include -Ithird_party/address_sorting/include -Ithird_party/cares -Ithird_party/cares/cares -DGPR_BACKWARDS_COMPATIBILITY_MODE -g -Wall -Wextra -DOSATOMIC_USE_INLINED=1 -Ithird_party/abseil-cpp -Ithird_party/re2 -Ithird_party/upb -Isrc/core/ext/upb-generated -Isrc/core/ext/upbdefs-generated -O2 -Wframe-larger-than=16384 -fPIC -I. -Iinclude -I/opt/homebrew/lib/ruby/gems/3.0.0/gems/grpc-1.34.0/src/ruby/ext/grpc/gens -DNDEBUG -DINSTALL_PREFIX=\"/usr/local\" -arch i386 -arch x86_64  -Ithird_party/zlib   -std=c99  -g   -fvisibility=hidden -MMD -MF /opt/homebrew/lib/ruby/gems/3.0.0/gems/grpc-1.34.0/src/ruby/ext/grpc/objs/opt/third_party/zlib/inflate.dep -c -o /opt/homebrew/lib/ruby/gems/3.0.0/gems/grpc-1.34.0/src/ruby/ext/grpc/objs/opt/third_party/zlib/inflate.o third_party/zlib/inflate.c
clang -fdeclspec -Ithird_party/boringssl-with-bazel/src/include -Ithird_party/address_sorting/include -Ithird_party/cares -Ithird_party/cares/cares -DGPR_BACKWARDS_COMPATIBILITY_MODE -g -Wall -Wextra -DOSATOMIC_USE_INLINED=1 -Ithird_party/abseil-cpp -Ithird_party/re2 -Ithird_party/upb -Isrc/core/ext/upb-generated -Isrc/core/ext/upbdefs-generated -O2 -Wframe-larger-than=16384 -fPIC -I. -Iinclude -I/opt/homebrew/lib/ruby/gems/3.0.0/gems/grpc-1.34.0/src/ruby/ext/grpc/gens -DNDEBUG -DINSTALL_PREFIX=\"/usr/local\" -arch i386 -arch x86_64  -Ithird_party/zlib   -std=c99  -g   -fvisibility=hidden -MMD -MF /opt/homebrew/lib/ruby/gems/3.0.0/gems/grpc-1.34.0/src/ruby/ext/grpc/objs/opt/third_party/zlib/inftrees.dep -c -o /opt/homebrew/lib/ruby/gems/3.0.0/gems/grpc-1.34.0/src/ruby/ext/grpc/objs/opt/third_party/zlib/inftrees.o third_party/zlib/inftrees.c
clang -fdeclspec -Ithird_party/boringssl-with-bazel/src/include -Ithird_party/address_sorting/include -Ithird_party/cares -Ithird_party/cares/cares -DGPR_BACKWARDS_COMPATIBILITY_MODE -g -Wall -Wextra -DOSATOMIC_USE_INLINED=1 -Ithird_party/abseil-cpp -Ithird_party/re2 -Ithird_party/upb -Isrc/core/ext/upb-generated -Isrc/core/ext/upbdefs-generated -O2 -Wframe-larger-than=16384 -fPIC -I. -Iinclude -I/opt/homebrew/lib/ruby/gems/3.0.0/gems/grpc-1.34.0/src/ruby/ext/grpc/gens -DNDEBUG -DINSTALL_PREFIX=\"/usr/local\" -arch i386 -arch x86_64  -Ithird_party/zlib   -std=c99  -g   -fvisibility=hidden -MMD -MF /opt/homebrew/lib/ruby/gems/3.0.0/gems/grpc-1.34.0/src/ruby/ext/grpc/objs/opt/third_party/zlib/deflate.dep -c -o /opt/homebrew/lib/ruby/gems/3.0.0/gems/grpc-1.34.0/src/ruby/ext/grpc/objs/opt/third_party/zlib/deflate.o third_party/zlib/deflate.c
clang -fdeclspec -Ithird_party/boringssl-with-bazel/src/include -Ithird_party/address_sorting/include -Ithird_party/cares -Ithird_party/cares/cares -DGPR_BACKWARDS_COMPATIBILITY_MODE -g -Wall -Wextra -DOSATOMIC_USE_INLINED=1 -Ithird_party/abseil-cpp -Ithird_party/re2 -Ithird_party/upb -Isrc/core/ext/upb-generated -Isrc/core/ext/upbdefs-generated -O2 -Wframe-larger-than=16384 -fPIC -I. -Iinclude -I/opt/homebrew/lib/ruby/gems/3.0.0/gems/grpc-1.34.0/src/ruby/ext/grpc/gens -DNDEBUG -DINSTALL_PREFIX=\"/usr/local\" -arch i386 -arch x86_64  -Ithird_party/zlib   -std=c99  -g   -fvisibility=hidden -MMD -MF /opt/homebrew/lib/ruby/gems/3.0.0/gems/grpc-1.34.0/src/ruby/ext/grpc/objs/opt/third_party/zlib/gzlib.dep -c -o /opt/homebrew/lib/ruby/gems/3.0.0/gems/grpc-1.34.0/src/ruby/ext/grpc/objs/opt/third_party/zlib/gzlib.o third_party/zlib/gzlib.c
clang -fdeclspec -Ithird_party/boringssl-with-bazel/src/include -Ithird_party/address_sorting/include -Ithird_party/cares -Ithird_party/cares/cares -DGPR_BACKWARDS_COMPATIBILITY_MODE -g -Wall -Wextra -DOSATOMIC_USE_INLINED=1 -Ithird_party/abseil-cpp -Ithird_party/re2 -Ithird_party/upb -Isrc/core/ext/upb-generated -Isrc/core/ext/upbdefs-generated -O2 -Wframe-larger-than=16384 -fPIC -I. -Iinclude -I/opt/homebrew/lib/ruby/gems/3.0.0/gems/grpc-1.34.0/src/ruby/ext/grpc/gens -DNDEBUG -DINSTALL_PREFIX=\"/usr/local\" -arch i386 -arch x86_64  -Ithird_party/zlib   -std=c99  -g   -fvisibility=hidden -MMD -MF /opt/homebrew/lib/ruby/gems/3.0.0/gems/grpc-1.34.0/src/ruby/ext/grpc/objs/opt/third_party/zlib/gzclose.dep -c -o /opt/homebrew/lib/ruby/gems/3.0.0/gems/grpc-1.34.0/src/ruby/ext/grpc/objs/opt/third_party/zlib/gzclose.o third_party/zlib/gzclose.c
clang -fdeclspec -Ithird_party/boringssl-with-bazel/src/include -Ithird_party/address_sorting/include -Ithird_party/cares -Ithird_party/cares/cares -DGPR_BACKWARDS_COMPATIBILITY_MODE -g -Wall -Wextra -DOSATOMIC_USE_INLINED=1 -Ithird_party/abseil-cpp -Ithird_party/re2 -Ithird_party/upb -Isrc/core/ext/upb-generated -Isrc/core/ext/upbdefs-generated -O2 -Wframe-larger-than=16384 -fPIC -I. -Iinclude -I/opt/homebrew/lib/ruby/gems/3.0.0/gems/grpc-1.34.0/src/ruby/ext/grpc/gens -DNDEBUG -DINSTALL_PREFIX=\"/usr/local\" -arch i386 -arch x86_64  -Ithird_party/zlib   -std=c99  -g   -fvisibility=hidden -MMD -MF /opt/homebrew/lib/ruby/gems/3.0.0/gems/grpc-1.34.0/src/ruby/ext/grpc/objs/opt/third_party/zlib/crc32.dep -c -o /opt/homebrew/lib/ruby/gems/3.0.0/gems/grpc-1.34.0/src/ruby/ext/grpc/objs/opt/third_party/zlib/crc32.o third_party/zlib/crc32.c
clang -fdeclspec -Ithird_party/boringssl-with-bazel/src/include -Ithird_party/address_sorting/include -Ithird_party/cares -Ithird_party/cares/cares -DGPR_BACKWARDS_COMPATIBILITY_MODE -g -Wall -Wextra -DOSATOMIC_USE_INLINED=1 -Ithird_party/abseil-cpp -Ithird_party/re2 -Ithird_party/upb -Isrc/core/ext/upb-generated -Isrc/core/ext/upbdefs-generated -O2 -Wframe-larger-than=16384 -fPIC -I. -Iinclude -I/opt/homebrew/lib/ruby/gems/3.0.0/gems/grpc-1.34.0/src/ruby/ext/grpc/gens -DNDEBUG -DINSTALL_PREFIX=\"/usr/local\" -arch i386 -arch x86_64  -Ithird_party/zlib   -std=c99  -g   -fvisibility=hidden -MMD -MF /opt/homebrew/lib/ruby/gems/3.0.0/gems/grpc-1.34.0/src/ruby/ext/grpc/objs/opt/third_party/zlib/adler32.dep -c -o /opt/homebrew/lib/ruby/gems/3.0.0/gems/grpc-1.34.0/src/ruby/ext/grpc/objs/opt/third_party/zlib/adler32.o third_party/zlib/adler32.c
clang -fdeclspec -Ithird_party/boringssl-with-bazel/src/include -Ithird_party/address_sorting/include -Ithird_party/cares -Ithird_party/cares/cares -DGPR_BACKWARDS_COMPATIBILITY_MODE -g -Wall -Wextra -DOSATOMIC_USE_INLINED=1 -Ithird_party/abseil-cpp -Ithird_party/re2 -Ithird_party/upb -Isrc/core/ext/upb-generated -Isrc/core/ext/upbdefs-generated -O2 -Wframe-larger-than=16384 -fPIC -I. -Iinclude -I/opt/homebrew/lib/ruby/gems/3.0.0/gems/grpc-1.34.0/src/ruby/ext/grpc/gens -DNDEBUG -DINSTALL_PREFIX=\"/usr/local\" -arch i386 -arch x86_64  -Ithird_party/zlib   -std=c99  -g   -fvisibility=hidden -MMD -MF /opt/homebrew/lib/ruby/gems/3.0.0/gems/grpc-1.34.0/src/ruby/ext/grpc/objs/opt/third_party/zlib/compress.dep -c -o /opt/homebrew/lib/ruby/gems/3.0.0/gems/grpc-1.34.0/src/ruby/ext/grpc/objs/opt/third_party/zlib/compress.o third_party/zlib/compress.c
third_party/zlib/gzread.c:35:15: warning: implicit declaration of function 'read' is invalid in C99 [-Wimplicit-function-declaration]
        ret = read(state->fd, buf + *have, get);
              ^
third_party/zlib/gzwrite.c:89:20: warning: implicit declaration of function 'write' is invalid in C99 [-Wimplicit-function-declaration]
            writ = write(state->fd, strm->next_in, put);
                   ^
third_party/zlib/gzwrite.c:110:24: warning: implicit declaration of function 'write' is invalid in C99 [-Wimplicit-function-declaration]
                writ = write(state->fd, state->x.next, put);
                       ^
third_party/zlib/gzread.c:651:11: warning: implicit declaration of function 'close' is invalid in C99 [-Wimplicit-function-declaration]
    ret = close(state->fd);
          ^
third_party/zlib/gzwrite.c:661:9: warning: implicit declaration of function 'close' is invalid in C99 [-Wimplicit-function-declaration]
    if (close(state->fd) == -1)
        ^
third_party/zlib/gzlib.c:252:9: warning: implicit declaration of function 'lseek' is invalid in C99 [-Wimplicit-function-declaration]
        LSEEK(state->fd, 0, SEEK_END);  /* so gzoffset() is correct */
        ^
third_party/zlib/gzlib.c:14:17: note: expanded from macro 'LSEEK'
#  define LSEEK lseek
                ^
third_party/zlib/gzlib.c:258:24: warning: implicit declaration of function 'lseek' is invalid in C99 [-Wimplicit-function-declaration]
        state->start = LSEEK(state->fd, 0, SEEK_CUR);
                       ^
third_party/zlib/gzlib.c:14:17: note: expanded from macro 'LSEEK'
#  define LSEEK lseek
                ^
third_party/zlib/gzlib.c:359:9: warning: implicit declaration of function 'lseek' is invalid in C99 [-Wimplicit-function-declaration]
    if (LSEEK(state->fd, state->start, SEEK_SET) == -1)
        ^
third_party/zlib/gzlib.c:14:17: note: expanded from macro 'LSEEK'
#  define LSEEK lseek
                ^
third_party/zlib/gzlib.c:400:15: warning: implicit declaration of function 'lseek' is invalid in C99 [-Wimplicit-function-declaration]
        ret = LSEEK(state->fd, offset - state->x.have, SEEK_CUR);
              ^
third_party/zlib/gzlib.c:14:17: note: expanded from macro 'LSEEK'
#  define LSEEK lseek
                ^
third_party/zlib/gzlib.c:496:14: warning: implicit declaration of function 'lseek' is invalid in C99 [-Wimplicit-function-declaration]
    offset = LSEEK(state->fd, 0, SEEK_CUR);
             ^
third_party/zlib/gzlib.c:14:17: note: expanded from macro 'LSEEK'
#  define LSEEK lseek
                ^
2 warnings generated.
3 warnings generated.
third_party/zlib/gzread.c:35:15: error: implicit declaration of function 'read' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
        ret = read(state->fd, buf + *have, get);
              ^
third_party/zlib/gzread.c:35:15: note: did you mean 'fread'?
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/stdio.h:158:9: note: 'fread' declared here
size_t   fread(void * __restrict __ptr, size_t __size, size_t __nitems, FILE * __restrict __stream);
         ^
third_party/zlib/gzread.c:651:11: error: implicit declaration of function 'close' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
    ret = close(state->fd);
          ^
2 errors generated.
third_party/zlib/gzwrite.c:89:20: error: implicit declaration of function 'write' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
            writ = write(state->fd, strm->next_in, put);
                   ^
third_party/zlib/gzwrite.c:89:20: note: did you mean 'fwrite'?
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/stdio.h:165:9: note: 'fwrite' declared here
size_t   fwrite(const void * __restrict __ptr, size_t __size, size_t __nitems, FILE * __restrict __stream) __DARWIN_ALIAS(fwrite);
         ^
third_party/zlib/gzwrite.c:110:24: error: implicit declaration of function 'write' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
                writ = write(state->fd, state->x.next, put);
                       ^
third_party/zlib/gzwrite.c:661:9: error: implicit declaration of function 'close' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
    if (close(state->fd) == -1)
        ^
3 errors generated.
5 warnings generated.
third_party/zlib/gzlib.c:252:9: error: implicit declaration of function 'lseek' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
        LSEEK(state->fd, 0, SEEK_END);  /* so gzoffset() is correct */
        ^
third_party/zlib/gzlib.c:14:17: note: expanded from macro 'LSEEK'
#  define LSEEK lseek
                ^
third_party/zlib/gzlib.c:252:9: note: did you mean 'fseek'?
third_party/zlib/gzlib.c:14:17: note: expanded from macro 'LSEEK'
#  define LSEEK lseek
                ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/stdio.h:162:6: note: 'fseek' declared here
int      fseek(FILE *, long, int);
         ^
third_party/zlib/gzlib.c:258:24: error: implicit declaration of function 'lseek' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
        state->start = LSEEK(state->fd, 0, SEEK_CUR);
                       ^
third_party/zlib/gzlib.c:14:17: note: expanded from macro 'LSEEK'
#  define LSEEK lseek
                ^
third_party/zlib/gzlib.c:359:9: error: implicit declaration of function 'lseek' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
    if (LSEEK(state->fd, state->start, SEEK_SET) == -1)
        ^
third_party/zlib/gzlib.c:14:17: note: expanded from macro 'LSEEK'
#  define LSEEK lseek
                ^
third_party/zlib/gzlib.c:400:15: error: implicit declaration of function 'lseek' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
        ret = LSEEK(state->fd, offset - state->x.have, SEEK_CUR);
              ^
third_party/zlib/gzlib.c:14:17: note: expanded from macro 'LSEEK'
#  define LSEEK lseek
                ^
make: *** [/opt/homebrew/lib/ruby/gems/3.0.0/gems/grpc-1.34.0/src/ruby/ext/grpc/objs/opt/third_party/zlib/gzread.o] Error 1
make: *** Waiting for unfinished jobs....
make: *** [/opt/homebrew/lib/ruby/gems/3.0.0/gems/grpc-1.34.0/src/ruby/ext/grpc/objs/opt/third_party/zlib/gzwrite.o] Error 1
third_party/zlib/gzlib.c:496:14: error: implicit declaration of function 'lseek' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
    offset = LSEEK(state->fd, 0, SEEK_CUR);
             ^
third_party/zlib/gzlib.c:14:17: note: expanded from macro 'LSEEK'
#  define LSEEK lseek
                ^
5 errors generated.
[C]       Compiling third_party/cares/cares/ares__close_sockets.c
mkdir -p `dirname /opt/homebrew/lib/ruby/gems/3.0.0/gems/grpc-1.34.0/src/ruby/ext/grpc/objs/opt/third_party/cares/cares/ares__close_sockets.o`
make: *** [/opt/homebrew/lib/ruby/gems/3.0.0/gems/grpc-1.34.0/src/ruby/ext/grpc/objs/opt/third_party/zlib/gzlib.o] Error 1
clang -fdeclspec -Ithird_party/boringssl-with-bazel/src/include -Ithird_party/address_sorting/include -Ithird_party/cares -Ithird_party/cares/cares -DGPR_BACKWARDS_COMPATIBILITY_MODE -g -Wall -Wextra -DOSATOMIC_USE_INLINED=1 -Ithird_party/abseil-cpp -Ithird_party/re2 -Ithird_party/upb -Isrc/core/ext/upb-generated -Isrc/core/ext/upbdefs-generated -O2 -Wframe-larger-than=16384 -fPIC -I. -Iinclude -I/opt/homebrew/lib/ruby/gems/3.0.0/gems/grpc-1.34.0/src/ruby/ext/grpc/gens -DNDEBUG -DINSTALL_PREFIX=\"/usr/local\" -arch i386 -arch x86_64  -Ithird_party/zlib   -Ithird_party/cares -Ithird_party/cares/cares -fvisibility=hidden -D_GNU_SOURCE -Ithird_party/cares/config_darwin    -DWIN32_LEAN_AND_MEAN -D_HAS_EXCEPTIONS=0 -DNOMINMAX -DHAVE_CONFIG_H -std=c99  -g   -g -MMD -MF /opt/homebrew/lib/ruby/gems/3.0.0/gems/grpc-1.34.0/src/ruby/ext/grpc/objs/opt/third_party/cares/cares/ares__close_sockets.dep -c -o /opt/homebrew/lib/ruby/gems/3.0.0/gems/grpc-1.34.0/src/ruby/ext/grpc/objs/opt/third_party/cares/cares/ares__close_sockets.o third_party/cares/cares/ares__close_sockets.c
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/opt/homebrew/Cellar/ruby/3.0.0/bin/$(RUBY_BASE_NAME)

extconf failed, exit code 1

Gem files will remain installed in /opt/homebrew/lib/ruby/gems/3.0.0/gems/grpc-1.34.0 for inspection.
Results logged to /opt/homebrew/lib/ruby/gems/3.0.0/extensions/arm64-darwin-20/3.0.0/grpc-1.34.0/gem_make.out
```

### What did you expect to see?
I expected the gem to install

### What did you see instead?
The gem did not install, full error above

**Comment by veblush** [comment] 2021-01-05 23:24
Duplicate of #25060

**Closed by veblush** 2021-01-05 23:24 UTC
Labels: kind/bug, lang/ruby, priority/P2
