### ISSUE TITLE
Surface more information in Ruby call credential errors

### ISSUE THREAD

**Issue by murgatroid99** [grpc/grpc#8072] opened 2016-09-13 02:23 UTC
Currently, if there is an error in a call credential callback, the only information surfaced from that error is the name of the exception class, which can make problems harder to debug, such as the one reported in GoogleCloudPlatform/google-cloud-ruby#896. We should try to surface other information too, including the message.

**Comment by timanovsky** [comment] 2016-09-13 07:08
Not only that. Transient network errors should be reported as `Unavailable` regardless which API it accesses (auth or the service), and should not be reported as authentication failures which are not retriable as per documentation.

**Comment by apolcyn** [comment] 2016-09-14 02:28
As for showing more info in what's returned to the client, thinking we could fill in the "details" of the status just with the "message" contents of the ruby exception that's thrown in the callback. I'm guessing we wouldn't want the full backtrace too, though it looks like that's also an option.

For the status code that gets returned when an exception is thrown by the callback, it looks to me like the issue is knowing whether it was thrown for permissions reasons by the callback. 

In case it is a real permissions error though, I think we still would want to return a status indicating that? It would change the API, but maybe we could change the default exception to unavailable, but do something like check the exception type thrown in the callback, and use the status code from that if it's a `BadStatus` exception, for example.

**Comment by vjpai** [comment] 2016-11-16 00:17
Fixed by #8102  - marking to close

**Closed** 2016-11-16 01:41 UTC
Labels: ruby, to close
