### ISSUE TITLE
CMake does not install pkg-config files

### ISSUE THREAD

**Issue by coryan** [grpc/grpc#15165] opened 2018-04-24 02:52 UTC
### Should this be an issue in the gRPC issue tracker?
 
Yes. 
 
### What version of gRPC and what language are you using?

v1.11.0 but as far as I can tell this is a problem with many versions of gRPC.
 
### What operating system (Linux, Windows, …) and version?

Linux, though presumably this is also a problem on macOS and Windows (where yes, sometimes pkg-config files are useful).
 
### What runtime / compiler are you using (e.g. python version or version of gcc)

See below, I have attached a full Dockerfile to reproduce the problem.
 
### What did you do?

Use this Dockerfile with `sudo docker build -f Dockerfile .` in an empty directory.

```Dockerfile

FROM ubuntu:16.04
MAINTAINER "Carlos O'Ryan <coryan@google.com>"

ARG NCPU=8

RUN apt-get update && apt-get install -y \
  build-essential \
  cmake \
  gcc \
  g++ \
  golang \
  git \
  cmake \
  libssl-dev \
  libtool \
  lsb-release \
  make \
  tar \
  wget \
  zlib1g-dev

WORKDIR /var/tmp/build-dependencies
RUN wget -q https://github.com/google/protobuf/archive/v3.5.2.tar.gz
RUN tar -xf v3.5.2.tar.gz
WORKDIR /var/tmp/build-dependencies/protobuf-3.5.2/cmake
RUN cmake \
  -DCMAKE_BUILD_TYPE=Release \
  -Dprotobuf_BUILD_TESTS=OFF \
  -H. -B.build
RUN cmake --build .build --target install -- -j ${NCPU}

WORKDIR /var/tmp/build-dependencies
RUN apt-get remove -y libc-ares-dev libc-ares2
RUN wget -q https://github.com/c-ares/c-ares/archive/cares-1_14_0.tar.gz
RUN tar -xf cares-1_14_0.tar.gz
WORKDIR /var/tmp/build-dependencies/c-ares-cares-1_14_0
RUN cmake \
  -DCMAKE_BUILD_TYPE=Release \
  -H. -B.build
RUN cmake --build .build --target install -- -j ${NCPU}

WORKDIR /var/tmp/build-dependencies
RUN wget -q https://github.com/grpc/grpc/archive/v1.11.0.tar.gz
RUN tar -xf v1.11.0.tar.gz
WORKDIR /var/tmp/build-dependencies/grpc-1.11.0
RUN cmake \
  -DCMAKE_BUILD_TYPE=Release \
  -DgRPC_BUILD_TESTS=OFF \
  -DgRPC_ZLIB_PROVIDER=package \
  -DgRPC_SSL_PROVIDER=package \
  -DgRPC_CARES_PROVIDER=package \
  -DgRPC_PROTOBUF_PROVIDER=package \
  -H. -B.build/grpc
RUN cmake --build .build/grpc --target install -- -j ${NCPU}

RUN if [ ! -f /usr/local/lib/pkg-config/grpc++.pc ]; then echo "Did not install grpc++.pc"; exit 1; fi
```
 
### What did you expect to see?

I expect the CMake files to install the pkg-config configuration files.  Regardless of how the library is compiled it should install the configuration files for however the application developer wants to use them. 
 
### What did you see instead?
 
The files are not installed, of course.

**Comment by jtattermusch** [comment] 2018-04-27 15:43
Dupe of https://github.com/grpc/grpc/issues/10727

**Closed by jtattermusch** 2018-04-27 15:43 UTC
Labels: area/build
