### ISSUE TITLE
Can't install using pip on ubuntu 19.04

### ISSUE THREAD

**Issue by dmars1972** [grpc/grpc#22645] opened 2020-04-11 21:52 UTC
### What version of gRPC and what language are you using?
1.28.x, pip3 (although I have the same issue with 2.7)

### What operating system (Linux, Windows,...) and version?
Ubuntu 19.04

### What runtime / compiler are you using (e.g. python version or version of gcc)
gcc 8.3

### What did you do?
git clone -b v1.28.x https://github.com/grpc/grpc
cd grpc
git submodule update --init
GRPC_PYTHON_BUILD_WITH_CYTHON=1 sudo pip3 install . 

### What did you expect to see?
Success?

### What did you see instead?
attached (I hope)
[err.txt](https://github.com/grpc/grpc/files/4465481/err.txt)

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

See [TROUBLESHOOTING.md](https://github.com/grpc/grpc/blob/master/TROUBLESHOOTING.md) for how to diagnose problems better.

**Comment by gnossen** [comment] 2020-04-13 19:32
Relevant linker error:

``` 
    /usr/bin/ld: /tmp/ccVHIvCb.ltrans1.ltrans.o: in function `upb_arena_doalloc.lto_priv.659':
    /usr/include/x86_64-linux-gnu/bits/string_fortified.h:34: undefined reference to `__wrap_memcpy'
    /usr/bin/ld: /tmp/ccVHIvCb.ltrans1.ltrans.o: in function `upb_msg_addunknown':
    /usr/include/x86_64-linux-gnu/bits/string_fortified.h:34: undefined reference to `__wrap_memcpy'
    /usr/bin/ld: /tmp/ccVHIvCb.ltrans1.ltrans.o: in function `upb_array_add':
    /usr/include/x86_64-linux-gnu/bits/string_fortified.h:34: undefined reference to `__wrap_memcpy'
    /usr/bin/ld: /tmp/ccVHIvCb.ltrans1.ltrans.o: in function `flush_pending':
    /usr/include/x86_64-linux-gnu/bits/string_fortified.h:34: undefined reference to `__wrap_memcpy'
    /usr/bin/ld: /tmp/ccVHIvCb.ltrans1.ltrans.o: in function `upb_put_bytes':
    /usr/include/x86_64-linux-gnu/bits/string_fortified.h:34: undefined reference to `__wrap_memcpy'
    /usr/bin/ld: /tmp/ccVHIvCb.ltrans1.ltrans.o:/usr/include/x86_64-linux-gnu/bits/string_fortified.h:34: more undefined references to `__wrap_memcpy' follow
    collect2: error: ld returned 1 exit status
    Traceback (most recent call last):
      File "/usr/lib/python3.7/distutils/unixccompiler.py", line 215, in link
        self.spawn(linker + ld_args)
      File "/tmp/pip-req-build-yeiiecs8/src/python/grpcio/_spawn_patch.py", line 54, in _commandfile_spawn
        _classic_spawn(self, command)
      File "/usr/lib/python3.7/distutils/ccompiler.py", line 910, in spawn
        spawn(cmd, dry_run=self.dry_run)
      File "/usr/lib/python3.7/distutils/spawn.py", line 36, in spawn
        _spawn_posix(cmd, search_path, dry_run=dry_run)
      File "/usr/lib/python3.7/distutils/spawn.py", line 159, in _spawn_posix
        % (cmd, exit_status))
    distutils.errors.DistutilsExecError: command 'x86_64-linux-gnu-g++' failed with exit status 1
```

CC @nicolasnoble @veblush

**Comment by nicolasnoble** [comment] 2020-04-16 21:38
The `_wrap_memcpy symbol` comes from the compilation trick that's fairly wildly used in lots of places that helps producing binaries that work around the nasty glibc "memcpy" symbol deprecation. [Protobuf uses it](https://github.com/protocolbuffers/protobuf/blob/master/ruby/ext/google/protobuf_c/wrap_memcpy.c), [grpc uses it](https://github.com/grpc/grpc/blob/master/src/core/lib/gpr/wrap_memcpy.cc).

I don't necessarily have enough information to understand what's going on here, but this behavior is enabled by the compilation option `-Wl,-wrap,memcpy`, and then the corresponding C file wasn't linked afterward.

**Comment by gnossen** [comment] 2020-04-16 22:28
@dmars1972 I tried to reproduce on 19.04, but that version went EOL January 23rd. I was unable to reproduce on 19.10.

@neilengineer Can you provide any details about the environment you're running in? Distro? Python version? Compiler version?

**Comment by neilengineer** [comment] 2020-04-16 23:01
Ubuntu 19.10
gcc (Ubuntu 9.2.1-9ubuntu2) 9.2.1 20191008
Python 3.7.5

I ran following cmd, but failed at building grpcio

`pip install tensorflow`

**Comment by neilengineer** [comment] 2020-04-16 23:05
[Update]
I did a distro upgrade to Ubuntu 19.10, now it passed building.


I ran following cmd, but failed at building grpcio

`pip install tensorflow`

**Comment by gnossen** [comment] 2020-04-16 23:06
@dmars1972 Can you try upgrading to 19.10 and seeing if that resolves the issue?

**Comment by jasonheffner** [comment] 2020-04-17 12:31
I experienced the same issue but using the official 19.04 Docker image. I was pinning tensorflow 'pip install xgboost==0.90.0' as we haven't updated our models yet. I tried reverting to 18.04 and got a segmentation fault, which is probably an issue for the LTS. I then tried 19.10 and got a successful install.

**Comment by gnossen** [comment] 2020-04-17 17:17
Since this issue only seems to be happening on an EOL Ubuntu release for which we are unable to reproduce, I'm going ahead and closing. If anyone is able to reproduce on other, in-support releases, feel free to revive the thread.

**Closed by gnossen** 2020-04-17 17:17 UTC
Labels: kind/bug, lang/Python, priority/P2

**Comment by moooeeeep** [comment] 2021-02-10 09:45
I can reproduce the error on Ubuntu 18.04 LTS.

I was trying to install tensorflow in a virtual environment via pip, which fails after encountering above described error.
