### ISSUE TITLE
Failed to initialize type Grpc.Core.Internal.PlatformApis

### ISSUE THREAD

**Issue by tiagonapoli** [grpc/grpc#24667] opened 2020-11-04 21:57 UTC
### What version of gRPC and what language are you using?
C# - .NET Core 3.1

Grpc@2.23.0
Grpc.Core@2.23.0
Grpc.Core.Api@2.23.0

### What operating system (Linux, Windows,...) and version?

Ubuntu - Linux kernel 5.4.0-52-generic

### What runtime / compiler are you using (e.g. .NET Core SDK version `dotnet --info`)
```
.NET Core SDK (reflecting any global.json):
 Version:   3.1.402
 Commit:    9b5de826fd
```

```
Runtime Environment:
 OS Name:     ubuntu
 OS Version:  20.04
 OS Platform: Linux
 RID:         ubuntu.20.04-x64
 Base Path:   /usr/share/dotnet/sdk/3.1.402/
```

```
.NET Core runtimes installed:
  Microsoft.AspNetCore.App 3.1.8 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.8 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
```

### What did you do?
Instantiate a new `Channel` on app initialization.

### What did you expect to see?
Successful initialization

### What did you see instead?

Exception thrown:
```
The type initializer for 'Grpc.Core.Internal.PlatformApis' threw an exception.
   at Grpc.Core.Internal.PlatformApis.get_IsXamarinIOS()
   at Grpc.Core.GrpcEnvironment.get_IsNativeShutdownAllowed()
   at Grpc.Core.GrpcEnvironment.GrpcNativeInit()
   at Grpc.Core.GrpcEnvironment..ctor()
   at Grpc.Core.GrpcEnvironment.AddRef()
   at Grpc.Core.Channel..ctor(String target, ChannelCredentials credentials, IEnumerable`1 options)
   at Grpc.Core.Channel..ctor(String target, ChannelCredentials credentials)
```
Inner exception.
```
Could not load file or assembly 'UnityEngine, Culture=neutral, PublicKeyToken=null'. An expected resource in the assembly manifest was missing. (0x80131532)

   at System.RuntimeTypeHandle.GetTypeByName(String name, Boolean throwOnError, Boolean ignoreCase, StackCrawlMarkHandle stackMark, ObjectHandleOnStack assemblyLoadContext, Boolean loadTypeFromPartialName, ObjectHandleOnStack type, ObjectHandleOnStack keepalive)
   at System.RuntimeTypeHandle.GetTypeByName(String name, Boolean throwOnError, Boolean ignoreCase, StackCrawlMark& stackMark, AssemblyLoadContext assemblyLoadContext, Boolean loadTypeFromPartialName)
   at System.RuntimeType.GetType(String typeName, Boolean throwOnError, Boolean ignoreCase, StackCrawlMark& stackMark)
   at System.Type.GetType(String typeName)
   at Grpc.Core.Internal.PlatformApis..cctor()
```

**Comment by jtattermusch** [comment] 2020-11-05 08:55
I think this is basically a dupe of https://github.com/grpc/grpc/issues/18801.

**Closed by jtattermusch** 2020-11-05 08:55 UTC
Labels: kind/bug, priority/P2
