### ISSUE TITLE
Add PHP cancellation interop tests

### ISSUE THREAD

**Issue by murgatroid99** [grpc/grpc#377] opened 2015-02-04 01:49 UTC
This is part of tracking issue #113

**Comment by murgatroid99** [comment] 2015-03-27 21:48
With the current API, it is completely impossible to write the `cancel_after_begin` test. I'll leave this open though, to keep track of that fact.

**Comment by stanley-cheung** [comment] 2015-08-21 20:05
Dupe of #1483 now

**Closed by stanley-cheung** 2015-08-21 20:05 UTC
Labels: interop, php, wrapped languages
