### ISSUE TITLE
socket closed error

### ISSUE THREAD

**Issue by fishpenguin** [grpc/grpc#20360] opened 2019-09-25 03:17 UTC
### What operating system (Linux, Windows,...) and version?
ubuntu16.04

### What did you do?
If possible, provide a recipe for reproducing the error. Try being specific and include code snippets if helpful.
I'm using grpc to transport 1 billion float data, but it report error when I transport 0.28 billion data. the error message:
<_Rendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "Socket closed"
	debug_error_string = "{"created":"@1569077205.534021459","description":"Error received from peer ipv4:","file":"src/core/lib/surface/call.cc","file_line":1052,"grpc_message":"Socket closed","grpc_status":14}"
>

<_Rendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses"
	debug_error_string = "{"created":"@1569077206.950326936","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":3528,"referenced_errors":[{"created":"@1569077206.950292580","description":"failed to connect to all addresses","file":"src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc","file_line":399,"grpc_status":14}]}"
>

### What did you see instead?

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

See [TROUBLESHOOTING.md](https://github.com/grpc/grpc/blob/master/TROUBLESHOOTING.md) for how to diagnose problems better.

**Comment by nicolasnoble** [comment] 2019-09-25 17:23
Please provide us with a reproduction case, and / or proper error logs.

**Comment by fishpenguin** [comment] 2019-09-26 11:15
> Please provide us with a reproduction case, and / or proper error logs.
I applied for 200G space in azure, the bug occurred when I inserted 185G data from native to azure server. the bug is not easy to reproduce. I just want to know what reasons may cause "Socket closed" error.

**Comment by fishpenguin** [comment] 2019-09-27 12:38
Anyone can answer my question?

**Comment by yashykt** [comment] 2019-09-30 18:32
Hi, There are two errors I see - 
One is an error which says that the connection was closed for some reason. If we have more logs, or if you can provide the debug error string, we would be able to know more as to why the connection was closed.

The second error says that gRPC could not connect to any backend.

**Comment by yashykt** [comment] 2019-09-30 18:33
Closing this, since it does not look like a bug.

**Closed by yashykt** 2019-09-30 18:33 UTC
Labels: disposition/requires reporter action
